### ISSUE TITLE
[Arthas/Sefrenia] - Quest Butcherbot

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#10]
https://www.wowhead.com/quest=25112/butcherbot
https://www.wowhead.com/quest=25111/scavengers-scavenged
https://www.wowhead.com/quest=25115/blisterpaw-butchery
The quest-npc, Butcherbot, doesnt always do what hes supposed to and sometimes he just stands still doing nothing when hes supposed to be cutting animals for the quest.

**Comment by LKArthas** [comment]
the Butcherbot Quest Requires Special Stuff to Get Active,  A Valid Dead Animal (Animal Validation Depends on Wich Quest You Have) Near 5 Yards of it, If that Isn't Meet Butcherbot will Despawn Inmediatly

**Comment by ghost** [comment]
Yeah this bugs, spawned npc just often stands next to dead basilisk. If in party only one random player can active that npc. I am multiboxing 5 characters and when i use /use Butcherbot Control Gizmo to all characters same time it works.
