### ISSUE TITLE
[Arthas/Sefrenia] - Quest: Teldrassil: Crown of Azeroth ID 28729

### ISSUE THREAD

**Issue by Talir-Shogun** [GuabinaCore/WoWKoi#100]
What is happening: When you approach the moonwell there is no event and no NPC spawning and talking about the lore. 

What should happen: When you approach the moonwell there should be an event and an NPC spawning and talking about the lore.

You can see how the quest is supposed to work in this video: https://www.youtube.com/watch?v=XawlLWGunLk

**Comment by Talir-Shogun** [comment]
So there are 5 in total of these moonwell "lore quests". I checked the second one and there is also no event, no NPC spawning and talking.

### **Currently Corithras Moonrage does not give you the next quest Teldrassil: The Refusal of the Aspects ID 929 maybe because this event doesn't work.**

I will list the other 4 quests here in case you want to fix them all at once:

1: Teldrassil: Crown of Azeroth (see above)
2: Teldrassil: Passing Awareness ID 28731

When you hand in this quest to Corithras, the Shade of the Kaldorei will spawn and continue the story.

Shade of the Kaldorei smiles at you knowingly as it approaches.
Shade of the Kaldorei says: With Malfurion Stormrage gone, the druids were left in disarray and in desperate need of a new leader.
Shade of the Kaldorei says: Arch Druid Fandral Staghelm roused the druids and convinced the Circle of Ancients in Darkshore that it was time for our people to rebuild.
Shade of the Kaldorei says: In an effort to regain immortality for our people, and with the approval of the Circle, Staghelm and the most powerful druids grew Teldrassil, upon whose boughs you now stand.
Shade of the Kaldorei says: Though we have our new home, our immortal lives have not been restored.
The Shade of the Kaldorei closes its eyes and fades away.

**Comment by Talir-Shogun** [comment]
3: Teldrassil: The Refusal of the Aspects ID 929

The moonwell is now at (60,50).
As you approach it, the Shade of the Kaldorei will spawn to continue his story.

Shade of the Kaldorei stares into the moonwell, lost in distant memories.
Shade of the Kaldorei says: The Arch Druid approached the dragons for their blessings, as the dragons had placed on Nordrassil in ancient times.
Shade of the Kaldorei says: But Nozdormu, Lord of Time, refused to give his blessing, chiding the druid for his arrogance.
Shade of the Kaldorei says: In agreement, Alexstrasza also refused Staghelm, and without her blessing, Teldrassil's growth has been flawed and unpredictable.
Shade of the Kaldorei says: Staghelm retreated to his enclave in Darnassus, ever seeking a new direction by which to bless Teldrassil, and restore the immortality of our people.
The Shade of the Kaldorei closes its eyes and fades away.

**Comment by Talir-Shogun** [comment]
4: Teldrassil: The Burden of the Kaldorei ID 7383

The moonwell is now at (40,29).
As you approach it, the Shade of the Kaldorei will spawn to continue his story.

Shade of the Kaldorei approaches the moonwell slowly, a familiar, thoughtful look upon its face.
Shade of the Kaldorei says: Over time, Staghelm only grew more disconnected from our people.
Shade of the Kaldorei says: Some pose that he blames us, his people, for the loss of his son, long ago during the War of the Shifting Sands.
Shade of the Kaldorei says: Others cite rumors of his escalating conflicts with Tyrande Whisperwind, the shining light of our people, our leader in Darnassus.
Shade of the Kaldorei says: But many druids of the Cenarion Circle stand firm that he wants only what is best for all of the Kaldorei, and serve him unerringly towards that end.
Shade of the Kaldorei says: Fandral Staghelm carries the burden of our sins and our follies, and in so doing deserves the respect of us all.
The Shade of the Kaldorei closes its eyes and fades away.

**Comment by Talir-Shogun** [comment]
5: Teldrassil: The Coming Dawn ID 933

The moonwell is now at (43,58).
As you approach it, the Shade of the Kaldorei will spawn to finish his story.

Shade of the Kaldorei rests on the side of the moonwell in peaceful contemplation.
Shade of the Kaldorei says: In weeks past, all of those living atop Teldrassil have found their memories blurry, as if time itself seized a portion of their lives.
Shade of the Kaldorei says: We break from this haze to find that Fandral Staghelm and many of his closest followers have disappeared without a word.
Shade of the Kaldorei says: But in his place, Shan'do Stormrage awoke from the dream and returned to his beloved Tyrande Whisperwind.
Shade of the Kaldorei says: And with his return came Alexstrasza and Ysera, to at long last offer their blessings upon Teldrassil
Shade of the Kaldorei says: Though a small corruption lingers, desperately longing to be cleansed, the boughs of Teldrassil itself seem changed. Growth has begun anew.
Shade of the Kaldorei says: None know what to expect next, but with Malfurion and Tyrande reunited, a new hope dawns on the Kaldorei.
Shade of the Kaldorei says: Hope for lasting relief from the shadow that has been cast on our people for so long.
The Shade of the Kaldorei closes its eyes and fades away.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
