### ISSUE TITLE
[NPC] - Misc NPCs in Coldridge Valley

### ISSUE THREAD

**Issue by Talir-Shogun** [GuabinaCore/WoWKoi#1001]
Joren Ironstock (ID 37081) - He should be constantly attacked by troggs and one shot them
https://www.youtube.com/watch?v=VFESy6MThak

Ragged Timber Wolf (ID 704) - Broken loot table
https://www.wowhead.com/npc=704/ragged-timber-wolf#drops:0-19+16+1

Bromos Grummner (ID 926) - Is not supposed to cast constantly
https://www.wowhead.com/npc=926/bromos-grummner#screenshots

Thran Khorman (ID 912) -  Is not supposed to read a book (he is a warrior trainer after all not a   librarian!)
https://www.wowhead.com/npc=912/thran-khorman#screenshots

Saripal Smolderbrew (ID 43455) - Is not supposed to cast constantly
https://www.wowhead.com/npc=43455/saripal-smolderbrew#screenshots

Branstock Khalder (ID 837) - Is not supposed to cast constantly
https://www.wowhead.com/npc=837/branstock-khalder#screenshots

Teegli Merrowith (ID 37121) - Is not supposed to cast constantly
https://www.wowhead.com/npc=37121/teegli-merrowith#screenshots

Teo Hammerstorm (ID 37115) - Is not supposed to cast constantly
https://www.wowhead.com/npc=37115/teo-hammerstorm#screenshots

**Comment by NightwindOI** [comment]
Its like that with all trainers around the world everywhere.
