### ISSUE TITLE
[Core] - Mage Frozen Orb

### ISSUE THREAD

**Issue by bonfim97** [GuabinaCore/WoWKoi#1005]
**Links:**

https://www.wowhead.com/spell=84714/frozen-orb

**What is happening:**
It's not doing any damage.

**What should happen:**

Launches an orb of swirling ice up to 40 yards forward which deals up to [20 * (16.27% of Spell power)] Frost damage to all enemies it passes through. Grants 1 charge of Fingers of Frost when it first damages an enemy.Enemies damaged by the Frozen Orb are slowed by 30% for 3 sec. | Launches an orb of swirling ice up to 40 yards forward which deals up to [20 * (16.27% of Spell power)] Frost damage to all enemies it passes through. Grants 1 charge of Fingers of Frost when it first damages an enemy.Enemies damaged by the Frozen Orb are slowed by 30% for 3 sec.
-- | --
Launches an orb of swirling ice up to 40 yards forward which deals up to [20 * (16.27% of Spell power)] Frost damage to all enemies it passes through. Grants 1 charge of Fingers of Frost when it first damages an enemy.Enemies damaged by the Frozen Orb are slowed by 30% for 3 sec.

**Comment by Macumbino** [comment]
Frozen Orb deals damage, however, it only seems to deal damage when you're near the mob it's hitting. If you're far away, it won't deal any damage to the mob.
