### ISSUE TITLE
[QUEST] Incendicite Ore

### ISSUE THREAD

**Issue by drbubbs** [GuabinaCore/WoWKoi#1006]
**Links:**
https://www.wowhead.com/quest=25735/incendicite-ore
https://www.wowhead.com/item=55240/spark-proof-pick

**What is happening:**
Unable to mine the incendicite veins using the spark proof pick provided for the quest. Veins require mining

**What should happen:**
You should be able to loot the ore from the veins without mining during the quest

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
