### ISSUE TITLE
[Arthas] - Quest Burnside Must Fall

### ISSUE THREAD

**Issue by Majeran0** [GuabinaCore/WoWKoi#1008]
**Links:**

https://www.wowhead.com/quest=28235/burnside-must-fall#comments

**What is happening:**
Fight with Magistrate Burnside is not triggering.

**What should happen:**
After you approach him, he should drop the invulnerable state and start the fight.

**Comment by GhostySimon** [comment]
Worked for me when approached with NPCs that should follow during this quest,

**Comment by LKArthas** [comment]
Fixed avaible on next update
