### ISSUE TITLE
Quest - In a dark corner

### ISSUE THREAD

**Issue by MeatyBoii** [GuabinaCore/WoWKoi#1010]
**Links:** https://www.wowhead.com/quest=26669/in-a-dark-corner

**What is happening:** Upon finishing previous quest, you're supposed to head out to other location to find out other parts of missing books. However, you are able to pick them up from the pile used in previous quest, thus rendering the search unneeded.

**What should happen:** You shouldn't be able to do that and be required to run to Rotting Orchard.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
