### ISSUE TITLE
Quest - The Warchief Cometh

### ISSUE THREAD

**Issue by Duskmourn** [GuabinaCore/WoWKoi#1012]
https://www.wowhead.com/quest=26965/the-warchief-cometh

When the Val'kyr raise the corpses, the resulting Undead NPCs float in the air, they then turn back into corpses when the quest has completed but continue to float until the quest is started again, when they fall back to the ground only to be resurrected and float again.

The corpses should raise to be resurrected, then fall to the ground when they transform into Undead NPCs, and stay there even when they turn back into corpses.

**Comment by LKArthas** [comment]
Fixed avaible on next update
