### ISSUE TITLE
[Arthas] - Onward, to Light's Hope Chapel quest bug

### ISSUE THREAD

**Issue by GhostySimon** [GuabinaCore/WoWKoi#1014]
**Links:**

from WoWHead or our Armory

**What is happening:**

After the ride with the caravan Fiona appears very briefly and then disappears preventing the player from completing the quest:
![image](https://user-images.githubusercontent.com/63936782/80294280-f31cf880-8735-11ea-8cce-a0f27446c8ae.png)

**What should happen:**

Fiona should appear near the crown guard tower so that player could complete the quest and continue the chain.

**Comment by GhostySimon** [comment]
On top of that...

![image](https://user-images.githubusercontent.com/63936782/80294310-4a22cd80-8736-11ea-849a-b4ee13b017da.png)

**Comment by NightwindOI** [comment]
That doesn't happen to me, but there are other problems.
Player and the dwarf face direction is wrong. It supposes to be that [way](https://wow.zamimg.com/uploads/screenshots/normal/251314-onward-to-lights-hope-chapel-riding-on-the-back.jpg)
and the caravan going away is a bit.... [strange ](https://imgur.com/a/4ZbfINR)

**Comment by LKArthas** [comment]
The Main issue there was fixed closing, the orientations of the 3 caravans will be fixed soon ;)
