### ISSUE TITLE
Minas de la Muerte - Npc mata de un golpe

### ISSUE THREAD

**Issue by carlosyuniro** [GuabinaCore/WoWKoi#1015]
https://es.classic.wowhead.com/the-deadmines
https://es.wowhead.com/npc=48338/camarera-de-mina

Camarera de mina mata de un golpe, solo esta bug la segundo camarera, la primera no.

![WoWScrnShot_042520_223843](https://user-images.githubusercontent.com/62365902/80295627-bf989900-874a-11ea-9a69-74ef4bdbd6bd.jpg)

**Comment by Cefiro-Caecias** [comment]
Aplicado ajuste. Disponible en el próximo update.
