### ISSUE TITLE
Profundidades de roca negra 

### ISSUE THREAD

**Issue by carlosyuniro** [GuabinaCore/WoWKoi#1016]
https://es.classic.wowhead.com/blackrock-depths
https://es.wowhead.com/npc=83540/c%C3%ADrculo-de-la-ley

La arena de Círculo de la Ley ya se encuentra abierta y no toca matar a los npc que la abren y al entrar en ella se activa el evento, pero en la primera ronda dejan de salir npc para matar y queda todo cerrado y no se puede continuar ni matar al boss.

**Comment by Cefiro-Caecias** [comment]
El Círculo d ela Ley es lo último que falta reparar en ese Dungeon. Paciencia ;)
