### ISSUE TITLE
[Core] - Weird bug upon quitting the quest window

### ISSUE THREAD

**Issue by MeatyBoii** [GuabinaCore/WoWKoi#1021]
**Links:** n/a

**What is happening:** When you finish a quest, the window should automatically close if there is no available quests remaining. That doesn't happen. With questgivers that only give quests, a standard dialog window opens with them, as if you right clicked on them to get some information. The NPCs that also serve as vendors or trainers, a random shop/skilling window opens. [An example, cooking vendor/trainer opens window for training riding and flying](https://user-images.githubusercontent.com/63917383/80306242-4c326e00-87c2-11ea-9172-f299bf261805.png)

**What should happen:** It shouldn't.

**Comment by Thordekk** [comment]
That is a feature implemented in Legion for some quest, i hate it too :)
