### ISSUE TITLE
[Quest - Phasing] Felwood "WANTED; The Demon Hunter"

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1026]
**Links:**

https://www.wowhead.com/quest=28217/wanted-the-demon-hunter

**What is happening:**

Feronas Sindweller (https://www.wowhead.com/npc=47923/feronas-sindweller) is stuck in a different phase. It is immposible to talk to him and start the script sequnece.

**What should happen:**
Feronas Sindweller should be on a different phase.

**Comment by LKArthas** [comment]
Fixed avaible on next update
