### ISSUE TITLE
Rare Loot issue.

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1032]
**Links:**

https://github.com/GuabinaCore/WoWKoi/issues/921

**What is happening:**
Great job with the spawn and everything, but by the look at things I'm super unlucky or 90% of the mob's that was added MoP+ don't have any loot.
Talk about the new added. 8/10 was without any loot so far.

**What should happen:**

**Comment by LKArthas** [comment]
They have Loot added but chances are low and still pendant to implement the guaranteed Loot system to rares

**Comment by NightwindOI** [comment]
If need an help on that---->know where to find me :)

**Comment by Cefiro-Caecias** [comment]
Drop realigned in all the Rares you reported in the Kalimdor Issue. Available in the next update.

I remind you that I hate you XD
