### ISSUE TITLE
[Core] - Monk - Windwalker - Fists of Fury

### ISSUE THREAD

**Issue by antonioyu0505** [GuabinaCore/WoWKoi#1033]
**Links:**
https://www.wowhead.com/spell=113656/fists-of-fury

**What is happening:**
When your target dies before the channeling is over, it breaks the spell, even if there are other enemies around. Moreover, it can only be cast when you're targeting somebody.

**What should happen:**
This spell should only be finished at the end of the duration or when manually removing the buff.
You should be able to cast this spell even without targets provided that there is enough chi.

**Comment by Exlyss** [comment]
I'd also like to add the fact that Fists of Fury should hit all the enemies in the cone of attack in front of you, but instead is hitting only the enemies physically in front of you, and not the ones a little on the side but still in the cone of the attack.

**Comment by Sav412** [comment]
I'd just like to say that this issue is still happening as of 6/30.
