### ISSUE TITLE
[Core] - Monk - Brewmaster - Tiger Palm

### ISSUE THREAD

**Issue by antonioyu0505** [GuabinaCore/WoWKoi#1034]
**Links:**
https://www.wowhead.com/spell=100780/tiger-palm

**What is happening:**
It doesn't reduce the cooldown on brews by 1 second.
It costs 25 energy.

**What should happen:**
It should reduce the cooldown on brews by 1 second on use.
It should cost 50 energy.

**Comment by Serithul** [comment]
https://www.wowhead.com/spell=100780/tiger-palm#changelog

If you hover over the 7.3.5 change you will see it costs 50 energy. So all good on that end.

**Comment by antonioyu0505** [comment]
Then it is bugged, because it costs 25 energy.

**Comment by Serithul** [comment]
Have you checked your talents and passives in case there is one that lowers it ?

**Comment by antonioyu0505** [comment]
I haven't seen any passive or talent that could lower the cost of it. This reduced cost has been like that since level 10.
