### ISSUE TITLE
Invisible Felblade Assassins at Durotar

### ISSUE THREAD

**Issue by AnastasioTheSexyTauren** [GuabinaCore/WoWKoi#1036]
**Links:**
https://www.wowhead.com/npc=100993/felblade-assassin#objective-of

from WoWHead or our Armory

**What is happening:** If you do aoe damage at some specific zones in orgrimar/durotar, you get killed by some invisible mobs, "felblade assasin" says on the combat log, here are some screenshots:
![WoWScrnShot_042620_233430](https://user-images.githubusercontent.com/63824920/80333658-ce4f8080-881c-11ea-84d8-dc5756730dce.jpg)
![WoWScrnShot_042620_232637](https://user-images.githubusercontent.com/63824920/80333722-05be2d00-881d-11ea-8516-072a9012c505.jpg)

**What should happen:** There should be no Felblade assassin at orgrimar/durotar

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
