### ISSUE TITLE
[Dungeon] Zul'Farrak - Raven and Oro Eyegouge are evade bugged

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#104]
**Links:**
https://classic.wowhead.com/npc=7606/oro-eyegouge
https://classic.wowhead.com/npc=7605/raven
https://classic.wowhead.com/zulfarrak

**What is happening:**
Oro Eyegouge and Raven are unhittable after activating the fight with Sergeant Bly. While the other enemies attack and can be attacked, Oro Eyegouge and Raven don't move, and cannot be hit. Every attack used on them is evaded, and they do not aggro onto the players.

**Comment by Cefiro-Caecias** [comment]
The Zul'Farrak Dungeon is not yet finished, like other Dungeons that we still have pending. We will notify you when they are 100% ready ;)
