### ISSUE TITLE
Quest - Coastal Delicacies!

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#1041]
**Links:**
https://www.wowhead.com/quest=28146/coastal-delicacies
https://www.wowhead.com/npc=47662/hungry-mine-creeper
https://www.wowhead.com/npc=2374/torn-fin-muckdweller

**What is happening:**
1. Hungry mine creeper aggroes NPC's.
2. Torn Fin Muckdweller can't kill player if they're out of range.

**What should happen:**
1. Hungry mine creeper follows up on player's aggro.
2. Torn Fin Muckdweller chases players if they're out of range.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
