### ISSUE TITLE
Quest: Inoculation!

### ISSUE THREAD

**Issue by MissTohka** [GuabinaCore/WoWKoi#1049]
**Links:**
https://www.wowhead.com/quest=9303/inoculation
from WoWHead or our Armory

**What is happening:**
When you accept the quest you can instantly turn it in and receive the rewards, without completing the quest objective, as if you had completed the quest objective.

**What should happen:**
You would have to inoculate six Owlkins before being able to turn in the quest, for the quest rewards.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
