### ISSUE TITLE
[Core] - Fly path after a crash

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1050]
**Links:**

**What is happening:**
I take a fly from  Swamp of Sorrows to Booty Bay.Server crash midway and that happens. Once I fly back to the city fly reset and everything turns to normal.
https://streamable.com/e3lfcn

**What should happen:**
If serer crash/u log out/ DC or anything u suppose to continue the flight.

**Comment by Thordekk** [comment]
Issue need test we implement corrections
