### ISSUE TITLE
[Core] - Herbalism issues.

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#1052]
**Links:**
https://wow.gamepedia.com/Herbalism
from WoWHead or our Armory

**What is happening:**

1. NPCs that can be gathered after they are killed show up as nodes on the minimap while they should not.

2. Herbs have profession level requirements to be gathered.

**What should happen:**
1. They should not show up as nodes.

2. Herbs can be gathered at any level BUT the loot i depends on your herbalism level.

**Comment by NightwindOI** [comment]
https://github.com/GuabinaCore/WoWKoi/issues/969
https://i.imgflip.com/2kvdsg.jpg

**Comment by Serithul** [comment]
Sorry bro, i thought it was only about the glow :(
