### ISSUE TITLE
Quest: Neither Human Nor Beast, Id: 24593

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#1058]
**Links:**
https://www.wowhead.com/quest=24593/neither-human-nor-beast
https://www.wowhead.com/npc=37873/vassandra-stormclaw
https://www.wowhead.com/object=201951/well-of-tranquility
https://www.wowhead.com/npc=37870/lyros-swiftwind
https://www.wowhead.com/object=201950/well-of-fury
from WoWHead or our Armory

**What is happening:**
Vassandra and Lyros say your name in caps when you drink from the well of Tranquility and well of Fury respectively.

![WoWScrnShot_042820_223604](https://user-images.githubusercontent.com/62258982/80530078-2adba880-89a1-11ea-8ca6-75f91f9aab4d.jpg)

![WoWScrnShot_042820_223429](https://user-images.githubusercontent.com/62258982/80530098-3333e380-89a1-11ea-89ba-05dc92d53722.jpg)

**What should happen:**
The name should be written normally.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
