### ISSUE TITLE
Baron Ashbury Enrage.

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#1059]
**Links:**
https://www.wowhead.com/npc=37735/baron-ashbury
https://www.wowhead.com/spell=8599/enrage
from WoWHead or our Armory

**What is happening:**
When he enraged, the text that comes in the chat was in spanish.

![WoWScrnShot_042820_224955](https://user-images.githubusercontent.com/62258982/80531077-b43faa80-89a2-11ea-8648-4a81514f5647.jpg)

**What should happen:**
It should be in english when on english client. "[Mob Name] becomes enraged!"

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
