### ISSUE TITLE
[Core] Random mobs evading and following forever

### ISSUE THREAD

**Issue by KermitTheHunter** [GuabinaCore/WoWKoi#106]
Some mobs when kited out of their radius become evade bugged and cant be hit, but still follow me and attempt to attack me forever until I relog or die
Specifically these two mobs did it for me
https://www.wowhead.com/npc=1674/rot-hide-gnoll
https://www.wowhead.com/npc=1934/tirisfal-farmer

**Comment by Cefiro-Caecias** [comment]
New fix implemented. Available after the next update.
