### ISSUE TITLE
NPC: Enslaved Villager, Id:37694

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#1061]
**Links:**
https://www.wowhead.com/npc=37694/enslaved-villager
from WoWHead or our Armory

**What is happening:**
Spanish emote after freeing him on english client.
![WoWScrnShot_042820_231224](https://user-images.githubusercontent.com/62258982/80533196-eacaf480-89a5-11ea-81a4-63a0953249de.jpg)

**What should happen:**
English emote on english client.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
