### ISSUE TITLE
NPC: Freed Emberstone Villager

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#1062]
**Links:**
https://www.wowhead.com/npc=38425/freed-emberstone-villager
from WoWHead or our Armory

**What is happening:**
Some are with Spanish names, some with English on an English client.

![WoWScrnShot_042820_233211](https://user-images.githubusercontent.com/62258982/80535053-d9cfb280-89a8-11ea-85db-0b91768913b6.jpg)

**What should happen:**
English names on English client

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
