### ISSUE TITLE
[Arthas] - Quest - It's Only Poisonous if You Ingest It (minor bug)

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1063]
**Links:**
https://www.wowhead.com/quest=27088/its-only-poisonous-if-you-ingest-it
https://www.wowhead.com/item=60808/mutant-bush-chicken-cage
from WoWHead or our Armory

**What is happening:**
The quest item Mutant Bush Chicken Cage can be used everywhere.

**What should happen:**
As stated in the text of the item, it should only be available to use when targeting the mob Forest Ettin.

**Comment by LKArthas** [comment]
Fixed
