### ISSUE TITLE
[Core] - Spell - Spinning Crane Kick

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1065]
**Links:**
https://www.wowhead.com/spell=101546/spinning-crane-kick
from WoWHead or our Armory

**What is happening:**
The spell doesn't have the 40% bonus damage per unique enemy hit.

**What should happen:**
Each unique enemy hit in the span of 15 secs with Tiger Palm, Blackout Kick or Rising Sun Kick should give Spinning Crane Kick a bonus of 40% damage per unique enemy hit.

Ps: I don't really know why the spell ingame says 40% bonus but on WoWHead it states that is 10%, in my experience in other servers I've always seen 40%, but it's up to you.

**Comment by DeltaVortex** [comment]
The one you linked is the BFA version of the spell. Here's the legion version: https://web.archive.org/web/20170608103632/https://www.wowhead.com/spell=101546/spinning-crane-kick 
So you are correct about the 40% bonus damage for only the Windwalker spec.
EDIT: Here's an additional link to help devs https://wow.gamepedia.com/Spinning_Crane_Kick
