### ISSUE TITLE
[Arthas] - Quest - Rise, Forsaken

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1066]
**Links:**
https://www.wowhead.com/quest=27097/rise-forsaken
from WoWHead or our Armory

**What is happening:**
When a mob is killed, when Agatha turns them into a Forsaken, the spell she uses is cast onto me too, causing the spawn of 2 Forsakens one into another, and thus halving the needed mobs killed to complete the quest.

**What should happen:**
When Agatha casts her spell, it should only be casted on the dead mob to turn him and not onto the player too.

![WoWScrnShot_042820_233026](https://user-images.githubusercontent.com/64436148/80539701-44342300-89a8-11ea-87f6-898d64f33164.jpg)
Showing the 2 Forsakens spawned together.
![WoWScrnShot_042820_233142](https://user-images.githubusercontent.com/64436148/80539893-9412ea00-89a8-11ea-9e0e-065df57da7e6.jpg)
In the chat log Agatha says: "Rise, (name)! Become Forsaken!" as proof that she casts the spell on the player too.

**Comment by Fhroozt** [comment]
I'll just +1 this, I just experienced exactly this
