### ISSUE TITLE
Molten Core Damage issues

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#1068]
**Links:**
https://wow.gamepedia.com/Molten_Giant
https://classic.wowhead.com/npc=11658/molten-giant#abilities

**What is happening:**
Normal Hits are around 3-4k a pop, about 300-400% above normal
Knock Away is around the same 300-400% above normal
Smash hits for 20-23k a pop about 2000% above normal.  
Have not been able to test other mobs yet as damage of first two mobs is far too much to pass.  

**What should happen:**
Normally hits a tank for 600 - 800 damage.
 Knock Away — Inflicts normal damage plus 54 to an enemy and knocks it back.
Smash — Smashes the ground, inflicting 1458 to 1782 damage to nearby enemies.

Now wowhead classic shows the damage of smash to be around 610-990 per hit. doesn't show or explain any normal damage.  Thanks so much!

**Comment by Velthur-bot-3000** [comment]
Found a YouTube video for reference in regards to the other mobs damage. Video is a 7.3.5 era lvl 60 warrior. Completely decked in epic 60 gear.  So it will be the best reference for more accurate damage from some of the mobs. Thanks!

https://youtu.be/VAytg_yD3Gs

**Comment by Velthur-bot-3000** [comment]
THANKS FOR THE REVENGE ON THOSE DAMNED MOLTEN GIANTS SEFRENIA-CAECIAS!!!!  <3

**Comment by Cefiro-Caecias** [comment]
Applied a temporary fix so they can raid. Work will continue in MC until a definitive solution is found. Revenge Forever, bukowywowwe! :D
