### ISSUE TITLE
Quest - Lordaeron (Visual Bug)

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1069]
In the cutscene after starting the questo Lordaeron, the player is mounting a horse that is itself mounting another horse.

![WoWScrnShot_042820_235924](https://user-images.githubusercontent.com/64436148/80541984-7e072880-89ac-11ea-9c13-e3d8da90df42.jpg)

EDIT: restarted the quest and the cutscene went on as it should normally do.

**Comment by Cefiro-Caecias** [comment]
It is not a Server bug. This "bug" occurs when your PC has low processing speed and fails to synchronously load ;)
