### ISSUE TITLE
Durotar - Rezlak quests

### ISSUE THREAD

**Issue by Tanis215** [GuabinaCore/WoWKoi#107]
In Durotar, two quests - Securing the lines and Winds in the desert are given by Orgnil Soulscar in Razor hill instead of Rezlak.
https://www.wowhead.com/npc=3293/rezlak
https://www.wowhead.com/npc=3142/orgnil-soulscar

**Comment by Cefiro-Caecias** [comment]
There is no bug present. Both NPCs give those quests, depending on not cutting the chain. We have deliberately programmed it that way.
