### ISSUE TITLE
Quest - Excising the Taint

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1070]
**Links:**
https://www.wowhead.com/npc=45195/bloodfang-stalker#abilities
from WoWHead or our Armory

**What is happening:**
The mobs are not stealthed even if the spell is active on them

**What should happen:**
When they have the spell Stalking active they should be stealthed.

![WoWScrnShot_042920_003345](https://user-images.githubusercontent.com/64436148/80544439-5b2b4300-89b1-11ea-9a0e-ce4a6751cef1.jpg)

**Comment by Cefiro-Caecias** [comment]
It is deliberate.
