### ISSUE TITLE
Quest - Seek And Destroy

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1071]
**Links:**
https://www.wowhead.com/quest=27193/seek-and-destroy
from WoWHead or our Armory

**What is happening:**
The mob required for completing the quest gets bugged in the roof of the house, making the quest impossible for a character without ranged spells.

**What should happen:**
It should come down to fight as soon as the player gets aggro of it.

![WoWScrnShot_042920_004034](https://user-images.githubusercontent.com/64436148/80544932-6f237480-89b2-11ea-9212-a6ae35116c67.jpg)

![WoWScrnShot_042920_004132](https://user-images.githubusercontent.com/64436148/80544940-721e6500-89b2-11ea-84eb-977afd62b11d.jpg)

**Comment by Cefiro-Caecias** [comment]
I just tried it several times, and it gave me no error. I assume it was a temporary bug.
