### ISSUE TITLE
NPC - Pile of Corpses (Scarlet Monastery)

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1072]
**Links:**
/www.wowhead.com/npc=59722/pile-of-corpses
from WoWHead or our Armory

**What is happening:**
The mob is untargetable.

**What should happen:**
It should be possible to target and kill it to stop it spawning zombies.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
