### ISSUE TITLE
Blackwing Lair Entrance -- Stays shut

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#1074]
**Links:**
n/a

**What is happening:**
The entrance gate to BWL stays completely shut and non interactive at all.  You may enter the raid initially, but if you die, you will be stuck between the portal and the entrance gate, with no way in the gate.

**What should happen:**

After going in, if you die, the gate shouldn't be able stuck shut, it should be open for others to enter/raid to enter if wipe occurs. 

Thanks!

**Comment by Cefiro-Caecias** [comment]
This Raid is under repair. Patience.
