### ISSUE TITLE
NPC - Mudsnout Shaman

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#1079]
**Links:**
https://www.wowhead.com/npc=2373/mudsnout-shaman

**What is happening:**
Mudsnout Shamans deal too much damage with their lightning bolts + they don't come to melee you if you interrupt their casting.

**What should happen:**
Mudsnout Shamans deal normal damage + they come to melee you if you interrupt spell casting

**Comment by Cefiro-Caecias** [comment]
Fixed.
