### ISSUE TITLE
[Arthas/Sefrenia] - Quest: Catalysm - 27435

### ISSUE THREAD

**Issue by Golvir** [GuabinaCore/WoWKoi#108]
**Links: https://www.wowhead.com/quest=27453/catalysm**

**What is happening: You can finish the quest by getting samples from one single mob.**

**What should happen: You should get samples from more than one mob.**

**Comment by Cefiro-Caecias** [comment]
Arthas, con spellhit no logré hacer que los cadáveres de los elementales Blighted Surge (8519) y Plague Ravager (8520) despawneen. A ver si vos podés hacer algo con la spell :S

**Comment by LKArthas** [comment]
Fixed for next update

**Comment by NightwindOI** [comment]
You still can do that (that's why we need server rev command..dn if the server is updated or not :D )
