### ISSUE TITLE
NPC - Daggerspine Siren

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#1080]
Links:
https://www.wowhead.com/npc=2371/daggerspine-siren

What is happening:
Daggerspine Sirens deal too much damage with their lightning bolts + they don't come to melee you if you interrupt their casting + walking while casting

What should happen:
Daggerspine Siren deal normal damage + they come to melee you if you interrupt spell casting + walking while casting.

**Comment by Cefiro-Caecias** [comment]
Fixed.
