### ISSUE TITLE
[Core] - Honorable Medallion with Stuns

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#1082]
**Links:**
https://www.wowhead.com/spell=195710/honorable-medallion
https://www.wowhead.com/crowd-control-diminishing-returns-wow-pvp    (only because it has each cc type with all the appropriate spells in each)
from WoWHead or our Armory

**What is happening:**
Honorable medallion does not break stun.

**What should happen:**
It should break stun.

**Comment by Thordekk** [comment]
Fixed
