### ISSUE TITLE
[Arthas] - Wailing Caverns completion

### ISSUE THREAD

**Issue by JayEverett** [GuabinaCore/WoWKoi#1083]
**Links:**

from WoWHead or our Armory

**What is happening:**
There is an issue with completion of the instance objectives. Once you complete the escort to the last boss involving https://classic.wowhead.com/npc=3678/disciple-of-naralex.

**What should happen:**
Upon escorting the npc https://classic.wowhead.com/npc=3678/disciple-of-naralex you should recieve the completion requirement for the instance.

**Comment by LKArthas** [comment]
Fixed
