### ISSUE TITLE
Rogue - Cheap Shot /Between the Eyes

### ISSUE THREAD

**Issue by bonfim97** [GuabinaCore/WoWKoi#1084]
**Links:**

https://www.wowhead.com/spell=199804/between-the-eyes
https://www.wowhead.com/spell=1833/cheap-shot

**What is happening:**
It appears DR is only afecting the same spells and not different stuns. So if you CS twice it gives DR and BTE twice it has DR, but not between one another.

EDIT: After further testing, BTE is also not being affected by DR. SO you can do full 12 secs stuns one after the other.

**What should happen:**
They should share Dr as they are both stuns.

**Comment by Serithul** [comment]
https://www.wowhead.com/crowd-control-diminishing-returns-wow-pvp

**Comment by biosintesis** [comment]
Fix
