### ISSUE TITLE
[Dungeon] Wailing Caverns - trash loot not scaling | Muyoh slow movement speed

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1085]
First case:

Trash loot in Wailing Caverns (supposedly in other dungeons as well) doesn't scale properly to player's level. Level 60 character still drop level 15~ items.
--------------------------------------------------------------
Second Case:

**Links:**
https://www.wowhead.com/npc=3678/muyoh
**What is happening:**
Muyoh movement speed is very slow, walking pace.
**What should happen:**
As of 4.0.3 his movement speed has been significantly increased. (Slightly faster than player's base movement speed)

**Comment by Cefiro-Caecias** [comment]
Fixed.
