### ISSUE TITLE
[Core] - Problema con Cast Flags 64

### ISSUE THREAD

**Issue by Cefiro-Caecias** [GuabinaCore/WoWKoi#1087]
Buenas, niños. Les voy a exponer un problema con el Cast Flags 64 de Smart Scripts, un problema que afecta a demasiados mobs del juego como para pasarlo por alto, debido a la cantidad de SAIs que tenemos utilizando este parámetro.

Recordemos: en Smart Scripts, cuando un mob utiliza el action 11 ("action_type", castear spell), en "action_param2" puedes ponerle el valor 64 (cast flags), para que el mob se quede en su sitio sin moverse, y castee la spell. es algo que suelen utilizar mucho los mobs casters que atacan a distancia con bolas de fuego o hechizo similares, o mobs que arrojan lanzas y hachas.

Ahora bien, los problemas del cast flags 64 son los siguientes:

1.- Si silencias a distancias a un mob que tiene orden de castear spells con cast flags 64, el NPC se queda en su sitio sin hacer nada, o sea, no activa el modo de ataque a melé, ni se pone a perseguirte mientras dura el silencio. Un ejemplo de esto puede ver se en el NPC: https://www.wowhead.com/npc=1562

2.- Si además el mob tiene orden de, digamos, arrojarte un hacha mientras estés a un rango de 5 a 30 yardas, y tú avanzas para atacarlo a melé, el NPC ya no castea la spell de arrojarte el hacha con cast flags 64 (lo cual está bien)... pero tampoco hace nada más. No te ataca cuerpo a cuerpo, ni hace nada, sólo se queda ahí mirando cómo lo matas. Un ejemplo de este caso puede verse en el NPC: https://www.wowhead.com/npc=44445

**Comment by NightwindOI** [comment]
The spell used to test is [this](https://www.wowhead.com/spell=2139/counterspell).
So if u cast it on the Bloodsail, he just cast a nova (no matter if u are out of range) and do nothing.

**Comment by Cefiro-Caecias** [comment]
Fixed :D
