### ISSUE TITLE
[Arthas] - Character is stuck after Rocket Rescue quest in Tanaris

### ISSUE THREAD

**Issue by laurex2010** [GuabinaCore/WoWKoi#109]
**Links:**
![image](https://user-images.githubusercontent.com/61942131/76664306-a5bc4180-6562-11ea-9fd7-e90794757224.png)
https://www.wowhead.com/quest=24910/rocket-rescue

from WoWHead or our Armory

**What is happening:**
Chaaracter is stuck after killing the pirates and saving the goblins. I can't use hearthstone or moonglade teleport, because it's saying that my character
 is already moving.

**What should happen:**
After killing the pirates and saving the goblins, the character should be sent back to Gadgetzan

**Comment by LKArthas** [comment]
you should use the rocket exit in order to get back

**Comment by laurex2010** [comment]
> 
> 
> you should use the rocket exit in order to get back

What is this exit? There's no red arrow :(
I'm floating in the air with only sea nearby

**Comment by LKArthas** [comment]
The 8 Th ability is the rocket éxito tryied this 5 times for each faction and works 100 % of the times also checked 3 videos and people we're using the ability to get back closing

**Comment by taktrix** [comment]
I'm having this exact same problem, tried pushing 8 but nothing is happening and I'm still stuck! I had to have a friend summon me out because there was no way out of it, the unstuck didn't work, and it wouldnt let me hearth or port because it kept saying that "you have to stand still to do that".
