### ISSUE TITLE
NPC - Baron Ashbury, Lord Walden, Lord Godfrey

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1090]
**What is happening:**
Ashbury, Walden and probably Godfrey got duplicated after a combat.

**What should happen:**
There should only be 1 NPC for each of them.

![WoWScrnShot_042920_150642](https://user-images.githubusercontent.com/64436148/80599583-73d83f00-8a2b-11ea-8959-e1bcdf6057c1.jpg)

**Comment by DeltaVortex** [comment]
duplicate #1037

**Comment by Exlyss** [comment]
Didn't see that, sorry for the mistake and thanks @DeltaVortex.
Closing the issue.
