### ISSUE TITLE
Quest - Helcular's Command

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1091]
**Links:**
https://www.wowhead.com/quest=28332/helculars-command
https://www.wowhead.com/npc=48260/bloodfang-forsaken-hunter
https://www.wowhead.com/npc=48260/bloodfang-forsaken-hunter#abilities

from WoWHead or our Armory

**What is happening:**
The NPC Bloodfang Forsaken Hunter have Stalking (a stealth spell) active on them but they can be seen.
**What should happen:**
They should be invisible until you are close enough to them.

![WoWScrnShot_042920_172432](https://user-images.githubusercontent.com/64436148/80614425-bb1bfb00-8a3e-11ea-82b1-f2f653ad19b4.jpg)

**Comment by Serithul** [comment]
If you watch the videos linked on the wowhead page, you can see that they are supposed to be seen. (Example GitGudGuides video at 0:36)

**Comment by Exlyss** [comment]
That's...strange, I mean they have a stealth spell but they're supposed to be seen. Still, sorry for the mistake and thanks @Serithul for making me notice it.
