### ISSUE TITLE
Dungeon - The Deadmines

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1093]
**Links:**
https://classic.wowhead.com/the-deadmines

from WoWHead or our Armory

**What is happening:**
After beating the boss Foe Reaper 5000, the iron door to go to the last section of the dungeon remains closed, while at the same time said door is open too, thus having 2 doors clipped together, one closed and one open.

**What should happen:**
There should be only one door that opens when the boss is dead.

![WoWScrnShot_043020_004954](https://user-images.githubusercontent.com/64436148/80654453-9181c480-8a7c-11ea-9e67-9dbf8fe11950.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
