### ISSUE TITLE
[Core] - Items unequipping when changing specialization (Monk)

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1094]
**What is happening:**
When i switch specialization from Windwalker to Mistweaver, i get automatically Back, one of the Rings and the Off-Hand Weapon unequipped; when switching from Mistweaver to Windwalker it happens to one of the Rings and the Main Weapon (only if it is a 2H Weapon such a Staff); switching from Windwalker to Brewmaster it unequips one of the Rings and both Main and Off-Hand weapon (only if you have 1H Weapons); switching from Brewmaster to Windwalker unequips one of the Rings and the 2H Weapon; from Brewmaster to Mistweaver unequips Back and one of the Rings; from Mistweaver to Brewmaster unequips one of the Rings and the Main Weapon only if it is a 1H Weapon.

**What should happen:**
Anything of this should happen.

PS: at the moment I did the tests I didn't have an Helm or the Trinkets: i'll make sure to do these tests again when i manage to fill these missing spots in the equipment

**Comment by Serithul** [comment]
This is a general bug that affects all classes reported here https://github.com/GuabinaCore/WoWKoi/issues/870

**Comment by Exlyss** [comment]
I just thought that giving an as detailed as possible description for my class could help devs find and fix the problem in an easier way.

**Comment by Serithul** [comment]
I didn't comment in order for you to close the ticket, don't get me wrong. I'm just "linking" the 2 reports.
