### ISSUE TITLE
Brujo Destrucción 

### ISSUE THREAD

**Issue by carlosyuniro** [GuabinaCore/WoWKoi#1098]
https://es.wowhead.com/spell=1122/invocar-infernal
Al invocar el infernal se desaparece enseguida 

https://es.wowhead.com/spell=157757/invocar-guardia-apocal%C3%ADptico
Solo te sigue pero no ataca y es muy pequeño.
![WoWScrnShot_043020_000327](https://user-images.githubusercontent.com/62365902/80667646-1ddcb900-8a76-11ea-9b72-11f3bca0164a.jpg)

**Comment by Cefiro-Caecias** [comment]
Infernal reparado. Doomguard quedará pendiente para en Dev de Core. Disponible en el próximo update.
