### ISSUE TITLE
[Arthas] - Quest Heroes of the Horde

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1100]
**Links:**

https://www.wowhead.com/quest=28400/heroes-of-the-horde

**What is happening:**
Ok, there are a lot of problems with this one. If you just fly over the top the RP/Quest never triggers. If u are at the [way](https://imgur.com/a/zbN48Ty) everything triggers fine. If u kill the NPC's that [Kingslayer Orkus](https://www.wowhead.com/npc=47443/kingslayer-orkus) fight (sry didn't see the names...some human female and dwarf)  [Kasha](https://www.wowhead.com/npc=48576/kasha) bug out and never come up to pick u...so u just stuck at the quest and must abound and redo it. 

**What should happen:**

**Comment by LKArthas** [comment]
Is not Bugged out Quests is supposed to get the stormpike battle plans from the slain quartermaster that orkus kills if you don't loot it kasha event won't occour tested 5 times with different classes and works good, report if you find any more issues
Closing
