### ISSUE TITLE
NPC - Desert Crawler (Visual Bug)

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1103]
**Links:**
https://www.wowhead.com/npc=40764/desert-crawler

**What is happening:**
The mob appears with a red name and bar as does aggressive NPCs, but he doesn't attack on sight.

**What should happen:**
I belive the NPC should have a yellow name and bar, as for the non-aggressive NPCs

![WoWScrnShot_043020_130816](https://user-images.githubusercontent.com/64436148/80703758-ac3b5400-8ae3-11ea-925d-be0750edfe19.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
