### ISSUE TITLE
NPC - Wild Horse

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#1107]
**Links:**
https://www.wowhead.com/npc=48180/wild-horse

**What is happening:**
Some horses are normal, rest are tiny.

**What should happen:**
All horses are normal sized.

![WoWScrnShot_043020_150223](https://user-images.githubusercontent.com/62393111/80708035-a6e60580-8af3-11ea-91ac-b6891133610d.jpg)

**Comment by Cefiro-Caecias** [comment]
They are different horses. If God liked homogeneity, he would have made us all horses the same size. Doubts and complaints, to the Titan Sargeras XD

**Comment by DeltaVortex** [comment]
hahaha love it
