### ISSUE TITLE
[Mob] Windfury Wind Witch's Air Blast dealing too much damage 

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#111]
**Links:**
https://ptr.wowhead.com/npc=2963/windfury-wind-witch
https://ptr.wowhead.com/spell=81181/air-blast

**What is happening:**
The Air Blast that Windfury Wind Witches cast deals over 100-150 damage to any enemy hit by it.

**What should happen:**
Air Blast should deal not deal nearly as much damage.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
