### ISSUE TITLE
NPC - Cranky Benj

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#1112]
**Links:**
https://www.wowhead.com/npc=14223/cranky-benj

**What is happening:**
NPC doesn't spawn.

**What should happen:**
NPC spawns.

**Comment by NightwindOI** [comment]
Already reported here https://github.com/GuabinaCore/WoWKoi/issues/981

**Comment by Cefiro-Caecias** [comment]
There is no bug present. This NPC is found.
