### ISSUE TITLE
[Hinterlands] - All that skitters (Quest)

### ISSUE THREAD

**Issue by KYovchevski** [GuabinaCore/WoWKoi#1114]
**Links:**

https://www.wowhead.com/quest=26523/all-that-skitters

**What is happening:**
 - Right clicking the spiderlings rapidly allows the player to loot multiple spiderlings for the quest from a single mob.
 - Killing a spiderling lets the player loot a spiderling for the quest from the corpse.

**What should happen:**
 - Right clicking the spiderling should grant a spiderling item to the player, with subsequent clicks not doing anything.
 - Based on wowhead comments, it appears that killing the spiderlings should not let the player loot quest items from them.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
