### ISSUE TITLE
Achievement - To All The Squirrels I've Loved Before

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1116]
**Links:**
https://www.wowhead.com/achievement=1206/to-all-the-squirrels-ive-loved-before

**What is happening:**
After doing the command /love on a critter listed in the achievement, it doesn't count as done.

**What should happen:**
There should be a sign on the critter /loved.

![WoWScrnShot_043020_181919](https://user-images.githubusercontent.com/64436148/80734218-246b3f00-8b0f-11ea-9847-325ee78fcfab.jpg)

EDIT: Checked the achievement with 19/21 the critters as suggested and it still counts as none of them being marked as done, but it's for now impossible to complete as Borean Frog and Steam Frog are located only in Borean Tundra, not yet available.

**Comment by Serithul** [comment]
Test doing it on all listed squirrels. Some achievements are visually bugged and don't show the progress while credit has been given.
