### ISSUE TITLE
Quest - The Princess Unleashed

### ISSUE THREAD

**Issue by Loquedog** [GuabinaCore/WoWKoi#112]
**Links:**

https://www.wowhead.com/quest=26049/the-princess-unleashed

**What is happening:**

The boss spawns fine and is ok, but the adds she spawn are level 60.

**What should happen:**

They should be spawning at level 25 or at least the level you complete the quest on at the time.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the netx update.
