### ISSUE TITLE
[Arthas] - Quest Kinelory Strikes

### ISSUE THREAD

**Issue by drbubbs** [GuabinaCore/WoWKoi#1120]
**Links:**

Quest: https://www.wowhead.com/quest=26116/kinelory-strikes
NPC: https://www.wowhead.com/npc=2713/kinelory

**What is happening:**

Kinelory casts rejuvenation on enemies during the escort quest.

**What should happen:**

Kinelory shouldn't cast rejuvenation on enemies.

**Comment by LKArthas** [comment]
Fixed
