### ISSUE TITLE
Dungeon - Stratholme (Live Side)

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1121]
**Links:**
https://www.wowhead.com/stratholme
from WoWHead or our Armory

**What is happening:**
The dungeon is working pretty fine, except for 3 things:
1. In the area of Market Row, a Monk using Chi Torpedo could fly and go into the walls;
2. The Argent Crusade isn't fighting the other NPCs;
3. The rats under the gate to enter Crusader's Square are all aggressive and keep the party in combat bug, even though they don't attack the players.

**Comment by ventarius5** [comment]
Supposedly, the flying bug is conncted with "manualy" entering the dungeon while being transformed into Obsidian nightwing.

**Comment by Exlyss** [comment]
Yes but he was far away from the entrance of the dungeon. I and even him used Chi Torpedo other times without having that bug.

**Comment by Cefiro-Caecias** [comment]
This Dungeons is still under reconstruction. Patience.
