### ISSUE TITLE
Ruins of Ahn'Qiraj Doors

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#1122]
**Links:**
https://www.youtube.com/watch?v=zdwPBW115Pw

**What is happening:**
Seems all the doors are now bugged closed?  No idea why, we were in about 3-4 days ago and all the doors, except Buru worked(because they, themselves are bugged, hahaha.) Today, after each down the doors stayed shut, had to use flying bug if want to complete.

**What should happen:**
Doors should just be opened, never closed.  It was after the 7.0.3 rework that turned it 10-man that this happened, if you look at the video I post you will see that the first boss gets completely skipped and the door is just open, not even there.

-----
Understand y'all have most raids and dungs under review, just want to make sure the report is up on Git to track. Thanks for all your hard work!

**Comment by Cefiro-Caecias** [comment]
This Raid is still under reconstruction. Patience.
