### ISSUE TITLE
Ancient Petrified Leaf drop.

### ISSUE THREAD

**Issue by Lvmymp5** [GuabinaCore/WoWKoi#1123]
https://classic.wowhead.com/guides/classic-hunter-quest-ancient-petrified-leaf
from wowhead and only link that goes into what the leaf does.
**What is happening:**
I got the drop Ancient Petrified Leaf from Majordomo Executus which got removed in cataclysm.
(Side note im just wondering if its possible to get the bow from the quest chain at the current state we are in.)

**What should happen:**
It should not drop at all as we are on patch 7.35.

**Comment by Cefiro-Caecias** [comment]
Fixed.
