### ISSUE TITLE
Ruins of Ahn'Qiraj -- Ossirian the Unscarred

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#1124]
**Links:**
https://wow.gamepedia.com/Ossirian_the_Unscarred

**What is happening:**
Tested Ossirian today, and it seems Supreme Mode was not on the boss which meant also no crystals were spawned or did spawn on the ground for the fight.

**What should happen:**
Ossirian should have debuff Supreme Mode, and a crystal/Pylon should be waiting mid room for the first pull, and another spawned randomly on the map.  After first crystal they then spawn randomly one by one after use.

-----
Understand y'all have most raids and dungs under review, just want to make sure the report is up on Git to track. Thanks for all your hard work!

**Comment by Cefiro-Caecias** [comment]
This Raid is still under reconstruction. Patience.
