### ISSUE TITLE
Blackwing Lair Doors

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#1125]
**Links:**
https://wow.gamepedia.com/Blackwing_Lair

**What is happening:**
After starting first encounter the entrance gate to BWL shuts... and wont reopen after combat.

**What should happen:**
Since 18 the gate is suppose to shut during most encounters, to refrain from running back in after death during fights.  But the gate should reopen after combat has ended, right now the gate just stays shut.
-------
Understand y'all have most raids and dungs under review, just want to make sure the report is up on Git to track. Thanks for all your hard work!

**Comment by Cefiro-Caecias** [comment]
This Raid is still under reconstruction. Patience.
