### ISSUE TITLE
Blackwing Lair Orb of Domination/Razorgore encounter

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#1127]
**Links:**
https://wow.gamepedia.com/Razorgore_the_Untamed

**What is happening:**
After pulling Grethok and his henchman, the timer starts, but at the end of it, no adds spawn and Razorgore doesn't aggro.  After use of orb nothing happens.  A visual effect like it works happens but the orb does nothing atm. After pulling to test boss, he hits like a truck, might be because egg mechanic/orb mechanic isn't working.

**What should happen:**

During Phase 1 the orcish orb controller, Grethok the Controller, and his two Blackwing Guardsmen are dealt with. On the pull a timer starts, at the end of which adds will start to spawn (phase 2). If the controller and his guards are dead before the timer expires, the raid will have a short phase out of combat at the end of phase 1. The Orb of Domination should be used right away to control Razorgore, else he will attack the raid. The controlled Razorgore is used to destroy all the eggs in the room.

----
Understand y'all have most raids and dungs under review, just want to make sure the report is up on Git to track. Thanks for all your hard work!

**Comment by Cefiro-Caecias** [comment]
This Raid is still under reconstruction. Patience.
