### ISSUE TITLE
Monk - Zen Pilgrimage spell

### ISSUE THREAD

**Issue by ghost** [GuabinaCore/WoWKoi#113]
**Links:**
https://www.wowhead.com/spell=126892/zen-pilgrimage

**What is happening:**
Monk lvl 14 spell Zen Pilgrimage doesn't teleport monk to home temple.
Error: The spell is not available to you.

**What should happen:**
Monk lvl 14 spell Zen Pilgrimage should teleport monk to home temple.

**Comment by Cefiro-Caecias** [comment]
There is no bug present. We have deliberately blocked that spell, to prevent them from traveling to Pandaria at this stage of development, since we have not yet repaired those maps, and they could cause a crash. Patience ^^
