### ISSUE TITLE
Dungeon - Dire Maul (Capital Gardens)

### ISSUE THREAD

**Issue by alekso999** [GuabinaCore/WoWKoi#1131]
**Links:**

from WoWHead or our Armory

**What is happening:**
The force field around Immol'thar doesn't disappear after deactivating the 5 pylons required for it. The pylons don't work as they don't visually change once deactivated.
Also the door in Immol'thar's room that leads to Prince Tortheldrin is open when it shouldn't be and the door after that boss which leads to the northern Dire Maul is closed when it should be open.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
This Dungeons is still under reconstruction. Patience.
