### ISSUE TITLE
[Arthas] - Quest: Mine disposal, the Goblin Way

### ISSUE THREAD

**Issue by highwarlord1** [GuabinaCore/WoWKoi#114]
Links: https://www.wowhead.com/quest=25058/mine-disposal-the-goblin-way

What is happening: The mines don't disappear after you detonate them and you can detonate one as many times as you want. Also they don't show the smoke animation when you detonate them.

What should happen: They should disappear after you detonate them and you have to detonate 10 different ones to complete the quest.

**Comment by LKArthas** [comment]
Fixed for next update
