### ISSUE TITLE
NPC - Encrusted Surf Crawler (Drop Rate)

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1146]
**Links:**
https://www.wowhead.com/npc=3108/encrusted-surf-crawler

**What is happening:**
I've killed dozens of these NPCs without a single drop of Crawler Meat, that should have 43% of drop rate, while getting many Green and White equipments having less than 1% of drop rate.

**What should happen:**
The NPCs should have a drop rate more consistent as the percentages seen on their WoWHead page.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
