### ISSUE TITLE
[Core] Neutral mobs pulled by being in close proximity to a npc within combat

### ISSUE THREAD

**Issue by Fhroozt** [GuabinaCore/WoWKoi#1147]
**Links:**
Wowhead: https://www.wowhead.com/npc=3101/vile-familiar

**Clips:**
Retail: https://youtu.be/MZ8eb10oD4E
Wowkoi: https://youtu.be/0ugeGNIEyt8

**What is happening:**
In the orc starter zone, the Vile Familiar mobs are neutral but in practice they have a very weird behaviour that means they start attacking you if you have another mob in the nearby area. 

**What should happen:**
The neutral mobs in close proximity to the vile familiar gets pulled without you hitting them with an ability. You can see the difference clearly in the clips.

This might be a bigger issue than just the orc starter zone but this is the only location I have tested it in.

**Comment by Fhroozt** [comment]
So from further testing, it seems like it's more of a core issue but I still had mixed results. It doesn't apply to all neutral mobs as you can see in this **clip:** https://youtu.be/WLeWC6YFSpM

In this clip I attack a wolf in the human starter zone but the 2nd wolf doesn't start attacking me, instead I pull it further to a Blackrock Spy which actually aggros. These mobs are all neutral.

https://www.wowhead.com/npc=49874/blackrock-spy
https://www.wowhead.com/npc=49871/blackrock-worg

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
