### ISSUE TITLE
[Quest] An Ancient Enemy

### ISSUE THREAD

**Issue by Drathnor** [GuabinaCore/WoWKoi#115]
**Links:**

https://www.wowhead.com/quest=24814/an-ancient-enemy
https://gyazo.com/8113e7be6cdb9a0f4dbedf4b2c517560

**What is happening:**

The turning-in quest text is in Russian for some reasons.

**What should happen:**

The turning-in quest text should be in English.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. Don't forget to delete Cache.
