### ISSUE TITLE
[Core] - Paladin Spell Beacon of Light

### ISSUE THREAD

**Issue by JadedNate** [GuabinaCore/WoWKoi#1154]
https://www.wowhead.com/spell=53563/beacon-of-light

**What is happening:**
The Paladin spell, Beacon of Light, only works when cast on self. The spell should cause the Paladin's heals to give a portion of healing done to the Beacon target, regardless of the current heals' targets.

**Comment by ShikoSCS** [comment]
Fixed, please test it
