### ISSUE TITLE
"Translation" quest bug

### ISSUE THREAD

**Issue by GhostySimon** [GuabinaCore/WoWKoi#1156]
**Links:**

from WoWHead or our Armory

**What is happening:**

When mounted spoke to Narimar, received a message that "You're mounted" and didn't get on the flying mount. Dismounted tried once again - got on the flying mount who' not getting anywhere:

![image](https://user-images.githubusercontent.com/63936782/80835825-884e4000-8bc1-11ea-8d91-7e265a52415d.png)

**What should happen:**

After speaking to Narmiar the player should be dismounted and the hop on the lying mount.

**Comment by Cefiro-Caecias** [comment]
The Desolace and Azshara maps are still under reconstruction, at 50%. Patience.
