### ISSUE TITLE
Dungeon - BlackRock Depths

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1158]
**Links:**
https://www.wowhead.com/object=169243/chest-of-the-seven

**What is happening:**
The Boss The Seven as killed dropped the chest with the loot inside but we couldn't open it

**What should happen:**
We should be able to open the chest to loot it.

![WoWScrnShot_050120_220354](https://user-images.githubusercontent.com/64436148/80838800-1e9e5800-8bfa-11ea-8884-de13215a1276.jpg)

**Comment by Cefiro-Caecias** [comment]
This Dungeons is still under reconstruction. Patience.
