### ISSUE TITLE
[Arthas] - Quest - Crossroads Caravan Delivery

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1162]
**Links:**
https://www.wowhead.com/quest=13975/crossroads-caravan-delivery

**What is happening:**
The second spell, Face Smash, is not working and the NPCs that attack the caravan start attacking the player, making completing the mission impossible.

**What should happen:**
The spell should be used to kill the attacking NPCs so you can protect the caravan.

![WoWScrnShot_050220_004727](https://user-images.githubusercontent.com/64436148/80847380-b5c1da80-8c0f-11ea-9a0b-06f0028be972.jpg)

**Comment by NightwindOI** [comment]
Hm ... I did that quest with no problem. Maybe bugged UI or that spell becomes Rip at some point.

**Comment by Exlyss** [comment]
EDIT: Asking around other people (@NightwindOI too) told me that they managed to complete easily the quest at low levels, so I think that the bug concerns both spells on the caravan: spell 1 should do more damage (right now it takes 5 hits to kill one NPC) and spell 2 should work, as it isn't at all.

**Comment by NightwindOI** [comment]
Aside from that, if two ppl do the quest (One on the Kodo...other follow and CC the spawned mobs) the event bug out and u gonna have a lot of NPC's stack on each other in the Crossroad.
