### ISSUE TITLE
[Arthas] - Quest Lost in the floods

### ISSUE THREAD

**Issue by Fhroozt** [GuabinaCore/WoWKoi#1164]
**Links:**

Wowhead: https://www.wowhead.com/quest=25187/lost-in-the-floods
Clip: https://youtu.be/L_8O_b9JPsM

**What is happening:**
Skipping the cinematic during the spyglass sequence teleports you to the location that you were at in the cinematics and gives you the ability to fly.

**What should happen:**
You should get teleported back to the tower and not gain the ability to fly

**Comment by Fhroozt** [comment]
From further testing, it's not just upon skipping the cinematic. If you watch the entire sequence you get teleported back but you still gain the ability to fly.

**Comment by Fhroozt** [comment]
From playing further, this seems to happen to more of the similar type of scripted content: https://www.wowhead.com/quest=13949/crossroads-caravan-pickup where after the caravan ride you also gain the ability to fly.

**Comment by LKArthas** [comment]
Fixed avaible on next update
