### ISSUE TITLE
[Arthas] - Quest Argent Call: The Trial of the Crypt

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1166]
**Links:**

https://www.wowhead.com/quest=27464/argent-call-the-trial-of-the-crypt

**What is happening:**
Cant attack the mobs. Only AOE spell's hit anything.Target spell gives that ''dispel'' error.
https://imgur.com/a/cXhc0n9

Relog fix the issue, but after that bug out again.So must be the add's u have that bug it out (The blood elf and dwarf)

**What should happen:**
U must be able to attack them.

**Comment by LKArthas** [comment]
Fixed
