### ISSUE TITLE
[Saitama] - Quest Warchief's Revenge

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#117]
**Links:**
https://www.wowhead.com/quest=14243/warchiefs-revenge
**What is happening:**
Some fo the Alliance Sailors that should be spawning on top of boats are spawning underwater, making them unhittable. Although the quest is completable, it takes longer to do so.

**What should happen:**
Every Alliance Soldier should either be on top of the boats, or on the water.

**Comment by LKArthas** [comment]
El Problema del respawn de las criaturas que vuelan Saitama
