### ISSUE TITLE
[Core] - Misc Visual - Unsheathing/Sheathing

### ISSUE THREAD

**Issue by Fhroozt** [GuabinaCore/WoWKoi#1171]
**What is happening:**
Sheathing and unsheathing your weapons glitches out sometimes and display you having it sjeathed  while it's really unsheathed and sometimes the other way around. Which is displayable when you press ur keybind for sheathing and it does the animation but the weapons do not move.

**What should happen:**
Sheathing or Unsheathing your weapons should always register correctly when you have them sheathed and you unsheath they're supposed to end up in your hands.

**Comment by Velthur-bot-3000** [comment]
It would seem this issue has been fixed.  Verified that this is fixed, thank you for reporting and enjoy!
