### ISSUE TITLE
[NPC] IX'lar The Underlord [MISC] Scale

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1174]
**Links:**

https://www.wowhead.com/npc=45744/ixlar-the-underlord
https://www.wowhead.com/spell=17169/summon-carrion-scarab
https://www.wowhead.com/npc=10699/carrion-scarab

**What is happening:**
The little scarabs he summ ( Carrion Scarab ) miss scale.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
