### ISSUE TITLE
"Firestarter" quest bug

### ISSUE THREAD

**Issue by GhostySimon** [GuabinaCore/WoWKoi#1176]
**Links:**

https://www.wowhead.com/quest=14196/firestarter

**What is happening:**

After using the ques item the vortex doesn't appear.

**What should happen:**

It should be following the player and absorbing the kills of Disciples of Elune.

**Comment by NightwindOI** [comment]
Desolace is at 50% fixed or something so that may be the reason.

**Comment by Cefiro-Caecias** [comment]
Desolace and Azshara maps are under repair, at 50%. Patience.
