### ISSUE TITLE
Random Portal Spawning in Tirisfal Glades

### ISSUE THREAD

**Issue by eighthourblink** [GuabinaCore/WoWKoi#1179]
**Links:**
https://www.wowhead.com/quest=24981/a-thorn-in-our-side

**What is happening:**
During this quest, there is a portal for Stormwind that is near the entrance of the scarlet Watchtower that is non-functional. 

**What should happen:**
Dont know if it should be here or not, but have never seen it at this location before 
![Screenshot_20200421_230518](https://user-images.githubusercontent.com/2291863/80866452-b7fe5600-8c5c-11ea-8a2e-fcd2ee3e54aa.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
