### ISSUE TITLE
Quest - Honor and Strength

### ISSUE THREAD

**Issue by Loquedog** [GuabinaCore/WoWKoi#118]
**Links:**

https://www.wowhead.com/quest=27449/honor-and-strength

**What is happening:**

The quest does not spawn the 3 Mossflayer Rogues.

**What should happen:**

It should spawn 3 Mossflayer Rogues which you are meant to kill so that you can recruit him into Fiona's caravan. It's a major road block to the zone quest line.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
