### ISSUE TITLE
[Arthas] - Quest Steel Thunder

### ISSUE THREAD

**Issue by Fhroozt** [GuabinaCore/WoWKoi#1180]
**Links:**
**https://www.wowhead.com/quest=27069/steel-thunder**

**What is happening:**
Every crate you pick up award 2 point into the quest

**What should happen:**
Every crate you pick up should award 1 point into the quest

**Comment by Fhroozt** [comment]
Okay so from further testing, it would seem the issue is way larger than this.

I got 2 points into the quest because I had abandoned and picked it up again,
This means I could get 5 sea pups and finish it with one click,
They also do not despawn when you die and try to release at corpse and,
Finally their running speed is supposed to match yours when you mount up but they don't.

**Comment by LKArthas** [comment]
Fixed and working as intended
