### ISSUE TITLE
[Tirisfal Glades] - Winter Veil Ornaments Showing off Seasonal

### ISSUE THREAD

**Issue by eighthourblink** [GuabinaCore/WoWKoi#1182]
**Links:**
from WoWHead or our Armory

There are Winter Veil Ornaments being showed outside of the seasonal event. Screenshot is around the Death's Watch Waypoint

**What should happen:**
Should not be appearing until the event starts

![Screenshot_20200422_215618](https://user-images.githubusercontent.com/2291863/80867327-a9666d80-8c61-11ea-88c8-d8f259239bba.png)

Calston Estate
![Screenshot_20200423_082827](https://user-images.githubusercontent.com/2291863/80867395-d3b82b00-8c61-11ea-97bb-c1c1e0bec65d.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
