### ISSUE TITLE
[Arthas] - Quest Lordaeron

### ISSUE THREAD

**Issue by Fhroozt** [GuabinaCore/WoWKoi#1184]
**Links:**
https://www.wowhead.com/quest=27098/lordaeron

**What is happening:**
If you skip the cutscene, you fall off the horse and sylvanas disappears.

**What should happen:**
When you skip the cutscene, you're supposed to be teleported to the Sepulcher.

**Comment by LKArthas** [comment]
The cutscene skip at retail seems to teleport you back yo sylvanas starting quest if your away from the sepulcher área and to the sepulcher once you have entered at the sepulcher zone completing the quest, tested several times at retail and fixed now as intendeed Will be avaible on next update
