### ISSUE TITLE
[Core] - Priest Talent Twist of Fate

### ISSUE THREAD

**Issue by pmoreira01** [GuabinaCore/WoWKoi#1185]
**Links:**

https://www.wowhead.com/spell=265259/twist-of-fate

**What is happening:**

After every cast, even mount or instant cast, you gain the buff.

**What should happen:**

After damaging a target below 35% health, you deal 20% increased damage and 20% increased healing for 10 sec.

**Comment by ShikoSCS** [comment]
Fixed, please test it
