### ISSUE TITLE
[Quest] Saving Foreman Oslow

### ISSUE THREAD

**Issue by Severikangas** [GuabinaCore/WoWKoi#1188]
**Links:**

https://www.wowhead.com/quest=26520/saving-foreman-oslow

from WoWHead or our Armory

**What is happening:**

Quest-reward is rewarded twice upon handing in the quest.

**What should happen:**

Quest-reward should only be rewarded once upon handing in the quest.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
