### ISSUE TITLE
[Dungeon] Dire Maul - Warpwood Quarter on RDF not completing after all bosses are killed

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1190]
**Links:**

**What is happening:**
When killing all bosses, the dungeon finder doesn't give dungeon completion to the players, as if we still were in queue.

**What should happen:**
When killing all bosses, the dungeon finder should give dungeon completion to the players.

**Comment by Cefiro-Caecias** [comment]
This Dungeons is still under reconstruction. Patience ^^
