### ISSUE TITLE
[Dungeon] Stratholme - Service Entrance's Ramstein the Gorger spawns before any mobs are dead

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1192]
**Links:**
https://classic.wowhead.com/npc=10417/venom-belcher
https://classic.wowhead.com/npc=10439/ramstein-the-gorger

**What is happening:**
Ramstein the Gorger has already spawned before any of the Venom Belchers or other mobs have been killed.

**What should happen:**
Ramstein the Gorger should only spawn after every single other mob in the room where he spawns is killed, at which point he opens the door to Baron Riverdare, walks through the door, and closes it.

**Comment by Cefiro-Caecias** [comment]
This Dungeons is still under reconstruction. Patience ^^
