### ISSUE TITLE
[Mob] Scarlet Cannoneer not scaled up in Scarlet Halls

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1195]
**Links:**
https://www.wowhead.com/npc=59293/scarlet-cannoneer
**What is happening:**
These mobs aren't scaling up with the player level, up to 90.

**What should happen:**
These mobs should scale with player level, up to 90.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
