### ISSUE TITLE
[Dungeon] Sunken Temple - first room's map all-green

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1196]
**Links:**
https://www.wowhead.com/sunken-temple
**What is happening:**

The Sunken Temple map in the first room only shows a green screen.

**What should happen:**
The Sunken Temple map should show up correctly.

**Comment by LKArthas** [comment]
Clear your cache folder, or check any maps addon sunken temple map is loading good
Best regards
