### ISSUE TITLE
[Mob] Jammal'An the Prophet spams voiceline

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1198]
**Links:**
https://classic.wowhead.com/npc=5710/jammalan-the-prophet

**What is happening:**
Jammal'an repeatedly says "The shield be down! Rise up Atal'ai! Rise up!" over 20 times before the boss is pulled. This may be related to aggroing, killing mobs, or other issues.

**What should happen:**
Jammal'an should only say this once, or a couple of times at most.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the enxt update.
