### ISSUE TITLE
[Quest] Who's Top of the Food Chain Now? 

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#120]
**Links:**
https://www.wowhead.com/quest=24816/whos-top-of-the-food-chain-now
**What is happening:**
The quest turn-in shown on the map isn't on the Town-In-A-Box. Instead, it is in the middle of the Dire Strait. However, the quest is turned in at the Town-In-A-Box.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
