### ISSUE TITLE
[Arthas] - Scholomance Instructor Chillheart

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#1200]
**Links:**
https://www.youtube.com/watch?v=TZJPTwnLyW4 (video reference)

https://wow.gamepedia.com/Scholomance
https://wow.gamepedia.com/Instructor_Chillheart

**What is happening:**
So during fight ice wall appears, but seems to move very quickly. Also it killed our party because it moved too quickly through room, was able to kill boss, when released and came back, urn and boss gone with no loot.

**What should happen:**
the ice wall should slowly move through from farside of room to the near side, taking a total of 2 minutes to do so, seems to be about every 3 seconds the wall moves a tad bit. very small amounts. Once you kill the physical body of the Instructor you then enter phase two and fight the urn! with no ice wall anymore.

**Comment by LKArthas** [comment]
Ice wall tales 6 secs between changing position you need to dos fast chillhearth to not be overwhelmed by the wall according to blizz sniff it noches at 6 secs pheraps se can adjunto the moving distance but overall should give between 20-30 secs more Shen only gots 90k life at lvl 60 for a bad geared party the 48 secs that takes to end the last part of the room is doable
