### ISSUE TITLE
[Arthas] - Scholomance Jandice Barov

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#1201]
**Links:**
https://www.youtube.com/watch?v=TZJPTwnLyW4 (video reference) 7.3.5

https://wow.gamepedia.com/Scholomance
https://wow.gamepedia.com/Jandice_Barov

**What is happening:**
Seems to go below allotted phase health.  Started fight and she proceeded to go to below 50% health before phasing to visions, amount of visions is ok, but Health and/or Damage of visions seems to be too much.  Also if you die during phase the visions will attack you on entrance to dung through walls.

**What should happen:**
When attacking Jandice, when reaching 60% she phases into visions, 12 different visions one being her, where you either kill the visions to find her, or she is hit, the visions disappear and fight commences again until you reach 30% where phase 2 happens again until you locate Jandice. Also vision health is literally nothing like 1 hp? you should be able to aoe with low damage or white auto to kill one.

**Comment by LKArthas** [comment]
This is fixed on previous commit
