### ISSUE TITLE
[Scaling] Booty bay bruiser (NPCID - 4624)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1206]
**Links:** https://www.wowhead.com/npc=4624/booty-bay-bruiser

from WoWHead or our Armory

**What is happening:**
The NPC isn't scaling and is always 110 right now (stopping me from farming Insane in the Membrane)

**What should happen:**
The NPC should be scaling to your level as the 2 - 120 in the WoWHead page suggests

**Comment by Cefiro-Caecias** [comment]
The NPC is well scaled in legion. What you report is already from BfA.
