### ISSUE TITLE
[Core] - Achievements: Represent and Giddy Up!

### ISSUE THREAD

**Issue by highwarlord1** [GuabinaCore/WoWKoi#121]
Links: https://www.wowhead.com/achievement=621/represent
https://www.wowhead.com/achievement=891/giddy-up

What is happening: When I equipped a tabard, I didn't get the Represent achievement. Also when I learned apprentice riding I didn't get the achievement, but when I relogged I saw that I got every single riding achievement including the master one for whatever reason.

What should happen: Obviously when I equip a tabard for the first time I should get Represent. And also when I learn apprentice riding I should just get the achievement for apprentice riding, not other ones.

**Comment by Thordekk** [comment]
This bug is not core related, look into achievement_dbc and add missing achievemnts like that ('621', '-1', '-1', '0', 'Represent', 'Equip a tabard.', '92', '10', '30', '0', '2637', '', 'Level 10', '0'),
