### ISSUE TITLE
NPC - Digsite Zombie

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1212]
**Links:**
https://www.wowhead.com/npc=52604/digsite-zombie

**What is happening:**
The NPC isn't scaled to the area's level, in fact he's level 85.

**What should happen:**
His level should be lowered to the max of the area, 60.

![WoWScrnShot_050320_133738](https://user-images.githubusercontent.com/64436148/80916285-05132280-8d58-11ea-860c-a66246da7be1.jpg)

**Comment by NightwindOI** [comment]
That not true. This specific zombie is visible only if u doing/done with ZG quest chain and its set to level 85 by default. You can see the level on your link too.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
