### ISSUE TITLE
[Quest] Stranglethorn Fishing Extravaganza world quest not starting

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1214]
**Links:**
https://www.wowhead.com/quest=44765/stranglethorn-fishing-extravaganza
**What is happening:**
The STV fishing extravaganza world quest doesn't begin after 2 PM server time, not starting at all (as of 2:16 PM).

**What should happen:**
The STV quest should be given to you a bit after 2 PM server time when you are in Northern Stranglethorn and the Cape of STV.

**Comment by Cefiro-Caecias** [comment]
Recalibrated date. This Sunday should already work properly. The advertiser will appear hours before, but the event will start at 02:00 PM until 05:00 PM.

https://www.wowhead.com/stranglethorn-fishing-extravaganza
