### ISSUE TITLE
[Bug] Battle pets

### ISSUE THREAD

**Issue by taktrix** [GuabinaCore/WoWKoi#1215]
There are multiple bugs here so I'm going to go through them one at a time. 

Problem: [Bug #1]{Quest} Battle pet activation the first time costing 15g.

Solution: [Bug #1]{Quest} Battle pets shouldn't cost 15g, in the retail version of the game it's simply a quest you take and then complete to activate and for a good reason, it's not easy to get your hands on 15g at the beginning of the game when everything is around 8 silver a complete. 

Problem: [Bug #2]{Quest} Battle pets slots all locked requiring payment and leveling.

Solution: [Bug #2]{Quest} the way battle pets is suppose to start is when you get the first quest you automatically get 2 level 1 pets, they both go in the first 2 slots. The reason for this is because the first battle you ever encounter should be a definite win, and you should face 1 level 1 pet who should be in the immediate area so you can then win your first battle and open up the 3rd slot. At which point here is how battle pets SHOULD work. 

Wild NPC Pets: Level 1 all pets of this level will not have ANY companion pets. Level 2 all pets will only have 1 companion pets. Level 3+ all pets will have 2 companions of the same level but NOT always of the same type making it random which 2 you fight as complimentary pets.

Problem: [Bug #3]{Mechanics} None of the battle pet abilities work as advertised, in fact a great deal of them not working properly makes it nearly impossible to battle correctly.

Solution: [Bug #3]{Mechanics} All pets should have abilities that work exactly as they are written in the description panel on their abilities, as of right now none of them work at all. When something happens right now no ability pops up, no buff or debuff pops up and the damage is completely varied. I'll give you 2 prime examples of this. Undead pets biggest attribute is that when they die they pop back up and are invincible for an entire round. Right now they do die, they aren't invincible, and the pet that killed them is instead bugged and attacks them twice in a row after they die. Which is another bug by the way. The last action in every pet battle right now is a big, if you capture someone in a cage it does the animation twice after they're caught as a bug or if they die it replays killing them twice.

Problem: [Bug #4]{Technical} You get no experience on your character after the battle and your pets don't heal upon battle completion.

Solution:  [Bug #4]{Technical} When the pet battle completes 2 things should occur, your last battle pet should get healed for about 20% of its life, and your actual character in the game should gain 1/3 of a bar of experience if the pets that you are fighting are of the same level as yours. Minor variations in experience based on how much higher or lower the pets you are fighting are compared to yours.

Problem: [Bug #5]{Audio} Sunflower battle pet vocalization is just crunchy.

Solution: [Bug #5]{Audio} Sunflower battle pet vocalization should be a song called "we don't want zombies on the lawn" from plants vs zombies.

Problem: [Bug #6]{Technical} Battle pets/vanity NPC pets all move as some really slow speed.

Solution: [Bug #6]{Technical} Battle pets/vanity pets should be moving at the exact speed of the person who they are attached to, if you fly they will either fly with you or alternatively if they are only ground pets they will disappear when you get out of 15 yard range away from them.

Problem: [Bug #7]{Mechanics} When switching pets into battles for some reason the enemy pet attacks giving it one extra phase.

Solution: [Bug #7]{Mechanics} When switching pets into battles all attacks should stop and then both pets get to pick their attack. The enemy pet would go first but right now you're losing an attack because the enemy pet just attacks for an entire phase without you doing anything when you switch.

Problem: [Bug #8]{Technical} There are lots of areas pretty much world wide where there are no battle pets that spawn in the wild. 

Solution: [Bug #8]{Technical} Place pets in those areas, mark those areas on the map with specific level caps like for example Durotar should be level 1-3 pets. Pet levels in areas are based on the characters level progression in the game. So starter areas will always have the lowest level battle pets and any area beyond Pandaria will have level 23-25 pets.

Problem: [Bug #9]{Technical} Battle pet experience per fight is wildly off norm. At level 1 if your battle pet fights and wins as the single battler it should level, if it fights and wins as part of a team that has to switch that experience gets cut by half so it takes 2 fights or 3 if all 3 battle pets switch in. The amount of time it takes to level right now is basically equivalent to if you were starting a battle pet at level 18.

Solution: [Bug #9]{Technical} Scale the experience appropriately. The only time it should take 8 battles to level a battle pet is at level 25. 

Problem: [Bug #10]{Technical}  Can't release pets. I tried releasing a pet of which I have 3 of, and it shows me releasing it but then when I relog it's there again, and it won't let me capture any more of that pet because of this bug.

Solution: [Bug #10]{Technical} Fix the pet count and the way release works.

**Comment by taktrix** [comment]
Problem: [Bug #11]{Visual} Showing incorrect levels in the world for Cluckatron, Gizmo, and Whirls from Cassadra Boom. 
![Cassandra Boom](https://user-images.githubusercontent.com/64738413/81236213-ae614f00-8fca-11ea-870c-7daa666b7aca.jpg)
![Cluckatron](https://user-images.githubusercontent.com/64738413/81236215-af927c00-8fca-11ea-8c73-9a297b2d669a.jpg)
![Gizmo](https://user-images.githubusercontent.com/64738413/81236216-af927c00-8fca-11ea-9ee5-27a4fba2806f.jpg)
![Whirls](https://user-images.githubusercontent.com/64738413/81236219-b02b1280-8fca-11ea-9bba-b5ac8f4f21a2.jpg)


Solution: [Bug #11]{Visual} Adjust the levels to their proper numbers.

**Comment by Kobasun** [comment]
Bugs confirmed for me:
- pets can't be released, after each relogging or using "Revive battle pets" all released pets appear in the list again
- pets bought from trainer (Orange Tabby Cat, Blue Moth, Jade Crane Chick, others are pretty sure affected too) don't have any abilities on lvl 1 until relogging, which means you can't use them in battle. When they level, you have to relog as well to be able to use new abilities.
- Attack and defence bonuses and penalties ("strong" and "weak") do not seem to be working as intended (covered in other bug reports here)
- Not a bug, but still: entry cost of 15 gold seems way too high for a fresh player to join pet battling.
**Battle pet achievements** are messed up too. The ones "raise a pet to level X" seem to work as intended, while "collect X pets" and "win X pet battles" are apparently bugged - I caught just a couple of pets and instantly got 5 achievements up to "Lil' Game Hunter" (for catching 1, 15, 25, 50 and 75 unique pets accordingly). Currently I have 280 achievement points in this category (not earned, obviously), but the achievement "Trainer Extraordinaire" for getting 100 AP hasn't popped up. The achievements for "win X pet battles" cannot be taken and do not even track. So currently battle pets seem to be the most bugged part of this otherwise near-perfect project.

**Comment by Velthur-bot-3000** [comment]
Hell all. I can't speak any anything other than the cost of training to start battle pets.  IT IS NOT A BUG THAT YOU PAY. You are correct in remembering a questline to introduce you to it, but you still, after that intro had to pay 10g(which is the max it should cost.). You have to train to use and play battle pets, that price has always been 10g unfortunately but you pay it once, it's account-wide.
