### ISSUE TITLE
[Core] - Druid Moonglade Spell not working

### ISSUE THREAD

**Issue by taktrix** [GuabinaCore/WoWKoi#1221]
Problem: Teleport Moonglade spell is suppose to take you to Moonglade then port you back if you press it again. Instead it just keeps porting you to Moonglade and never ports you back.

Solution: Adjust spell to work correctly.

**Comment by Serithul** [comment]
https://www.wowhead.com/spell=18960/teleport-moonglade

Please remember to link any npc, spell, quest, etc involved with the bug reported as it helps speed up the devs work.

**Comment by taktrix** [comment]
Thank you I will.
