### ISSUE TITLE
[Quest] Nat Pagle, Angler Extreme giving you the fishing pole without completing the quest

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1222]
**Links:**
https://www.wowhead.com/quest=6607/nat-pagle-angler-extreme

**What is happening:**
This quest is giving the reward before you collect the fish and turn the quest in, having another quest, with the same name, that needs no turn-in, and gives you the rod as the reward, that says "Well hello there, young (race). Either my memory is failing me, or I forgot to give you this last time we spoke..."

**What should happen:**
The quest shouldn't have that option available at all, only having 1 of the Nat Pagle, Angler Extreme quests - the one that doesn't give you the pole automatically.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
