### ISSUE TITLE
[Profession] Arctic Char dropping from Schools of Tastyfish

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1223]
**Links:**
https://www.wowhead.com/object=180248/school-of-tastyfish
https://www.wowhead.com/item=69931/arctic-char
**What is happening:**
The Arctic Char fish is dropping from Schools of Tastyfish, where it should not be available - it should only be fishable for a quest in Dun Morogh.

**What should happen:**
The Arctic Char shouldn't drop from Schools of Tastyfish.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
