### ISSUE TITLE
NPC - Hive'Regal Slavemaker

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1227]
**Links:**
https://www.wowhead.com/npc=11733/hiveregal-slavemaker
https://www.wowhead.com/spell=19469/poison-mind

I belive the spell Poison Mind should be given a longer cooldown: at the moment is impossible to kill one of these NPCs alone, because if you don't one-shot them, they would charm you for 15 seconds refulling all their hp, and after these 15 seconds of charm they would use the spell again in less than 3 seconds.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
