### ISSUE TITLE
Duplicate quest

### ISSUE THREAD

**Issue by GhostySimon** [GuabinaCore/WoWKoi#1229]
**Links:**

from WoWHead or our Armory

**What is happening:**

Got two same quests by picking one from NPC and accepting the other one that has been picked up by a party member:
![image](https://user-images.githubusercontent.com/63936782/80929325-0143c800-8d79-11ea-8adf-b375ef5c3adc.png)

**What should happen:**

Should not allow have two identical quests.

**Comment by Cefiro-Caecias** [comment]
I see. One quest is for the Alliance, and one for the Horde. Recalibrated. Available in the next update.

https://www.wowhead.com/quest=27676
https://www.wowhead.com/quest=27681
