### ISSUE TITLE
[Quest] Naga Hide, Bilgewater Cartel Represent, Irresistible Pool Pony, and Surrender Or Else!

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#123]
**Links:**
https://www.wowhead.com/quest=24859/naga-hide
https://www.wowhead.com/quest=24858/bilgewater-cartel-represent
https://www.wowhead.com/quest=24864/irresistible-pool-pony
https://www.wowhead.com/quest=24868/surrender-or-else
**What is happening:**
All these quests' turn-in locations are incorrect on the map, showing them to be in the middle of the Ruins of Vashj'Elah, when they should be near the top of the hill (52.25, 73.00)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
