### ISSUE TITLE
[Bug]{Mechanical} Vendor Items Disappearing

### ISSUE THREAD

**Issue by taktrix** [GuabinaCore/WoWKoi#1230]
Problem: Green Balloon and Yellow Balloon from the Blax Bottlerocket goblin vendor in Ogrimmar are bugged to where you can't use them, it has a reference to childrens week in the item description which might be the cause of the issue. When I relogged to check if that would help they vanished from my bags! It has also come to my attention since the original posting of this post that it is not just these 2 items. I purchased a bunch of pets from a vendor and when I used them nothing happened and when I relogged afterward they never appeared in my list, which is to say that this seems to be a widespread issue with vendor items in at least Ogrimmar.

https://www.wowhead.com/item=69895/green-balloon

https://www.wowhead.com/item=69896/yellow-balloon

Solution: Check and recheck all the vendor items because as of right now they don't appear to function beyond selling them, they appear in your inventory but then they don't function properly or get used but don't get added to your pages.

**Comment by Cefiro-Caecias** [comment]
Fixed items being sold outside of your world event or quest. Available in the next update.
