### ISSUE TITLE
NPC's with Fly emote/movement

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1234]
**Links:**

https://www.wowhead.com/npc=46861/nyxondra

**What is happening:**
Nyxondra is just an example. Most of the time's these mobs fly just fine, but at some point, they forgot about that ability and just start to walk into the air.
https://imgur.com/a/F0kHVTD

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Nyxondra fixed. Available in the next update.
