### ISSUE TITLE
[Mob] Gorishi Grub and Gorishi Egg (Clutchmother Zavas spawns) not scaled up

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1237]
**Links:**
https://www.wowhead.com/npc=9498/gorishi-grub
https://www.wowhead.com/npc=9496/gorishi-egg
**What is happening:**
The Gorishi Grub and Gorishi Egg NPCs that spawn from Clutchmother Zavas don't scale up when spawned by her.

**What should happen:**
The Gorishi Grub and Gorishi Egg NPCs that spawn from Clutchmother Zavas should scale up when spawned by her.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
