### ISSUE TITLE
[Quest] 6134 ghost-o-plasm-round-up

### ISSUE THREAD

**Issue by cyberfreak666** [GuabinaCore/WoWKoi#124]
https://classic.wowhead.com/quest=6134/ghost-o-plasm-round-up

The ghost do not spawn when you lay the ghost magnets on the selected area.
Possible work around is to have the skeletons drop the Ghost-o-plasm.

When you lay the Ghost Magnets down the ghost centaurs should be moving toward the magnets so you can kill them for there Ghost-o-plasm drop.

**Comment by Cefiro-Caecias** [comment]
Desolace is still under repair. We will notify when the map is 100% complete.
