### ISSUE TITLE
[Bug]{Technical} Charging a mob on top of a hill caused a fall through the map.

### ISSUE THREAD

**Issue by taktrix** [GuabinaCore/WoWKoi#1242]
Problem: I had used my druid wild charge ability to engage a bird in the middle of desolace, it was up on a pretty steep hill, when I got to it instead of going up the hill it decided to path through the hill. And once that happened I dropped through the map and fell to my death.

Solution: Rework pathing conditions to consider terrain collision parameters.

**Comment by NightwindOI** [comment]
its global issue with every charge/blink spell.Need Vmap rework.

**Comment by Cefiro-Caecias** [comment]
It is a big problem in review. Patience.
