### ISSUE TITLE
[Mob] Mobs not scaled up to lvl 20

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1247]
**Links:**
https://www.wowhead.com/npc=38300/spitescale-wavethrasher
https://www.wowhead.com/npc=38301/spitescale-siren
**What is happening:**
These mobs aren't scaled up to lvl 20.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
