### ISSUE TITLE
[Quest] 14393 Into the Fray and 14394 Death to Agogridon

### ISSUE THREAD

**Issue by cyberfreak666** [GuabinaCore/WoWKoi#125]
https://www.wowhead.com/quest=14393/into-the-fray
https://www.wowhead.com/quest=14394/death-to-agogridon

Reason I am listing these together is cause they suffer from the same problem and are in the same quest line. 
After you speak to Khan Leh'Prah about joining the fight you get to mount one of the Centaur Warmonger you should also have 3 other unit centaurs to follow you one that heals one that tanks and another dps but without the other 3 units the only button that will work is to throw your spear. Needless to say that this made fighting the Doomguard and Priestess Thandarissa 
hard to complete. When the Centaur I was riding got low on health I got off and fought the monsters myself in order to finish the quest.

The follow up quest Death to Agogridon suffers from the same problem which is why I reported them both together.

**Comment by LKArthas** [comment]
Both área still pendants script desolace isnt Marked completed yet :,-)

**Comment by Cefiro-Caecias** [comment]
Desolace is still under repair. We will notify when the map is 100% complete.

**Comment by LKArthas** [comment]
Fixed now
