### ISSUE TITLE
[NPC] Was able to buy a Ironforge Satchel at Friendly rep

### ISSUE THREAD

**Issue by Thovia** [GuabinaCore/WoWKoi#1254]
**Links:**
https://www.wowhead.com/npc=50309/captain-stonehelm

**What is happening:**
I was able to buy a Ironforge Satchel that says it needs Revered, but i was able to buy one at Friendly rep.
I can also use the bag.

**What should happen:**
I should be only able to buy it at Revered rep

**Comment by Thovia** [comment]
Update: The same thing is with Gnomeragan Satchel

**Comment by Serithul** [comment]
It's the same across all quartermasters. Alliance and Horde ones.

**Comment by Cefiro-Caecias** [comment]
So is. It is deliberate.
