### ISSUE TITLE
[Mob] Spitescale Siren spell damage too high

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1255]
**Links:**
https://www.wowhead.com/npc=38301/spitescale-siren

**What is happening:**
Spitescale Sirens' spell damage is too high, dealing about 1/3 an appropriately-leveled player's health per spellcast.

**What should happen:**
The spells should deal less damage.

**Comment by Cefiro-Caecias** [comment]
Fixed.
