### ISSUE TITLE
Heirloom Vendors

### ISSUE THREAD

**Issue by JadedNate** [GuabinaCore/WoWKoi#1257]
https://www.wowhead.com/npc=52030/liliana-emberfrost

**What is happening:**
PvP Heirloom Vendor sells the same heirlooms as the one in Ironforge.

**What should happen:**
PvP Heirloom vendors should only sell the heirlooms that the player can buy with Marks of Honor.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
