### ISSUE TITLE
[Arthas] - Quest What tomorrow brings

### ISSUE THREAD

**Issue by rapierwow** [GuabinaCore/WoWKoi#1258]
**Links:**
https://www.wowhead.com/quest=27401/what-tomorrow-brings
from WoWHead or our Armory

**What is happening:**
If you skip the cinematic when you click on the telescope you start flying.

**What should happen:**
You should get teleported back to the telescope if you skip the cinematic

**Comment by skazord** [comment]
Can confirm, this is reproducible.
