### ISSUE TITLE
[Quest] 14376  Jugkar's Undoing

### ISSUE THREAD

**Issue by cyberfreak666** [GuabinaCore/WoWKoi#126]
https://www.wowhead.com/quest=14376/jugkars-undoing

The Infernal Power Core when used did not let me control Lord Azerthoc like its post to. But no you can not just kill Jugkar Grim'rod without the demon I tried that.

If it was working the infernal power core would let you control Lord Azerthoc for 2 mins during which time you use him to kill the Warlock Jugkar Grim'rod.

**Comment by Cefiro-Caecias** [comment]
Desolace is still under repair. We will notify when the map is 100% complete.
