### ISSUE TITLE
[Quest] Return to Razor Hill has wrong description text

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1261]
**Links:**
https://www.wowhead.com/quest=6386/return-to-razor-hill
**What is happening:**
When opening the quest book, the quest on the sidebar reads "Buy a wind rider to **the Crossroads** from the wind rider master Doras, then bring Gryshka's Letter to **Zargh** at **the Crossroads**.

**What should happen:**
When opening the Quest Book, the quest on the sidebar should read "Buy a wind rider to Razor Hill from the wind rider master Doras, then bring Gryshka's Letter to Grimtak at Razor Hill".

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
