### ISSUE TITLE
[Core] - Self Interrupt due GCD

### ISSUE THREAD

**Issue by ZarisTR** [GuabinaCore/WoWKoi#1262]
**What is happening:**
When you try to spam skills, after global cooldown you have to click to spell one or two more time, other wise it is being interrupted. It is actually hard to explain this bug. I captured a video about it: 

https://streamable.com/0e5ows

Please watch the video, you'll see what i mean.

**What should happen:**

As a retail player, i just detected issue. In retail, it's just casting spell after global cooldown without more tries. so its smooth when u do spam heals also u dont lose your seconds.

**Comment by Midzet** [comment]
Seems to be a priest bug.

**Comment by ZarisTR** [comment]
I think it's a general issue. I faced same problem when i playing in freakz and it was same for mw monk too. It must be same here also.

**Comment by NightwindOI** [comment]
It's a general issue. I had it with a mage and a shaman.

**Comment by Serithul** [comment]
http://thedefiantguild.com/forums/discussion/15431

This could help convey the problem better.
