### ISSUE TITLE
Dungeon - The Deadmines

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1263]
**Links:**

from WoWHead or our Armory

**What is happening:**
1. When boss Helix Gearbraker's Oaf uses Oaf Smash, the player caught by that is able to fly for all the time he stays in the dungeon. It persists through death.
2. The door that leads to Ironclad Cove can't be opened unless you have a key from blacksmithing or a rogue in the party.

**What should happen:**
1. The spell shouldn't allow you to fly.
2. The door should be opened by using the cannon in front of it.

**Comment by Cefiro-Caecias** [comment]
This Dungeon is under repair. Patience.
