### ISSUE TITLE
[Spell] Ticking Time Bombs deal way too much damage

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1264]
**Links:**
https://www.wowhead.com/spell=60227/ticking-time-bomb
**What is happening:**
Ticking Time Bombs, used by Northwatch Marines and Sergeant Curtis, take away half your health. 

**What should happen:**
They should deal less damage per spellcast.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
