### ISSUE TITLE
[Arthas] - Quest After using quest item, you can swim in the air

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1265]
**Links:**
https://www.wowhead.com/quest=25187/lost-in-the-floods
**What is happening:**
After you use the quest item to find where people are (this may be because I am a troll, somehow? I'm not sure if it happened in my other characters, though - it might've, and I just didn't notice.), you can swim in the air.

**What should happen:**
You're not meant to be able to swim in the air.

**Comment by taktrix** [comment]
This is actually not an item bug, but a general game bug whenever there's a sequence in the game if you press something during it like jump swimming is the result.

**Comment by Macumbino** [comment]
Anytime you dismount from a quest "mount", this also happens.

**Comment by taktrix** [comment]
Yea from what I've seen I've drawn the conclusion that this bug occurs when the game doesn't know what to do. So instead of an action that doesn't exist it defaults you into a floating state.

**Comment by LKArthas** [comment]
Fixed avaible on next update
