### ISSUE TITLE
Stranglethorn Valley - NPCs Type

### ISSUE THREAD

**Issue by antonioyu0505** [GuabinaCore/WoWKoi#1268]
**Links:**
https://classic.wowhead.com/npc=588/bloodscalp-scout
https://classic.wowhead.com/npc=595/bloodscalp-hunter
https://classic.wowhead.com/npc=587/bloodscalp-warrior

**What is happening:**
These NPCs are lacking the "Humanoid" type.

**What should happen:**
These NPC should have the "Humanoid" type.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
