### ISSUE TITLE
[Arthas] - Quest A Heap of Delicious Worg

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1269]
**Links:**
https://www.wowhead.com/quest=28313/a-heap-of-delicious-worg

**What is happening:**
So this quest is just an example.''On use'' quest's are very easy to be abused since u can spam the item on the body until the NPC despawn.Not sure how to tag the issue.as Global or Core...since its DB issue but affect all the quests that work that way.

**What should happen:**
Generally speaking, once u use the item on a body, that body must despawn 99% of the time.
https://www.youtube.com/watch?v=_HRbN-mffZg

**Comment by LKArthas** [comment]
Fixed
