### ISSUE TITLE
Dungeon - Dire Maul (Warpwood Quarter)

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1271]
**Links:**

from WoWHead or our Armory

**What is happening:**
1. Mage's Blink doesn't dispel Rooted.
2. NPCs Arcane Aberrations are dealing too much magic damage.
3. Before Boss Tendris Warpwood, if you fall down from the upper floor, there is an invisible walkway (screenshot).
4. NPCs Residual Monstruosity in Prison of Immol'thar are wandering around.

**What should happen:**
1. Blink should dispel Root debuff.
2. NPCs should deal less magic damage.
3. The invisible walkway shouldn't exist.
3.NPCs should be sticking close to the pillar they're protecting.

![WoWScrnShot_050620_135138](https://user-images.githubusercontent.com/64436148/81175378-bce84000-8fa3-11ea-839e-b2e7563b15c6.jpg)

**Comment by Cefiro-Caecias** [comment]
This Dungeon is still under reconstruction. Patience.
