### ISSUE TITLE
NPC: Diseased Hawk

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#1274]
**Links:**
https://www.wowhead.com/quest=26954/a-different-approach
https://www.wowhead.com/npc=44481/diseased-hawk
from WoWHead or our Armory

**What is happening:**
Mob is untargetable, making the quest impossible to complete.

**What should happen:**
Mob should be targetable

**Comment by NightwindOI** [comment]
U need to bring the dude on the top and he will pull them or w/e. Done that quest last week with no problems.

**Comment by LKArthas** [comment]
Exactly bring zen Kiki up
