### ISSUE TITLE
[Core] - Priest - Shadow - Shadowy Apparitions

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#1277]
**Links:**
https://www.wowhead.com/spell=78203/shadowy-apparitions
from WoWHead or our Armory

**What is happening:**
They appear when you crit but once they reach the target, they don't deal damage.

**What should happen:**
It should proc when you crit and once the apparition reaches the target it should deal damage.

**Comment by Thordekk** [comment]
Fixed need test
