### ISSUE TITLE
[Arthas] - Quest: King of Centaur Mountain; scaling

### ISSUE THREAD

**Issue by highwarlord1** [GuabinaCore/WoWKoi#128]
Links: https://www.wowhead.com/quest=13995/king-of-centaur-mountain

What is happening: The orc doesn't do anything when you accept the quest, and Korak just stands there and you kill him and complete the quest.

What should happen: The orc says something and runs to the hill, places a banner, and then mobs come attack you and then Korak at the end. Also, mobs in the Stagnant Oasis aren't level scaled.

**Comment by LKArthas** [comment]
Fixed
