### ISSUE TITLE
[Arthas] - Quest: Remove Their Arms

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#1282]
**Links:**
https://www.wowhead.com/quest=25713/remove-their-arms
https://www.wowhead.com/object=203707/okrillon-weapons-crate
from WoWHead or our Armory

**What is happening:**
Can't interact with the crates.

**What should happen:**
Should be able to interact and loot them.

**Comment by LKArthas** [comment]
Thats not the quest that you should throw a grenade to the boxes???

**Comment by Serithul** [comment]
Update: The quest works but you can use the grenade on the same crate up to 3 times before it despanws.
