### ISSUE TITLE
[Arthas] - In the Outhouse quest bug

### ISSUE THREAD

**Issue by GhostySimon** [GuabinaCore/WoWKoi#1284]
**Links:**

https://www.wowhead.com/quest=25526/in-the-outhouse

**What is happening:**

The crowbar doesn't work as intended:
![image](https://user-images.githubusercontent.com/63936782/81239784-c4bfd880-8fd3-11ea-894d-434f6f451735.png)

**What should happen:**

Crowbar when used near the outhouse should complete the quest.

**Comment by Serithul** [comment]
Thousand Needles, along with Delosace and Azshara, aren't fully scripted yet.
