### ISSUE TITLE
Maybe a bug or maybe not

### ISSUE THREAD

**Issue by pointaction** [GuabinaCore/WoWKoi#1285]
I played retail World of Warcraft since Vanilla and I normally play Night Elf race.

I noticed after I got done with the starting quests and like I always do in retail version I head to Gold Shire to do the quests there. When I got there, I found that most of the quests were not showing up for me and did like 4 quests and that was all the quests shown up for me.

I had to farm experience by just killing mobs to level up high enough to move to Westfall. I found the same issue in Westfall not many quests to do.

Is this a bug and not many quests show up for me because of being Night Elf?

or

Is this because there no other quests available at this point?

In retail there is a ton of quests in these zones. I left myself at Red Ridge and same thing there to not many quests available.

**Comment by NightwindOI** [comment]
It's intended. If u wonder Why....ask Serithul in our Discord (or just ask around in there, i don't have much info).

**Comment by pointaction** [comment]
Thank you

**Comment by Cefiro-Caecias** [comment]
You must take the quests from the Board, or finish the quest chain from the previous map so that the new quests are unlocked.
