### ISSUE TITLE
[Core] - DK Skill Bug

### ISSUE THREAD

**Issue by ShadowhunterKoi** [GuabinaCore/WoWKoi#1286]
**Links:**
https://www.wowhead.com/spell=53344/rune-of-the-fallen-crusader
https://www.wowhead.com/spell=62158/rune-of-the-stoneskin-gargoyle

**What is happening:**

The Runes are not avalible for runeforging.

**What should happen:**
DK should be able to use all 3 of his runes at the start or the game.

**Comment by Serithul** [comment]
They are not supposed to be available from the start. Navigate to the changelog of each one and see the last legion update to them, Fallen crusader is at level 70 and gargoyle at level 72.

**Comment by Thordekk** [comment]
Issue duplicated
