### ISSUE TITLE
[Quest] Seasoned Wolf Kabobs got me Honored with Exodar

### ISSUE THREAD

**Issue by Thovia** [GuabinaCore/WoWKoi#1288]
**Links:**
https://www.wowhead.com/quest=26620/seasoned-wolf-kabobs

**What is happening:**
When i turned in the quest to a npc, i got honored with Exodar for some reason.

**What should happen:**
It didnt show me that i got rep for Exodar, so i shouldnt get the rep for that faction.

![image](https://user-images.githubusercontent.com/64737510/81289266-c68aaa00-906e-11ea-80ae-7107fd19f46d.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
