### ISSUE TITLE
DB -- Some neutral mobs showing up aggressive with red health bars and nameplates

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#1291]
**Links:**
![WoWScrnShot_050720_122249](https://user-images.githubusercontent.com/43558040/81319911-60962680-905e-11ea-9e80-15c294876173.jpg)

https://wow.gamepedia.com/Goretusk

**What is happening:**
Some neutral mobs showing up aggressive with red health bars and nameplates, saw a boar specifically in Westfall in this bug.

**What should happen:**
It's supposed to have neutral nameplate, tooltip and name since it's a neutral mob.

**Comment by Velthur-bot-3000** [comment]
Hi Sef!

**Comment by Velthur-bot-3000** [comment]
![WoWScrnShot_050720_124933](https://user-images.githubusercontent.com/43558040/81321978-46aa1300-9061-11ea-89d4-4aae110a2c1d.jpg)
Another mob in westfall

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
