### ISSUE TITLE
Blackrock Summoner not scaling properly(too high level) - Redrige

### ISSUE THREAD

**Issue by kenshonski** [GuabinaCore/WoWKoi#1297]
**Links:**
https://i.imgur.com/7DbAZaW.jpg - Normal level mob

https://i.imgur.com/dpTnfQB.jpg - The level every Blackrock Summoner has in Redrige and dealing 1,5k dmg per hit.

from WoWHead or our Armory

**What is happening:**
Blackrock Summoners are too high level in Redridge and are not scaling properly.

**What should happen:**
Should be my level.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. Do not forget to delete the Cache folder of your WoW before entering the game, or you will not see the changes.
