### ISSUE TITLE
[Core] - Spell The "Charge" spell and "Interception"

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#13]
Warrior - protection - Spell
The "Charge" spell and "Interception" spell doesn't work underwater or when falling, it consume one charge and put the spells on cooldown and the mob is aggro'ed but the warrior doesn't move when underwater and stay in place, or just fall on the ground whithout charging when falling (or die from fall damage when falling from high enough). Sometimes, when bumped away by some mobs, charge/intercept won't worek either.
Also, you can use Intercept without having any target and it still consume one charge and give you the rage instead of telling you "I need a target" and denying the use.

**Comment by ShikoSCS** [comment]
Fixed
