### ISSUE TITLE
[Arthas] - Stromgarde Keep house blocked

### ISSUE THREAD

**Issue by taktrix** [GuabinaCore/WoWKoi#1302]
Problem: I was in Arathi Highlands, in Stromgarde keep and there's a house in the back that seems to be designed just like any other house on it's apparently blocked off so you can't enter it.

Solution: Remove the block and implement the full house assets.
![WoWScrnShot_050820_112107](https://user-images.githubusercontent.com/64738413/81420763-710dd600-911e-11ea-9e47-669333ea9e3f.jpg)

**Comment by Cefiro-Caecias** [comment]
This defect can occur when your character is resized by a transformation or mount. There is no invisible wall. Next time try relogging.
