### ISSUE TITLE
Looting permission issue

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#1303]
**Links:**
**What is happening:**
Currently when lotting, in or out of a party, it tells you, "you do not have permissions to loot this item that would be stealing."  Ill assume it a weird loot table issue with multiple bodies? But also noticed it happening when I loot a single mob with just money on the body.

**What should happen:**
Loot as normal with no query saying your not allowed to loot.

**Comment by Cefiro-Caecias** [comment]
This is a strange and annoying bug that is under investigation. Usually relogging is solved. We will look for the cause and remove it.
