### ISSUE TITLE
[Arthas] - Raventusk Village Quest

### ISSUE THREAD

**Issue by taktrix** [GuabinaCore/WoWKoi#1305]
Problem: In the quest is says "speak to Urda if you wish to fly to Raventusk". However Upon speaking to her there is no option to fly to Raventusk nor is there a flightpath to it.

https://www.wowhead.com/quest=26430/revantusk-village

Solution: Include a which chat bubble when speaking to her saying to fly to Raventusk.
![WoWScrnShot_050820_201129](https://user-images.githubusercontent.com/64738413/81458453-798afe80-9168-11ea-8afa-adc6eb2f88f4.jpg)

**Comment by LKArthas** [comment]
fixed
