### ISSUE TITLE
[Core] - Glitched through a wall, fell through the ground, server crashed twice >.<

### ISSUE THREAD

**Issue by emilywoof** [GuabinaCore/WoWKoi#1306]
**Links:**
N/A?
from WoWHead or our Armory

**What is happening:**
Ok im not sure how to do this, but like... I made a worgen, and went and did the first quest, I completed the quest and i guess my key got stuck or something cause i started running at the gate. I glitched through it somehow, and ended up on the other side. After being there, I decided I might as well explore a bit of the area before using the unstuck tool to get back, and i ended up swimming to a lighthouse to see what was over there, and found i could actually swim AROUND an invisible wall there. So i swam over to behind the Queen's Gate and was poking around, looked very unfinished, and i saw a couple holes in the ground. Figured i shouldnt fall through em, so... ignored em. I explored a bit more and set myself on autorun to the north, but when i came back from getting some water i'd fallen through some sort of crack and had fallen through the world or something, as i was dead. I couldn't press "release now", so i waited for it to release me, hoping i would at least end up back in the unfinished zone or something... but after i waited the six minutes, the entire server crashed :V for everyone :V when i logged back in after it was back up, i was still there, still dead, and so i waited again, thinking it might just be a coincidence. It wasnt. The server crashed again. I've decided it'd be best to just delete the character and remake it, so as to not cause further distress on other players >.< they told me to do this.

![image](https://user-images.githubusercontent.com/65062604/81466677-40fb1d00-9188-11ea-8d1a-53b2af5bb572.png)

**What should happen:**
The server probly shouldn't crash >.<

**Comment by Thordekk** [comment]
Fixed
