### ISSUE TITLE
[Scaling] - Mulgore Palemane Poacher

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1308]
**Links:** https://www.wowhead.com/npc=2951/palemane-poacher
from WoWHead or our Armory

**What is happening:**
The scaling is broken. With a level 5 Druid, I face level 36 poachers

**What should happen:** They should scale to level 6.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
