### ISSUE TITLE
[Quest] AHHHHHHHHHHHH! AHHHHHHHHH!!!

### ISSUE THREAD

**Issue by Nikismyname** [GuabinaCore/WoWKoi#1310]
**Links:**
https://www.wowhead.com/quest=26708/ahhhhhhhhhhhh-ahhhhhhhhh

**What is happening:**
When you kill 200 orks, they do not stop spawning when you are out of the vehicle, they kill you and the guy who accepts the quest.

PS: Only happens if you do not complete the quest right away. I like reading the text.

**Comment by LKArthas** [comment]
The mobs at the valley doesnt stop soawning you should foward to encampment ti deliver the quest
