### ISSUE TITLE
[quest] It's Gotta be the Horn

### ISSUE THREAD

**Issue by Nikismyname** [GuabinaCore/WoWKoi#1311]
**Links:**
https://www.wowhead.com/quest=865/its-gotta-be-the-horn

**What is happening:**
The rare monster does not spawn at the given location.

**What should happen:**
He should spawn.

**Comment by Cefiro-Caecias** [comment]
There is no bug present. This mob is in the area, but it is not fixed: it is following a predetermined route, walking in circles around the area. It is a little hard to find, but there it is.
