### ISSUE TITLE
[Achivement] E'ko Madness

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1313]
**Links:**

https://www.wowhead.com/achievement=5443/eko-madness
https://www.wowhead.com/spell=91992/juju-mending
https://www.wowhead.com/spell=93165/juju-chill

**What is happening:**
Bear and the Yeti one was too low rate or not working. Killed like x30 of both and nothing.

**What should happen:**
It must proc at like 15-20 kills.

**Comment by Exlyss** [comment]
I think you were probably just unlucky with those two, I got the achievement without a sweat.

**Comment by LKArthas** [comment]
Yup prob for triggering are 10 % at kill wich is it quite high according to blizz sniff data should be 5% so you are quité unlucky buddy 😁
