### ISSUE TITLE
[Bug]{Technical} Object collision needs to be modified

### ISSUE THREAD

**Issue by taktrix** [GuabinaCore/WoWKoi#1314]
Problem: The object collision as it stands right now is not fully modified correctly which causes things to walk through seemingly solid objects and fall through the ground here are some examples.

Solution: Modify the object collision parameters to be slightly outside the needed range so when something hits them instead of going inside they are pushed outward.

![WoWScrnShot_050920_143423](https://user-images.githubusercontent.com/64738413/81482093-8ceaa800-9202-11ea-816f-399cb3d31da8.jpg)
![WoWScrnShot_050920_143424](https://user-images.githubusercontent.com/64738413/81482095-8f4d0200-9202-11ea-8295-048ed900800d.jpg)
![WoWScrnShot_050920_143425](https://user-images.githubusercontent.com/64738413/81482097-91af5c00-9202-11ea-9ea8-affc82b66f4a.jpg)

**Comment by NightwindOI** [comment]
U mean Vmap not object?

**Comment by taktrix** [comment]
I

> U mean Vmap not object?

Is that what it's called here? I just know the most basic term used for it, if object collision is vmap then yea vmap.

**Comment by Cefiro-Caecias** [comment]
At the moment, there is no possible solution. The defect of the Vmaps is a nuisance with which we must live temporarily.
