### ISSUE TITLE
[Profession] - Archaeology fragments in Winterspring inaccessible

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1315]
**What is happening:**
When in the Owl Wing Thicket Digsite, it is possible for the fragments to become hidden in an area where there is no place to land on, which makes it impossible to collect the artifacts (65.79, 78.18 for near-exact coordinates of where I assume it spawned, which places it under a mountain that you can't land on).

**What should happen:**
This should not be possible at all, as it makes the digsite incompleteable.

**Comment by Thordekk** [comment]
Please try again archeology was rewrited
