### ISSUE TITLE
[Mob] Acidic Swamp Oozes don't aggro at all

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1316]
**Links:**
https://shadowlands.wowhead.com/npc=4393/acidic-swamp-ooze
**What is happening:**
These mobs seem to have no aggro range - I can sit right next to them, and they don't aggro on me.

**What should happen:**
They should have an appropriate aggro range.

**Comment by Macumbino** [comment]
Note: [Bubbling Swamp Oozes](https://shadowlands.wowhead.com/npc=4394/bubbling-swamp-ooze) seem to do the same thing.

**Comment by Macumbino** [comment]
I thought it was working correctly - it still doesn't work.

**Comment by Cefiro-Caecias** [comment]
It is not a bug. We deliberately put them into passive mode, as it became extremely difficult to complete the quest involving them, that they were instantly aggressive.
