### ISSUE TITLE
[Quest] - Blackwood hold quests

### ISSUE THREAD

**Issue by Maximal45** [GuabinaCore/WoWKoi#1317]
**Links:**

1) https://www.wowhead.com/quest=13545/cleansing-the-afflicted

2) https://www.wowhead.com/quest=13572/jadefire-braziers

**What is happening:**

1) Spirits of corruption that are summoned through the quest item are not properly lvl scaled

2) Braziers don't disappear visually when destroyed

**What should happen:**

1) Spirits should be up to your lvl (in my case I was lvl 40 and spirits were lvl 19)

2) Braziers should visually disappear

**Comment by Maximal45** [comment]
Actually braziers do disappear, but only after a very long time, like 1-2 minutes

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
