### ISSUE TITLE
[Core] Mobs that have "Pets" are bugged

### ISSUE THREAD

**Issue by Maximal45** [GuabinaCore/WoWKoi#1318]
**Links:**

**What is happening:**

So, some mobs have a "pet" attached to them, and from my experience all of the "pets" are bugged, they all have a skull for their level (meaning very high) and they dodge or parry almost all attacks due to that. Their HP and Damage values seem to be normal though.

Bugged examples:
https://www.wowhead.com/npc=2070/moonstalker-runt (Moonstalker Matriarch's Pet)
https://www.wowhead.com/npc=40271/tamed-crawler (Greymist Refugee's Pet)

**What should happen:**

They should have an appropriate level scaling.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
