### ISSUE TITLE
[Core] - Died as a spirit

### ISSUE THREAD

**Issue by Maximal45** [GuabinaCore/WoWKoi#1319]
**Links:**

N/A

**What is happening:**

After getting killed by a dragonkin in Bough Shadow in Ashenvale I've been sent to the graveyard, and then instantly died again. (they also have a bad scaling they show up as equal lvl but they killed me in 2 hits) 

**What should happen:**

You shouldn't die a second time

**Comment by Maximal45** [comment]
It happened only once, but still.

Also the spirit healer in Nightsong woods faces away from the player.

**Comment by Thordekk** [comment]
Fixed
