### ISSUE TITLE
[Arthas] - Young and Vicious

### ISSUE THREAD

**Issue by SoonTrademark** [GuabinaCore/WoWKoi#1320]
**Links:**

https://www.wowhead.com/quest=24626/young-and-vicious

**What is happening:**

After escorting Swiftclaw to the raptor pens, I am able to swim into the air. Landing does not seem to fix the issue.
![WoWScrnShot_050920_231736](https://user-images.githubusercontent.com/65105919/81492454-a1539280-924c-11ea-82c9-017c47cf20c6.jpg)
Logging out and back in fixed the issue.

**What should happen:**

**Comment by LKArthas** [comment]
this was fixed closing :)
