### ISSUE TITLE
Turned into a Demon Dog?

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#1325]
**Links:*
**What is happening:**
I went into a Specfic Dung Quee for BRD last night.  We completed the dung and I ported out to where my toon was before, in Light's Hope Chapel.  I noticed that my toon was a Demon Dog, but didn't think anything of it.  logged off for the night, only to return to being a demon dog on this character still. lol

**What should happen:**
ummm, I don't turn into a Demon Dog, nice prank y'all. haha
![WoWScrnShot_051020_120109](https://user-images.githubusercontent.com/43558040/81504528-d8ab5900-92b7-11ea-9ef0-56bb7b1d1aa6.jpg)
![WoWScrnShot_051020_120600](https://user-images.githubusercontent.com/43558040/81504529-da751c80-92b7-11ea-9846-114222c3c30e.jpg)

**Comment by Cefiro-Caecias** [comment]
Solved XD
