### ISSUE TITLE
Through Light's Hope Chapel Floor?

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#1327]
**Links:**

**What is happening:**
If logging out in Light's hope chapel, sometimes it glitches you through the floor to a Sanctum of Light with 110 Silverhand Protectors.  If you continue down the stairs it insta kills you.  I experienced this while in demon dog form so Screenshot is not that great
**What should happen:**
should just log into the lights hope chapel, not on a hidden staircase below the floor.
![WoWScrnShot_051020_122022](https://user-images.githubusercontent.com/43558040/81505154-3beaba80-92bb-11ea-85bd-86a96c4f58ad.jpg)

**Comment by Cefiro-Caecias** [comment]
Down there is the Paladin Class Hall, and anyone who enters it by any means, including GMs in GM mode, will automatically die, until we reach the Legion stage ^^
