### ISSUE TITLE
Mining: Smelt Dark Iron Quest/Skill

### ISSUE THREAD

**Issue by AnastasioTheSexyTauren** [GuabinaCore/WoWKoi#1329]
**Links:**
https://www.wowhead.com/spell=14891/smelt-dark-iron#comments
from WoWHead or our Armory

**What is happening:**

You complete the quest but don't get the skill to smelt dark iron

**What should happen:**
You should get the skill to smelt dark iron in smelting

Screenshot of quest completion
![WoWScrnShot_050820_172618](https://user-images.githubusercontent.com/63824920/81509689-6c8e1c80-92da-11ea-8e43-10d3ead7acd9.jpg)
I didn't get the skill, also tried the same quest on another character w/ mining 300, it didn't work.
![WoWScrnShot_051020_190139](https://user-images.githubusercontent.com/63824920/81512732-baae1a80-92f0-11ea-8f0d-32000bd60226.jpg)

**Comment by AnastasioTheSexyTauren** [comment]
I would like to ask if you can give me the ability to smelt dark iron on the alts that I had completed the quest with. Names "Anastasio", "Zerstrorer".

**Comment by Cefiro-Caecias** [comment]
Quest fixed. Available in the next update.

As you already completed that quest, write me to the Discord when you are online, so with my GM I show you the spell.
