### ISSUE TITLE
[Quest] Got honored with Gilneas with a quest that didnt give gilneas rep.

### ISSUE THREAD

**Issue by Thovia** [GuabinaCore/WoWKoi#1333]
**Links:**
https://www.wowhead.com/quest=24948/lifting-the-siege
from WoWHead or our Armory

**What is happening:**
I turned in Lifting The Siege and got rep for Stormwind and got honored with Gilneas for some reason.

**What should happen:**
I shouldnt get 'rep' with gilneas from Lifting The Siege quest.

![unknown (1)](https://user-images.githubusercontent.com/64737510/81557763-2fd32b80-9395-11ea-8869-c36adbbf0493.png)

**Comment by Cefiro-Caecias** [comment]
Yes, is normal.
