### ISSUE TITLE
[Arthas] - Dungeon - Scholomance

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1334]
**Links:**
https://www.wowhead.com/scholomance
https://www.wowhead.com/npc=58722/lilian-voss

**What is happening:**
Boss fight with Lilian Voss is not starting.

**What should happen:**
After a little chat with Darkmaster Gandling, the fight should start.

**Comment by LKArthas** [comment]
Fixed avaible on next commit
