### ISSUE TITLE
[Core] - Range npc [Visual]

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1336]
**Links:**

https://www.wowhead.com/npc=7155/deadwood-pathfinder

**What is happening:**
Example.
https://streamable.com/i49snt
Range NPC's miss the animation when shooting with bow/crossbow.
Gonna add NPC's ID's at a later point, but at least 90% of them are bugged.

**What should happen:**

**Comment by Thordekk** [comment]
Look creature template addon
