### ISSUE TITLE
[Arthas] - Taking Back Acherus

### ISSUE THREAD

**Issue by Nikismyname** [GuabinaCore/WoWKoi#1337]
**Links:**
https://www.wowhead.com/quest=13165/taking-back-acherus

**What is happening:**
The quest giver dispersal after a while, i teleported with death gate to look for him. He was not there or at least not giving the quest. Now the Plaguelands have fazed and I can not find him there. I have no way to finish the quest line now.

**Comment by Cefiro-Caecias** [comment]
Solved.
