### ISSUE TITLE
[Core] - Wand auto attack

### ISSUE THREAD

**Issue by Torgaun** [GuabinaCore/WoWKoi#134]
**Links:**

from WoWHead or our Armory

**What is happening:**
When casting the Wand auto attack it raises the wand but the cancels and says it was interrupted
(Tested on Mage)

**What should happen:**
You should be able to wand your target as normal

**Comment by daddylongneck123** [comment]
Doesn't always happen, though definitely happens a lot, but sometimes the wand doesnt do any damage at all when auto attacking a mob of similar level (combat log doesnt show anything, so no resist or anything like that)

**Comment by NightwindOI** [comment]
SPELL_ATTR2_AUTOREPEAT_FLAG and 
PROC_FLAG_DONE_RANGED_AUTO_ATTACK is missing.
