### ISSUE TITLE
Zul'Farrak event Breaking and Entering does not start.

### ISSUE THREAD

**Issue by Sabellas2020** [GuabinaCore/WoWKoi#1345]
**Links:**
https://www.wowhead.com/quest=27076/breaking-and-entering
from WoWHead or our Armory

**What is happening:**
Event does not start. Mobs down the stairs do not spawn.

**What should happen:**
Event should commence and the mobs should spawn,

**Comment by Cefiro-Caecias** [comment]
This Dungeons is still under reconstruction. Patience.
