### ISSUE TITLE
[Arthas] - Quest Rocket Rescue

### ISSUE THREAD

**Issue by Maximal45** [GuabinaCore/WoWKoi#1346]
**Links:**

https://www.wowhead.com/quest=25050/rocket-rescue

**What is happening:**

The quest was going OK (the bomb hitbox is kinda meh) but I managed to finish it, upon the rocket returning me back, It gave a parachute (assuming I would slowly fall down) but I just stuck in place midair, I couldn't do anything, so I alt-f4 the game, when I logged back in, I was in the middle of nowhere.
![2020-05-12_14-58-21](https://user-images.githubusercontent.com/64925504/81689563-139dc000-9463-11ea-8479-6ddcd62b08dc.png)
![2020-05-12_15-01-59](https://user-images.githubusercontent.com/64925504/81689579-17314700-9463-11ea-8057-d57889c0f97f.png)

**What should happen:**

You should descent down after the rocket brings you back

**Comment by Maximal45** [comment]
Another person have had the same experience, so It's definitely a confirmed bug.
Good luck with fixing, appreciate your work!

**Comment by jgoret** [comment]
I just got the exact same problem, thanks @Sefrenia-Caecias for the help!
