### ISSUE TITLE
[quest] the battle for the ebon hold

### ISSUE THREAD

**Issue by Nikismyname** [GuabinaCore/WoWKoi#1348]
**Links:**
https://www.wowhead.com/quest=13166/the-battle-for-the-ebon-hold
**What is happening:**
I can not cast spells with buff this quest gives you, obliterate says nothing to dispel. Frost spec. Long story I got the quest from a gm, so the problem might be something else.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
