### ISSUE TITLE
Acherus Portal to Stormwind

### ISSUE THREAD

**Issue by Nikismyname** [GuabinaCore/WoWKoi#1352]
Causes  dying of fall damage. I know an issue like that was already closed but it happened to me, it worked fine the first use for the quest to go to Stormwind to talk with Varian, but next time when it teleports you in mage tower you die of fall damage.

**Comment by Serithul** [comment]
Have you cleared your cache folder recently ? If not, that might be the case. The cache folder messes with the application of the fixes.

**Comment by Nikismyname** [comment]
It was fine the second time I went through, I will clear the cache more regularly then.

**Comment by Cefiro-Caecias** [comment]
I tried it a thousand times, and I never died. It only remains for me to think that the problem is not the portal, but the cracking times of your PC / internet, which takes longer to load the stormwind textures, and for that reason you fall into the void and die.
