### ISSUE TITLE
[Core] [NPC AI] Blink

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1354]
**Links:**

https://www.wowhead.com/npc=7115/jaedenar-adept

**What is happening:**
This NPC is just an example, but still.
If the NPC has a Blink and Fireball(or other spells). If u silence the Fireball, he starts moving to male attack u and just before reaching you...it blinks over you.

**What should happen:**
He must use blink to reach you IF it's silenced and suppose to male you.
PS: That NPC not suppose to have Blink at all in Legion.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
