### ISSUE TITLE
Quest The Battle for Ebon Hold

### ISSUE THREAD

**Issue by Icebeam666** [GuabinaCore/WoWKoi#1357]
**Links:**

https://www.wowhead.com/quest=13166/the-battle-for-the-ebon-hold

**What is happening:**

Whenever I try to use any offensive spell I get the error "Nothing to dispel"

**What should happen:**

My spells should work like they normally do
![WoWScrnShot_051420_000202](https://user-images.githubusercontent.com/65196200/81871427-0e7e6500-9578-11ea-961a-a2ae7b753f27.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
