### ISSUE TITLE
[Core] - Guild Achievements "It All Adds Up", "Critter Kill Squad" and "Now That's an Achievement"

### ISSUE THREAD

**Issue by Lamvince** [GuabinaCore/WoWKoi#1360]
Links:
https://www.wowhead.com/achievement=4913/it-all-adds-up
https://www.wowhead.com/achievement=5144/critter-kill-squad
https://www.wowhead.com/achievement=5198/now-thats-an-achievement

What is happening: Counter is not increasing with corresponding activity.

What should happen: Counter increases with corresponding activity.

**Comment by Thordekk** [comment]
Achievement system was rewrited need test and wait untill we update the core systems
