### ISSUE TITLE
[Core] - Dk-unholy-runic corruption 

### ISSUE THREAD

**Issue by Theadon45** [GuabinaCore/WoWKoi#1362]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/spell=51462/runic-corruption
**What is happening:**
Spending runic power doesn't activate runic corruption 

**What should happen:**
Spending runic power should proc the passive skill runic corruption

**Comment by Serithul** [comment]
Duplicate of https://github.com/GuabinaCore/WoWKoi/issues/963
