### ISSUE TITLE
[Core] - Dk-unholy-scourge strike

### ISSUE THREAD

**Issue by Theadon45** [GuabinaCore/WoWKoi#1364]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/spell=55090/scourge-strike
**What is happening:**

Scourge strike hits all enemies without death and decay present 

**What should happen:**
Scourge strike must hit one enemy, only doing aoe if death and decay is present

**Comment by Serithul** [comment]
Duplicate of https://github.com/GuabinaCore/WoWKoi/issues/955
