### ISSUE TITLE
[Arthas] - Able to spawn several John J. Keeshan's in Chiselgrip, the Heart of the Steppes Quest

### ISSUE THREAD

**Issue by Thovia** [GuabinaCore/WoWKoi#1368]
**Links:**
https://www.wowhead.com/quest=28184/chiselgrip-the-heart-of-the-steppes
from WoWHead or our Armory

**What is happening:**
Im able to spawn as many John H. Keeshan's as i want to, by
1. Aggro mobs while mounted, having the quest and having john j keeshan follow you
2. When mobs are aggrod, have john attacking them, and just keep running away
3. A 2nd john should spawn near you
4. Have the 2nd john attack the mobs, by going to the mobs that you originally aggrod, the 2nd john should start attacking them too.
5. Repeat step 2 untill satisfied
6. Kill the mobs that the johns are attacking and you should have a army of them.

**What should happen:**
I shouldnt be able to have a army of johns.

**Comment by Thovia** [comment]
![bug](https://user-images.githubusercontent.com/64737510/81938850-2dbfd580-95fe-11ea-94d4-62d613831d26.png)

**Comment by NightwindOI** [comment]
Already reported/its global issue with all quests that work like that.
https://github.com/GuabinaCore/WoWKoi/issues/1252
