### ISSUE TITLE
[Profession] Silverleaf plants should not be underwater

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1369]
**Links:**
https://classic.wowhead.com/item=765/silverleaf

**What is happening:**
In Tirisfal Glades (48,56), there are Silverleaf plants underwater.

**What should happen:**
The Silverleaf plants should not spawn in the lake, but around it.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
