### ISSUE TITLE
[Quest] Send A Message

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#137]
**Links:**
https://www.wowhead.com/quest=24929/send-a-message

**What is happening:**
The Send a Message's map completion location is shown on the middle of the village, when it should be to the east of the Oomlot village. However, when you get closer to the actual quest marker than to the village, it seems to be corrected.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
