### ISSUE TITLE
[Core] - Spell - Judgment

### ISSUE THREAD

**Issue by Majeran0** [GuabinaCore/WoWKoi#1370]
**Links:**

https://www.wowhead.com/spell=231663/judgment

**What is happening:**

Judgment rank 3 passive debuff is not applied on spell hit.
Targets do not take increased damage.

**What should happen:**

Targets hit by judgement should get debuff.

**Comment by Velthur-bot-3000** [comment]
I believe that was post 8.0.1 I could be wrong though.

**Comment by alekso999** [comment]
@bukowywowwe the 25% is bfa. In legion, judgment rank 3 increases damage taken from holy power spenders by 10% for 8 seconds.

**Comment by Thordekk** [comment]
Need a video of that, i cant see the issue with the spell
