### ISSUE TITLE
Brann Bronzebeard's Lost Letter

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#1373]
**Links:**
https://classic.wowhead.com/item=20461/brann-bronzebeards-lost-letter
https://wow.gamepedia.com/Brann_Bronzebeard%27s_Lost_Letter
**What is happening:**
Brann himself gives you the quest, then you turn it back in for reward.
**What should happen:**
The actual letter should drop off of random hive NPC mobs, you then turn it in to him at his camp.

**Comment by Cefiro-Caecias** [comment]
Deliberately put like this.
