### ISSUE TITLE
[Zone] Ashenvale [MISC] Scale problem.

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1374]
**Links:**

https://www.wowhead.com/npc=33304/spirit-of-gorat
https://www.wowhead.com/npc=33421/gorka
https://www.wowhead.com/npc=33374/brutusk
https://www.wowhead.com/npc=8582/kadrak
https://www.wowhead.com/npc=44414/durak
https://www.wowhead.com/npc=34206/kaldorei-assassin

**What is happening:**
The scale is missing.

**What should happen:**
Suppose to scale till 60.

Will add more till progress true the zone.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. Don't forget to delete the Cache folder from your WoW, or you won't see the changes.

**Comment by NightwindOI** [comment]
Somehow u miss ''Will add more till progress true the zone.'' but ok. I will make a new report if I find more NPCs in there. Ty 👾
