### ISSUE TITLE
[Quest] - Three Little Pygmies and Rockin' Powder

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#138]
**Links:**
https://www.wowhead.com/quest=24945/three-little-pygmies
https://www.wowhead.com/quest=24946/rockin-powder
**What is happening:**
Both these quests' completion locations are incorrect, being at the place where you find the powder for the Rockin' Powder quest, and the bosses at the Three Little Pygmies quest, instead of being in the correct turn-in location.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
