### ISSUE TITLE
[Core] - DK - Frost - Shattering Strikes.

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#1381]
Testing conducted by Hibiki and me.

**Links:**
https://www.wowhead.com/spell=207057/shattering-strikes
https://www.wowhead.com/spell=49143/frost-strike
https://www.wowhead.com/spell=53343/rune-of-razorice
https://www.wowhead.com/spell=51714/razorice
from WoWHead or our Armory

**What is happening:**
Frost Strike consumes 1 to 5 stacks of Razorice and doesn't deal 60% more damage to the target.

**What should happen:**
Frost Strike should consume the Razorice stacks only when they are 5 and it should increase it's damage by 60% if you have chosen Shattering Strikes.

**Comment by Theadon45** [comment]
Talent is working fine for me, both the damage and stack consumption..You have two razor ice rune forges so the game can't keep up with how fast they apply that's all.

**Comment by Serithul** [comment]
@Theadon45 i tested it multiple times, i can consume any number of stacks whilst the damage stays the same.

**Comment by Theadon45** [comment]
This difference happens a lot I presume and in different content/types. I mean today I was trying out some quests in desolace. For me they were bugged, for a guild mate they worked fine. Talent might be off but at least for my dk the stacks are consumed at 5

**Comment by Serithul** [comment]
Have you recently deleted your cache folder on your client ? If not, that messes up a lot of stuff. I clear it on a daily basis and i have the issue mentioned.
