### ISSUE TITLE
[Arthas] - The twilight Skymaster Quest, Thousand Needles

### ISSUE THREAD

**Issue by Williet13** [GuabinaCore/WoWKoi#1390]
https://www.wowhead.com/quest=28098/the-twilight-skymaster

**What is happening:**
Heartrazor Dissappears
Abandoned quest, 2 x, logged, still no Skymaster or Heartrazor.. soon as you accept quest Heartrazor disappears.

**What should happen:**
  | Get a flight from Heartrazor
-- | --
Twilight Skymaster Richtofen dealt with

**Comment by Exlyss** [comment]
I managed to get a flight from Heartrazor after killing Skymaster.

**Comment by NightwindOI** [comment]
Confirmed, its bugged.
PS: The way I did it...Take the quest---> Fly there with the mount. --->kill the npc--->come back and the take the fly again.

**Comment by Williet13** [comment]
Yeah for me the mount would appear and then go away before i could get a ride.

**Comment by alekso999** [comment]
This is still bugged.
