### ISSUE TITLE
[Arthas] - Quest I Think She's Hungry

### ISSUE THREAD

**Issue by Lamvince** [GuabinaCore/WoWKoi#1392]
https://www.wowhead.com/quest=26739/i-think-shes-hungry

What is happening: Lashtail Hatchling takes 40 bites from the crystal spine basilisk, instantly completing the quest

What should happen: Lashtail Hatchling should only eat 4 times from basilisk corpses, only increasing the count for "basilisks of meat" by 4 each time a basilisk is killed.

**Comment by Kobasun** [comment]
The Lashtail Hatchling actually eats 40 bites at once from any killed animal, a Young Panther in my case, which is also wrong.
