### ISSUE TITLE
[Arthas] - Translation Quest Desolace- Horde

### ISSUE THREAD

**Issue by Williet13** [GuabinaCore/WoWKoi#1393]
https://www.wowhead.com/quest=14189/translation

**What is happening:**
No ride on dragnonhawk, after speaking to  Narimar ( the Flight Master) to quest area

**What should happen:**
Dragonhawk should fly you to quest area, it locks and does not move.

**Comment by Cefiro-Caecias** [comment]
The Desolace and Azshara maps are still under repair, at 50%. Patience.
