### ISSUE TITLE
Firestarter/Quest -Desolace 

### ISSUE THREAD

**Issue by Williet13** [GuabinaCore/WoWKoi#1394]
**Links:**
https://www.wowhead.com/quest=14196/firestarter

**What is happening:**
Gem does not summon Wispy Vortex
**What should happen:**

Vortex GemItem Level 1Quest Item
Use: Summons a Wispy Vortex, which will grow as Disciples of Elune are defeated in its proximity. (3 Sec Cooldown)

**Comment by Cefiro-Caecias** [comment]
The Desolace and Azshara maps are still under repair, at 50%. Patience.
