### ISSUE TITLE
[npc] Young Panther Missing

### ISSUE THREAD

**Issue by Nikismyname** [GuabinaCore/WoWKoi#1398]
**Links:**
https://classic.wowhead.com/npc=683/young-panther

**What is happening:**
Panthers are missing. Probably not respawning like the Lashtail Raptor.

**Comment by NightwindOI** [comment]
U looking classic Map.
They are at another place in Legion https://www.wowhead.com/npc=683/young-panther

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
