### ISSUE TITLE
[NPC] Ringo ID: 9999

### ISSUE THREAD

**Issue by PHO3NIZ** [GuabinaCore/WoWKoi#1399]
**Links:**

https://www.wowhead.com/npc=9999/ringo

**What is happening:**
The quest accept pop-up is not appear. While hovering the mouse to Ringo, the cursor turn to golden hand.

**What should happen:**
The quest accept pop-up must be appeared.

**Comment by LKArthas** [comment]
This quest is working you see that because another player Took the quest and didn't Wale up ringo
