### ISSUE TITLE
[Quest] - Repel the Paratroopers, The Heads of the SI:7, Mine Disposal, the Goblin Way, and The Pride of Kezan

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#140]
**Links:**
https://www.wowhead.com/quest=25024/repel-the-paratroopers
https://www.wowhead.com/quest=25093/the-heads-of-the-si-7
https://www.wowhead.com/quest=25058/mine-disposal-the-goblin-way
https://www.wowhead.com/quest=25066/the-pride-of-kezan
**What is happening:**
These quests' turn-in locations on the map are incorrect, however, they fix themselves upon approaching the quest turn-in NPC.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
