### ISSUE TITLE
Quest - Carcass Collection

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1407]
**Links:**
https://www.wowhead.com/quest=25672/carcass-collection

**What is happening:**
One carcass can be looted multiple times by spamming right click on it, allowing one to finish the quest with just the first carcass.

**What should happen:**
Each carcass should despawn after being looted (it does) and the player shouldn't be able to continue looting it after doing it once.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
