### ISSUE TITLE
[Core] - Archaeology - Moving while crafting 

### ISSUE THREAD

**Issue by alekso999** [GuabinaCore/WoWKoi#1408]
**Links:**

from WoWHead or our Armory

**What is happening:**

If you move your character while crafting an archaeology item, it cancels the crafting process like it should, but also uses up the fragments that are required to make it and that shouldn't happen.

**Comment by yo931** [comment]
just happened to me i lost 100 dwarf fragments im just wondering if a GM can give that back lol was like 3 hours of farming
