### ISSUE TITLE
[Arthas] - Quest - That Smart One's Gotta Go

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1409]
**Links:**
https://www.wowhead.com/quest=28048/that-smart-ones-gotta-go
https://www.wowhead.com/npc=47389/hive-controller

**What is happening:**
The quest is impossible to do alone as the NPC needed to kill can use mind control, blocking every movement and while you're charmed he heals up to full health. The spell lasts 13 seconds but he can cast it after 3 or 5 after it has ended, making the NPC impossible to kill alone.

**What should happen:**
I believe the NPC should not be able to use this spell so frequently, or alternatively when the player is charmed, you shouldn't exit combat so the NPC can't heal up.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
