### ISSUE TITLE
Darnassian Scout missing texture.

### ISSUE THREAD

**Issue by Mfvcker** [GuabinaCore/WoWKoi#1412]
Wowhead link : https://www.wowhead.com/npc=15968/darnassian-scout
The npc's texture is missing.
![WoWScrnShot_051920_210702](https://user-images.githubusercontent.com/65628240/82378919-8daae780-9a15-11ea-9cb0-fd25ff83bedb.jpg)

**Comment by Cefiro-Caecias** [comment]
It is not a bug, it is a download error from your client, very common when using the Minimal version.
