### ISSUE TITLE
[Arthas] - Quest Into the Black Tooth Hovel

### ISSUE THREAD

**Issue by Lamvince** [GuabinaCore/WoWKoi#1413]
https://www.wowhead.com/quest=28239/into-the-black-tooth-hovel
Burning Steppes quest

What is happening: First time disguise is used, casting bar appears but nothing happens. Second time onward, games says "you can't do that yet" despite the one second cooldown.

What should happen: Using the disguise should show a casting bar followed by gaining a buff saying the character is in disguise. A mask should appear over the character's face.

**Comment by LKArthas** [comment]
This is working tested at relog
