### ISSUE TITLE
Manhunt - Missing "The Collector"

### ISSUE THREAD

**Issue by Mfvcker** [GuabinaCore/WoWKoi#1415]
Wowhead quest link : https://www.wowhead.com/quest=147/manhunt

**What is happening:**

After using my Taunt abillity on "The Collector" he got into evade bug. Then i hearthstoned away and came back and the npc was missing for good. I have killed the two other npcs in the house a bunch of times, but the quest one didn't show up since the first attempt.

**Comment by Cefiro-Caecias** [comment]
The general "evade" problem is under review. Patience ;)
