### ISSUE TITLE
[Arthas] - Furlbrow's Deed, npc's dissappearing

### ISSUE THREAD

**Issue by Mfvcker** [GuabinaCore/WoWKoi#1416]
WOWHEAD LINK : https://www.wowhead.com/quest=184/furlbrows-deed

**What is happening:**
![WoWScrnShot_052020_102933](https://user-images.githubusercontent.com/65628240/82436344-347a9c80-9a85-11ea-8596-3aaad4910422.jpg)

Upon completing the quest "Furlbrow's Deed", the other npc's nearby which i had quest to turn in to, dissapear. Problem seems to be resolved my doing a relog.

**Comment by Maximal45** [comment]
They are actually moved to the sentinel hill I think, because of the phasing
