### ISSUE TITLE
[Core] - "Power word: shield" problem

### ISSUE THREAD

**Issue by Tikomiuss** [GuabinaCore/WoWKoi#1417]
**Links:**

from WoWHead or our Armory

**What is happening:**
"Power word: shield" do not block damage almost at all, either showed numbers are incorrect, or its downgraded for "reasons unknown" that its blocks like barely 1 any auto from monster of your level(starting at level 10+), i am not a programmer but pretty sure that is not how this spell supposed to work, maybe its got bugged after last update idk.

**What should happen:**
simply block that amount damage that number shows or even barely close to the number would be awesome.

**Comment by Tikomiuss** [comment]
i just saw it was submitted before but havent fixed yet, sometimes its hard to play priest knowing that "Power word: shield" doesnt work, this spell kinda useful thing to have.

**Comment by Thordekk** [comment]
Fixed need test when server apply corrections
