### ISSUE TITLE
[Arthas] - Quest Be Raptor

### ISSUE THREAD

**Issue by Nikismyname** [GuabinaCore/WoWKoi#1418]
**Links:**
https://www.wowhead.com/quest=26775/be-raptor

**What is happening:**
After the quest is done [excellent scripting btw], when you are moved back to your body you die of fall damage.

**Comment by NightwindOI** [comment]
that must be new. I had 0 problems with that quest.

**Comment by LKArthas** [comment]
Thats weird Will check
