### ISSUE TITLE
[NPC] Astranaar Thrower [MISC] Scale

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1419]
**Links:**

https://www.wowhead.com/npc=34132/astranaar-thrower

**What is happening:**
Don't scale.

**What should happen:**
Suppose to scale till 60.

**Comment by Cefiro-Caecias** [comment]
Fixed https://www.wowhead.com/npc=34492/astranaar-thrower. Available in the next update.
