### ISSUE TITLE
[Core] - Winterfall Pathfinders don't have firing animations

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#1422]
**Links:**
https://www.wowhead.com/npc=7442/winterfall-pathfinder
**What is happening:**
Winterfall Pathfinders don't have firing animations.

**What should happen:**
Winterfall Pathfinders should have firing animations, and the projectile they shoot should be visible.

**Comment by NightwindOI** [comment]
Confirm. Its a problem with other NPC's too.
