### ISSUE TITLE
[Core] - Talent Ray of Frost

### ISSUE THREAD

**Issue by Plagadins** [GuabinaCore/WoWKoi#1423]
**Links:**

https://www.wowhead.com/spell=205021/ray-of-frost#changelog
https://wow.gamepedia.com/Ray_of_Frost

from WoWHead or our Armory

**What is happening:**

It doesnt have cooldown so it can be spawmed no stop.

**What should happen:**
Have a 1 minute cooldown

Ray of Frost
Level 15 Frost mage talent
40 yd range
1 min cooldown
Channeled
For the next 10 sec, you can channel a beam of icy power at an enemy, slowing movement by 50% and dealing (230% of spell power) Frost damage every 1 sec. Each time Ray of Frost deals damage, its damage increases by 20%.

**Comment by Icebeam666** [comment]
This is incorrect, ray of frost does have a cooldown.

**Comment by DeltaVortex** [comment]
you can retarget an npc and cast ability again right before it ends and it will do a full cast again.

**Comment by Icebeam666** [comment]
That is true, the spell is very buggy but it does go on cooldown
