### ISSUE TITLE
[Core] - Clean Up Bags doesnt work

### ISSUE THREAD

**Issue by solini123** [GuabinaCore/WoWKoi#1429]
**What is happening:**
When you click on the button is bags "Clean Up Bags" it doesn't sort your items.

**What should happen:**
It should sort all items and free space in bags so it doesn't look like a mess

**Comment by Velthur-bot-3000** [comment]
This is a duplicate bug ticket to #94 , please make sure that if there is already a report you can simply add any missing info/links to the original bug tracker post!  Thanks for your time, ill be closing this as it is a dup.
