### ISSUE TITLE
[Core] - Dungeon que-ing

### ISSUE THREAD

**Issue by solini123** [GuabinaCore/WoWKoi#1430]
**What is happening:**
When you have for example 4 ppl in dungeon group already qued for a dungeon and you find 5th player to join, you invite him, your group ofc leaves the que, but the "dungeon eye" is still there and you get bugged so everyone needs to relog to fix it which is really annoying

**What should happen:**
When for example 5th person is invited to a group while your (at the moment) 4 player team is qued for dungeon finder, your team should be removed from que ("the dungeon eye" should disappear and you can now reque 5 ppl normally).

Please fix this. It's one of the most essential things to be fixed and it's rly anoying

**Comment by Winkoo6** [comment]
The team doesn't need to be removed, at least the 5th member can join alone to the dungeon finder, and the system will pair 4 of you and he as the 5th member, the calling will pop, and all of you can enter the dungeon together. (If 4 of you was in the queue, and you still waiting, that means nobody else was in the queue, so if the 5th member join anywhere on any way, he will paired immedietly with that 4 in the queue)
But the queue leaving needs to be repaired, thats true. We can't leave the queue, if we joined there. Even if you finished the dungeon only the logout can leave the queue.
