### ISSUE TITLE
[Arthas] - Quest Backdoor Dealings

### ISSUE THREAD

**Issue by Nikismyname** [GuabinaCore/WoWKoi#1431]
**Links:**
https://www.wowhead.com/quest=26809/backdoor-dealings

**What is happening:**
I was in druid travel form when I put the incense. When I did, I saw the flying thing go, but I was not it. Then I walked to the place and completed the quest. Then I was teleported where I put the incense.

**What should happen:**
If I remember correctly, you should become the flying thing and spy through it's eyes, not walk there yourself.

**Comment by LKArthas** [comment]
Fixed
