### ISSUE TITLE
Quest-Wetter than Wet

### ISSUE THREAD

**Issue by solini123** [GuabinaCore/WoWKoi#1432]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=14264/wetter-than-wet

Changing into Naga works. Servants of Neptulon exist but even when you kill them you don't get progress. And every time you attack it in Naga form your naga form is removed.

**Comment by LKArthas** [comment]
Tested this yesterday and works good, seems to be a Linux compilation issue that we're working on it
