### ISSUE TITLE
[Core] - Dungeon Deserter

### ISSUE THREAD

**Issue by Sithis-koi** [GuabinaCore/WoWKoi#1433]
**Links:**

from WoWHead or our Armory

**What is happening:**
When I finish a dungeon with my guild group through Dungeon finder, I leave the instance group and I get Deserter

**What should happen:**
After finishing a dungeon through RDF tool, I shouldn't get Deserter

**Comment by Exlyss** [comment]
Already reported in threads #154 and #649. The only known way to solve this at the moment is to teleport out of the dungeon and then relog while still being inside the group, as logging out will result in automatically leaving the group without getting the Deserter Debuff.

**Comment by Thordekk** [comment]
Closed duplicated issue
