### ISSUE TITLE
Fradd Swiftgear Store is Empty

### ISSUE THREAD

**Issue by Lamvince** [GuabinaCore/WoWKoi#1434]
https://www.wowhead.com/npc=41435/fradd-swiftgear

What is happening: The store interface is empty.

What should happen: Should be stocked with items.

**Comment by Lamvince** [comment]
This only occurs if the store NPC is also a questgiver. The glitch will only happen after handing in a quest.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
