### ISSUE TITLE
Wetter than wet

### ISSUE THREAD

**Issue by Theadon45** [GuabinaCore/WoWKoi#1435]
**Links:**
https://www.wowhead.com/quest=14264/wetter-than-wet
from WoWHead or our Armory

**What is happening:**
So I was trying to do desolace quests and on the Naga chapter after obtaining the charm Naga for kept breaking when I used any Naga skill.. So I decided to destroy the amulet, relog and delete cache in order to take the amulet again from the Tauren. When I logged back in the Tauren didn't give me anything.. Kept trying everything I could and nothing happens

**What should happen:**
Naga for shouldn't break when using Naga skills and Tauren should give the amulet back

**Comment by LKArthas** [comment]
This issue is duplicated and quest works good seems like to be a global issue between Linux compilation and local Windows compilation thats why is failing on love server, but quest overall works withouth issue, when the incompatibilty between Linux and win compilations are solved this Will be too
