### ISSUE TITLE
[Quest] Watch Your Step

### ISSUE THREAD

**Issue by jgoret** [GuabinaCore/WoWKoi#1436]
**Links:**

https://www.wowhead.com/quest=14296/watch-your-step
https://www.youtube.com/watch?v=gEv1rXT0kJ8

**What is happening:**

We can get the "Energized" buff without a problem but the jump boosters needed to help us get to the top of the mountain are not spawned.

**What should happen:**

Jump boosters should appear before each big jump so we can get to the top (see the youtube video for a full quest progression).

**Comment by LKArthas** [comment]
This is fixed but not yet commited until the 3 trials quests are commited
