### ISSUE TITLE
[Core] - Guild Bank - Invisible Tab

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1437]
**What is happening:**
When I have the addon Bagnon active, I can't see the last tab from GBank.

**What should happen:**
I should be able to see and interact with it.

![WoWScrnShot_052220_124149](https://user-images.githubusercontent.com/64436148/82661034-8eb56200-9c2b-11ea-83fc-70afa536c845.jpg)
![WoWScrnShot_052220_124212](https://user-images.githubusercontent.com/64436148/82661066-9d037e00-9c2b-11ea-8676-36a149773ba3.jpg)

**Comment by Thordekk** [comment]
Addon problem
