### ISSUE TITLE
[Quest] What Kind of Name is Chip, Anyway?

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#144]
**Links:**
https://www.wowhead.com/quest=25203/what-kind-of-name-is-chip-anyway
**What is happening:**
The quest turn-in is in the incorrect spot, being at the place where you kill Chip instead of the place where you meet with Ace.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
