### ISSUE TITLE
[Core] - Guild tabs dont work

### ISSUE THREAD

**Issue by solini123** [GuabinaCore/WoWKoi#1442]
**Links:**

Guild tabs:
-Guild Status : works
-Player Status : works
-Achievement points: works only for online players and for offline players displays 0 ach points
-Professions : Doesn't work at all.
-Guild Reputation : Doesn't work at all (says neutral to everyone)

**Comment by antonioyu0505** [comment]
It would help if you could be more specific regarding the professions because it is not easy to pinpoint the problems regarding these without more details.

**Comment by Thordekk** [comment]
System is being rewrited most of guild bugs are fixed
