### ISSUE TITLE
[Core] - Rogue Spell: Roll the bones - leach doesn't work

### ISSUE THREAD

**Issue by solini123** [GuabinaCore/WoWKoi#1443]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/spell=193316/roll-the-bones

**What is happening:**
Whenever I get Leach/Attack Speed buff from RLD spell, only the attack speed part works. Leach doesn't

**What should happen:**
Leach should work.

**Comment by antonioyu0505** [comment]
Duplicate of #893.
