### ISSUE TITLE
Quest: The Ballad of Maximillian

### ISSUE THREAD

**Issue by solini123** [GuabinaCore/WoWKoi#1444]
**Links:**
from WoWHead or our Armory
https://www.wowhead.com/quest=24707/the-ballad-of-maximillian

Quest doesn't work because once you accept the quest Maximillian disappears immediately.

**Comment by antonioyu0505** [comment]
Keep in mind that you have to be dismounted in order to start the cinematic, which I think is a bug, as it should dismount automatically. Try it again after dismounting and see if it works.

**Comment by LKArthas** [comment]
Yup dismounts should work anyways the new function for auto dismount is now added si Will be fix those issues on all relates quests soon

**Comment by LKArthas** [comment]
Fixed avaible on next update
