### ISSUE TITLE
Un'Goro crater quests don't exist

### ISSUE THREAD

**Issue by solini123** [GuabinaCore/WoWKoi#1445]
**Links:**

I cant mention all of the quests but so many quests in Un'Goro are missing. Please check the list of the quests on YT and you'll see there are so many quests missing in for example Marshal Stand area.

Also there's a quest in Tanaris located at Gunstan's Dig flightpath which is connected to the Valley of the Watchers that requires you to retrieve 5 gems from those white dwarf statues inside the tomb (Valley of the Watchers) and that quest is also missing.

**Comment by antonioyu0505** [comment]
I'm not sure about that, I have the completion achievement of both zones. Keep in mind that you have to do every single quest that you come across in a zone in order to progress, in the case of Tanaris, you must finish every quest related to Gunstan's Dig before moving on to Valley of the Watchers.

**Comment by NightwindOI** [comment]
Quest's existing and they work just fine. The ''problem'' is they are ''locked'' behind the quest chain that starts from the pre-zone or the board.
