### ISSUE TITLE
[Arthas] - Quest Jin'Zil's Blessing

### ISSUE THREAD

**Issue by Majeran0** [GuabinaCore/WoWKoi#1447]
**Links:**

https://www.wowhead.com/quest=26067/jinzils-blessing

**What is happening:**
Quest progress does not increase after empowering Krom'gar Marauder

**Comment by Dawbra** [comment]
Same here for me using an item gives the proper buff but it wasn't count to the quest

**Comment by LKArthas** [comment]
Fixed one more time ;)
