### ISSUE TITLE
[Arthas] - A Love Eternal

### ISSUE THREAD

**Issue by KKAWOW** [GuabinaCore/WoWKoi#1453]
**Links:**

https://www.wowhead.com/quest=13563/a-love-eternal

**What is happening:**

As a hunter when first attacking Anaya Dawnrunner she becomes hostile.  But when she kills your pet she becomes neutral and you are unable to attack her.  She evades all further shots.  You must abandon the quest, and dismiss your pet in order for her to stay hostile to kill her and get the amulet.

**Comment by LKArthas** [comment]
Fixed
