### ISSUE TITLE
[Arthas] - The warden's game

### ISSUE THREAD

**Issue by Michael-0-Jordan** [GuabinaCore/WoWKoi#1455]
**Links:**https://www.wowhead.com/quest=27885/the-wardens-game

from WoWHead or our Armory

**What is happening:** when you click the little golem they are not moving like they are supposed to, they are moving into each other and not to an open spot on the board.

**What should happen:** this video is what should happen when you click the golems https://www.youtube.com/watch?v=MxJ9M_RZ0G4

**Comment by NightwindOI** [comment]
Already reported
https://github.com/GuabinaCore/WoWKoi/issues/1207
