### ISSUE TITLE
[Quest] Tanaris is Calling

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1458]
**Links:**

https://www.wowhead.com/quest=27447/tanaris-is-calling

**What is happening:**
The phase is bugged so u cant see the npc's

After relog mobs are there.

**What should happen:**
https://www.youtube.com/watch?v=MEGqSUt2jf0&feature=emb_title

**Comment by Cefiro-Caecias** [comment]
Fixed.
