### ISSUE TITLE
[Core] - Pet battle

### ISSUE THREAD

**Issue by Michael-0-Jordan** [GuabinaCore/WoWKoi#1460]
**Links:**

from WoWHead or our Armory

**What is happening:** Nothing I think.

**What should happen:**when my pet is going against a critter he should get increased damage and it should say (strong) because the attack is strong against the critter. and then do that on all the pets :/ and then put in (weak) for the ones that attack is against a weak element

**Comment by Thordekk** [comment]
Its visual bug on it
