### ISSUE TITLE
[Scaling] - Windfury Zombie

### ISSUE THREAD

**Issue by Maximal45** [GuabinaCore/WoWKoi#1462]
**Links:**

https://www.wowhead.com/npc=38909/sandfury-zombie#comments

**What is happening:**

There's two types of this NPC (you can check the comment on the WoW head)
So the ones that spawn naturally have the proper scaling and are lvl 61
While the ones summoned from the "Shallow Grave" object do not scale and are lvl 46

**What should happen:**
NPCs summoned by interacting with the "Shallow Grave" should scale properly

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
