### ISSUE TITLE
Treasure chest with lots of rare items

### ISSUE THREAD

**Issue by eddy1323** [GuabinaCore/WoWKoi#1463]
**Links:**
https://classic.wowhead.com/maps?data=45:354572

**What is happening:**
found a treasure chest with 15 rare items. some of the items have level requirements of level 62, 63, 67 and 70. other items level are from 16 to 44. i'll provide links for the higher level items that i found in the treasure chest.

https://www.wowhead.com/item=31305/ceds-carver
https://www.wowhead.com/item=31303/valanos-longbow
https://www.wowhead.com/item=31306/leggings-of-the-sacred-crest
https://www.wowhead.com/item=31275/necklace-of-trophies
https://www.wowhead.com/item=31175/blade-dancers-wristguards
https://www.wowhead.com/item=31145/headdress-of-the-sleeper

edit: silverbound treasure chest. thats the name of the chest.
https://www.wowhead.com/object=207472/silverbound-treasure-chest

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
