### ISSUE TITLE
[Core] - Guild Calendar

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#1464]
**What is happening:**
I got a strange bug when making an event for my guild: as I created the event, stating that it would be done at 4pm, the event in the calendar that appeared to everyone stated that it was at 5pm. The only way to solve this problem is to edit the hour selecting exactly 1 hour before the actual time you want to do the event.

**What should happen:**
Obviously the time set when creating the event should be the same shown to everybody, without having to edit that.

**Comment by Thordekk** [comment]
Calendar was rewrited try now
