### ISSUE TITLE
[Core] - DK Dark Succor/Obliterate

### ISSUE THREAD

**Issue by Majeran0** [GuabinaCore/WoWKoi#1465]
**Links:**

https://www.wowhead.com/spell=178819/dark-succor
https://www.wowhead.com/spell=49020/obliterate

**What is happening:**

Obliterate consumes dark succor buff

**What should happen:**

Obliterate should consume only Killing Machine buff

Dark Succor should only be consumed by Death Strike

**Comment by Theadon45** [comment]
Same happens with scourge strike and festering strike and frost strike
