### ISSUE TITLE
[Arthas] - No Tanks Quest Minor Bug

### ISSUE THREAD

**Issue by JuneEST** [GuabinaCore/WoWKoi#1466]
Im Junely Ingame and June#8507 on Discord add me if more info is needed.
**What is happening:**
You can aggro the Repaired Mechano-Tanks with Frost Nova and when the freeze is over they glitch out and come and follow you around dealing no damage.

**What should happen:**
You Should Not be able to attack the Mechano-Tanks at all. You should only be able to use the Techno Grenade to destroy them.

**Comment by LKArthas** [comment]
Fixed
