### ISSUE TITLE
[Quest] - The Kessel Run

### ISSUE THREAD

**Issue by Maximal45** [GuabinaCore/WoWKoi#1467]
**Links:**

https://www.wowhead.com/quest=9663/the-kessel-run

**What is happening:**

The requirements are in Spanish
![2020-05-29_02-02-19](https://user-images.githubusercontent.com/64925504/83204399-6d390680-a154-11ea-906b-8bfae51a2406.png)

**What should happen:**
They should translated in English

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
