### ISSUE TITLE
[Arhas] - Quest Catch and Release

### ISSUE THREAD

**Issue by Maximal45** [GuabinaCore/WoWKoi#1468]
**Links:**

https://www.wowhead.com/quest=9629/catch-and-release

**What is happening:**

The quest requires to tag the Murloc scouts, **NOT** kill them, currently you have to kill the tagged murloc to get quest credit, which is not how it's supposed to be.

**What should happen:**
You should get the quest credit just by tagging the murlocs not killing them.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
