### ISSUE TITLE
[Achievement] Glutton of Shadowy Punishment ID: 5547

### ISSUE THREAD

**Issue by PHO3NIZ** [GuabinaCore/WoWKoi#1470]
**Links:**

https://www.wowhead.com/achievement=5547/glutton-for-shadowy-punishment

**What is happening:**
The Weeping Souls won't spawn after clicking the start crystal.

**What should happen:**
The Weeping Souls should be spawned from the portal.

**Comment by LKArthas** [comment]
Did you try to move around???

**Comment by LKArthas** [comment]
This works good closing :)
