### ISSUE TITLE
[Quest] Cleansing Our Crevasse ID: 14381

### ISSUE THREAD

**Issue by PHO3NIZ** [GuabinaCore/WoWKoi#1471]
**Links:**

https://www.wowhead.com/quest=14381/cleansing-our-crevasse

**What is happening:**
The quest giver doesn't give this quest after completing [https://www.wowhead.com/quest=14380/an-impactful-discovery](url). By the way, I didn't complete this quest [https://www.wowhead.com/quest=6134/ghost-o-plasm-round-up](url) so I don't know is it make the quest giver give me the quest.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
