### ISSUE TITLE
[Core] - Hidden Shirt Transmog

### ISSUE THREAD

**Issue by Maximal45** [GuabinaCore/WoWKoi#1472]
**What is happening:**

Selecting the "Hidden Shirt option, prevents you from applying transmog
![2020-05-29_20-50-34](https://user-images.githubusercontent.com/64925504/83289810-43342280-a1ee-11ea-82e8-0b0ed5650a64.png)
Clicking Apply does nothing.

**Comment by Thordekk** [comment]
Duplicated report
