### ISSUE TITLE
[Minor] - Chair Tint bug

### ISSUE THREAD

**Issue by Maximal45** [GuabinaCore/WoWKoi#1473]
**What is happening:**

This Chair in Tower of Ilgalar (Redridge Mountains) is blue for some reason.
![2020-05-30_04-33-23](https://user-images.githubusercontent.com/64925504/83316545-10f6e500-a22f-11ea-8241-db960198a6e1.png)

**Comment by Cefiro-Caecias** [comment]
Because that's how it is prettier.
