### ISSUE TITLE
[Core] - Godmode on some players

### ISSUE THREAD

**Issue by MayuzumiSayaka** [GuabinaCore/WoWKoi#1475]
**Links:**

-

**What is happening:**

After the latest restart, as of 31st May, some players do not take damage, basically being granted godmode.

**What should happen:**

Not get godmode, I don't know :^

**Comment by MayuzumiSayaka** [comment]
Update: It may seem that it's only happening to Rogue players, this coming from Monarch and Razorscale on Discord.

**Comment by Razorscale** [comment]
It seems is not only rogues. "Coomer" on discord he takes no damages as mage too
Additional informations : We can have debuffs but we cannot be interrupted while casting

**Comment by Zinumwow** [comment]
I am having the same issue, i cant take damage from npc. I am a paladin

**Comment by MayuzumiSayaka** [comment]
Update: I'm also having the same issue, I'm a Warrior tho.

**Comment by dan2142** [comment]
same issue, it is related to scaling somehow.

**Comment by MayuzumiSayaka** [comment]
Update: What has been said above is most likely true, I fought a level 53 mob as a lv 23, I got decimated in 3 hits.

**Comment by MayuzumiSayaka** [comment]
Update: At level 59, you don't have godmode anymore.
