### ISSUE TITLE
[Arthas] - Quest - Steel Thunder

### ISSUE THREAD

**Issue by Zinumwow** [GuabinaCore/WoWKoi#1476]
**Links:**
https://www.wowhead.com/quest=27069/steel-thunder

**What is happening:**
There is no Sea Dog Crate to recover, so i cant do the quest

**What should happen:** Its self explanatory

**Comment by LKArthas** [comment]
Did you wait the respawn of the crates because the are spawned properly so pheraps someone pass through there and despawn the crates

**Comment by Zinumwow** [comment]
I was there for like 30 minutes and nothing

**Comment by NightwindOI** [comment]
done that quest before a week or so. Was ok back then.
