### ISSUE TITLE
[Quest] Refleshification

### ISSUE THREAD

**Issue by MayuzumiSayaka** [GuabinaCore/WoWKoi#1479]
**Links:**

https://www.wowhead.com/quest=14194/refleshification

**What is happening:**

After finishing the quest (destoning the miners) the quest doesn't mark as complete, so it's a missing flag

**What should happen:**
Quest should be marked as complete, to be able to turn in

**Comment by Cefiro-Caecias** [comment]
Azshara is still under reconstruction, at 50%. Patience.
