### ISSUE TITLE
[Quest] [Item] Gob Squad Flare

### ISSUE THREAD

**Issue by MayuzumiSayaka** [GuabinaCore/WoWKoi#1482]
**Links:**

https://www.wowhead.com/item=49629/gob-squad-flare
https://www.wowhead.com/quest=14485/ticker-required
https://www.wowhead.com/quest=14484/head-of-the-snake

**What is happening:**

The Gob Squad Fire item doesn't work, therefore it is literally impossible to complete Ticker Required and Head of The Snake, the latter being completable cause of the current godmode bug that's happening

**What should happen:**

https://www.youtube.com/watch?v=nTAtIAbkJ60 (Ticker Required)
https://www.youtube.com/watch?v=e4aM4Iycxf4 (Head of The Snake)

**Comment by Cefiro-Caecias** [comment]
Azshara is still under reconstruction, at 50%. Patience.
