### ISSUE TITLE
You cannot create a death knight unless you have a level 55 or more character

### ISSUE THREAD

**Issue by MayuzumiSayaka** [GuabinaCore/WoWKoi#1483]
**Links:**

https://i.imgur.com/v1sgbea.png
https://i.imgur.com/WrhsF5I.png

**What is happening:**

I cannot create a Death Knight unless I have a level 55+ character.

**What should happen:**

I should be able to create a Death Knight, the level requirement has been removed in 2014.

**Comment by LKArthas** [comment]
We're aware of that the disable desition comes to balance the server meanwhile the 1-60 expansion is ser, that requirements Will be removed as soon wotlk patch is released to keep stuff balanced
