### ISSUE TITLE
[Arthas] - Quest The Ballad of Maximillian

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1484]
**Links:**

https://www.wowhead.com/quest=24707/the-ballad-of-maximillian
**What is happening:**
Once u complete it and dismount u go underground
https://imgur.com/a/W1KufRn
It may be Vmap issue, not quest one tho.

**What should happen:**

**Comment by LKArthas** [comment]
Is global vehicle issue depending on the terrain Will check
