### ISSUE TITLE
[Core] - Warrior Heroic Leap

### ISSUE THREAD

**Issue by MayuzumiSayaka** [GuabinaCore/WoWKoi#1485]
**Links:**

https://www.wowhead.com/spell=6544/heroic-leap

**What is happening:**

You can't really use Heroic Leap unless there's like 80% flat surface, in retail you can parkour with this, but here you can't, issue is most likely related to pathing/maps.

**What should happen:**

Be able to jump almost anywhere except on steep places even without a clear flat surface

**Comment by Thordekk** [comment]
Fixed now spell deal damage the pathing is not fixed to prevent bug abuse
