### ISSUE TITLE
Slither blade charm

### ISSUE THREAD

**Issue by Theadon45** [GuabinaCore/WoWKoi#1486]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/item=49064/slitherblade-charm
**What is happening:**
Using any Naga skill keeps breaking Naga form. I tried deleting cache, retaking the amulet and deleting cache but Naga form still breaks

**What should happen:**
You should be able to use your Naga form skills without Naga form failing else it makes all quests completion obsolete

**Comment by Theadon45** [comment]
Update:The Tauren at Ethel rethor doesn't have the dialogue option to give you back the amulet

**Comment by MayuzumiSayaka** [comment]
Can confirm

**Comment by Cefiro-Caecias** [comment]
Fixed.
