### ISSUE TITLE
[Core] - Transmog

### ISSUE THREAD

**Issue by MayuzumiSayaka** [GuabinaCore/WoWKoi#1492]
**Links:**

-

**What is happening:**

Transmog is bugged, you can't change any appearance

**What should happen:**

Transmog working

**Comment by mK2-12** [comment]
transmog is working fine for me is maybe because you have a tabard or shirt equiped i think

**Comment by MayuzumiSayaka** [comment]
I tried making the tabard invisible and changing the appearance of my pants, neither worked

**Comment by mK2-12** [comment]
Tabard and shirt is not working, but all other parts are working, try change the appearance of your pants without changing tabard or shirt appearance.

**Comment by MayuzumiSayaka** [comment]
I guess that worked, but I don't know why not tabard/shirt, anyway, this can be closed or left open, but should prolly fix sometime

**Comment by mK2-12** [comment]
Yea, Tabard and shirt slots need to be fixed.

**Comment by Thordekk** [comment]
Tabard and shirt need new function like legendary npc transmogrifier in Legion blizz change the tmog system
