### ISSUE TITLE
Ashenvale Impossible to continue

### ISSUE THREAD

**Issue by MayuzumiSayaka** [GuabinaCore/WoWKoi#1494]
**Links:**

https://www.wowhead.com/quest=13815/making-stumps
https://www.wowhead.com/quest=13865/wet-work
https://www.wowhead.com/npc=33889/krokk

**What is happening:**

When trying to turn the quests in Krokk is not where he's supposed to be. Pic: https://i.imgur.com/gFmNWn9.jpg

**What should happen:**

He should be besides the bonfire or whatever it is

**Comment by LKArthas** [comment]
You should use the ítem provided to summon the npc newr the brazier
