### ISSUE TITLE
Two If By Boat

### ISSUE THREAD

**Issue by KKAWOW** [GuabinaCore/WoWKoi#1498]
**Links:**
https://www.wowhead.com/quest=25489/two-if-by-boat

**What is happening:**

When activiating the quest you should be put in the boat to travel to the Mirage Raceway.  The boat appears briefly then disapears dumping you in the water.

**What should happen:**

Should be able to travel by boat without being dumped in the water

**Comment by LKArthas** [comment]
Fixed avaible on next update
