### ISSUE TITLE
[Saitama] - Spell Subterfuge

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#15]
Subtlety Rogue talent Subterfuge does not function.
https://es.wowhead.com/spell=108208/subterfugio

**Comment by login6710** [comment]
Fixed

https://github.com/GuabinaCore/TYCE-Group/commit/9d1b834b9a684e0cb3ca72d48046513d395196a5

**Comment by justfortest098** [comment]
i cant use skill during subterfuge like SHADOWSTRIKE. You sure its fixed?
