### ISSUE TITLE
Huntress Davinia's pet Moonshadow scaled wrong

### ISSUE THREAD

**Issue by jgoret** [GuabinaCore/WoWKoi#1500]
**Links:**

https://www.wowhead.com/npc=41864/huntress-davinia
https://www.wowhead.com/npc=43498/moonshadow
 
**What is happening:**

Same as #368 , when you attack Huntress Davinia as a lvl 22 her pet spawns at an unkown lvl and kills you really fast.

**What should happen:**

Moonshadow should scale the same way as Huntress Davinia

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
