### ISSUE TITLE
[Core] - Flight master travel bug

### ISSUE THREAD

**Issue by Kobasun** [GuabinaCore/WoWKoi#1502]
**What is happening:**
When taking a flight between flight masters, sometimes the character doesn't ride a gryphon but makes swimming motions and "swims" through the air (as if being in water) with the gryphon's speed and route. This happens completely randomly in Eastern Kingdoms (at least) approximately 1 flight out of 10 or so. Quite funny, actually, but still a bug :)

**What should happen:**
The character should ride the flight master's beast and not pretend being a Superman learning to fly :)

**Comment by Maximal45** [comment]
This one never happened to me, I suppose this **may** be a case of model not loading quick enough, meaning it's not a serverside problem, but if it stays like that for the whole flight, then it's something different.

**Comment by Kobasun** [comment]
> but if it stays like that for the whole flight

Yes, it's either a normal flight, or an air swim from start to end, the gryphon doesn't appear somewhere at mid-route. Happens quite rarely and randomly, the bug doesn't seem to be connected with a particular flight master or route.

**Comment by Thordekk** [comment]
Issue caused by high latency, or wrong movements now are corrected
