### ISSUE TITLE
Valley of Trials: Felstalker Drain Life

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#1506]
**Links:**

 https://www.wowhead.com/npc=3102/felstalker
https://www.wowhead.com/spell=79619/drain-life
https://www.wowhead.com/spell=79616/drain-life

**What is happening:**
Seems, instead of the Drain Life ability scaling to correct damage amounts, it instead uses full power for the spell/ I believe level 20 spell.

**What should happen:**

When tested on retail now(Level 1 mage, all starter gear.), which might be less then suppose to in legion as well, shows a level 1 felstalker(DB GUID:157913, ENTRY: 3102)  hitting for 3-4 physical, and 1dmg/s for 5 seconds on Drain Life, not a full 50dmg/sec for 5.

THANKS!

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
