### ISSUE TITLE
[Core] - Monk - Brewmaster - Stagger

### ISSUE THREAD

**Issue by JakubMajzlik** [GuabinaCore/WoWKoi#1507]
Links:
https://www.wowhead.com/spell=124255/stagger

What is happening:
1) No matter how big dot dmg you get, you get high level of stagger.

2) When you get dmg, about 78% of received dmg is delayed.

3) If you have stagger debuff and you take dmg, duration of stagger is not refreshed.

4) Unitframe that should display staggered dmg is always empty (tried without addons).
![WoWScrnShot_061120_124701](https://user-images.githubusercontent.com/15659728/84376815-f2ef9400-abe1-11ea-88bc-403d9d3d67cd.jpg)

What should happen:

1) If stagger dot tick dmg > 0% of max hp, stagger should be light; if stagger dot tick dmg > 3% max hp, stagger should be medium; if stagger dot tick dmg > 6% max hp, stagger should be high

2) 40% of received dmg should be delayed

3) If you have stagger debuff and you take dmg, duration of stagger should refresh

4) Unitframe should display staggered dmg

**Comment by Thordekk** [comment]
Its visual bug only we are on it
