### ISSUE TITLE
[Quest] Aid of the Frostwolf

### ISSUE THREAD

**Issue by jgoret** [GuabinaCore/WoWKoi#1510]
**Links:**

https://www.wowhead.com/quest=28587/aid-of-the-frostwolf

**What is happening:**
It seems like [High Warlord Cromush](https://www.wowhead.com/npc=48545/high-warlord-cromush) in Tarren Mills does not give this quest after "[Heroes of the Horde](https://www.wowhead.com/quest=28400/heroes-of-the-horde)".

I don't know if it can have an impact, but I'm playing as a Horde Pandaren

**What should happen:**
Cromush should give the quest which leads to end of Hillsbrad Foothills' storyline

**Comment by Cefiro-Caecias** [comment]
To receive the "Aid of the Frostwolf" quest, you must first complete these quests:

- The Heart of the Matter (28484)
- Yetimus the Yeti Lord (28485)
- Humbert's Personal Problems (28487)
- Stagwiches (28489)
- A Fighting Chance (28495)
