### ISSUE TITLE
Nethergarde Needs You!

### ISSUE THREAD

**Issue by KKAWOW** [GuabinaCore/WoWKoi#1511]
**Links:**

https://www.wowhead.com/quest=28867/nethergarde-needs-you

**What is happening:**

Unable to travel through portal to Blasted Lands from Cenarion Hold in Silithus. 

Constantly told that “You can’t do that yet”

**What should happen:**

Should be teleported to Silithus

**Comment by Velthur-bot-3000** [comment]
I don't want to make it sound like you missed it, but are you making sure to use the correct factions portal? I would assume as your using it after getting the quest line?

**Comment by Cefiro-Caecias** [comment]
Fixed. I had misplaced a usage restriction for Level 58 or higher; modified to Level 40 or higher. Available in the next update.
