### ISSUE TITLE
Cracked Silithid Carapace

### ISSUE THREAD

**Issue by MayuzumiSayaka** [GuabinaCore/WoWKoi#1514]
**Links:**

https://www.wowhead.com/item=5877/cracked-silithid-carapace
https://www.wowhead.com/quest=1148/parts-of-the-swarm

**What is happening:**

Clicking it does not open any quest

**What should happen:**

Should begin the quest: Parts of the Swarm

**Comment by Cefiro-Caecias** [comment]
That item should no longer be dropped, it was removed just like your quest. Fixed, available in the next update. You can already discard it ;)
