### ISSUE TITLE
[MOB] Sharphorn Stag

### ISSUE THREAD

**Issue by Dawbra** [GuabinaCore/WoWKoi#1518]
https://www.wowhead.com/npc=40193/sharphorn-stag
**What is happening:**
![WOWKOI-64bits_2020_06_14_16_59_45_436](https://user-images.githubusercontent.com/3331347/84596872-774f4a80-ae60-11ea-9ba1-12703c70cf72.jpg)

Stags overall not only the one in ferellas Azashara and Ashenvile have that too they like to get run out and lost aggro or be unkillable/reset hp. Its make few quest bit longer to make, to find proper idk spawned mob

**What should happen:**
Every stag should be able to get killed not go stuck/reset after the fight

**Comment by Cefiro-Caecias** [comment]
Fixed Sharphorn Stag. Available in the next update.
