### ISSUE TITLE
[Core] - Talent becomes unusuable

### ISSUE THREAD

**Issue by jakechamberja** [GuabinaCore/WoWKoi#1519]
level 18 protection warrior tauren  name : Jake
addons using : GW2 UI
after level up or sometimes  cooldown , i can't use  shockwave  and it stays gray like i didn't select it in the talents tab
After reloag, shockwave dissapears from my action bar
To fix this i have to go to the rested exp zone and select another talent, then switch back to shockwave,after that i can use shocwave, until i reloag , level up, or sometimes after combat
All this time shockwave looks selected in the talents tab
I have cleared Catche

**Comment by Thordekk** [comment]
Put wowhead link please
