### ISSUE TITLE
[Arthas] - Insane agro range

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#1523]
The server has about double or even more agro range like the normal. For any unexperienced player will quit immedietly from this server, because they can't deal with 2-3 monster. And because of the extremly high agro range, you always pull more than one enemy, you almost can't avoid it.
Also it's nearly impossible to reach the enemy in stealth, because of this insane range, they attack you first, and you can't use your opener in stealth. (even if you try to reach him from behind, because one of the enemy next to him will agro you before you can use your opener skill..)

What is happening:
Decrease the agro range to half for example, it's about the normal range, and let's see how will work that.

**Comment by Velthur-bot-3000** [comment]
Aggro ranges are fine? Actually really close of not on point with blizzlike features. I don’t think I have experienced this same issue as you have.
