### ISSUE TITLE
[Arthas] - The Dawning of a New Day bug

### ISSUE THREAD

**Issue by Allgart** [GuabinaCore/WoWKoi#1524]
**Links:**
https://www.wowhead.com/quest=26297/the-dawning-of-a-new-day
from WoWHead or our Armory

**What is happening:**
The quest says I have to gather information from the Moonbrook rally. When I go to the location people are already gathered together but Hope Saldean doesn't appear at the bottom of the hay wagon so the quest stucks. Relogging or abandon and then restart the quest doesn't solved the problem.

**What should happen:**
Hope Saldean should appear as a shadowy figure at the bottom of the hay wagon and she should start talking to the peeople.

**Comment by LKArthas** [comment]
Go to the middle of the town to summon hope saldean

**Comment by Allgart** [comment]
Oh thanks! Yeah, I had to go to a different location as originally, but
when I made a circle around the building next to the church she appeard.

LKArthas <notifications@github.com> (időpont: 2020. jún. 17., Sze, 21:52)
ezt írta:

**Comment by Allgart** [comment]
Yeah thanks! I had to go to a different location as originally, but when I made a circle around the building next to the church, she appeard.
