### ISSUE TITLE
[Core] - Druid - Travel Form bugs

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#1525]
The travel form rank 2 has incorrect speed value. It's only 60% but it's an additional 60% to the base 40%, it's 100% total (this is a unique class mount replacement and match with the lvl 40 mount skill).

https://www.wowhead.com/spell=159456/travel-form

And Aquatic form is castable inside a cave too.

Video for serpentshrine cavern, aquatic form inside the cave:
https://www.youtube.com/watch?v=JyCFbAZY60E&feature=youtu.be&t=46

What should happen:
Increase the lvl 38 travel form speed to 100% bonus when casted out of combat, and remove the feline swiftness speed bonus from this. Also activate the bonus automaticly if we casted the spell in combat, and the combat status removed, currenty we need to recast the travel form to get the correct speed benefit after the combat (it's working with flight form, that switch automaticly after the combat, but the speed incerase didn't worked between lvl 38-58).
And remove the outdoor check from the aquatic form version if we are swimming, it's castable.

**Comment by Winkoo6** [comment]
I was reminded of something ambiguous, the feline swiftness bonus is only removable from the 100% speed bonus version (rank 2), the slower travel form it still get the benefits from feline swiftness.

**Comment by Thordekk** [comment]
Corrected
