### ISSUE TITLE
[Core] - Druid - Nature's Cure bug

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#1526]
https://www.wowhead.com/spell=88423/natures-cure

Seems it's only removing 1 of each type of magic, if we has 3 separated poison debuff, 2 magic debuff, and we cast this spell, 2 poison and 1 magic debuff still on us.
It's 'removing all Magic, Curse, and Poison effects' not just one of each type.

What should happen:
Remove every negative effect which match the criteria of debuff type, because of the 8 sec cooldown you can't spam to remove all of the debuffs.

**Comment by Winkoo6** [comment]
Example to test/reproduce the bug:
- [Forest Creeper](https://www.wowhead.com/npc=2350/forest-creeper) cast [Corrosive Poison](https://www.wowhead.com/spell=3396/corrosive-poison), if you pull 2 of this spider, and both of them cast the poison on you, the nature's cure will remove only one debuff, and the other poison still on you after the cast.

**Comment by Thordekk** [comment]
Corrected
