### ISSUE TITLE
[Core] - Druid - Lunar Empowerment bug

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#1527]
https://www.wowhead.com/spell=292664/lunar-empowerment

The Lunar Empowerment only working with Balance specialization, with Resto specialization + Balance affinity we also get the starsurge which gives us the same Lunar Empowerment (SpellID: 164547) buff, but here it's not consumed with the Lunar Strike.

What should happen:
The Balance specilazition Lunar Strike (SpellID: 194153) works fine, need to fix the Resto specilazition + Balance affinity Lunar Strike (SpellID: 197628) too.

**Comment by Thordekk** [comment]
Incorrect link, druid spell its https://www.wowhead.com/spell=164547/lunar-empowerment

**Comment by Thordekk** [comment]
Fixed corrected aura
