### ISSUE TITLE
[Arthas] - Quest Vorsha the Lasher NPC doesn't leave event spot.

### ISSUE THREAD

**Issue by Akozgw** [GuabinaCore/WoWKoi#1533]
**Links:**

https://classic.wowhead.com/quest=6641/vorsha-the-lasher

**What is happening:**

I abandoned quest and NPC "Muglash" now stays on island (till restart i guess), i know there was reports about this quests - but it's bugged, i checked him few times for 6h(!) and he's still on island

**What should happen:**

He should leave island back to he's normal spot (no matter if you abandon or complete quest/event).

**Comment by LKArthas** [comment]
If you don't click the altar he Will stay waiting for you there

**Comment by Akozgw** [comment]
Altar is unclickable without quest
