### ISSUE TITLE
Deadmines

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#1535]
The bridges before you go up to the ship are under bombing, and those bombs has much better visuals, the dark circles on the floor, if you avoid them you will never knocked to the water. But that is missing, so basiclly pure luck you avoid the bomb or not, and it's much harder to cross the bridge.
https://youtu.be/IBgdicuSH7s?t=698

**What should happen:**
The impact palces are much darker, so players can see which area they need to be avoid.

**Comment by LKArthas** [comment]
Do you have graphics up buddy because i see it pretty much darker 😁 try to ser graphics to 10 disable shadows and distance vieweing if you want more performance and confirm if you still not seeing the areas
