### ISSUE TITLE
[Core] - Logout

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#1538]
It's remove you from the current party immedietly. But you can even stay in the party, there is an offline status for players too. It's serious problem, if you get the release bug, what i reported previously, and you need to logout, or you can't do anything. In this case you lose the dungeon finder queue (and the reward is lost too) because you leaved the party. But there are countless acceptable reason why can be someone offline for a short time, you don't need to remove them from the party, if the party want to remove him, they has a vote to kick options, make instant usable on offline characters (if it's coded properly, i didn't tested yet, but you can't kick anybody in the first 15 mins, make there an exception, if he online = 15 mins, if he offline immedietly kickable)

**What should happen:**
Don't remove the members from the party if they logout, if he ask the others properly, they can wait a few mins while he is returning, and anyway they can use "the vote to kick" system if needed.
Also if he was the party leader just demote him automaticlly, and the others can solve everything else, because there is a new leader.

**Comment by Thordekk** [comment]
group issue was rewrited test again
