### ISSUE TITLE
[Core] - Reagent Bank

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#1540]
**Links:**
https://wow.gamepedia.com/Reagent_Bank

**What is happening:**
If you buy the Reagent Bank, all of your reagents are automaticlly stored there if you loot them. It's confusing, because you will never see the looted item in your inventory, you can't determinate what you want to store, everything is stored there immedietlly. The correct way is, everything stored in your bags like normally, and after you sold the trash what you don't want to store, you go to the bank, and pushing the "Deposit All Reagents" button. At this point this button is meaningless, because you never loot anything in your bags, also you need much more work to clean the reagent bank, because all trash is stored there too.

**What should happen:**
If we loot a reagent, don't store that in the reagent bank, it's always in our bags, only the craftings with proffessions can use that bank from anywhere, and that craft results is always appear in your bags (even if it's a reagent too), not in the bank.

**Comment by Thordekk** [comment]
Try it now and comment if issue persist
