### ISSUE TITLE
Parry for Blood Death Knight

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#1541]
**Links:**
https://worldofwarcraft.fandom.com/et/wiki/Parry#Functionality

**What is happening:**
Blood death knights has an increased parry, as their main tanking avoidance. 25% of their strength is added as parry rating, and this part is remained, even the defense changes, they still has higher parry. Their healing abilities only neutralizes the lacking of shiled (which is more armor/damage mitigation, and the possibility to block). They still need avoidance, only the armor is not enough mitigation (especially without a shield).

**What should happen:**
Add parry rating to blood death knights equal of 25% of total strength.

**Comment by Thordekk** [comment]
Need wowhead link to see if this spell is in egion or if its removed from game.

**Comment by MayuzumiSayaka** [comment]
https://shadowlands.wowhead.com/spell=82246/parry
