### ISSUE TITLE
Dungeon -- Scholomance Lilian Voss Encounter

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#1543]
**Links:**
https://wow.gamepedia.com/index.php?title=Lilian_Voss_(tactics)&oldid=5498670  historic page

https://wow.gamepedia.com/Lilian_Voss_(tactics)
**What is happening:**
Fixate, during phase 2 works, but not properly. Lilian is tauntable during fixate.  Also when fight ends the chest is not lootable as it doesn't think Lilian Voss is "defeated"  The chest and completion are think she needs to be killed, and she isn't as she lives the fight.  health pool only goes down to 2%?
**What should happen:**
While phase 2 is active and fixate is up, you cannot taunt Lilian.  When fight is done, Lilian would be at 1% health to end fight and chest is lootable and Dungeon boss completion would be complete as well.

**Comment by LKArthas** [comment]
Fixed credit part left fixate mechanics need confirmation on chest dtuff
