### ISSUE TITLE
Daily Cooking and Fishing quests

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#1544]
**Links:**
https://www.wowhead.com/quest=29325/a-slippery-snack
https://www.wowhead.com/item=67414/bag-of-shiny-things#contains

**What is happening:**
I only link one quest, but there is 5 in 3-3 capital city / factions, so total of 30 quests for each proffessional.
The basic money reward is fine, at least we get that 90 silver, but almost nothing else, we get 91s 50c for each quest, which is deffinitly not 9450xp converted to gold (on lvl 60). Also it's always give 250 reputation for that city, this is missing too. Also the bag reward is almost empty, it's always contains something, at least a vendor trash, but if you check the percents it's total of 207% drop, so avarage 2 items dropped, but never less than 1 (bags only for fishing, cooking has extra currency reward).

**What should happen:**
Need to add the missing repitutaion reward, and need to fix the xp what we get for this quest, now seems like we completed a lvl 1 quest on lvl 60, so we get almost nothing. And need to fix the bag reward, it's always drop something, it can't be empty.

**Comment by Winkoo6** [comment]
Update, on lvl 59 it's fine, i got 9300xp and 90 silver, but on lvl 60 the 9450xp not converted into gold correctly.
And the reputation is fine, it was a UI mistake by me with that char. Now i got the 250 rep.

**Comment by Thordekk** [comment]
Added daily proffession quest , fix in progress
