### ISSUE TITLE
Flying mount in water

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#1545]
**Links:**
https://www.youtube.com/watch?v=vzXKeBY2JP8&feature=youtu.be&t=12

**What is happening:**
If you ride your flying mount in the water, you start to drowning, even you still over the water. And you can't jump enough high to start to fly, because your breath bar is almost permanently there, you are drowing even with jumps. (the druids involved here too, the bug there has more visual, there is a 0,2-0,3 sec stag form between the aquatic and flight form)

**What should happen:**
On the mount we need to breath too if we are over the water :) And we need to fly out of the water with a simple jump. Also eliminate the stag form between aquatic/flight form for druids.

**Comment by Thordekk** [comment]
Invalid that video its from bfa, in legion that system isnt implemented
