### ISSUE TITLE
[Core] - Warrior - Charge/Intercept

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#1546]
**Links:**
https://www.wowhead.com/spell=100/charge
https://www.wowhead.com/spell=198304/intercept

**What is happening:**
Both of them are useable in roots, roots an immobilizing effect, we are not able to move, even with skills.

**What should happen:**
Need to check in both skills the root effect, if we are rooted, we are not able to charge.

**Comment by Thordekk** [comment]
Modified need test
