### ISSUE TITLE
[Arthas] - Quest Small Hands, Short Fuse

### ISSUE THREAD

**Issue by Zaatshot** [GuabinaCore/WoWKoi#1548]
**Links:**

https://www.wowhead.com/quest=13944/small-hands-short-fuse

**What is happening:**
Zone : Ashenvale.
Missing GOB and Trigger.

**What should happen:**
Add GOB and Trigger + fix credit

**Comment by Cefiro-Caecias** [comment]
Reverted commit that produced this failure. It should already work properly.
