### ISSUE TITLE
[Arthas] - Quest "Trelane's Defenses"

### ISSUE THREAD

**Issue by WineForMe** [GuabinaCore/WoWKoi#1549]
**Links:**
https://classic.wowhead.com/quest=694/trelanes-defenses

**What is happening:**
The npc "Apprentice Kryten" is missing. He doesn't appeear on the spot that he is suppose to be.

**What should happen:**
The npc "Apprentice Kryten" should be there so you're able to turn the quest and continue with the chain.

**Comment by Cefiro-Caecias** [comment]
Reverted commit that produced this failure. It should already work properly.
