### ISSUE TITLE
[Arthas] - Quest irresistible-pool-pony quest Goblin starting area

### ISSUE THREAD

**Issue by Williet13** [GuabinaCore/WoWKoi#1550]
https://www.wowhead.com/quest=24864/irresistible-pool-pony

**What is happening:**
had to abandon quest, no Hatchlings were spawning, no Npc's would appear that were phased, town in a box NPC's all disappeared.

**What should happen:**
Naga hatchlings in Nasj'elean spawning pool would be attracted to my pool pony.

**Comment by Williet13** [comment]
no Hatchlings were present

**Comment by Cefiro-Caecias** [comment]
Reverted commit that produced this failure. It should already work properly.
