### ISSUE TITLE
[Arthas] - Quest Volcanoth! Goblin starting area Quest- Horde.

### ISSUE THREAD

**Issue by Williet13** [GuabinaCore/WoWKoi#1551]
https://www.wowhead.com/quest=24958/volcanoth

**What is happening:**
first off after getting quest, no entrance to cave, then logged out. Deleted cache, and then logged in, all pahsed mobs and NPC's were gone, abandoned quest, logged out/in. i could go into cave but no Volcanoth, no phased mobs outside or NPC's.

**What should happen:**
The cave should be open and Volcanoth inside.

**Comment by Cefiro-Caecias** [comment]
Reverted commit that produced this failure. It should already work properly.
