### ISSUE TITLE
[Arthas] - Quest Going Deep - Missing Npc

### ISSUE THREAD

**Issue by Akozgw** [GuabinaCore/WoWKoi#1552]
Links:

https://www.wowhead.com/quest=14260/going-deep

What is happening:

Npc is missing on island, doesn't matter if you use disguise or no

What should happen:

Npc " Valishj" should stay at this ruins.

P.S 

she can be killed, but i waited for about 1h and she  didn't respawn.
![WoWScrnShot_062820_121838](https://user-images.githubusercontent.com/67214964/85945479-b1334d00-b946-11ea-9ac6-79ef12e8178d.jpg)

**Comment by Cefiro-Caecias** [comment]
Reverted commit that produced this failure. It should already work properly.
