### ISSUE TITLE
[Arthas] - Quest A Strange Request - Missing Npc

### ISSUE THREAD

**Issue by Akozgw** [GuabinaCore/WoWKoi#1553]
Links:

https://www.wowhead.com/quest=27764/a-strange-request

What is happening:

Quest Npc "Rhea" is missing.

What should happen:

He should stay at 67/55.
![WoWScrnShot_062820_135835](https://user-images.githubusercontent.com/67214964/85945467-99f45f80-b946-11ea-913e-96bbf9f74c35.jpg)

**Comment by Cefiro-Caecias** [comment]
Reverted commit that produced this failure. It should already work properly.
