### ISSUE TITLE
[Arthas] - Quest Warchief's Command: Burning Steppes! - Missing Npc

### ISSUE THREAD

**Issue by Akozgw** [GuabinaCore/WoWKoi#1554]
Links:

https://www.wowhead.com/quest=28667/warchiefs-command-burning-steppes

What is happening:

Quest Npc "Ariok" is missing.

What should happen:

Npc "Ariok" should stand 17/51.
![WoWScrnShot_062820_155500](https://user-images.githubusercontent.com/67214964/85948188-18a5c880-b958-11ea-9312-8886c521f1a1.jpg)

**Comment by Cefiro-Caecias** [comment]
Reverted commit that produced this failure. It should already work properly.
