### ISSUE TITLE
Macro deleting

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#1557]
**What is happening:**
When we deleting a macro, that disappear from the list, but the bottom macro text remain there, so the next macro in the list is overwrited with the deleted macro text.

**What should happen:**
Update the macro text correctly when the macro is deleted, and it's switched to the next macro automaticlly.

**Comment by Thordekk** [comment]
U need to move macro with cltrl out of bars thats not an issue
