### ISSUE TITLE
[Mob] Razormane Plunderer, Razormane Thornweaver, Razormane Defender not scaling with player level

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#156]
**Links:**
https://www.wowhead.com/npc=3267/razormane-plunderer
https://classic.wowhead.com/npc=3266/razormane-defender
https://classic.wowhead.com/npc=3268/razormane-thornweaver
**What is happening**
None of these enemies are scaling with player level.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
