### ISSUE TITLE
[Core] - Priest Power Word: Shield

### ISSUE THREAD

**Issue by WineForMe** [GuabinaCore/WoWKoi#1561]
**What is happening:**
The ability power word: shield applies the buff on you but the shield doesn't absorbd damage (Literally it says that absorbs 0 damage)

**What should happen:**
The shield should absorb an amount of damage that sacales with your level, intellect and spell power.

**Comment by Thordekk** [comment]
Rewrited aura need test in next update

**Comment by Thordekk** [comment]
If spell work close the issue
