### ISSUE TITLE
[Mob] Stonearm and Barak Kodobane's levels not scaling up

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#157]
**Links:**
https://classic.wowhead.com/npc=3394/barak-kodobane
https://classic.wowhead.com/npc=5837/stonearm
**What is happening:**
Barak Kodobane and Stonearm's levels aren't scaling up with player level.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
