### ISSUE TITLE
[Core] - Achievements

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#1570]
**What is happening:**
Achievements are account wide, not individual for characters. There is a separated options in the "Interface/Social/Display only character achievements to others" where you can allow this to be character dependant, but withouth that, it's account wide. You see the achievement tooltip like others with your alt, if you has not completed yet, for example "completed by Winkoo".

For example if you unlock the Allied Race later, and you create one, how that will work? Because in the current system he has zero achievements, so he is not able to play new races, it's not unlocked yet.

**What should happen:**
Even with the freshly created char the previously completed achievements on your account needs to be displayed, there are lot of things depends from the completed achievements. (for example mounts, you did not get the achievement which gives you the mount, but you are useing that mount?)

**Comment by Thordekk** [comment]
somsomeone can test now
