### ISSUE TITLE
[Core] - Warrior - Charge skill

### ISSUE THREAD

**Issue by Jaredfc** [GuabinaCore/WoWKoi#1571]
**Links:**

from WoWHead or our Armory
Charge (No talent) : ID 100
Charge (Double Time Talent) : ID 103827
Intercept (Prot warrior) : ID 198304
**What is happening:**
Charge/Intercept uses both stacks by spamming the button quickly. You may also experience a weird "run back and then forth" animation.

**What should happen:**
Charge/Intercept should only consume 1 stack, and then not be useable again during the duration of its travel to the target.

**Comment by Winkoo6** [comment]
Charge has a lot of problem, i already reported some, but it's not even changed, so im tired to get the evidences and report them for nothing. (we still can charge while we are rooted).

**Comment by Velthur-bot-3000** [comment]
Still aving the issue as well, When you charge in the sky, falling, etc. it should charge you to target and avoid any fall damage.  It still does not happen, uses a charge count/CD but doesnt charge to target while in air...

**Comment by Jaredfc** [comment]
https://www.youtube.com/watch?v=GHLBckGeSS4 Double Time Talent Charge Bug
https://www.youtube.com/watch?v=TMmuYR0ZR_Y Prot Warrior Intercept Bug
