### ISSUE TITLE
[Core] - Prot Warrior Talent - Shockwave

### ISSUE THREAD

**Issue by Jaredfc** [GuabinaCore/WoWKoi#1573]
**Links:**

from WoWHead or our Armory
Shockwave Talent : ID 46968

**What is happening:**
Deleted Cache, and WTF in a attempt to fix. Talent Shockwave becomes randomly un-useable. It disappears from bars. It also will disappear from spellbook even when talented during certain relog situations. The only way to get it back it to change talents after every relog

**What should happen:**
Talent Shockwave should give the spell consistently/permanently for it being talented

**Comment by Velthur-bot-3000** [comment]
I haven't noticed this bug on my warrior previously or currently.  Please recheck this again, and make sure its not a weird issue with an addon?  Thanks for reporting and enjoy!
