### ISSUE TITLE
[Core] - Holy-Protection - Consacration Animation

### ISSUE THREAD

**Issue by WineForMe** [GuabinaCore/WoWKoi#1574]
**Links:**

from WoWHead or our Armory

**What is happening:**
The Consacration animation is not working for both of these specs. If you press the key nothing happens yet the damage is still there. (It works fine for the retribution spec)

**What should happen:**
The animation of consacration should appear

**Comment by Velthur-bot-3000** [comment]
Animation/Spell visual bugs have been updated and taken care of.  Verified this is fixed, thank you for reporting and enjoy!
