### ISSUE TITLE
[Core] - Disengage - Hunter ability

### ISSUE THREAD

**Issue by Anterrka** [GuabinaCore/WoWKoi#1575]
**Links:** https://www.wowdb.com/spells/781-disengage

from WoWHead or our Armory

**What is happening:**

Currently, you do not get Disengage as MM or BM at level 8, but every level you will get a message that you learned that spell, but it will be grayed out and you won't be able to use it. I think it has something to do with this legion change : **Legion Patch 7.1.5 (2017-01-10): Made available to Survival as a level 45 talent, replacing  [Farstrider].** bugging it out.

**What should happen:**

Unless you play Survival, you should get Disengage much sooner than at level 45. // The level 8 i mentioned is the closest one i got to in terms of Legion Patches, some patches vary and show it is usable from level 20 etc. Needs confirmation.

**Comment by Velthur-bot-3000** [comment]
This issue got closed out early, it was not and has never been fixed. My original post/gut about it was post 2 months ago and got closed.
