### ISSUE TITLE
[Core] - Cobra Shot, Multi Shot and Stomp // Visual bug - Hunter

### ISSUE THREAD

**Issue by Anterrka** [GuabinaCore/WoWKoi#1577]
**Links:** https://www.wowhead.com/spell=193455/cobra-shot // https://www.wowhead.com/spell=199530/stomp // https://www.wowhead.com/spell=257620/multi-shot

from WoWHead or our Armory

**What is happening:**

There is no animation for those 3 spells, but the damage still occurs

**What should happen:**

Only a visual bug, nothing too crazy, we just need to be able to see the spell animations.

**Comment by Velthur-bot-3000** [comment]
Issues with spell visual not showing up has been fixed, atleast for the hunter spells mentioned!  Thanks for the report and enjoy!
