### ISSUE TITLE
[Arthas] - Quest : No One Gets Out Alive, Cutscene Skip  - Hillsbrad Foothills (Horde)

### ISSUE THREAD

**Issue by Jaredfc** [GuabinaCore/WoWKoi#1587]
**Links:**

from WoWHead or our Armory
https://youtu.be/QRJtpMbAaME
**What is happening:*
Skipping The cutscene makes the quest incompletable.

**What should happen:**
Even hitting the Escape Key and skipping the cutscene should allow the quest to be completable

**Comment by LKArthas** [comment]
Fixed
