### ISSUE TITLE
[Arthas] - Quest: The Ritual Bond

### ISSUE THREAD

**Issue by lugnut1** [GuabinaCore/WoWKoi#1590]
**Links:**

from WoWHead or our Armory

https://www.wowhead.com/quest=13569/the-ritual-bond

**What is happening:**

The quest is given but no animal spirits appear, so quest can't be completed.

**What should happen:**

The quest is given and animal spirits appear, so quest can be completed.

**Comment by Velthur-bot-3000** [comment]
Quest is completable!  So it seems the first click on the incense pile sometimes just glitches and doesn't do anything.  But after clicking it the second time, I spawned into the grey space and saw the bear spirit near the hills.  Did not double check that all sprirts were there.  

https://youtu.be/JhL1rMxyVKc
