### ISSUE TITLE
[Core] - Minor profession bugs

### ISSUE THREAD

**Issue by Kobasun** [GuabinaCore/WoWKoi#1591]
**What is happening:**

**Archeology**: digsite disappears after 3-4 digs, digsite progress bar and "digsite complete" message do not appear
**Skinning, herbalism, mining**: after learning the relevant profession all mobs that can be skinned (or, rarely, mined and looted for plants) get sparkles (like ore or plants) and appear as resource target on minimap (filling it completely in locations like Elwynn Forest).

**What should happen:**

**Archeology**: digsites should disappear after 6 digs, showing digsite progress bar and "digsite complete" message accordingly.
**Skinning, herbalism, mining**: the relevant mobs should not be sparkling and should only show info on mouseover like "skinnable". Not sure whether they should appear on minimap (at least for skinning).

**Comment by Velthur-bot-3000** [comment]
You are correct in thinking they should not show on map.  only way to show beasts on minimap would be through track beasts.  Sefrenia has located the issue with these visual bugs, and you can expect to see a lot of profession changes this week.  Thank you for reporting.
