### ISSUE TITLE
[Core] - Profession - First Aid - Linen Bandage does not heal

### ISSUE THREAD

**Issue by Adunai** [GuabinaCore/WoWKoi#1592]
**Links:**
https://www.wowhead.com/item=1251/linen-bandage

**What is happening:**
The Linen Bandage can be cast on the target, applies the buff, but it does not heal.

**What should happen:**
The buff should heal the target.

**Comment by Williet13** [comment]
AS WELL AS OTHERS , IE silk, heavy linen, wool, i think some potions are not working, like healing ones now as well.

**Comment by Velthur-bot-3000** [comment]
Seems there has been a fix, please recheck. I was able to heal from low level bandages, all healing properly.  A lot of profession fixes hit this week.
