### ISSUE TITLE
[Arthas] - Horde quest- Jin'zil's blessing Stonetalon Mountains

### ISSUE THREAD

**Issue by Williet13** [GuabinaCore/WoWKoi#1593]
**Links:**
https://www.wowhead.com/quest=26067/jinzils-blessing

**What is happening:**

Use the Voodoo Stick on our guys, the Krom'gar Marauders, that are fighting with the Grimtotem Brutes. They turn a lovely shade of red and gain Voodoo Power. Joy!
++++++++++++++++++++++++++
the Voodoo magic of the stick works, you just get no credit.

**What should happen:**
you should be gaining credit after the stick is used to buff the Marauders.

**Comment by Akozgw** [comment]
there's already one report about this quest

**Comment by LKArthas** [comment]
Fixed
