### ISSUE TITLE
[Core] - Mobs resetting when running on low health

### ISSUE THREAD

**Issue by Williet13** [GuabinaCore/WoWKoi#1594]
**What is happening:**
Animal mobs, withered Mosshoof -Asharza
Spiders-Stonetalon peaks
Seeming to run at low health and evade to get back to spawn point, at 100 percent health, this is even being pulled a short distance.

**What should happen:**
Not to evade and return to spawn point once at low health.

**Comment by Cefiro-Caecias** [comment]
The NPC "Mosshoof Courser" (https://www.wowhead.com/npc=8761) seems to work fine.

The NPC "Weakened Mosshoof Stag" (https://www.wowhead.com/npc=35096) has, in its combat sequence, an order that tells it that when it reaches 15% HP, it must flee in terror and seek help with the nearest mob, if there is one, or if not, it simply moves away a few meters, but then returns to continue attacking.

I imagine the same thing happens with spiders. Check again.
