### ISSUE TITLE
[Core] Floating Combat Text incorrect/Values not showing correctly

### ISSUE THREAD

**Issue by Branbal** [GuabinaCore/WoWKoi#1595]
**Links:**
https://www.wowhead.com/spell=589/shadow-word-pain

**What is happening:**
As a Night Elf Warrior right in the starting zone, floating damage of Slam or regular hits does not show correcly when mobs are damaged.
Shadow word: Pain of a lvl5 Night Elf Priest seems to be not working aswell.
I tried also a Hunter and it is the same.

**What should happen:**

Show correctly the number of the hit or skill.

**Comment by Velthur-bot-3000** [comment]
@Branbal Make sure you are linking a non classic link, that will show very wrong information on dmg, as it would be scaled up more in later patches
