### ISSUE TITLE
Bloodtalon Hatchlings attack Bloodtalon Raptors

### ISSUE THREAD

**Issue by toamuka** [GuabinaCore/WoWKoi#1596]
These mobs are found in Troll starter zone in the Bloodtalon shore

This also applies to the mobs on Zalazane's Fall

'Lost Bloodtalon Hatchling' on 'Corrupted Bloodtalon' 

they seem to fight each other when aggro'd near a player.

**Comment by Velthur-bot-3000** [comment]
https://vimeo.com/441515463

video evidence of the two NPC mobs attacking each other. 

Lost Bloodtalon Hatchling ID:39157
Corrupted Bloodtalon ID:37961  (Also showing up aggressive, where they should always show neutral)
