### ISSUE TITLE
[Quest] - Handling the Goods (Azsharah)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1605]
The quest [Handling the Goods](https://www.wowhead.com/quest=14486/handling-the-goods) has only one [Highborne Tablet](https://www.wowhead.com/item=49639/highborne-tablet) spawn. When it should have multiple ones.

It's been so long since I've reported something, glad to be back 😄

**Comment by Cefiro-Caecias** [comment]
Welcome back. Fixed, available in the next update.
