### ISSUE TITLE
[Quest] - Blacken the Skies (Azsharah)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1606]
The [Talrendis Glaive Throwers](https://www.wowhead.com/npc=36890/talrendis-glaive-thrower) gets automatically out of combat (evading and regenerating their HP). The quest is still doable but you have to spam like hell to kill one of them.

**Comment by LKArthas** [comment]
This is fixed, but fix is not yet applyed, will be avaible later or tomorrow
thanks for reporting it anyways ;)
