### ISSUE TITLE
[NPC] Bleeding Hollow Necrolyte - missing spells

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1607]
**Links:**

https://www.wowhead.com/npc=19422/bleeding-hollow-necrolyte#abilities

**What is happening:**

Bleeding Hollow Necrolyte doesn't cast their spell spells

**What should happen:**
There are 3 abilities in spell table to cast. (One of them is summoning minor creatures, keep in mind they should not grant XP)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
