### ISSUE TITLE
[Quest] The Eyes of Grillok

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1608]
**Links:**

https://www.wowhead.com/quest=10813/the-eyes-of-grillok

**What is happening:**

-Quest NPC (https://www.wowhead.com/npc=19440/eye-of-grillok) deals too much damage. They deal ~1,8k per hit, while the rest of the mobs deal ~400 on avarage.

-In order to complete the quest you need to use quest items and then return to the quest giver with a buff on yourself. When near the quest giver, the quest marks itself as completed. Hitbox of the "completion mark" is way to small. Yuo need to make a couple of circles around the quest giver in order to find the spot to complete it.

**What should happen:**
Eye of Frillok should deal less dmage.

Quest completion hitbox range should be wider.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
