### ISSUE TITLE
[Quest] The battle horn

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1609]
**Links:**

https://www.wowhead.com/quest=10230/the-battle-horn

**What is happening:**
 Quest NPC (https://www.wowhead.com/npc=16978/lieutenant-commander-thalvos) is missing. He randomly appeared for a second but was invulnerable (Maybe is't some sort of phasing bug?).

*EDIT* He actually just falls under the ground and is not targetable.

**What should happen:**
The NPC should be roaming freely around Expedition Armory

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
