### ISSUE TITLE
[Core] - Quest The Foot of the Citadel

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1610]
**Links:**

https://www.wowhead.com/quest=10876/the-foot-of-the-citadel#criteria-of

**What is happening:**

I can't loot the quest item: The Head of the Hand of Kargath https://www.wowhead.com/item=31706/the-head-of-the-hand-of-kargath
When looting error message pops up "Already looted"

**What should happen:**

**Comment by ventarius5** [comment]
https://imgur.com/a/7oiN0vw

**Comment by Cefiro-Caecias** [comment]
This is an error that sometimes occurs with summoned NPCs; however, it allows you to loot the corpses if you move away and come closer again. I pass it on to Core review.

**Comment by Thordekk** [comment]
Someone can test again?
