### ISSUE TITLE
[NPC] Ssslith - auto attack deals too much damage

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1611]
**Links:**

NPC - https://www.wowhead.com/npc=18154/ssslith
From Quest - https://www.wowhead.com/quest=9729/fhwoor-smash

**What is happening:**

Ssslith deal more damage than intended. He hits for ~2k per hit, instead of avarage ~400.

**What should happen:**
Avarage monster dmaage is ~400

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
