### ISSUE TITLE
[NPC] Starving Bog Lords, Starving Fungal Giants, Sporeggar Spawns

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1612]
**Links:**
https://www.wowhead.com/npc=18358/sporeggar-spawn

https://www.wowhead.com/npc=19519/starving-bog-lord
https://www.wowhead.com/npc=18125/starving-fungal-giant 

**What is happening:**

 Starving Bog Lords, Starving Fungal Giants and Sporeggar Spawns are fighting each other. Their attacks deal damage to each other. This causes Bog lords and Fungal Giants to be not loot-able when sporeggar spawns bring them below 50% HP.

**What should happen:**
NPCs attacks shouldn't deal damage to each other.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
