### ISSUE TITLE
[Quest] Untold truth

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1613]
**Links:**

https://www.wowhead.com/quest=11614/untold-truths

**What is happening:**

Quest is auto-complete. Can be turned in at the quest giver.

**What should happen:**
Correct quest turn in NPC:
https://www.wowhead.com/npc=25328/shadowstalker-luther

**Comment by Cefiro-Caecias** [comment]
Honey, we haven't even started repairing the WOTLK Expansion, so please don't report any of it :P
