### ISSUE TITLE
[NPC] Nerub'ar skitterer - quest item drop chance

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1614]
**Links:**

https://www.wowhead.com/npc=24566/nerubar-skitterer

https://www.wowhead.com/item=34709/warsong-munitions

**What is happening:**

Nerub'ar skitterers drop Warsong ammunition. Current drop rate seems to be 100%

**What should happen:**

According to WoWHead drop chance is 0.01%. (I did not find any indications in the comment section about it being higher)

**Comment by Cefiro-Caecias** [comment]
Honey, we haven't even started repairing the WOTLK Expansion, so please don't report any of it :P
