### ISSUE TITLE
[Quest] Cutting of the source

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1615]
**Links:**

https://www.wowhead.com/quest=11602/cutting-off-the-source

**What is happening:**

Quest description shows "10/10 eggs destroyed" and a progress bar with 0% done. The quest cannot be completed=

**What should happen:**

There shouldn't be a progress bar in the quest.

**Comment by Cefiro-Caecias** [comment]
Honey, we haven't even started repairing the WOTLK Expansion, so please don't report any of it :P
