### ISSUE TITLE
[Quest] Foolish Endeavors

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1616]
**Links:**

https://www.wowhead.com/quest=11705/foolish-endeavors

**What is happening:**

When the dialogue end, mobs spawn and kill the player.

**What should happen:**

According to retail video sources, the debuff that player is stunned with should last ~10 seconds longer, so all the mobs focus on High Lord Saurfang. Saurfang is using cleave skill to get rid of the adds and leave the quest NPC alive for players to finish him.

**Comment by Cefiro-Caecias** [comment]
Honey, we haven't even started repairing the WOTLK Expansion, so please don't report any of it :P
