### ISSUE TITLE
[Quest] A race Against Time

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1617]
**Links:**

https://www.wowhead.com/quest=11671/a-race-against-time

**What is happening:**

Inquisitor Salrand is already spawned with random mobs around her. Box with quest item that spawns after killing her is always spawned, even if not on the quest.

**What should happen:**

The platform Inquisitor Salrand is on should be clear of monsters. She should be summoned using an item provided by the quest (https://www.wowhead.com/item=34897/beryl-shield-detonator). A box ith quest reward should be spawned after killing Inquisitor Salrand.

**Comment by Cefiro-Caecias** [comment]
Honey, we haven't even started repairing the WOTLK Expansion, so please don't report any of it :P
