### ISSUE TITLE
[Core] - Bug Visual

### ISSUE THREAD

**Issue by carlosyuniro** [GuabinaCore/WoWKoi#1618]
https://es.wowhead.com/spell=121820/alanoche-obsidiana

Al montarme en "Alanoche Obsidiana" se me genera un bug visual lo cual no veo la montura.

![WoWScrnShot_090820_230800](https://user-images.githubusercontent.com/62365902/92547190-bbb57100-f22a-11ea-9b6d-f25a84e0395f.jpg)

**Comment by Cefiro-Caecias** [comment]
Thor, esta montura funcionaba, pero ahora s egenera este bug visual. Esto no ocurre con monturas normales. Como recordarorio, esta montura es especial, ya que no te sube a una montura, sino que te convierte a tí en montura, y podés llevar en tu grupa a un amigo.

Probé meter el relleno completo de las tablas mount, mount_capability, mount_type_x_capability, mount_x_display y vehicle, y no se solucionó. Especulo que el bug puede estar en algo relacionado con las auras, ya que se han reportado otros bugs que antes no existían, cuando sos convertido en algún bicho con spells de disfraces. Queda en tus manos.

**Comment by Thordekk** [comment]
Las monturas tambien tienen su creature_template, apenas tenga el cliente intentaré reproducir el problema
