### ISSUE TITLE
Misión "Mas húmedo que mojado" desolace 

### ISSUE THREAD

**Issue by carlosyuniro** [GuabinaCore/WoWKoi#1619]
https://es.wowhead.com/quest=14264/m%C3%A1s-h%C3%BAmedo-que-mojado

Al trasformarte en naga y tratar de matar "Sirviente de neptulon" sales de la transformacion de "naga" por lo cual no puedes completar la misión, se destranforma al usar un hechizo y no realiza ataques automáticos.

**Comment by Cefiro-Caecias** [comment]
Acabo de probarlo, y no me ocurre ningún bug o.O
