### ISSUE TITLE
[Mob] Kolkar Pack Runners/Kolkar Packhounds not scaling up

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#162]
**Links:**
https://classic.wowhead.com/npc=3274/kolkar-pack-runner
https://classic.wowhead.com/npc=4316/kolkar-packhound
**What is happening:**
Kolkar Pack Runners and Kolkar Packhounds are not scaling up to player level.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
