### ISSUE TITLE
[Quest] To Legion Hold

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1626]
**Links:**

https://www.wowhead.com/quest=10596/to-legion-hold

**What is happening:**

Using provided quest item doesn't start the event.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
The Shadowmoon Valley, Blade's Edge Mountains and Netherstorm maps are still not fixed, so please do not open reports on them :P
