### ISSUE TITLE
[NPC] Shadowmoon valley wildlife

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1627]
**Links:**

https://www.wowhead.com/npc=21978/shadowmoon-valley-wildlife

**What is happening:**

This "NPC" is spawned along with Felboars (https://www.wowhead.com/npc=21878/felboar) and is considered a quest objective.

**What should happen:**

Even though, this "NPC" exists in WoW database, it should not be spawned.

**Comment by ventarius5** [comment]
https://imgur.com/a/0Md8dE6

**Comment by Cefiro-Caecias** [comment]
The Shadowmoon Valley, Blade's Edge Mountains and Netherstorm maps are still not fixed, so please do not open reports on them :P
