### ISSUE TITLE
[Quest] The Fel and the Furious

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1628]
**Links:**

https://www.wowhead.com/quest=10613/the-fel-and-the-furious

**What is happening:**

Fel Reaver control console doesn't work.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
The Shadowmoon Valley, Blade's Edge Mountains and Netherstorm maps are still not fixed, so please do not open reports on them :P
