### ISSUE TITLE
[Quest] A necessary distraction

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1629]
**Links:**
https://www.wowhead.com/quest=10688/a-necessary-distraction

**What is happening:**

Can't use quest item on quest NPC.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
The Shadowmoon Valley, Blade's Edge Mountains and Netherstorm maps are still not fixed, so please do not open reports on them :P
