### ISSUE TITLE
[Mob] Wyneth/Verog the Dervish not scaling up

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#163]
**Links:**
https://classic.wowhead.com/npc=3395/verog-the-dervish
https://gyazo.com/f3c25a20ebb31f991a4b2dfc562fdd37 (Wyneth)
**What is happening:**
Verog the Dervish and Wyneth are not scaling up to player level.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
