### ISSUE TITLE
Boren Tundra - Visual bug.

### ISSUE THREAD

**Issue by XiriuBR** [GuabinaCore/WoWKoi#1630]
These Winps appear standing near the entrance to the alliance's base and some of them stay in the air near the bats.

![Sem título](https://user-images.githubusercontent.com/69175635/93021549-8f4a7d80-f5b9-11ea-9d86-47b6fb107847.png)

**Comment by Cefiro-Caecias** [comment]
All WOTLK is still unrepaired, so it is not necessary to report any of that Expansion ^^
