### ISSUE TITLE
Boren Tundra - Quest bug.

### ISSUE THREAD

**Issue by XiriuBR** [GuabinaCore/WoWKoi#1631]
Quest "The Emissary" - 0/1 Leviroth slain = When you use the quest item "Trident of Naz´Jan to kill the elite, the quest not complete, I already tried to abandon the quest and get it again, it didn't work.

Quest "Unfit for Death" 0/8 Nesingwary Trapper Trapped = When you use the bait in the trap some times kills you.
![Sem título1](https://user-images.githubusercontent.com/69175635/93021659-38917380-f5ba-11ea-9d98-983b20ef2f22.png)

**Comment by Cefiro-Caecias** [comment]
All WOTLK is still unrepaired, so it is not necessary to report any of that Expansion ^^
