### ISSUE TITLE
pináculo de utgarde

### ISSUE THREAD

**Issue by asecine** [GuabinaCore/WoWKoi#1637]
https://es.wowhead.com/npc=26687/gortok-pezu%C3%B1a-p%C3%A1lida
https://es.wowhead.com/npc=26693/skadi-el-despiadado
from WoWHead or our Armory

gortok pezuña pálida solo tiene el modelo, no hay ninguna clase de interacción posible y skadi el despiadado se queda quieto en la entrada de su sala después de su diálogo 

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Eso ocurre porque aun no hemos tocado la Expansión WOTLK ni empezado a repararla :P
