### ISSUE TITLE
[Arthas] - "Dafeng, the spirit of air" bugged cant complete

### ISSUE THREAD

**Issue by mellardsmike2211** [GuabinaCore/WoWKoi#165]
quest bugged in the wandering isle cant complete panda starting zone because of it. During quest "Dafeng, the spirit of air" character must wait for winds to slow down to follow npc, but the winds never slow down causing player to  take damage when trying to follow npc to complete quest.

**Comment by LKArthas** [comment]
Fixed yesterday, increase timers between wind activations
