### ISSUE TITLE
[Scenario] Assault on Broken Shore /Stage 2 [Core] Vmap/Pathing

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1652]
**Links:**

https://www.wowhead.com/zone=8581/assault-on-broken-shore

**What is happening:**
The NPC's who assign don't have swim animation or Vmap is broken since they fly over the water or if there is a little hill. from A to B.
https://imgur.com/a/9iSkvb0
https://imgur.com/a/UX4tx0C

**What should happen:**
Fix the Vmap in that area.

**Comment by Cefiro-Caecias** [comment]
In the process of reconstruction.
