### ISSUE TITLE
[Core] Formation stack/split.

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1653]
**Links:**

**What is happening:**
If there is a formation of mobs that suppose to follow the same path they stack on each other like that. They stay stacked ever if attack something.
https://imgur.com/a/VvGVqdW
That's just an example, I'm 100% sure it's a global core issue.

**What should happen:**
When they move they are splited like that.
https://youtu.be/x-r6YiSPIgk?t=337
When they attack they made a formation like that.
https://youtu.be/x-r6YiSPIgk?t=357

**Comment by Cefiro-Caecias** [comment]
In the process of reconstruction.
