### ISSUE TITLE
[Misc] Visible trigger

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1655]
**Links:**

https://www.wowhead.com/npc=121137/maggie-slither-masterson

**What is happening:**
If u port to that NPC u can see the trigger 
https://imgur.com/a/jctykEt

Some more visible triggers
https://imgur.com/a/nnxQzK4

**What should happen:**
Trigger suppose to be invisible to the players.

**Comment by Cefiro-Caecias** [comment]
Fixed.
