### ISSUE TITLE
[NPC] Double/Triple spawn [MISC] Missing Animations [Quest] To be Prepared/Horde

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1656]
**Links:**
https://www.wowhead.com/quest=44281/to-be-prepared
https://www.wowhead.com/npc=3296/orgrimmar-grunt
https://www.wowhead.com/npc=114114/gregg
https://www.wowhead.com/npc=74228/darkspear-headhunter
https://www.wowhead.com/npc=7980/deathguard-elite
https://www.wowhead.com/npc=113381/horde-recruit

**What is happening:**
When u take ''To be prepared'' u see some strange things.
They have double or more spawns at each other.
https://imgur.com/a/2a1HN9j
https://imgur.com/a/odXRsB6
Headhunters miss the Attack animation
Deathguard elites suppose to be alive
Horde Recruit suppose to attack the dummies
Dark rangers are fine

**What should happen:**
Suppose to be only one spawn.
Headhunters suppose to shoot the targets like here
https://youtu.be/mHYsI0XrLHo?t=28
Alive guards
https://youtu.be/mHYsI0XrLHo?t=38
Attack Dummies
https://youtu.be/mHYsI0XrLHo?t=45

**Comment by ShikoSCS** [comment]
Corrected, but it continues working in the area
