### ISSUE TITLE
[NPC] Double/Triple spawn [MISC] Missing Animations [Quest] To be Prepared/Alliance

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1657]
**Links:**
https://www.wowhead.com/npc=107829/alliance-recruit
https://www.wowhead.com/npc=108483/tasha-highfoot
https://www.wowhead.com/npc=51348/stormwind-gryphon-rider
https://www.wowhead.com/npc=29152/stormwind-dock-worker

**What is happening:**
https://imgur.com/a/ia5poBT
Alliance Recruit miss the attack animation when are around the dummies
On recruit (when the quest start) is missing the RP/path then the mobs sigh and go back to attack (see below on the video)
Tasha Highfoot miss the ''forge'' animation 
Alliance recruit miss the ''sharp'' animation when its around the grinder (close to Tasha)
Stormwind gryphon riders suppose to fly around, not stay on the ground.
One of the tables missing (can't find the ID).
Stormwind Dock Workers miss all the animation/RP and pathing they have.
The Npc's on the '' duel'' place miss ''cheer up'' emote

**What should happen:**
https://www.youtube.com/watch?v=ANir2S1iiWI (sigh, go back to attack)
You can see the attack animation too
Dock workers animation/what do
https://www.wowhead.com/npc=29152/stormwind-dock-worker#screenshots (most of it is on the screenshots)
Everything can be seen in the video above.

**Comment by ShikoSCS** [comment]
Corrected, but it continues working in the area
