### ISSUE TITLE
[Misc] Stormwind Guards issuee's.

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1658]
**Links:**

https://www.wowhead.com/npc=42218/stormwind-royal-guard
https://www.wowhead.com/npc=1642/northshire-guard

**What is happening:**
Stormwind Royal Guard missing any path.They stay at one place or move around from random movement.
Some of Northshire Guards dont have the path they suppose to.
Stormwind Guard that have path is missing it. (cant find the right Legion ID)

**What should happen:**
How Royal Guards suppose to move
https://www.wowhead.com/npc=42218/stormwind-royal-guard#comments:id=1482066
Northshire guards (u gonna see some stay on the road ) must walk around the path.
Same as Stormwing Guards.

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt blizzlike later on.
