### ISSUE TITLE
Cannot escape Pandaren Startzone

### ISSUE THREAD

**Issue by theblueraccoon** [GuabinaCore/WoWKoi#1659]
**Links:**

from WoWHead or our Armory

**What is happening:**

Questline "a new friend" in the Pandaren Starting zone cannot be completed.

**What should happen:**
The water god should appear, and I should play with the water spouts in order to befriend him.

**Comment by Nephilimkoi** [comment]
He Appears. but the mechanics is kinda broken and should be reviewed. It can be completed but you gotta have patience.

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt blizzlike later on.
