### ISSUE TITLE
Chamber_of_Whispers (MoP) Quest

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1660]
**Links:**
https://www.wowhead.com/quest=29785/dafeng-the-spirit-of-air
https://wow.gamepedia.com/Chamber_of_Whispers

from WoWHead or our Armory

**What is happening:**

There is no air-storm inside the chamber of whispers

https://imgur.com/a/vGqg3Ku
(tho in the pic i had already completed the quest its for reference)

**What should happen:**

**Dafeng, having been scared by Zhao-Ren, now attempts to protect himself by making the wind really intense through the rooms harming those that try to run through without waiting for the wind to settle down.**

There should be an Wind Storm that makes you stop every once in a while because it inflict a DoT when you are exposed to it

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt blizzlike later on.
