### ISSUE TITLE
Battle for the Skies (MoP) (Zhao-Ren NPC) 

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1661]
**Links:**
https://www.wowhead.com/quest=29786/battle-for-the-skies
https://www.wowhead.com/npc=55786/zhao-ren
https://imgur.com/a/eJ1dvla

from WoWHead or our Armory

**What is happening:**

Zhao Ren Model isnt changing when the battle start keeping the model with over 400k HP.

**What should happen:**
Zhao Ren Model should be remplaced for https://www.wowhead.com/npc=55786/zhao-ren when the battle gets started as the one presented has over **400K HP** while the **55786 ID** one has **3,228 HP**

Althought the battle is still doable only using the fireworks but still you should be able to hit him when he gets down.

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt blizzlike later on.
