### ISSUE TITLE
The Suffering of Shen-zin Su (MoP) (QUEST)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1662]
**Links:**
https://www.wowhead.com/quest=29791/the-suffering-of-shen-zin-su
https://imgur.com/a/FrslL77

from WoWHead or our Armory

**What is happening:**
there are 2 things that are happening

1. Sometimes you have the chances of being drop down
1.1 The only way to go back to the ballon is  to use hearthstone then get to the part where you have to fight the stone guardian 
1.2 Since the Path is blocked the only way is to die using .stuck command. 

2. Shen Zin Su dialog is broken it only say one or two things. 

**What should happen:**
1. The Air Balloom shouldnt have any problem moving
2. Shen Zin Su dialog should be scripted and tell the tale of his problem.

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt blizzlike later on.
