### ISSUE TITLE
Bidden to Greatness (MoP) (Quest)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1663]
**Links:**
https://www.wowhead.com/quest=29792/bidden-to-greatness
https://imgur.com/a/qMAFXHA

from WoWHead or our Armory

**What is happening:**

The doors are clickeable and you can easily pass throught

**What should happen:**

Doors should be jammed and only open after certain dialog are said

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt blizzlike later on.
