### ISSUE TITLE
Pei-Wu_Forest (MoP) (Zone)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1664]
**Links:**
https://wow.gamepedia.com/Pei-Wu_Forest
https://imgur.com/a/HTn8mfN

from WoWHead or our Armory

**What is happening:**

Darkened Horrors and the Hordes are just standing and awkwardly looking at each other.

**What should happen:**

They should be Fighting to Death.

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt blizzlike later on.
