### ISSUE TITLE
Vordraka, the Deep Sea Nightmare (MoP) (NPC)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1665]
**Links:**
https://www.wowhead.com/quest=29798/an-ancient-evil

from WoWHead or our Armory

**What is happening:**

Vordraka, the Deep Sea Nightmare is in the zone **WAY BEFORE** the quest is taken

**What should happen:**
Vordraka, the Deep Sea Nightmare should be in the zone **AFTER** the quest is taken not before

Also Aysa should help you fight it. Not just Stare Awkwarly in the side

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt blizzlike later on.
