### ISSUE TITLE
The Healing of Shen-zin Su (MoP) (Quest)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1666]
**Links:**
https://www.wowhead.com/quest=29799/the-healing-of-shen-zin-su
https://imgur.com/a/nQDOCwF

from WoWHead or our Armory

**What is happening:**

Whole Script is broken AF.

1. There are No Healers to rescue
2. The mobs dont spawm all around the area. they just suddently appear behind a rock and jump to attack the healers
3. The Healers just magically spawm from god knows where
4. You only need to stay infront of the rock and attack the mobs.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt blizzlike later on.
