### ISSUE TITLE
[Tyce] - Assault on Violet Hold Dungeon

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1667]
**Links:**
https://wow.gamepedia.com/Assault_on_Violet_Hold
https://imgur.com/a/0GLV2g5

from WoWHead or our Armory

**What is happening:**

Sometimes Mobs are Spawmed laid on the ground as they were faking death making them unable to be hit.
Making the Dungeon unable to Be completed as you cant complete the % needed

**What should happen:**

Mobs should spawn as normal. and the fight should be able to proceed

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_102620_153641](https://user-images.githubusercontent.com/73371905/97220090-551bf080-17a1-11eb-9e69-12ee5cb72da5.jpg)
 
UPDATE 

After 2th boss you get stuck as there is no progress and no new portals spawn

**Comment by Nephilimkoi** [comment]
Act. while i cant say its fixed. you can now do the dungeon as the dead mobs now spawn actually dead rather than "dead" but with health

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
