### ISSUE TITLE
[Tyce] - Vault of the Wardens Dungeon

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1668]
**Links:**
https://wow.gamepedia.com/Vault_of_the_Wardens
https://wow.gamepedia.com/Tirathon_Saltheril
https://wow.gamepedia.com/Cordana_Felsong_(tactics)

from WoWHead or our Armory

**What is happening:**

1. Tirathon_Saltheril 
Sometimes after Fel Mortar he just stay still. he isnt doing anything but just gettin hit.

2.Cordana_Felsong
Creeping Doom Skill is broken, it doesnt summon the avatars that cover the plataform and that you have to dodge. she just get inside her bubble. rises and after the skill is "done" she comes down and the dynamics start again.

**What should happen:**

Both should properly work in their scripted actions.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
