### ISSUE TITLE
[Dungeon Eye of Azshara] - Lady Hatecoil

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1669]
**Links:**
https://wow.gamepedia.com/Eye_of_Azshara_(instance)
https://wow.gamepedia.com/Lady_Hatecoil

from WoWHead or our Armory

**What is happening:**

**Lady_Hatecoil**
Focused Lightning

Static Nova
 
All of those skills have some problems activating for example with **Static Nova** you need  to run to land to avoid being stunned, it doesnt work and you get stunned anyway

Same Happens with **Focused Lightning** you need to run away to water. but you get stunned anyway

**What should happen:**

you shouldnt get stunned by **Static Nova** while in land
you shouldnt get stunned by **Focused Lightning** while in water

**Comment by Nephilimkoi** [comment]
**Focused Lightning
Same Happens with Focused Lightning you need to run away to water. but you get stunned anyway
you shouldnt get stunned by Focused Lightning while in water** Works now after latest scripting

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_102620_124925](https://user-images.githubusercontent.com/73371905/97203357-11b68780-178b-11eb-8fe0-6ed8b4cbff98.jpg)
Static Nova still Bugged.

**Comment by ShikoSCS** [comment]
Fix
