### ISSUE TITLE
Hymdall (LEGION) (DUNGEON) (BOSS)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1670]
**Links:**
https://wow.gamepedia.com/Halls_of_Valor
https://wow.gamepedia.com/Hymdall_(tactics)

from WoWHead or our Armory

**What is happening:**
Hymdall
Dancing Blade doesnt do anything but hover nicely.

**What should happen:**

**Dancing Blade — Hymdall throws an enchanted blade towards a random player. Upon landing the blade begins to whirl inflicting 170625 to 179375 Physical damage every 2 sec to all enemies within the zone.**

**Comment by ShikoSCS** [comment]
Fixed
