### ISSUE TITLE
Neltharion's Lair (LEGION) (DUNGEON) (ZONE) (NPC) ( BOSS)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1671]
**Links:**
https://wow.gamepedia.com/Neltharion%27s_Lair

from WoWHead or our Armory

**What is happening:**

1. after throwing yourself in the tunnel when landing down the pit. you can somehow temporally fly. skipping the path to the first boss. 
2. even when you land all targets are invalid and you cannot attack them only with aoe.
3. reloging doesnt solve any problem.

**What should happen:**

you shouldnt be able to fly

You should be able to hit targets.

**Comment by Arkanheal** [comment]
Seems fixed, just tried it on normal (was alone though) I full cleared and wasn't able to fly.

**Comment by ShikoSCS** [comment]
Fixed
