### ISSUE TITLE
Naroua, King of the Forest (LEGION) (WORLD QUEST) (NPC)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1674]
**Links:**
https://www.wowhead.com/quest=48502/naroua-king-of-the-forest
https://www.wowhead.com/npc=126419/naroua

from WoWHead or our Armory

**What is happening:**

Naroua, King of the Forest not counting for the world quest.
No loot

**What should happen:**
Killing Naroua, King of the Forest should count for the world quest.
And have loot.

**Comment by Cefiro-Caecias** [comment]
Fixed.
