### ISSUE TITLE
Sorolis the Ill-Fated (LEGION) (MINI BOSS) (WORLD QUEST)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1675]
**Links:**
https://www.wowhead.com/npc=126889/sorolis-the-ill-fated

from WoWHead or our Armory

**What is happening:**

This one is to give an example but the truth is that there is no mini bosses at all in Mac' Aree to complete the world quest.

**What should happen:**

There should be Mini Boses in their spawmed zone.

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_102520_092058](https://user-images.githubusercontent.com/73371905/97108482-43a0ee80-16a4-11eb-8177-92b165e3370f.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed.
