### ISSUE TITLE
INVASION POINTS (LEGION) (ESCENARIO) (QUEST)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1676]
**Links:**
https://www.wowhead.com/quest=48461/where-they-least-expect-it
https://www.wowhead.com/quest=48513/invasion-point-offensive

from WoWHead or our Armory

**What is happening:**

There are no invasion points spawmed after 1 day waiting.

**What should happen:**

The portal in the pic should be open and sent you to complete the escenario

![WoWScrnShot_102520_093500](https://user-images.githubusercontent.com/73371905/97108754-e1e18400-16a5-11eb-8e0c-895a67e8a967.jpg)

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_102520_100324](https://user-images.githubusercontent.com/73371905/97109399-671a6800-16a9-11eb-90b0-f6c67fb874bd.jpg)
![WoWScrnShot_102520_100327](https://user-images.githubusercontent.com/73371905/97109403-6c77b280-16a9-11eb-865a-031e01b54e61.jpg)
![WoWScrnShot_102520_100335](https://user-images.githubusercontent.com/73371905/97109409-700b3980-16a9-11eb-90c0-b3e9b0c517e2.jpg)
 
Not even the general one about the legion invasion in westfall

**Comment by NightwindOI** [comment]
Hm....horde Invasion work fine.Crossroad etc.

**Comment by Nephilimkoi** [comment]
> Hm....horde Invasion work fine.Crossroad etc.

Close it. it was fixed with the update.
