### ISSUE TITLE
Light's Judgment (LEGION) (ARGUS) (SKILL)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1677]
**Links:**
https://www.wowhead.com/spell=255647/lights-judgment

from WoWHead or our Armory

**What is happening:**

Dosent do any Damange just the visual

**What should happen:**

**Call down a strike of Holy energy, dealing [Attack power * 3 * 1 * (1 + Versatility)] Holy damage to enemies within 5 yards after 3 sec.

![WoWScrnShot_102520_103103](https://user-images.githubusercontent.com/73371905/97110043-5ec42c00-16ad-11eb-90e0-e9a39cdd43c0.jpg)
**

**Comment by ShikoSCS** [comment]
Fixed
