### ISSUE TITLE
azurewing repose zone

### ISSUE THREAD

**Issue by bartimick99** [GuabinaCore/WoWKoi#1679]
**Links:** https://www.youtube.com/watch?v=KuLhyh1KUgM

from WoWHead or our Armory

**What is happening:**
withered skulkers are everywhere in that part of zone,  azurewing repose, 2  senegos  and  ael'yith is there

**What should happen:** that place  should be clear of enemy mobs / npcs, they should  come later in chapter, 
i put video  link from yt where it shows how that part should be

**Comment by Cefiro-Caecias** [comment]
Fixed.
