### ISSUE TITLE
in deep slumber 

### ISSUE THREAD

**Issue by bartimick99** [GuabinaCore/WoWKoi#1680]
**Links:**https://www.wowhead.com/quest=41436/in-deep-slumber

from WoWHead or our Armory

**What is happening:**
bashana runetotem is spaming every sec one  line, corruption is  going kinda  fast

**What should happen:**
she shouldnt spam 1 sentence  and  coruption should go kinda slower up, but im not 100% sure

**Comment by Cefiro-Caecias** [comment]
Fixed.
