### ISSUE TITLE
 [Dungeon Eye of Azshara] - Spell Gaseous Bubbles

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1681]
**Links:**
https://www.wowhead.com/npc=91797/king-deepbeard
https://www.wowhead.com/spell=193018/gaseous-bubbles

from WoWHead or our Armory

**What is happening:**

Gaseous Bubbles you get the debuff... but nothing happens

**What should happen:**

Gaseous Bubbles
Absorbs 250.000 damage.  
Causes a Gaseous Explosion if the bubble is not depleted before expiring.

**Comment by ShikoSCS** [comment]
Please, could you corroborate this data because I tested it and if the spell works
