### ISSUE TITLE
[Dungeon] Eye of Azshara [ NPC] Wandering Shellback

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1683]
**Links:**
https://www.wowhead.com/npc=111633

**What is happening:**
Its Aggressive 

**What should happen:**
Suppose to be Neutral to Ali and Horde until u pull close by NPC and then the Wandering Shellback engage
https://youtu.be/pDrJJwwciX8?t=39
https://i.imgur.com/fJZrf1v.png

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
