### ISSUE TITLE
the scythe of souls

### ISSUE THREAD

**Issue by bartimick99** [GuabinaCore/WoWKoi#1685]
**Links:**
https://www.wowhead.com/quest=37660/the-scythe-of-souls
from WoWHead or our Armory

**What is happening:** its autcomplete for me, i took quest and  could  return in it after

**What should happen:**
i should  talk with Allari the Souleater to break 1 by 1 crystal and then defeat final  demon

**Comment by NightwindOI** [comment]
How suppose to be.
https://www.youtube.com/watch?v=iVwO9G-_PBk

**Comment by NightwindOI** [comment]
Duplicate with https://github.com/GuabinaCore/WoWKoi/issues/1720
