### ISSUE TITLE
[Dungeon] Eye of Azshara [ NPC] Saltsea Droplet 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1686]
**Links:**

https://www.wowhead.com/npc=97172/saltsea-droplet

**What is happening:**
It's aggressive

**What should happen:**
Suppose to be neutral and turn aggressive if u attack something around it.
https://youtu.be/pDrJJwwciX8?t=177

**Comment by Cefiro-Caecias** [comment]
In the wow link that you put, figure that it is aggressive.

**Comment by NightwindOI** [comment]
that's why I put video too :)

**Comment by Cefiro-Caecias** [comment]
So which one is correct? Aggressive or neutral?

**Comment by Cefiro-Caecias** [comment]
Although the wowhead link says it is aggressive, I will put it neutral to avoid claims. Fixed. Available in the next update.
