### ISSUE TITLE
[Dungeon] Eye of Azshara [ NPC] Gritslime Snail

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1687]
**Links:**

https://www.wowhead.com/npc=91786/gritslime-snail
https://www.wowhead.com/eye-of-azshara-dungeon-strategy-guide

**What is happening:**

It's aggressive

**What should happen:**
suppose to be neutral until u pull something around him.
https://www.youtube.com/watch?v=pDrJJwwciX8&t=217s
https://i.imgur.com/XIZpKv4.png

**Comment by Cefiro-Caecias** [comment]
Although the wowhead link says it is aggressive, I will put it neutral to avoid claims. Fixed. Available in the next update.
