### ISSUE TITLE
[Tyce] - The Seat of the Triumvirate Dungeon

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1689]
**Links:**
https://www.wowhead.com/the-seat-of-the-triumvirate
https://www.wowhead.com/npc=122313/zuraal-the-ascended
https://www.wowhead.com/npc=124309/viceroy-nezhar#comments

from WoWHead or our Armory

**What is happening:**
1) when you pull the first 3 mobs all the mobs around the first boss get pulled
2) The first Boss Zuraal the Ascended just stay there waiting to be beaten only cast 2 spells decimate and null palm the rest doesnt do anything
3) The thirth boss... even when you have already killed the 2th boss he keeps being void phased(have a inmunity shield) 

**What should happen:**

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_102620_184518](https://user-images.githubusercontent.com/73371905/97239766-ca4bed80-17c2-11eb-8a4c-9b64867e7fef.jpg)
![WoWScrnShot_102620_193608](https://user-images.githubusercontent.com/73371905/97239769-ccae4780-17c2-11eb-9201-21181e1b1955.jpg)

**1st Boss And 3rd Boss**

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_102720_080021](https://user-images.githubusercontent.com/73371905/97299205-fc913580-182a-11eb-87bd-e30e5150de1e.jpg)


Here is why the 3rd boss in Void Phasing. somehow. for some reason the pet of the 2 th boss ressurects and cannot do anything but evade.

**Comment by Nephilimkoi** [comment]
The time of the Boss and his pet health is off by around 1%. the pet doesnt ressurect. what it happens is that after you kill the boss as his HP is always lower than the pet by that +/- 1% the boss is killed and the pet reset position making it evade all attacks. as when the boss is killed the pet has like 0.5% hp

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
