### ISSUE TITLE
[Class] Mage [Quest] Fire Mage Artifact Weapon quest chain.

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1690]
**Links:**

https://www.wowhead.com/quest=41036/the-dreadlords-prize
https://www.wowhead.com/npc=102700/meryl-felstorm

--------------------------------------------------------------------------------------------
https://www.wowhead.com/quest=40267/an-unexpected-message
https://www.wowhead.com/npc=26673/image-of-archmage-modera

---------------------------------------------------------------------------------
https://www.wowhead.com/npc=99600/frozen-geist
https://www.wowhead.com/npc=99605/frost-block
https://www.wowhead.com/quest=11997/the-frozen-flame
https://www.wowhead.com/npc=98760/iceborn-conjurer
https://www.wowhead.com/spell=198484/chilling-winds

**What is happening:**
When u take ''The Dreadlords Price'' quest, Meryl ''move'' in kneeling animation.
He supposes to walk
When you arrive at the gates nothing happens. If u talk to him, he just teleports you inside.
When he arrives at the gate, they suppose to open by himself---> you talk with him and enter the dungeon.

------------------------------------------------------------------------------
At stage 4, the orb supposes to ''bring you in the air'' until u absorb it. Right now u just stuck at the ground for that time.
At stage 4 , you can bug Kathra to walk in the stairs (most likely Vmap issue).
If u complete stage 4 out of Meryl range, it bugs out /RP doesn't start, so u cant complete the next stage.  (The trigger/count range must be increased dungeon wise).
At stage 5 some visuals are missing and some RP

-------------------------------------------------------------------------------
When u take ''An Unexpected Message'' and use the crystal, Image of Archmage Modera bug out in swim animation.
Suppose to be like that https://youtu.be/0CLj9qdSEyE?t=437

--------------------------------------------------------------------------
When u take ''The Frozen Flame'' and enter the scenario, ''Frost Block'' is missing over ''Frozen Geists''.
''Chilling Winds'' is somehow there, but only parts and do nothing.
When u enter combat with him, ever that he doesn't cast the spell anything, the visual of it is still on the map. The ''wind'' suppose to stop once u enter in combat with him.
In the stage after that, the infernal triggers are there, but the spells are missing.
It supposes to look like that
https://wow.zamimg.com/uploads/screenshots/normal/571187-the-frozen-flame.jpg
Before u complete stage 2 the pack of mobs supposes to path around, not be static.

And at the end, some triggers are supposed to be invisible but they are visible.

---------------------------------------------
All images here. https://imgur.com/a/UbDKr1R
Video of the quest chain.
https://www.youtube.com/watch?v=zxquIyMmlzY

**Comment by Arkanheal** [comment]
I'll add it here, to group it all up

**The Path of Atonement**: https://www.wowhead.com/quest=40270/the-path-of-atonement:

- [Aethas Sunreaver](https://www.wowhead.com/npc=99415/aethas-sunreaver) disappears in the middle of the dialog. He should stay, allowing you to continue the quest chain.

**Comment by Cefiro-Caecias** [comment]
Fixed.
