### ISSUE TITLE
<Paladin>Arcane Torrent  does NOT give Holy Power

### ISSUE THREAD

**Issue by Meresin** [GuabinaCore/WoWKoi#1692]
**Links:**
https://www.wowhead.com/spell=155145/arcane-torrent
from WoWHead or our Armory

**What is happening:**
Does not give 1 Holy Power

**What should happen:**
Give 1 Holy Power

**Comment by Meresin** [comment]
Not sure if fixed, but today it seems to be working

**Comment by ShikoSCS** [comment]
Thanks for the report. Spell fixed
