### ISSUE TITLE
[Class] Arcane Mage [Quest] A New Threat ]

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1693]
**Links:**

https://www.wowhead.com/quest=42006/a-new-threat

**What is happening:**
Ok so, u can complete the quest just by click on the quest item on cooldown without do anything else. If u click on the objects around nothing happen again.

**What should happen:**
As u can see in the clip below that quest is Bind to a Objects. Once u are close to the object u suppose to click on the crystal u got OR on the object and the ''spirit'' gonna spawn and count. You need to click on all 3 types (smallest/medium gate and the dragon skull).
https://www.youtube.com/watch?v=kZxXtB1Qk8M

**Comment by Cefiro-Caecias** [comment]
Fixed.
