### ISSUE TITLE
[Core/Sniff] Dead body's 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1694]
**Links:**

https://ptr.wowhead.com/npc=26280/dragonblight-mage-hunter
https://www.wowhead.com/npc=26816/focus-wizard

**What is happening:**
These two NPCs are just an example. They ''stay'' as dead but at the same time when u click on them, u can see the full health bar. Its a global issue with that type of mobs.

**What should happen:**
They suppose to be like objects, can click on them but they cant despawn or have any health....since dead.

**Comment by Cefiro-Caecias** [comment]
Fixed.
