### ISSUE TITLE
[Class] Mage [Quest] Arcane Mage Artifact Weapon quest chain. 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1695]
**Links:**

https://www.wowhead.com/npc=106706/echo-of-aluneth
https://www.wowhead.com/spell=216901/arcane-barrage

**What is happening:**
Echo of Aluneth cast the barrage, but the spell does nothing.
Once you reach Stage 4 u stuck and can't continue.
https://imgur.com/a/dRqdDsr

**What should happen:**
https://youtu.be/GiatDyLS6Tg?t=1421

**Comment by Cefiro-Caecias** [comment]
Fixed.
