### ISSUE TITLE
A Found Memento (LEGION) (QUEST)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1696]
**Links:**
https://www.wowhead.com/quest=46268/a-found-memento

from WoWHead or our Armory

**What is happening:**

The Battered Trinket isnt anywhere to be seen

**What should happen:**

**_The quest item "Battered Trinket" is under water off the southern tip of the Broken Shore at 53.35, 80.43. It will show up on your mini-map as a !.

It will give you the quest "A Found Memento" which you turn in to Anduin Wrynn in the Stormwind Keep for an AP item that gives 2.1 million AP with AK 30_**

**Comment by Cefiro-Caecias** [comment]
Fixed.
