### ISSUE TITLE
The Highlord's Return (ARTIFACT) (QUESTLINE)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1697]
**Links:**
https://www.wowhead.com/quest=45416/the-highlords-return

from WoWHead or our Armory

**What is happening:**

After last patch up the quest giver is gone

**What should happen:**

NPC should be close to where the mage tower should be

**Comment by Cefiro-Caecias** [comment]
Available when certain conditions are met.
