### ISSUE TITLE
HOLY PALADIN ARTIFACT (LEGION) (QUESTLINE) (ARTIFACT)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1698]
**Links:**
https://www.wowhead.com/quest=42377/the-brothers-trail

from WoWHead or our Armory

**What is happening:**

When you are in the mission **The Brother's Trail** after you fullfill most of the criteria and you are done in the place and come back to **Lanigosa** side she doesnt show you a way back to dalaran and **if you come back to dalaran using a healthstone the criteria doesnt fullfill either** 

**What should happen:**

**Take Lanigosa's ride to Dalaran (OPTIONAL).

Return to Dalaran.**

https://www.youtube.com/watch?v=L1Mtf_kxAqw

**Comment by Cefiro-Caecias** [comment]
Fixed.
