### ISSUE TITLE
Broken Shores Scenario #1 7/9 "Find Tirion" (LEGION)

### ISSUE THREAD

**Issue by ralphhorizon** [GuabinaCore/WoWKoi#1699]
What is happening: Broken Shores scenario stops progressing at 7/9 "Find Tirion 0/1"
RP works up until then and Krosus spawns. Fight commences and he is dead, Sylvannas says "lets go stop gul'dan" but then nothing happens. 

"Find Tirion 0/1" stays uncomplete.

What should happen: Supposed to continue to part 8 and 9 im guessing.

**Comment by Cefiro-Caecias** [comment]
In the process of reconstruction.
