### ISSUE TITLE
[Mob] King Reaperclaw/Sunscale Consort not scaling up to player level

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#170]
**Links:**
https://www.wowhead.com/npc=34829/king-reaperclaw
https://www.wowhead.com/npc=44165/sunscale-consort
**What is happening:**
King Reaperclaw and the 2 Sunscale Consorts that accompany him aren't scaling up to player level.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
