### ISSUE TITLE
No "New Dalaran" Portal in Orgrimmar

### ISSUE THREAD

**Issue by ralphhorizon** [GuabinaCore/WoWKoi#1700]
**What is happening: Boosted to 110 and finished starting zone of Demon Hunter Questline, got ported to Orgrimmar, and was not able to see the portal to New Dalaran in the Cleft of Shadow until a GM gave me a certain quest I was not able to pick up.

**What should happen: Portal should be visible, or quest should be obtainable. Maybe a quick fix for this could be adding a Dalaran hearthstone with the 100/110 boost?

**Comment by Cefiro-Caecias** [comment]
The portals will be visible after completing the quest "In the Blink of an Eye".
