### ISSUE TITLE
To Old Friends Legion Val'sharah Quest

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1702]
**Links:**
https://www.wowhead.com/quest=38582/to-old-friends

from WoWHead or our Armory

**What is happening:**
1) Ysera is phasing 

2) RP is missing upon completion 

_**Know this, <name>. You did the only thing you could.**_
_**When a mortal has become corrupted by the nightmare, there is no return. Only death will set them free.**_

**What should happen:**

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_102820_203614](https://user-images.githubusercontent.com/73371905/97511626-e8018a00-195d-11eb-9b2b-822cb4bb0b79.jpg)
![WoWScrnShot_102820_203624](https://user-images.githubusercontent.com/73371905/97511652-f5b70f80-195d-11eb-8999-6b93540a3fa9.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed.
