### ISSUE TITLE
The Demon's Trail  Quests Legion Val'sharah

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1703]
**Links:**
https://www.wowhead.com/quest=38753/the-demons-trail

from WoWHead or our Armory

**What is happening:**

Tyrande is mounting her pet while stacking on top of her pet 

![WoWScrnShot_102820_204138](https://user-images.githubusercontent.com/73371905/97514474-2c445880-1965-11eb-83e6-8470ba98fea5.jpg)

**What should happen:**

The 2th pet shouldnt be there

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
