### ISSUE TITLE
Softening the Target Quests - Legion - Val'sharah

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1704]
**Links:**
https://www.wowhead.com/quest=43702/softening-the-target

from WoWHead or our Armory

**What is happening:**

1) There are 2 Tyrande
2) **(NEEDS TO BE CONFIRMED BY ANOTHER USER)** Nightwing isnt dysplaying action bar

![WoWScrnShot_102820_214056](https://user-images.githubusercontent.com/73371905/97515266-18015b00-1967-11eb-8057-f105b88dc3e2.jpg)

![WoWScrnShot_102820_214425](https://user-images.githubusercontent.com/73371905/97515277-1b94e200-1967-11eb-8a51-2aa9f8fda99b.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
