### ISSUE TITLE
[NPC] Inquisitor Baleful [Spell] 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1707]
**Links:**

https://www.wowhead.com/npc=93105/inquisitor-baleful

**What is happening:**
Inquisitor Baleful works fine overall, but when he entered the ''phase'' with the infernals there is a problem. The Infernals are x2 (phase problem maybe) and the attacks they do mele and meteor don't do any dmg. At the start of the battle, the beam/eye's that Baleful cast don't do dmg too.

**What should happen:**
Infernals do dmg, eye's do dmg.
https://youtu.be/CgjIK34qDS0?t=58

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt blizzlike later on.
