### ISSUE TITLE
[Quest] Before We're Overrun 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1710]
**Links:**

https://www.wowhead.com/quest=38766/before-were-overrun
https://www.wowhead.com/spell=192604/before-were-overrun-spire-of-woe-area-trigger

**What is happening:**
https://imgur.com/a/5AfZYKa
The quest can be completed and that's all. All other things about it are bugged. There is no RP, the Doom don't ever move from his place. Pillars around him don't work. 

**What should happen:**
That's how suppose to work
Click on the crystals to remove the boom/fire around him.
https://youtu.be/zNOX7K5UExo?t=56

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt blizzlike later on.
