### ISSUE TITLE
[Quest] Hidden No More

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1711]
**Links:**

https://www.wowhead.com/quest=39495/hidden-no-more
https://www.wowhead.com/spell=197180/fel-infusion

**What is happening:**
The NPC is there and that's all. Killed him like 20 times, it counts as complete but marks not appear on the map. All the RP is missing too.
When he uses Fel Infusion there is no dmg. When u attack you without axe the dmg is between 1 to 3.

**What should happen:**

https://youtu.be/1evVdpVTCI0?t=64

**Comment by Arkanheal** [comment]
The quest is finishable though. There is just no marker + dmg/RP problems.

**Comment by Nephilimkoi** [comment]
As of Jan/2021 you cannot go throught the rocks
even tho the rocks do their animation

Reloging seem to do the trick

![WoWScrnShot_010421_132744](https://user-images.githubusercontent.com/73371905/103562695-dd013380-4e91-11eb-984e-958dbd7e03f1.jpg)



![WoWScrnShot_010421_132743](https://user-images.githubusercontent.com/73371905/103562674-d5418f00-4e91-11eb-9238-bbd5def0e493.jpg)

**Comment by Nephilimkoi** [comment]
and it completed in 1 try but visually it doesnt show it

![WoWScrnShot_010421_134224](https://user-images.githubusercontent.com/73371905/103563239-cf987900-4e92-11eb-8354-f415dcd55b7f.jpg)

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_010421_134526](https://user-images.githubusercontent.com/73371905/103563445-2bfb9880-4e93-11eb-989a-24f37795b29c.jpg)
![WoWScrnShot_010421_134533](https://user-images.githubusercontent.com/73371905/103563467-3322a680-4e93-11eb-8332-48071b7be1c3.jpg)

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt blizzlike later on.
