### ISSUE TITLE
[Quest] The Imp Mother's Tome 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1713]
**Links:**

https://www.wowhead.com/quest=40222/the-imp-mothers-tome
**What is happening:**
Quest work and can be completed, but all the RP is missing. There are no nagas to help u or anything.
In the end, when u kill it, they're supposed to be a ''wave'' of minions that want to attack you. Right now there is just a dog and a Felguard spawned at the place at the tunnel.

**What should happen:**
https://youtu.be/tpGLar6Y6bE?t=108

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt blizzlike later on.
