### ISSUE TITLE
Archidruid of Lore Quest  - Legion - Val'sharah

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1716]
**Links:**
https://www.wowhead.com/quest=38235/solid-as-a-rock
https://www.wowhead.com/quest=38225/death-to-the-witchmother

from WoWHead or our Armory

**What is happening:**

You Can accept the quest... and Instantly turn it in. without doing anything. in Both of his quest
1)Solid as a Rock
2)Death to the Witchmother

**What should happen:**

Actually complete the objetives before turn it in the quest

-------------------------1------------------
**Rescue Marnor Lorleaf, Erwind Mistfen and Del'thanar Sagewood.
Marnor Lorleaf Rescued
Erwind Mistfen Rescued
Del'thanar Sagewood Rescued**

-------------------------2------------------
**Magula slain**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
