### ISSUE TITLE
Wisp in the Willows  Quests - Legion - Val'sharah

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1717]
**Links:**
https://www.wowhead.com/quest=39354/wisp-in-the-willows
from WoWHead or our Armory

**What is happening:**

The wisp is missing.

![WoWScrnShot_102920_075504](https://user-images.githubusercontent.com/73371905/97565294-5a08bc00-19bc-11eb-9ab0-0a779a734950.jpg)

**What should happen:**

There should be wisp infront of the NPC after you accept the quest that you can use to grown trees

![](https://wow.zamimg.com/uploads/screenshots/normal/647458-wisp-in-the-willows-quest-giver-syndrelle-and-the-wisp-54-4-68-3.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
