### ISSUE TITLE
Archdruid of the Vale

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1718]
**Links:**
https://www.wowhead.com/quest=38382/archdruid-of-the-vale
from WoWHead or our Armory

**What is happening:**

Phasing in its 2 locations.

**FOR REFERENCE**
![WoWScrnShot_102920_080717](https://user-images.githubusercontent.com/73371905/97573326-f3859d00-19bf-11eb-88eb-0a89daa97fe3.jpg)

**What should happen:**
There should only be 1. the one of the quest you are currently doing.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
