### ISSUE TITLE
The Corruptor Quests - Legion - Val'sharah

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1719]
**Links:**
https://www.wowhead.com/quest=39384/the-corruptor

from WoWHead or our Armory

**What is happening:**

Imposible to turn in. Even if the quest say its completed.

![WoWScrnShot_102920_081943](https://user-images.githubusercontent.com/73371905/97573601-655de680-19c0-11eb-96b8-b2fbe601920f.jpg)

**What should happen:**

After killing the Mob. you go to the girl behind the mob spot and talk with her. to turn in the quest.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
