### ISSUE TITLE
Enemy - Shadowforge Commander

### ISSUE THREAD

**Issue by Loquedog** [GuabinaCore/WoWKoi#172]
**Links:**

https://wowwiki.fandom.com/wiki/Shadowforge_Commander

**What is happening:**
The unit is giving off a devotion aura stat of 3000 additional armour to all nearby units.

**What should happen:**

Should only be 300 at best.

**Comment by Cefiro-Caecias** [comment]
This NPC no longer executes powers. Eliminated combat spell. It was also not scaled. Repaired. Available in the next update.

https://www.wowhead.com/npc=2744
