### ISSUE TITLE
The Scythe of Souls Quests - Legion - Azsuna

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1720]
**Links:**
https://www.wowhead.com/quest=37660/the-scythe-of-souls

from WoWHead or our Armory

**What is happening:**

3rd Cristal is missing

**What should happen:**

There should be a 3rd cristal in the area that you can click and do the rest of the quest 

**Soul Gem entered
Arev'naal compelled
Leave soul gem
Meet back up with Allari**

**Credit to Windyy**

**Comment by NightwindOI** [comment]
Must be fixed now, please retest.

**Comment by Cefiro-Caecias** [comment]
Fixed.
