### ISSUE TITLE
Entangled Dreams Quests - Legion - Val'sharah

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1721]
**Links:**
https://www.wowhead.com/quest=38147/entangled-dreams

from WoWHead or our Armory

**What is happening:**

There should be a visual Wall that you have to click to pass through to get to the NPC is. The wall is there but its invisible

And killing the NPC isnt counting to the Quest.

![WoWScrnShot_102920_090110](https://user-images.githubusercontent.com/73371905/97577191-7826ea00-19c5-11eb-9780-72f4eb296b74.jpg)
![WoWScrnShot_102920_090035](https://user-images.githubusercontent.com/73371905/97577181-74936300-19c5-11eb-969d-0e9a40165e8e.jpg)

**What should happen:**

Open the Bramble Wall

Morphael slain

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
