### ISSUE TITLE
Stromkar questline

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1723]
**Links:**
https://www.wowhead.com/quest=41105/the-sword-of-kings
from WoWHead or our Armory

**What is happening:**

After executing Zakajz the Corruptor he is still alive with small amount of hp. (and still unkillable)
There is no portal to Skyhold.
**What should happen:**

Zakajz should die.
There hould be portal to Skyhold.

**Comment by Cefiro-Caecias** [comment]
Fixed.
