### ISSUE TITLE
Ravencrest's Legacy Quests - Campaigns - Order Hall

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1725]
**Links:**
https://www.wowhead.com/quest=44479/ravencrests-legacy
https://www.wowhead.com/quest=44479/ravencrests-legacy#videos:id=105362
from WoWHead or our Armory

**What is happening:**

The event that triggers the escenario isnt appearing at all
 
![WoWScrnShot_102920_140231](https://user-images.githubusercontent.com/73371905/97614135-f26c6400-19ef-11eb-9aae-30de34358631.jpg)

![WoWScrnShot_102920_140241](https://user-images.githubusercontent.com/73371905/97614147-f6988180-19ef-11eb-9467-4380f1ac557c.jpg)

**What should happen:**

when you get to the area you should see an action buttoms to that when you click it should take you to the escenario

**Comment by Cefiro-Caecias** [comment]
Autocomplete temporal fix. Available in the next update.
