### ISSUE TITLE
Destiny Unfulfilled Quests - Campaigns - Order Hall

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1726]
**Links:**
https://www.wowhead.com/quest=44481/destiny-unfulfilled
https://www.youtube.com/watch?v=JPOyvNDVmoo
from WoWHead or our Armory

**What is happening:**

Same as https://github.com/GuabinaCore/WoWKoi/issues/1725

The action buttom that supossed triggers the event. doesnt appear.

**What should happen:**

An Action buttom should appear when you come close to the door and when you press it a tiny cinematic should happen and then you become ilidan

**Comment by Cefiro-Caecias** [comment]
Autocomplete temporal fix. Available in the next update.
