### ISSUE TITLE
[Quest-Stormheim] - Shielded Secrets

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1727]
**Links:**
https://www.wowhead.com/quest=38878/shielded-secrets

from WoWHead or our Armory

**What is happening:**

1) Objetive 1 can be completed by clicking multiples times 1 shield
**Examine Engraved Shields (6)**

2) Quest Objetives in display are in spanish

![WoWScrnShot_102920_165744](https://user-images.githubusercontent.com/73371905/97632953-ae865880-1a09-11eb-9ce9-6dbf29663526.jpg)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
