### ISSUE TITLE
[Quest-Stormheim] - Built to Scale

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1729]
**Links:**
https://www.wowhead.com/quest=38337/built-to-scale
https://www.wowhead.com/item=122610/storm-drake-scale
from WoWHead or our Armory

**What is happening:**

Some dragons dont move at all and like standing on the air
Some dragons are invalid target
Some dragons that are standing cannot be attacked as it show that target is not in line of sight

![WoWScrnShot_102920_162248](https://user-images.githubusercontent.com/73371905/97633929-4173c280-1a0b-11eb-9c70-2f36b75ce02a.jpg)

Quest For some reason it complete itself at a random ammount of scales but when you turn it in you cant as there is no enough scales

![WoWScrnShot_102920_162322-1](https://user-images.githubusercontent.com/73371905/97634038-6cf6ad00-1a0b-11eb-9f99-24e05e1b2bef.jpg)

There is a scale that the dragons drop that you can click it to get the same quest. but it says that its the wrong faction and when you click it multiple times you get it as many times as you accept the quest

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
