### ISSUE TITLE
Signal Boost Quests - Legion - Stormheim

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1730]
**Links:**
https://www.wowhead.com/quest=38060/signal-boost
from WoWHead or our Armory

**What is happening:**

Alert is in russian and mobs fly in a weird way

![WoWScrnShot_102920_153723](https://user-images.githubusercontent.com/73371905/97634506-39685280-1a0c-11eb-8eed-403de0a034fd.jpg)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
