### ISSUE TITLE
Dark Revelations Quests - Legion - Azsuna

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1732]
**Links:**
https://www.wowhead.com/quest=37449/dark-revelations
https://www.wowhead.com/npc=90982/stellagosa
from WoWHead or our Armory

**What is happening:**

Nightglaive the Traitor slain
Ride back to Illidari Stand **(OPTIONAL)**
Meet back at Illidari Stand

The quest itself doesnt have major problems but the NPC Stellagosa ID (90982) is way too high and you cant reach her to mount her back.

Tho if you try to walk your way back. the quest doesnt complete when you reach the location the quest doesnt complete even tho riding stellagosa is optional.

Also... she is already on the place before you kill the traitor. and she should only be there after you kill him 

**What should happen:**

She should be on hand reach so you can easily mount her or easily complete the quest by getting to the location on your own

https://www.youtube.com/watch?v=4l5fDL7OOE4

**Comment by NightwindOI** [comment]
Added to that, if u are range u can just nuke the NPC since he doesn't move from the spot.
https://imgur.com/a/8Kn7Fmc

**Comment by NightwindOI** [comment]
Must be fixed , please retest.

**Comment by Cefiro-Caecias** [comment]
Fixed.
