### ISSUE TITLE
Defending Azurewing Repose

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1733]
**Links:**
https://www.wowhead.com/quest=37853/the-death-of-the-eldest
https://www.wowhead.com/quest=37991/agapanthus
https://www.wowhead.com/npc=91157/withered-outcast
from WoWHead or our Armory

**What is happening:**

1)The Death of the Eldest
Apart from the fact that the cristals have a ridiculous low drop chances that you have to wipe out the entire cave to get them. 
The mobs gang attack Stellelagosa in waves killing her faster than you can get to her to complete the quest.

**RIP STELLAGOSA**
![WoWScrnShot_103020_022904](https://user-images.githubusercontent.com/73371905/97671159-19fa1580-1a5e-11eb-876d-df2c4225f790.jpg)

2)Agapanthus
Same happens here. the mobs are killing Agapanthus before you can do anything

3) Which bring us to the 3rd issue. when the mobs fight the NPC even tho the mobs hit 0% they are kept alive till a player kill them.

![WoWScrnShot_103020_025104](https://user-images.githubusercontent.com/73371905/97671215-30a06c80-1a5e-11eb-826f-822905b8732d.jpg)

**What should happen:**

**Comment by NightwindOI** [comment]
Must be fixed, please retest.

**Comment by Cefiro-Caecias** [comment]
Fixed.
