### ISSUE TITLE
The Haunted Halls Quests - Legion - Azsuna

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1734]
**Links:**
https://www.wowhead.com/quest=42370/wanding-101
https://www.wowhead.com/quest=42371/study-hall-combat-research
https://www.wowhead.com/quest=37729/pop-quiz-advanced-rune-drawing
from WoWHead or our Armory

**What is happening:**

Can be completed without doing anything. the items or actions either automatically complete or they get in your bag as soon as you take the quest

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Temporal Autocomplete Fix.
