### ISSUE TITLE
Return to Sender Quests - Legion - Dalaran

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1735]
**Links:**
https://www.wowhead.com/quest=46278/return-to-sender
from WoWHead or our Armory

**What is happening:**

There should be letters flying around the room for the player to pick up but there is none

![WoWScrnShot_103020_053154](https://user-images.githubusercontent.com/73371905/97689098-79adec00-1a71-11eb-9d19-700c672c68eb.jpg)

**What should happen:**

![697799-return-to-sender](https://user-images.githubusercontent.com/73371905/97689343-cbef0d00-1a71-11eb-907d-6c80b7e6c411.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
