### ISSUE TITLE
[MISC] Russian/Spanish text Part 1

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1736]
**Links:**

https://imgur.com/a/ZbSqqD4

**What is happening:**
If not sure what is wrong check bottom right (mouseover) . It's there or on the screen.

**What should happen:**

**Comment by Nephilimkoi** [comment]
Hijacking your post to report these guys too
I cant seem to find the quest in wowhead or anywhere tbh but its from the special events in dalaran. you get there using the table infront of the NPC



![WoWScrnShot_102820_182323](https://user-images.githubusercontent.com/73371905/97731282-4ee08980-1aab-11eb-9cc6-3c44fc9b135e.jpg)

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_103020_123705](https://user-images.githubusercontent.com/73371905/97732314-bea34400-1aac-11eb-8c45-19e58d75ae95.jpg)

Also the automatic letter you get after completing the first quest from the postmaster questline

**Comment by NightwindOI** [comment]
https://imgur.com/a/BUlByhx (check the mouseover)
https://imgur.com/a/tYwXlku
The chest name https://imgur.com/a/TYMclJA
https://imgur.com/a/oIJ4BSJ mouseover
https://imgur.com/a/DkQnMTO

**Comment by NightwindOI** [comment]
Related https://github.com/GuabinaCore/WoWKoi/issues/1761

**Comment by NightwindOI** [comment]
https://imgur.com/a/kjvjNEk

**Comment by NightwindOI** [comment]
Related
https://github.com/GuabinaCore/WoWKoi/issues/1814

**Comment by NightwindOI** [comment]
related
https://github.com/GuabinaCore/WoWKoi/issues/1874

**Comment by NightwindOI** [comment]
related
https://github.com/GuabinaCore/WoWKoi/issues/1912

**Comment by Cefiro-Caecias** [comment]
Fixed almost all translations, except for a few NPCs that I couldn't identify. Available in the next update. Don't forget to clear Cache.
