### ISSUE TITLE
[Mob] Theramore Marine, Theramore Deck Hand, Theramore Preserver, Theramore Sharpshooter, Lieutenant Pyre, Lieutenant Buckland not scaling up

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#174]
**Links:**
https://classic.wowhead.com/npc=3385/theramore-marine
https://www.wowhead.com/npc=34707/theramore-deck-hand
https://classic.wowhead.com/npc=3386/theramore-preserver
https://www.wowhead.com/npc=34706/theramore-sharpshooter
https://www.wowhead.com/npc=34752/lieutenant-pyre
https://www.wowhead.com/npc=34753/lieutenant-buckland
**What is happening:**
None of these mobs are scaling up with player level.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
