### ISSUE TITLE
[Class] Rogue [Zone] Hall of Shadows

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1741]
**Links:**

https://imgur.com/a/nmdvmEr
https://www.wowhead.com/champion=779/lord-jorach-ravenholdt#quests
**What is happening:**
The RP about the quest is double. Somehow u can bug it out and won't be able to stand up since the RP/quest stuck.
There is some strange rabbit that following me.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
