### ISSUE TITLE
Quests- Legion- Highmountain - Phasings

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1742]
**Links:**
https://www.wowhead.com/quest=42590/moozys-reunion

from WoWHead or our Armory

**What is happening:**

NPCS inside the hut of the main city of Highmountain are phasing 
When you get inside the hut they simply disapear..

**What should happen:**

The NPCS should stay in phase.

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_103020_130510](https://user-images.githubusercontent.com/73371905/97735838-3f643f00-1ab1-11eb-9bc0-4a2f8283e61c.jpg)
![WoWScrnShot_103020_130547](https://user-images.githubusercontent.com/73371905/97736026-79cddc00-1ab1-11eb-8d55-a7854d45281d.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed.
