### ISSUE TITLE
Eye of Azshara: Wrath of Azshara Quests - Dungeons - Eye of Azshara

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1743]
**Links:**
https://www.wowhead.com/quest=38286/eye-of-azshara-wrath-of-azshara

from WoWHead or our Armory

**What is happening:**

First objetive isnt completing when entering the dungeon solo /in party

Eye of Azshara entered 
Warlord Parjesh slain
Wrath of Azshara slain

**What should happen:**
Entering the dungeon should complete the first objetive

![WoWScrnShot_103020_211524](https://user-images.githubusercontent.com/73371905/97767981-2631b180-1af6-11eb-95b7-b8cac131f39b.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.

**Comment by Dragonsworn** [comment]
First objective not completing, Eye of Azshara Entered is not registering.
