### ISSUE TITLE
Burn the Candle at Both Ends Quests - Legion - Highmountain

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1744]
**Links:**
https://www.wowhead.com/quest=40345/burn-the-candle-at-both-ends
https://www.wowhead.com/quest=40339/candle-of-command
from WoWHead or our Armory

**What is happening:**

its repeating the script of the last quest 
**https://www.wowhead.com/quest=40339/candle-of-command**

![WoWScrnShot_103120_001903](https://user-images.githubusercontent.com/73371905/97770995-f347e780-1b0e-11eb-9c0e-30dbc448f9af.jpg)

**What should happen:**

https://www.youtube.com/watch?v=xY_xCsMB06Q

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
