### ISSUE TITLE
Storyline Skyhorn Tribe Quests - Legion - Highmountain

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1745]
**Links:**
https://www.wowhead.com/quest=39318/nursing-the-wounds
https://www.wowhead.com/quest=38913/the-skyhorn-tribe
from WoWHead or our Armory

**What is happening:**

NPC isnt giving the follow up Quest 
https://www.wowhead.com/quest=39318/nursing-the-wounds
![WoWScrnShot_103120_004027](https://user-images.githubusercontent.com/73371905/97771290-afa2ad00-1b11-11eb-8514-c3b41f17a9f3.jpg)

**What should happen:**
After turning in https://www.wowhead.com/quest=38913/the-skyhorn-tribe
NPC should give https://www.wowhead.com/quest=39318/nursing-the-wounds

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
