### ISSUE TITLE
Huln's War - The Nathrezim  Quests - Legion - Highmountain 

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1746]
**Links:**
https://www.wowhead.com/quest=39992/hulns-war-the-nathrezim

from WoWHead or our Armory

**What is happening:**

after killing the boss you get stuck in the zone.

**What should happen:**

You should get either teleported out after you kill the boss. or after 10-15min in the zone

**So, after defeating Tichondrius, at the moment there is a risk of getting booted out of the "vehicle" (Huln), and remaining at Azshara. At this point, there is nothing you can do to get out (except maybe getting summoned out by a warlock, did not test that). Hearthstones don't work, CM portals don't work. Logging out doesn't work. After maybe 10-15 minutes I got auto-teleported out (to Val'sharah, of all places), so don't despair about having to go through Legion launch ticket queue times.**

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_103120_104033](https://user-images.githubusercontent.com/73371905/97782936-e78a0e80-1b6a-11eb-8ce8-13a16d11c8bd.jpg)


You can use Hearthstone when you shouldnt be able. **tho its better like this**

**Comment by Cefiro-Caecias** [comment]
Fixed.
