### ISSUE TITLE
Can't Hold a Candle To You Quests - Legion - Highmountain

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1747]
**Links:**
https://www.wowhead.com/quest=39772/cant-hold-a-candle-to-you

from WoWHead or our Armory

**What is happening:**

Cant reach the candleking 

![WoWScrnShot_103120_093250](https://user-images.githubusercontent.com/73371905/97783037-7139dc00-1b6b-11eb-81e7-1c54e1dead8a.jpg)

**Recover Oenia's Skull from the Candleking.**
**Oenia's Skull**
**Gate of the Candleking**

**What should happen:**

![maxresdefault](https://user-images.githubusercontent.com/73371905/97783067-9dedf380-1b6b-11eb-9845-390101e3dc78.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
