### ISSUE TITLE
The Bloodtotem Tribe Quests - Legion - Highmountain

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1748]
**Links:**
https://www.wowhead.com/quest=38912/the-bloodtotem-tribe
https://www.wowhead.com/npc=93826/mayla-highmountain
from WoWHead or our Armory

**What is happening:**

npc=93826/mayla-highmountain isnt giving the quest.

**What should happen:**

After completing a few storylines the quest should just get enabled

![WoWScrnShot_103120_132848](https://user-images.githubusercontent.com/73371905/97785693-085b5f80-1b7d-11eb-9041-85b7408d4552.jpg)

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_103120_133906](https://user-images.githubusercontent.com/73371905/97786017-fc709d00-1b7e-11eb-960f-0480387cc03b.jpg)




**Even If you get the quest by GM help... the quest cant be turned in**

**Comment by Howizter** [comment]
Now you can complete quest but there is no follow up quests in chain to take

**Comment by Cefiro-Caecias** [comment]
Fixed.
