### ISSUE TITLE
Warrior Fury Artifact Weapon

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1749]
**Links:**
https://www.wowhead.com/quest=40043/the-hunter-of-heroes
from WoWHead or our Armory

**What is happening:**
1. Falling at start is extremely slow.
2. At the end, you should jump back to skyhold.

**What should happen:**
1. Fast fall.
2. Area with opinion of jump.

**Comment by Cefiro-Caecias** [comment]
Fixed.
