### ISSUE TITLE
[Mob] Southsea Privateer, Southsea Cutthroat, Glomp not scaling up

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#175]
**Links:**
https://classic.wowhead.com/npc=3384/southsea-privateer
https://classic.wowhead.com/npc=3383/southsea-cutthroat
https://www.wowhead.com/npc=34747/glomp
**What is happening:**
None of these mobs are scaling up.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
