### ISSUE TITLE
Chosing another artifact ot pursuit.

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1750]
**Links:**
https://www.wowhead.com/quest=43949/more-weapons-of-legend
from WoWHead or our Armory

**What is happening:**

1. No progress, when chosing another artifact.
2. Can't complete quest.

**What should happen:**
You should get progress and be able complete quest.

**Comment by asecine** [comment]
also happens whit hunters

**Comment by Cefiro-Caecias** [comment]
Fixed.
