### ISSUE TITLE
Warrior Protection artifact quest

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1751]
**Links:**
https://www.wowhead.com/quest=39191/legacy-of-the-icebreaker
from WoWHead or our Armory

**What is happening:**
1. There is no teleport to skyhold.

**What should happen:**
1. There should be teleport to skyhold.

**Comment by Arkanheal** [comment]
Might have been patched but there is teleport to Skyhold now. But you don't get credit for "Speak to Hruthnir" step of the quest which makes it undoable

**Comment by Cefiro-Caecias** [comment]
Fixed.
