### ISSUE TITLE
[Zone] Azsuna [NPC] Rare list

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1752]
**Links:**

https://www.wowhead.com/npc=109641/arcanor-prime
https://www.wowhead.com/npc=90244/arcavellus

**What is happening:**
Arcanor prime is missing
Arcavellus is there be default. Missing the ''event'' to summ him.
Continue later

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
