### ISSUE TITLE
Bad Apples Quests - Legion - Suramar

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1753]
**Links:**
https://www.wowhead.com/quest=41107/bad-apples

from WoWHead or our Armory

**What is happening:**

There are no flowers to loot Shadowbloom x(8)

![WoWScrnShot_110120_174517](https://user-images.githubusercontent.com/73371905/97913394-97ef4280-1d24-11eb-9de5-0f42d771f03c.jpg)

**What should happen:**

There should be some flowers around the flogs area

![562213](https://user-images.githubusercontent.com/73371905/97913311-7beba100-1d24-11eb-8dcc-caa79336fc70.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
