### ISSUE TITLE
Dispensing Compassion Quests - Legion - Suramar

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1754]
**Links:**
https://www.wowhead.com/quest=41148/dispensing-compassion

from WoWHead or our Armory

**What is happening:**

Even if you revive everyone the quest doesnt complete and therefore cannot be turned in

Sometimes if you click fast enough 1 person it counts as several. futher bugging the quest
**What should happen:**

After going to every family member the quest should complete itself.

Citizens Revived (4)

Mother Revived
Brother Revived
Husband Revived
Neighbor Revived

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
