### ISSUE TITLE
NPC following even after killing

### ISSUE THREAD

**Issue by upal212** [GuabinaCore/WoWKoi#1756]
**Links:**

https://imgur.com/a/KPW5KBj
https://classic.wowhead.com/npc=732/murloc-lurker

**What is happening:**

Murloc Lurker is following even after killing the NPC near Stone Cairn Lake, Elwynn Forests - as shown on the screenshot

**What should happen:**

NPC should die and not follow you after.

**Comment by NightwindOI** [comment]
Didn't seen it so far in Legion so it may be a specific NPC problem...or it's a core issue. Thx for the report!

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
