### ISSUE TITLE
[Quest] Time is of the Essence [Class] Demon Hunter

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1758]
**Links:**

https://www.wowhead.com/quest=41067/time-is-of-the-essence
https://www.wowhead.com/npc=95240/kayn-sunfury

**What is happening:**

The quest work fine, but Kayn doesn't change the phase so u cant turn the quest and can't take the next one.
It works only on GM mode since u can see all the phases.

**What should happen:**
Kayn must spawn at the top and the phase must be changed
https://www.youtube.com/watch?v=heZdJkJZYyM

**Comment by Cefiro-Caecias** [comment]
Pending complete reconstruction of the area.
