### ISSUE TITLE
[Quest]  in the house of light and shadow

### ISSUE THREAD

**Issue by asecine** [GuabinaCore/WoWKoi#1759]
https://www.wowhead.com/quest=44448/in-the-house-of-light-and-shadow

from WoWHead or our Armory

can´t complete in the class hall

quest mark  in the light´s heart didn´t appear

**Comment by Arkanheal** [comment]
I might add that you shouldn't be able to pick this quest before doing this [one](https://www.wowhead.com/quest=44338/goddess-watch-over-you) or this [one](https://www.wowhead.com/quest=44337/goddess-watch-over-you)

**Comment by Cefiro-Caecias** [comment]
Fixed.
