### ISSUE TITLE
evento de arma artefacto, priest/shadow

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#1761]
![WoWScrnShot_111020_135027](https://user-images.githubusercontent.com/44954266/98714624-7f53dd80-235f-11eb-985c-ad2aa5be9d19.jpg)
![WoWScrnShot_111020_135045](https://user-images.githubusercontent.com/44954266/98714629-81b63780-235f-11eb-8330-7cb2ffc82354.jpg)
![WoWScrnShot_111020_135052](https://user-images.githubusercontent.com/44954266/98714634-837ffb00-235f-11eb-9770-09bf5a7c3954.jpg)
NO PERMITE TOMAR NINGUNA DE LAS 3 PISTAS @ShikoSCS

**Comment by NightwindOI** [comment]
Hello there. Thx for the report, but can u please do them in English and don't tag the devs. 
Thx again!
Sorted in here with the other problems https://github.com/GuabinaCore/WoWKoi/issues/1761
