### ISSUE TITLE
[Quest] Death Comes From On High [Class] Death Knight

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1764]
**Links:**

https://www.wowhead.com/quest=12641/death-comes-from-on-high

**What is happening:**
If u are Unholy and Summ Gnoll (Raise Dead) before u take the quest after u click on the pillar the ''Eye'' doesn't have any spells since the pet bar Overwrite them or something like that. If u click on the Pillar without a pet...the eye works perfectly.

**What should happen:**
May add a condition to de-spawn the pet before the object spawns the eye. No matter what the ''Eye'' must have spells.

**Comment by Cefiro-Caecias** [comment]
Pending complete reconstruction of the area.
