### ISSUE TITLE
[Quest] The Gift That Keeps On Giving [Class] Death Knight

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1765]
**Links:**

https://www.wowhead.com/quest=12698/the-gift-that-keeps-on-giving

**What is happening:**
If u are Unholy/have a pet, once u take that quest the pet bar disappears and u can't control the pet. 
Ever after u complete the quest, the pet bar bug out and u need to relog to fix it.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Pending complete reconstruction of the area.
