### ISSUE TITLE
[Quest] [Massacre At Light's Point] [Class] Death Knight

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1766]
**Links:**

https://www.wowhead.com/quest=12701/massacre-at-lights-point

**What is happening:**
Quest works fine, but the ship on the left (down one)  somehow is bugged. The cannons are close to useless. The other ship work just fine.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Pending complete reconstruction of the area.
