### ISSUE TITLE
[Spell] Dominion Over Acherus

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1767]
**Links:**

https://www.wowhead.com/spell=51721/dominion-over-acherus
**What is happening:**
The spell work, but not on every flour. Got the buff sparkle effect but not the movement speed one. ( If u take a fly from outside to the crypt u can reproduce it )

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Pending complete reconstruction of the area.
