### ISSUE TITLE
[Quest] A Meeting With Fate [Class] Death Knigh

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#1769]
**Links:**

https://www.wowhead.com/quest=12755/a-meeting-with-fate
https://www.wowhead.com/spell=53081/scarlet-crusade-disguise

**What is happening:**
The  Scarlet Crusade Disguise trigger too late (when u are almost on the beach)

**What should happen:**
Suppose to trigger like 2 sec after u take the quest
https://www.youtube.com/watch?v=rvyEKnNl1DI

**Comment by Cefiro-Caecias** [comment]
Pending complete reconstruction of the area.
