### ISSUE TITLE
warrior questline

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#1771]
https://www.wowhead.com/quest=38904/return-to-the-broken-shore

al llegar a broken shore en evento no avanza, se queda en el step 1
![WoWScrnShot_111720_200756](https://user-images.githubusercontent.com/44954266/99465488-f0236880-2910-11eb-8664-8e846c2c397a.jpg)
![WoWScrnShot_111720_200823](https://user-images.githubusercontent.com/44954266/99465495-f3b6ef80-2910-11eb-8db7-de4cd8848c10.jpg)

**Comment by NightwindOI** [comment]
Hey, thx for the report, but can u do it in English so the rest of us can understand the issue too.

**Comment by Arkanheal** [comment]
Just to add something to that, the scenario works but the stage on the UI aren't the right ones
