### ISSUE TITLE
[Spell][Talent] Fellblade

### ISSUE THREAD

**Issue by notrinium** [GuabinaCore/WoWKoi#1772]
Demon hunters lvl 99 talent "Fellblade" worked as intended at start, but became unusable after logging off.  The spell is gone from the players spellbook.

**Comment by NightwindOI** [comment]
https://www.wowhead.com/spell=213241/felblade Thats the spell ID
@notrinium  please delete your cache folder or try without addons.The spell work just fine to me.

**Comment by ShikoSCS** [comment]
This spell work fine
