### ISSUE TITLE
[Quest][DH][Artifact] The Hunt

### ISSUE THREAD

**Issue by notrinium** [GuabinaCore/WoWKoi#1775]
**Links:**

https://www.wowhead.com/quest=41119/the-hunt#videos:id=154705

**What is happening:**

The quest does not transition into Stage 3 - Wrath of the Illidari, where the player is tasked with killing demons and clicking Fellshield Wards. I've tried clicking all three wards and killing a bunch of demons, but I could not proceed.

**What should happen:**
The quest should enter stage 3 after the player lands into the area

Edit: Fixed itself after dropping&repicking the quest. However, the final cutscreen of the quest (right before stage 4, where you fight the boss) lasts longer than it should (about 2-3 minutes for a normally 10 sec cutscreen). Quest is completable. 

Edit2: The final boss spams /yells rapidly, enough to cause a mild lag.

**Comment by Cefiro-Caecias** [comment]
Fixed.
