### ISSUE TITLE
[Quest] - Fate of the horde (40522)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1777]
**Links:** https://www.wowhead.com/quest=40522/fate-of-the-horde

from WoWHead or our Armory

**What is happening:**
The quest asks you to report to Saurfang -- no problem
Then Saurfang, teleports you inside Grommash Hold, but the cinematic starts before the step "Enter the Grommash Hold" validates which makes you unable to complete the beginning of Legion.

**What should happen:**
All steps should validate allowing to continue your questing

**Comment by NightwindOI** [comment]
by any % that u use the mini client? If not please delete the cache folder. I Done that quest like 10 times in the last week with 0 problems.

**Comment by Arkanheal** [comment]
I don't really understand what you mean by mini client (I think I might have the full client 50-ish Gigs of download). Tried to delete the cache folder. Doesn't work. I'll try on another character

**Comment by Arkanheal** [comment]
Nope doesn't work on my tank either. My client is fairly old though, first server Beta access. Could this be the problem?

**Comment by Arkanheal** [comment]
Update: 

- Tried with and without addons.
- Tried with a new full install (the 45G DL)

None worked

**Comment by Arkanheal** [comment]
Fixed.
