### ISSUE TITLE
[Quest/Cinematic] - The Battle for Broken Shore (44543)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1778]
**Links:** https://www.wowhead.com/quest=44543/the-battle-for-broken-shore

from WoWHead or our Armory

**What is happening:**
Multiple micro-bugs during this scenario.

- Some NPCs evade leaving you bugged in combat in phase 2, 4 and the last one
- During the battle against Krosus (as Horde) when Krosus goes back to Alliance side, Horde NPCs follow him which lead to flying NPCs (cf screenshot)
- The end cinematic when Horde and Alliance escapes plays 2 times, the first time it cuts when Varian jumps to free the battleship from the huge demon. The second time it plays fully.

**What should happen:**
- NPCs shouldn't evade
- NPCs shouldn't follow Krosus on the platform that is not their factions'
- The end cinematic should not cut/repeat
![WoWScrnShot_112220_123828](https://user-images.githubusercontent.com/27277903/99903191-2a9b5580-2cc3-11eb-8280-eb89b815b528.jpg)

**Comment by NightwindOI** [comment]
Both scenarios (Ali and Horde)  will be wiped and re-writed since as u may see....they are a mess.
