### ISSUE TITLE
[Quest] Unbridled Power

### ISSUE THREAD

**Issue by notrinium** [GuabinaCore/WoWKoi#1779]
**Links:**

https://www.wowhead.com/quest=41037/unbridled-power#comments

**What is happening:**

At the end of the short scripted event, the questgiver does not phase back properly, making it impossible to turn the quest in. However, logging off and then back in sends the questgiver back to its default position, making the quest semi-working.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
I just tried the quest and it didn't give me any problems o.O
