### ISSUE TITLE
The sword of kings - protection warrior legendary weapon quest

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1782]
**Links:**

https://www.wowhead.com/quest=39191/legacy-of-the-icebreaker

**What is happening:**

(Although the quest is completable, there are a few clunky mechanics that need to be polished.)
------------------------------------

https://www.wowhead.com/npc=96455/swirling-storms
1. Swirling storms when attacked, they run away causing Hruthnir to chase them into the wall and get stuck.
 - Swirling storms should have fixed path of movement.

----------------

https://www.wowhead.com/npc=96034/magnar-icebreaker
2. In the first phase Magnar can be killed before finishing the dialogue (for example by changing spec from prot to fury). It causes the whole script to get stuck. (reset required)

----------------

3. After completing the scenario, quest objectives are not completed, leaving a dead quest in the questlog. (Presumably an issue that happens in other artifact wep scenarios)

**Comment by Cefiro-Caecias** [comment]
Fixed.
