### ISSUE TITLE
Bringer of the light

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1784]
**Links:**

https://www.wowhead.com/quest=44004/bringer-of-the-light

**What is happening:**

Dying during scenario teleports the player into the void, forcing to alt+F4. In result, the event is reset.

**What should happen:**

According to wowhead comments "if you do die, when you release, you spawn fully alive and healed standing with several friendly NPC's".

**Comment by Cefiro-Caecias** [comment]
Fixed.
