### ISSUE TITLE
quest line

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#1785]
la mision https://www.wowhead.com/quest=42740/the-battle-for-broken-shore
esta en autocompletar

y la mision https://www.wowhead.com/quest=40517/the-fallen-lion no avanza 

![WoWScrnShot_112320_211952](https://user-images.githubusercontent.com/44954266/100035824-64f51780-2dd5-11eb-889d-b27a02ca15a9.jpg)
![WoWScrnShot_112320_213637](https://user-images.githubusercontent.com/44954266/100035834-68889e80-2dd5-11eb-9955-9dea46cde198.jpg)

**Comment by Cefiro-Caecias** [comment]
Ya Arthas está terminando de reconstruir todo eso. Paciencia ^^
