### ISSUE TITLE
Hardstuck tp into void

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1787]
I won't follow the usual process. As it's fairly unusual.
So I was on my druid, made the first quest for the _heart of light_ (with the Velen/Exodar scenario) then brought back my heart of light at my order hall. After completing the quest, I see that I can click on the _heart of light_ using the _Tear of Elune_ (that I don't have). Then I'm tped in the **Great Dark Beyond** and fall down to my death without the ability to res/unstuck with the help tab.

**Comment by Arkanheal** [comment]
Quest related to me clicking is:
[The house Light and Shadow](https://www.wowhead.com/quest=44448/in-the-house-of-light-and-shadow) ID: **44448**

**Comment by Cefiro-Caecias** [comment]
Fixed.
