### ISSUE TITLE
[Quest-Stormheim] - The dark lady's bidding

### ISSUE THREAD

**Issue by artycice** [GuabinaCore/WoWKoi#1791]
https://www.wowhead.com/quest=38872/the-dark-ladys-bidding

Npc https://www.wowhead.com/npc=93624/dread-rider-cullen **Dread-rider cullen** doesn't fly you to the corresponding spot(54.55, 72.95)

The said npc should fly or teleport you there.
![WoWScrnShot_112420_210904](https://user-images.githubusercontent.com/74986688/100142463-97b61300-2e9c-11eb-80b1-ce179c678926.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed.
