### ISSUE TITLE
[Quest-Stormheim] - Turn the Keys

### ISSUE THREAD

**Issue by artycice** [GuabinaCore/WoWKoi#1792]
https://www.wowhead.com/quest=38778/turn-the-keys

It doesn't register the using of those runes.

Should register the credit bunny after using them.( Quest is not important as it doesn't affect overall progression for stormheim chapters)

**Comment by Arkanheal** [comment]
Worked fine for me this morning (except animation bug see #1897 )

**Comment by Cefiro-Caecias** [comment]
Fixed.
