### ISSUE TITLE
[Quest-Stormheim] - Stormheim's Salvation

### ISSUE THREAD

**Issue by artycice** [GuabinaCore/WoWKoi#1793]
https://www.wowhead.com/quest=40005/stormheims-salvation

Npc https://www.wowhead.com/npc=92307/god-king-skovald starts stunning you for 20 seconds straight and you can't do anything as he slowly kills you , he repeats the stun the moment the first stun fades.

How he should behave : https://youtu.be/seLj4f5ra8U?t=67

**Comment by Cefiro-Caecias** [comment]
Fixed.
