### ISSUE TITLE
MM artifact quest Rescue Mission

### ISSUE THREAD

**Issue by artycice** [GuabinaCore/WoWKoi#1794]
https://www.wowhead.com/quest=40419/rescue-mission

I am able to complete it fully and loot the artifact, but the "Travel through the portal to Niskara' credit doesn't register,resulting in not being able to turn in the quest and progress to class hall quest.

It should register when you enter the portal (Link to the buggy point of the quest https://www.wowhead.com/npc=102129/kill-credit-use-portal). Not sure if the last link helps.

**Comment by Cefiro-Caecias** [comment]
Fixed.
