### ISSUE TITLE
BM artifact quest Never Hunt ALone

### ISSUE THREAD

**Issue by artycice** [GuabinaCore/WoWKoi#1795]
https://www.wowhead.com/quest=42185/never-hunt-alone

The part "Fly to the Temple of Storms" doesn't register (simmilar with the mm quest bug),even though i was able to complete all the quests and gain the artifact i couldn't turn it in.

"Fly to the temple of storms" credit should register (https://www.wowhead.com/npc=106672/kill-credit-fly-to-the-temple-of-storms) once you appear before thorim.
![WoWScrnShot_112420_222126](https://user-images.githubusercontent.com/74986688/100147291-d69b9700-2ea3-11eb-959a-829487814972.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed.
