### ISSUE TITLE
Survival hunter quest The Spear in the Shadow

### ISSUE THREAD

**Issue by artycice** [GuabinaCore/WoWKoi#1796]
https://www.wowhead.com/quest=40385/the-spear-in-the-shadow

First of all the highmountain hippogryph  https://www.wowhead.com/npc=100967/highmountain-hippogryph is supposed to fly you to the Eagle spirit in highmountain.There you have to get the https://www.wowhead.com/quest=39427/the-eagle-spirits-blessing quest which is followed by the scenario that's already provided on the server.
After finishing the scenario it doesn't register the credit for getting to the place in this case its:
 Take the Eagle Spirit flight to the harbor
Return to Dalaran

Should register the killbunny credits (going to the needed spot) and should be able to take and complete https://www.wowhead.com/quest=39427/the-eagle-spirits-blessing
How it all should go down: https://www.youtube.com/watch?v=Ovnnw4R9m6o

**Comment by Cefiro-Caecias** [comment]
Fixed.
