### ISSUE TITLE
The Hammer in the Deep Enhancement Shaman Artifact Scenario

### ISSUE THREAD

**Issue by artycice** [GuabinaCore/WoWKoi#1798]
**Links:**
https://www.wowhead.com/quest=40224/the-hammer-in-the-deep

**What is happening:**
Everything in the scenario goes fine except for the last stage.
First of all 
A)the friendly dwarf npc Stormcaller Mylra https://www.wowhead.com/npc=96539/stormcaller-mylra becomes hostile,instead of getting the boss (https://www.wowhead.com/npc=98379/gethxun) hp down to 1.3kk hp as she is supposed to.
B) the the boss (https://www.wowhead.com/npc=98379/gethxun) hits too hard, 50k-100k isnt really doable if enhancement is the 1st choice of artifact on lvl 100
C)Stormcaller Mylra remains alive/disappears after the encounter and we can't proceed the quest.
![WoWScrnShot_112520_172741](https://user-images.githubusercontent.com/74986688/100251832-e2409980-2f47-11eb-9f12-bae719bcdeb3.jpg)
![WoWScrnShot_112520_173200](https://user-images.githubusercontent.com/74986688/100251848-e7054d80-2f47-11eb-9c2e-698292095f89.jpg)

**What should happen:**
a)Stormcaller Mylra https://www.wowhead.com/npc=96539/stormcaller-mylra remains friendly and aids us or just dies but the boss https://www.wowhead.com/npc=98379/gethxun should be set to 1.3kk hp
b)the ability to get Stormcaller Mylra up after the encounter to proceed with the quest
A video showing the proper encounter: https://youtu.be/qMU6iYIZZik?t=257

**Comment by Cefiro-Caecias** [comment]
Fixed.
