### ISSUE TITLE
Highmountain starting quest Keepers of the Hammer

### ISSUE THREAD

**Issue by artycice** [GuabinaCore/WoWKoi#1799]
**Links:**
https://www.wowhead.com/quest=38907/keepers-of-the-hammer

**What is happening:**
Well it doesnt register the credit for arriving to highmountain.
![WoWScrnShot_112520_183511](https://user-images.githubusercontent.com/74986688/100256050-f20eac80-2f4c-11eb-9a04-7a8895731d3c.jpg)

**What should happen:**
It should register the credit for arrival after speaking with the fly master https://www.wowhead.com/npc=96813/aludane-whitecloud as it is mentioned in his **objective of** on wowhead.
A link to the video of how it's supposed to go down: https://www.youtube.com/watch?v=YUxDhnuzv-k

**Comment by Cefiro-Caecias** [comment]
Fixed.
