### ISSUE TITLE
The Third Trial of Ursol

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1801]
**Links:**
https://www.wowhead.com/quest=41792/the-third-trial-of-ursol
from WoWHead or our Armory

**What is happening:**

After talking to Ursol to begin, enemies spawn but i dont get credit for talking. Just for protecting lea after killing mobs.

**What should happen:**
After talking to Ursol and killing mobs, quest should complete.

**Comment by Cefiro-Caecias** [comment]
Fixed.
