### ISSUE TITLE
[Arthas] - Blood DK ARtifact weapon scenario

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1802]
**Links:** https://www.wowhead.com/quest=40740/the-dead-and-the-damned

from WoWHead or our Armory

**What is happening:**

In the scenario, if you go too far from baron sliver the next stage doesn't come up.

**What should happen:**

If if you get far the scenario should continue.

**Comment by Arkanheal** [comment]
As they are all linked, I'll just report all blood dk scenario bugs here.

So 1. the friendly NPCS

- They don't aggro any mobs (they should)
- They don't help when you fight enemy mobs (they should)
- They should follow you in a "triangle" formation and not be stacked up one upon another

2. The Maw of the Damned (Blood dk artifact) is invisible, you can click it but you can't see it. (it should be visible)

**Comment by Cefiro-Caecias** [comment]
Fixed.
