### ISSUE TITLE
[Arthas] - Death knight order hall 

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1803]
Unsure if it should be this way, but i'll try to group all Death Knight Order Hall related bugs here. **Feel free to comment**

As a blook death knight, when you first arrive in Acherus (Legion) you instantaneously get Nazgrim and Thassarian as followers

Followers:
- Should be a quest chain [here](https://www.wowhead.com/storyline/the-four-horsemen-232) -- This questchain seems to be script but not gated (for example you can take [Maw of Souls: Maul of the Dead](https://www.wowhead.com/quest=43574/maw-of-souls-maul-of-the-dead) from [Salanar](https://www.wowhead.com/npc=28653/salanar-the-horseman) way too early.

**Comment by Arkanheal** [comment]
Mission:

- When you complete a mission, you get progress in pretty much all of garrison (Draenor) related achievements
- Can't complete the mission Troops in the Field (The linked [quest](https://www.wowhead.com/quest=43267/troops-in-the-field) auto-completes)

**Comment by Arkanheal** [comment]
Troops:

- The text to recruit ghouls (NPCID: [106435](https://www.wowhead.com/npc=106435/dark-summoner-marogh)) shows up 3 times
- When ghouls are ready to be recruited, the flag you have to click is still transparent (should be plain when one or more "orders" are ready)
- The text to recruit Ebon Knights (NPCID: [106436](https://www.wowhead.com/npc=106436/korgaz-deadaxe)) shows up 2 times

**Comment by Arkanheal** [comment]
[Questchain](https://www.wowhead.com/storyline/the-four-horsemen-232):
Aside from the order of the quests beeing wrong I'll report the bug I found doing those quests in this comment.

- [Death... and Decay](https://www.wowhead.com/quest=42535/death-and-decay) : The [Witherbark Supplies](https://www.wowhead.com/object=250650/witherbark-supplies) doesn't despawn (only clickable once)
- [A Personal Request](https://www.wowhead.com/quest=42708/a-personal-request): Thassarian should run and help you with mobs. Right now he walks, doesn't aggro enemy NPCs and doesn't help you in combat
- [Steeds of the Damned](https://www.wowhead.com/quest=43899/steeds-of-the-damned: The quest should complete after 5 missions related are done. Here the quest is validated after only one mission 
    - [1260](https://www.wowhead.com/mission=1260/fallen-steeds-saddle-of-the-frozen-crown)
    - [1261](https://www.wowhead.com/mission=1261/fallen-steeds-the-barons-saddle)
    - [1262](https://www.wowhead.com/mission=1262/fallen-steeds-saddle-of-the-headless-horseman)
    - [1263](https://www.wowhead.com/mission=1263/fallen-steeds-saddle-of-the-huntsman)
    - [1264](https://www.wowhead.com/mission=1264/fallen-steeds-reins-of-shadow)

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
