### ISSUE TITLE
[NPC] - Warbrave Oro (97666)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1804]
**Links:**
https://www.wowhead.com/npc=97666/warbrave-oro
https://www.wowhead.com/quest=39733/the-lone-mountain

from WoWHead or our Armory

**What is happening:**
When giving back the Lone Moutain, his animation is buggy (he looks like a meteor)

**What should happen:**
He should just be standing here with no extra animation beside HM-Tauren ones.

**Comment by Cefiro-Caecias** [comment]
Fixed, full blizzlike. Available in the next update.
