### ISSUE TITLE
The Fangs of Ashamane

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1806]
**Links:**
https://www.wowhead.com/quest=42430/the-fangs-of-ashamane#comments
from WoWHead or our Armory

**What is happening:**

I dont get credit after mounting Ebonfang, but i got teleported to Dreamgrove.
 
**What should happen:**
I should get credit complete quest.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available now.
