### ISSUE TITLE
The Codex of Ra Elemental Shaman artifact quest

### ISSUE THREAD

**Issue by artycice** [GuabinaCore/WoWKoi#1808]
**Links:**
https://www.wowhead.com/quest=43338/the-codex-of-ra

**What is happening:**
a)The shaman doesn't enter in any needed for the quest phase resulting in missing quest objects such as:
 **https://www.wowhead.com/item=139432/the-edict-of-fire**
**https://www.wowhead.com/item=139433/the-edict-of-stone**
**https://www.wowhead.com/item=139434/the-edict-of-the-storm**
![WoWScrnShot_112520_191644](https://user-images.githubusercontent.com/74986688/100276717-a8cd5580-2f6a-11eb-90f5-ff3881eadb2c.jpg)

b)There are no needed for the quest completition mobs :
  **https://www.wowhead.com/npc=110569/shao-tien-spirit-warrior**
**https://www.wowhead.com/npc=110570/shao-tien-wraith**
![WoWScrnShot_112520_220921](https://user-images.githubusercontent.com/74986688/100276864-e4681f80-2f6a-11eb-96e6-5a4ab6d1f1d5.jpg)
c) The common (already) bug with not getting credit for arriving to the spot.

**What should happen:**
If it's possible there should be a phase speciffic for elemental shamans to pass this quest with the points mentioned above.If not,spawn the mobs and the items.
Mobs should be tagged as neutral so they don't bother low lvls that are leveling up in the zone.
And ofcourse you should get the credit for arriving to the spot.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
