### ISSUE TITLE
restoration shaman artifact to the deeps

### ISSUE THREAD

**Issue by artycice** [GuabinaCore/WoWKoi#1809]
**Links:**
https://www.wowhead.com/quest=43644/to-the-deeps

**What is happening:**
a)Not getting credit upon arrival (see the screenshot provided)
![WoWScrnShot_112520_184133](https://user-images.githubusercontent.com/74986688/100277782-67d64080-2f6c-11eb-9ef4-c74f92951762.jpg)
b) not getting the movement speed according to the zone (vashj'ir)
 https://www.wowhead.com/spell=73701/sea-legs

**What should happen:**
Should get credit for arriving to the spot and should get movement speed buff.
https://www.youtube.com/watch?v=Ay3g2JmU9Mc
Here you can see the movement speed boost.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
