### ISSUE TITLE
[Quest] - Blood: Aid of the Illidari (QuestID: 47025)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1811]
**Links:**

https://www.wowhead.com/quest=47025/blood-aid-of-the-illidari

from WoWHead or our Armory

**What is happening:**

You are able to pick this quest as horde

**What should happen:**

This quest should be Alliance only

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
