### ISSUE TITLE
[QuestChain] Origins (StorylineID: 206)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1812]
**Links:**
https://www.wowhead.com/storyline/origins-206

from WoWHead or our Armory

The order of the quests is basically all wrong.

**Comment by NightwindOI** [comment]
That's ok, but what's the right order.

**Comment by Arkanheal** [comment]
1. https://www.wowhead.com/quest=43705/nobundos-last-stand (Picked up during the phase 2 of the Light's Heart scenario in Exodar -- started by this [quest](https://www.wowhead.com/quest=44004/bringer-of-the-light))
2. https://www.wowhead.com/quest=44009/a-falling-star
3. https://www.wowhead.com/quest=44414/felspawns-of-lothros
4. https://www.wowhead.com/quest=44415/the-red-axe
5. https://www.wowhead.com/quest=44416/hunter-of-night
6. https://www.wowhead.com/quest=44464/awakenings
7. https://www.wowhead.com/quest=44466/an-unclear-path
8. https://www.wowhead.com/quest=44479/ravencrests-legacy
9. https://www.wowhead.com/quest=44480/in-my-fathers-house
10. https://www.wowhead.com/quest=44481/destiny-unfulfilled

The order might be a bit different for paladins

**Comment by Arkanheal** [comment]
You take the last 5 quests without taking any other ones in the Warrior class Order Hall. (Due to the fact the Light's Heart is here where it shouldn't before you bring it back after Falling Star quest)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
