### ISSUE TITLE
[Questchain] Obliterum Forge

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1813]
**Links:**

https://www.wowhead.com/quest=41778/firing-up-the-forge#

from WoWHead or our Armory

**What is happening:**
This [quest](https://www.wowhead.com/quest=41778/firing-up-the-forge) should be Alliance only. (Unsure)

**Comment by Cefiro-Caecias** [comment]
It is quite confusing, but everything seems to indicate that it should be for both factions.
