### ISSUE TITLE
[Quest] - A Choice of Allies (QuestID: 4993050242

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1814]
**Links:**
https://www.wowhead.com/quest=50242/a-choice-of-allies

from WoWHead or our Armory

**What is happening:**
Horde side : The quest isn't doable. The choice Sylvanas should give you is none (only a window with a sentence in russian -- кого из возможных союзников вы хотите привлечь -- which means sort of "Which ally do you cant to choose)

Might be because I don't have the requirements to do Allied Race

**What should happen:**
If I don't have the requirement, I should get the first quest of the [chain](https://www.wowhead.com/quest=49930/the-call-for-allies) else you should be able to pick an allied race

**Comment by Cefiro-Caecias** [comment]
Fixed translate. Available in the next update.
