### ISSUE TITLE
[Quest] - Protect the Home Front (QuestID: 44092)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1816]
**Links:**
https://www.wowhead.com/quest=44092/protect-the-home-front

The quest should be pickable after this [one](https://www.wowhead.com/quest=40605/keep-your-friends-close). Right now it doesn't show up instead we get this [one](https://www.wowhead.com/quest=44184/in-the-blink-of-an-eye)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
