### ISSUE TITLE
The Legend of the Sands (Wind Walker Monk Artifact Weapon Quest)

### ISSUE THREAD

**Issue by Nymaea** [GuabinaCore/WoWKoi#1817]
**Links:**
https://www.wowhead.com/quest=40569/the-legend-of-the-sands

**What is happening:**
Speaking to Li Li after picking up the quest will open the dialogue option to talk about Uldum, but nothing happens after that dialogue finishes. Also, if you click on the quest while speaking to her, the continue key isn't greyed out but nothing happens after you click on it.

**What should happen:**
Once you've finished the dialogue with Li Li, the quest should be complete and available to turn in to progress with the questline.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
