### ISSUE TITLE
The Wanderer's Companion (Brewmaster Monk Artifact Quest)

### ISSUE THREAD

**Issue by Nymaea** [GuabinaCore/WoWKoi#1818]
**Links:**
https://www.wowhead.com/quest=42762/the-wanderers-companion

**What is happening:**
Writing on behalf of a friend. According to him, he speaks to Tak-Tak like the quest directs him to do, but it doesn't complete to the quest when he arrives at Tian Monastery and he is unable to turn it in.

**What should happen:**
You should fly from the class hall to Tian Monastery after speaking to Tak-Tak. Once landing there, you should be able to turn the quest in with the Monkey King, to progress the rest of the questline.

**Comment by Arkanheal** [comment]
Just made it, can confirm

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
