### ISSUE TITLE
Tying Up Loose Ends

### ISSUE THREAD

**Issue by Nymaea** [GuabinaCore/WoWKoi#1819]
**Links:**
https://www.wowhead.com/quest=39861/tying-up-loose-ends

**What is happening:**
After speaking to Khadgar, I talked to the flight master to take me to Val'Sharah, but after I'm teleported there, the quest stays at 0/1 and I am unable to turn it in at Malfurion. Also, during this whole time, the bar at the top of my screen still shows that I'm still in the Monk class hall.

**What should happen:**
The flight master sends me to Val'Sharah after choosing the option with him to send me there. I'd be flown to Lorlathil where I'd speak to Malfurion to finish the quest.

**Comment by Arkanheal** [comment]
Linked with #1799

**Comment by NightwindOI** [comment]
''Need more info'' is added for me (there may be a global fix for all of them)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
