### ISSUE TITLE
[Arthas] - Quest In the Blink of an Eye (44184)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1820]
**Links:**
https://www.wowhead.com/quest=44184/in-the-blink-of-an-eye

**What is happening:**
The quest is picked up after finishing Keep your friends close. 

**What should happen:**
The quest should be at the end of a quest chain ([44182](https://www.wowhead.com/quest=44182/city-under-siege), [44421](https://www.wowhead.com/quest=44421/anomalous-anomalies), [44500](https://www.wowhead.com/quest=44500/author-author), [44184](https://www.wowhead.com/quest=44184/in-the-blink-of-an-eye))

**Comment by LKArthas** [comment]
https://wowpedia.fandom.com/wiki/In_the_Blink_of_an_Eye
Patches and hotfixes
    Legion Hotfix (2017-04-03): Players above level 100 should now be able to acquire "In the Blink of an Eye". <----
    Legion Hotfix (2016-09-28): Tomes of the Tranquil Mind obtained from "In the Blink of an Eye" are now Bind-on-pickup.
    Legion Hotfix (2016-08-30): Legion players who had begun the post-Broken Shore event quests, but not completed them, should now be eligible to receive “In the Blink of an Eye”.
    Legion Patch 7.0.3 (2016-07-19): Added. 
It's added there blizzlike, but questline will be added too
