### ISSUE TITLE
[Quest] - Hidden History (QuestID: 43466)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1823]
**Links:**
https://www.wowhead.com/quest=43466/hidden-history

from WoWHead or our Armory

**What is happening:**
This quest and pretty much all the quest of this [storyline](https://www.wowhead.com/storyline/artifact-research-211) are useless in 7.3 (no more artifact knowledge). You can pick them here (saw them in Druid and Warrior Order Hall at least)

**What should happen:**
You shouldn't be able to pick those.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
