### ISSUE TITLE
[Paladin] - To Northrend (Quest ID: 42002)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1824]
**Links:**
https://www.wowhead.com/quest=42002/to-northrend
from WoWHead or our Armory

The quest display on the map and minimap is glitchy (spread in a horizontal line)
![WoWScrnShot_112620_114240](https://user-images.githubusercontent.com/27277903/100341165-8116d580-2fdc-11eb-998e-db7f8bb2c115.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
