### ISSUE TITLE
[Paladin] - The end of the Saga (QuestID: 42005

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1825]
**Links:**
https://www.wowhead.com/quest=42005/the-end-of-the-saga
from WoWHead or our Armory

**What is happening:** When you speak to Tahu nothing happens

**What should happen:** Tahu should bring back a spirit atop of a scroll, then some RP, then you can continue the quest chain

**Comment by Cefiro-Caecias** [comment]
Fixed, although the final event will go blizzlike later. Available in the next update.
