### ISSUE TITLE
[Quest] - Mage: Thrice the Power (QuestID: 44310)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1826]
**Links:** https://www.wowhead.com/quest=44310/thrice-the-power

from WoWHead or our Armory

**What is happening:** You can pick this quest before getting your 2 first artifact weapons

**What should happen:** You should be able to pick this quest only after getting your 2 first artifact weapons

**Comment by NightwindOI** [comment]
Must be fixed now, please retest.

**Comment by Arkanheal** [comment]
Fixed it is
