### ISSUE TITLE
[Mage] Order Hall

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1827]
As I did with [DK ](https://github.com/GuabinaCore/WoWKoi/issues/1803), I'll report here all the order hall related bugs.

**Quest Order**

- When arriving after the quest [The Dreadlord's Prize](https://www.wowhead.com/quest=41036/the-dreadlords-prize), you can pick up [The Might of the Tirisgarde](https://www.wowhead.com/quest=44689/the-might-of-the-tirisgarde) straight away. It should come way later. After finishing this [storyline](https://www.wowhead.com/storyline/the-tirisgarde-reborn-248) and the first quests of this [one](https://www.wowhead.com/storyline/rise-of-the-tirisgarde-237)

**Comment by NightwindOI** [comment]
Must be fixed now, please retest.

**Comment by Arkanheal** [comment]
I can still pick this quest up
