### ISSUE TITLE
[Mission Table] - Scouting Mission

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1829]
Wehn you chose a zone, you shouldn't be able to click another zone before finishing the one you selected first. Now you can click, Accept the quest, but it won't show up in your questlog which means you could be stuck after finishing a zone.

**Comment by ventarius5** [comment]
As far as I remember, on retail wow, It was possible to take all the starter quests at once.

**Comment by Arkanheal** [comment]
In any case, (I'll try to get info this evening), you should either:
1. Be able to pick up all zones at once (which means it gives you the quest)
2. Be able to pick only one at a time, so you shouldn't be able to pick up the quest
