### ISSUE TITLE
[Quest-Stormheim] - A Trial of will

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1830]
**Links:**
[ label:Quest / label:Zone:Stormheim ]
https://www.wowhead.com/quest=39592/a-trial-of-will

**What is happening:**

1. Quest is autocomplete right at the questgiver.

2. The event works properly but doesn't grant credits after completing it.

3. If a player leaves event area, the mobs won't disappear. (Low priority thing but still might be used to grief other players with endless waves of mobs)

**What should happen:**
-

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
