### ISSUE TITLE
[Stormheim] - NPC Vault Guardian (89817)

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1831]
**Links:**

[ label:MISC / label:NPC / label:Zone:Stormheim ]

https://www.wowhead.com/npc=89817/vault-guardian

**What is happening:**

Missing animation and action. Vault guardians don't kill you when entering Aggramar's Vault before https://www.wowhead.com/quest=39594/a-trial-of-might quest is taken.

**What should happen:**
According to WoWhead comments "These block the entrance to Aggramar's Vault until you start A Trial of Might. Trying to enter the vault before then will cause them to one-shot you."

**Comment by Arkanheal** [comment]
I'll add that they should be neutral and not friendly but cannot be hit by anything

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
