### ISSUE TITLE
[Quest-Stormheim] - A Trial of Might

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1832]
**Links:**

[ label:Quest / label:Zone:Stormheim ]

https://www.wowhead.com/quest=39594/a-trial-of-might

https://www.wowhead.com/npc=96175/yotnar

**What is happening:**

1. Quest is being completed right after clicking on the console. (no need to fight Yotnar)

2.Yotnar is missing his abilities.

3.Yotnar is missing some dialogues. (and some texts are in spanish)

**What should happen:**

**Comment by Arkanheal** [comment]
Video here => https://www.wowhead.com/quest=39594/a-trial-of-might#videos:id=101073

**Comment by Arkanheal** [comment]
I'll add a bug I've discovered (which is kinda annoying to be honest)
If you click the console then AFK for some time. Yotnar despawns and as you have to kill him to complete the quest, you are stuck.
EDIT: Logging in the day after Yotnar didn't spawn, he respawns.

**Comment by Arkanheal** [comment]
I'll add as well that you should 'win' the fight at Yotnar 20% HP. Here you are to kill him

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
