### ISSUE TITLE
[Quest-Stormheim] - Buffwalker Goat

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1833]
**Links:**
[ label:Quest / label:Zone:Stormheim / label:NPC ]
https://www.wowhead.com/quest=38374/assault-the-drekirjar

**What is happening:**

Releasing Buffwalker Goat (2%) doesn't grant credits toward 100%

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
