### ISSUE TITLE
[Quest-Stormheim] - Built to Scale

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1834]
**Links:**

[ label:Quest / label:Zone:Stormheim ]

https://www.wowhead.com/quest=38616/built-to-scale

**What is happening:**

https://imgur.com/a/Y8O3xdY

I was granted the quest 9 times, 8 from https://www.wowhead.com/npc=92567/dread-rider-cullen and one droped from quest NPC.

**What should happen:**
According to wowhead, this quest is granted only by https://www.wowhead.com/item=124037/storm-drake-scale as a drop.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
