### ISSUE TITLE
[Quest-Stormheim] - Impalement Insurance

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1835]
**Links:**

[ label:Quest / label:Zone:Stormheim ]

https://www.wowhead.com/quest=38615/impalement-insurance

**What is happening:**

Interacting with Harpoon Launchers doesn't count credits toward quest completion.

**What should happen:**

**Comment by ventarius5** [comment]
This quest is part of a long storyline. Being unable to progress blocks me from testing it further. I would set this quest as HIGH priority.

**Comment by NightwindOI** [comment]
99% of the quests are with high prior. We fixing them zone by zone, but if u want I can complete it for you, so u can continue testing.

**Comment by artycice** [comment]
I'm quite sure it doesn't affect further progression as i didn't complete it but got all of the chapters done without this one and the rune activation quest in the forrest .

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
