### ISSUE TITLE
[Tyce] - Neltharion's Lair - Spell Razor Shards Animation (188169)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1836]
**Links:**
https://www.wowhead.com/spell=188169/razor-shards
https://www.wowhead.com/npc=91003/rokmora
from WoWHead or our Armory

**What is happening:**
If your tank (in this case me) stands too close to the boss when he casts [Razor Shards](https://www.wowhead.com/spell=188169/razor-shards), the animation will glitch and he will turn the wrong way. The spell still goes the way it should which makes it kinda messy.
If you are max-range/not in his NPC circle (the red one below him), the animation is fine.

**What should happen:**
The animation shouldn't glitch no matter how close the targeted player is

**Comment by Cefiro-Caecias** [comment]
Fixed.
