### ISSUE TITLE
[Tyce] - Neltharion's Lair - NPC Understone Drummer (92610)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1837]
**Links:**
https://www.wowhead.com/npc=92610/understone-drummer
from WoWHead or our Armory

**What is happening:** They run to their drum properly, but if you grab them away, they won't go back to it and the add will continue to spawn every 6 second (timer is perfect btw).
If you CC them, they will hit you but adds will continue to spawn

**EDIT**: To be more precise, the adds spawn no matter what when he starts to cast the spell, but they fly and fall only after 6 seconds.

The add animation when falling from the roof is kinda glitchy as well.

**What should happen:** As soon as the drummer isn't channeling [war drums](https://www.wowhead.com/spell=183526/war-drums), the adds should stop spawning.
The drummer should rush back to his drum if CCed of push away.
The animation should be smoother ^^

**Comment by Cefiro-Caecias** [comment]
Fixed.
