### ISSUE TITLE
[Dungeon] Neltharion's Lair - Stoneclaw Hunter

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1838]
**Links:**
https://www.wowhead.com/npc=91332/stoneclaw-hunter
from WoWHead or our Armory

**What is happening:** 

- If you kill the hunter first the pet despawns
- If you kill the pet first, the hunter doesn't spawn another one

**What should happen:** 

- If you kill the hunter first, you should have to kill the pet too
- If you kill the pet first, the hunter should spawn another one (infinitly)

**Comment by Cefiro-Caecias** [comment]
There is a problem in the system, which prevents a second pet from being invoked until the first one has been dewormed, so the resolution is pending.
