### ISSUE TITLE
[Tyce] - Neltharion's Lair - NPC Petrifying Totem (94224)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1839]
**Links:**
https://www.wowhead.com/npc=94224/petrifying-totem
https://www.wowhead.com/spell=202108/petrifying-totem
https://www.wowhead.com/npc=90998/blightshard-shaper

**What is happening:** The [Petrifying Totem](https://www.wowhead.com/spell=202108/petrifying-totem) doesn't work, it deals damage but you don't get petrified after 10 sec of standing in the cloud. Also the totem sometimes follows the player with the most aggro. (Probably the healer in a group as you can't hit it)

**What should happen:**he [Petrifying Totem](https://www.wowhead.com/spell=202108/petrifying-totem) should stun you after 10 sec of standing in the cloud. The totem should be static as well

**Comment by Cefiro-Caecias** [comment]
Fixed.
