### ISSUE TITLE
[Dungeon] - Neltharion's Lair - Burning Geode

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1840]
**Links:**
https://www.wowhead.com/npc=101437/burning-geode

**What is happening:**
The burning geode move when casting [Scorch](https://www.wowhead.com/spell=202075/scorch)

**What should happen:**
The burning geode shouldln't move when casting [Scorch](https://www.wowhead.com/spell=202075/scorch)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
