### ISSUE TITLE
[Dungeon] Neltharion's Lair - Stoneclaw Grubmaster

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1843]
**Links:**

https://www.wowhead.com/npc=102404/stoneclaw-grubmaster

from WoWHead or our Armory

When they spawn [Tarspitter Grub](https://www.wowhead.com/npc=94869/tarspitter-grub) with Worm Call, the grubs should start casting Metamorphosis instantly

**Comment by Cefiro-Caecias** [comment]
Fixed. Worms will begin casting Metamorphosis within 1-3 seconds of being summoned. Available after the next update.
