### ISSUE TITLE
[Dungeon] Neltharion's Lair - Naraxass

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1844]
**Links:**
https://www.wowhead.com/npc=101075/wormspeaker-devout

**What is happening:**
1. Naraxxas corpse falls down a bit in the pit making it glitch through the cave ground
2. When dropping in the pit, you get a slow falling buff

**What should happen:**
1. Naraxxas corpse's should be above the ground
2. You should just fall in the water down the pit w/o a slow falling buff

**Comment by artycice** [comment]
1) It's an istant cast.Check the spell flags on wh.

**Comment by Arkanheal** [comment]
True, edited
