### ISSUE TITLE
Becoming the Ascendant Horde Stormheim 

### ISSUE THREAD

**Issue by artycice** [GuabinaCore/WoWKoi#1846]
**Links:**
https://www.wowhead.com/quest=39155/becoming-the-ascendant

**What is happening:**
Doesn't react to "attempt to commune with the statue." line .
![WoWScrnShot_112720_010914](https://user-images.githubusercontent.com/74986688/100396422-84967500-304d-11eb-8b1d-f4803f57cc6f.jpg)

**What should happen:**
It should react to the line.

**Comment by Arkanheal** [comment]
Most of quest text is in spanish/portuguese as well
Makes you stuck in Stormheim storyline

**Comment by Cefiro-Caecias** [comment]
Fixed. Available now.
