### ISSUE TITLE
[Tyce] - DK - Taking no damage

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1850]
On a DK, as a 110 testing normal dungeons, some spells straight up don't hit me. Have no idea why. Ask @NightwindOI

**Comment by NightwindOI** [comment]
By some spell, just attack the first boss in ''Eye of Azshara''. The spell does damage to the rest of the party, but not to the tank/DK. It may be some bugged passive/talent.

**Comment by Arkanheal** [comment]
Not only this spell. In fact, I feel like a lot of others do as well. But I sadly don't have the full list
