### ISSUE TITLE
[Dungeon] - Eye of Azshara - Restless Tides

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1851]
**Links:**
https://www.wowhead.com/npc=111644/restless-tides
https://www.wowhead.com/spell=195284/undertow

from WoWHead or our Armory

If you kill the Restless Tides during his Undertow casts, you are pushed back until the cast ends (the NPC is dead but it's like the channeling continues). The push back AND damage should stop when the NPC dies

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
