### ISSUE TITLE
[Dungeon] - Eye of Azshara - Hatecoil Wavebinders

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1852]
**Links:**
https://www.wowhead.com/spell=196031/bubble-shield
https://www.wowhead.com/npc=97170/hatecoil-wavebinder#abilities;mode:normal

**What is happening:**
The bubble shied only procs at a %age of life. When you break it the mobs does as if nothing happens

**What should happen:** The shield should be casted occasionnally and when you break it if should stun the mob for 6 second and it should take increased damage

**Comment by ShikoSCS** [comment]
Corrected, please review and in case of any error report it.
