### ISSUE TITLE
[Tyce] - Eye of Azshara - Boss Lady Hatecoil (91789)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1853]
**Links:**
https://www.wowhead.com/spell=193597/static-nova
https://www.wowhead.com/npc=91789/lady-hatecoil
https://www.wowhead.com/spell=193682/beckon-storm#used-by-npc
https://www.wowhead.com/spell=193698/curse-of-the-witch

**What is happening:**
1. If you get hit by Static Nova it makes you're character moving like an epileptic having a crisis
2. You can't kill Beckon Storm adds with Curse of the witch expiring
3. Sometimes your own Curse of the Witch will bump you.
4. You get the Stay Salty achievement by killing the boss (even in normal)

**What should happen:**
1. Your character should jump be stunned if hit by the Static Nova
2. Curse of the witch frontal cone should one shot Beckon Storm adds
3. You shouldn't be bumped by your Curse of the witch (happened only to my DK not the DH that was with me)
4. You shouldn't get the Stay Salty achievement just by killing the boss

**Comment by artycice** [comment]
3) Quite sure they retaliate some of the damage if you meean that,or do you mean that it knocks you arround?

**Comment by Arkanheal** [comment]
@artycice I mean your own Curse of the Witch expiring knocks you back. You don't take any damage
