### ISSUE TITLE
[Tyce] - Eye of Azshara - Spell Armorshell (196175)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1854]
**Links:**
https://www.wowhead.com/npc=95947/makrana-hardshell
https://www.wowhead.com/spell=196175/armorshell
from WoWHead or our Armory

**What is happening:**
The mobs do channel Armorshell for the whole duration of the buff

**What should happen:**
They should do their 2.5sec cast then start behaving normally afterwards

**Comment by Travven** [comment]
Closed the spell work good. Has the flag channeled
