### ISSUE TITLE
[Dungeon] Eye of Azshara - Skrog Wavecrasher

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1855]
**Links:**
https://www.wowhead.com/npc=91796/skrog-wavecrasher

1. They win 2 stacks per casts of Rising Fury (should only be one) 
2. They cast Rising Fury a bit too often. The first one should be 7 sec into the fight
3. then every 18 sec.

** Video proof **:
2. https://www.youtube.com/watch?v=loovDPouy3s&t=16m13s aggro (first cast is at 16m20s)
3. https://www.wowhead.com/eye-of-azshara-dungeon-strategy-guide#king-deepbeard (Skorg Wavecrasher part) -- In the video he dies at 16m37 so just before he should cast Rising Fury again.

**Comment by ShikoSCS** [comment]
Corrected, please review and in case of any error report it.
