### ISSUE TITLE
[Dungeon] Eye of Azshara - Skrog Tidestomper

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1856]
**Links:**
https://www.wowhead.com/npc=95939/skrog-tidestomper
https://www.wowhead.com/spell=195801/massive-quake
from WoWHead or our Armory

They cast Massive Quake a bit too much. 
1. The first cast should be around 7 sec after the aggro
2. They should cast it every 20 sec (countdown starting from the start of the cast)

**Video Proof**:
1. https://www.youtube.com/watch?v=loovDPouy3s&t=15m13s (First cast begins at 15m 20s)
2. https://www.youtube.com/watch?v=loovDPouy3s&t=15m40s (Second cast begins)

**Comment by ShikoSCS** [comment]
Corrected, please review and in case of any error report it.
