### ISSUE TITLE
[Dungeon] Eye of Azshara - Weather update

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1857]
**Links:**
https://www.wowhead.com/spell=191797/violent-winds
https://www.wowhead.com/spell=192794/lightning-strike

from WoWHead or our Armory

**What is happening:**
There is no Violent Winds nor Lightning Strikes

**What should happen:**
Violent winds should be pushing players for 10 sec every 90 sec after the group killed the 2nd boss (might only be in MM but I believe it's in NM and HM too)
Lightning Strikes should appear near player location every few seconds as a watery swirl then deal damage atfer 3 second.

**Comment by NightwindOI** [comment]
It's Mything only, same as seagulls, but will let it open for now.

**Comment by Arkanheal** [comment]
Wrong as you can see here in a normal mode video guide
https://www.youtube.com/watch?v=ecBPq0hnxSw&t=2m34s for the winds
and here in the same normal mode video guide
https://www.youtube.com/watch?v=ecBPq0hnxSw&t=4m41s for the lightning (but the spells I linked are MM only true)

**Comment by NightwindOI** [comment]
look like wowhead is retarded once again
https://i.imgur.com/4wKsV5y.png

**Comment by Arkanheal** [comment]
Yeah I see that too, but can't find the right spell for some reason

**Comment by Arkanheal** [comment]
Still doesn't work (tested in NM solo on a BDK)
