### ISSUE TITLE
[Quest-Stormheim] - Lay Them to Rest

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1858]
**Links:**

https://www.wowhead.com/quest=39791/lay-them-to-rest

**What is happening:**

Restless Ancestor can still be killed after using Branch of the Runewood. This allows to spam Branch of the Runewood on a single corpse to complete the quest.

**What should happen:**

After using Branch of the Runewood, Restless Ancestor should immediately become invincible.

**Comment by Arkanheal** [comment]
Just picked it up, can't use the item. Making the quest undoable

**Comment by Cefiro-Caecias** [comment]
Fixed.
