### ISSUE TITLE
[Tyce] - Eye of Azshara - Boss Wrath of Azshara (96028)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1859]
**Links:**
https://www.wowhead.com/npc=96028/wrath-of-azshara
https://www.wowhead.com/spell=192706/arcane-bomb
https://www.wowhead.com/spell=197165/heaving-sands
https://www.wowhead.com/spell=192675/mystic-tornado

**What is happening:**
1. Arcane bomb follow up is kinda laggy. (Even the adds before the boss ones)
2. Tidal Waves should only spawn when the boss reaches 10%
3. Heaving sands should trigger each time the boss melees the tank
4. No Violent Winds or Lightning Strikes after the Cry of Wrath cast (maybe linked to #1857 )
5. Mystic Tornadoes seem to take a looong time to load making them invisible but still doing damage/knockback
6. The model particles seems a bit too messy (you can hardly see the border of the water pond he's in)

**What should happen:**
1. The Arcane Bomb should just stay atop of the player character. Without the laggy animation
2. Self-explanatory
3. Self explanatory
4. There should be bothering weather mechanics (not only in this fight but for the whole dungeon starting from the 2nd and 3rd boss kill)
5. You should be able to see Mystic tornadoes
6. The model particles should be a spreading less (as you can see here https://www.youtube.com/watch?v=ecBPq0hnxSw&t=6m19s)

**Comment by artycice** [comment]
5)Do you have spell projection on?It is disabled sometimes.

**Comment by Arkanheal** [comment]
> 
> 
> 5)Do you have spell projection on?It is disabled sometimes.

I do, the tornadoes actually do appear, but only after some time (and I mean 5-10 sec, might be a loading problem as they do appear in the end). The DH I was with had the same problem.
