### ISSUE TITLE
Balance Druid Quest The Dark Riders

### ISSUE THREAD

**Issue by artycice** [GuabinaCore/WoWKoi#1861]
https://www.wowhead.com/quest=40838/the-dark-riders#guides

**What is happening:**
https://www.wowhead.com/npc=101257/the-conservator#abilities <-- This guy hits like a truck, might be the fact that i lost the helping npc (https://www.wowhead.com/npc=101286/revil-kost) but there is no way a fresh 100 could kill this version of the npc,could you check him out ?
 **What should happen**
1) The https://www.wowhead.com/npc=101286/revil-kost should assist you (he pretty much carries the whole scenario normally)
2)Even though im not entirely sure, https://www.wowhead.com/npc=101257/the-conservator#abilities shouldn't kill you that easily especially in full 680 ilvl. 
Link to demonstrate a what seem to be a new to the class player killing this guy with no problem: 
https://youtu.be/2EnF20-SqZ4?t=243

**Comment by Cefiro-Caecias** [comment]
1.- Fixed.
2.- I'll improve it later.
