### ISSUE TITLE
[Dungeon] - Maw of Souls - Seacursed soulkeeper

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1862]
**Links:**
https://www.wowhead.com/npc=97200/seacursed-soulkeeper
https://www.wowhead.com/spell=195031/defiant-strike
from WoWHead or our Armory

**What is happening:** He stays static when casting defiant strike

**What should happen:**
https://www.youtube.com/watch?v=mGOBZGcDmCA&t=1m38s

**Comment by ShikoSCS** [comment]
Corrected, please review and in case of any error report it.
