### ISSUE TITLE
[Dungeon] - Maw of Souls - Cursed Falker/Start of the dungeon bridge

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1863]
https://www.youtube.com/watch?v=mGOBZGcDmCA&t=1m30s
As you can see on the video all birds should aggro and jump on the 1st guy to put a foot on the bridge. Right now, they do aggro but only after like 3/4 seconds and not all of them (probably just proximity aggro while it should be an event)

**Comment by NightwindOI** [comment]
https://www.wowhead.com/npc=97163/cursed-falke

**Comment by Cefiro-Caecias** [comment]
Fixed.
