### ISSUE TITLE
 [Dungeon] - Maw of Souls - Horn cinematic event

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1865]
**Links:**
 https://www.youtube.com/watch?v=mGOBZGcDmCA&t=7m45s
from WoWHead or our Armory

**What is happening:** You spawn in the prison room in the Naglfar (the ship)

**What should happen:**
You should spawn in a cage then be able to break free by clicking on it as seen in the video

**Comment by Cefiro-Caecias** [comment]
Fixed. Available now.
