### ISSUE TITLE
 [Dungeon] - Maw of Souls - Random NPC model

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1867]
![WoWScrnShot_112820_130334](https://user-images.githubusercontent.com/27277903/100517348-4b175400-318a-11eb-9f16-264e7fa233bf.jpg)

Those models shouldn't exist.
See [here]( https://www.youtube.com/watch?v=mGOBZGcDmCA&t=8m39s)

**Comment by NightwindOI** [comment]
https://www.wowhead.com/npc=98919/seacursed-swiftblade

**Comment by Arkanheal** [comment]
I was talking about the blue one in the middle of the screenshot. Not the mobs behind it

**Comment by NightwindOI** [comment]
I link the mob ID since as I see they are the same mobs with different models.
Nvm...the UI trick me.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
