### ISSUE TITLE
 [Dungeon] - Maw of Souls - Seacursed Swiftblade

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1868]
**Links:**
https://www.wowhead.com/npc=98919/seacursed-swiftblade
https://www.wowhead.com/spell=194615/sea-legs

**What is happening:**
Sealegs lasts for 3 seconds

**What should happen:**
Sealegs should last for 6 seconds

**Comment by Travven** [comment]
fix.
this can be closed
