### ISSUE TITLE
[Tyce] - Maw of Souls - Spell Poisonous Sludge (194102)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1869]
**Links**
https://www.wowhead.com/npc=97185/the-grimewalker#abilities;mode:normal
https://www.wowhead.com/spell=194102/poisonous-sludge

** What is happening **
Sludge pools expand twice as much as they should. See [here]( https://www.youtube.com/watch?v=mGOBZGcDmCA&t=10m47s) and wait for it to expand to the maximum size (around [here]( https://www.youtube.com/watch?v=mGOBZGcDmCA&t=11m01s))

**Comment by Cefiro-Caecias** [comment]
Curioso, @ShikoSCS. La spell debería cambiar su velocidad de expansión según el Nivel de dificultad del Dungeon. Quizás el problema pueda estar en que aplica ambos valores de expansión simultáneamente?
