### ISSUE TITLE
 [Dungeon] - Maw of Souls - Helarjar Champion

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1870]
**Links:**
https://www.wowhead.com/npc=97097/helarjar-champion
https://www.wowhead.com/spell=198405/bone-chilling-scream?dd=1&ddsize=5

from WoWHead or our Armory

**What is happening:**
Fear lasts for 3 seconds

**What should happen:**
Fear should lasts for 5 seconds

**Comment by NightwindOI** [comment]
depend of the rev, depend of the dev's if they gonna change it or not.

**Comment by Travven** [comment]
in wowhead is 3s.

this can be closed.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available now.
