### ISSUE TITLE
[Dungeon] - Maw of Souls - Harbaron

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1871]
**Links:**
https://www.wowhead.com/npc=96754/harbaron
https://www.wowhead.com/spell=194216/cosmic-scythe?dd=1&ddsize=5
https://www.wowhead.com/spell=194266/void-snap?dd=1&ddsize=5
https://www.wowhead.com/spell=194231/summon-shackled-servitor?dd=1&ddsize=5

from WoWHead or our Armory

**What is happening:**
1. The scythe animation is wrong
2. So summoned Servitor cast void snap instantly but repeat their cast instantly after if not kicked.
3. Shackled Servitor "purple prison" stays after their death

**What should happen:**
1. https://www.youtube.com/watch?v=mGOBZGcDmCA&t=12m57s
2. Adds should cast void snap every 6 seconds (approx): [proof](https://www.wowhead.com/maw-of-souls-dungeon-strategy-guide#harbaron-tips-strategy)
3. This "prison" should disappear shortly after the add's death. [proof]( https://www.youtube.com/watch?v=mGOBZGcDmCA&t=13m34s)

**Comment by ShikoSCS** [comment]
Corrected, please review and in case of any error report it.
