### ISSUE TITLE
[Dungeon] - Maw of Souls - Skjal

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1872]
**Links:**
https://www.wowhead.com/npc=99307/skjal#abilities;mode:normal*
https://www.wowhead.com/spell=195250/double?dd=1&ddsize=5
https://www.wowhead.com/spell=196885/give-no-quarter?dd=1&ddsize=5

from WoWHead or our Armory

**What is happening:**
1. Double doesn't exist (was testing on my DK so might be linked to #1850 
2. Give no Quarter has no animation
3. Adds spawn after 4/5 sec aggro

**What should happen:**
1. Should exist
2. Animation [here](https://www.youtube.com/watch?v=mGOBZGcDmCA&t=18m58s)
3. Adds should spawn when the Skjal is aggroed [proof](https://www.youtube.com/watch?v=mGOBZGcDmCA&t=18m50s)

**Comment by ShikoSCS** [comment]
Corrected, please review and in case of any error report it.
