### ISSUE TITLE
 [Tyce] - Maw of Souls - Helya

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1873]
**Links:**
https://www.wowhead.com/npc=96759/helya
https://www.wowhead.com/spell=195309/swirling-water
https://www.wowhead.com/npc=100360/grasping-tentacle
https://www.wowhead.com/spell=197858/turbulent-waters?dd=1&ddsize=5
https://www.wowhead.com/spell=227233/corrupted-bellow?dd=1&ddsize=5
https://www.wowhead.com/spell=197264/taint-of-the-sea?dd=1&ddsize=5
from WoWHead or our Armory

**What is happening:**
Let's go:
1. Swirling waters (that occurs when falling into a hole in the desk) doesn't stun.
2. You can actually stay in the hole for quite some time 
3. Graspy tentacle had a buggy clip for me after a wipe (voluntary wipe ofc) see screen below
4. You sort of float before jumping to Helya platform (see screen 2)
5. Turbulent Waters is inexistant 
6. Corrupted below deals damage 5 times
7. Corrupted Below Damage increase each time you get hit during a cast
8. No more Taint of the Sea after the first Submerge
9. Helya dispawns at 71%
 (TW)

**What should happen:**
1. Swirling waters should stun you for 2 seconds
2. You should be knockbacked on the desk instantly when hit by Swirling waters
3. 
![WoWScrnShot_112820_135554](https://user-images.githubusercontent.com/27277903/100517862-35a42900-318e-11eb-82a1-6ef71863e3f1.jpg)
4. 
![WoWScrnShot_112820_134633](https://user-images.githubusercontent.com/27277903/100517878-540a2480-318e-11eb-884c-f7bdbe47ba42.jpg)
5. There should be Turbulent Water (looks like [that](https://www.youtube.com/watch?v=mGOBZGcDmCA&t=21m50s) -- the blue circle to dodge)
6. Corrupted below should only deal damage 3 times (once a second) [proof](https://www.wowhead.com/maw-of-souls-dungeon-strategy-guide#helya-tips-strategy)
7. Corrupted Below should be the same damage each time it deals damage
8. There should still be Taint of the sea after the first submerge
9. Helya should dispawn at 70% (no one cares in NM/HM/MM but in high M+ this could be an advantage)

**Comment by ShikoSCS** [comment]
Fixes:
Helya: The event of Turbulent Waters works.
195309 Swirling Water: push and stun correctly.

**Comment by Travven** [comment]
this can be closed.
