### ISSUE TITLE
Dargrul and the Hammer

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1874]
**Links:**
https://www.wowhead.com/quest=39027/dargrul-and-the-hammer
from WoWHead or our Armory

**What is happening:**

I dont get credit for -Escape Bitestone Enclave- so i cant complete quest.
Also dialogue with Spiritwalker Ebonhorn is in russian.

**What should happen:**
I should get credit and complete quest.

**Comment by Howizter** [comment]
Confirmed

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
