### ISSUE TITLE
[Quest-Stormheim] - Pump it up (QuestID: 38358)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1875]
**Links:**
https://www.wowhead.com/quest=38358/pump-it-up
from WoWHead or our Armory

**What is happening:**
You can spam click a barrel to complete the quest

**What should happen:**
You should only be able to activate a barrel once

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
