### ISSUE TITLE
[Quest-Stormheim] - A Grim Trophy (QuestID: 38362)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1876]
**Links:**
https://www.wowhead.com/quest=38362/a-grim-trophy#videos:id=94410
from WoWHead or our Armory

**What is happening:**
Nathanos should come with you to help you kill the NPC. Right now he doesn't move

**What should happen:**
See the link

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later.
