### ISSUE TITLE
 [Quest-Stormheim] - Masters of Disguise (QuestID: 38317)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1877]
**Links:**
https://www.wowhead.com/quest=38317/masters-of-disguise
https://www.wowhead.com/npc=97250/forsaken-bat-rider

from WoWHead or our Armory

**What is happening:**
- The NPC where you can turn in the quest is doubled (two stacked up models and you can turn in to both)
- His dialog, doesn't do anything

**What should happen:**
He should be there only once.
- His dialog should fly you back to the "Forsaken Foothold" flightpath.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
