### ISSUE TITLE
[Quest-Stormheim] - Will of the Thorignir (QuestID: 38611)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1878]
**Links:**
https://www.wowhead.com/quest=38611/will-of-the-thorignir
https://www.wowhead.com/npc=96254/havi

**What is happening:**
- The NPC model is present 2 times (stacked up)
- You shouldn't be able to take the quest before doing those quests
  1. https://www.wowhead.com/quest=39592/a-trial-of-will
  2. https://www.wowhead.com/quest=39593/the-shattered-watcher
  3. https://www.wowhead.com/quest=39594/a-trial-of-might
  4. https://www.wowhead.com/quest=39597/the-blessing-of-the-watchers#

**What should happen:**
- NPC model should be here only once
- You shouldn't be able to pick up the quest without doing the 4 I linked in the "what is happening" part.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.

**Comment by Sefrenia-Caecias** [comment]
Fixed. Available in the next update.
