### ISSUE TITLE
[Quest-Stormheim] - Havi's Test (QuestID: 38331)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1879]
**Links:**
https://www.wowhead.com/quest=38331/havis-test

from WoWHead or our Armory

**What is happening:**
The events seems buggy. Sometimes it teleports you inside the barrel of crabs or the pile of stew

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
