### ISSUE TITLE
 [Quest-Stormheim] - Blood and Gold (QuestID: 39595)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1880]
**Links:**
https://www.wowhead.com/quest=39595/blood-and-gold
https://www.wowhead.com/item=128511/challengers-tribute
from WoWHead or our Armory

**What is happening:**
You are still able to loot Challenger's Tribute after completing the quest

**What should happen:**
Challenger's tribute shouldn't loot if you already completed the quest

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
