### ISSUE TITLE
 [Quest-Stormheim] - Yotnar's Head Quest chaining

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1882]
**Links:**
https://www.wowhead.com/quest=39592/a-trial-of-will#videos:id=101072
https://www.wowhead.com/quest=39593/the-shattered-watcher#videos:id=94408

from WoWHead or our Armory

**What is happening:**
You should not be able to pick those quest before finishing this [one](https://www.wowhead.com/quest=39591/a-trial-of-valor)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
