### ISSUE TITLE
[NPC-Stormheim] - Dread-Rider Cullen [NPCID: 92566]

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1883]
**Links:**
https://www.wowhead.com/npc=92566/dread-rider-cullen
from WoWHead or our Armory

The NPC model is present 2 times (stacked up). Should be only one model.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.

**Comment by Sefrenia-Caecias** [comment]
Fixed. Available in the next update.
