### ISSUE TITLE
[Quest-Stormheim] - Impalement Insurance (QuestID: 38615) 

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1885]
**Links:**
https://www.wowhead.com/quest=38615/impalement-insurance
from WoWHead or our Armory

is auto complete

You can use harpoons but they aren't destroyed (just disappear after some time) and it doesn't count for the quest.

For the destruction animation: https://www.wowhead.com/quest=38615/impalement-insurance#videos:id=110333 at 0:16s

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, as there are currently no impediments to completing the quest.
