### ISSUE TITLE
 [Quest-Stormheim] - Another Way (QuestID: 38617) 

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1886]
**Links:**
https://www.wowhead.com/quest=38617/another-way#videos:id=94439

from WoWHead or our Armory

**What is happening:**
 Cullen AI is pretty much broken, she clips through walls, doesn't stop when aggroing NPCs, doesn't hit (or flee) when hit by an NPC. Suicide by jumping from the top of the tower.

**What should happen:**
As you can see on the video she should just run to the NPC you have to kill, attack with you while you kill him, then climb the stairs and stop.

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, as there are currently no impediments to completing the quest.
