### ISSUE TITLE
[Questchaining - Stormheim] - Vethir (NPCID: 91249)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1887]
**Links:**
https://www.wowhead.com/npc=91249/vethir

**What is happening:**
You can pick up [Wings of Liberty](https://www.wowhead.com/quest=38413/wings-of-liberty), [Heart of a Dragon](https://www.wowhead.com/quest=38414/heart-of-a-dragon) and [Fury of the Storm](https://www.wowhead.com/quest=40568/fury-of-the-storm)
 before completing [Above the Winter Moonlight](https://www.wowhead.com/quest=38618/above-the-winter-moonlight)

**What should happen:**
You shouldn't be able to as those quest are chained (only available after completing Above the Winter Moonlight)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
