### ISSUE TITLE
 [Quest-Stormheim] - Fury of the Storm (QuestID: 40568) 

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1889]
**Links:**
https://www.wowhead.com/quest=40568/fury-of-the-storm
https://www.wowhead.com/npc=91566/felskorn-executioner
https://www.wowhead.com/npc=91244/felskorn-trapper
from WoWHead or our Armory

**What is happening:**
Each Felskorn Executioner slain counts as 2 for the quest. No problem when killing the trappers.

**What should happen:**
Should only count as one

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
