### ISSUE TITLE
[Quest-Stormheim] - Wings of Liberty (QuestID: 38413) 

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1890]
**Links:**
https://www.wowhead.com/quest=38413/wings-of-liberty
from WoWHead or our Armory

**What is happening:**
There is no animation when you free a drake and you can free him again (useless to do so but you can)

**What should happen:**
A time code for what the animation of each drake should look like (1, 2 and 3 are the same animation but with different dialog)
1. [Hrafsir](https://www.youtube.com/watch?v=4xYuN0yEI3U&t=38s) 
2. [Erilar](https://www.youtube.com/watch?v=4xYuN0yEI3U&t=1m02s) 
3. [Hridmogir](https://www.youtube.com/watch?v=4xYuN0yEI3U&t=1m18s) 
4. [Aleifir](https://www.youtube.com/watch?v=4xYuN0yEI3U&t=2m16s)

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, as there are currently no impediments to completing the quest.
