### ISSUE TITLE
 [Quest-Stormheim] - Heart of a Dragon (QuestID: 38414) 

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1891]
**Links:**
https://www.wowhead.com/quest=38414/heart-of-a-dragon

from WoWHead or our Armory

**What is happening:**
It lacks animation of green "chains" on Thrymjaris and RP at the end

**What should happen:**
Animation before the kill : https://www.youtube.com/watch?v=hUmQ_cm4Mtc&t=1m52s
RP after the kill : https://www.youtube.com/watch?v=hUmQ_cm4Mtc&t=2m40s

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, as there are currently no impediments to completing the quest.
