### ISSUE TITLE
[NPC - Stormheim] - Felskorn Subduer

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1892]
**Links:**
https://www.wowhead.com/npc=91759/felskorn-subduer
from WoWHead or our Armory

**What is happening:**
They aren't doing anything, if you hit them they continue their pathing without minding you

**What should happen:**
They should hit you back with their abilities

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
