### ISSUE TITLE
 [Quest-Stormheim] - Where dragons rule (QuestID: 39652) 

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1893]
**Links:**
https://www.wowhead.com/quest=39652/where-dragons-rule#videos:id=94437
from WoWHead or our Armory

**What is happening:**
You get teleported to the summit. And this happens
![WoWScrnShot_112920_115947](https://user-images.githubusercontent.com/27277903/100539975-82ddd480-323a-11eb-9238-845237c3deb4.jpg)

**What should happen:**
As you can see on the video, you should fly then plenty of RP talk. And there shouldn't be this clusterfuck of Vethir

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, as there are currently no impediments to completing the quest.
