### ISSUE TITLE
The Final Judgement

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#1894]
**Links:**

https://www.wowhead.com/quest=38818/the-final-judgment#
https://www.wowhead.com/npc=93093/runeseer-faljar

**What is happening:**

1. There are two Runeseer Faljars spawned. One is level 101, the second one is 110 (one-shotting lower level payer)

2. Dialogue, abilities and "quest completion event animation" are missing.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Autocomplete Temporal Fix. Available in the next update.
