### ISSUE TITLE
 [Quest-Stormheim] - The Dark Lady's Bidding (QuestID: 38872) 

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1895]
**Links:**
https://www.wowhead.com/quest=38872/the-dark-ladys-bidding
https://www.wowhead.com/npc=93624/dread-rider-cullen
from WoWHead or our Armory

**What is happening:**
- Cullen has his dialog line before you pick up the quest
- The dialog line (that should fly you to Nathanos) isn't working

**What should happen:**

- Cullen should only have her dialog line after you pick up the quest
- The dialog line should fly you to Nathanos [proof](https://www.wowhead.com/quest=38872/the-dark-ladys-bidding#videos:id=136164)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
