### ISSUE TITLE
 [Quest-Stormheim] - Turn the keys (QuestID: 38778) 

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1897]
**Links:**
https://www.wowhead.com/quest=38778/turn-the-keys
from WoWHead or our Armory

**What is happening:**
There is no animation (the top of the keystone just disappears) when you activate a keystone and if you spam click it can proc the quest twice (2/3 with only one keystone)

**What should happen:**
There should be an [animation](https://www.youtube.com/watch?v=3XFbANeQrNY&t=1m10s) and you shouldn't be able to get 2/3 with only one key

**Comment by Cefiro-Caecias** [comment]
Fixed, although I couldn't find cosmetic spells for rotation and aura effects. Available in the next update.
