### ISSUE TITLE
 [Quest-Stormheim] - The Runes That Bind (QuestID: 38823)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1899]
**Links:**
https://www.wowhead.com/quest=38823/the-runes-that-bind
from WoWHead or our Armory

**What is happening:**
No animation when breaking the runes and some of them are clickable while broken

**What should happen:**
Here's the animation https://www.youtube.com/watch?v=f96NaG-Bkpw&t=16s.
Runes should only be usable when not broken

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
