### ISSUE TITLE
[Saitama] - Spell Aimed Shot Movement Glitch

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#19]
Class: Hunter
Spec: Marksman
Spells: [Arcane Shot](https://www.wowhead.com/spell=185358/arcane-shot)/[Aimed Shot](https://www.wowhead.com/spell=19434/aimed-shot)
**What is happening:**
After casting [Arcane Shot](https://www.wowhead.com/spell=185358/arcane-shot), if you cast [Aimed Shot](https://www.wowhead.com/spell=19434/aimed-shot) and begin moving, the spell continues casting, and the cast bar continues showing. When the (bugged, while moving) spell finishes casting, an arrow is shot, but it does not deal any damage. You can also cast other spells while this glitched aimed shot is being cast.
**What should happen:**
When casting [Aimed Shot](https://www.wowhead.com/spell=19434/aimed-shot), any movement should stop the channeling for the spell, and there should be no cast bar or arrow shot when/after you begin moving, be it before or after casting [Arcane Shot](https://www.wowhead.com/spell=185358/arcane-shot).

**Comment by login6710** [comment]
Fixed
