### ISSUE TITLE
Cragjaw is Evading

### ISSUE THREAD

**Issue by Crimson-tear** [GuabinaCore/WoWKoi#190]
**Links:**
https://www.wowhead.com/npc=41064/cragjaw
from WoWHead or our Armory

**What is happening:**
The Cragjaw is evading even though is not stuck into anything. It does not argo either

**What should happen:**
It should be killable, else can not proceed with the quest line for Stonetalon Mountain zone.
https://www.wowhead.com/quest=26043/beware-of-cragjaw

**Comment by Cefiro-Caecias** [comment]
Adjustment applied. Available in the next update.
