### ISSUE TITLE
 [Quest-Stormheim] - The Final Judgment (QuestID: 38818)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1900]
**Links:**
https://www.wowhead.com/quest=38818/the-final-judgment#videos:id=100643
from WoWHead or our Armory

**What is happening:** Faljar is present twice and there is no event going on

**What should happen:**
There should be an event (as you can see in the video)
Faljar should only be here once

**Comment by NightwindOI** [comment]
https://github.com/GuabinaCore/WoWKoi/issues/1894 duplicate
