### ISSUE TITLE
 [Quest-Stormheim] - An Unworthy Task (QuestID: 39837)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1901]
**Links:**
https://www.wowhead.com/quest=39837/an-unworthy-task#videos:id=94453
from WoWHead or our Armory

**What is happening:**
- Ashildir model is present twice
![WoWScrnShot_112920_125623](https://user-images.githubusercontent.com/27277903/100541199-68a7f480-3242-11eb-9df9-c9be803668b2.jpg)

- Quest is auto-complete

**What should happen:**
- Ashildir should run from Helheim entrance to his second position
- Quest shouldn't be auto complete (see video)

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later.
