### ISSUE TITLE
 [Quest-Stormheim] - Sundered (QuestID: 39850)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1902]
**Links:**
https://www.wowhead.com/quest=39850/sundered
from WoWHead or our Armory

**What is happening:**
![WoWScrnShot_112920_131022](https://user-images.githubusercontent.com/27277903/100541470-75c5e300-3244-11eb-8ed8-7e4630358c8c.jpg)

**What should happen:**
Should be your character model in chains.

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later.
