### ISSUE TITLE
[Quest-Stormheim] - Paid in Lifeblood (QuestID: 39855) 

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1903]
Maybe linked to #1898 
**Links:**
https://www.wowhead.com/quest=39855/paid-in-lifeblood
from WoWHead or our Armory

**What is happening:**
No event and Helya is not here.

**What should happen:**
https://www.wowhead.com/quest=39855/paid-in-lifeblood#videos:id=100671
show the event and how the Helya should be, etc etc

**Comment by Cefiro-Caecias** [comment]
Autocomplete Temporal Fix. Available in the next update.
