### ISSUE TITLE
 [Quest-Stormheim] - A Heavy Burden (QuestID: 40078) 

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1904]
**Links:**
https://www.wowhead.com/quest=40078/a-heavy-burden
from WoWHead or our Armory

**What is happening:**
This quest doesn't exist

**What should happen:**
This quest should validate To Hellheim and Back! for the Stormheim questline achievement (on the server it's validated by https://www.wowhead.com/quest=39855/paid-in-lifeblood)
This quest is a small event: https://www.wowhead.com/quest=40078/a-heavy-burden#videos:id=103427

**Comment by Cefiro-Caecias** [comment]
As I see in the system, the quest "A Heavy Burden" is unlocked after you complete the quest "Shadows in the Mists" (https://www.wowhead.com/quest=40044). If it's not correct, let me know.
