### ISSUE TITLE
[Quest-Dalaran] An Important Mission

### ISSUE THREAD

**Issue by justSelim** [GuabinaCore/WoWKoi#1905]
**Links:**

https://www.wowhead.com/quest=42814/an-important-mission

**What is happening:**

Danath Trollbane [ ID: 96183 ] doesn´t show up, better said none of these npcs which should show up doesn`t

**What should happen:**

Danath Trollbane [ ID: 96183 ] should show up or better said like Khadgar and every other npc should stay on Krasus Landing

**Comment by Cefiro-Caecias** [comment]
Fixed. Available now.
