### ISSUE TITLE
[NPC-Broken Isles] Burning Hellion 

### ISSUE THREAD

**Issue by justSelim** [GuabinaCore/WoWKoi#1907]
**Links:**

https://www.wowhead.com/npc=90660/burning-hellion

**What is happening:**

These NPC's are doing so much dmg like some raid bosses. Between 30k-80k dmg per sec. It is literally impossible to kill them without dying if you don't have high iLvL Equip. Look at the Screenshot I attached. 
![WoWScrnShot_112920_155738](https://user-images.githubusercontent.com/19872202/100545353-be3ccb00-325b-11eb-934a-dc8be17eae9c.jpg)

**What should happen:**

They literally shouldnt do so much damage.
https://youtu.be/MhrfPoY0Pv0?t=124 <----- You can watch how much damage they do literally ( no stats or anything to see right now)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
