### ISSUE TITLE
[Quest-Stormheim] - A Gift for greymane (QuestID: 39385)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1908]
**Links:**
https://www.wowhead.com/quest=39385/a-gift-for-greymane
from WoWHead or our Armory

**What is happening:**
- [Nathanos](https://www.wowhead.com/npc=93603/nathanos-blightcaller) gives you the quest
- Explosives are already set
- By clicking an explosive underwater, putting camera over water resets the state of the explosive allowing you to reclick it (spamming one to complete the quest)
- No animation when you detonate the explosives 

**What should happen:**
- [Those](https://www.wowhead.com/object=243454/gilnean-heavy-explosive) should give you the quest
- Explosive shouldn't be already set, but instead have a yellow placeholder (See [here](https://www.youtube.com/watch?v=8wq37Gf0kEQ&t=17s))
- You shouldn't be able to click an explosive multiple times
- Animation should occur on the boat when detonating the explosives (See [here](https://www.youtube.com/watch?v=8wq37Gf0kEQ&t=1m30s))

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
