### ISSUE TITLE
[Quest-Stormheim] - To Skold-Ashil (QuestID: 39154)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1909]
**Links:**
https://www.wowhead.com/quest=39154/to-skold-ashil#videos:id=100691
from WoWHead or our Armory

**What is happening:**
- The boat you are supposed to take is underwater
![WoWScrnShot_112920_160324](https://user-images.githubusercontent.com/27277903/100545540-9e59d700-325c-11eb-899f-779568cc7b84.jpg)
- The boat doesn't move

**What should happen:**
Pretty much what's shown in the video linked

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
