### ISSUE TITLE
We Need More Powder! Quests - Professions - Alchemy

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1910]
**Links:**
https://www.wowhead.com/quest=39336/we-need-more-powder
https://www.wowhead.com/npc=95748/katterin-the-blistered
https://www.wowhead.com/item=128345/katterins-alchemy-kit

from WoWHead or our Armory

**What is happening:**

Katterin the Blistered <Alchemist> simply dissapear when her HP hits 0

**What should happen:**

**Katterin the Blistered <Alchemist>** should simply drop death so you can loot her the  **Katterin's Alchemy Kit**

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_112820_215755](https://user-images.githubusercontent.com/73371905/100545738-ba954e00-3233-11eb-83fe-768296c0ad4e.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
