### ISSUE TITLE
[NPC-Azsuna] 

### ISSUE THREAD

**Issue by justSelim** [GuabinaCore/WoWKoi#1911]
**Links:**

https://www.wowhead.com/npc=109326/leystone-spiderling

**What is happening:**

The NPC's with the ID 109326 or with the Name Leystone Spiderling are doing high damage which shouldnt be the case. They are doing like the same damage like Raid Bosses.
Look at the Screenshot I attached
![WoWScrnShot_112920_160930](https://user-images.githubusercontent.com/19872202/100545736-9fd7cf00-325d-11eb-8f79-27a98d2e34ed.jpg)

**What should happen:**

They shouldnt do so much damage like on this Youtube Video.
https://youtu.be/ZrnYDW1yHU0?t=170

**Comment by Cefiro-Caecias** [comment]
Fixed. Available now.
