### ISSUE TITLE
[Quest-Stormheim] - Shielded Secrets (QuestID: 38878)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1912]
**Links:**
https://www.wowhead.com/quest=38878/shielded-secrets
from WoWHead or our Armory

**What is happening:**
![image](https://user-images.githubusercontent.com/27277903/100545739-a5351980-325d-11eb-9a57-f0c222095c7c.png)

As you can see on the screenshot:
- Text is mostly in spanish (or portuguese, I'm sorry I can't tell)
- You can do the english part by spam clicking one shield

**What should happen:**
- Only the first line should be displayed
- You should be allowed to click on each shield only once

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
