### ISSUE TITLE
[NPC - Stormheim] - Tideskorn Warbear (NPCID: 98955)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#1913]
**Links:**
https://www.wowhead.com/npc=98955/tideskorn-warbear
from WoWHead or our Armory

**What is happening:**
They aren't doing anything, if you hit them they continue their pathing without minding you

**What should happen:**
They should hit you back with their abilities

_Might be the same bug as #1892_

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
