### ISSUE TITLE
Eye of Azshara: The Heart of Zin-Azshari Quests- Legion - Artifact

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1914]
**Links:**
https://www.wowhead.com/quest=40668/eye-of-azshara-the-heart-of-zin-azshari
https://www.wowhead.com/item=132738/heart-of-zin-azshari

from WoWHead or our Armory

**What is happening:**

Cant loot Heart of Zin-Azshari

**What should happen:**

Item should be able to be looted on sight

![WoWScrnShot_112820_083115](https://user-images.githubusercontent.com/73371905/100545861-81a9a900-3234-11eb-880d-4f6ba7210ff5.jpg)

**Comment by Nephilimkoi** [comment]
![Uploading WoWScrnShot_112920_113451.jpg…]()

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_112920_113451](https://user-images.githubusercontent.com/73371905/100546297-fed61d80-3236-11eb-9db8-716e82fef6d5.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
