### ISSUE TITLE
Insurrection - Quests - Legion - Suramar Part 1 [LOCKDOWN]

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1915]
**Links:**
1)https://www.wowhead.com/quest=38649/silence-in-the-city
2) https://www.wowhead.com/quest=38695/crackdown
3) https://www.wowhead.com/quest=38694/regroup
from WoWHead or our Armory

**What is happening:**

1) Sometimes Chief Telemancer Oculeth is phasing and isnt in his postion despite the quest mark in the map pointing at the position he should be.

2) Sometimes the pad doesnt work and you have to abandon the quest. and retake it. 

3) Silgryn simply phases away. the gondola moves underwater... rather than on top of it.

![WoWScrnShot_110720_124135](https://user-images.githubusercontent.com/73371905/100546742-5ecdc380-3239-11eb-9ed3-41a25fe833fb.jpg)
 
- Follow Silgryn
- Ride on Deline's Gondola
- Teleport to the Top of the Terrace

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
