### ISSUE TITLE
Insurrection - Quests - Legion - Suramar Part 2 [Missing Persons] & 3 [Waxing Crescent]

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1916]
**Links:**

1)https://www.wowhead.com/quest=44725/hostage-situation
2)https://www.wowhead.com/quest=44742/tavernkeepers-fate

from WoWHead or our Armory

**What is happening:**
1) Quest Autocompletes 
2) You have to take the portal several times  till the objetives complete so you can proceed with the quest.

- Take the Portal to Lunastre Estate
- Learn of Vanthir's Fate

**Comment by Cefiro-Caecias** [comment]
Did not give me any error o.O
