### ISSUE TITLE
Insurrection - Quests - Legion - Suramar Part 4 [An Elven Problem]

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1917]
**Links:**
1)https://www.wowhead.com/quest=40391/take-me-to-your-leader
2)https://www.wowhead.com/quest=44831/taking-a-promenade
3)https://www.wowhead.com/quest=41916/a-better-future
4)https://www.wowhead.com/quest=44834/nullified
from WoWHead or our Armory

**What is happening:**

1) Sometimes phases away others times he simply stay put.
2) Quest Autocompletes
3) Quest Autocompletes
4) Quest Autocompletes

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
They will become blizzlike later on.
