### ISSUE TITLE
Insurrection - Quests - Legion - Suramar Part 5 [Crafting War]

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1918]
**Links:**
1)https://www.wowhead.com/quest=44928/somethings-not-quite-right
2)https://www.wowhead.com/quest=44829/we-need-weapons
3) https://www.wowhead.com/quest=44874/unbeleyvable
4)https://www.wowhead.com/quest=44875/the-art-of-flow
5)https://www.wowhead.com/quest=44876/a-dance-with-dragons
from WoWHead or our Armory

**What is happening:**

1) Some Infiltrators are already exposed.
2) You can just complete the quest by clicking fast the same one.
3) 
- The Script never starts.
- Somehow the quest is optional and you dont need to complete it to proceed,
4) Since the (3) is somehow optional and cannot be completed this one cant be started.
5) Same as (4)

**Comment by Cefiro-Caecias** [comment]
1) It gave me no faults.
2) Fixed.
3) Autocomplete Temporal Fix.
4) Autocomplete Temporal Fix.
5) Autocomplete Temporal Fix.
