### ISSUE TITLE
Insurrection - Quests - Legion - Suramar Part 6 [ March on Suramar] & Part 7 [ Elisande's Retort]

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1919]
**Links:**
1)https://www.wowhead.com/quest=44738/full-might-of-the-elves

2)https://www.wowhead.com/quest=44822/temporal-investigations
from WoWHead or our Armory

**What is happening:**

1) friendly npcs dont move. they just phase away to the next location.

2)Quest Autocompletes

**Comment by Cefiro-Caecias** [comment]
1) Autocomplete Temporal Fix.
2) It will become blizzlike later.
