### ISSUE TITLE
Get to High Ground

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1922]
**Links:**
https://www.wowhead.com/quest=38909/get-to-high-ground
from WoWHead or our Armory

**What is happening:**
 I dont get credit for Lead Jale Rivermane to Thunder Totem
Jale Rivermane has wrong name: Highmountain Shaman

**What should happen:**
I get credit so i can continue.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. Due to a texture problem, the vaquita will not accompany you to where Mayla Highmountain is, since due to a texture defect, she goes crazy when trying to cross the bridge. However, you will be able to complete the quest normally.
