### ISSUE TITLE
The Scythe of Souls

### ISSUE THREAD

**Issue by outremague** [GuabinaCore/WoWKoi#1923]
Links: https://www.wowhead.com/quest=37660/the-scythe-of-souls

What is happening: Breaking either of the soul gems doesn't do anything.

What should happen: After breaking the gem, the Demon Soul appears and you have to defeat it, if memory serves me right.
![WoWScrnShot_112920_232422](https://user-images.githubusercontent.com/75224441/100554052-e4359000-329a-11eb-8e14-d5168d5d73b9.jpg)

**Comment by NightwindOI** [comment]
duplicate
https://github.com/GuabinaCore/WoWKoi/issues/1720
