### ISSUE TITLE
NPC duplicates

### ISSUE THREAD

**Issue by Bunny9421** [GuabinaCore/WoWKoi#1925]
**Links:**

from WoWHead or our Armory

**What is happening:**
![image](https://user-images.githubusercontent.com/75498851/101200884-ce3f1b00-365e-11eb-8ec3-7d2c5c479415.png)
![image](https://user-images.githubusercontent.com/75498851/101201753-232f6100-3660-11eb-8f41-91ff323cd337.png)
![image](https://user-images.githubusercontent.com/75498851/101202477-3a228300-3661-11eb-9170-362806aa492d.png)

There are duplicates of NPC's and for examples where Geth'Xun has not arrived at the edge of shaman's The Maelstrom zone but instead, he just appeared here like legion "stormborne Infer".  All NPC's are just standing there doing nothing.  They should have engaged each other in defending/attacking "The Maelstrom" this place but instead are standing dummies. 

**What should happen:**

https://www.wowhead.com/npc=97386/gethxun

Geth'Xun should have fly and say "Are you the so-called "World Shaman?" Hah! You fight like a crippled pig. Come on Thrall, clearly, the correct response to that is "How appropriate, you fight like a cow". after that he should have jumped off his mount and start attacking Thrall.

The Stormborne Infernal should have arrived at "The Maelstrom" by falling from the sky and breaking up when hitting the ground and then re-assembling themself as infernals. 

Since duplication of Geth'Xun NPC one flying on the mount without jumping and another standing on the edge, Thrall also has stuck and would not proceed toward attacking Geth'Xun. This is bugged to the level that this quest cannot be completed there fore cannot aquire legendary weapon.

**Comment by Bunny9421** [comment]
Target is invalid and cannot be killed. Seen a similar issue with Sylvanas quest just outside of Ogrimar where two Sylvanas are available for interaction. Also, all Infernals and legion NPC are spawn before the quest is started which is incorrect. 

![image](https://user-images.githubusercontent.com/75498851/101204557-507e0e00-3664-11eb-98f3-90b66f6a1853.png)
![image](https://user-images.githubusercontent.com/75498851/101204591-5e339380-3664-11eb-9c74-4a871214f771.png)
Same issue in Ogrimar where NPC's are scattered around and should not be anywhere besides their own posts. 
In the picture, you can see clearly duplicates of npc's all over the map. 
![image](https://user-images.githubusercontent.com/75498851/101204733-976c0380-3664-11eb-90e7-3dbbce03d731.png)
![image](https://user-images.githubusercontent.com/75498851/101204836-c6827500-3664-11eb-9b25-71c09128ae9f.png)

The same can be seen in Dalaran.
![image](https://user-images.githubusercontent.com/75498851/101204789-b10d4b00-3664-11eb-9275-a7bf39800902.png)

**Comment by Cefiro-Caecias** [comment]
Re-phasing.
