### ISSUE TITLE
The Nexus Vault

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1926]
**Links:**
https://www.wowhead.com/quest=42011/the-nexus-vault#comments
from WoWHead or our Armory

**What is happening:**

After killing all 3 Scions of magic,  Azuregos just disappear. 

**What should happen:**
I should walk with  Azuregos to ice wall.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
