### ISSUE TITLE
The Path of Atonement

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1927]
**Links:**
https://www.wowhead.com/quest=40270/the-path-of-atonement#comments
from WoWHead or our Armory

**What is happening:**

Aethas Sunreaver disappear in middle of dialogue.
I dont get credit for listening after dialogue, so I cant complete quest.

**What should happen:**
I should get credit and turn in the quest to Aethas Sunreaver

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
