### ISSUE TITLE
Their Dying Breaths Quests - Legion - Azsuna

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1929]
**Links:**
https://www.wowhead.com/quest=42271/their-dying-breaths#comments
from WoWHead or our Armory

**What is happening:**

1) You can see the Grievously Wounded Whelpling Before collecting the cristals

2) After collecting the cristals you cant revive the  Grievously Wounded Whelpling

**What should happen:**

> NOW you go into the cave (49.36 25.90) you kept trying to use for  The Death of the Eldest. You want the sharpest/bluest/most opaque of the crystals (users have submitted screenshots).
> 
> Once you have 4, exit the cave and use the crystals on the Mana-Drained Whelpling that are lying on the ground around Agapanthus.

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_121020_194207](https://user-images.githubusercontent.com/73371905/101843302-4d7d9480-3b20-11eb-810d-897f8345fdb6.jpg)
![WoWScrnShot_121020_194233](https://user-images.githubusercontent.com/73371905/101843304-4eaec180-3b20-11eb-85c5-120d2a8f2bda.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed.
