### ISSUE TITLE
[Mob] Venture Co. Drudger, Venture Co. Mercenary, and Overseer Glibby not scaled up to player level

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#193]
**Links:**
https://www.wowhead.com/npc=6606/overseer-glibby
https://www.wowhead.com/npc=3284/venture-co-drudger
https://www.wowhead.com/npc=3282/venture-co-mercenary
**What is happening:**
Venture Co. Drudgers, Venture Co. Mercenaries and Overseer Glibby are not scaled up to player level.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
