### ISSUE TITLE
The Tirisgarde Reborn

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1933]
**Links:**
https://www.wowhead.com/quest=41124/the-tirisgarde-reborn
from WoWHead or our Armory

**What is happening:**

Meryl do not give me title-> can't complete quest -> can't progress.

**What should happen:**
Meryl should talk, give me title and I should be able to complete quest.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
