### ISSUE TITLE
Runas Knows the Way Quests - Legion - Azsuna (Re-Report)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1935]
**Links:**
https://www.wowhead.com/quest=37857/runas-knows-the-way
from WoWHead or our Armory

**What is happening:**

https://github.com/GuabinaCore/WoWKoi/issues/1930
After the fix. the quest is still bugged. 
 
You still cant get the credit for it.

**Comment by Cefiro-Caecias** [comment]
Fixed.
