### ISSUE TITLE
You Scratch My Back...

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1936]
**Links:**
https://www.wowhead.com/quest=37860/you-scratch-my-back#comments
from WoWHead or our Armory

**What is happening:**

After destroying pylons, nothing happens.

**What should happen:**
After destroying, completion popup should show.

**Comment by NightwindOI** [comment]
Must be ok with the server update (please delete cache folder)
Please re-check and let me know.

**Comment by Cefiro-Caecias** [comment]
Fixed.

**Comment by NightwindOI** [comment]
Still not working

**Comment by Dragonsworn** [comment]
Quest not working, Should auto complete but didn't. It is completed but still in quest list.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available now.
