### ISSUE TITLE
The Price of the Black Market Quests - Professions - Alchemy

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1938]
**Links:**
https://www.wowhead.com/quest=39342/the-price-of-the-black-market
https://www.wowhead.com/item=136723/silver-hair-of-khadgar
from WoWHead or our Armory

**What is happening:**

Khadgar silver hair never gets to your inventory. and the moment you open the window to take the hair your invisivilty gets dispelled

**What should happen:**

https://www.wowhead.com/item=136723/silver-hair-of-khadgar#comments
"Use Recipe: Skaggldrynk potion to get Silver Hair of Khadgar ;)"

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_113020_171642](https://user-images.githubusercontent.com/73371905/102269596-3f9a8b80-3ef3-11eb-9ef2-890745546126.jpg)
![WoWScrnShot_113020_171716](https://user-images.githubusercontent.com/73371905/102269612-46290300-3ef3-11eb-8517-b072c792d4e9.jpg)
![WoWScrnShot_113020_171641](https://user-images.githubusercontent.com/73371905/102269624-4aedb700-3ef3-11eb-9bca-fc376d9020e0.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available now.
