### ISSUE TITLE
problemas con artefactos

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#1940]
hare un solo report por todos los problemas que ya habia reportado de los artefactos en un solo lugar, creo que es mas organizado

1)picaro forajido: al elegir el arma que deseas no tiene traduccion el panel de eleccion, luego se hace imposible completar la mision ya que https://es.wowhead.com/npc=102293/almirante-aterradora-eliza te mata de 1 solo hit 
![WoWScrnShot_110120_023822](https://user-images.githubusercontent.com/44954266/102308159-6fba4c80-3f3c-11eb-886c-13093b8966d8.jpg)

2) shaman enhancement: se puede pasar directo a la sala donde se encuentra el doom hammer sin completar la mision
![WoWScrnShot_110320_101402](https://user-images.githubusercontent.com/44954266/102308649-7dbc9d00-3f3d-11eb-8362-7c8f44cb1a9d.jpg)

3) warlock: un problema en la etapa general impide continuar de la 2da etapa de el evento https://www.wowhead.com/quest=40729/the-new-blood 
![WoWScrnShot_110420_231738](https://user-images.githubusercontent.com/44954266/102308807-d5f39f00-3f3d-11eb-9fc8-f1f5b61d797f.jpg)

4)mage: al igual que el warlock un problema en la etapa general impide avanzar, en la primera etapa de el evento https://www.wowhead.com/quest=41036/the-dreadlords-prize 
![WoWScrnShot_110720_001402](https://user-images.githubusercontent.com/44954266/102309093-6df18880-3f3e-11eb-9d3c-7fa7edeffb9d.jpg)

5)druida feral(horda): el primer problema que me encontre es que la mision https://www.wowhead.com/quest=40645/to-the-dreamgrove esta en autocompletar y molesta un poco para continuar con la cadena, luego ya al entrar en la mision de el artefacto no puedes pasar de la primera etapa ya que no se derriba la puerta 
![WoWScrnShot_111020_005713](https://user-images.githubusercontent.com/44954266/102309295-db051e00-3f3e-11eb-85c3-d3cdb3aea67c.jpg)

6)priest shadow: al iniciar la cadena de el artefacto, en la primera etapa te pide tomar 3 pistas de unos libros, pero no cuenta ninguna https://www.wowhead.com/quest=40710/blade-in-twilight
![WoWScrnShot_111020_135027](https://user-images.githubusercontent.com/44954266/102309450-2fa89900-3f3f-11eb-954e-473be1c27c79.jpg)

7)dk unholy: en la 3ra etapa de el evento https://www.wowhead.com/quest=40934/the-dark-riders te pide matar a "el conservator" el cual hace demasiado daño e impide continuar con la mision, adicional a eso si mueres el npc que te deberia acompañar para poder completar la mision desaparece terminando de dañar la cadena 
![WoWScrnShot_111120_235617](https://user-images.githubusercontent.com/44954266/102309755-e442ba80-3f3f-11eb-8b28-50dfe794ee0b.jpg)

8) warrior: en la etapa general al iniciar el evento https://www.wowhead.com/quest=38904/return-to-the-broken-shore no avanza de la primera etapa luego de haber llegado a la playa 
![WoWScrnShot_111720_200823](https://user-images.githubusercontent.com/44954266/102309847-1e13c100-3f40-11eb-88a2-263b6cde4995.jpg)

**Comment by NightwindOI** [comment]
No idea what you say...but by the look at it, it must be artifact quest's issues.

**Comment by Cefiro-Caecias** [comment]
1) Reparado.
2) No sé de cuál misión hablas.
3) Fix temporal de autocompletado.
4) Reparado.
5) Reparado.
6) Reparado.
7) Reparado.
8) Fix temporal de autocompletado.

Disponibles luego del próximo update.
