### ISSUE TITLE
Nar'thalas Academy quests

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1941]
**Links:**
https://www.wowhead.com/quest=37729/pop-quiz-advanced-rune-drawing#comments
https://www.wowhead.com/quest=42370/wanding-101
https://www.wowhead.com/quest=42371/study-hall-combat-research
https://www.wowhead.com/quest=37530/save-yourself
from WoWHead or our Armory

**What is happening:**

- quests are autocompleted

**What should happen:**

**Comment by NightwindOI** [comment]
I'll assign Sef to check them out when he can, but Autocomplete may be set for a reason so won't block the progress of the zone, but will be finished/polished later on.

**Comment by Cefiro-Caecias** [comment]
Indeed, those 4 quests were in autocomplete mode, and they will be made full blizzlike in the future, don't worry ;)
