### ISSUE TITLE
[Tyce] - Shaman - Spell Hex (51514)

### ISSUE THREAD

**Issue by gankyplanky** [GuabinaCore/WoWKoi#1942]
**Links:**

https://www.wowhead.com/spell=51514/hex

**What is happening:**

When Hexed hostile mobs act as normal

**What should happen:**

When Hexxed mobs should ignore hostile targets untill attacked

Spell ID : 51514
![WoWScrnShot_122120_223410](https://user-images.githubusercontent.com/56677315/102824393-083d4a80-43dd-11eb-8ec3-0bf9f16a62b4.jpg)
![WoWScrnShot_122120_223402](https://user-images.githubusercontent.com/56677315/102824424-14c1a300-43dd-11eb-9bcb-ce3cc44be303.jpg)

**Comment by Arkanheal** [comment]
Hex should still put you in combat if you walk too close to the frog
