### ISSUE TITLE
Elemental Shaman Artifact

### ISSUE THREAD

**Issue by Liquidzwow** [GuabinaCore/WoWKoi#1943]
**Links:**

from WoWHead or our Armory

**What is happening:**
First part when you are collecting pieces from elites is not working, you cant get into temple. Even first elite is not spawning, for some players it was working but not for me. 

**What should happen:**
You should be able to enter temple, finish the first objecitve and then kill all the elites and collect items from them.

**Comment by Cefiro-Caecias** [comment]
What quest? I need exact information ^^
