### ISSUE TITLE
Monk Brewmaster artifact quests not working 

### ISSUE THREAD

**Issue by gankyplanky** [GuabinaCore/WoWKoi#1944]
**Links:**

1) https://www.wowhead.com/quest=42868/the-monkey-kings-challenge#videos:id=100349
2)https://www.wowhead.com/quest=42765/the-trial-at-the-temple#videos:id=100350

**What is happening:**

1)The Monkey king's challange- After accepting nothing happenes and quest can't be turned in.
2)The trial at the temple - After the scenario is over and you take the ride on Yu'lon(ID:109391) to The Wandering Isle and the quest isnt completed.

**What should happen:**
1)Several object should appear and you should be able to interact with them in the order The Monkey King(ID:109187) requests.
2)After the scenario you should be able to take a ride on Yu'lon to The Wandering Isle and the quest should be completed.

1)Quest ID: 42868
2)Quest ID: 42765

**Comment by Cefiro-Caecias** [comment]
1) Temporal Autuocomplete Fix.
2) Fixed.

Available in the next update.
