### ISSUE TITLE
Scouting map in Monk class hall not appearing 

### ISSUE THREAD

**Issue by gankyplanky** [GuabinaCore/WoWKoi#1945]
**Links:**

https://www.wowhead.com/quest=41945/tianji-of-the-ox#comments

**What is happening:**

When accepting the quest tianji of the Ox scouting map isn't appearing (Interestingly the object itself is there but not visible as i was able to collide with it, but not see or interact)

**What should happen:**

Accepting the Quest should unlock the Scouting map 

Quest ID: 41945

As you can see there the quest is accepted but no scouting map
![WoWScrnShot_122120_225720](https://user-images.githubusercontent.com/56677315/102826204-818a6c80-43e0-11eb-9c09-5e52fbf15c18.jpg)

**Comment by gankyplanky** [comment]
A lil update: The scouting map in Vindicaar was working as intended and i was able to do quests and other stuff there

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
