### ISSUE TITLE
[Tyce] - Protection Warrior - Spell Charge Bugged

### ISSUE THREAD

**Issue by Liquidzwow** [GuabinaCore/WoWKoi#1947]
**Links:**

from WoWHead or our Armory

**What is happening:**
Simply, charge doesnt work. You cannot charge to enemies becouse they are lined all the time.
Charging to allies actually works fine, the animation is not perfect but it works. 

**What should happen:**
You should be able to charge to enemies and allies with your charge/intercept.

**Comment by Travven** [comment]
I dont understand what is what work bad
