### ISSUE TITLE
[Tyce] - Mage Class Hall - Teleportation Nexus Order Advancement (386)

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1950]
**Links:**
https://www.wowhead.com/order-advancement=386/teleportation-nexus
from WoWHead or our Armory

**What is happening:**

Not working- there is no portals.

**What should happen:**
There should be portals after researching it.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.

**Comment by Megafla** [comment]
Nothing yet?
