### ISSUE TITLE
crossroads caravan pickup

### ISSUE THREAD

**Issue by nalberthdionisio** [GuabinaCore/WoWKoi#1954]
**Links:**

https://pt.wowhead.com/quest=13949/escolta-para-a-caravana-da-encruzilhada

from WoWHead or our Armory

**What is happening:**

when the quest is accepted and we click on the NPC to start the quest nothing happens

**What should happen:**

when a mission is accepted and clicks on the NPC to start a mission the NPC was supposed to put us in a caravan and escort us to the end of the mission using a weapon to kill the mobs who were going to try to steal the cargo

**Comment by NightwindOI** [comment]
Server gonna be Instant 100 so we focus on the Legion part for now, but thx for the report!

**Comment by Cefiro-Caecias** [comment]
Applied autocomplete temporary fix; it will be repaired full blizzlike later. Available in the next update.
