### ISSUE TITLE
animal services

### ISSUE THREAD

**Issue by nalberthdionisio** [GuabinaCore/WoWKoi#1955]
**Links:**

https://www.wowhead.com/quest=13970/animal-services

from WoWHead or our Armory

**What is happening:**

you can't interact with the bag-shaped items that are scattered around the map and hostile mobs are paralyzed

**What should happen:**

the items should be interactive and when they are clicked you can collect them and the hostile mobs in the vicinity should attack

**Comment by NightwindOI** [comment]
Server gonna be Instant 100 so we focus on the Legion part for now, but thx for the report!

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
