### ISSUE TITLE
[Tyce] - Mobs wont reset after Mind Control

### ISSUE THREAD

**Issue by leojoipas** [GuabinaCore/WoWKoi#1956]
**Links:**
https://www.wowhead.com/spell=605/mind-control
from WoWHead or our Armory

**What is happening:**
Some mobs bug after you mind control them, some stand in the same place and wont even react to attacks or skills

**What should happen:**
after the Mind Control fades they should be get aggroed by the caster or reset to the original location

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_122520_233948](https://user-images.githubusercontent.com/73371905/103145072-9467ae80-470a-11eb-8ebd-36c657254b9c.jpg)
![WoWScrnShot_122520_233958](https://user-images.githubusercontent.com/73371905/103145073-992c6280-470a-11eb-9b3b-3f3b3be3ec97.jpg)

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_122520_234122](https://user-images.githubusercontent.com/73371905/103145088-b8c38b00-470a-11eb-8850-b3c809bf7d70.jpg)

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_122520_234215](https://user-images.githubusercontent.com/73371905/103145093-d5f85980-470a-11eb-93aa-695bad75a003.jpg)
