### ISSUE TITLE
Crossroads Caravan Delivery

### ISSUE THREAD

**Issue by nalberthdionisio** [GuabinaCore/WoWKoi#1957]
**Links:**

https://pt.wowhead.com/quest=13975/entrega-da-caravana-da-encruzilhada

from WoWHead or our Armory

**What is happening:**

when you take the quest, no speech bubble appears to summon the caravan

**What should happen:**

when you take the quest a speech bubble should appear in the NPC causing it to disappear and you would use the weapon he gave to kill the mob that will appear

**Comment by NightwindOI** [comment]
Duplicate
