### ISSUE TITLE
Flying infernals on The Barrens

### ISSUE THREAD

**Issue by leojoipas** [GuabinaCore/WoWKoi#1958]
**Links:**
https://www.wowhead.com/npc=6073/searing-infernal
https://www.wowhead.com/npc=34640/barrens-vulture
from WoWHead or our Armory

**What is happening:**
Some Flying infernals are around the Cross roads and all along The Barrens
seems like a npc without a texture or model missing probably a bird

**What should happen:**
They shouldn't be there or needs to be replaced with this model on the second link

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_122520_233723](https://user-images.githubusercontent.com/73371905/103145056-29b67300-470a-11eb-939c-e9f3ee185039.jpg)


**For Reference**

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_122520_232257](https://user-images.githubusercontent.com/73371905/103145065-5a96a800-470a-11eb-8407-e4c97aa6bae5.jpg)

**Comment by NightwindOI** [comment]
Its for Legion Invasion, the flag must be changed.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
