### ISSUE TITLE
Quest Righteous Fury bugged

### ISSUE THREAD

**Issue by leojoipas** [GuabinaCore/WoWKoi#1959]
**Links:**
https://www.wowhead.com/quest=47589/righteous-fury
from WoWHead or our Armory

**What is happening:**
When you activate one Devastator Anchor(Crystals around  the Devastator) he triggers the vindicar bean at the Devastator and doesn't count as complete

**What should happen:**
Clicking at the 3 Devastator Anchors and then vindicar bean hits the Devastator

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
