### ISSUE TITLE
The Third Trial of Ursol

### ISSUE THREAD

**Issue by nalberthdionisio** [GuabinaCore/WoWKoi#1960]
**Links:**

https://www.wowhead.com/quest=41792/the-third-trial-of-ursol

from WoWHead or our Armory

**What is happening:**

the quest doesn’t complete when we kill all the mobs that summon ursol

**What should happen:**

when we finished killing all the mobs, the quest should complete in order to proceed with the other artifact quests

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.

**Comment by nalberthdionisio** [comment]
ok i'm replying, and sorry for my english, i'm using translator to send
this message

Em seg, 4 de jan de 2021 14:59, Sefrenia <notifications@github.com>
escreveu:
