### ISSUE TITLE
Quest: A Second Legend

### ISSUE THREAD

**Issue by leojoipas** [GuabinaCore/WoWKoi#1961]
**Links:**
https://www.wowhead.com/quest=43935/a-second-legend

from WoWHead or our Armory

**What is happening:**
![bug1](https://user-images.githubusercontent.com/67007231/103153200-a62e6d80-476d-11eb-91e7-c94bcdfb2809.png)

After you  take the quest a chat on the npc shows up "I would like to review  weapons we might pursue" but nothing happens if you click on it

**What should happen:**
When you click on the "I would like to review  weapons we might pursue" option he should be showing up the artifacts you can obtain

**Comment by Cefiro-Caecias** [comment]
Fixed. Available now.
