### ISSUE TITLE
Quest: The Best and Brightest

### ISSUE THREAD

**Issue by leojoipas** [GuabinaCore/WoWKoi#1962]
**Links:**
https://www.wowhead.com/quest=43373/the-best-and-brightest
https://www.youtube.com/watch?v=pzzp0D22hXI  (quest video)

from WoWHead or our Armory

**What is happening:**
 Zabra Hexx is not petrified and nothing happens when you interact with him

![bug2](https://user-images.githubusercontent.com/67007231/103157805-bbb78d80-4795-11eb-84df-6638b66e1a4c.png)

**What should happen:**
he should be petrified like this:
![bug3](https://user-images.githubusercontent.com/67007231/103157842-02a58300-4796-11eb-8aa5-9994487f884c.png)
and should be reacting to player when you interact with him

**Comment by Cefiro-Caecias** [comment]
Fixed. Available now.
