### ISSUE TITLE
Quest: Becoming the Ascendant

### ISSUE THREAD

**Issue by luxarana** [GuabinaCore/WoWKoi#1963]
![WoWScrnShot_122620_184702](https://user-images.githubusercontent.com/76631772/103159745-c2e99600-47ab-11eb-8145-aac45d5a600f.jpg)

I click on the button to communicat with the statue, but nothing happens.

I shoul talk with the statue and it shuld complet the quest.

**Comment by NightwindOI** [comment]
https://www.wowhead.com/quest=39092/becoming-the-ascendant

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
