### ISSUE TITLE
[Tyce] - Summoned creatures do not attack

### ISSUE THREAD

**Issue by astearon** [GuabinaCore/WoWKoi#1964]
**Links:**

from WoWHead or our Armory

**What is happening:**

Tested on class Mage, summoned Water Elemental will not attack when prompted with either Assist or Defensive
Their magical abilities also do not work when triggered.

**What should happen:**

Creatures should attack when the proper setting or command is given.

**Comment by Howizter** [comment]
Same with with Warlock Doomguard

**Comment by ShikoSCS** [comment]
Improved the pet control system. In the case of the Water Elemental, the Waterbolt spell must be autocast for it to attack.
