### ISSUE TITLE
Monk Campaign - Stolen Knowledge

### ISSUE THREAD

**Issue by gankyplanky** [GuabinaCore/WoWKoi#1965]
**Links:**

https://www.wowhead.com/quest=41039/stolen-knowledge

**What is happening:**

"-Stormforged Grapple Hook obtained" objective in this quest does not complete regardless of me having the hook 

**What should happen:**

This objective should be completed imidietly if the hook is in players inventory, the hook itself is obtained from quest "No wings Required"(ID:38613) or it can be picked up at Lornas post(Coordinates : 37 63)-Alliance or Cullens Post(Coordinates: 44 58)-Horde if the hook is removed from inventory afterwards

Quest ID: 41039

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
