### ISSUE TITLE
Maw of Souls: A Hope in Helheim Quests - Professions - Alchemy

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1966]
**Links:**
https://www.wowhead.com/quest=39350/maw-of-souls-a-hope-in-helheim
https://www.wowhead.com/item=136819/dragur-dust
from WoWHead or our Armory

**What is happening:**

1) Sometimes Dragur Dust dont even drop.
2) The times Dragur Dust do drop and when you try to turn in the quest it says that you dont have the req item.

**What should happen:**

You should be able to loot Dragur Dust all the time. and once you fulfill the req. you should be able to turn in the quest like normal

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_122720_101326](https://user-images.githubusercontent.com/73371905/103174360-d4787f80-4837-11eb-9f7d-d342a236a445.jpg)

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_122420_233601 -10](https://user-images.githubusercontent.com/73371905/103174405-376a1680-4838-11eb-9dca-a8e465a71253.jpg)
![WoWScrnShot_122420_233608](https://user-images.githubusercontent.com/73371905/103174407-3a650700-4838-11eb-8924-2ed3aed76370.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
