### ISSUE TITLE
Quest: Becoming the Ascendant

### ISSUE THREAD

**Issue by luxarana** [GuabinaCore/WoWKoi#1967]
**Links:**
![WoWScrnShot_122620_184702](https://user-images.githubusercontent.com/76631772/103254187-2c5fd500-4963-11eb-89c4-a8fe34619093.jpg)

from WoWHead or our Armory

**What is happening:**
i cant communicat with the statue

**What should happen:**
i shoud can communicat with the statue and it will get me to the temple

**Comment by NightwindOI** [comment]
https://github.com/GuabinaCore/WoWKoi/issues/1963
