### ISSUE TITLE
[Mob] Burning Blade Attackers/Acolytes not scaling up with player level

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#197]
**Links:**
https://classic.wowhead.com/npc=3380/burning-blade-acolyte
https://www.wowhead.com/npc=52338/burning-blade-attacker
**What is happening:**
Burning Blade Attackers and Acolytes aren't scaling up with player level.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
