### ISSUE TITLE
Warlock quest New Blood

### ISSUE THREAD

**Issue by Howizter** [GuabinaCore/WoWKoi#1970]
**Links:**
https://www.wowhead.com/quest=40729/the-new-blood

**What is happening:**

After summoning deamon you got teleported into Dreadscar Rift cage you nearby deamon is not enslaveable ergo you got perma stuck inside a cage. There is no conversation with RItssyn

**What should happen:**

After summoning deamon you got teleported into Dreadscar Rift cage you should enslave nearby deamon to free yourself from it after short talk with Ritssyn

https://www.youtube.com/watch?v=ixhKSduj8u8

**Comment by Cefiro-Caecias** [comment]
Applied autocomplete temporary fix; it will be repaired full blizzlike later. Available in the next update.
