### ISSUE TITLE
the fix that coused problem 

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#1971]
in last few changelog the quest of ( fangs of ahamane) fixed 
i did the quest before that therefore i have the weapon now it shows on the map and i have to complete it in order to progress in my class hall and when i do because i have the weapon at the end i cant pick it up so the quest wont complete ... and im stuck

**Comment by NightwindOI** [comment]
Its personal issue since i add u the weapon before that.
