### ISSUE TITLE
Shal'aran Quest

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1972]
**Links:**
https://www.wowhead.com/quest=42229/shalaran
from WoWHead or our Armory

**What is happening:**
After taking quest, nothing happend

**What should happen:**
You should explore Shal'aran with Thalyssra

**Comment by Cefiro-Caecias** [comment]
Applied autocomplete temporary fix; it will be repaired full blizzlike later. Available in the next update.
