### ISSUE TITLE
Not A Toothless Dragon - Mage campaign

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1973]
**Links:**
https://www.wowhead.com/quest=42508/not-a-toothless-dragon
from WoWHead or our Armory

**What is happening:**

Ride is instant- teleport
After "ride", quest is not completed.

**What should happen:**
Kalecgos should fly with you.
Quest should be competed after landing

**Comment by Cefiro-Caecias** [comment]
Applied autocomplete temporary fix; it will be repaired full blizzlike later. Available in the next update.
