### ISSUE TITLE
The Enemy of My Enemy...

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1974]
**Links:**
https://www.wowhead.com/quest=42521/the-enemy-of-my-enemy#comments
from WoWHead or our Armory

**What is happening:**

I dont get credit for finding Milhouse, only for saving him- cant complete quest

**What should happen:**
-Find Milhouse-> Save Milhouse -> progress

**Comment by Cefiro-Caecias** [comment]
Applied autocomplete temporary fix; it will be repaired full blizzlike later. Available in the next update.
