### ISSUE TITLE
[Tyce] - Priest Class Hall - Scouting Map bugged

### ISSUE THREAD

**Issue by Dragonsworn** [GuabinaCore/WoWKoi#1975]
**Links:**

from WoWHead or our Armory

**What is happening:**
![WoWScrnShot_010121_204859](https://user-images.githubusercontent.com/76816833/103446090-8d452100-4c73-11eb-9e48-65157c89b5b7.jpg)
![WoWScrnShot_010121_204908](https://user-images.githubusercontent.com/76816833/103446092-8e764e00-4c73-11eb-9b0f-aa69c5f032cb.jpg)

Scouting map not working as intended. Quest not being added to quest log. 

**What should happen:**
Quest should be added to quest log in order to begin new zone.

**Comment by Cefiro-Caecias** [comment]
Fixed.
