### ISSUE TITLE
Quest The death of the eldest

### ISSUE THREAD

**Issue by Howizter** [GuabinaCore/WoWKoi#1978]
**Links:**

from WoWHead or our Armory

https://www.wowhead.com/quest=37853/the-death-of-the-eldest

**What is happening:**

https://www.wowhead.com/npc=109326/leystone-spiderling#comments hits too hard....40k to my 100 lvl cloth user

**What should happen:**

They shouldnt hit that hard

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
