### ISSUE TITLE
The head of the snake Quest

### ISSUE THREAD

**Issue by Howizter** [GuabinaCore/WoWKoi#1979]
**Links:**

https://www.wowhead.com/quest=37470/the-head-of-the-snake

**What is happening:**

Parjesh is missing

**What should happen:**

Parjesh should assist  Athissa in fight

https://www.youtube.com/watch?v=6JsW7pdm84c

**Comment by Cefiro-Caecias** [comment]
Later this quest will be rebuilt blizzlike. At the moment, it can be completed without problems.
