### ISSUE TITLE
Warlock quest Ritual Ruination

### ISSUE THREAD

**Issue by GraF0X** [GuabinaCore/WoWKoi#1981]
**Links:**

https://www.wowhead.com/quest=43254/ritual-ruination

**What is happening:**

When you click on Fell Bat teleports you to the island, you need to click on Gulldan in order for him to speak. After that, there is the "Slay Allaris Nassarin" stage and nothing happens, when the questlog is opened, all goals are completed except for "Slay Allaris Nassarin"
Allaris is not near the player

**What should happen:**

https://www.youtube.com/watch?v=izHfTLwUI1M

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update,
