### ISSUE TITLE
Mountainstrider Round-Up

### ISSUE THREAD

**Issue by Dragonsworn** [GuabinaCore/WoWKoi#1982]
**Links:**
https://www.wowhead.com/quest=42596/mountainstrider-round-up
from WoWHead or our Armory

**What is happening:**
Unable to mount Mountainstrider to ride back to quest destination. Mountainstrider Disappears once mounted. 

**What should happen:**
Player should be able to mount the Mountainstrider and ride back to quest destination multiple times to complete quest.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
