### ISSUE TITLE
The Underking Comes

### ISSUE THREAD

**Issue by Dragonsworn** [GuabinaCore/WoWKoi#1983]
**Links:**
https://www.wowhead.com/quest=42104/the-underking-comes

from WoWHead or our Armory

**What is happening:**
Unable to interact with Tauren to progress in quest.

**What should happen:**
Player should be able to talk to Rivermane Tauren in order to evacuate them and complete quest.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. Don't forget to use the "Horn of Jale" spell they provide for the quest.
