### ISSUE TITLE
Quest you scratch my back

### ISSUE THREAD

**Issue by Howizter** [GuabinaCore/WoWKoi#1984]
**Links:**

https://www.wowhead.com/quest=37860/you-scratch-my-back

**What is happening:**

No animation for whelps to attack pillars, also hit box of pillars is way off. Plus there is no UI to click complete quest.

**What should happen:**

Whelps should attack pillars, also there should be UI to finish quest.   "

https://www.youtube.com/watch?v=04LAobMmQg8

**Comment by Cefiro-Caecias** [comment]
In the future we will see to rebuild it blizzlike; until then patience. Regarding the UI to end the quest, there is a system problem with this function, which causes the quest to close automatically when completed, without the player's intervention. Now I will report the bug ;)

**Comment by Howizter** [comment]
Quest isnt closed automatically when complete. In fact I can drop it and redoit but still it stays in questlog

**Comment by NightwindOI** [comment]
https://i.imgur.com/dZ2FHl4.png there is no Complete Option as ppl say 
https://i.imgur.com/dZ2FHl4.png

**Comment by Cefiro-Caecias** [comment]
Fix. I hate you. Available in the next update :P

**Comment by syphex97** [comment]
Certain aspects of the closed issue still presists.

https://www.youtube.com/watch?v=00juTKcjepE
https://www.wowhead.com/quest=37860/you-scratch-my-back


**What is happening:**
I get Quest credit before the whelplings do the animation on the mana pylons.
The pylons does not put a Leyline on you when you move nearby the pylons.
The Whelplings can enage in combat and can be attacked randomly

**What should happen:**
The pylons should be putting a Leyline debuff when you move nearby the pylons.
The whelpings move to the leyline and starts casting their effect to disable them.
The Whelplings should not be attackable or help attacking.
