### ISSUE TITLE
Priest - Second and Third Artifact Quests

### ISSUE THREAD

**Issue by Dragonsworn** [GuabinaCore/WoWKoi#1985]
**Links:**
https://www.wowhead.com/quest=43935/a-second-legend

https://www.wowhead.com/quest=44407/the-third-legend

from WoWHead or our Armory

**What is happening:**
Quests can be picked up from Npc in class order hall but cannot progress as there is no option to choose an artifact. 

**What should happen:**
Player should be able to talk to Npc, begin quest for second or third artifact, UI should bring up a choice bewteen two and player should be able to click which artifact they would like to pursue next.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
