### ISSUE TITLE
DeathKnights Artifacts Quest.

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1986]
**Links:**
https://www.wowhead.com/npc=94164/the-lich-king
https://www.wowhead.com/npc=93963/echo-of-arthas-menethil
https://www.wowhead.com/npc=94982/echo-of-nerzhul
from WoWHead or our Armory

**What is happening:**

> Frost ( The only way i was able to fully do it without wipe was after getting blood artifact)

1)Some Npc are just standing on the air.

![WoWScrnShot_010321_155534](https://user-images.githubusercontent.com/73371905/103540809-b383e000-4e70-11eb-8115-014360d14bd5.jpg)

1.1) **Forgot to take SS** but the plate that the begining of the quest that you should stand on. shouldnt have any option and is lacking an indicator arrow

2) The lich king model isnt the right one and in fact shouldnt be there
https://www.wowhead.com/npc=94164/the-lich-king

![WoWScrnShot_010321_155619](https://user-images.githubusercontent.com/73371905/103541074-30af5500-4e71-11eb-8931-9d1a86251b82.jpg)

3)The frost dispensers.. dont do anything. you can stand on them. they should freeze you.

![WoWScrnShot_010321_160505](https://user-images.githubusercontent.com/73371905/103541116-458be880-4e71-11eb-8bb2-f17160bc1171.jpg)

3.1) on the sides after you kill the 2th group of mobs. the next group should be casting an spell that doesnt allow you to get close and therefore you have to use the grips to pull him to you.

4) The gargolyes after you kill them instantly turn into stone and set on the right position on the pressure plate. they should make into stone in the place you kill them. and use deathgrip to set them in each pressure plate.

5) Each fight must be nerfted so far its almost imposible to do.

![WoWScrnShot_010321_160443](https://user-images.githubusercontent.com/73371905/103543578-27c08280-4e75-11eb-8b7b-11fe3caeac5f.jpg)

6) Fragments of  the Frostmourne arent using the right model...

![WoWScrnShot_010321_163809](https://user-images.githubusercontent.com/73371905/103543673-4de62280-4e75-11eb-8e96-eb59f6ecc526.jpg)

![WoWScrnShot_010321_164651](https://user-images.githubusercontent.com/73371905/103543761-68b89700-4e75-11eb-84b2-65c7fa5ee0a0.jpg)

7. With the horsed mobs. you can skip them as they dont move at all.

![WoWScrnShot_010321_163511](https://user-images.githubusercontent.com/73371905/103543859-96054500-4e75-11eb-8f52-6bba3008efed.jpg)
![WoWScrnShot_010321_170644](https://user-images.githubusercontent.com/73371905/103543898-a3223400-4e75-11eb-9bf7-3ce1a6f84819.jpg)

8. Magroth the defender has a huge consacration aura.

![WoWScrnShot_010321_171643](https://user-images.githubusercontent.com/73371905/103543973-be8d3f00-4e75-11eb-9a5a-7fd5297c6382.jpg)

9. Almost all the fights to this point should be nerfted.

10. the frostmourne hilt shouldnt be like that but standing. (tho it works fine like that)

![WoWScrnShot_010321_160925](https://user-images.githubusercontent.com/73371905/103544763-f8ab1080-4e76-11eb-9af5-2c6aad126052.jpg)

11. def should be nerfted.
11.1 Arthas isnt summoning Razor Ice spikes from the ground.
11.2 Arthas isnt using divine shield
11.3 Artas shadown pact doesnt do anything. he isnt summoning undeaths to heal him and he is following you when in fact he should next to nerzhul
11,4 nerzhul isnt using his one skill the void barrage.

![WoWScrnShot_010321_172429](https://user-images.githubusercontent.com/73371905/103545279-b7ffc700-4e77-11eb-8bde-0044aa9dc526.jpg)

12. After you kill arthas the fight should end... but right now you end up fighting nerzhul

**What should happen:**

https://warcraft.blizzplanet.com/blog/comments/the-call-of-icecrown-frost-death-knight-in-legion
https://www.youtube.com/watch?v=EnPn89NFPHU&feature=youtu.be

**Comment by Nephilimkoi** [comment]
> Unholy

1) when i first tried to do it i got stuck in a part in which you have to kill 
https://www.wowhead.com/npc=101257/the-conservator (which should be summoned. not naturally spawn)
but after 3 tries i called it a day and decided not to try anymore but the next morning when i decided to give it another go. when i restarted the escenario. i found myself unable to get past the getes. it simply doesnt open. tried it over 5 times. deleted cache. and so on. but no matter what it simply didnt wanted to open up


![WoWScrnShot_010421_092648](https://user-images.githubusercontent.com/73371905/103552133-cf43b200-4e81-11eb-96ea-1382613ee57b.jpg)






https://www.youtube.com/watch?v=CwKwJ01dHX8

**Comment by Nephilimkoi** [comment]
> Blood


1) you need to kill the mobs before the blockage in certain order if not. the gate wont open.
1.1) When baron Sliver is working on the gate. no new demons Spawn (which should)
1.2) All of the mobs need to be nerfted.
1.3) None of the allied NPC help you with the fights at any moment.

![WoWScrnShot_010321_173547](https://user-images.githubusercontent.com/73371905/103554621-91e12380-4e85-11eb-902b-2aec96fd2695.jpg)
![WoWScrnShot_010321_173710](https://user-images.githubusercontent.com/73371905/103554628-9574aa80-4e85-11eb-91a9-77812fae5c9b.jpg)
![WoWScrnShot_010321_174144](https://user-images.githubusercontent.com/73371905/103554648-9dcce580-4e85-11eb-8222-074d4a260e7b.jpg)

You currently need to deal with only 2 out of 3 mobs by the gate. 

![WoWScrnShot_010321_214308](https://user-images.githubusercontent.com/73371905/103554876-f9976e80-4e85-11eb-9753-cdc292e53044.jpg)

2) Mobs arent patroling. just staying still.

3) NPC lacks some green chains around it that are supposed to be holding it.

![WoWScrnShot_010321_214915](https://user-images.githubusercontent.com/73371905/103555471-b984bb80-4e86-11eb-86e7-d5a38b0c2182.jpg)


4) You can skip all the mobs to the final miniboss 
4.1) the fight with https://www.wowhead.com/npc=101778/gorelix-the-fleshripper should be nerfted.
4.2) You can put the miniboss to the spot on the pic. and simply avoid fighting the adds that spawns. 

![WoWScrnShot_010321_215319](https://user-images.githubusercontent.com/73371905/103556107-a8887a00-4e87-11eb-86f0-97b1dea4adf9.jpg)


https://www.youtube.com/watch?v=x9GL_P9lQ7g

**Comment by Cefiro-Caecias** [comment]
I just need to know the quests that cannot be completed. or if you somehow get stuck without being able to graduate. Later they will become full blizzlike.
