### ISSUE TITLE
The Third Trial of Ursol - Guardian Artifact Quest.

### ISSUE THREAD

**Issue by Dragonsworn** [GuabinaCore/WoWKoi#1987]
**Links:**
https://www.wowhead.com/quest=41792/the-third-trial-of-ursol
from WoWHead or our Armory

**What is happening:**
When interacting with Ursol He says "The final trial will not be easy, speak with me when you are ready". Quest is not progessing to next stage where he asks you to guard Lea Stonepaw.

**What should happen:**
Player should interact with Ursol in order to progress to next stage of quest which is to protect Lea Stonepaw, and Begin Ursol's Dialogue. Player Should be able to complete this stage and finish the quest.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
