### ISSUE TITLE
DemonHunters Artifacts Quest

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1988]
**Links:**
https://www.wowhead.com/quest=41804/ask-and-you-shall-receive
https://www.youtube.com/watch?v=gokwbBFJiU8
from WoWHead or our Armory

> Havoc
Found no major problem that stop you or that requires nerfing with the Havoc artifact quest.
probably some tweks here and there. but req indeep detailing.

> Vengance

**What is happening:**

Currently. when you do the quest Ask and you shall receive. in the part that you pick up the cristalized soul. after you do.  Kadghar phases away. rather than manually going downstair. meaning that you cannot follow him.. making you unable to complete the 2th objetive of the quest. and therefore even if you have the cristalized soul.. you cannot complete the quest.

![Uploading WoWScrnShot_010421_170650.jpg…]()
![WoWScrnShot_010421_170647](https://user-images.githubusercontent.com/73371905/103581639-cb7c5380-4eb2-11eb-94a2-0c7d5f1933d4.jpg)

**What should happen:**
https://www.youtube.com/watch?v=gokwbBFJiU8

**Comment by Nephilimkoi** [comment]
![WoWScrnShot_010421_170650](https://user-images.githubusercontent.com/73371905/103581953-51989a00-4eb3-11eb-9653-09c766cb9a1a.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. Don't forget to clear Cache, abandon the quest, and take it again.
