### ISSUE TITLE
Warrior Artifacts Quest

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1989]
**Links:**
https://www.wowhead.com/quest=42814/an-important-mission
https://www.wowhead.com/npc=96183/danath-trollbane

from WoWHead or our Armory

**What is happening:**
Danath Trollbane simply isnt there making it imposible to get any of the artifact quest. 

![WoWScrnShot_010421_184248](https://user-images.githubusercontent.com/73371905/103587154-ff5c7680-4ebc-11eb-90b5-41dd35eafe18.jpg)

**What should happen:**

![](https://wow.zamimg.com/uploads/screenshots/normal/613115-an-important-mission.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
