### ISSUE TITLE
[Mob] Venture Co. Overseer and Venture Co. Enforcer not scaled up to player level

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#199]
**Links:**
https://classic.wowhead.com/npc=3286/venture-co-overseer
https://classic.wowhead.com/npc=3283/venture-co-enforcer
**What is happening:**
These mobs are not scaling up with player level.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
