### ISSUE TITLE
Rogue Artifact Quest

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1990]
**Links:**
https://www.wowhead.com/npc=102120/fleet-admiral-tethys
https://www.wowhead.com/quest=40849/the-dreadblades
https://www.wowhead.com/npc=102293/dread-admiral-eliza
https://www.wowhead.com/spell=208226/musket-barrage
https://www.wowhead.com/npc=105536/akaari-shadowgore
https://www.wowhead.com/quest=40995/injection-of-power
https://www.wowhead.com/npc=102594/marin-noggenfogger
from WoWHead or our Armory

**What is happening:**

> Outlaw
1) sometimes when you load the area of booty bay where you take the quest from Fleet Admiral Tethys he falls off the boat. and simply doesnt react and give the quest.

![WoWScrnShot_010521_111115](https://user-images.githubusercontent.com/73371905/103667185-fff01e00-4f4b-11eb-9912-742e501fd848.jpg)

2) The skill of Dread Admiral Eliza Musket Barrage triggers way too fast and doesnt give any time at all to hide behind a pilar to avoid the skill.

3) The Glyph gets stuck in midflight and doesnt do anything at all after that. the only way out is to relog or use Hearthstone

![WoWScrnShot_010521_113154](https://user-images.githubusercontent.com/73371905/103667368-375eca80-4f4c-11eb-977c-6f16aee3a154.jpg)
![WoWScrnShot_010521_113211](https://user-images.githubusercontent.com/73371905/103667477-5f4e2e00-4f4c-11eb-8085-c06b92e3f6db.jpg)

> Subtetly

Sometimes in your first encounter with  Akaari Shadowgore if you attack too fast or do too much damange too quicky the encounter bugs out and doesnt proceed to the next part.

Apart from that. the rest behave normal.

>Assassination

Somehow you get the item before looting it. but you are still able to complete the quest after a few seconds. 

![WoWScrnShot_010521_000659](https://user-images.githubusercontent.com/73371905/103668408-6fb2d880-4f4d-11eb-9702-4dde47c28ac2.jpg)

During the quest Injection of Power you are unable to convince Marin Noggenfogger not matter what you do.

![WoWScrnShot_010521_113706](https://user-images.githubusercontent.com/73371905/103668141-2ebac400-4f4d-11eb-8922-363faa3b9568.jpg)

**Comment by Cefiro-Caecias** [comment]
I just need to know the quests that cannot be completed. or if you somehow get stuck without being able to graduate. Later they will become full blizzlike.

**Comment by Nephilimkoi** [comment]
you are unable to progress and fully unlock the rogue artifacts since you cant finish the quest injection of power
(the one at the end)

**Comment by Cefiro-Caecias** [comment]
Quest "Injection of Power", fixed. Available in the next update.
