### ISSUE TITLE
Paladin Artifact Quest

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1991]
**Links:**
https://www.wowhead.com/quest=42005/the-end-of-the-saga
https://www.wowhead.com/npc=105736/unquiet-dead
https://www.wowhead.com/quest=42017/shrine-of-the-truthguard
https://www.wowhead.com/npc=106245/inna-the-cryptstalker#abilities
https://www.wowhead.com/spell=210661/shoot
https://www.wowhead.com/spell=210395/pin-down

from WoWHead or our Armory

**What is happening:**

> Protection

1) When doing the [quest](https://www.wowhead.com/quest=42005/the-end-of-the-saga)  the mobs that spawn when you click the [wrong grave are already lvl 110](https://www.wowhead.com/npc=105736/unquiet-dead) when they shouldnt be. they should be around lvl 99 

![WoWScrnShot_010521_141731](https://user-images.githubusercontent.com/73371905/103685275-56b52200-4f63-11eb-86fd-f3c55b661fb0.jpg)

1.1) [When you click the right grave.](https://www.wowhead.com/quest=42005/the-end-of-the-saga#screenshots:id=659786) there is no lore or event. it simply autocomplete.

**the pic is how it should be**
![](https://wow.zamimg.com/uploads/screenshots/normal/659786-the-end-of-the-saga.jpg)

2) During the part of the escenario  to get the [truthguard](https://www.wowhead.com/quest=42017/shrine-of-the-truthguard) 
When you have to face the [first mob](https://www.wowhead.com/npc=106245/inna-the-cryptstalker#abilities). she can instantly kill you with the skill [Shoot ](https://www.wowhead.com/spell=210661/shoot) and even if you manage to overcome that by using divine shield. the rest of her skills dont trigger.

![WoWScrnShot_010521_142153](https://user-images.githubusercontent.com/73371905/103685806-33d73d80-4f64-11eb-8fc2-1e2985a2a442.jpg)
![WoWScrnShot_010521_142032](https://user-images.githubusercontent.com/73371905/103685790-2d48c600-4f64-11eb-85d1-6e788b875507.jpg)
![WoWScrnShot_010521_142121](https://user-images.githubusercontent.com/73371905/103685891-5701ed00-4f64-11eb-9086-564973d218e1.jpg)

 **Travel northwest to 84.5, 9.8 and battle Inna the Cryptstalker, and her drake, Shae.
- - When Inna the Cryptstalker casts  Pin Down, pick up the Quicksteel Arrow to break yourself or your companions free, and then use the extra action ability,  Pin Down to fire the arrow at either Inna the Cryptstalker or Shae.**

https://www.youtube.com/watch?v=uxuX1VNonRY

**Comment by Nephilimkoi** [comment]
> Retribution

https://www.wowhead.com/npc=90981/balnazzar

Found nothing major. Only lack of quotes. but the whole thing work good.

**Comment by Nephilimkoi** [comment]
> Holy

https://www.wowhead.com/quest=42377/the-brothers-trail
https://www.wowhead.com/object=250295/old-campfire
https://www.wowhead.com/object=250364/broken-sword
https://www.wowhead.com/npc=107329/lurking-void-wraith
https://www.wowhead.com/npc=107361/jotun
https://www.wowhead.com/npc=107359/lanigosa


1) The part of the quest where you look for the old campfire is completely skiped.
1.1) when you click the broken sword you summon some void wraiths... but one of those wraiths is lvl 110 killing you almost instantly. he should be like the others. lvl 99


![WoWScrnShot_010521_145311](https://user-images.githubusercontent.com/73371905/103687071-12775100-4f66-11eb-8ea0-b1921a651ea4.jpg)


![WoWScrnShot_010521_130700](https://user-images.githubusercontent.com/73371905/103686706-9ed54400-4f65-11eb-88bf-61f3ac890201.jpg)

![WoWScrnShot_010521_130842](https://user-images.githubusercontent.com/73371905/103686711-a09f0780-4f65-11eb-8a62-7d9ac3a509e1.jpg)


2) on the part you have to fight Joton first he is by default lvl 110 with 14M hp making him imposible to kill. and when you ask Lanigosa to buff you. he spawm again... making it so that every time you ask for a buff.. he also spawm. stacking tens of them.


![WoWScrnShot_010521_131439](https://user-images.githubusercontent.com/73371905/103687493-bc56dd80-4f66-11eb-88ae-e6d783dd8090.jpg)

**Comment by Cefiro-Caecias** [comment]
I just need to know the quests that cannot be completed. or if you somehow get stuck without being able to graduate. Later they will become full blizzlike.

**Comment by Nephilimkoi** [comment]
The only one that you are able to fully complete is retribution. the rest require to be nerfted as the mobs either insta 1shot you or simply are lvl 110 and you cannot kill them while being lvl 100

**Comment by Cefiro-Caecias** [comment]
Fixed NPCs:

* Unquiet Dead (105736)
* Inna the Cryptstalker (106245): is controlled by a Core script; I made some adjustments, but if it continues to bother me, let me know to refer its repair to a Core Dev.
* Balnazzar (90981)
* Lurking Void Wraith (107329)
* Jotun (107361)
* Lanigosa (107359)

Available in the next update.
