### ISSUE TITLE
The Nightborne Prince Quest

### ISSUE THREAD

**Issue by Howizter** [GuabinaCore/WoWKoi#1992]
**Links:**

https://www.wowhead.com/quest=37861/the-nightborne-prince

**What is happening:**

After completing https://www.wowhead.com/quest=37960/leyline-abuse NPC does nothing

**What should happen:**

After completing https://www.wowhead.com/quest=37960/leyline-abuse Projection of Senegos should grant THe NIghtborne Prince quest

**Comment by Cefiro-Caecias** [comment]
Fixed. Available today, after the morning update.
