### ISSUE TITLE
Hunter Artifacts Quest

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#1993]
**Links:**
https://www.wowhead.com/quest=40419/rescue-mission
https://www.wowhead.com/npc=100398/ranger-orestes
https://www.wowhead.com/quest=42185/never-hunt-alone
https://www.wowhead.com/quest=40385/the-spear-in-the-shadow

from WoWHead or our Armory

**What is happening:**

> Marksmanship

1) Lets start by saying that the portal should have some event happening. but currently just instantly appear once you take the quest 

![WoWScrnShot_010521_160709](https://user-images.githubusercontent.com/73371905/103718771-f394b100-4f9d-11eb-80fc-7c37115adb20.jpg)

2)the quest [Rescue Mission](https://www.wowhead.com/quest=40419/rescue-mission) autocompletes the moment you go throught the portal

![WoWScrnShot_010521_160740](https://user-images.githubusercontent.com/73371905/103718778-f7283800-4f9d-11eb-9fbc-c86dd20970e3.jpg)

3) after you find the ranger Orestes the escenario objetive doesnt progress at all. but you can still somehow keep moving forward.

![WoWScrnShot_010521_201823](https://user-images.githubusercontent.com/73371905/103718805-00190980-4f9e-11eb-9219-a54f785f8fde.jpg)

![WoWScrnShot_010521_202118](https://user-images.githubusercontent.com/73371905/103718922-42424b00-4f9e-11eb-9fd0-9a3dbb9f70ab.jpg)

4)the weapon model to loot it isnt the right one

![WoWScrnShot_010521_203927](https://user-images.githubusercontent.com/73371905/103718957-58500b80-4f9e-11eb-859f-964d2a752e23.jpg)

![WoWScrnShot_010521_203932](https://user-images.githubusercontent.com/73371905/103719055-951c0280-4f9e-11eb-9dfa-ab7a105b36ff.jpg)

Somehow completable without major things (if you are reading a guide or seeing a vid. or know the way). still. both things are a major issue the fact that the quest autocompletes before doing anything and that the escenario objetives doesnt progress.

> Beast Mastery

i think that the only thing  that has a problem is the fact that the weapon to loot has a wrong model
the quest progressed as normal. no mobs need to be nerfted. and the escenario worked nice. maybe there are issues but nothing directly visual and needs to be more detailed.

![WoWScrnShot_010521_210632](https://user-images.githubusercontent.com/73371905/103719131-c09eed00-4f9e-11eb-9cda-9fc52bb65ccb.jpg)

> Survival

Now. with this one i did got stuck and cant get it at all.

1) the quest [The Spear in the Shadow](https://www.wowhead.com/quest=40385/the-spear-in-the-shadow) autocompletes the moment you get to the escenario.

2)The dialog need to be scripted better.

![WoWScrnShot_010521_210926](https://user-images.githubusercontent.com/73371905/103719348-33a86380-4f9f-11eb-9d99-188567d7fa54.jpg)

3)When you get to stage 6 of the escenario you are unable to progress as Apata cant be interacted with rendering you unable to tell her about the harpons to travel outside the mist and find the beast 

![WoWScrnShot_010521_212553](https://user-images.githubusercontent.com/73371905/103719835-4a02ef00-4fa0-11eb-925e-da8a34ad7f19.jpg)

![WoWScrnShot_010521_211504](https://user-images.githubusercontent.com/73371905/103719363-3a36db00-4f9f-11eb-8b4f-ed266b9be287.jpg)

![WoWScrnShot_010521_212729](https://user-images.githubusercontent.com/73371905/103719472-78cc9580-4f9f-11eb-8d82-28a96b631728.jpg)

![WoWScrnShot_010521_212855](https://user-images.githubusercontent.com/73371905/103719484-7cf8b300-4f9f-11eb-8e09-003eb6f14cfa.jpg)

**What should happen:**

Marksmanship
https://www.youtube.com/watch?v=MweA5mA40hY 

Survival
https://www.wowhead.com/quest=40385/the-spear-in-the-shadow#videos:id=100421

**Comment by Cefiro-Caecias** [comment]
I just need to know the quests that cannot be completed. or if you somehow get stuck without being able to graduate. Later they will become full blizzlike.

**Comment by Nephilimkoi** [comment]
The survival part is imposible to complete. as you are unable to progress in the escenario

**Comment by Cefiro-Caecias** [comment]
Quest "The Spear in the Shadow" put into temporary autocomplete mode; I'll rebuild it blizzlike later. Available in the next update.
