### ISSUE TITLE
The Prince is Going Down Quest

### ISSUE THREAD

**Issue by Howizter** [GuabinaCore/WoWKoi#1995]
**Links:**

https://www.wowhead.com/quest=37566/the-prince-is-going-down#

**What is happening:**

You fight prince alone.

**What should happen:**

Okuna Longtusk should assist you in fight.

https://www.youtube.com/watch?v=8lKtTGPqCVI&feature=emb_logo

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later.
