### ISSUE TITLE
The Scythe of Souls Quests - Legion - Azsuna

### ISSUE THREAD

**Issue by Deaalmgren** [GuabinaCore/WoWKoi#1996]
**Links:**

https://www.wowhead.com/quest=37660/the-scythe-of-souls

**What is happening:**

During "3rd" step of this quest - 0/1 Arev'naal compelled, the scaling is off. Both himself and his occulus take about 10% of my health per hit. 

**What should happen:**

He should be able to be soloable.
https://youtu.be/iVwO9G-_PBk?t=95 <- Point of reference to see how the damage should hit.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
