### ISSUE TITLE
Mountainstrider round up Quest

### ISSUE THREAD

**Issue by Howizter** [GuabinaCore/WoWKoi#1998]
**Links:**

https://www.wowhead.com/quest=42596/mountainstrider-round-up

**What is happening:**

When clicking on mountainstrider to mount up  they vanish

**What should happen:**

You should be able to mount up and raid back to base to return them

https://www.youtube.com/watch?v=NviBv-fHMK0

**Comment by Cefiro-Caecias** [comment]
This quest has already been fixed, but they have not applied the update yet. I already notify the person in charge of applying the updates.
