### ISSUE TITLE
Impending Dooooooom!

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#1999]
**Links:**
https://www.wowhead.com/quest=42493/impending-dooooooom
from WoWHead or our Armory

**What is happening:**

There is no magic barrier.

**What should happen:**
You should be able to cross magic barrier with Blink.

**Comment by NightwindOI** [comment]
You mean just the visual barrier or the trigger doesn't work?

**Comment by Floding69** [comment]
> You mean just the visual barrier or the trigger doesn't work?

Both

**Comment by Cefiro-Caecias** [comment]
Fixed. The magic bars I'll put in later, when I rebuild and refase the area. Available in the next update.
