### ISSUE TITLE
[Saitama] - Spell Aimed Shot/Auto Attacks

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#20]
Class: Hunter
Spec: Marksman
Spell: [Aimed Shot](https://classic.wowhead.com/spell=19434/aimed-shot)/[Auto Attack
](https://www.wowhead.com/spell=6603/auto-attack)
**What is happening:**
Sometimes, after casting [Aimed Shot](https://classic.wowhead.com/spell=19434/aimed-shot), [auto attacks](https://www.wowhead.com/spell=6603/auto-attack) randomly stop shooting.

**What should happen:**
Using [Aimed Shot](https://classic.wowhead.com/spell=19434/aimed-shot) should never make it so that hunters' [auto attacks](https://www.wowhead.com/spell=6603/auto-attack) stop shooting, as they should continue shooting after the cast time of [Aimed Shot](https://classic.wowhead.com/spell=19434/aimed-shot) finishes, and the ability activates.

**Comment by login6710** [comment]
Fixed
