### ISSUE TITLE
Wolf Pack Attack Quest

### ISSUE THREAD

**Issue by Howizter** [GuabinaCore/WoWKoi#2000]
**Links:**

https://www.wowhead.com/quest=39656/wolf-pack-attack

**What is happening:**

Gun doesnt scatter Icefang Howlers. You can still kill leader to get quest done, but adds hit for 75-120k dmg each

**What should happen:**

Gun should scare off Icefang Howlers so you can single out Pack Leaders

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
