### ISSUE TITLE
druid campaign 

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#2001]
**Links:**
https://www.wowhead.com/quest=42036/idol-of-the-wilds
from WoWHead or our Armory

**What is happening:**
after completing the quest the object should return to keeper remulus but when you get to class hall he doesnt let you interact with him 

**What should happen:**
returning point of the quest should be keeper remulus

**Comment by NightwindOI** [comment]
[Click ](https://cdn.discordapp.com/attachments/677992489973579887/797897396800716850/WoWScrnShot_011021_220742.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
