### ISSUE TITLE
Securing the Way

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#2002]
**Links:**
https://www.wowhead.com/quest=42872/securing-the-way
from WoWHead or our Armory

**What is happening:**

Can't interact with portal.

**What should happen:**
I hould be able to open portal and teleport to Class Hall

**Comment by NightwindOI** [comment]
We have a problem with the portals right now , so not sure if that's the issue or separate one.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
