### ISSUE TITLE
[Quest] [Stormheim] Clear the Deck

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2003]
**Links:**

https://www.wowhead.com/quest=38873/clear-the-deck

**What is happening:**

 Forsaken Catapult can be clicked on multiple times to gain quest credits.

**What should happen:**

One credit per catapult.

**Comment by Cefiro-Caecias** [comment]
Fixed. You can use the catapults 1 time every 30 seconds. Available in the next update.
