### ISSUE TITLE
[Quest] [Stormheim] A gift for Greymane

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2004]
**Links:**

https://www.wowhead.com/quest=39385/a-gift-for-greymane

**What is happening:**

"Plant explosives" can be clicked on multiple times to gain quest credits.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
I patched that quest yesterday, but they haven't applied my fixes yet. Patience ;)
