### ISSUE TITLE
[Quest] [Stormheim] Assault on Skold-Ashil

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2005]
**Links:**

https://www.wowhead.com/quest=39119/assault-on-skold-ashil
https://www.wowhead.com/npc=94466/shieldmaiden-armaments

**What is happening:**

Shieldmaiden Armaments dont grant credits towards bonus objectives.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
