### ISSUE TITLE
artifact weapon 

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#2007]
**Links:**
https://www.wowhead.com/quest=41631/the-nexus-vault
https://www.wowhead.com/quest=43338/the-codex-of-ra
**What is happening:**
after starting the scenario in dungeon the dragon that you should heal says ( invalid target)  {for disp priest}

when you go in the underground palace the is no mob to cleanse to get the edicts {for shaman}

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
1.- Fixed. Available in the next update.
2.- Leave the quest and take it again, so that Xuen will teleport you to the correct phase. Available now.
