### ISSUE TITLE
Demon Souls

### ISSUE THREAD

**Issue by Floding69** [GuabinaCore/WoWKoi#2009]
**Links:**
https://www.wowhead.com/quest=37653/demon-souls#comments
from WoWHead or our Armory

**What is happening:**

After completing "Down to Aszuna" quest at Khadgar,  I don't get this quest or any other.
Maybe because  I am playing DH, and its because of "Into the Fray" quest that is only for DH.

**What should happen:**
I should get next quests.

EDIT: I got quest after i deleted some weird version of  "[deprecated]Down to Aszuna", that appeared in quest log today.

**Comment by NightwindOI** [comment]
Hmm, that appear on a new character or an old one?

**Comment by Cefiro-Caecias** [comment]
With good reason, because I went to the NPC, and he gave me the quests without problem. I close Issue.
