### ISSUE TITLE
[Quest-Stormheim] - Stormheim's Salvation

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#2010]
https://www.wowhead.com/quest=40005/stormheims-salvation

**What is happening:**

the mob "god-king skovlad" stuns you permanently in a 30 sec cycle

**Comment by NightwindOI** [comment]
The spell is right, the problem is he suppose to cast it before he die...and run away.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
