### ISSUE TITLE
Gembroken imp NPC

### ISSUE THREAD

**Issue by Howizter** [GuabinaCore/WoWKoi#2011]
**Links:**

https://www.wowhead.com/npc=100025/gembroken-imp

**What is happening:**

They hit my cloth 104lvl user for 100k+ dmg.   https://i.imgur.com/t8rOr6j.jpg

**What should happen:**

THey shouldnt hit that hard

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
