### ISSUE TITLE
[Tyce] - Monk Artifact Weapon chain

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#2013]
**Links:**

So far, the quest chain is work just fine, but the mobs are overturned and hit like a truck.
Windwalker Artifact choice works too but have the same issue.

**What is happening:**
https://www.wowhead.com/quest=12103/before-the-storm - Everything hit as a truck.
https://www.wowhead.com/quest=40570/into-the-heavens - Most of the NPC's here do like 5 times more dmg than suppose to.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
@ShikoSCS, más ejemplos de overdamage de scaling, incluso con NPCs que no castean spells.
