### ISSUE TITLE
[Class] Shaman [Scenario] [Quest] The Hammer in the Deep [Artifact weapon]

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#2014]
**Links:**
https://www.wowhead.com/quest=41335/the-elements-call
https://www.wowhead.com/quest=40224/the-hammer-in-the-deep

**What is happening:**

After u complete The Elements Call and pick up the Enhancement, the phasing bug out.
There must a be little RP from Thrall to tell you what to do https://youtu.be/IdEPKqRlVQA?t=238
You suppose to talk with Mylra and continue the Quest chain, but there are 2 Mylars and 1 Drainie that offer you a restoration Quest chain for some reason. [Click](https://imgur.com/a/UdtRS2t)
The scenario is ok ( The Hammer in the Deep ), but you stuck at the last stage after u kill the Demon, since Mylra is missing and the Gryphon not landing ( He wait you at the cave entrance right now)
https://youtu.be/IdEPKqRlVQA?t=707
The '' Enter the Crumbling Depths'' part don't Count too.

PS: There is a quest chain before ''The Hammer in the deep'' scenario, but for now leave it as it is (without that quests) until we catch up.
**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
