### ISSUE TITLE
[Class] Shaman [Quest] [Artifact weapon]

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#2015]
**Links:**
 https://www.wowhead.com/quest=39746/a-ring-unbroken
https://www.wowhead.com/npc=99549/whispering-winds

**What is happening:**

Once u land in the new Dalaran, Thrall don't follow you (as the other class's the custom fix) to give you the Artifact quest
Thrall ID 91731
( The blizzlike way is with the walking ''wind'' https://warcraft.blizzplanet.com/blog/comments/a-ring-unbroken-shaman-artifact-questline) "{Name}! I found you! The four winds have been sent to seek you out. Come with me."
In  ''A ring unbroken'' Scenario, at stage 2 one of the object (the campfire)  is not market on the map and don't ''glow'' too
[Click](https://imgur.com/a/UYWo8Rr)

**What should happen:**
Put Thrall to follow you once u land, or the Whispering winds that gaid you to Thrall.

**Comment by Cefiro-Caecias** [comment]
Fixed.
