### ISSUE TITLE
[Class] Shaman  [Scenario] The Voice of Thunder [Artifact] Elemental

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#2016]
**Links:**

https://www.wowhead.com/quest=39771/the-voice-of-thunder

**What is happening:**
The Scenario kinda work ( u can take the weapon) , but  u stuck at stage 3. At this point you can just run to the top, claim the weapon and die from the mobs.

**What should happen:**
General speaking the scenario is a mess ( Tiger's dont walk with you or anything)
Once u are done with Stage 2, it suppose to have another fight https://youtu.be/EBJNm6YQC4Y?t=242
At the final stage (after u clain the weapon) the mobs that spawn hit too hard (at least the spell)

**Comment by Cefiro-Caecias** [comment]
Fixed.
