### ISSUE TITLE
[Class] Warlock [Artifact] [MISC]

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#2017]
**Links:**
https://www.wowhead.com/npc=101097/calydus
https://www.wowhead.com/quest=40731/the-heart-of-the-dreadscar
https://www.wowhead.com/quest=43100/finding-the-scepter
https://www.wowhead.com/quest=40495/ulthalesh-the-deadwind-harvester
https://www.wowhead.com/npc=111740/mile-raitheborne

**What is happening:**
Once u made a warlock and reach Dalaran u suppose to talk with Calydus, but he has 2 quests. The artifact one and ''The Heart of the dreadscar''. As u can see that quest requires a long quest chain so it's not supposed to be there for you.
Once u accept the Quest and get ported to the Class hall and pick Affliction, in Calydus pop up two new quests. One for Affliction and ''Finding the Scepter''. That quest does not suppose to be there since you pick Affliction and the quest is for Destro.
https://imgur.com/a/mAs8mCs
Once u take the Affliction quest ''Ulthalesh, the Deadwind Harvester'' the UI bug out and u don't see it in the Quest log. It gets fixed after relog.
Mile Raithborne has a Vendor option that can be removed since it's no more needed in 7.3.5.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
