### ISSUE TITLE
[Class] Warlock [ Artifact] [Quest] The Dark Riders [Affiction] 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#2018]
**Links:**

https://www.wowhead.com/quest=40623/the-dark-riders
https://www.wowhead.com/npc=101257/the-conservator
https://www.wowhead.com/spell=201693/hateful-bolt
https://www.wowhead.com/spell=201692/evocation

**What is happening:**
Aside from missing the RP,  corps on the ground on stage 2 don't do any dmg
https://youtu.be/0JeaNk1jlG8?t=129
The spell that ''The Conservator'' uses / Hateful Bolt/  need any mana so he just kills you. It suppose to be like 1/9 of all the mana he have
https://youtu.be/0JeaNk1jlG8?t=215
He May miss the ''Evocation'' too. 

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
The Conservator, fixed. The rest will be blizzlike later. Available in the next update.
