### ISSUE TITLE
[Zone] Azsuna [Quest] Hunger's End

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#2019]
**Links:**

https://www.wowhead.com/quest=42756/hungers-end

**What is happening:**
Everything works fine, but at the last second before the kill, Ael'Yith disappears and you cant complete the quest.

**What should happen:**
https://www.youtube.com/watch?v=_RsEl7K84-k
You suppose to kill him, that's it.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
