### ISSUE TITLE
[Tyce] - Demon Hunter - Spell Fel Rush

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#2020]
**Links:**

https://www.wowhead.com/spell=195072/fel-rush

**What is happening:**
From time to time, on the first cast, it doesn't do any dmg.
It may be a range issue (we cast it out of range, or spell issue)

**What should happen:**
Suppose to do dmg.

**Comment by therealgm007** [comment]
from close range works perfectly. maybe the skill needs 1-2 yards (bigger range)

**Comment by Arkanheal** [comment]
Does anyone has an update on this?
