### ISSUE TITLE
[Class] WW monk Scenario / artifact

### ISSUE THREAD

**Issue by thyrazpowa** [GuabinaCore/WoWKoi#2022]
**Links:**

https://www.wowhead.com/windwalker-monk-artifact-weapon-fists-of-the-heavens-guide
https://www.wowhead.com/item=128940/fists-of-the-heavens?bonus=0

**What is happening:**
At WW monk scenario. Entering here with Essence of the wind item. Mobs hitting hard, and little mobs making unbelivable damage.
At the end of scenario, i dont get my Fist of the heavens artifact

**What should happen:**
Nerf the mobs, bcs the starting gear is 680 and it is not so much for get it, i mean scenario.
At the end, we will need to get the artifact.

**Comment by NightwindOI** [comment]
Duplicate with https://github.com/GuabinaCore/WoWKoi/issues/2013
