### ISSUE TITLE
[Tyce] - Monk getting small artifact power + colors bug

### ISSUE THREAD

**Issue by thyrazpowa** [GuabinaCore/WoWKoi#2023]
**Links:**
https://imgur.com/a/ptjYzow
https://imgur.com/a/ptjYzow
from WoWHead or our Armory

**What is happening:**
After "completing" the scenario and getting the weapon, we get 75 power for artifact, but its still need 100 for first trait.

And, after purchasing artifact powero from shopo, and get it the all trait dont get the color named by "purchasing all trait"
**What should happen:**
Getting 100 or 125 artifact powero, and getting color by purchasing all traito.

**Comment by NightwindOI** [comment]
This is the Scenario he talk about https://www.wowhead.com/quest=40570/into-the-heavens

**Comment by Cefiro-Caecias** [comment]
@ShikoSCS, lo que te había mencionado sobre el poder de Armas Artefacto, que ya te expuse en otro Issue ;)
