### ISSUE TITLE
[Zone] Suramar [Quest] Shal'Aran

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#2025]
**Links:**
https://www.wowhead.com/quest=42229/shalaran
from WoWHead or our Armory

**What is happening:**
npc called "first arcanist thalyssra" gives you a this quest which he should start moving and explore shal'aran when you hit ( im ready) but she wont

**Comment by NightwindOI** [comment]
SHe give u the quest but quest not work or ?

**Comment by armirmoazezi** [comment]
yes the quest is available and she gives you you accept it then you say you are ready but it wont work

**Comment by Cefiro-Caecias** [comment]
The quest was temporarily put into autocomplete mode. Later it will be blizzllike. Until then, it can be delivered without problems.
