### ISSUE TITLE
[Tyce] - Raid Firelands

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#2026]
**Links:**
https://www.wowhead.com/firelands
from WoWHead or our Armory
Beth'tilac <The Red Widow> https://www.wowhead.com/npc=52498/bethtilac ( she is immune to melee attack) 
Lord Rhyolith https://www.wowhead.com/npc=52558/lord-rhyolith ( doesnt drop loot tested on 25 heroic ) 
Shannox https://www.wowhead.com/npc=53691/shannox ( npc is miss located ) 
Ragnaros https://www.wowhead.com/npc=52409/ragnaros ( drops loot but you cant loot it ) 
and 2 npc right before him https://www.wowhead.com/npc=53617/molten-erupter they wont work invalid target

**Comment by NightwindOI** [comment]
Beth'tilac  need some time until ''trigger'' the fight, that may  be the issue
Shannox supposes to move all around the road, right now his just at the left side doing nothing.
Ragnaros was able to loot it but with a recheck

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
