### ISSUE TITLE
[Class] Death Knight [Artifact] [Quest] The Dead and the Damned

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#2027]
scenario stage 9 ( kill slay gorlix) npc is op

**Comment by armirmoazezi** [comment]
https://www.wowhead.com/quest=40740/the-dead-and-the-damned link of the quest

**Comment by NightwindOI** [comment]
Thats the NPC ( think so )
https://www.wowhead.com/npc=101778/gorelix-the-fleshripper

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
