### ISSUE TITLE
[Class] Demon Hunter [Quest]  Time of the essence

### ISSUE THREAD

**Issue by therealgm007** [GuabinaCore/WoWKoi#2029]
**Links:**

https://www.youtube.com/watch?v=0X3dr03P9QY

**What is happening:**

after pick the quest theres no npc  to speak with  : Kayn Sunfury  to return  and end the quest .

**What should happen:**\

NPC : Kayn Sunfury should be on the  main deck of The Fel Hammer next to scouting map.

**Comment by NightwindOI** [comment]
Duplicate with https://github.com/GuabinaCore/WoWKoi/issues/1758
