### ISSUE TITLE
 [Tyce] [Class] Demon hunter [Object] [Quest]  Scouting map 

### ISSUE THREAD

**Issue by therealgm007** [GuabinaCore/WoWKoi#2030]
**Links:**

-----------

**What is happening:**

when click on the scouting map the menu is open ,  after that need to choose a map location ( azsuna , suramar ,  stormheim.+++).
when choose a location theres no any quest to send you there.( as start location quest.)

**What should happen:**

open a new quest thats send you to location

**Comment by Cefiro-Caecias** [comment]
Fixed.
