### ISSUE TITLE
[Tyce] [Class] Death Knight [Object] [Quest] Scouting map 

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#2031]
scouting map wont work when you unlock class hall for the first time on dk class 
as default you get a quest to complete a scout on the map to  start leveling ()
but when you pick one zone ( i picked azsuna ) it does give you the starting quest for azsuna after that you have to travel to new dalaran to visit archmage khadgar on landing pad after that i got stuck because  there was no npc to click and  go in azsuna 
............................................................
this however is different on druid class scouting map for high mountain zone works perfect ( tested on horde and alliance) but the rest of the map wont work

**Comment by Cefiro-Caecias** [comment]
Fixed.
