### ISSUE TITLE
[Quest] [Keli'dan the Breaker] Not priority WoD quest. 

### ISSUE THREAD

**Issue by thyrazpowa** [GuabinaCore/WoWKoi#2032]
**Links:**
https://www.wowhead.com/quest=34741/kelidan-the-breaker

**What is happening:**
https://imgur.com/a/WFJ5qFP
After killing boss, rocks dont De-spawn, and cant get out.
Later is problem for mount farming, or doing achievs, etc.

**What should happen:**
Rocks need despawn after killing quest mob and continue the questline for garrison.

**Comment by Cefiro-Caecias** [comment]
I just tested the quest, and by killing Keli'dan the Breaker, the mini-scene in which Khadgar appears is activated, and they are all teleported out of that fortress, with which the quests can be continued quietly o.O
