### ISSUE TITLE
[Class] Warrior  [Quest] Odyn and the Valarjar [Artifact]

### ISSUE THREAD

**Issue by thyrazpowa** [GuabinaCore/WoWKoi#2033]
**Links:**
Proof: https://youtu.be/f_4DuyjG6NE
Quest LINK: https://www.wowhead.com/quest=39654/odyn-and-the-valarjar

**What is happening:**
https://youtu.be/f_4DuyjG6NE
NPC de-spawn, fade away, just look video lmao

**What should happen:**
NPC start guideing at class hall, and speak to player. Or smth like that, or Give instant Complete quest, and need to run odyn.

**Comment by Cefiro-Caecias** [comment]
The error occurs because when taking that quest, you are on a mount, and the mount blocks the execution of a script to invoke the Valkyr. Try leaving the quest and taking it again, without being on a mount. We will see to implement some security measure so that these problems do not occur.
