### ISSUE TITLE
[Class] Hunter  [Artifact] [Quest]

### ISSUE THREAD

**Issue by thyrazpowa** [GuabinaCore/WoWKoi#2034]
**Links:**
------------------------------------
**What is happening:**
MM Hunter artifact Scenario skipped, ( After going to broken shore u speak with npcs and instant skipped scenario so u never entered it) ))) so you CANT get artifact and getting to the class hall, doing questline. After u reach class hall, get the quest, purchase 1 trait, but you dont have artifact for it.

**What should happen:**
Disable not working hunter artifact scenarios at Choosing artifact, make them gray, cant click on it, and let new players dont waste time, or repair mm hunter scenario.

**Comment by NightwindOI** [comment]
what?

**Comment by Cefiro-Caecias** [comment]
Fix all Hunter Artifact Quests. Available in the next update.
