### ISSUE TITLE
[World Quest] - Green Horror

### ISSUE THREAD

**Issue by thyrazpowa** [GuabinaCore/WoWKoi#2036]
**Links:**

**What is happening:**
https://imageshack.com/i/poKCIf2Nj
Random, dream warden at grass, he play hide n seek...
Lot of invasion mobs at this zone, without invasion so ? :/

**What should happen:**

**Comment by NightwindOI** [comment]
Hello there, thx for the report, but next time please add at least some info/ links.
NPC ID https://www.wowhead.com/npc=99910/dream-warden
Quest name (World quest) https://www.wowhead.com/quest=42087/green-horror
How it suppose to be https://www.youtube.com/watch?v=Hv8l2WuEcTc
World quest is there, but the phase is the issue as I see it.

**Comment by Cefiro-Caecias** [comment]
We must rebuild this World Quest. I'll save it for later.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
