### ISSUE TITLE
[Zone] Azsune [Quest] The Nightborne Princ [NPC] [MISC]

### ISSUE THREAD

**Issue by thyrazpowa** [GuabinaCore/WoWKoi#2037]
**Links:**
https://imgur.com/a/0xTrPmO
https://www.wowhead.com/quest=37861/the-nightborne-prince

**What is happening:**
Move lower that npc, after killing boss that needed. 
Him coming but he take so hard spot for speak him.

**What should happen:**
Just get off the highground stella bro' come lower i want talk to you <3

**Comment by thyrazpowa** [comment]
if cant see the pic here is it : https://imgur.com/a/JgBqII7

**Comment by NightwindOI** [comment]
Do you want to move the NPC close to the building?

**Comment by thyrazpowa** [comment]
ye, cant touch him thanks.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
