### ISSUE TITLE
[World Event] Feast of Winter Veil [Object] Gift''s  [MISC] 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#2038]
**Links:**

https://www.wowhead.com/feast-of-winter-veil

**What is happening:**
https://imgur.com/a/UB8dgfw
The decoration/ Christmas tree is gone since the event is over, but the ''presents'' under are still here.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
