### ISSUE TITLE
[Tyce] - Pet del Hunter bug al usar Piedra hogar de dalaran

### ISSUE THREAD

**Issue by Mariohsotoh** [GuabinaCore/WoWKoi#2042]
The title, whenever u use Dalaran hearthstone the hunter's pet will spawn dead, it can't be dimiss or revived and can't change pet either. (the soution i found is relog and it solve the problem c= )

EDIT: Traslate

**Comment by NightwindOI** [comment]
Since it's in Spanish, I have no idea what that means. The good part is we have Spanish dev's : )

**Comment by Noahkrr** [comment]
tambien se bugea la pet al cambiar de zona, estaba en val'sharah pase por el limite de Azsuna y la pet se bugeo... esto tambien pasa al salir de mazmorras de legion con la pet activa... tambien pasa al entrar a Totem de trueno dentro del escenario o arriba en el escenario La cuna del martillo, eso pasa a ingresar por los puertas o ascensores la pet se muere y no revive (el bug solo ocurre en la expansión de legión, en la demás expansiones antiguas funcionan normalmente)

**Comment by ShikoSCS** [comment]
Fixed

**Comment by Fireevil** [comment]
como arreglaron esto tengo el mismo problema :(
