### ISSUE TITLE
[Arthas] - Unholy DK artifact questline bug

### ISSUE THREAD

**Issue by Jhonatinha** [GuabinaCore/WoWKoi#2043]
**Links:**

from WoWHead or our Armory

**What is happening:**
So when you click the weapon you should get it and then kill the boss, but in fact it just trigger the boss but the item does not goes to your bag

**What should happen:**
|The Weapon should go to your bag

**Comment by NightwindOI** [comment]
You mean this part of the quest? https://ptr.wowhead.com/quest=40986/the-dark-riders

**Comment by Jhonatinha** [comment]
yes, is this part, when i was doing it i just could not get the weapon

**Comment by LKArthas** [comment]
This is Working Completable Not Blizzlike but working check if you already had the weapon on the inventory, tried to reproduce couple times and everytime the item was given
