### ISSUE TITLE
Holy Pally artifact quest

### ISSUE THREAD

**Issue by gokugodmode** [GuabinaCore/WoWKoi#2044]
Links

https://www.wowhead.com/quest=42120/the-silver-hand

**What is happening:**
I was attempting the artifact quest line for holy paladin. The scenario quest line after you swim down with the npc's, the mobs keep one shotting me with void bolt as soon as I pull agro from any form of attack or heal . These continus deaths put me out of range for the rp once the NPCs are able to clear the trash and I get stuck in a loop of not being able to move on to the next chamber . I did the fresh 100 boost and equipped all the gear so not sure why the 1 shots. 
I have tried sitting way back and just letting the npcs kill everything but when I moved on the 2nd part down the tunnel they run and grab a 3 pack , there is also 2 additional mobs there who dont get pulled by them so I was out of range of the RP again as I had to try to grab them myself and these mobs have a healing buff that generally makes them unkillable with holy spec damage through put .
I had abandoned the quest to restart several times and also tried relogging during the loop of not seeing the RP to continue
But I cant get past the 2nd tunnel either cuz of deaths and/or being out of range of the RP while trying to not get 1 shot by pulling agro of doing any sort of damage to it.

Per KTiger cant pick up weapon as well

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Regarding the damage they take in those quests, we have been on it, and we have come to the conclusion that it is due to the low level of equipment that they receive in the Promo, since those mobs are designed as if they carry the best equipment of Draenor. All that remains is for Guabina to authorize the improvement of items in the Promo.
