### ISSUE TITLE
[Sefrenia] - Rise, champions!

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2047]
**Links:**
https://www.wowhead.com/quest=42671/rise-champions
https://www.wowhead.com/quest=42670/rise-champions

from WoWHead or our Armory

**What is happening:**
the NPC that grants a quest (https://www.wowhead.com/npc=103025/battlelord-gaardoun), grants 2 quests. both quests require recruiting Asha Ravensong (https://www.wowhead.com/npc=103007/asha-ravensong). so in fact, when u do whatever  first quest of those u took, other one becomes incompletable, since Asha Ravensong is already recruited by previous quest. that stucks  whole questline. 

**What should happen:** 
the NPC that grants a quest (https://www.wowhead.com/npc=103025/battlelord-gaardoun) should give only one quest, depending on what choice was made during "A new direction" quest (https://www.wowhead.com/quest=40373/a-new-direction).

**Comment by Cefiro-Caecias** [comment]
Fixed.
