### ISSUE TITLE
Engineering Quest Endless Possibilities

### ISSUE THREAD

**Issue by jainasfatbussy** [GuabinaCore/WoWKoi#2050]
**Links:**
https://www.wowhead.com/quest=40854/endless-possibilities

**What is happening:**
if you fail to pick up Fel Reaver Husk it disappears and relog or taking the quest again doesnt respawn it. 

Went back after doing the assassination weapon questline and it respawned so I could pick it up

**What should happen:**
It shouldnt disappear and if it does only should be a few seconds if not instantaneously reappear again

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the enxt update.
