### ISSUE TITLE
[Tyce] - Rogue Assassination Legion Quest Cloak and Dagger

### ISSUE THREAD

**Issue by jainasfatbussy** [GuabinaCore/WoWKoi#2051]
**Links:**
https://www.wowhead.com/quest=42539/cloak-and-dagger

**What is happening:**
Althea Ebonlocke just stands there doing nothing and can be killed. 
There aren't any markings around Blood of the Innocent.
Skull of the Innocent isn't on a legion table and it says when hovered over the skull "Cráneo del inocente" and Chef Grual is not present at the skull. 
If you kill Althea Ebonlocke and abandon the quest and go back to auto pickup the quest at the previous quest house & go back to kill Althea when she spawns she will take self damage.

**What should happen:**
https://youtu.be/luT2gIrNqpQ?t=93

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
