### ISSUE TITLE
Young and Vicious

### ISSUE THREAD

**Issue by Skullbasha** [GuabinaCore/WoWKoi#2052]
**Links:**
https://www.wowhead.com/quest=24626/young-and-vicious
from WoWHead or our Armory

**What is happening:**
The raptor we have to ride is stanionary and our quest item doesnt work

**What should happen:**
We should ride the dinosaur and he should be moving around

**Comment by NightwindOI** [comment]
Hello this,we focus on Legion part of the game (since its and gonna be instant level 100) , but thx for the report!

**Comment by Cefiro-Caecias** [comment]
That area will be repaired blizzlike later. Patience ;)

**Comment by Skullbasha** [comment]
Great thank you for responding all I needed to hear ,Just wanted to
contribute to your guys efforts :)
