### ISSUE TITLE
Runas the Shamed

### ISSUE THREAD

**Issue by jacobx97** [GuabinaCore/WoWKoi#2053]
**Links:**
https://www.wowhead.com/quest=37957/runas-the-shamed

**What is happening:**
Quest can not be completed, because npc Runas the Shamed do not become friendly after fight with him and he die. So, you can not escort him to Senegos

**What should happen:**
You fight with Runas The Shamed and after a while he became a friendly and you can escort him to Senegos. You should not be able to kill him

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
