### ISSUE TITLE
[Quest - Highmountain] Bolas Bastion

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2054]
**Links:**

https://www.wowhead.com/quest=42630/bolas-bastion

https://www.wowhead.com/spell=214357/launch-bolas

**What is happening:**

Launch Bolas ability doesn't grant credits toward the quest. (The other ability Flaming Bloas ID214476 does grant credits, so the quest can be completed)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
