### ISSUE TITLE
[NPC - Highmountain] Overgrown Larva

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2055]
**Links:**

Quest - https://www.wowhead.com/quest=39490/infestation

NPC - https://www.wowhead.com/npc=94691/overgrown-larva

**What is happening:**

The NPC engages melee combat.

**What should happen:**

Overgrown Larva should be stationary, spamming Acid spit.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
