### ISSUE TITLE
[NPC - Highmountain] Rivermane Tauren missing

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2057]
**Links:**

Quest - https://www.wowhead.com/quest=39274/defend-the-riverlands

NPC - https://www.wowhead.com/npc=99406/rivermane-tauren-freed

**What is happening:**

Rivermane Tauren are missing around the bonus objective area.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
