### ISSUE TITLE
[Quest / Object - Highmountain] 

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2058]
**Links:**

Quest - https://www.wowhead.com/quest=39488/balance-of-elements

Object - https://www.wowhead.com/object=243639/siphoning-crystal

**What is happening:**

Siphoning Crystal is missing around the questing area. The quest can still be completed, because the mobs in the area drop the quest item. Although, it's completable, the drop rate of the quest item is so low, It is required to clear the whole area twice by one player.
**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
