### ISSUE TITLE
[NPC - Highmountain] Jale Rivermane - wrong quest order?

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2059]
**Links:**

https://www.wowhead.com/npc=96520/jale-rivermane

https://www.wowhead.com/quest=39489/invading-spelunkers

**What is happening:**

Jale rivermane gives only one quest (https://www.wowhead.com/quest=39488/balance-of-elements).

**What should happen:**

She is supposed to give Invading Spelunkers along with Balance of Elements. Have these quest after each other forces to clear the cave twice.
 (This issue might be caused by the bug, that makes quest disappear form the dialogue options. For example: If there are 2 or more quests, sometimes, taking one quest makes the other one disappear.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
