### ISSUE TITLE
[NPC - Highmountain] Rivermane Shaman

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2060]
**Links:**

https://www.wowhead.com/npc=96038/rivermane-shaman

**What is happening:**

The NPC is copied every time a quest is accepted, completed or abandoned.

https://imgur.com/a/FzM3MM3

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
