### ISSUE TITLE
[NPC Highmountain] Bitestone Raider

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2061]
**Links:**

https://www.wowhead.com/npc=102274/bitestone-raider
https://www.wowhead.com/npc=95043/young-mountainstrider

**What is happening:**

Bitestone Raiders don't attack and invincible Young Mountainstriders are "attached" to them.

https://imgur.com/a/Kj15FrU

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
