### ISSUE TITLE
[Quest - Highmountain] Ceremonial Drums

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2062]
**Links:**

https://www.wowhead.com/quest=42622/ceremonial-drums

**What is happening:**

Large Ceremonial Drum and Medium Ceremonial Drum are missing.

EDIT: Their position is just incorrect.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. The "Small Ceremonial Drum" are summoned when you kill the "Bluewax Drumtaker" on the upper terrace of Thundertotem ;)

https://www.wowhead.com/npc=108145/bluewax-drumtaker
