### ISSUE TITLE
[Arthas] - Quest - Highmountain - Scout it Out 

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2064]
**Links:**

Quest - https://www.wowhead.com/quest=40228/scout-it-out

1.Quest Item - https://www.wowhead.com/item=130074/flare-gun

2.Quest NPC - https://www.wowhead.com/npc=95762/irewing

**What is happening:**

1. Flare gun doesn't provoke the quest NPC. Flare gun has wrong spell animation.

2.Irewing is attack-able by default. Irewing should be attack-able only after being provoked by Flare Gun.

**What should happen:**

**Comment by LKArthas** [comment]
Quest Will Is Scripted Now, but spell ID - 195059 Signal Flare Should be fixed it's search radius to go up instead down the player
