### ISSUE TITLE
Demons among us

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2065]
**Links:**
https://www.wowhead.com/quest=40607/demons-among-us
from WoWHead or our Armory

**What is happening:**
quest works as it should, yet the issue is that half of the mobs cant be attacked. whenever you attack them, they "evade". there are still ombs that cant be killed, few tho. 

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
This whole chain is being repaired by Arthas. Patience.

**Comment by klaxce** [comment]
You have to flag yourself PVP Enabled in order to attack the demons
