### ISSUE TITLE
Saving Stellagosa

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2066]
**Links:**
https://www.wowhead.com/quest=37450/saving-stellagosa
from WoWHead or our Armory

**What is happening:**
after finding Stellagosa quest goals do not change. they still show 0\3 chains broken. the person, who doesnt know where to find key to break chains will be stuck, since theres no pointer to Overseer Lykill. also, few words about Overseer Lykill. he puts some weird Pacify effect, that seems permanent. since im a paladin i managed to break it with Hand of Freedom(i guess Divine Shield works too) but other classes do not have such abilities mostly. check it out.

**What should happen:**
after finding stellagosa the goal of quest should change to "Lykill's Key" and show the location of Lykill(https://www.wowhead.com/npc=86535/overseer-lykill). 
theres a YT video of this quest https://www.youtube.com/watch?v=HlKEYf25lIM

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
