### ISSUE TITLE
[NPC - Highmountain] King Mrgl-Mrgl

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2067]
**Links:**

https://www.wowhead.com/npc=98067/king-mrgl-mrgl

**What is happening:**

King Mrgl-Mrgl has all of his quests available right away.

These 3 quest are available at the start:
1. I'll Huff, I'll Puff... (https://www.wowhead.com/quest=40047/ill-huff-ill-puff)
2. Nature vs. Nurture (https://www.wowhead.com/quest=40045/nature-vs-nurture)
3. Slime Time (https://www.wowhead.com/quest=40049/slime-time)

After these quests are completed, these two are unlocked: 
1. Murlocs: The Next Generation (https://www.wowhead.com/quest=40102/murlocs-the-next-generation)
2. Oh, the Clawdacity! (https://www.wowhead.com/quest=40230/oh-the-clawdacity)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
