### ISSUE TITLE
[NPC - Highmountain] Crab Rider Grmlrml / Tamed Coralback

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2068]
**Links:**

https://www.wowhead.com/npc=97933/crab-rider-grmlrml
https://www.wowhead.com/npc=97928/tamed-coralback

**What is happening:**

Both NPCs are passive. They don't attack, use skills or even get aggro. Just walking around.
Crab Raider Grmlrml cannot be attacked.
After killing Tamed Crab, Crab Raider Grmlrml dies as well.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
