### ISSUE TITLE
[Tyce] - Murky's Egg, Murky form

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2069]
**Links:**

- Quest "Murlocs: The Next Generation": https://www.wowhead.com/quest=40102/murlocs-the-next-generation

- NPC "Murky": https://www.wowhead.com/npc=89619/murky

**What is happening:**

2."Murky" form doesn't let mobs target the player, mob just stands there doing nothing. If you walk a few steps away from the mob you are attacking, it resets.

3. Murky abilities:

   1. Slime - works properly,
   
   2. March of the Murlock - the spell is channeling, but doesn't do damage. The spell always activates in only one direction (https://imgur.com/a/HZC07Qx). The spell should be cast in the direction the player is facing.
   https://www.wowhead.com/spell=179062/march-of-the-murlocs

  3. Pufferfish - the spell doesn't do damage. It spawns a Pufferfish critter that attracts aggrobut doesn't do anything..
     https://www.wowhead.com/spell=179023/pufferfish

 4. Saftey bubble - can't tell if it works, cuz mobs can't attack the player.
    https://www.wowhead.com/spell=179038/safety-bubble

**Comment by Cefiro-Caecias** [comment]
Partially repaired. I notify Core Devs regarding spells and NPCs that do not take you as an enemy even if they attack.

**Comment by Arkanheal** [comment]
Update: Mob now targets the player instead of the "form" (you lose HP instead of your "vehicle").
March of the murloc deals damage but the animation is wrong.
