### ISSUE TITLE
[NPC - Highmountain] Swamprock Tadpole

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2070]
**Links:**
https://www.wowhead.com/npc=98046/swamprock-tadpole

**What is happening:**

Swamprock Tadpole can be clicked multiple times for additional quest credits. (They don't despawn right after being clicked)

**What should happen:**

One click, one credit.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
