### ISSUE TITLE
[NPC - Highmontain] Oakin Ironbull <Rivermane Emissary>

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2071]
**Links:**

https://www.wowhead.com/npc=95256/oakin-ironbull#starts

**What is happening:**

Oakin Ironbull doesn't give any quests after turning in https://www.wowhead.com/quest=38912/the-bloodtotem-tribe

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
