### ISSUE TITLE
[NPC - Highmountain] Arru

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2072]
**Links:**

https://www.wowhead.com/npc=97220/arru

https://www.wowhead.com/object=244473/thunder-totem-stolen-goods

**What is happening:**

Thunder Totem Stolen Goods do not spawn after Arru script is finished.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
