### ISSUE TITLE
[NPC - Lasan Skyhorn

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2073]
**Links:**

https://www.wowhead.com/npc=97407/lasan-skyhorn

https://www.wowhead.com/quest=39780/the-underking

**What is happening:**

The only quest in Snowblind Mesa is The Underking, its handed by Lasan Skyhorn. It can't even be completed because of missing phase from previous quests that are missing in the area.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
This quest will be repaired when you rebuild the area, as there are many terrain details involved, and it will not be easy.
