### ISSUE TITLE
[NPC - Highmountain] Captive Great Eagle

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2074]
**Links:**

https://www.wowhead.com/npc=94991/captive-great-eagle-rescued

**What is happening:**

The NPC can be clicked multiple times for addtitional quest credits.

Rescue animation is bugged. The model just slides in the air and vanishes after a second.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
