### ISSUE TITLE
[NPC] Naxa, Arxas, Xist

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2075]
**Links:**

https://www.wowhead.com/npc=99217/naxa
https://www.wowhead.com/npc=99216/arxas
https://www.wowhead.com/npc=97013/xist

**What is happening:**

NPCs above are missing attack animation and spells.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
