### ISSUE TITLE
[NPC] Necrodark Defiler, Shadow Lurker

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2076]
**Links:**

https://www.wowhead.com/npc=104888/necrodark-defiler
https://www.wowhead.com/npc=105069/shadow-lurker
https://www.wowhead.com/npc=125136/dark-tendril

**What is happening:**

NPCs above are 110 despite player's level and are visible out of their quest phase (https://www.wowhead.com/quest=41764/walking-in-their-footsteps) 

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Scaling, fixed. His phase will be repaired when he rebuilds the area. Available in the next update.
