### ISSUE TITLE
[Quest - Highmountain] Justice rains from above

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2077]
**Links:**

https://www.wowhead.com/quest=40594/justice-rains-from-above

https://www.wowhead.com/npc=100712/war-eagle

  https://www.wowhead.com/spell=213467/skyhorn-strafing-run
  https://www.wowhead.com/spell=198380/stonedark-brulfist
  https://www.wowhead.com/spell=213444/rivermane-totem

**What is happening:**

War Eagle's abilities don't work

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
