### ISSUE TITLE
Nightglave the Traitor

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2078]
**Links:**
https://wow.gamepedia.com/Nightglaive_the_Traitor
from WoWHead or our Armory

**What is happening:**
NPC doesnt use a single ability. she just autoattacks, pretty low damage. according to wow wiki, she has 4 abilites(listed below)

**What should happen:**
NPC should use abilites (https://www.wowhead.com/?spell=209317) (https://www.wowhead.com/?spell=209325) (https://www.wowhead.com/?spell=212054) (https://www.wowhead.com/?spell=186041).
YT video of quest https://www.youtube.com/watch?v=igae9ljhnTQ

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
