### ISSUE TITLE
Flashwyrm ("Their Dying Breaths" quest)

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2079]
**Links:**
https://www.wowhead.com/npc=107098/flashwyrm
from WoWHead or our Armory

**What is happening:** flashwyrms are passive. 

**What should happen:**
first of all, they seem hostile(red nameplate), tho have to be neutral( yellow nameplate). second, even tho they have hostile nameplate they do not attack. third, related to quest (https://www.wowhead.com/quest=42271/their-dying-breaths). when a player gathers a "cracked ley crystal" (https://www.wowhead.com/item=122306/cracked-ley-crystal), 1 nearby flashwyrm should become hostile and attack a player.
proof : https://www.youtube.com/watch?v=NQz7o6y6c2k

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
