### ISSUE TITLE
[Arthas/Sefrenia] - El cabo de tuercespina

### ISSUE THREAD

**Issue by carlosyuniro** [GuabinaCore/WoWKoi#208]
https://es.wowhead.com/quest=26663/hundido-desde-dentro

Al darle click al objeto no lo cuenta en la mision

al darle click al objeto te debe contar la misión son 3 ninguno de los 3 funciona

**Comment by Cefiro-Caecias** [comment]
No hay bug presente. Asumo que quizás estabas en party, y la quest no estaba calibrada para admitir party en los objectives. He aplicado un ajuste a eso, por las dudas. Disponible en el próximo update.

**Comment by carlosyuniro** [comment]
Listo ya tengo el logro de misiones en vega, muchas gracias, excelente trabajo felicitaciones
