### ISSUE TITLE
The walk of shame(prince farondis bug)

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2080]
**Links:**
https://www.wowhead.com/quest=37467/the-walk-of-shame
from WoWHead or our Armory

**What is happening:**
Prince Farondis is running to the end of the quest, ignoring(well, actually, he strafes back and forward when he pulls mobs while running) mobs.

**What should happen:**
Prince Farondis should kill any mobs that aggro at him or player with his fire meteors. 
related YT video

NOTE: quest works FINE, its just about Prince Farondis wrong behaviour.

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later on.
