### ISSUE TITLE
Shipwrecked Sailors

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2081]
**Links:**
https://www.wowhead.com/quest=42220/shipwrecked-sailors
from WoWHead or our Armory

**What is happening:** most of those "sailors" cant be rescued because u cant click on them. out of all "sailors" that are represented there, ive found only 6 of those, who can be saved. 

**What should happen:**
every "sailor" should be clickable and thus - saved.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
