### ISSUE TITLE
Koda Steelclaw(and related quests)

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2082]
**Links:**
https://www.wowhead.com/npc=91223/koda-steelclaw
from WoWHead or our Armory

**What is happening:** there are few issues with this npc. first of all she appears in a wrong location(should be in the cave, yet its standing outside). second issue relates to a quest she gives, Entangled Dreams(https://www.wowhead.com/quest=38147/entangled-dreams). 2nd part of the quest doesnt get its credit after killing the mob required for it(https://www.wowhead.com/npc=91045/morphael). but, if u come back to Koda, u can turn in the quest, even tho credit shows as 0\1. 3rd issue is the quest, that starts whole questchain with Koda, that one(https://www.wowhead.com/quest=38142/archdruid-of-the-claw). it does not lead to Steelclaw Vale, where a player will follow the questline, instead it cant be instantly turned in to the same npc u took it from, (https://www.wowhead.com/npc=91651/nyandra-springbloom)

**What should happen:**
NPC should be in the cave. Entangled Dreams should get 1\1 credit after killing Morphael. Archdruid of the Claw quest should lead to Steelclaw Vale

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
