### ISSUE TITLE
Val'sharah and class hall bug

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2083]
**Links:**

from WoWHead or our Armory

**What is happening:** for some reason in Val'sharah the upper string from class hall appears(one u can see amount of resources and name of the class hall). i will put a screenshot to clarify. happens on every character(so far ive seen this on DH, rogue, paladin).
link to the screenshot : https://imgur.com/afXHYs2

**What should happen:**

**Comment by menelys** [comment]
same goes for Highmountain

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
