### ISSUE TITLE
NPC Thistleleaf Ruffian, Thisteleaf Menace

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2084]
**Links:**
https://www.wowhead.com/npc=91474/thistleleaf-ruffian
https://www.wowhead.com/npc=91472/thistleleaf-menace
from WoWHead or our Armory

**What is happening:**
1st - some of those cant be attacked.
2nd - they use death voice lines while still alive.
3rd - those of them, who fly over a dragon are immune to any kind of attack and they can fly in textures.
4th (relates to the place, where NPCs are located) - the water in the pool is invisible. water exists, but invisible. somehow. i got no idea how to explaing it, screenshot will be provided. 
screenshot link :https://imgur.com/THiUrhu

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
