### ISSUE TITLE
Moonclaw vale(bonus objective)

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2085]
**Links:**
https://www.wowhead.com/quest=39393/moonclaw-vale
from WoWHead or our Armory

**What is happening:**u can get credit from killing mobs, but cant save moonclaw druids and cant destroy nightmare totems to get % for credit.

**What should happen:**
destroying a totem should grant 3% credit. saving a druid should grant 3% of credit. totems and druids should be clickable(they cant be clicked atm)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
