### ISSUE TITLE
Paladin class hall dublicate NPCs

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2087]
**Links:**

the following NPCs are dublicated. im pointing only those who stay in 1 place, not pointing those who are spreaded across whole class hall.

Aponi Brightmane(https://www.wowhead.com/champion=757/aponi-brightmane) (the one located near scounting map)
Arator the Redeemer (https://www.wowhead.com/npc=99997/arator-the-redeemer) ( the one located near scouting map)
Delas Moonfang(https://www.wowhead.com/npc=110866/delas-moonfang) ( the one located near scouting map)
Champion Vranesh (https://www.wowhead.com/npc=100088/champion-vranesh)
Eadric the Pure (https://www.wowhead.com/npc=100196/eadric-the-pure)
Tarenar Sunstrike (https://www.wowhead.com/npc=45729/tarenar-sunstrike)
Gidwin Goldbraids (https://www.wowhead.com/npc=100077/gidwin-goldbraids)
Sister Elda (https://www.wowhead.com/npc=91190/sister-elda)
Katherine the Pure (https://www.wowhead.com/npc=92313/katherine-the-pure)
Defender Katroi (https://www.wowhead.com/npc=100009/defender-katroi)
Aenea(https://www.wowhead.com/npc=100201/aenea)
Tiza Battleforge ( https://www.wowhead.com/npc=92373/tiza-battleforge)
Azar Stronghammer (https://www.wowhead.com/npc=99945/azar-stronghammer)
Defender Ursi (https://www.wowhead.com/npc=100010/defender-ursi)
Archivist Emeline(https://www.wowhead.com/npc=92271/archivist-emeline)
 

from WoWHead or our Armory

**What is happening:**

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
This will be repaired later when we rebuild the Hall. Patience ;)
