### ISSUE TITLE
The end of the saga

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2088]
**Links:**
https://www.wowhead.com/quest=42005/the-end-of-the-saga
from WoWHead or our Armory

**What is happening:**
the NPC (https://www.wowhead.com/npc=105724/orik-trueheart) does not start a quest. means protection paladin artifact cant be obtained atm.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
