### ISSUE TITLE
A falling star

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2089]
**Links:**
https://www.wowhead.com/quest=44009/a-falling-star
from WoWHead or our Armory

**What is happening:** quest cant be turned in, Archmage Khadgar is existing. 

**What should happen:**
Archmage Khadgar should locate in the Chamber of the Guardian so a player can turn in a quest.

**Comment by Cefiro-Caecias** [comment]
Fixed.
