### ISSUE TITLE
[Arthas/Sefrenia] - NPC: Dialog in Spanish

### ISSUE THREAD

**Issue by Loquedog** [GuabinaCore/WoWKoi#209]
**Links:**

https://www.wowhead.com/npc=47418/runda

**What is happening:**

Her dialog when you speak to her is in spanish (I think)

**What should happen:**
Should probably be in english.

**Comment by DeltaVortex** [comment]
I think every single profession trainer has this issue, as in goblin starter area it's the same.

**Comment by Cefiro-Caecias** [comment]
No translation for that at the moment. Patience ^^
