### ISSUE TITLE
A sight for sore eyes

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2090]
**Links:**
https://www.wowhead.com/quest=38646/a-sight-for-sore-eyes
from WoWHead or our Armory

**What is happening:**
completely broken. half of the Black Rook Falcons are dead(means they cant be marked), other half cant be marked, even tho they are alive. it always says "target is invalid", no matter what Falcon is targeted, dead or alive

**What should happen:**
Alive Black Rook Falcons should be markable and killed by grandma, granting quest credit

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
