### ISSUE TITLE
[Tyce] - Dalaran: Greyfang Enclave + Windrunner's Sanctuary Bug

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2091]
**Links:**

from WoWHead or our Armory

**What is happening:**
if horde player enters Greyfang enclave on a mount, he doesnt get kicked  away by guards. however, if u go by feet, u will be  kicked. i guess that works for alliance too(cant say, only play horde).

**What should happen:**
horde players should be kicked from Greyfang Enclave instantly, regardless of their state(mounted\dismounted)

P.S. i guess this issue relates to mechanic(that is wrong, in fact), when u cant click on some quest item, or speak to NPC unless u dismount. i think that way because game keeps warning "You are mounted"while i ride in Greyfang Enclave. as soon  as i dismount, im instantly kicked
screenshot link : https://imgur.com/SABJahP

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
