### ISSUE TITLE
Serenity's End scenarion - Infernal Destroyer

### ISSUE THREAD

**Issue by jacobx97** [GuabinaCore/WoWKoi#2092]
**Links:**

https://www.wowhead.com/quest=12103/before-the-storm
https://www.wowhead.com/npc=98011/infernal-destroyer
https://youtu.be/LgynLiSpaco?t=97

**What is happening:**
Infernal destroyer in monk's class hall scenario have too much hp, it has got 2.38M.
And after you kill it, you get combat bug, so you can not complete stage 3 because of it(probably). After I click on Number Nine Jia, nothink happened.

**What should happen:**
It should has got 1.4M hp (see youtube video from retail)

**Comment by Cefiro-Caecias** [comment]
Fixed.
