### ISSUE TITLE
Dreamleaf

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2093]
**Links:**
https://www.wowhead.com/item=124102/dreamleaf#gathered-from-object
from WoWHead or our Armory

**What is happening:**
so, there are few issues with dreamleaf ive found so far.
1st : default dreamleaf bush doesnt grant skill up point. its always grey. link : https://www.wowhead.com/object=244775/dreamleaf
2nd : however, theres another dreamleaf bush, that grants skill up point. link : https://www.wowhead.com/object=244776/dreamleaf. the difference is that second link leads to a bush that drops "blight infested dreamleaf" that is the target for a quest (https://www.wowhead.com/quest=40019/an-empathetic-herb)
3rd : for some reason its not called "dreamleaf" ingame, its in spanish, "frondasueno". 
to make it even more clear, theres a picture u can see default bush and red bush. red one grants skill upi point, default does not. 
pic link : https://imgur.com/6dUGaAB
**What should happen:**
every bush should grant a skill up point. name shud be in english(for english client)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
