### ISSUE TITLE
The demon's trail

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2094]
**Links:**
https://www.wowhead.com/quest=38753/the-demons-trail
from WoWHead or our Armory

**What is happening:**
upon reaching the point of quest, cinematic starts.. yet its only black screen. after skipping cinematic theres no Tyrande to turn in quest to. cant be completed.

**What should happen:**
after reaching the point of quest, there should be 2 cinematics and Tyrande to turn in quest to.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
