### ISSUE TITLE
[Quest - Highmountain] Bloodtotem tribe storyline start

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2095]
**Links:**

https://www.wowhead.com/quest=38912/the-bloodtotem-tribe

https://www.wowhead.com/quest=39371/witches-of-the-sky

https://www.wowhead.com/quest=39372/witch-of-the-wood
https://www.wowhead.com/quest=39373/hags-of-a-feather

**What is happening:**

After turning in "The Bloodtotem Tribe" NPC is left with no quests resulting in being stuck. For some reason, completing "Witches of the Sky" Bonus Objective quest unlocks the next quest "Witch of the wood"

**What should happen:**

According to YT videos, "Witch of the wood" and "Hags of a Feather" should be available at the NPC right after turning in ""The Bloodtotem Tribe"

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
