### ISSUE TITLE
[Quest - Highmountain] Cave of the blood trail

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2096]
**Links:**

https://www.wowhead.com/quest=39455/cave-of-the-blood-trial

**What is happening:**

1. Oakin Ironbull has incorrect pathing. He goes through walls into the cave.
2. Feltotem Warmonger (https://www.wowhead.com/npc=96307/feltotem-warmonger) are visible out of their phase, are a WQ objective or they just aren't supposed to be there, cuz yt videos don't indicate their presence in the cave while doing the storyline quests. 
3. "Harpy placed on altar" missing harpy model

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
