### ISSUE TITLE
[NPC - Highmountain] Navarrog

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2097]
**Links:**

https://www.wowhead.com/npc=95421/navarrogg

https://www.wowhead.com/quest=39425/stonedark-crystal
https://www.wowhead.com/quest=39588/they-will-pay-with-blood

**What is happening:**

Navarrogg only give "Stonedark Crystal" after completing "Pet Rocks"

**What should happen:**

He is supposed to give both  "Stonedark Crystal" and "They will pay with blood" at the same time.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
