### ISSUE TITLE
[Quest - Highmountain] Blood Debt

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2098]
**Links:**

https://www.wowhead.com/quest=39426/blood-debt

https://www.wowhead.com/npc=96453/stonedark-drogbar

**What is happening:**

1. Accepting/abandoning the quest spawns 2 copies of  Stonedark Dogbar.
2. Leaving the questgiver's cave (coords:45.0, 32.0, spawns additional 1 Stonedark Dogbar. (works infinitely, I can just run in and out spawning infinite amount of copies)
3. Stonedark Dogbar movement speed is very slow.
4. Entering bridge (coords: 47.9, 26.4) spawns another copy of Stonedark Dogbar.
5. After completing the quest, some copies of Stonedark Dogbar did not disappear.

**What should happen:**

According to YT video, Stonedark Drogbar should only be spawned when leaving the cave.
According to YT video, Stonedark Drogbar' movement speed should equal player's movement speed (mount included)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
