### ISSUE TITLE
[Saitama] - Spell Bursting Shot not pushing back

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#21]
Class: Hunter
Spec: Marksmanship
Spell: [Bursting Shot](https://www.wowhead.com/spell=186387/bursting-shot)
**What is happening:**
Sometimes, [Bursting Shot](https://www.wowhead.com/spell=186387/bursting-shot) does not push the targeted enemy back, be they immune to pushback or not.

**What should happen:**
[Bursting Shot](https://www.wowhead.com/spell=186387/bursting-shot) should always push the targeted enemy back, unless they are immune to pushback.

**Comment by login6710** [comment]
Check this spell and if it works correctly. Only in some cases when there are unevennesses in the map it can give you the impression that the spell does not push the NPCs. I tried it 30 times with 1 NPC on a flat surface and it always worked.
