### ISSUE TITLE
Into The Heavens problems

### ISSUE THREAD

**Issue by jacobx97** [GuabinaCore/WoWKoi#2100]
**Links:**

https://www.wowhead.com/quest=40570/into-the-heavens#

**What is happening:**
- When you enter the scenario, the quest complete immediately, so you can HS and complete the quest, but you do not get artifact weapon and then there is no way to get it.
- NPCs do a lot of dmg with melee attacks
- If you die in stage 4, you are released in final stage

**Comment by Cefiro-Caecias** [comment]
At the moment, it is completable. It will be refined later. Damage-wise, it's because the promo team is pretty mediocre; We will see to provide them with better equipment.
