### ISSUE TITLE
[Quest - Stormheim] Stormdrake Welp Cave

### ISSUE THREAD

**Issue by Remer6520** [GuabinaCore/WoWKoi#2101]
**Links:**
https://www.wowhead.com/npc=92415/storm-drake-whelp

https://www.wowhead.com/quest=38059/pins-and-needles

https://www.wowhead.com/quest=38058/lightning-rod

**What is happening:** 

You are able to spam click 7th Legion Dragoons, causing you to complete the “Pins and Needles” quest almost immediately, and are able to do so even after you are done with the quest. This allows you to farm all charge needed in the “Lightning Rod” quest without fighting any stormdrake whelps. 

The “Lightning Rod” quest itself is also extremely difficult to complete without using this bug, as the stormdrake whelps in the cave are hitting extremely hard, and come in packs of 3-4. Another bug is also causing all charge to be lost on death, and for the quest to be forced to be abandoned and then reacquired to try again.  
**What should happen:**

If I recall correctly, you should not be able save 7th Legion Dragoons after completing the “Pins and Needles” quest, as well as the drakes being more manageable to take damage from so you can complete the quest properly.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
