### ISSUE TITLE
The New Blood Warlock Quest

### ISSUE THREAD

**Issue by toril2** [GuabinaCore/WoWKoi#2102]
**Links:**
https://www.wowhead.com/quest=40729/the-new-blood

**What is happening:**
This is a warlock quest. A pit lord named Jagganoth should come in and use fel fire on the player. He disappears and the quest cannot be completed.

**What should happen:**
Jagganoth should try to kill the player who runs and escapes.

**Comment by Cefiro-Caecias** [comment]
The quest can be completed, you only have to go to the portal to leave the area, and at that point it is completed. It will be refined later.
