### ISSUE TITLE
starving ghostclaw are friendly

### ISSUE THREAD

**Issue by j-9000** [GuabinaCore/WoWKoi#2103]
**Links:**

https://www.wowhead.com/npc=16347/starving-ghostclaw
https://www.wowhead.com/quest=9147/the-fallen-courier

**What is happening:**
starving ghostclaw are friendly and can attacke or be attacked

**What should happen:**
need to kill them to complet quest fallen courier

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
