### ISSUE TITLE
Worgen area Quest"Evacuate the Merchant Square"

### ISSUE THREAD

**Issue by Hypomanic94** [GuabinaCore/WoWKoi#2106]
**Links:**
https://www.wowhead.com/quest=14098/evacuate-the-merchant-square
from WoWHead or our Armory

**What is happening:** 
when i tried to do the quest objective by opening the merchant doors the doors opened but nothing happens

**What should happen:**
when i open the doors the quest tracker should count the doors i open and the quest get finished

**Comment by Cefiro-Caecias** [comment]
This area will go blizzlike in the future. Patience.
