### ISSUE TITLE
Aszuna Quest:Their Dying Breaths

### ISSUE THREAD

**Issue by Skullbasha** [GuabinaCore/WoWKoi#2108]
**Links:**
https://www.wowhead.com/quest=42271/their-dying-breaths
from WoWHead or our Armory

**What is happening:**

Basically,a grievously wounded whelping gets disapeared

**What should happen:**
It shouldn't Disapear

**Comment by Skullbasha** [comment]
Also,if you abandon and try again,the crystals for 1st part are missing But i suppose its the respawn time most likely

**Comment by Cefiro-Caecias** [comment]
Improved respawn. Available in the next update.
