### ISSUE TITLE
[CORE] - Stomp hunter talent doesn't work

### ISSUE THREAD

**Issue by Quelan** [GuabinaCore/WoWKoi#211]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/spell=199530/stomp#comments (it got changed in BFA but in Legion u casted dire beast for it to proc)

**What is happening:**

When you summon dire beast nothing is happening.

**What should happen:**

When you summon dire beast they should instantly stomp(simillar to thunderclap) and deal aoe damage to all enemies near them.

**Comment by ShikoSCS** [comment]
Fixed
