### ISSUE TITLE
Codex of Command

### ISSUE THREAD

**Issue by Skullbasha** [GuabinaCore/WoWKoi#2110]
**Links:**
https://www.wowhead.com/quest=42890/the-codex-of-command
from WoWHead or our Armory

**What is happening:**

The NPC we kill doesnt drop the quest item,Codex of command

**What should happen:**
HE should drop it and also it seems that the npc we save doesnt interact maybe cause i didnt recieve the q item

**Comment by Cefiro-Caecias** [comment]
There is no bug present. If you were in a party doing the quest, then it won't drop you. The quest must be done alone.
