### ISSUE TITLE
Legion Leatherworker "Over Your Head"

### ISSUE THREAD

**Issue by j-9000** [GuabinaCore/WoWKoi#2114]
**Links:**
https://www.wowhead.com/quest=40183/over-your-head
https://www.wowhead.com/spell=196428/rough-warhide-mask

from WoWHead or our Armory

**What is happening:**
unable to get legion leatherworking as the npc is not giving you the recipe to craft the rough war hide mask you need to make to complete quest

**What should happen:**
she should teach you how to make Shaved Stonehide Pelt, Tanned Stonehide Leather,  Stonehide Leather Strip and  Stonehide Leather Lining to make the Rough Warhide Mask

**Comment by j-9000** [comment]
was unable to get anyone else to confirm glitch, but i have given up and tried the quest multiple times to no avail

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
