### ISSUE TITLE
[Tyce] - Falling into the void won't let you release the spirit.

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2115]
**Links:**

https://imgur.com/a/E8ckwM5

**What is happening:**

Falling into the void won't let you release the spirit.

EDIT: Places I wasn't able to release were ICC(dropping off of the Arthas arena and Firelands)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
In which area? I don't recognize the place o.O

**Comment by ventarius5** [comment]
Places I wasn't able to release were ICC(dropping off of the Arthas arena and Firelands)

**Comment by Cefiro-Caecias** [comment]
@ShikoSCS, creo que esto es un efecto colatreral de haber reemplazado la tabla de cementerios.

**Comment by Nephilimkoi** [comment]
Creo que pasa en cualquier parte cuando te caes del mapa.
