### ISSUE TITLE
El principe nocheeterna

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2118]
Link
https://es.wowhead.com/quest=37861/el-príncipe-nocheterna

Lo que está sucede:
Al tomar la mision me indica que mate a Ael'Yith, voy hacia donde la misión me marca como objetivo, encuentro a Ael'Yith le estoy matando, pero el npc cambia de modo hostil a aliado, el Npc que debo matar esta como aliado, lo cual es imposible completar la misión, si no se puede golpear al npc.
intente relogear y tomar la misión de nuevo, incluso borre la carpeta cache por si hubo algun error, pero el npc de la misión ya no vuelve ser hostil, aparece como aliado lo cual no puedo matar para completar la mision

Lo qué debería pasar:
Después de encontrar a Ael'Yith, el objetivo de la misión debería poder  matarlo y completar la mision..
ubicación de Ael'Yith (https://es.wowhead.com/npc=90267/aelyith)
Hay un video de YouTube de esta misión https://www.youtube.com/watch?v=7zcx9NNbLag

![WoWScrnShot_032121_212353](https://user-images.githubusercontent.com/81131460/111936576-021a4100-8a94-11eb-8a87-9325f0bc7f4e.jpg)

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update ;)
