### ISSUE TITLE
The school or roguery(and all similar quests for other classes)

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2119]
**Links:**
https://www.wowhead.com/quest=43013/the-school-of-roguery#videos:id=101275
from WoWHead or our Armory

**What is happening:**
when u take quest and head to an npc to recruit troops u have to wait 30 mins to recruit them from trainer npc.

**What should happen:**
when u 1st time come to training npc, recruiting shud last like 7 seconds instead of 30 mins. YT video link : https://www.youtube.com/watch?v=uGmb0Hcjef0&t=44s.
P.S. same goes for every class hall, not only rogue, obviously

**Comment by Cefiro-Caecias** [comment]
This will be repaired as we rebuild the Halls. Patience ;)
