### ISSUE TITLE
Elana

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2120]
**Links:**
https://www.wowhead.com/npc=112575/elana#english-comments
from WoWHead or our Armory
this npc stands in priest class hall 
**What is happening:**

she does not apply "body and soul" buff to a player when player comes by

**What should happen:**
she should apply "body and soul" buff to a player when player comes by
"body and soul" buff link : https://www.wowhead.com/spell=224098/body-and-soul

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
