### ISSUE TITLE
[Tyce] - Vault of the Wardens (mythic)

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2121]
**Links:**
https://www.wowhead.com/vault-of-the-wardens
from WoWHead or our Armory

**What is happening:**
so, lets go step by step.
1st boss. Tirathon. 
we encountered vengeance form and what ive seen is that Fel chains(https://www.wowhead.com/spell=202826/fel-chain) ability is missing. 
3rd boss(Ash'golm). 
countermeasures do not exist at the beginning, they randomly appeared after ~30 seconds after fight started. 
4th boss(Glazer). 
it spawns only 1 Pulse(https://www.wowhead.com/spell=214893/pulse). also, during focus(https://www.wowhead.com/spell=194289/focused), only 3 lenses spawned. and no overloaded lens at all. 
5th boss. Cordana
1st issue: during Shadowstep(https://www.wowhead.com/spell=197823/shadowstep) there is no Avatar of the shadow.  https://www.wowhead.com/npc=104293/avatar-of-shadow. 
2nd issue: Creeping doom spawns only 2 walls of spirits. https://www.wowhead.com/spell=197422/creeping-doom.
**What should happen:**
Tirathon : during Vengeance form Fel Chain ability should exist(https://www.wowhead.com/spell=202826/fel-chain).
Ash'golm: countermeasures should exist from the beginning
Glazer: there should be more Pulses spawned(3), more lenses spawned(5) and 1 overloaded lens(https://www.wowhead.com/npc=113552/overloaded-lens)
Cordana: Avatar of the shadow shud be spawned during Shadowstep and steal the light from its wielder. also there should be 4 walls of spirits spawned each 8 seconds

also some mobs. 
Spirit of vengeance(https://www.wowhead.com/npc=100364/spirit-of-vengeance) doesnt cast a single ability.
barbed spiderling(https://www.wowhead.com/npc=97677/barbed-spiderling#abilities;mode:m) doesnt cast a single ability.
Aranasi Broodmother(https://www.wowhead.com/npc=97678/aranasi-broodmother) doesnt cast Pull(https://www.wowhead.com/spell=193997/pull) ability.

**Comment by OnlyWATCH** [comment]
4th boss(Glazer).  , 

in the [Focus] phase , [Focused] not spawning ( fake lens ) , and If you don't complete this phase in time, the boss is getting bugged ( not clicking to lens)

@Sefrenia-Caecias

**Comment by OnlyWATCH** [comment]
in the [Creeping Doom] phse , if u can stay to stairs walls not touching to u and boss not reseting , Storm is missing 

![image](https://user-images.githubusercontent.com/82822767/116787838-231c7b80-aaaf-11eb-89dd-938fa6602c33.png)

https://youtu.be/q6ibiep6rtg?t=1799

in the video u can saw storm to stairs

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
