### ISSUE TITLE
Felbound Enforcer

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2122]
**Links:**

https://www.wowhead.com/npc=104278/felbound-enforcer
**What is happening:**
she doesnt cast her ability Fel detonation(https://www.wowhead.com/spell=211464/fel-detonation).
also one of 3 enforcers doesnt call miniboss from 2nd boss. we had to deal with boss + 1 miniboss.

**What should happen:**
she should cast Fel detonation. also every enforcer should call for miniboss upon its death.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
