### ISSUE TITLE
[Arthas] - Una audiencia real

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2123]
Links:
https://es.wowhead.com/quest=42978/una-audiencia-real
from WoWHead or our Armory

Lo que esta sucediendo:
la misión se auto-completa, la misión me envía a ventormenta para entregar la misión al Rey Anduin, pero el NPC rey Anduin no me reconoce la misión, no hay signo de misión sobre el NPC

Lo que debería suceder:
una vez tenga la misión, en ventormenta al NPC Rey Anduin debería recibir la misión
 y darme la recompensa de dicha misión y posteriormente darme la otra misión siguiente:
 https://es.wowhead.com/quest=42982/el-botín-de-los-vencedores
![imagen_2021-03-22_123143](https://user-images.githubusercontent.com/81131460/112032598-90310e80-8b0a-11eb-8eb8-095bd8df522e.png)

**Comment by Cefiro-Caecias** [comment]
@LKArthas, el Anduin que recibe esta quest y otorga la siguiente, no está puesto en Ventormenta. Asumo que pertenece a una fase posterior y, como vos te estás encargando del faseo de Ventormenta, lo dejo en tus manos para que lo calibres ^^

**Comment by ShikoSCS** [comment]
Corregido, pero necesita una mejor calibración @LKArthas
