### ISSUE TITLE
scattered memories

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2125]
**Links:**
https://www.wowhead.com/quest=40326/scattered-memories
from WoWHead or our Armory

**What is happening:**
1st. there are no Kel'Danath notes around at all, except one, that starts quest, only  way to complete is to click it 6 times(becomes clickable again within a minute or smth).
2nd. upon completing the quest the point at the map that shows a place to turn in the quest is incorrect. a player that have never done this quest before wont find right place for sure. 

**What should happen:**
notes should be spawned around the quest area. completition point shud be replaced and set correct.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
