### ISSUE TITLE
La batalla por La Costa Abrupta

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2126]
Links:
https://es.wowhead.com/quest=42740/la-batalla-por-costa-abrupta
from WoWHead or our Armory

Lo que sucede:
Al tomar la misión, se auto-completa y solo se tiene que entregar en el barco aereo al NPC Genn Cringris  para terminar la misión
la misión omite muchas cosas y no aparezco tele-transportado en la barco aéreo para entregar la mision..

Lo que debería suceder:
Al tomar la misión, debería subir al barco y encontrarme con el NPC capitana Angelica y hacer click en el dialogo de dicho NPC, lo cual al se presenta una cinemática del juego, donde viajamos a la Costa Quebrada y tenemos que completar una gesta y al termino se presenta una cinemática.. al terminar aparezco teletransportado en un barco aéreo donde entrego la misión al NPC Genn Cringris.
Aquí dejo un link de Youtube de la mision: https://www.youtube.com/watch?v=mdV3xuliUs8&t=30s

**Comment by Cefiro-Caecias** [comment]
Arthas se encuentra actualmente reconstruyendo esta quest completa. Paciencia, estará lista en un par de semanas ;)
