### ISSUE TITLE
the masks we wear

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2127]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=41834/the-masks-we-wear
**What is happening:**

basicall u can get all 8\8 credit by clicking the same npc over and over again.

**What should happen:**
every single npc shud grant 1 credit upon clicking

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
