### ISSUE TITLE
arcane communion

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2128]
**Links:**
https://www.wowhead.com/quest=40324/arcane-communion
from WoWHead or our Armory

**What is happening:**
a player doesnt lose 300 ancient mana after feeding Theryn

**What should happen:**
a player should lose 300 ancient mana after feeding Theryn.
https://www.youtube.com/watch?v=a0W_SaJh7Ug&t=1s

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
