### ISSUE TITLE
[Tyce] - GCD issue #1

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2129]
**Links:**

from WoWHead or our Armory

**What is happening:**
so basically GCD itself is broken which leads to multiple errors during combat. this especially can affect classes and spec that rely on haste very hard. and ofc, during bloodlust\tw\other similar buffs. so whats going on. if a person clicks few times the same ability after casting an instant ability such as Renew or Ice Lance or Shadow Word:Pain(it doesnt matter, it goes same for all instant abilities), basically server records that ability was used before it went out of GCD. this causes overlapping abilities. u can see it by just clicking Renew on yourself 7 times in a row. if the haste rating is high enough this may cause some spec to lose shitton of burst damage due to overlapping. basically, during bloodlust a person presses abilities very often in order to maximize the dps. but with this issue this will instead lead to dps loss cuz server will not record correctly the abilites used by a person. it can be seen very clear on the following video. 
https://youtu.be/fBkiHC7MQKI

**What should happen:**
instant abilities should be recorded by server ONLY when they go off the GCD

**Comment by ShikoSCS** [comment]
Fixed
