### ISSUE TITLE
[Arthas/Sefrenia] - Quest A Family Divided

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#213]
**Links:**
https://www.wowhead.com/quest=24543/a-family-divided

**What is happening:**
quest is starting from npc Naralex 

**What should happen:**
npc should start from npc Tawane

**Comment by DeltaVortex** [comment]
Also, quest should appear right after finishing quest Bad to Worse: https://www.wowhead.com/quest=24529/bad-to-worse
and not after w/e it is rn.

**Comment by Cefiro-Caecias** [comment]
Indeed. We have deliberately calibrated it like this, so as not to break the quest chain, taking distracted players into account.
