### ISSUE TITLE
Ayudar a nuestros aliados

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2132]
Links:
https://es.wowhead.com/quest=42436/ayudar-a-nuestros-aliados
from WoWHead or our Armory

Lo que sucede:
al tomar la mision nos indica que debemos ir ayudar al  NPC Meliah Plumagrís con 100 suministros, nos dan 3 sub-misiones para poder recolectar suministros, el problema es que solo dar click  (abrir y cerrar el dialogo) del NPC nos cuenta como objetivo 1 suministro, y solo con clickear (abrir y cerrar dialogo) en el NPC varias veces logras completar la misión.

Lo que debería suceder:
Al tomar la misión debemos ir donde se encuentra el El NPC Meliah Plumagrís, y deberíamos completar las misiones de 100 suministros, realizando las 3 sub-misiones que nos da dicho NPC .
Aquí dejo un link de Youtube de la mision: https://www.youtube.com/watch?v=MIM3SIa_bkc

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
