### ISSUE TITLE
NPC Calydus [misiones de clase: Brujo afliccion] 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2133]
Links:

misiones que faltan
https://es.wowhead.com/quest=40731/el-corazón-de-cicatriz-del-terror
https://es.wowhead.com/quest=40823/reconstruir-el-consejo

Lo que sucede:
el NPC Calydus no da las misiones siguientes:
-mirando en la oscuridad
-el corazón de cicatriz del terror
-reconstruir el consejo
al terminar la gesta que da el arma artefacto. me dan la misiones https://es.wowhead.com/quest=40712/el-poder-poseído
despues de entregar esa mision, recien deberian darme las misiones https://es.wowhead.com/quest=40731/el-corazón-de-cicatriz-del-terror
https://es.wowhead.com/quest=40823/reconstruir-el-consejo
como ven en la imagen , se omitieron esas dos misiones y me pasaron a dar la mision del segundo arma artefacto, sin ir a la sede.. y la sede esta abierta lo cual no deberia estarlo, porque faltan estas dos misiones para desbloquear la sede.
![image](https://user-images.githubusercontent.com/81131460/113242620-035b2300-9277-11eb-821b-416c320bd21d.png)
este portal que lleva  ala sede debería no estar activo aun...
![image](https://user-images.githubusercontent.com/81131460/113243823-56ce7080-9279-11eb-9ac1-51696dd93cd8.png)

Lo que debería suceder:
una vez terminada esta mision
https://es.wowhead.com/quest=40712/el-poder-poseído
recien deberian darme las misiones
https://es.wowhead.com/quest=40731/el-corazón-de-cicatriz-del-terror
https://es.wowhead.com/quest=40823/reconstruir-el-consejo
para poder ir a la sede, una ves esté en la sede, recién debería darme las misiones para  segunda arma artefacto y no antes
Dato importante:
NPC Calydus
https://es.wowhead.com/npc=106610/calydus
mision anterior (funcional)
https://es.wowhead.com/quest=40712/el-poder-poseído

**Comment by Cefiro-Caecias** [comment]
Pendiente de reconstrucción. Paciencia ;)

**Comment by Noahkrr** [comment]
sigo teniendo problemas con estas misiones, ya me dieron la primera mision, solo que es hay un conflicto estas misiones con la sede ya disponible, cuando hago la primera mision me envia a una gesta, entro camino unos pasos en la gesta y me teletransporta a la sede, y se me hace imposible hacer la gesta con la sede disponible, se supone que estas misiones al culminar recien abren la sede de Brujo... por si acaso intentare hacer estas misiones con otro pj
