### ISSUE TITLE
[Tyce] - Halls of Valor (mythic)

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2134]
**Links:**

**What is happening:**
BOSSES
1. Hymdall
he spawns only one storm drake after using horn of valor (https://www.wowhead.com/spell=191284/horn-of-valor#used-by-npc)
2. Odyn
if a player dies, he dies and can be ressed.
3. Fenryr
it seems like he has too short evade border, a player with Scent of Blood can easily evade boss.

MOBS
1. Stormforged Sentinel(https://www.wowhead.com/npc=96574/stormforged-sentinel). he doesnt cast anything, but shield. 
2. Valarjar Mystic(https://www.wowhead.com/npc=95834/valarjar-mystic). he casts spells, but it takes too much time for him to cast smth, usually he gets killed before he casts any of his spells, so i can count that as "he doesnt cast anything".

**What should happen:**

1. Hymdall should spawn two Storm drakes while using Horn of Valor
2. Odyn. when a player dies during Odyn encounter, he gets placed upon balcony and can see the fight from there, but cant move or cast anything. cant be resurrected too.
3. Fenryr should have a bit larger evade borders.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
