### ISSUE TITLE
Risen Archer(BRH mythic)

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2135]
**Links:**
https://www.wowhead.com/npc=98275/risen-archer#abilities;mode:normal
https://www.wowhead.com/spell=200345/arrow-barrage
from WoWHead or our Armory

**What is happening:**
mob doesnt cast Arrow Barrage, or, in fact, it does, but deals no dmg and no animation. 

**What should happen:**
should cast Arrow Barrage.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
