### ISSUE TITLE
Un edicto real [Mision de inicio hacia Tormenheim]

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2137]
Links:
https://es.wowhead.com/quest=38035/un-edicto-real
from WoWHead or our Armory

Lo que sucede:
Al tomar la mision del NPC Almirante del cielo Rogers en Dalaran, esta mision nos da como objeto Citacion Real, al leerla aparece un dialogo del Rey Anduin y al terminar de leer, la mision cambia a el Abrasacielo Abordado .. voy al portal  y me teletransporto al Abrasacielo en ventormenta voy donde esta el NPC Almirante del cielo Rogers y la mision no se completa..

Lo que debería suceder:
Al tomar la misión del NPC Almirante del cielo Rogers en Dalaran, esta misión nos da como objeto Citación Real, al leerla aparece un dialogo del Rey Anduin y al terminar de leer, El NPC Almirante cielo Rogers, debería dialogar conmigo y la misión cambia a el Abrasacielo Abordado .. EL NPC Almirante del cielo Rogers caminaría hacia el portal y se teletransportaria y yo voy al portal  y me teletransporto al Abrasacielo en ventormenta, yo voy donde esta el NPC Almirante del cielo Rogers y la misión estaria completa y podría entregarla .
Aqui dejo el link de Youtube de la mision: https://www.youtube.com/watch?v=U3X3uXXwch8

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update. No olvides borrar Cache, abandonar la misión, y volverla a tomar.
