### ISSUE TITLE
[Arthas/Sefrenia] - Quest Meet the New Boss

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#214]
**Links:**
https://www.wowhead.com/quest=24551/meet-the-new-boss

**What is happening:**
Quest can be started from both npc Warlord Bloodhilt and Tatternack Steelforge

**What should happen:**
Quest should only be started from npc Tatternack Steelforge

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
