### ISSUE TITLE
[Tyce] - Grand Challenger's Bounty

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#2142]
**Links:**
https://wowpedia.fandom.com/wiki/Grand_Challenger%27s_Bounty

from WoWHead or our Armory

**What is happening:**

Currently the chest doesnt give you any reward from the mytic + runs you do during the week.
it only says that you have already claimed the reward

**What should happen:**

Should give you AP, some Mytic grade piece of gear related to the hightest ilvl you got during the runs in the week.
Should have the chance to give you a legendary or otherwise increase your odds.

![WoWScrnShot_032421_190936](https://user-images.githubusercontent.com/73371905/112395959-bc4cbb00-8cd5-11eb-9fab-c50bd9b5e105.jpg)
![WoWScrnShot_032421_191422](https://user-images.githubusercontent.com/73371905/112395964-bf47ab80-8cd5-11eb-9b7d-e6a8f0ee18f6.jpg)

**Comment by menelys** [comment]
raid lock seems to expire at friday. at least its what raid info says. so maybe need to w8 till friday and see if its gonna work or not.

**Comment by Nephilimkoi** [comment]
![image](https://user-images.githubusercontent.com/73371905/112399196-32ecb700-8cdc-11eb-9420-9cf2a1dab413.png)
it says wednesday to me

**Comment by Nephilimkoi** [comment]
**Bounty Chest Reseted on Friday at 11:59 Pm SVT**

so.. yes. it works properly :D
