### ISSUE TITLE
The hidden city

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2143]
**Links:**
https://www.wowhead.com/quest=42228/the-hidden-city

**What is happening:**
quest doesnt work correctly. in fact u can get the quest credit out of first meeting with Orathiss by simply kiling him. but u still have to go deeper to turn in. 

**What should happen:**
a player should confront Orathiss 3 times. 2 times Orathiss will run away and player has to follow him to finish it. on the 3rd time player kills Orathiss and turns in quest to the Ancient seed near him.

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later on.
