### ISSUE TITLE
[Tyce] - Fallo en cinemática: Quest The Valewalker's Burden

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2144]
**Links:**
https://www.wowhead.com/quest=42230/the-valewalkers-burden
from WoWHead or our Armory

**What is happening:**

the quest itself is kinda fine, but the cinematic is incorrect(nothing actually happens during it) and after cinematic i got black screen without any ability to do anything. i had to alt f4 and then game forced me to trip a bit from shal'aran to dalaran and then from dalaran to stormheim on a fly route. and again i had no possibilty to do smth ecxept waiting on when its gonna end.

**What should happen:**

**Comment by menelys** [comment]
in fact, after that every time i log on it keeps me forcing on a trip that takes like 7 minutes.

**Comment by Nephilimkoi** [comment]
i was thinking and now that i remember i downloaded leatrix plus. an addon for the ability to skip cinematics because the black screen during a cinematic used to happen to me a lot. and would keep me stuck like that

**Comment by Cefiro-Caecias** [comment]
@ShikoSCS, otro fallo de cinematica como pasó con el Warrior.
