### ISSUE TITLE
[Artifact Quest] - Windwalker Monk - Into the Heavens.

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2148]
**Links:**
https://www.wowhead.com/quest=40570/into-the-heavens

**What is happening:**
After the quest item teleports the character in Skywall, you are supposed to slay several minions to obtain, at the end, the artifact, but the last one that should appear, Zaurac (a dragon), doesn't spawn. Also, going away from the dungeon (ie. Hearthstone, Zen Pilgrimage) will allow you to complete the quest without you having obtained the Artifact.

**What should happen:**
The Dragon Zaurac should spawn as the last minion to slay, and after that you can ride him to reach Typhinius. Defeating Typhinius would result in you obtaining the Artifact.

UPDATE: it seems that the whole Artifact system for Monks is bugged, as I can't even take the quest for Brewmaster Artifact.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
