### ISSUE TITLE
[Misc - Quest] - Priestly Matter

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2149]
**What is happening:**
Just a little error in the text of the NPC's speech. Some spaces between words missing at the end, a letter missing, some punctuation not correct.

**What should happen:**
The last phrase should be: "Are you, Blood Elf, ready for the test?" Or something along that. (not a native English sorry if i made mistakes)

![WoWScrnShot_032521_155359](https://user-images.githubusercontent.com/64436148/112493530-89accc00-8d82-11eb-9454-1a1f5055ade6.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
