### ISSUE TITLE
Time Flies When Yer Havin' Rum!

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2150]
**Links:**

https://www.wowhead.com/quest=44117/time-flies-when-yer-havin-rum

**What is happening:**

the quest itself is fine, but those ropes at the ships, they do nothing when u click on them.

**What should happen:**
when u click a rope u should be placed on a ship. there are bottles to collect.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
