### ISSUE TITLE
[Quest] - The Corruptor

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2151]
**Links:**
https://www.wowhead.com/quest=39384/the-corruptor

**What is happening:**
Can't turn in the quest and can't open the cage.

**What should happen:**
You should be able to complete the quest and interact with the cage to free her.

Repost of #1719 as it seems like the fix didn't work.

**Comment by Cefiro-Caecias** [comment]
I just tried the quest, and the next quest, and they work fine. Clear Cache and try again.
