### ISSUE TITLE
rogue class hall doors

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2152]
**Links:**

**What is happening:**
when u try to open a door to the chamber of shadows while being in stealth, nothing happens. it only opens when u do it unstealthed. same also goes for a door in the hidden coridor, if u try  to open it from inside. 
![image](https://user-images.githubusercontent.com/77908571/112510872-8ae9f300-8d9a-11eb-94ad-cb205158c4b8.png)

**What should happen:**
doors should be opened upon clicking on torch or lever no matter if a player is stealthed or unstealthed

**Comment by Cefiro-Caecias** [comment]
There is no bug present. You can only interact stealthily with doors that are under the "locked" condition.
