### ISSUE TITLE
[Quest] - Solid as a Rock

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2153]
**Links:**
https://www.wowhead.com/quest=38235/solid-as-a-rock

**What is happening:**
The NPCs that I sould help to do the quest as they spawn they go under the terrain, making the quest impossible to do.

**What should happen:**
As they spawn they should not go under terrain.

![WoWScrnShot_032521_175151](https://user-images.githubusercontent.com/64436148/112511834-152e5900-8d93-11eb-9465-2db1c70cc9ed.jpg)

**Comment by Dinarte-Moscon** [comment]
Out of Range
![image](https://user-images.githubusercontent.com/82131217/113961035-cd301d00-97fb-11eb-8f25-12e79d0935a8.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
