### ISSUE TITLE
Recuerdos dispersos (Mision de Suramar)

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2154]
Links:
https://es.wowhead.com/quest=40326/recuerdos-dispersos
from WoWHead or our Armory

Lo que sucede:
Al tomar la misiones pide como objetivos, encontrar 6 notas, busque las notas y encontré todas
el problema es para entregar la misión, el mapa me indica en el lugar erróneo por que el NPC (Objeto) que debo entregar esta otro lugar..

Lo que debería suceder:
Al tomar la misión, pide como objetivo encontrar 6 notas, al completar la misión. el mapa debería reflejar el lugar exacto donde se encuentra el NPC (Objeto) para entregar la misión
ubicación del NPC (Objeto):
https://es.wowhead.com/object=247694/morral-de-keldanath

Link de youtube de la mision: https://www.youtube.com/watch?v=hQIEtYAUj6Q

como ven en la imagen donde esta el cursor de mi ubicación en el mapa, debería marcar la misión de entrega.
![imagen_2021-03-25_170836](https://user-images.githubusercontent.com/81131460/112550054-bf56b280-8d8c-11eb-80e4-ed91ecd68bdc.png)

**Comment by Cefiro-Caecias** [comment]
Reparada. No olvides borrar Cache, o no te tomará los cambios nuevos de las reparaciones.
