### ISSUE TITLE
[Quest] - Lord of the Spire

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2156]
**Links:**
https://www.wowhead.com/quest=47993/lord-of-the-spire

**What is happening:**
Can't get on the Lightforged Warframe to fight Nath'raxas. Also if you abandon the quest, instead of being given by High Exarch Turalyon at Destiny Point, you have to walk almost to Nath'raxas area to get the pop up of the quest.

**What should happen:**
Lightforged Warframe should be usable and the quest should be given by High Exarch Turalyon at Destiny Point.

**Comment by Cefiro-Caecias** [comment]
Partially repaired. I'll see about the warframe when I go over the area.
