### ISSUE TITLE
Sangre de mi sangre (Misión Suramar)

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2157]
Links:
https://es.wowhead.com/quest=41989/sangre-de-mi-sangre
from WoWHead or our Armory

Lo que sucede:
Al tomar la misión, nos pide como objetivos: inspeccionar el Monumento de Lunastre y derrotar a Anarys Lunastre.
el segundo objetivo de derrotar a Anarys Lunastre, no puede completar porque no aparece el NPC.
NPC que no aparece: https://es.wowhead.com/npc=106418/anarys-lunastre
ya logre completarlo, en la tercer vez. Anarys no apareceo al inspeccionar otro npc aparecio y al matarlo por 3ra vez recien aparece Anarys como aliado y puede llevarlo con Ly'leth y completar la mision..
Lo que debería suceder:
Al tomar la misión, se realiza los objetivos de inspeccionar el Monumento de Lunastre, una vez inspeccionado, debería aparecer Anarys para poder derrotarlo y entregarlo con Ly'leth Lunastre para entregar la misión.

link de youtube de la mision: https://www.youtube.com/watch?v=_8Mbvb0tUuc&t=100s

**Comment by Cefiro-Caecias** [comment]
Reparada, y blizzlike. Para ser una quest insignificante, tenía muchísimas complicaciones técnicas que me sacaron canas verdes. Disponible en el próximo update.
