### ISSUE TITLE
Primer contacto (mision de Suramar)

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2158]
Links:
https://es.wowhead.com/quest=42147/primer-contacto
from WoWHead or our Armory

Objetivo de la mision:
Hablar con Vanthir

Lo que sucede:
Al tomar la mision buscamos a Vanthir debemos hablar con él, se completa el objetivo. pero no la misión. si voy a Sha'Aran encontramos que la misión, se puede entregar pero en le mapa no aparece la misión para entregar. bug visual?

Lo que debería suceder:
Al tomar la misión, vamos ubicamos a Vanthir y conversamos con él, se debería completar la misión y podríamos entregar la misión con la Primera arcanista Thalyssra en Shal'Aran.
![image](https://user-images.githubusercontent.com/81131460/112560762-dbb11a00-8da1-11eb-815a-40a794349455.png)

**Comment by Cefiro-Caecias** [comment]
Reparada. Disponible en el próximo update.
