### ISSUE TITLE
Lady Lunastre (Misión de Suramar)

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2159]
Links:
https://es.wowhead.com/quest=41877/lady-lunastre
from WoWHead or our Armory

Objetivo de la misión:
Buscar a Ly'leth

Lo que sucede:
al tomar la misión, en el mapa no aparece el objetivo de la misión..

Lo que debería suceder:
al tomar la misión, debería aparecer la ubicación del objetivo de la misión
ubicación del NCP ly'leth para esta mision son las coordenadas 47.0 61.8
https://es.wowhead.com/npc=107632/lyleth-lunastre

como ven el mapa no aparecen el objetivo y la misión.
![image](https://user-images.githubusercontent.com/81131460/112563434-5466a500-8da7-11eb-9ac0-a9e3bff4492d.png)

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
