### ISSUE TITLE
Ofrecer compasión (Mision de Suramar)

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2160]
Links:
https://es.wowhead.com/quest=41148/ofrecer-compasión
from WoWHead or our Armory

Objetivo de la misión:
revivir 4 ciudadanos
objeto que permite reanimar a los ciudadanos es:
https://es.wowhead.com/item=138308/frasco-de-vino-de-maná
ubicación del npc para entregar la misión, coordenadas de Vanthir 48.4 83.4
https://es.wowhead.com/npc=107598/vanthir

Lo que sucede:
al tomar la misión tengo q ubicar a los 4 ciudadanos le di vino, se completo el objetivo pero no me reconoce la misión.. no se completar

Lo que debería suceder:
Al ubicar a cada uno los 4 ciudadanos, debo revivirlos con el vino y con eso se completa el objetivo de la misión.
Link de youtube de la misión: https://www.youtube.com/watch?v=vn6qGj1u5H8

![image](https://user-images.githubusercontent.com/81131460/112566111-5f700400-8dac-11eb-8770-ad78529bd07b.png)

**Comment by Cefiro-Caecias** [comment]
Reparado hace tiempo. No olvides borrar Cache.
