### ISSUE TITLE
Guardian Thor'el (NCP duplicado)

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2161]
Links:
https://es.wowhead.com/npc=110944/guardián-thorel
from WoWHead or our Armory

lo que sucede:
El NPC esta duplicado, hay dos NPC Guardian Thor'el

Lo que debería suceder:
debería haber un Guardian Thor'el

![image](https://user-images.githubusercontent.com/81131460/112567780-6c422700-8daf-11eb-9a09-eb4a72405d59.png)

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
