### ISSUE TITLE
Quest: Warlock : An eye for a scepter

### ISSUE THREAD

**Issue by SirShmo** [GuabinaCore/WoWKoi#2162]
https://www.wowhead.com/quest=43153/an-eye-for-a-scepter

from WoWHead or our Armory

**What is happening:**
This quest series has issues in several locations.
1. Taking the portal from Dalaran sends the player falling into the crater.
2. The ruins of cell block D can be entered without triggering the npcs.
3. Following and killing Nagaz does not always trigger the next step.
4. Nagaz does not fight back once engaged.
5. If you manage to kill Nagaz, Allaris is unresponsive.

**What should happen:**
![EYEfaS1](https://user-images.githubusercontent.com/53211124/112572449-68aaa200-8da7-11eb-970f-ec5503c7271f.png)
![EYEfaS2](https://user-images.githubusercontent.com/53211124/112572463-6fd1b000-8da7-11eb-9aa1-9a2f25de7622.png)
![EYEfaS3](https://user-images.githubusercontent.com/53211124/112572494-7eb86280-8da7-11eb-8447-35579a9eef3c.png)
![EYEfaS4](https://user-images.githubusercontent.com/53211124/112572510-86780700-8da7-11eb-8bb6-9da0e5a819cd.png)

**Comment by Cefiro-Caecias** [comment]
Reconstruction pending. Patience ;)
