### ISSUE TITLE
Enhancement Shaman Artifact

### ISSUE THREAD

**Issue by Torgaun** [GuabinaCore/WoWKoi#2163]
The Final Stage where you need to help Stormcaller Mylra she is nowhere to be found, this is the 2nd time I have tried this quest.
![image_2021-03-26_033712](https://user-images.githubusercontent.com/57377101/112598160-8e09d100-8de4-11eb-8208-e608e12ef648.png)

**Comment by Cefiro-Caecias** [comment]
Reconstruction pending. Patience ;)
