### ISSUE TITLE
[Tyce] - Upgrading Class Armor Set - Class Hall

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#2164]
**Links:**
https://www.wowhead.com/npc=100196/eadric-the-pure
https://www.wowhead.com/item=140974/highlords-lesser-armor-kit?bonus=0
https://www.wowhead.com/item=140941/highlords-armor-kit?bonus=0
https://www.wowhead.com/item=140975/highlords-greater-armor-kit?bonus=0
https://www.wowhead.com/transmog-set=2120/battleplate-of-the-silver-hand
from WoWHead or our Armory

**What is happening:**
Currently when you try to apply an Armor kit it only says invalid target.

**i think this apply to every class.**

![WoWScrnShot_032621_124937](https://user-images.githubusercontent.com/73371905/112666696-d2bc5900-8e32-11eb-9cde-2d811b27b1d4.jpg)

![WoWScrnShot_032621_124940](https://user-images.githubusercontent.com/73371905/112666679-ce903b80-8e32-11eb-9cbc-495327b9985a.jpg)

**What should happen:**
Should Upgrade the ilvl of your armor

**Comment by Arkanheal** [comment]
Might be linked to #3271
