### ISSUE TITLE
Engineering : Item : Twirling Bottom Repeater

### ISSUE THREAD

**Issue by SirShmo** [GuabinaCore/WoWKoi#2167]
**Links:**
https://www.wowhead.com/item=136630/twirling-bottom-repeater

from WoWHead or our Armory

**What is happening:**
A bought item from Hobart Grapplehammer , the twirling bottom repeater is missing from purchase list. Player is therefore unable to craft up to 4 items. (see image).
This item is also not available from Fargo Flintlock (per Wowhead).
Successor items are therefor also not available as you need base item to upgrade.
![Twirling](https://user-images.githubusercontent.com/53211124/112732240-09a77300-8ef6-11eb-91fc-684be0bccdab.png)

**What should happen:**
Player requires some access from the stated, or other sources to create said item.

**Comment by Cefiro-Caecias** [comment]
There is no bug present. In fact, both sellers own said item for sale. In the upper right part of the sale tab, where the filters are located, activate the "All" option, and then it will show you all your items for sale, and not only those filtered for your Class ;)
