### ISSUE TITLE
GENERAL BUGS OF STORMHEIM - WORLD QUEST - NPC - ARCHIEVEMENTS - ITEMS - OTHERS

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#2168]
**GONNA BE BREAKED DOWN IN SEVERAL COMMENTS**

**Links**
https://www.wowhead.com/quests/type:109?filter=35;7;0#0+1+12;q=stormheim

https://www.wowhead.com/achievement=11263/adventurer-of-stormheim ++

https://www.wowhead.com/achievement=11259/treasures-of-stormheim +++

++  All the rares spawn properly. but some might need to be worked on either for their abilities or dynamics. 
(need further testing and more feedback)

+++ Overall all the treasures spawn and give their loot. properly. but the same as with [Aszuna](https://github.com/GuabinaCore/WoWKoi/issues/1776)  they arent counting for the archievement.

**Comment by Nephilimkoi** [comment]
https://www.wowhead.com/npc=92415/storm-drake-whelp
https://es.wowhead.com/npc=92128/ratero-vilskorn


Are giving rep and are waaay too overtunned


![WoWScrnShot_032721_165555](https://user-images.githubusercontent.com/73371905/112734664-944f9880-8f1d-11eb-98a5-22035bca643a.jpg)
![WoWScrnShot_032721_165719](https://user-images.githubusercontent.com/73371905/112734667-96195c00-8f1d-11eb-911e-078a02b7b80c.jpg)
![WoWScrnShot_032721_170013](https://user-images.githubusercontent.com/73371905/112734739-f7412f80-8f1d-11eb-9439-caaa7d877511.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
