### ISSUE TITLE
[Tyce] - Unlocking World Quest In Alts

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#2169]
**Links:**
https://www.mmo-champion.com/threads/2097838-7-1-brings-account-wide-world-quests-for-alts
https://es.wowhead.com/world-quests-guide
https://wowpedia.fandom.com/wiki/Uniting_the_Isles_(alt)
https://www.wowhead.com/quest=43341/uniting-the-isles#comments

from WoWHead or our Armory

**What is happening:**

You should be able to directly go to Khadgar and get your world quest unlocked on your alts. but currently that isnt happening

**What should happen:**

> These World Quests can be completed by players under 110 and reward a hefty amount of experience. These World Quests unlock on alts if you already have a level 110 character.

> This version of the Uniting the Isles quest is automatically given by Archmage Khadgar when you reach level 110, provided you have already completed N [110] Uniting the Isles on another character. The main goal is to unlock World Quests.

> By irthinker (2,303 – 2·7·28) on 2016/10/25 (Patch 7.1.0) 
> As of 7.1, alts will not need to meet the reputation requirements provided their main has completed this quest.
> http://eu.battle.net/forums/en/wow/topic/17613734064

**the link doesnt work tho**

**Comment by Nephilimkoi** [comment]
![image](https://user-images.githubusercontent.com/73371905/112735921-4b034700-8f25-11eb-8ad6-f187cfde8a3b.png)



**Also russian text**

**Comment by Cefiro-Caecias** [comment]
Reparada la traducción.

**Comment by NightwindOI** [comment]
The translation may be fixed, but the quest is still not account bound, so u need to complete it with the alts.

**Comment by ShikoSCS** [comment]
Fixed
