### ISSUE TITLE
GENERAL BUGS OF HIGHMOUNTAIN - WORLD QUEST - NPC - ARCHIEVEMENTS - ITEMS - OTHERS 

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#2170]
Sephrenia's Comments:

1) https://www.wowhead.com/quest=39784/beastmaster-paolek: Fixed.
2) https://www.wowhead.com/quest=41013/darkbrul-arena: Fixed.
3) https://www.wowhead.com/npc=101077/sekhan: Fixed
4) https://www.wowhead.com/npc=94688/diseased-grub: Fixed.
5) https://www.wowhead.com/npc=98273/icefang-howler: Reprogrammed. When you kill the "Icefang Packleader", the "Icefang Howlers" will lose the "Strength of the Pack buff".
6) https://www.wowhead.com/npc=98038/fledgling-rockcrawler: Fixed.
7) https://www.wowhead.com/npc=95277/skywhisker-loyalist: Fixed.
8) https://www.wowhead.com/achievement=11257/treasures-of-highmountain: Fixed.

**Comment by Nephilimkoi** [comment]
https://www.wowhead.com/achievement=11264/adventurer-of-highmountain ++
https://www.wowhead.com/quest=39784/beastmaster-paolek

In the case of this rare.  everything works perfectly. but it doesnt count it

![WoWScrnShot_032721_181507](https://user-images.githubusercontent.com/73371905/112736381-99661500-8f28-11eb-99aa-8398893cd5f7.jpg)
![WoWScrnShot_032721_181514](https://user-images.githubusercontent.com/73371905/112736387-9cf99c00-8f28-11eb-98aa-9b50f35ad27e.jpg)
![WoWScrnShot_032721_181518](https://user-images.githubusercontent.com/73371905/112736391-a1be5000-8f28-11eb-97bb-30bdd71a2e8e.jpg)
![WoWScrnShot_032721_181502](https://user-images.githubusercontent.com/73371905/112736379-94a16100-8f28-11eb-8d10-83757e9c3c0c.jpg)

![WoWScrnShot_032721_181537](https://user-images.githubusercontent.com/73371905/112736373-8eab8000-8f28-11eb-9b3d-004967e41a50.jpg)

![WoWScrnShot_032721_181531](https://user-images.githubusercontent.com/73371905/112736368-8b17f900-8f28-11eb-9fc9-52c1f3323221.jpg)

![WoWScrnShot_032721_181524](https://user-images.githubusercontent.com/73371905/112736366-85baae80-8f28-11eb-9e73-abd491356fd0.jpg)

**Comment by Nephilimkoi** [comment]
https://www.wowhead.com/quests/type:109?filter=35;7;0#0+1+12;q=HIGHMOUNTAIN


https://www.wowhead.com/quest=45071/barrels-o-fun
https://www.wowhead.com/quest=40978/bears-behaving-badly
https://www.wowhead.com/quest=40951/bitestone-bazaar
https://www.wowhead.com/quest=40925/bitestone-burglary
https://www.wowhead.com/quest=41308/border-reinforcements
https://www.wowhead.com/quest=41310/border-reinforcements
https://www.wowhead.com/quest=41706/briny-waters
https://www.wowhead.com/quest=41623/champions-of-highmountain#comments
https://www.wowhead.com/quest=41622/crawliacs-legacy
https://www.wowhead.com/quest=41095/critical-crops#comments
https://www.wowhead.com/quest=43767/enigmatic
https://www.wowhead.com/quest=39424/everything
https://www.wowhead.com/quest=41701/gettin-tuffer
https://www.wowhead.com/quest=43764/ley-race
https://www.wowhead.com/quest=45048/like-the-wind
https://www.wowhead.com/quest=41122/mists-take-you
https://www.wowhead.com/quest=41078/munitions-testing
https://www.wowhead.com/quest=41057/primal-payback ++
https://www.wowhead.com/quest=40850/prisoners-of-greystone
https://www.wowhead.com/quest=41416/retake-the-skyhorn
https://www.wowhead.com/quest=41144/return-to-the-river
https://www.wowhead.com/quest=40985/rimescale-naga-incursion-highmountain
https://www.wowhead.com/quest=41691/sea-of-feathers
https://www.wowhead.com/quest=40920/stonebinder-bounty
https://www.wowhead.com/quest=42086/the-feltotem
https://www.wowhead.com/quest=43766/the-magic-of-flight
https://www.wowhead.com/quest=44823/thunder-totem-cleanup-detail ++
https://www.wowhead.com/quest=43455/wanted-devouring-darkness
https://www.wowhead.com/quest=41838/wanted-slumber +++
https://www.wowhead.com/quest=41145/water-of-life
https://www.wowhead.com/quest=41321/weapons-of-deathwing


None of these quest actually Pop up

++(I honestly dont remember ever seeing it on) (primal Payback and Thunder Totem Cleanup)
++(i do recall doing it. but it could be from a quest in the questline rather than actual WorldQuest)
+++ The Npc is there. just that there is no World Quest poping up

-------------------------------------------------------------------------------------------

https://www.wowhead.com/quest=41705/assault-on-thunder-totem

Pop up but nothing happen

**Comment by Nephilimkoi** [comment]
https://www.wowhead.com/quest=41013/darkbrul-arena

Pop up but nothing happen

**Comment by Nephilimkoi** [comment]
https://www.wowhead.com/quest=41013/darkbrul-arena#videos

The npc you need to talk with isnt there. and the mobs are already spawned.

sometimes when passing under bridges the mobs suddently go up to it


![WoWScrnShot_032721_185928](https://user-images.githubusercontent.com/73371905/112737342-47c18880-8f30-11eb-9dc7-abaa44085de0.j
![WoWScrnShot_032721_190100](https://user-images.githubusercontent.com/73371905/112737366-73dd0980-8f30-11eb-9d1e-44da8c401260.jpg)
pg)

**Comment by Kirrkoi** [comment]
Npc rare duplicado
https://es.wowhead.com/npc=101077/sekhan

**Comment by Nephilimkoi** [comment]
https://www.wowhead.com/npc=94688/diseased-grub

slighly overtuned. they do way too much dmg than they should

**Comment by Nephilimkoi** [comment]
https://www.wowhead.com/npc=98273/icefang-howler
slighly overtuned. they do way too much dmg than they should

![image](https://user-images.githubusercontent.com/73371905/112804074-f6092300-9041-11eb-8ac1-dde858c46e2a.png)

**Comment by Nephilimkoi** [comment]
https://www.wowhead.com/npc=98038/fledgling-rockcrawler
slighly overtuned. they do way too much dmg than they should

![image](https://user-images.githubusercontent.com/73371905/112886756-57f87580-90a0-11eb-82d3-d1b91d47af29.png)

**Comment by Nephilimkoi** [comment]
https://www.wowhead.com/npc=95277/skywhisker-loyalist.

slighly overtuned. they do way too much dmg than they should

**Comment by Cefiro-Caecias** [comment]
I was able to repair some things, and others are on hold. I leave my comments at the beginning of the post.
