### ISSUE TITLE
Engineering : Quest : Fire and Forget

### ISSUE THREAD

**Issue by SirShmo** [GuabinaCore/WoWKoi#2171]
**Links:**
https://www.wowhead.com/quest=40869/fire-and-forget
from WoWHead or our Armory

**What is happening:**
Player does not gain credit for healing on second round of "wounded guards" after calibrating gun.

![FireAForget](https://user-images.githubusercontent.com/53211124/112737807-6026a880-8f1a-11eb-9417-d69837625e86.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed, but due to technical limitations I had to deactivate secondary objectives. Available in the next update.
