### ISSUE TITLE
Imagen de Mirmiron (NPC de sede cazador)

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2172]
Links:
https://es.wowhead.com/npc=110424/imagen-de-mimiron
from WoWHead or our Armory

Lo que sucede:
este npc no aparece en la sede

Lo que debería suceder:
este npc debería aparecer en la sede y darme una misión
https://es.wowhead.com/quest=43370/un-nuevo-invento

**Comment by Cefiro-Caecias** [comment]
NPC agregado, NPC asistente agregado, y quest reparada así luego no me la reclamas :P
Disponible en el próximo update.
