### ISSUE TITLE
El poder interior (Mision de sede de cazador)

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2173]
Links:
el NPC que deberia darme las misiones es: https://es.wowhead.com/npc=110768/imagen-de-kalec
y estas son las misiones: (esta cadena de misiones se llama Equilibrio de poderes)
parche 7.0.3
https://es.wowhead.com/quest=43496/el-poder-interior
https://es.wowhead.com/quest=40668/ojo-de-azshara-el-corazón-de-zin-azshari
https://es.wowhead.com/quest=43514/un-pasado-jactancioso
https://es.wowhead.com/quest=43517/arboleda-corazón-oscuro-poder-caído
https://es.wowhead.com/quest=43518/oscuridad-moderada
https://es.wowhead.com/quest=43519/fuerza-lúcida
https://es.wowhead.com/quest=43581/la-sabiduría-de-la-paciencia
https://es.wowhead.com/quest=43520/pesadilla-esmeralda-en-pesadillas
https://es.wowhead.com/quest=43521/pesadilla-esmeralda-esencia-de-poder
Parche 7.1.0
https://es.wowhead.com/quest=43522/consumo-esencial
https://es.wowhead.com/quest=43938/centrar-nuestros-esfuerzos
https://es.wowhead.com/quest=43527/salvar-a-la-guardia
https://es.wowhead.com/quest=43937/buscar-refugio
https://es.wowhead.com/quest=43523/deuda-pagada
https://es.wowhead.com/quest=40673/conocimientos-perdidos
https://es.wowhead.com/quest=43524/corte-de-las-estrellas-perfección-literaria
https://es.wowhead.com/quest=40675/la-arquería-el-rito-del-capitán
https://es.wowhead.com/quest=43525/cámara-de-las-celadoras-tomar-prestado-sin-permiso
https://es.wowhead.com/quest=40678/poder-alterado
https://es.wowhead.com/quest=43526/una-prueba-de-verdad
https://es.wowhead.com/quest=40603/en-busca-de-las-valkyras
https://es.wowhead.com/quest=40608/la-marca
https://es.wowhead.com/quest=40613/fauce-de-almas-recuperar-el-guardián-de-svaln
https://es.wowhead.com/quest=40614/un-festín-digno-de-odyn
https://es.wowhead.com/quest=40672/guarida-de-neltharion-la-clave-está-en-la-presentación
https://es.wowhead.com/quest=40615/cámaras-del-valor-bendición-de-odyn
https://es.wowhead.com/quest=43898/preparar-el-traslado
https://es.wowhead.com/quest=43528/planear-el-asalto
parche 7.1.5
https://es.wowhead.com/quest=43530/el-bastión-nocturno-delirios-de-grandeza
https://es.wowhead.com/quest=43531/bastión-nocturno-hacia-el-bastión-nocturno
https://es.wowhead.com/quest=43532/el-bastión-nocturno-llamada-de-la-oscuridad
https://es.wowhead.com/quest=43533/equilibrio-de-poderes

from WoWHead or our Armory

Lo que sucede:
NPC Imagen de kalec no da misiones

![image](https://user-images.githubusercontent.com/81131460/112739934-16e85000-8f3e-11eb-9e22-27ddad888adf.png)

Lo que debería suceder:
NPC Imagen Kalec deberia poder darme estas misiones.. ya que termine las demás misiones de sede.

**Comment by Cefiro-Caecias** [comment]
Reparado. Ya Kalec comienza la cadena, cuando se cumplen las condiciones. Sólo faltaría fasearlo, pero eso queda pendiente cuando se reconstruya el Hall.
