### ISSUE TITLE
NPC Miasu

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2174]
Links:
https://es.wowhead.com/npc=111653/miasu
from WoWHead or our Armory

lo que sucede:
el npc no aparece.. no esta, tampoco estan los adds que lo acompañan

Lo que debería suceder:
el npc deberia estar.. para poder completar logro o alguna mision.

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
