### ISSUE TITLE
Una estrella fugaz

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2176]
Links:
https://es.wowhead.com/quest=44009/una-estrella-fugaz
from WoWHead or our Armory

Misiones relacionadas. que continuan la cadena de misiones
https://es.wowhead.com/quest=44414/entes-viles-de-lothros
https://es.wowhead.com/quest=44415/el-hacha-roja
https://es.wowhead.com/quest=44416/cazador-de-la-noche
https://es.wowhead.com/quest=44464/despertares
https://es.wowhead.com/quest=44466/un-camino-incierto
https://es.wowhead.com/quest=44479/legado-de-cresta-cuervo
https://es.wowhead.com/quest=44480/en-casa-de-mi-padre
https://es.wowhead.com/quest=44481/destino-frustrado

Lo que sucede:
khadgar nunca da la mision. deberia dar la mision es importante

Lo que debería suceder:
khadgar debería dar esta misión para continuar una cadena de misiones hacia la sede para desbloquear un nuevo npc (Corazón de la Luz) en la sede.
NPC Corazón de la luz
https://es.wowhead.com/npc=113857/corazón-de-la-luz

**Comment by Cefiro-Caecias** [comment]
Reparada hace tiempo. Ya debería darla cuando se completa la quest "La última carga de Nobundo".
