### ISSUE TITLE
[Tyce] - Assault on Violet Hold - Dungeon

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#2178]
**Links:**
https://wowpedia.fandom.com/wiki/Assault_on_Violet_Hold#Encounters
https://wowpedia.fandom.com/wiki/Mindflayer_Kaahrj#Adventure_Guide
https://www.wowhead.com/spell=227178/amplified-darkness
https://wowpedia.fandom.com/wiki/Fel_Lord_Betrug
https://www.wowhead.com/spell=202328/mighty-smash
https://www.wowhead.com/quest=43487/assault-on-violet-hold-the-fel-lexicon
https://www.wowhead.com/npc=102282/lord-malgath
https://www.wowhead.com/item=139445/fel-lexicon
from WoWHead or our Armory

**What is happening:**
_Aditional information: The test run was done in HC_

1. The Boss Mindflayer Kaahrj doesnt use the skill [amplified-darkness](https://www.wowhead.com/spell=227178/amplified-darkness) which should  **Periodically increases Eternal Darkness damage by 5%. This effect stacks.** 

2. The Mini boss [lord-malgath](https://www.wowhead.com/npc=102282/lord-malgath) Shouldnt drop the [Fel Lexicon](https://www.wowhead.com/item=139445/fel-lexicon) Unless you have the [quest ](https://www.wowhead.com/quest=43487/assault-on-violet-hold-the-fel-lexicon) 

3. this is more like a visual bug with The final Boss [Fel_Lord_Betrug](https://wowpedia.fandom.com/wiki/Fel_Lord_Betrug) 
When he uses the skill Mighty Smash. sub category Excecute. the player should be draged to the middle of it on the top most part of the area. yet currently the player get stunned where he was at the moment that the boss uses the skill

https://github.com/GuabinaCore/WoWKoi/issues/1667

**Comment by Nephilimkoi** [comment]
Aditional information the critter in the dungeon give The consortion and lower city reputation 

![WoWScrnShot_032821_173308](https://user-images.githubusercontent.com/73371905/112769703-65562700-8ff0-11eb-8627-067b3131adf9.jpg)

**Comment by Nephilimkoi** [comment]
Credits to @Exlyss to suport with making this report.

**Comment by Nephilimkoi** [comment]
adding to the report 

https://wowpedia.fandom.com/wiki/Millificent_Manastorm 


For some reason the Boss Milificent ManaStorm leave the encounter at 2% out of nowhere and become invalid target as he walks to the exit
Altho i forgot to take a pic after he left.
here is a pic of the enconter restarting AFTER i came out the dung at 2%

![WoWScrnShot_033021_142338](https://user-images.githubusercontent.com/73371905/113037613-8f7c2600-9163-11eb-83c4-2bf671df5d25.jpg)

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
