### ISSUE TITLE
https://es.wowhead.com/quest=42622/tambores-ceremoniales

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2180]
Links:
https://es.wowhead.com/quest=42622/tambores-ceremoniales
from WoWHead or our Armory

tambores medianos y grandes
https://es.wowhead.com/item=138198/tambor-ceremonial-mediano
https://es.wowhead.com/item=138199/tambor-ceremonial-grande

Lo que sucede:
esta misión pide recolectar tambores pequeños, medianos  y grandes. no puedo completar la misión si los tambores medianos y grandes solo aparecen 2 como objetivos.. hay muchos tambores que no son marcados como objetivos.

Lo que debería suceder:
la misión debería tener mas objetivos disponibles para completar la misión

**Comment by Nephilimkoi** [comment]
no los marca en el mapa. pero si hay bastantes que si te toma por toda el area

**Comment by Cefiro-Caecias** [comment]
No hay bug presente. Los tambores medianos y grandes, los recoges en la zona, tanto debajo como arriba subiendo por el ascensor. En cuanto a los pequeños, los dropean los kobolds ladrones en la plataforma superior, cuando los matas y los dejan caer.
