### ISSUE TITLE
NPC sella agua sabia 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2181]
Links:
https://es.wowhead.com/npc=96084/sella-agua-sabia
from WoWHead or our Armory

Lo que sucede:
Sella agua sabia NPC , al entrar a escenario La Cuna del martillo el npc desaparece y sus acompañantes también
Cuando estoy en la puerta de entraba npc esta visible
![image](https://user-images.githubusercontent.com/81131460/112785776-6ac86700-901a-11eb-9622-0ab12b50876a.png)
al entrar al escenario La cuna del martillo desaparece
![image](https://user-images.githubusercontent.com/81131460/112786537-1625eb80-901c-11eb-985e-11579fdd518f.png)

![image](https://user-images.githubusercontent.com/81131460/112786179-4a4cdc80-901b-11eb-8148-284aeca00903.png)

Lo que debería suceder:
no debería desaparecer el NPC Sella agua sabia ya que tiene una misión 
https://es.wowhead.com/quest=42590/la-reunión-con-mugi``

**Comment by Nephilimkoi** [comment]
https://github.com/GuabinaCore/WoWKoi/issues/1742

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
