### ISSUE TITLE
Monte alto - las misiones no están en orden

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2182]
Links:

from WoWHead or our Armory

Lo que sucede:
como ven en la imagen complete  capitulo 1 y 2 de Monte alto, deberia darme la misión inicio del capitulo 3
![image](https://user-images.githubusercontent.com/81131460/112786764-96e4e780-901c-11eb-8f59-0908aabe819f.png)
esta mision no deberian darme ya que pertenece al capitulo 4 y no al 3
![image](https://user-images.githubusercontent.com/81131460/112787333-e5df4c80-901d-11eb-8bef-338e5a77b6b4.png)

Lo que debería suceder:
las misiones de capítulos de historia deberían aparecer en orden.. para evitar bugearlas.
el NPC que da las misiones es https://es.wowhead.com/npc=93826/mayla-monte-alto
por ende la mision que deberian darme es 
https://es.wowhead.com/quest=38913/la-tribu-cuerno-del-cielo
y las que le siguen son:
https://es.wowhead.com/quest=39318/cuidar-de-las-heridas
https://es.wowhead.com/quest=38910/rocs-contra-águilas
https://es.wowhead.com/quest=39321/las-tres
https://es.wowhead.com/quest=39429/ataque-a-la-tierra-de-las-brujas
https://es.wowhead.com/quest=39322/la-reina-bruja
https://es.wowhead.com/quest=39387/los-cielos-de-monte-alto
y al terminar el capitulo 3 recien deberian darme esta mision
https://es.wowhead.com/quest=38912/la-tribu-tótem-sangriento

Aqui les dejo un archivo con todas las misiones historia de monte alto, por capitulos ordenadamente
[Cadena de misiones de monte alto.txt](https://github.com/GuabinaCore/WoWKoi/files/6219225/Cadena.de.misiones.de.monte.alto.txt)

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update. Reencadené todo, siguiendo esta guía de confianza:

https://wowpedia.fandom.com/wiki/Highmountain_storyline
