### ISSUE TITLE
[Quest] Rune Ruination: Runeskeld Rollo

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2183]
**Links:**

https://www.wowhead.com/quest=42737/rune-ruination-runeskeld-rollo

https://www.wowhead.com/npc=108578/runeskeld-rollo

**What is happening:**

Runeskeld Rollo doesn't drop quest item.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Check again, because the drop of that item is 100% if you have the quest and if you are not in party.
