### ISSUE TITLE
Quest - The Defense of Tian Monastery

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2184]
**Links:**
https://www.wowhead.com/quest=41728/the-defense-of-tian-monastery

**What is happening:**
Talking with NPC Tak-Tak spawns a Kite on you and counts the action as done but doesn't teleport the player to Tian Monastery.

**What should happen:**
You should ride on the Kite to go to Tian Monastery in Pandaria.

![WoWScrnShot_032921_190653](https://user-images.githubusercontent.com/64436148/112873698-42944300-90c2-11eb-8b2f-b2ccc891707f.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
