### ISSUE TITLE
Quest - Storm, Earth and Fire

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2186]
**Links:**
https://www.wowhead.com/quest=41731/storm-earth-and-fire

**What is happening:**
Some of the Fel Fires are not actual fires but non-targetable Imps NPCs, making it hard to understand that they are the objective for that part of the mission.
Fel Spike's name while highlighted is in Spanish.

**What should happen:**
All Fel Fires should look like fires, not Imps.
Their name should be in English.

Imps/Fel Fires
![WoWScrnShot_032921_193318](https://user-images.githubusercontent.com/64436148/112877051-8ee18200-90c6-11eb-83a6-fa71dcfed361.jpg)
![WoWScrnShot_032921_193244](https://user-images.githubusercontent.com/64436148/112877108-a456ac00-90c6-11eb-907a-cc3942c91ed0.jpg)

Fel Spikes
![WoWScrnShot_032921_193504](https://user-images.githubusercontent.com/64436148/112876962-6eb1c300-90c6-11eb-8dbd-5f06bcb61616.jpg)
![WoWScrnShot_032921_193531](https://user-images.githubusercontent.com/64436148/112876996-796c5800-90c6-11eb-9f0a-45798857792a.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
