### ISSUE TITLE
Quest - An Ample Stockpile

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2187]
**Links:**
https://www.wowhead.com/quest=43054/an-ample-stockpile

**What is happening:**
The text in single quests for turning in Silkweave Bandages and Highmountain Salmon is in Cyrillic.

**What should happen:**
The text should be in English/the language the player is using for the game.

![WoWScrnShot_032921_195010](https://user-images.githubusercontent.com/64436148/112878463-475bf580-90c8-11eb-8f51-730220dddba9.jpg)
![WoWScrnShot_032921_194959](https://user-images.githubusercontent.com/64436148/112878521-580c6b80-90c8-11eb-9cc2-f8ac0424e42c.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
