### ISSUE TITLE
Cambio de Turno - Mision suramar

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2188]
Links:
https://es.wowhead.com/quest=40745/cambio-de-turno
from WoWHead or our Armory

Lo que sucede:
Al tomar la misión pide como objetivos:
-esperar que aparezca el guardia
-sigue al guardia
y la cesta esta bug, no se puede salir cuando uno entra en ella
https://es.wowhead.com/npc=107474/cesta-convenientemente-colocada
para completar el primer objetivo necesito esconder en una canasta, lo hice pero el guardia no aparece y se completa el objetivo
para el segundo objetivo, no se puede porque no aparece el guardia

lo que debería suceder:
-para el primer objetivo funcione, uno debe esconderse en la canasta, al esconderme automáticamente aparecerá el guardia,  se completa el objetivo
-para  el segundo objetivo, tengo que seguir al guardia lejos de su campo de visión, hasta ciertos puntos de la ciudad y al terminar de visitar los puntos, el guardia se ira casa donde debo matar  un guardia y liberar a Korine un npc  y tengo que llevarla devuelta con su madre..
Link de Youtube de la mision: https://www.youtube.com/watch?v=UXNP1_YI7Gk

**Comment by Cefiro-Caecias** [comment]
Reparada, blizzlike. Disponible en el próximo update.
