### ISSUE TITLE
Se busca brogozog - Mision de mundo Azsuna

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2189]
Links:
https://es.wowhead.com/quest=43607/se-busca-brogozog
from WoWHead or our Armory

Lo que pasa:
Misión es ta activa activa en el mapa pero, no da objetivos
![image](https://user-images.githubusercontent.com/81131460/112888094-8cb4fe80-9099-11eb-8763-e3d31901c518.png)
el npc que lo invocar por medio de dialogo.. no da opción de dialogo
https://es.wowhead.com/npc=106914/tehd-zapatero
![image](https://user-images.githubusercontent.com/81131460/112888294-ca198c00-9099-11eb-9cae-7548ebb7e454.png)

Lo que debería suceder:
la misión de mundo debería estar activa , uno dialoga con tehd Zapatero y invoca al demonio, lo mato y completo la misión de mundo
link de Youtube de la misión de mundo: https://www.youtube.com/watch?v=GsegCj3vVTM

**Comment by Cefiro-Caecias** [comment]
Reparada, blizzlike. Disponible en el próximo update.
