### ISSUE TITLE
Quest - The Butcher of Taurajo

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#219]
**Links:**
https://www.wowhead.com/quest=24637/the-butcher-of-taurajo
https://www.wowhead.com/npc=38018/general-hawthorne

**What is happening:**
NPC General Hawthorne isn't scaled to his appropriate level.

**Comment by DeltaVortex** [comment]
Also, his adds despawn once he is killed but they should continue being same health.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
