### ISSUE TITLE
Pararrayos - Misión de Tormenheim

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2190]
**Links:**
https://es.wowhead.com/quest=38058/pararrayos
from WoWHead or our Armory

Lo que sucede:**
La misión pide cargar transpondedor hasta el 100%
nos pide entrar la cueva  y matarlos crias de dracos de tormenta y con eso se cargaría

Lo que debería suceder:
la misión para que el transpondedor se cargue tenemos que entrar en la cueva  y buscar una rayos que se mueven, debemos pararnos encima de los rayos y estos al hacer contacto cargarían el Transpondedor con varios rayos movibles
en el vídeo se ve mejor explicado la misión
Link de youtube vídeo de la misión: https://www.youtube.com/watch?v=qEuIDSfEBaw

**Comment by Cefiro-Caecias** [comment]
Por el momento no puedo replicar lo de las nubes de rayos en el suelo, pero como compensación reparé las cuevas y dracos. Igual podrá completarse la quest, recibiendo las descargas de rayos con las que atacan los dracos. Disponible en el próximo update.
