### ISSUE TITLE
Archaeology : Archaeological find(fragments) placed on player's position directly.

### ISSUE THREAD

**Issue by SirShmo** [GuabinaCore/WoWKoi#2192]
**Links:**

from WoWHead or our Armory

**What is happening:**
Archaeology finds appear directly under player character, causing a graphical bug. 
More apparent in taller models like Night Elves, no real issue on smaller models, like gnomes.

![ArcheologyVase](https://user-images.githubusercontent.com/53211124/112920461-df081680-90bd-11eb-8750-e8ba4fbeb880.png)

**What should happen:**
The placement of archaeological find a slight distance away from player might be preferable.

**Comment by Cefiro-Caecias** [comment]
Archeology has been temporarily disabled as it causes a Server crash. We will be informing you of the progress.
