### ISSUE TITLE
Inscription : Quest : Player is unable to complete the inscription quest The Ink Flows.

### ISSUE THREAD

**Issue by SirShmo** [GuabinaCore/WoWKoi#2194]
**Links:**

https://www.wowhead.com/quest=39948/the-ink-flows

from WoWHead or our Armory

**What is happening:**
Player is not able to complete inscription quest The Ink Flows.
 No item is given upon quest acceptance and none seem to be required for turn in.

![InkFlows](https://user-images.githubusercontent.com/53211124/112921865-5b9bf480-90c0-11eb-9e03-e05fad1b55f4.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
