### ISSUE TITLE
Mining : Mining node extras

### ISSUE THREAD

**Issue by SirShmo** [GuabinaCore/WoWKoi#2195]
**Links:**

from WoWHead or our Armory

**What is happening:**

In iron mining nodes, extra copper ore, and rough stone may appear.
In gold mining nodes, Goldthorn herb can appear.

![IronNode](https://user-images.githubusercontent.com/53211124/112922456-5db28300-90c1-11eb-8d7a-93d6019a9f2f.png)

![MiningGold](https://user-images.githubusercontent.com/53211124/112922473-64d99100-90c1-11eb-846f-34f1eeae9444.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
