### ISSUE TITLE
Quest - The Fangs of Ashamane

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2196]
**Links:**
https://www.wowhead.com/quest=42430/the-fangs-of-ashamane

**What is happening:**
The platform to get on the lower floors of Temple of Fal'adora can be used only for the first time, if for any reason you get teleported away (crash) even if you interact it doesn't send you over the fence to continue the quest.
After killing the last Boss Mob, the Artifact Fangs of Ashamane can't be interacted with, making it impossible to collect it.

**What should happen:**
The platform should be always available to use.
The Artifact should be interagible to collect it after as you finish the quest.

![WoWScrnShot_033021_225613](https://user-images.githubusercontent.com/64436148/113058507-806e9580-91ae-11eb-8551-3df64f7a19e7.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed that the artifact can be looted. I'll see the other detail when I review the area. Available in the next update.
