### ISSUE TITLE
The only way out is through

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2197]
**Links:**
https://www.wowhead.com/quest=40008/the-only-way-out-is-through
from WoWHead or our Armory

**What is happening:**
quest itself is mostly ok, only wanted to point out that thalyssra takes weird path and goes in water instead of bridge 
![image](https://user-images.githubusercontent.com/77908571/113078181-3fd94100-91db-11eb-81dd-6bdf7531f434.png)

**What should happen:**
she should walk on bridge

**Comment by Cefiro-Caecias** [comment]
Fixed.
