### ISSUE TITLE
Solido como una roca - mision Val'sharah

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2199]
Links:
https://es.wowhead.com/quest=38235/sólido-como-una-roca
from WoWHead or our Armory

Lo que sucede:
La misión da como objetivos rescatar:
Marnor Lorhoja rescatado
Ventus Brumazal rescatado
Del'thanar Troncosabio rescatado

El objetivo Marnor Lorhoja no se puede rescatar porque este al acercarte se cae debajo del suelo y es imposible rescatarlo
https://es.wowhead.com/npc=93602/marnor-lorhoja-rescatado
![image](https://user-images.githubusercontent.com/81131460/113187585-a3d12900-921e-11eb-962e-aaf3e1473a76.png)

Lo que debería suceder:
todos los npcs que la misión da deberían poderse ver para poder rescatarlos, y completar la misión

**Comment by Exlyss** [comment]
Already posted in #2153.

**Comment by Cefiro-Caecias** [comment]
Fixed.
