### ISSUE TITLE
[Saitama] - Spell Black Arrow Pet Taunt

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#22]
Class: Hunter
Spec: Marksmanship
Spell: [Black Arrow](https://www.wowhead.com/spell=194599/black-arrow)
**What is happening:**
The pet summoned when using [Black Arrow](https://www.wowhead.com/spell=194599/black-arrow) is not taunting the enemy the spell was used on, as it should, for the duration of the debuff (8 seconds).

**What should happen:**
The pet summoned when using [Black Arrow](https://www.wowhead.com/spell=194599/black-arrow) should taunt the enemy the arrow was cast on for the duration of the debuff that it gives (8 seconds).

**Comment by login6710** [comment]
Fixed
