### ISSUE TITLE
Mision de Bonificacion - Val'sharah

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2200]
Links:
https://es.wowhead.com/quest=38372/hermanas-condenadas
from WoWHead or our Armory

Lo que sucede:
misión de bonificación activa pero no se visualiza en el mapa..
![image](https://user-images.githubusercontent.com/81131460/113189512-e267e300-9220-11eb-884b-d0ef1a0c87c9.png)
deberia aparecer asi como este otro objetivo de bonificacion
![image](https://user-images.githubusercontent.com/81131460/113189811-3b377b80-9221-11eb-8b6a-2c218079474f.png)

Lo que debería suceder:
la misión de bonificacion, debería visualizarse en el mapa, para que uno pueda acercarse a la zona y poder completarla.

**Comment by Cefiro-Caecias** [comment]
Irresoluble por el momento. Queda pendiente.
