### ISSUE TITLE
Mantenimiento seguro - Mision de mundo Suramar

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2201]
Links:
https://es.wowhead.com/quest=44799/mantenimiento-seguro
from WoWHead or our Armory

Lo que sucede:
la misión pide rescatar 5 refugiados desesperados, pero no indica o da objetivo donde llevarlo para que se complete la misión y otro problema es que esta misión de mundo  marca como objetivos en el minimapa, pero no aparece como activa en el mapa.

![image](https://user-images.githubusercontent.com/81131460/113196377-0cbd9e80-9229-11eb-8a1f-c788122e1f5b.png)

Lo que debería suceder:
debería poder rescatar a los 5 refugiados y llévalos  una casa en las coordenadas 49.36. 74.69
link de youtube de la mision: https://www.youtube.com/watch?v=HHSsEk_WLHo

**Comment by Cefiro-Caecias** [comment]
Irresoluble por el momento. Queda pendiente.
