### ISSUE TITLE
Archidruida de la Zarpa - Val'sharah 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2202]
Links:
https://es.wowhead.com/storyline/archidruida-de-la-zarpa-186
from WoWHead or our Armory

Lo que sucede:
al terminar el capitulo 1 archidruida del Valle, el npc Nyandra Brote Primaveral debería darme la misión https://es.wowhead.com/storyline/archidruida-de-la-zarpa-186 que comienza la cadena de misiones del capitulo 2 Archidruida de la zarpa, Nyandra el NPC no da la misión, sino que se salta al capitulo 3
![image](https://user-images.githubusercontent.com/81131460/113379489-4aace680-933f-11eb-964f-9b314775bc74.png)
![image](https://user-images.githubusercontent.com/81131460/113379522-60baa700-933f-11eb-92ec-fde7cb2d42e9.png)

Lo que debería suceder:
NPC que da la misión
https://es.wowhead.com/npc=91651/nyandra-brote-primaveral

las misiones deben aparecer una después de otra, para así poder hacer evitar bugearlas, en orden deberían estar.

Aqui dejo las misiones del sub-logro de Archidruida de la Zarpa 
https://es.wowhead.com/storyline/archidruida-de-la-zarpa-186
https://es.wowhead.com/quest=38922/pelusín
https://es.wowhead.com/quest=38246/llamada-totémica
https://es.wowhead.com/quest=38455/fúrbolgs-demenciados
https://es.wowhead.com/quest=38143/el-despertar-de-la-archidruida
https://es.wowhead.com/quest=38144/los-demonios-de-abajo
https://es.wowhead.com/quest=38145/adiós-al-sueño
https://es.wowhead.com/quest=38147/sueños-enredados
 una vez terminada estas 9 misiones se completa el sub-logro Archidruida de la zarpa
y recien deberiadarme la mision de Archidruida del conocimientoy sus respectivas misiones de su cadena

**Comment by Cefiro-Caecias** [comment]
Fixed.
