### ISSUE TITLE
Cadena de misiones de Brujo hacia la sede + arma artefacto brujo afliccion

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2203]
Links:
https://es.wowhead.com/quest=42939/tracking-down-uthalesh
https://es.wowhead.com/quest=40495/ulthalesh-la-falce-del-paso-de-la-muerte
https://es.wowhead.com/quest=40588/seguir-la-maldición
https://es.wowhead.com/quest=40604/perturbar-el-pasado
https://es.wowhead.com/quest=40606/señalar-el-camino
https://es.wowhead.com/quest=40611/el-destino-del-paso-de-la-muerte
https://es.wowhead.com/quest=40623/los-jinetes-oscuros
https://es.wowhead.com/quest=40712/el-poder-poseído
https://es.wowhead.com/quest=40731/el-corazón-de-cicatriz-del-terror
https://es.wowhead.com/quest=40823/reconstruir-el-consejo
from WoWHead or our Armory

Lo que pasa:
estas dos misiones el NPC Calydus no las da
antes de eso deberían eliminar el portal que lleva a la sede porque deberia estar bloqueado, recien cuando se completen estas dos misiones se desbloqueara la sede.
https://es.wowhead.com/quest=40731/el-corazón-de-cicatriz-del-terror
https://es.wowhead.com/quest=40823/reconstruir-el-consejo

Lo que debería pasar:
debería el NPC Calydus dar todas las misiones para poder desbloquear la sede del brujo

**Comment by Cefiro-Caecias** [comment]
Fixed.
