### ISSUE TITLE
Priest Class Hall - Command Map

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2204]
**Links:**
https://www.youtube.com/watch?v=R_O8exO_ueY Minute 3:30 shows how the Command Map should corretly look.

**What is happening:**
After completing a mission it bugs out, mostly is the mission was failed, continuing to give the report for that mission every time the player interacts with the Command Map. Also the "Next" button is greyed out, making the only way to exit by closing the Command Map.
(Visual) The Command Map is not spawning correctly.

**What should happen:**
As one mission is completed, be it successful or failed, the report shouldn't be given more than one time.

![WoWScrnShot_040221_122629](https://user-images.githubusercontent.com/64436148/113408116-0eb16a00-93af-11eb-8fad-662f5e50c112.jpg)

![WoWScrnShot_040221_122130](https://user-images.githubusercontent.com/64436148/113408099-01947b00-93af-11eb-9074-d4c74d974be9.jpg)

**Comment by Cefiro-Caecias** [comment]
Reconstruction pending.
