### ISSUE TITLE
[Quest] The Splinetered fleet - Auto-complete workaround request

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2206]
**Links:**

https://www.wowhead.com/quest=39801/the-splintered-fleet#

**What is happening:**

Although the quest has already been reported, there is no auto-complete option to get past the scenario. It makes you stuck on the ship.

https://imgur.com/a/FAjB2a9

**What should happen:**

**Comment by Exlyss** [comment]
Copy of #2107, please before posting check if there already is a report about the same thing you are going to report.
