### ISSUE TITLE
[quest] Becoming the ascendant

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2207]
**Links:**

https://www.wowhead.com/quest=39092/becoming-the-ascendant

**What is happening:**

The quest has already been flagged as fixed. It still doesn't work. The "Commune with the Statue" (https://www.wowhead.com/npc=94477/credit-bunny) dialogue dont grant credits toward the quest.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
