### ISSUE TITLE
[NPC] Helya, Gripping Tentacle

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2209]
**Links:**
ToV:
https://www.wowhead.com/npc=114537/helya
https://www.wowhead.com/npc=114905/gripping-tentacle

MoS:
https://www.wowhead.com/npc=96759/helya

**What is happening:**

Helya (both raid and dungeon id) and Gripping Tentacle are not affected by Demon Hunter's Eye Beam(https://www.wowhead.com/spell=198013/eye-beam)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
