### ISSUE TITLE
[Tyce] - Class Hall Mission - Darkfall Ridge Supplies

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2212]
**Links:**
https://www.wowhead.com/mission=1780/darkfall-ridge-supplies

**What is happening:**
Even with more than 100% chance to succeed in the mission, as the report comes in it always states 13% chance and fails the mission.

**What should happen:**
The % stated when the mission complete should be the exact same as when it started.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
