### ISSUE TITLE
Quest - The Seed of Ages

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2213]
**Links:**
Can't actually find it on WoWHead. The quest is about "Imbue the artifact weapon with new power", it is the quest given after you get the first artifact acting as a tutorial to getting traits for that.

**What is happening:**
The artifact in question, The Fangs of Ashamane (Feral Druid) has 0 Artifact Power, making impossible to complete the quest.

**What should happen:**
The artifact should have exactly 100 Artifact Power to get the first trait.

![WoWScrnShot_040421_174108](https://user-images.githubusercontent.com/64436148/113514092-f8e9a380-956c-11eb-90e3-b8de95331312.jpg)

**Comment by NightwindOI** [comment]
Please relog and check if its still bugged.

**Comment by Exlyss** [comment]
Yes it's still bugged even after a relog.

**Comment by Cefiro-Caecias** [comment]
You must have the weapon equipped when you take the quest, or you do not receive the 100 artifact power as a gift to complete the quest.

**Comment by jacobx97** [comment]
This quest is still bugged, you do not get 100 ap even when you have weapon equiped(resto weapon)
