### ISSUE TITLE
Misiones de monte alto- Deuda de sangre - Adentrarse en la oscuridad

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2214]
**Links:**
https://es.wowhead.com/quest=39426/deuda-de-sangre
https://es.wowhead.com/quest=40229/adentrarse-en-la-oscuridad
from WoWHead or our Armory

Lo que sucede:
esta mision se puede completar exitosamente, solo que al entregar la mision que esta mal planteada, ya que al tomar la mision Navarrog no nos sigue.. y cuando mato a Torok  la mision se completa y me envie a la cueva donde entrego la mision y no me la mision que sigue 
https://es.wowhead.com/quest=40229/adentrarse-en-la-oscuridad
como ven al imagen navarrog no da la mision..
![image](https://user-images.githubusercontent.com/81131460/113516603-c45ff280-9540-11eb-99ad-70a35f9bafc9.png)

Lo que debería suceder:
al tomar la mision Navarrogg deberia seguirnos hasta llegar al objetivo, una vez matado  
Torok Tótem Sangriento , debemos entregar la mision en Navarrogg y despues de entregar la mision nos deberia dar la mision
https://es.wowhead.com/quest=40229/adentrarse-en-la-oscuridad
NPC que da la mision y deberia entregar la mision
https://es.wowhead.com/npc=95421/navarrogg
link de youtube de la mision: https://www.youtube.com/watch?v=4c7CbzgoOEk
Dato wowhead o youtube esta esta mal en como plantear la mision.. si se fijan en la descripcion de wowhead y el video veran la diferencia :s

**Comment by Cefiro-Caecias** [comment]
Pendiente de revisión.
