### ISSUE TITLE
Druid - Restoration Artifact

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2215]
**Links:**
https://www.wowhead.com/quest=40649/meet-with-mylune
https://www.wowhead.com/npc=113525/mylune

**What is happening:**
The quest to start Restoration Artifact is impossible to be found, even if another player has obtained it.

**What should happen:**
After talking with NPC Rensar Greathoof, the player should be able to start the quest at NPC Mylune, but she hasn't even appeared.

Additional: I already have the other 3 Artifacts, so I don't think it's a problem of going on with quests.

![WoWScrnShot_040421_205726](https://user-images.githubusercontent.com/64436148/113519183-ec744380-958a-11eb-9ac2-a6e691a130ec.jpg)
![WoWScrnShot_040421_212012](https://user-images.githubusercontent.com/64436148/113519295-905def00-958b-11eb-9525-26d09bbb55bc.jpg)

**Comment by SirShmo** [comment]
She can be seen by others though, for reasons unknown
![MissingMylune](https://user-images.githubusercontent.com/53211124/113519760-36d1d200-9543-11eb-9b1a-c3068c3b3a6d.png)

**Comment by Cefiro-Caecias** [comment]
There is no bug present. I tried, and Mylune was crossing the bridge. I was able to turn in the quest and take the next one o.O
