### ISSUE TITLE
Archidruida de la Zarpa - Mision Val'sharah

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2217]
Links:
https://es.wowhead.com/quest=38142/archidruida-de-la-zarpa
from WoWHead or our Armory

Lo que sucede:
esta mision me la da el NPC Aranelle y termina en Aranelle como ven la imagen y el mapa me marca que la mision debo entregar en otro punto(el correcto pero el npc no la reconoce)
como ven en las imágenes, la mision esta mal planteada, porque tengo que entregar la mision con el NPC Nyandra brote primaveral.. lo cual no pasa.
![image](https://user-images.githubusercontent.com/81131460/113527572-a10a6700-9583-11eb-99b3-bd217e43be6a.png)
![image](https://user-images.githubusercontent.com/81131460/113527642-ca2af780-9583-11eb-83ae-4293a081af10.png)
![image](https://user-images.githubusercontent.com/81131460/113527782-3574c980-9584-11eb-9aee-9540eccb2fbd.png)
![image](https://user-images.githubusercontent.com/81131460/113528364-f778a500-9585-11eb-8d2e-f819d0faf507.png)

Lo que debería suceder:
hay dos npc que deberían iniciar la mision:
https://es.wowhead.com/npc=91651/nyandra-brote-primaveral
https://es.wowhead.com/npc=94179/aranelle
la mision termina en este npc
https://es.wowhead.com/npc=73426/rylissa-cantodeoso

Al tomar la mision de Aranelle o Nyandra brote primaveral, esta mision deberia terminar en Rylissa cantodeoso.
link de youtube de la mision: https://www.youtube.com/watch?v=EDCthS_qMjE

**Comment by Cefiro-Caecias** [comment]
Reparada. Disponible en el próximo update.
