### ISSUE TITLE
Sueños enredados - Mision de Val'sharah

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2218]
Links:
https://es.wowhead.com/quest=38147/sueños-enredados
from WoWHead or our Armory

Lo que sucede:
al tomar la mision el NPC Koda Zarpacerada me sigue hasta el pasadizo donde esta la cueva con un muro de zarza, la cual no se abre y  no puedo matar Morphael.
![image](https://user-images.githubusercontent.com/81131460/113529603-77543e80-9589-11eb-82e0-d80a9f5fb580.png)

Lo que debería suceder:
Al tomar la mision me pide eliminar el muro de zarza debería derrumbarse al estar cerca del muro de zarza una vez derrumbado deberia entrar y deberia matar Morphael y se completaria la mision.
link de youtube de la mision: https://www.youtube.com/watch?v=t7OiW7njpZE

**Comment by Cefiro-Caecias** [comment]
Reparada.
