### ISSUE TITLE
[NPC] Conjurer Margoss

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2219]
**Links:**

https://www.wowhead.com/npc=108825/conjurer-margoss

**What is happening:**

The NPC is missing Fishing training and vendor option in dialogue menu.

**What should happen:**

The NPC grants Drowned mana quest, is a Fishing Trainer and a vendor.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
