### ISSUE TITLE
Dungeon - Temple of the Jade Serpent

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2222]
**Links:**
https://www.wowhead.com/temple-of-the-jade-serpent

**What is happening:**
Unable to enter, it says the player have to be level 115 to enter.

**What should happen:**
Being it a Pandaria Dungeon, being level 90 shoul be enough to enter.

![WoWScrnShot_040621_151833](https://user-images.githubusercontent.com/64436148/113720229-b5b73e00-96ee-11eb-8969-1a3936991db0.jpg)

**Comment by Cefiro-Caecias** [comment]
Pending for the future.
