### ISSUE TITLE
[Tyce] - Heart of Fear

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2223]
**Links:**
https://www.wowhead.com/heart-of-fear
https://www.wowhead.com/npc=62837/grand-empress-shekzeer

**What is happening:**
1. The ID for normal and heroic mode seem to overlap, making impossible to enter a 25 heroic if you have already done 10 heroic. Note that this issue is happening with MOST RAIDS.
2. After leaving the raid (ie crash, relog) while an encouter is in progress, even if you are alone you can't enter in the raid. This often happens even if the encounter is actually finished but the player is still in combat because of some bug, like invisible or bugged MOBs.
3. When the boss runs out of sha energy, it disappears and spawns some mobs you have to kill, but after completing this phase the boss isn't coming back, making it impossible to kill.

**What should happen:**
1. They should be two completely different IDs.
2. After leaving the dungeon for any reason, the boss should reset, making it possible to enter again.
3. Right after the mobs it spawns (https://www.wowhead.com/npc=64453/setthik-windblade) dies, the boss should come out again to continue the fight.

Also, the boss should start with full sha energy, but it starts with already 0.
![WoWScrnShot_040621_162135](https://user-images.githubusercontent.com/64436148/113727259-4133cd80-96f5-11eb-912d-0b3872dfbda0.jpg)
![WoWScrnShot_040621_162211](https://user-images.githubusercontent.com/64436148/113727303-4abd3580-96f5-11eb-81fb-176337d55ae9.jpg)

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
