### ISSUE TITLE
[Tyce] - Raid Siege of Orgrimmar - Paragon of Klaxxi

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2224]
**Links:**
https://www.wowhead.com/npc=71161/kilruk-the-wind-reaver

**What is happening:**

Skipping Galakras results in not being able to trigger Mantid Amber (Paragons of Klaxxi). I wasn't able to find ID for Mantid Amber object.
*skipping Galakras as Demon Hunter is a valid thing on retail*
**What should happen:**

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
