### ISSUE TITLE
Jewelcrafting : Quest : Hidden Intentions.

### ISSUE THREAD

**Issue by SirShmo** [GuabinaCore/WoWKoi#2229]
**Links:**

https://www.wowhead.com/quest=40539/hidden-intentions

from WoWHead or our Armory

**What is happening:**
1. Quest has incorrect localization of text in various places (see screenshots)
2. Dialogue choices with with npc Ms. Zulian are non functional. Player may use 4th option (Killing npc Inkrot)
3. Ms. Zulian does not actually create a gem for player upon dialogue choices, quest breaks and is unable to finish at this point.

![HiddenIntentions](https://user-images.githubusercontent.com/53211124/113792572-1fd5e000-96fb-11eb-8843-235444e39883.png)

![HiddenIntentions2](https://user-images.githubusercontent.com/53211124/113792602-2b290b80-96fb-11eb-9e8a-fa98151ab3b4.png)

![HiddenIntentions3](https://user-images.githubusercontent.com/53211124/113792673-53b10580-96fb-11eb-8907-194ed1a36004.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed, blizzlike. Available in the next update.
