### ISSUE TITLE
[Sefrenia] - Mining Legion: Player has greatly diminished skill raising after attaining 700 points.

### ISSUE THREAD

**Issue by SirShmo** [GuabinaCore/WoWKoi#2230]
**Links:**

https://www.wowhead.com/legion-mining-guide

from WoWHead or our Armory

**What is happening:**
Upon reaching skill 700, legion mining nodes turn grey, with the exception or felslate seam. This includes felslate, and leystone normal, felslate and leystone rich, and leystone seam.
However skill ups are infrequently attained as if all nodes mentioned were green to player.
Felslate seam functions as normal, only tool-tip has incorrect localization.

![MiningLegion](https://user-images.githubusercontent.com/53211124/113793836-0f733480-96fe-11eb-8e40-643c750f7198.png)

![MiningLegion2](https://user-images.githubusercontent.com/53211124/113793850-1ac66000-96fe-11eb-9574-9a18b3000088.png)

![MiningLegion3](https://user-images.githubusercontent.com/53211124/113793991-637e1900-96fe-11eb-8378-8426ee868073.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Reviewing and analyzing in the Database, I find this data:

* Felslate Deposit --- Max skil gain 700
* Rich Felslate Deposit --- Max skil gain 700
* Felslate Thorn --- Max skil gain 775
* Felslate Seam --- Max skil gain 795
* Burning Felslate Deposit - Max skil gain 775 (Mining World Quest)
* Darkened Felslate Deposit --- Max skil gain 775 (Mining World Quest)
* Heavy Felslate Deposit - Max skil gain 775 (Mining World Quest)
* Odious Felslate Outcropping --- Max skil gain 775 (Mining World Quest)
* Shattered Felslate Seam --- Max skil gain 785 (Mining World Quest)

* Leystone Deposit --- Max skil gain 700
* Rich Leystone Deposit --- Max skil gain 700
* Leystone Seam --- Max skil gain 700
* Crude Leystone Seam --- Max skil gain 785 (Mining World Quest)
* Wild Leystone Seam --- Max skil gain 785 (Mining World Quest)
* Raw Leystone Seam --- Max skil gain 795 (Mining World Quest)
* Bright Leystone Deposit --- Max skil gain 765 (Mining World Quest)
* Charged Leystone Deposit --- Max skil gain 765 (Mining World Quest)
* Dark Leystone Deposit --- Max skil gain 765 (Mining World Quest)
* Dense Leystone Outcropping --- Max skil gain 765 (Mining World Quest)
* Gleaming Leystone Outcropping --- Max skil gain 765 (Mining World Quest)
* Glowing Leystone Deposit --- Max skil gain 765 (Mining World Quest)
* Hard Leystone Deposit --- Max skil gain 765 (Mining World Quest)
* Luminous Leystone Outcropping --- Max skil gain 765 (Mining World Quest)
* Massive Leystone Deposit --- Max skil gain 765 (Mining World Quest)
* Radiant Leystone Outcropping --- Max skil gain 765 (Mining World Quest)
* Rough Leystone Outcropping --- Max skil gain 765 (Mining World Quest)
* Stormy Leystone Deposit --- Max skil gain 765 (Mining World Quest)
* Striking Leystone Deposit --- Max skil gain 765 (Mining World Quest)

As I understand it, "basic" Deposits increase your skill up to 700 points (intended to move up from Draenor to Legion); then, the "rare" Deposits allow you to raise more, but obviously it is the Deposits assigned to the World Quests that allow you to raise the skill with greater intensity.

I await your comments to see if this information is correct, or if I should raise the skill gain of a particular Deposit.
