### ISSUE TITLE
[Tyce] - Spell Strangling Roots (204574)

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#2232]
**Links:**
https://wowpedia.fandom.com/wiki/Oakheart
https://www.wowhead.com/npc=103344
https://www.wowhead.com/spell=204574/strangling-roots
from WoWHead or our Armory

**What is happening:**

Strangling Roots not rooting target

**What should happen:**

Strangling Roots: Roots emerge under nearby enemies, inflicting 248 Physical damage every 1 sec. and **rooting them in position for 1 min** or until destroyed. 

Collaboration with @Exlyss

**Comment by Arkanheal** [comment]
They become active only after 2 sec https://www.wowhead.com/darkheart-thicket-dungeon-strategy-guide#oakheart-tips-strategy

They must be targetable at all times though. More info on this @Nephilimkoi ?
