### ISSUE TITLE
Quest - Dazed of the Past 

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2235]
**Links:**
https://www.wowhead.com/quest=41889/dazed-of-the-past

**What is happening:**
NPC Namha Moonwater is giving only 10 Namha's Stonehide Leather, insufficient to complete the quest.

**What should happen:**
She should give 100 Namha's Stonehide Leather.

(At the moment the only way to complete this quest is to craft 10 Tanned Stonehide Leather, delete the quest and take it again, and craft again until you have enough materials to complete the quest. Also don't craft the final items for the last craft as when you delete the quest they are removed from inventory).

There is also an issue about the crafted material appearing  as Tanned Stonehide PELT in the Leatherworking tab, but as Tanned Stonehide LEATHER when crafted and in the tool-tip, making it also conflict with the other craftable quest material Stonehide Leather Strip that needs Tanned Stonehide Leather, but isn't recognizing the item that has been crafted. 
![WoWScrnShot_040721_181118](https://user-images.githubusercontent.com/64436148/113899060-b7573380-97cc-11eb-87be-d94aca1a7cf2.jpg)
![WoWScrnShot_040721_181546](https://user-images.githubusercontent.com/64436148/113899656-4cf2c300-97cd-11eb-8c1f-08213fd53c65.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
