### ISSUE TITLE
[Quest] Network Security

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2236]
**Links:**

https://www.wowhead.com/quest=40748/network-security

**What is happening:**

1. [Arcane Coil](https://www.wowhead.com/object=246297/arcane-coil-overcharged) (4) can be used multiple times for additional credits.
2. [Warpcaster Thwen](https://www.wowhead.com/npc=101116/warpcaster-thwen) is missing her shield, that protects her till Arcane Coils are overcharged. She's also missing her dialogue, abilities and animations.

**What should happen:**

1. One click, one credit.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
