### ISSUE TITLE
Quest - Claw of the Land

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2237]
**Links:**
https://www.wowhead.com/quest=40192/claw-of-the-land
https://www.wowhead.com/item=130070/stalker-claw#dropped-by
https://www.wowhead.com/npc=99481/pinerock-stalker#drops

The drop rate of Stalker Claw COULD be broken, as I got only 3 of them after killing tens of Pinerock Stalkers (11% chance from drop, 19% chance from skinning).

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
