### ISSUE TITLE
[Quest] Survey Says

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2238]
**Links:**

https://www.wowhead.com/quest=40956/survey-says

**What is happening:**

Nothing is happening during channeling.

**What should happen:**

1.During channeling the following NPCs should be spawned:
   - [Warp Rift](https://www.wowhead.com/npc=106799/warp-rift)(Im not sure about this ID) that summons [Warp Spark](https://www.wowhead.com/npc=106808/warp-spark). 
   Click Warp rift to close it.
   - [Time-Scarred Fiend](https://www.wowhead.com/npc=106690/time-scarred-fiend)
   - [Quantum Devourer](https://www.wowhead.com/npc=106810/quantum-devourer)

2.Channeling should be interrupted in the moment of NPC spawning.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
