### ISSUE TITLE
[Tyce] - Raid - Throne of Thunder - Iron Qon

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2240]
**Links:**
https://www.wowhead.com/throne-of-thunder
https://www.wowhead.com/npc=68078/iron-qon

**What is happening:**
The 3 adds of the boss (Ro'shak, Quet'zal and Dam'ren) are spawned twice, resulting with the first kill that opens the door, and the second closes it, or some strange combinations resulting in either opening the door smoothly, or not opening it at all.

**What should happen:**
The boss should spawn only 1x each add and open the door as the boss fight ends.

![WoWScrnShot_040721_204717](https://user-images.githubusercontent.com/64436148/113918730-12942080-97e3-11eb-9ab4-40ed371e3fec.jpg)

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
