### ISSUE TITLE
Missing Hunter Pets

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2241]
**Links:**
https://www.wowhead.com/npc=50854/bloodtooth
https://www.wowhead.com/npc=50850/savage
https://www.wowhead.com/npc=50843/portent

**What is missing:**
Bloodtooth not spawned.
Savage not spawned.
Portent is spawned, but instead of following its path, he's stuck in place (Screenshot not yet ready).

**Comment by Noahkrr** [comment]
Agregaría algunas pet 
Npc Gon
https://es.wowhead.com/npc=121571/gon
Objeto que invoca a Gon
https://es.wowhead.com/object=269796/cascara-de-huevo-espectral
Npc grifo espectral
https://es.wowhead.com/npc=121567/grifo-espectral-perdido
Objeto que invoca al grifo espectral perdido
https://es.wowhead.com/object=269775/pluma-espectral
Npc fenryr bestia domable
https://es.wowhead.com/npc=99868/fenryr
El fenryr se puede donar al completar el desafío de cazador hacer la mazmorra cámaras del valor en mítico solo.. al matar al fenryr se genera un fenryr domable dentro de la cueva..
https://m.youtube.com/watch?v=Lip4Tw-K3mM&feature=youtu.be

**Comment by Cefiro-Caecias** [comment]
Fixed all except Fenrys, which is made by Core. Available in the next update.
