### ISSUE TITLE
Missing Pandaria Hunter Pets

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2242]
**Links:**
https://www.wowhead.com/npc=67820/bombyx
https://www.wowhead.com/npc=50859/glimmer
https://www.wowhead.com/npc=50885/patrannache
https://www.wowhead.com/npc=50944/bristlespine
https://www.wowhead.com/npc=50998/stompy
https://www.wowhead.com/npc=51013/rockhide-the-immovable
https://www.wowhead.com/npc=50960/hexapos

**What is happening:**
All of them are missing.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
