### ISSUE TITLE
Vial de purificación vil - Objeto que sirve para domar lobos viles - Cazador

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2243]
Links:
https://es.wowhead.com/item=124506/vial-de-purificación-vil
from WoWHead or our Armory

Lo que sucede:
Al usar el vial de purificación vil en el lobo de vinculo vil, el vial no hace efecto en la bestia sigue siendo indomable.
como ven en la imagen le lanze el vial al lobo pero no se deja domesticar..
![WoWScrnShot_040821_133546](https://user-images.githubusercontent.com/81131460/114081187-dcea4880-9871-11eb-9120-5953b6a67584.jpg)

Lo que debería suceder:
Al usar el Vial de purificación vil(https://es.wowhead.com/item=124506/vial-de-purificación-vil) en un lobo  de vinculo vil (https://es.wowhead.com/npc=90517/lobo-de-vínculo-vil)
este debería poder ser domable para cualquier cazador

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
