### ISSUE TITLE
[Quest] Shift Change

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2247]
**Links:**

https://www.wowhead.com/quest=40745/shift-change

**What is happening:**

- Hiding in [Inconspicuous Basket](https://www.wowhead.com/npc=107371/inconspicuous-basket) won't let you leave when clicking eject button.
- [Guard Morgaine](https://www.wowhead.com/npc=108616/guard-morgaine)'s ability [On Alert](https://www.wowhead.com/spell=212826/on-alert) doesn't work

**What should happen:**

- Baskets should let you out when clicking eject button
- When entering range of [On Alert](https://www.wowhead.com/spell=212826/on-alert), the event should be reset.

**Comment by Cefiro-Caecias** [comment]
Fixed.
