### ISSUE TITLE
[Quest] Friends in Cages

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2249]
**Links:**

https://www.wowhead.com/quest=42722/friends-in-cages

**What is happening:**

- [Containment Field](https://www.wowhead.com/object=266138/containment-field#objective-of) (I am not sure about this ID) tooltip text is in spanish
- Containment Field reset cooldown is very short. Can be clicked multiple times for additional credits.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
