### ISSUE TITLE
[Quest] Friends on the Outside

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2251]
**Links:**

https://www.wowhead.com/quest=42487/friends-on-the-outside

**What is happening:**

[Thalyssra](https://www.wowhead.com/npc=97140/first-arcanist-thalyssra) doesn't give credit towards the quest after clicking the dialogue option.

**What should happen:**

**Comment by OnlyWATCH** [comment]
Correctly not happening anything . Arcanist not taking "Gift-Wrapped Bottle of Arcwine" this quest item.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
