### ISSUE TITLE
[Quest] Moths to a Flame

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2252]
**Links:**

https://www.wowhead.com/quest=42828/moths-to-a-flame

**What is happening:**

Only 2 out of 4 [Underglow Locust](https://www.wowhead.com/npc=109158/underglow-locust)s spawn in the area forcing you to wait untill they respawn

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
