### ISSUE TITLE
[Quest] Estate Jewelery: Haute Claw Ture

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2253]
**Links:**

https://www.wowhead.com/quest=41466/estate-jewelry-haute-claw-ture

**What is happening:**

- [Mornath](https://www.wowhead.com/npc=104369/mornath) is missing his abilities.
- [Mornath's Custodian](https://www.wowhead.com/npc=106310/mornaths-custodian) is friendly and cannot be killed. This npc is mostly likely causing the quest to be bugged because the custodian isn't killed and the quest stage isn't completed.

The issue below will most likely be eliminated after fixing the one above.
- Looting looting [The Claw Clacks for Thee](https://www.wowhead.com/item=135509/the-claw-clacks-for-thee) from [Mornath Curio Chest](https://www.wowhead.com/object=247050/mornaths-curio-chest) doesnt go towards credtis

**What should happen:**

According to Wowhead comments: "I couldn't click the chest despite reducing Mornath's HP to 1. When I killed his "pet" before killing him it finally turned clickable."

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
