### ISSUE TITLE
[Quest] Make an Entrance

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2254]
**Links:**

https://www.wowhead.com/quest=42829/make-an-entrance

**What is happening:**

>>> **low priority, its just polishing, the quest can be completed** <<<

[Palanquin](https://www.wowhead.com/npc=109114/palanquin)  movement trajectory incorrect. It stops halfway to the quest NPC.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
