### ISSUE TITLE
[Quest] The old Fashioned way

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2255]
**Links:**

https://www.wowhead.com/quest=42835/the-old-fashioned-way

**What is happening:**

- [Shadefruit](https://www.wowhead.com/object=251493/shadefruit), [Purified Water](https://www.wowhead.com/object=251492/purified-water) and [Silver Jasmine](https://www.wowhead.com/object=251494/silver-jasmine) have their tooltip text in spanish.
- Randomly clicking on the quest objects will complete the quest.

**What should happen:**

According to Wowhead comments:
  1. Jump
      NPC says: The juices need a little massaging - step into the vat and jump to squish the mixture around!
  2.  Use Shadefruit
       NPC says: I think a sour note is in order. Add a shadefruit, please
  3.  Use Purified Water
       NPC says: You need to add a bit of moisture or you'll back up the taps
  4.  Use Silver Jasmine
       NPC says: Ah! It needs something floral, to add a little brightness

**Comment by Cefiro-Caecias** [comment]
Fixed.
