### ISSUE TITLE
[Quest Item] Fresh Fel-Flesh

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2257]
**Links:**

https://www.wowhead.com/item=133743/fresh-fel-flesh

**What is happening:**

Drop rate seems too low. People on wowhead complained about low drop rate, but I cleared the whole area twice to get 3 out of 6 pieces.
EDIT: It took 5 respawns to complete the quest.
**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
