### ISSUE TITLE
[Quest] A fate worse than dying

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2258]
**Links:**

https://www.wowhead.com/quest=40328/a-fate-worse-than-dying

**What is happening:**

[Felsoul Cage](https://www.wowhead.com/object=246568/felsoul-cage) can be clicked multiple times for additional credits.

**What should happen:**

one click one credit

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
