### ISSUE TITLE
[Tyce] - Boss - The Stone Guards - Mogu'shan Vaults

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2260]
**Links:**
https://www.wowhead.com/npc=60051/cobalt-guardian

**What is happening:**
After taming one of the four bosses, the bossfight gets bugged and even killing all the remaining bosses, the doors won't open.
Coming back after the raids is reset makes the bug appear again, unless the precedently tamed boss has been abandoned.

**What should happen:**
Even if one of the bosses has been tamed, the boss fight should end as usual.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
