### ISSUE TITLE
Quest - Shipwrecked Sailors

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2264]
**Links:**
https://www.wowhead.com/quest=42220/shipwrecked-sailors

**What is happening:**
The NPCs can't be clicked to be saved.

**What should happen:**
Everyone of them should be able to be clicked.

Already reported in #2081 but it seems the fix wasn't successful

![WoWScrnShot_041421_142529](https://user-images.githubusercontent.com/64436148/114709782-4912f380-9d2d-11eb-8ad2-ea1db405fa04.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed.
