### ISSUE TITLE
[Quest] Giving it all we've got

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2266]
**Links:**

https://www.wowhead.com/quest=43562/giving-it-all-weve-got

**What is happening:**

Talking to the corresponding pylon will give credit towards towards it. No need to complete the activation quest.

**What should happen:**

Credits toward the quest should be granted after leyline activation quest is completed.

EDIT: According to WoWhead comment: "...If you have already done that achievement before getting this quest, you can simply just walk down to Arcanist Valtrois to advance the quest - you do not have to activate them again."

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
