### ISSUE TITLE
La salvación de Tormenheim - Mision

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2267]
Links:
https://es.wowhead.com/quest=40005/la-salvación-de-tormenheim
from WoWHead or our Armory

Lo que sucede:
al tomar la misión debo ir hablar con el dragón Vethir, el dragón me lleva arriba de la plataforma para pelear con 
Rey dios Skovald para derrotado, al estar derrotándolo, este npc me aturde, el npc no se va solo se para en la orilla de la plataforma, lo cual la misión no se completa

Lo que debería suceder:
Vethir me debe llevar volando hacia la plataforma donde esta el Rey dios Skovald, debo derrotarlo, Rey dios Skovald debe aturdirme y desaparecer para que la misión se complete

link de youtube de la mision: https://www.youtube.com/watch?v=gO7M6u6BUt0

**Comment by Cefiro-Caecias** [comment]
Fixed.
