### ISSUE TITLE
[Quest]The Nightborne Prince

### ISSUE THREAD

**Issue by MicuRazvan-Florentin2E3** [GuabinaCore/WoWKoi#2269]
Links:
https://www.wowhead.com/quest=37861/the-nightborne-prince
![WoWScrnShot_041421_223111](https://user-images.githubusercontent.com/79265627/114768774-00315e00-9d72-11eb-9464-08d3f43fa25f.jpg)

What is happening:
After you defeat Ael'Yith when he is going outside he stays there.

What should happen:
After you defeat Ael'Yith he supposed to go outside and dissapear and the quest should be done.

I tried to abandon the quest and kill him again but he is still stuck outside, cant even fight him again( the ss is made after i abandoned the quest and tried to do it again this is why it is 0/1 at slain)

**Comment by Cefiro-Caecias** [comment]
There is no bug present on my Test Server, and I tested that mob twice in a row. I will ask for a system check, since apparently it is something in the system that is causing errors, and not in the script.

**Comment by Cefiro-Caecias** [comment]
Fixed, now available.
