### ISSUE TITLE
Sólido como una roca - Mision Val'sharah

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2271]
Links:
https://es.wowhead.com/quest=38235/sólido-como-una-roca
from WoWHead or our Armory

Lo que sucede:
al tomar la misión, da como objetivos
Marnor Lorhoja rescatado
Ventus Brumazal rescatado
Del'thanar Troncosabio rescatado

al llegar a cada uno de los objetivos, al hacer click no los cuenta como objetivos de la misión
el objeto (rama de Elothir) que da la misión no funciona y no debería estar asociada en esta misión..

Lo que debería suceder:
al hacer click a los objetivos de la misión, debería contar como objetivo para si completar la misión
link de youtube de la mision: https://www.youtube.com/watch?v=3AaKfV5YNLo

**Comment by Cefiro-Caecias** [comment]
La quest funciona bien en mi Server de pruebas, y sólo habría que anexarle algunas medidas de seguridad. Este es el tercer caso en el que, asumo, existe una falla de sistema o un defecto en el montaje del Server público. Ya me contacté con el encargado para examinar a fondo el montaje y resolverlo.
