### ISSUE TITLE
[Quests]Azsuna

### ISSUE THREAD

**Issue by MicuRazvan-Florentin2E3** [GuabinaCore/WoWKoi#2272]
Links:
https://www.wowhead.com/quest=42370/wanding-101
https://www.wowhead.com/quest=42371/study-hall-combat-research
https://wowpedia.fandom.com/wiki/Pop_Quiz:_Advanced_Rune_Drawing
https://www.wowhead.com/quest=37530/save-yourself

What is happening:
When you start the quests they are all auto-completed.

What should happen:To do the quests normally.

Infos:
All 4 quests are part of "Azsuna vs Azshara" chapter in Azsuna zone

**Comment by Cefiro-Caecias** [comment]
These quests will become blizzlike later on.
