### ISSUE TITLE
[Quest] Arcan'dor, Gift of the Ancient Magi

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2274]
**Links:**

https://www.wowhead.com/quest=43568/arcandor-gift-of-the-ancient-magi#comments

**What is happening:**

Zone is in a wrong phase. [Fruit of the Arcan'dor](https://www.wowhead.com/item=140315/fruit-of-the-arcandor) is not present. Cannot complete the quest.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
