### ISSUE TITLE
[Quests]Val`sharah main storyline quests

### ISSUE THREAD

**Issue by MicuRazvan-Florentin2E3** [GuabinaCore/WoWKoi#2275]
Links:
https://www.wowhead.com/quest=38743/the-fate-of-valsharah
![WoWScrnShot_041521_205323](https://user-images.githubusercontent.com/79265627/114916347-5c0ced00-9e2d-11eb-8bc2-51d1e3cc7f24.jpg)

https://www.wowhead.com/quest=38377/the-emerald-queen
![WoWScrnShot_041521_210045](https://user-images.githubusercontent.com/79265627/114916985-1ef52a80-9e2e-11eb-9ed3-474032b00cfe.jpg)
![WoWScrnShot_041521_210129](https://user-images.githubusercontent.com/79265627/114916988-1f8dc100-9e2e-11eb-9339-65330613dbd2.jpg)

What is happening:
-For "the fate of val`sharah" :after you speak with tyrande she is doing nothing and if you go to temple by yourself there is no dragon to kill.
-For " the emerald queen": Nothing, after you speak with Malfurion( there are 2 Malfurion you can take the quests from both and speak with both, is the same) the cinematic doesnt run and you can speak with him 100 times and still nothing.

What should happen:
-For "the fate of val`sharah" after you speak with tyrande she helps you to go to temple of elune to fight the dragon.
-For "the emerald queen" after you speak with malfurion a cinematic starts and the quest is done.

These are the only 2 main quests I couldnt do in val'sharah I did all the main quests and I think all the side quests(not sure if there are side quests I didnt saw tho).

**Comment by Cefiro-Caecias** [comment]
Fixed.
