### ISSUE TITLE
[Zone+Quest] Stormscale Cavern - stormhelm zone

### ISSUE THREAD

**Issue by MicuRazvan-Florentin2E3** [GuabinaCore/WoWKoi#2278]
Are several problems with this zone:
-The ads and the NPCs you have to save respawn time is to high, is over 2minutes
-The ads are doing to much damage to players, got killed instantly by 3 little dragons( before this part of the questline I could easly agro 10 ads without problems).
-Inside the cave you can find only "Storm Drake Whelp" which are the little dragons but you cant find any "Adolescent Storm Drake" which are the big dragons.
There 3 problems are making doing the "light rode" almost impossible.

-The quest "light rode" is also bugged, if you die you lose the progress bar for the crystal that you have to charge and if you abandon the quest, you cant take it back and after 1minut of walking you get randomly the next quest from questline which is "Signal boost"

Link for the quest
https://www.wowhead.com/spell=210689/lightning-rod

**Comment by Cefiro-Caecias** [comment]
Fixed.
