### ISSUE TITLE
[Quest] Havi's test -minor

### ISSUE THREAD

**Issue by MicuRazvan-Florentin2E3** [GuabinaCore/WoWKoi#2279]
Links:
https://www.wowhead.com/quest=38331/havis-test
![WoWScrnShot_041521_220652](https://user-images.githubusercontent.com/79265627/114926100-a34cab00-9e38-11eb-8dd5-e5cb96ccda9f.jpg)

What is happening:
when you throw the vegetables to the pot, you can move around.

What should happen:
You are not supposed to move while throwing the vegetables.

**Comment by Cefiro-Caecias** [comment]
Fixed.
