### ISSUE TITLE
Quest - A Peaceful World 

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2281]
**Links:**
https://www.wowhead.com/quest=41086/a-peaceful-world

**What is happening:**
NPC Iron-Body Ponshu doesn't have the interaction option to give in the quest.

![WoWScrnShot_041521_134632](https://user-images.githubusercontent.com/64436148/114940725-861cda00-9e42-11eb-96db-897cf5935ed8.jpg)
![WoWScrnShot_041521_233039](https://user-images.githubusercontent.com/64436148/114940800-9b920400-9e42-11eb-923b-0bf43de3d267.jpg)

**Comment by Exlyss** [comment]
EDIT: the quest can be given in at Chen Stormsnout, that is the STARTER NPC of this quest, not the FINISHER of the quest.
Located here.
![WoWScrnShot_041821_160424](https://user-images.githubusercontent.com/64436148/115148420-c3aa7e80-a05f-11eb-849f-84574be1f55c.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
