### ISSUE TITLE
Pluma espectral - Cascara de huevo espectral - Objetos

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2282]
**Links:**
https://es.wowhead.com/object=269775/pluma-espectral
https://es.wowhead.com/object=269796/cáscara-de-huevo-espectral
from WoWHead or our Armory

Lo que sucede:
al usar la pluma pluma espectral invoca al grifo espectral perdido, solo funciona una vez , si lo vuelves usar la pluma cuando aparece otra vez, ya no invoca nada..
lo mismo pasa con la cascara de huevo espectral, invoca a gon. una vez usado. el objeto desaparece
y vuelve aparecer tiempo despues, al volver usar la cascara de huevo ya no invoca nada.. 

Lo que debería suceder:
ambos objetos una vez usado, invocas sus respectivos NPC(gon y grifo espectral perdido), al terminar de domesticar desaparece  los objetos, tiempo pasa y los objetos aparecen , al usarlo debería invocar a los NPC (gon y grifo espectral perdido). los objetos siempre deben funcionar..

**Comment by Cefiro-Caecias** [comment]
Reparados, disponible en el próximo update. Ambos objetos sólo podrán ser vistos y clickeados por Hunters, y tendrán respawn de 2 horas, reutilizables.
