### ISSUE TITLE
[Tyce] - Perdida de proceso de juego al Relogear

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2283]
Links:

from WoWHead or our Armory

Lo que pasa:
un problema de perdida de progreso e el juego, al relogear o al salirme del juego, aveces mi PJ aparece en una zona diferente donde lo deje..ejemplo ayer me desconecte del juego, dejando mi PJ en Vallesfreno kalimdor.. al conectarme al juego al dia siguiente, mi Pj estaba en Tormenheim islas abruptas, ayer estaba en esa zona horas antes de llegar a kalimdor. se perdio minutos de progreso de juego. esto me pasa casi siempre al relogear  o desconectarme 
otro ejemplo cuando hacia misiones en Monte alto - relogie porque la mision que hacia estaba bug, estaba frente al lugar donde se desarrolla la mision. me desconecto y vuelvo a conectar al juego, mi Pj estaba en el maestro de vuelo, deberia estar en la mision, yo antes de hacer las misiones estaba en maestro de vuelo, la cuestion es que se perdio proceso de juego

Lo que debería suceder:
No deberia perderse proceso en el juego al desconectarme o relogear

**Comment by Cefiro-Caecias** [comment]
@ShikoSCS, he notado que este defecto ocurre luego de utilizar vehicles en varias quests que te cambian de zona, como si el sistema no actualizara correctamente tu información de posicionamiento por haber subido a un vehicle.
