### ISSUE TITLE
La reina Esmeralda - Mision - Cadena de misiones: Hacia la pesadilla - Val'sharah

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2284]
**Links:**
https://es.wowhead.com/quest=38377/la-reina-esmeralda
from WoWHead or our Armory

Lo que sucede:
al tomar la misión , debemos hacer click en el dialogo de Malfurion, pero no pasa nada.

Lo que debería suceder:
al click en el dialogo malfurion, debe aparecer una escena donde vemos Cenarius en el suelo, al termino de la escena. Ysera dice unos diálogos, malfurion esta en otro lugar.. y la mision esta lista para entregar
Link de youtube de la misión: https://www.youtube.com/watch?v=rgjscQ-cZbk

**Comment by Cefiro-Caecias** [comment]
Reparada, disponible en el próximo update.
