### ISSUE TITLE
Favor de cuidador de zoo - Encantamiento

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2286]
**Links:**
https://es.wowhead.com/item=144346/favor-del-cuidador-de-zoo
from WoWHead or our Armory

**Lo que sucede:**
no funciona el encantamiento, nunca arroja https://es.wowhead.com/item=144345/montón-de-obsequios-para-mascota

**Lo que debería suceder:**
deberia arrojar https://es.wowhead.com/item=144345/montón-de-obsequios-para-mascota cuando mate adds, tiene un porcentaje de caida...

**Comment by Cefiro-Caecias** [comment]
Fixed.
