### ISSUE TITLE
[Quest] Take me to your leader

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2287]
**Links:**

https://www.wowhead.com/quest=40632/take-me-to-your-leader

**What is happening:**

- When accepting the quest, a message " That quest is not available to your race." is displayed on chat (Horde side). Ingame ID is correct.
- The quest doesn't trigger proper phase. Quest area is empty, therefore cannot be turned in.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
