### ISSUE TITLE
Misiones - Montura de clase: Cazador

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2288]
**Links:**
https://es.wowhead.com/quest=46336/una-oportunidad-de-oro
https://es.wowhead.com/quest=46337/noche-de-las-tierras-inexploradas
from WoWHead or our Armory

**Lo que sucede:**
ya saque el logro A tumba abierta deberia desbloquearse la cadena de misiones: Montura de clase: cazador
que te da las siguientes misiones
https://es.wowhead.com/quest=46336/una-oportunidad-de-oro
https://es.wowhead.com/quest=46337/noche-de-las-tierras-inexploradas

**Lo que debería suceder:**
esta mision debería aparecer o activarse al terminar la cadenas de misiones la costa Abrupta y completar el logro "A tumba abierta"
https://es.wowhead.com/achievement=11546/a-tumba-abierta

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
