### ISSUE TITLE
Quest - Moments of Reflection

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2289]
**Links:**
https://www.wowhead.com/quest=49077/moments-of-reflection

**What is happening:**
The crystal on top of the bench is missing.

**What should happen:**
There should be a crystal on the bench to complete the last segment of the quest.

![WoWScrnShot_041821_220533](https://user-images.githubusercontent.com/64436148/115159223-5e23b580-a092-11eb-8aee-fb36abfa6244.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
