### ISSUE TITLE
Monk Quest - Stolen Knowledge

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2290]
**Links:**
https://www.wowhead.com/quest=41039/stolen-knowledge

**What is happening:**
Stormforged Grapple Hook can't be obtained.

**What should happen:**
After clicking on it it should be obtained as an item.

![WoWScrnShot_041821_233937](https://user-images.githubusercontent.com/64436148/115161880-5e2ab200-a0a0-11eb-9a7f-930967230094.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
