### ISSUE TITLE
Lightforged Draenei Allied Race and Uuna Questlines - Escenario - Alied Race 

### ISSUE THREAD

**Issue by Nephilimkoi** [GuabinaCore/WoWKoi#2291]
**Links:**
https://www.wowhead.com/quest=49266/forge-of-aeons
https://es.wowhead.com/spell=254817/liberar-a-tpaartos
https://www.wowhead.com/news/lightforged-draenei-allied-race-and-uuna-questlines-broadcast-text-spoilers-277578
from WoWHead or our Armory

**What is happening:**

Basically during the end of the combat Tpaartos should use his spell to finish it. but. even when the spell do trigger it doesnt do anything at all

![WoWScrnShot_040821_200805](https://user-images.githubusercontent.com/73371905/115180961-d004fa80-a0a4-11eb-8fce-66b9b44df615.jpg)
![WoWScrnShot_040821_201002](https://user-images.githubusercontent.com/73371905/115180963-d1cebe00-a0a4-11eb-86b3-198cb2515293.jpg)
![WoWScrnShot_040821_202810](https://user-images.githubusercontent.com/73371905/115180965-d3988180-a0a4-11eb-9a52-ea3806142ee9.jpg)

**What should happen:**

Tpaartos should unleash his fist. and finish the combat. making him drop this dialog

Fareeya: T'paartos... You confronted your fears... your failings... and have been reborn.
Fareeya: We all have darkness inside us. It is no easy thing to face.
T'paartos: T'paartos realizes this now.

**Comment by ShikoSCS** [comment]
Done!
