### ISSUE TITLE
[Quest] The Story of Huin

### ISSUE THREAD

**Issue by MicuRazvan-Florentin2E3** [GuabinaCore/WoWKoi#2292]
Links:
https://www.wowhead.com/quest=40167/the-story-of-huln

![WoWScrnShot_041921_152825](https://user-images.githubusercontent.com/79265627/115236339-f0c06500-a123-11eb-9716-30f212166dcb.jpg)

What is happening:
After the cinematic you cant complete the quest. I tried to skip the cinematic once and once without skiping, in both cases couldnt end the quest, The NPC "Highmountain Spiritwalker" doesnt move on his new location 

What should happen:
After the cinematic the NPC should move to a new location(which is the location when you take the quest from) .

**Comment by Exlyss** [comment]
Just done this quest, to fix the problem you just need to relog.

![WoWScrnShot_041921_165836](https://user-images.githubusercontent.com/64436148/115257568-806c1080-a130-11eb-99f1-5ac5078e561d.jpg)

**Comment by MicuRazvan-Florentin2E3** [comment]
> Just done this quest, to fix the problem you just need to relog.
> 
> ![WoWScrnShot_041921_165836](https://user-images.githubusercontent.com/64436148/115257568-806c1080-a130-11eb-99f1-5ac5078e561d.jpg)

This works only if you are the only one in that zone, bcs you reset the zone and the NPC gets fixed, if there will be more than 1 player it will be stack untill everyone will leave that zone.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
