### ISSUE TITLE
[Tyce] - Achievement - Glory of the Pandaria Raider

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2293]
**Links:**
https://www.wowhead.com/achievement=6932/glory-of-the-pandaria-raider
https://www.wowhead.com/achievement=6823/must-love-dogs
https://www.wowhead.com/achievement=6730/heroic-grand-empress-shekzeer
https://www.wowhead.com/achievement=6922/timing-is-everything
https://www.wowhead.com/achievement=6824/face-clutchers
https://www.wowhead.com/achievement=6933/whos-got-two-green-thumbs

Achievement 6823, Must Love Dogs: killing the boss Stone Guard with dogs companions doesn't award the achievement, tested with https://www.wowhead.com/item=127705/lost-netherpup and https://www.wowhead.com/item=140320/corgnelius.

Achievement 6730, Heroic: Grand Empress Shek'zeer: the boss gets bugged while going into Stage Two: The Empress Retreats!, causing her to not come back and thus making the achievement impossible to obtain unless the player is able to oneshot the boss.

Achievement 6922, Timing is Everything: linked to achievement 6730 bug, as the boss goes into Stage Two, it spawns the Kor'thik Reavers needed for the achievement, but as the boss doesn't come back it's impossible to obtain this achievement.

Achievement 6824, Face Clutchers: Parasitoid Sha isn't spawned at any time during the bossfight.

Achievement 6933, Who's Got Two Green Thumbs?: as the bossfight ends, even if the Enchanted Plant is still alive it doesn't award the achievement.

Achievement 6730 and 6922
![WoWScrnShot_040621_162135](https://user-images.githubusercontent.com/64436148/113727259-4133cd80-96f5-11eb-912d-0b3872dfbda0.jpg)
![WoWScrnShot_040621_162211](https://user-images.githubusercontent.com/64436148/113727303-4abd3580-96f5-11eb-81fb-176337d55ae9.jpg)

Achievement 6933
![WoWScrnShot_041921_144713](https://user-images.githubusercontent.com/64436148/115241528-3b8cad80-a121-11eb-8b7b-07fcaeb8e478.jpg)

**Comment by Arkanheal** [comment]
Achievement 6823, Must Love Dogs: Corgnelius doesn't count towards this achievement (see WH comments)
