### ISSUE TITLE
[Tyce] - Spells para Quest Gatekeeper's Challenge: Cunning

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#2298]
https://www.wowhead.com/quest=47685/gatekeepers-challenge-cunning

color mixes don't work properly to get the chests. Right now u don'T need to mix that colors . u can click chest without colors

**Comment by Cefiro-Caecias** [comment]
At the moment, I can't rebuild this blizzlike quest, as it relies on repairing many spells that control their colors and combinations. It is in less than the Core Devs.

**Comment by Cefiro-Caecias** [comment]
@ShikoSCS, para esta quest se requieren reparar varias spells de colores, así que queda en tus manos es aparte.

**Comment by Arkanheal** [comment]
Info on this @Sefrenia-Caecias ?
