### ISSUE TITLE
[Saitama] - Spell Hunter Autoshots

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#23]
Class: Hunter
Spec: Any
Spell: [Auto shot](https://www.wowhead.com/spell=6603/auto-attack)
**What is happening:**
Sometimes, [auto shots](https://www.wowhead.com/spell=6603/auto-attack) randomly are canceled, without the Hunter stopping them.
**What should happen:**
[Auto shots](https://www.wowhead.com/spell=6603/auto-attack) should only stop when the Hunter purposefully stops autoing.

**Comment by login6710** [comment]
Fixed
