### ISSUE TITLE
Mobs in Mulgore are not scaling

### ISSUE THREAD

**Issue by aaberant** [GuabinaCore/WoWKoi#230]
**Links:**
https://imgur.com/zbvVTTE
**What is happening:**
The mobs are not scaling with my level

**What should happen:**
They should scale with my level
![eadf](https://user-images.githubusercontent.com/62454214/77217330-e4ac4300-6ade-11ea-9f49-ecfdfab64835.PNG)

**Comment by Cefiro-Caecias** [comment]
Palemane Tanner, Palemane Skinner and Palemane Poacher, fixed. Available in the next update.
