### ISSUE TITLE
[Quest] Given to Corruption

### ISSUE THREAD

**Issue by sebastian1322** [GuabinaCore/WoWKoi#2303]
**Links:**

https://www.wowhead.com/quest=38675/heart-of-the-nightmare
https://www.wowhead.com/quest=41749/given-to-corruption

**What is happening:**
after finishing heart of the nightmare quest the next quest doesn't appear on the archdruid of the lore

**What should happen:**
it should appear after tyrande's and archdruid interaction

**Comment by Cefiro-Caecias** [comment]
Fixed.
