### ISSUE TITLE
Cámara de las celadoras: Hacia la Cámara de las Celadoras

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2304]
**Links:**
https://es.wowhead.com/quest=44261/cámara-de-las-celadoras-hacia-la-cámara-de-las-celadoras
from WoWHead or our Armory

**Lo que sucede:**
objeto que otorga la mision:
https://es.wowhead.com/item=141188/yelmo-de-celador-roto
Al usar el yelmo de celador roto, nos otorga una mision "Cámara de las celadoras: Hacia la Cámara de las Celadoras" esta mazmorra se desarrollora en la dicha mazmorra y nos pide como objetivo matar a Cordana.
lo que sucede, es que al matar al Cordana, la mision no reconoce el objetivo y la mision no se completa, probé realizando la misión en otras dificultades de la mazmorra.

**Lo que debería suceder:**
Se supone que al matar a Cordana el ultimo jefe de cámara de las Celadoras, esta debería contarme como objetivo y la misión debería completarse ..

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update. No olvides borrar Cache, o no verás los cambios.
