### ISSUE TITLE
Proles de falcosaurios - Misiones de cada prole

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2305]
**Links:**
Prole Contemplasangre: https://es.wowhead.com/npc=115787/prole-de-contemplasangre
https://es.wowhead.com/quest=44990/criar-a-tu-contemplasangre
si eres (Alianza)
https://es.wowhead.com/quest=44991/el-olor-de-los-draenei
si eres (Horda)
https://es.wowhead.com/quest=44993/el-olor-de-los-elfos-de-sangre
https://es.wowhead.com/quest=44996/lección-de-caza-maligno-de-maná-erudito
https://es.wowhead.com/quest=44998/aliados-en-azsuna
https://es.wowhead.com/quest=45000/equipo-con-contemplasangre
https://es.wowhead.com/quest=45002/presa-peligrosa
https://es.wowhead.com/quest=45004/lección-de-caza-plumarrey-volantón
https://es.wowhead.com/quest=45006/la-facción-desfavorable
https://es.wowhead.com/quest=45008/estrechar-lazos-con-tu-contemplasangre
https://es.wowhead.com/quest=45010/lección-de-caza-correpacho-joven
https://es.wowhead.com/quest=45008/estrechar-lazos-con-tu-contemplasangre
https://es.wowhead.com/quest=45014/lección-de-caza-araña-vil
https://es.wowhead.com/quest=45016/lección-de-trabajo-en-equipo-skorpyron
https://es.wowhead.com/quest=45018/pelea-en-equipo-con-contemplasangre
https://es.wowhead.com/quest=45020/reunión-de-contemplasangres

Prole Garfafilada: https://es.wowhead.com/npc=115786/prole-de-garfafilada
https://es.wowhead.com/quest=44989/criar-a-tu-garfafilada
si eres (Alianza)
https://es.wowhead.com/quest=44992/el-olor-de-los-elfos-de-la-noche
si eres (Horda)
https://es.wowhead.com/quest=44994/el-olor-de-los-no-muertos
https://es.wowhead.com/quest=44995/lección-de-caza-zancudo-primaveral
https://es.wowhead.com/quest=44997/aliados-en-valsharah
https://es.wowhead.com/quest=44999/equipo-con-garfafilada
https://es.wowhead.com/quest=45001/presa-destructiva
https://es.wowhead.com/quest=45003/lección-de-caza-larva-de-terror
https://es.wowhead.com/quest=45005/la-facción-poco-amigable
https://es.wowhead.com/quest=45007/estrechar-lazos-con-tu-garfafilada
https://es.wowhead.com/quest=45009/lección-de-caza-colanillo-caoba
https://es.wowhead.com/quest=45011/lección-de-trabajo-en-equipo-dresaron
https://es.wowhead.com/quest=45013/lección-de-caza-revoloteador-del-valle
https://es.wowhead.com/quest=45015/lección-de-trabajo-en-equipo-xavius
https://es.wowhead.com/quest=45017/pelea-en-equipo-con-garfafilada
https://es.wowhead.com/quest=45019/reunión-de-garfafiladas

Prole Plumanívea
https://es.wowhead.com/quest=44948/criar-a-tu-plumanívea
si eres (Alianza)
https://es.wowhead.com/quest=44949/el-olor-de-los-humanos
si eres (Horda)
https://es.wowhead.com/quest=44971/el-olor-de-los-orcos
https://es.wowhead.com/quest=44950/lección-de-caza-lechuzas-gavilanas-del-norte
https://es.wowhead.com/quest=44953/aliados-en-monte-alto
https://es.wowhead.com/quest=44954/equipo-con-plumanívea
https://es.wowhead.com/quest=44956/presa-letal
https://es.wowhead.com/quest=44957/lección-de-caza-castor-colapincho
https://es.wowhead.com/quest=44958/la-facción-hostil
https://es.wowhead.com/quest=44959/estrechar-lazos-con-tu-plumanívea
https://es.wowhead.com/quest=44960/lección-de-caza-caracola-valvalodo
https://es.wowhead.com/quest=44961/lección-de-trabajo-en-equipo-naraxas
https://es.wowhead.com/quest=44962/lección-de-caza-cigarra-marina-dorsocoral
https://es.wowhead.com/quest=44967/lección-de-trabajo-en-equipo-ursoc
https://es.wowhead.com/quest=44968/pelea-en-equipo-con-plumanívea
https://es.wowhead.com/quest=44969/reunión-de-plumaníveas

Prole Picoterrible
https://es.wowhead.com/quest=44973/criar-a-tu-picoterrible
si eres (Alianza)
https://es.wowhead.com/quest=44974/el-olor-de-los-enanos
si eres (Horda)
https://es.wowhead.com/quest=44975/el-olor-de-los-tauren
https://es.wowhead.com/quest=44976/lección-de-caza-taipan-rosa
https://es.wowhead.com/quest=44977/aliados-en-tormenheim
https://es.wowhead.com/quest=44978/equipo-con-picoterrible
https://es.wowhead.com/quest=44979/presa-nefasta
https://es.wowhead.com/quest=44980/lección-de-caza-aparición-diminuta
https://es.wowhead.com/quest=44981/la-facción-poco-amable
https://es.wowhead.com/quest=44982/estrechar-lazos-con-tu-picoterrible
https://es.wowhead.com/quest=44983/lección-de-caza-aguilucho-dorado
https://es.wowhead.com/quest=44984/lección-de-trabajo-en-equipo-fenryr
https://es.wowhead.com/quest=44985/lección-de-caza-castor-tormentogolpeado
https://es.wowhead.com/quest=44986/lección-de-trabajo-en-equipo-krosus
https://es.wowhead.com/quest=44987/pelea-en-equipo-con-picoterrible
https://es.wowhead.com/quest=44988/reunión-de-picoterribles

from WoWHead or our Armory

**Lo que sucede:**
las misiones de las proles estan funcionando mal, se saltean.. no hay orden . y si logras hacer la mision en desorden se bugea todo, y dejan de darte misiones

**Lo que debería suceder:**
Una vez que obtengas tu prole, invocalo para que comience una cadena de misiones para ayudarlo a crecer y hacerse fuerte, y eventualmente ganar una montura. Solo podrás completar una misión por día, ya que cada actividad hará que los pequeños se cansen. (Las misiones se reinician con el reinicio diario).
Cada prole da 15 misiones.. están ordenadas en orden

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
