### ISSUE TITLE
Misiones de mundo de suramar - bug visual menor

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2306]
**Links:**
https://es.wowhead.com/quest=44817/agitar-al-enjambre
https://es.wowhead.com/quest=44811/ayuda-en-camino
https://es.wowhead.com/quest=44801/defender-shalaran
https://es.wowhead.com/quest=44805/donde-está-la-acción
from WoWHead or our Armory

**Lo que sucede:**
estas misiones no aparecen en el mapa como objetivos, se activan cuando uno pasa por la zona..
como ven el mapa la mision no aparece en el mapa.. solo en el minimapa cuando uno llega a la zona
![image](https://user-images.githubusercontent.com/81131460/115448703-9f75ab80-a1df-11eb-9a72-a631134ccc22.png)

**Lo que debería suceder:**
las misiones de mundo deberían visualizarse en el mapa, para que uno se acerque a la zona y pueda realizar dichas misiones..

**Comment by Cefiro-Caecias** [comment]
Bajo investigación.
