### ISSUE TITLE
[Quest] A Better Future

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2307]
**Links:**

https://www.wowhead.com/quest=41916/a-better-future

**What is happening:**

[Shal'dorei Insurgent](https://www.wowhead.com/npc=115279/shaldorei-insurgent) can be clicked multiple times for additional credits.

**What should happen:**

One click, one credit.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
