### ISSUE TITLE
[Tyce] - Spell Monk: Fists of furry

### ISSUE THREAD

**Issue by MicuRazvan-Florentin2E3** [GuabinaCore/WoWKoi#2313]
Links:

https://www.wowhead.com/spell=113656/fists-of-fury

What is happening:
When your target dies before the channeling is over, it breaks the spell.

What should happen:
This spell should be finished at the end of the duration or when cancelled by using another spell.

**Comment by lemmiwinkss** [comment]
As of 05/09/2021 this is still an issue. It has not been fixed.

**Comment by Tarkinug** [comment]
Some update the spell finishes we just can't see it. The dam goes on but the visual doesn't also the channeling bar breaks

**Comment by Arkanheal** [comment]
Duplicate of #3269
