### ISSUE TITLE
[Quest] An Offering of Shadow

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#2314]
https://www.wowhead.com/quest=48560/an-offering-of-shadow

1 :  ![image](https://user-images.githubusercontent.com/82822767/115736409-f0c69c00-a393-11eb-973e-810f1532ea63.png)
2 : ![image](https://user-images.githubusercontent.com/82822767/115736494-0045e500-a394-11eb-83a0-bb6e1728b0be.png)

if i try to essence of shadow ( pics 1) giving me this (2) still im staying close to netherlight crucible .

**Comment by Exlyss** [comment]
If I may add, the Crucible at Mac'Aree is visually bugged, not showing the light essence being present.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
