### ISSUE TITLE
[Quest] The Seal's power

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2315]
**Links:**

https://www.wowhead.com/quest=44833/the-seals-power#comments

**What is happening:**

The quest can be completed, although, the event is really clunky. [Arcanist Valtrois](https://www.wowhead.com/npc=115524/arcanist-valtrois) has her dialogue option in russian. When her event starts she gets stuck on a step. IT takes her ~30 seconds to get to the ley line. [Ley Line Channeler](https://www.wowhead.com/npc=116421/ley-line-channeler) doesn't do anything. 

![image](https://user-images.githubusercontent.com/63166930/115736735-cec91b80-a38b-11eb-9111-5b189f90bb54.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Completely rebuilt quest, blizzlike. Available in the next update.
