### ISSUE TITLE
[Tyce] - Spells Detector (203761,298085,230368)

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2317]
**Links:**

https://www.wowhead.com/spell=203761/detector
https://www.wowhead.com/spell=298085/detector
https://www.wowhead.com/spell=230368/detector

**What is happening:**

The ability doesn't uncover [Masquerade](https://www.wowhead.com/spell=202477/masquerade).

![image](https://user-images.githubusercontent.com/63166930/115739814-86f7c380-a38e-11eb-86f7-5112d238966f.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
