### ISSUE TITLE
Monk Scenario - The Council of Masters

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2319]
**Links:**
https://www.wowhead.com/npc=98011/infernal-destroyer#abilities

**What is happening:**
Dying in the first phase of the scenario has Master Hight unavailable to continue with the scenario.
Also, continuing the other parts of the scenario is a bit random, as it doesn't count doing the tasks and you just end up with finishing it.

**What should happen:**
Even after dying you should be able to talk to him.
Also, the mob attacking should be way less powerful, because like this is almost impossible for a level 100 to even begin his class hall.
![WoWScrnShot_042221_174604](https://user-images.githubusercontent.com/64436148/115744422-d809b680-a392-11eb-8c1f-0f8c6431ab1c.jpg)
![WoWScrnShot_042221_173849](https://user-images.githubusercontent.com/64436148/115744496-e788ff80-a392-11eb-93f0-e581a245a1eb.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed.
