### ISSUE TITLE
[Arthas] - Quest Journey's End - EPL

### ISSUE THREAD

**Issue by Spewee** [GuabinaCore/WoWKoi#232]
**Links:**
https://www.wowhead.com/quest=27527/journeys-end

from WoWHead or our Armory

**What is happening:**
if you abandon the quest once back at lights hope chapel, the caravan disappears and does not reappear back at lights hope, preventing you from accepting the quest again and completing Eastern plaguelands quests.

**What should happen:**

The caravan should appear at lights hope chapel after the quest:
https://www.wowhead.com/quest=27526/gidwins-fate-revealed
and remain there ready to pick up the follow up; Journey's End

**Comment by LKArthas** [comment]
Journeys end should be Taken from Godwin at the ziggurat instead on lights hope
