### ISSUE TITLE
[Quest] Breaching hte sanctum

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2323]
**Links:**

https://www.wowhead.com/quest=44719/breaching-the-sanctum

**What is happening:**
- The scenario seems to be missing markers on the minimap, making it very hard to navigate or finding the direction you must head to.
- [Andaris Narassin](https://www.wowhead.com/npc=114915/andaris-narassin#abilities) is missing a shield.
- [Archmage Khadgar](https://www.wowhead.com/npc=115367/archmage-khadgar) doesn't have the option to turn in the quest.
- Scenarios needs some overall polishing but these above are the uppermost.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later.
