### ISSUE TITLE
[Artifact Quest] [The Sword of Kings]

### ISSUE THREAD

**Issue by Hrogdar** [GuabinaCore/WoWKoi#2324]
Links:
https://www.wowhead.com/quest=41105/the-sword-of-kings

from WoWHead or our Armory

Lo que sucede: 
https://www.wowhead.com/quest=41105/the-sword-of-kings
La misión te pide ir a la tumba de Tyr en Tirisfal Glades por medio de la Valkyria, pero al ir no aparece ningún npc, el escenario no se actualiza. 

Lo que debería suceder: 
El escenario debería actualizarse y aparecer los NPC's.

**Comment by Cefiro-Caecias** [comment]
Reparado. La quest tenía errores de objetivos y traducciones. Ahora ya podrás acceder a la zona correcta utilizando a Aerylia en Bastión Celestial, lo que también figurará como primer objetivo de la quest, tal y como debe ser. Disponible en el próximo update.
