### ISSUE TITLE
The Scythe of Souls

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2325]
**Links:**
https://www.wowhead.com/quest=37660/the-scythe-of-souls
https://www.wowhead.com/npc=89673/questioner-arevnaal

**What is happening:**
The mob and his summons do a lot more damage than they should. The quest seems impossible to do as a new level 100 with starting equipment.

**What should happen:**
He should do less damage.

Combat log with the damage he does.
![WoWScrnShot_042221_194218](https://user-images.githubusercontent.com/64436148/115761927-2e7ef100-a3a3-11eb-8ef8-6778f73ebe9e.jpg)

**Comment by Cefiro-Caecias** [comment]
Repaired. It will now cast "Piercing Gaze" at 20% HP, just 1 time. Applied other adjustments to his combat sequence. Also his minions. Available in the next update.
