### ISSUE TITLE
Worgen The last Stand

### ISSUE THREAD

**Issue by ApatheticVirgin** [GuabinaCore/WoWKoi#2327]
**Links:**
https://www.wowhead.com/quest=14222/last-stand

from WoWHead or our Armory

**What is happening:**
I was stuck in the same city but couldn't go to the next place, so I was stuck after the cutscene happened. Had to go to the quest area manually

**What should happen:**
Apparently judging from the next quest, I was supposed to be spawned at a new location with my new transformation and things but nothing happened.

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, when the area is rebuilt.

**Comment by ApatheticVirgin** [comment]
Ah alright, this is related to the quest issues correct?
