### ISSUE TITLE
Assasination Rouge -  Artifact scenario

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2329]
https://www.wowhead.com/acquiring-the-kingslayers-assassination-rogue-artifact

**What is happening:**

**At current state, the scenario is completable, although, the majority of steps is being brute-forced(sprint to destination-> vanish, wait 3min cooldown -> repeat). Fixing all the issues below should provide smooth and blizzlike feeling**

- [Commander Althea Ebonlocke <Leader of The Night Watch>](https://www.wowhead.com/npc=107837/commander-althea-ebonlocke) doesn't attack and is missing her ablities.
- At the Darkshire Town Hall entrance/in the center of Darkshire, there is an "invisible thing" that attacks you. It's damage is not shown in the chat. 
![image](https://user-images.githubusercontent.com/63166930/115763285-9c77e800-a3a4-11eb-862e-8880e5de7985.png)

During [Unseen Blade](https://www.wowhead.com/quest=42504/the-unseen-blade) scenario:
- At the very beggining [Garona](https://www.wowhead.com/npc=107979/garona-halforcen) should be stealthed.
- [Stormwind City Guard](https://www.wowhead.com/npc=108059/stormwind-city-guard)s are stationary instead of patrolling. They are "invalid target" and I cant use skill on them. They should behave as ordinary hostile npc.
- Scenario objectives are missing map markers. 
- [Stormwin City Patroller](https://www.wowhead.com/npc=108058/stormwind-city-patroller) stealth detection ability missing. I couldn't find the ability ID.
- According to the videos on YB, detection range from all the NPC in the area (beside Stormwind City Patrollers" should be greatly reduced.
- [Lucas Severing](https://www.wowhead.com/npc=108399/lucas-severing) event on the bridge missing.
- [Fatigued Ritualist](https://www.wowhead.com/npc=108333/fatigued-ritualist) missing his ablity, the trigger for the event behind him is located in front of him.
- [The Kingslayers](https://www.wowhead.com/object=251107/the-kingslayers) have incorrect object model.
![image](https://user-images.githubusercontent.com/63166930/115772961-021da180-a3b0-11eb-97d1-47f4412b5724.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, when the area is rebuilt.
