### ISSUE TITLE
Trail of the Crypt - EPL

### ISSUE THREAD

**Issue by Spewee** [GuabinaCore/WoWKoi#233]
**Links:**
https://www.wowhead.com/quest=27464/argent-call-the-trial-of-the-crypt

from WoWHead or our Armory

**What is happening:**
The killing of Lord Raymond George during the quest is supposed to grant Revered reputation with "Argent Dawn" but it does not. Am now stuck at neutral when I should be Revered

**What should happen:**

Lord Raymond George should give 21000 argent dawn rep. He does not during this quest

**Comment by Cefiro-Caecias** [comment]
There is no bug present. Only 500 reputation points are earned with this quest, as indicated by wowhead.

**Comment by Spewee** [comment]
Sorry, but you are correct that it does reward 500 xp with The Argent Crusade however, my bug report was in reference to the "The Argent Dawn" faction; https://www.wowhead.com/faction=529/argent-dawn which should bring the player up to revered after the quest.

**Comment by Cefiro-Caecias** [comment]
I see... Re-fixed. Available in the next update ;)
