### ISSUE TITLE
[Quest] Injection of Power - rouge artifact

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2330]
**Links:**

https://www.wowhead.com/quest=40995/injection-of-power

**What is happening:**

Dunno if thats about the quest or the artifact wep itself (The kingsmaker in this situation), although, I did not receive any artifact power to complete the quest.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
There is no bug present. You must have the Artifact Weapon equipped when you take the quest, in order to receive the AP bonus for completing the quest. Try again.
