### ISSUE TITLE
Monk Scenario - Mistweaver Artifact

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2331]
**What is happening:**
At stage 4, the 5 NPC should fight the boss together, but only Taran Zhu is actually fighting.

**What should happen:**
They should all take part to the fight.

![WoWScrnShot_042221_221019](https://user-images.githubusercontent.com/64436148/115780190-2336c000-a3b9-11eb-8414-f066f92e9651.jpg)

**Comment by Exlyss** [comment]
Also, at the end of the scenario, the quest https://www.wowhead.com/quest=43973/two-paths-two-weapons doesn't get completed, making impossible getting the third Artifact.

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, when the area is rebuilt.
