### ISSUE TITLE
[Quest] The Farmsteads

### ISSUE THREAD

**Issue by kiazmey** [GuabinaCore/WoWKoi#2332]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=38644/the-farmsteads
**What is happening:**
When you go Heathrow house, find Penelope and speak with her nothing happens..

Video:
https://www.youtube.com/watch?v=PWRuLooiDZI

**Comment by kiazmey** [comment]
Quest works if you first go to Heathrow house which is not chronological order

**Comment by Cefiro-Caecias** [comment]
I just tested the quest, and it worked flawlessly. I went for Penelope last, and I was in trouble.
