### ISSUE TITLE
Subtlety Rouge - Artifact scenario

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2333]
**What is happening:**

1. Quest [A matter of Finesse](https://www.wowhead.com/quest=41920/a-matter-of-finesse):
  -  [Archmage Celindra](https://www.wowhead.com/npc=105400/archmage-celindra) missing detection event.
2. Quest [Closing In](https://www.wowhead.com/quest=41921/closing-in):
  - [Valeera Sanguinar](https://www.wowhead.com/npc=98102/valeera-sanguinar) movement across questing area and dialogue missing.
3. Quest [Traitor!](https://www.wowhead.com/quest=41922/traitor):
  - [Valeera Sanguinar](https://www.wowhead.com/npc=98102/valeera-sanguinar) movement and dialogue missing.
  - [Val"zuun](https://www.wowhead.com/npc=105333/valzuun) dialogue and animation missing.
4. Quest/scenario [Fangs of the Devourer](https://www.wowhead.com/quest=41924/fangs-of-the-devourer):
  - [Akaari Shadowgore](https://www.wowhead.com/npc=105536/akaari-shadowgore) missing dialogues across quest objectives.
  - _**Legion Cage(did not find the ID) can be opened without a key(very important, as doing thing not in order will break the scenario)**_ !!!!!!!!!!!!!!!!!!
  - "Disarmed" effect missing. It should be cleared after click on Weapons cache(did not find ID) _credit is granted after clicking the cashe, so it's only cosmetic value_

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, when the area is rebuilt.
