### ISSUE TITLE
Warlock Scenario - Destruction

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2334]
Nothing else to say except for the whole thing is broken: to go on with the scenarios i had to get help from Nephilim with killing and respawning the NPCs for 5+ times each one, because they would get bugged and either not complete that particular scenario, or not even start the dialogue as I wasn't there. 
Also the Imps are a bit overtuned.

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, when the area is rebuilt.
