### ISSUE TITLE
La senda de Los Cicatriz del terror - Sede - Brujo

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2335]
**Links:**
https://es.wowhead.com/quest=40824/la-senda-de-los-cicatriz-del-terror
from WoWHead or our Armory

**lo que sucede:**
la mision funciona bien, solo que el npc que te da la mision no cambia de lugar como deberia..como ven el npc se queda en su lugar donde se inicia la mision y no donde deberia terminar
![image](https://user-images.githubusercontent.com/81131460/115791488-16e93d80-a38e-11eb-8538-549922f4e26d.png)

**Lo que deberia suceder:**
el npc al terminar la mision deberia aparecer cerca del tablon de misiones de los campeones de sede.

**Comment by Cefiro-Caecias** [comment]
Se hará blizzlike más adelante, cuando se reconstruya la zona.
