### ISSUE TITLE
Warlock Scenario - Demonology

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2336]
After killing literally 4 mobs on the road to the Skull of the Man'ari NPC, as I passed into a gate, I got teleported to Warlock Class Hall, that I hadn't unlocked yet, with the Artifact in the bag.

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, when the area is rebuilt.

**Comment by LKArthas** [comment]
Fixed Now
