### ISSUE TITLE
Misiones de Suramar -capitulo 3,4,5,6,7.8,9,10,11 - continuara

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2339]
* Comentarios de Sefrenia:

1) https://es.wowhead.com/quest=42828/como-moscas-a-la-miel: reparada.
2) https://es.wowhead.com/quest=42835/a-la-antigua-usanza: reparada.
3) https://es.wowhead.com/quest=42836/sabotaje-alaseda: reparada.
4) https://es.wowhead.com/quest=42837/equilibrio-de-sobra: reparada.
5) https://es.wowhead.com/quest=42840/si-las-palabras-no-funcionan: reparada.
6) https://es.wowhead.com/quest=42792/deja-tu-huella: reparada.
7) https://es.wowhead.com/quest=43311/o-contra-nosotros: reparada.
8) https://es.wowhead.com/quest=43313/se-rumorea-por-ahí: reparada.
9) https://es.wowhead.com/quest=43565/traer-la-baliza-a-casa: reparada, aunque no pude lograr el efecto de que la luz de la baliza se moviera.
10) https://es.wowhead.com/quest=43567/a-por-todas: por el momento quedará en modo autocompletable, hasta reconstruir la zona.
11) https://es.wowhead.com/quest=43568/arcandor-regalo-de-los-antiguos-magi: reparada.
12) https://es.wowhead.com/quest=40883/el-destino-de-la-guardia: reparada.
13) https://es.wowhead.com/quest=40964/la-falla-de-en-medio: reparada.
14) https://es.wowhead.com/quest=40968/recuperar-el-poder-robado: irresoluble por el momento.
15) https://es.wowhead.com/quest=41109/a-la-espera-de-venganza: reparada. Por un defecto del sistema, no se están dando las quests automáticamente, así que hay que tomarlas manualmente. En este caso, la dará Serena Windfeather si la abandonaste.
16) https://es.wowhead.com/quest=41108/lluvia-mortal: reparada.
17) https://es.wowhead.com/quest=40965/aniquilación-con-minas: irreparable por el momento, debido a mecánicas confusas. Reducido temporalmente a 1 el objetivo de matar 50 elfos.
18) https://es.wowhead.com/quest=40972/la-última-carga-de-la-guardia-lunar: reparada.
19) https://es.wowhead.com/quest=40266/el-consejero-perdido: reparada.
20) https://es.wowhead.com/quest=40744/una-antigua-receta: reparada.
21) https://es.wowhead.com/quest=40227/malas-intenciones: reparada.
22) https://es.wowhead.com/quest=41467/la-única-decisión-posible: temporalmente quedará así, ya que no existe el item de la antorcha en la Database. Pendiente de actualización.
23) https://es.wowhead.com/quest=41462/un-problema-con-pies-enormes: temporalmente quedará así, ya que no existe el item en la Database. Pendiente de actualización.
24) https://es.wowhead.com/quest=40332/fogata-en-la-playa: reparada.
25) https://es.wowhead.com/quest=40334/tónico-del-pescador: reparada, pero el problema era otro: para esta quest, se te brinda un acompañante combatiente, el NPC 102381, a quien le entregas esta quest, y quien debe darte la siguiente. Ya dejé esto nuevo funcionando.
26) https://es.wowhead.com/quest=40927/la-última-esperanza-de-jandvik: reparada.
27) https://es.wowhead.com/quest=41409/la-importancia-del-momento-oportuno: reparada. Fjolrik está un poco lejos, y es sencillo pasarlo por alto o no encontrarlo. Ahora Brytag también iniciará esta quest, en consideración a los desorientados ;)
28) https://es.wowhead.com/quest=40336/necesito-una-balista: derivado el reporte a los Devs de Core.
29) https://es.wowhead.com/item=137179/grotesque-ettin-leather: notificado en inciso 23.
30) https://es.wowhead.com/quest=41197/te-estás-quedando-conmiaugo: reparada.
31) https://es.wowhead.com/quest=41469/vuelve-al-refugio-bosqueférreo: reparada.

**Comment by Kirrkoi** [comment]
https://es.wowhead.com/quest=43565/traer-la-baliza-a-casa
esta mision una baliza de telemancia para inspeccionar algunas zonas de la ciudad de Suramar, al tomar esta mision me da la baliza y me autocompleta la mision, omite lo de inspeccionar
https://es.wowhead.com/quest=43567/a-por-todas
en esta mision se autocompleta, no me lleva a la gesta , en la gesta deberia sabotear conductor nocturno, examinar a Arluin y entrar en Shal'Aran
![image](https://user-images.githubusercontent.com/81131460/115927842-b7049c80-a44a-11eb-899d-192e8317feac.png)
link de youtube de la mision: https://www.youtube.com/watch?v=fNGg3JLzWr0
https://es.wowhead.com/quest=43568/arcandor-regalo-de-los-antiguos-magi
en esta mision pide alimentar a oculeth a Valtrois y Thalyssra. solo puede alimentar a los dos primero y a Thalyssra no me dejo alimentarla, reincie la mision, no me dejo alimentar a ninguno

**Comment by Kirrkoi** [comment]
https://es.wowhead.com/quest=40883/el-destino-de-la-guardia
esta mision pide encontrar los cadaveres de Nyellus Tejestrellas, Galar'thus Riberárbol y Kailea Ventopluma y realiza para ellos unos ritos fúnebres.
al encontrar los cuerpos realizo el rito en los dos primeros y se completa la mision, la mision omite al tercero.

https://es.wowhead.com/quest=40964/la-falla-de-en-medio
la mision pide Monta en Picobravo para ir a El Athenaeum, la mision se autocompleta al hacer dialogo en el hipogrifo, debería poder montar al hipogrifo para volar a El Athenaeum

https://es.wowhead.com/quest=40968/recuperar-el-poder-robado
la mision tiene un error visual, que no se visualiza en el mapa donde transcurre dicha mision

https://es.wowhead.com/quest=41109/a-la-espera-de-venganza
al tomar la mision me pide montar en el hipogrifo lo cual se completa al hacer click en el hipogrifo y no vuela el hipogrifo.
Asi funciona la mision, tengo que montar en el hipogrifo y la mision se completa, el hipogrifo debe llevarme volando a El Athenaeum y en el transcurso del vuelo dan la mision (https://es.wowhead.com/quest=41108/lluvia-mortal)
https://www.youtube.com/watch?v=Q8swPo10544

https://es.wowhead.com/quest=41108/lluvia-mortal
esta mision no me dan, porque la mision anterior(https://es.wowhead.com/quest=41109/a-la-espera-de-venganza) no funciona

**Comment by Kirrkoi** [comment]
https://es.wowhead.com/quest=41108/lluvia-mortal
esta mision no funciona porque depende de la mision anterior (https://es.wowhead.com/quest=41109/a-la-espera-de-venganza). tambien no funciona correctamente porque algunos adds no cuentan como objetivosde la mision
video de youtube e como funciona la mision: https://www.youtube.com/watch?v=DyY4OMSecmY

https://es.wowhead.com/quest=40965/aniquilación-con-minas
la mision pide matar 50 Nocheterna y me dan una mina(runa trampa), las runastrampas no detonan
objeto runa trampa: https://es.wowhead.com/item=133882/runa-trampa

https://es.wowhead.com/quest=40972/la-última-carga-de-la-guardia-lunar
primer error el NPC Thalrenus Riberárbol esta envuelto en hielo, segundo error la mision al terminar, el mapa marca el lugar incorrecto donde se debe entregar la mision
![image](https://user-images.githubusercontent.com/81131460/115968676-99910a80-a4fe-11eb-9f18-5a5bbdf820cc.png)
video de youtube de la mision: https://www.youtube.com/watch?v=cdgvCJaZjYY

https://es.wowhead.com/quest=40266/el-consejero-perdido
la mision funciona solo hay un pequeño bug al recolectar riscoespinas, me cuentan por tres, deberia ser por uno.

https://es.wowhead.com/quest=40744/una-antigua-receta
al terminar la mision, el mapa muestra al npc para entregar la mision, en una ubicacion incorrecta
![image](https://user-images.githubusercontent.com/81131460/115969480-bdeee600-a502-11eb-9d3e-56a5356f766c.png)

https://es.wowhead.com/quest=40227/malas-intenciones
primer error es que antes de tomar la mision, la mision me figura en otra ubicacion en el mapa
segundo error es al tomar la mision, me pide dialogar con el npc, en uno de sus dialogos me aprece este error:
![image](https://user-images.githubusercontent.com/81131460/115969576-305fc600-a503-11eb-9625-f96bc49518ff.png)
https://es.wowhead.com/quest=41467/la-única-decisión-posible
omite la quema de la raiz y se autocompleta
![image](https://user-images.githubusercontent.com/81131460/115970589-f98cae80-a508-11eb-819a-60b465a7b9b3.png)
video de youtube de la mision: https://www.youtube.com/watch?v=aVPxm1gCX5k

https://es.wowhead.com/quest=41462/un-problema-con-pies-enormes
para obtener esta mision:
1ro debemos matar Ettin Famelico (https://es.wowhead.com/npc=104220/ettin-famélico) 
2do al matarlo nos dropea este objeto (https://es.wowhead.com/item=137179/grotesque-ettin-leather) y 3ro este objeto nos otorga esta mision (https://es.wowhead.com/quest=41462/un-problema-con-pies-enormes)
video de youtube de la mision: https://www.youtube.com/watch?v=LRxaY7kKz94

**Comment by Kirrkoi** [comment]
https://es.wowhead.com/quest=40332/fogata-en-la-playa
esta mision pide recolectar 6 maderas de la deriva y construir una pira.  el problema está en que la pira esta construida y aparece un mensaje contruyendo pira y al terminar y entregar la mision. sigue apareciendo ese mensaje cada vez que me acerco a la pira. lo peor es como un hechizo que forza mi pj hacerlo.
![WoWScrnShot_042421_220426](https://user-images.githubusercontent.com/81131460/115980549-2e255800-a553-11eb-9816-b70239294ec6.jpg)

https://es.wowhead.com/quest=40334/tónico-del-pescador
al terminar la mision, el mapa ubica al NPC para entregar la mision en un lugar equivocado, el NPC deberia marcar en las coordenadas 72.26. 58.97
![WoWScrnShot_042421_220624](https://user-images.githubusercontent.com/81131460/115980500-dc7ccd80-a552-11eb-8b2c-018987d83335.jpg)

https://es.wowhead.com/quest=40927/la-última-esperanza-de-jandvik
hay dos npc duplicado de  Toryl uno afuera y otro dentro de una jaula

https://es.wowhead.com/quest=40927/la-última-esperanza-de-jandvik
no dan esta mision

https://es.wowhead.com/quest=41001/hacer-pedazos-a-los-sashjtar
no dan esta mision

https://es.wowhead.com/quest=41499/como-un-calamar-fuera-del-agua
no dan esta mision

https://es.wowhead.com/quest=40336/necesito-una-balista
no dan esta mision

**Comment by Kirrkoi** [comment]
https://es.wowhead.com/item=137179/grotesque-ettin-leather
este item no cae, no esta implementado en el juego..

https://es.wowhead.com/quest=41197/te-estás-quedando-conmiaugo
la mision no funciona correctamente, al hacer click en los Buhogatitos se completa el objetivo, deberia arrear a los buhogatitos hasta llegar a casa
link de youtube de la mision: https://www.youtube.com/watch?v=UpL92frl1dI

https://es.wowhead.com/quest=41469/vuelve-al-refugio-bosqueférreo
la mision se completa exitosamente, el mapa marca el lugar incorrecto donde deberia estar el NPC.

**Comment by Cefiro-Caecias** [comment]
Reparadas la mayoría. Dejo arriba el detalle del trabajo hecho. Mañana se implementarán las reparaciones finales. Te odio por hacerme trabajar tanto :P

**Comment by Kprtn** [comment]
https://es.wowhead.com/quest=40336/necesito-una-balista

"Necesito una balista"
La última de la cadena no funciona bien, la balista no se eleva y unicamente dispara a las escaleras y es imposible matar a la decena de élites que salen si atacas sin la balista. ayer morí unas cuantas veces intentándolo, hoy borré caché, deshabilité todos los addons, por si era ese el problema,  pero no, todo continúa igual

![WoWScrnShot_122721_190438](https://user-images.githubusercontent.com/96433337/147497264-70f4df53-ce4c-4502-91a3-03e16163948b.jpg)
