### ISSUE TITLE
[Arthas] - Training Dummies Dying in Orgrimmar

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#234]
**Links:**
https://www.wowhead.com/npc=31144/training-dummy
https://imgur.com/a/p91FS9P
from WoWHead or our Armory

**What is happening:**
After a couple of hits training dummies die, despawn and respawn.

**What should happen:**
Training dummies should be unkillable

**Comment by Maczuga** [comment]
Can't confirm the dummies dying (perhaps something was changed), however all dummies enter the evade state after droping combat and can't fight them again.
![image](https://user-images.githubusercontent.com/544349/79757877-ef940680-831c-11ea-9db6-433074ed72b9.png)

**Comment by antonioyu0505** [comment]
Confirmed. Every dummy gets into evade once you drop combat.
