### ISSUE TITLE
[Object] Mount hyjal portals

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#2341]
![image](https://user-images.githubusercontent.com/82822767/115839069-f5866100-a422-11eb-8c7c-f3224beaeb57.png)

need portal to ogrimmare and stormwind .

http://i.imgur.com/y6FnZ.jpg

http://i.imgur.com/bwV8M.jpg

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
