### ISSUE TITLE
[Ques] Pump it Up

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#2342]
https://www.wowhead.com/quest=38358/pump-it-up

every " Containment Unit " giving 2. This is not enought for the complate quest

![image](https://user-images.githubusercontent.com/82822767/115857804-d691ca00-a436-11eb-85c1-6d0e361782e3.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Now each barrel will grant 15 quest credits. Available in the next update.
