### ISSUE TITLE
[Quest]  The champion of stormheim

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#2344]
https://www.wowhead.com/quest=39855/paid-in-lifeblood
https://www.wowhead.com/storyline/the-champion-of-stormheim-138
https://www.wowhead.com/quest=40078/a-heavy-burden

something is wrong. i don't know. i can't found this quest line.

**Comment by Cefiro-Caecias** [comment]
Repaired long ago, when I re-chained Stormheim.
