### ISSUE TITLE
Non-English Templates

### ISSUE THREAD

**Issue by alkie24** [GuabinaCore/WoWKoi#2346]
**What is happening:** 
some clickable items, etc are not in English
![image](https://user-images.githubusercontent.com/81719671/115877429-01e9d880-a47a-11eb-9b87-6ce722431e35.png)
![image](https://user-images.githubusercontent.com/81719671/115877661-45444700-a47a-11eb-9f7b-c6f32468d977.png)
![image](https://user-images.githubusercontent.com/81719671/115877754-6147e880-a47a-11eb-95f2-2a0ce11dafdb.png)

**What should happen:**
to be translated to English

**Comment by Exlyss** [comment]
Note that these objects should have correct template but the description given by the object when interacted with is in cyrillic. In the link from Wowhead there's also the complete "dialogue" in English.

https://ptr.wowhead.com/object=213331/valley-of-the-emperors
https://ptr.wowhead.com/object=213332/the-lost-dynasty
https://ptr.wowhead.com/object=213333/spirit-binders
https://ptr.wowhead.com/object=213334/the-thunder-king

https://ptr.wowhead.com/object=213327/the-saurok
https://ptr.wowhead.com/object=213328/the-defiant
https://ptr.wowhead.com/object=213329/the-deserters
https://ptr.wowhead.com/object=213330/the-last-stand

https://ptr.wowhead.com/object=215799/the-emperors-burden-part-1
https://ptr.wowhead.com/object=215797/the-emperors-burden-part-2
https://ptr.wowhead.com/object=213421/the-emperors-burden-part-3
https://ptr.wowhead.com/object=213422/the-emperors-burden-part-4
https://ptr.wowhead.com/object=213445/the-emperors-burden-part-5
https://ptr.wowhead.com/object=213443/the-emperors-burden-part-6
https://ptr.wowhead.com/object=213455/the-emperors-burden-part-7
https://ptr.wowhead.com/object=213456/the-emperors-burden-part-8

https://ptr.wowhead.com/object=213417/yaungol-tactics
https://ptr.wowhead.com/object=213418/dominance
https://ptr.wowhead.com/object=215798/yaungoil
https://ptr.wowhead.com/object=213420/trapped-in-a-strange-land

https://ptr.wowhead.com/object=213409/cycle-of-the-mantid
https://ptr.wowhead.com/object=213410/mantid-society
https://ptr.wowhead.com/object=213411/amber
https://ptr.wowhead.com/object=213412/the-empress

https://ptr.wowhead.com/object=213413/pandaren-fighting-tactics
https://ptr.wowhead.com/object=213414/always-remember
https://ptr.wowhead.com/object=213415/the-first-monks
https://ptr.wowhead.com/object=213416/together-we-are-strong
https://ptr.wowhead.com/object=213511/victory-in-kun-lai

https://ptr.wowhead.com/object=213459/the-birthplace-of-liu-lang
https://ptr.wowhead.com/object=213460/a-most-famous-bill-of-sale
https://ptr.wowhead.com/object=213461/the-wandering-widow
https://ptr.wowhead.com/object=215765/waiting-for-the-turtle

https://ptr.wowhead.com/object=211990/hozen-speech
https://ptr.wowhead.com/object=211993/hozen-maturity
https://ptr.wowhead.com/object=215785/embracing-the-passions
https://ptr.wowhead.com/object=211994/the-hozen-ravage

https://ptr.wowhead.com/object=215779/watersmithing
https://ptr.wowhead.com/object=215780/waterspeakers
https://ptr.wowhead.com/object=215782/origins
https://ptr.wowhead.com/object=215783/role-call

**Comment by alkie24** [comment]
@Valley of the Sword, Stormheim
![image](https://user-images.githubusercontent.com/81719671/115957079-0de5a100-a533-11eb-84fa-414bead90177.png)

**Comment by Exlyss** [comment]
https://www.wowhead.com/object=242994/eyirs-helm
https://www.wowhead.com/object=242995/eyirs-pauldron
https://www.wowhead.com/object=242996/eyirs-shield
https://www.wowhead.com/object=242998/eyirs-spear

All four are in spanish, including shown objective of the mission https://www.wowhead.com/quest=39155/becoming-the-ascendant.
![WoWScrnShot_042421_174723](https://user-images.githubusercontent.com/64436148/115964564-6746d380-a525-11eb-86c3-2a051a23c1f1.jpg)

**Comment by Exlyss** [comment]
The Nighthold Raid teleporter.
![WoWScrnShot_042521_153153](https://user-images.githubusercontent.com/64436148/115995444-82741a80-a5db-11eb-99ed-6a95f25c679f.jpg)

**Comment by Exlyss** [comment]
https://www.wowhead.com/item=88895/serpents-scale
https://www.wowhead.com/object=222688/firestorm-egg
https://www.wowhead.com/object=222689/fiery-altar-of-ordos
https://www.wowhead.com/object=220832/sunken-treasure

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. Don't forget to delete "Cache", or you won't see the new translations.
