### ISSUE TITLE
[Quest] Titanic Showdown

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2347]
**Links:**

https://www.wowhead.com/quest=39578/titanic-showdown

**What is happening:**

1. The event start off right after taking the quest, rather than after clicking on the brazier.

2.[Vision of Deathwing](https://www.wowhead.com/npc=97056/vision-of-deathwing) is being killed by nearby friendly NPCs:
- [Rebel Drogbar](https://www.wowhead.com/npc=99138/rebel-drogbar)
- [Ancestral Warbrave](https://www.wowhead.com/npc=99137/ancestral-warbrave)
- [Igrul the Scalebane](https://www.wowhead.com/npc=96387/igrul-the-scalebane)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
