### ISSUE TITLE
[Artifact Quest] - Guardian Druid - The Third Trial of Ursol

### ISSUE THREAD

**Issue by alkie24** [GuabinaCore/WoWKoi#2348]
**Links:** https://www.wowhead.com/quest=41792/the-third-trial-of-ursol

from WoWHead or our Armory

**What is happening:**
I accepted the quest, however the mobs spawned are from the 2nd trial, it doesn't complete the "Speak with Ursol to begin the third trial 0/1" but it shows "Protect Lea Stonepaw 1/1"
as seen:
![image](https://user-images.githubusercontent.com/81719671/115886771-d66beb80-a483-11eb-9b0c-1f7d836e04c3.png)
chatlog shows i clicked multiple times but no progress.
![image](https://user-images.githubusercontent.com/81719671/115886949-01eed600-a484-11eb-8a47-a2d8f412e15f.png)
![image](https://user-images.githubusercontent.com/81719671/115886992-0d420180-a484-11eb-93d5-180581dedc20.png)

**What should happen:**
![image](https://user-images.githubusercontent.com/81719671/115887140-38c4ec00-a484-11eb-9132-1bf1356f7d34.png)
as seen in youtube link:
https://www.youtube.com/watch?v=EXBqNxdn-Yg

**Comment by ShikoSCS** [comment]
Fixed
