### ISSUE TITLE
[Tyce] - Spell Skyhorn Strafing Run (213467) for Quest Justice Rains from Above

### ISSUE THREAD

**Issue by kiazmey** [GuabinaCore/WoWKoi#2349]
**Links:**
https://www.wowhead.com/quest=40594/justice-rains-from-above

**What is happening:**
1st spell on War Eagle is not working properly, it will cast 5-6 times and then it would say "You have no target"
Also, theres a lot mobs missing
VIDEO:
https://youtu.be/lFYFGhkGWxw

**What should happen:**
https://www.youtube.com/watch?v=4TXX-oCxY4Q

**Comment by Cefiro-Caecias** [comment]
@ShikoSCS, el problema radica en la spell 213467 (https://www.wowhead.com/spell=213467): esta spell está obligando al player a tener seleccionado "algo", cualquier cosa, al águila misma, a un NPC amistoso o uno enemigo, para poder castearla, cosa que no tiene sentido, ya que es una spell de daño de area. Por DB y Condition 13 no surte efecto ninguna reparación, así que debes ajustarla por Core.
