### ISSUE TITLE
[Arthas] - Quest ID 24591: Changing of the Gar'dul

### ISSUE THREAD

**Issue by bedle** [GuabinaCore/WoWKoi#235]
**Links:**
https://www.wowhead.com/quest=24591/changing-of-the-gardul
from WoWHead or our Armory

**What is happening:**
Nothing. Player is able to pick up the quest, however game doesnt register that player climbed the tower so it doesnt start next step.

**What should happen:**
https://www.youtube.com/watch?v=ylTxTGTGydw

**Comment by LKArthas** [comment]
Fixed
