### ISSUE TITLE
[Storyline Quest] Grasp of the Underking

### ISSUE THREAD

**Issue by kiazmey** [GuabinaCore/WoWKoi#2350]
**Links:**
https://www.wowhead.com/quest=38915/battle-of-snowblind-mesa
https://www.wowhead.com/quest=39025/grasp-of-the-underking
from WoWHead or our Armory

**What is happening:**
When you take quest there should be a cutscene and Dragul should destroy mountian with his hummer, no cutscene no mountian destroyed. Cant finish highmountian storyline

VIDEO:
https://www.youtube.com/watch?v=8QBBNUv-_9Y

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, when the area is rebuilt.
