### ISSUE TITLE
World Quest - Bloodline of Stone

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2351]
**Links:**
https://www.wowhead.com/quest=41955/bloodline-of-stone
https://www.wowhead.com/npc=91130/magula

**What is happening:**
Not sure if it's related to the whole quest or only the NPC, but Magula is spawned under the floor.

On the minimap it's shown that she's there, and by the downward arrow meaning that she's on a floor under the player -> under the textures.
![WoWScrnShot_042421_010007](https://user-images.githubusercontent.com/64436148/115937674-be529700-a498-11eb-8998-7209f9d68579.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
