### ISSUE TITLE
[Tyce] - Spell Mage: Frozen orb

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#2353]
https://www.wowhead.com/spell=84714/frozen-orb
https://youtu.be/5EozpvcEYM0?t=217

if frozen orb touch anyone frozen orb is slowing to this location in retail . this here is orb not stopping going to far 40 yard

**Comment by Arkanheal** [comment]
It's only a visual bug (but it's kinda annoying, specially for tanks to place the mobs)
