### ISSUE TITLE
Argus Quest - Source of Darkness

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2354]
**Links:**
https://www.wowhead.com/quest=47217/sources-of-darkness

**What is happening:
It's possible to finish the quest while clicking on only one portal.

**What should happen:**
After being deactivated, the portal should be disabled, not allowing the spam on only one portal to finish the quest.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
