### ISSUE TITLE
Argus Quest - A Beacon in the Dark

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2355]
**Links:**
https://www.wowhead.com/quest=47220/a-beacon-in-the-dark

**What is happening:**
Prophet Velen is in the wrong ship and in the wrong place. He can only be found in the Vindicaar at Antoran Wastes.

**What should happen:**
He should be in the centre of the Vindicaar at Mac'Aree.

Mac'Aree, absent.
![WoWScrnShot_042421_162627](https://user-images.githubusercontent.com/64436148/115962227-9441b900-a51a-11eb-95d7-53eee05e721c.jpg)

Antoran Wastes, present. Placement in both in Argus and on the ship is wrong.
![WoWScrnShot_042421_163217](https://user-images.githubusercontent.com/64436148/115962240-a6bbf280-a51a-11eb-808f-3acfed26d2d5.jpg)

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, when the area is rebuilt.
