### ISSUE TITLE
NPC+Related Quests - Yotnar

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2356]
**Links:**
https://www.wowhead.com/npc=96257/yotnar
https://www.wowhead.com/object=243836/yotnars-head
https://www.wowhead.com/quest=39593/the-shattered-watcher

**What is happening:**
Yotnar whole body is present without having completed the quest https://www.wowhead.com/quest=39593/the-shattered-watcher, that should be given by the head, but the head doesn't give it. Also as the body is there, his hitbox covers the head's one, making impossible interacting with the head.

**What should happen:**
Yotnar's whole body shouldn't be there unless the quest to reform its body has been completed.

![WoWScrnShot_042421_193943](https://user-images.githubusercontent.com/64436148/115967990-cdd3ed80-a535-11eb-91be-578596afeb22.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
