### ISSUE TITLE
*Misión Val'sharah* "Sólido como una roca".

### ISSUE THREAD

**Issue by Mokoloko92** [GuabinaCore/WoWKoi#2357]
https://es.wowhead.com/quest=38235/s%C3%B3lido-como-una-roca

Simplemente, los ancianos Marnor Lorhoja, Ventus Brumazal y Del'thanar Troncosabio no se liberan y no se completan los objetivos de la misión.

Los ancianos deberían liberarse de la petrificación.

**Comment by Cefiro-Caecias** [comment]
Por el momento la quest es completable. Se hará blizzlike más adelante, cuando reconstruya la zona.
