### ISSUE TITLE
*Misión* "Libertad illidari"

### ISSUE THREAD

**Issue by Mokoloko92** [GuabinaCore/WoWKoi#2358]
**Link:**
https://es.wowhead.com/quest=38719/libertad-para-los-illidari

**¿Qué pasa?:**
Al hablar con Sirius Alébano, se queda estático y no realiza ninguna acción.

Al hablar con él, ataca y al matarlo completa el objetivo "Sirius Alabenuz encontrado"
https://www.youtube.com/watch?v=_lpU7QDaun4

**Comment by Cefiro-Caecias** [comment]
Fixed.
