### ISSUE TITLE
[Fishing] Drowned Mana

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2359]
**Links:**

https://www.wowhead.com/item=138777/drowned-mana

**What is happening:**

Drowned mana doesn't drop.

**What should happen:**

**Comment by Nephilimkoi** [comment]
it does drop. just that you need to use the lures and a whole system just to get 10. its awful

**Comment by ventarius5** [comment]
According to wowhead comments: 
![image](https://user-images.githubusercontent.com/63166930/116372051-57244200-a80c-11eb-8449-fb8471ae5f63.png)

They don't suggest there are any other requirements to be able to fish up drowned mana. Just basic fishing skill.

**Comment by Nephilimkoi** [comment]
interesting.
