### ISSUE TITLE
Achievement - Glory of the Ulduar Raider

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2360]
**Links:**
https://www.wowhead.com/achievement=12387/one-light-in-the-darkness
https://www.wowhead.com/achievement=12386/two-lights-in-the-darkness
https://www.wowhead.com/achievement=12385/three-lights-in-the-darkness

Achievement 12385 - 12386 - 12387: Keepers not working properly, making impossible to obtain the achievements.

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, when the area is rebuilt.
