### ISSUE TITLE
Achievement - Glory of the Hero

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2361]
**Links:**
https://www.wowhead.com/achievement=2154/brann-spankin-new
https://www.wowhead.com/achievement=2155/abuse-the-ooze
https://www.wowhead.com/achievement=2043/the-incredible-hulk

Achievement 2154: bossfight won't complete.

Achievement 2155: boss Sjonnir doesn't spawn Malformed Oozes.

Achievement 2043: boss Svala Sorrowgrave doesn't use the spell Ritual Strike, needed to kill the Scourge Hulk.

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, when the area is rebuilt.
