### ISSUE TITLE
[Tyce] - Dungeon: Maw of souls Mythic keystone

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#2363]
Maw of Souls first boss has to spawn some mobs but it doesn't work
https://www.wowhead.com/spell=193566/arise-fallen

And for the last boss we have to kill Helya twice. Boss reseted itself. 

And there should be a portal to turn us the beginning of the dg. But there isn't. 
https://youtu.be/sckkyc_lALI?t=483  (Retail)

And the holes of the last boss has to send you backward but it doesn't work as well and it overkill.

**Comment by Nephilimkoi** [comment]
> Maw of Souls first boss has to spawn some mobs but it doesn't work
> https://www.wowhead.com/spell=193566/arise-fallen

he does.
![WoWScrnShot_042821_000030](https://user-images.githubusercontent.com/73371905/116344739-ca9a6500-a7b4-11eb-9295-7b8473cad982.jpg)
