### ISSUE TITLE
[Dungeon] [Raid] Personal loot

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#2364]
Drop chances are so low. We can't get item as usual. mythic keystone and raid only 1 person taking item

**Comment by Nephilimkoi** [comment]
about that. the core dev said that drop chances are 15% meaning that in a party of 10 people. around 1-2 should be getting loot. which is the blizzlike drop chance
even basing it in samples taken from regular players in retail the drop chances are just around 20% in average. and thats taking into account the best cases.
https://www.reddit.com/r/CompetitiveWoW/comments/9138e7/personal_loot_specifics/
that is a debate about.
