### ISSUE TITLE
[Tyce] - Dungeon Black rook hold

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#2367]
Black Rock Hold first boss addes phase doesn't work well. Because there should be achivment part. The adds turn into another adds which name Frustrated Soul. And after we finish the dg, you have to talk Malfruin to take us the beginning of the dg. But it doesn't work.

https://www.wowhead.com/achievement=10710/black-rook-moan

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
