### ISSUE TITLE
[Dungeon] Eye of Azshara

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#2368]
In Eye Of Azshara behind of the last boss there is a thing which name tidestone of the golganneth. It should be taken. 
https://www.wowhead.com/item=137206/tidestone-of-golganneth

And the Violent Winds in EoA has to stop after the killing to Serpentrix.
https://www.wowhead.com/spell=191797/violent-winds

 In mythic difficulty Hatecoil Arcanist doesn't use [Polymorph:Fish] skill
https://www.wowhead.com/spell=197105/polymorph-fish

**Comment by Nephilimkoi** [comment]
https://www.wowhead.com/quest=38286/eye-of-azshara-wrath-of-azshara
**After you turn in the quest 38286 on the Tidestone.**
https://www.wowhead.com/object=246465/tidestone-of-golganneth

**You get the quest 42213**
https://www.wowhead.com/quest=42213/eye-of-azshara-the-tidestone-of-golganneth

**in which the tidestone is a provided item** 
https://www.wowhead.com/item=137206/tidestone-of-golganneth

so to answer the first point. no the tidestone of golganneth isnt lootable. its a provided item and it works just fine

**Comment by Nephilimkoi** [comment]
> In mythic difficulty Hatecoil Arcanist doesn't use [Polymorph:Fish] skill
> https://www.wowhead.com/spell=197105/polymorph-fish

uh. they do
![image](https://user-images.githubusercontent.com/73371905/116338018-19420200-a7a9-11eb-8bc4-fbdf3b4a965b.png)

**Comment by Nephilimkoi** [comment]
> And the Violent Winds in EoA has to stop after the killing to Serpentrix.
> https://www.wowhead.com/spell=191797/violent-winds

https://www.wowhead.com/eye-of-azshara-dungeon-strategy-guide

> No matter what path players take, the environment in the Eye of Azshara becomes more hostile as the party progresses further into the dungeon.
> After defeating two bosses,  Violent Winds will occasionally push players in a random direction
> These  Violent Winds last for 10 seconds, and occur every 90 seconds, whether players are in or out of combat
> As there are many mechanics in the Eye of Azshara that are sensitive to positioning, this can make some bosses very difficult
> The Lady Hatecoil encounter has the most position-sensitive mechanics, which is why players should kill her second, before  Violent Winds are active
> After killing a third boss, the storm intensifies, causing  Lightning Strikes to appear near players every few seconds
>  Lightning Strike first appears as small watery swirl; after 3 seconds, a bolt of lightning strikes the ground, dealing moderate to heavy damage to players within 4 yards
> While these environmental effects do not affect much gameplay, players will have to continually be aware of them when dealing with the rest of the dungeon's mechanics.

so to answer that point. no. Violent winds should appear after killing the 2th boss. tho they should disappear after killing Wrath of Azshara
