### ISSUE TITLE
[Tyce] - Dungeon The arcway mythic+

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#2370]
In Arcway there is no exit. If you want to go out from where you start. You can't. When you use your key, there should be a barrier for the countdown.

 But there isn't. Nal'tira uses Web Link to the tank. This is a huge problem. 
 https://www.wowhead.com/spell=200227/tangled-web
 
 And the spawn of the spiders should rework because they have to spawn processionally. 
https://youtu.be/goeYoCbXsvU?t=604

And the last boss uses [Banishing of Time] skill, you go somewhere else in the dg. In that phase there should be Timeless Wrath mobs. There aren't. In stead of them there is usual mobs in that phase. 
https://www.wowhead.com/npc=103130/timeless-wraith
https://youtu.be/goeYoCbXsvU?t=1671

**Comment by Nephilimkoi** [comment]
> And the last boss uses [Banishing of Time] skill, you go somewhere else in the dg. In that phase there should be Timeless Wrath mobs. There aren't. In stead of them there is usual mobs in that phase.
> https://www.wowhead.com/npc=103130/timeless-wraith
> https://youtu.be/goeYoCbXsvU?t=1671

from what i have seen for example. in this vid
https://www.youtube.com/watch?v=42eW2hHl0OQ  around 2:30 
there are mob corposes while in the banishing time phase. meaning that there is the posibility to encounting mobs if you dont clear the area.

also the wraths are there 

![WoWScrnShot_042721_232813](https://user-images.githubusercontent.com/73371905/116342298-5cec3a00-a7b0-11eb-945c-c2b5528af4f3.jpg)

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
