### ISSUE TITLE
[Tyce] - Appererances Prestige

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#2372]
The Prestige Artifact Skin doesn't work for some classes for example Prot Pala and DK.

![image](https://user-images.githubusercontent.com/82822767/116050298-fb2cb280-a67f-11eb-96c2-d7fd93777ef4.png)

![image](https://user-images.githubusercontent.com/82822767/116050351-0a136500-a680-11eb-8c66-8940909beb5e.png)

**Comment by Nephilimkoi** [comment]
uh. did you do https://www.wowhead.com/quest=42985/a-royal-audience
and got
https://www.wowhead.com/item=138996/high-warlords-medal-of-valor ?
maybe could be bugged in hord. in ally side i have unlocked them all

![WoWScrnShot_042721_230146](https://user-images.githubusercontent.com/73371905/116340100-8f943380-a7ac-11eb-9fd9-3e522179a0c0.jpg)


![WoWScrnShot_042721_230356](https://user-images.githubusercontent.com/73371905/116340263-e00b9100-a7ac-11eb-84b9-453c56b0f1fe.jpg)
