### ISSUE TITLE
[Quest] Grassroots Effort

### ISSUE THREAD

**Issue by kiazmey** [GuabinaCore/WoWKoi#2379]
**Links:**
https://www.wowhead.com/quest=42884/grassroots-effort
from WoWHead or our Armory

**What is happening:**
Old Grizzleback's Staff is only working on 1 house, when you use it on other 4 houses nothing happens.
VIDEO:  https://youtu.be/xJpxmo9ukfg

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
