### ISSUE TITLE
Runa de caida lenta- NPC

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2380]
**Links:**
https://es.wowhead.com/npc=116317/runa-de-caída-lenta
from WoWHead or our Armory

**Lo que sucede:**
Runa de caída lenta, no esta implementado en el juego

**Comment by Cefiro-Caecias** [comment]
Existe en la DB, pero no tengo información de dónde se usa o para qué. En un futuro Issue, si me proporcionas más datos, puedo agregarla.
