### ISSUE TITLE
[DH HAVOC] Transformed into a wisp 

### ISSUE THREAD

**Issue by kiazmey** [GuabinaCore/WoWKoi#2381]
When i took Demonic talent for Havoc DH, when i pop my eye beam and get metamorph. bug  i get transformed into a wisp
VIDEO:  https://youtu.be/8yKSfBlrxyQ

**Comment by Nephilimkoi** [comment]
Thats because of the legendary effect. 
if you notice there is a buff that is stacking.
https://www.wowhead.com/item=146669/the-sentinels-eternal-refuge?bonus=3630
https://www.wowhead.com/spell=241331/the-sentinels-eternal-refuge

**Comment by kiazmey** [comment]
Problem is that when buff is over i dont get turned to normal form, i need to attack something or just relog to return, forgot to write that above, sorry

**Comment by Arkanheal** [comment]
duplicate #2248. Closing
