### ISSUE TITLE
entidad no visible - Suramar - Finca de Lunastre

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2382]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
me fui a matar a Magister Praedis, al matarlo. una entidad no visible me esta atacando.. 
![image](https://user-images.githubusercontent.com/81131460/116345479-d0d91300-a7ad-11eb-8b80-b80072f865c3.png)
![image](https://user-images.githubusercontent.com/81131460/116345498-df272f00-a7ad-11eb-9e7b-683554cc220f.png)

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
