### ISSUE TITLE
World Event - Children's week incorrect stating time

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2384]
**Links:**

https://www.wowhead.com/childrens-week-guide
https://www.wowhead.com/npc=14444/orcish-orphan

**What is happening:**

Children's week has started today April 28, instead of May 1.

Orcish Orphan quests are autocomplete. Also, there is no option to turn in the quests.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
