### ISSUE TITLE
[Tyce] - Quest The Emerald Nightmare: The Stuff of Dreams

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#2385]
![image](https://user-images.githubusercontent.com/82822767/116449229-9f6e4f00-a862-11eb-9323-67c82f8672a0.png)

![image](https://user-images.githubusercontent.com/82822767/116449249-a4330300-a862-11eb-8cf2-bc0b14b311d1.png)

after kill xavius im stuck in last boss location . dreamway teleport is not working on LFR

**Comment by ventarius5** [comment]
It's already been reported. #2265
