### ISSUE TITLE
Suramar - insurreccion cap 2, 3, 4, 6, 7 ,8 ,9

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2386]
**What is happening:**

https://es.wowhead.com/quest=44725/toma-de-rehenes
la mision omite la parte de dialogar con el cautivo en el puerto, anclarme como cuativo y la escena donde le guarida nos ve y nos sube al bote para ir a Bastion Alma vil..
https://www.youtube.com/watch?v=49XHFbTU_KI

https://www.youtube.com/watch?v=49XHFbTU_KI
Talysrra invoca ecos para buscar a Vanthir, lo hace todo a la vez , deberia hacer de uno en uno
https://www.youtube.com/watch?v=2473U_7Z_ZQ

https://es.wowhead.com/quest=44754/cuarto-creciente
los guardias y silgryn llegan tarde al objetivo cuando esta muerto.. o aveces están antes de matar a Thoramir y desaparecen, y al morir Thoramir aparecen los guardias y Silgryn
https://www.youtube.com/watch?v=EhFKIIIGiP0

https://es.wowhead.com/quest=44814/refugio-menguante
al tomar la mision, unos dialogos del Npc y automaticamente nos teletransportamos a la ciudad de suramar, sin usar el barco...

https://es.wowhead.com/quest=45316/estabilizar-suramar
bug visual se quedo en 8/10 logre completar la mision

https://es.wowhead.com/quest=41916/un-futuro-mejor
bug npc insurgente rescatado, se le puede hacer click varias veces al mismo npc para completar la mision.

https://es.wowhead.com/quest=44834/nulificado
la mision no marca el lugar especifico donde esta los items que debo encontrar y el baston no esta visible
https://www.youtube.com/watch?v=BMa9mAz2uBM
![image](https://user-images.githubusercontent.com/81131460/116494605-c464c100-a866-11eb-999c-d8549005fd87.png)

https://es.wowhead.com/quest=44845/romper-un-brazo
la mision deberia marcarme en el mapa, la ubicacion del objetivo de la mision.

https://es.wowhead.com/quest=44874/increíbley
la mision se autocompleta
![image](https://user-images.githubusercontent.com/81131460/116495781-3938fa80-a869-11eb-8461-26e29ea1cf20.png)

https://es.wowhead.com/quest=44875/el-arte-de-fluir
la mision se autocompleta
![image](https://user-images.githubusercontent.com/81131460/116495812-4b1a9d80-a869-11eb-89b7-fca4398f3b76.png)

https://es.wowhead.com/quest=44876/danza-de-dragones
la mision se autocompleta omite los dialogos del npc Stellagosa

https://es.wowhead.com/quest=44740/punto-de-escala
el objetivo de la mision no me marca la ubicacion de la baliza de telemancia
![image](https://user-images.githubusercontent.com/81131460/116500101-72766800-a873-11eb-99c5-a95876b1b964.png)

**Comment by Noahkrr** [comment]
https://es.wowhead.com/quest=44822/investigaciones-temporales
la mision se autocompleta, omite la investigacion del bloqueo temporal
![image](https://user-images.githubusercontent.com/81131460/116743973-4d8f0b80-a9bf-11eb-957d-9690d9ab59d7.png)
https://www.youtube.com/watch?v=Tb3pKj2-xeQ

https://es.wowhead.com/quest=45209/esos-ojos-escudriñadores
no marca ubicacion del objetivo de la mision  en el mapa. deberia marca puntos amarillos en el mapa de cada orbe ..
![image](https://user-images.githubusercontent.com/81131460/116744224-a52d7700-a9bf-11eb-99e9-9ab0c95c54a9.png)

https://es.wowhead.com/quest=44832/explorar-la-brecha
el NPC Arcanista Valtrois no nos sigue para despejar los guardias, sino que se crea una copia al llegar a  la puerta de la gesta bastion nocturno, y se autocompleta antes de examinar la puerta, deberia el NPC Arcanista Valtrios 
![image](https://user-images.githubusercontent.com/81131460/116746774-a0b68d80-a9c2-11eb-8eac-cb128b76987e.png)
https://www.youtube.com/watch?v=1ehQ6xracBE

https://es.wowhead.com/quest=44833/el-poder-del-sello
al llegar a  Kel' balor el npc Valtrios ya se encuentra dentro, y tiene un dialogo en ruso
![image](https://user-images.githubusercontent.com/81131460/116748225-bcbb2e80-a9c4-11eb-9ee0-bdbf9e5e5fa3.png)
https://www.youtube.com/watch?v=s2rZSOM0ALY

https://es.wowhead.com/quest=44919/un-desafío-de-nuestros-enemigos
Talysrra nunca toma el portal hacia  Finca de Lunastre, cuando tomo el portal, talysrra aparece junto ami, se omite el enfrentamiento con Andraris, se autocompleta el objetivo. despues rescato a los ciudadanos atemorizados y completo la mision.
https://www.youtube.com/watch?v=vtgJBRWw07E&t=30s

https://es.wowhead.com/quest=45062/trabajando-sin-descanso
el orbe para desactivar desactivar no aparece, uso el spell y se completa la mision
https://www.youtube.com/watch?v=n7j34H0_ikQ

https://es.wowhead.com/quest=45065/inspeccionar-la-ciudad
la  baliza para inspeccionar el paseo del orden , se bugea aveces se sale de la zona del objetivo a inspeccionar 

https://es.wowhead.com/quest=45066/inestabilidad-experimental
las fallas inestables no funcionan, los orbes desechados no desaparecen al recojerlos y se puede hacer click varias veces hasta completar el objetivo
https://www.youtube.com/watch?v=GkK7LJ2AFj4

https://es.wowhead.com/quest=44719/irrupción-en-el-santuario
al terminar la gesta la mision se completa, pero no aparece donde entregar la mision
![image](https://user-images.githubusercontent.com/81131460/116756166-47a22600-a9d1-11eb-8c25-094de868a44f.png)
no se supone que la misión termina, al entregar la misión a khadgar, pero la gesta no termino se bugeo 
![image](https://user-images.githubusercontent.com/81131460/116756241-656f8b00-a9d1-11eb-9e97-9f1e171af711.png)
relogee y no puedo entregar la mision, khadgar no reconoce la mision ..
![image](https://user-images.githubusercontent.com/81131460/116757761-563e0c80-a9d4-11eb-831d-176e5d82538f.png)
https://www.youtube.com/watch?v=exYQ-y_e7mY

**Comment by Cefiro-Caecias** [comment]
https://es.wowhead.com/quest=44725/toma-de-rehenes: se hará blizzlike más adelante.
https://es.wowhead.com/quest=44754/cuarto-creciente: se hará blizzlike más adelante.
https://es.wowhead.com/quest=44814/refugio-menguante: se hará blizzlike más adelante.
https://es.wowhead.com/quest=45316/estabilizar-suramar: se hará blizzlike más adelante.
https://es.wowhead.com/quest=41916/un-futuro-mejor: reparada hace tiempo.
https://es.wowhead.com/quest=44834/nulificado: reparada hace tiempo.
https://es.wowhead.com/quest=44845/romper-un-brazo: reparada, disponible en el próximo update.
https://es.wowhead.com/quest=44874/increíbley: se hará blizzlike más adelante.
https://es.wowhead.com/quest=44875/el-arte-de-fluir: se hará blizzlike más adelante.
https://es.wowhead.com/quest=44876/danza-de-dragones: se hará blizzlike más adelante.
https://es.wowhead.com/quest=44740/punto-de-escala: reparada, disponible en el próximo update.
https://es.wowhead.com/quest=44822/investigaciones-temporales: se hará blizzlike más adelante.
https://es.wowhead.com/quest=45209/esos-ojos-escudriñadores: reparada, disponible en el próximo update.
https://es.wowhead.com/quest=44832/explorar-la-brecha: se hará blizzlike más adelante.
https://es.wowhead.com/quest=44833/el-poder-del-sello: reparada hace tiempo.
https://es.wowhead.com/quest=44919/un-desafío-de-nuestros-enemigos: se hará blizzlike más adelante.
https://es.wowhead.com/quest=45062/trabajando-sin-descanso: reparada, disponible en el próximo update.
https://es.wowhead.com/quest=45065/inspeccionar-la-ciudad: reparada, disponible en el próximo update.
https://es.wowhead.com/quest=45066/inestabilidad-experimental: reparada, disponible en el próximo update.
https://es.wowhead.com/quest=44719/irrupción-en-el-santuario: ya se puede completar y entergar, aunque se hará blizzlike más adelante.
