### ISSUE TITLE
[Tyce] - Old Karazhan

### ISSUE THREAD

**Issue by geristus89** [GuabinaCore/WoWKoi#2387]
**Links:**

from WoWHead or our Armory

**What is happening:**
Today I was in Old Karazhan, after killed Moroes, I can't pick up loot, so I log out. After that i can't log in again, my logging screen is stopped (printscreen below). After use unstucked on site, I was back in Dalaran and try to walk in to Karazhan again, but then i got same problem and only unstuck again help.
![image](https://user-images.githubusercontent.com/5372411/116523327-696ab280-a8d6-11eb-9994-0f7bf77c4a4f.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
