### ISSUE TITLE
[NPC] Petrified Infernal - multiple credits

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2388]
**Links:**

NPC - https://www.wowhead.com/npc=119491/petrified-infernal
Quest - https://www.wowhead.com/quest=46197/from-the-skies-they-fel

**What is happening:**

Petrified Infernals can be clicked on multiple tiems for additional credits.

**What should happen:**

One click, one credit.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
