### ISSUE TITLE
[NPC] Great Eagle - multiple credits

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2389]
**Links:**

https://www.wowhead.com/quest=46195/swarming-skies

https://www.wowhead.com/npc=119191/great-eagle-rescued

**What is happening:**

Great Eagle can be clicked on multiple times for additional credits.

**What should happen:**

One click, one credit.

**Comment by Cefiro-Caecias** [comment]
Fixed.
