### ISSUE TITLE
Quest: Military Breakthrough. Id: 14470

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#239]
**Links:**
https://www.wowhead.com/quest=14470/military-breakthrough
from WoWHead or our Armory

**What is happening:**
When you get to the marked area you don't see anything there and nothing spawns. But if you leave the area Forlorn Ridge and go a bit away when you are marked as in Azshara and not Azshara: Forlorn Ridge, you can see Warlord Kreillan there spawned. It's like you phase in a different area that the mob can't spawn in

**What should happen:**
Warlord Kreillan, Sergeant Dynamo and the SFG should spawn in the marked area even when you are phased in Forlorn Ridge.

**Comment by LKArthas** [comment]
Fixed for next update
