### ISSUE TITLE
[Quest] Holding Our Ground

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2390]
**Links:**

https://www.wowhead.com/quest=45572/holding-our-ground

**What is happening:**

1. [Injured Protector](https://www.wowhead.com/npc=117265/injured-protector#models) and[ Energy Crystal](https://www.wowhead.com/npc=117533/energy-crystal-destroyed) can be clicked on multiple times for additional credits.
2. [Incinerator Vyrthe](https://www.wowhead.com/npc=117473/incinerator-vythe) missing [Withering Felfire](https://www.wowhead.com/spell=238994/withering-felfire) ability.

**What should happen:**

One click, one credit.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
