### ISSUE TITLE
[Quest]Highmountain Legion Invasion - Battle for Highmountain

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2391]
**Links:**

https://www.wowhead.com/quest=46182/battle-for-highmountain

**What is happening:**

**Updated**

1. [Rivermane Shaman](https://www.wowhead.com/npc=119855/rivermane-shaman) can be spam clicked for additional credits.
2. [Mana-Etched Signet](https://www.wowhead.com/item=151155/mana-etched-signet), [Marin Noggenfogger's Lucky Coin](https://www.wowhead.com/item=139781/marin-noggenfoggers-lucky-coin), [Charmed Choker](https://www.wowhead.com/item=151148/charmed-choker), [Managleam Pendant](https://www.wowhead.com/item=151154/managleam-pendant) and [Tacky Chronometer](https://www.wowhead.com/item=151151/tacky-chronometer) are Rouge specific items(Im not a rouge). They are a random drop from mobs across the scenario.

3. Dialogue in Russian 
![obraz](https://user-images.githubusercontent.com/63166930/117466668-45047b00-af53-11eb-9870-91caf74595fc.png)

4. Clicking on the russian dialogue puts you in a scenario queue, instead of teleporting you to it.
![obraz](https://user-images.githubusercontent.com/63166930/117466839-6f563880-af53-11eb-83bb-3be65d806923.png)

5. [War Eagle](https://www.wowhead.com/npc=119857/war-eagle)s flight can be interrupted by hostile NPC, making war eagle attack them.

6. [Fel Commander Erixtol slain](https://www.wowhead.com/npc=119579/fel-commander-erixtol) doesn't grant credit. Scenario cannot be finished.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
-Fixed: 2, 3, 5.
-In Review: 1, 4, 6.
