### ISSUE TITLE
Misión de bonificacion - Monte Alto

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2393]
**Links:**
https://es.wowhead.com/quest=39274/defender-las-riberas
from WoWHead or our Armory

**Lo que sucede:**
la misión no aparece en el mapa.. cuando te acercas aparece activo
![image](https://user-images.githubusercontent.com/81131460/116653118-2b0fda80-a94c-11eb-8d75-61578c6dbc18.png)

**Lo que debería suceder:**
misión de bonificacion, debería poder visualizarse en el mapa..

**Comment by Cefiro-Caecias** [comment]
Irresoluble por el momento.
