### ISSUE TITLE
[Artifact quest] Monk brewmaster - The trial of the Temple

### ISSUE THREAD

**Issue by MicuRazvan-Florentin2E3** [GuabinaCore/WoWKoi#2396]
Links:

https://www.wowhead.com/quest=42765/the-trial-at-the-temple

What is happening:You cant complete the quest, after you obtain the "Fu Zan" you speak with the dragon and he teleports you to class call but the quest isnt completed.
![WoWScrnShot_043021_153855](https://user-images.githubusercontent.com/79265627/116696760-fd1dab00-a9ca-11eb-9945-75dd88d87827.jpg)

What should happen:Fly with the dragon and the quest should get completed

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
