### ISSUE TITLE
[Quest] [Not Their Last Stand]

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#2398]
u can't click to moonfall hippogryph u can do max 4/5 .2 moonfall  is click not working . others flying .
![image](https://user-images.githubusercontent.com/82822767/116708260-31e42f00-a9d8-11eb-9c09-efdb5eb1f2d0.png)

![image](https://user-images.githubusercontent.com/82822767/116708283-3872a680-a9d8-11eb-82e9-0245772346c3.png)

![image](https://user-images.githubusercontent.com/82822767/116708312-40cae180-a9d8-11eb-93df-e39c589e0be0.png)

**Comment by OnlyWATCH** [comment]
after 6-7 min spawning again u can do with like this

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
