### ISSUE TITLE
[Class hall Quest - Demon Hunter] The Invasion of Niskara

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2399]
**Links:**

https://www.wowhead.com/quest=42920/the-invasion-of-niskara

https://wowpedia.fandom.com/wiki/The_Invasion_of_Niskara

**What is happening:**

_**I had redone the scenario  3 times to be sure. Report updated**_

1. Stage 1: Commence Bombardment!:
     -
     - Artillery Controls doesn't work properly. It tilts camera upwards and wont let you shot.
     - Progress bar fills automatically.
     
2. Stage 2: Glide Down to the Rendezvous:
     -
     - Works properly
     
3. Stage 3: Destroy the Legion:
     -
     - [Soulchaser](https://www.wowhead.com/npc=109417/soulchaser) [Drain Life](https://www.wowhead.com/spell=182217/drain-life) ability doesn't heal him.
     - If Kayn's movement is interrupted by a hostile mob, he gets stuck and won't let you trigger stage 4.
     - When Soulchaser is defeated, Kayn and other friendly NPCs approach Fel Hammer. If you bring hostile mobs to them while all stage 3 objectives are not completed, they might bug out of their position which will prevent Kayn from having stage 4 dialogue. (That's what happend to me in the first try.)
     - According to YB videos, Kayn should be ignoring all the mobs and he should be going right for Soulchaser.
                         
4. Stage 4: Regroup In Front of the Command Center:
     -
     - Works properly

5. Stage 5: Fel Hammer, Fire!:
     -
     - Shade of Akama dialogue window doesn't disappear.
     
6. Stage 6: Caria and Varedis At Last
     -
     - Works properly
     
7. Final Stage: Malevolence, Get Us Out of Here
    -
    - Works properly

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Pending review.
