### ISSUE TITLE
Quest: Hand-me-downs. Id=14469

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#240]
**Links:**
https://www.wowhead.com/quest=14469/hand-me-downs#videos
from WoWHead or our Armory

**What is happening:**
No dead body is spawned in the marked area so you can loot the quest item.

**What should happen:**
Dead bodies should spawn in the marked area in order to collect the required amount of quest items so the quest can be finished.

**Comment by LKArthas** [comment]
Fixed for next update
