### ISSUE TITLE
[Misión] "Distracción abrumadora/Overwhelming distraction"

### ISSUE THREAD

**Issue by Mokoloko92** [GuabinaCore/WoWKoi#2402]
**Link:**
https://es.wowhead.com/quest=40971/distracci%C3%B3n-abrumadora

**Que pasa:**
La NPC, Syrana Tejestrellas la omite.

**Que debería pasar:**
La debería dar junto a la misión "El causante de nuestra destrucción"

**Comment by Cefiro-Caecias** [comment]
Reparada hace tiempo.
