### ISSUE TITLE
[Misión] "La última carga de la Guardia Lunar/Last Stand of the Moon Guard"

### ISSUE THREAD

**Issue by Mokoloko92** [GuabinaCore/WoWKoi#2403]
**Links:**

https://es.wowhead.com/quest=40972/la-%C3%BAltima-carga-de-la-guardia-lunar

**Que pasa:**

El NPC, Thalrenus Riberárbol, no da la misión.

**Que debería suceder:**

Luego de finalizada la misión "El causante de nuestra destrucción", Thalrenus Riberárbol nos debería dar esta misión, la cual consiste en hablar con él para que nos teletransporte a la entrada de Shal'Aran y posteriormenteentregarle la misión a Thalyssra.
Con esta misión se completa el capítulo "Fuerte de Guardia Lunar" del progreso de historia de Suramar.

**Comment by Cefiro-Caecias** [comment]
Reparado hace tiempo. Recibirás esta misión luego de completar estas dos quests:

https://es.wowhead.com/quest=40970/el-causante-de-nuestra-destrucci%C3%B3n
https://es.wowhead.com/quest=40971/distracci%C3%B3n-abrumadora
