### ISSUE TITLE
Aguafiestas - Misión de mundo - Suramar

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2404]
**Links:**
https://es.wowhead.com/quest=42106/aguafiestas
from WoWHead or our Armory

**Lo que sucede:**
la misión de mundo no aparece en el mapa y no funciona el spell
https://es.wowhead.com/quest=42106/aguafiestas
ya que  al lanzar a los barcos no los quema, y ademas los barcos aparecen quemados antes de iniciar la misión..
![image](https://user-images.githubusercontent.com/81131460/116758343-71f5e280-a9d5-11eb-9fe7-8a6dfdbd8e3b.png)
![image](https://user-images.githubusercontent.com/81131460/116758472-b5e8e780-a9d5-11eb-9801-a74100bd7eb9.png)

**Comment by Cefiro-Caecias** [comment]
Reparada. Disponible en el próximo update.
