### ISSUE TITLE
Monte alto - misiones 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2405]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/quest=39661/caverna-brote-de-vida
el npc Jale crin de rio, deberia acompañarnos a la cueva, lo cual no pasa.. al llegar a la entrada de la cueva , hay otro npc Jale crin de rio. 
https://www.youtube.com/watch?v=CPcTyCd-Peg

https://es.wowhead.com/quest=39488/el-equilibrio-de-los-elementos
al tomar la mision, el NPC jale crin de rio debe desaparecer, ya que esta mision la hacemos junto con el chaman crin de rio y entregamos la mision al chaman crin de rio.
https://www.youtube.com/watch?v=5B045kAguM8
![image](https://user-images.githubusercontent.com/81131460/116738806-8a0b3900-a9b8-11eb-8609-86b2b8759da4.png)

https://es.wowhead.com/quest=42104/viene-el-infrarrey
una vez rescatados los tauren crin de rio, deben desaparecer para poder entregar la mision, lo cual pasa pero al terminar la misión vuelven aparecer..
la mision se desarrolla en la aldea antes que el infrarrey haga un crater y destruya las casas.. lo cual no pasa.
https://www.youtube.com/watch?v=F22GgAlI1H0

https://es.wowhead.com/quest=39025/en-poder-del-infrarrey
una vez rescatados deberian desaparecer los 3 taurens pero vuelven aparecer encerrados
![image](https://user-images.githubusercontent.com/81131460/116767393-7af6ac00-a9f5-11eb-98a2-1128c8d73022.png)

https://es.wowhead.com/quest=39043/enclave-roepiedra
el npc Guerrero bravo Oro, esta en la puerta de la cueva, nos da esta mision, al terminar la mision npc deberia desaparecer y aparecer dentro de la cueva lo cual no pasa, sino que hay dos npc Guerrero bravo Oro, uno ya esta adentro de la cueva antes de comenzar la mision, y  el otro afuera.
![image](https://user-images.githubusercontent.com/81131460/116768227-94e6bd80-a9fa-11eb-8378-dcf7f8e6c8ea.png)
![image](https://user-images.githubusercontent.com/81131460/116768165-37eb0780-a9fa-11eb-84f5-ad959d226c1d.png)

https://es.wowhead.com/quest=39318/cuidar-de-las-heridas
la mision pide apagar el fuego en cuerno del cielo, al terminar la mision el fuego vuelve...
![image](https://user-images.githubusercontent.com/81131460/116769369-35d87700-aa01-11eb-9966-eadf12d876a2.png)

https://es.wowhead.com/quest=39429/ataque-a-la-tierra-de-las-brujas
el mapa no marca el lugar correcto, donde deberia entregar la mision , ya que hay 3 npc con distinto id que me pueden completar la mision.

**Comment by Cefiro-Caecias** [comment]
Todas se harán blizzlike más adelante. Reparado el defecto de la última. Disponible en el proximo update.
