### ISSUE TITLE
[Dungeon] Vault of the wardens

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#2406]
Glazer boss is bugged , [Focus] phase is beam turning to back him doing nothing .

![image](https://user-images.githubusercontent.com/82822767/116775962-b2ee0580-aa6e-11eb-900b-bc088f30b5ca.png)

![image](https://user-images.githubusercontent.com/82822767/116775965-b6818c80-aa6e-11eb-84b4-e4a43a73d587.png)

after casting time boss staying doing nothing just staying normally ,

**Comment by OnlyWATCH** [comment]
only a bug , i try 3 -4 more times not happened to

**Comment by Arkanheal** [comment]
Do you have an update on this?

**Comment by Arkanheal** [comment]
Fixed (at least in HC). Closing for now feel free to comment. @OnlyWATCH
