### ISSUE TITLE
[Mist] Spanish/russian to English 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#2408]
**Links:**

https://es.wowhead.com/object=248011/hierba-vil
https://es.wowhead.com/object=247105/red-dr%C3%B3gbar
https://www.wowhead.com/object=243368/wooden-barricade
https://www.wowhead.com/object=247345/mucksnout-den-crystal
https://es.wowhead.com/object=246851/runa-de-alma
https://es.wowhead.com/object=246384/%C3%ADdolo-serpiente
https://es.wowhead.com/object=241641/flor-de-raposa
https://es.wowhead.com/object=246735/almeja-babosa
https://es.wowhead.com/object=251681/papiro-deteriorado
**What is happening:**

Its in spanish

**What should happen:**
Must be in English ingame.

**Comment by Exlyss** [comment]
#2346 is also for wrong language templates.

**Comment by Nephilimkoi** [comment]
https://es.wowhead.com/object=246297/bobina-arcana#same-model-as
https://es.wowhead.com/object=246328/bobina-arcana
https://es.wowhead.com/object=246757/bobina-de-alta-potencia
https://es.wowhead.com/object=250379/bobina-de-alta-potencia
https://es.wowhead.com/object=246758/bobina-de-baja-potencia
https://es.wowhead.com/object=250380/bobina-de-baja-potencia
https://es.wowhead.com/object=252258/suministro-de-l%C3%ADnea-ley
https://es.wowhead.com/object=252259/suministro-de-l%C3%ADnea-ley
https://es.wowhead.com/object=252260/suministro-de-l%C3%ADnea-ley
https://es.wowhead.com/object=252261/suministro-de-l%C3%ADnea-ley
https://es.wowhead.com/object=252262/suministro-de-l%C3%ADnea-ley
https://es.wowhead.com/object=252263/suministro-de-l%C3%ADnea-ley
https://es.wowhead.com/object=252264/suministro-de-l%C3%ADnea-ley

**Comment by Nephilimkoi** [comment]
https://es.wowhead.com/quest=40747/el-delicado-arte-de-la-telemancia
todos los objetos que usas para teletransportarte durante esta mision. que por alguna razon no encuentro los ID

Act.
encontre los ID 
https://es.wowhead.com/object=252816/baliza-de-telemancia-desactivada#same-model-as
alli esta la lista

![WoWScrnShot_050521_044356](https://user-images.githubusercontent.com/73371905/117116616-926ac780-ad5c-11eb-85ad-efb3c3f6a662.jpg)

**Comment by Nephilimkoi** [comment]
https://es.wowhead.com/object=253095/monumento-antiguo#same-model-as
https://es.wowhead.com/object=245681/tarro-sellado

**Comment by Nephilimkoi** [comment]
https://www.wowhead.com/object=250666/seal-of-the-earth
https://www.wowhead.com/object=250667/seal-of-the-sky
https://www.wowhead.com/object=250378/seal-of-the-tides

**Comment by Nephilimkoi** [comment]
https://es.wowhead.com/object=250240/botella-de-vino-de-arco
https://es.wowhead.com/object=250086/tonel-de-vino-de-arco

**Comment by Nephilimkoi** [comment]
https://www.wowhead.com/object=251047/faladora-beacon#same-model-as
https://www.wowhead.com/object=246225/weathered-telemancy-beacon
https://www.wowhead.com/object=252817/unpowered-telemancy-beacon
https://www.wowhead.com/object=252816/unpowered-telemancy-beacon
https://www.wowhead.com/object=252815/unpowered-telemancy-beacon
https://www.wowhead.com/object=252814/unpowered-telemancy-beacon
https://www.wowhead.com/object=252107/unpowered-telemancy-beacon
https://www.wowhead.com/object=266009/telemancy-beacon
https://www.wowhead.com/object=265532/telemancy-beacon
https://www.wowhead.com/object=265528/telemancy-beacon
https://www.wowhead.com/object=258977/telemancy-beacon
https://www.wowhead.com/object=258976/telemancy-beacon

**Comment by Nephilimkoi** [comment]
https://es.wowhead.com/object=265435/recipiente-de-semillas-antiguas

**Comment by Nephilimkoi** [comment]
https://es.wowhead.com/object=252783/toma-de-la-arquer%C3%ADa#same-model-as
https://es.wowhead.com/object=252691/salida-de-las-cloacas
https://es.wowhead.com/object=252776/toma-de-la-arquer%C3%ADa
https://es.wowhead.com/object=252779/toma-de-la-arquer%C3%ADa

**Comment by Cefiro-Caecias** [comment]
Reparados. Disponibles en el próximo update. No olviden borrar Cache.
