### ISSUE TITLE
[Core] - NPC: Razormane Hunter. Location: Northrern Barrens

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#241]
**Links:**
https://www.wowhead.com/npc=3265/razormane-hunter
from WoWHead or our Armory

**What is happening:**
The mob targets you after his wolf has targeted you first but continues on his walking pattern, doesn't attack you or stops moving when attacked.

**What should happen:**
Once aggro'ed the mob should stop moving and start to attack you.

**Comment by Cefiro-Caecias** [comment]
Para los devs de Core: este no es un problema del mob en sí mismo, sino de los mobs con pathid; muchas veces, te atacan y siguen caminando en sus rutas predeterminadas sin detenerse.
