### ISSUE TITLE
[Quest] Lay Waste, Lay Mines

### ISSUE THREAD

**Issue by Cyrous96** [GuabinaCore/WoWKoi#2411]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=40965/lay-waste-lay-mines
**What is happening:**
trap does not work

**What should happen:**
supposed to snare a nightborne and make them explode

**Comment by Cefiro-Caecias** [comment]
Since the rune spell is buggy, I'll temporarily put the quest into autocomplete mode. Available in the next update.
