### ISSUE TITLE
[Quest] On Eagle's Wings

### ISSUE THREAD

**Issue by CptKartoffel** [GuabinaCore/WoWKoi#2414]
https://www.wowhead.com/quest=40953/on-eagles-wings

from WoWHead or our Armory

**What is happening:**
''Speak to the flight master in Krasus' Landing'' is an optional step but is actually needed to complete the quest
![Untitled 1](https://user-images.githubusercontent.com/83533835/116807668-ae8c2000-ab34-11eb-9fff-5f9a0cd1be55.jpg)

**What should happen:**
ignore optional steps lmao

**Comment by Cefiro-Caecias** [comment]
Translation error. The step is mandatory, the "optional" reference is above. Fixed, and available in the next update.
