### ISSUE TITLE
[Assault World Quest] The Soul Harvesters 

### ISSUE THREAD

**Issue by kiazmey** [GuabinaCore/WoWKoi#2415]
**Links:**
https://www.wowhead.com/quest=45134/the-soul-harvesters
https://www.wowhead.com/npc=116297/doom-lord-kronak
from WoWHead or our Armory

**What is happening:**
Doom Lord Kro'nak is stucked in groud, cant attack him, 
![WoWScrnShot_050221_133740](https://user-images.githubusercontent.com/79423008/116811929-36c9ef80-ab4c-11eb-8ec1-712d16904dfd.jpg)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
