### ISSUE TITLE
[Orderhall][Death Knight] Frost Wyrm

### ISSUE THREAD

**Issue by Cyrous96** [GuabinaCore/WoWKoi#2421]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/order-hall-advancements-guide#advancements-t5-option-2
has proably been replaced in a newe version of wow so no wowheadlink found
**What is happening:**
frost wyrm orderhall ability isn't working

**What should happen:**
supposed to clear 1 wq every 18 hour,no npc present

**Comment by Cefiro-Caecias** [comment]
It will go blizzlike when the area is rebuilt.
