### ISSUE TITLE
[Quest] A Heavy Burden

### ISSUE THREAD

**Issue by Cyrous96** [GuabinaCore/WoWKoi#2425]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=40078/a-heavy-burden
https://www.wowhead.com/quest=39855/paid-in-lifeblood
**What is happening:**
wrong questchain order

**What should happen:**
"A Heavy Burden" should be unlocked when "Paid in Lifeblood" is done

**Comment by Cefiro-Caecias** [comment]
Repaired long ago, when I re-chained Stormheim.
