### ISSUE TITLE
[Quest] A Strike at the Heart

### ISSUE THREAD

**Issue by Cyrous96** [GuabinaCore/WoWKoi#2427]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=46842/a-strike-at-the-heart
**What is happening:**
Turalyon keeps despawning after Aggonar is dead so you can't turn the quest in

**What should happen:**

**Comment by Cyrous96** [comment]
respawns after leaving argus

**Comment by Cefiro-Caecias** [comment]
Fixed. You can give the quest to the second Turalyon indicated by the quest. Available in the next update ..
