### ISSUE TITLE
[Quest] Mark of the Sentinax

### ISSUE THREAD

**Issue by Cyrous96** [GuabinaCore/WoWKoi#2430]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=47139/mark-of-the-sentinax
https://www.wowhead.com/spell=240640/the-shadow-of-the-sentinax
**What is happening:**
the buff shadows of the sentinax isn't working,making it impossible to farm the mark

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
