### ISSUE TITLE
La marca del demonio - mision - objeto

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2431]
**Links:**
https://es.wowhead.com/quest=38656/la-marca-del-demonio
from WoWHead or our Armory

**Lo que sucede:**
esta misión esta mal, porque pide matar a Gravax el profanador. lo cual no debería pasar ya que para acceder a la misión, necesito un objeto, que es botin de Gravax el profanador.

**Lo que debería suceder:**
debería poder entregarse.. sin ningún requisito
Dato: la misión lo inicia el siguiente objeto
https://es.wowhead.com/item=124131/emblema-demoníaco
el npc que da el objeto
https://es.wowhead.com/npc=92802/gravax-el-profanador

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update. No olvides borrar Cache.
