### ISSUE TITLE
[Core] Hostile mobs float towards platform, that is above them.

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2432]
**Links:**

https://www.wowhead.com/quest=41013/darkbrul-arena#

**What is happening:**

#2170 

When you pull enemy mobs and there is floating, walkable platform above them (small bridge in this case), they start to fly towards it.

This issue was encountered in Darkbrul Arena, although, It seems like It's core flaw so, I guess it affects any NPC in such conditions.

![image](https://user-images.githubusercontent.com/63166930/117191064-6db83380-ade0-11eb-9254-888ba13e1091.png)

------

![image](https://user-images.githubusercontent.com/63166930/117191091-76a90500-ade0-11eb-8ba6-1b93bd6277bb.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
