### ISSUE TITLE
Val'sharah - misiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2433]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/quest=42857/setos-frutales
el npc no da la misión..
NPC que otorga la mision
https://es.wowhead.com/object=251425/chumbogrís-húmedo
link de  youtube de la mision: https://www.youtube.com/watch?v=oyrYYFZEpis&t=3s
![image](https://user-images.githubusercontent.com/81131460/117393093-f99d8e80-aeb8-11eb-9959-bb449f097962.png)

https://es.wowhead.com/quest=42748/hermanas-esmeralda
la mision no funciona,al clikear las hermanas no rescata..
link de youtube de la mision: https://www.youtube.com/watch?v=LEdQiPwv8JE
![image](https://user-images.githubusercontent.com/81131460/117393703-53528880-aeba-11eb-9e99-e5a71e7970c4.png)

**Comment by kiazmey** [comment]
already reported #2378

**Comment by Cefiro-Caecias** [comment]
Reparadas. Disponibles en el próximo update.
