### ISSUE TITLE
[Quest][Death Knight] Amal'thazad's Message

### ISSUE THREAD

**Issue by Cyrous96** [GuabinaCore/WoWKoi#2434]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=46719/amalthazads-message
https://www.wowhead.com/achievement=11546/breaching-the-tomb
**What is happening:**
quest not available

**What should happen:**
should be unlocked after achieving Breaching the Tomb

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
