### ISSUE TITLE
[Tyce] - Neltharion's Lair: Emberhusk Dominator attack when in paralyze

### ISSUE THREAD

**Issue by MicuRazvan-Florentin2E3** [GuabinaCore/WoWKoi#2435]
Links:

https://www.wowhead.com/npc=102295/emberhusk-dominator
![WoWScrnShot_050821_002025](https://user-images.githubusercontent.com/79265627/117510817-67b78380-af95-11eb-9285-82bcaaaeb16b.jpg)

On screenshot you can see the projectile in air coming to hit me while the add is paralyzed.
What is happening:When the add is in paralyzed he still attacks the player

What should happen:The add shouldnt be able to attack

**Comment by Cefiro-Caecias** [comment]
@ShikoSCS, ese bicho está hecho por Core, así que queda en tus manos.
