### ISSUE TITLE
Azsuna - Misiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2439]
**Links:**
https://es.wowhead.com/quest=40207/escamas-de-lo-arcano
from WoWHead or our Armory

**Lo que sucede:**
misión de peleteria, pide hablar con los siguientes npc y obtener la escama de dragón azul
Escama de dragón azul
Habla con Cedonu
Habla con Kharmeera
Habla con Agapanthus

lo unico q funciona es hablar con Agapanthus y se logra obtener la escama de dragón azul. hablar con Cedonu y Kharmeera no funciona.
![image](https://user-images.githubusercontent.com/81131460/117551390-5315d280-b00b-11eb-86aa-f206b3d5049c.png)

**Lo que debería suceder:**
link de youtube de la mision: https://www.youtube.com/watch?v=gOwLgnY3RJw

**Links:**
https://es.wowhead.com/quest=36811/reconquista-faronaar
from WoWHead or our Armory

**Lo que sucede:**
no funciona esta misión de bonificacion, no esta activa, ni aparece el mapa

**Lo que debería suceder:**
link de youtube de la mision: https://www.youtube.com/watch?v=jcdw_JVBUrI

**Links:**
https://es.wowhead.com/quest=37727/el-magister-de-la-ciencia-de-la-mezcla
https://es.wowhead.com/quest=37728/la-presentación-lo-es-todo
from WoWHead or our Armory

**Lo que sucede:**
en npc Magister Garuhod (https://es.wowhead.com/npc=89341/magister-garuhod)
no las siguientes misiones..

**Lo que debería suceder:**
Magister Garuhod debería dar estas misiones..

**Comment by Cefiro-Caecias** [comment]
1) https://es.wowhead.com/quest=40207/escamas-de-lo-arcano: reparada hace tiempo.
2) https://es.wowhead.com/quest=36811/reconquista-faronaar: en revisión.
3) https://es.wowhead.com/quest=37727/el-magister-de-la-ciencia-de-la-mezcla: reparada, disponible en el próximo update.
4) https://es.wowhead.com/quest=37728/la-presentación-lo-es-todo: reparada, disponible en el próximo update.
