### ISSUE TITLE
Monte alto - Misiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2440]
**Links:**
https://es.wowhead.com/quest=40520/ver-el-pasado
https://es.wowhead.com/quest=39983/la-guerra-de-huln-la-llegada
from WoWHead or our Armory

**Lo que sucede:**
https://es.wowhead.com/quest=40520/ver-el-pasado
esta misión al reunir los requisitos que el NPC Caminaespíritus cuerno de ébano (https://es.wowhead.com/npc=98825/caminaespíritus-cuerno-de-ébano), entregamos los objetos y el NPC nos cuenta su pasado en una escena del juego, al terminar de contarnos, el NPC desaparece. al salir de la Totem de trueno y regresar a Totem de Trueno, aparece el NPC  para entregar la mision.

**Lo que sucede:**
https://es.wowhead.com/quest=39983/la-guerra-de-huln-la-llegada
al tomar la misión nos envia hacer una gesta donde. estamos convertido en tauren y debemos matar 25 demonios, pero al entrar a la gesta no puedo mover al PJ, solo puedo lanzar hechizos. asi que abandone la misión para hacerlo al dia siguiente. quise tomar la misión otra vez pero el NPC Caminaespíritus cuerno de ébano (https://es.wowhead.com/npc=98825/caminaespíritus-cuerno-de-ébano) ya no está.
https://www.youtube.com/watch?v=gya-02pnw88

**Comment by Noahkrr** [comment]
![image](https://user-images.githubusercontent.com/81131460/117559986-75314400-b04f-11eb-83e1-d3c4dfc76c93.png)
![image](https://user-images.githubusercontent.com/81131460/117560154-e7565880-b050-11eb-9514-07ca6f8ec88e.png)
![image](https://user-images.githubusercontent.com/81131460/117560157-ede4d000-b050-11eb-9653-52dfdeca8119.png)

perdi misiones por el desorden de las misiones.. ya no puedo acceder a estas misiones.
Nota: estas misiones estan funcionales ya las hice con otro PJ, solo pido establecer el orden, ya que se bugean, si no lo hacen en orden.. como me paso  a mi
https://es.wowhead.com/quest=40170/la-hora-de-los-aficionados
https://es.wowhead.com/quest=39123/al-acecho-de-leones
https://es.wowhead.com/quest=39867/es-un-león-no-mi-imaginación
https://es.wowhead.com/quest=39124/tiro-al-alce
https://es.wowhead.com/quest=39178/un-alce-suelto
https://es.wowhead.com/quest=39392/caza-de-osos
https://es.wowhead.com/quest=40228/de-vigilancia
https://es.wowhead.com/quest=39670/disparo-de-dispersión-de-alimañas
https://es.wowhead.com/quest=39656/manada-de-lobos-al-ataque
https://es.wowhead.com/quest=40102/múrlocs-la-nueva-generación

**Comment by Cefiro-Caecias** [comment]
1) https://es.wowhead.com/quest=40520/ver-el-pasado: se hará blizzlike más adelante.
2) https://es.wowhead.com/quest=40520/ver-el-pasado: aplicaré medidas de seguridad cuando reconstruya la zona.
3) Claro, al estar reencadenadas ahora, afectan a lso que tomaron quests antes. Nada que hacerle por el momento. Igual e suna Beta, así que todo se borrará.
