### ISSUE TITLE
Artifacts Potentially Bugged

### ISSUE THREAD

**Issue by IncognitoCreeper** [GuabinaCore/WoWKoi#2444]
I went to do the quest "Cursed Forge of the Nathrezim" as part of the Havoc DH artifact questline, but when I went to empower my artifact, there were several issues;
1) The artifact already had it's artifact ability unlocked when I equipped it as if it was already empowered, however when I shift right-click on the artifact to open the menu while it's either equipped or in my bags, it seems as it should be for the current quest step
2) I was given no starting AP from the questline steps before this, meaning even if it were working, I wouldn't have enough AP to empower my artifact.
This means that not only am I stuck on this quest, but I won't be able to upgrade my artifact any further even if I do somehow get AP from a different source
![image](https://user-images.githubusercontent.com/83927926/117643246-09c5a000-b13d-11eb-9c03-1bf438cacd83.png)
![image](https://user-images.githubusercontent.com/83927926/117643473-485b5a80-b13d-11eb-98dd-badea4c231fc.png)
![image](https://user-images.githubusercontent.com/83927926/117643518-57daa380-b13d-11eb-9f9a-8f43316980c3.png)

Someone mentioned a similar issue in the Discord server with one of the Warrior artifacts. No screenshots for that addendum, but it seems consistent enough to mention it here.

**Comment by Cefiro-Caecias** [comment]
You must have the Artifact Weapon equipped when you take that quest, so the NPC gives you the 100 AP you need to complete the quest. Try again.

**Comment by IncognitoCreeper** [comment]
That did it, thank you!

**Comment by Cefiro-Caecias** [comment]
To serve you, darling ^^
