### ISSUE TITLE
Suramar  - Misiones - Crecimiento inminente 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2446]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
NPC no esta
https://es.wowhead.com/npc=110987/vistanocturna
misiones que otorga dicho NPC
https://es.wowhead.com/quest=41216/supervivencia-del-más-fuerte
https://es.wowhead.com/quest=43582/parque-shalássico

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
