### ISSUE TITLE
Misiones de mundo de Profesiones - Peleteria

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2448]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
https://es.wowhead.com/quest=41323/piel-de-foca-león-grasa
esta mision esta bug aparece y desparece.. no cuenta todas las zonas en el mapa, donde debería estar los objetivo de la mision
![image](https://user-images.githubusercontent.com/81131460/117881986-7ccf3380-b26f-11eb-8a79-80adbf7e0c45.png)

https://es.wowhead.com/quest=41560/pellejo-vil
mision de mundo de desuello no esta activa, pero aparece en el mapa como activa .
![image](https://user-images.githubusercontent.com/81131460/117885655-b3a74880-b273-11eb-87fb-b4718df103e3.png)

https://es.wowhead.com/quest=41642/pedido-escarpines-de-pellejo-de-guerra
el npc no reconoce la mision de undo, ni icono de mision tiene
![image](https://user-images.githubusercontent.com/81131460/117886812-64faae00-b275-11eb-9bb3-c856e46387ef.png)

Extra
https://es.wowhead.com/quest=41317/suministros-necesarios-piedra-ley
el npc no reconoce la mision de undo, ni icono de mision tiene
![image](https://user-images.githubusercontent.com/81131460/117886870-7348ca00-b275-11eb-9ebf-b4fc90e8c707.png)

**Comment by Noahkrr** [comment]
https://es.wowhead.com/quest=41233/piel-de-oso-erizada
la mision al llegar a la zona de objetivo de la mision desaparece
![image](https://user-images.githubusercontent.com/81131460/118069871-943f1700-b36a-11eb-94e7-56ca332533b4.png)
![image](https://user-images.githubusercontent.com/81131460/118070254-2c3d0080-b36b-11eb-9300-aec3ae080191.png)
![image](https://user-images.githubusercontent.com/81131460/118070068-df592a00-b36a-11eb-9f08-fe9370439f35.png)

https://es.wowhead.com/quest=41582/pellejo-de-trotasoles-suave
mision de mundo activa en el mapa, no marca objetivo en ninguna zona..

**Comment by Cefiro-Caecias** [comment]
1) https://es.wowhead.com/quest=41323/piel-de-foca-león-grasa: reparada, disponible en el próximo update.
2) https://es.wowhead.com/quest=41560/pellejo-vil: reparada, disponible en el próximo update.
3) https://es.wowhead.com/quest=41642/pedido-escarpines-de-pellejo-de-guerra: reparada, disponible en el próximo update.
4) https://es.wowhead.com/quest=41317/suministros-necesarios-piedra-ley: reparada, disponible en el próximo update.
5) https://es.wowhead.com/quest=41233/piel-de-oso-erizada: reparada, disponible en el próximo update.
6) https://es.wowhead.com/quest=41582/pellejo-de-trotasoles-suave: reparada.
