### ISSUE TITLE
[Tyce] - Misiones de mundo - Islas Abruptas

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2453]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
todas estas misiones. no marcan objetivo en la zona, donde deberia realizarse la mision
https://es.wowhead.com/quest=41451/asalto-a-hrydshal
![WoWScrnShot_051321_142452](https://user-images.githubusercontent.com/81131460/118185294-fbf47100-b401-11eb-803f-d95e74fb6c20.jpg)
https://es.wowhead.com/quest=41678/pedido-pack-de-armas
![WoWScrnShot_051321_142831](https://user-images.githubusercontent.com/81131460/118185330-0878c980-b402-11eb-99d0-3b68a636d945.jpg)
https://es.wowhead.com/quest=41938/hermanos-de-skovald
![WoWScrnShot_051321_143229](https://user-images.githubusercontent.com/81131460/118185256-f26b0900-b401-11eb-8f78-0c60fc153677.jpg)
https://es.wowhead.com/quest=42025/pelea-a-pelo
https://es.wowhead.com/quest=41145/agua-de-vida
https://es.wowhead.com/quest=41675/pedido-armatesta-de-activación-por-parpadeo
https://es.wowhead.com/quest=41303/suministros-necesarios-rosas-luz-estelar

**Comment by Cefiro-Caecias** [comment]
En revisión.
