### ISSUE TITLE
Desuello - NPC

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2458]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/npc=106197/jorhuttam
NPC no encontrado
https://es.wowhead.com/npc=111380/orca-asesina
NPC no se puede desollar
![image](https://user-images.githubusercontent.com/81131460/118866433-98f25680-b8a7-11eb-993a-f5de20ebc03b.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Reparados. Disponibles en el próximo update (no olvides que a Jorhuttam se la invoca con un item durante una quest).
