### ISSUE TITLE
[Quest][Guardian Druid] The Third Trial of Ursol

### ISSUE THREAD

**Issue by Ferallyeasy** [GuabinaCore/WoWKoi#2459]
**Links:**
https://www.wowhead.com/quest=41792/the-third-trial-of-ursol

When you go to talk to Ursol nothing happens and you don't join the party with lea and you can spawn ancestral warriors over and over with no end

you should join a party with lea and protect her from a few waves of ads and then the quest turns into ursol

**Comment by ShikoSCS** [comment]
Fixed
