### ISSUE TITLE
Lista de campeones - Salon de clase - cazador

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2460]
**Links:**
https://ptr.wowhead.com/order-advancement=496/roster-of-champions
from WoWHead or our Armory

**Lo que sucede:**
no deberia aumentarme la cantidad de campeones activos, tengo 5 debería tener 6
![image](https://user-images.githubusercontent.com/81131460/119203123-f3cab000-ba57-11eb-82a2-b2b535cb357f.png)
![image](https://user-images.githubusercontent.com/81131460/119202973-9d5d7180-ba57-11eb-8eee-b4c04457f25e.png)

**Comment by Cefiro-Caecias** [comment]
Pendiente de reconstrucción. Paciencia ^^
