### ISSUE TITLE
Misión - peletería

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2461]
**Links:**
https://es.wowhead.com/quest=40207/escamas-de-lo-arcano
from WoWHead or our Armory

**Lo que sucede:**
La misión nos se puede completar, ya que al interactuar con los dragones Cedonu y Kharmeera no presentan diálogos.. lo cual hace imposible completar la misión

**Comment by Cefiro-Caecias** [comment]
Reparada hace un tiempo.
