### ISSUE TITLE
[Item - container] Rattling Iron Cage is empty

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2462]
**Links:**

https://www.wowhead.com/item=128025/rattling-iron-cage#contains

**What is happening:**

Rattling Iron Cage is empty.

![image](https://user-images.githubusercontent.com/63166930/119227767-d48f5980-bb0f-11eb-8316-de815c932b71.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
There is no bug present. Items have a 33% drop chance, so it's a matter of luck ;)

https://www.wowhead.com/item=128025/rattling-iron-cage#comments
