### ISSUE TITLE
Mineria - misiones - objetos

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2464]
**Links:**
https://es.wowhead.com/quest=38777/muestra-de-depósito-de-piedra-ley
https://es.wowhead.com/quest=38784/muestra-de-veta-de-piedra-ley
https://es.wowhead.com/quest=38785/muestra-de-piedra-ley-viviente

from WoWHead or our Armory

**Lo que sucede:**
los items se buegan ya que esos items inician las misiones.
para hacer la primera misión, se necesita
https://es.wowhead.com/item=124489/muestra-de-depósito-de-piedra-ley
para la segunda mision, se necesita
https://es.wowhead.com/item=124490/muestra-de-veta-de-piedra-ley
para la tercera mision
https://es.wowhead.com/item=124491/muestra-de-piedra-ley-viviente

 el problema es, si obtienes el item de la tercera misión (muestra de piedra vil viviente) y activas la mision y la completas, los otros items de la primera y segunda misión (muestra de deposito de piedra ley) y (muestra de veta de piedra ley) se bugearan , lo cual sera imposible conseguirlos ya que salteaste la primera y segunda misión.

 eso es un problema ya que debes eliminar y farmear lo que el item que te falta en mi caso, tube que eliminar mi progreso de 300p de mineria para farmear muestra de deposito de piedra ley y muestra de veta de piedra ley

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
