### ISSUE TITLE
Misiones - Profesiones  - Mineria - Peleteria

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2465]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
https://es.wowhead.com/quest=38803/rinthissa
no logro obtener esta mision, y ademas para rango 3 me pide la mision rinthissa lo cual parece otro mision en la imagen. El ojo de rinthissa pertenece al rango 2.. ya está completado
![image](https://user-images.githubusercontent.com/81131460/119608087-011ace00-bdbb-11eb-9cf9-2efd1254fdff.png)
Para conseguir el último rango, tendremos que volver a picar un Depósito de Pizzara Vil. En el momento que lo hagamos, saldrá Rin'thissa (hermana de Nal'ryssa), la cuál nos proporcionará una misión que lleva su nombre. 

https://es.wowhead.com/quest=40415/tiempo-bien-gastado
esta mision no me da el npc https://es.wowhead.com/npc=98948/hrul-pezuña-afilada
![image](https://user-images.githubusercontent.com/81131460/119608919-5c998b80-bdbc-11eb-9411-50b4edf8dc7d.png)
![image](https://user-images.githubusercontent.com/81131460/119609038-8ce12a00-bdbc-11eb-8285-85de30f566f6.png)

https://es.wowhead.com/quest=40214/curtido-vil
Ya complete la cadena de misiónes, está misión es la última. Debería poder obtener esta misión..

**Comment by Cefiro-Caecias** [comment]
1) https://es.wowhead.com/quest=38803/rinthissa: reparada, disponible en el próximo update. Ahora Rin'thissa aparecerá cuando mines un Felslate Deposit, pero sólo si antes has completado las quests "Ondri's Still-Beating Heart", "Lyrelle's Right Arm" y "Rin'thissa's Eye". El error de que en la ventanita aparece como requisito la quest "Rin'thissa's Eye" no puedo corregirlo aun.

2) https://es.wowhead.com/quest=40415/tiempo-bien-gastado: reparada, disponible en el próximo update.

3) https://es.wowhead.com/quest=40214/curtido-vil: obtendrás esta misión luego de completar "Hounds Abound" y "Wrong End of the Knife".
