### ISSUE TITLE
[NPC] Felskorn Pilferer

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2466]
**Links:**

https://www.wowhead.com/npc=92128/felskorn-pilferer

**What is happening:**

Felskorn Pilferer grant Valajar rep on kill.

![image](https://user-images.githubusercontent.com/63166930/119615273-81fbb900-bdff-11eb-9b83-0c125358be72.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
