### ISSUE TITLE
[WQ] Black Rook Rumble

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2467]
**Links:**

https://www.wowhead.com/quest=42023/black-rook-rumble#comments

**What is happening:**

Enemy NPCs grant 6% progress. I wasn't able to check the "2% credit" because i was alone.

**What should happen:**

According to WoWhead: "2% Credit for being in the arena when someone dies, 
10% Credit if you get the killing blow!"

**Comment by Cefiro-Caecias** [comment]
Unsolvable for the moment. Suffers :P
