### ISSUE TITLE
[Arthas] - Artifact Weapon - Blood Death Knight - The Dead and the Damned

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2469]
**Links:**

https://www.wowhead.com/quest=40740/the-dead-and-the-damned#comments

**What is happening:**

- Pre scenario: [Ride Zeomus to the Broken Shore](https://www.wowhead.com/npc=102403/ride-zeomus-to-the-broken-shore) is clunky, the mount goes through walls and is stuttering when turning. It gets you to the destination, so, really low priority.
- After the flight is over [Zemous](https://www.wowhead.com/npc=102416/zeomus) can be still clicked on. It will spawn Zemous "pet guardian" by your side.

Scenario:

- [ ] Map markers are missing for every stage of the scenario.

1. Stage 1 - Hunting the Hunters:
   -  
   - Player's name is not printed properly in the dialogue window. (My name is in russian alphabet, might it be the issue?)
  
      ![image](https://user-images.githubusercontent.com/63166930/120083449-059bfb00-c0c9-11eb-8ff9-ebd6837a6001.png)

2. Stage 2: Scout the Path:
   -
   - Baron Silver is idle, not helping the player with guards.
   - [Felguard Sentry](https://www.wowhead.com/npc=102244/felguard-sentry) should walk down the road and approach the player. Killing only one of them triggers Stage 3.
   
   
3. Stage 3: Breaching the Defenses:
   -
   - [Niskaran Doombringer](https://www.wowhead.com/npc=102549/niskaran-doombringer) is standing next to the gate. She should not be there. 
   - Niskaran doombringer and Felguard Sentry should spawn and run from up the hill towards the player after Baron Silver approaches the gate.
 
4. Stage 4: The Search Continues:
   -
   - Baron Silver ignores enemies, If a player spends too long fighting the mobs or goes afk, Baron will not trigger the dialogue and won't walk down the hill. (that's my conclusion, because I went to research the scenario for the report and after a couple of minutes I did not manage to trigger him) Really random, but possible situation to happen.
 

5. Stage 5: End of the Inquisition:
   -
   - Baron Silver ignores the mobs.

6. Stage 6: Back to the Prisoner:
   -
   - Works properly

 7. Stage 7: Sieging the Citadel:
    -
    - Killing only one mob in the area will trigger Stage 8.
    - Stage 8 should only trigger if the area around is clear, otherwise it will overwhelm the player.

8. Stage 8: Into the Depths:
   -
   - "Baron Sliver says: I suppose I owe you one, <name>. I almost had my final death there." dialogue is printed. It is Stage 1 
dialogue.
 
9. Stage 9: The Fleshripper:
   -
   - [Gorelix the Fleshripper](https://www.wowhead.com/npc=101778/gorelix-the-fleshripper#abilities) cutscene was played twice.

**What should happen:**

**Comment by IntroverseLaw** [comment]
currently, Baron Silver only stands still in front of the barrier in stage 3 and nothing happens

![bdkscenario](https://user-images.githubusercontent.com/87998390/127724860-198ea9dd-1cd2-44b7-a8c0-d07d6bd03d36.png)
