### ISSUE TITLE
[Saitama] - Spell - Bribe

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#247]
**Links:**
https://www.wowdb.com/spells/199740-bribe

**What is happening:**
Bribed mob doesn't attack nor auto cast its skills.

**What should happen:**
Bribed mob attacks and casts its skills.

**Comment by Cefiro-Caecias** [comment]
I don't know what mobs you mean o.O

**Comment by DeltaVortex** [comment]
I honestly didn't check it on other mobs, but Deadwood Shamans in Felwood behave like I described. 
https://www.wowhead.com/npc=7158/deadwood-shaman
I guess if it's going to take programming each mob to work with Bribe then it's not worth xD

**Comment by DeltaVortex** [comment]
Ok so I just checked and the mob Winterfall Totemic in Winterspring also has the same issues. Spells do actually work but they don't auto cast and the mob refuses to attack. I think having the cooldown lowered during the beta period would be better to test more mobs? 30 min is too much.
https://www.wowhead.com/npc=7441/winterfall-totemic
