### ISSUE TITLE
Mascotas mecanicas - Cazador

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2470]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
https://es.wowhead.com/npc=107836/e-re-02
npc no enconttrado

https://es.wowhead.com/npc=107431/robonejo-con-armas
npc no encontrado

https://es.wowhead.com/npc=44616/pollo-de-batalla-ido
npc aparece como aliado (aura verde) lo cual no puede ser domesticado

https://es.wowhead.com/npc=115479/modelo-gu-4rd-3r
npc no encontrado

https://es.wowhead.com/npc=114992/aracnodrón-de-cobre
npc no encontrado

https://es.wowhead.com/npc=114993/aracnodrón-plateado
npc no encontrado

https://es.wowhead.com/npc=114991/aracnodrón-dorado
npc no encontrado

https://es.wowhead.com/npc=111820/amigador
npc no encontrado, debería estar durmiendo en los laboratorios de ingeniería y se debe activar con los botones encendidos de las 3 paredes de dicho laboratorio, lo cual no pasa porque no hay npc y no hay botones en las paredes del laboratorios de ingeniería.

**Comment by Cefiro-Caecias** [comment]
Reparados, y disponibles en el próximo update. En cuanto al último perro, no tengo info de los botones como para reproducir la secuencia, así que por ahora será domesticable sin necesidad de activar ese puzzle.

**Comment by Noahkrr** [comment]
el puzzle funciona así:
el muro de 6 luces
Pulsa 2, 5, 6 y 1.
el muro de 7 luces
Pulsa 5, 4, 6, 4 y 7.
el muro de 8 luces
Pulsa 6, 8, 4 y 7.
