### ISSUE TITLE
[NPC] Festerhide Grizzly

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2471]
**Links:**

https://www.wowhead.com/npc=95779/festerhide-grizzly

**What is happening:**

NPC grants 500 Dreamweavers reputation on kill.

EDIT: The issue might be triggered by [Darkheart Thicket: A Burden to Bear](https://www.wowhead.com/quest=42745/darkheart-thicket-a-burden-to-bear) world quest.

**What should happen:**

No rep for you on kill. sadkek

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
