### ISSUE TITLE
[Tyce] - Desuello - Profesion

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2473]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
ya tengo todo aprendido en desuello legion, misiones completadas. Tengo un problema, es que no sube los puntos de desuello, se quedo estancado en 715. logre subir a 741, matando adds en mazmorras y jefes de mazmorras, dejo de subir puntos. he farmeado en todas las zonas de las islas abruptas, mazmorras, Costa quebrada y Argus. pero no sube a 800
![image](https://user-images.githubusercontent.com/81131460/120139556-57628500-c19e-11eb-86b6-d3572ccea94a.png)
ese bonus +10, es un bug  visual, antes tenia minería, lo borre y me hice desuello ...

**Comment by Kirrkoi** [comment]
la profesion de mineria esta igual, llega 730p y no sube..
