### ISSUE TITLE
NPC - Valdemar Buscatormentas - Misiones de mundo de Profesiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2474]
**Links:**

from WoWHead or our Armory

**What is happening:**
Las misiones aparecen en el mapa, pero el NPC no las reconoce como activas

NPC que otorga las misiones de mundo
https://es.wowhead.com/npc=106904/valdemar-buscatormentas

Misiones de mundo de Profesiones:
Inscripción
https://es.wowhead.com/quest=41666/pedido-de-runa-vantus-nythendra
Joyería
https://es.wowhead.com/quest=41654/pedido-aro-de-ópalo-de-reina
Sastrería
https://es.wowhead.com/quest=41648/pedido-brazales-de-filoseda
Alquimia
https://es.wowhead.com/quest=41660/pedido-brebajeskaggl
Herrería
https://es.wowhead.com/quest=41636/pedido-coraza-de-piedra-ley
Desuello
https://es.wowhead.com/quest=41344/pedido-escamas-tormentosas
Peletería
https://es.wowhead.com/quest=41642/pedido-escarpines-de-pellejo-de-guerra
Herbolestería
https://es.wowhead.com/quest=41297/pedido-fjarnskaggl
Ingeniería
https://es.wowhead.com/quest=41678/pedido-pack-de-armas
Encantamiento
https://es.wowhead.com/quest=41672/pedido-palabra-de-celeridad
Minería
https://es.wowhead.com/quest=41313/pedido-piedra-ley
Pesca
https://es.wowhead.com/quest=41277/pedido-rayatormentas

Misiones de mundo
https://es.wowhead.com/quest=41345/suministros-necesarios-escamas-tormentosas
https://es.wowhead.com/quest=41298/suministros-necesarios-fjarnskaggl
https://es.wowhead.com/quest=41317/suministros-necesarios-piedra-ley

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
