### ISSUE TITLE
NPC - Sylvia Cornociervo - Misiones de mundo de Profesiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2475]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
Las misiones aparecen en el mapa, pero el NPC no las reconoce como activas

NPC que otorga las misiones:
https://es.wowhead.com/npc=106901/sylvia-cornociervo

Misiones de mundo de Profesiones
Inscripción
https://es.wowhead.com/quest=41664/pedido-de-runa-vantus-dragones-de-la-pesadilla
Joyería
https://es.wowhead.com/quest=41652/pedido-anillo-de-ámbar-intenso
Alquimia
https://es.wowhead.com/quest=41658/pedido-elixires-nemorosos
Herbolesteria
https://es.wowhead.com/quest=41292/pedido-frondasueño
Sastrería
https://es.wowhead.com/quest=41646/pedido-guantes-de-filoseda
Herrería
https://es.wowhead.com/quest=41634/pedido-guardabrazos-de-piedra-ley
Peletería
https://es.wowhead.com/quest=41640/pedido-máscara-de-pellejo-de-guerra
Encantamiento
https://es.wowhead.com/quest=41670/pedido-palabra-de-agilidad
Pesca
https://es.wowhead.com/quest=41272/pedido-perca-branquimusgo
Minería
https://es.wowhead.com/quest=41312/pedido-piedra-ley
Ingeniería
https://es.wowhead.com/quest=41676/pedido-pistola-de-vendas-de-pistón
Desuello
https://es.wowhead.com/quest=41338/pedido-cuero-de-petrapiel

Misiones de mundo
https://es.wowhead.com/quest=41293/suministros-necesarios-frondasueño
https://es.wowhead.com/quest=41316/suministros-necesarios-piedra-ley
https://es.wowhead.com/quest=41339/suministros-necesarios-cuero-de-petrapiel

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
