### ISSUE TITLE
NPC - Ransa Pluma Gris - Misiones de mundo de Profesiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2476]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
las misiones aparecen en el mapa, pero npc no reconoce las misiones de mundo activas

Npc que da la misiones
https://es.wowhead.com/npc=106902/ransa-pluma-gris

Misiones de mundo de profesiones
Inscripción
https://es.wowhead.com/quest=41665/pedido-de-runa-vantus-ursoc
Peletería
https://es.wowhead.com/quest=41641/pedido-bandas-de-vínculo-bélico
Herrería
https://es.wowhead.com/quest=41635/pedido-botas-de-piedra-ley
Joyería
https://es.wowhead.com/quest=41653/pedido-colgante-de-piedra-celestial
Alquimia
https://es.wowhead.com/quest=41659/pedido-elixires-de-avalancha
Herbolestería
https://es.wowhead.com/quest=41223/pedido-flor-de-raposa
Ingeniería
https://es.wowhead.com/quest=41677/pedido-martillo-automático
Encantamiento
https://es.wowhead.com/quest=41671/pedido-palabra-de-fuerza
Mineria
https://es.wowhead.com/quest=41206/pedido-piedra-ley
Pesca
https://es.wowhead.com/quest=41240/pedido-salmón-de-monte-alto
Sastrería
https://es.wowhead.com/quest=41647/pedido-toga-de-filoseda
Desuello
https://es.wowhead.com/quest=41235/pedido-cuero-de-petrapiel

Misiones de mundo
https://es.wowhead.com/quest=41224/suministros-necesarios-flor-de-raposa
https://es.wowhead.com/quest=41207/suministros-necesarios-piedra-ley
https://es.wowhead.com/quest=41237/suministros-necesarios-cuero-de-petrapiel

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
