### ISSUE TITLE
NPC - Veridis Fallon - Misiones de mundo de Profesiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2477]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
las misiones aparecen en el mapa, pero el NPC no reconoce las misiones de mundo activas

Npc que otorga las misiones
https://es.wowhead.com/npc=107376/veridis-fallon

Misiones de mundo de Profesiones
Inscripcion
https://es.wowhead.com/quest=41663/pedido-de-runa-vantus-elerethe-renferal
Herbolestería
https://es.wowhead.com/quest=41287/pedido-aethril
Ingenieria
https://es.wowhead.com/quest=41675/pedido-armatesta-de-activación-por-parpadeo
Peleteria
https://es.wowhead.com/quest=41639/pedido-bufas-de-vínculo-bélico
Joyeria
https://es.wowhead.com/quest=41651/pedido-colgante-de-azsunita
Sastreria
https://es.wowhead.com/quest=41645/pedido-cubrehombros-de-filoseda
Desuello
https://es.wowhead.com/quest=41326/pedido-escamas-tormentosas
Herreria
https://es.wowhead.com/quest=41633/pedido-grebas-de-piedra-ley
Alquimia
https://es.wowhead.com/quest=41657/pedido-jarabes-de-magia-pura
Encantamiento
https://es.wowhead.com/quest=41669/pedido-palabra-de-golpe-crítico
Pesca
https://es.wowhead.com/quest=41267/pedido-pez-reina-maldito
Mineria
https://es.wowhead.com/quest=41311/pedido-piedra-ley

Misiones de mundo
https://es.wowhead.com/quest=41288/suministros-necesarios-aethril
https://es.wowhead.com/quest=41327/suministros-necesarios-escamas-tormentosas
https://es.wowhead.com/quest=41315/suministros-necesarios-piedra-ley

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
