### ISSUE TITLE
Misiones - Tormenheim

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2478]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/quest=39594/una-prueba-de-poder
la mision se bugea al derrotar a Yotnar, no cuenta como objetivo derrotarlo..
link de youtube de la mision: https://www.youtube.com/watch?v=apW8hcj41KE

https://es.wowhead.com/quest=39652/donde-reinan-los-dragones
al tomar la mision, vethir me teletransporta a otra zona donde esta el dragon (Thrymjaris), dialogo con  Thrymjaris y se completa la mision. se omite lo de volar encima de vethir
link de youtube de la mision: https://www.youtube.com/watch?v=DKSc5otPK6M

https://es.wowhead.com/quest=38624/truenos
no aparece en el mapa y no se completa el objetivo de la mision. al encontrar al npc que termina la mision, la mision aparece completa..
![image](https://user-images.githubusercontent.com/81131460/120258435-a8827f80-c257-11eb-8e7d-627144a0e058.png)
![image](https://user-images.githubusercontent.com/81131460/120258465-ba642280-c257-11eb-8ac2-eda56206bc55.png)
link de youtube de la mision: https://www.youtube.com/watch?v=gcWs1Z0nRhY&t=27s

https://es.wowhead.com/quest=38823/las-runas-que-atan
bug visual, al completar objetivos destruir piedra ritual, rompes una piedra sigue apareciendo en el mapa como objetivo, si cuenta al romper la piedra ritual

https://es.wowhead.com/quest=38818/el-juicio-final
la mision se autocompleta omitiendo el combate con  vidente de runas Faljar y ayudar a Ashildir
![image](https://user-images.githubusercontent.com/81131460/120263411-3c0c7e00-c261-11eb-91d0-06b9e320a475.png)

link de youtube de la mision: https://www.youtube.com/watch?v=ifsHbRNWBsI

**Comment by Cefiro-Caecias** [comment]
1) https://es.wowhead.com/quest=39594/una-prueba-de-poder: acabo de probar la quest dos veces consecutivas, y me funcionó perfecta. Sólo si estás en Raid no te cuenta el objetivo.
2) https://es.wowhead.com/quest=39652/donde-reinan-los-dragones: reparada, disponible en el próximo update.

**Comment by Cefiro-Caecias** [comment]
3) https://es.wowhead.com/quest=38624/truenos: reparada, disponible en el próximo update.

**Comment by Cefiro-Caecias** [comment]
4) https://es.wowhead.com/quest=38823/las-runas-que-atan: reparada, disponible en el próximo update.
5) https://es.wowhead.com/quest=38818/el-juicio-final: se hará blizzlike más adelante.
