### ISSUE TITLE
Mylune Missing

### ISSUE THREAD

**Issue by QTstPie** [GuabinaCore/WoWKoi#2480]
**What is happening:**
The NPC Mylune for the quest Meet with Mylune is not spawning at all neither is the command board that she is normally next to 

**What should happen:**
These 2 NPCs should be there
![Capture](https://user-images.githubusercontent.com/85270454/120586901-3d68b280-c3e9-11eb-8ad7-4c7616c530e2.PNG)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
