### ISSUE TITLE
Maestro de establos - Cazador

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2482]
**Links:**

from WoWHead or our Armory

**What is happening:**
hay muchos otros maestros de establos, que no tienen la opcion de acceder a establo de mascotas
https://es.wowhead.com/npc=28690/tassia-cañada-susurrante
![image](https://user-images.githubusercontent.com/81131460/120689648-f1118700-c469-11eb-80f6-c7be8eb384b5.png)
https://es.wowhead.com/npc=44252/karin
https://es.classic.wowhead.com/npc=11069/jenova-petrescudo

**Comment by Cefiro-Caecias** [comment]
Reparados. Disponibles en el próximo update.
