### ISSUE TITLE
[Tyce] - Thunder Totem - elevators

### ISSUE THREAD

**Issue by jacobx97** [GuabinaCore/WoWKoi#2483]
**What is happening:**
Elevators in Thunder Totem in Highmountain sometimes disappear and you fall down.

**Comment by Cefiro-Caecias** [comment]
@ShikoSCS, este problema no es del GO del ascensor, ni un problema de fase. Asumo que es un problema del sistema multihilos, ya que cuando cambias de zona en el ascensor, y pasas de Thunder Totem Zone 7731 - Hall of Chieftains Area 7999 a la parte superior que es Highmountain Zone 7503 - Thunder Totem Area 7731, el sistema se demora algunos segundos en cargar el área, y por eso el ascensor desaparece también unos segundos. Este defecto es igual de perceptible en otras zonas, como por ejemplo en Dalran y la islita donde tienen el portal los DH, y otras más.
