### ISSUE TITLE
artifact weapon quest : injection of power 

### ISSUE THREAD

**Issue by mouhovic** [GuabinaCore/WoWKoi#2484]
**Links:** https://imgur.com/zHM5w1x

from WoWHead or our Armory 

**What is happening:** so basically i take the quest from the NPC to empower my Artefact weapon but when i try to do that i can't somehow because it says ' you need 100 artefact weapon to do that ' and as u know i cant go down to broken isles yet until i finish this quest so i cant get any AP 

**What should happen:** what should happen here is we get a free 100 AP to empower the weapon and move on with the quest because there is no way that we can get any AP from the start

**Comment by ventarius5** [comment]
You need your Artifact weapon equipped in order to receive 100 ap from the quest. That's pretty common thing to happen to ppl. I guess it should be a "global" reward to avoid such situations.

**Comment by mouhovic** [comment]
yes actually i was equipping the  weapon but got no AP as u can see in the pic ( click the link up there )

**Comment by mouhovic** [comment]
> You need your Artifact weapon equipped in order to receive 100 ap from the quest. That's pretty common thing to happen to ppl. I guess it should be a "global" reward to avoid such situations.

.

**Comment by Nephilimkoi** [comment]
> yes actually i was equipping the weapon but got no AP as u can see in the pic ( click the link up there )

Did you equiped the artifact. Abandoned the quest and retook it?

**Comment by ventarius5** [comment]
If they know, that completing the quest doesn't grant AP, it's too late to to retake I guess hehe
