### ISSUE TITLE
Darkmoon faire

### ISSUE THREAD

**Issue by TopliKroasan** [GuabinaCore/WoWKoi#2485]
1. [Zina Sharpworth](https://wowpedia.fandom.com/wiki/Zina_Sharpworth)
**Issue**: Sells too many variations with different prices of the same two items.
**Example**: https://youtu.be/j3fa-v-A-8k?t=57 (0:57)

2. [Mola, Whack-a-Gnoll](https://www.wowhead.com/npc=54601/mola)
**Issues**: Text to initiate game appears double, hits do not always register, hitting babies doesn't stun you and rewards a point, sometimes two will pop out from the same barrel and the 'pop ups' sometimes slow down.
**Example**: https://youtu.be/vRgiv4iSeX4

3. [Maxima Blastenheimer, Darkmoon Faire Cannoneer](https://www.wowhead.com/npc=15303/maxima-blastenheimer)
**Issues**: Text to initiate game appears double, force of trajectory after canceling wings feels slightly over-tuned (although I may be wrong)
**Also related**: [Teleportologist Fozlebub](https://www.wowhead.com/npc=57850/teleportologist-fozlebub#abilities) prices are wrong. Correct price: https://youtu.be/1KQgpNogjGM?t=50 (0:50)
**Example**: https://youtu.be/1KQgpNogjGM

4. [Rinling](https://www.wowhead.com/npc=14841/rinling)
**Issues**: shooting the gun does not hit the targets, rewards no points.

5. [Finlay Coolshot, Tonk Challenge](https://www.wowhead.com/npc=54605/finlay-coolshot)
**Issues**: the little tanks and blimps in the game to not move, unable to hit some of the targets, dismissing the game spawns the character inside the ring at the place of the tank.
**Example**: https://youtu.be/ibmCfjmHVRY

6. [Jessica Rogers, Ring Toss](https://www.wowhead.com/npc=54485/jessica-rogers)
**Issues**: Playing the game turns the character invisible, there is no turtle to throw rings at
**Example**: https://youtu.be/JNKL6BRIGL8?t=17

7. [Malle Earnhard, Race Official](https://www.wowhead.com/npc=74056/malle-earnhard) and [Patti Earnhard, Race Official](https://www.wowhead.com/npc=90473/patti-earnhard)
**Issues**: games cannot be started.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
