### ISSUE TITLE
[Tyce] - Spell Emerald Winds

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2487]
**Links:**
https://www.wowhead.com/item=139773/emerald-winds
https://www.wowhead.com/spell=221585/emerald-winds
https://www.wowhead.com/spell=221635/dream
**What is happening:**
I keep the buff and spell for the full 2 minutes after touching back down to the ground.

**What should happen:**
The buff and spell should end once I'm not in the air anymore.

**Comment by ShikoSCS** [comment]
It already works and was verified
