### ISSUE TITLE
Netherlight Temple - Scouting Map

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2488]
**Links:**
https://www.wowhead.com/netherlight-temple
https://wowpedia.fandom.com/wiki/File:Scouting_Map_priest.jpg
https://www.youtube.com/watch?v=R_O8exO_ueY&t=234s
**What is happening:**
The scouting map is very small
![image](https://user-images.githubusercontent.com/85613053/121440173-a5b51800-c944-11eb-8ef5-c74420290810.png)

**What should happen:**
The scouting map should be larger.
https://static.wikia.nocookie.net/wowpedia/images/f/f1/Scouting_Map_priest.jpg/revision/latest?cb=20180424031750

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.

**Comment by nevarden** [comment]
its missing entirely now since yesterday
