### ISSUE TITLE
[Tyce] - Mounts - Special Project Awards

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2489]
**Links:**
![image](https://user-images.githubusercontent.com/85613053/121441667-781d9e00-c947-11eb-8028-46a0c035ef77.png)

**What is happening:**
A bunch of non-blizzard custom modded swag mounts show up in the mount list.

**What should happen:**
The mounts shouldn't exist or be in the list.

**Comment by Cefiro-Caecias** [comment]
Fixed.
