### ISSUE TITLE
Quest: Dressed to Impress. ID: 14340

### ISSUE THREAD

**Issue by bedle** [GuabinaCore/WoWKoi#249]
**Links:**
https://www.wowhead.com/quest=14340/dressed-to-impress

**What is happening:**
Nothing. NPC "Image of Archmage Xylem" (NPC ID: 35187) is not spawned.

**What should happen:**
https://www.youtube.com/watch?v=Pa9JaSrb4Tg

NPC "Image of Archmage Xylem" should have been spawned, however players should be unable to complete quest until you put "Dingy Wizard Hat" on your head.

**Comment by LKArthas** [comment]
Azshara not yet finished taht Will be completed when questline is done with reparos 😁
