### ISSUE TITLE
Mision de mundo en mazmorra - bug mision en mazmorra incorrecta

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2490]
**Links:**
https://es.wowhead.com/quest=42926/cámara-de-las-celadoras-cómo-ha-llegado-ahí-arriba
from WoWHead or our Armory

**Lo que sucede:**
como ven en la imagen, estoy en Camaras del valor  en Tormenheim y me marcan dos misiones de mundo, una de ellas no pertenece a la mazmorra, sino que es la mision de mundo de Camara de las celadoras en Azsuna.
![image](https://user-images.githubusercontent.com/81131460/121461363-4ec73700-c974-11eb-87a1-0aa5c03755b3.png)
cuando voy a Camaras de las celadoras, la mision de mundo no se activa, solo se activa cuando entro a camaras del valor. La mision se activa en la mazmorra incorrecta.

**Comment by Cefiro-Caecias** [comment]
reparado. Disponible en el próximo update.
