### ISSUE TITLE
Cazador - Misiones - Sede

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2492]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
estas misiones no aparecen y los npc tampoco
https://es.wowhead.com/quest=44212/destino-oculto
https://es.wowhead.com/quest=45392/recuerdo-oscuro
https://es.wowhead.com/quest=46022/una-advertencia-urgente

**Comment by Cefiro-Caecias** [comment]
Hall pendiente de reconstrucción.
