### ISSUE TITLE
Battle for the Broken Shore [Horde]

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2493]
**Links:**
https://www.wowhead.com/quest=43926/legion-the-legion-returns
https://www.wowhead.com/quest=40518/the-battle-for-broken-shore
**What is happening:**
After completing the quest "To Be Prepared" the next quest in line is auto-completed, instead of sending us to the Broken Shore Scenario. There is no option to start the scenario. Instead, the quest can be handed in immediately and the scenario is skipped.
**What should happen:**
We should be given an entire scenario event to complete on the Broken Shore.
The scenario should start upon boarding Captain Russo's ship.
Holgar Stormaxe should provide dialogue to allow the scenario to be skipped.

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/123499374-787a9200-d5f3-11eb-9d63-32d356c2c67e.png)

**Comment by Cefiro-Caecias** [comment]
This scenario is being rebuilt. Patience ^^
