### ISSUE TITLE
In the Blink of an Eye

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2494]
**Links:**
https://www.wowhead.com/quest=44184/in-the-blink-of-an-eye

**What is happening:**

The teleportation and pillars of creation explanation gets skipped.

**What should happen:**
Dalaran should be in Deadwind Pass before finishing this questline, and finishing it should move Dalaran to The Broken Isles.

**Comment by Cefiro-Caecias** [comment]
This scenario is being rebuilt. Patience ^^
