### ISSUE TITLE
Stormheim - Grapple Points

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2495]
**Links:**
https://www.wowhead.com/item=138111/stormforged-grapple-launcher
https://www.wowhead.com/quest=38612/a-grapple-a-day
**What is happening:**
Able to use Grapple Points before getting a grapple launcher.

**What should happen:**
Should need to get a grapple launcher or have had one before being able to use grapple points.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
