### ISSUE TITLE
Nomi vendor recipes

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2496]
**Links:**
https://www.wowhead.com/quest=40990/a-good-recipe-list
https://www.wowhead.com/npc=101846/nomi
**What is happening:**

He sells quest item recipes immediately.

**What should happen:**
A recipe should only be visible to purchase after the quest to unlock that recipe has been completed.

**Comment by nevarden** [comment]
Another issue with Nomi. Any recipes I try to get him to research turn into requesting Nomi's Silver Mackerel.

![image](https://user-images.githubusercontent.com/85613053/122000223-b235d800-cd6b-11eb-893a-041a3a8a5f8e.png)

Any recipe I try to research results in this issue:
![image](https://user-images.githubusercontent.com/85613053/122000252-c11c8a80-cd6b-11eb-875e-c785e0b56f94.png)

**Comment by jacobx97** [comment]
I found another issue related to this quest. If you learn a recipe, abadon quest and take it again, you start from 0/6. So if you learn all recipes and you abadon quest, you can not complete it.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
