### ISSUE TITLE
Quests in Nar'thalas Academy

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2497]
**Links:**
https://www.wowhead.com/quest=37468/into-the-academy
https://www.wowhead.com/quest=42370/wanding-101
https://www.wowhead.com/quest=42371/study-hall-combat-research
https://www.wowhead.com/quest=37729/pop-quiz-advanced-rune-drawing
**What is happening:**
Both doors to each wing are accessible before doing any quests. They should be locked first.
Wanding 101 auto completes.
Study Hall: Combat Research auto completes.
Pop Quiz: Advanced Rune Drawing auto completes.

**What should happen:**
Wanding 101 should give you an extra action button that fires a shot out from your academy wand so you can shoot the targets.
Study Hall: Combat Research should have you grab a book from a bookshelf, put it on the table, and cause you to enter a fight. 3 times.
Pop Quiz: Advanced Rune Drawing should put little lines on the ground that have to be traced.

**Comment by Cefiro-Caecias** [comment]
All of that will be done blizzlike later on. Patience ^^
