### ISSUE TITLE
Toy - Copy of Daglop's Contract

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2498]
**Links:**
https://www.wowhead.com/item=138878/copy-of-daglops-contract

**What is happening:**
Buff shows up for 5 minutes and dialogue from some random NPC shows up, not even Daglop's lines.

**What should happen:**
Daglop should show up on top of your head and have his own dialogue.

**Comment by Cefiro-Caecias** [comment]
Partially repaired. Daglop will appear, follow you and say dialogues, but he will not climb on your shoulders. Available in the next update.
