### ISSUE TITLE
Quest - Shipwrecked Sailors [Horde]

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2499]
**Links:**

https://www.wowhead.com/quest=42268/shipwrecked-sailors 

**What is happening:**

There is no interaction available after slaying the mob. The NPC sailors have no reaction.

**What should happen:**
After killing a mob guarding a sailor, I should be able to interact with the sailor to rescue him.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
