### ISSUE TITLE
Sinking from within - Cape of Strangethorn

### ISSUE THREAD

**Issue by Spewee** [GuabinaCore/WoWKoi#250]
**Links:**
https://www.wowhead.com/quest=26663/sinking-from-within

from WoWHead or our Armory

**What is happening:**
The sabotaging of the Grog, Cannonballs and Gunpowder to not give quest credit when interacting with them, thus preventing from completing quest

**What should happen:**

Interacting with the quest items should credit allowing completion of quest, thanks

**Comment by LKArthas** [comment]
Fixed for next update
