### ISSUE TITLE
Misiones - Suramar

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2500]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/quest=41216/supervivencia-del-más-fuerte
https://es.wowhead.com/quest=41231/superdepredador
https://es.wowhead.com/quest=43582/parque-shalássico
estas misiones no aparecen, 
estan ordenadamente. al termino de estas misiones se desbloquea una mision de mundo https://es.wowhead.com/quest=43583/la-vida-se-abre-camino

https://es.wowhead.com/item=137179/grotesque-ettin-leather
este item no cae, deberia tener un 67% de chance de caida, el npc que lo arroja es https://es.wowhead.com/npc=104220/ettin-famélico

https://es.wowhead.com/quest=44719/irrupción-en-el-santuario
la gesta, se bugea a veces en la cuarta fase o 6ta fase. y cuando logras completar la gesta, no deja entregar la mision, Khadgar no reconoce la mision.

**Comment by Cefiro-Caecias** [comment]
1) Quest "Supervivencia del más fuerte", "Superdepredador" y "Parque shalássico", destrabadas.

2) El item "Grotesque Ettin Leather" no existe en nuestra DB, así que ahora el "Ettin famélico" te agregará directamente la quest en tu diario cuando lo mates, si no la entregaste antes, ya que esa quest la estaba dando el mismo NPC al que debes entregársela (cosa que también corregí).

3) Quest "Irrupción en el Santuario": la reconstruiré más adelante. Pero si ves que no puede completarla y quedas trabado allí, me avisas en nuevo Issue.

Todo disponible en el próximo update.
