### ISSUE TITLE
Shrine of the Ox - Monk quests are available to any class

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2501]
**Links:**

https://www.wowhead.com/npc=66260/master-hight

**What is happening:**

Master Hight starts all monk class quests even if you are not a monk.

[Complete Your Training: The Final Test](https://www.wowhead.com/quest=31944/complete-your-training-the-final-test) is auto complete.

![image](https://user-images.githubusercontent.com/63166930/121782987-afd94f80-cbac-11eb-99d7-e8b57f2d303d.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
