### ISSUE TITLE
Ingeniería Legión - Esquemas de items

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2502]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/item=137726/esquema-boya-de-piedra-ley
verificar el porcentaje de caida, no logro obtener el item

https://es.wowhead.com/npc=99630/carroñero-morroacre
este npc no existe en el juego. este npc al matarlo, tiene un 4% de caida, de esquema: boya de piedra ley 

https://es.wowhead.com/item=136701/esquema-choquinator
verificar el porcentaje de caida, no logro obtener el item

https://es.wowhead.com/item=144335/esquema-tecnoquevedos-a-medida
https://es.wowhead.com/item=144337/esquema-tecnoquevedos-de-eslabones
https://es.wowhead.com/item=144336/esquema-tecnoquevedos-bastos
https://es.wowhead.com/item=144338/esquema-tecnoquevedos-pesados
verificar el porcentaje de caida, no logro obtener estos items

**Comment by Cefiro-Caecias** [comment]
1) Item "Esquema: boya de piedra Ley": reparado.

2) Item "Esquema: choquinator": reparado.

3) NPCs "Carroñero Morroacre": se encuentran en el Dungeon Ojo de Azshara.

4) Esquemas reportados: drop mejorado al 10%.

Disponibles en el próximo update.
