### ISSUE TITLE
Stormheim - Cry Thunder! - Unleash Storm's Fury

### ISSUE THREAD

**Issue by jacobx97** [GuabinaCore/WoWKoi#2503]
**Links:**
https://www.wowhead.com/quest=38624/cry-thunder#

**What is happening:**
When you use spell Unleash Storm's Fury in Cry Thunder! quest, it kills you.

**What should happen:**
The spell should dmg just enemies

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
