### ISSUE TITLE
Entidad y NPC no existente - Gnomeregan - Mazmorra

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2504]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
https://es.wowhead.com/object=251048/perforágrafo-matriz-3005-e
no hay entidad, deberia estar para poder insertar mi tarjeta y poder desbloquear un cuarto, donde esta el npc: https://es.wowhead.com/npc=108106/mecazancudo-sensible

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
