### ISSUE TITLE
Quest - Tying Up Loose Ends

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2505]
**Links:**
https://www.wowhead.com/quest=39861/tying-up-loose-ends
https://www.youtube.com/watch?v=MN4smsIV0Xc

**What is happening:**

Load screen instantly teleported.

**What should happen:**

Fly.

**Comment by Cefiro-Caecias** [comment]
For the moment we will leave it in teleport mode, since I do not have information about the flying gryphon, spell or taxi path to reproduce the original flight.
