### ISSUE TITLE
Quest - Wisp in the Willows

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2506]
**Links:**
https://www.wowhead.com/quest=39354/wisp-in-the-willows
https://www.youtube.com/watch?v=sAPU2jTkaIY
**What is happening:**
Controlling a very awkward flying wisp, budding trees lack visuals,  and there are no hungry fish.

**What should happen:**
Should have different controls of the wisp, budding trees should have effects, and there should be hungry fish to chomp the wisp.

**Comment by Cefiro-Caecias** [comment]
Very true. However, I have no information on those cosmetic effects to recreate the 100% blizzlike quest, for now. It's on the to-do list.
