### ISSUE TITLE
Treasure for Thistleleaf Branch

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2507]
**Links:**

https://www.wowhead.com/item=130147/thistleleaf-branch

**What is happening:**

Can just loot the treasure and take it. Nothing spawns to fight.

**What should happen:**

When you click on the chest, sprites ambush you. After they die you can loot the treasure.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
