### ISSUE TITLE
Quest - Tears For Fears

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2510]
![image](https://user-images.githubusercontent.com/85613053/122004582-d399c280-cd71-11eb-9a13-f5700b957e3b.png)

**What is happening:**
They want me to find Tears of Elune, but they're right here already.

**What should happen:**
Tears of Elune shouldnt be here in this early phase.

**Comment by Cefiro-Caecias** [comment]
I'll fix it when I rebuild the area. Patience.
