### ISSUE TITLE
[Tyce] - Artifact Quest - The Nexus Vault

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2512]

**Comment by nevarden** [comment]
Issue 2:
![image](https://user-images.githubusercontent.com/85613053/122114557-a89a8780-cde0-11eb-9270-47280181c908.png)
Leaving group while in the scenario teleports you to the front and sticks you in the air, unable to logout or hearth.

**Comment by Cefiro-Caecias** [comment]
Issue 1, fixed; available in the next update.

Issue 2 ---Z @ShikoSCS
