### ISSUE TITLE
Stormheim - untargetable enemy skeletons

### ISSUE THREAD

**Issue by jacobx97** [GuabinaCore/WoWKoi#2513]
**Links:**
https://www.wowhead.com/npc=109795/neglected-bones

**What is happening:**
All enemy skeletons in Field of Fallen Kings in Stormheim are untargetable, so you can not kill them, when they are attacking you (you have to just run away).
![WoWScrnShot_061621_065922](https://user-images.githubusercontent.com/74407627/122173554-22368200-ce82-11eb-979a-10add3ef2968.jpg)

**What should happen:**
They should be targetable

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
