### ISSUE TITLE
Demon Hunter starting Zone Quest ( The keystone)

### ISSUE THREAD

**Issue by 11011010** [GuabinaCore/WoWKoi#2514]
**What is happening:**

She seems to hit to hard. After trying 3 times in tank spec i just kited her down to the other mobs and kill her.

**What should happen:**

https://www.youtube.com/watch?v=d5j-1QUwLYY

**Comment by 11011010** [comment]
Also some npcs which should be dead? are alive with full hp and you cannot attack them.

**Comment by 11011010** [comment]
Kayn sunfury is also double spawned ( in the down area) maybe because of zoning?

**Comment by Cefiro-Caecias** [comment]
Arthas is already rebuilding the area. Patience ^^
