### ISSUE TITLE
Quest - Stormheim - Victory is Eternal

### ISSUE THREAD

**Issue by jacobx97** [GuabinaCore/WoWKoi#2515]
**Links:**
https://www.wowhead.com/quest=39853/victory-is-eternal

**What is happening:**
Valkyries should help you to beat boss in this quest, they are just standing and watching.

**What should happen:**
Valkyries should fight the boss with you

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later. Patience ^^
