### ISSUE TITLE
Kethrazor( DH starting area) 

### ISSUE THREAD

**Issue by 11011010** [GuabinaCore/WoWKoi#2516]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/npc=96997/kethrazor
**What is happening:**
I had a Double spawm and the spawned adds are not killable

**What should happen:**
1 Spawn and adds should be killable ;)
https://www.youtube.com/watch?v=JAeYz6jheDo

**Comment by Cefiro-Caecias** [comment]
Arthas is already rebuilding the area. Patience ^^
