### ISSUE TITLE
NPC's should be dead.

### ISSUE THREAD

**Issue by 11011010** [GuabinaCore/WoWKoi#2517]
**Links:**

from WoWHead or our Armory

**What is happening:**
Around quest "all the way up"
https://www.wowhead.com/quest=39686/all-the-way-up
are alive?

**What should happen:**
https://www.youtube.com/watch?v=UskP-x722Ps
Most dead and a fight like shown in the video.
Also a dialog is missing.

**Comment by Cefiro-Caecias** [comment]
Arthas is already rebuilding the area. Patience ^^
