### ISSUE TITLE
DH Quest- Multiple

### ISSUE THREAD

**Issue by 11011010** [GuabinaCore/WoWKoi#2518]
**Links:**

https://www.wowhead.com/quest=39688/between-us-and-freedom
**What is happening:**

Quest not completing on kill when the npc gets the last hit.

**It happens with other quest mobs to in the DH starting area. But someone needs to recheck.**

**What should happen:**
Quest complete, does not matter who gets the last hit.
This is super important for or we will have each demon hunter have fight for last hit ;)

**Comment by 11011010** [comment]
same for the Quest forged in fire https://www.wowhead.com/quest=39683/forged-in-fire

**Comment by Cefiro-Caecias** [comment]
Arthas is already rebuilding the area. Patience ^^

**Comment by Sariet** [comment]
![image](https://user-images.githubusercontent.com/88337786/127941689-1a4f71a7-0300-4439-97eb-aee63caf79f1.png)

When you click this owl and abandon the quest then kill the quest boss you will then get the quest completion for Between us and Freedom.
