### ISSUE TITLE
Double spawm Vault of wardens.

### ISSUE THREAD

**Issue by 11011010** [GuabinaCore/WoWKoi#2519]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=39690/illidari-we-are-leaving

**What is happening:**
2 times Archmage Khadgar

**What should happen:**
1 time Archmage Khadgar is enough

**Comment by Cefiro-Caecias** [comment]
Arthas is already rebuilding the area. Patience ^^
