### ISSUE TITLE
[Tyce] - Dungeon  - Darkheart Thicket missing mechanics

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2521]
**I've only done this as a 2-man on Normal mode. All of these have only been tested on Normal mode.**

**What is happening:**
Crazed Razorbeak: 'Propelling Charge' sends them in a direction very very slowly. Doesn't move, damage, or stun correctly.
Dreadsoul Poisoner: Seems like when an effect ends from this mob, other nearby mobs often will ninja-pull from very far away. If another poisoner gets ninja-pulled, then its quite likely that poisoner will continue the chain of ninja-pulling.
Rotheart Dryad: Not leaping away ever.
Vilethorn Blossom: Not casting one of their ranged 'root burst' spells with the swirl effect underneath.
Rotheart Keeper: Not summoning 'Vile Mushrooms.'
Nightmare Dweller: If their 'Tormenting Eye' cast finishes, the targeted player isn't being feared.
Oakheart: After 'Crushing Grip' ends, the tank should get thrown at a specified player. Instead, the tank just gets thrown straight down.
Hatespawn Slime: Not detonating after death. 
Hatespawn Whelpling: Not hatching from any of the eggs before combat with Dresaron.
Taintheart Summoner: Their 'Curse of Isolation' doesn't harm nearby players.

https://www.wowhead.com/spell=220369/vile-mushroom
https://www.wowhead.com/spell=204246/tormenting-fear
https://www.wowhead.com/spell=201191/dreadburst
https://www.wowhead.com/spell=199313/hatch-whelpling

**Comment by nevarden** [comment]
**MORE MISSING MECHANICS** 
Frenzied Nightclaw: puts 'Frantic Rip' on the group rather than the player it leaps to.
Dreadsoul Ruiner: their 'Star Shower' ability should summon several waves of stars, instead it only casts 1 wave.
Oakheart: the 'Strangling Roots' don't root.
Festerhide Grizzly:(*on mythic*) should spew corruption, summoning adds that leave a trail of bad on the ground.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
