### ISSUE TITLE
Quest "You as and shall recieve" annoying dropchance

### ISSUE THREAD

**Issue by 11011010** [GuabinaCore/WoWKoi#2522]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=41804/ask-and-you-shall-receive
**What is happening:**
https://www.wowhead.com/item=136385/crystallized-soul
It seems the dropchance for a "Crystialized soul" is not 100 %  
seems like 2/7 :-D

**What should happen:**
It should have it for 100 %

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
