### ISSUE TITLE
Stage 6 "Venegence of the Illidari"

### ISSUE THREAD

**Issue by 11011010** [GuabinaCore/WoWKoi#2524]
**Links:**

from WoWHead or our Armory

**What is happening:**
I cannot attack "Caria Felsoul"
Quest" the Venegence will be yours"

She says:
"The legion is only the beginning. My blades call upong power from beyond!"
Jumps away and stays in pose and does nothing.

**What should happen:**
She should attack you when you get in range.

**redoing the scenario fixed the problem
still should not happen on release ;)

**Comment by 11011010** [comment]
I did the Scenario 8 times already, 
after 3 tries i could do the fight and then i had another bug that my return do dalaran got not registed so I had to do it again..

**Comment by 11011010** [comment]
I cannot carry another pair of them so i cannot finish the quest at all. Character "Big" needs a quest complete gm command :-D
[Vengeance Will Be Ours]

**Comment by nevarden** [comment]
still bugged

**Comment by Cefiro-Caecias** [comment]
Arthas is already rebuilding the area. Patience ^^
