### ISSUE TITLE
NPC Flog the Captain-Eater

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2527]
**Links:**
https://www.wowhead.com/npc=89884/flog-the-captain-eater

**What is happening:**
Walks after the player while still keeping the 'Anchor Drag' buff. Doesn't attack or anything, just slides around after you.

**What should happen:**
Getting in combat should stop his Anchor Drag and then he gets actual abilities and attacks.

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/122295309-4744e800-ceb6-11eb-8d9d-d93cfda6f885.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update (although I couldn't remove the vertical chain thing).
