### ISSUE TITLE
Non-English when hovering over some things in Azsuna

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2528]
No. 1
![image](https://user-images.githubusercontent.com/85613053/122292133-e1a32c80-ceb2-11eb-9fd0-28eb90b625f5.png)
https://www.wowhead.com/object=251168/ephemeral-crystal

No. 2
![image](https://user-images.githubusercontent.com/85613053/122293767-9722af80-ceb4-11eb-8b17-e4404e73fead.png)
https://www.wowhead.com/quest=39390/a-mysterious-text

No. 3 
![image](https://user-images.githubusercontent.com/85613053/122294177-08faf900-ceb5-11eb-9a5a-24aab4f2025e.png)
![image](https://user-images.githubusercontent.com/85613053/122294379-39429780-ceb5-11eb-9f8d-aa0d4b15c5ff.png)
![image](https://user-images.githubusercontent.com/85613053/122295544-8e32dd80-ceb6-11eb-84f1-735961fbb70d.png)
https://www.wowhead.com/quest=37495/plunder-the-cove

**Comment by NightwindOI** [comment]
https://github.com/GuabinaCore/WoWKoi/issues/2534

**Comment by IntroverseLaw** [comment]
Dalaran Non-English Interactions

Nomi's Cooking Table at 69.76, 38.25
![langCookingTable6976-3825](https://user-images.githubusercontent.com/87998390/127749107-8cc62511-387a-46b3-a25c-2526179c076b.png)

Desmond's Chest at 28.5, 64.49
![langDesmongChest285-6449](https://user-images.githubusercontent.com/87998390/127749120-6df5efdb-b841-416d-822a-95f0c6537a00.png)

The Annals of Light and Shadow Vol.1 at 30.03, 51.44
![langHiddenAppearanceDPriest3001-5144](https://user-images.githubusercontent.com/87998390/127749138-471fb3cc-f57b-4f6d-a5a2-786db5e7b5a9.png)

Warmage Silva at 33.46, 47.36
![langWarmageSilva3346-4736](https://user-images.githubusercontent.com/87998390/127749285-2a6d3680-197d-4767-bf89-f43e62e39894.png)
![langWarmageSilva2](https://user-images.githubusercontent.com/87998390/127749287-81bad401-74f7-44ab-9385-ec6fff2cfb73.png)

Both the scroll and the wand (toy). At 47.52, 41.5
![langScrollWand4752-415](https://user-images.githubusercontent.com/87998390/127749187-0d95cbf3-7194-466a-9e56-c7a31ed3167c.png)
![langScrollRussian](https://user-images.githubusercontent.com/87998390/127749193-8f46f5a5-7fd8-4094-b834-2e13a75d2265.png)

Levia's Research Journal at 46.42, 40.02
![langLeviaNote4642-4002](https://user-images.githubusercontent.com/87998390/127749215-d8853ef0-3756-4ab8-8bf3-3a056a8f8816.png)

Obliterum Forge at 42.64, 27.12
![langObliterumForge](https://user-images.githubusercontent.com/87998390/127749246-5df83e3a-c724-4696-aafc-9b4fe5ce2945.png)

Pretty much all of the interactable tailoring objects in this workshop 35.54, 34.13
![langTailor](https://user-images.githubusercontent.com/87998390/127749421-2f410b4e-084f-4d9f-9fc9-97a2920c1cfd.png)

Pillars of Creation at Portrait Room 47.3, 59.87
![langPillars473-5987](https://user-images.githubusercontent.com/87998390/127749381-d1f0e603-6d0c-43df-ac05-2afdf80a136b.png)
![langPillars2](https://user-images.githubusercontent.com/87998390/127749428-80d33394-260d-4b58-8a63-0e80cee18ec0.png)

Shadow Word:Pain IV at Chamber of the Guardian 60.51, 71.13
![langChamberOfTheGuardian6051-7113](https://user-images.githubusercontent.com/87998390/127749451-e76c150c-52c1-4a4b-8541-b2370fd7afa0.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. Don't forget to clear Cache.
