### ISSUE TITLE
[Tyce] - Monk Class Hall - Brewhouse

### ISSUE THREAD

**Issue by jacobx97** [GuabinaCore/WoWKoi#2529]
**Links:**
https://www.wowhead.com/order-advancement=254/brewhouse

**What is happening:**
After unlocking the Brewhouse upgrade in Class Hall Upgrades you still can not access Stormstout Inn, because the doors are still closed.

**What should happen:**
The doors of the Stormtout Inn should be opened and you should be able take Bubbling Keg once a day.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
