### ISSUE TITLE
Event - STV fishing

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#253]
**What is happening:**

Event isn't starting.

**Comment by DeltaVortex** [comment]
Event started but fishing schools don't spawn

**Comment by Cefiro-Caecias** [comment]
There is no bug present. The event lasts two hours, and is activated every Sunday from 2pm to 4pm.

**Comment by DeltaVortex** [comment]
lol I'm used to STV fish having their own spawn but now it's shared with other fish according to wowhead so sorry for the false report ^^
