### ISSUE TITLE
Dh- havoc - Eternal Vigil

### ISSUE THREAD

**Issue by 11011010** [GuabinaCore/WoWKoi#2533]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=42869/eternal-vigil

**What is happening:**

Nothing, you fly down and nothing happens :-D

**What should happen:**
https://www.youtube.com/watch?v=tTP9cwH2ISw

*What fixes it?
A relog.

**Comment by Cefiro-Caecias** [comment]
It is a map loading defect. If you stay a few seconds in the area, the NPCs will appear when the system loads the area.
