### ISSUE TITLE
Quest: give-me-sight-beyond-sight Wrong language.

### ISSUE THREAD

**Issue by 11011010** [GuabinaCore/WoWKoi#2534]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=39262/give-me-sight-beyond-sight

**What is happening:**
Wrong language in quest text
![image](https://user-images.githubusercontent.com/69040574/122462220-01267c00-cfbd-11eb-8f62-85ffc1946409.png)

**What should happen:**
correct english.

**Comment by 11011010** [comment]
Also I had to accept the quest 2 times because after speaking to him i did not get the "talk to him complete"

**Comment by NightwindOI** [comment]
added to https://github.com/GuabinaCore/WoWKoi/issues/2528

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. Don't forget to clear Cache.
