### ISSUE TITLE
[Tyce] - GCD issue. absolutely urgent. has to be fixed before release.

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2535]
**Links:**
theres a 12 minute video, tried to explain as much as i can whats wrong. https://www.youtube.com/watch?v=v6sp4uhOt24
also the initial video i recorded before and used to show. https://www.youtube.com/watch?v=2ijD5xKINY4
from WoWHead or our Armory

**What is happening:**

**What should happen:**

**Comment by Arkanheal** [comment]
Might be the way server handles spell batching. Need some investigations
