### ISSUE TITLE
NPC - Roach - critter grants rep

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2537]
**Links:**

https://www.wowhead.com/npc=4076/roach

**What is happening:**

Grants reputation on kill.

![image](https://user-images.githubusercontent.com/63166930/122566736-2b714b80-d048-11eb-8209-4983acd84c3c.png)

EDIT: This ID was already reported and I still encountered the issue, strange. Unless this was the old core report. https://github.com/GuabinaCore/WoWKoi/issues/1650
**What should happen:**

No rep for you sadkek

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
