### ISSUE TITLE
Neltharion's Lair mechanics

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2538]
**Normal mode**

**What is happening:**
Tarspitter Lurker: They interrupt their Viscid Bile cast to phase out of existence rather than submerge. They then phase back into existence a few seconds later and run to the tank. 
Blightshard Skitter: give 300 rep/kill if you have a rep tabard on. (adds during Rokmora fight)
Understone Drummer: Attempts to run to the drum after entering combat, but will just stay and fight if any CC gets applied. 
Stoneclaw Hunter: Doesn't summon a new pet if it lives long enough after its pet has died.
Rockbound Pelter: Runs back into melee range after leaping away, instead of consistently throwing discs from range.
Blightshard Shaper: Targets most threatening player with Stone Bolt casts instead of any player.
Petrifying Totem: The totem follows its Blightshard Shaper around instead of staying in place.
Rotdrool Grabber: Moves around in combat instead of planting itself where it spawns. Should spawn a Rancid Pool around it after spawning.

Naraxas lootpile disappeared as soon as 1 person looted it. 
'Naraxas’ Spiked Tongue' - dropped for guardian druid with guardian as their targeted loot specialization.

**Links:**
https://www.wowhead.com/spell=183433/submerge
https://www.wowhead.com/spell=183560/rancid-pool

**Comment by nevarden** [comment]
The Blightshard Shaper and Rockbound Pelter cast far less often than they should be.
Understone Drummer gets 2 buffs instead of 1 when summoning adds. Stunning the drummer only removes 1 buff. Killing the drum after the Drummer is already running towards it doesn't prevent the Drummer from using the drum and summoning adds.

**Comment by Cefiro-Caecias** [comment]
* Tarspitter Lurker: Mmmm... It is a glitch in the "Submerge" spell. Referred to Arthas for resolution, it will be ready shortly.

* Blightshard Skitter: Fixed. They will no longer give reputation when killed.

* Understone Drummer: Referred to Arthas for resolution, it will be ready shortly.

* Stoneclaw Hunter: Fixed. The Stoneclaw Hunter will summon a new Rockback Gnasher, two seconds after the latter's death.

* Rockbound Pelter: Fixed. If you are between 5-25 yards, it will use the Jagged Disc without moving from its place. If you get within 5 yards or less, it will use Retreat once every 10 seconds, then continue to cast Jagged Disc without moving.

* Blightshard Shaper: Fixed.

* Petrifying Totem: Fixed.

* Rotdrool Grabber: Fixed.

* Naraxas lootpile: In review, referred to Arthas.

*Naraxas Spiked Tongue: In review, referred to Shiko.

All available in the next update.
