### ISSUE TITLE
[Tyce] - Rogue subtlety artifact chain bugged

### ISSUE THREAD

**Issue by Dorleloriel** [GuabinaCore/WoWKoi#2541]
**Links:**
https://www.wowhead.com/quest=41924/fangs-of-the-devourer

**What is happening:** after entering the scenario to get the artifact you are to confront Akaari shadowgore, when you kill her she doesnt give you credit for it so you are basically trapped in the scenario since she doesnt respawn

**What should happen:** killing akaari should give you credit and transport you to phase 2 of the scenario

**Comment by Dorleloriel** [comment]
after trying for the 3rd time, you just have to stop dpsing her at 50% till she does her roleplay, I think you shouldnt be able to kill her before that

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
