### ISSUE TITLE
Quest - The Final Judgment

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2544]
**Links:**
https://www.wowhead.com/quest=38818

**What is happening:**
Unscripted auto-complete quest. You have to just walk straight into Helheim and hand in a quest that says you were captured.

**What should happen:**
Should get banished to Helheim while trying to fight Runeseer Faljar.

**Comment by Cefiro-Caecias** [comment]
Fixed, 95% blizzlike. Available in the next update.
