### ISSUE TITLE
Quest - An Unworthy Task

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2545]
**Links:**
https://www.wowhead.com/quest=39837/an-unworthy-task

**What is happening:**
Auto-completed and the prisoner is already free to hand the quest into.

**What should happen:**
Should have to go around opening cages until you free the right prisoner.

**Comment by nevarden** [comment]
Tons of missing dialogue and animations through the entire questline in Helheim.

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, when the area is rebuilt.
