### ISSUE TITLE
Quest - Paid in Lifelood

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2546]
**Links:**
https://www.wowhead.com/quest=39855/paid-in-lifeblood

**What is happening:**
Just stand there at the altar waiting for a loading screen while someone talks to themself and then suddenly appear back at Valdisdall.

**What should happen:**
Should have a chat with Helya and then be lifted up and teleported out.

**Comment by Cefiro-Caecias** [comment]
It will become blizzlike later, when the area is rebuilt.
