### ISSUE TITLE
Quest - A Heavy Burden

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2547]
**Links:**
https://www.wowhead.com/quest=40078/a-heavy-burden

**What is happening:**
Walk up to the "Lanza" skewer and click it. No fish carrying involved.

**What should happen:**
Havi should have dialogue, move to the fire, and there should be fish to carry and cook for him.

**Comment by Cefiro-Caecias** [comment]
Fixed, blizzlike; like all the quests offered by Havi, since I was forced to create, order and concatenate the SAIs of all of them. I hate you. Available in the next update ^^
