### ISSUE TITLE
Quest - Stem The Tide

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2548]
**Links:**
https://www.wowhead.com/quest=40003/stem-the-tide
https://www.wowhead.com/spell=210536/rain-of-fire
https://www.wowhead.com/spell=190895/horn-of-helheim
https://www.wowhead.com/spell=190919/guardian-orbs
https://www.wowhead.com/spell=190863/call-of-the-storm

**What is happening:**
Vethir animations are missing. Somehow able to get rain of fire applied to yourself. It's a permanent DoT that requires death to remove. Missing extra action button.

**What should happen:**
Should show more animations, and should have an extra action button that toggles between 3 spells each cast.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
