### ISSUE TITLE
Quest - Stormheim's Salvation

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2549]
**Links:**
https://www.wowhead.com/quest=40005/stormheims-salvation

**What is happening:**
Get teleported up and takes like 5 minutes before Skovald appears. Skovald also doesn't move once the encounter begins. Missing the extra action button. Get teleported down after fighting Skovald and speaking with Vethir. 

**What should happen:**
We should ride Vethir up to Skovald, have a scripted encounter, and then ride Vethir back down after Skovald escapes.

**Comment by Cefiro-Caecias** [comment]
It will go blizzlike when you rebuild the area.
