### ISSUE TITLE
Quest: Into the Raptor's Den, Id:905

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#255]
**Links:**
https://www.wowhead.com/quest=905/into-the-raptors-den
https://www.youtube.com/watch?v=G4WUXUiEbDk
from WoWHead or our Armory

**What is happening:**
Two things:
1) When close to the nests, clicking the feathers doesn't give you credit,
2) The area marked on the minimap that has the Blue Raptor Nest in it, doesn't have the appropriate nest.
The 2nd one misleads the played to thinking he can't complete the quest.

**What should happen:**
Clicking the feathers when you are close to each nest should give you the credit and the area with the Blue Raptor Nest should be moved to the proper location as showed in the linked video, up the hill.

**Comment by bedle** [comment]
Completed the quest today just fine.
Firstly i farmed few feathers, to be sure that i have 3 in my inventory.
Second, when close to the nest mousing over the nest mouse cursor should change to mechanism (interaction) cursor. Right clicking on the nest with feathers in the inventory should give you credit toward the quest.
Blue Nest. There's small uphill path on the right side of Raptor Nests zone. Going up the path you will reach Blue Nest.

**Comment by Serithul** [comment]
The blizzlike way of the quest is not clicking the nest or an egg, but click the feather in your inventory when you are close to the nest. And yes you are right about the blue nest being on that uphill, but area marked on the minimap though for the blue nest does not show the uphill.

**Comment by bedle** [comment]
Correct on both.
Took me a while to find Blue Nest due to not being when its marked on minimap.
Just wanted to confirm that quest works, tho took me a bit to find how can be completed.
