### ISSUE TITLE
Quest - No Wings Required

### ISSUE THREAD

**Issue by IcyNovaX** [GuabinaCore/WoWKoi#2551]
**Links:**
https://www.wowhead.com/quest=38318/no-wings-required
**What is happening:**
Nothing happens after you grapple to the grapple point.
**What should happen:**
On the wall the quest is updated to meet Commander Lorna Crowley inside Hrydshal.

**Comment by Cefiro-Caecias** [comment]
Repaired. I was also forced to repair the other quests in the chain, up to "Above the Winter Moonlight". Available in the next update.
