### ISSUE TITLE
no deberia recibir reputacion - PNJ - Amalgama de almas

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2552]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
jefe de mazmorra (Torreon Grajo Negro)
https://es.wowhead.com/npc=98542/amalgama-de-almas
da reputacion con Pandaren tushui al matar a Amalgama de Almas
![image](https://user-images.githubusercontent.com/81131460/122859042-f7fd1e00-d2e0-11eb-96f6-9d39c5eba163.png)
no tengo tabardo alguno, y no debería dar reputación.

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
