### ISSUE TITLE
NPC duplicado - Sylvia Cornociervo

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2553]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
https://es.wowhead.com/npc=106901/sylvia-cornociervo
![image](https://user-images.githubusercontent.com/81131460/122971843-1d2b7400-d355-11eb-86f2-5fdd7a79990a.png)
 este npc da misiones de mundo de profesiones, las cuales no se activan correctamente, deberian activarse automaticamente al llegar a la zona de Lorlatil, al completar la mision debemos entregar la mision de mundo al npc (Sylvia cornociervo). las misiones de mundo de profesion deberian visualizarse en el mapa lo cual no sucede..

**Comment by Cefiro-Caecias** [comment]
Duplicado retirado; el resto, en revisión. Disponible en el próximo update.

**Comment by Kirrkoi** [comment]
npc diplicado sigue...
![image](https://user-images.githubusercontent.com/81131460/128768844-a6429df1-6f8f-4810-91f7-3621e00814c9.png)
