### ISSUE TITLE
[Tyce] - Mazmorra - El regreso de Karazhan bug?

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2554]
**Links:**

from WoWHead or our Armory

**What is happening:**
1- Usando el Buscador de mazmorras especificas en Herocias
- La mazmorra Karazhan inferior, mi pj inicia en cerca del jefe final (Attumen el Montero)
![image](https://user-images.githubusercontent.com/81131460/123157541-479e2f80-d430-11eb-97c7-fcda15314884.png)
deberia aparecer en la entrada de la mazmorra.
comencé en el final de la mazmorra, ahora trato de llegar al primer jefe y la puerta esta cerrada, intente tomar atajo por la otra puerta, tambien esta cerrada
![image](https://user-images.githubusercontent.com/81131460/122980962-e195a780-d35e-11eb-88fb-3a4300dcafdd.png)

- La mazmorra Karazhan Superior, aparezco en penultimo jefe de la mazmorra (Devorador de mana), y otro bug es que me aparecen como objetivos de Karazhan inferior y la mazmorra dice karazhan inferior
![image](https://user-images.githubusercontent.com/81131460/123158371-51746280-d431-11eb-9bd9-d8e042ba7241.png)
2- Usando el buscador de mazmorras heroicas aleatorias
inicia mi PJ en el jefe final del nivel inferior (Attumen el Montero)
![image](https://user-images.githubusercontent.com/81131460/123167848-bda89380-d43c-11eb-8202-3921c6027c5a.png)

3- Al entrar de forma manual
- Al entrar a la mazmorra karazhan en heroico, funciona bien, inicio es donde deberia estar, 3er jefe Moroes me arrojo un item 880. 

- Al entrar a la mazmorra karazhan en mitico, inicio en el comienzo de la mazmorra 
![image](https://user-images.githubusercontent.com/81131460/123162003-b5008f00-d435-11eb-96fb-e744c237cffc.png)
pero la barra de tropas enemigas, solo cuenta los espitirus melancolicos como credito al matarlos, los demas adds  no los cuenta
![image](https://user-images.githubusercontent.com/81131460/123162553-5c7dc180-d436-11eb-900f-4c8c3ea47771.png)
![image](https://user-images.githubusercontent.com/81131460/123162730-95b63180-d436-11eb-9738-85e9ae58c77b.png)
al terminar de matar a los 4 jefes del nivel inferior, al subir las escaleras, la puerta para subir al nivel superior esta cerrada, lo cual es imposible terminar la mazmorra
![image](https://user-images.githubusercontent.com/81131460/123165881-65709200-d43a-11eb-965d-54691cb6100f.png)

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
