### ISSUE TITLE
[Tyce] - Gesta - Arma artefacto - Cazador Punteria

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2555]
**Links:**

from WoWHead or our Armory

**What is happening:**
al matar al Heraldo Xarbizuld, no lo cuenta como objetivo, ya se queda estancado en la fase 5
![image](https://user-images.githubusercontent.com/81131460/123363267-bca85c80-d537-11eb-8c55-e219239f4c6e.png)
logre pasar la fase 5, en el intento 4to, ahora se bugea en la fase 6, me pide derrotar al Alto Inquisidor Qormaladon y sus ojos. al derrotarlo, el npc (veressa) se libera y sigue caminando, llegando al final de la gesta. la mision se completa y tengo opcion de tomar el arco artefacto,(bug visual de fase 6, ya veressa aparece en la fase final, pero el objetivo de fase 6 no cuenta como objetivo).
![WoWScrnShot_062421_230419](https://user-images.githubusercontent.com/81131460/123370093-a228b000-d544-11eb-88fc-0b6761904022.jpg)
PDta: logre tomar el arco, obtuve el arma artefacto, la fase 6 bug visual o mala coordinacion de faseo del npc

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
