### ISSUE TITLE
Quest - Neltharion's Lair: Potent Powder

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2556]
**Links:**
https://www.wowhead.com/quest=39335/neltharions-lair-potent-powder

**What is happening:**
When opening the Precipitating Powder, there is nothing to loot. 

**What should happen:**
Should get loot so you can finish the quest.

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/126008826-4d8de5e6-3b8c-4e99-82b9-361c28d1818d.png)

**Comment by nevarden** [comment]
![WoWScrnShot_071821_155316](https://user-images.githubusercontent.com/85613053/126087598-eda0ad2b-8692-40cd-89d1-b0f584b3265d.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
