### ISSUE TITLE
Quest - Advanced Quenching

### ISSUE THREAD

**Issue by j-9000** [GuabinaCore/WoWKoi#2557]
**Links:**

https://www.wowhead.com/quest=44449/advanced-quenching

**What is happening:**

cant complete because he is not giving the mats

**What should happen:**

he should give you some Shopkeeper's Leystone Ore to start with

**Comment by j-9000** [comment]
this part was fixed but quest still broken as there is no "Frozen Quenching Trough"

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
