### ISSUE TITLE
Bolsa de recuperación hermética - objeto 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2558]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/item=141179/bolsa-de-recuperación-hermética
al abrir la bolsa no me da items, deberia darme items aleatorios de la mazmorra ojo de azshara en mitico
![image](https://user-images.githubusercontent.com/81131460/123483959-350d2d00-d5cd-11eb-97e2-52d3f47eb01d.png)

**Comment by Cefiro-Caecias** [comment]
Reparado; recibirás 3 items aleatorios la próxima vez que las abras. Disponible en el próximo update.
