### ISSUE TITLE
Quest: Gnomish Engineering

### ISSUE THREAD

**Issue by dan2142** [GuabinaCore/WoWKoi#256]
https://www.wowhead.com/quest=29477/gnomish-engineering

Npc Roxxik https://www.wowhead.com/npc=11017/roxxik 
He dose not have the Gnomish spec quest for engineering.

He should give u option to chose Gnomish engineering or Gobling engineering, but he only gives u the Goblin engineering quest.

**Comment by LKArthas** [comment]
Fixed for next update
