### ISSUE TITLE
[Tyce] - Missing bag features

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2560]
**Links:**
![image](https://user-images.githubusercontent.com/85613053/123498913-12d8d680-d5f0-11eb-9158-f410a18e5b63.png)
![image](https://user-images.githubusercontent.com/85613053/123498916-1b311180-d5f0-11eb-8d4d-25e4ea084b1d.png)

**What is happening:**
'Clean Up Bags' doesn't work and 'Assign to Bag:' doesn't affect the sorting of items into bags.

**Comment by ShikoSCS** [comment]
Fixed
