### ISSUE TITLE
Minería - Items - Deposito / Veta de Empirium

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2561]
**Links:**

from WoWHead or our Armory

**What is happening:**
no hay orden en obtener los items para poder obtener los esquemas de rango 1,2 y 3
Al picar Vetas de Empirium obtengo el ítem, que da la misión del rango 2, sin obtener antes el ítem y la misión de rango 1.

**What should happen:**
orden de objetos obtenidos picando Deposito de Empirium
https://www.wowhead.com/item=151860/empyrium-deposit-chunk
este item da una misión (https://www.wowhead.com/quest=48034/empyrium-deposit-chunk), que al entregar al npc Khamir, este nos da el esquema para aprender Deposito de Empirium rango 1

https://www.wowhead.com/item=151861/empyrium-dust
este item da una misión (https://www.wowhead.com/quest=48035/angling-for-a-better-strike), que al entregar al npc Khamir, este nos da el esquema para aprender Deposito de Empirium rango 2

https://www.wowhead.com/item=151862/unusable-empyrium-core
este item da una misión (https://www.wowhead.com/quest=48036/precision-perfected), que al entregar al npc Khamir, este nos da el esquema para aprender Deposito de Empirium rango 3

orden de objetos obtenidos picando Vetas de Empirium
https://www.wowhead.com/item=151863/empyrium-seam-chunk
este item da una misión (https://www.wowhead.com/quest=48037/empyrium-seam-chunk), que al entregar al npc Khamir, este nos da el esquema para aprender Veta de Empirium rango 1

https://www.wowhead.com/item=151864/embedded-empyrium-ore
este item da una misión (https://www.wowhead.com/quest=48038/dont-just-pick-at-it), que al entregar al npc Khamir, este nos da el esquema para aprender Veta de Empirium rango 2

https://www.wowhead.com/item=151865/empyrium-bits
este item da una misión (https://www.wowhead.com/quest=48039/balancing-the-break), que al entregar al npc Khamir, este nos da el esquema para aprender Veta de Empirium rango 3

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
