### ISSUE TITLE
[Tyce] - Class Hall Upgrade 'Shadow Heresy'

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2562]
**Links:**
![image](https://user-images.githubusercontent.com/85613053/123524300-8b8a7200-d686-11eb-9924-d7be5e04f78a.png)
![image](https://user-images.githubusercontent.com/85613053/123524322-a8bf4080-d686-11eb-84f7-15260cfeed55.png)
![image](https://user-images.githubusercontent.com/85613053/123524356-e15f1a00-d686-11eb-8334-0765da83b2af.png)

**What is happening:**
After acquiring Shadow Heresy, Hiring new Zealots still results in a Band of Zealots.

**What should happen:**
After acquiring 'Shadow Heresy' any Zealots that I recruit from then after should be upgraded versions called 'Dark Zealots'.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
