### ISSUE TITLE
Materiales de Sastreria

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2563]
**Links:**

from WoWHead or our Armory

**What is happening:**
los items no se pueden obtener, son necesarios para las misiones de Encantamiento...

https://es.wowhead.com/object=242636/tinte-morado-de-tanithria
al abrir obtenemos:
https://es.wowhead.com/item=127289/tinte-morado-de-tanithria

https://es.wowhead.com/object=242637/tinte-azul-de-tanithria
al abrir obtenemos:
https://es.wowhead.com/item=127290/tinte-azul-de-tanithria

https://es.wowhead.com/object=242638/tinte-rojo-de-tanithria
al abrir obtenemos:
https://es.wowhead.com/item=127291/tinte-rojo-de-tanithria

https://es.wowhead.com/object=242639/tinte-verde-de-tanithria
al abrir obtenemos:
https://es.wowhead.com/item=127292/tinte-verde-de-tanithria

https://es.wowhead.com/object=248093/caja-de-pelaje-de-oso
al abrir obtenemos 5 unidades
https://es.wowhead.com/item=135538/pelaje-de-oso

https://es.wowhead.com/object=242634/hilo-de-tanithria
al abrir obtenemos:
https://es.wowhead.com/item=127287/hilo-de-tanithria

**Comment by Cefiro-Caecias** [comment]
Reparada TODA la cadena de quests de Sastrería de Legion, blizzlike. Disponibles en el siguiente update, y de acuerdo a esta guía de progresión:

https://wowpedia.fandom.com/wiki/Sew_It_Begins
