### ISSUE TITLE
Misiones de Sastreria - 1ra parte

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2564]
**Links:**
from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/quest=38945/esto-no-debería-ser-complicado-no
se autocompleta la mision, deberia poder fabricarlo con los materiales que pide la mision
![image](https://user-images.githubusercontent.com/81131460/123697072-1b185800-d822-11eb-86b7-4524ed2df5d3.png)
link del video de la mision: https://www.youtube.com/watch?v=7ZQ5SAO9iTQ

https://es.wowhead.com/quest=38947/tripa-rúnica
bug visual, la tripa rúnica, no esta como objetivo de misión en el inventario, pero al dropearlo si cuenta como objetivo de la misión,
![image](https://user-images.githubusercontent.com/81131460/123700513-2f5e5400-d826-11eb-8cd1-d4589a5069f7.png)

https://es.wowhead.com/quest=38949/así-que-crees-que-sabes-coser
se autocompleta la mision, deberia poder fabricarlo con los materiales que pide la mision y me da el item ya creado.

https://es.wowhead.com/quest=38953/labores-de-aguja-avanzadas
se autocompleta la mision, deberia poder fabricarlo con los materiales que pide la mision y me da el item ya creado.
link de video de la mision: https://www.youtube.com/watch?v=7ZQ5SAO9iTQ

https://es.wowhead.com/quest=38955/coser-y-cantar
se autocompleta la mision, deberia poder fabricarlo con los materiales que pide la mision y me da el item ya creado.

**Comment by Noahkrr** [comment]
en conclusión, todas las misiones que piden crear un item, se autocompletan, no es posible crear porque los materiales estan bug ,,,

**Comment by Noahkrr** [comment]
https://es.wowhead.com/quest=38960/alinéalos
esta mision no me la dan, la veia en el npc, al tomar (https://es.wowhead.com/quest=38959/olvidados), la mision desaparecio del npc.. complete olvidados y no da la mision (https://es.wowhead.com/quest=38960/alinéalos)

https://es.wowhead.com/quest=38963/la-última-lección
la mision se autocompleta, aparece en el inventario ya creado.
![image](https://user-images.githubusercontent.com/81131460/123731414-aebb4a00-d85d-11eb-9050-f11fdd9aeab0.png)
![image](https://user-images.githubusercontent.com/81131460/123731427-b67aee80-d85d-11eb-9c9a-c2fbedcffc68.png)

**Comment by Noahkrr** [comment]
https://es.wowhead.com/quest=38966/métodos-secretos-de-tejido-de-filoseda
mision se autocompleta, el item aparece creado en mi inventario listo para entregar. deberia poder yo crearlo con las herramientas de sasteria.
![image](https://user-images.githubusercontent.com/81131460/124413083-917ef380-dd15-11eb-8ae8-f23c649cf4a4.png)

**Comment by Cefiro-Caecias** [comment]
Reparada TODA la cadena de quests de Sastrería de Legion, blizzlike. Disponibles en el siguiente update, y de acuerdo a esta guía de progresión:

https://wowpedia.fandom.com/wiki/Sew_It_Begins
