### ISSUE TITLE
[Tyce] - Halls of Valor missing mechanics

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2565]
**What is happening:**
Valarjar Thundercaller: 'Thunderstrike' only is being cast on the tank. It should be randomly targetted at players.
Hymdall: Only 1 Storm Drake strafes across the platform after Horn of Valor cast. 
Hymdall completely disappears after the fight ends and leaves a chest called “Alijo de Hymdall”
Stormforged Sentinel: Casts 'Crackle' at players but nothing happens. Doesn’t cast Charged Pulse.
Valarjar Mystic: Rune of Healing doesn't heal players if they stand in it. Doesn't cast Holy Radiance on mythic.
Mug of Mead: Floats above the tables. Doesn’t consistently stop the enemies from attacking you for the duration. Mug of Mead buff can apply to players and make them unfriendly to you and unhealable. You can also drop combat with mobs by hitting your party with the mug. Makes enemies friendly to you when used on yourself. Can even be used in Fields of the Eternal and will make the hostile mobs in there friendly to you too.
Valarjar Purifer: Should always be attempting to cast. The AoE damage from Cleansing Flames doesn’t work.
Hyrja: Solsten kept doing his mechanics after killing him. Would cast Eye of the Storm before and during the Hyrja fight.
Valarjar Trapper: Bear Trap doesn’t work. 
Valarjar Falconer: Stands there and doesn’t do anything.
Portal to Fields of the Eternal can be taken while in combat and cause to you be stuck in combat.
Storm Drake: Doesn't land and kill the extra stags in front of the portal. (after going to Fields of the Eternal)
Ebonclaw Worg: Strength of the Pack goes away immediately. Doesn’t buff nearby worgs. Doesn’t use Leap for the Throat or Ferocious Bite.
All 4 kings before God-King Skovald can be pulled before killing any of them.
Odyn: doesn't pull you out of the fight with val'kyrs if you die or mess up mechanics. His 'Runic Brand' gives the same Brand every time.
Odyn completely disappears after the fight ends and leaves a chest called “Botin de los dignos”
Stag Party achievement: earnable in normal mode

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
