### ISSUE TITLE
[Tyce] - Black Rook Hold missing mechanics

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2566]
**What is happening:**
Both directions are open at start. Only one gate should be open.
Lady Velandras Ravencrest - shouldn’t have Soul Echoes ability I think?
Amalgam of Souls: Reap Souls spell effect on the ground does not consistently line up with the hitbox of the ability. Knockback doesn’t work on the Restless Souls.
You Used to Scrawl Me In Your Fel Tome: Should only be one page spawned per instance.
Rook Spiderling: Doesn’t cast Internal Rupture (on mythic)
Risen Archer: Tries to run into melee range between/while shooting and then stops shooting once getting into melee. Doesn’t target random players with Arrow Barrage.
Risen Arcanist: Missing its Arcane Minion pet
Illysanna Ravencrest: Dark Rush doesn’t leave Felblazed Ground on the path towards players. It only leaves the ground on the player. When targeted by Eye Beams, the beam should track towards the new player, but isnt consistent. Sometimes it creates a new Eye Beam instead of just re-tracking to the new player.
Boulders: They do nothing. Can just walk through them without getting stunned or knocked back. Missing the roleplaying Wyrmtongue Trickers that are meant to be rolling the boulders down the stairs.
Wyrmtongue Scavenger: Doesn’t throw assorted garbage. Gets indigestion and keeps casting the fire over and over.
Felspite Dominator: Sic Bats! Ability doesn’t cause the Fel Bat Pups to swap to the debuffed player. 
The gauntlet doesn’t work. There is no gauntlet. Mobs don’t keep spawning.
Fel Bat Pups: Gets ‘The Maw Must Feed’ buff for some reason. Doesn’t target the player with ‘Sic Bats!’ debuff.
No NPC to portal us out after killing last boss.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
