### ISSUE TITLE
[Tyce] - Violet Hold missing mechanics

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2567]
**What is happening:**
No demons or portals at the start fighting the guards.
Anub’esset: Impale doesn’t knock players into the air. Spitting Scarabs spawn on top of the boss and run at players instead of shooting from afar. Spitting Scarabs don’t apply DoT. Blistering Beetles aren’t burrowing.
Blood-Princess Thal’ena: Uncontrollable Frenzy only lasts 10 seconds and the player just stands still during the effect.
Millificent Manastorm: Roleplay at the beginning doesn’t happen. Millificent Manastorm can be killed and looted for gear.
Mindflayer Kaahrj: Summons 2 Faceless Tendrils next to the boss. Faceless Tendrils channel Eternal Darkness on the entire group instead of targeting a random player with it. Collapsing Shadows doesn’t draw nearby players towards it.
Lord Malgath: Shadow Bomb debuff doesn’t spread properly. Seeping Shadows from the Shadow Beasts doesn't do damage when standing in it.
Fel Lord Betrug: Execution doesn’t teleport the chosen player, it just roots them where they are. The crystals that need to be broken to let the player out are clickable from far away.
Sael’orn: Venom Spray spell effect goes the opposite direction of where the hitbox is. Only one Phase Spider spawns. (spawned as second boss instead of last boss)

Portal Guardian - Inquisitor: Eyebomb summons untargetable mobs that move around and melee players before eventually exploding.
Portal Guardian - Jailer: Soul Vortex doesn’t pull players towards the cage.
Portal Keeper - Felguard: Throw Axe doesn’t cast or seem to work properly. Fel Axe is an unforgettable mob which moves around and melees players. 
Portal Keeper - Dreadlord: Doesn’t cast Sleeping Dust (on heroic at least)
Infiltrator Assassin: Doesn’t use Fel Poison.
Felstalker Ravener: Often spawns from portal as a corpse and runs to the exit.

Blazing Infernal, Corrosive Felhound, Fel Inciter, Felhound Mage Slayer, Wrathguard Bladeweaver, and Sael’orn’s trash never spawned. (never got Sael’orn as last boss. Never got Shivermaw as a boss.)

Leaving Violet Hold teleports me to 46, 21 in Dalaran, instead of right outside the instance.

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/125175567-615aa900-e18a-11eb-9c5f-61870195dd96.png)
![image](https://user-images.githubusercontent.com/85613053/125175582-759ea600-e18a-11eb-9c5c-fa76260baf2c.png)

If you root a mob before entering combat with it, it will start channeling on the seal from wherever it is rooted.

**Comment by nevarden** [comment]
![WoWScrnShot_071021_143152](https://user-images.githubusercontent.com/85613053/125175832-104bb480-e18c-11eb-95fa-8b4f052c1be1.jpg)

Millificent Manastorm should run away and leave a chest of loot at the stairs instead of dying.

**Comment by nevarden** [comment]
https://www.wowhead.com/item=139445/fel-lexicon

Fel Lexicon drops off Lord Malgath for everyone.

**Comment by nevarden** [comment]
Chaos Talisman drops off Fel Lord Betrug for Guardian loot specialization.

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/125256474-b3e6b300-e2b9-11eb-9d5b-71aba0ac0a05.png)

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
