### ISSUE TITLE
Quest - An Artisan's Mark

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2568]
**Links:**
https://www.wowhead.com/quest=41123/

**What is happening:**
Daelar Swiftmeadow is hostile while wearing the disguise and can't be talked to for the ring. He doesn't drop the ring when he is killed either.

**What should happen:**
Daelar Swiftmeadow should give you the ring. Either voluntarily or by killing him.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
