### ISSUE TITLE
Misiones de sede - Brujo

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2569]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/quest=41767/un-rescate-atrevido
al termino de la mision, no aparece el portal que te lleva Azsuna, no hay manera de salir de Niskara, sin el portal. el portal deberia aparece junto a la jaula de jubeka.
video de la mision: https://www.youtube.com/watch?v=rhaKmVYOM90

https://es.wowhead.com/quest=41798/reclutar-más-tropas
la mision se autocompleta, omitiendo objetivo de la mision, que es ir con el reclutador jared, solicitar tropas, una vez que tenga las tropas lista, la mision se completara.
![image](https://user-images.githubusercontent.com/81131460/124057635-7a769380-d9ed-11eb-9041-945002ad3712.png)

**Comment by Cefiro-Caecias** [comment]
Se harán blizzlike más adelante.
