### ISSUE TITLE
Quest - Kum'isha's Endeavors / One Draenei's Junk... - Blasted Lands

### ISSUE THREAD

**Issue by Spewee** [GuabinaCore/WoWKoi#257]
**Links:**

https://www.wowhead.com/quest=25772/kumishas-endeavors / https://www.wowhead.com/quest=25771/one-draeneis-junk
from WoWHead or our Armory

**What is happening:**
Both of these quests are supposed to be repeatable to turn in for killing rares and mobs in blasted lands. Currently they are not repeatable; once you turn in one item it says "You have already completed this quest"

**What should happen:**

These quests should be repeatable allowing you to turn in multiple fragments and spheres

**Comment by LKArthas** [comment]
Fixed for next update
