### ISSUE TITLE
[Tyce] - Maw of Souls missing mechanics

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2572]
**What is happening:**
First Enslaved Shieldmaiden: After ‘Break Chains’, stays in the cage and doesn’t enter combat. 
Seacursed Slaver: Only does the AoE DoT Barbed Spear. Doesn’t throw Barbed Spear. 
Seacursed Soulkeeper: Brackwater Blast doesn’t do AoE damage after it expires. Doesn’t keep moving forward during Defiant Strike cast.
The Grimewalker: Bile Breath animation tracks the tank but the hitbox is located at the starting point of the cast.
Skeletal Warrior: Doesn’t use Mortal Strike.
Seacursed Mistmender: Uses “Whirlpool of Souls” which is a Seacursed Mistcaller ability. Doesn’t cast Torrent of Souls.
Helarjar Champion: Doesn’t use Ghostly Rage until 40% HP.
Harbaron: Cosmic Scythe projectile is missing some ground effects. Can target the tank with Fragment.
All the mobs between Harbaron and Skjal are already positioned at their destinations instead of running to their positions. 
Helarjar Mistcaller: Doesn’t cast Surging Waters.
Helya: Doesn’t do initial gust/push-back. Piercing Tentacles don’t break through the floor. The intermission during Helya’s Submerged is missing effects. Swirling Water damage can trigger multiple times in a single fall. (i got hit by 4 ticks of Swirling Water at the same time). Taint of the Sea isn’t being cast in phase 2. Torrent spell effect is missing.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
