### ISSUE TITLE
Vault of the Wardens missing mechanics

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2573]
Several bugs and and missing mechanics I've encountered. Edited for clarity and formatting. 

1. **The Warden's Court** 

**Links:**
https://www.wowhead.com/npc=98940/shadow-hunter
https://www.wowhead.com/npc=98926/shadow-hunter
https://www.wowhead.com/spell=194611/metamorphosis

**What is happening:**
Shadow Hunter instantly uses Metamorphosis. No animation or cast.

**What should happen:**
Should be a cast and not just suddenly a different model.

**Links:**
https://www.wowhead.com/npc=98177/glayvianna-soulrender
https://www.wowhead.com/spell=193607/double-strike
https://www.wowhead.com/spell=191767/swoop
https://www.wowhead.com/spell=194990/fel-trap

**What is happening:**
Glayvianna Soulrender doesn’t cast Swoop. 
Double Strike debuff hits herself. 
Fel trap effects are inconsistent / missing.

**What should happen:**
Should cast Swoop.
Shouldn't hurt herself.
Should have all effects.

**Links:**
https://www.wowhead.com/npc=98954/felsworn-myrmidon
https://www.wowhead.com/spell=191735/deafening-screech

**What is happening:**
Felsworn Myrmidon faces wrong direction while casting Deafening Screech.

**What should happen:**
Should face the direction its casting at.

**Links:**
https://www.wowhead.com/npc=99956/fel-infused-fury
https://www.wowhead.com/spell=196787/metamorphosis
https://www.wowhead.com/spell=196799/unleash-fury
https://www.wowhead.com/spell=196796/fel-gaze

**What is happening:**
Fel-Infused Fury doesn't cast Metamorphosis or Unleash Fury. 
Fel Gaze doesn’t knockback or damage consistently. Poor hitbox.

**What should happen:**
Should cast abilities.
Abilities should be able to hit players.

**Links:**
https://www.wowhead.com/npc=95885/tirathon-saltheril
https://www.wowhead.com/spell=191767/swoop
https://www.wowhead.com/spell=191823/furious-blast
https://www.wowhead.com/spell=192504/metamorphosis?buff
https://www.wowhead.com/spell=190836/hatred
https://www.wowhead.com/spell=202740/metamorphosis?buff
https://www.wowhead.com/spell=192014/throw-glaive
https://www.wowhead.com/spell=214625/fel-chain

**What is happening:**
Triathlon Saltheril doesn’t Swoop or Furious Blast.
While in Havoc form, Hatred channel aims at the tank always, and tracks incorrectly.
In Vengeance form, he doesn't throw glaives or use Fel Chain.

**What should happen:**
The boss should cast their spells.

**Links:**
https://www.wowhead.com/npc=98963/blazing-imp
https://www.wowhead.com/spell=194675/fireblast
https://www.wowhead.com/spell=194682/implosion

**What is happening:**
Blazing Imp doesn't target random players with fireblast.
Doesn't cast implosion.

**What should happen:**
Should target random players
Should cast implosion.

**Links:**
https://www.wowhead.com/npc=98533/foul-mother
https://www.wowhead.com/spell=210202/foul-stench
https://www.wowhead.com/spell=194037/mortar
https://www.wowhead.com/spell=194064/a-mothers-love

**What is happening:**
Foul Stench is missing effects, usually invisible. 
Doesn't cast Mortar unless a player is within melee range.
Missing telegraphs/effects on A Mother's Love.

**What should happen:**
Foul Stench should be visible.
Mortar should cast to ranged players.
Should have all effects.

**Links:**
https://www.wowhead.com/npc=96579/frenzied-animus
https://www.wowhead.com/spell=161035/vortex
https://www.wowhead.com/spell=193936/arcane-sentries
https://www.wowhead.com/spell=161056/temporal-anomaly
https://www.wowhead.com/spell=193919/spark
https://www.wowhead.com/spell=193927/mortar

**What is happening:**
Frenzied Animus abilities don't work. 
Temporal Anomaly doesn’t do anything. 
Vortex doesn’t pull players in. 
Arcane Sentries doesn’t do anything. 
Doesn’t cast Mortar or Spark.

**What should happen:**
Should cast their spells and they should work.

2.**Vault of the Wardens**
Mogu’shan Secret-Keeper: melee and run around.
Grimoira: Just melees.
Blade Dancer Illianna: Gift of the Doomsayer doesn’t heal. Doesn’t cast Deafening Shout.
Glazer: standing in the beam doesn’t hurt. Pulse orbs don’t track towards the nearest player. 
Dreadlord Mendacius: Meteor cast doesn’t do anything. Grimguard doesn’t cast Mortal Strike or Charge.
Ash’Golm: Fissure lava pools are off-centered and fade immediately. Volcano’s aren’t spitting fire. Lava Wreath pools fade away after a couple seconds and don’t spread consistently.
Grimhorn the Enslaver: Anguished Souls gets permanently applied to the player. No effects or anything for the spell. Imprisons the tank and applies Torment to them, doesn’t do any AoE damage, doesn’t do any effects, just applies a debuff.

3.**Vault of the Betrayer**
Spirit of Vengeance: Doesn’t cast anything.
Barbed Spiderling: Doesn’t cast Barbed Spit.
Varanasi Broodmother: Casts Razors on its own location instead of at players. Doesn’t cast Pull.
Cordana Felsong: Deepening Shadows doesn’t shrink when the Light is on top of the effect unless the player is holding the Light. Turn Kick doesn’t knock back. Avatar of Vengeance spawns already revealed. When she goes stealth after Shadowstep, she isn’t revealed by the Light being nearby unless the player throws the Light.
All the mobs in the bottom floor can take damage without being seen by the Light.

**Comment by nevarden** [comment]
Inquisitor Tormentorum evades if you run past him towards the door. If you restart combat with him while there, he will stand still while you kill him from range.

**Comment by nevarden** [comment]
The bottom floor is missing all Barbed Web patches.
Cordana Felsong 'Creeping Doom' cast is very buggy. Cordana projectile effect at the start of each wall forming is missing/inconsistent. The second wall takes a very long time to appear. In mythic, there should be more waves that show up, and they should spawn perpendicular to eachother. The announcement for this spell is also in russian or something.

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/125177092-5efe4c00-e196-11eb-8586-bd6101bfcc35.png)

This warning comes when Creeping Doom cast starts. The walls come up the same direction both times with a long delay between them.

**Comment by nevarden** [comment]
Falling off the edge of the final boss room kills you, rather than getting caught and brought back up.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
