### ISSUE TITLE
Cling to Hope

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#2574]
**Links:**
https://www.wowhead.com/quest=40798/cling-to-hope
from WoWHead or our Armory

**What is happening:**
quest is semi-autocomplete, by that i mean, the end of the quest is the same NPC( https://www.wowhead.com/npc=101848/absolon) which gives it.

**What should happen:**
it should lead to https://www.wowhead.com/npc=111318/noressa .

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
