### ISSUE TITLE
Got belt from Relinquished Spaulders

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2575]
**Links:**
https://www.wowhead.com/item=133976/cinidaria-the-symbiote?bonus=3630
https://www.wowhead.com/item=153215/relinquished-spaulders
**What is happening:**
Received 'Cinidaria, the Symbiote' legendary belt from 'Relinquished Spaulders'

**What should happen:**
Receive legendary shoulders.

**Comment by nevarden** [comment]
![WoWScrnShot_070321_153152](https://user-images.githubusercontent.com/85613053/124368286-fa367500-dc1c-11eb-80c6-9e076d935fe9.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed.
