### ISSUE TITLE
Misiones - Monte alto

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2576]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
https://es.wowhead.com/quest=39277/pulverización
mision bug, al usar (https://es.wowhead.com/item=127988/pulverizador-de-insectos) en un drogbar, me cuenta 3 objetivos rociados, lo cual solo deberia ser uno, y se puede volver usar varias veces en el mismo drogbar
![image](https://user-images.githubusercontent.com/81131460/124371484-d6d4ef80-dc47-11eb-8aae-5a5489f93239.png)

https://es.wowhead.com/quest=39387/los-cielos-de-monte-alto
al tomar la mision, deberia poder usar a (https://es.wowhead.com/npc=98715/aviash) para que me lleve a Totem de trueno, lo cual no sucede ya que avisah no se puede seleccionar y puedo montarlo...
vídeo de la misión: https://www.youtube.com/watch?v=mcEiDW7xudM

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=40216/a-hunter-at-heart
se autocompleta la mision. deberia
![imagen_2021-08-09_231419](https://user-images.githubusercontent.com/81131460/128807262-f988ab9d-00ab-4157-b459-b21456fda53d.png)
![image](https://user-images.githubusercontent.com/81131460/128805220-d2962aa2-f149-4e33-97f4-c236b1a686ca.png)

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=42425/going-down-going-up
pide usar el Rappel Point de Oren para descender a las profundidades y recuperar sus posesiones perdidas
el Rappel point (https://www.wowhead.com/npc=116438/orens-rappel-point) no funciona, no aparece la cueva que no deberia bajar del puenta al fondo de la cueva.
video de la mision: https://www.youtube.com/watch?v=9GDSj0mKhOw

https://www.wowhead.com/quest=40339/candle-of-command
esta mision pide sentarse en el trono de ordenar y da órdenes a los kobolds que se acercan.
- Siéntate en el trono de ordenar (https://www.wowhead.com/npc=99724/throne-of-ordering-around)
- Misión de colección dada (https://www.wowhead.com/npc=99745/snazzle-shinyfinder)
- Matar misión dada (https://www.wowhead.com/npc=99746/trytooth-hardchisel)
- Búsqueda de velas dada (https://www.wowhead.com/npc=99747/kindle-candlecrafter)
- Misión minera dada (https://www.wowhead.com/npc=99748/dug-digger)

![image](https://user-images.githubusercontent.com/81131460/129253959-068ed6c2-30f2-4d3c-9b54-23c59ab274dc.png)
el primer credito de la mision funciona, los demas creditos no.
video de la mision: https://www.youtube.com/watch?v=8l6Qus7XngM

**Comment by Cefiro-Caecias** [comment]
1) https://es.wowhead.com/quest=39277/pulverización: reparada.
2) https://es.wowhead.com/quest=39387/los-cielos-de-monte-alto: reparada.
3) https://www.wowhead.com/quest=40216/a-hunter-at-heart: se hará blizzlike más adelante.
4) https://www.wowhead.com/quest=42425/going-down-going-up: puesta temporalmente en modo autocompletable; falla de la spell Rappel (213041).
5) https://www.wowhead.com/quest=40339/candle-of-command: reparada.

Todo disponible en el próximo update.
