### ISSUE TITLE
La batalla de Val'sharah - Asalto de la legión - Val'sharah

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2577]
**Links:**

from WoWHead or our Armory

**Lo que sucede:**
https://es.wowhead.com/quest=44789/sostener-las-murallas
al terminar esta misión, y entregar al NPC (https://es.wowhead.com/npc=118250/comandante-jarod-cantosombrío), no deja que tome la siguiente misión (https://es.wowhead.com/quest=45856/la-batalla-de-valsharah) esta misión desaparece, y es imposible tomarla.,

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
