### ISSUE TITLE
Festering blood plaguing Blasted lands

### ISSUE THREAD

**Issue by Spewee** [GuabinaCore/WoWKoi#258]
**Links:**
https://www.wowhead.com/spell=82914/festering-blood#used-by-npc
from WoWHead or our Armory

**What is happening:**
No idea how, but a level 85 raid mechanic is currently active near the murlocs in blasted land, doing 10k damage every second. Preventing questing there,

https://cdn.discordapp.com/attachments/676175909161533453/691585475554574396/WoWScrnShot_032320_094222.jpg
https://cdn.discordapp.com/attachments/676175909161533453/691585480382480454/WoWScrnShot_032320_094413.jpg

**What should happen:**
Well it shouldnt happen haha :)

**Comment by Spewee** [comment]
After leaving the area and coming back 20-30 mins later it seems to have sorted it out. Still probs shouldnt have happened haha

**Comment by LKArthas** [comment]
Fixed for next update
