### ISSUE TITLE
Misiones de mundo - PVP & Profesiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2580]
**Links:**

from WoWHead or our Armory

**What is happening:**
Misiones de mundo PVP
Tormenheim
https://www.wowhead.com/quest=43599/warden-tower-assault-blackhawks-bulwark
https://www.wowhead.com/quest=43600/warden-tower-assault-whisperwinds-citadel
Monte alto
https://www.wowhead.com/quest=41257/warden-tower-assault-cordanas-apex
https://www.wowhead.com/quest=41420/warden-tower-assault-nightwatchers-perch
Val'sharah
https://www.wowhead.com/quest=42070/warden-tower-assault-starstalkers-point
https://www.wowhead.com/quest=43248/warden-tower-assault-darkfollows-spire

Misiones de mundo de Profesiones
Val'sharah
desuello
https://www.wowhead.com/quest=41333/rugged-wolf-hide
https://www.wowhead.com/quest=41566/felhide
Mineria
https://www.wowhead.com/quest=41486/brimstone-destroyer

**Comment by Noahkrr** [comment]
https://es.wowhead.com/quest=41566/pellejo-vil
no hay npc ..

**Comment by Cefiro-Caecias** [comment]
1) https://www.wowhead.com/quest=41486/brimstone-destroyer: reparada.
2) https://es.wowhead.com/quest=41566/pellejo-vil: reparada.

Disponibles en el próximo update. Sigo mañana con las otras.

**Comment by Cefiro-Caecias** [comment]
Reparadas, zonas reconstruidas. Disponibles en el próximo update.
