### ISSUE TITLE
[Tyce] - Toy - Autographed Hearthstone Card

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2581]
**Links:**
https://www.wowhead.com/item=118427/autographed-hearthstone-card
![image](https://user-images.githubusercontent.com/85613053/124654376-b41b2480-de5b-11eb-89a6-eb1b412a54e1.png)

**What is happening:**
When I use Autographed Hearthstone Card I get a chat message saying "You can't use color on chat! 000" The hands glow like a card is being revealed, but no emote goes out.

**What should happen:**
Should do an emote like Player turns over their card, revealing a hearthstone card.

**Comment by Cefiro-Caecias** [comment]
It seems to work fine.
