### ISSUE TITLE
Toy - Indestructible Bone

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2582]
**Links:**
https://www.wowhead.com/item=127707/indestructible-bone
https://www.wowhead.com/spell=187399/indestructible-bone
https://www.wowhead.com/npc=37865/perky-pug
**What is happening:**
Can use Indestructible Bone on anyone, not just Perky Pug.

**What should happen:**
Should only be able to use it on Perky Pug pet.

![image](https://user-images.githubusercontent.com/85613053/124655346-f5600400-de5c-11eb-8754-a0331459ec30.png)
![image](https://user-images.githubusercontent.com/85613053/124655384-014bc600-de5d-11eb-92a1-3be2a63899cf.png)
![image](https://user-images.githubusercontent.com/85613053/124655452-19234a00-de5d-11eb-8250-5acf675a5b09.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
