### ISSUE TITLE
NPC - Pinchshank (missing weapon)

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2583]
**Links:**
https://www.wowhead.com/npc=107846/pinchshank#screenshots:id=571013
![image](https://user-images.githubusercontent.com/85613053/124656141-0b21f900-de5e-11eb-9a28-6d69edbb0d63.png)

**What is happening:**
Pinchshank has no weapon! 

**What should happen:**
NPC Pinchshank should have a weapon while hostile. (weapon should disappear from the model if a hunter tames him)

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/124656393-5f2cdd80-de5e-11eb-9214-520d65f94f19.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
