### ISSUE TITLE
[Arthas] - Toy - Crab Shank

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2584]
**Links:**
https://www.wowhead.com/item=140314/crab-shank
https://www.wowhead.com/spell=223303/crab-shank
**What is happening:**
Usable on anything. 

**What should happen:**
Should only be able to use this toy on a hunter crab pet.

![image](https://user-images.githubusercontent.com/85613053/124657033-36591800-de5f-11eb-9678-78bc59e3bc5f.png)

**Comment by Cefiro-Caecias** [comment]
@LKArthas, a ver si podés condicionar esta spell para que sólo afecte a las mascotas Cangrejo de los Cazadores. Probé un poco con el Condition 71, pero e sinsuficiente.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
