### ISSUE TITLE
Toy - Never Ending Toy Chest

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2585]
**Links:**
https://www.wowhead.com/item=130209/never-ending-toy-chest

**What is happening:**
Places a non-interactive chest down.

**What should happen:**
Should place a chest down that opens up when clicked on, revealing a slightly smaller chest. This should repeat for several layers until you get some junk loot out of the final chest.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
