### ISSUE TITLE
Quest - Balance to Spare

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2587]
**Links:**
https://www.wowhead.com/quest=42837/balance-to-spare
![image](https://user-images.githubusercontent.com/85613053/124660155-0f044a00-de63-11eb-8c15-7e780b61fe1e.png)

**What is happening:**
Gives 2 pets for completion, and instead of collecting Shadescale Flyeaters, you get completion by killing Tattered Silkwings.

**What should happen:**
Should have to collect the Shadescale Flyeater manawyrms that are in the Twilight Vineyards. Should only get 1 pet for completion.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
