### ISSUE TITLE
Quest - Survival of the Fittest

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2588]
**Links:**
https://www.wowhead.com/quest=41216/survival-of-the-fittest
https://www.wowhead.com/npc=110987/nighteyes

**What is happening:**
Missing follow-up quests after doing Nighteyes questline at Crimson Thicket.

**What should happen:**
If prior quests are completed, he should offer this quest at the menagerie. It should lead into more quests and unlock a World Quest afterwards.

**Comment by Cefiro-Caecias** [comment]
Fixed.
