### ISSUE TITLE
Questline - Lucid Nightmare

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2592]
**Links:**
https://www.wowhead.com/item=151623/lucid-nightmare
https://www.wowhead.com/object=270855/inconspicuous-note
![WoWScrnShot_083017_041135](https://user-images.githubusercontent.com/85613053/124826221-d3848100-df31-11eb-9966-6a3d33f3b4df.jpg)

**What is happening:**
The inconspicuous note to start the questline for Lucid Nightmare is missing.

**What should happen:**
Should be an interactive note there with a haiku about Ulduar, which will provide flag completion for the first step in acquiring Lucid Nightmare.

Used this script to confirm flags being done when getting this mount on retail.
/run local N,t,d={"DAL","ULD","AQ","DEEP","GNOMER","VAL","MAZE","MOUNT"},{47826,47837,47841,47850,47852,47863,47881,47885} for s,k in pairs(N)do d=IsQuestFlaggedCompleted(t[s]) print(k,"=",d and "\124cFF00FF00" or "\124cFFFF0000NOT","DONE")end

**Comment by Cefiro-Caecias** [comment]
Fixed, although the saga to get that mount is not fixed yet.
