### ISSUE TITLE
Questline Step 2 - Riddler's Mind Worm

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2593]
**Links:**
https://www.wowhead.com/item=147835
https://www.wowhead.com/object=209270/page-78

**What is happening:**
'Darkmoon Faire Ring Toss Target' is the name of the object at the moonwell in Duskwood. Clicking on the object gave completion for step 7 of the mount questline, skipping earlier steps.

**What should happen:**
Page 78 should be there instead, and interacting with it should provide completion for step 2 in acquiring the mount. 

/run local N,t,d={"1","2","3","4","5","6","7","MOUNT"},{45470,47207,47208,47209,47210,47211,47212,47213} for s,k in pairs(N)do d=IsQuestFlaggedCompleted(t[s]) print(k,"=",d and "\124cFF00FF00" or "\124cFFFF0000NOT","DONE")end

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the enxt update.
