### ISSUE TITLE
Guarida de Neltharion - jefes & adds

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2595]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/npc=91003/rokmora
tiene como nombre entidad desconocida...
![image](https://user-images.githubusercontent.com/81131460/124861610-875d2f00-df79-11eb-81a7-3e4983613c6c.png)
https://es.wowhead.com/npc=102295/dominador-caparabrasa
![image](https://user-images.githubusercontent.com/81131460/124863659-1d468900-df7d-11eb-9a22-f9d441593146.png)
https://es.wowhead.com/npc=103271/kraxa
este npc aparece sin nombre, al matarlo no cuenta como objetivo de mision de mundo mazmorra
![image](https://user-images.githubusercontent.com/81131460/124862718-80cfb700-df7b-11eb-9792-3673ce3bdf91.png)
https://es.wowhead.com/npc=91007/dargrul
tiene como nombre identidad desconocida.. 
![image](https://user-images.githubusercontent.com/81131460/124863804-64347e80-df7d-11eb-8762-68c63e47f73c.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Reparado. No olvides borrar Cache para ver todo bien nuevamente.
