### ISSUE TITLE
Mascotas de Cazador - Legion

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2597]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/npc=121625/kveldulfnir
npc aparece como aliado, deberia ser neutral o hostil.
![WoWScrnShot_070421_170459](https://user-images.githubusercontent.com/81131460/125025850-05d4d200-e049-11eb-8244-c09c59ca9c96.jpg)

https://es.wowhead.com/npc=121623/varoudnir
npc aparece como aliado, deberia ser neutral o hostil.
![WoWScrnShot_070421_171408](https://user-images.githubusercontent.com/81131460/125025871-11c09400-e049-11eb-8848-79a8dec4c96f.jpg)

**Comment by Cefiro-Caecias** [comment]
Reparadas. Disponibles en el próximo update.
