### ISSUE TITLE
[Core] - Warlock Skill : Call Dreadstalkers Issue

### ISSUE THREAD

**Issue by cglim94** [GuabinaCore/WoWKoi#260]
![WoWScrnShot_032420_005249](https://user-images.githubusercontent.com/62562336/77341712-184ecd80-6d6a-11ea-90b7-3c3b9eb8fb22.jpg)
Dreadstalkers would not attack. They'll just stay idle during fight. Please help.

**Comment by login6710** [comment]
Fixed
