### ISSUE TITLE
Sastreria - Mision - ¡Inspírame! 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2600]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/quest=38975/inspírame
la misión funciona bien y se puede completar, el unico problema es al crear los items que pide la mision, el npc genera dialogos en ruso. al hacer click en cada uno de los dialogos, los objetivos de la mision se completan, completando la mision
Dato:  Los items que pide la mision crear, se crean junto al npc que otorga la misión.
![WoWScrnShot_070521_232030](https://user-images.githubusercontent.com/81131460/125171311-374cbb00-e179-11eb-832a-b86bb2924626.jpg)

**Comment by LKArthas** [comment]
Fixed
