### ISSUE TITLE
Legion Invasion World Quest - Feast of the Hounds

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2602]
**Links:**
![image](https://user-images.githubusercontent.com/85613053/125174272-53ecf100-e181-11eb-86d0-0202a2eafb95.png)
https://www.wowhead.com/quest=45786/feast-of-the-hounds
**What is happening:**
Not getting credit towards quest by killing the mobs.

**What should happen:**
Should be able to get credit from killing the listed mobs in the quest.

**Comment by nevarden** [comment]
https://www.wowhead.com/item=151152/star-etched-ring
The NPCs also drop Star-Etched Ring and other pick-pocketing items for non-rogues.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
