### ISSUE TITLE
Legion Invasion World Quest - Crushing the Legion

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2604]
**Links:**
https://www.wowhead.com/quest=46179
https://www.wowhead.com/npc=116614
https://www.wowhead.com/npc=118985
**What is happening:**
Fel Corruptor dying/being smashed doesn't count towards the quest.
The fel hammer is invisible before being picked up.

**What should happen:**
Fel Corruptor should count towards quest completion when smashed. The fel hammer should be visible before being picked up.

**Comment by Cefiro-Caecias** [comment]
Fixed. Zone reworked. Available in the next update.
