### ISSUE TITLE
Arcway missing mechanics

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2607]
**Links:**
https://www.wowhead.com/npc=98426/unstable-ooze
https://www.wowhead.com/npc=98728/acidic-bile
https://www.wowhead.com/npc=105651/dreadborne-seer
https://www.wowhead.com/npc=106757/eye-of-the-beast
https://www.wowhead.com/spell=211037/celerity-zone
https://www.wowhead.com/npc=106059/warp-shade
https://www.wowhead.com/spell=226206/arcane-reconstitution
https://www.wowhead.com/npc=106546/astral-spark
https://www.wowhead.com/spell=196804/nether-link
https://www.wowhead.com/spell=211543/devour
https://www.wowhead.com/npc=98759/vicious-manafang
https://www.wowhead.com/spell=211757/portal-argus
https://www.wowhead.com/spell=226285/demonic-ascension
https://www.wowhead.com/npc=105706/priestess-of-misery
https://www.wowhead.com/spell=211917/felstorm
https://www.wowhead.com/spell=212030/shadow-slash
https://www.wowhead.com/spell=220443/wake-of-shadows
https://www.wowhead.com/spell=203139/force-nova
https://www.wowhead.com/spell=203957/time-lock

**What is happening:**
Unstable Amalgamation: Unstable Ooze are not casting Ooze Explosion.
Acidic Bile: Consume leaps to a player AFTER the cast finishes rather than leaping at the start of the cast. Corrosive isn’t applying from melees.
Dreadborne Seer: When Eye of the Beast cast Optic Blast the spell effect doesn’t cover where the hitbox is. They also move around and cast it while chasing after players..
Forgotten Spirit: Casts Torment rarely rather than chain-casting it.
Celerity Zone: Doesn’t affect players. Missing visually.
Warp Shade: Doesn’t cast Arcane Reconstitution.
Arcane Anomaly: Doesn’t cast Arcane Reconstitution. Summons Astral Spark and the Spark just wanders around. When casting Arcane Slicer, faces the wrong direction, and only casts it towards the tank.
Mana Wyrm: Doesn’t cast Nether Spike at random targets.
Ivanyr: Nether Link ability doesn’t work.
Nightborne Reclaimer: Doesn’t cast Celerity Zone. 
Corstilax: Players can fall through the floor after Quarantine gets broken. Tank can be targeted by everything. 
Vicious Manafang: Doesn’t cast Devour.
Eredar Chaosbringer: Doesn’t cast Portal: Argus. Doesn’t cast Demonic Ascension. Doesn’t chase after you when you break line of sight.
Priestess of Misery: Felstorm ability doesn’t work and she interrupts herself to move if the tank isn’t in melee range.
General Xakal: Shadow Slash and Wake of Shadows are out of sync and go different directions.
Advisor Vandros: Force Bomb doesn’t explode afterwards, it just fades away.
Timeless Wraith: Doesn’t immediately cast Time Lock.

Portable Manacracker drops for Guardian loot specialization.

**Comment by Cefiro-Caecias** [comment]
That area will be rebuilt later. Patience.
