### ISSUE TITLE
[Wotlk][Zone][Alliance side] Borean Tundra - complete zone report

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2608]
**Links**:
https://www.wowhead.com/borean-tundra

---

1. 
- [ ] NPC - [Scourged Flamespitter](https://www.wowhead.com/npc=25582/scourged-flamespitter) :  
     - sometimes gets stuck in the air causing constant "combat bug"
     - they get aggro even if you are on the ground, away from them

 ---
2. 
- [ ] NPC - If you dismount from [Dusk](https://www.wowhead.com/npc=26191/dusk) another [Dusk](https://www.wowhead.com/npc=28182/dusk#comments) with different ID is created. Griefing alert.

 ---
3. 
 - [x] NPC - [Drowned Guardian](https://www.wowhead.com/npc=26224/drowned-guardian) deals too much melee dmg. 5k hits compared to average 200-300. Impossible to beat for character with lvl 60-80.
   
 ---
4. 
- [ ] NPC - [Counselor Talbot](https://www.wowhead.com/npc=25301/counselor-talbot#abilities) missing his abilities after transformation.

 ---
5. 
- [ ] Quest - [Re-cursive](https://www.wowhead.com/quest=11712/re-cursive)
     - [Re-Cursive Transmatter Injection](https://www.wowhead.com/item=34973/re-cursive-transmatter-injection) can be used multiple times on [Fizzcrank Mechagnome](https://www.wowhead.com/item=34973/re-cursive-transmatter-injection) for additional credits.

 ---
6. 
 - [ ] Quest - [Lefty Loosey, Righty Tighty](https://www.wowhead.com/quest=11788/lefty-loosey-righty-tighty)
     - Objects [North Point Station Valve](https://www.wowhead.com/object=187985/north-point-station-valve), [Mid Point Station Valve](https://www.wowhead.com/object=187986/mid-point-station-valve), [South Point Station Valve](https://www.wowhead.com/object=187987/south-point-station-valve) and [West Point Station Valve](https://www.wowhead.com/object=187984/west-point-station-valve) can be clicked multipletimes to spawn infinite amount of quest NPC. Griefieng alert.
---
7. 
 - [ ] Quest - [Hah... You're Not So Big Now!](https://www.wowhead.com/quest=11653/hah-youre-not-so-big-now)
     - [Crafty's Ultra-Advanced Proto-Typical Shortening Blaster](https://www.wowhead.com/item=34812/craftys-ultra-advanced-proto-typical-shortening-blaster) is missing it's debuff animation on both player and monster. 
---
8. 
 - [ ] Quest - [Lupus Pupus](https://www.wowhead.com/quest=11728/lupus-pupus)
     - [Wolf Bait](https://www.wowhead.com/item=35121/wolf-bait) doesn't have any effect on [Oil-stained Wolf](https://www.wowhead.com/npc=25791/oil-stained-wolf). It should make [Oil-stained Wolf](https://www.wowhead.com/npc=25791/oil-stained-wolf) neutral and make them disappear after a second.
---
9. 
 - [ ] NPC - [Wooly Mammoth Bull](https://www.wowhead.com/npc=25743/wooly-mammoth-bull#abilities)
     - [Mammoth Trample](https://www.wowhead.com/spell=46317/mammoth-trample) deals too much damage (as for a lvl 70 character)
     - [Mammoth Charge](https://www.wowhead.com/spell=46315/mammoth-charge) deals too much damage.
     
![image](https://user-images.githubusercontent.com/63166930/125402021-33f14380-e3b4-11eb-88b7-583ec19577cb.png)
![image](https://user-images.githubusercontent.com/63166930/125402476-bda11100-e3b4-11eb-8ad3-3e577c62bb33.png)
---
9. 
 - [ ] Quest - [Leaning to Communicate](https://www.wowhead.com/quest=11571/learning-to-communicate)
     - [The King's Empty Conch](https://www.wowhead.com/item=34598/the-kings-empty-conch) can be used without any target to complete the quest.
     - [King Mrgl-Mrgl <D.E.H.T.A.>](https://www.wowhead.com/npc=25197/king-mrgl-mrgl) doesn't provide [Water Breathing](https://www.wowhead.com/spell=45328/water-breathing)
---
10. 
 - [ ] NPC - [Glimmer Bay Orca](https://www.wowhead.com/npc=25204/glimmer-bay-orca)
     - In fact, its not a bug, but it seems there is too few Orcas around the quest area. I covered the whole area and got about 5/8 quest items (taking under consideration the quest item is not 100% drop chance) 
---
11. 
 - [ ] Quest - [Oh Noes, the Tadpoles!](https://www.wowhead.com/quest=11560/oh-noes-the-tadpoles#comments)
     - Interacting with [Cage](https://www.wowhead.com/object=176306/cage) should grant 3 credits towards [Winterfin Tadpole rescued](https://www.wowhead.com/npc=25201/winterfin-tadpole-rescued), instead of 1.
---
12. 
 - [ ] NPC - [Librarian Garren](https://www.wowhead.com/npc=25291/librarian-garren#abilities;mode:normal)
     - His dialogue option doesn't cast [Water Breathing](https://www.wowhead.com/spell=52909/water-breathing)
---
13. 
 - [ ] Quest - [Prison Break](https://www.wowhead.com/quest=11587/prison-break)
     - [Arcane Prison](https://www.wowhead.com/object=187561/arcane-prison) can be opened without [Beryl Prison Key](https://www.wowhead.com/item=34688/beryl-prison-key)
---
14. 
 - [ ] Quest - [Abduction](https://www.wowhead.com/quest=11590/abduction)
     - After using the quest item, [Captured Beryl Sorcerer](https://www.wowhead.com/npc=25474/captured-beryl-sorcerer) is hostile. He should be friendly and follow player on a chain.
---
15. 
 - [ ] Quest -[A Race Against Time](https://www.wowhead.com/quest=11671/a-race-against-time)
     - [Inquisitor Sarland](https://www.wowhead.com/npc=25584/inquisitor-salrand) can be killed without using [Beryl Shield Detonator](https://www.wowhead.com/quest=11671/a-race-against-time) on her.
---
16. 
 - [ ] Quest - [Rescuing Evanor](https://www.wowhead.com/quest=11681/rescuing-evanor)
     - Event missing. 
---
17. 
 - [ ] Quest - [Reading the Meters](https://www.wowhead.com/quest=11900/reading-the-meters)
     - [Nexus Geological Reading](https://www.wowhead.com/object=188100/nexus-geological-reading) and [Northern Coldarra Reading](https://www.wowhead.com/object=188102/northern-coldarra-reading) are in wrong places. Nexus is placed next to Southern and Northern is placed next to Western. 
---
18. 
 - [ ] Quest - [Hatching a Plan](https://www.wowhead.com/quest=11936/hatching-a-plan)
     - [Coldarra Wyrmkin](https://www.wowhead.com/npc=25728/coldarra-wyrmkin)s don't drop [Frozen Axe](https://www.wowhead.com/item=35586/frozen-axe)
---
19. 
 - [ ] Quest - [Help Those That Cannot Help Themselves](https://www.wowhead.com/quest=11876/help-those-that-cannot-help-themselves)
     - [D.E.H.T.A. Trap Smasher](https://www.wowhead.com/item=35228/d-e-h-t-a-trap-smasher)  doesn't have cooldown. Can be clicked multiple times for additional credits
---
20. 
 - [ ] Quest - [Kaw the Mammoth Destroyer](https://www.wowhead.com/quest=11879/kaw-the-mammoth-destroyer)
     - Kaw is just standing on the platform. He doesn't do anything.
     - Kaw's animation and [Kaw's War Halberd](https://www.wowhead.com/object=188066/kaws-war-halberd) missing.
---
21. 
 - [ ] Quest - [Drake Hunt](https://www.wowhead.com/quest=11919/drake-hunt)
     - [Raelorasz's Spear](https://www.wowhead.com/item=35506/raeloraszs-spear) doesn't subdue the drake. The drake doesn't become friendly. The drake disappears after being brought close to the quest giver.
---
22. 
 - [ ] Quest - [The Cell](https://www.wowhead.com/quest=11943/the-cell)
     - [General Cerulean](https://www.wowhead.com/npc=25716/general-cerulean) doesn't drop [Prison Casing](https://www.wowhead.com/item=35668/prison-casing)
---
23. 
 - [ ] Quest - [Bait and Switch](https://www.wowhead.com/quest=11951/bait-and-switch)
     - Object [Crystalized Mana](https://www.wowhead.com/object=188140/crystallized-mana) is missing.
---
24. 
 - [ ] Quest - [Saragosa's End](https://www.wowhead.com/quest=11957/saragosas-end)
     - Event doesn't work. Saragosa flys down to the platform and disappears.
     -  [Arcane Power Focus](https://www.wowhead.com/item=35690/arcane-power-focus) can be clicked multiple times to trigger additional events. 
---
25. 
 - [ ] Quest - [Springing the Trap](https://www.wowhead.com/quest=11969/springing-the-trap)
     - Object Signal Fire(I wasn;t able to find the proper ID) is missing. Can't trigger event with [Raelorasz' Spark](https://www.wowhead.com/item=44950/raelorasz-spark)
     - After using the quest item, there is an event going. I can't provide info if it works or not because of the missing signal fire.

**Comment by NightwindOI** [comment]
https://github.com/GuabinaCore/WoWKoi/issues/2599

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt much later. Much patience :P
