### ISSUE TITLE
Quest: Take it up with Tony , Id: 14052

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#261]
**Links:**
https://www.wowhead.com/quest=14052/take-it-up-with-tony
https://imgur.com/a/IdPSI3i
from WoWHead or our Armory

**What is happening:**
Gazlowe also gives the quest along with the proper quest starter Wharfmaster Dizzywig.

**What should happen:**
Only Wharfmaster Dizzywig should give the quest.

**Comment by LKArthas** [comment]
Fixed for next update
