### ISSUE TITLE
Return to Karazhan attunement

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2610]
**Links:**
https://www.wowhead.com/storyline/return-to-karazhan-294

**What is happening:**
Able to queue and enter Return to Karazhan without doing attunement questline.

**What should happen:**
Shouldn't be able to enter without first doing the questline in front of Karazhan.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. The line of progression indicated in this article has been followed: https://wowpedia.fandom.com/wiki/Edict_of_the_God-King
