### ISSUE TITLE
[DUNGEON][LEGION] Lower Karazhan missing mechanics

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2611]
**Links:**
https://www.wowhead.com/npc=113971/maiden-of-virtue
https://www.wowhead.com/spell=227789/sacred-ground
![image](https://user-images.githubusercontent.com/85613053/125206507-e904ee00-e244-11eb-891c-ed2c52a7b3c0.png)
![WoWScrnShot_071121_123722](https://user-images.githubusercontent.com/85613053/125206536-13ef4200-e245-11eb-9088-6ac3e8b116ec.jpg)
**What is happening:**
Not applying damage in the expanding zone after the AoE grows.

**What should happen:**
Get the DoT for standing in any part of the AoE.

https://www.wowhead.com/spell=227908/ghost-trap
**What is happening:**
Doesn't go away after using it once. Can be used for the whole 30 minute duration repeatedly.

**What should happen:**
Should only be able to use Ghost Trap once.

https://www.wowhead.com/spell=227365/spectral-charge
https://www.wowhead.com/npc=114264/midnight
**What is happening:**
Doesn't cast spectral charge.

**What should happen:**
Should cast spectral charge.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
