### ISSUE TITLE
[DUNGEON][LEGION] Upper Karazhan missing mechanics

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2612]
**Links:**
https://www.wowhead.com/npc=114350/shade-of-medivh
https://www.wowhead.com/spell=227779/ceaseless-winter
![WoWScrnShot_071121_132405](https://user-images.githubusercontent.com/85613053/125207780-6f243300-e24b-11eb-80bd-e32eec9bf8e5.jpg)
**What is happening:**
Ceaseless winter is missing visual effects on the ground.

If inside a frostbite block when Ceaseless Winter casts, you won't have to move when you break out. The Ceaseless Winter won't affect you.
**What should happen:**
The ground should be covered in ice when ceaseless winter casts.

**Links:**
https://www.wowhead.com/item=143664/rodent-of-usual-size
https://www.wowhead.com/achievement=11431/the-rat-pack
**What is happening:**
Attempting to use Rodent of Usual Size doesn't work. Results in being told "You can't do that yet"
Able to attempt looting Medivh's Chest (Mana Devourer loot) while small. The chest is missing while large.
**What should happen:**
Be able to mount Rodent of Usual Size while small. Used to earn The Rat Pack achievement.
Should be able to loot it after killing boss while big.

**Links:**
https://www.wowhead.com/npc=114790/vizaduum-the-watcher
https://www.wowhead.com/spell=229151/disintegrate
https://www.wowhead.com/spell=229906/soul-harvest
**What is happening:**
Viz'aduum Disintegrate effect/telegraph doesn't line up with the hitbox of the ability.
Phase 2, disintegrate only casts towards the middle. The soul harvesters on the sides of the ship aren't dealing damage.
**What should happen:**
Disintegrate telegraph should be consistent with the hitbox of the ability.
In phase 2, disintegrate should cast either left, middle, or right. The soul harvesters on the sides of the ship should deal damage to nearby players.

**Comment by nevarden** [comment]
![WoWScrnShot_071121_141043](https://user-images.githubusercontent.com/85613053/125707433-8ee5b7b1-5416-4ec1-bfab-f55f84a4dad0.jpg)

Pacified for too long after landing on ship at phase 2 and phase 3 of Viz'aduum.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
