### ISSUE TITLE
 Objeto/Misión - Abalorio maltrecho

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2613]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/item=146408/abalorio-maltrecho
este ítem no esta en el juego, este ítem inicia una misión (https://es.wowhead.com/quest=46268/el-hallazgo-de-un-recuerdo)

**Comment by Cefiro-Caecias** [comment]
Sí, sí está en el juego. Pídele a un GM que te lleve hasta donde se encuentra el objeto que inicia la quest, que se encuentra debajo del agua, utilizando el siguiente comando de teleportación:

.go object 150288

O Puedes ir a buscarlo donde marca esta foto: https://es.wowhead.com/object=268478/abalorio-maltrecho#map

**Comment by Noahkrr** [comment]
ya lo encontre pero las coordenadas 49.41 83.56 son incorrectas, deberia estar en las coordenadas 53.5 80.5 
![image](https://user-images.githubusercontent.com/81131460/132960844-388cce65-28e3-424c-a13d-3958879ab11e.png)
![image](https://user-images.githubusercontent.com/81131460/132960907-306592bc-fd45-4487-b1e8-9ec758172a4d.png)
