### ISSUE TITLE
[DUNGEON][LEGION] Court of Stars missing mechanics

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2614]
**Links:**
https://www.wowhead.com/spell=210261/sound-alarm
https://www.wowhead.com/npc=104251/duskwatch-sentry
https://www.wowhead.com/npc=104245/arcane-beacon
**What is happening:**
Sentry doesn't run to the arcane beacon to sound alarm.

**What should happen:**
Sentry should run to the beacon and channel their cast.

**Links:**
https://www.wowhead.com/spell=225100/charging-station
https://www.wowhead.com/spell=225101/power-charge
https://www.wowhead.com/npc=104270/guardian-construct

**What is happening:**
Guardian Construct doesn’t cast Charging Station.
**What should happen:**
Should cast Charging Station and buff nearby mobs with Power Charge.

**Links:**
https://www.wowhead.com/spell=209027/quelling-strike
https://www.wowhead.com/npc=104918/vigilant-duskwatch
**What is happening:**
Often faces the wrong way while casting Quelling Strike
**What should happen:**
Should face the correct way while casting.

**Links:**
https://www.wowhead.com/spell=209404/seal-magic
https://www.wowhead.com/npc=104247/duskwatch-arcanist

**What is happening:**
Duskwatch Arcanist is only casting Nightfall Orb.

**What should happen:**
Duskwatch Arcanist should cast Seal Magic.

**Links:**
https://www.wowhead.com/item=133806/arcanic-compressor
https://www.wowhead.com/npc=104215/patrol-captain-gerdo

**What is happening:**
Only able to poison the Flask of the Solemn Night as rogue.
Arcanic Compressor drops for non-engineers.
**What should happen:**
Alchemists and rogues should be able to poison the Flask so when the boss drinks it, they die.
Arcanic Compressor should only drop for engineers on the quest.

**Links:**
https://www.wowhead.com/npc=105715/watchful-inquisitor
https://www.wowhead.com/npc=106584/watchful-oculus
https://www.wowhead.com/spell=212784/eye-storm
**What is happening:**
Watchful oculus auto attack randomly.
Watchful Inquisitor isn’t casting Eye Storm
**What should happen:**
Watchful oculus should attack with Searing Glare.
Watchful Inquisitor should cast Eye Storm.

**Links:**
https://www.wowhead.com/npc=104295/blazing-imp
https://www.wowhead.com/spell=211401/drifting-embers
**What is happening:**
Blazing imp interrupts itself as soon as it casts drifting embers.

**What should happen:**
It should continue the cast.

**Links:**
https://www.wowhead.com/spell=211470/bewitch
https://www.wowhead.com/npc=104300/shadow-mistress
**What is happening:**
Casts bewitch at their main target, the tank.

**What should happen:**
Should cast it at random players.

**Links:**
https://www.wowhead.com/npc=104277/legion-hound
https://www.wowhead.com/spell=211477/ferocity
**What is happening:**
Legion Hound isn’t casting Ferocity.

**What should happen:**
Legion Hound should cast Ferocity.

**Links:**
https://www.wowhead.com/npc=104278/felbound-enforcer

**What is happening:**
Able to run out Felbound Enforcers to pull emissaries.

**What should happen:**
Felbound Enforcer should respawn on the opposite side of the court if there aren’t any currently alive.

**Links:**
https://www.wowhead.com/npc=104274/baalgar-the-watchful
https://www.wowhead.com/spell=207980/disintegration-beam
**What is happening:**
Casts Disintegration Beam only at the main target, the tank.
Disintegration Beam is fully rooting after hitting 2 stacks.
**What should happen:**
Should cast on random players.
The beam should only reduce movespeed 75%.

**Links:**
https://www.wowhead.com/npc=107486/chatty-rumormonger

**What is happening:**
The only clue they give is that the spy is female, even if the spy isn’t female.

**What should happen:**
They should have many other clues to provide.

**What should happen:**
They should have many other clues to provide.
**Links:**
https://www.wowhead.com/npc=108151/gerenth-the-vile
https://www.wowhead.com/spell=214690/cripple
https://www.wowhead.com/spell=214688/carrion-swarm
**What is happening:**
Gerenth stays as a Suspicious Noble and just changes into a Dreadlord.
Casts Cripple only at the main target, the tank.
Often faces the wrong way while casting Carrion Swarm.

**What should happen:**
Should turn into Gerenth the Vile and do a mini-knockback on transformation.
Should cast on random players.
Should face the correct direction.

**Links:**
https://www.wowhead.com/spell=215428/overloaded

**What is happening:**
Using Arcane Power Conduit turns Guardian Constructs friendly and asleep.

**What should happen:**
Using Arcane Power Conduit should overload Guardian Constructs and turn them neutral.

**Comment by nevarden** [comment]
**Links:**
https://wow.zamimg.com/uploads/guide/images/10612.jpg
https://www.wowhead.com/spell=188501/spectral-sight
**What is happening:**
Spectral sight isn’t able to determine which suspicious noble is the spy.

**What should happen:**
After speaking to all 5 Chatty Rumormongers, Spectral Sight should reveal the spy.

**Comment by nevarden** [comment]
**Links:**
https://www.wowhead.com/npc=104218/advisor-melandrus
![WoWScrnShot_071321_163319](https://user-images.githubusercontent.com/85613053/125704866-e295fb76-f307-4975-9dc8-462f59e2a444.jpg)


**What is happening:**
Able to pull outside the room and keep fighting.
Can fight him while standing on an invisible platform around the center tree. 
**What should happen:**
Should reset if pulled outside the room.

**Comment by nevarden** [comment]
Links:
https://www.wowhead.com/item=128866/truthguard
https://wow.zamimg.com/uploads/guide/images/10195.jpg
What is happening:
Truthguard isn’t able to determine which suspicious noble is the spy.

What should happen:
Just being near the hiding demon should make the shield light up.

**Comment by nevarden** [comment]
Fel Orb - Paladins can use
Infernal Tome - Demon Hunters can use

**Comment by nevarden** [comment]
https://www.wowhead.com/spell=207815/flask-of-the-solemn-night
https://www.wowhead.com/npc=104215/patrol-captain-gerdo

What is happening:
If the group dies after Patrol Captain Gerdo drinks the flask, the boss will keep the buff into the next fight.
What should happen:
Boss should reset and lose the buff.

**Comment by nevarden** [comment]
https://www.wowhead.com/npc=105215/discarded-junk
![WoWScrnShot_071921_160629](https://user-images.githubusercontent.com/85613053/126396496-22cf0213-0804-473b-9082-8e25b4e28544.jpg)
What is happening:
Felbound Enforcer nearby yells once the discarded junk is interacted with. Felbound Enforcer becomes unkillable and just stands still.
Discarded Junk respawns after a few minutes and can be used again

What should happen:
Should not use a Felbound Enforcer.
Discarded Junk shouldn't respawn.

**Comment by nevarden** [comment]
Links:
https://www.wowhead.com/npc=108151/gerenth-the-vile
https://www.wowhead.com/achievement=10611/dropping-some-eaves
![WoWScrnShot_071321_151214](https://user-images.githubusercontent.com/85613053/126398209-73229137-3bb8-4e7b-be2a-f6089cd39992.jpg)

What is happening:
There is no key near Dreadlord after it dies.
Instantly earn the achievement after killing the mob.
Door to Elisande and Melandrus is already open.

What should happen:
There should be a key that needs to be picked up by any player before the door can be opened by any player.
Achievement should be earned by listening in to Elisande and Melandrus before opening the door.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
