### ISSUE TITLE
Mision de mundo - Sastrería

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2616]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/quest=41645/pedido-cubrehombros-de-filoseda
esta mision de mundo, me pide crear (https://es.wowhead.com/item=126993/cincho-de-filoseda?bonus=3408), lo cual esta mal.
![Captura](https://user-images.githubusercontent.com/81131460/125354333-4b371f00-e329-11eb-9f60-db28af9f9a5c.PNG)

**What should happen:**
deberia pedirme crear este item (https://es.wowhead.com/item=126992/cubrehombros-de-filoseda?bonus=3408)

**Comment by Cefiro-Caecias** [comment]
Reparada. Disponible en el próximo update. No olvides borrar Cache.
