### ISSUE TITLE
NPC  - Marinero de la represalia de la reina /Marinera de la represalia de la reina

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2617]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/quest=42220/marineros-naufragados
mision no se puede completar por que los npc estan bugeado, no se les puede atacar (https://es.wowhead.com/npc=89289/marinero-de-la-represalia-de-la-reina)  (https://es.wowhead.com/npc=89290/marinera-de-la-represalia-de-la-reina)
es imposible completar la mision, si los objetivos de la mision estan bug
![image](https://user-images.githubusercontent.com/81131460/125551653-fef08344-64df-4beb-83f6-773ef6ebc14c.png)

**Comment by Noahkrr** [comment]
![image](https://user-images.githubusercontent.com/81131460/125555247-17be4749-1d8a-4d19-b216-8fcbe58241a7.png)
ni siquiera puedo hacer la misión de mundo activa, ya que no matar a los npc

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
