### ISSUE TITLE
Hacia la grieta - Suramar

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2618]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/quest=42227/hacia-la-grieta
Al comenzar la mision, tengo que seguir a (https://es.wowhead.com/npc=107126/caminavalles-farodin), una vez llegando a la Grieta, se completa el primer credito seguir a caminavalles Farodin), el segundo credito (entrar en los Tuneles de Falanar) no se completa, porque el npc no salta hacia la grieta, solo se queda en el filo y desaparece segundos después

**What should happen:**
el primer credito se completa al seguir a Caminavalles Farodin.
el segundo credito se completa: cuando Caminavalles Farodin  lanzar unos dialogos y salta hacia la grieta y mi PJ debe saltar y llegar a los tuneles de Falanar.

Link  de video de la mision: https://www.youtube.com/watch?v=O4gtomhTYJY

**Comment by Kirrkoi** [comment]
ya se puede completar, tiene un dialogo en ruso, el npc Caminavelles Farodin cuando esta en la orilla del
