### ISSUE TITLE
Formulas de encantamiento - NO deberia...

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2619]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/item=141919/fórmula-encantar-collar-marca-de-la-sacerdotisa-anciana
no debería poder usar esa formula sin antes haber aprendido el rango 2
![image](https://user-images.githubusercontent.com/81131460/125559872-d1802477-b1d8-4295-afcc-15af20d84530.png)

mismo problema:
https://es.wowhead.com/item=128610/fórmula-encantar-collar-marca-de-la-zarpa
https://es.wowhead.com/item=141918/fórmula-encantar-collar-marca-del-soldado-adiestrado
no deberia poder permitirme aprender antes del rango 2.
![image](https://user-images.githubusercontent.com/81131460/125560026-172b6d5d-1500-4fb8-b8a4-916fb71b8c0b.png)
![image](https://user-images.githubusercontent.com/81131460/125560052-ec3478a4-0439-4408-8d9e-f484ca1eb193.png)

**Comment by Noahkrr** [comment]
al usar la formula de: Marca de zarpa de rango 3, aprendi el rango 2 y el rango 3. sin necesidad de la formula del rango 2, se omitio la restriccion (Requiere rango anterior)
![image](https://user-images.githubusercontent.com/81131460/125561340-97e6c0cc-5b1a-474d-bcc0-0d7637d4aa8f.png)

**Comment by Noahkrr** [comment]
este problema sucede con las formulas de rango 3 de Encantamiento que son los siguientes:
https://es.wowhead.com/item=128610/fórmula-encantar-collar-marca-de-la-zarpa
https://es.wowhead.com/item=141918/fórmula-encantar-collar-marca-del-soldado-adiestrado
https://es.wowhead.com/item=141919/fórmula-encantar-collar-marca-de-la-sacerdotisa-anciana
supongo que se debería probar todas las formulas de encantamiento de rango 3, 

el mismo problema sucede con los patrones de rango 3 de sastrería que son los siguientes:
https://es.wowhead.com/item=138007/patrón-capote-de-filoseda-imbuida
https://es.wowhead.com/item=138001/patrón-sombra-de-filoseda-imbuida
https://es.wowhead.com/item=138004/patrón-ornamento-de-filoseda-imbuida
https://es.wowhead.com/item=138010/patrón-mantón-de-filoseda-imbuida
seria cuestion de probar todos los patrones, para ver si tienen el mismo error

otro error que tanto formulas y patrones mencionadas en este chat, se pueden obtener sin la necesidad de tener las profesiones (sastreria/encantamiento). osea puedes tener otras profesiones o no tener ninguna, estos patrones y formulas son dropeadas por los adds... deberia ser dropeadas exclusivamente al tener dicha profesion.

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
