### ISSUE TITLE
[DUNGEON][LEGION] M+ Affix Grievous not working

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2620]
**Links:**
![WoWScrnShot_071421_004727](https://user-images.githubusercontent.com/85613053/125682729-6975de67-9308-4658-81f5-6d07ae5f15f6.jpg)
![image](https://user-images.githubusercontent.com/85613053/125683008-0a471fb5-48fe-410f-a0e9-31dce2d684d0.png)
https://www.wowhead.com/affix=12/grievous

**What is happening:**
Ran upper kara mythic+ and grievous never applied to us.

**What should happen:**
When a player falls below 90% health, the Grievous Wound DoT is applied and begins to stack every couple of seconds until healed up.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later.
