### ISSUE TITLE
Stormwind Portal to Dalaran Legion

### ISSUE THREAD

**Issue by swat54swe** [GuabinaCore/WoWKoi#2621]
https://www.youtube.com/watch?v=aboysnazdR8

portal is missing,

video shows where its supposed to be

**Comment by Kirrkoi** [comment]
you have to do the chain of quests that take you to Dalaran from legion
![image](https://user-images.githubusercontent.com/81131460/125695611-d498f9f8-620f-4039-be90-dfa08dfca428.png)

**Comment by Noahkrr** [comment]
you have to do the chain of missions that take you to Dalaran de legion
![WoWScrnShot_071421_163011](https://user-images.githubusercontent.com/81131460/125696811-0529dc9b-c542-418c-b229-cd1f4b1c3222.jpg)
Once the quest chain is finished, when you return to Stormwind the portal will still be available to go to Dalaran de Legion
