### ISSUE TITLE
[Tyce] - PVE Guardian Druid Loot Table

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2622]
**Links:**
https://www.wowhead.com/item=144463/shard-of-kaldorei-stained-glass
https://www.wowhead.com/item=142160/mrrgrias-favor
https://www.wowhead.com/item=137349/naraxas-spiked-tongue
https://www.wowhead.com/item=140794/arcanogolem-digit
https://www.wowhead.com/item=137459/chaos-talisman
https://www.wowhead.com/item=141536/padawsens-unlucky-charm
https://www.wowhead.com/item=133641/eye-of-skovald
https://www.wowhead.com/item=137539/faulty-countermeasure
https://www.wowhead.com/item=136715/spiked-counterweight
https://www.wowhead.com/item=137357/mark-of-dargrul
https://www.wowhead.com/item=137433/obelisk-of-the-void

**What is happening:**
Receiving items that are not on the Druid Guardian Personal Loot table while both in the Guardian spec and having Guardian selected for loot. 

**What should happen:**
Selected Loot Specialization should affect the loot tables and change potential boss drops. These items shouldn't drop for Guardian.

**Comment by nevarden** [comment]
**Links:**
https://www.wowhead.com/item=137486/windscar-whetstone
https://www.wowhead.com/item=144259/kiljaedens-burning-wish
https://www.wowhead.com/item=144258/velens-future-sight

These are more trinkets that are non-Guardian loot spec but still dropping.

**Comment by Arkanheal** [comment]
Not only linked to Guardian Druid. Personal Loot tables are fcked
