### ISSUE TITLE
[Legion][Professions][Cooking] Recipe: Bear Tartare

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2623]
**Links:**
https://www.wowhead.com/npc=93371/mordvigbjorn
https://www.wowhead.com/item=133827/recipe-bear-tartare

**What is happening:**
Recipe: Bear Tartare isn't dropping off Mordvigbjorn.

**What should happen:**
Recipe: Bear Tartare should be a guaranteed drop.

**Comment by Cefiro-Caecias** [comment]
That Recipe has an 80% drop chance, more than wowhead indicates (64%).
