### ISSUE TITLE
Cazador de demonios - Misiones de zona de inicio

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2625]
**Links:**

from WoWHead or our Armory

**What is happening:**
no hay mision de inicio, el npc (https://es.wowhead.com/npc=93011/kayn-furia-del-sol) deberia entregar las misiones de inicio de los cazadores de demonios
https://es.wowhead.com/quest=40077/comienza-la-invasión
![image](https://user-images.githubusercontent.com/81131460/125723994-d44172b1-9350-4d2a-b617-505675e4d7fb.png)

**Comment by LKArthas** [comment]
Fixed
