### ISSUE TITLE
[Tyce] - Priest Mind Control permanent combat

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2627]
**Links:**
https://www.wowhead.com/spell=605/mind-control
![image](https://user-images.githubusercontent.com/85613053/125741203-7ad2201e-ff8d-4336-beb6-32447c3d3265.png)
![image](https://user-images.githubusercontent.com/85613053/125741368-1f5046e6-ed75-4968-8254-cb4726a92e04.png)
![image](https://user-images.githubusercontent.com/85613053/125741484-17ba4861-906d-4c93-af3a-6df78d8386d7.png)

**What is happening:**
Mind Controlled mobs will chase you forever after Mind Control ends.

**What should happen:**
They should reset and tether back to their original location if you leave the nearby vicinity,

**Comment by Arkanheal** [comment]
Linked to #1956 ?
