### ISSUE TITLE
[Wotlk][Zone][Alliance side] Dragonblight - complete zone report(under construction)

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2628]
**Links:**

https://www.wowhead.com/dragonblight
---
1. 
 - [ ] Quest - [The Liquid Fire of Elune](https://www.wowhead.com/quest=12166/the-liquid-fire-of-elune)
     - [Liquid Fire of Elune](https://www.wowhead.com/item=36956/liquid-fire-of-elune) can be used multiple times on one corpse for additional credits.
---
2. 
 - [ ] Quest [Planning for the Future](https://www.wowhead.com/quest=11960/planning-for-the-future)
     - Clicking on [Snowfall Glade Pup](https://www.wowhead.com/npc=26200/snowfall-glade-pup) doesn't give quest item [Snowfall Glade Pup](https://www.wowhead.com/item=35692/snowfall-glade-pup) 
---
3. 
 - [ ] Location - New Hearthglen
     - Whenever I enter Hearthglen, I instantly die after a couple of seconds. It seems, there are certain spots that kill you when walked on. Chat logs don't show anything that would indicate what is the cause of the instant death. EDIT: fighting mobs and not moving doesn't help, I still get randomly one shot and it's not coming from the mobs.
     
![image](https://user-images.githubusercontent.com/63166930/126077262-3d192bbc-2e5d-4bf0-af6f-21b324142355.png)

---
4. 
 - [ ] Quest - [The Truth Shall Set Us Free](https://www.wowhead.com/quest=12301/the-truth-shall-set-us-free)
     - The event doesn't grant credits after it finishes.
     - The event isn't 100% correct, some movement and animations missing. Might as well ignore this part.
---
5. 
 - [ ] Quest - [The Cleansing Of Jintha'kalar](https://www.wowhead.com/quest=12545/the-cleansing-of-jinthakalar)
     - Monsters missing in northern part of questing area. 2 respawns required.
     - [Tormented Drakkari](https://www.wowhead.com/npc=26965/tormented-drakkari) are dormant instead of behaving like ordinary mobs.
---
6. 
 - [ ] Quest - [Conversing With the Depths](https://www.wowhead.com/quest=12032/conversing-with-the-depths)
     - [Oacha'noa](https://www.wowhead.com/npc=26648/oachanoa) doesn't disappear after finishing the event.
---
7. 
 - [ ] Quest - [Steamtank Surprise](https://www.wowhead.com/quest=12326/steamtank-surprise)
     - Quickly leaving and re-entering [Alliance Steam Tank](https://www.wowhead.com/npc=27587/alliance-steam-tank#abilities) teleported me to random place far away from the continent. I was unable to do anything.
     - [Drop Off Soldier](https://www.wowhead.com/spell=49081/drop-off-soldier) ability doesn't grant credits toward the quest.
     - Alliance Steam Tanks don't disappear or reset to their default position after being left by the player.
---
8. 
 - [ ] Quest - [The Chain Gun And You](https://www.wowhead.com/quest=12457/the-chain-gun-and-you)
     - [7th Legion Chain Gun](https://www.wowhead.com/npc=27714/7th-legion-chain-gun) - [Call Out Injured Soldier](https://www.wowhead.com/spell=49550/call-out-injured-soldier#comments) doesn't work. I just spawns an NPC on the player.
     -[Mindless Ghoul](https://www.wowhead.com/npc=27712/mindless-ghoul)s should mass spawn when the call out ability is used.(?)
---
9. 
 - [ ] Quest - [Chasing Icestorm: Thel'zan's Phylactery](https://www.wowhead.com/quest=12467/chasing-icestorm-thelzans-phylactery)
     - ["Wyrmbait"](https://www.wowhead.com/npc=27843/wyrmbait)'s dialogue doesn't trigger [Icestorm](https://www.wowhead.com/npc=26287/icestorm) spawning event.
---
10. 
 - [ ] Quest - [An End And A Beginning](https://www.wowhead.com/quest=12473/an-end-and-a-beginning#comments)
     - Event missing. (Since it's old content, spawning the quest NPC a couple of meters away from the quest giver will be just fine)
---
11. 
 - [ ] NPC
     -
---
12. 
 - [ ] [Mystery of the Infinite](https://www.wowhead.com/quest=12470/mystery-of-the-infinite)
     - Quest is not completed after finishing the event.
---
13. 
 - [ ] [The Plume of Alystros](https://www.wowhead.com/quest=12456/the-plume-of-alystros)
     - [Alystros the Verdant Keeper](https://www.wowhead.com/npc=27249/alystros-the-verdant-keeper) should be in stasis.
     - [Skytalon Molts](https://www.wowhead.com/item=37881/skytalon-molts) doesn't taunt Alystros.
---
14. 
 - [ ] [That Which Creates Can Also Destroy](https://www.wowhead.com/quest=12459/that-which-creates-can-also-destroy)
     - [Using Seeds of Nature's Wrath](https://www.wowhead.com/item=37887/seeds-of-natures-wrath) can't be used. It says "You can't do that yet".
---
15. 
 - [ ] [No Place To Run](https://www.wowhead.com/quest=12261/no-place-to-run)
     - After summoning the crystal and finishing the event,  the quest is not completed.
---
16. 
 - [ ] [Neltharion's Flame](https://www.wowhead.com/quest=12267/neltharions-flame)
     - After using [Neltharion's Flame](https://www.wowhead.com/item=37539/neltharions-flame), [Rothin the Decaying](https://www.wowhead.com/npc=27355/rothin-the-decaying) is still immune to damage.
---
17. 
 - [ ] NPC
     -
---
18. 
 - [ ] NPC
     -
---
19. 
 - [ ] NPC
     -
---
20. 
 - [ ] NPC
     -
---
21. 
 - [ ] NPC
     -
---
22. 
 - [ ] NPC
     -
---
23. 
 - [ ] NPC
     -
---
24. 
 - [ ] NPC
     -
---
25. 
 - [ ] NPC
     -
---
26. 
 - [ ] NPC
     -
---
27. 
 - [ ] NPC
     -
---
28. 
 - [ ] NPC
     -
---
29. 
 - [ ] NPC
     -
---
30. 
 - [ ] NPC
     -
---

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt much later. Much patience :P
