### ISSUE TITLE
[Core] - Spell Sweeping Strikes - Warrior Arms Talent

### ISSUE THREAD

**Issue by Trevis77** [GuabinaCore/WoWKoi#263]
**Links:**
https://classic.wowhead.com/spell=12292/sweeping-strikes

**What is happening:**
Execute doesn't deal AOE damage with the talent "Sweeping Strikes" when it should (but Mortal Strike does).

**Comment by GuabinaCore** [comment]
Fixed, please check the spell and inform us if everything is good
