### ISSUE TITLE
[Tyce] - Guardian Druid Growl procs Galactic Guardian

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2631]
**Links:**
![image](https://user-images.githubusercontent.com/85613053/125833528-2d71b90d-a82b-4f4d-84fa-66ca876b5d29.png)
![image](https://user-images.githubusercontent.com/85613053/125833592-7358854a-af03-44a7-a864-e734aeccb342.png)
https://www.wowhead.com/spell=203964/galactic-guardian
https://www.wowhead.com/spell=6795/growl
**What is happening:**
Growling can proc Galactic Guardian.

**What should happen:**
Galactic Guardian should only proc from damage.

**Comment by Arkanheal** [comment]
Do you have an update on this @nevarden ?
