### ISSUE TITLE
Demon Hunter - Misiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2632]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/quest=38728/la-piedra-angular
esta mision esta bug, el npc  (https://es.wowhead.com/npc=93802/reina-de-la-progenie-tyranna)
pelea con alguien que no se ve, tambien hace mucho daño, y hay un Demon hunter enemigo que pega mucho daño y su vida se restaura rapidamente al golpearlo imposible matar, y al matar (https://es.wowhead.com/npc=93802/reina-de-la-progenie-tyranna) , la mision se completa, se supone que debemos lootear (https://es.wowhead.com/item=124672/piedra-angular-sargerita)

https://es.wowhead.com/quest=39688/entre-nosotros-y-la-libertad
la mision no cuenta objetivo si los aliados matan o si le dan el golpe de gracia (https://es.wowhead.com/npc=96783/bastillax)

https://es.wowhead.com/quest=39689/illidari-nos-vamos
Khadgar npc duplicado (https://es.wowhead.com/npc=97978/archimago-khadgar)

![image](https://user-images.githubusercontent.com/81131460/125848126-3c0d384b-9991-4db1-b659-873e4e8f1f78.png)

hay adds que no se mueven ni te hacen caso y hay muchos adds que reaparecen muy rapido despues de matarlos

**Comment by Cefiro-Caecias** [comment]
Arthas se está encargando de reconstruir la zona. Paciencia ^^
