### ISSUE TITLE
Vengeance Demon Hunter Ability Missing

### ISSUE THREAD

**Issue by Uladentar** [GuabinaCore/WoWKoi#2634]
**What is happening:**
By the time of completion of the Demon Hunter starting questline, I am still missing the [Sigil of Flame] ability. In its place, I have a second Metamorphosis. 

**What should happen:**
I should by this point have the Sigil of Flame, and should have never had 2 Metamorphosis spells as shown below.
![Screenshot (1193)](https://user-images.githubusercontent.com/87512805/125893271-e6e85990-718b-4f25-90fd-f1654fae512c.png)

**Comment by Uladentar** [comment]
EDIT: Woke up this morning, have not one ability that was missing, but a second, Imprison, that I didn't notice I was missing. Still have 2 Metamorphosis spells.

**Comment by Cefiro-Caecias** [comment]
In the process of reconstruction. Patience.
