### ISSUE TITLE
Frost DK Artifact Scenario Quest - The Call of Icecrown

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2636]
**Links:**
https://www.wowhead.com/quest=38990/the-call-of-icecrown

**What is happening:**
Click on the Death Gate, which has opened for you, watch the cinematic and sit in a black screen forever once it ends.

**What should happen:**
Should be able to watch the til the end without needing to skip.

**Links:**
https://www.wowhead.com/npc=94913/phantom-mage
https://www.wowhead.com/spell=192033/freezing-winds

**What is happening:**
Spell currently doesn't do anything while channeling.

**What should happen:**
Pushback and visual effects.

**Links:**
https://www.wowhead.com/npc=97320/stoneskin-gatekeeper
https://www.wowhead.com/spell=192188/hardened

**What is happening:**
They are stuck in Hardened animation and after they are defeated, they float back to their pedestal. The pressure plates don't affect the door either. 

**What should happen:**
The mobs should be animated and when they are defeated, they cast hardened and stay still. The player has to defeat them on a pressure plate, or death grip the mob onto a pressure plate. Both pressure plates have to have something on them for the door to be open.

**Links:**
https://www.wowhead.com/npc=94907/spectral-knight

**What is happening:**
They just stand still instead of fighting back.

**What should happen:**
Aggro to the player and fight.

**Links:**
https://www.wowhead.com/item=127009/fragment-of-frostmourne

**What is happening:**
Looting the first fragment gives 2/4 towards stage 3 progression. Looting the second fragment puts you at 4/4 and starts Stage 4.

**What should happen:**
Each fragment should only count as 1 fragment. Need to collect 4 fragments to get to the next stage.

**Links:**
https://www.wowhead.com/spell=200669/avengers-shield
https://www.wowhead.com/npc=93950/magroth-the-defender
https://www.wowhead.com/spell=79968/blessing-of-kings
https://www.wowhead.com/spell=200678/consecration
https://www.wowhead.com/spell=200679/consecration

**What is happening:**
He doesn't have blessing of kings up.  Avengers shield doesn't hit anything, just flings a shield out. Consecration debuff doesn't end when consecration ground effect fades away.

**What should happen:**
He should have blessing of kings. Avengers shield should hit, daze, and bounce. Consecration debuff should end once the ground effect is gone.

**Links:**
https://www.wowhead.com/npc=93951/gavinrad-the-cruel
https://www.wowhead.com/spell=79976/retribution-aura

**What is happening:**
He doesn't have retribution aura up.

**What should happen:**
He should have retribution aura.

**Links:**
https://www.wowhead.com/npc=93963/echo-of-arthas-menethil
https://www.wowhead.com/spell=189537/shadow-strike
https://www.wowhead.com/npc=95622/razor-ice
https://www.wowhead.com/spell=189679/divine-shield
https://www.wowhead.com/spell=200816/dark-pact
https://www.wowhead.com/npc=94982/echo-of-nerzhul
https://www.wowhead.com/spell=200694/void-barrage

**What is happening:**
No razor ice, no effect after shadow strike. Does divine shield and dark pact at the same time, and runs after the player during the entire ability. Ner'zhul is killable throughout the fight. He doesn't enter combat when the player attacks Arthas. His void barrage aims the wrong way and shoots at the walls.

**What should happen:**
Razor Ice spawns and telegraph to avoid. Divine Shield and run to specific location to cast Dark Pact. Summon waves of undead that run to Arthas and need to be killed. Ner'zhul unkillable and in combat when entering combat with Arthas. Void Barrage should aim in a direction that can hit the player.

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/126118139-f4438631-505d-46b3-ac61-ccb43eb6c78a.png)
![image](https://user-images.githubusercontent.com/85613053/126118597-56a702e3-4e96-4e34-a69d-388c159ffd3a.png)
![image](https://user-images.githubusercontent.com/85613053/126120640-8c0ef426-d299-4286-a0d2-a9f573e477b3.png)

**Comment by nevarden** [comment]
Stage 5 missing thawing and effects on frostmourne.

**Comment by Cefiro-Caecias** [comment]
In the process of reconstruction. Patience.
