### ISSUE TITLE
Neltharion's Lair - Ularogg Cragshaper loot table

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2637]
**Links:**
https://www.wowhead.com/npc=91004/ularogg-cragshaper
https://www.wowhead.com/item=141570/cainens-preeminent-chestguard
https://www.wowhead.com/item=141569/samnohs-exceptional-leggings

**What is happening:**
He drops random BoE world drops as boss loot.

**What should happen:**
Boss should drop loot from his loot table.

**Comment by nevarden** [comment]
![WoWScrnShot_071821_155226](https://user-images.githubusercontent.com/85613053/126397087-b767464a-5de2-4a25-a2d5-ec7e36d4fd7c.jpg)

**Comment by nevarden** [comment]
![WoWScrnShot_071121_153401](https://user-images.githubusercontent.com/85613053/126399560-90a64d1a-c203-4129-81dc-da3d6dd58519.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
