### ISSUE TITLE
Shal'aran - Feed Oculeth 

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2638]
**Links:**
https://www.wowhead.com/quest=43106/feed-oculeth
https://i.gyazo.com/160c4be41b1f6c6f1bd3bcc352e89ac4.png
https://www.wowhead.com/spell=224186/warpwalking
https://www.wowhead.com/npc=98548/chief-telemancer-oculeth

**What is happening:**
Has gossip to buff you with Warpwalking for 10 mana. It doesn't buff or take mana from you.

**What should happen:**
work like daily quests. You feed NPC with 50 Ancient Mana and he gives you a buff and 50 reputation with the The Nightfallen. Can buy buff at any time, but reputation quest can be done once in 24 hours.

![image](https://user-images.githubusercontent.com/85613053/126224378-372b1dc7-87a6-40bc-9bb7-37c7f1fa455c.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
