### ISSUE TITLE
Shal'aran - Feed Thalyssra

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2639]
**Links:**
https://www.wowhead.com/quest=43994/feed-thalyssra
https://www.wowhead.com/spell=224772/ward-of-the-first-arcanist
https://www.wowhead.com/npc=112146/first-arcanist-thalyssra
https://www.wowhead.com/npc=97140/first-arcanist-thalyssra
**What is happening:**
There are 2 Thalyssra at same time. Missing gossip option to feed Thalyssra.

**What should happen:**
work like daily quests. You feed NPC with 50 Ancient Mana and he gives you a buff and 50 reputation with the The Nightfallen. Can buy buff at any time, but reputation quest can be done once in 24 hours.

![WoWScrnShot_071921_141533](https://user-images.githubusercontent.com/85613053/126227824-b76a2e9c-2cf0-4493-8289-afc1fcdc3e2a.jpg)
![image](https://user-images.githubusercontent.com/85613053/126228273-4fae1d3b-360c-4d9d-8b61-c216dee25d44.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
