### ISSUE TITLE
Quest: Mor'shan Caravan Delivery, Id:29111

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#264]
**Links:**
https://www.wowhead.com/quest=29111/morshan-caravan-delivery
from WoWHead or our Armory

**What is happening:**
Too many mobs spawn coming to attack you making it nearly impossible to complete because they are coming faster than you kill them.
Also the wind riders are flying down and attacking you constantly.

**What should happen:**
The Burning Blade Attackers should not be spawning and following you immediately, they should start following and attacking you when the caravan comes close to them.
The Burning Blade Windriders should not land, follow and attack you constantly, they should be flying and attacking you when you pass near them and only when they are close enough to the caravan they should follow you for a bit before going back in the air to attack again.

**Comment by cyberfreak666** [comment]
Also Serithul the burning blade attackers should die in one hit but there not it takes like 5 hits to kill one.  It might be possible if the mobs were killable in one hit.

**Comment by LKArthas** [comment]
Fixed for next update
