### ISSUE TITLE
[Tyce] - Mythic Keystone expiration

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2640]
**Links:**
![image](https://user-images.githubusercontent.com/85613053/126236128-4597d550-9fa2-4bd3-bde9-9a28b74f2aa9.png)
![image](https://user-images.githubusercontent.com/85613053/126236348-a5531d44-ae64-404a-8251-f15427068190.png)

**What is happening:**
Mythic Keystones expire in the middle of the week, instead of on weekly reset. When weekly reset happens, the mythic keystone disappears, although it hasn't technically expired. This results in being unable to obtain a mythic keystone after the weekly reset until the middle of the week, when the keystones expire again.

**What should happen:**
Mythic keystones should expire on weekly reset and you should be able to loot a keystone from the final boss in a mythic dungeon if you do not have a keystone.

**Comment by nevarden** [comment]
cant get a key for 4 days following weekly reset except from the weekly chest IF ive completed a keystone the previous week

**Comment by ShikoSCS** [comment]
Fixed
