### ISSUE TITLE
Misiones - Joyeria

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2641]
**Links:**

from WoWHead or our Armory

**What is happening:**
se deberia revisar el orden de las misiones, me estoy estancando en la mision (https://es.wowhead.com/quest=40531/venganza-presta), despues no hay misiones.. deberia haber mas misiones..
![image](https://user-images.githubusercontent.com/81131460/128618343-436f9fd7-b97f-4e00-8a7b-a9dc6d2e83db.png)

estas son las misiones que no he recibido y faltan mas misiones--
https://es.wowhead.com/quest=40524/como-anillo-al-dedo
https://es.wowhead.com/quest=40525/sortijas-que-no-baratijas
https://es.wowhead.com/quest=42214/aro-con-descaro

esta mision se añadio en 8.0.1
https://es.wowhead.com/quest=40526/toques-finales

en wowhead: en la cadena de misiones de joyeria, hay algunas misiones añadidas en parche de bfa.

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
