### ISSUE TITLE
Mision - Favor del constructor - Ingenieria

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2642]
**Links:**
https://es.wowhead.com/quest=46119/favor-del-constructor
from WoWHead or our Armory

**What is happening:**
he terminado la cadena de misiones de ingenieria, esta mision me falta, no puedo acceder a ella
en el mapa me aparece esta mision en el mapa, el npc que deberia darme la mision es. (https://es.wowhead.com/npc=93539/hobart-martillazos)

Dato: todas las misiones de ingenieria funcionan correctamente, solo falta ordenar, ya que esta mision (https://es.wowhead.com/quest=46119/favor-del-constructor) deberia estar dentro de la cadena de misiones.

**Comment by Cefiro-Caecias** [comment]
Reparadas. Disponibles en el próximo update.
