### ISSUE TITLE
Mision - Endurecer el pellejo - Peleteria

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2643]
**Links:**
https://es.wowhead.com/quest=40190/endurecer-el-pellejo
from WoWHead or our Armory

**What is happening:**
esta pertenece a  la cadena de misiones de Peleteria, pero no puedo acceder a esta mision, creo que el orden de las misiones esta mal, ya que deberia poder tomar esta mision.
el npc que da la mision es (https://es.wowhead.com/npc=93522/diane-latas)
DATO: todas las misiones estan funcionales, solo falta ordenarlas adecuadamente

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Reparadas. Disponibles en el próximo update.
