### ISSUE TITLE
[Wotlk][Zone][Alliance side] Zul'Drak - complete zone report(under construction)

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2644]
**Links:**

https://www.wowhead.com/zuldrak
-

---
1. 
 - [ ] Quest - [Trolls Is Gone Crazy!](https://www.wowhead.com/quest=12861/trolls-is-gone-crazy)
     - Two [Captured Rageclaw](https://www.wowhead.com/npc=29686/captured-rageclaw)s stand on top of each other.
     - Using [Drakuru "Lock Opener"](https://www.wowhead.com/item=41161/drakuru-lock-opener) spawns another Captured Rageclaw.
     - [Drakuru "Lock Opener"](https://www.wowhead.com/item=41161/drakuru-lock-opener) can be used multiple tiems on the same target.
---
2. 
 - [ ] Quest - [The Storm King's Vengeance](https://www.wowhead.com/quest=12919/the-storm-kings-vengeance):
     - Monsters reset agert being hit while riding [Gymer](https://www.wowhead.com/npc=29884/gymer).
     - Grymer's Abilities:
       -  [Gymer's Grab](https://www.wowhead.com/spell=55516/gymers-grab) doesn't work
       - [Gymer's Throw](https://www.wowhead.com/spell=55421/gymers-throw) I can't confimr if it works since grba ability doesn't work
       - [Gymer's Smash](https://www.wowhead.com/spell=55426/gymers-smash) seems to work fine, although the range is very small
     - [Reanimated Corpse](https://www.wowhead.com/npc=29897/reanimated-corpse) are standing idle, they should run around the are and attack Grymer
     - Storm Clouds are missing around the questing area. (Did not manage to find the ID)
---
3. 
 - [ ] Quest - [Parachutes for the Argent Crusade](https://www.wowhead.com/quest=12740/parachutes-for-the-argent-crusade)
     - Can't use [Crusader Parachute](https://www.wowhead.com/item=39615/crusader-parachute) on [Argent Crusader](https://www.wowhead.com/npc=28029/argent-crusader).
---
4. 
 - [ ] Quest - [Gluttonous Lurkers](https://www.wowhead.com/quest=12527/gluttonous-lurkers)
     - Clicking on [Zul'drak Rat](https://www.wowhead.com/npc=28202/zuldrak-rat) doesn't give quest item "[Zul'Drak Rat](https://www.wowhead.com/item=38380/zuldrak-rat)"
     - Due to the first part being bugged, I can't confirm if using 5 [Zul'Drak Rat](https://www.wowhead.com/item=38380/zuldrak-rat)s on [Lurking Basilisk](https://www.wowhead.com/npc=28145/lurking-basilisk) will spawn a corpse with [Basilisk Crystal](https://www.wowhead.com/item=38382/basilisk-crystals)
---
5. 
 - [ ] NPC - [Vargul Blighthound](https://www.wowhead.com/npc=29452/vargul-blighthound)
     - NPC is friendly instead of Hostile
---
6. 
 - [ ] Quest - [Trouble at the Altar of Sseratus](https://www.wowhead.com/quest=12506/trouble-at-the-altar-of-sseratus)
     - The quest requires the player to complete the objective two times.
---
7. 
 - [ ] Quest - [Troll Patrol: The Alchemist's Apprentice](https://www.wowhead.com/quest=12541/troll-patrol-the-alchemists-apprentice)
     - Quest Giver's dialogue doesn't trigger the event.
---
8. 
 - [ ] Quest [Stocking the Shelves](https://www.wowhead.com/quest=12609/stocking-the-shelves#comments)
     - People in the wowhead comments bragged about low drop rate of quest item, but getting 1 quest item per 10 mobs is ridiculous. Can we have it drop a "normal" way?
---
9. 
 - [ ] Quest [Clipping Their Wings](https://www.wowhead.com/quest=12610/clipping-their-wings)
     - People in the wowhead comments bragged about low drop rate of quest item, but getting 1 quest item per 10 mobs is ridiculous. 
---
10. 
 - [ ] Quest - [Mushroom Mixer](https://www.wowhead.com/quest=12514/mushroom-mixer)
     - Quest Object [Muddlecap Fungus](https://www.wowhead.com/object=190399/muddlecap-fungus) missing.
---
11. 
 - [ ] NPC - [Nerubian Cocoon](https://www.wowhead.com/npc=28413/nerubian-cocoon)
     - Spawns 5 [Drakkari Captive](https://www.wowhead.com/npc=28414/drakkari-captive)
     - The NPC should be stationary.
---
12. 
 - [ ] Quest - [Throwing down](https://www.wowhead.com/quest=12598/throwing-down)
     - [High Impact Grenade](https://www.wowhead.com/item=38574/high-impact-grenade) can be used multiple times on the same Nerubian Crater.
---
13. 
 - [ ] Quest [Leave No One Behind](https://www.wowhead.com/quest=12512/leave-no-one-behind)
     - Quest credit is not granted after escorting quest npcs to the base.
---
14. 
 - [ ] NPC - [Plague Sprayer](https://www.wowhead.com/npc=28274/plague-sprayer)
     - NPC is lvl80, even though the player is lower lvl.
     - NPC should float a little bit higher, so it doesn't catch aggro from the player on the ground. (I believe they shouldn't even behave as an ordinary mob).
---
15. 
 - [ ] Quest - [Infiltrating Voltarus](https://www.wowhead.com/quest=12661/infiltrating-voltarus)
     - [Ensorcelled Choker](https://www.wowhead.com/item=38699/ensorcelled-choker) is not provided when the quest is accepted. 
     - [Stefan's Horn](https://www.wowhead.com/item=41390/stefans-horn) can be used to summon multiple copies of [Stefan Vadu](https://www.wowhead.com/npc=28518/stefan-vadu). Old copies disappear after a couple of minutes, but it still can be used to grief.
     - [Stefan Vadu](https://www.wowhead.com/npc=28518/stefan-vadu)s dialogue to give you another [Ensorcelled Choker](https://www.wowhead.com/item=38699/ensorcelled-choker) doesn't work.
     -
---
16. 
 - [ ] Quest - [Malas the Corrupter](https://www.wowhead.com/quest=12554/malas-the-corrupter)
     - NPC doesn't drop [Head of the Corrupter](https://www.wowhead.com/item=38521/head-of-the-corrupter)
---
17. 
 - [ ] Quest - [Dark Horizon](https://www.wowhead.com/quest=12664/dark-horizon)
     - [Gorebag](https://www.wowhead.com/npc=28666/gorebag)'s dialogue doesn't do anything.
---
18. 
 - [ ] Quest - Reunited
     - Dialogue option doesn't do anything.
---
19. 
 - [ ] Quest - [Too Much of a Good Thing](https://www.wowhead.com/quest=12516/too-much-of-a-good-thing#)
     - [Modified Mojo](https://www.wowhead.com/quest=12516/too-much-of-a-good-thing#) can't be used. It says "You can't do that yet".
---
20. 
 - [ ] [It Rolls Downhill](https://www.wowhead.com/quest=12673/it-rolls-downhill)
     - [Scepter of Suggestion](https://www.wowhead.com/item=39157/scepter-of-suggestion) can't be used. It says "You can't do that yet".
---
21. 
 - [ ] [Fuel for the Fire](https://www.wowhead.com/quest=12690/fuel-for-the-fire)
     - Control over [Bloated Abomination](https://www.wowhead.com/npc=28843/bloated-abomination) is lost after the abomination attack enemies.
     - [Bloated Abomination](https://www.wowhead.com/npc=28843/bloated-abomination) is missing his spells:
          - [Flatulate](https://www.wowhead.com/spell=52497/flatulate)
          - [Burst at the Seams](https://www.wowhead.com/spell=52811/burst-at-the-seams) (I am not certain if that's the correct ID)
---
22. 
 - [ ] [Betrayal](https://www.wowhead.com/quest=12713/betrayal)
     - [Overlord Drakuru](https://www.wowhead.com/npc=28503/overlord-drakuru)'s dialogue option doesn't trigger the event on the roof of Voltarus.
---
23. 
 - [ ] [Bringing Down Heb'Jin](https://www.wowhead.com/quest=12662/bringing-down-hebjin)
     - [Heb'Jin](https://www.wowhead.com/npc=28636/hebjin) is not being summoned when [Heb'Jin's Drum](https://www.wowhead.com/object=190695/hebjins-drum) is used.
---
24. 
 - [ ] [Tails Up](https://www.wowhead.com/quest=13549/tails-up)
     - [Icepaw Bear](https://www.wowhead.com/npc=29319/icepaw-bear) doesnt have dialogue option after using provided quest item on it.
     - [Frost Leopard](https://www.wowhead.com/npc=29327/frost-leopard) grants credits towards Icepaw bear, insted to frost leopards recovered.
     - Unable to get Female Frost leopards credit, it's always female bear or male leopard.
---
24. 
 - [ ] [I Sense a Disturbance](https://www.wowhead.com/quest=12665/i-sense-a-disturbance)
     - [Harkoa](https://www.wowhead.com/npc=28401/harkoa) doesn't have a dialogue option to start the RP travel.
---
25. 
 - [ ] [ZIm'Rhuk](https://www.wowhead.com/object=190657/zimrhuk)
     - Can't complete [Blessing of Zim'Rhuk](https://www.wowhead.com/quest=12656/blessing-of-zimrhuk) because his hitbox is too small, which won't let you click "continue" while talking to him.
---
26. 
 - [ ] [Seek the Wind Serpent Goddess](https://www.wowhead.com/quest=12667/seek-the-wind-serpent-goddess)
     - When getting close to ALtar of Quetz'lun, player should get a buff that allows to see [Quetz'lun's Spirit](https://www.wowhead.com/quest=12667/seek-the-wind-serpent-goddess). I didn't manage to find the ID of the buff.
---
27. 
 - [ ] NPC
     -
---
28. 
 - [ ] NPC
     -
---
29. 
 - [ ] NPC
     -
---
30. 
 - [ ] NPC
     -
---
31. 
 - [ ] NPC
     -
---
31. 
 - [ ] NPC
     -

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt much later. Much patience :P
