### ISSUE TITLE
Class Hall: Missions

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2645]
Links:
![WoWScrnShot_071821_135543](https://user-images.githubusercontent.com/85613053/126397210-c8e41da5-bdff-467a-a192-dba88f16a116.jpg)
![image](https://user-images.githubusercontent.com/85613053/126397240-9643af6b-3368-486d-a1c4-84e259d2e71d.png)
![image](https://user-images.githubusercontent.com/85613053/126397271-2609d0d9-032d-49ad-b628-caa08972e1a9.png)

**What is happening:**
Shows % before sending them on a mission, and is different once they are sent on a mission.
Many unrelated achievements earned from mission.

**What should happen:**
% before and after should be accurate and consistent.
Should only earn achievements related to the activity.

**Comment by Cefiro-Caecias** [comment]
In Review. Patience.
