### ISSUE TITLE
[Tyce] - Leytorrent Potion

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2647]
**Links:**
![image](https://user-images.githubusercontent.com/85613053/126404310-b0d49e3b-c7bb-4dea-b709-b9fd93078985.png)

**What is happening:**
Using it out of combat doesn't start cooldown. says {Cooldown Starts Upon Leaving Combat)

**What should happen:**
If not in combat, the cooldown should begin.

**Comment by Arkanheal** [comment]
Do you have an update on this @nevarden ?
And have you tested if other pots are involved?
