### ISSUE TITLE
Feast of the Fishes

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2649]
**Links:**
https://www.wowhead.com/item=152564/feast-of-the-fishes

**What is happening:**
Can place it down but right clicking the feast doesn't do anything. Can't eat from it.

**What should happen:**
Should be able to eat from the feast so you can become the flopping fish you always wanted to be.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
