### ISSUE TITLE
[Core] - Spell Warlock Ability - Hand of Gul'dan

### ISSUE THREAD

**Issue by axryn** [GuabinaCore/WoWKoi#265]
Ability: Hand of Gul'dan
Class: Warlock (Demonology)

https://www.wowhead.com/spell=105174/hand-of-guldan#changelog

Ability does no damage on landing, and summons too many imps. Ability should deal AoE shadowflame damage when casted, and summon only up to 4 imps. Currently summons up to 40.

**Comment by biosintesis** [comment]
It deals damage and summon the correctly amount of imps
