### ISSUE TITLE
Tome of the Clear Mind

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2650]
**Links:**
https://www.wowhead.com/item=141640/tome-of-the-clear-mind
https://www.wowhead.com/spell=227563/tome-of-the-clear-mind

**What is happening:**
Works at level 110 still. 

**What should happen:**
Says cannot be used above level 109. Shouldn't be able to use it at level 110. Should need to use Tome of the Tranquil Mind instead, at 110.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
