### ISSUE TITLE
Drums of Rage

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2651]
**Links:**
https://www.wowhead.com/item=102351/drums-of-rage
https://www.wowhead.com/spell=146555/drums-of-rage

**What is happening:**
Works at level 110 still.

**What should happen:**
Says cannot be used above level 90. Shouldn't be able to use it at level 110.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
