### ISSUE TITLE
[Emerald Nightmare][Raid Finder] Nythendra

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2652]
**Links:**
https://www.wowhead.com/npc=102672/nythendra
https://www.wowhead.com/spell=202977/infested-breath
**What is happening:**
After Nythendra casts Infested Breath at a player, she keeps that player targeted and will attack it until taunted away.

**What should happen:**
Should target the tank again after casting Infested Breath.
Missing enrage.

**Comment by nevarden** [comment]
Trash at start before Nythendra
Gelatinized Decay knockback from the mob instead of from the debuff. Missing slime trail. After dying, should get sucked towards boss.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
