### ISSUE TITLE
[Emerald Nightmare][Raid Finder] Il'gynoth

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2653]
**Links:**
https://www.wowhead.com/npc=105393/ilgynoth

**What is happening:**
Eye of Il'gynoth doesn't enter combat on pull, unless you attack it specifically. Attacking the other mobs in the encounter doesn't start combat with the eye, so it will heal back to 100% after slimes explode on it.
If you enter the chamber in P2 before Eye has finished death animation, your vision of the heart will be obscured.
Can DPS the heart once Eye dies without having to enter the chamber.

**What should happen:**
Eye of Il'gynoth should enter combat once the encounter begins.
Heart should only be obscured while outside of the room. Shouldn't be able to dps the heart without entering the chamber.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
