### ISSUE TITLE
[Emerald Nightmare][Raid Finder] Elerethe Renferal

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2654]
**Links:**
https://www.wowhead.com/npc=106087/elerethe-renferal
https://www.wowhead.com/spell=215288/web-of-pain
https://www.wowhead.com/achievement=10771/webbing-crashers#

**What is happening:**
Web of pain doesn't reflect damage and there is no change based on distance.
Automatically earn webbing crashers achievement after killing boss.

**What should happen:**
Web of pain should hurt each player, and do more damage if they are more than 20 yards away.
Should have to destroy all the sacs around the boss room for the achievement.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
