### ISSUE TITLE
[Emerald Nightmare][Raid Finder] Dragons of Nightmare

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2655]
**Links:**
https://www.wowhead.com/npc=102679/ysondre

**What is happening:**
They do not share HP properly. One of the dragons die while the others are at 15%

**What should happen:**
They should share health pool and die together.
Missing enrage.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
