### ISSUE TITLE
[Trial of Valor][Raid Finder] Odyn

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2656]
**Links:**
https://www.wowhead.com/npc=114263/odyn
https://www.wowhead.com/spell=198190/unworthy
https://www.wowhead.com/spell=227629/unerring-blast
https://www.wowhead.com/npc=114360/hyrja
https://www.wowhead.com/npc=114361/hymdall
https://www.wowhead.com/spell=228915/stormforged-spear

**What is happening:**
Odyn doesn't cast Unerring Blast in phase 1.
Hyrja and Hymdall don't show up in phase 2.
Missing unworthy mechanic. Die instead of being taken out of fight.
Stormforged Spear gets thrown at anyone.

**What should happen:**
Odyn should cast Unerring Blast in phase 1 as well.
Hyrja and Hymdall should occasionally come down and fight in phase 2.
When damage that would kill you occurs, you should be picked up and taken out of the fight.
Stormforged Spear should only be thrown at the current tank.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
