### ISSUE TITLE
[Trial of Valor][Raid Finder] Guarm

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2657]
**Links:**
https://www.wowhead.com/npc=114344/guarm
https://www.wowhead.com/spell=227883/roaring-leap
https://www.wowhead.com/spell=227816/headlong-charge
**What is happening:**
Doesn't seem to leap at the largest group.
Interrupts its own Headlong Charge often.

**What should happen:**
Shouldnt interrupt its charge. 
Should leap to the biggest group of players.
Missing enrage.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
