### ISSUE TITLE
[Nighthold][Raid Finder] Skorpyron

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2658]
**Links:**
https://www.wowhead.com/npc=102263/skorpyron
https://www.wowhead.com/spell=204471/focused-blast
**What is happening:**
Direction the boss faces and casts and effects land are often inconsistent and impossible to predict.

**What should happen:**
All aspects of the spell and and effects should line up in the same direction.

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/126431444-82f52a9d-5efc-4e86-a74e-11888b3e89d2.png)

Arcane Tether can remain on the tank after the fight has ended.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
