### ISSUE TITLE
[Nighthold][Raid Finder] Chronomatic Anomaly

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2659]
https://www.wowhead.com/npc=104415/chronomatic-anomaly
https://www.wowhead.com/spell=219815/temporal-orbs
https://www.wowhead.com/spell=206607/chronometric-particles
https://www.wowhead.com/spell=206612/burst-of-time

**What is happening:**
Temporal Orb spawns often come out the opposite direction.
**Tank randomly gets one-shot about 20 seconds into the first Time Bomb. Nothing shows up in combat log for death.**
Chronometric Particles doesn't happen.
Burst of time doesn't deal damage.

**What should happen:**
Temporal Orbs should come out the correct direction instead of taking 10 seconds to come out of the middle because theyre going the opposite direction.
Chronometric Particle mechanic should work :D
Tank shouldn't suddenly die.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
