### ISSUE TITLE
[Nighthold][Raid Finder] Trilliax

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2660]
**Links:**
https://www.wowhead.com/npc=104288/trilliax
https://www.wowhead.com/spell=206820/cleansing-rage

**What is happening:**
Doesn't use cleansing rage if there is left-over cake.

**What should happen:**
After Tidy-Up, if theres any old leftover cake, he should use cleansing rage.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
