### ISSUE TITLE
[Nighthold][Raid Finder] Star Auger Etraeus

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2661]
**Links:**
https://www.wowhead.com/spell=206585/absolute-zero
https://www.wowhead.com/npc=103758/star-augur-etraeus

**What is happening:**
Absolute Zero can be removed by walking to 1 player.

**What should happen:**
Should require 3 players to remove it.

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/126438735-789bcaf3-d6e2-41e9-811d-dddee3c4d7d5.png)

'Feared' every time cast finishes but not actually feared.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
