### ISSUE TITLE
[Nighthold][Raid Finder] High Botanist Tel'arn

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2662]
**Links:**
https://www.wowhead.com/npc=104528/high-botanist-telarn
https://www.wowhead.com/npc=112057/parasitic-lasher
https://www.wowhead.com/spell=218424/parasitic-fetter

**What is happening:**
Parasitic Lashers do nothing when they arrive to their fixated target.
Phase 2 instantly became phase 3. Boss went from 75% HP to 25% right away.

**What should happen:**
If the parasite reaches its target, it should jump into them and afflict them with Parasitic Fetter.
Encounter should continue normally instead of boss losing a huge chunk of HP suddenly.

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/126565941-7ee69100-8bd2-4598-b460-72ffe625c955.png)


Phase 2 only lasted 7 seconds, despite very little damage going out. Boss lost huge chunk of HP and went straight into Phase 3.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
