### ISSUE TITLE
[Nighthold][Raid Finder] Gul'dan

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2663]
**Links:**
https://www.wowhead.com/spell=210339/time-dilation
https://www.wowhead.com/spell=217830/scattering-field
https://www.wowhead.com/spell=210296/resonant-barrier
https://www.wowhead.com/spell=243521/fel-scythe
https://www.wowhead.com/spell=206221/empowered-bonds-of-fel
https://www.wowhead.com/npc=104536/inquisitor-vethriz
https://www.wowhead.com/npc=106986/gaze-of-vethriz
https://www.wowhead.com/spell=206840/gaze-of-vethriz
https://www.wowhead.com/spell=207006/dark-blast
https://www.wowhead.com/spell=207938/shadowblink

**What is happening:**
Extra action button is missing for time dilation, scattering field, and resonant barrier.
Fel scythe is missing.
Empowered Bonds of Fel knock the player up.
Inquisitor Vethriz doesn't cast anything.
Gusting Winds doesn't do anything.

**What should happen:**
Should have an extra action button depending on your role.
Fel scythe should be cast when Gul'dan reaches full energy or when an extra player stands in front of Gul'dan to be cleaved.
Empowered Bonds of Fel should knock the player back.
Inquisitor Vethriz should cast his abilities.
Gusting Winds should push players south.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
