### ISSUE TITLE
Misiones de Peleteria

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2664]
**Links:**
https://www.wowhead.com/quest=40212/wrong-end-of-the-knife
https://www.wowhead.com/quest=40213/hounds-abound
from WoWHead or our Armory

**Lo que sucede:**
Ambas misiones funcionan bien, estos items (https://www.wowhead.com/item=130130/felhide-bracers), que recibes al aceptar dichas misiones, son el problema.

**Lo que debería suceder:**
no deberia recibir (https://www.wowhead.com/item=130130/felhide-bracers) al tomar las misiones

**Links:**
https://www.wowhead.com/quest=40214/fel-tanning
from WoWHead or our Armory

**Lo que sucede:**
al tomar la mision, me dan (https://www.wowhead.com/item=130130/felhide-bracers), no deberia darme estos items, ya que no forman parte de la mision.
**Links:**![image](https://user-images.githubusercontent.com/81131460/126569295-3e465b8b-665d-4b2a-818f-e9cbf9ebbc96.png)

**Lo que deberia suceder:**
al tomar la mision, deberiamos aprender estos spell en peleteria:
https://www.wowhead.com/spell=196457/fel-leather-cuff
https://www.wowhead.com/spell=196395/fel-leather-strap
https://www.wowhead.com/spell=196456/felhide-bracers
y me deben dar 9x (https://www.wowhead.com/item=130879/tanned-fel-leather)

estos spell son temporales, solo estan visibles durante la misión.

para crear este item (https://www.wowhead.com/item=130130/felhide-bracers)
necesitamos:
usando el spell (https://www.wowhead.com/spell=196456/felhide-bracers) y los items
(https://www.wowhead.com/item=130937/fel-leather-cuff)
(https://www.wowhead.com/item=130880/fel-leather-strap)
y 9 unidades (https://es.wowhead.com/item=124438/garra-sin-romper)

1er item
se crea (https://www.wowhead.com/item=130937/fel-leather-cuff)
usando el spell (https://www.wowhead.com/spell=196457/fel-leather-cuff) 
2 unidades de (https://www.wowhead.com/item=130879/tanned-fel-leather)

2do item
se crea (https://www.wowhead.com/item=130880/fel-leather-strap)
usando el spell (https://www.wowhead.com/spell=196395/fel-leather-strap)
5 unidades (https://www.wowhead.com/item=130879/tanned-fel-leather)

una vez obtenido el item creado (https://www.wowhead.com/item=130130/felhide-bracers), la mision se completara.
Link de la mision https://www.youtube.com/watch?v=6IKCbVxmXos

**Comment by Kirrkoi** [comment]
de paso reportar a Nomi el cocinero, hace mucho spam en el chat y  aparece y desaparece invocandose cada momento con un ¿Disculpa? ¡Hola!

**Comment by nevarden** [comment]
![WoWScrnShot_071921_150258](https://user-images.githubusercontent.com/85613053/126576308-54b3663d-2610-46f7-b419-f6f2cd69b541.jpg)

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
