### ISSUE TITLE
Netherlight Crucible covered by Light Tigel of the Voids

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2665]
**Links:**
![image](https://user-images.githubusercontent.com/85613053/126571815-2a53b2e5-c237-4680-9188-b06a7bc51bea.png)
![WoWScrnShot_072121_171825](https://user-images.githubusercontent.com/85613053/126571892-3cbcd743-85f2-4877-8d33-b4dbb55f3755.jpg)

**What is happening:**
There is an interactable 'Light Tigel of the Voids' directly on top of the Netherlight Crucible. 

**What should happen:**
There should be no Light Tigel of the Voids. There should only be a Netherlight Crucible.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
