### ISSUE TITLE
Krokuun Quests 

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2666]
**Links:**
https://www.wowhead.com/quest=47589/righteous-fury

**What is happening:**
Quest objective reads "Destroy 1 Legion Devastators."

**What should happen:**
Quest objective should read "Destroy 3 Legion Devastators."

**Links:**
https://www.wowhead.com/quest=46297/overwhelming-power

**What is happening:**
Quest objective reads "Kill 1 demons."

**What should happen:**
Quest objective should read "Kill 12 demons."

**Comment by nevarden** [comment]
**Links:**
https://www.wowhead.com/quest=47627/vengeance
https://www.wowhead.com/npc=120361/antaen-light-breaker
https://www.wowhead.com/spell=250863/reckless-stomp
![image](https://user-images.githubusercontent.com/85613053/126573688-08a6d700-cf85-4bd1-9a11-e542d828e92f.png)
![image](https://user-images.githubusercontent.com/85613053/126573733-bc603643-548a-4d72-9763-a9d0c3d152a9.png)

**What is happening:**
He spawns in front of his head.
Doesn't cast Reckless Stomp.
Russian during when he should do Felshock Bombardment.

**What should happen:**
He should climb out of the ground.
Should use abilities, should be in correct language.

**Comment by nevarden** [comment]
**Links:**
https://www.wowhead.com/quest=46732/the-prophets-gambit

**What is happening:**
NPCs are already there, not scripted. 
Completable without following or standing with Velen

**What should happen:**
Should have to follow Prophet Velen, and be ambushed by ridgestalkers and a whole bunch of ensuing dialogue.

**Comment by nevarden** [comment]
**Links:**
![image](https://user-images.githubusercontent.com/85613053/126574411-9429a5ec-4741-433f-bd1b-6e228855e54c.png)
https://www.wowhead.com/quest=46816/rendezvous

**What is happening:**
The beacon is already there. You click the signal crystal and unlock a flight path.

**What should happen:**
After using the signal crystal the beacon should come flying down from the Vindicaar.

**Comment by nevarden** [comment]
https://www.wowhead.com/quest=46840/prisoners-no-more

Rescuing the slaves just kills them instead. They instantly respawn again and you can just keep clicking on the same cages.

**Comment by nevarden** [comment]
https://www.wowhead.com/quest=47431/gathering-light

rubble isnt blocked, super unscripted

**Comment by nevarden** [comment]
ok well most of the quests in this zone have bugs of some sort. didnt report every one of them because it feels like every one of them has bugs

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt later. Patience.
