### ISSUE TITLE
Light's Judgment

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2667]
**Links:**
https://www.wowhead.com/quest=47287/the-vindicaar-matrix-core
https://www.wowhead.com/spell=247427/lights-judgment

**What is happening:**
Have access to Light's Judgment ability before you should have it.
Able to use the matrix core as soon as you board the Vindicaar.

**What should happen:**
Shouldn't be able to use matrix core.
Shouldn't have access to the ability.

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/126721929-c1ef8cb8-d2de-42c5-9b74-069fcc326cd2.png)

Should be able to destroy specific rocks with it.

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt later. Patience.
