### ISSUE TITLE
Suramar - Mision - El material de los sueños

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2668]
**Links:**
https://es.wowhead.com/quest=43362/el-material-de-los-sueños
from WoWHead or our Armory

**What is happening:**
esta mision pide matar a Xavius en la Pesadilla esmeralda y recuperar item (https://es.wowhead.com/item=139342/esencia-de-vida-purificada),
mato a xavius  en la pesadilla esmeralda, l

**What should happen:**
esta mision pide matar a Xavius en la Pesadilla esmeralda y recuperar item (https://es.wowhead.com/item=139342/esencia-de-vida-purificada) este item se obtiene despues de matar a xavius, la pesadilla termina y aparecemos en el sueño esmeralda, donde vamos hacia Cenarius y a su costado hay un roble donde obtenemos la Esencia de vida purificada.

https://www.youtube.com/watch?v=Ivm9H3Rxmyw

este es el cenarius (https://es.wowhead.com/npc=106088/cenarius) que esta al lado del roble donde se extrae el item (https://es.wowhead.com/item=139342/esencia-de-vida-purificada).

**Comment by Noahkrr** [comment]
La mision se actualiza en bfa: ahora se crea un portal directo al sueño esmeralda, donde se debe matar al imagen de Xavius, obtenemos el item (https://es.wowhead.com/item=139342/esencia-de-vida-purificada). omitiendo ir a la banda Pesadilla Esmeralda y matar al ultimo jefe Xavius.

**Comment by Noahkrr** [comment]
Pueden hacer la misión autocompletable por ahora.

**Comment by Cefiro-Caecias** [comment]
Puesta temporalmente en modo autocomplete. Disponible en el próximo update. Debes borrar Cache.
