### ISSUE TITLE
Vindicaar hearthstone location

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2669]
**Links:**
https://www.wowhead.com/npc=123395/high-priestess-ishanah

**What is happening:**
Setting hearthstone to the Vindicaar while it's in Azuremyst Isle will send you back to that Vindicaar.

**What should happen:**
Hearthstone location should get changed to the Vindicaar in Argus once you've unlocked the use of the navigation console.

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt later. Patience.
