### ISSUE TITLE
Navigation Console and Lightforged Beacon 'Flight Paths'

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2670]
**Links:**
https://www.wowhead.com/spell=252201/lightforged-beacon-krokul-hovel
https://www.wowhead.com/npc=118830/lightforged-beacon
https://www.wowhead.com/npc=123139/navigation-console

**What is happening:**
Lightforged Beacon counts as flight paths, and requires picking up the navigation console flight path to be able to return to the Vindicaar.

**What should happen:**
Shouldn't need to grab any flight paths. Should be able to teleport back to the Vindicaar without any flight paths.

**Comment by Cefiro-Caecias** [comment]
This area will be rebuilt later. Patience.
