### ISSUE TITLE
Garothi Obliterator damage

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2671]
**Links:**
https://www.wowhead.com/npc=120354/garothi-obliterator
https://www.wowhead.com/spell=251921/obliterating-smash
https://www.wowhead.com/spell=251924/fiery-mortars

**What is happening:**
Garothi Obliterator literally does 1 damage. 3 damageif you're an unlucky cloth-wearer.
Just auto attacks, no abilities.

**What should happen:**
Garothi Obliterator should do maybe a bit more than that.
Should cast his abilities too.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
