### ISSUE TITLE
Attacks and abilities able to miss

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2672]
**Links:**
![image](https://user-images.githubusercontent.com/85613053/126719765-49676908-a4d1-4502-a7d6-aa8ee828050e.png)

**What is happening:**
You are able to miss on bosses.
Here you can see in combat log that mind blast missed.

**What should happen:**
Players should have 100% chance to hit up to 3 levels higher (including against bosses).

**Comment by Cefiro-Caecias** [comment]
Fixed.
