### ISSUE TITLE
Shop toys with a problem's

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#2673]
**Links:**

[Brazier of Dancing Flames](https://tbc.wowhead.com/item=34686/brazier-of-dancing-flames) - Do nothing. Its suppose to dance
https://www.youtube.com/watch?v=aYdwWVihq0I

[[Crashin' Thrashin' Robot]](https://tbc.wowhead.com/item=23767/crashin-thrashin-robot) - Do nothing. Must fight with other robots if there are any. 

[[Imp in a Ball]](https://tbc.wowhead.com/item=32542/imp-in-a-ball) - Do nothing. There is no imp or ball or questions to ask.

[[Winter Veil Disguise Kit]](https://www.wowhead.com/item=17712/winter-veil-disguise-kit) - It work,but since its seasonable (need Snowball's may become problematic)  

[[Power Converter]](https://tbc.wowhead.com/item=30690/power-converter) - Do nothing. Must be like fireworks. 

[[Sylvanas' Music Box]](https://www.wowhead.com/item=52253/sylvanas-music-box) - The Lady's spawn, but don't do any emotions and the music don't play at all. 
https://www.youtube.com/watch?v=gPhaIg_VoKI

[[Arrival of the Naaru]](https://www.wowhead.com/item=64456/arrival-of-the-naaru) - Nothing happen. There must be a RP event.
https://www.youtube.com/watch?v=ZHP_yWZ7aeA

[[Chalice of the Mountain Kings]](https://www.wowhead.com/item=64373/chalice-of-the-mountain-kings) - Nothing happen. There must be a little RP event.
https://www.youtube.com/watch?v=AcfHEG2hUrI

[[Flimsy Yellow Balloon]](https://www.wowhead.com/item=75042/flimsy-yellow-balloon) -It's specific event item that won't work out of it. 

[[Grim Campfire]](https://www.wowhead.com/item=67097/grim-campfire) - spirit buff is missing

[[Pendant of the Scarab Storm]](https://www.wowhead.com/item=64881/pendant-of-the-scarab-storm) it work , but the bug's spawn on each other.

[[Little Wickerman]](https://www.wowhead.com/item=70722/little-wickerman) - spirit buff is missing

[[Puzzle Box of Yogg-Saron]](https://www.wowhead.com/item=64482/puzzle-box-of-yogg-saron ) spawn infernals( triggers)
It suppose to whisper you some.... things.
https://www.wowhead.com/item=64482/puzzle-box-of-yogg-saron#comments:id=1132633

[[Crashin' Thrashin' Flyer Controller] ](https://www.wowhead.com/item=104318/crashin-thrashin-flyer-controller)- [rockets](https://www.wowhead.com/spell=148581/rocket-attack) dont work (second spell)

[[Darkmoon Seesaw]](https://www.wowhead.com/item=97994/darkmoon-seesaw) - nothing is summoned

[[Turnip Punching Bag]](https://www.wowhead.com/item=88375/turnip-punching-bag) - Thats a raid boss dmg and act like NPC...its suppose to be Dummy.

[[Shado-Pan Geyser Gun]](https://www.wowhead.com/item=98132/shado-pan-geyser-gun) - cant remove the toy effect

[[Safari Hat]](https://www.wowhead.com/item=92738/safari-hat) - bit P2W toy

[[Autographed Hearthstone Card]](https://www.wowhead.com/item=118427/autographed-hearthstone-card) - not working
It suppose to make emotes
https://www.wowhead.com/item=118427/autographed-hearthstone-card

[[Darkmoon Tonk Controller] ](https://www.wowhead.com/item=122122/darkmoon-tonk-controller)-  not working

[[Crashin' Thrashin' Roller Controller] ](https://www.wowhead.com/item=108631/crashin-thrashin-roller-controller)- not working

[[Crashin' Thrashin' Shredder Controller]](https://www.wowhead.com/item=116763/crashin-thrashin-shredder-controller) - not working

[[Giant Deathweb Egg]](https://www.wowhead.com/item=117569/giant-deathweb-egg) - no spider

[[Goren "Log" Roller] ](https://www.wowhead.com/item=119180/goren-log-roller)- it's a mess

[[Personal Hologram] ](https://www.wowhead.com/item=108745/personal-hologram)- not working

[[Portable Audiophone] ](https://www.wowhead.com/item=122700/portable-audiophone) -  must be a object, not npc that follow me

[[Firefury Totem] ](https://www.wowhead.com/item=119145/firefury-totem)- do nothing

[[Stolen Breath]](https://www.wowhead.com/item=111476/stolen-breath) - dont have the spell effect

[[Steamworks Sausage Grill]](https://www.wowhead.com/item=116757/steamworks-sausage-grill) - dont have the spirit effect

[[Arcano-Shower] ](https://www.wowhead.com/item=141297/arcano-shower)- ''shower'' effect is missing

[[Black Ice]](https://www.wowhead.com/item=133997/black-ice) - Ring dont appear

[[Crab Shank]](https://www.wowhead.com/item=140314/crab-shank) - bit broken visual .It suppose to work only on pet Crabs, not on players (yourself)

[[Crate of Bobbers: Carved Wooden Helm] ](https://www.wowhead.com/item=147307/crate-of-bobbers-carved-wooden-helm ) - don't change the fishing pole 

[[Enchanted Bobber] ](https://www.wowhead.com/item=147308/crate-of-bobbers-enchanted-bobber) -  don't change the fishing pole

[[Replica Gondola]](https://www.wowhead.com/item=147311/crate-of-bobbers-replica-gondola)  - don't change the fishing pole

[[Displacer Meditation Stone]](https://www.wowhead.com/item=141298/displacer-meditation-stone) -stuck in ''sit'' pose until relog

[[Fal'dorei Egg] ](https://www.wowhead.com/item=140780/faldorei-egg)- missing walk animation and stuck in ''lay'' emote once the effect is gone.

[[Falanaar Echo]](https://www.wowhead.com/item=140779/falanaar-echo) - do nothing...but not ever sure if suppose to

[[Fractured Necrolyte Skull](https://www.wowhead.com/item=151016/fractured-necrolyte-skull)] - cast the spell but not kill the npc or summ the portal

[[Hearthstation]](https://www.wowhead.com/item=151343/hearthstation) - work halfway

[[Love Boat]](https://www.wowhead.com/item=142341/love-boat) - suppose to work only around the water.now can summ it anywhere

[[Legion Communication Orb]](https://www.wowhead.com/item=153194/legion-communication-orb) - Beam part dont work

[[Leather Love Seat]](https://www.wowhead.com/item=129956/leather-love-seat) - it work, but once u sit u cant move anymore

[[Never Ending Toy Chest] ](https://www.wowhead.com/item=130209/never-ending-toy-chest)- nothing  inside ,cant ever click on it

[[Verdant Throwing Sphere]](https://www.wowhead.com/item=151184/verdant-throwing-sphere) - very bugged

**What is happening:**

**What should happen:**

**Comment by nevarden** [comment]
https://www.wowhead.com/item=118191/archmage-vargoths-spare-staff the NPC is not supposed to follow you

**Comment by nevarden** [comment]
https://www.wowhead.com/item=54651/gnomeregan-pride unlocks account wide, same with the horde version. not unusual

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/126840190-c2ddc559-7520-4be3-af2a-49c9031056ac.png)

https://www.wowhead.com/item=133997/black-ice
Black Ice appears but does not glimmer

**Comment by nevarden** [comment]
#2585 
#2584 
#2581

**Comment by NightwindOI** [comment]
ty ^_^

**Comment by nevarden** [comment]
Ruthers' Harness - summons ruthers but should also smack into me.
Scarlet Confessional Book - doesnt work
Memory Cube - has memories that shouldnt be accessable yet (because i havent done those events yet). you get portaled after cinematics. follows you around like a pet.
Dirty Spoon - can be used on whatever
Fake Teeth - can be used on whatever
Purple Blossom - can be used on whatever
Tiny Pack - can be used on whatever

![image](https://user-images.githubusercontent.com/85613053/126879325-f032047c-500d-4f18-acd9-133c310d2436.png)

**Comment by Cefiro-Caecias** [comment]
* Brazier of Dancing Flames: fixed. Do not forget to test the commands on it: /dance, /kiss, /wave, /bow, /joke ;)

* Crashin' Thrashin' Robot: partially repaired.

* Imp in a Ball: it seems to work fine.

* Winter Veil Disguise Kit: item removed from the Store.

* Power Converter: it seems to work fine.

* Sylvanas' Music Box: it seems to work fine.

* Arrival of the Naaru: I have not found data on the summoned NPCs, to be able to reproduce the effect.

* Chalice of the Mountain Kings: I have not found data on the summoned NPCs, to be able to reproduce the effect.

* Flimsy Yellow Balloon: fixed.

* Grim Campfire: I have not found data on the correct buff.

**Comment by Cefiro-Caecias** [comment]
* Pendant of the Scarab Storm: partially repaired.

* Little Wickerman: I have not found data on the correct buff.

* Puzzle Box of Yogg-Saron: repaired; now the whispers will haunt you.

**Comment by Cefiro-Caecias** [comment]
* Crashin' Thrashin' Flyer Controller: reported corrupted spell to core devs.

* Darkmoon Seesaw: partially repaired.

**Comment by Cefiro-Caecias** [comment]
* Turnip Punching Bag: fixed.

* Shado-Pan Geyser Gun: reported corrupted spell to core devs.

* Safari Hat: may god bless the poor XD

* Autographed Hearthstone Card: it seems to work fine.

* Darkmoon Tonk Controller: fixed.

* Crashin' Thrashin' Roller Controller: it seems to work fine.

* Crashin' Thrashin' Shredder Controller: it seems to work fine.

* Giant Deathweb Egg: it seems to work fine.

* Goren "Log" Roller: reported corrupted spell to core devs.

* Personal Hologram: reported corrupted spell to core devs.

* Portable Audiophone: fixed.

* Firefury Totem: partially repaired.

* Stolen Breath: reported corrupted spell to core devs.

* Steamworks Sausage Grill: I have not found data on the correct buff.

* Arcano-Shower: it seems to work fine.

* Black Ice: reported corrupted spell to core devs.

* Crab Shank: fixed.

* Crate of Bobbers: Carved Wooden Helm: partially repaired.

* Enchanted Bobber: partially repaired.

**Comment by Cefiro-Caecias** [comment]
* Replica Gondola: partially repaired.

* Displacer Meditation Stone: reported corrupted spell to core devs.

* Fal'dorei Egg: reported corrupted spell to core devs.

* Falanaar Echo: reported corrupted spell to core devs.

* Fractured Necrolyte Skull: reported corrupted spell to core devs.

* Hearthstation: in review.

**Comment by Cefiro-Caecias** [comment]
* Love Boat: partially repaired.

* Legion Communication Orb: reported corrupted spell to core devs.

* Leather Love Seat: fixed.

* Never Ending Toy Chest: fixed.

* Verdant Throwing Sphere: reported corrupted spell to core devs.

**Comment by Cefiro-Caecias** [comment]
* Archmage Vargoth's Spare Staff: fixed.

* Gnomeregan Pride: it seems to work fine.

* Ruthers' Harness: fixed.

* Scarlet Confessional Book: reported corrupted spell to core devs.

* Memory Cube: fixed. 

* Dirty Spoon: fixed. 

* Fake Teeth: fixed. 

* Purple Blossom: fixed. 

* Tiny Pack: fixed.

**Comment by Cefiro-Caecias** [comment]
Done. Available in the next update. I hate you :P
