### ISSUE TITLE
Misiones al completarlas se bugean

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2674]
**Links:**

from WoWHead or our Armory

**What is happening:**
las misiones al completar
![image](https://user-images.githubusercontent.com/81131460/126856797-06f753c4-c6e2-4fa5-b9ab-8e5589b87a8a.png)
, al rato cambian a
![image](https://user-images.githubusercontent.com/81131460/126856734-f33746c9-fa54-4662-a788-c7d5cf667136.png)

otra vez complete otra mision
![image](https://user-images.githubusercontent.com/81131460/126856811-188724d7-6519-4ca8-a1b9-3ff9b72715a5.png)
el mismo problema la mision que estaba completa cambia a sin rastreo.
![image](https://user-images.githubusercontent.com/81131460/126856850-2429e006-e912-45aa-8152-76922a346a64.png)

![image](https://user-images.githubusercontent.com/81131460/126858180-590854d5-6671-4654-80b6-e76d0fa9565d.png)
![image](https://user-images.githubusercontent.com/81131460/126858182-819f3abb-3195-4481-9f7d-77a5c4621045.png)
![image](https://user-images.githubusercontent.com/81131460/126858190-b3efa699-5fda-47ec-bab2-86e070a5a260.png)
estas misiones si pudieron entregar a pesar de no tener rastreo, cuando tomo dos misiones, ya las completo una tras otra, una de las misiones se bugea o ambas. el NPC al que debo entregar la mision aveces no reconoce la mision o no aparece (solo en el caso que el NPC que inicia la mision y el npc que termina la mision son diferentes)

**Comment by Cefiro-Caecias** [comment]
Eso ya debería estar solucionado.
