### ISSUE TITLE
Tónico del Pescador - NPC - Guerrero de Jandvik 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2676]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/quest=40334/tónico-del-pescador
en npc (https://es.wowhead.com/npc=102381/guerrero-de-jandvik) se bugea, es como si se invocara, eso lo repite a cada momento (el sonido de la invocacion es molesto y es repetitivo), el npc te sigue hasta cierto punto (si completas el primer credito de la mision, dejara de seguirte) y el resto de la mision se logra completar exitosamente.
![image](https://user-images.githubusercontent.com/81131460/126878226-4725903a-e6a7-446c-be96-3582f25a4e58.png)

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
