### ISSUE TITLE
The Netherlight Crucible

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2678]
**Links:**
https://www.wowhead.com/quest=49224/the-netherlight-crucible
https://www.wowhead.com/quest=48560/an-offering-of-shadow

**What is happening:**
access to the quest and crucible before finishing the earlier steps of the questline 

**What should happen:**
should need to do An Offering of Shadow first.

**Comment by Cefiro-Caecias** [comment]
Added security measure to Netherlight Crucible. The rest will be rebuilt later. Available in the next update.
