### ISSUE TITLE
[Quest][Demon Hunter]The Keystone

### ISSUE THREAD

**Issue by Cyrous96** [GuabinaCore/WoWKoi#2679]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=38728/the-keystone
**What is happening:**
Kor'vas Bloodthorn gets full healed every 10 sec so you can't stop the transformation and eyebeam deals too much damage

**What should happen:**

**Comment by LKArthas** [comment]
this will be fixed as soon i get there, don't worry only few quests before it :)
