### ISSUE TITLE
Northern Barrens Mob Behavior

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#268]
**Links:**
https://imgur.com/a/iFMhLxh

https://www.wowhead.com/npc=3246/fleeting-plainstrider

https://www.wowhead.com/npc=3275/kolkar-marauder
https://www.wowhead.com/npc=3396/hezrul-bloodmark
https://www.wowhead.com/npc=44170/hezruls-bloodguard
https://www.wowhead.com/npc=3241/savannah-patriarch
https://www.wowhead.com/npc=34647/barrens-boar
https://www.wowhead.com/npc=3379/burning-blade-bruiser
https://www.wowhead.com/npc=3276/witchwing-harpy
https://www.wowhead.com/npc=95806/witchwing-slayer
https://www.wowhead.com/npc=3280/witchwing-windcaller
https://www.wowhead.com/npc=3452/serena-bloodfeather

Appear on quest Counterattack! (https://www.wowhead.com/quest=4021/counterattack)
https://www.wowhead.com/npc=9524/kolkar-invader
https://www.wowhead.com/npc=9456/warlord-kromzar

from WoWHead or our Armory

**What is happening:**
Fleeting Plainstrider  appears to be hostile, it's nameplate, unitframe and tooltip while it's behaves like it should be neutral.

The rest of the mobs in the pictures/linked don't scale with your leverls.

**What should happen:**
Fleeting Plaistrider should have neutral nameplate, unitframe and tooltip.

These mobs should scale with you.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
