### ISSUE TITLE
Suramar - Misión - La ultima esperanza de Jandvik 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2680]
**Links:**
https://www.wowhead.com/quest=40927/jandviks-last-hope
from WoWHead or our Armory

**What is happening:**
La mision  reunise con Toryl en la gruta Sashj'Tar
Encontrar con Toryl el credito se completa, vemos Toryl encerrada y Toryl impostora  a la cual se revela su identidad (la maestra de las mareas Sashj'tar) y debemos derrotarla (https://www.wowhead.com/npc=104319/kill-credit-tidemistress-sashjtar)
no se puede derrotar a Toryl (La maestra de las mareas Sashj'tar), se queda con poca vida y sigue golpeando. lo cual la mision no se completa.
![image](https://user-images.githubusercontent.com/81131460/126909260-64955d18-52e0-4933-9173-116ddb2e11a3.png)

**What should happen:**
Al derrotar a la maestra de las mareas Sashj'tar (https://www.wowhead.com/npc=104319/kill-credit-tidemistress-sashjtar), deberia aturdirnos y escapar.
Video de la mision: https://www.youtube.com/watch?v=b_VOKObnBbg

**Comment by Cefiro-Caecias** [comment]
Aacabo de probar dos veces la quest, y me funcionó bien. Cierro Issue o.O
