### ISSUE TITLE
Tormenheim - Misión - Una tarea indigna

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2681]
**Links:**
https://www.wowhead.com/quest=39837/an-unworthy-task
from WoWHead or our Armory

**What is happening:**
al tomar la mision, y el credito de la mision se bugea. me deja entregar la mision.
![image](https://user-images.githubusercontent.com/81131460/126909907-744d588e-579f-4fe0-8174-f36f64655289.png)
![image](https://user-images.githubusercontent.com/81131460/126910066-14f503af-e618-43b1-abe0-2999fb125c1f.png)
![image](https://user-images.githubusercontent.com/81131460/126910072-b7542fff-5fa0-487a-8a01-c8d65e876032.png)

**What should happen:**
la mision pide buscar un espiritu cooperador (https://www.wowhead.com/object=241778/colborns-cage), al encontrarlo, lo liberamos de su celda y el npc caminaria hacia las coordenadas 64.6 43.6 y se estableceria en ese punto donde debemos de entregar la mision con el mismo npc.
video de la mision: https://www.youtube.com/watch?v=e-y77_T2utc

**Comment by Noahkrr** [comment]
el lugar donde estaba la jaula del npc que liberamos, se bugeo hay una mancha luminosa.
![image](https://user-images.githubusercontent.com/81131460/126910147-ec413df3-58cb-4fcc-87e2-745c27eaa1d1.png)

**Comment by Cefiro-Caecias** [comment]
1) https://www.wowhead.com/quest=39837/an-unworthy-task: reparada, aunque más adelante la haré blizzlike.
