### ISSUE TITLE
Fall and die from Beacon

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2683]
**What is happening:**
Able to  take City Center beacon to Hope's Landing beacon.
And then take fall damage and die.
![image](https://user-images.githubusercontent.com/85613053/126914671-a5bb841d-0058-4cc3-8852-7b636af5f614.png)

**What should happen:**
Not be able to teleport like that.
Not take fall damage and die like that.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
