### ISSUE TITLE
mount shop bugs 

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#2685]
following mounts do not perform their /specialmount : 

https://www.wowhead.com/item=54860/x-53-touring-rocket
https://www.wowhead.com/item=49286/x-51-nether-rocket-x-treme
https://www.wowhead.com/item=89363/disc-of-the-red-flying-cloud
https://www.wowhead.com/item=45693/mimirons-head
https://www.wowhead.com/item=143764/leywoven-flying-carpet
https://www.wowhead.com/item=87250/depleted-kyparium-rocket
https://www.wowhead.com/item=87251/geosynchronous-world-spinner
https://www.wowhead.com/item=152842/vibrant-mana-ray
https://www.wowhead.com/item=152840/scintillating-mana-ray
https://www.wowhead.com/item=152844/lambent-mana-ray
https://www.wowhead.com/item=152843/darkspore-mana-ray
https://www.wowhead.com/item=152841/felglow-mana-ray
https://www.wowhead.com/item=138201/fathom-dweller
https://www.wowhead.com/item=142398/darkwater-skate

following mounts do not have the right speed increase : 

https://www.wowhead.com/spell=98718/subdued-seahorse
https://www.wowhead.com/item=142398/darkwater-skate
https://www.wowhead.com/item=138201/fathom-dweller

**Comment by armirmoazezi** [comment]
i forgot to mention the mount "stormcrow" : 
https://www.wowhead.com/item=104011/stormcrow 
when you buy it it doesn't add up to your collection

**Comment by nevarden** [comment]
mana rays dont have their animations in this patch. even their jump animation doesnt exist i believe.

**Comment by Cefiro-Caecias** [comment]
Fixed, available in the next update.
