### ISSUE TITLE
Deliverance Point NPCs

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2686]
**Links:**
https://wowpedia.fandom.com/wiki/Deliverance_Point#Class_specific_NPCs

**What is happening:**
NPCs for other classes and faction show up here even though I'm a horde priest.

**What should happen:**
NPCs for other classes/factions should be phased out.

**Comment by Cefiro-Caecias** [comment]
It will be rebuilt later. Patience.
