### ISSUE TITLE
Commander Chambers/Legionfall Construction Table

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2687]
**Links:**
https://www.wowhead.com/npc=119305/legionfall-construction-table
https://www.wowhead.com/npc=120183/commander-chambers

**What is happening:**
Commander Chambers acts like the Legionfall Construction Table. Legionfall War Supplies contribution goes to him instead of the construction table. He tells you which buildings are active. (Nether Disruptor)
The Legionfall Construction Table constantly shows the all 3 builds Under Attack.
![image](https://user-images.githubusercontent.com/85613053/127036977-d6544f3f-5150-474d-9d65-02187361639d.png)

**What should happen:**
Commander Chambers should provide you a buff based on which building is active.  He should NOT act like the legionfall construction table. 
The Legionfall Construction Table should be where we make contributions and see building progress. 
![image](https://user-images.githubusercontent.com/85613053/127037147-3f0d2f76-a9dd-4439-87ac-619ff177f5e7.png)
https://wow.zamimg.com/uploads/screenshots/normal/614095.jpg

**Comment by Cefiro-Caecias** [comment]
It will be rebuilt later. Patience.
