### ISSUE TITLE
Breaching the Tomb Quest Sequence

### ISSUE THREAD

**Issue by IntroverseLaw** [GuabinaCore/WoWKoi#2688]
**Links:**

https://www.wowhead.com/achievement=11546/breaching-the-tomb
https://www.wowhead.com/quest=46247/defending-broken-isles
https://www.wowhead.com/quest=47137/champions-of-legionfall

**What is happening:**

Currently, the quest [Champions of Legionfall] is avaible as soon as you complete the Broken Shore scenario, and [Defending Broken Isles] once you complete [Begin Construction].

![breachingtomb](https://user-images.githubusercontent.com/87998390/127038819-5402af20-9c8e-4aab-b23d-812011c4ba16.png)

**What should happen:**

Each chapter of this achievement matches a respective quest, given one by one upon the completion of the previous quest. More especifically Champions of Legionfall, it is required that you complete the class hall campaign for this quest to be up. It definitely shouldn't be avaible right away once you get to Broken Shore.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
