### ISSUE TITLE
[Tyce] - Shadow Priest - Mind Blast CD entering/leaving Voidform

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2689]
**Links:**
https://www.wowhead.com/spell=8092/mind-blast
https://www.wowhead.com/spell=228264/voidform#changelog
https://www.wowhead.com/item=132864/mangazas-madness

**What is happening:**
I noticed while using Mangaza's Madness gaining an additional Mind Blast upon entering voidform, and ocasionally losing a charge upon leaving voidform.

![WoWScrnShot_072621_123723](https://user-images.githubusercontent.com/85613053/127041115-0e41751e-7761-4ab8-af14-39facd194037.jpg)
1.  Before entering Void Form, Mind Blast has 0 charges and less than 3 seconds remaining before getting 1 charge.
![WoWScrnShot_072621_123725](https://user-images.githubusercontent.com/85613053/127041120-e80f2129-3dc2-462c-b66f-8ba50ceb4661.jpg)
2. After entering Void Form, Mind Blast has 1 charge and less than 1 second remaining before getting 2 charges.

**What should happen:**
No refunds of the timer on Mind Blast, just a reduction of cooldown on Mind Blast and re-adjustment of the current rolling timer to be equal to the original percentage of the timer before the reduction. 
Idk math so idk how to explain, but I shouldn't have Mind Blast back to max charges like that.

**Comment by nevarden** [comment]
This bug also affects you upon leaving form. The cooldown gets changed after Void Form ends, leaving you with a "no charges" error message when casting the mind blast that you should have.

**Comment by Arkanheal** [comment]
Do you have an update on this @nevarden ?
