### ISSUE TITLE
[Arthas] - Quest: Got Wood?, Id: 13628

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#269]
**Links:**
https://www.wowhead.com/quest=13628/got-wood
from WoWHead or our Armory

**What is happening:**
The kodo 4/5 times stops after doing the jump smash attack on the attackers. If you relog, abandon and do the quest again, it may stop again or it may not. It's a bit frustrating

**What should happen:**
It should continue moving after doing that attack.

**Comment by LKArthas** [comment]
Fixed Yesterday
