### ISSUE TITLE
[Tyce] - Holy Priest: Guardian Angel Talent

### ISSUE THREAD

**Issue by IntroverseLaw** [GuabinaCore/WoWKoi#2690]
**Links:**

https://www.wowhead.com/spell=47788/guardian-spirit#changelog
https://www.wowhead.com/spell=200209/guardian-angel#changelog

**What is happening:**

At the moment, the talent Guardian Angel is reducing the cooldown of Guardian Spirit to 1 minute and 30 seconds (a total of 140 seconds, discounting the buff duration before expiring).

![a](https://user-images.githubusercontent.com/87998390/127047897-e4223fe0-bfb2-4ff1-b66a-6f72bab0d3bc.png)
![b](https://user-images.githubusercontent.com/87998390/127047907-e77ff99f-7451-4025-8cdd-4b8e4aa692a8.png)

**What should happen:**

The cooldown of Guardian Spirit should be reduced to 2 minutes and 20 seconds once the Guardian Angel condition is met. Keep in mind I'm considering patch 7.1.0 Build 22758 for Guardian Spirit and patch 7.1.0 Build 22864 for Guardian Angel, as those are the latest changes for each of them in the expansion. Even if they aren't the patches you're currently using, the cooldown reduction is way above any present in legion builds.

**Comment by Arkanheal** [comment]
Do you have an update on this @IntroverseLaw ?
