### ISSUE TITLE
Return to Karazhan Storyline

### ISSUE THREAD

**Issue by IntroverseLaw** [GuabinaCore/WoWKoi#2691]
**Links:**

https://www.wowhead.com/storyline/return-to-karazhan-294
https://www.wowhead.com/quest=45422/edict-of-the-god-king

**What is happening:**

The storyline quests are avaible all at once. There's no sequence from one quest to another, and you can just get the last one, skipping everything else.

![karazhan1](https://user-images.githubusercontent.com/87998390/127050279-bd49a65b-6989-4acc-8b04-dce35eb7ebec.png)
![karazhan2](https://user-images.githubusercontent.com/87998390/127050286-b9906a7e-fe7d-46db-9660-ff56dbf3ea74.png)

**What should happen:**

The quests should be unlocked as the player completes the previous one, since it is a storyline.

**Comment by Cefiro-Caecias** [comment]
Fixed.
