### ISSUE TITLE
[Tyce] - Imposible recolectar MAtojo vil

### ISSUE THREAD

**Issue by MatiasSparda** [GuabinaCore/WoWKoi#2694]
No se me permite recolectar el matojo vil de la mision de mundo ya que indica que no tengo herboristeria cuando la tengo al maximo como se puede ver en la imagen
![image](https://user-images.githubusercontent.com/47328328/127234494-1b9cdba7-6c62-4980-a9de-102b5e3834e8.png)

**Comment by MatiasSparda** [comment]
El problema como se puede ver en la imagen, es que al subir la profesion desde el shop no te da la habilidad de recolectar plantas, solo los conocimientos.

**Comment by ShikoSCS** [comment]
¿Una pregunta, cuando usted compró la profesión le subió a 800 al momento? Para ser mas exacto, necesito saber si compro la profesión recientemente después de los cambios que hicimos en la tienda.

**Comment by MatiasSparda** [comment]
Hola Shiko, por favor no me trate de usted aunque gracias por la formalidad, La profesion subio al maximo al momento pero el matojo vil no me dejaba recolectarlo. Esto sucedio el mismo dia que hice el post es decir el 28 de julio, con lo que si se hicieron cambios recientes en la tienda es anterior a esto

**Comment by MatiasSparda** [comment]
De hecho, casi se me olvida y lo recorde viendo la imagen, como se puede apreciar solo aparece en el menu de profesiones las habildiades de herboristeria pero tambien deberia de aparecer la habilidad de recolectar plantas, como se peude ver en la primera imagenno aparece
![image](https://user-images.githubusercontent.com/47328328/133432253-cbbc0b0b-c355-4e8c-b688-1ae7c87f2f4d.png)

**Comment by MatiasSparda** [comment]
Esto está solved fue solo en la beta, voy a cerrarlo
