### ISSUE TITLE
Rey Morgalash - Rare - Suramar

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2695]
**Links:**

from WoWHead or our Armory

**What is happening:**
Al usar el estandarte de Jandvik , no invoca adds y al rare Rey Morgalash (https://www.wowhead.com/npc=103827/king-morgalash).

**What should happen:**
Se invoca al rey Morgalash (https://www.wowhead.com/npc=103827/king-morgalash) haciendo clic en el estandarte de Jandvik (https://www.wowhead.com/npc=103467/jandvik-banner) en la playa del este. 

Hay algunas oleadas de adiciones que se generan después de hacer clic en el banner (las dos primeras están compuestas por 3-4 mobs), una combinación de Sashj'tar Wave Crusher (https://www.wowhead.com/npc=103930/sashjtar-wave-crusher), Sashj'tar Wave Breaker (https://www.wowhead.com/npc=103929/sashjtar-wave-breaker) y Sashj'tar Wave Caller (https://www.wowhead.com/npc=103929/sashjtar-wave-breaker), seguido por dos Elder Trenchwalker (https://www.wowhead.com/npc=103932/elder-trenchwalker) y finalmente el propio Rey Morgalash (https://www.wowhead.com/npc=103827/king-morgalash).

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
