### ISSUE TITLE
[Tyce] - Trinket - Sheath of Asara

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2698]
**Links:**
https://www.wowhead.com/item=151971/sheath-of-asara
https://www.wowhead.com/spell=255857/shadow-blades
https://www.wowhead.com/spell=253263/shadow-blades
https://www.wowhead.com/spell=255856/shadow-blades
https://www.wowhead.com/spell=255818/unknown-spell
![image](https://user-images.githubusercontent.com/85613053/127431231-b1b96c0d-dc11-40cc-bd71-fef1dd2648b6.png)

**What is happening:**
Sheath of Asara procs but fades away a second later. Does no damage or anything.

**What should happen**
Function pls.

**Comment by Arkanheal** [comment]
Added in 7.3. Low prio for now
