### ISSUE TITLE
Campaña de Chaman - La gran Madre Pétrea

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2699]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=41775/the-great-stonemother
al tomar la misión, nos pide ir a hablar con Therazane en Infralar, uso el portal de la sede hacia Infralar, cuando llego a Infralar el NPC (https://www.wowhead.com/npc=42465/therazane) con quien debo charlar y entregar la misión no esta.

**Comment by Cefiro-Caecias** [comment]
En revisión.
