### ISSUE TITLE
¡Haz la cosa! - Mglrgrs de nuestros grmlgrlr - Suramar

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2701]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=42396/do-the-thing
la mision se autocompleta, deberia poder completar los creditos antes..
video de la mision: https://www.youtube.com/watch?v=60Zulaoyp7c

https://www.wowhead.com/quest=41143/mglrgrs-of-our-grmlgrlr
la mision se autocompleta, deberia completar primero los creditos para que se complete la mision y el murlock (https://www.wowhead.com/npc=107302/pearlhunter-phin) deberia seguirnos en la mision.
![image](https://user-images.githubusercontent.com/81131460/127727151-0a313a5d-e0ef-4c05-9342-5bed33c8f7d9.png)
video de la mision: https://www.youtube.com/watch?v=udH4s7eknZw

**Comment by Cefiro-Caecias** [comment]
Reparadas. Disponibles en el próximo update.
