### ISSUE TITLE
Dalaran - Misiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2702]
**Links:**

from WoWHead or our Armory

**What is happening:**
Misiones faltantes

1- https://www.wowhead.com/quest=44009/a-falling-star
2- https://www.wowhead.com/quest=44004/bringer-of-the-light

https://www.wowhead.com/quest=43705/nobundos-last-stand (mision secundaria)
esta mision esta bug, se autocompleta sin ganar creditos.
![image](https://user-images.githubusercontent.com/81131460/127798768-f0781fc6-7d07-43ae-9f47-42f13cac40f9.png)
![image](https://user-images.githubusercontent.com/81131460/127798813-200ef7f6-491d-4d17-90e1-e8c3909d1648.png)

3- https://www.wowhead.com/quest=44153/lights-charge
4- https://www.wowhead.com/quest=44338/goddess-watch-over-you (requerimiento 110)
5- https://www.wowhead.com/quest=44448/in-the-house-of-light-and-shadow
6- https://www.wowhead.com/quest=44464/awakenings
7- https://www.wowhead.com/quest=44466/an-unclear-path
8- https://www.wowhead.com/quest=44479/ravencrests-legacy

https://www.wowhead.com/quest=44414/felspawns-of-lothros (mision secundaria)
https://www.wowhead.com/quest=44415/the-red-axe (mision secundaria)
https://www.wowhead.com/quest=44416/hunter-of-night (mision secundaria)

9- https://www.wowhead.com/quest=44480/in-my-fathers-house

10- https://www.wowhead.com/quest=44481/destiny-unfulfilled

https://www.wowhead.com/quest=44497/destiny-unfulfilled  (solo si eres cazador de demonios)

11- https://www.wowhead.com/quest=45174/the-hunt-for-illidan-stormrage
12- https://www.wowhead.com/quest=45175/soul-prism-of-the-illidari
13- https://www.wowhead.com/quest=45176/trial-of-valor-the-once-and-future-lord-of-shadows
14- https://www.wowhead.com/quest=45177/the-nighthold

**What should happen:**

**Comment by Noahkrr** [comment]
estas misiones es necesaria para todas las clases, excepto los Paladines, ya que ellos tienen su propia cadena
 de misiones para obtener "el corazón de la luz"..

**Comment by Cefiro-Caecias** [comment]
Reparado.

**Comment by Noahkrr** [comment]
estas misiones desbloquean un logro y una apariencia del arma artefacto para cada clase. actualmente solo funciona en los Paladines (estas misiones forman parte exclusiva de sus misiones de campaña) y las misiones del informe, son una cadena de misiones que abarca para todas las clases, por favor no confundir con las misiones del paladin que son similares.. pero tienen la misma finalidad
