### ISSUE TITLE
[Tyce] - Trinkets: Eye of F'harg / Shatug

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2704]
**Links:**
https://www.wowhead.com/item=153544/eye-of-fharg
https://www.wowhead.com/item=152645/eye-of-shatug

**What is happening:**
Equip effect doesn't work.
Use effect doesn't swap the ring.

**What should happen:**
Equip effect should provide a buff to the other tank.
Use effect should change the trinket equipped into the other trinket.

**Comment by Arkanheal** [comment]
7.3 item so putting in low prio
