### ISSUE TITLE
mount bug 

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#2705]
following mounts  in shop add "savage raptor" instead of the correct mount : 
https://www.wowhead.com/item=64883/scepter-of-azjaqir
https://www.wowhead.com/item=69224/smoldering-egg-of-millagazor
they give : 
https://www.wowhead.com/item=69228/savage-raptor

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update :D
