### ISSUE TITLE
Suramar - NPC - Resguardo Arcano

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2706]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=41149/a-re-warding-effort
la mision funciona correctamente, el problema es que NPC(https://www.wowhead.com/npc=109022/arcane-ward) que inicia la mision, no tiene modelo en el juego.
![image](https://user-images.githubusercontent.com/81131460/127751049-1b21bf09-b0fa-4bb9-8427-a68dd21b227a.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Reparado, y también reparé la quest, porque estaba horrible. Disponible en el próximo update.
