### ISSUE TITLE
Coilskar Harpooner NPC standing still doing nothing DH starting zone.

### ISSUE THREAD

**Issue by Sariet** [GuabinaCore/WoWKoi#2707]
![image](https://user-images.githubusercontent.com/88337786/127894969-8d5bed78-0c94-45f0-9f67-941c621fa2ea.png)

Edit: This would include all the Coilskar Harpooner's in the area + the Illidari Demon Hunters.
Coilskar Harpooner is not hitting mobs so the 7 mobs that are around him will hit you 3 times each resulting in a quick death not instant.

Coilskar Harpooner should be hitting the mobs ;)

**Comment by Cefiro-Caecias** [comment]
Arthas is already rebuilding the area. Patience ^^
