### ISSUE TITLE
[Wotlk][Zone][Alliance] Grizzly Hills - complete report

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2708]
**Links:**

https://www.wowhead.com/grizzly-hills
 ---

---
1. 
 - [ ] NPC - [Arcturis](https://www.wowhead.com/npc=38453/arcturis)
     - NPC is lvl110 in lvl80 zone.
---
2. 
 - [ ] [The Thane of Voldrune](https://www.wowhead.com/quest=12255/the-thane-of-voldrune)
     - [Flamebringer](https://www.wowhead.com/npc=27292/flamebringer) vehicle doesn't work. Clicking on it doesn't do anything.
---
3. 
 - [ ] NPC - [Grizzly Bear](https://www.wowhead.com/npc=27131/grizzly-bear)
     - NPC doesn't attack.
---
4. 
 - [ ] Quest - [Seared Scourge](https://www.wowhead.com/quest=12029/seared-scourge)
     - There should be more npc in the questing area. Currently it's very tedious to complete the quest.
     - [Mack Fearsen](https://www.wowhead.com/npc=26604/mack-fearsen)'s dialogue option doesn't give [Mack's Dark Grog](https://www.wowhead.com/item=35908/macks-dark-grog)
---
5. 
 - [ ] Quest - [Escape from Silverbrook](https://www.wowhead.com/quest=12308/escape-from-silverbrook)
     - Escorting path is scuffed but it eventually gets you to the destination, so, I guess it can be ignored.
     - Completion credit is not granted after arriving to the destination.
---
6. 
 - [ ] NPC - [Drakkari Shaman](https://www.wowhead.com/npc=26447/drakkari-shaman) and [Drakkari Warrior](https://www.wowhead.com/npc=26425/drakkari-warrior)
     - [Frozen Mojo](https://www.wowhead.com/item=35799/frozen-mojo) doesn't drop. According to WowHead, it's 60% droprate. I've killed 20 trolls so far, 0 dropped.
---
7. 
 - [ ] Quest - [Scourgekabob](https://www.wowhead.com/quest=12484/scourgekabob)
     - Objeect [Scourged Troll Mummy](https://www.wowhead.com/object=190223/scourged-troll-mummy) is empty. Should contain item [Scourged Troll Mummy](https://www.wowhead.com/item=38149/scourged-troll-mummy)
---
8. 
 - [ ] Quest - [Dun-da-Dun-tah!](https://www.wowhead.com/quest=12082/dun-da-dun-tah)
     - Completion credit is not granted after finishing the escort. **EDIT: This quest was completed for my by a GM and after a couple of seconds the quest turned back to incomplete. Might it be a core issue, since, other smiliar quests behave the same way** #2740 
---
9. 
 - [ ] Quest - [Rallying the Troops](https://www.wowhead.com/quest=12070/rallying-the-troops)
     - [Shard of the Earth](https://www.wowhead.com/item=36764/shard-of-the-earth) doesn't work
---
10. 
 - [ ] Quest [Steady as a Rock?](https://www.wowhead.com/quest=12014/steady-as-a-rock)
     - [Portable Seismograph](https://www.wowhead.com/item=35837/portable-seismograph) doesn't do anything.
---
11. 
 - [ ] Quest - [Anatoly Will Talk](https://www.wowhead.com/quest=12330/anatoly-will-talk)
     - [Tatjana](https://www.wowhead.com/npc=27627/tatjana) should be riding [Tatjana's Horse](https://www.wowhead.com/npc=27626/tatjanas-horse), instead of walking around separately. 
     - Using [Tranquilizer Dart](https://www.wowhead.com/item=37665/tranquilizer-dart) doesn't work. After using [Tranquilizer Dart](https://www.wowhead.com/item=37665/tranquilizer-dart), [Tatjana's Horse](https://www.wowhead.com/npc=27626/tatjanas-horse) should become a vehicle.
---
12. 
 - [ ] Quest - [Chill Out, Mon](https://www.wowhead.com/quest=12137/chill-out-mon)
     - [Snow of Eternal Slumber](https://www.wowhead.com/item=36859/snow-of-eternal-slumber) doesn't grant quest credits when used
---
13. 
 - [ ] [The Captive Prospects](https://www.wowhead.com/quest=12180/the-captive-prospectors)
     - Using [Dun Argol Cage Key](https://www.wowhead.com/item=37013/dun-argol-cage-key) on Dun Argol Cage( I didn't manage to find the ID) doesn't grant credits.
---
14. 
 - [ ] Quest - [Ursoc, the Bear God](https://www.wowhead.com/quest=12249/ursoc-the-bear-god#)
     - Using [Purified Ashes of Vordrassil](https://www.wowhead.com/item=37307/purified-ashes-of-vordrassil) on [Ursoc](https://www.wowhead.com/npc=26633/ursoc)'s corpse says "You can't do it right now". Unable to complete the quest.
---
15. 
 - [ ] Quest - [Hour of the worg](https://www.wowhead.com/quest=12164/hour-of-the-worg)
     - [Shade of Argul](https://www.wowhead.com/npc=27018/shade-of-arugal-defeated) is surrounded by 5 [Bloodmoon Cultist](https://www.wowhead.com/npc=27024/bloodmoon-cultist). Instead, he should start an event, where he summons his troops. (Since it's old content, maybe just make him tank and spank) 
     - [Shade of Argul](https://www.wowhead.com/npc=27018/shade-of-arugal-defeated) casts [Worgen's Command](https://www.wowhead.com/spell=53070/worgens-command), making it impossible to solo kill.
---
16. 
 - [ ] Quest - [Looking the Part](https://www.wowhead.com/quest=12183/looking-the-part)
     - [Overseer's Uniform](https://www.wowhead.com/item=37035/overseers-uniform) dropped after 3 kills, there are no comments on WoWhead concerning low drop rate.
---
17. 
 - [ ] Quest [Cultivating an Image](https://www.wowhead.com/quest=12184/cultivating-an-image)
     - Using [Kilian's Camera](https://www.wowhead.com/item=37045/kilians-camera) on copses doesn't grant credits.
---
18. 
 - [ ] Quest - [We Have Power](https://www.wowhead.com/quest=12131/we-have-the-power#comments)
     - [Rune-Smith Durar](https://www.wowhead.com/npc=26409/rune-smith-durar) and [Rune-Smith Kathorn](https://www.wowhead.com/npc=26410/rune-smith-kathorn) drop their quest item after 3-4 kills. WoWhead comments don't indicate low drop rate.
     ---
19. 
 - [ ] Quest - [The Iron Thane and His Anvil](https://www.wowhead.com/quest=12153/the-iron-thane-and-his-anvil)
     - [Charged War Golem](https://www.wowhead.com/npc=29005/charged-war-golem#abilities) is missing ablilities.
     - [Iron Thane Furyhammer](https://www.wowhead.com/npc=26405/iron-thane-furyhammer) is no spawned in the designated area.
---
20. 
 - [ ] NPC
     -
---
21. 
 - [ ] NPC
     -
---
22. 
 - [ ] NPC
     -
---
23. 
 - [ ] NPC
     -
---
24. 
 - [ ] NPC
     -

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
