### ISSUE TITLE
[Quest] Stormheim

### ISSUE THREAD

**Issue by IntroverseLaw** [GuabinaCore/WoWKoi#2709]
**Links:**

https://www.wowhead.com/quest=39864/stormheim

**What is happening:**

The objective counter shows weird numbers once you get to the Violet Citadel.
![bugkoi](https://user-images.githubusercontent.com/87998390/128264267-6ffce14c-d4c7-4f85-8cfd-0ce1ff6e1452.png)

**What should happen:**

The objective counter should show "Travel to Dalaran: 1/1" once properly accomplished.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
