### ISSUE TITLE
Ashenvale Stalker Level scaling

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#271]
**Links:**
https://imgur.com/a/POjPQcK
https://www.wowhead.com/npc=33458/ashenvale-stalker
https://www.wowhead.com/quest=13640/management-material
from WoWHead or our Armory

**What is happening:**
This mob appears when you order a Demoralized Peon to cut you wood for the quest Management Material and appears to not be scaled to your level.

**What should happen:**
The mob should be level scaling.

**Comment by LKArthas** [comment]
Fixed for next update
