### ISSUE TITLE
[Tyce] - Discipline/Holy Priest: Leap of Faith

### ISSUE THREAD

**Issue by IntroverseLaw** [GuabinaCore/WoWKoi#2710]
**Links:**

https://www.wowhead.com/spell=73325/leap-of-faith

**What is happening:**

The spell doesn't do anything when I use on any party/raid member.

**What should happen:**

I should <s> become Scorpion and get them over here </s>  bring the targeted ally to my side.

**Comment by Arkanheal** [comment]
Do you have an update on this issue @IntroverseLaw ?
