### ISSUE TITLE
Prio list of issue's that need fix pre-release.

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#2711]
Post the link's of the bugreport on Discord /off-topic/ .After review we gonna decide if gonna add it here or not.

**Comment by Cefiro-Caecias** [comment]
Try to post here as I have so much work on repairs that I hardly check Discord :D

**Comment by NightwindOI** [comment]
https://github.com/GuabinaCore/WoWKoi/issues/2710
https://github.com/GuabinaCore/WoWKoi/issues/2690
https://github.com/GuabinaCore/WoWKoi/issues/2313
https://github.com/GuabinaCore/WoWKoi/issues/2640
https://github.com/GuabinaCore/WoWKoi/issues/2672
https://github.com/GuabinaCore/WoWKoi/issues/2729
