### ISSUE TITLE
Ancient Mana Basin / Mana Catalyst

### ISSUE THREAD

**Issue by IntroverseLaw** [GuabinaCore/WoWKoi#2712]
**Links:**

https://www.wowhead.com/item=141296/ancient-mana-basin
https://www.wowhead.com/spell=225818/mana-catalyst

**What is happening:**

The toy properly creates the mana basin for 2min, but interacting with it doesn't give you mana catalyst.
![manaBasin](https://user-images.githubusercontent.com/87998390/128398775-e61ecfa2-17aa-4fd3-ad1a-a14f67dfe140.png)

**What should happen:**

By clicking on the mana basin, the player should receive Mana Catalyst, that once used gives a buff for 50% increased effects of Suramar magical foods and mage conjured food and drink. This is relevant because the 50% increased mana regeneration from mage food makes a huge diffference in mythic+ runs.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
