### ISSUE TITLE
[The Dreamgrove] Raider's Training Dummy

### ISSUE THREAD

**Issue by IntroverseLaw** [GuabinaCore/WoWKoi#2714]
**Links:**

https://www.wowhead.com/npc=113964/raiders-training-dummy
https://www.wowhead.com/spell=167381/dummy-strike
https://www.wowhead.com/spell=167385/uber-strike

**What is happening:**

The dummy doesn't do anything.

**What should happen:**

Once in combat, it should use its abilities to damage the player. It's supposed to be a training dummy for tanks.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
