### ISSUE TITLE
NPC - Sujeto de prueba marchitos - Suramar

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2715]
**Links:**
https://www.wowhead.com/npc=109188/withered-test-subject
from WoWHead or our Armory

**What is happening:**
he visto varios npc con esta misma forma, los gigantes no puedo seleccionarlo y tampoco puedo atacar a los npc con este modelo , creo q es un error de modelo o algo
![image](https://user-images.githubusercontent.com/81131460/128557393-1a1d8431-d304-4b2c-bfc5-89354ecb2133.png)

**Comment by Cefiro-Caecias** [comment]
En realidad era una flag defectuosa en el campo unit_flags de creature_template. Ambos mobs reparados. Disponible en el próximo update ^^
