### ISSUE TITLE
NPC - Castigaelfos - Suramar

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2716]
**Links:**
https://www.wowhead.com/npc=99792/elfbane
from WoWHead or our Armory

**What is happening:**
el npc no se mueve ni ataca, esta inmovil incluso cuando esta siendo atacado
![image](https://user-images.githubusercontent.com/81131460/128558828-620d2c05-f4c3-4140-9f07-ff985caee71b.png)

**Comment by LKArthas** [comment]
Fixed Today
