### ISSUE TITLE
Misiones de Minería - parte 1

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2717]
**Links:**

from WoWHead or our Armory

**What is happening:**
bug visual, no aparece en el mapa donde esta la ubicacion del npc (https://www.wowhead.com/npc=93691/ronos-ironhorn) para entregar estas misiones:

https://www.wowhead.com/quest=38789/rethus-journal
https://www.wowhead.com/quest=38790/rethus-pick
https://www.wowhead.com/quest=38791/rethus-horn

**What should happen:**
deberia aparecer un signo (?) en el mapa para saber la ubicacion del npc, para entregar las misiones

**Comment by Cefiro-Caecias** [comment]
Reparado, junto con el resto de quests de Minería de Legion. Disponibles en el próximo update.
