### ISSUE TITLE
Misiones de Minería - parte 2

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2718]
**Links:**

from WoWHead or our Armory

**What is happening:**
al picar un nodo de (Deposito de piedra ley o Veta de piedra ley) o  invoca al npc (https://www.wowhead.com/npc=93735/rethu-ironhorn), el problema es que me da las misiones de deposito de piedra ley, veta de piedra ley y deposito viviente de piedra ley. cuando diferente versiones de Rethu cuerno ferreo deberia darnos la misiones de cada nodo deposito, veta y piedra viviente
![image](https://user-images.githubusercontent.com/81131460/128610994-b812ba44-342f-4ddf-b793-7c0e13888669.png)
![image](https://user-images.githubusercontent.com/81131460/128612183-48c3a2f7-5b34-426d-85a2-da59edbbb039.png)
en conclusión, si picas deposito o veta de piedra ley invocas al mismo npc (https://www.wowhead.com/npc=93735/rethu-ironhorn) que da la misiones de los nodos de Deposito de piedra ley, Veta de piedra ley y Piedra ley viviente. en el caso de los nodos vivientes, no se invoca nada.

Extra: al picar el primer nodo de piedra ley o veta de piedra ley se invoca al npc. deberia funcionar con porcentaje para que se logre invocar al npc. Estaría bien un 10% de chance de invocar al npc.

**What should happen:**
cuando deberia  funcionar de esta manera:
- picas un nodo de Deposito de piedra ley invoca (https://www.wowhead.com/npc=93735/rethu-ironhorn) que nos da la mision (https://www.wowhead.com/quest=38792/rethus-lesson)
- picas un nodo de Veta de piedra ley invoca (https://www.wowhead.com/npc=93743/rethu-ironhorn) que nos da la mision (https://www.wowhead.com/quest=38793/rethus-experience)
- picas un nodo viviente (basiliskos, gusanos de piedra ley, elemental de marea, etc) invoca a (https://www.wowhead.com/npc=93744/rethu-ironhorn) y nos da la mision (https://www.wowhead.com/quest=38794/rethus-sacrifice)

**Comment by Cefiro-Caecias** [comment]
Reparadas. Disponibles en el próximo update.
