### ISSUE TITLE
3 Flight paths unlocked without me visiting them ever.

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#272]
**Links:**
Edit: https://imgur.com/a/wRbKFbz
from WoWHead or our Armory

**What is happening:**
Mulgore, Thunder Bluff and Moonglade flight paths are unlocked for me (playing a Troll Shaman atm) without ever visiting that locations.

**What should happen:**
They should not be unlocked without me visiting the flight masters of each location.

**Comment by cyberfreak666** [comment]
normaly mulgore and thunderbluff would be unlocked if your a tauren but that might be changed since in cata they buildt a wall that closed off ground routes to mulgore so to get there you need to take a ziplin or fly there.  Not sure about moonglade that is normaly only unlocks for druids

**Comment by Spewee** [comment]
Mulgore and Durotar flight paths are unlocked by default. Only Moonglade shouldn't be unlocked.
