### ISSUE TITLE
[Neltharion's Lair] No Exit

### ISSUE THREAD

**Issue by IntroverseLaw** [GuabinaCore/WoWKoi#2720]
**Links:**

https://www.wowhead.com/neltharions-lair

**What is happening:**

There's no exit at the end of the dungeon.
![WoWScrnShot_080721_224253](https://user-images.githubusercontent.com/87998390/128618112-dca23874-26ad-425a-ad0d-f795374e97ce.jpg)
![mapNL](https://user-images.githubusercontent.com/87998390/128618116-0d69e5e5-1e4e-4749-96b3-c35d148ad739.jpg)

**What should happen:**

there should be a portal that takes the player out of the dungeon in this location.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
