### ISSUE TITLE
[Tyce] - Priest: Can't jump while under effect of levitate.

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2721]
**Links:**
https://wowpedia.fandom.com/wiki/Patch_7.3.0_(undocumented_changes)

**What is happening:**
Unable to jump while levitating.

**What should happen:**
Should be able to jump while levitating.

"Players can now jump while under the effect of a priest's [Levitate]."

**Comment by Arkanheal** [comment]
Closing as it's not current content.
