### ISSUE TITLE
[Neltharion's Lair] Stolen Skyhorn Goods

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2723]
**Links:**
https://www.wowhead.com/object=253999/stolen-skyhorn-goods
https://www.youtube.com/watch?v=5Z5wj2I_CF0&t=41s

**What is happening:**
The hidden chest in the tunnel of Naraxas is missing.

**What should happen:**
One of the stolen goods is in the shaft immediately after you defeat the worm boss Naraxas. In the tunnel under his corpse, there is a small opening in the side. When you interact with the chest it will knock the chest down and you can then loot it at the bottom. This does not show up in mini-map until it's knocked down.

**Comment by Cefiro-Caecias** [comment]
Unreproducible animation for the moment.
