### ISSUE TITLE
[Cosmetic] Perky Pug costumes

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2724]
**Links:**
![WoWScrnShot_080821_171250](https://user-images.githubusercontent.com/85613053/128648487-769fc621-3044-46f7-85a1-164872e41a0c.jpg)
![image](https://user-images.githubusercontent.com/85613053/128648584-96fcbba8-3a41-481c-a138-6bdeb1df8c54.png)
https://www.wowhead.com/spell=148244
https://www.wowhead.com/spell=148206
https://www.wowhead.com/spell=148246
https://www.wowhead.com/spell=171470
https://www.wowhead.com/spell=171479
https://www.wowhead.com/spell=171930

**What is happening:**
Able to apply costumes meant for only perky to any NPC.

**What should happen:**
Only be able to use the cosmetics on the specified NPC.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
