### ISSUE TITLE
Val'sharah - Mision - Atracador de Luna / item - Restos Grotescos

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2725]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/item=138441/grotesque-remains
este item no cae, parece que no esta en el juego o tiene un drop muy bajo, pueden verificar
el drop de caida es 5% del npc (https://www.wowhead.com/npc=108327/undulating-boneslime)

https://www.wowhead.com/quest=42751/moon-reaver
no puedo obtener esta mision.. 
el NPC que otorga la mision es (https://www.wowhead.com/npc=108304/guviena-bladesong)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
En efecto, el item no existe en la DB. Para solventar este defecto, cuando mates a cualquier Baba de hueso ondulante, Lechubestia con manía lunar o Lechubestia alunada, tendrás un 50% de chance de recibir automáticamente la quest en tu diario de misiones. Disponible en el próximo update.
