### ISSUE TITLE
Item - NPC - No estan en el juego

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2726]
**Links:**

from WoWHead or our Armory

**What is happening:**
No estan en el juego ... segun reportes no estan en la base de datos los siguentes items y npc:
https://www.wowhead.com/item=138441/grotesque-remains
https://www.wowhead.com/npc=119990/fenryr
https://www.wowhead.com/npc=104220/starving-ettin

**Comment by Cefiro-Caecias** [comment]
1) Grotesque Remains: aunque el item no existe en la Database, diseñé un fix mediante el cual ontienes la quest, al matar a cualquiera de los 3 mobs que deberían dropearlo.

2) Fenryr y Starving Ettin sí existen en la Database. El segundo es perfectamente matable ^^

**Comment by Noahkrr** [comment]
el fenryr mencionado aqui, es el fenryr tameable por los cazadores y no se puede obtener ya no aparece en la cueva
los otros items no estan en el juego, este hilo se creo para reunir todos items, npc que no esten en el juego..
