### ISSUE TITLE
Val'sharah - NPC - Misiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2728]
**Links:**
https://www.wowhead.com/npc=92326/shimmering-oleander
from WoWHead or our Armory

**What is happening:**
los npc no puedo seleccionarlos con el tabulador, y tengo que hacer click en ellas, parecen muertas en la forma en que se mueven.

https://www.wowhead.com/quest=42857/moist-around-the-hedges
esta mision pide recolectar 5 (https://www.wowhead.com/item=138788/moist-grizzlecomb) pero su drop es muy bajo que demore 30 minutos para completarlo la primera vez, ahora no puedo completarla, creo q se ha dañado

**Comment by Noahkrr** [comment]
Ambas misiones son clasificadas como obsoletas segun wowhead . deberian ser retiradas
https://www.wowhead.com/quest=41891/tainted-growth
https://www.wowhead.com/quest=38688/hope-remains

**Comment by Noahkrr** [comment]
https://es.wowhead.com/quest=38643/una-aldea-en-peligro
esta mision es para los hordas, yo soy alianza no deberia poder tomarla

**Comment by Noahkrr** [comment]
https://www.wowhead.com/item=127860/wardens-signet
este item deberia ser dropeado por el npc (https://www.wowhead.com/npc=94366/lelyn-swiftshadow), tiene un 77.19% de caida.

**Comment by Cefiro-Caecias** [comment]
1) https://www.wowhead.com/npc=92326/shimmering-oleander:  reparado.
2) https://www.wowhead.com/quest=42857/moist-around-the-hedges: reparado.
3) https://www.wowhead.com/quest=41891/tainted-growth: reparado.
4) https://www.wowhead.com/quest=38688/hope-remains: reparado.
5) https://es.wowhead.com/quest=38643/una-aldea-en-peligro: hay dos misiones con el mismo nombre, y son para ambas facciones; ambas quests son mutuamente excluyentes, y al tomar una, la otra se deshabilita. No poseen restricción de facción.
6) https://www.wowhead.com/item=127860/wardens-signet: el item no existe en la Database, así que a partir de ahora, al matar a Lelyn Swiftshadow, te dará automáticamente la quest del item.

Todo disponible en el próximo update.
