### ISSUE TITLE
Tormenheim - NPC 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2730]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=91069/forsaken-dreadwing
no se puede atacar
![image](https://user-images.githubusercontent.com/81131460/128958188-fef4b9b1-0417-41a8-bef8-866b312daaa1.png)

https://www.wowhead.com/npc=90899/forsaken-bat-rider
el modelo de NPC deberia estar sin murcielago, al estar en el aire deberia estar con el murcielago y cuando aterriza al suelo el murcielago desaparece..
![image](https://user-images.githubusercontent.com/81131460/128958687-5bb5a291-ea21-4a16-8d2a-3fddb38cec54.png)

https://www.wowhead.com/npc=90903/adolescent-storm-drake
no deberia dar reputacion
![image](https://user-images.githubusercontent.com/81131460/128960557-dffbe6c2-fc87-4cb0-aaa2-96a238e18da7.png)

https://www.wowhead.com/npc=92415/storm-drake-whelp
no deberia dar reputacion
![image](https://user-images.githubusercontent.com/81131460/128960780-9489a856-4f4d-4646-9b51-8a14039fc78a.png)

**What should happen:**

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=14881/spider
no deberia dar reputacion
![image](https://user-images.githubusercontent.com/81131460/129089603-09201da8-07ba-4874-a448-28472c21c504.png)

https://www.wowhead.com/item=128512/challengers-tribute
este item al hacer click inicia esta mision(https://www.wowhead.com/quest=39595/blood-and-gold)
una vez completada la mision este item(https://www.wowhead.com/item=128512/challengers-tribute) deberia desaparecer de mi inventario
![image](https://user-images.githubusercontent.com/81131460/129094912-b2c6c235-47b9-4c9b-97cb-f251ed19ff5d.png)

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=92206/felscale-pilferer
no deberian dar reputacion
![image](https://user-images.githubusercontent.com/81131460/129433037-446240dc-c15e-4004-a8bb-11f959fcb268.png)
https://www.wowhead.com/npc=93095/voracious-bear
el oso aparece como muerto, pero atacan  y al matarlos no puedo lootear, mi pj le sigue atacando estando muerto el npc
![image](https://user-images.githubusercontent.com/81131460/129433577-6e8380e9-68f8-4177-a5c3-eb34c6f1c355.png)
![image](https://user-images.githubusercontent.com/81131460/129433603-36144575-1a83-49ed-b50a-8dde8b38169f.png)
https://www.wowhead.com/quest=38818/the-final-judgment
la mision funciona bien aveces, aveces desparecen todos adds en la plataforma cuando estamos en combate,, y tengo que abandonar mision o salirme de la plataforma donde ocurre la mision para que vuelvan aparecer los adds y otro error es que la plataforma donde transcurre la mision, las pets del cazador no pueden seguirme y desaparecen estando invocadas.
![image](https://user-images.githubusercontent.com/81131460/129434187-346cce79-bb24-4374-9c11-2f90867a6346.png)

**Comment by Cefiro-Caecias** [comment]
1) https://www.wowhead.com/npc=91069/forsaken-dreadwing: reparado.
2) https://www.wowhead.com/npc=90899/forsaken-bat-rider: hay dos modelos, uno ataca sobre un murciélago, y el otro en tierra invocando un murciélago para que lo asista. Ambos reparados.
3) https://www.wowhead.com/npc=90903/adolescent-storm-drake: reparado.
4) https://www.wowhead.com/npc=92415/storm-drake-whelp: reparado.
5) https://www.wowhead.com/npc=14881/spider: reparado.
6) https://www.wowhead.com/item=128512/challengers-tribute: reparado.
7) https://www.wowhead.com/npc=92206/felscale-pilferer: reparado.
8) https://www.wowhead.com/npc=93095/voracious-bear: reparadoo.
9) https://www.wowhead.com/quest=38818/the-final-judgment: es un problema de los Vmpas. En revisión.
