### ISSUE TITLE
[Tyce] - Calendar Create Event Time

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2731]
**Links:**
![image](https://user-images.githubusercontent.com/85613053/129085489-c178e8a3-9b4d-46ed-8b18-cfb6ba89c94e.png)
![image](https://user-images.githubusercontent.com/85613053/129085684-45e1d179-64b2-4c74-94fe-f9a9e5c924a2.png)

**What is happening:**
1. Show Calendar ->
2. Create Event ->
3. Write Title ->
4. Create ->
5. Time changes 1 hour
Any update to the event also makes the time change 1 hour.

**What should happen:**
The time should remain consistent.

**Comment by Arkanheal** [comment]
Fixed. Closing
