### ISSUE TITLE
[Tyce] - Medallon Honorable - Logro - Spell

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2732]
**Links:**
https://www.wowhead.com/achievement=10561/honorable-medallion
https://www.wowhead.com/spell=195710/honorable-medallion
from WoWHead or our Armory

**What is happening:**
lo gane al entrar a dalaran en la mision (https://www.wowhead.com/quest=44663/in-the-blink-of-an-eye) cuando estaba por este pasillo y me golpeo unos adds
![image](https://user-images.githubusercontent.com/81131460/129097925-84839fa2-a9fa-4ef5-a9a3-c114d256a904.png)

**What should happen:**
El logro se obtiene al ingresar a una arena o campo de batalla por primera vez. y recibes el spell

**Comment by Cefiro-Caecias** [comment]
@ShikoSCS, el Logro se detona al ser atacado por cualquier entidad con Flag PvP.
