### ISSUE TITLE
NPC - Mascotas de Cazador

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2733]
**Links:**

from WoWHead or our Armory

**What is happening:**
No aparecen, no estan en el juego
https://www.wowhead.com/npc=50843/portent
https://www.wowhead.com/npc=50839/chromehound

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
1) Portent: posee 10 spots de respawn aleatorio, con 1 hora de temporizador. A explorar mejor y encontrarlo ;)

2) Chromehound: agregado, con 1 hora de respawn. Lo encontrarás tomando una siesta en el próximo update.
