### ISSUE TITLE
MM Hunter artifact quest

### ISSUE THREAD

**Issue by gordaoxd** [GuabinaCore/WoWKoi#2734]
Was doing the MM hunter artifact quest, i "got" the artifact in the mission progress, but i didnt get the item artifact weapon, making me unable de level it up and progress on the campaing
![WoWScrnShot_081221_171440](https://user-images.githubusercontent.com/88856875/129263432-64aa4568-a740-48a1-9a19-fdc876477c18.jpg)

**Comment by Cefiro-Caecias** [comment]
I just tried it, and it didn't give me any error. You must have the Artifact Weapon equipped when you take the quest.
