### ISSUE TITLE
[Wotlk][Zone][Alliance] Storm Peaks - complete report (under construction)

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2736]
**Links:**

https://www.wowhead.com/the-storm-peaks

---
1. 
 - [ ] [The Crone's Bargain](https://www.wowhead.com/quest=12841/the-crones-bargain)
     - After completing the quest, player should be given illusion buff/aura, that makes them friendly with nearby Vrykul. I did not manage to find the spell ID.
---
2. 
 - [ ] [Pushed Too Far](https://www.wowhead.com/quest=12869/pushed-too-far)
     - [Fjorlin Frostbrow](https://www.wowhead.com/npc=29732/fjorlin-frostbrow)'s dialogue to ride [Stormcrest Eagle](https://www.wowhead.com/npc=30108/stormcrest-eagle) doesn't work.
     - [Stormcrest Eagle](https://www.wowhead.com/npc=30108/stormcrest-eagle) vehicle abilities don't have any effect..
         - [Eye Gouge](https://www.wowhead.com/spell=55951/eye-gouge)
         - [Storm Bolt](https://www.wowhead.com/spell=55958/storm-bolt)
         - [Swoop](https://www.wowhead.com/spell=55936/swoop)
---
3. 
 - [ ] [Loyal Companions](https://www.wowhead.com/quest=12865/loyal-companions)
     - [Fresh Ice Rhino Meat](https://www.wowhead.com/item=41340/fresh-ice-rhino-meat) has too low drop rate. I had to kill about 10-20 for 1 meat to drop. According WoWhead, it's 14%, according YB videos, its about 99%.
     - [Stormcrest Eagle](https://www.wowhead.com/npc=29854/stormcrest-eagle)s are not present in the questing area.
---
4. 
 - [ ] NPC [Sirana Iceshriek](https://www.wowhead.com/npc=29794/sirana-iceshriek)
     - [Ice Shriek](https://www.wowhead.com/spell=61211/ice-shriek) deals too much damage. According to wowhead, It should be around 18k dmg.
     
![image](https://user-images.githubusercontent.com/63166930/129747880-bd9dc5c7-3a44-4d7f-9be8-c9bdf6fd9a71.png)

---
5. 
 - [ ] [The Iron Colossus](https://www.wowhead.com/quest=13007/the-iron-colossus#comments)
     - [Tamed Jormungar](https://www.wowhead.com/npc=30301/tamed-jormungar)'s abilities don't work.
     - Monsters reset after attacking [Tamed Jormungar](https://www.wowhead.com/npc=30301/tamed-jormungar).
      

---
6. 
 - [ ] [Injured Goblin Miner](https://www.wowhead.com/npc=29434/injured-goblin-miner)
     - Cannot interact with the NPC, therefore, I can't take the quests she offers.
---
7. 
 - [ ] NPC
     -
---
8. 
 - [ ] NPC
     -
---
9. 
 - [ ] NPC
     -
---
10. 
 - [ ] NPC
     -
---
11. 
 - [ ] NPC
     -
---
12. 
 - [ ] NPC
     -
---
13. 
 - [ ] NPC
     -
---
14. 
 - [ ] NPC
     -
---
15. 
 - [ ] NPC
     -
---
16. 
 - [ ] NPC
     -
---
17. 
 - [ ] NPC
     -
---
18. 
 - [ ] NPC
     -
---
19. 
 - [ ] NPC
     -
---
20. 
 - [ ] NPC
     -
---
21. 
 - [ ] NPC
     -
---
22. 
 - [ ] NPC
     -
---
23. 
 - [ ] NPC
     -
---
24. 
 - [ ] NPC
     -

 ---  --------------------------------------

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
