### ISSUE TITLE
[Wotlk][Zone][Alliance] Icecrown - complete report (under construction)

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2737]
**Links:**

https://www.wowhead.com/icecrown

---
1. 
 - [ ] [Preparations for War](https://www.wowhead.com/quest=13418/preparations-for-war#comments)
     - [Officer Van Rossem](https://www.wowhead.com/npc=31081/officer-van-rossem)'s dialogue to transport you to the Skybreaker doesn't work. Since it's old content, might as well just teleport there. The ship is constantly moving though... 
---
2. 
 - [ ] NPC
     -
---
3. 
 - [ ] NPC
     -
---
4. 
 - [ ] NPC
     -
---
5. 
 - [ ] NPC
     -
---
6. 
 - [ ] NPC
     -
---
7. 
 - [ ] NPC
     -
---
8. 
 - [ ] NPC
     -
---
9. 
 - [ ] NPC
     -
---
10. 
 - [ ] NPC
     -
---
11. 
 - [ ] NPC
     -
---
12. 
 - [ ] NPC
     -
---
13. 
 - [ ] NPC
     -
---
14. 
 - [ ] NPC
     -
---
15. 
 - [ ] NPC
     -
---
16. 
 - [ ] NPC
     -
---
17. 
 - [ ] NPC
     -
---
18. 
 - [ ] NPC
     -
---
19. 
 - [ ] NPC
     -
---
20. 
 - [ ] NPC
     -
---
21. 
 - [ ] NPC
     -
---
22. 
 - [ ] NPC
     -
---
23. 
 - [ ] NPC
     -
---
24. 
 - [ ] NPC
     -

 ---  --------------------------------------

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
