### ISSUE TITLE
Suramar - Misiones - Spell

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2739]
**Comentarios de Sefrenia**

* https://www.wowhead.com/item=132472/fel-deconstructor: reparado.

* https://www.wowhead.com/npc=98862/fel-cannon: reparado.

* https://www.wowhead.com/npc=113682/felbound-manasaber: reparado.

* https://www.wowhead.com/quest=41222: reparado.

* https://www.wowhead.com/quest=41214: reparado.

* https://www.wowhead.com/quest=41309: reparado.

**Comment by Noahkrr** [comment]
* https://www.wowhead.com/npc=112140/thudchop-trunksmasher: reparado.

* https://www.wowhead.com/quest=43588/leyline-feed-kelbalor: reparado.

* https://www.wowhead.com/quest=43592/leyline-feed-falanaar-arcway: reparado.

* https://www.wowhead.com/quest=43594/leyline-feed-halls-of-the-eclipse: reparado.

* https://www.wowhead.com/quest=43590/leyline-feed-ley-station-moonfall: reparado.

* https://www.wowhead.com/quest=43593/leyline-feed-falanaar-depths: reparado.

* https://www.wowhead.com/quest=43587/leyline-feed-elorshan: reparado.

* https://www.wowhead.com/quest=43591/leyline-feed-ley-station-aethenar: reparado.

**Comment by Noahkrr** [comment]
* https://www.wowhead.com/npc=105613/shardback-skitterer: reparado.

* https://www.wowhead.com/npc=113532/arcward: reparado.

* https://www.wowhead.com/npc=114793/faldorei-slicer: reparado.

**Comment by Noahkrr** [comment]
* https://www.wowhead.com/object=265435/ancient-seed-holder: reparada.

**Comment by Noahkrr** [comment]
* https://www.wowhead.com/quest=42837/balance-to-spare: reparada.

**Comment by Noahkrr** [comment]
* https://www.wowhead.com/quest=40125/branch-of-the-arcandor: reparada.

* https://www.wowhead.com/quest=43318/lyleths-champion: reparada.

**Comment by Noahkrr** [comment]
* https://www.wowhead.com/object=252450/shimmering-ancient-mana-cluster: reparado.

* https://www.wowhead.com/object=252449/shimmering-ancient-mana-cluster: reparado.

* https://www.wowhead.com/object=251416/ancient-mana-chunk: reparado.

* https://www.wowhead.com/object=252446/shimmering-ancient-mana-cluster: reparado.

* https://www.wowhead.com/object=252831/glimmering-treasure-chest: este GO sí se encuentra (.go object 110570 con comando GM).

* https://www.wowhead.com/npc=105685/faldorei-broodlord: reparado.

* https://www.wowhead.com/npc=105686/faldorei-webspinner: reparado.

* https://www.wowhead.com/npc=114793/faldorei-slicer: reparado.

* https://www.wowhead.com/npc=99765/wyrmtongue-toady: reparado.

* https://www.wowhead.com/quest=43565/bring-home-the-beacon: reparado.

* https://www.wowhead.com/quest=40901/grimwing-the-devourer: reparado.

* https://www.wowhead.com/item=133968/moon-guard-sigil: reparado parcialmente; dado que el item no existe en la DB actual, recibirás la quest la próxima vez que mates a cualquiera de los 4 mobs que dropean el item original.

* https://www.wowhead.com/quest=41452/feline-frantic: parcialmente reparado, no encuentro cómo tumbar los objects.

* https://es.wowhead.com/quest=40907/eliminar-obstáculos: reparado.

**Comment by Noahkrr** [comment]
https://github.com/GuabinaCore/WoWKoi/issues/2742 un extra :)

**Comment by Noahkrr** [comment]
https://github.com/GuabinaCore/WoWKoi/issues/2861

**Comment by Cefiro-Caecias** [comment]
Reparadas. Algunas de ellas disponibles en el próximo update. Ver mis comenatrios arriba. Los enlaces a los otros dos posts los revisaré más adelante ^^
