### ISSUE TITLE
[Core] - Spell Shaman Ability - Stormbringer

### ISSUE THREAD

**Issue by axryn** [GuabinaCore/WoWKoi#274]
Ability: Stormbringer (Passive)
Class: Shaman (Enhancement)

https://www.wowhead.com/spell=201845/stormbringer

Buff is being consumed by Lava Lash and Crash Lightning. Should only be consumed when casting Stormstrike.

**Comment by RygardNin** [comment]
Confirmed still not working properly

**Comment by Maczuga** [comment]
Can confirm too.
