### ISSUE TITLE
[Core?] Escort/defend a spot quests become incomplete after a while.

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2740]
**Links:**

https://www.wowhead.com/quest=12470/mystery-of-the-infinite
https://www.wowhead.com/quest=12082/dun-da-dun-tah
https://www.wowhead.com/quest=12864/missing-scouts

**What is happening:**
I completed the quests above and after a couple of minutes the objectives have turned back to be incomplete. Bug has been encountered in Northrend. I haven't seen something like it happen on Legion content, so it might just be quests from the old content being bugged like this.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Northrend will be rebuilt later. Patience.
