### ISSUE TITLE
Error de misiones completas 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2741]
**Links:**

from WoWHead or our Armory

**What is happening:**
yo tengo un problema al completar algunas misiones, estas cambian de estar completas a perder el rastro (como se ve en la imagen la mision aparece con los creditos completos, deberia estar como la mision de arriba con el signo (?) de mision completada), aveces no me deja entregar mision y aveces si, porque en el mapa no aparece el signo (?) donde entregar la mision 
![afs](https://user-images.githubusercontent.com/81131460/129841710-6eecede5-3ac2-49df-a4b2-3e9fb3fd4e8a.PNG)
aqui otras misiones
la primara mison
1ro se pierde el rastreo de las misiones que estaban completas
![hlas](https://user-images.githubusercontent.com/81131460/129845076-74875dbe-4122-4c25-989e-720a05927a45.PNG)
2do no se puede ubicar en el mapa donde esta el npc para entregar la mision.
![sasd](https://user-images.githubusercontent.com/81131460/129845128-22ba3e33-f603-4f8f-9c32-e88bcf2ffc9c.PNG)
3ro encontre al npc, tiene un signo gris
![dgdg](https://user-images.githubusercontent.com/81131460/129845204-a08b416d-8a57-4172-8d1f-68b24931da33.PNG)
4to al intentar entregar la mision, tengo la opcion de continuar
![fdfdffdf](https://user-images.githubusercontent.com/81131460/129845237-f559e1b4-fc30-4603-a876-fe8b3a0caf26.PNG)
![image](https://user-images.githubusercontent.com/81131460/129846010-14213347-e62a-4e2b-acae-d7f860f7635b.png)

5to al continuar, recien la mision cambia de ser gris sin rastreo a estar completa, con su signo respectivo
![sfsffs](https://user-images.githubusercontent.com/81131460/129845282-3e9159ba-aaf3-47cb-ad65-488c6aaa55b8.PNG)
![image](https://user-images.githubusercontent.com/81131460/129846142-dd01d92a-f6d3-49a3-aabd-1aa241d6f318.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Reparado.
