### ISSUE TITLE
Suramar - Insurreccion

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2742]

**Comment by Noahkrr** [comment]
**Comentarios de Sefrenia**

* https://www.wowhead.com/quest=44727/smuggled: reparado; tuve que reconstruir la zona completa y 2 quests más de allí, ya que detecté muchos errores extra y muy poco amor por lo blizzlike. Te odio -.-

* https://www.wowhead.com/npc=116317/slowfall-rune: reparado.

* https://www.wowhead.com/quest=38720/no-reason-to-stay: reparado.

* https://www.wowhead.com/quest=44753/on-public-display: reparado.

**Comment by Noahkrr** [comment]
* https://www.wowhead.com/quest=41140/search-and-rescue: reparado.

* https://www.wowhead.com/quest=41222/into-the-pit: reparado.

* https://www.wowhead.com/quest=41214/parts-unknown: reparado.

* https://www.wowhead.com/quest=41309/mangelrath: reparado.

**Comment by Cefiro-Caecias** [comment]
Reparadas. Disponibles en el próximo update.
