### ISSUE TITLE
Dalaran - orientacion/busqueda 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2744]
**Links:**

from WoWHead or our Armory

**What is happening:**
la busqueda no funciona, ejemplo: quiero la ubicación del peluquero, no me lo muestra el mapa de dalaran.
![image](https://user-images.githubusercontent.com/81131460/130342228-05b1c897-87b2-4549-8446-04d1266d7fd8.png)
![image](https://user-images.githubusercontent.com/81131460/130342334-2c7d0afa-fca3-462e-a6db-d6a105015526.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
