### ISSUE TITLE
[Wotlk][Zone][Alliance] Howling Fjord - complete zone report (under construction)

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#2745]
**Links:**

https://www.wowhead.com/howling-fjord
https://www.wowhead.com/storyline/howling-fjord-528

---
1. 
 - [ ] [If Valgarde Falls...](https://www.wowhead.com/quest=11243/if-valgarde-falls)
     - According to YB video, [Dragonflayer Invader](https://www.wowhead.com/npc=24051/dragonflayer-invader) and [Dragonflayer Worg](https://www.wowhead.com/npc=24063/dragonflayer-worg) should constantly swarm the questing area. Currently it requires 2 respawns to complete the quest.
---
2. 
 - [ ] [Guided by Honor](https://www.wowhead.com/quest=11289/guided-by-honor)
     - Clicking "Continue" while talking to [Lord Irulon Trueblade](https://www.wowhead.com/npc=24191/lord-irulon-trueblade) won't let me complete the quest.
---
3. 
 - [ ] [It Goes to 11](https://www.wowhead.com/quest=11421/it-goes-to-11)
     - [ Harpoon Control Mechanism](https://www.wowhead.com/item=34032/harpoon-control-mechanism) doesn't start vehicle event.
--- 
4. 
 - [ ] Elevators on the East end of Howling Fjord are visually bugged. If you look from certain angle, they looke like on the screenshot. The elevators do work, so might as well ignore that issue.
     

> 
![image](https://user-images.githubusercontent.com/63166930/130351737-6566d1fb-135a-48a2-a518-09e575586c81.png)

---
5. 
 - [ ] NPC
     -
---
6. 
 - [ ] NPC
     -
---
7. 
 - [ ] NPC
     -
---
8. 
 - [ ] NPC
     -
---
9. 
 - [ ] NPC
     -
---
10. 
 - [ ] NPC
     -
---
11. 
 - [ ] NPC
     -
---
12. 
 - [ ] NPC
     -
---
13. 
 - [ ] NPC
     -
---
14. 
 - [ ] NPC
     -
---
15. 
 - [ ] NPC
     -
---
16. 
 - [ ] NPC
     -
---
17. 
 - [ ] NPC
     -
---
18. 
 - [ ] NPC
     -
---
19. 
 - [ ] NPC
     -
---
20. 
 - [ ] NPC
     -
---
21. 
 - [ ] NPC
     -
---
22. 
 - [ ] NPC
     -
---
23. 
 - [ ] NPC
     -
---
24. 
 - [ ] NPC
     -

 ---  --------------------------------------

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
