### ISSUE TITLE
Monte alto - Misiones part2

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2746]
**Comentarios de Sefrenia**

1) https://www.wowhead.com/npc=95866/drogbar-manathirster: reparado.
2) https://www.wowhead.com/npc=94261/bitestone-rockbeater: reparado.
3) https://www.wowhead.com/item=127767/morashus-antlers: reparado.

**Comment by Noahkrr** [comment]
4) https://www.wowhead.com/quest=39578/titanic-showdown: reparado
5) https://www.wowhead.com/quest=40312/a-timely-opportunity: reparado
6) https://www.wowhead.com/quest=42596/mountainstrider-round-up: reparado
7) https://www.wowhead.com/quest=39134/wrathshard: reparado; sin embargo, luego de investigar, el requisito para que esta quest esté disponible, es haber complateado la quest "Get to High Ground" (38909), que es parte del Logro "No hay montaña demasido alta" (segmento "Riverbend").

**Comment by Noahkrr** [comment]
8) https://www.wowhead.com/spell=190720/unstable-sled: reparado.

**Comment by Noahkrr** [comment]
9) https://www.wowhead.com/quest=40193/getting-the-kinks-out: reparada, pero recibirás la quest luego de completar las quests Stamped Stories (40191) y Claw of the Land (40192).

**Comment by Noahkrr** [comment]
10) https://www.wowhead.com/npc=97544/bloodtotem-warmonger: reparado.
11) https://www.wowhead.com/quest=39860/rite-of-blood: pendiente de reconstrucción.

**Comment by Cefiro-Caecias** [comment]
Reparados. Comentarios arriba. Disponibles en el próximo update.
