### ISSUE TITLE
Mineria - NPC - Herrera vil Nalryssa

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2748]
**Links:**
from WoWHead or our Armory

**What is happening:**
al comletar las misiones de nivel 2 de: deposito de pizarra vil, veta de pizarra vil y piedra vil viviente,
el npc (https://www.wowhead.com/npc=92264/felsmith-nalryssa) no deberia dar las misiones.. se obtienen las misiones picando nodos de pizarra vil
![image](https://user-images.githubusercontent.com/81131460/130724962-fcb51e9d-fa3d-481a-aded-71d6cb54a258.png)

PD: no tome la mision del npc, la consegui picando vetas de pizarra vil y logre invocar a Lyrelle, fue quien me dio la mision y logre completarla

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Eso ya está reparado, pero aun no aplican mis fixes. Te adelantaste, y perdiste toda la experiencia full blizzlike que temriné de reparar y publicar ayer.
