### ISSUE TITLE
[Core] - Spell Shaman Talent - Hailstorm

### ISSUE THREAD

**Issue by axryn** [GuabinaCore/WoWKoi#275]
Ability: Hailstorm
Class: Shaman Talent (Enhancement)

https://www.wowhead.com/spell=210853/hailstorm

Talent is always active.

**Comment by bonfim97** [comment]
Can confirm. This only seems to happen when you chose the talent then change it but using hearthstone made it go back to normal. There's also another bug with hailstorm/frostbrand that i pointed out here : https://github.com/GuabinaCore/WoWKoi/issues/86
