### ISSUE TITLE
[Tyce] - Rogue Class Hall Quest: Injection of Power

### ISSUE THREAD

**Issue by LeonardoVillarreal** [GuabinaCore/WoWKoi#2750]
Hi I've been trying since yesterday to do this quest but it's impossible, I don't receive the 100 AP to empower the weapon (Subtlety),  already tried unequipping the weapons, re-logging, changing especialization, etc.

I read that this issue was already solved, maybe some changes broke it again.

**Comment by Arkanheal** [comment]
Do you have an update on this @LeonardoVillarreal ?
