### ISSUE TITLE
bug-quest "Another Way" 

### ISSUE THREAD

**Issue by gongzifusu** [GuabinaCore/WoWKoi#2751]
**Links:**https://www.wowhead.com/quest=38342/another-way

from WoWHead or our Armory

**What is happening:**
![bug](https://user-images.githubusercontent.com/3193729/130939201-f7e57657-f3d7-4410-aeed-b6e91af306fa.png)

**What should happen:**

https://www.wowhead.com/npc=91240/gunnlaug-scaleheart#abilities

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
