### ISSUE TITLE
Return to Alcaz Isle - needs Legion update

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2752]
**Links:**
https://wowpedia.fandom.com/wiki/Return_to_Alcaz_Isle
https://wowpedia.fandom.com/wiki/Alcaz_Island#Legion
https://www.youtube.com/watch?v=fOxnnvfkAj4

**What is happening:**
The island is still tuned to level 60. Not fully updated to Legion.

**What should happen:**
Level 60~ mobs should be removed. Level 110 turrets and mechanicals should be added and scripted.

**Comment by Cefiro-Caecias** [comment]
Fixed. You will see the classic zone up to Level 97, but when you go up to Level 98 you will see the zone adapted to Legion. Available in the next update.
