### ISSUE TITLE
Deaths of Chromie - can't access scenario?

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2753]
**Links:**
https://wowpedia.fandom.com/wiki/Deaths_of_Chromie
https://www.wowhead.com/quest=47543/the-day-that-chromie-dies
https://www.youtube.com/watch?v=0IZ8Vkf9fh8

**What is happening:**
The scenario isn't accessible. 

**What should happen:**
Should be able to meet with Chromie and begin the scenario.

**Comment by Cefiro-Caecias** [comment]
It will be repaired later. Patience ^^
