### ISSUE TITLE
Profesión - Primeros auxilios - Misiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2754]
**Comentarios de Sefrenia**

1) Todos los items que inician las misiones, caen sin tener la profesión aprendida, debería aprender primero y después recién al farmear los items caigan: reparados.

2) https://www.wowhead.com/quest=42255/deprecated-bloody-note: reparado.

3) https://www.wowhead.com/quest=42245/deprecated-singed-note: reparado.

4) https://www.wowhead.com/quest=42308/deprecated-bloody-plea: reparado.

5) https://www.wowhead.com/quest=42303/deprecated-fevered-note: reparado.

6) https://www.wowhead.com/quest=42309/deprecated-bloody-request: reparado.

7) https://www.wowhead.com/quest=42323/deprecated-fevered-letter: reparado.

8) https://www.wowhead.com/quest=42334/deprecated-crumpled-note: reparado.

**Comment by Noahkrr** [comment]
9) https://www.wowhead.com/quest=42350/deprecated-bloody-letter: reparado.

10) https://www.wowhead.com/quest=42351/deprecated-bloody-prayer: reparado.

11) https://www.wowhead.com/quest=42215/deprecated-singed-letter: reparado.

12) https://www.wowhead.com/quest=42340/deprecated-singed-plea: reparado.

13) https://www.wowhead.com/quest=41985/deprecated-fevered-request: reparado.

14) https://www.wowhead.com/quest=42333/deprecated-crumpled-letter: reparado.

15) https://www.wowhead.com/quest=42058/deprecated-crumpled-request: reparado.

**Comment by Cefiro-Caecias** [comment]
Todas reparadas (incluidas 2 extra que olvidaste postear). Disponibles en el próximo update.
