### ISSUE TITLE
[Quest : 39787] Stormheim - Rigging the water

### ISSUE THREAD

**Issue by HelooxD** [GuabinaCore/WoWKoi#2757]
**Links:**

from WoWHead or our Armory

**What is happening:**
the quest rigging the wager you need to click on dirt to spawn a boss but he does not spawn

**What should happen:**

**Comment by nevarden** [comment]
https://www.wowhead.com/quest=39787/rigging-the-wager

**Comment by Arkanheal** [comment]
@HelooxD Do you have an update on this issue?

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
