### ISSUE TITLE
Quest/NPC Onslaught Envoy - Mariella the Heretic

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2759]
**Links:**
https://www.wowhead.com/npc=110683/mariella-the-heretic
https://www.wowhead.com/quest=43386/onslaught-envoy
https://www.wowhead.com/npc=111191/onslaught-apostate

**What is happening:**
During the priest questline to get Mariella, she shows up as "Onslaught Apostate" for the player.

**What should happen:**
She should be named properly for the player on the quest. Everyone else should see Onslaught Apostate, but the player on the quest should see Mariella the Heretic.

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/131167117-d5a0fe6b-d546-4236-90bf-a32e2095dbef.png)

**Comment by Arkanheal** [comment]
Do you have an update on this @nevarden ?
