### ISSUE TITLE
Lorlathil missing mailbox

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2761]
**Links:**
https://wowpedia.fandom.com/wiki/Lorlathil#Patch_changes

**What is happening:**
missing mailbox in front of Lorlathil inn
![image](https://user-images.githubusercontent.com/85613053/131176986-266f99a0-1d40-4746-ab1c-41498cc5a574.png)

**What should happen:**
a mailbox should be added in front of Lorlathil inn.
![image](https://user-images.githubusercontent.com/85613053/131176848-8a9d397c-095d-431b-b481-ecaae45141a8.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
