### ISSUE TITLE
Alternate Mana Bar missing visual spell-cost indication

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2762]
**Links:**

from WoWHead or our Armory

**What is happening:**
The mana bar visually shows how much mana the spell that is casting will cost in mana bar, but is not showing in alternate mana bar.

**What should happen:**
PlayerFrameAlternateManaBar should also visually show how much mana the spell that is casting will cost, similar to how shields show up on the health bar.

**Comment by Arkanheal** [comment]
Do you have an update on this?
