### ISSUE TITLE
Val'sharah - Tesoros

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2763]
**Links:**

from WoWHead or our Armory

**What is happening:**
al abrir cofres de tesoros, recibo reputacion con los orcos lobo gelidos de draenor, lo cual no deberia pasar, esto sucede con todos los cofres de la zona de Val'sharah
![image](https://user-images.githubusercontent.com/81131460/131179201-26feae2b-0cc2-48df-a97d-57bca5dd9df1.png)

**What should happen:**

**Comment by Kirrkoi** [comment]
Algunos tesoros de tormenheim y de suramar.. tienen el mismo bug de reputación adquirida al abrir cofre del tesoro

**Comment by Noahkrr** [comment]
https://www.wowhead.com/object=242647/treasure-chest
https://www.wowhead.com/object=254127/small-treasure-chest
https://www.wowhead.com/object=242346/small-treasure-chest
https://www.wowhead.com/object=242671/glimmering-treasure-chest
https://www.wowhead.com/object=242645/small-treasure-chest
https://www.wowhead.com/object=242678/treasure-chest
https://www.wowhead.com/object=242675/small-treasure-chest
https://www.wowhead.com/object=240608/small-treasure-chest
https://www.wowhead.com/object=242250/small-treasure-chest
https://www.wowhead.com/object=242242/small-treasure-chest
https://www.wowhead.com/object=240653/small-treasure-chest
https://www.wowhead.com/object=242328/small-treasure-chest
al abrir los  me otorga reputación con orcos Lobo Gélido 350 y 350 por cada cofre total, osea al abrir un cofre recibo 700p de reputacion, no deberia recibir reputacion y algunos cofres tienen otro modelo


https://www.wowhead.com/object=242683/treasure-chest
no hay tesoro
https://www.youtube.com/watch?v=Ym4trJ04sTk

https://www.wowhead.com/object=242669/small-treasure-chest
no hay tesoro
https://www.youtube.com/watch?v=HGvnpH9Vx6I

https://www.wowhead.com/object=242446/small-treasure-chest
no hay tesoro
https://www.youtube.com/watch?v=RxOCfiQgmp0

https://www.wowhead.com/object=242642/small-treasure-chest
no hay tesoro
https://www.youtube.com/watch?v=MPDbtwEJm2g

**Comment by Noahkrr** [comment]
https://www.youtube.com/watch?v=jAbgx3aR3S8
el tesoro del video otorga 350 de reputacion, no deberia otrogar reputacion
https://www.youtube.com/watch?v=pR8w4G15wms
el tesoro del video otorga 350 de reputacion. no deberia otorgar reputacion
https://www.wowhead.com/object=242666/treasure-chest
el tesoro otorga 350 de reputacion. no deberia otorgar reputacion y el modelo del cofre es incorrecto
https://www.wowhead.com/object=242660/small-treasure-chest
el tesoro otorga 350 de reputacion. no deberia otorgar reputacion y el modelo del cofre es incorrecto
https://www.wowhead.com/object=242665/small-treasure-chest
el tesoro otorga 350 de reputacion. no deberia otorgar reputacion y el modelo del cofre es incorrecto
https://www.wowhead.com/object=242668/glimmering-treasure-chest
el tesoro otorga 350 de reputacion. no deberia otorgar reputacion y el modelo del cofre es incorrecto
https://www.wowhead.com/object=242667/small-treasure-chest
No hay cofre

**Comment by Noahkrr** [comment]
https://www.wowhead.com/object=242670/treasure-chest
el tesoro otorga 350 de reputacion, no deberia otorgar reputacion y el modelo del cofre es incorrecto

https://www.youtube.com/watch?v=Mal3qqtNSUM (coordenadas 68.3, 40.6)
el tesoro del vídeo otorga 350 de reputación, no debería otorgar reputación y el modelo del cofre es incorrecto

https://www.wowhead.com/object=242959/treasure-chest
https://www.wowhead.com/object=254141/small-treasure-chest
https://www.wowhead.com/object=241773/small-treasure-chest
https://www.wowhead.com/object=241772/treasure-chest
https://www.wowhead.com/object=242644/treasure-chest
el tesoro otorga 350 de reputacion, no deberia otorgar reputacion

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
