### ISSUE TITLE
[Legion][Artifact][Mage] Extra artifact power gain

### ISSUE THREAD

**Issue by ericdethman** [GuabinaCore/WoWKoi#2764]
**Links:**

https://www.wowhead.com/quest=41125/unlocked-potential

**What is happening:**

upon finishing the unlock potential quest on my mage arcane, i received 350 artifact points, releasing several power traits.
The quest link in the wowhead shows the proper functioning releasing only one trait.
as you can see in the image, it released several strokes and I'm still at lvl 100

**What should happen:**
![WoWScrnShot_082721_185522](https://user-images.githubusercontent.com/89655917/131192698-e334397e-5882-43cb-8d8e-1384cdd9c25b.jpg)

**Comment by Arkanheal** [comment]
Fixed. Closing
