### ISSUE TITLE
Asalto al Bastion Violeta: El Lexicon vil - Mision de sede Paladin

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2765]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=43487/assault-on-violet-hold-the-fel-lexicon
nos pide recuperar el lexicon vil (https://www.wowhead.com/item=139445/fel-lexicon)
este item cae de npc Lord Malgath(https://www.wowhead.com/npc=102282/lord-malgath)

actualmente el item no cae..
**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Reparado.
