### ISSUE TITLE
Profesion - Herreria - Misiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2767]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=39681/the-properties-of-leystone
npc Arlad Schmied tiene dialogo ruso, durante la mision
![image](https://user-images.githubusercontent.com/81131460/131231692-bed9a5bb-7215-44ef-aea6-3774970a34a3.png)

https://www.wowhead.com/quest=38505/engineers-not-completely-useless
no aparece en el mapa hacia donde ir, donde buscar..
![image](https://user-images.githubusercontent.com/81131460/133690738-cb91ad5a-06d6-49c0-8edd-190815f3edc8.png)

https://www.wowhead.com/quest=38506/chicken-scratch
npc Timofey Oshenko tiene dialogo ruso, durante la mision
![image](https://user-images.githubusercontent.com/81131460/131232329-18b94da5-698d-47ec-b1d5-7c039031c146.png)

https://www.wowhead.com/quest=38507/secrets-of-leysmithing
no aparece en el mapa hacia donde ir, donde buscar..
![image](https://user-images.githubusercontent.com/81131460/131232375-d8ae2f1e-1f3d-40fc-bb5b-8188863998a0.png)
![image](https://user-images.githubusercontent.com/81131460/131232382-f92dd519-2ec1-418a-a0c1-7a8fa6d7f616.png)

https://www.wowhead.com/quest=39699/ironhorn-leysmithing
![image](https://user-images.githubusercontent.com/81131460/131232939-a19c94ed-2595-41c4-918b-45b58e876d6c.png)
video de la mision: https://www.youtube.com/watch?v=u0XC5McYa8k

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Reparadas todas, excepto la última, que se hará blizzlike más adelante. Disponible en el próximo update.
