### ISSUE TITLE
[Worldquest]Black Rook Rumble

### ISSUE THREAD

**Issue by Cyrous96** [GuabinaCore/WoWKoi#2768]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=42023/black-rook-rumble
**What is happening:**
Mathias Zunn and the worgen act as "invalid target", need to wait to despawn

**What should happen:**

**Comment by Noahkrr** [comment]
![image](https://user-images.githubusercontent.com/81131460/133544334-a131ff33-ed5a-42b8-bb6e-7d0ec2ab3ad0.png)

**Comment by Arkanheal** [comment]
Duplicate #3234 Closing
