### ISSUE TITLE
[Tyce] - Monk: Black Ox Statue

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2769]
**Links:**
https://www.wowhead.com/npc=61146/black-ox-statue
https://www.wowhead.com/spell=115315/summon-black-ox-statue
![image](https://user-images.githubusercontent.com/85613053/131277691-677fdba0-d752-4734-9844-154099751038.png)

**What is happening:**
1. Black Ox Statue isn't pulsing threat.

2. Other monks can taunt the statue.

3. Black Ox Statue taunts enemies to attack it when the monk casts provoke on the statue.

**What should happen:**
1. Black Ox Statue should pulse threat every 1 second, scaling with the monks AP.

2. The statue should only be tauntable by the monks owner.

3. All enemies in a 10 yard range around the statue should be taunted by the monk when the monk casts provoke on the statue.

**Comment by Arkanheal** [comment]
Do you have an update on this @nevarden ?
