### ISSUE TITLE
[Artifactquest][Druid]Cleansing the Mother Tree

### ISSUE THREAD

**Issue by Cyrous96** [GuabinaCore/WoWKoi#2770]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=41689/cleansing-the-mother-tree
**What is happening:**
G'Hanir can be picked up before stage 4,resulting in bugging the scenario and dupicating the weapon

**What should happen:**

**Comment by Arkanheal** [comment]
@Cyrous96 Do you have an update on this issue?
