### ISSUE TITLE
Monk - Unable to choose a second artifact to pursue

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2771]
**Links:**
https://www.wowhead.com/quest=43973/two-paths-two-weapons

**What is happening:**
No options pop up after picking up the quest. Can't select a 2nd artifact to pursue after I got Mistweaver artifact.

**What should happen:**
Should be given a big window to select the other 2 artifacts and begin their questline.

**Comment by Arkanheal** [comment]
Probably linked to #3270

**Comment by Arkanheal** [comment]
Do you have an update on this @nevarden ?
