### ISSUE TITLE
Flourishing Starlight Roses

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2772]
**Links:**
https://www.wowhead.com/quest=41304/flourishing-starlight-roses
![image](https://user-images.githubusercontent.com/85613053/131575711-45dfc834-e065-4c0b-be86-5136e6680987.png)
**What is happening:**
Up without world quest and not in English

**What should happen:**
Not up without world quest, and in English.

**Comment by Arkanheal** [comment]
Do you have an update on this issue @nevarden ?

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
