### ISSUE TITLE
Class Hall Followers - Combat Ally

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2773]
**Links:**
https://www.wowhead.com/spell=211390/combat-ally
https://www.wowhead.com/spell=222080/bodyguard#see-also-other

**What is happening:**
Unable to select a combat ally.
![image](https://user-images.githubusercontent.com/85613053/131726849-0e443e41-3227-403e-9d0f-9c2fba3d341c.png)
![image](https://user-images.githubusercontent.com/85613053/131726859-5f43cb70-d3e3-4396-84e1-8e9344af654d.png)

**What should happen:**
You can level your followers by assigning them as Combat Allies (at level 110, every quest and world quest gives 150 xp).
Combat Allies can be put in 3 categories:

    Bodyguards: Pretty much the same as the bodyguards in WoD.
        Will show up when you're on the Broken Isles (not in Dalaran or your order hall) and accompany you permanently.
        Depending on the champion, will either be a pure dps, a tank (taunting every few seconds, but not necessarily holding aggro all that well), or a dps who will also heal you occasionally.
        Classes without a tank spec don't seem to get tanking champions, I assume the same goes for non-healers.
        Ranged dps will stand still while fighting, but they don't pull additional mobs even if they patrol right across them.
        When bodyguards get killed, they will simply show up again seconds later with full health.
        They will start attacking only when you attack something. If you get attacked by a mob, they will not automatically intervene. If you switch targets, they will switch a few seconds later. They will stop attacking cc'd mobs, e.g. disoriented.
    Summonable allies: Can be summoned on a cooldown to help you for a short time.
        If you have one of these assigned, you will get a button ( Combat Ally in the middle of your screen. You can drag that button to your action bars, same as the garrison abilities in WoD.
        Will damage / debuff your enemies and/or heal you once or for a few seconds before they despawn.
    "Random" allies: Will show up "randomly", but really when the internal cooldown is up and you meet a certain requirement (e.g. taking damage, so they will only show up while you're fighting).
        When you're in a zone where the ally can show up, you will get a buff reminiscent of his ability.

**Comment by Jellicat12** [comment]
Bump, still an issue, unable to assign follwers as combat allies.
