### ISSUE TITLE
[Vault of the Wardens] Tirathon Saltheril

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2776]
Links:
https://www.wowhead.com/npc=95885/tirathon-saltheril
https://www.wowhead.com/spell=191767/swoop
https://www.wowhead.com/spell=191823/furious-blast
https://www.wowhead.com/spell=192504/metamorphosis?buff
https://www.wowhead.com/spell=190836/hatred
https://www.wowhead.com/spell=202740/metamorphosis?buff
https://www.wowhead.com/spell=192014/throw-glaive
https://www.wowhead.com/spell=214625/fel-chain

What is happening:
Triathlon Saltheril doesn’t Swoop
While in Havoc form, Hatred channel aims at the tank always, and tracks incorrectly.
In Vengeance form, he doesn't throw glaives or use Fel Chain.

What should happen:
The boss should cast their spells.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
