### ISSUE TITLE
[Vault of the Wardens] Glazer

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2778]
**Links:**
https://www.wowhead.com/npc=95887/glazer
https://www.wowhead.com/npc=99865/glazer
https://www.wowhead.com/spell=194880/pulse
https://www.wowhead.com/spell=202046/beam
https://www.wowhead.com/spell=194289/focused

**What is happening:**
1. Pulse just bounces around back and forth instead of aiming at a player.

2. Standing in the beam doesn't hurt.

3. If Focused buff expires instead of the phase being pushed, Glazer just stands still and doesn't attack anymore.

![Uploading WoWScrnShot_090121_132557.jpg…]()

**What should happen:**
1. Pulse will bounce off of the walls of the room toward the nearest player.

2.Standing in the beam should hurt.

3. Glazer should go back to attacking after the phase ends.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
