### ISSUE TITLE
[Vault of the Wardens] Inquisitor Tormentorum

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2779]
**Links:**
https://www.wowhead.com/npc=96015/inquisitor-tormentorum
https://www.wowhead.com/spell=212567/summon-tormenting-orb
https://www.wowhead.com/spell=212564/inquisitive-stare

**What is happening:**
1. The boss resets if you pull him towards the doorway that he stands in front of.

2. No Tormenting Orb / Inquisitive Stare.

**What should happen:**
1. Boss shouldn't reset there. It's a common area to stack the group to line of sight mobs when the boss teleports away.

2. Boss should summon orbs all throughout the fight which cast Inquisitive Stare.

Lots of other bugs related to the abilities and functions from the jailed NPCs released during the encounter.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
