### ISSUE TITLE
[Vault of the Wardens] Blazing Imp

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2780]
Links:
https://www.wowhead.com/npc=98963/blazing-imp
https://www.wowhead.com/spell=194675/fireblast
https://www.wowhead.com/spell=194682/implosion

What is happening:
1. Blazing Imp doesn't target random players with fireblast.

2. Casts implosion occasionally while alive. Doesn't pull players towards the location.

What should happen:
1. Blazing Imp should cast Fireblast at random targets.

2. When a Blazing Imp dies, it begins to cast Implosion. This spell will draw all players within 10 yards towards the Imp's location, and then detonate, dealing heavy damage to nearby players

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
