### ISSUE TITLE
[Vault of the Wardens] Blade Dancer Illianna

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2781]
**Links:**
https://www.wowhead.com/npc=96657/blade-dancer-illianna
https://www.wowhead.com/spell=193164/gift-of-the-doomsayer
https://www.wowhead.com/spell=191527/deafening-shout

**What is happening:**
1. Gift of the Doomsayer buff doesn't copy and send healing to the original caster.All healing received is copied to the original caster of this spell.

2. Doesn't cast Deafening Shout.

**What should happen:**
1. All healing received is copied to the original caster of this spell. Any direct heal received by the target heals the caster of this spell.

2.  Illianna will periodically cast Deafening Shout, which will interrupt the spell casts of all players within 55 yards.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
