### ISSUE TITLE
[Vault of the Wardens] Dreadlord Mendacius

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2782]
**Links:**
https://www.wowhead.com/npc=99649/dreadlord-mendacius
https://www.wowhead.com/spell=196249/meteor
https://www.wowhead.com/spell=196252/summon-grimguard
https://www.wowhead.com/spell=16856/mortal-strike
https://www.wowhead.com/spell=184406/charge

**What is happening:**
1. Casts meteor but doesn't seem to do any damage or effect.

2. Grimguard doesn't do any abilities.

**What should happen:**
1. Meteor will strike the player. Meteor's damage is split amongst all players standing within the marked circle.

2. When Grimguard is summoned, it should have have Mortal Strike and Charge abilities.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
