### ISSUE TITLE
[Vault of the Wardens] Ash'Golm

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2783]
**Links:**
https://www.wowhead.com/npc=95886/ashgolm
https://www.wowhead.com/spell=192631/lava-wreath
https://www.wowhead.com/spell=192522/fissure
https://www.wowhead.com/spell=192519/lava

**What is happening:**
1. Lava pools despawn after only a couple seconds.

2. Lava wreath lava pools all move the same direction.

3. Fissure lava pools spawn in a line and then disappear.

**What should happen:**
1. Lava pools should not fade until coming into contact with a unit or finishing their duration.

2. Lava wreath lava pools should spread all directions away from the player it was cast on.

3.Fissure lava pools should rotate around the room.

The mechanics for the Ember to have Smoldering and detonate,etc. have some problems too

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
