### ISSUE TITLE
[Vault of the Wardens] Grimhorn the Enslaver

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2784]
**Links:**
https://www.wowhead.com/npc=102566/grimhorn-the-enslaver
https://www.wowhead.com/spell=202615/torment
https://www.wowhead.com/spell=202635/torment
https://www.wowhead.com/spell=202608/anguished-souls

**What is happening:**
![WoWScrnShot_090121_133025](https://user-images.githubusercontent.com/85613053/131741100-3c189f2f-f4fb-4260-8f40-cba80981e4ce.jpg)
1. Casts torment on the tank repeatedly. 

2. Anguished Souls is being applied as a debuff to players without any ground effect.

**What should happen:**
1. Torment should cast on non-tanks. Torment should do AoE damage divided among nearby players.

2. Anguished Souls should be visible on the ground and avoidable.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
