### ISSUE TITLE
[Vault of the Wardens] Cordana Felsong

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2785]
**Links:**
https://www.wowhead.com/npc=95888/cordana-felsong
https://www.wowhead.com/spell=189469/turn-kick
https://www.wowhead.com/spell=213583/deepening-shadows
https://www.wowhead.com/spell=197941/elunes-light
https://www.wowhead.com/spell=197823/shadowstep
https://www.wowhead.com/spell=213685/creeping-doom
**What is happening:**
1. Turn Kick cast happens but seems not to knockback.

2. Falling off the platform during the fight kills you.

3. Deepening Shadows only recedes if you hold Elune's Light nearby.

4. Boss is only revealed after Shadowstep by throwing Elune's Light.

5. Creeping Doom spawns only 2 waves and they never intersect.

**What should happen:**
1. Turn Kick knocks the tank back, and hits before the tank can get up and reposition from the Knockdown Kick. 

2. If you are thrown off the platform, a bat will catch you and fly you back up to the platform, so you do not die.

3. Deepening Shadows will recede if Elune's Light is nearby without being held by a player.

4. The player should be able to reveal the boss by holding Elune's Light nearby.

5.  Creeping Doom should spawn 4 waves on mythic difficulty, and the waves should intersect. At the start of the Creeping Doom cast, Cordana will turn and fire a volley of arrows at one edge of the platform. These arrows summon ghostly spirits that slowly creep across the platform. There will be a gap in the green flashes it creates as it summons the spirits.

Some more bugs regarding the Avatars that she summons throughout the fight.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
