### ISSUE TITLE
[Quest]A Falling Star

### ISSUE THREAD

**Issue by Cyrous96** [GuabinaCore/WoWKoi#2786]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=44257/a-falling-star
**What is happening:**
quest can't be picked up by death knights when requierements are fulfilled

**What should happen:**

**Comment by Arkanheal** [comment]
I don't get what you mean as it's part of the paladin class order hall campaign.
Do you have more informations? @Cyrous96

**Comment by Cyrous96** [comment]
was available in beta, should be fixed now
