### ISSUE TITLE
Tormenheim - Misiones - NPC 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2787]
**Comentarios de Sefrenia:**

1) https://www.wowhead.com/npc=92516/forsaken-dreadwing: reparado.

2) https://es.wowhead.com/spell=190895/cuerno-de-helheim: reportado a los Devs de Core.

3) https://www.wowhead.com/quest=39060/combustible-contagion: reparado.

4) https://www.wowhead.com/quest=39850/sundered: agregadas medidas de seguridad, y lo cosmético se reparará más adelante, cuando reconstruya la zona.

5) https://www.wowhead.com/npc=106842/creeping-horror: reparado.

**Comment by Noahkrr** [comment]
**Comentarios de Sefrenia:**

6) https://www.wowhead.com/quest=39594/a-trial-of-might: derivado a los devs de Core.

7) https://www.wowhead.com/quest=42431/the-brood-of-nithogg: reparada. La spell de las piedras pasa a los Devs de Core.

8) https://www.wowhead.com/quest=38337/built-to-scalemate: reparado.

9) https://www.wowhead.com/quest=38374/assault-the-drekirjar: reparado.

**Comment by Noahkrr** [comment]
10) https://www.wowhead.com/npc=91657/bloodbeard: reparada.

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=38321/blackbeak-overlook
objetivo de bonificacion, según wowhead es para hordas, soy alianza no debería tener la misión, tampoco debería estar activa en nivel 110, todas los objetivos de bonificacion deberían estar inhabilitado al llegar a nivel 110

**Comment by Noahkrr** [comment]
11) https://www.wowhead.com/npc=107673/helarjar-soulkeeper: reparado.

**Comment by Cefiro-Caecias** [comment]
Reparados. Disponibles en el próximo update.
