### ISSUE TITLE
[Vault of the Wardens] Barbed Web

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2788]
**Links:**
https://www.wowhead.com/spell=193956/barbed-web

**What is happening:**
The Barbed Web patches are not visible.

**What should happen:**
The player holding Elune's Light is immune to the Barbed Web damage and slowing effects
Walking through the Barbed Web patches will clear a path for the other players to pass through unharmed
Barbed Web patches should be visible.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
