### ISSUE TITLE
[Vault of the Wardens] Veiled in Shadow

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2789]
**Links:**
https://www.wowhead.com/spell=192750/veiled-in-shadow

**What is happening:**
Veiled in Shadow mechanic is entirely missing.

**What should happen:**
While faint outlines of enemies can be briefly seen in the shadows, players cannot target or attack the enemies until they are fully revealed by Elune's Light. (Note that players can be attacked by these enemies if they step into the enemy's combat reach, and will be unable to fight back without Elune's Light!)
Players must use Elune's Light to destroy the patches of Barbed Web that lie near enemy packs, and to reveal the location of the Aranasi Broodmother, Barbed Spiderling, and Spirit of Vengeance mobs that inhabit the area.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
