### ISSUE TITLE
Voidwalker Minion of Vilebranche Shadowcaster level doesn't scale with player level

### ISSUE THREAD

**Issue by Trevis77** [GuabinaCore/WoWKoi#279]
**Links:**
https://classic.wowhead.com/npc=2642/vilebranch-shadowcaster

**What is happening:**
Voidwalker Minion of Vilebranche Shadowcaster level doesn't scale with player level.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
