### ISSUE TITLE
[Vault of the Wardens] Spirit of Vengeance

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2790]
**Links:**
https://www.wowhead.com/npc=100364/spirit-of-vengeance
https://www.wowhead.com/spell=214988/throw
https://www.wowhead.com/spell=214989/knockdown-kick
https://www.wowhead.com/spell=189469/turn-kick

**What is happening:**
Spirit of Vengeance doesn't use abilities.

**What should happen:**
1. Spirit of Vengeance should use abilities.

2. Throw and Knockdown Kick should knock Elune's Light away. 

3. Turn Kick should knock the tank back.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
