### ISSUE TITLE
[Vault of the Wardens] Aranasi Broodmother

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2791]
**Links:**
https://www.wowhead.com/npc=97678/aranasi-broodmother
https://www.wowhead.com/spell=193997/pull
https://www.wowhead.com/spell=193969/razors

**What is happening:**
1. Aranasi Broodmother doesn't cast Pull.

2. Razors cast is placing the spell on the Aranasi Broodmother.

**What should happen:**
1. Should cast Pull.

2. Razors should appear on players instead of on the caster.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
