### ISSUE TITLE
[Vault of the Wardens] Barbed Spiderling

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2792]
**Links:**
https://www.wowhead.com/npc=97677/barbed-spiderling
https://www.wowhead.com/spell=193951/barbed-spit

**What is happening:**
Barbed Spiderling doesn't use abilities or flee.

**What should happen:**
1. Barbed Spiderlings deal melee damage and attack random players with Barbed Spit. 

2. When they reach low health, they will run away from Elune's Light, and players will have to chase them down to finish them off and exit combat.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
