### ISSUE TITLE
[Artifactquest][Priest]Eyes of the Dragon

### ISSUE THREAD

**Issue by Cyrous96** [GuabinaCore/WoWKoi#2793]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=41628/eyes-of-the-dragon
**What is happening:**
Surge Needle can't be scouted, Platforms does not spawn

**What should happen:**

**Comment by Arkanheal** [comment]
Do you have an update on this issue @Cyrous96 ?

**Comment by Cefiro-Caecias** [comment]
Fixed.
