### ISSUE TITLE
Priest Class Hall Upgrade - Shadow Heresy

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2794]
**Links:**
https://www.wowhead.com/champion=920/dark-zealots
![image](https://user-images.githubusercontent.com/85613053/132048598-d1860ab3-c676-4810-8520-2a579e22b1f3.png)
![image](https://user-images.githubusercontent.com/85613053/132048756-b8f11ba7-42fa-401e-9044-a66d410153f7.png)

**What is happening:**
Recruiting Dark Zealots gives regular Band of Zealots.

**What should happen:**
Dark Zealots should be recruited instead of Band of Zealots.

**Comment by Arkanheal** [comment]
Probably for all class order halls are concerned.
