### ISSUE TITLE
[Quest]Professionally Good Looking

### ISSUE THREAD

**Issue by Cyrous96** [GuabinaCore/WoWKoi#2795]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=44915/professionally-good-looking
**What is happening:**
map marker for phloem  doesn't appear on the map

**What should happen:**

**Comment by Arkanheal** [comment]
Quest shouldn't be available. Low prio.

**Comment by Cefiro-Caecias** [comment]
Fixed, blizzlike. Available in the next update.
