### ISSUE TITLE
[Ancient Mana] nodes need multi-tapping

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2797]
**Links:**
https://wowpedia.fandom.com/wiki/Patch_7.1.0_(undocumented_changes)
" [Ancient Mana] nodes can now be looted by multiple players."

**What is happening:**
Once one player has looted the node, it'll despawn and no one else is able to receive loot from it.

**What should happen:**
Once one player has looted the node, it should despawn after 5 players have looted from it and/or after a short amount of time.

**Comment by Arkanheal** [comment]
Do you have an update on this issue @nevarden ?
