### ISSUE TITLE
Herbalism nodes need multi-tapping

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2798]
**Links:**
https://www.mmo-champion.com/content/5785-Legion-Developer-Q-A-Professions
https://www.youtube.com/watch?v=IQcmycsZC4o&t=2947s

**What is happening:**
Once one player has looted the node, it'll despawn and no one else is able to receive loot from it.

**What should happen:**
Once one player has looted the node, it should despawn after 5 players have looted from it and/or after a short amount of time.

Multiple people can gather from the same node for a few seconds, so no more stealing nodes.

**Comment by Arkanheal** [comment]
Do you have an update on this issue @nevarden ?

**Comment by PiR4T496** [comment]
Hi, I'm the warlock Morgoth, I can attest that none of the rank 3 improvements work in Herborist, neither do the seeds, nor the npcs that appear when you finish picking up a plant like the foxes in the case of the vulpine
