### ISSUE TITLE
[Darkheart Thicket] Crazed Razorbeak

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2799]
**Links:**
https://www.wowhead.com/npc=95766/crazed-razorbeak
https://www.wowhead.com/spell=200768/propelling-charge

**What is happening:**
When the Crazed Razorbeak casts 'Propelling Charge' the mob moves very slowly and doesn't really do anything else.

**What should happen:**
When the Crazed Razorbeak casts 'Propelling Charge' the mob should quickly charge through the tank and do damage and stun.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.

**Comment by ShikoSCS** [comment]
Fixes
