### ISSUE TITLE
[Saitama] - Spell Freezing Trap not breaking

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#28]
Class: Hunter
Spec: Marksmanship
Spell: Freezing Trap/Aimed Shot/Arcane Shot
**What is happening:**
When casting [the glitched Arcane + Aimed Shot combo mentioned in issue #19](https://github.com/GuabinaCore/WoWKoi/issues/19), if the enemy is in a Freezing Trap, the trap is not broken, but the enemy is still damaged for the Aimed Shot + Arcane Shot damage. However, this only occurs on neutral (yellow-health) monsters.

**What should happen:**
Any damage, including the damage caused by the glitched Aimed Shot + Arcane Shot, should cause Freezing Trap to break immediately.

**Comment by login6710** [comment]
Fixed
https://github.com/GuabinaCore/TYCE-Group/commit/57a61d941f08c3b33d5004d7156347d0853370d7
