### ISSUE TITLE
[Darkheart Thicket] Dreadsoul Ruiner

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2800]
**Links:**
https://www.wowhead.com/npc=95771/dreadsoul-ruiner
https://www.wowhead.com/spell=200658/star-shower

**What is happening:**
When Dreadsoul Ruiner casts 'Star Shower' only one wave of stars fall.

**What should happen:**
When Dreadsoul Ruiner casts 'Star Shower' several waves of stars should fall.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
