### ISSUE TITLE
[Darkheart Thicket] Festerhide Grizzly

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2801]
**Links:**
https://www.wowhead.com/npc=95779/festerhide-grizzly
https://www.wowhead.com/spell=218755/spew-corruption

**What is happening:**
On Mythic difficulty, Festerhide Grizzly isn't casting Spew Corruption.

**What should happen:**
Festerhide Grizzlies gain Spew Corruption, which spawns 3 Nightmare Abomination adds near random players' locations
The Nightmare Abominations Fixate on random players and slowly chase them
These Abominations leave Corruption Pool in their wake, which deals moderate damage to players standing in it

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
