### ISSUE TITLE
[Darkheart Thicket] Rotheart Keeper

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2802]
**Links:**
https://www.wowhead.com/npc=99359/rotheart-keeper
https://www.wowhead.com/spell=220369/vile-mushroom

**What is happening:**
Rotheart Keeper isn't casting Vile Mushroom

**What should happen:**
Rotheart Keepers should summon Vile Mushrooms, which will detonate and deal heavy damage to nearby players when disturbed

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
