### ISSUE TITLE
[Darkheart Thicket] Rotheart Dryad

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2803]
**Links:**
https://www.wowhead.com/npc=99358/rotheart-dryad

**What is happening:**
Rotheart Dryad is running into melee to attack, and isn't leaping away.

**What should happen:**
Rotheart Dryad will leap directly away from the current tank. The tank should make sure that it leaps in a favorable direction.
If the tank needs to move the Rotheart Dryad, use line-of-sight.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
