### ISSUE TITLE
[Darkheart Thicket] Vilethorn Blossom

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2804]
**Links:**
https://www.wowhead.com/npc=99360/vilethorn-blossom
https://www.wowhead.com/spell=201129/root-burst
![image](https://user-images.githubusercontent.com/85613053/132139119-ebced7c2-ce17-442f-b5d6-e1c4cebaf728.png)

**What is happening:**
Vilethorn Blossom stop chasing at some point and just stand still.
When Vilethorn Blossom casts 'Root Burst' the telegraph is not visible.

**What should happen:**
Vilethorn Blossom should keep chasing to melee, and 'Root Burst' should display telegraph and cast in that area.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
