### ISSUE TITLE
[Darkheart Thicket] Nightmare Dweller

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2805]
**Links:**
https://www.wowhead.com/npc=101991/nightmare-dweller
https://www.wowhead.com/spell=204243/tormenting-eye
https://www.wowhead.com/spell=204246/tormenting-fear
![image](https://user-images.githubusercontent.com/85613053/132139264-08062a1a-9165-469e-90a7-202f2663c557.png)

**What is happening:**
When Nightmare Dweller casts 'Tormenting Eye' it isn't fearing the target after the channel completes.

**What should happen:**
When Nightmare Dweller casts 'Tormenting Eye' it should fear the target if the channel completes.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
