### ISSUE TITLE
[Darkheart Thicket] Oakheart

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2806]
**Links:**
https://www.wowhead.com/npc=103344/oakheart
https://www.wowhead.com/spell=204574/strangling-roots
https://www.wowhead.com/spell=204611/crushing-grip

**What is happening:**
1. When Oakheart casts 'Crushing Grip' players have their target dropped. 

2. When Oakheart finishes 'Crushing Grip' he drops the player on the ground.

3. 'Strangling Roots' aren't rooting players.

**What should happen:**
1. Players should keep their current target when Oakheart casts 'Crushing Grip'

2. When Oakheart finishes 'Crushing Grip' he should throw the player at another player.

3. 'Strangling Roots' should arm and then root any player that walks on it.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
