### ISSUE TITLE
[Darkheart Thicket] Corrupted Dragon Eggs

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2807]
**Links:**
https://www.wowhead.com/npc=101072/corrupted-dragon-egg
https://www.wowhead.com/spell=199313/hatch-whelpling
![image](https://user-images.githubusercontent.com/85613053/132139709-66f6fd9f-412b-4d6e-a6e8-a8f26aa3316b.png)

**What is happening:**
Nothing happens when walking onto corrupted dragon eggs.

**What should happen:**
Corrupted Dragon Eggs line both sides of the corridor leading northeast out of Oakheart's room toward Dresaron. If players disturb these eggs by walking near them, they will Hatch Whelpling, spawning a Hatespawn Whelpling.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
