### ISSUE TITLE
[Darkheart Thicket] Hatespawn Slime

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2808]
**Links:**
https://www.wowhead.com/npc=100529/hatespawn-slime
https://www.wowhead.com/spell=201191/dreadburst

**What is happening:**
Hatespawn Slime isn't detonating after dying.

**What should happen:**
When the Slimes die, they detonate in a Dreadburst, dealing minor Shadow damage to players within 5 yards.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
