### ISSUE TITLE
[Darkheart Thicket] Bloodtainted Fury

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2809]
**Links:**
https://www.wowhead.com/npc=113398/bloodtainted-fury
https://www.wowhead.com/spell=201227/blood-assault

**What is happening:**
Bloodtainted Fury casts 'Blood Assault' but always misses the target.

**What should happen:**
The Bloodtainted Fury will rush forward with Blood Assault, knocking players back
Each player struck by Blood Assault will take moderate damage, and the Bloodtainted Fury will heal
'Blood Assault' needs a better hitbox

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
