### ISSUE TITLE
[Darkheart Thicket] Hatespawn Whelpling

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2810]
**Links:**
https://www.wowhead.com/npc=101074/hatespawn-whelpling
https://www.wowhead.com/spell=212797/hatespawn-detonation

**What is happening:**
Hatespawn Whelplings are only spawning while Dresaron encounter is in progress. They are also missing their detonation on Mythic difficulty.

**What should happen:**
On Mythic difficulty, the Hatespawn Whelplings will detonate with Hatespawn Detonation when killed. 
Hatespawn Whelplings should be able to spawn before the encounter begins.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
