### ISSUE TITLE
[Darkheart Thicket] Taintheart Summoner

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2811]
**Links:**
https://www.wowhead.com/npc=99366/taintheart-summoner
https://www.wowhead.com/spell=201842/curse-of-isolation

**What is happening:**
'Curse of Isolation' isn't doing any AoE around the cursed player.

**What should happen:**
 Curse of Isolation does not harm the affected player, but causes the player to erupt with Shadow energy every 2 seconds
This eruption deals moderate damage to any player within 6 yards of the affected player

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
