### ISSUE TITLE
[Darkheart Thicket] Taintheart Stalker

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2812]
**Links:**
https://www.wowhead.com/npc=99365/taintheart-stalker
https://www.wowhead.com/spell=201517/dark-hunt

**What is happening:**
Taintheart Stalkers isn't using Dark Hunt.

**What should happen:**
Taintheart Stalkers rapidly dash to a ranged target, then back to a melee target, dealing moderate damage with Dark Hunt.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
