### ISSUE TITLE
[Darkheart Thicket] Taintheart Deadeye

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2813]
**Links:**
https://www.wowhead.com/npc=100539/taintheart-deadeye
https://www.wowhead.com/spell=201885/shadow-decoy

**What is happening:**
Taintheart Deadeye is running into melee to attack.
Taintheart Deadeye isn't casting Shadow Decoy.

**What should happen:**
Taintheart Deadeyes will Shoot their target when out of melee range, will frequently fire a Scorching Shot at a random target, and will summon a Shadow Decoy every 25 seconds.
When the Deadeye casts Shadow Decoy, he will teleport away, leaving a shadowy Deadeye Decoy in his original position
These Decoys have low health, and use only melee and Shoot to attack their targets

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
