### ISSUE TITLE
NPC - Portador de la Fatalidad - Los bajos fondos - Dalaran

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2815]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=121922/doombringer
este npc aparece en los bajos fondos y al matarlo no da ojos.. no encontre informacion si este npc pertenece a esta zona..
![image](https://user-images.githubusercontent.com/81131460/132155474-566888c0-1f15-45b7-8448-e4a71791c521.png)

**Comment by Cefiro-Caecias** [comment]
NPC quitado de la zona. Disponible en el próximo update.
