### ISSUE TITLE
[Tyce] - Artifact Quest: An Eye for a Scepter

### ISSUE THREAD

**Issue by Hov9999** [GuabinaCore/WoWKoi#2818]
https://www.wowhead.com/quest=43153/an-eye-for-a-scepter

DESTRUCTION WARLOCK Artifact Quest.

During the final stage of the quest (stage 10/10 "the eye of the beast") , the player has to kill Occul'tharon and find the Eye of Dalaran.

-What happens:
Once the beast is dead, nothing happens.

-What Should happen:
Allaris Narassin (NPC) should give the Eye to the player, then create a portal to Dalaran.

Thank you.

![WoWScrnShot_090621_230445](https://user-images.githubusercontent.com/90220497/132260944-7a7e3714-3a07-435f-b29c-04362e5035ca.jpg)

**Comment by Arkanheal** [comment]
Do you have an update on this issue @Hov9999 ?
