### ISSUE TITLE
[Warlock Spell] Eye of Kilrogg

### ISSUE THREAD

**Issue by Hov9999** [GuabinaCore/WoWKoi#2819]
https://www.wowhead.com/spell=126/eye-of-kilrogg

**What is happening:**
The Eye of Kilrogg is not stealthed, it draws aggro from mobs.

**What should happen:**
The Eye of Kilrogg should be stealthed, and be hidden from mobs (no detection).

**Comment by Arkanheal** [comment]
Do you have an update on this issue @Hov9999 ?
