### ISSUE TITLE
[Suramar] Custom 'Nightborn portal' in Shal'Aran

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2820]
**Links:**
![image](https://user-images.githubusercontent.com/85613053/132395286-98a16c9d-0415-4d77-aaaa-c5ef3b046e71.png)

**What is happening:**
There is a 'Nightborn portal' in Shal'Aran which allows for teleporting to different areas of Suramar.

**What should happen:**
The portals should be unlocked and accessed 1 at a time. There should not be 1 portal to teleport to multiple places.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
