### ISSUE TITLE
Cost of entry for Withered Army Training

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2821]
**Links:**
![image](https://user-images.githubusercontent.com/85613053/132396342-02e24e0c-68b7-475a-9b4b-07df727ca8d9.png)
![image](https://user-images.githubusercontent.com/85613053/132396405-6a081633-64fc-469e-a6b7-c053ede793ed.png)
https://www.wowhead.com/npc=111948/withered-scenario-launch-credit

**What is happening:**
Selecting the 400 ancient mana option took 400 ancient mana twice.

**What should happen:**
The NPC should've only taken my ancient mana once.

**Comment by Arkanheal** [comment]
Fixed. Closing.
