### ISSUE TITLE
[Withered Army Training] Scenario 

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2822]
**Links:**
https://www.wowhead.com/quest=43943/withered-army-training
https://www.wowhead.com/spell=218958/scared
https://www.youtube.com/watch?v=Omi8aUYqtlk
![image](https://user-images.githubusercontent.com/85613053/132402467-99347990-a575-4755-9664-13bf8b75f73b.png)

**What is happening:**
1. Score doesn't work
2. The withered never attempt to flee
3. 'Mayhem!' vs 'Follow Me!' isnt affecting the withered decisions
4. Withered Exiles fade away after being caught
 
**What should happen:**
1. Score should work
2. Withered should attempt to flee, and need to be clicked on to prevent them getting away
3. 'Mayhem!' should make them more stationary, attack randomly, ranged, stronger, and flee more often
4. Withered Exiles should be added to the current army

**Comment by Arkanheal** [comment]
Instant complete for now. Closing for now.
