### ISSUE TITLE
Herbolestería - Misión de mundo

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2823]
**Comentarios de Sefrenia**

1) https://www.wowhead.com/quest=41290/aqueous-aethril: reparada.

**Comment by Kirrkoi** [comment]
Hay muchos nodos de herbolesteria en Suramar que no otorgan hierbas , algunos dan mana antiguo o nada.. y no me es visible tierra fértil donde sembrar semillas...

**Comment by Noahkrr** [comment]
2) https://www.wowhead.com/quest=41292/work-order-dreamleaf: reparado.

**Comment by Noahkrr** [comment]
3) https://www.wowhead.com/quest=41532/bushy-dreamleaf: reparado.

4) https://www.wowhead.com/object=248025/bushy-dreamleaf: reparado.

**Comment by Noahkrr** [comment]
5) https://www.wowhead.com/quest=41225/felwort: reparado.

**Comment by Noahkrr** [comment]
6) https://www.wowhead.com/quest=41289/flourishing-aethril: reparado.

**Comment by Cefiro-Caecias** [comment]
Reparadas. Disponibles en el próximo update.
