### ISSUE TITLE
[Quest] Shriek No More

### ISSUE THREAD

**Issue by Hov9999** [GuabinaCore/WoWKoi#2824]
Quest: 
https://www.wowhead.com/quest=39117/shriek-no-more

What is happening: Rotbeak is not dropping the quest item.

What should happen: Rotbeak is supposed to drop Rotbeak's head.

Thank you.

EDIT: the quest item drops, but it's not a 100%. I got it on the 3rd kill.

**Comment by Arkanheal** [comment]
Item isn't 100% on wowhead (see [here](https://www.wowhead.com/item=127411/rotbeaks-head) ).

Closing.
