### ISSUE TITLE
[Questlog]Recruiting the Troops

### ISSUE THREAD

**Issue by Cyrous96** [GuabinaCore/WoWKoi#2825]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=42848/recruiting-the-troops
**What is happening:**
"Recruiting the Troops" for Paladin is categorized as Death Knight Campaign
need to delete cache to let the banner spawn to pick up the troops

**What should happen:**

**Comment by Arkanheal** [comment]
The mission is common to every class order hall campaign.

Do you have an update for the banner problem @Cyrous96 ?

**Comment by Cyrous96** [comment]
works now
