### ISSUE TITLE
[Suramar] Menagerie - Collar of Domination missing

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2832]
**Links:**
https://www.wowhead.com/spell=205061/collar-of-domination

**What is happening:**
All the creatures in the exhibits in the menagerie are missing their Collar of Domination.

**What should happen:**
All the creatures in the exhibits in the menagerie should have this buff. When it is removed by Overloaded Collar, (https://www.wowhead.com/item=134119/overloaded-collar) the mobs should become hostile.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
