### ISSUE TITLE
Quest - Survival of the Fittest

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2833]
**Links:**
https://www.wowhead.com/quest=41216/survival-of-the-fittest
![image](https://user-images.githubusercontent.com/85613053/132902317-33eb161e-00da-4d80-ae0b-735e849190bb.png)

**What is happening:**
Can't complete quest. 
 "- Free $1oa exhibits from the Menagerie." doesn't complete.

**What should happen:**
Quest should be completable.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
