### ISSUE TITLE
Cambio de profesiones - NPC - Misiones de mundo de profesión

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2835]
**Links:**

from WoWHead or our Armory

**What is happening:**

al cambiar de profesión los npc se han buegado, como ven en la imagen yo cambiar ingenieria por sastreria, y los npc se quedaron con las misiones anteriores de profesion ingenieria. ya no otorga misiones mundiales de profesiones
![image](https://user-images.githubusercontent.com/81131460/132904878-4359bd24-ad9e-4c55-ad94-510800d161da.png)

![image](https://user-images.githubusercontent.com/81131460/132904836-5ffb4b40-d32c-4e57-bf68-74d5759da4c4.png)
en esta otra imagen, el npc tiene la mision de la profesion de peleteria que fue mi segunda profesion que cambie por sasteria, se ha buegado ya no recibo misiones de mundo de profesiones ..
![image](https://user-images.githubusercontent.com/81131460/132905567-dde3f817-d212-4ea8-ad2b-8b3c96038c00.png)

**What should happen:**

**Comment by Noahkrr** [comment]
este npc se bugeo :(
![image](https://user-images.githubusercontent.com/81131460/132907219-0d4776fe-9498-41a9-a66b-6007a370564f.png)

**Comment by Cefiro-Caecias** [comment]
Reparado. No olvides, en esos casos, salir del juego y borrar cache para que los datos se actualicen correctamente.
