### ISSUE TITLE
[Profession Quest]Leatherworking questchain

### ISSUE THREAD

**Issue by Cyrous96** [GuabinaCore/WoWKoi#2836]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=40191/stamped-stories
https://www.wowhead.com/quest=40192/claw-of-the-land
https://www.wowhead.com/quest=40186/drogbar-durability
https://www.wowhead.com/quest=40185/shoulder-the-burden
https://www.wowhead.com/quest=40194/reclaimed-cargo
https://www.wowhead.com/quest=40195/a-daring-rescue
**What is happening:**
claw-of-the-land and stamped-stories should be given by Hrul Sharphoof after completing drogbar-durability and shoulder-the-burden
same for Celea with reclaimed-cargo and a-daring-rescue

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
