### ISSUE TITLE
NPC - Val'sharah

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2837]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=110032/festering-eye
no se ve el npc..
![image](https://user-images.githubusercontent.com/81131460/132917253-a58c44ff-b20e-4710-8c7a-7083a5437a04.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
