### ISSUE TITLE
Misiones de mundo - Desuello

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2838]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=41233/bristled-bear-skin
la mision esta rota, cuando entro a la zona de la mision, desaparece la mision activa
![image](https://user-images.githubusercontent.com/81131460/132934261-32f19c31-222f-4be1-85a2-30fbcba8c377.png)
cuando salgo de la zona de la mision a lo lejos puedo ver la mision activa
![image](https://user-images.githubusercontent.com/81131460/132934152-df5cf04f-cd82-48f1-a760-9323c38b35da.png)

https://www.wowhead.com/quest=41324/silky-prowler-fur
estoy lejos de la mision, y esta se activa, al llegar al area de la mision, desaparece se vuelve inactiva
![image](https://user-images.githubusercontent.com/81131460/132935342-63774cee-ede8-4f0a-bbce-6f424486b5ff.png)
![image](https://user-images.githubusercontent.com/81131460/132935401-2fa05328-be9e-401f-b59f-fb6f548a09de.png)
DATO: las dos primeras misiones fueron completadas, el wow me desconecto, al entrar pude entrar a la zona de mision sin que desaparezca y pude completar la mision, al salir de la zona de la mision se vuelve a bugear.. 

el error se visualiza en casi todas las misiones de  mundo de Desuello (misiones de recoger pellejos a montones, para ser mas específicos)
aqui algunas otras misiones de Desuello
https://www.wowhead.com/quest=41323/fatty-lion-seal-skin
https://www.wowhead.com/quest=41582/smooth-sunrunner-hide
https://www.wowhead.com/quest=41342/thick-bear-hide
https://www.wowhead.com/quest=41343/solid-crabshell-fragment
https://www.wowhead.com/quest=41337/pristine-stag-hide
...

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=41340/perfect-storm-drake-scale
mision de mundo activa no se puede recolectar escamas(https://www.wowhead.com/item=134814/perfect-storm-drake-scale) o el drop es muy pero muy bajo o no esta implementado en la mision..
tiene otro error la mision pide 8 escamas perfectas de Draco de tormenta, deberia pedir 12 escamas perfectas de Draco de tormenta
![image](https://user-images.githubusercontent.com/81131460/132996306-09e560b3-1d8c-4824-94bc-82e2958e7e87.png)

https://es.wowhead.com/item=124037/escama-de-draco-de-tormenta
este item, solo deberia llevar uno en el inventario y ademas me sale un mensaje "esa mision no es disponible par tu raza", esta mision ya la he completado antes, no deberia poder recibir este item.
![image](https://user-images.githubusercontent.com/81131460/132996408-c15fb51d-ef96-423e-9702-cc0448911a25.png)

**Comment by Cefiro-Caecias** [comment]
Reparadas. Disponibles en el próximo update.
