### ISSUE TITLE
[Core?] - Framerate very low at the gnome starting zone

### ISSUE THREAD

**Issue by Trevis77** [GuabinaCore/WoWKoi#285]
**What is happening:**
For some reasons the framerate is very low in the gnome's starting zone, this must be coming from the thing I surrounded in [this screenshot.](https://cdn.discordapp.com/attachments/529355061319565332/692714069517402122/WoWScrnShot_032620_133610.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
