### ISSUE TITLE
Invitación para la Arena - Item / Mision - Ganarse al Publico

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2850]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/item=143478/arena-invitation
el item no funciona, al hacerle click deberia iniciar está mision (https://www.wowhead.com/quest=45179/win-the-crowd)
![image](https://user-images.githubusercontent.com/81131460/132962262-fb8d0797-7f0d-49ac-8eab-dadd20992201.png)

**Comment by Cefiro-Caecias** [comment]
@ShikoSCS, probé de mil maneras alterar este item, tanto por item_template como por item_sparse, y aun así se niega a dar la quest : /
