### ISSUE TITLE
Suramar - Misiones iniciales

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2851]
**Links:**
www.wowhead.com/quest=39987/trail-of-echoes
from WoWHead or our Armory

**What is happening:**
la varia no esta funcionando como deberia, la animacion del spell 
al encontrar los rastros de ecos, No hay tiempo de carga al hacer click en los rastros de ecos  y no aparecen los ecos de Thalyssra ni hay dialogos
matar a Erasmus aparece como credito final lo cual esta mal deberia ser el credito 4to
el NPC Arcanista Thalyssra (https://www.wowhead.com/npc=98312/first-arcanist-thalyssra) tiene el modelo con traje de Arcanista, deberia tener su traje de marchito

**What should happen:**
primero al usar la varita spell (https://www.wowhead.com/item=131931/khadgars-wand) al usarse, deberia moverse y buscando un lugar donde se encuentra el rastro a encontrar
Primero rastro de eco (credito uno)
al encontrar el rastro de eco (https://www.wowhead.com/npc=100169/faint-arcane-echo-revealed) y hacer click en el, se revelaría el eco de la arcanista, dice sus dialogos y al finalizar corre por el camino y se desvanece
seguimos caminando usando la varita para buscar el siguiente eco
Segundo rastro de eco (credito dos)
al encontrar el rastro de eco (https://www.wowhead.com/npc=114070/blinking-arcane-echo-revealed) y hacer click en el, vuelve aparecer el eco de la arcanista dice sus dialogos y desaparece..
seguimos caminando usando la varita para buscar el siguiente eco
Tercer rastro de eco (credito tres)
al encontrar el rastro de eco (https://www.wowhead.com/npc=114071/pulsing-arcane-echo-revealed) y hacer click en el, vuelve aparecer el eco de la arcanista dice sus dialogos y desaparece
Matar a Erasmus (https://www.wowhead.com/npc=99213/erasmus-moonblade)  (credito cuatro)
Encontrar a la Arcanista Thalyssra (credito 5)

video de la mision: https://www.youtube.com/watch?v=fiZj5heVqMA

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=40008/the-only-way-out-is-through
Arcanista Thalyssra sus spell no funcionan correctamente 
https://www.wowhead.com/spell=194124/arcane-barrier
https://www.wowhead.com/spell=194538/arcane-barrier
los marchitos pueden cruzar la barrera, deberia chocar con la barrera y salir volando causándoles daño y debería haber marchitos drenando la barrera a distancia ...
al termino de la mision le npc Arcanista Thalyssra, deberia cambiar su postura a cansada..
![image](https://user-images.githubusercontent.com/81131460/132971840-e1137ff7-7127-4e41-9214-a3dce336b1ef.png)
video de la mision: https://www.youtube.com/watch?v=2LzqduckNDY

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=40123/the-nightborne-pact
el NPC tiene el traje de arcanista , deberia estar con el traje de marchito
![image](https://user-images.githubusercontent.com/81131460/132971954-2fdef576-eaac-4bf4-9a1c-fd1ae00709b3.png)
al termino de la cinematica cambia su traje ..desde el comienzo de la mision deberia tener el traje de marchito

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=40009/arcane-thirst
el npc que da la mision ha bugeado sigue invocando su barrera..
buscar Shal'Aran (primer credito se autocompleta), deberia entrar y tocar el tronco del arbol pero no hay tronco
Guardiana Selentia matado (segundo credito) el npc es inmune hasta matar al npc vinculo eterno, esta fallando el npc inmune si lo atacas, te ataca  deberia estar inmovil lanzando hechizos en el area, el npc vinculo eterno deberia estar moviendose alrededor y los demas adds (https://www.wowhead.com/npc=99088/ancient-keeper) deberia estar volando, cuando les atacas deberian bajar a atacarte..
video de la mision: https://www.youtube.com/watch?v=DRfx-Sw-NH4

**Comment by ShikoSCS** [comment]
Fix spell Arcane Barrier
