### ISSUE TITLE
[Quest] - The Skies of Highmountain

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#2853]
**Links:**
https://www.wowhead.com/quest=39387
from WoWHead or our Armory

**What is happening:**

When you take the bird (only when you take the bird) that brings you back to Thundertotem, you skip the phase when you need to talk to Lasan which makes the quest incompletable. Works perfectly when walking to Thundertotem.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
