### ISSUE TITLE
gesta de desbloqueo salon de los magos

### ISSUE THREAD

**Issue by raxodia** [GuabinaCore/WoWKoi#2854]
**Links:**

from WoWHead or our Armory

**What is happening:**
La gesta inicial que entrega el teletransporte al salon del guardian (sede de clase de magos), no se deja finalizar, pues en la fase 4 se bugea como si no se hubiera matado al elite, por ende no deja continuar la mision

**What should happen:**

**Comment by ShikoSCS** [comment]
Por favor, verifique porque acabo de hacer la gesta completa y me funciono.
