### ISSUE TITLE
[MAJOR BUG][Artifact Quest] Vengeance Will Be Ours

### ISSUE THREAD

**Issue by djawl** [GuabinaCore/WoWKoi#2858]
QUEST: [Vengeance Will Be Ours](https://www.wowhead.com/quest=40249/vengeance-will-be-ours)

The last part of the vengeance demon hunter artifact quest scenario requires a trigger named "Return to Dalaran" to procc. 

Picture Proof: https://i.imgur.com/iiBNLCO.png

Sadly here it doesn't. Meaning you can't complete the quest and is therefore unable to progress the demon hunter class campaign. Which ultimately means you're almost completely locked out of legion if you make a veng DH.

Video Proof: [Video 1](https://gyazo.com/f10fdd374d575c09294c041af03e732b) + [Video 2](https://gyazo.com/73ce6c7a4c4434970f126a8be41bbb55)

This makes someone playing a Vengeance Demon Hunter unable to play legion, so please fix ASAP :)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.

However, you will need to ask a GM to complete the quest for you with the command .quest complete 40249, as the weapon cannot be destroyed to do the quest again.
