### ISSUE TITLE
[DUNGEON] Normal Mode Boss Scaling

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2864]
**What is happening:**
Normal Mode bosses from dungeons aren't scaling up in HP even though it visually looks it.
Level 99 boss: 5.565 million HP
Level 110 boss: 46.693 million HP

Dealing 250k damage removes 3.266 million HP from level 110 boss.

**What should happen:**
Scaling for normal mode bosses in the level 98-110 dungeons needs fixing.

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/133840940-7e041286-87c6-46f2-a963-d4c171d307e6.png)

**Comment by djawl** [comment]
This bug is only present on NORMAL difficulty.

It **only** appears when you are level 110.

It **only** affects the bosses, not the trash mobs.

The dungeons that have this bug present is: Halls of Valor, Darkheart Thicket, Eye of Azshara & Assault on Violet Hold.
