### ISSUE TITLE
[Halls of Valor] Valarjar Thundercaller

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2866]
**Links:**
https://www.wowhead.com/npc=95842/valarjar-thundercaller
https://www.wowhead.com/spell=198605/thunderstrike
https://www.wowhead.com/spell=215429/thunderstrike

**What is happening:**
Valarjar Thundercaller is casting Thunderstrike only at the player with aggro. Thunderstrike is missing the stun in mythic.

**What should happen:**
Thunderstrike should aim at random players.
Thunderstrike should stun in mythic.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
