### ISSUE TITLE
[Halls of Valor] Hymdall

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2867]
**Links:**
https://www.wowhead.com/npc=94960/hymdall
https://www.wowhead.com/spell=191284/horn-of-valor

**What is happening:**
Hymdall casts Horn of Valor, and only one Storm Drake shows up.

**What should happen:**
There should be 3 drakes.

**Comment by nevarden** [comment]
After the battle ends, he is despawning. 

He should not despawn.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
