### ISSUE TITLE
[Halls of Valor] Stormforged Sentinel

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2868]
**Links:**
https://www.wowhead.com/npc=96574/stormforged-sentinel
https://www.wowhead.com/spell=210875/charged-pulse
https://www.wowhead.com/spell=199805/crackle
https://www.wowhead.com/spell=215435/sentinels-watch

**What is happening:**
Stormforged Sentinel: Casts 'Crackle' at players but nothing happens.

Isn't casting Charged Pulse.

Should buff nearby mobs with Sentinel's Watch.

**What should happen:**
Should use all abilities properly.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
