### ISSUE TITLE
quest The end of the Deserters

### ISSUE THREAD

**Issue by Lukaspolacco** [GuabinaCore/WoWKoi#287]
**Links:**
https://www.wowhead.com/quest=27213/the-end-of-the-deserters
from WoWHead or our Armory

**What is happening:**
There are no mobs on the boat only the quest target making the quest really easy 

**What should happen:**
there should be mobs around and inside the boat

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
