### ISSUE TITLE
Pesadilla Esmeralda - Cofre - Cenarius

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2874]
**Links:**
https://www.wowhead.com/object=254168/spoils-of-the-nightmare
from WoWHead or our Armory

**What is happening:**

Al matar a Cenarius en la pesadilla esmeralda no se genera su cofre de botin, debería generarse su cofre

**Comment by ShikoSCS** [comment]
Corregido
