### ISSUE TITLE
NPC - Misiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2876]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=110839/stormwing-drake
yo al atacar al npc, no reacciona, me ignora
![image](https://user-images.githubusercontent.com/81131460/133915344-207a7c8d-801c-4792-bf1b-5c0012d2c32d.png)
https://www.wowhead.com/npc=112972/giant-thicketstomper
yo al atacar al npc, no reacciona, me ignora
![image](https://user-images.githubusercontent.com/81131460/133916441-04dc9067-0b38-4465-848a-42ed65742724.png)

**What should happen:**

**Comment by Kirrkoi** [comment]
https://www.wowhead.com/npc=105547/rauren
npc no reacciona al ser atcado, es un npc hostil deberia atacarme pero nada..

https://www.wowhead.com/npc=110050/stillwater-snapper
npc roto, no se si tiene un golpe especial que me mata de un golpe cuando pega.. puedo matra al npc, pero el problema es que no deberia matar de un golpe..
![image](https://user-images.githubusercontent.com/81131460/133942608-01f93f03-3e37-4c3d-a1e5-6e108d52a7aa.png)
![image](https://user-images.githubusercontent.com/81131460/133942735-a88e6b8d-034a-4801-a72e-5c840e0ceb45.png)

https://www.wowhead.com/quest=42396/do-the-thing
asi funcioan la mision: interactúa con uno de cada uno de los elementos alrededor de Phin, incluido un pequeño cangrejo. Después de que haya una perla brillante en el suelo, saquela para completar la misión. item  (https://www.wowhead.com/item=137383/speckled-pearl) que pide la mision no se puede obtener, es visible la perla pero no se puede tomar..

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=41258/fruit-of-the-doom
el npc no me otorga esta mision
https://www.wowhead.com/item=140238/scavenged-felstone
este item(no puede ser obtenido o no esta en el juego, deberia ser implementado) inicia esta mision (https://www.wowhead.com/quest=40694/one-small-step-for-magic)

estas misiones son las siguientes
https://www.wowhead.com/quest=40713/the-black-tome
https://www.wowhead.com/quest=40919/fel-bent-for-leather
https://www.wowhead.com/quest=40642/power-get-the-power
https://www.wowhead.com/quest=42366/the-bigger-they-are-the-harder-they-fel

**Comment by Kirrkoi** [comment]
https://www.wowhead.com/npc=105554/shardmaiden
no deberia dar reputacion
![image](https://user-images.githubusercontent.com/81131460/133962117-c1b3de5e-aae0-4476-85c5-c2914979639b.png)

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=113201/thicket-manahunter
npc se encuentra como aliado, deberia ser hostil
![image](https://user-images.githubusercontent.com/81131460/134066693-2457b297-9bc3-42f4-82ba-cc7e74f04289.png)

https://www.wowhead.com/npc=112627/curious-manasaber
npc no encontrado, el npc deberia cambiarte 25 de mana antiguo por el spell (https://www.wowhead.com/spell=225401/ride-manasaber?buff)

https://www.wowhead.com/npc=111513/leyweaver-kelorin
no hay npc, el npc deberia cambiarte 25 de mana antigo por el spell (https://www.wowhead.com/spell=222174/leywoven-bulwark)

https://www.wowhead.com/npc=113455/nightborne-wretch
https://www.wowhead.com/npc=109409/nightborne-wretch
https://www.wowhead.com/npc=113449/nightborne-wretch
https://www.wowhead.com/npc=113457/nightborne-wretch
estos npc deben cambiarme 5 mana antiguo por el spell (https://www.wowhead.com/spell=225678/empathy?buff)
![image](https://user-images.githubusercontent.com/81131460/134070388-0c6e70a5-ba8c-45bf-9b70-11391470547a.png)

https://www.wowhead.com/npc=112555/flameweaver-ovin
el npc debería cambiarme 25 de mana antiguo por el spell (https://www.wowhead.com/spell=224047/flameweavers-fury?buff)
![image](https://user-images.githubusercontent.com/81131460/134069912-1333b2bf-9fee-40d0-96ba-d87de1f90f48.png)

https://www.wowhead.com/npc=113778/deactivated-security-module
npc no encontrado, el npc debería cambiarme 25 de mana antiguo por el item (https://www.wowhead.com/item=141531/powered-security-module)

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=89014/grassland-heron
npc no reacciona al ser atacado, deberia atacarme cuando le ataco..

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=114657/ley-line-node
no se que hace...
![image](https://user-images.githubusercontent.com/81131460/134742063-ca732d25-1efe-41f0-9421-7a71af61b1b8.png)

**Comment by Noahkrr** [comment]
https://www.wowhead.com/item=141409/candraels-charm
este item es exclusivamente para los cazadores de demonios, ya que les sirve para desbloquear una nueva apariencia de artefacto.. deberia ser visible y dropeado solo por cazadores de demonios

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=40424/a-desperate-journey
la mision se completa omitiendo los creditos, debería funcionar así: Siga los postes de luz para llevar Iadreth a Astoril . completar los creditos: primera area explorada, segunda area explorada y encontrar a Astoril

https://www.wowhead.com/quest=40470/quality-of-life
la mision se autocompleta, omitiendo todos los creditos de la mision

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=43331/time-to-collect
al completar la mision, no recibo este item(https://www.wowhead.com/item=140601/sixtrigger-resource-crate) es parte de la recompensa de la mision

**Comment by Noahkrr** [comment]
https://github.com/GuabinaCore/WoWKoi/issues/2787 algunas aqui

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=111383/lytheron-gloomscale
npc hostiles al atacarles no reaccionan, deberian atacarme

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=95937/hill-ettin
npc con aura hostil, al pasar en su camino , el npc no me ataca , solo respone cuando le ataco. cualquier npc hostil deberia atacarme si me cruzo en su camino..

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=97671/wingterror-ikzil
este npc esta montado en un murcielago (https://www.wowhead.com/npc=97672/fel-bat)
al pegar al npc Alaterror ikzil, este npc no responde, no se mueve de su lugar y no me ataca... su vida se renegera (al atacarle sale un mensaje objetivo no valido), si mato al murcielago, ambos npc mueren
![image](https://user-images.githubusercontent.com/81131460/135380643-aea2eb62-9995-480f-b64b-7b297b6655ef.png)
alrededor del área donde se encuentran estos npc. hay arpias muertas
https://www.wowhead.com/npc=100614/wormtalon-huntress
https://www.wowhead.com/npc=100613/wormtalon-witch

DATO: encontré información este npc(https://www.wowhead.com/npc=97671/wingterror-ikzil) es objetivo de una misión(https://www.wowhead.com/item=128966/demon-hunt-wingterror-ikzil) de sede (mision para los campeones de sede).. la mision de sede es completable.

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=106288/sylvan-bear
npc me ignora, no me ataca cuando le ataco, debería atacarme, el npc es hostil

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=100427/turbulent-lifefury
npc esta con aura de aliado, debería ser hostil..
https://www.wowhead.com/npc=98022/plague-imp
al matar al npc me otorga 75 de reputación con Tejesueños, no debería dar reputacion
https://www.wowhead.com/npc=98020/felguard-legionnaire
al matar al npc 75 de reputación con Monte Alto, no debería recibir reputacion
https://www.wowhead.com/npc=98757/pit-lord
al matar al npc me otorga 75 de reputación con Tejesueños, no debería dar reputacion

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=125951/obsidian-deathwarder
https://www.wowhead.com/npc=104733/obsidian-deathwarder
no hay npc..

**Comment by Noahkrr** [comment]
https://www.wowhead.com/item=147905/chest-of-champion-equipment
al abrir el cofre no hay items, se supone que deberia poder adquirir un item..

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=100014/withered-husk
al matar la npc, recibo 50 de reputación con Caídos de la Noche (solo hasta reputación amistoso), no debería recibir reputación..

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=42079/masquerade
al completar esta mision, se habilita el portal a Shal'Aran, lo cual esta mal, para habilitar el porta Shal'Aran es necesario hacer la mision (https://www.wowhead.com/quest=43811/lunastre-estate-teleporter-online)
https://www.wowhead.com/quest=43811/lunastre-estate-teleporter-online
al completar esta misión, no aparece el portal, debería habilitarse el portal Shal'Aran...
https://www.wowhead.com/npc=99765/wyrmtongue-toady
el npc al morir me otorga 50 de reputación con Caídos de la Noche..

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=92794/terrorfiend-bat
el npc me ignora al atacarle, el npc debería responder a cualquier ataque..

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=95717/skyhorn-interceptor
 este npc esta flotando en el aire, debería estar en terreno

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=114959/soul-engine-hound
al acercarte a los canes no revelan tu identidad, deberían romper el disfraz como lo hacen algunos nocheternas

https://www.wowhead.com/npc=115954/valthis-amaran
npc bug, tiene menos de la mitad de vida y esta  caminando sin moverse de su lugar y no se le puede atacar

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=112336/meredil-glider
este npc me ignora al atacarle, debería atarme cuando le ataco.
