### ISSUE TITLE
[Arthas] - Ashenvale - Quest: Bad News Bear-er, Id: 13848

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#288]
**Links:**
https://www.wowhead.com/quest=13848/bad-news-bear-er#comments
from WoWHead or our Armory

**What is happening:**
Speaking to Vhulgra (the flight master) opens up only the flight paths map only.

**What should happen:**
Speaking to her should open up a dialog that gives you two choices, one to get a flight to Zoram Stand (because of the quest) and the other to open up the flight paths map.

**Comment by LKArthas** [comment]
Fixed
