### ISSUE TITLE
[World Event] Brewfest - Ram Racing

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2884]
**Links:**
https://www.wowhead.com/brewfest-guide#ram-racing-quests
https://www.wowhead.com/spell=42924/giddyup
https://www.wowhead.com/quest=11409/now-this-is-ram-racing-almost
**What is happening:**
There is no fatigue counter, and the extra action button doesn't work.

**What should happen:**
Script quest

**Comment by ShikoSCS** [comment]
Fixed
