### ISSUE TITLE
Misiones de Mundo -  Suramar

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2889]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=44022/wanted-shalan (World Quest)
Al completar la mision me otorga 75 de reputación con Las Celadoras y 150 de reputación con Corte de Farondis, debería darme 150 de reputación con las Celadoras  y 150 de reputación con Caídos de la Noche 
![image](https://user-images.githubusercontent.com/81131460/134569934-3147477d-245b-403d-9357-bb8a015a8918.png)
![image](https://user-images.githubusercontent.com/81131460/134570156-d343cbdd-047e-4c44-abe8-6af06961db34.png)
Mision similar
https://www.wowhead.com/quest=44024/wanted-shalan (Rare World Quest)
otorga 250 de reputacion a los Caidos de la noche y Celadoras
https://www.wowhead.com/quest=42089/the-fallen-ones (World Quest)
Al completar la misión me otorga 75 de reputación con Caídos de la Noche, debería darme 150 de reputación con Caídos de la Noche

https://www.wowhead.com/quest=42090/skittering-subjects (World Quest)
Al completar la misión me otorga 50 de reputación con Caídos de la Noche, debería darme 150 de reputación con Caídos de la Noche

https://www.wowhead.com/quest=44012/wanted-siegemaster-aedrin (World Quest)
Al completar la mision me otorga 75 de reputación con Las Celadoras y 75 de reputación con Caídos de la Noche, debería darme 150 de reputación con las Celadoras  y 150 de reputación con Caídos de la Noche 
![image](https://user-images.githubusercontent.com/81131460/134575506-3f2047de-bef1-4087-a169-73d271133c0c.png)
mision similar
https://www.wowhead.com/quest=44023/wanted-siegemaster-aedrin (Rare World Quest)
Al completar otorgara 250 de reputacion con las Celadoras y 250 de reputacion con Caidos de la noche

https://www.wowhead.com/quest=44016/wanted-cadraeus (World Quest)
Mision de mundo comun
Al completar la mision me otorga 75 de reputacion con las Celadoras y 75 de reputacion con Caídos de la Noche, deberia darme 150 de reputacion con las Celadoras y 150 de reputacion con Caidos de la noche
![image](https://user-images.githubusercontent.com/81131460/134576701-5b110d26-ccaf-4ade-8510-d5d4273d46c8.png)

Que raro hice la misma mision pero un dia despues y con otro pj y recibo 82 de reputacion...
![image](https://user-images.githubusercontent.com/81131460/134756872-f5623350-4eaa-4e5b-9774-91bfd110b070.png)

Misión similar
https://www.wowhead.com/quest=44031/wanted-cadraeus (Rare World Quest)
Al completar otorgara 250 de reputacion con las Celadoras y 250 de reputacion con Caidos de la Noche

Misiones de mundo que no aparecen o no estan implementadas ..
https://www.wowhead.com/quest=44805/in-the-thick-of-it
https://www.wowhead.com/quest=42880/meeting-their-quota
https://www.wowhead.com/quest=44744/lifelines
https://www.wowhead.com/quest=43445/air-superiority
https://www.wowhead.com/quest=42769/court-of-stars-bring-me-the-eyes
https://www.wowhead.com/quest=43814/unspeakable-collaborators

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=42209/freeing-the-taken (Rare World Quest)
la mision de mundo esta bug , recolecto los orbes pero no puedo usarlos para liberar a los prisioneros ..
![image](https://user-images.githubusercontent.com/81131460/134616892-c6620e5c-e598-4bc2-8e07-b8f15452990d.png)

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=42962/secret-correspondence
al completar la misión recibo 75 de reputación con Caídos de la Noche, debería recibir 200 de reputación..

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=44028/wanted-lieutenant-strathmar (Rare World Quest)
al completar la misión recibo 275 de reputación con Las Celadoras y 165 de reputación con Corte de Farondis, debería recibir 250 de reputación con Las celadoras y 250 de reputación con Caídos de la Noche
![image](https://user-images.githubusercontent.com/81131460/134740037-ac783264-5b5a-4159-ba7c-b3132d588f39.png)
Misión similar
https://www.wowhead.com/quest=44019/wanted-lieutenant-strathmar (World Quest)
al completarse la mision, recibimos 150 de reputación con Las Celadoras y 150 de reputación con Caídos de la Noche

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=43930/fiends-of-telanor (World Quest)
al completar la mision, recibo 82 de reputación con Caidos de la Noche, deberia recibir 150 de reputacion con Caídos de la Noche
![image](https://user-images.githubusercontent.com/81131460/134743224-4ab6198b-6f18-4661-83bf-eecae232f47c.png)

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=42797/danger-scythemaster-cilraman (Rare Elite World Quest)
al completar la misión recibí 275 de reputación con Las Celadoras, debería recibir 350 con Las Celadoras y 350 reputación con Caídos de la Noche
![image](https://user-images.githubusercontent.com/81131460/134755658-025cb306-405e-41cb-9af8-67ceb35f9e12.png)

https://www.wowhead.com/quest=45307/claws-for-alarm (World Quest)
al completar la misión recibí 275 de reputación con Caídos de la Noche, debería recibir 350 de reputación con Caídos de la Noche
![image](https://user-images.githubusercontent.com/81131460/134757153-4f5f77a7-ee12-4235-b994-fe4b252dcc0c.png)

https://www.wowhead.com/quest=42111/aggressive-reconnaisance (World Quest)
Al terminar la misión recibí 82 de reputación con Caídos de la Noche, debería recibir 150 de reputación con Caídos de la Noche
![image](https://user-images.githubusercontent.com/81131460/134757466-e0b02414-e15e-4ed8-ad6d-411c654dce9e.png)

**Comment by Noahkrr** [comment]
Misiones de mundo no encontradas y no implementadas - Suramar
https://www.wowhead.com/quest=43807/withered-wrangling-ambervale
https://www.wowhead.com/quest=44769/arming-the-populace
https://www.wowhead.com/quest=44780/backlash
https://www.wowhead.com/quest=44158/withered-wrangling-falanaar
https://www.wowhead.com/quest=44867/contain-their-advance
https://www.wowhead.com/quest=43932/forces-of-oppression
https://www.wowhead.com/quest=44816/continued-exposure
https://www.wowhead.com/quest=43959/stelleris-shakedown
https://www.wowhead.com/quest=44801/defending-shalaran

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=42796/wanted-broodmother-shumalis (World Quest)
debería recibir 150 de reputación con las Celadoras y 150 de reputación con Caidos de la Noche
![image](https://user-images.githubusercontent.com/81131460/134791647-edfa469e-50e0-4f62-a025-2295e2374b9a.png)
con otro pj recibo otra cantidad de reputación..
![image](https://user-images.githubusercontent.com/81131460/138026438-351bad93-60b3-4e5e-96ff-3a6cacd36675.png)
https://www.wowhead.com/quest=42169/left-for-dead (World Quest)
al completar la misión he recibido 82 de reputación con Caídos de la Noche, debería recibir 150 de reputación con Caídos de la Noche
![image](https://user-images.githubusercontent.com/81131460/134791977-b29864c9-1de8-44cc-93fc-b15ea8e05378.png)
https://www.wowhead.com/quest=42071/honoring-the-past (World Quest)
al completar la misión he recibido 82 de reputación con Caídos de la Noche, debería recibir 150 de reputación con Caídos de la Noche, tambien esta bug el Monumento antiguo(https://www.wowhead.com/object=253095/ancient-monument), se puede activar varias veces para completar el credito, solo espera unos segundo y se volverá activar..

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=42725/sharing-the-wealth (Rare World Quest)
al completar la mision de mundo no he recibio reputacion, debería recibir 200 de reputación con Caídos de la Noche
https://www.wowhead.com/quest=43943/withered-army-training (World Quest)
al elegir los 400 marchitos, la misión de mundo se completa, pero no soy teletransportado a la instancia donde deberia entrenar marchitos

**Comment by Noahkrr** [comment]
https://github.com/GuabinaCore/WoWKoi/issues/2857

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=41697/danger-colerian-alteria-and-selenyi (Rare Elite World Quest)
al completar la misión he recibido 350 de reputación con las Celadoras y 250 de reputación con Monte Alto, debería recibir 350 de reputación con las Celadoras y 350 de reputación con Caídos de la Noche,
![image](https://user-images.githubusercontent.com/81131460/138024376-46db04f2-3b67-4cdc-8ead-386fd71b4859.png)

https://www.wowhead.com/quest=42795/wanted-sanaar (World Quest)
al completar la misión recibí 75 de reputación con Las Celadoras y 75 reputación con Caídos de la Noche, debería recibir 150 con Las Celadoras y 150 reputación con Caídos de la Noche
![image](https://user-images.githubusercontent.com/81131460/138025828-45b24ab7-f5e5-4cfc-b4b4-15c210c100ab.png)

**Comment by MatiasSparda** [comment]
+1
