### ISSUE TITLE
"Fate of Queen's Reprisal" Azsuna

### ISSUE THREAD

**Issue by KurosakiRuri** [GuabinaCore/WoWKoi#2896]
Links:
![image](https://user-images.githubusercontent.com/91566630/135152667-42dcfac4-c65e-461c-80a1-0e92a744cc1f.png)
https://www.wowhead.com/npc=106930/lieutenant-surtees#ends 

What is happening:
Lieutenant Surtees is not there

What should happen:
Npc should be there to turn-in the quest

**Comment by jonto999** [comment]
Still not resolved as of 11/05/2021

**Comment by Cefiro-Caecias** [comment]
Fixed.
