### ISSUE TITLE
[Halls of Valor] Storm Drake

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2897]
**Links:**
https://www.wowhead.com/npc=97068/storm-drake
https://www.wowhead.com/spell=198888/lightning-breath

**What is happening:**
When dragon casts lightning breath, it aims towards the ground near the player. Almost never hurts the player and is reaching much less than 25 yards.

**What should happen:**
The lightning breath should be a cone that reaches 25 yards.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
