### ISSUE TITLE
[Halls of Valor] Doorway & Guards

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2899]
**Links:**
https://www.wowhead.com/npc=96574/stormforged-sentinel
https://youtu.be/ly2U3jhpsOM?t=600
![image](https://user-images.githubusercontent.com/85613053/135335527-1dadfe10-e8d5-4edd-883c-f18678bb195d.png)

**What is happening:**
There are no Stormforged Sentinels guarding the doorway to Halls of Valor.

The entrance is open without any animations after receiving Odyn's Blessing.

**What should happen:**
There should be a Stormforged Sentinel on either side of the entrance to The Ephemeral Way.

The entrance should animate instead of completely disappearing.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
