### ISSUE TITLE
[Arthas/Sefrenia] - Quest Aetherion can't be killed

### ISSUE THREAD

**Issue by laurex2010** [GuabinaCore/WoWKoi#29]
**Links:**
https://www.wowhead.com/quest=13558/call-down-the-thunder
from WoWHead or our Armory

**What is happening:**
After being shrinked, Aetherion is hittable but he is only missing and blocking the attacks. He is not taking damage

**What should happen:** Aetherion should be killable after the shrink ("aparo" = miss)

Print:     https://user-images.githubusercontent.com/61942131/76165689-be2df580-6137-11ea-802f-9a65a1fd1e94.png

**Comment by LKArthas** [comment]
Fixed
