### ISSUE TITLE
[Halls of Valor] Mug of Mead

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2900]
**Links:**
https://www.wowhead.com/npc=102423/mug-of-mead
https://www.wowhead.com/spell=202287/mug-of-mead
https://www.wowhead.com/spell=202285/mug-of-mead
https://www.wowhead.com/spell=202298/mug-of-mead

**What is happening:**
**Extremely** bugged. Mug of Mead floats above the tables in the Hearth of Revelry. It currently can be grabbed and refreshed an unlimited amount of times.

Can also be used on party members to change their faction. Allows players to reset combat or skip any/everything. This can also turn your party members into non-friendly targets, preventing them from being healed, etc.

**What should happen:**
Mug of Mead should cause **all vrykul hit** to begin a brawl and become distracted for 20 secs.

Should have limited uses. Clicking a single mug of mead should remove that mug from the room.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
