### ISSUE TITLE
[Halls of Valor] Valarjar Shieldmaiden

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2901]
**Links:**
https://www.wowhead.com/npc=95832/valarjar-shieldmaiden
https://www.wowhead.com/spell=199050/mortal-hew

**What is happening:**
If the targeted player is outside of melee range before Mortal Hew finishes the cast, the cast will cancel instead of finishing.

**What should happen:**
The cast should still go off even if the player leaves melee range.  Mortal Hew **sweeps their blade** at the target.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
