### ISSUE TITLE
[Halls of Valor] Valarjar Purifier

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2902]
**Links:**
https://www.wowhead.com/npc=97197/valarjar-purifier
https://www.wowhead.com/spell=192563/cleansing-flames

**What is happening:**
Cleansing Flames is dealing no damage.

The mob runs down the stairs and prefers to melee the player over casting from range.

**What should happen:**
Cleansing Flames spell should work.

The mob should always prefer casting if able to.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
