### ISSUE TITLE
[Halls of Valor] Valarjar Aspirant

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2903]
**Links:**
https://www.wowhead.com/npc=101637/valarjar-aspirant
https://www.wowhead.com/spell=191508/blast-of-light

**What is happening:**
When Valarjar Aspirant casts Blast of Light, it doesn't aim it correctly. Very hard to get hit by it even standing in the beam 5 yards away.

**What should happen:**
The ability should deal damage up to 50 yards in front of the caster.

The group of mobs also should not immediately be in position. They should lift off from near Hyrja and then head to their position.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
