### ISSUE TITLE
[Halls of Valor] Olmyr the Enlightened & Solsten

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2904]
**Links:**
https://www.wowhead.com/npc=97202/olmyr-the-enlightened
https://www.wowhead.com/npc=97219/solsten

**What is happening:**
The NPCs are both neutral instead of hostile.

They will reset if you run 35 yards away.

When killing Solsten first, he will evade half-way through and be an invalid target. He will continue casting Eye of the Storm from then onwards.

**What should happen:**
NPCs shouldn't be neutral and should be able to drag away.
Solsten shouldn't continue casting Eye of the Storm after being defeated.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
