### ISSUE TITLE
[Halls of Valor] Hyrja

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2905]
**Links:**
https://www.wowhead.com/npc=95833/hyrja
https://www.wowhead.com/spell=200901/eye-of-the-storm
https://www.wowhead.com/spell=192307/sanctify

**What is happening:**
Eye of the Storm is only dealing damage 3 times per cast.

Sanctify swirls come out incorrectly, in a pathetic pattern.

**What should happen:**
Eye of the Storm should deal damage 6 times per cast.
Sanctify should radiate in all directions (like 3x clockwise, 3x counterclockwise, rather than 6 all in a straight line).

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
