### ISSUE TITLE
[Halls of Valor] Field of the Eternal Hunt

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2906]
**Links:**
https://www.wowhead.com/npc=101697/field-of-the-eternal-hunt
https://www.wowhead.com/npc=101712/halls-of-valor
https://youtu.be/ly2U3jhpsOM?t=419
![image](https://user-images.githubusercontent.com/85613053/135345340-24f7e00b-f0e1-409c-af23-19825dec512a.png)

**What is happening:**
Have to click on the portal to enter, able to enter while in combat, and able to bring Mug of Mead into the zone with you.
Receive a loading screen when entering instead of the expected screen transition.

**What should happen:**
Should be able to just walk up to portal and receive transition to the next zone.

**Comment by nevarden** [comment]
![image](https://user-images.githubusercontent.com/85613053/135349274-3ab7a136-2e49-4ce0-b801-195454b8c57b.png)

This Storm Drake flies away but it should come down and burn a bunch of stags.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
