### ISSUE TITLE
[Halls of Valor] Gildedfur Stag

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2907]
**Links:**
https://www.wowhead.com/npc=96609/gildedfur-stag
https://www.wowhead.com/spell=199108/frantic-gore

**What is happening:**
The **stags die immediately** after they cast Frantic Gore.

**What should happen:**
Frantic Gore should deal damage to the targeted player.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
