### ISSUE TITLE
[Halls of Valor] Valarjar Trapper

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2908]
**Links:**
https://www.wowhead.com/npc=96934/valarjar-trapper
https://www.wowhead.com/spell=199341/bear-trap

**What is happening:**
The mob throws the trap on the ground underneath itself.
Walking on the bear trap does nothing. Bear trap does not trigger.  

**What should happen:**
The mob should throw the trap at a random player.
Players should be able to trigger the trap.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
