### ISSUE TITLE
[Halls of Valor] Valarjar Falconer

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2909]
**Links:**
https://www.wowhead.com/npc=99804/valarjar-falconer
https://www.wowhead.com/npc=99828/trained-hawk
![image](https://user-images.githubusercontent.com/85613053/135349958-b12f2a8c-daee-4a98-8bb4-21ea8ea0539e.png)

**What is happening:**
Valarjar Falconer stands still the whole time.
Trained Hawk is invisible.

**What should happen:**
FIGHT

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
