### ISSUE TITLE
Ashenvale - Wrathtail Razortail Level Scaling

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#291]
**Links:**
https://www.wowhead.com/quest=6641/vorsha-the-lasher
https://imgur.com/a/jNxVynN
https://www.wowhead.com/npc=3712/wrathtail-razortail
from WoWHead or our Armory

**What is happening:**
The mob is spawning when u have the quest and it isn't scaled to your level.

**What should happen:**
The mob should scale.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
