### ISSUE TITLE
[Halls of Valor] Ebonclaw Worg

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2911]
**Links:**
https://www.wowhead.com/npc=96608/ebonclaw-worg
https://www.wowhead.com/spell=199179/leap-for-the-throat
https://www.wowhead.com/spell=199182/leap-for-the-throat
https://www.wowhead.com/spell=199177/ferocious-bite
https://www.wowhead.com/spell=199184/strength-of-the-pack

**What is happening:**
None of the spells or buffs for Ebonclaw Worg are working.

**What should happen:**
Fix Strength of the Pack, and make ferocious bite and leap for the throat cast.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.

**Comment by ShikoSCS** [comment]
Fixed
