### ISSUE TITLE
[Halls of Valor] Mythic Achievements

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2912]
**Links:**
https://www.wowhead.com/achievement=10542/i-got-what-you-mead
https://www.wowhead.com/achievement=10543/surge-protector
https://www.wowhead.com/achievement=10544/stag-party

**What is happening:**
All Halls of Valor mythic achievements can be earned through normal mode.

**What should happen:**
Should only be able to earn the achievements in the correct mode.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.

**Comment by ShikoSCS** [comment]
Fixed
