### ISSUE TITLE
[Halls of Valor] Four Vrykul Kings

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2913]
**Links:**
https://www.wowhead.com/npc=95843/king-haldor
https://www.wowhead.com/npc=97083/king-ranulf
https://www.wowhead.com/npc=97084/king-tor
https://www.wowhead.com/npc=97081/king-bjorn

**What is happening:**
Able to speak and intiate combat with all Kings while still engaged in combat with a King.

**What should happen:**
Should only be able to intiate combat with a single King until he's defeated. When there are only 2 Kings left, they should both enter combat at the same time together.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.

**Comment by ShikoSCS** [comment]
Fixed
