### ISSUE TITLE
[Halls of Valor] Odyn

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2914]
**Links:**
https://www.wowhead.com/npc=95676/odyn
https://www.wowhead.com/spell=198072/spear-of-light
https://www.wowhead.com/spell=198088/glowing-fragment
https://www.wowhead.com/spell=197961/runic-brand
https://www.wowhead.com/spell=198190/unworthy

**What is happening:**
Odyn starts out hostile

Odyn disappears after defeating him.

Runic Brand is always the same brand.

**What should happen:**
Odyn should start out friendly and need to be spoken to to initiate the fight.

Odyn should become friendly after defeating him and remain in the room.

Spear of Light should emit glowing fragments on mythic difficulty.

Players who take fatal damage during the Odyn encounter do not die, but are deemed Unworthy and carried by Valkyr to the balcony above Odyn's arena.

These players cannot re-enter the fight unless Odyn is killed or the rest of the party wipes

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
