### ISSUE TITLE
[Halls of Valor] Earlnoc the Beastbreaker

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2915]
**Links:**
https://www.wowhead.com/npc=96647/earlnoc-the-beastbreaker
https://www.wowhead.com/spell=199394/crush-smash
https://www.wowhead.com/spell=199467/crush-smash
https://youtu.be/ly2U3jhpsOM?t=1011

**What is happening:**
His Crush Smash ability doesn't do anything anything except channel.
![image](https://user-images.githubusercontent.com/85613053/135356857-db0c93fe-39ed-4425-8a47-d1d28728aa3c.png)

**What should happen:**
Swirls under players feet and having to dodge the attack.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.

**Comment by ShikoSCS** [comment]
Fixed
