### ISSUE TITLE
Ashenvale - Quest: Vorsha the Lasher, Id:6641

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#292]
**Links:**
https://www.wowhead.com/quest=6641/vorsha-the-lasher
from WoWHead or our Armory

**What is happening:**
Abandoning the quest doesn't reset the quest giver npc.

**What should happen:**
It should reset his position and the ability to give the quest again.

**Comment by LKArthas** [comment]
Event should be completed acompaning the npc abandoning the quest the npc Will still be doing the event

**Comment by Serithul** [comment]
I accompanied him till the island, died there on the first wave making the mobs disappear so I had to abandon it and take it again since he wasn't attacking or getting attacked
