### ISSUE TITLE
The nightborn prince

### ISSUE THREAD

**Issue by Arcy91** [GuabinaCore/WoWKoi#2923]
**Links:**
https://www.wowhead.com/quest=37861/the-nightborne-prince
from WoWHead or our Armory

**What is happening:**
Nothing, not able to kill the prince... he just stay in his place,

**What should happen:**
He should start to dmg

**Comment by Noahkrr** [comment]
now the quest is functional
![image](https://user-images.githubusercontent.com/81131460/139618561-4cdf19df-0e8a-4192-ab7c-5fe3ed27bb63.png)

**Comment by NightwindOI** [comment]
https://github.com/GuabinaCore/WoWKoi/issues/3067

**Comment by GuabinaCore** [comment]
Fixed, please check again and let us know
