### ISSUE TITLE
[Maw of Souls] Seacursed Slaver stuck in place

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2924]
**Links:**
https://www.wowhead.com/npc=97043/seacursed-slaver
![image](https://user-images.githubusercontent.com/85613053/136675845-9fe90fc0-eb57-410a-a5d2-5a4eac25b2c0.png)

**What is happening:**
If the Seacursed Slayer is CCed or interrupted early on before letting out the Shieldmaiden, he just breaks and stands there.

**What should happen:**
The mob should fight properly.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
