### ISSUE TITLE
[Tyce] - Maw of Souls: Seacursed Slaver

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2925]
**Links:**
https://www.wowhead.com/npc=97043/seacursed-slaver

https://www.wowhead.com/spell=198891/fracture
https://www.wowhead.com/spell=201566/swirling-muck

**What is happening:**
Seacursed Slaver is not dealing damage with fracture.
Swirling Muck damage is not positioned properly.

**What should happen:**
Give the guy his abilities.

**Comment by Cefiro-Caecias** [comment]
Problemas de spells, @ShikoSCS ^^
