### ISSUE TITLE
[Tyce] - Maw of Souls: Seacursed Soulkeeper

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2926]
**Links:**
https://www.wowhead.com/npc=97200/seacursed-soulkeeper

https://www.wowhead.com/spell=201397/brackwater-blast
https://www.wowhead.com/spell=195035/defiant-strike
https://www.wowhead.com/spell=195038/defiant-strike

**What is happening:**
Seacursed Soulkeeper is *standing still* during Defiant Strike, and missing proper swings.
Brackwater Blast damage isn't happening.

**What should happen:**
Guy should have abilities that work better.

**Comment by Cefiro-Caecias** [comment]
Problemas de spells, @ShikoSCS ^^
