### ISSUE TITLE
Cazador de Demonios - Zona de inicio

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2928]
**Links:**

from WoWHead or our Armory

**What is happening:**
hay cofres de tesoros de Mardum que no estan y algunos se abren y se cierran rápido que no se obtiene nada .. las misiones estan geniales, todo funcional en Mardum

estas misiones son de la camara de celadoras DH
https://www.wowhead.com/npc=96997/kethrazor
npc duplicado, deberia haber uno ..

https://www.wowhead.com/npc=97225/wrathguard-legate
npc no se le puede golpear, mensaje "no se puede atacar a ese objetivo", estos npc están inmoviles..
https://www.wowhead.com/npc=92782/savage-felstalker
Dato ignorar el npc muerto de la foto, el unico problema de estos npc, es que aveces cuando pasas por su camino o cerca del npc, estos no reaccionan siguen inmoviles, si les atacas reaccionan ..
![image](https://user-images.githubusercontent.com/81131460/138613407-184f3158-4207-408f-9282-190cc9b38867.png)

https://www.wowhead.com/quest=39689/illidari-we-are-leaving
al entregar completar la mision, Khadgar debería teletransportarnos hacia ventormenta.. coordenadas 72.6  47.3
video la mision: https://www.youtube.com/watch?v=asGMB9e9A3Y

**Comment by Cefiro-Caecias** [comment]
Reparado lo de Mardum. Lo de Cámaras queda pendiente de reconstrucción.
