### ISSUE TITLE
Quest: Vorsha the Lasher, Id: 6641 - 2 mobs associated level scale

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#293]
**Links:**
https://www.wowhead.com/quest=6641/vorsha-the-lasher
https://imgur.com/a/VM1u3wG
https://www.wowhead.com/npc=3715/wrathtail-sea-witch
https://www.wowhead.com/npc=12940/vorsha-the-lasher
from WoWHead or our Armory

**What is happening:**
These two mobs associated with the quest, don't level scale properly.

**What should happen:**
They should scale.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
