### ISSUE TITLE
[Darkheart Thicket] Nightmare Dweller

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2936]
Links:
https://www.wowhead.com/npc=101991/nightmare-dweller
https://www.wowhead.com/spell=204243/tormenting-eye
https://www.wowhead.com/spell=204246/tormenting-fear
![image](https://user-images.githubusercontent.com/85613053/137533200-ded497a4-3a55-4eb7-8fdc-264f40465e9b.png)

What is happening:
When Nightmare Dweller casts 'Tormenting Eye' it isn't fearing the target after the channel completes.

What should happen:
When Nightmare Dweller casts 'Tormenting Eye' it should fear the target if the channel completes.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
