### ISSUE TITLE
Map error, Un Goro

### ISSUE THREAD

**Issue by zodIIac** [GuabinaCore/WoWKoi#294]
See screenshots for exact locations.
![image](https://user-images.githubusercontent.com/47585500/77756937-203b9580-7028-11ea-8e9a-903ddd12f83b.png)
![image](https://user-images.githubusercontent.com/47585500/77756973-33e6fc00-7028-11ea-8a2e-ff348fd4d76a.png)

Got feared under texture and died.

**Comment by Cefiro-Caecias** [comment]
Possibly it is a problem of your client, and I suppose that it would be solved by downloading a new one.
