### ISSUE TITLE
[Arthas] - Ashenvale - Clattering Crawler

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#295]
**Links:**
https://www.wowhead.com/npc=3812/clattering-crawler
https://imgur.com/a/SHyI2jO
from WoWHead or our Armory

**What is happening:**
Clattering crawler is a neutral mob with hostile tooltip, unitframe and nameplate.

**What should happen:**
It should have a neutral tooltip, unitframe and nameplate.

**Comment by Cefiro-Caecias** [comment]
Arthas: es curioso, aunque este bicho tiene faction 7, sigue apareciendo como enemigo. te lo traspaso.

**Comment by LKArthas** [comment]
Fixed
