### ISSUE TITLE
[Vault of the Wardens] Grimhorn the Enslaver

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2955]
Links:
https://www.wowhead.com/npc=102566/grimhorn-the-enslaver
https://www.wowhead.com/spell=202615/torment
https://www.wowhead.com/spell=202635/torment
https://www.wowhead.com/spell=202608/anguished-souls

What is happening:
![image](https://user-images.githubusercontent.com/85613053/137535475-98e23f6f-b2f4-4c61-8c8f-73a45d9656a9.png)

1. Casts torment on the tank repeatedly.

2. Anguished Souls is being applied as a debuff to players without any ground effect.

What should happen:

1. Torment should cast on non-tanks. Torment should do AoE damage divided among nearby players.

2. Anguished Souls should be visible on the ground and avoidable.

**Comment by Cefiro-Caecias** [comment]
The area will be rebuilt later. Patience.
