### ISSUE TITLE
[Core] - Spell Monk Mistweaver - Teachings of the Monastery

### ISSUE THREAD

**Issue by Trevis77** [GuabinaCore/WoWKoi#296]
**Links:**
https://www.wowhead.com/spell=116645/teachings-of-the-monastery

**What is happening:**
As a Mistweaver monk, when you use Tiger Palm once, you gain two stacks of the buff "Teaching of the monastery".

**What should happen:**
You should gain only one stack of the buff.

**Comment by biosintesis** [comment]
Tiger Palm now apply 1 stack of the aura.
