### ISSUE TITLE
[Tyce] - Maw of Souls: The Grimewalker

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2962]
**Links:**
https://www.wowhead.com/npc=97185/the-grimewalker

**What is happening:**
 Bile Breath animation tracks the tank but the hitbox is located at the starting point of the cast.

Pool of sludge size increases dramatically suddenly.

**What should happen:**
The tank must face The Grimewalker away from the party so that Bile Breath does not affect them
Bile Breath leaves behind a stacking Disease that reduces the tank's maximum health
The Grimewalker frequently knocks nearby players back with Poisonous Slam
This deals moderate damage and creates a pool of Poisonous Sludge that gradually grows larger

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
