### ISSUE TITLE
[Maw of Souls] Skeletal Warrior

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2963]
**Links:**
https://www.wowhead.com/npc=98973/skeletal-warrior
https://www.wowhead.com/spell=198375/mortal-strike
https://www.wowhead.com/spell=198374/hamstring

**What is happening:**
Not casting abilities

**What should happen:**
The Skeletal Warriors attack the tank with Mortal Strike and Hamstring

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
