### ISSUE TITLE
[Maw of Souls] Seacursed Mistmender

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2964]
**Links:**
https://www.wowhead.com/npc=97365/seacursed-mistmender

**What is happening:**
Uses “Whirlpool of Souls” which is a Helarjar Mistcaller ability. Doesn’t cast Torrent of Souls.

**What should happen:**
Cast the correct spells

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
