### ISSUE TITLE
[Maw of Souls] Helarjar Mistcaller

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2966]
**Links:**
https://www.wowhead.com/npc=99033/helarjar-mistcaller
https://www.wowhead.com/spell=216197/surging-waters

**What is happening:**
Doesn’t cast Surging Waters.

**What should happen:**
Should cast.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
