### ISSUE TITLE
[Tyce] - Maw of Souls: Helya

### ISSUE THREAD

**Issue by nevarden** [GuabinaCore/WoWKoi#2967]
**Links:**
https://www.wowhead.com/npc=96759/helya
https://www.wowhead.com/npc=100188/piercing-tentacle
https://www.wowhead.com/spell=197117/piercing-tentacle
https://www.wowhead.com/spell=197264/taint-of-the-sea
https://www.wowhead.com/spell=197858/turbulent-waters

**What is happening:**
Helya: Doesn’t do initial gust/push-back. 

Piercing Tentacles don’t break through the floor. 

The intermission during Helya’s Submerged is missing effects. 

Swirling Water damage can trigger multiple times in a single fall. (i got hit by 4 ticks of Swirling Water at the same time). 

Taint of the Sea isn’t being cast in phase 2.

Torrent spell effect is missing.

**What should happen:**
Should have some more mechanics fixed and added.

**Comment by ShikoSCS** [comment]
Fixed
