### ISSUE TITLE
Quest Turning the Earth 

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#297]
**Links:**
https://www.wowhead.com/quest=28615/turning-the-earth
https://www.wowhead.com/npc=48965/deez-rocksnitch

**What is happening:**
Quest can be started from both npc Tanrir and npc Deez Rocksnitch

**What should happen:**
Quest can only be started from npc Tanrir

**Comment by LKArthas** [comment]
Fixed, thanks for the specific Information :) +1
