### ISSUE TITLE
artifact relics ilvl+ is not correct

### ISSUE THREAD

**Issue by ruriro** [GuabinaCore/WoWKoi#2970]
**Links:**

from WoWHead or our Armory

**What is happening:**artifact weapon start at 750 ilvl, i have 2 +10 ilvl artifact relics but they only geve +2 ilvl each.

**What should happen:**my weapon should be 770 ilvl but its only 754.

**Comment by NightwindOI** [comment]
We aim for nerfed version of that (something between 7.0 and  7.3). Thats why its like that.
