### ISSUE TITLE
the skys of highmountain

### ISSUE THREAD

**Issue by ruriro** [GuabinaCore/WoWKoi#2971]
**Links:**

from WoWHead or our Armory: https://www.youtube.com/watch?v=TKiv40BPC

**What is happening:** NPC not showing up after landing.

**What should happen:** tauren npc should be there so you can do the intro.

**Comment by ruriro** [comment]
i try it again and just before you land you see the npc but after you land hes gone, so my guess is a phasing issue.

**Comment by ruriro** [comment]
I found a way around it, instead of flying with the bird to highmountain. just fly or walk regular and take the lift down, then the npc wont phase out/away!

**Comment by Arkanheal** [comment]
Duplicate #2853
