### ISSUE TITLE
Death Knight's don't get the Runeforging ability

### ISSUE THREAD

**Issue by kikitheman** [GuabinaCore/WoWKoi#2972]
**Links:**
https://www.wowhead.com/skill=960/runeforging
https://www.wowhead.com/spell=53428/runeforging
from WoWHead or our Armory

**What is happening:**
When you create a DK at lvl 55, it should start with this skill / spell learned, but I could not find it in the spell book, nor the professions tab.  
Trying to /cast it, also doesn't work.

**What should happen:**

DK's should have the ability already learned in their spellbook.

Thanks for taking a look at this bug!

**Comment by ventarius5** [comment]
Runeforging appears in your spellbook after using boost form in-game shop (dunno about the boost NPC cuz its going to be removed on release anyway). I believe you can close the issue

![image](https://user-images.githubusercontent.com/63166930/138458428-bec4d762-64e9-449b-b5aa-8de900d321b3.png)
