### ISSUE TITLE
Apariencia oculta de arma artefacto - Cazador de demonios

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2974]
**Links:**

from WoWHead or our Armory

**What is happening:**
primero se consigue el item: https://www.wowhead.com/item=141409/candraels-charm (funcional)
despues entregamos el item al npc Candrael Twinshadow: https://www.wowhead.com/npc=113935/candrael-twinshadow (funcional)
Candrael Twinshadow, al entregar el item, el npc nos lanza hacia Downfall https://www.wowhead.com/npc=111110/downfall  y este npc dropea el item apariencia del arma artefacto de DH.. (no se ha confirmado el loot, ya que no pude lootearlo)

**What should happen:**
el npc Candrael Twinshadow, debería un dialogo opción, que nos permita volver a  intentar matar a Downfall (en caso de caer en pleno combate, morir o no recibir loot)

**Comment by Cefiro-Caecias** [comment]
Reparado.
