### ISSUE TITLE
Dark Revelations

### ISSUE THREAD

**Issue by Jellicat12** [GuabinaCore/WoWKoi#2976]
https://www.wowhead.com/quest=37449/dark-revelations#

What is happening:

NPC that follows you vanishes when you climb ramp before fight, as you change subzone into "traitor's overlook". The fight does not begin as it should, and the npc is behind an invincible shield.

What should happen:

NPC should initiate the fight.

https://www.youtube.com/watch?v=IIuN-URBRaY

**Comment by ruriro** [comment]
it worked for me, just follow npc instead since its slower then you. then you get RP and you can kill the mob.
