### ISSUE TITLE
The lone mountain quest bug

### ISSUE THREAD

**Issue by Humanzd** [GuabinaCore/WoWKoi#2979]
https://www.wowhead.com/quest=39733/the-lone-mountain

https://www.wowhead.com/quest=44700/stormheim

https://www.wowhead.com/quest=39731/the-tranquil-forest

https://www.wowhead.com/quest=39718/paradise-lost

All of these quests are not doable as a Rogue, i was able to do it on a warrior. The quests are stuck on 0/1 Travel to Dalaran.

I have tried logging out, deleting the cache folder, teleporting to dalaran, flying to dalaran via flight master, teleporting to old Wotlk dalaran, using the dalaran portal in stormwind, abandoning the quests and doing all of the above.

When i abandon the quests, as soon as i enter the rogue order hall it just auto accepts all four of them.

In the beginning i just took the highmountain quest.

![Quests](https://user-images.githubusercontent.com/93193197/138860392-6ea2298d-87f5-4123-9a8e-3d046ab6407c.jpg)

**Comment by Humanzd** [comment]
I did the quests on my warrior, there is an NPC in Skyhold (warrior order hall) that teleports you to different zones, and i just teleported to dalaran and the quest was done. There is no such npc in rogue's order hall.

**Comment by Cefiro-Caecias** [comment]
After trying various possible solutions with no satisfactory results, I was left with no choice but to add a Portal to Dalaran in the Hall, which will complete quests for you when you tap on it. Available in the next update.
