### ISSUE TITLE
Quest Bearzerker

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#298]
**Links:**
https://www.wowhead.com/quest=28614/bearzerker
https://www.wowhead.com/npc=48965/deez-rocksnitch

**What is happening:**
Quest can be started from both npc Burndl and npc Deez Rocksnitch

**What should happen:**
Quest can only be started from npc Burndl

**Comment by LKArthas** [comment]
Fixed: Again thanks for the good Information :)
