### ISSUE TITLE
fevered letter

### ISSUE THREAD

**Issue by ruriro** [GuabinaCore/WoWKoi#2987]
**Links:** 

from WoWHead or our Armory: https://www.wowhead.com/item=139523/fevered-letter#comments

**What is happening:** when you try to begin the quest you only see the word "skill" in your chatbox.
you cannot start the quest.

**What should happen:**

**Comment by Noahkrr** [comment]
You need to have learned the first aid profession .. to access the missions

**Comment by Noahkrr** [comment]
Almost all first aid missions are bug 
https://github.com/GuabinaCore/WoWKoi/issues/2754

**Comment by Sefrenia-Caecias** [comment]
Fixed.

**Comment by Cefiro-Caecias** [comment]
You must have learned First Aid.
