### ISSUE TITLE
Ashenvale - Quest: Condition Critical! (Not important)

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#299]
**Links:**
https://www.wowhead.com/quest=13958/condition-critical
https://imgur.com/a/ZyC2bUD
from WoWHead or our Armory

**What is happening:**
The turn in text doesn't say your actual race (as it states in the screenshot).

**What should happen:**
Wowhead says that it states your class, not your race so i don't know which is correct of the two. I leave it to you guys.

**Comment by LKArthas** [comment]
Fixed
