### ISSUE TITLE
the old fashioned way

### ISSUE THREAD

**Issue by ruriro** [GuabinaCore/WoWKoi#2994]
**Links:**

from WoWHead or our Armory: https://www.wowhead.com/quest=42835/the-old-fashioned-way

**What is happening:** npc buggs out cannot talk to hir to start event.
https://imgur.com/a/nV7qFwl

**What should happen:**

**Comment by Noahkrr** [comment]
the mission is functional. Exit the mission, close the game, delete the cache folder and enter the game and do the mission again.
![image](https://user-images.githubusercontent.com/81131460/140462369-d081e3af-ba51-4ed0-8979-5db32acb1033.png)

**Comment by ruriro** [comment]
i did that and now im stuck after using the shadefruit, npc just buggs out and wont tell me to use next item..

**Comment by Noahkrr** [comment]
How strange, the mission was working well yesterday I finished it without problems, surely your game data is personalized or from another server. or make sure you have deleted the cache folder from the wow

**Comment by ruriro** [comment]
i have the client from wow koi itself+ i delete my cache on every loggin. npc is even busy when i relogg/remove cache

**Comment by Noahkrr** [comment]
Maybe the mission got corrupted, they recently updated the server, please wait for this mission to fix
