### ISSUE TITLE
Casa de Subastas - buscador

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#2995]
**Links:**

from WoWHead or our Armory

**What is happening:**
el buscador de la Casa de subastas no funciona correctamente, solo puedes darle buscar y te muestra todos los ítem. también busca por filtros, pero si buscas por su nombre no funciona,.

**What should happen:**
debería poder buscar items por su nombre

**Comment by ShikoSCS** [comment]
Se trato de reproducir el error probando con el cliente en Inglés y Español y en ambos casos funciona correctamente la búsqueda. Le pedimos que verifique nuevamente y si persiste el problema nos comente como reproducir el error de manera más exacta.
