### ISSUE TITLE
Ashenvale - Quest: Thunder Peak, Id: 13879

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#300]
**Links:**
https://www.wowhead.com/quest=13879/thunder-peak
https://imgur.com/a/zyNtDiG
from WoWHead or our Armory

**What is happening:**
Thagg gives the quest as well as the proper quest giver Broyk.

**What should happen:**
Only Broyk should give you the quest.

**Comment by LKArthas** [comment]
Fixed
