### ISSUE TITLE
Death Knight creation lvl 55

### ISSUE THREAD

**Issue by Cold-Martijn** [GuabinaCore/WoWKoi#3001]
**Links:**
https://wowwiki-archive.fandom.com/wiki/Starting_a_death_knight#cite_note-nethaeraDKCreationChange-2

https://www.bluetracker.gg/wow/topic/us-en/15538775570-death-knight-creation-change/

from WoWHead or our Armory

**What is happening:**

Creating a DK should not require a lvl 55 character.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
I think I've already mentioned that the Build Level restriction for the DK is due to my personal taste for the old days of WOTLK, and it will stay that way. Thanks for your understanding ^^
