### ISSUE TITLE
Mage Class Hall "The Dreadlord's Prize"

### ISSUE THREAD

**Issue by sankii03** [GuabinaCore/WoWKoi#3002]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=41036/the-dreadlords-prize
**What is happening:**
When you complete the scenario in Violet Hold and get teleported to Hall of the Guardians, Meryl's dialogue won't finish and get you 1/1 for quest

**What should happen:**
Meryl finishing his dialogue with the other NPC and giving you credits towards the quest

**Comment by Arkanheal** [comment]
So this was fixed by the reboot

**Comment by ShikoSCS** [comment]
Fixed
