### ISSUE TITLE
Feral Articaft power

### ISSUE THREAD

**Issue by Tilttoo** [GuabinaCore/WoWKoi#3009]
I did complete questline for feral artifact but i do not get artifact item to empower my weapon to complete quest and conntinue questline.

**Comment by Vyzu** [comment]
I have the same problem, as far i know i completed everything right and didn't get any artifact power so i can complete the quest

**Comment by Cefiro-Caecias** [comment]
You must have the Artifact Weapon equipped when you take the quest, for it to score 100 points. Try again ^^
