### ISSUE TITLE
Ashenvale Sentinel - Honorable Medallion Achievement

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#301]
**Links:**
https://www.wowhead.com/npc=8015/ashenvale-sentinel
https://www.wowhead.com/achievement=10561/honorable-medallion
https://imgur.com/a/DwK7XW3
from WoWHead or our Armory

**What is happening:**
Passing by an Ashenvale Sentinel awards you the Honorable Medallion achievement as well as the Honorable Medallion ability because it's marked as a pvp target as seen in the picture.

**What should happen:**
I don't know if it should be marked as a PvP target or not but passing right by it shouldn't award you with that achievement as it should only be given to players when they first enter a battleground or arena.

**Comment by LKArthas** [comment]
Fixed
