### ISSUE TITLE
[The New Blood] still not working [Warlock]

### ISSUE THREAD

**Issue by seanwow1337** [GuabinaCore/WoWKoi#3010]
**Links:**
https://www.wowhead.com/quest=40729/the-new-blood

from WoWHead or our Armory

**What is happening:** 
cant enslave Beshtal
Vid from your server:
https://youtu.be/BB48BBuIwMs

**What should happen:**
https://youtube.com/clip/UgkxgT9RG2nv00oF_rq1362msFErplvG6G3C

**Comment by Cefiro-Caecias** [comment]
Fixed.
