### ISSUE TITLE
Forja runa faltante

### ISSUE THREAD

**Issue by MatiasSparda** [GuabinaCore/WoWKoi#3011]
**Links:** https://es.wowhead.com/spell=53428/forja-de-runas

from WoWHead or our Armory

**What is happening:** Los Dk no tenemos el skill de forjar runas

**What should happen:** Poseer el skill al realizar el instant
https://gyazo.com/c153513280273b0ede567b4f87b53b6d

**Comment by Cefiro-Caecias** [comment]
Reparado.
