### ISSUE TITLE
Tumores de repulsion

### ISSUE THREAD

**Issue by MatiasSparda** [GuabinaCore/WoWKoi#3012]
**Links:** 

from WoWHead or our Armory

**What is happening:** En la gesta del arma artefacto del DK sangre los tumores de repulsion estan flotando

![Screenshot_1](https://user-images.githubusercontent.com/47328328/141651548-06f81458-ee13-4c98-846d-29bd7d613790.png)

**What should happen:** Deberian estar a la altura del suelo ya que de esta forma no hacen daño

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
