### ISSUE TITLE
Mage class order hall - can't return quests to meryl

### ISSUE THREAD

**Issue by mefjek** [GuabinaCore/WoWKoi#3016]
**Links:**

https://www.wowhead.com/npc=102700/meryl-felstorm

**What is happening:**
cant return any quest to Meryl Felstorm

**What should happen:**

**Comment by Arkanheal** [comment]
I think this one has been fixed by the reboot

**Comment by Arkanheal** [comment]
Linked to 
[3041](https://github.com/GuabinaCore/WoWKoi/issues/3041)
[3005](https://github.com/GuabinaCore/WoWKoi/issues/3005)
[3021](https://github.com/GuabinaCore/WoWKoi/issues/3021)
probably. 
Had the same problem on [this quest](https://www.wowhead.com/quest=34981/the-only-way-to-travel)

**Comment by Jellicat12** [comment]
Same issue, have completed Ebonchill artifact scenario, but can't hand in the quest to Meryl.

**Comment by GuabinaCore** [comment]
Fixed
