### ISSUE TITLE
[They Came From the Sea]

### ISSUE THREAD

**Issue by Tilttoo** [GuabinaCore/WoWKoi#3019]
**Links:**

from WoWHead or our Armory https://www.wowhead.com/quest=47577/they-came-from-the-sea

**What is happening:** Mob do not drop head after killing them

**What should happen:** Mob should drop item

**Comment by Gazzdaa** [comment]
it dropped on the 3rd time

**Comment by Cefiro-Caecias** [comment]
Fixed.
