### ISSUE TITLE
Ashenvale - Quest: Tweedle's Tiny Package, Id: 13974

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#302]
**Links:**
https://www.wowhead.com/quest=13974/tweedles-tiny-package
https://imgur.com/a/LK6ZuK1
from WoWHead or our Armory

**What is happening:**
Stikwad also gives the quest along with Tweedle.

**What should happen:**
Only Tweedle should give the quest.

**Comment by LKArthas** [comment]
Fixed
