### ISSUE TITLE
[Druid Artifact] Nightmare Blight not spawning during [To the Dreamgrove]

### ISSUE THREAD

**Issue by Gergus** [GuabinaCore/WoWKoi#3023]
[**Links:**

from WoWHead or our Armory](https://www.wowhead.com/quest=40645/to-the-dreamgrove)

**What is happening:**

The adds spawn but no nightmare blight has spawned to cleanse the corruption. Have tried abandoning and repicking up the quest 3 times to no luck.

**What should happen:**

Nightmare blight should spawn to be able to cleanse the corruption in the Emerald Dreamway

**Comment by Cefiro-Caecias** [comment]
Fixed.
