### ISSUE TITLE
dark heart thicket

### ISSUE THREAD

**Issue by ruriro** [GuabinaCore/WoWKoi#3024]
**Links:**

from WoWHead or our Armory

**What is happening:** all the spider mobs are lvl 110. even iff the full grp was lvl 101
alo all boss machanics where overtuned to the point you get hit for 85% of your total health with an ability that should not rly almost 1 shot you.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
