### ISSUE TITLE
Drop Rate of "Crackling Leyworm Core" Takes Hours to Complete Quest

### ISSUE THREAD

**Issue by ZarisTR** [GuabinaCore/WoWKoi#3026]
Burrowing Leyworm doesn't drop enough Crackling Leyworm Core, slayed 30 of mobs only got only 1 drop. It needs hours to complete this quest with this drop rate.  Quest name: "The Death of the Eldest"

**Comment by ZarisTR** [comment]
Quest name: "The Death of the Eldest"

**Comment by ShikoSCS** [comment]
Fixed
