### ISSUE TITLE
[Tyce] - Blood Death Knight Spells + Talents

### ISSUE THREAD

**Issue by Sariet** [GuabinaCore/WoWKoi#3028]
Link1: https://www.wowhead.com/spell=55078/blood-plague
Link2: https://www.wowhead.com/spell=49028/dancing-rune-weapon#summons
Link3: https://www.wowhead.com/spell=50842/blood-boil

Edit: The application of Blood Plague from Dancing Rune Weapon disappears without casting Blood Boil for another application. 

Edit2: All applications of Blood Plague should remain until the next cast of blood boil IF Dancing Rune Weapon is not active.

https://www.youtube.com/watch?v=7Et47Xn6Suc
0:03 - 0:13
https://youtu.be/Ztpn27y9SD0
0:38 - 0:50

**Comment by Sariet** [comment]
Link1: https://www.wowhead.com/spell=219786/ossuary
Link2: https://www.wowhead.com/spell=49998/death-strike

Death Strike cost not being reduced with Talent: Ossuary.

Death Strikes cost should be reduced to 35 and should also reflect that in the tooltip when cost is being reduced so instead of showing as cost 40 it should show as cost 35.

https://www.youtube.com/watch?v=yZnuHgcEcIs
0:00 - 0:25

**Comment by Travven** [comment]
All the spell are working OK, pay more attention to those videos.
