### ISSUE TITLE
Ashenvale - Quest Item: Befouled Water Globe

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#303]
**Links:**
https://www.wowhead.com/item=16408/befouled-water-globe
https://www.wowhead.com/npc=3917/befouled-water-elemental
from WoWHead or our Armory

**What is happening:**
It dropped from the first Befouled Water Elemental i killed.

**What should happen:**
It should only drop from Tideress with a 45% drop rate as seen in wowhead.

**Comment by LKArthas** [comment]
Fixed
