### ISSUE TITLE
[Tyce] - Wind walker Monk Artifact weapon scenario

### ISSUE THREAD

**Issue by Cinnix97** [GuabinaCore/WoWKoi#3030]
**Links:**

from WoWHead or our Armory

**What is happening

During the scenario in Skywall, lilly isnt moving at all and the mobs are almost oneshotting me. My ilvl is 637 and i know how to play ww monk but the mobs are literally hitting like trains. Please fix this asap coz its impossible to play like this.

**What should happen:**
Lilly should move to trigger the next phase and i should be able to kill a group of 3 mobs.

**Comment by Arkanheal** [comment]
Can you link us the quest linked to this scenario?
