### ISSUE TITLE
Cannot Claim Truthguard - Protection Paladin Artifact Scenario

### ISSUE THREAD

**Issue by Merrena5102** [GuabinaCore/WoWKoi#3031]
**Links:**
https://www.wowhead.com/quest=42017/shrine-of-the-truthguard
from WoWHead or our Armory

**What is happening:**

I finished the Scenario and defeated Yrgrim, however when you have to click on truthguard to pick it up, nothing happens.  It just does the looting animation.

**What should happen:**
Should start the little flair cutscene for receiving Truthguard and finish the scenario.

**Comment by Cefiro-Caecias** [comment]
Fixed.
