### ISSUE TITLE
death knight missing Runeforging skill

### ISSUE THREAD

**Issue by amirhoseyn-skh** [GuabinaCore/WoWKoi#3032]
**Links:**
https://www.wowhead.com/skill=960/runeforging
**What is happening:**
the class is missing Runeforging skill

**What should happen:**
its an skill u get from dk starter area but since we are spawning in the main city its not happening and dk has no Runeforging skill

**Comment by Sariet** [comment]
This already has a post 
Here: https://github.com/GuabinaCore/WoWKoi/issues/3020

**Comment by ShikoSCS** [comment]
Fixed
