### ISSUE TITLE
"When dreams become nightmares" Stage 3 Guardian Druid Artifact Scenario

### ISSUE THREAD

**Issue by Ellevier** [GuabinaCore/WoWKoi#3033]
**Links:**

from WoWHead or our Armory
 https://www.wowhead.com/quest=40647/when-dreams-become-nightmares

**What is happening:**
Stage 3 of the scenario spawns mobs painfully slow (around 10 minutes between waves or an unknown trigger)
After some time the mob Arch-Desecrator Malithar spawns but is untargatable and the scenario is stuck from there.

**What should happen:**
After stage 3 there should be 2 more stages with the second and third assault,those don't trigger and the scene from stage 6 plays which spawns Arch-Desecrator Malithar

**Comment by ShikoSCS** [comment]
Fixed, available in the next update
