### ISSUE TITLE
Quest Altered Beasts

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#304]
**Links:**
https://www.wowhead.com/quest=28837/altered-beasts#videos
https://www.wowhead.com/npc=49161/altered-beast
https://www.wowhead.com/item=66052/mana-addled-brain
https://www.youtube.com/watch?v=PzAzpVfTKN4

**What is happening:**
ok so multiple components here get ready for the spaghetti :)
1. Mobs (id 49161) aren't scaled and are level 1.
2. Mobs are already transformed and there is a bear (https://imgur.com/a/zHbc6T1) there that is skinnable perhaps separate mob id.
3. Drop rate is 100% for the quest item (id 66052).

**What should happen:**
1. Mobs are supposed to scale.
2. Mobs are supposed to start as critters and critter size as seen in video and then transform to either a raptor/lion/flesh beast/gorilla.
3. Drop rate is supposed to be 45% for the quest item (id 66052).
4. All mobs should be skinable.
5. bear model shouldn't be used no clue why it's there (??)

**Comment by Cefiro-Caecias** [comment]
Fixed all. Available in the next update.
