### ISSUE TITLE
Mage Arifact Quest Chain: The Mage Hunter

### ISSUE THREAD

**Issue by Survikrowa** [GuabinaCore/WoWKoi#3041]
**Links:**

Quest: https://www.wowhead.com/quest=42479/the-mage-hunter

**What is happening:**
After reading 3 books u can't click on meryl. he has that "glow" around him but can't click and talk to him

**What should happen:**
Meryl should be clickable with Gossip action inside. Someone told me that he was able to after server restart

**Comment by GuabinaCore** [comment]
Fixed, please check it and let us know!
