### ISSUE TITLE
Este es MI contrato 

### ISSUE THREAD

**Issue by juan23145232** [GuabinaCore/WoWKoi#3047]
[Este es MI contrato.]

Esta quest ubicada en tumulo de penumbra en la tierras de val´sharan a la hora de querer empezar la invocacion para asesinar al npc para completar la mision, el diablillo no se puede interactuar con el, para que inicie la invocación

y normalmente, debería simplemente llegar al lugar, interactuar con el diablillo para que inicie la invocacion y listo, pero no se puede interactuar con el.

**Comment by Cefiro-Caecias** [comment]
Reparada.
