### ISSUE TITLE
Lost Mail

### ISSUE THREAD

**Issue by runehearth** [GuabinaCore/WoWKoi#3048]
**Links:**
https://www.wowhead.com/quest=41368/lost-mail
from WoWHead or our Armory

**What is happening:**
Turned in the quest and nothing happened, the mail that came back is blank

**What should happen:**
I should get a mail from the postmaster to do the rest of the quest

**Comment by Cefiro-Caecias** [comment]
There is no bug present. Return to The Postmaster for the next quest.
