### ISSUE TITLE
DK randomly unlearned Runeforging ability

### ISSUE THREAD

**Issue by kikitheman** [GuabinaCore/WoWKoi#3051]
**Links:**
https://www.wowhead.com/skill=960/runeforging
from WoWHead or our Armory

**What is happening:**
You learn the runeforging ability when you boost your character, but it seems like I've immediately lost it somehow between the Broken Shore scenario and going to Dalaran and starting my artifact weapon quest.

I've also confirmed it with another DK that also doesn't have the ability learned at lvl 101. 

**What should happen:**
You should have this ability permanently learned and not lose it. 

Thanks for taking a look at the ticket :D

**Comment by ExonHUN** [comment]
I still have this issue.

**Comment by Cefiro-Caecias** [comment]
Fixed.
