### ISSUE TITLE
[Minor issue] Floating Alliance soldier instead of DK Tier Sets in Acherus

### ISSUE THREAD

**Issue by kikitheman** [GuabinaCore/WoWKoi#3052]
**Links:**

from WoWHead or our Armory

**What is happening:**
The decorative armor sets with the DK tier armors that are hanging around the training dummy circle in Acherus have the floating models of the trigger ( an alliance soldier ) instead of the respective tier armors.

https://prnt.sc/1zht03q

**What should happen:**
The tier armors should be equipped on each alliance character I guess, or they should be floating on top of the armor rack like it was on retail.

Thanks for taking a look at the ticket :D

**Comment by Cefiro-Caecias** [comment]
Unfortunately, the spells that the models give to the mannequins do not work. I will put them in invisible mode until I find a solution, and so as not to generate suspicions ;)
