### ISSUE TITLE
Unable to start quest [Blood and Gold] id=39595

### ISSUE THREAD

**Issue by Gergus** [GuabinaCore/WoWKoi#3053]
[**Links:**](https://www.wowhead.com/quest=39595/blood-and-gold)

from WoWHead or our Armory

**What is happening:**

When right clicking the Challengers Tribute to start quest nothing happens, a message "prev" appears in chatbox.

**What should happen:**
Blood and Gold quest should begin
![CRzb3qE](https://user-images.githubusercontent.com/34123720/141664391-96f2c9ac-6582-4f4a-a75f-9fa861648d31.png)
![gR93yRe](https://user-images.githubusercontent.com/34123720/141664392-6778352e-8b7d-4eb0-b2a1-40b05369d3e7.png)

**Comment by Cefiro-Caecias** [comment]
To start that quest, you must first have completed the quest "Havi's Test" (38331). threw that item at you ahead of time. I already repair it.
