### ISSUE TITLE
Cristal efímero - Montura Hipogrifo olvidado hace tiempo

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3054]
**Links:**
https://www.wowhead.com/object=251168/ephemeral-crystal
from WoWHead or our Armory

**What is happening:**
estos cristales al clickearlo varias veces(un solo cristal), invoca un hipogrifo amistoso y recibimos la montura, lo cual esta mal porque no se cumple con la mecanica, y otro bug es que los cristales al usarse no desaparecen

**What should happen:**
pasos para obtener la montura:
primero
Debes hacer clic en cinco Cristal efímero en Azsuna dentro de las ocho horas y sin morir para recibir esta montura.
segundo
El tiempo de aparición de los cristales es de 2 a 8 horas .
tercero
Hay 99 apariciones confirmadas, consulte Puntos de generación para obtener más información.
https://www.wowhead.com/guides/reins-of-the-long-forgotten-hippogryph-mount#spawn-points

**Comment by Cefiro-Caecias** [comment]
Reparado.
