### ISSUE TITLE
Gear not giving stats

### ISSUE THREAD

**Issue by Jellicat12** [GuabinaCore/WoWKoi#3055]
**What is happening:**

My gear isn't giving stats. I have +1,364 stam from gear, and +2,458 int, which is nowhere near enough.

**What should happen:**

I should have +3,986 stam from gear, and +3,777 int
![image](https://user-images.githubusercontent.com/92908929/141668291-274fadf0-d656-4e8f-9d21-db1d19c53e25.png)
![image](https://user-images.githubusercontent.com/92908929/141668323-b4f3e692-cd98-4eb8-8720-c16c6edb4bc0.png)

**Comment by ShikoSCS** [comment]
The equipment of the promotion is a basic equipment. It is roughly the equipment you would have if you arrived leveling. Each item we check and it gives the statistics correctly. To raise the statistics you must start doing the different chains of missions in Legion, obtain your artifact, reach level 110 and then you will see how you can face much more powerful enemies.

**Comment by ShikoSCS** [comment]
https://github.com/GuabinaCore/WoWKoi/issues/3139
