### ISSUE TITLE
Assault on Skold-Ashil - Weapons not clickable

### ISSUE THREAD

**Issue by Gergus** [GuabinaCore/WoWKoi#3057]
[**Links:**
![Uploading UEwEtT4.png…]()

from WoWHead or our Armory](https://www.wowhead.com/quest=39119/assault-on-skold-ashil)

**What is happening:**

Unable to click on the weapon racks which contribute towards the Assault on Skold-Ashil bonus objective

**What should happen:**
These should be clickable

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the enxt update.
