### ISSUE TITLE
They Came From the Sea

### ISSUE THREAD

**Issue by Malvarmo** [GuabinaCore/WoWKoi#3059]
**Links:**
https://www.wowhead.com/quest=37256/they-came-from-the-sea
from WoWHead or our Armory

**What is happening:**
Head don't have 100% drop i kill him 3 times and nothing drop

**What should happen:**
Fathom-Commander Zarrin should drop head and head should have 100%

**Comment by NightwindOI** [comment]
Duplicate https://github.com/GuabinaCore/WoWKoi/issues/3019
