### ISSUE TITLE
Huln's War - Reinforcements Bugged

### ISSUE THREAD

**Issue by Desecas** [GuabinaCore/WoWKoi#3060]
**Links:**

from WoWHead or our Armory

**What is happening:**
Mobs aren't spawning for the quest

**What should happen:**
Mobs should be spawning for the quest

**Comment by Grogser** [comment]
I'am unable to move normally as the NPC that's given to me, so I can't get to the location. Therefor i need to loose the transformed form and because of that, i don't get the buff from Malfurion and can't kill the NPCs for the quest.
