### ISSUE TITLE
Side Effects May Include Mild Undeath

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#3062]
**Links:**
https://www.wowhead.com/quest=38357/side-effects-may-include-mild-undeath#guides
https://www.wowhead.com/npc=91569/volatile-bear
https://www.wowhead.com/npc=91563/volatile-sailor
**What is happening:**
Only volatile bears give credit for quest upon killing

**What should happen:**
Both Volatile Bears and Volatile Sailors should give credit upon killing

**Comment by Cefiro-Caecias** [comment]
Fixed.
