### ISSUE TITLE
The final judgment 

### ISSUE THREAD

**Issue by Tsukrik** [GuabinaCore/WoWKoi#3066]
**Links:**https://www.wowhead.com/quest=38818/the-final-judgment

from WoWHead or our Armory

**What is happening:**Runeseer Faljar Is just standing And casting And you can't fight him 

**What should happen:**There should be an event like thing where some valkyr Are Fighting bonespeakers And youre supposed to get the Runeseer to a certain health threshhold and he will cast a spell to banish you to helheim

**Comment by OnlyWATCH** [comment]
just enter the portal

**Comment by GuabinaCore** [comment]
Autocomplete  just take the portal.
