### ISSUE TITLE
Ashenvale - Raging Ancient & Ashenvale Bowman Level Scaling

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#307]
**Links:**
https://www.wowhead.com/npc=33688/raging-ancient
https://www.wowhead.com/npc=34066/raging-ancient
https://www.wowhead.com/npc=33912/raging-ancient
https://www.wowhead.com/npc=34124/raging-ancient

https://imgur.com/a/dOX970R

https://www.wowhead.com/npc=34012/ashenvale-bowman
https://www.wowhead.com/npc=33195/ashenvale-bowman
https://www.wowhead.com/npc=33914/ashenvale-bowman
from WoWHead or our Armory

**What is happening:**
As you can see from the picture, some Ancients/Bowmen aren't scaling to your level while others are.

**What should happen:**
Searching on wowhead brought up different mobs with the same name in the area so i linked in them in order to make them level scale.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
