### ISSUE TITLE
The Final Judgment [quest] not working

### ISSUE THREAD

**Issue by amirhoseyn-skh** [GuabinaCore/WoWKoi#3072]
**Links:**

[from WoWHead or our Armory
](https://www.wowhead.com/quest=38818/the-final-judgment#comments)
**What is happening:**
the quest conversation is not triggering so it cant be done

**Comment by OnlyWATCH** [comment]
just enter the portal

**Comment by GuabinaCore** [comment]
Autocomplete  just take the portal.
