### ISSUE TITLE
Forging New Strength

### ISSUE THREAD

**Issue by yshouldbrun** [GuabinaCore/WoWKoi#3074]
(https://www.wowhead.com/quest=39722/forging-new-strength)

At first i have done the quest but couldn't turn in. After that i abandoned it to retry. Now it says me "empower my artifact" which i already done before.  Trait refund npc doesn't work and I dont have ap for another trait.  

Refund npc should work or quest needs to acknowledge that i have trait.

**Comment by Cefiro-Caecias** [comment]
You must have the Artifact Weapon equipped when you take the quest, and then you receive 100 AP to complete the quest.
