### ISSUE TITLE
[Tyce] - Mage Talent: Living Bomb (Spell 44457)

### ISSUE THREAD

**Issue by Preto333** [GuabinaCore/WoWKoi#3079]
**Links:** https://youtu.be/xfRxxmt32lQ?t=425 
![image](https://user-images.githubusercontent.com/94292811/141678930-be1bb781-23e9-41b1-8aee-24fc01a74a4b.png)

from WoWHead or our Armory

**What is happening:**
When you use Living Bomb on a dying target and he dies when he still has the living bomb on him, it doesn't spread to the other targets.

**What should happen:**
 As you can see in the video at 7:05 the living bomb spreads to other nearby targets after the mob is killed.

**Comment by Arkanheal** [comment]
Link : https://www.wowhead.com/spell=44457/living-bomb
