### ISSUE TITLE
[Core] - Spell Monk - Roll while dead

### ISSUE THREAD

**Issue by Trevis77** [GuabinaCore/WoWKoi#308]
**Links:**
https://www.wowhead.com/spell=107427/roll

**What is happening:**
Using roll while dead does not make the player gain speed

**What should happen:**
Player should gain speed by using roll while being dead.

**Comment by Spydoc** [comment]
Just to add something to this ability. The roll very often breaks itself early, especially when it's used on uneven terrain.
