### ISSUE TITLE
*URGENT* "Armies of Legionfall" Quest is Enabled right at lvl 110

### ISSUE THREAD

**Issue by Adb12345** [GuabinaCore/WoWKoi#3080]
**Links:**
https://www.wowhead.com/quest=46730/armies-of-legionfall#criteria-of)

**What is happening:**

Armies of Legionfall" Quest is Enabled right at lvl 110 - u can do the quest and at the end you are at the broken shore- which is usually enabled in a later patch - access to 850 gear and more. 

**What should happen:**

Quest shouldnt be available

**Comment by GuabinaCore** [comment]
Fixed thanks for the info.
