### ISSUE TITLE
Cant gather herbs while infight, sometimes no loot at all

### ISSUE THREAD

**Issue by Adb12345** [GuabinaCore/WoWKoi#3086]
**Links:**

from WoWHead or our Armory

**What is happening:**

Cant gather herbs while infight, sometimes no loot at all

**What should happen:**

Should be gatherable while in combat, should always contain loot - experienced @starlight roses in Suramar

**Comment by Adb12345** [comment]
I could gather all herbs while in combat, but starlight roses in Suramar.

**Comment by Arkanheal** [comment]
I do think there might be a bug with node despawning after looting them.
Could you confirm that all nodes you loot despawns?

**Comment by Adb12345** [comment]
Some herbs took a while, like up to ~1.5 seconds to despawn, that happened to me only on starlight roses, soemtimes I were able to loot twice, but both times didnt give loot. 

Other herbs did despawn.

I experienced this a week ago tho, I didnt farm till now, perhaps needs further testing
