### ISSUE TITLE
Server restart

### ISSUE THREAD

**Issue by bogdan12397** [GuabinaCore/WoWKoi#3087]
**Links:**
sorry for no links

from WoWHead or our Armory

**What is happening:**
after server restarted i lost all my character specific key binding settings, aldo all my spells stayed at place (bars) where i put them. Also i would love to add that on mage my elemental presence has changed from frost to stone and back. 

**What should happen:**
server restart shouldnt affect any of personal settings. mages should have just frost elementals.

**Comment by bogdan12397** [comment]
edit: not only my keybindings but also all interface setting have been reverted to basic

**Comment by serkantarcan** [comment]
when you make a change in your settings just log off and back in so all recorded once and for all.
