### ISSUE TITLE
A good recipe list

### ISSUE THREAD

**Issue by Malvarmo** [GuabinaCore/WoWKoi#3096]
**Links:**
https://www.wowhead.com/quest=40990/a-good-recipe-list
from WoWHead or our Armory

**What is happening:**
i learn all recipe but only one count to credit https://ibb.co/6YwD8s3

https://ibb.co/L5mFN48

**What should happen:**
All recipe should count

**Comment by NightwindOI** [comment]
''Yea, it happens when u learned recipes before nomi gives u quest'' Info from Discord.

**Comment by Cefiro-Caecias** [comment]
Removed the requirement to learn recipes, to avoid possible cumulative bugs. Available in the enxt update. Quit the quest, exit the game, clear your WoW Cache, and take the quest again.
