### ISSUE TITLE
The Dreadlord's Prize

### ISSUE THREAD

**Issue by Csab4** [GuabinaCore/WoWKoi#3098]
**Links:**
https://www.wowhead.com/quest=41036/the-dreadlords-prize

**What is happening:**
the quest cannot be completed

**What should happen:**
![WoWScrnShot_111421_163932](https://user-images.githubusercontent.com/94306960/141688148-a7045594-3290-40ea-b7f0-1278613f4147.jpg)

**Comment by ShikoSCS** [comment]
An update was recently made with calibrations for that quest. Please remove the quest from your registry and try again. If the problem continues, let us know.
