### ISSUE TITLE
The Bloody Truth 

### ISSUE THREAD

**Issue by Gruszkin123** [GuabinaCore/WoWKoi#3099]
**Links:**
https://wowhead.com/quest=44041/the-bloody-truth

from WoWHead or our Armory

**What is happening:**
SI7 guys sit and one of them repeat one quote, then appear two succubi on 110lvl then one of them attack. After fight there is nothing. 

**What should happen:**
SI7 guys should talk and then quest is complete

**Comment by Arkanheal** [comment]
Do you have an update on this issue @Gruszkin123 ?

**Comment by Cefiro-Caecias** [comment]
There is no bug present. You must be in Stealth mode when you enter the room.
