### ISSUE TITLE
[Arthas] - Orgrimmar - Daily Quest: A Time to Reflect, Id: 43461

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#310]
**Links:**
https://www.wowhead.com/quest=43461/a-time-to-reflect#comments
from WoWHead or our Armory

**What is happening:**
Auto-completes.

**What should happen:**
Should ask you a question first. If your answer is wrong or you close the window, you will be prompted with a new question.

It's not that important since we don't have timewalking events etc. but since i got it and saw it, i reported it so i don't forget.

**Comment by Serithul** [comment]
Also, after completing it, talking to the NPC again, does nothing while it should open his shop.

**Comment by DeltaVortex** [comment]
Just remove it altogether imo it's an anniversary npc.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
