### ISSUE TITLE
the nightborne prince aszuna

### ISSUE THREAD

**Issue by ruriro** [GuabinaCore/WoWKoi#3100]
**Links:**

from WoWHead or our Armory

**What is happening:** mob ael'yith in aszuna bugged out, hes staying at 6% hp (someone else attacked him)
and keep using his ability's so no reset. need him for story line.

**What should happen:**

**Comment by serkantarcan** [comment]
this is working now i killed him

**Comment by GuabinaCore** [comment]
Fixed, please check again and let us know
