### ISSUE TITLE
The skies of highmountain

### ISSUE THREAD

**Issue by Gruszkin123** [GuabinaCore/WoWKoi#3102]
**Links:**
https://www.wowhead.com/quest=39387/the-skies-of-highmountain#
from WoWHead or our Armory

**What is happening:**
Cannot witnes ritual, missing npc

**What should happen:**
after landing we meet npc go with him insode hightotem see ritual, complete quest

**Comment by GuabinaCore** [comment]
Hello, retake the quest and walk there, dont use the hawk.
