### ISSUE TITLE
Garrison quest line cannot be completed if quests are done out of order

### ISSUE THREAD

**Issue by B-Sabev** [GuabinaCore/WoWKoi#3104]
**Links:**

[quests to unlock level 1 garrison](https://www.wowhead.com/guides/garrisons/quests-to-unlock-a-level-1-and-level-2-garrison)
[back to work](https://www.wowhead.com/quest=34375/back-to-work)
[a grinning problem](https://www.wowhead.com/quest=34592/a-gronnling-problem)
[establish your garrison](https://www.wowhead.com/quest=34378/establish-your-garrison)
[den of skog](https://www.wowhead.com/quest=34765/the-den-of-skog)

**What is happening:**
For Horde: the quest "establish your garrison" can be completed before the other 2 - "back to work" and "a grinning problem" which phases the empty field into the garrison hall, such that the other two quests cannot be completed. If "back to work" and "a grinning problem" aren't completed, all garrison quests don't work anymore, NPCs aren't there or they cannot be interacted with.

**What should happen:**
Make "establish your garrison" quest appear only after, "Back to Work" and  "A Gronnling Problem" and the following quest "The Den of Skog" are done. Make the master surveyor not interactable until the three pre-requisite quests are done.

**Comment by serkantarcan** [comment]
just go around the map and do the open area quests and you'll hit 100 no need to go with garrison or other stuff in WOD content.
