### ISSUE TITLE
One cutscene in DH starting zone do not play subtitles correctly

### ISSUE THREAD

**Issue by B-Sabev** [GuabinaCore/WoWKoi#3105]
**Links:**

[wowhead guide to DH starting zone quests](https://www.wowhead.com/guides/classes/demon-hunter/starting-quests)
[quest: return to the black temple](https://www.wowhead.com/quest=38729/return-to-the-black-temple)

**What is happening:**
After the quest "return to the black temple", the cutscene with Maeve Shadowsong taking the DHs as prisoners does not have subtitles. On a few occasions, the seconds of the video flash as subtitles instead of the text itself. 

**What should happen:**
The cutscene should have correct subtitles.

**Comment by serkantarcan** [comment]
delete this non sense! there are real bugs that stops you playing the game. those must be prio to be solved. don't make it crowded with no good reason.
