### ISSUE TITLE
Fate of the Queen's Reprisal quest turn in NPC in Dalaran is INVISIBLE. Worgen NPC in Greyfang Enc.

### ISSUE THREAD

**Issue by serkantarcan** [GuabinaCore/WoWKoi#3106]
**Links:**

from WoWHead or our Armory

**What is happening:**

**What should happen:**

**Comment by Arkanheal** [comment]
Can you provide us with more informations? Screenshots and/or NPC links would be appreciated :) @serkantarcan

**Comment by Cefiro-Caecias** [comment]
Fixed.
