### ISSUE TITLE
[Preparing For War] Quest (Warrior Campaign)

### ISSUE THREAD

**Issue by XeroXXP** [GuabinaCore/WoWKoi#3107]
**Links:** https://prnt.sc/1zkq1sa

**From WoWHead or our Armory:** https://www.wowhead.com/quest=43585/preparing-for-war

**What is happening:** I have the quest as you can see in the screenshot, but when I open class hall missions the missions I'm supposed to do in order to complete the quest do not appear in the class hall missions.

**What should happen:** Listed missions should appear in the class hall missions.

**Comment by Arkanheal** [comment]
Do you have any update on this issue? @XeroXXP

**Comment by Cefiro-Caecias** [comment]
Fixed.
