### ISSUE TITLE
Cry Havoc and Let Slip the Illidari! Qest problem

### ISSUE THREAD

**Issue by Cryptonboy** [GuabinaCore/WoWKoi#3108]
**Links:**
https://www.youtube.com/watch?v=tHvrpvio_lo

**What is happening:**
Mannethrel NPC is not in the camp, and I cant taught him what I've learned 

**What should happen:**
Mannethrel got to be under the tent sitting on 60.27/44.67 and when I talk with him , he need to die

**Comment by Arkanheal** [comment]
Do you have an update on this? @Cryptonboy

**Comment by Cefiro-Caecias** [comment]
Fixed.
