### ISSUE TITLE
Bug Dirige nuestra colera

### ISSUE THREAD

**Issue by NewCrooS** [GuabinaCore/WoWKoi#3109]
https://es.wowhead.com/quest=41069/dirigir-nuestra-ira
No puedo avanzar con la misión principal de los DH "Dirige nuestra cólera" por que no me da ninguna cadena de misión

**Comment by Cefiro-Caecias** [comment]
No hay bug presente. La siguiente quest la recibirás en Dalaran, aparecerá Asha Ravensong para perseguirte hasta que tomes la quest.
