### ISSUE TITLE
[Ammen Vale] Quests can be turned in twice

### ISSUE THREAD

**Issue by Frosty015** [GuabinaCore/WoWKoi#311]
**Links:** [Inoculation](https://www.wowhead.com/quest=9303/inoculation) and [Spare Parts](https://www.wowhead.com/quest=9305/spare-parts)

from WoWHead or our Armory

**What is happening:** After completing the quest requirements I'm able to turn in the quest _twice_ and am able to receive the quest rewards twice as well. The quest line does not continue onto the next  part of the quest otherwise.

**What should happen:** Quests need only be submitted once before continuing on to the next quest in the chain

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
