### ISSUE TITLE
misión bug valshara: por los viejos amigos

### ISSUE THREAD

**Issue by Eatherx** [GuabinaCore/WoWKoi#3110]
la misión se puede completar sin hacer lo que pide matar las 50 plantas, entrar a la cueva y matar a los druidas pero al matar plantas te cuenta para la misión menos entrar a dicha cueva para matar a los druidas
https://es.wowhead.com/quest=38582/por-los-viejos-amigos

**Comment by Cefiro-Caecias** [comment]
Reparada. Disponible en el próximo update.
