### ISSUE TITLE
[Tyce] - Shadow Priest artifact quest, final fight

### ISSUE THREAD

**Issue by buznac** [GuabinaCore/WoWKoi#3111]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/npc=101148/twilight-deacon-farthing

**What is happening:
He cant be killed, his health bugs on 2hp and he is immortal so you cant finish artifact questline 

**What should happen:**
He should die so you can get artifact

**Comment by Arkanheal** [comment]
Do you have an update on this issue @buznac ?
