### ISSUE TITLE
Fire Mage Ignite

### ISSUE THREAD

**Issue by Preto333** [GuabinaCore/WoWKoi#3113]
**Links:**
![image](https://user-images.githubusercontent.com/94292811/141694510-80d6b1b1-0f4b-4dec-9cea-ac53e440886f.png)

from WoWHead or our Armory

**What is happening:** Ignite only spreads to another nearby enemy every like 8 to 10 seconds (i tested in orgrimmar dummies).

**What should happen:** Ignite should spread every 2 seconds.
"Every 2 sec, your Ignites may spread to another nearby enemy." as it says on mastery tooltip.

**Comment by Arkanheal** [comment]
Do you have an update on this issue?
