### ISSUE TITLE
mision bug suavizar al objetico y enemigos bug zona valshara

### ISSUE THREAD

**Issue by Eatherx** [GuabinaCore/WoWKoi#3114]
**Links:**
https://es.wowhead.com/quest=43702/suavizar-al-objetivo
from WoWHead or our Armory

**What is happening:**

lo enemigos de esta misión no de aparecen al terminarla si no que se quedan en la zona y al hacer la misión estos enemigo no caminan por la zona si no que están estáticos pero al terminar la misión y acercarte a ellos te atacan esos enemigos solo deben aparecen cuando estas montado en el murciélago y desaparecen al completar la misión

**Comment by Cefiro-Caecias** [comment]
La zona se refaseará más adelante.
