### ISSUE TITLE
Warlock pets disappearing / not working properly

### ISSUE THREAD

**Issue by Arwyxz** [GuabinaCore/WoWKoi#3115]
Warlocks pets are disappearing on each loading screen, and when they are summoned they are back to passive and no abilities highlighted for auto use, each time they are summoned, also summon infernal and summon doomguard are set to use no abilities, they sometimes just stay AFK or auto attack with no abilities used, please fix this

**Comment by GuabinaCore** [comment]
Just close the game, delete cache folder and relogging and should be ok, please let us know if it works for you.
