### ISSUE TITLE
wrong ilvl

### ISSUE THREAD

**Issue by forgotten420** [GuabinaCore/WoWKoi#3116]
**Links:**

from WoWHead or our Armory

**What is happening:**
The items from world quests and legendaries are with wrong ilvl

**What should happen:**
![Screenshot_74](https://user-images.githubusercontent.com/94320738/141697525-c0f2a866-8747-4ea0-a4a8-69f718a5b3b4.png)
![Screenshot_75](https://user-images.githubusercontent.com/94320738/141697528-b6ae56f8-2f66-4a82-af59-5e3ceeead852.png)

**Comment by Arkanheal** [comment]
Fixed
