### ISSUE TITLE
Profession exp amounts off

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#3117]
**What is happening:**
Gathering profession exp seems to be off.  Haven't tested on herbalism yet, but for mining on a level 5 character i get 6exp per node, which is about a 10th of the exp i get for killing a level 5 mob.  killing a level 5 mob nets me 70 exp.

**What should happen:**

when a copper node is green to me the exp gained from mining would be closer to this amount(70 exp example given).  bonus exp is gained for mining or herbing a node that is orange, and yellow. green is a normal amount of exp gained.  I dont have any videos from legion retail to show this, but a 6exp gain from a copper node is very low comparing to killing mobs at that level.

**Comment by Arkanheal** [comment]
Duplicate #3168
