### ISSUE TITLE
[Dun Morogh] Pushing Forward quest unavailable

### ISSUE THREAD

**Issue by Frosty015** [GuabinaCore/WoWKoi#312]
**Links:** [Pushing Forward](https://www.wowhead.com/quest=25792/pushing-forward)

**What is happening:** For reference I'm playing as a draenei, went to the dwarf zone after hitting lvl 5 so I could go through cata leveling. I completet the previous quests in this chain, [Culling the Wendigos](https://wow.gamepedia.com/Pushing_Forward) and now no new quests appear in the Kharanos area

**What should happen:** To my understanding this quest should be available now, although I'm not too familiar with the questing process in Cata so forgive me if I'm mistaken. But no other quests are appearing in the area either

**Comment by Cefiro-Caecias** [comment]
The "Pushing Forward" quest (https://www.wowhead.com/quest=25792) will be available once you have completed the quests:

-Forced to Watch from Afar (https://www.wowhead.com/quest=313)
-The Perfect Stout (https://www.wowhead.com/quest=315)
-Culling the Wendigos (https://www.wowhead.com/quest=25667)
-Pilfered Supplies (https://www.wowhead.com/quest=25668)
-Frostmane Aggression (https://www.wowhead.com/quest=25724)

By mistake, it was required to complete an extra mission that is only for Dwarf / Gnome. Fixed. Available in the next update.
