### ISSUE TITLE
[Tyce] - Elemental Shaman Artifact Quest gets stuck before fighting Chen and Lili

### ISSUE THREAD

**Issue by hueymcduck1** [GuabinaCore/WoWKoi#3120]
**Links:**

from WoWHead or our Armory

**What is happening:**
Talk to Xuen, kill Sigurd the Giantslayer, need to talk to Xuen again, doesn't start the next portion of the quest. I ran past and was able to get the artifact and cheese the last fight. I can't complete the actual quest to progress the storyline though so it doesn't matter.

**What should happen:**
Fight Chen and Lili and progress the artifact quest

**Comment by Arkanheal** [comment]
Do you have an update on this issue @hueymcduck1 ?
