### ISSUE TITLE
[Quest] [Val'sharah] [Entangled Dreams] 

### ISSUE THREAD

**Issue by seanwow1337** [GuabinaCore/WoWKoi#3121]
**Links:**
https://www.wowhead.com/quest=38147/entangled-dreams

**What is happening:**
cannot attack the mob.

**What should happen:**

**Comment by Sariet** [comment]
https://www.wowhead.com/npc=91045/morphael
https://www.wowhead.com/quest=38147/entangled-dreams

Morphael is an invalid target.


Morphael needs to be a valid target to hit so you can kill him and complete the quest Entangled Dreams

![image](https://user-images.githubusercontent.com/88337786/141716286-a0ceeae7-07cd-4ead-b055-4c85566cc414.png)

**Comment by Arkanheal** [comment]
Do you have an update on this issue?

**Comment by Cefiro-Caecias** [comment]
Temporal bug. Solved.
