### ISSUE TITLE
Survival Hunter Disengage Talent

### ISSUE THREAD

**Issue by dojodojo2** [GuabinaCore/WoWKoi#3122]
**What is happening:**

Every time I log into the game the Disengage ability disappears from my spellbook. To fix this I have to go back to the talent tree and deselect and select the ability again, but I have to do this every single time I relog.

**What should happen:**

The Disengage ability should be in my spellbook at all times as long as I have selected the talent.

**Comment by Arkanheal** [comment]
Do you have an update on this issue? @dojodojo2
