### ISSUE TITLE
[Tyce] - Delay on fury warrior skills

### ISSUE THREAD

**Issue by Nozdormi** [GuabinaCore/WoWKoi#3126]
**What is happening:**
I was in ogrimmar practising with my warrior and I noticed that my skills were getting delayed.
They were fine at the beginning but then it started to get off, for example, when I use Bloodthirst, Raging blow and then Furious Slash, doing the normal rotation, then getting over 70 rage and using rampage, but doing it quickly, was when I noticed that the skills were not going in my commands, they started to get off track and slowing down the rotation. (Same thing happened with Whirlwind instead of Furious Slash, when aoe and I would like to let you know that I was using the artifact ability and cds as well - Battle cry/orc racial).
To be more clear, 1 ability is always behind from what I am clicking. 
For the beginning of the server this is fine, I mean while lvling, but for m+ or raiding it starts to get annoying.

**Comment by XeroXXP** [comment]
I encountered the same issue, thought it was due to lag or something, but apparently others experience this too. Would be great if it gets fixed, since fury is so spammy it will be hard to keep up steady DPS with this being an issue.

**Comment by Arkanheal** [comment]
Probably due to weird spell batching interaction. Linked with #2535 ?
