### ISSUE TITLE
Esto esta en mi contrato

### ISSUE THREAD

**Issue by NewCrooS** [GuabinaCore/WoWKoi#3128]
https://es.wowhead.com/quest=38237/esto-está-en-mi-contrato

Bug: La mision "Este es mi contrato" Habla con Daglop para empezar el ritual. No te deja hablar con Daglop en la cueva

**Comment by Cefiro-Caecias** [comment]
Puesta temporalmente en modo autocompletable. Disponible en el próximo update.
