### ISSUE TITLE
Items have the wrong tool tip information

### ISSUE THREAD

**Issue by Sariet** [GuabinaCore/WoWKoi#3131]
https://www.wowhead.com/item=130019/armplates-of-unrelenting-anguish

Items have the wrong information about Item level.

![image](https://user-images.githubusercontent.com/88337786/141720190-0953d4f1-f238-40b9-8071-a4ebfee846e9.png)

**Comment by ShikoSCS** [comment]
Excuse me, but I don't understand what you are saying is wrong. The one in wowhead shows the stats of the items but based on the recent expansion: Shadowland

**Comment by Sariet** [comment]
> Excuse me, but I don't understand what you are saying is wrong. The one in wowhead shows the stats of the items but based on the recent expansion: Shadowland

The icon shows an ilvl of 719 when the actual ilvl of the item is 699.

Regardless of the wowhead link I was making sure you knew which item I was linking but this seems to be an issue with most or all quest rewards.

**Comment by Arkanheal** [comment]
I don't get what you mean Sariet. Your screen shows an item of 719 that you have equipped (probably scaled with the level you had when you finished the quest/got the item) and another item that you don't have equipped which is 699. Could you elaborate please?
