### ISSUE TITLE
[Quest]The Story of Huln

### ISSUE THREAD

**Issue by Sariet** [GuabinaCore/WoWKoi#3133]
https://www.wowhead.com/quest=40167/the-story-of-huln

when you start the scenario and enter the Huln vehicle it breaks and will not move but all his abilities work, when you dismount the Huln vehicle you are not ported back to Thunder Totem in Highmountain and instead have to portal back manually or walk.

When you exit the Huln vehicle you should be ported back to Thunder Totem (Highmountain)

**Comment by Sariet** [comment]
https://www.wowhead.com/npc=98825/spiritwalker-ebonhorn

Spiritwalker Ebonhorn has two dialog options.

There should only be 1 Dialog option.

https://youtu.be/fBy7HE-qzIc
0:00 - 0:10

**Comment by Sariet** [comment]
https://www.wowhead.com/npc=98825/spiritwalker-ebonhorn

Spiritwalker Ebonhorn has the same dialog option always which will bring you to the Story of Huln scenario zone.

There should be no dialog option after completing The Story of Huln [Quest]https://www.wowhead.com/quest=40167/the-story-of-huln

**Comment by Sariet** [comment]
Turns out that the quest works as intended but because of the two dialog options a lot of time is wasted if you click that one instead.

The vehicle works BUT there should still only be one dialog option.

**Comment by Cefiro-Caecias** [comment]
Fixed all, 99% blizzlike. Available in the next update.
