### ISSUE TITLE
[Mob]Brimstone Destroyer

### ISSUE THREAD

**Issue by Sariet** [GuabinaCore/WoWKoi#3137]
https://www.wowhead.com/npc=93237/brimstone-destroyer

Brimstone Destroyer blocking path into the cave behind it for a quest.

Brimstone Destroyer should not be here until later in the expansion.

**Comment by Arkanheal** [comment]
Comment says otherwise on your link (https://www.wowhead.com/npc=93237/brimstone-destroyer#comments)
Closing.
