### ISSUE TITLE
Starter gear is broken and is not giving any of the stats it shows on the tooltip

### ISSUE THREAD

**Issue by Wizardenjoyer** [GuabinaCore/WoWKoi#3139]
What is happening:
This issue was previously closed without the bug being solved. Most of the instant 100 boost gear is broken and doesn't actually provide any stat other than its base armor value. I have checked Monk and Mage and most of the gear is similarly broken and are not giving ANY stats at all (other than armor). Only the trinkets, the neck, the rings and the weapons (some cloaks work, some don't) seem to be working properly.

https://github.com/GuabinaCore/WoWKoi/issues/3055

What should happen:
The gear should provide the stats actually shown on the items.

This is incredibly easy to replicate. Just create one of the classes mentioned and try any of the gear on.

**Comment by ShikoSCS** [comment]
![imagen](https://user-images.githubusercontent.com/31458085/141739943-b35663db-ae0f-48ac-8bd9-85d641b3e9d7.png)

**Comment by ShikoSCS** [comment]
![imagen](https://user-images.githubusercontent.com/31458085/141740024-e5507c27-6d69-4e18-aa8e-0fe13833476f.png)

**Comment by ShikoSCS** [comment]
The promotion team is a basic team. It is roughly the equipment you would have if you arrived leveling. Each item we check and it gives the statistics correctly. To raise the statistics you must start doing the different chains of missions in Legion, obtain your artifact, reach level 110 and then you will see how you can face much more powerful enemies.

**Comment by Wizardenjoyer** [comment]
![image](https://user-images.githubusercontent.com/13365524/141741011-1668a73d-36cf-4eff-b636-38a879849d6c.png)

**Comment by Wizardenjoyer** [comment]
As you can see from that screenshot, we have the same stats and i have almost no items equipped, because the other items give no stats at all.

**Comment by Wizardenjoyer** [comment]
![image](https://user-images.githubusercontent.com/13365524/141742057-118ac5c0-3872-4deb-ba6e-fe530514aa24.png)
This is monk, again same primary stats as your screenshot, minus the armor value

**Comment by ShikoSCS** [comment]
I already understood, I'm already checking

**Comment by ShikoSCS** [comment]
![imagen](https://user-images.githubusercontent.com/31458085/141748170-69e1834d-8eb5-4026-a398-4fd2e15c40b4.png)

**Comment by ShikoSCS** [comment]
Fixed, available in the next update
