### ISSUE TITLE
quest This IS In My Contract NOT working

### ISSUE THREAD

**Issue by Gazzdaa** [GuabinaCore/WoWKoi#3142]
https://www.wowhead.com/quest=38237/this-is-in-my-contract
What is happening:
You cannot talk to the imp to progress the quest

What should happen:
Should be able to talk to the imp and summon demon version of himself to kill it)

**Comment by NightwindOI** [comment]
duplicate https://github.com/GuabinaCore/WoWKoi/issues/3044
