### ISSUE TITLE
Quest: The Light and the Void

### ISSUE THREAD

**Issue by Jellicat12** [GuabinaCore/WoWKoi#3143]
**Links:**

[from WoWHead or our Armory](https://www.wowhead.com/quest=40938/the-light-and-the-void)

**What is happening:**

I'm not getting credit for taking the portal to Netherlight Temple. All other parts of the quest are working correctly, just not getting credit for using the portal, and therefroe can't hand it in.

![image](https://user-images.githubusercontent.com/92908929/141757012-0e6da945-66a8-4cd0-a7f4-be773bbe1da6.png)

**What should happen:**

Should get credit for using the portal.

**Comment by Arkanheal** [comment]
Do you have an update on that?

**Comment by Jellicat12** [comment]
> Do you have an update on that?

Smaily completed the quest for me in game, so don't know if this is still an ongoing issue.

**Comment by Arkanheal** [comment]
Closing for now.
