### ISSUE TITLE
lock 7.1+ content. 

### ISSUE THREAD

**Issue by menelys** [GuabinaCore/WoWKoi#3144]
remove 7.1+ content, such as:
1. questlines. upon getting 110, a player instantly gets 7.2 scenario of broken shore assault.
2. mobs and bosses in open world. there are tons of different legion forces in open world in each zone that dont belond there yet. mostly those are from 7.2 invasions, for some reasons they exist right now.
3. 7.3 ilvl and legendary vendor. no comments, this is just hilarious, getting wakening essences and 890+ wq gear. we 7.3 now or what.
4. argus(the one present right now) and (i guess) broken shore and kirin tor emissaries. obviously they didnt exist at the launch, they have to be locked.
5. order advancement. research time on release was way longer than 7.3. example: 
![image](https://user-images.githubusercontent.com/77908571/141759186-b7a7b859-f8fb-4a26-803c-712c53f21e3e.png)
6th tier of research, that allows a player to wear 2nd legendary should take 7 days, 5th tier should take 5 days and so on.

might be more, i personally didnt encounter others, tho, its more than enough things to lock\remove. will add more if encountered.
p.s. right now progressing is just stupid, with all this stuff, u have to fix that asap, right after fixing artifact. forget about some random quests in areas and focus on really important things.

**Comment by Arkanheal** [comment]
1, 3 and 4 have been fixed.
For the 5th points. I believe in 7.0.5 you could equip only one legendary given this blue post https://fr.wowhead.com/legion-legendary-items-guide#how-many-can-be-equipped-at-one-time. 
Feel free to elaborate.

**Comment by menelys** [comment]
According to wowhead, emerald nightmare raid was added in patxh 7.0.1. According to warcraftlogs for that period players used 2 legendaries on any boss fights.

**Comment by Arkanheal** [comment]
Can't remember it's been so long. ^^ I'll assume wlogs are right.

**Comment by Cefiro-Caecias** [comment]
Fixed.
