### ISSUE TITLE
[Quest] Lieutenant of the Tower

### ISSUE THREAD

**Issue by Joolifer** [GuabinaCore/WoWKoi#3146]
**Links: https://www.wowhead.com/quest=38721/lieutenant-of-the-tower**

from WoWHead or our Armory

**What is happening: Maiev and Jarod are not fighting with the player and are just standing there repeating dialogue.**

**What should happen: They should be attacking Desdel. Without them, he does too much damage.**

**Comment by Arkanheal** [comment]
Duplicate #3304. Closing
