### ISSUE TITLE
Shaman Rise, Champions

### ISSUE THREAD

**Issue by Erayde** [GuabinaCore/WoWKoi#3147]
![Screenshot_351](https://user-images.githubusercontent.com/94382034/141806584-c94953a8-8983-44b1-91a8-b9a6aa007799.png)
**Links:**

from WoWHead or our Armory

**What is happening:**i can't talk with that npc

**What should happen:**

**Comment by NightwindOI** [comment]
There are quest with the same name for every class. Will be great if some info is added.

**Comment by Arkanheal** [comment]
Do you have an update on this? @Erayde

**Comment by Erayde** [comment]
https://www.wowhead.com/quest=42383/rise-champions 
still same problem , i can't talk with that npc . i stuck on that classhall quests

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. Take the quest, leave it, and take it again. Don't forget to clear Cache, or you won't see the changes.
