### ISSUE TITLE
[Tyce] - Mining nodes in dead Npcs

### ISSUE THREAD

**Issue by ExonHUN** [GuabinaCore/WoWKoi#3148]
**What is happening:**
1. When mining a node there is a chance a basilisk spawns. I kill it, but it despawns almost instantly or maybe I can loot it, but still cant mine the corpse.
2. Some of the wild basilisk are shown on the map, as nodes, yet they are alive. Even the tooltip show it as a node to mine. This is just mindly infuriating, because it crowds the minimap and just doesnt make any sence.

**Comment by Jellicat12** [comment]
I also have the issue of having the basilisk spawn, attack, and then disappear when killed instead of being lootable.
