### ISSUE TITLE
Missing header! (quest designers)

### ISSUE THREAD

**Issue by ExonHUN** [GuabinaCore/WoWKoi#3149]
**What is happening:**
I accepted the quest: Maw of Souls: Maul of the Dead
And the header is: " Missing header! (quest designers) "

**What should happen:**
Idk but this quest is definetly part of the DK quest hall campaign.

**Comment by Cefiro-Caecias** [comment]
Mysterious bug. I have just done several tests, and that has not come out. I close the Issue O.O
