### ISSUE TITLE
[Quest] [Suramar] Into the Crevasse

### ISSUE THREAD

**Issue by black0ut23** [GuabinaCore/WoWKoi#3150]
**Links:**
(https://www.wowhead.com/quest=42227/into-the-crevasse)

**What is happening:**
When you jump into the cavern with Valewalker Farodin you don't get credit for entering the Falanaar tunnels, I've tried a few work arounds to get it to trigger haven't been able to find one yet.

**What should happen:**
After speaking to Valewalker Farodin you both jump into the Falanaar ruins from above and when you hit the water you should get credit for entering the Falanaar tunnels.

**Comment by Arkanheal** [comment]
Do you have an update on this @black0ut23 ?

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
