### ISSUE TITLE
Quest - Fate of the Queen's Reprisal

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3151]
**Links:** https://www.wowhead.com/quest=40794/fate-of-the-queens-reprisal#videos:id=106816

from WoWHead or our Armory

**What is happening:**
No NPC to complete the quest. Oh, and the book is in russian cyrillic that you have to give him (i use english in game)
![image](https://user-images.githubusercontent.com/84509345/141816661-d7b946f0-3f96-4d64-8d21-759a6c5a2a27.png)
![image](https://user-images.githubusercontent.com/84509345/141817240-9e0b77c3-7210-44f4-b02c-90bd90b25322.png)

**What should happen:**
NPC dude should stand there at the desk to complete the quest

**Comment by Cefiro-Caecias** [comment]
Fixed, blizzlike. Available in the next update.
