### ISSUE TITLE
[Tyce] - Can't pickup Work Orders (Imps, Warlock Order Hall)

### ISSUE THREAD

**Issue by Cynthilla** [GuabinaCore/WoWKoi#3152]
After creating Work Orders for Imps at Imp Mother Dyala in the Warlock Order Hall, there is no way to pick up the work order once its completed.

**Comment by Arkanheal** [comment]
Do you have an update on this @Cynthilla

**Comment by ShikoSCS** [comment]
Fixed, available in the next update
