### ISSUE TITLE
[Quest] [Azsuna] The Walk of Shame

### ISSUE THREAD

**Issue by StrangeTaste** [GuabinaCore/WoWKoi#3153]
**Links:**

https://www.wowhead.com/quest=37467/the-walk-of-shame

**What is happening:**

After completing the previous quest (Nar'thalas Still Suffers) i wasn't given the next guest from Prince Farondis (the quest giver).

**What should happen:**

Get next guest from the quest giver, so I can escort them to the entrance of the Nar'thalas Academy.

![bugreportwalk](https://user-images.githubusercontent.com/94391929/141826589-d9a5e7a8-b7ea-4122-a104-45cff2e04486.jpg)

**Comment by Cefiro-Caecias** [comment]
There is no bug present. To obtain the quest "The Walk of Shame", you must first complete these 4 quests in that area:

-Nar'thalas Still Suffers
-Children of Nar'thalas
-You Never Know Until You Scry
-Back from the dead
