### ISSUE TITLE
NPC Selling full 970ilvl Gear

### ISSUE THREAD

**Issue by phantom1004** [GuabinaCore/WoWKoi#3155]
Was checking out the server to see if it was property of SPP and stumbled upon one of our Secret NPC's that you can get full iLVL 970 gear. If you want to know where it is you can have Guabina DM me on discord.

-Noodle

**Comment by phantom1004** [comment]
[https://cdn.discordapp.com/attachments/704025977449218213/909885720863342623/unknown.png](url)

**Comment by phantom1004** [comment]
![image](https://user-images.githubusercontent.com/24859361/141842515-5de2eb93-2073-4712-99f7-15be092fc7f6.png)

**Comment by GuabinaCore** [comment]
No thanks!
