### ISSUE TITLE
[Talent - Mage - Frost] Frost Bomb 

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#3157]
**What is happening:** 
I can't seem to find a link to the spell on WowHead. I may add screenshots if needed. The Frost Bomb talent (this ID apparently: 112948) should deal damage to the main target when you proc it with Shattered Ice Lance. Right now it deals no damage to main target.

**What should happen:**
Should deal damage to main target and target around when Shattered Ice Lance is used on the target debuffed.

**Comment by Travven** [comment]
Fixed
