### ISSUE TITLE
Artifact weapon not scaling ilvl and stats

### ISSUE THREAD

**Issue by Clayrer91** [GuabinaCore/WoWKoi#3159]
**Links:**

from WoWHead or our Armory

**What is happening:** Artifact weapon not scaling item level and stats

**What should happen:** When adding or replacing the artifact relics, the level doesn't get updated. Example, Artifact base level 750, runes +20 ilvl each. Total level the weapon should have: 790. Actual weapon level: 754.

![weapon ilvl](https://user-images.githubusercontent.com/94410144/141863170-29e9d1ed-d1ae-4c06-88f4-b6ff07cfc918.png)
![Artifact Relic](https://user-images.githubusercontent.com/94410144/141863174-61cc8f1f-9f0a-4ce7-8094-b61b69aaf78a.png)

**Comment by YisGG** [comment]
i have the same problem with my artifact weapons

**Comment by MatiasSparda** [comment]
+1

**Comment by Arkanheal** [comment]
Weird, my artifact right now is 840 or smthing.

**Comment by MatiasSparda** [comment]
Fixed right Now muy artifact is 867 right now

**Comment by Arkanheal** [comment]
Okay. Closing. Thanks
