### ISSUE TITLE
[GM Ingame] - Val'shara chapter of the history is not completed [bradensbrook]

### ISSUE THREAD

**Issue by YisGG** [GuabinaCore/WoWKoi#3160]
**Links:**
https://www.wowhead.com/storyline/bradensbrook-191

**What is happening:**
I have compelted all quest needed for the completion of the chapter but i dont have the archivement and the chapter completed, in addition i have completed de next chapter of history that need bradensbrook completed to initiate the questline
![Fallo historia 1](https://user-images.githubusercontent.com/35253676/141868312-3d06b707-21c3-4650-8f6d-6452966335cf.PNG)
![Fallo historia 2](https://user-images.githubusercontent.com/35253676/141868314-98cf9ee9-cfa6-4729-a1aa-2b54143fd2c3.PNG)
![Fallo historia 3](https://user-images.githubusercontent.com/35253676/141868316-aad13247-76a9-4b5c-b229-925e089d9184.PNG)

My ingame name is Narandrias

**What should happen:**
This chapter should be completed and i should have the archivement asociated to this chapter

**Comment by Noahkrr** [comment]
cierra el juego y borra cache, deberias tener el logro, esas misiones que marcas con rojo son misiones secundarias que no forman parte del logro.
![imagen_2021-11-15_223346](https://user-images.githubusercontent.com/81131460/141891170-f6090206-d090-4fa2-b353-af687f4cbd66.png)
![imagen_2021-11-15_223426](https://user-images.githubusercontent.com/81131460/141891231-b9c6a83f-1b80-47e9-b707-b7b25c05d351.png)

**Comment by YisGG** [comment]
Sigue igual la cosa

**Comment by YisGG** [comment]
Sigue igual la cosa

**Comment by Cefiro-Caecias** [comment]
Contáctame por Discord cuando estés online, para solucionar tu problema.
