### ISSUE TITLE
[Herbalism] Spayed by the Spade ( Aetrhil Rank 1 )

### ISSUE THREAD

**Issue by Ghlimk** [GuabinaCore/WoWKoi#3161]
**Links:**https://www.wowhead.com/quest=40014/spayed-by-the-spade

**What is happening:**
I farmed nearly +150 Aetrhril https://es.wowhead.com/object=244774/aethril and i didnt get the items for the quest, it's rank 1 and its not hard to get this items, i think they dont drop correctly. I confirmed the items drops ( i couldnt get them from the plant )

**What should happen:**Harvesting Aetrhil should have a much higher chance to reward you with the items ( even both can drop in the same flower )

**Comment by ericdethman** [comment]
I got this quest, but it doesn't work, it doesn't show on the map, and even looking in the wowhead for the place, getting there there's nothing to cultivate.

**Comment by Cefiro-Caecias** [comment]
Drop raised from 2% to 50%. Available in the next update.
