### ISSUE TITLE
The Nightborne Prince bugged

### ISSUE THREAD

**Issue by Skullcowboy** [GuabinaCore/WoWKoi#3163]
**Links:**

from WoWHead or our Armory: https://www.wowhead.com/quest=37861/the-nightborne-prince

**What is happening:**

Quest mob is in correct spot but can't be engaged. 

**What should happen:**

Mob should start dialogue as he is approached and should become targetable. Currently, I can run on top of him and nothing occurs.

**Comment by Ghlimk** [comment]
I did this quest yesterday without problem, there must be something weird that bugs the npc.

**Comment by Skullcowboy** [comment]
> I did this quest yesterday without problem, there must be something weird that bugs the npc.

I'm going to try again tonight to see if maybe it was just something weird going on. I ran up to start him after logging back in, maybe thinking I bugged out or something and thought I saw a Paladin's consecration but didn't see anyone else around. Funny enough, that happened at Runos as well, saw the ability but no one around.

**Comment by GuabinaCore** [comment]
Fixed, please check again and let us know
