### ISSUE TITLE
Ancient mana looted from mining in Stormheim

### ISSUE THREAD

**Issue by Jellicat12** [GuabinaCore/WoWKoi#3164]
**What is happening:**

Mined a felslate seam in Stormheim, and received 3 ancient mana.  
![image](https://user-images.githubusercontent.com/92908929/141958263-741a4ae0-9fc4-46e1-a869-79547b01e428.png)

**What should happen:**
Shouldn't be getting ancient mana in Stormheim.

**Comment by Jellicat12** [comment]
Update: appears to only happen when I mine felslate. Leystone doesn't give mana.

Edit: have now also received ancient mana from leystone. still appears more frequently from felslate.

**Comment by Arkanheal** [comment]
Do this bug still occurs?

**Comment by Jellicat12** [comment]
![image](https://user-images.githubusercontent.com/92908929/143524271-ffe362e7-e010-43af-b8dd-2398c07ff287.png)

yes, just tested, this is still happening

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
