### ISSUE TITLE
Nomi appearance quest

### ISSUE THREAD

**Issue by Jellicat12** [GuabinaCore/WoWKoi#3165]
**Links:**

https://www.wowhead.com/quest=40988/too-many-cooks

**What is happening:**

Nomi appeared and offered me his cooking quest after I mined a leystone ore node 
![image](https://user-images.githubusercontent.com/92908929/141958905-3d667670-b936-4c65-bdbd-363a523544e3.png)

**What should happen:**

Nomi shouldn't be offering this quest after mining - he should be offering it after looting a recipe

**Comment by Cefiro-Caecias** [comment]
Fixed.
