### ISSUE TITLE
[Tyce] - Mobs which can be mined when killed appearing on minimap

### ISSUE THREAD

**Issue by Jellicat12** [GuabinaCore/WoWKoi#3166]
**What is happening:**

With find minerals active, mobs which can be mined when killed appear on the minimap

![image](https://user-images.githubusercontent.com/92908929/141959490-d2df34f7-3096-4847-85c2-e6e0a3d63fdd.png)

**What should happen:**

They shouldn't appear on the minimap

**Comment by YisGG** [comment]
This is a bug? I thought it was normal, if this is a bug, it occurs with the mobs that can be gatherer with herbalism

**Comment by Jellicat12** [comment]
> This is a bug? I thought it was normal, if this is a bug, it occurs with the mobs that can be gatherer with herbalism

Happened with skinning too during beta, as in, you can see alive animals on the map which can be skinned if you kill them. It's been a while since Legion was live, but I'm 99.5% sure that that wasn't the case in live.
