### ISSUE TITLE
[HoV] Combat bug and boss HP

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#3167]
Bosses just gets one shotted in normal mode (probably scaling problem, linked to [this](https://github.com/GuabinaCore/WoWKoi/issues/2864) )
If a drake is up on first boss and you kill it, you stay in combat forever which means you can't engage the last 4 mini bosses and can't finish the dungeon.
You shouldn't be able to take the portal to Fenryr while in combat.

**Comment by Cefiro-Caecias** [comment]
On reconstruction.
