### ISSUE TITLE
Mining not rewarding xp

### ISSUE THREAD

**Issue by Jellicat12** [GuabinaCore/WoWKoi#3168]
**What is happening:**

Mining leystone and felslate mineral nodes rewards zero xp. 

**What should happen:**

mining should reward xp, somewhere around 2x - 4x the amount of a mob kill

**Comment by Ghlimk** [comment]
This also should happens with all the plants:

https://es.wowhead.com/object=272782/gloria-astral
https://es.wowhead.com/item=124106/matojo-vil#gathered-from-object
https://es.wowhead.com/object=244778/rosa-luz-estelar
https://es.wowhead.com/object=244777/fjarnskaggl
https://es.wowhead.com/object=241641/flor-de-raposa
https://es.wowhead.com/object=244775/frondasueño
https://es.wowhead.com/object=244776/frondasueño
https://es.wowhead.com/object=244774/aethril

- A guide to legion herbalism - https://es.wowhead.com/legion-herbalism-guide

**Comment by Cefiro-Caecias** [comment]
Insoluble for the moment.
