### ISSUE TITLE
Flying in Stormheim

### ISSUE THREAD

**Issue by Jellicat12** [GuabinaCore/WoWKoi#3169]
**What is happening:**

I can fly in Stormheim 
![image](https://user-images.githubusercontent.com/92908929/141967616-471ad398-9df8-4228-a944-e94dac8b275f.png)

**What should happen:**

I should not be able to fly anywhere in the Broken Isles

**Comment by Jellicat12** [comment]
After dismounting I am no longer able to fly. Still, bug!

**Comment by GuabinaCore** [comment]
Ok thanks for the info.
