### ISSUE TITLE
Geir is too stronk, we are fighting alone

### ISSUE THREAD

**Issue by Savenir** [GuabinaCore/WoWKoi#3172]
https://wowpedia.fandom.com/wiki/Victory_is_Eternal

Geir is just way too stronk, on retail we are fighting with army.

**Comment by gigaslurp** [comment]
[Victory Is Eternal](https://www.wowhead.com/quest=39853/victory-is-eternal) Quest 39853
**What Is Happening:**
You walk up to geir and there's a bunch of Valkyra Guardians just standing around him. You attack him and the Valkyra Guardians continue to stand there doing nothing.
**What should be happening:**
The Valkyra Guardians are meant to assist you in killing him.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the enxt update.
