### ISSUE TITLE
Kel'danath's Legacy

### ISSUE THREAD

**Issue by HelooxD** [GuabinaCore/WoWKoi#3174]
In this quest you need to charm 5 Withered but you do not get the item to charm them

**Comment by Noahkrr** [comment]
I took the mission and it works fine for me, you must abandon the mission and relocate, if it does not work, clear the cache and return to the game.
![sfsf](https://user-images.githubusercontent.com/81131460/142270923-94ae75a1-cfb3-498d-8504-a67643d7ac57.PNG)

**Comment by Arkanheal** [comment]
Do you have an update? @HelooxD

**Comment by Fixencsalok** [comment]
Same problem for me. Disabled all my addons, cleared cachce folder, took the quest again, but still no button.

**Comment by Cefiro-Caecias** [comment]
Fixed.
