### ISSUE TITLE
Suramar bugged quest eminent-grow-main

### ISSUE THREAD

**Issue by Adb12345** [GuabinaCore/WoWKoi#3176]
**Links:**
https://www.wowhead.com/quest=41494/eminent-grow-main

**What is happening:**
Clicking the thing, she says ITS DONE yey then nothing, quest should be completed afterwards

**What should happen:**
 quest should be completed after she saying ITS DONE

**Comment by bogdan12397** [comment]
confirming this bug today, npc doesnt move or cast anything but it should
link of video > https://youtu.be/WYWo2suOChk

**Comment by Noahkrr** [comment]
I also have the same problem, the mission does not work

**Comment by GuabinaCore** [comment]
autocomplete until fix. please abandon the quest and take it again Thanks!
