### ISSUE TITLE
[Arthas] - Quest Mor'shan Caravan delivery

### ISSUE THREAD

**Issue by cyberfreak666** [GuabinaCore/WoWKoi#318]
https://www.wowhead.com/quest=29111/morshan-caravan-delivery
Well I finally was able to beat the quest but the turn in NPC Kadrak is not there. 
I think the reason is I had done all the Ashenvale quest and he is at splinter tree.
Is there some way to implement a remote turn in like they do with alot of quest that could resolve the issue.

**Comment by RygardNin** [comment]
Same for me. I complete Ashenvale entry questline and that moves Kadrak to Splinter Tree. He has no yellow question mark above his head, unable to complete. This quest finishes a quest line for Northern Barrens questing achievment.
