### ISSUE TITLE
Enemy mobs deal crushing damage

### ISSUE THREAD

**Issue by Blasiiren** [GuabinaCore/WoWKoi#3180]
**What is happening:**
Every enemy is dealing critical(crushing) damage in every hit, at least to my rogue.

**What should happen:**
Enemy should not be dealing critical(crushing) damage with every attack.

**Comment by Arkanheal** [comment]
Every single enemy? @Blasiiren  or just specific ones?

**Comment by Arkanheal** [comment]
Probably linked to #3255

**Comment by Blasiiren** [comment]
Every single one, no matter what level. Be it the small minion enemies, or elites, or normal mobs.

**Comment by Arkanheal** [comment]
Is it only to your rogue? or on your other characters as well?

**Comment by Blasiiren** [comment]
People in the discord reported having the same issue.

**Comment by Arkanheal** [comment]
Not on every mob though. see #3255

**Comment by Cefiro-Caecias** [comment]
Fixed.
