### ISSUE TITLE
Elites Azuna

### ISSUE THREAD

**Issue by NewCrooS** [GuabinaCore/WoWKoi#3181]
Arañuelo de flujo vil Estos enemigos tiene un daño excesivo Me pegaron 146192 de un golpe
![imagen_2021-11-16_151809](https://user-images.githubusercontent.com/94256935/142042672-05638107-5abc-41b1-a136-e77c217e302e.png)

**Comment by NewCrooS** [comment]
Hola soy yo denuevo :) pude pasar su defensa de arañuelos mamados y me encontre con el elite el cual me cargo una técnica y me borro el pj (en sentido figurado) 
![imagen_2021-11-16_152315](https://user-images.githubusercontent.com/94256935/142043392-9af31618-93e1-4bf3-9262-b861d632d62e.png)

**Comment by NewCrooS** [comment]
"Hijo de playero" también están desbalanceados se encuentran en la playa de manantial Nor´danil
![imagen_2021-11-16_164123](https://user-images.githubusercontent.com/94256935/142054327-8c7d5c65-7997-430f-a3fa-2a318cdab0fa.png)

**Comment by NewCrooS** [comment]
Los adds de arcavellus también están desbalanceados. En realidad directamente no me tiro ningún resumen de muerte.
![imagen_2021-11-16_170022](https://user-images.githubusercontent.com/94256935/142056996-81b70e12-00cc-461e-a92a-f919f9c022c6.png)

**Comment by Cefiro-Caecias** [comment]
Reparados. Disponibles en el próximo update.
