### ISSUE TITLE
[Tyce] - Finding a gateway mission in class hall missions

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3183]
**Links:** i dont know what to link here https://www.wowhead.com/mission=648/finding-a-gateway

from WoWHead or our Armory

**What is happening:**
i managed to fail the mission at 95% chance, but now when i want to open the class hall mission table this windows appears saying the mission is a success, and when i click on the chest to see my reward, nothing is there and i cant advance (grey Next) to do other missions
![image](https://user-images.githubusercontent.com/84509345/142054182-5d36fbef-ecb2-49a8-be0a-24d0fdbf2f8d.png)

**What should happen:**
as i failed i should still click next

**Comment by Arkanheal** [comment]
This happens sometimes, I have to find a way of reproducing it (you can probably, quit the game & delete cache to get unlocked if needed)
