### ISSUE TITLE
Frost mage artifact quest

### ISSUE THREAD

**Issue by bogdan12397** [GuabinaCore/WoWKoi#3184]
Last quest in chain called "The mage hunter" first got bugged like 3-4 days ago when i completed it but couldnt hand in after. 
So i tried to retake quest but then i realize its impossible to loot another ebonchill and so its impossible to complete quest.

How it should be:
well npc that is used for completing quest should not desapier or not be able to finish it. also if i took quest again and it says i should loot something but i already have that item it should auto complete. 
My char name is "necestinigde" please if you can complete this for me..

**Comment by GuabinaCore** [comment]
Fixed, should be working ok now!
