### ISSUE TITLE
[Tyce] - Spell Horn of Helheim (190895)

### ISSUE THREAD

**Issue by Cynthilla** [GuabinaCore/WoWKoi#3185]
La spell Horn of Helheim (190895) no funciona durante las quests "Break the Spine" y "Stem the Tide". debería invocar 3 vrykuls que te ayudan en la batalla. Su segundo efecto funciona bien, que es linkearte la siguiente spell, Guardian orbs (190919).

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. I refer Core devs to repair the spell "Horn of Helheim" (190895)
