### ISSUE TITLE
[Inscription quest] The Legacy Passed On

### ISSUE THREAD

**Issue by MicuRazvan-Florentin2E3** [GuabinaCore/WoWKoi#3187]
**Links:**
https://www.wowhead.com/quest=39956/the-legacy-passed-on#videos

**What is happening:**
Behind the dwarf should be a table which is not and when you click the NPC "Bill Spearshaker" you should have some chat options to chose from.
https://imgur.com/a/ur5oQmH

**What should happen:** The table to be there and the chat options from NPC.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
