### ISSUE TITLE
[Tyce] - Mission table level problems

### ISSUE THREAD

**Issue by Jellicat12** [GuabinaCore/WoWKoi#3188]
**Links:**

https://www.wowhead.com/legion-class-hall-mission-guide#champions-paladin

**What is happening:**

On receiving Liadrin and Tyrosus as followers, they were level 107 and 110 respectively. As such, I am only receiving level 110 missions, which are much harder to complete due to Liadrin's lower level.

Additionally I am not able to attach Liadrin as a combat ally.

**What should happen:**

They should have been level 100 on joining. I should be being offered lower level missions. I should be able to use Liadrin as a combat ally.

**Comment by Arkanheal** [comment]
Related to all classes. Updating title
