### ISSUE TITLE
Frost mage talent/stats "lost"

### ISSUE THREAD

**Issue by bogdan12397** [GuabinaCore/WoWKoi#3190]
**Links:**

from WoWHead or our Armory

**What is happening:**
aperently i lost either all my status from items or/and my tallents while questing in Highmountain. to be more precise i think it happened either after i completed quests witch went to azhara and made me kill ton of legion there with some NPC i got, or after i went for quest chain which lead up to deathwing in cave (sorry for not mentioning specific names of quests).
i notice this as frost mage with tallent for splliting ice (my ice lance should hit 2 targets) but that doesnt work anymore

**What should happen:**
i should not lose status or talent bonuses during any part of game, except if its not quest specific related.

**Comment by Cynthilla** [comment]
This happened to me too on my warlock in highmountain, had to reset my talents for it to work again.

**Comment by bogdan12397** [comment]
After del. wow cache folder problem seems to be fixed..

**Comment by GuabinaCore** [comment]
Ok nice
