### ISSUE TITLE
"A Desperate Journey"

### ISSUE THREAD

**Issue by Cynthilla** [GuabinaCore/WoWKoi#3192]
Quest doesn't work. It autocompletes, but at the location where you are supposed to turn it in, no one stands. Telling the NPC to go doesn't do anything.
![image](https://user-images.githubusercontent.com/15199664/142097350-f4d7d924-4b3a-4859-9bb2-7fd57b454f48.png)
![image](https://user-images.githubusercontent.com/15199664/142097537-4f7b8e8f-779a-48c4-9037-5f9749c38d21.png)

**Comment by Cynthilla** [comment]
After walking around a bit I found the NPC you have to turn the quest into. Quest is still bugged though, and the initial quest turn in location on the map is incorrect and misleading.

**Comment by Cefiro-Caecias** [comment]
Fixed, blizzlike. Available in the next update. Don't forget to abandon the quest and clear Cache, or you won't see the new changes.
