### ISSUE TITLE
The Blood of Demons

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3195]
**Links:** https://www.wowhead.com/quest=37447/the-blood-of-demons

from WoWHead or our Armory

**What is happening:**
These crystals gets outlined with a tooltip, but they do not give anything upon use
![image](https://user-images.githubusercontent.com/84509345/142166531-ec2b7604-85d6-4701-98f2-1269086019c3.png)

**What should happen:**
Not getting outlined like it has anything to do with the quest

**Comment by Cefiro-Caecias** [comment]
That crystal was mistakenly targeted for the quest. Fixed, available in the next update.
