### ISSUE TITLE
[Tyce] - Addon messages interpreted as chat, triggers spam filter

### ISSUE THREAD

**Issue by xdpirate** [GuabinaCore/WoWKoi#3196]
**What is happening:**
Addon messages are being interpreted as chat messages. I haven't said anything on any channel as you can see here:

![image](https://user-images.githubusercontent.com/1757462/142176433-b00fade5-4846-4d96-8166-50ba79b395f0.png)

**What should happen:**
Addon messages are not chat messages. A lot of addons send a lot of messages on hidden channels and addon channels to broadcast and communicate with other player addons. Addon messages should not trigger any sort of flood detection when they are not posted to public, viewable channels.

**Comment by Arkanheal** [comment]
Can you give us a screenshot of your add-on list?

**Comment by xdpirate** [comment]
These are all either 7.3.5 versions of the addons or 7.x versions where 7.3.5 versions aren't specifically available. All of them were sourced from Curseforge. The NoGryph addon is self made, but does not communicate, it only hides the actionbar gryphons.

!Swatter
Altoholic
Altoholic_Achievements
Altoholic_Agenda
Altoholic_Characters
Altoholic_Grids
Altoholic_Guild
Altoholic_Search
Altoholic_Summary
Archy
AtlasLoot
AtlasLoot_BurningCrusade
AtlasLoot_Cataclysm
AtlasLoot_Classic
AtlasLoot_Collections
AtlasLoot_Crafting
AtlasLoot_Factions
AtlasLoot_Legion
AtlasLoot_MistsofPandaria
AtlasLoot_Options
AtlasLoot_PvP
AtlasLoot_WarlordsofDraenor
AtlasLoot_WorldEvents
AtlasLoot_WrathoftheLichKing
Auc-Advanced
Auc-Filter-Basic
Auc-ScanData
Auc-Stat-Histogram
Auc-Stat-iLevel
Auc-Stat-Purchased
Auc-Stat-Simple
Auc-Stat-StdDev
Auc-Util-FixAH
AutoRepair
BadBoy
BadBoy_CCleaner
BadBoy_Ignore
BadBoy_Levels
Bagnon
Bagnon_Config
Bagnon_GuildBank
Bagnon_VoidStorage
BankStack
BeanCounter
BGDefender
Broker_SmartBuff
Buffet
Chatter
DataStore
DataStore_Achievements
DataStore_Agenda
DataStore_Auctions
DataStore_Characters
DataStore_Containers
DataStore_Crafts
DataStore_Currencies
DataStore_Garrisons
DataStore_Inventory
DataStore_Mails
DataStore_Pets
DataStore_Quests
DataStore_Reputations
DataStore_Spells
DataStore_Stats
DataStore_Talents
DBM-AntorusBurningThrone
DBM-AQ20
DBM-AQ40
DBM-Argus
DBM-Azeroth
DBM-Azeroth-BfA
DBM-BaradinHold
DBM-BastionTwilight
DBM-BlackrockFoundry
DBM-BlackTemple
DBM-BlackwingDescent
DBM-Brawlers
DBM-BrokenIsles
DBM-BWL
DBM-ChamberOfAspects
DBM-Coliseum
DBM-Core
DBM-DefaultSkin
DBM-DMF
DBM-Draenor
DBM-DragonSoul
DBM-EmeraldNightmare
DBM-EyeOfEternity
DBM-Firelands
DBM-GarrisonInvasions
DBM-GUI
DBM-HeartofFear
DBM-HellfireCitadel
DBM-Highmaul
DBM-Hyjal
DBM-Icecrown
DBM-Karazhan
DBM-MC
DBM-MogushanVaults
DBM-Naxx
DBM-Nighthold
DBM-Onyxia
DBM-Outlands
DBM-Pandaria
DBM-Party-BC
DBM-Party-BfA
DBM-Party-Cataclysm
DBM-Party-Classic
DBM-Party-Legion
DBM-Party-MoP
DBM-Party-WoD
DBM-Party-WotLK
DBM-Scenario-MoP
DBM-Serpentshrine
DBM-SiegeOfOrgrimmarV2
DBM-StatusBarTimers
DBM-Sunwell
DBM-TerraceofEndlessSpring
DBM-TheEye
DBM-ThroneFourWinds
DBM-ThroneofThunder
DBM-TombofSargeras
DBM-TrialofValor
DBM-Uldir
DBM-Ulduar
DBM-VoA
DBM-WorldEvents
Enchantrix
Enchantrix-Barker
Firestorm
Gatherer
GMTickets
GnomishVendorShrinker
GoGoMount
HHTD
Informant
Mapster
MBB
NoGryph
Overachiever
Overachiever_Tabs
Overachiever_Trade
Paste
Postal
Quartz
QuestCompletist
Recount
Routes
SafeQueue
SavedInstances
SaySapped
SellJunk
ShadowedUF_Options
ShadowedUnitFrames
SlideBar
SmartBuff
Storyline
Stubby
teksLoot
TipTac
TipTacItemRef
TipTacOptions
TipTacTalents
TomTom
VanasKoS
VendorBait
WeakAuras
WeakAurasModelPaths
WeakAurasOptions
WeakAurasTemplates
WIM
WowLua
XLoot
XLoot_Frame
XLoot_Group
XLoot_Master
XLoot_Monitor
XLoot_Options
