### ISSUE TITLE
[Tyce] - Oh, The Clawdacity! (Highmountain) Quest ID 40230

### ISSUE THREAD

**Issue by gigaslurp** [GuabinaCore/WoWKoi#3197]
**Links:**
[https://www.wowhead.com/quest=40230/oh-the-clawdacity](https://www.wowhead.com/quest=40230/oh-the-clawdacity)
Problem also applies to [Murlocs: The Next Generation Quest ID 40102](https://www.wowhead.com/quest=40102/murlocs-the-next-generation), but it's not as apparent since the player doesn't take as much damage killing small mobs.
Video showing the issue: [https://www.youtube.com/watch?v=Ic9hKEtVZUk](https://www.youtube.com/watch?v=Ic9hKEtVZUk)
**What is happening:**
In these quests, you play as King Mrgl-Mrgl, and in 'Oh, The Clawdacity!' you must kill Clawdayshus, a mob with 3.6 million HP. 
While you are killing him, instead of King Mrgl-Mrgl, the vehicle/mob you are playing as, getting damaged, the player character takes damage instead. Since there's no way to heal the actual player or use health pots or normal spells during this time, the player dies without the murloc taking any damage.
Additional problems with using King Murgl-Murgl is that the Slime ability has a weirdly high cd, and March of the Murlocs only goes in 1 direction instead of a targeted direction.
I've also found that sometimes King Murgl-Murgl will start slow walking for reason's im not sure of, but this can be fixed by just pressing the walk/run toggle hotkey once or twice.

**What should happen:**
The player shouldn't take any damage at all, and the murloc should be what is taking damage. 
Slime should also have little to no actual cooldown, at least comparably from how long it takes to cast it again in game, from what I remember playing legion in retail. March of the Murlocs should also be able to be cast in a direction of the players choosing.

**Comment by Arkanheal** [comment]
Linked #2069
