### ISSUE TITLE
[Tyce] - Enchant Legion Skinning not working on certain mobs

### ISSUE THREAD

**Issue by Adb12345** [GuabinaCore/WoWKoi#3198]
Skinning should be x3 faster with this enchant, on some mobs it works, on some it doesnt. It doesnt work for seaspray crabs on the EoA island for example.

**Comment by Arkanheal** [comment]
Can you provide us with a link to the enchantment and/or a list of the NPC on which it's not working?

**Comment by Adb12345** [comment]
The mobs are https://www.wowhead.com/npc=111647/seaspray-crab - HOWEVER - not the ones in the instance, perhaps it wont work in there either, but I tested it on the mobs, that are found on the island south of dalaran. 

The enchant is https://www.wowhead.com/item=128560/enchant-gloves-legion-skinning
