### ISSUE TITLE
Floating pot and questionmark without an npc

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3199]
**Links:**

from WoWHead or our Armory

**What is happening:** 
In Dalaran, flowerpots are floating in front of this garden, and next to it there is a blue questionmark without anyone there. Im playing from an SSD so they supposed to have a chance to load
![image](https://user-images.githubusercontent.com/84509345/142170450-b9df1272-e11e-4fdf-b939-425e283ae4af.png)

An other:
When pointing the cursor at the anvil inside the place next to the john cena npc with the blue question mark, some parts of this anvil is saying "Doodad_7dl_dalaran_blacksmithforge002" and ...002 directly on the other side
![image](https://user-images.githubusercontent.com/84509345/142180605-26053bff-f34a-43be-a7e2-219c4c18df8a.png)

**What should happen:**
Flower pot should be placed on the ground below it, some npc should stand there, and in the building it should say what that object is, if it has a tooltip i think

**Comment by Cefiro-Caecias** [comment]
1) NPC Illnea Bloodthorn (115264): successfully put into invisible mode until Patch 7.1 content is released.

2) NPC Flower Pot (106528): fixed, blizzlike. If you have Aethril, Dreamleaf, Foxflower, Fjarnskaggl, Starlight Rose or Felwort in your inventory, the hidden dialogue options will be activated, and you will be able to plant a seed until the next server restart.

3) GO Doodad_7dl_dalaran_blacksmithforge001/002: fixed.

All available in the next update.
