### ISSUE TITLE
[Core] - Spell Judgment

### ISSUE THREAD

**Issue by zodIIac** [GuabinaCore/WoWKoi#32]
**Links:**
https://www.wowhead.com/spell=20271/judgment#changelog
https://www.wowhead.com/spell=231644/judgment

**What is happening:**

Started a fresh Level 1 paladin (Having Retribution as default spec), upon reached the level this spell is granted,  it learned (probably) the rank 3 variant. It does damage 1 additional enemy plus puts the debuff on the target.

**What should happen:**

According to wowhead changelog, Rank 1 variant should just damage 1 enemy.
Rank 2 should be learned at Level 16 and damage +1 enemy, Rank 3 should apply the debuff after learning it at level 78.

**Comment by ShikoSCS** [comment]
Fixed
