### ISSUE TITLE
[Tyce] - Habilidad DK

### ISSUE THREAD

**Issue by MatiasSparda** [GuabinaCore/WoWKoi#3200]
**Links:** https://es.wowhead.com/spell=212552/paso-espectral

from WoWHead or our Armory

**What is happening:** Caminata/Paso espectral no funcina estando muerto, se cancela automaticamente

**What should happen:** Deberia funcionar normalmente ttal cual funciona estando vivo

**Comment by Travven** [comment]
La habilidad esta funcionando correctamente
