### ISSUE TITLE
[Tyce] - Guardian druid artifact chain Stage 7

### ISSUE THREAD

**Issue by Zurwan** [GuabinaCore/WoWKoi#3202]
What is happening:
Tried to leave instance instead of spawning in last known location i get tp back to beginning of instance without able to cast/move/movesreen with perm info "You do not meet requirments to enter this instance"

What should happen:
Should be able to leave instanced location without unstuck option

**Comment by Arkanheal** [comment]
@Zurwan Do you have more recent informations about this issue?

**Comment by Zurwan** [comment]
Yea, finally did it but mostly rp breaks out after hitting xavius with
anything (aoe, dot, anything). He's stunning player for rp purpose kinda
too slow (u have 2-3 seconds before u get your "RP stun"). Hitting Xavius
make your quest target untargetable (don't remember his name, but he was
spawning with Xavius and stealing claws)

śr., 24 lis 2021 o 19:32 Pierre Savigny ***@***.***>
napisał(a):
