### ISSUE TITLE
Vengeance Will Be Ours

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3203]
**Links:** https://www.wowhead.com/quest=40249/vengeance-will-be-ours

from WoWHead or our Armory

**What is happening:**
dead npcs has additional lines about their damage and health, and if they could be tamed
![image](https://user-images.githubusercontent.com/84509345/142194660-db323d52-a485-42c3-a79f-89e55089ba8a.png)

**What should happen:**
last 3 line should not be there

**Comment by Cefiro-Caecias** [comment]
This is a descriptive flaw for spell 26299, which provides the kill effect. It is pending review.
