### ISSUE TITLE
[Tyce] - Bag cleanup

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3204]
**Links:**

from WoWHead or our Armory

**What is happening:**
Clicking the clean up bags button does not do anything
![image](https://user-images.githubusercontent.com/84509345/142208902-d49c53aa-17a7-428f-af6d-2d08a630cb63.png)

Ignore this bag button doesnt do anything either
![image](https://user-images.githubusercontent.com/84509345/142209402-ec82df83-8da1-4bf6-a477-764dbeeefd2d.png)

**What should happen:**
the opposite

**Comment by MatiasSparda** [comment]
Please solve this ♥

**Comment by Cefiro-Caecias** [comment]
Fixed :D
