### ISSUE TITLE
[Tyce] - Seguidor Demon Hunter

### ISSUE THREAD

**Issue by ashtrayxheart** [GuabinaCore/WoWKoi#3206]
**Links:**

from WoWHead or our Armory

**What is happening:**

Seleccioné a Kayn Furia del Sol como acompañante en las Islas Quebradas. Ahora lo quiero quitar desde el menu de la sede de clase y, por más que presione la opción, no hace nada. No puedo continuar con las misiones de sede de clase

![image](https://user-images.githubusercontent.com/94543725/142214206-c3c93f79-4add-4311-bb15-49d155988e17.png)

**What should happen:**

Al seleccionar "Quitar" debería devolver al seguidor a los disponibles para enviar misiones

**Comment by Cefiro-Caecias** [comment]
Aplicado un fix. Disponible en el próximo update. Cualquier problema, me avisas.

**Comment by ShikoSCS** [comment]
Fixed up
