### ISSUE TITLE
Garden of the moon, Val sharah, "defend the temple" bonus objective

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3207]
**Links:** https://www.wowhead.com/quest=39029/defend-the-temple

from WoWHead or our Armory

**What is happening:**
Nothing happens when i try to rescue druid of the moon npc
![image](https://user-images.githubusercontent.com/84509345/142274022-2ec702c3-d2a8-4194-be9c-e43e2a5246c7.png)

**What should happen:**
rescuing them should count to the percentage

**Comment by Cefiro-Caecias** [comment]
Repaired. Available in the next update.
