### ISSUE TITLE
[Tyce] - World Quest Montealto: Arena Bruloscuro

### ISSUE THREAD

**Issue by Ghlimk** [GuabinaCore/WoWKoi#3208]
**Links:** https://es.wowhead.com/quest=41013/arena-bruloscuro

**What is happening:**
- Los enemigos de esta zona https://es.wowhead.com/npc=102623/camorrista-puñopiedra  pegan demasiado, si no eres tanque de 3-4 golpes te aniquilan.
- En la arena salen cofres con 2 bufos, Daño  https://www.wowhead.com/spell=202806/brulzerking#sounds  y Sanación  https://www.wowhead.com/spell=202814/deep-rejuvenation , el área de hitbox para beneficiarte de los bufos es demasiado pequeña (debes pasar por encima varias veces para poder beneficiarte), parece ser que si estás en sigilo es aún más pequeña. A demás de que al coger los bufos te saca de sigilo.

**What should happen:**
- El daño de los enemigos debe ser bastante inferior.
- El área para que los jugadores se beneficien de los bufos en la arena de combate debe ser mayor y el sigilo no debe afectar a beneficiarte de los bufos ni eliminar el sigilo del jugador.

**Comment by Cefiro-Caecias** [comment]
Mmmm... Los monstruos de este lugar son Nivel 110 y Rango ëlite, no sorperende que peguen duro. Creo que la subzona está diseñada para hacerla en grupo y con healers en el grupo. Dejo el issue abierto por los reclamos de las spells/areatriggers y lo del sigilo, par los Devs de Core.

**Comment by Ghlimk** [comment]
Me jugué Legión en retail de inicio a fin, esa zona es pvp y ninguna World Quest que no tenga el icono de dragón y sea azul o épica está pensada para ser hecha en grupo ( aún así con algo de ilvl las elites azules las puedes hacer solo ), esos npc están ahí para completar la quest en caso de que no haya jugadores, y eran perfectamente matables por un solo jugador, es cierto que deben pegar más que un mob normal, pero te meten hits de +300k ( a mi, siendo cuero y con 1.6 millones de vida ) es demasiado daño para un solo jugador, deberían pegar alrededor de 50 - 55k que es algo más de lo que pegan los mobs normales.
