### ISSUE TITLE
[Tyce] - Hunter and Warlock pets have problems

### ISSUE THREAD

**Issue by jlspwsn** [GuabinaCore/WoWKoi#3212]
For occupations with pets, the pets are set to automatically cast spells. After the assist mode, the system does not remember them. When the pets are re-summoned, they all return to their original state.  The correct thing is that the system should remember the various states set by the player and keep them when the pet is called again.

**Comment by Jellicat12** [comment]
Clear your cache, and make sure the WoW folder isn't set to read only - I had the same problems, that resolved it for me.
