### ISSUE TITLE
[Tyce] - Stage 2 of Frost Death Night Artifact Quest

### ISSUE THREAD

**Issue by yenfuron** [GuabinaCore/WoWKoi#3213]
**Links:**

from WoWHead or our Armory

**What is happening:**

The teleporter takes you to a Wrath event rather than a legion one.

**What should happen:**
the teleporter should activate to keep you within the instance allowing you to continue with the quest. Also, the UI will not show that there is an event occurring, which should also be fixed.

**Comment by Arkanheal** [comment]
Do you have informations about this issue (quest or scenario links for instance) @yenfuron
