### ISSUE TITLE
[Tyce] - Foam Sword not working as intended

### ISSUE THREAD

**Issue by Noodlerogue88** [GuabinaCore/WoWKoi#3214]
**Links:**
https://wowpedia.fandom.com/wiki/Soft_Foam_Sword
from WoWHead or our Armory
https://www.wowhead.com/item=137663/soft-foam-sword
**What is happening:**
Doing normal expected weapon damage
**What should happen:**
Can only be used on a mob that is 20 or more levels lower then users current level, only allowing the target to fall to 90% health.

**Comment by Cefiro-Caecias** [comment]
@ShikoSCS, hay que condicionar por Core la spell de este item, ya que por DB no se puede. La Spell Careful Swing (213712) debe poseer las sigueintes condiciones:

1) Afecta a creatures que sean 20 Niveles inferior al jugador.
2) Las creaturas deben poseer el 10% de HP o menos para ser afectadas.
3) Las creatures afectadas no pueden ser rango Elite o superior (rare, boss, world boss, etc).

**Comment by Noodlerogue88** [comment]
Edit: I noticed I stated the target would fall to 90% hp, what I mean to say is it will not drop LOWER then 90% hp loss, or better explained as it shouldn't fall below 10% hp remaining
