### ISSUE TITLE
reading the leaves incorrect turn in location

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3215]
**Links:** https://www.wowhead.com/quest=38684/reading-the-leaves

from WoWHead or our Armory

**What is happening:**
The location to complete the quest is shown at the area we do the quest in, instead of the treedude im targeting
![image](https://user-images.githubusercontent.com/84509345/142408593-70124193-cce4-4401-a1f5-757ca89a6ff1.png)

**What should happen:**
the quest complete location on the map should be where im standing at

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the enxt update.
