### ISSUE TITLE
mayor heathrow is getting out of hand...

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3216]
**Links:** https://www.wowhead.com/npc=118752/mayor-heathrow

from WoWHead or our Armory

**What is happening:**
...now there are four of them
![image](https://user-images.githubusercontent.com/84509345/142410512-44a69e7f-fb27-4c44-94e0-522e55c7104e.png)

**What should happen:**
he should pull himself together and just have one around instead of 4

**Comment by Sefrenia-Caecias** [comment]
It will be repaired later when you rebuild the area.

**Comment by Cefiro-Caecias** [comment]
Apply temporal fix.
