### ISSUE TITLE
[Rogue Class Campaign] Deciphering the Letter

### ISSUE THREAD

**Issue by Ghlimk** [GuabinaCore/WoWKoi#3217]
**Links:** https://www.wowhead.com/quest=42680/deciphering-the-letter

**What is happening:** 
In this mission we must interact with the letter on the table and we watch a cinematic, after seeing theit the mission should be completed but it doesnt.

![2021-11-18 13_56_39-Greenshot](https://user-images.githubusercontent.com/93592448/142419486-9b36953d-6eba-4451-86f1-b6c057931878.png)

**What should happen:** When you finish watching the cinematic quest should be completed.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. Don't forget to touch The Raven's Eye next to the letter.
