### ISSUE TITLE
[Tyce] - Costos de vuelo

### ISSUE THREAD

**Issue by ashtrayxheart** [GuabinaCore/WoWKoi#3218]
**Links:**

n/a

**What is happening:**

En el trayecto de un punto de vuelo a otro, si pasas por un un punto de vuelo intermedio (sin bajar), te cobra igualmente el coste.
Es decir, se cobran múltiples vuelos en un solo trayecto

**What should happen:**

El vuelo sólo debería cobrarse al jugador cuando aborda en punto A, y el valor sólo debería ser el correspondiente de punto A a punto B

**Comment by MatiasSparda** [comment]
A mi tambien me pasa
