### ISSUE TITLE
[Tyce] - Demon Hunter Class Hall Follower

### ISSUE THREAD

**Issue by ashtrayxheart** [GuabinaCore/WoWKoi#3220]
**What is happening:**

InGame Name : Shanalott
I can't remove Kayn Sunfury from the follower slot. Also he's not following me in the open world
This means I am not able to use him for follower quests

**What should happen:**

You should be able to remove or add followers from the slot everytime you need to.

**Comment by Cefiro-Caecias** [comment]
Applied a fix. Available in the next update.

**Comment by ashtrayxheart** [comment]
Hi! I still cannot remove Kayn as follower :(
