### ISSUE TITLE
Camapaña de Demon hunter

### ISSUE THREAD

**Issue by NewCrooS** [GuabinaCore/WoWKoi#3222]
No puedo reclamar la misión de los seguidores
![imagen_2021-11-18_161652](https://user-images.githubusercontent.com/94256935/142481994-e510bbc9-4d39-4ec9-a3f7-44cbf047eb05.png)

**Comment by Cefiro-Caecias** [comment]
Prueba salir del juego, borrar cache, y volver a loguear.

**Comment by NewCrooS** [comment]
Si gracias eso hice. lo que si no me dio para seguir la campaña de los DH

**Comment by NewCrooS** [comment]
![imagen_2021-11-18_164533](https://user-images.githubusercontent.com/94256935/142486166-d83ec8ed-f5ab-4d2d-b1bc-ee65a826ed6e.png)
![imagen_2021-11-18_164551](https://user-images.githubusercontent.com/94256935/142486202-6f8d3279-5409-4307-a441-484b3cb81af5.png)

**Comment by Cefiro-Caecias** [comment]
No recuerdo en qué punto de la campaña ocurría, pero la siguiente quest te la daban en Dalaran, aparecía otra vez una NPC persiguiéndote para darte la quest, como al principio de la cadena. O quizás sólo te falte Nivel ^^

**Comment by Cefiro-Caecias** [comment]
Cuando pone el signo en color blanco, significa que te falta Nivel :P

**Comment by NewCrooS** [comment]
jajaja nunca me paso eso que noob que soy
Perdón por las molestias

**Comment by Cefiro-Caecias** [comment]
Para servirte, cariño. Cierro Issue ^^
