### ISSUE TITLE
Vashj'ir No Speed Buff (during Resto sham artifact quest)

### ISSUE THREAD

**Issue by KickYourFace** [GuabinaCore/WoWKoi#3225]
**Links:**
https://www.wowhead.com/quest=43644/to-the-deeps
https://www.wowhead.com/spell=73701/sea-legs

**What is happening:**
No speed boost when in Vashj'ir for swimspeed/running on sea floor

**What should happen:**
Sea legs buff should be active

**Comment by Arkanheal** [comment]
The fact is the spell isn't working (sea legs). Not really linked to the shaman quest line.

**Comment by Cefiro-Caecias** [comment]
In effect, the speed spell is received upon completing a Cataclysm quest. There is no bug present.
