### ISSUE TITLE
Vidente de runas de Faljar

### ISSUE THREAD

**Issue by NewCrooS** [GuabinaCore/WoWKoi#3227]
No le puedo pegar al vidente esta inmunerable
https://es.wowhead.com/npc=93093/vidente-de-runas-faljar
![imagen_2021-11-18_233409](https://user-images.githubusercontent.com/94256935/142555133-91052a2b-6350-4d8c-918d-81726fb8339d.png)

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible ene l próximo update.
