### ISSUE TITLE
Martillo Vil Boss

### ISSUE THREAD

**Issue by NewCrooS** [GuabinaCore/WoWKoi#3228]
El jefe que desbloqueas en las mejoras del Martillo Vil esta bugeado no suelta loot.
![imagen_2021-11-18_235554](https://user-images.githubusercontent.com/94256935/142557174-1f893a35-9fdb-4d85-bf47-7f766f827e79.png)

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
