### ISSUE TITLE
[Horde] (Allied Races) A Choice of Allies Quest ID 50242

### ISSUE THREAD

**Issue by gigaslurp** [GuabinaCore/WoWKoi#3230]
**Links:**
[https://www.wowhead.com/quest=50242/a-choice-of-allies](https://www.wowhead.com/quest=50242/a-choice-of-allies)
**Video:** [https://www.youtube.com/watch?v=P4R0VYD66UM](https://www.youtube.com/watch?v=P4R0VYD66UM)
**What is happening:**
After accepting the quest from Sylvanas, you are to learn about each of the 2 factions you have to choose from, from Baine and Liadrin, afterwards you can't select an allied race to pursue first. You can't click on either of the 2 warbanners next to Sylvanas that represent each allied race.

**What should happen:**
you should be able to pick an allied race.

**Comment by Cefiro-Caecias** [comment]
Partially repaired. Available in the next update.
