### ISSUE TITLE
Urgent!  Mobs reset all the time

### ISSUE THREAD

**Issue by bogdan12397** [GuabinaCore/WoWKoi#3231]
I logged in today like few hours ago and went to do quests. first place was suramar trying to do q called "Impending doooooom!" and mobs inside of that zone were targetable but wouldnt move or agro you and so reseting after every few sec which means i have to one shot them in order to be able to kill them. next thing was dungeon, Eye of Azshara and some mobs were resetting there as well. last place where i was is Stormheim trying to do world quest, and so same problem, adds wont target you so making them impossible to kill because they reset all the time. 
How it should be:
once you enter combat add should have agro on you and so target you and unless killed or left his range right it shouldnt be able to reset by its own..

**Comment by bogdan12397** [comment]
i want to update my previous post. i was playing whole day and well problem presist in a lot of cases. one of them usually comes when we have to use some quest items perhaps or things like that. so there are few cases like some times i stay in combat and cant leave it unless alt+f4 or i leave combat but cant progress.. 
>>btw solution is to del cache folder ,so far every time i do that, mobs go back to normal but soon after i do something else it happens again

**Comment by Arkanheal** [comment]
A fix has been applied yesterday, do you have more recent informations on this issue? @bogdan12397

**Comment by Cefiro-Caecias** [comment]
Fixed.
