### ISSUE TITLE
[Tyce] - Daring Rescue Warlock Quest

### ISSUE THREAD

**Issue by Howizter** [GuabinaCore/WoWKoi#3232]
**Links:**

https://www.wowhead.com/quest=41767/a-daring-rescue

**What is happening:**
After freeing all council member there is no portal to comeback

**What should happen:**

There should be clickable portal to teleport back

**Comment by Arkanheal** [comment]
@Howizter Is the quest doable?

**Comment by Howizter** [comment]
> @Howizter Is the quest doable?

Yes, I used HS to go back
