### ISSUE TITLE
Highmountain storyline bug

### ISSUE THREAD

**Issue by Fritya** [GuabinaCore/WoWKoi#3233]
**Links:**https://www.wowhead.com/storyline/rivermane-tribe-144

**What is happening:**You do the quest line and didn't get the story progress checked.

**What should happen:**When you do the quest chain, then it should check "The Rivermane Tribe" story progress
![2021-11-19](https://user-images.githubusercontent.com/46970886/142646878-009c51c8-5111-4aee-89e8-cdae02512f1d.png)
.
![2021-11-19 (1)](https://user-images.githubusercontent.com/46970886/142646916-6701c087-227b-450b-a0fb-e6bde5880c5c.png)
![2021-11-19 (2)](https://user-images.githubusercontent.com/46970886/142647017-b17c15db-36b4-479b-9006-1cf019657d44.png)
![2021-11-19 (3)](https://user-images.githubusercontent.com/46970886/142647043-c0c0ce63-a172-4235-9883-04b074f7244a.png)

**Comment by thendur** [comment]
Just walk there dont take the eagle

**Comment by Fritya** [comment]
And what should i do if i already did the quest?
