### ISSUE TITLE
BRH World Quest Bugg

### ISSUE THREAD

**Issue by Kaisennnn** [GuabinaCore/WoWKoi#3234]
https://www.wowhead.com/quest=42023/black-rook-rumble

Some of the NPC's or Monster in Black Rook Hold arena unable to be attacked and it ruins the pvp world quest that is usually there most of them function properly but a few of them are completely bugged.

**Comment by Arkanheal** [comment]
Do you have the name of the bugged NPCs? @Kaisennnn

**Comment by Arkanheal** [comment]
https://fr.wowhead.com/npc=111144/mathias-zunn
https://www.wowhead.com/npc=111140/brock-the-crazed
Apparently are the buggy ones

**Comment by Cefiro-Caecias** [comment]
Fixed.

**Comment by NightwindOI** [comment]
Is the server updated with that fix already?
