### ISSUE TITLE
[Tyce] - Creación de hermandad

### ISSUE THREAD

**Issue by NewCrooS** [GuabinaCore/WoWKoi#3237]
No me deja crear una hermandad y ya tengo los estatutos firmados.
![imagen_2021-11-19_132712](https://user-images.githubusercontent.com/94256935/142657247-9bc34020-1e57-429e-8611-274713d90a7a.png)
![imagen_2021-11-19_132849](https://user-images.githubusercontent.com/94256935/142657498-b7237094-8a48-4848-abe7-8a0dc310d0bb.png)

**Comment by MatiasSparda** [comment]
+1

**Comment by juan23145232** [comment]
Tengo el mismo problema.
