### ISSUE TITLE
The Farmsteads

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3239]
**Links:** https://www.wowhead.com/quest=38644/the-farmsteads

from WoWHead or our Armory

**What is happening:**
dude says some russian stuff if i click on his quest
![image](https://user-images.githubusercontent.com/84509345/142662512-e480a144-d4c0-435b-93e9-08da882be621.png)

**What should happen:**
should say it in english

**Comment by Doxxy0** [comment]
oh and nothing happens when i return to bradensbrook like the quest asks me to do, tried leaving the place, relog, cache delete (i remove that every day anyways)

**Comment by HelooxD** [comment]
Even so the quest does not trigger when you need to go back to the quest npc

**Comment by Arkanheal** [comment]
Duplicate #3258. Closing.
