### ISSUE TITLE
Turning the Tidemistress

### ISSUE THREAD

**Issue by j-9000** [GuabinaCore/WoWKoi#3241]
**Links:**
https://www.wowhead.com/quest=40336/turning-the-tidemistress

**What is happening:**
tide mistress and local mobs reset after taking any damage not lettings you kill them even using the Makeshift Ballista built

**What should happen:**
should be able to kill her and mobs for quest credit

**Comment by Arkanheal** [comment]
Probably linked to the evade bug. Do you have more recent informations @j-9000 ?

**Comment by Arkanheal** [comment]
Linked #3283

**Comment by j-9000** [comment]
yes it was the evade bug i completed the q the other day after the fix

**Comment by j-9000** [comment]
wasnt sure how to close this lol

**Comment by Arkanheal** [comment]
Thanks for reporting and closing. Have fun
