### ISSUE TITLE
[Quest-Stormheim] - Blood and Gold (QuestID: 39595)

### ISSUE THREAD

**Issue by Geke3** [GuabinaCore/WoWKoi#3242]
**Links:**
https://www.wowhead.com/quest=39595/blood-and-gold
https://www.wowhead.com/item=128511/challengers-tribute
from WoWHead or our Armory

**What is happening:**
You are still able to loot Challenger's Tribute item (the one where you get the quest from) while doing the quest

**What should happen:**
Challenger's Tribute item (the one where you get the quest from) shouldn't loot if you are currently on the quest or completed it

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
