### ISSUE TITLE
[Tyce] - Frost Mage artifact questline bug

### ISSUE THREAD

**Issue by ghost** [GuabinaCore/WoWKoi#3244]
**Links:**

from WoWHead or our Armory

**What is happening:**
Combat pug on fmage artifact weapon, button on stage 4 doesnt appear & cant continue ql, also stuck on combat for no reason

**What should happen:**
button should appear & i should be able to continue stage 4

**Comment by Arkanheal** [comment]
fmage is frost or fire? Can you give us the quest related to the bug you faced?

**Comment by vechiiro** [comment]
I have the same problem guys. its stage 4 of the frost mage scenario..it is broken. a button should appear and the scenario should move on to the next stage but it doesn't sadly.
