### ISSUE TITLE
Salones del valor

### ISSUE THREAD

**Issue by NewCrooS** [GuabinaCore/WoWKoi#3245]
Despues de matar a Odyn el ultimo jefe de la mazzmorra este queda en combate por lo cual no se puede lutiar el ultimo cofre.
![imagen_2021-11-19_154744](https://user-images.githubusercontent.com/94256935/142675421-739b2415-8e97-4a2c-bf69-72b4635e4c92.png)

**Comment by Cefiro-Caecias** [comment]
Resuelto.
