### ISSUE TITLE
Stormwind Patrollers

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3248]
**Links:** https://www.wowhead.com/npc=37944/stormwind-city-patroller

from WoWHead or our Armory

**What is happening:**
stormwind patrollers automatically assume i want to find the auction house instead of giving me the usual direction menu like the simple guards do
![image](https://user-images.githubusercontent.com/84509345/142683748-d72bcbcc-12f2-4b22-b40e-345aba1dfa55.png)

**What should happen:**
![image](https://user-images.githubusercontent.com/84509345/142683855-c629a3d8-4cdc-4e3e-8531-ff1817165566.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
