### ISSUE TITLE
[Arthas] - Quest Step Three : Prophet

### ISSUE THREAD

**Issue by Trevis77** [GuabinaCore/WoWKoi#325]
**Links:**
https://www.wowhead.com/quest=27773/step-three-prophet

**What is happening:**
After having completed the quest "step three : prophet" you are not teleported to Lord Itharius.

**What should happen:**
You should to be teleported to Lord Itharius after having completed the quest.

**Comment by Cefiro-Caecias** [comment]
Arthas, esta quest tiene puesta la spell de teleportación, pero parece que al completarla a distancia no se castea. Se podrá hacer algo, o es fallo de sistema?
