### ISSUE TITLE
La invasión de Niskara

### ISSUE THREAD

**Issue by juan23145232** [GuabinaCore/WoWKoi#3250]
[La invasión de Niskara. (https://es.wowhead.com/quest=42920/la-invasi%C3%B3n-de-niskara) 

*All NPCs are immune to damage, and you have to wait for Kayn and the followers to hit in order to kill them, that's fine. but annoying because the followers continue without more, avoiding 2 npc and you have to wait for them to reach the door to speak again kayn to return, and return to travel, during his return you can kill the carnivore but the lookout not (in my case I killed him) to other players I do not think they have the same luck, since the npc regenerates automatically throughout life

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Temporal bug. Solved.
