### ISSUE TITLE
Ooker Dooker keeps appearing throughout all locations

### ISSUE THREAD

**Issue by chest3x** [GuabinaCore/WoWKoi#3251]
Ooker Dooker, a companion from one of Azsuna's quest, keeps appearing due to a trinket and keeps messing with my targets, making plenty of mobs impossible to kill - they fully re-heal after couple of shots from him.

Char - Filomena.

**Comment by Arkanheal** [comment]
Probably linked with evade bug
Got recent informations @chest3x ?

**Comment by Arkanheal** [comment]
Marked as fixed due to lack of informations. Feel free to comment if needed. Closing.
