### ISSUE TITLE
Stormhiem / Un monton de costillas

### ISSUE THREAD

**Issue by NewCrooS** [GuabinaCore/WoWKoi#3252]
Los Cuernoruna curpulento de las tierras altas estan bug se les puede pegar pero se reinician.
https://es.wowhead.com/quest=39792/costillar-un-manjar
![imagen_2021-11-19_194208](https://user-images.githubusercontent.com/94256935/142700516-b3636cf0-9559-41bc-91c1-eb430e715c1c.png)

**Comment by Cefiro-Caecias** [comment]
Bug temporal. Resuelto.
