### ISSUE TITLE
The Final Judgement quest Stormheim

### ISSUE THREAD

**Issue by Tarkinug** [GuabinaCore/WoWKoi#3253]
Runeseer Faljar untargetable. 
Relog: didn't help
Del Cache: didn't help
Abandon: didn't help

**Comment by Tarkinug** [comment]
my name: Cowid

**Comment by GuabinaCore** [comment]
Just take the portal, the quest is in autocomplete.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
