### ISSUE TITLE
Swarming Vermin Damage NPC 113195

### ISSUE THREAD

**Issue by gigaslurp** [GuabinaCore/WoWKoi#3255]
1) https://www.wowhead.com/npc=113195/swarming-vermin: Fixed.

**What is happening:**
Each rat does like 180k damage per attack. 4 Rats can deal a collective million damage within seconds.

**Comment by gigaslurp** [comment]
2) https://www.wowhead.com/npc=105756/leyline-spiderling: Fixed.

**What is happening:**
Leyline Spiderlings also deal too much damage as far as I can tell. Npc 105756

**Comment by gigaslurp** [comment]
3) https://www.wowhead.com/npc=106375/felsoul-trickster: Fixed.

**What is happening:**
Felsoul Tricksters also seem to deal far too much damage. NPC 106375

**Comment by Arkanheal** [comment]
4) Linked #3285: Fixed.

5) https://www.wowhead.com/npc=110435/shoalfin-slave: Fixed.

6) https://www.wowhead.com/npc=110448/shoalfin-slave: Fixed.

**Comment by Arkanheal** [comment]
7) Linked #3181: Fixed.

**Comment by Arkanheal** [comment]
8) Linked #3308: Fixed.

9) https://www.wowhead.com/npc=91073/shadowfiend: Fixed.

10) https://www.wowhead.com/npc=107029/blood-maggots: Fixed.

11) https://www.wowhead.com/npc=115379/felclaw-fiend: Fixed.

**Comment by jlspwsn** [comment]
12) https://www.wowhead.com/npc=115379/felclaw-fiend: Fixed.

**Comment by NightwindOI** [comment]
12) 111768: Fixed.

13) 110032: Fixed.

14) 95071: Fixed.

15) 107891: Fixed.

16) 93319: Fixed.

17) 102507: Fixed.

18) 92128: Fixed.

19) 90242: Fixed.

20) 92837: Fixed.

21) 89288: Fixed.

**Comment by jlspwsn** [comment]
22) https://www.wowhead.com/npc=111623/ensorcelled-mana-wraith: Fixed.

**Comment by Cefiro-Caecias** [comment]
Fixed all. Available in the next update.
