### ISSUE TITLE
Candrael's Charm - Demon Hunter  havoc hidden appearance Guise of the Deathwalker

### ISSUE THREAD

**Issue by Natanaelek** [GuabinaCore/WoWKoi#3256]
**Links:**

[from WoWHead or our Armory]
(https://www.wowhead.com/item=141409/candraels-charm#comments)

**What is happening:**
After obtaining _Candrael's Charm_ from mobs I went to _Candrael Twinshadow_ on the cliff west of Felsoul Hold, taked to her and being kicked to fight _Downfall_ but ater reaching him Downfall despawns. The buff allowing you to float in the air is present but Downfall disappears. Because of this the hidden havoc appearance is impossible to get.

**What should happen:**
Correct order of obtaining hidden appearance:
1. Find  _Candrael's Charm_ bropped by mobs in Suramar (this item is required for Downfall to spawn)
2. Take this to _Candrael Twinshadow_ on the cliff west of Felsoul Hold (28.2, 70.2)
3. Talk to her and she kicks you to flying demon _Downfall_. If you are near him his winds will keep you aloft while you fight him.
4. He will occassionaly knock you back, make use of your glide ability and make sure you float back to (through) him, you will begin to float once you come near.
5. When he dies his corpse will fall and, you can loot  _Guise of the Deathwalker_

This can be done in Havoc OR Vengeance spec, with any loot spec seletected.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
