### ISSUE TITLE
Enraged Ambershard npcs unkillable

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3257]
**Links:** https://www.wowhead.com/quest=39133/no-time-to-talk

from WoWHead or our Armory

**What is happening:**
The enraged ambershard npcs only stand in one place taking damage for a short time then they just go back to full hp, this makes them unkillable
![image](https://user-images.githubusercontent.com/84509345/142730065-22e26648-5d62-40d4-815e-5931f38b13e7.png)

**What should happen:**
They should fight and take damage like a real man

**Comment by Arkanheal** [comment]
Probably linked to evade bug

**Comment by Doxxy0** [comment]
Yeah works now thanks
