### ISSUE TITLE
Return to Bradensbrook"

### ISSUE THREAD

**Issue by Atremm** [GuabinaCore/WoWKoi#3258]
**Links:**
https://es.wowhead.com/quest=38644/las-granjas

**What is happening:**
Return to Bradensbrook" doesnt Work. i run around in circles in the city

**What should happen:**
Have to work.

**Comment by Arkanheal** [comment]
Well made it 8 days ago. Could you be a bit more precise ?

**Comment by Arkanheal** [comment]
Duplicate #3239

**Comment by burt245** [comment]
i did the quest a week ago, the kid is in the cellar als it should be, but investigating(walking there) the other areas doesnt do anything.

**Comment by Arkanheal** [comment]
@burt245 did you manage to complete the quest? If so, how?

**Comment by Cefiro-Caecias** [comment]
Fixed. Don't forget to clear Cache, or you won't see the changes.
