### ISSUE TITLE
[Boss] Naraxas drop

### ISSUE THREAD

**Issue by MatiasSparda** [GuabinaCore/WoWKoi#3259]
**Links:**

from WoWHead or our Armory

**What is happening:** Naraxas tercer jefe de la mazmorra Guarida de Neltharion solo dropea items al primero que lootea, una vez el primero recoge el loot el botin desaparece para todos

**What should happen:** Naraxas deberia dropear items (Aunque sea poder de artefacto u oro) a todos los jugadores

**Comment by forgotten420** [comment]
+1

**Comment by Arkanheal** [comment]
I think this is a problem common to nearly all "loot chest" bosses.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
