### ISSUE TITLE
Mision Las Granjas

### ISSUE THREAD

**Issue by NewCrooS** [GuabinaCore/WoWKoi#3261]
Cuando le decís a la nena que "Es seguro" te dice que conoce un atajo al pueblo y desaparece debajo de las escaleras
https://es.wowhead.com/quest=38644/las-granjas
![imagen_2021-11-20_160953](https://user-images.githubusercontent.com/94256935/142738277-3670a2cd-4d99-4c50-8aef-ea9f00e18ea4.png)

**Comment by TirionVadin** [comment]
Hola, tengo el mismo problema

**Comment by Cefiro-Caecias** [comment]
Reparada.
