### ISSUE TITLE
Rivermane Tauren

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3262]
**Links:** https://www.wowhead.com/npc=99406/rivermane-tauren

from WoWHead or our Armory

**What is happening:**
They are highlighted but i dont have any quests tied to them
![image](https://user-images.githubusercontent.com/84509345/142743117-930d8103-8f11-4c2c-9cb5-31b75448af72.png)

**What should happen:**
they should be when they are needed for something

**Comment by Cefiro-Caecias** [comment]
Objetives of World Quests Defend the Riverlands (https://www.wowhead.com/quest=39274/defend-the-riverlands). Solved.
