### ISSUE TITLE
[Quest - Mage Order Hall] Impending doom

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#3264]
**Links:**
https://www.wowhead.com/quest=42493/impending-dooooooom
from WoWHead or our Armory

**What is happening:**
You can't blink accross the barrier

**What should happen:**
You should be able to blink accross the barrier (was working in beta :P)

**Comment by Arkanheal** [comment]
Apparently you can do it but the angle is very hard to find (I didn't but found some mages that did)

**Comment by doona12345** [comment]
im stuck on this quest too. Plus 'the proper way of things' another mage campaign quest. Cant syphon from the corpes

**Comment by Arkanheal** [comment]
@doona12345 See #3296

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
