### ISSUE TITLE
Retri Paladin First Artifact Quest

### ISSUE THREAD

**Issue by LePapst** [GuabinaCore/WoWKoi#3265]
Hello,

I cannot do the retri paladin first artifact quest for ashbringer. In the scenario at stage 3 when you have to kill the jailer zerus, the mob just heals to full hp and doesnt react or attack.

**Comment by Arkanheal** [comment]
Could we have some link to the quests related to this scenario? This one ? https://www.wowhead.com/quest=38376/the-search-for-the-highlord#

**Comment by LePapst** [comment]
Yes it is the quest you linked. This here is better: https://wowpedia.fandom.com/wiki/The_Search_for_the_Highlord#Stage_3:_Holy_Vengeance here you can see what I meant with Phase 3 of the scenario :)

**Comment by Arkanheal** [comment]
Might be linked to evade bug. To test.
Have you tried again since you created the issue @LePapst ?

**Comment by Arkanheal** [comment]
Marked as fixed with the evade bug. Feel free to comment if problem still occurs. Closing
