### ISSUE TITLE
artifact quest evade porblem 

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#3266]
**Links:**
https://www.wowhead.com/quest=42430/the-fangs-of-ashamane#

**What is happening:**
when you enter this part (4th and final part of the quest chain) all npcs in the area go invalid or evade you can freely do 2 o 3 part of the scenario with no problem but when you enter the shrine and you have to dmg the npcs you can not progress more due to the evading problem 

**(this problem has not been solved after update and i tried the delete cash file method 2 times already)** 

**What should happen:**
all npcs should be triggered as normal

**Comment by Arkanheal** [comment]
Evade bug has been fixed yesterday (23/11) got post-update informations? @armirmoazezi

**Comment by Cefiro-Caecias** [comment]
Fixed.
