### ISSUE TITLE
Random Legion Dungeon Normal XP reward

### ISSUE THREAD

**Issue by sapadtordog** [GuabinaCore/WoWKoi#3267]
https://i.imgur.com/3g0JGhZ.jpeg - Gives that much xp on the server.

https://youtu.be/Kk4PH3FGpN0?t=18 - In this video you can see how many xp a normal difficulty dungeon gave on the retail servers. If you continue to watch the video, you can see that they are writing about the chat from Runetotem and Sylvanas realm (before anyone comes up with the video being made from an unofficial server).

**What is happening:**

LFG gives not enough xp.

**What should happen:**

The xp reward needs to be increased.

**Comment by MatiasSparda** [comment]
+1

**Comment by forgotten420** [comment]
+1

**Comment by NightwindOI** [comment]
Need to be increased x8 and will do the job

**Comment by jlspwsn** [comment]
+1

**Comment by Cefiro-Caecias** [comment]
Fixed.
