### ISSUE TITLE
[Mision - logro] La estrategia de Cringris

### ISSUE THREAD

**Issue by MatiasSparda** [GuabinaCore/WoWKoi#3268]
**Links:** https://es.wowhead.com/storyline/gambito-de-cringr%C3%ADs-130#quest

from WoWHead or our Armory

**What is happening:** Tengo realizada toda la questline de Stormheim sin embargo no me contó la primera mision y por ende no me da el logro de zona 

**What should happen:** Completarse como realizada y por ende otorgar el logro correspondiente

![image](https://user-images.githubusercontent.com/47328328/142774429-691d78d2-8257-4b92-93c5-829ceee76378.png)

**Comment by MatiasSparda** [comment]
El nombre de mi personaje es TAndrina, no lo agregue al post original

**Comment by Cefiro-Caecias** [comment]
Jugador ayudado.
