### ISSUE TITLE
[Quest] Explorer's League Document #3 missing from location

### ISSUE THREAD

**Issue by Frosty015** [GuabinaCore/WoWKoi#327]
**Links:** [Gorick's Stash](https://www.wowhead.com/item=45079/goricks-stash-list#comments) and item [Explorers League Document 3 of 6](https://www.wowhead.com/quest=13657/explorers-league-document-3-of-6)

**What is happening:** Currently doing the quest Gorick's Stash, I went to the location listed for the quest item, even defeated the rare mob spawn but no item can be seen

**What should happen:** There should be an interactable item spawned on the ground with a quest marker over it which will allow me to get the explorer's league document quest item

**Comment by Cefiro-Caecias** [comment]
There is no bug present. The Object is located there, at the exit of the cave on the left, next to a box.
