### ISSUE TITLE
[Tyce] - Monk artifact issues

### ISSUE THREAD

**Issue by Tarkinug** [GuabinaCore/WoWKoi#3270]
So I have got my 2. weapon (first was WW 2. was MW) but the Two paths, Two weapons quest is still uncomplete. Now I am working on the 3. one, but the 3 Riddle quests can't be completed. The monkey king doesn't speak to me. My name is Cowid if you could help me I'd be greatfull!

So the bugged quests and raw informations: 
Two paths, Two weapons
The Riddle of Purity (it can be completed, not the other 2 tho, and the Dala bug helper made me do it again even after I completed it once)
The Riddle of the Land
The Riddle of the Barrel
Char name: Cowid

**Comment by Arkanheal** [comment]
https://www.wowhead.com/quest=43973/two-paths-two-weapons
https://www.wowhead.com/quest=42767/the-riddle-of-the-land
https://www.wowhead.com/quest=42766/the-riddle-of-the-barrel

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
