### ISSUE TITLE
[Tyce] - Monk combat ally cannot be unassigned

### ISSUE THREAD

**Issue by Tarkinug** [GuabinaCore/WoWKoi#3272]
Monk combat ally cannot be unassigned! This way I cannot use one of my guys in missions. He is my only counter to some things so I really miss him. Can you make the unassign button work please?

**Comment by Jellicat12** [comment]
I have the same issue with my paladin followers. I had Liadrin assigned, and replaced her with Boros. It didn't return Liadrian as a follower for missions, Boros doesn't appear as a bodyguard when I'm questing in the world, and I can't unassign Boros. So I have TWO followers completely unavailable and doing nothing.

**Comment by Likander** [comment]
I didn't know about this and assigned Boros as a follower for my paladin and he's locked in. Any chance this could be fixed?
