### ISSUE TITLE
[Shrine of the Truthguard] Inna The Cryotstalker PROT PALA quest line

### ISSUE THREAD

**Issue by vi0lat0r1** [GuabinaCore/WoWKoi#3273]
Prot pala artefact quest line stage 1 of the quest [Shrine of the Truthguard], the NPC  Inna The Cryotstalker isnt getting any DMG from me, when i try to atack it says "invalid target"but she's active and doing dmg to the NPC witch are acompany me and they are doing some sully dmg to her.  
---> https://ibb.co/5Kv0XV2

**Comment by vi0lat0r1** [comment]
And the spear cannot be picked up, when i try it says "interupted"and ending the cast even when im not moving, taking a dmg or casting !

**Comment by Arkanheal** [comment]
I suggest you to contact ShenZin and/or Smaily on Discord.
This bugtracker is made for general purposes and this looks like a personal issue.
Closing for now
