### ISSUE TITLE
Legacy bug with DK Runeforging

### ISSUE THREAD

**Issue by kikitheman** [GuabinaCore/WoWKoi#3274]
**Links:**

from WoWHead or our Armory

**What is happening:**
Hello, there was a previous bug I reported with Runeforging ability being missing from the DK class after a while, but now I cannot find a way to restore the ability to my character, since I made him before you've fixed the bug. 

Could you please restore it to Athomix, or add an NPC to Acherus in Legion to learn the ability?

I couldn't find a way to open a ticket ingame and there was no GM on global at the moment. 

**What should happen:**
DK's should have the runeforging ability in order to enchant their weapons.

Thank you for taking a look at this bug :D

**Comment by Cefiro-Caecias** [comment]
Let me know when you are in the game to give you your skills ^^

**Comment by kikitheman** [comment]
Hello,

I logged onto the game. Thank you very much ^^

**Comment by kikitheman** [comment]
> Let me know when you are in the game to give you your skills ^^

Hello, 
I logged in, on my DK Athomix.
Thank you :D

**Comment by Cefiro-Caecias** [comment]
Solved ^^
