### ISSUE TITLE
[WQ] Hertha Grimdottir

### ISSUE THREAD

**Issue by MatiasSparda** [GuabinaCore/WoWKoi#3275]
**Links:** https://es.wowhead.com/npc=103223/hertha-grimdottir

from WoWHead or our Armory

**What is happening:** Hertha tiene una WQ que da recompensa de equipo pero al matarla nada sucede la mision de mundo no se completa

**What should happen:** Al morir Hertha deberia dar el equipo y la mision por completada

![image](https://user-images.githubusercontent.com/47328328/142878144-ea76e418-0439-484b-9725-6e2b2cba31c7.png)

**Comment by Arkanheal** [comment]
The problem is that the World quest "zone" of action doesn't trigger. So the world quest is here on your map, but not on the minimap (you don't get the small yellow circle)

**Comment by Cefiro-Caecias** [comment]
Temporal bug. Solved.
