### ISSUE TITLE
[Quest : 38970] Suramar - Tailoring main questline

### ISSUE THREAD

**Issue by forgotten420** [GuabinaCore/WoWKoi#3276]
**Links:**
https://www.wowhead.com/quest=38970/the-queens-grace-loom

from WoWHead or our Armory

**What is happening:**
the quest doesnt show up and cant continue the questline

**What should happen:**

**Comment by madbessoul** [comment]
+1, blocks the questline.

**Comment by Cefiro-Caecias** [comment]
Fixed.
