### ISSUE TITLE
I have the questing progress from my warrior on my alt warlock.

### ISSUE THREAD

**Issue by killerlorde** [GuabinaCore/WoWKoi#3277]
**Links:**http://prntscr.com/20iy22z
http://prntscr.com/20iye84
http://prntscr.com/20iyfxd
http://prntscr.com/20iyh2m
from WoWHead or our Armory

**What is happening:**
I have finished all the zones on my warrior except suramar and I have all this progression on my warlock aswell.

**What should happen:**
It should restart my progress so I can begin all the chapters again.

**Comment by Arkanheal** [comment]
Does it block you from earning the achievements again?

**Comment by Cefiro-Caecias** [comment]
Contact me on Discord, see if I can help you.
