### ISSUE TITLE
[Dungeon - Halls of Valor] Fenryr is unattackable.

### ISSUE THREAD

**Issue by gigaslurp** [GuabinaCore/WoWKoi#3278]
**Links:**
[https://www.wowhead.com/npc=99868/fenryr](https://www.wowhead.com/npc=99868/fenryr)

**What is happening:**
We are unable to aggro or attack fenryr. He just stands there.

**What should happen:**
Should be able to attack and aggro him.

**Comment by MatiasSparda** [comment]
+1

**Comment by ashtrayxheart** [comment]
Same here

**Comment by NewCrooS** [comment]
+2

**Comment by Arkanheal** [comment]
Could you give us the difficulty you encountered this bug? (Had no problem killing him a week ago in Normal)

**Comment by MatiasSparda** [comment]
Normal, we tried 4 times yesterday

**Comment by MatiasSparda** [comment]
I guess the wq in his zone is bugging him someway

**Comment by madbessoul** [comment]
+1. 
Also tried clearing the whole area of enemies.

**Comment by deorganised** [comment]
+1 Never got a single working Fenryr run yet

**Comment by Koyosu** [comment]
+1

**Comment by Cefiro-Caecias** [comment]
Fixed.

**Comment by Arkanheal** [comment]
Available in the next update sorry. Closing again (and for the last time I hope)
