### ISSUE TITLE
Ashenvale Bowmane Level Scaling

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#328]
**Links:**
https://www.wowhead.com/npc=33195/ashenvale-bowman
https://www.wowhead.com/npc=33914/ashenvale-bowman
https://www.wowhead.com/npc=34012/ashenvale-bowman

https://imgur.com/a/cxaLNgN
from WoWHead or our Armory

**What is happening:**
As you can see in the screenshot, Ashenvale Bowman doesn't scale properly. At least some of them.

**What should happen:**
They should scale.

**Comment by Cefiro-Caecias** [comment]
Fixed days ago. Don't forget to delete your "Cache" folder to see the new changes.
