### ISSUE TITLE
Companion's mission DK campaign

### ISSUE THREAD

**Issue by Paninoninoz** [GuabinaCore/WoWKoi#3280]
Nick: Krila

Problem: I need to send my companions on the starter order class hall missions in order to progress in the class hall questline, but when i send them away it doesn´t do so and im trapped in a loop in which i cant send them and i cant complete the quests.

**Comment by Arkanheal** [comment]
Could you give us more informations about the bug you're facing?
You can't send any NPC to missions? just the quest related missions?

**Comment by Paninoninoz** [comment]
Hi, I received help from a mod in the discord server and now I’m doing
good.
Thank you and sorry for not updating my report, I’m a little new in this
kind of forum interactions.
I will update it now.

**Comment by Arkanheal** [comment]
Thank you for reporting. Glad you got helped. Closing.
