### ISSUE TITLE
[Tyce] - MW monk talent Chiji doesn't autocast

### ISSUE THREAD

**Issue by Tarkinug** [GuabinaCore/WoWKoi#3281]
MW monk talent Chi JI doesn't auto cast the heals. you need to activate it like a pet ability.

**Comment by Arkanheal** [comment]
Can you add a link to the talent? Can't seem to find it. I believe you're talking about the [Invocation](https://wowhead.com/spell=325197), could you confirm?

**Comment by Tarkinug** [comment]
Yes this one. (ofc legion version)

**Comment by Travven** [comment]
Fixes
