### ISSUE TITLE
[Quest : 37566] Azsuna Main Storyline - The Prince is Going Down

### ISSUE THREAD

**Issue by Koyosu** [GuabinaCore/WoWKoi#3282]
**Links:**
https://www.wowhead.com/quest=37566/the-prince-is-going-down

from WoWHead or our Armory

**What is happening:**
you fight the prince alone. the npc should accompany you in killing him, otherwise its kinda impossible if you start wth azuna zone.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed, blizzlike. Available in the next update.
