### ISSUE TITLE
[Quest : 40336] Suramar Main Storyline - Turning the tidemistress

### ISSUE THREAD

**Issue by doona12345** [GuabinaCore/WoWKoi#3283]
[**Links:**](https://www.wowhead.com/quest=40336/turning-the-tidemistress#)

Makeshift Ballista doesnt work, hence cant kill the million adds surrounding the objective boss

Makeshift Ballista should nuke all the adds surrounding the boss + damage boss a little too (tidemistress sashj'tar)

i really need this quest done to unlock a vendor to get a food recipe, hoping the vendor appears/works as intended.

**Comment by Arkanheal** [comment]
Well adds are killable and the boss is as well but I agree it's fcking hard.

**Comment by Cefiro-Caecias** [comment]
Partially repaired. The original Ballista spell was temporarily replaced, until the correct spell was repaired. The quest can now be completed. Available in the next update.
