### ISSUE TITLE
[Quest : 41896] Azsuna - Operation Murloc Freedom  

### ISSUE THREAD

**Issue by jlspwsn** [GuabinaCore/WoWKoi#3285]
**Links:**
https://www.wowhead.com/quest=41896/operation-murloc-freedom
from WoWHead or our Armory

**What is happening:**
The monster's attack damage is too high

**What should happen:**
Should be set to reasonable damage

**Comment by Arkanheal** [comment]
Which NPCs are you targetting by saying the attack damage is too high?

**Comment by jlspwsn** [comment]
https://www.wowhead.com/npc=110435/shoalfin-slave
https://www.wowhead.com/npc=110448/shoalfin-slave
The damage of these 2 npc is too high.

**Comment by jlspwsn** [comment]
Sorry I uploaded a picture in Chinese. I will tell the value. (Melee attack hits me with 197966 physical damage)
![QQ图片20211124093612](https://user-images.githubusercontent.com/49065263/143258338-d94954a8-e831-4192-9a7c-0b6855288c9a.png)

**Comment by jlspwsn** [comment]
The normal damage from being attacked should fluctuate between 20,000 and 25,000.

**Comment by Arkanheal** [comment]
Confirmed. Switched to Medium prio because it makes the quest and WQ associated with it kinda hard for classes without kiting abilities.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
