### ISSUE TITLE
The blue bar will terminate unexpectedly and the game will exit when switching maps when joining the dungeon.

### ISSUE THREAD

**Issue by jlspwsn** [GuabinaCore/WoWKoi#3286]
**Links:**

from WoWHead or our Armory

**What is happening:**
When joining the dungeon, there is a chance that the blue bar will stop.

**What should happen:**
It should load the map normally

**Comment by Arkanheal** [comment]
Do you have more informations on how/when/where this happens? @jlspwsn

**Comment by jlspwsn** [comment]
https://github.com/GuabinaCore/WoWKoi/issues/3306 Please refer to this article.  Our expression means the same

**Comment by Arkanheal** [comment]
Duplicate. Closing
