### ISSUE TITLE
The problem of disconnecting the game in the queue dungeon

### ISSUE THREAD

**Issue by jlspwsn** [GuabinaCore/WoWKoi#3287]
**Links:**

from WoWHead or our Armory

**What is happening:**
Join the heroic dungeon through the queue. If you accidentally exit the game. Start the game again. The character will leave the dungeon and teleport to the dungeon gate. And leave the team

**What should happen:**
It is correct to be in the team and in the dungeon after joining the game. It should not be teleported out of the dungeon.

**Comment by MatiasSparda** [comment]
+1

**Comment by jlspwsn** [comment]
Now a new situation has emerged.  Disconnecting the game in the dungeon will randomly teleport to the endless sea.

**Comment by jlspwsn** [comment]
https://github.com/GuabinaCore/WoWKoi/issues/3306

**Comment by Arkanheal** [comment]
Duplicate. Closing
