### ISSUE TITLE
[Quest] [Alquimia]

### ISSUE THREAD

**Issue by MatiasSparda** [GuabinaCore/WoWKoi#3288]
**Links:** https://www.wowhead.com/quest=39341/vault-of-the-wardens-demons-bile

from WoWHead or our Armory

**What is happening:** La mision Demon's bile no se inicia al finalizar la anterior y no hay forma de iniciarla manualmente

**What should happen:** al finalizar la mision anterior esta deberia iniciarse automaticamente si se cumplen los requisitos (Ser nivel 110)

**Comment by Cefiro-Caecias** [comment]
Fixed.
