### ISSUE TITLE
Scythe of Elune scenario not awarding the artifact.

### ISSUE THREAD

**Issue by Ellevier** [GuabinaCore/WoWKoi#3289]
**Links:**
https://www.youtube.com/watch?v=2EnF20-SqZ4&t=128s (The scenario)

from WoWHead or our Armory
https://www.wowhead.com/quest=40838/the-dark-riders#criteria-of

**What is happening:**
During the final stage of the artifact scenario where you pick up the scythe after right clicking it it was empty,the scenario proceeded as if I got the scythe but I didn't.
This pretty much locks you out of getting your artifact if you turn the quest in and don't notice you're missing the scythe.

**What should happen:**
After defeating the mob and right clicking the scythe you should get it as with other artifacts.

**Comment by Arkanheal** [comment]
You should contact Shen Zin and/or Smaily on Discord to fix your problem.
This bugtracker is made for general purposes and it looks like a personal issue. Closing for now.
