### ISSUE TITLE
Timewalking Loot ilvl + equipped loot ilvl before fix

### ISSUE THREAD

**Issue by sapadtordog** [GuabinaCore/WoWKoi#3290]
https://i.imgur.com/2n7o3K4.jpg

When item scaling was fixed, the items of the previously equipped (Timewalking drops and Artifact Relics) were not corrected.
Video: https://youtu.be/MozDN9e7bCY?t=216
Picture from video: https://i.imgur.com/OcPvdce.jpg

**What is happening:**

Bad Timewarped loots ilvl--> 880
Bad Artifact Relics ilvl --> Higher than 850

**What should happen:**

Correct Timewarped loots ilvl: --> 835
Correct Artifact Relics ilvl: --> max. 850

**Comment by forgotten420** [comment]
+1

**Comment by Arkanheal** [comment]
As stated in the announcment relics weren't touched by fear of breaking the whole artifact system. So for now it will stay as is.
For Timewalking items, after you relogged were they scaled to 850?
I know it isn't the right value but it's the fix that was applied. @forgotten420 @sapadtordog

**Comment by ShikoSCS** [comment]
Fixed
