### ISSUE TITLE
Server crash - Loss of items

### ISSUE THREAD

**Issue by deorganised** [GuabinaCore/WoWKoi#3291]
ign:Culle
I haven't taken a screencap after obtaining the ring but I've had screencapped my guild news section in which the written data mentions my character looting a 875 mythic necklace(?)
https://imgur.com/a/ykVEt77

**What is happening:**
A pvp world quest reward in Highmountain, the pvp quest in which you battle in the arena, was a 890 ilvl ring. Five minutes later after finishing the quest and equipping the before mentioned 890 ilvl ring I encountered a server disconnect, and after the relog the ring was nowhere to be found.

**What should happen:**
A disconnect should not be the cause of an item disappearance.

**Comment by MatiasSparda** [comment]
I was there, my ign is Tandrina we did together the quest (He's Alliance and im Horde) i dc before the server crash and i kept the ring, here's my screenshot, OC the ring downgraded his ilvl to 850 
![image](https://user-images.githubusercontent.com/47328328/143092450-3461d4bf-a44c-49fb-ad8d-501cc0abc062.png)

**Comment by Arkanheal** [comment]
@NightwindOI all you <3

**Comment by Arkanheal** [comment]
This is a kind of a special one. But I think it's important to fix right now before raids and MM+ goes live. Because if a 890+ ring isn't that important. A BiS Titanforged piece lost to a crash will get people real mad.

**Comment by Arkanheal** [comment]
I suggest you to contact Shen Zin and/or Smaily on Discord.
Closing for now.
