### ISSUE TITLE
World Quest - Bloodline of Stone 

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#3292]
**Links:**
https://www.wowhead.com/quest=41955/bloodline-of-stone
https://www.wowhead.com/npc=91130/magula
from WoWHead or our Armory

**What is happening:**
Eggs are broken when they spawn making the WQ undoable + they probably get broken by harpies (shouldn't)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
