### ISSUE TITLE
The Skies of Highmountain bug

### ISSUE THREAD

**Issue by Tonage** [GuabinaCore/WoWKoi#3293]
**Links:**
https://www.wowhead.com/quest=39387/the-skies-of-highmountain

**What is happening:**
No Lasan comes back to finish his ritual at the base of Thunder Totem.

**What should happen:**

Should meet Lasan at Thunder Totem to finish the ritual

**Comment by Arkanheal** [comment]
Duplicate of #2853. Closing.
For now you can complete the quest by not taking the bird and walking all the way to Thundertotem (you'll need to abandon the quest and taking it again)
