### ISSUE TITLE
Russiun language in the English version

### ISSUE THREAD

**Issue by vi0lat0r1** [GuabinaCore/WoWKoi#3294]
**Links:**

https://imgur.com/KufHIpg

**What is happening:**

Random Russian language in the Engrish version of the game.

**What should happen:**
shouldn't be in russian

**Comment by Arkanheal** [comment]
https://www.wowhead.com/quest=41909/tracking-the-tideskorn
As well (from #3177)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
