### ISSUE TITLE
[Tyce] - Mage Campaing - Into the oculus (Quest : 42734)

### ISSUE THREAD

**Issue by bogdan12397** [GuabinaCore/WoWKoi#3295]
Everything works fine untill last phase of scenario where i find Npc name Kathra'natir.
![WoWScrnShot_112321_231509](https://user-images.githubusercontent.com/94296968/143138104-9a4a65b1-50cb-418f-a691-30b1a17f57fc.jpg)
How it should be:
i should be able to dps npc below 70% and then use the orb on the ground to complete quest.

**Comment by bogdan12397** [comment]
https://www.youtube.com/watch?v=vsxUTywBK2w 
here is yt video of how it should be

**Comment by Defqonn** [comment]
+1 PLS fix this guys

**Comment by wowmagemaster** [comment]
+1 PLS fix this guys!!!!!!!!!!!!!!!!!!!!!it's still not working!!!!!!!!!!!!!!!!!!

**Comment by OnlyWATCH** [comment]
Still not fixed . last phase is broken need to be fix it
