### ISSUE TITLE
[Quest : 42955] Mage Campaign - The proper way of things

### ISSUE THREAD

**Issue by bogdan12397** [GuabinaCore/WoWKoi#3296]
**Links:**

https://www.wowhead.com/quest=42955/the-proper-way-of-things

**What is happening:**
I dont get an item called Phial of Nightwell Energy,  but only Wand of Siphoning. Because of that im not able to siphon any energy from dead mobs in area.

**What should happen:**
I should get required items for quest and with them i should be able, once i kill proper npcs, to siphon energy from them in order to complete quest.

**Comment by Defqonn** [comment]
+1

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. You will be able to complete the quest; even so, the item's spell has a defect that must be fixed by Core.
