### ISSUE TITLE
[Tyce] - Warlock Artifact: Ritual Ruination

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3297]
**Links:**

(https://www.wowhead.com/quest=43254/ritual-ruination)

**What is happening:**
Once you land Gul Dan don't trigger the quest and his out of the green circle.

**What should happen:**
That's how supposed to be 
https://www.youtube.com/watch?v=izHfTLwUI1M&start=146

**Comment by Arkanheal** [comment]
https://www.wowhead.com/quest=43254/ritual-ruination
