### ISSUE TITLE
Suramar questchain 

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#3298]
**Links:**
https://www.wowhead.com/quest=40012/an-old-ally 
i was going to do this quest chain in order to progress my leather work prof by unlocking this npc : 
https://www.wowhead.com/npc=98969/stalriss-dawnrunner#comments

**What is happening:**
after you give that scroll the quest "an old ally" i spouse to give you the next quest in line "Scattered Memories" and so on but it doesn't give you any quest

**Comment by Arkanheal** [comment]
Could you elaborate? I managed to do nearly all of Suramar. And I finished this questchain up to the mask that allows you to walk "freely" in Suramar

**Comment by Tonage** [comment]
I also finished that quest in the Suramar chain without a problem : )

**Comment by armirmoazezi** [comment]
https://www.wowhead.com/npc=98969/stalriss-dawnrunner#comments

3rd comment "By Vyola on 2018/01/19 (Patch 7.3.5)" i was doing as he said in that comment when i started the quest chain (3rd part of his instruction) as you can see the next quest given by the scroll should be :
https://www.wowhead.com/quest=40326/scattered-memories 
which it doesn't give me any scroll 

also the mask you are referring to is a different chain quest and if i am correct its not necessary for this chain ( i could be wrong and ill be happy if any leather worker correct me )

**Comment by Arkanheal** [comment]
It doesn't give you the quest? Or you have the quest and don't find any scrolls?

**Comment by Arkanheal** [comment]
You can get this https://www.wowhead.com/quest=41149/a-re-warding-effort on a nearby ward which is the next quest in the quest line.
It might be an quest order issue.

**Comment by Arkanheal** [comment]
Closing. Saw with the issuer.
