### ISSUE TITLE
[Tyce] - Warrior campaign bug at Hodir's door

### ISSUE THREAD

**Issue by deorganised** [GuabinaCore/WoWKoi#3299]
https://imgur.com/a/OVojcVV
What is happening: 
Was doing the warrior campaign in Ulduar (https://www.wowhead.com/quest=43090/ulduars-oath) .Proceeded to the part where you pull Hodir's door with the chains and the quest bugged out while I was pulling the door, it wouldn't budge no matter how far I pulled. Couldn't finish the scenario and I abandoned the mission and used Dalaran hearthstone, now I have the "Heavy Chains" (https://www.wowhead.com/spell=218597/heavy-chain) debuff even when I'm outside of the scenario.

**ISSUE SOLVED AFTER SUICIDE**

**Comment by Arkanheal** [comment]
@NightwindOI For this guy's debuff.

**Comment by Valcry1** [comment]
Dvalen Ironrune also doesn't start next scenario to continue line (0/1 Follow Dvalen Ironrune).
