### ISSUE TITLE
[Core] - Winter is Coming - Frost Death Knight talent.

### ISSUE THREAD

**Issue by Drathnor** [GuabinaCore/WoWKoi#33]
**Links:**
https://www.wowhead.com/spell=207170/winter-is-coming
https://www.wowhead.com/spell=196770/remorseless-winter

**What is happening:**
Enemies struck 5 times by Remorseless Winter aren't affected by a 4-second stun.

**What should happen:**

Enemies struck 5 times by Remorseless Winter should be stunned for 4 seconds.

**Comment by GuabinaCore** [comment]
Remorseless Winter fixed
