### ISSUE TITLE
Quest - Damn You, Frostilicus

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#330]
**Links:**
https://www.wowhead.com/quest=28831/damn-you-frostilicus
https://www.wowhead.com/npc=10929/haleh

**What is happening:**
Quest can be started from both npc Haleh and Jadrag the Slicer

**What should happen:**
Quest can be started from Jadrag the Slicer

**Comment by Cefiro-Caecias** [comment]
We have deliberately calibrated it that way, for clueless players.

**Comment by DeltaVortex** [comment]
Ummm there is no need? I mean you pass there while doing the quests from the other npc anyway. imo blizzlike in this case makes more sense and breaking the immersion I have while questing isn't good at all.
