### ISSUE TITLE
[Tyce] - Herboristeria: Rosa Luz estelar

### ISSUE THREAD

**Issue by MatiasSparda** [GuabinaCore/WoWKoi#3302]
**Links:** https://es.wowhead.com/object=244778/rosa-luz-estelar

from WoWHead or our Armory

**What is happening:** Al recolectar la rosa luz estelar a veces me da solo polvo

**What should happen:** Al poseer el nivel 3 de rosa luz estelar siempre debe dar el objeto de rosa luz y no polvo ya que esto solo sucede antes del nivel 3

![image](https://user-images.githubusercontent.com/47328328/143271395-23c2336f-4266-47ad-a8fc-1521637a5adf.png)

**Comment by Cefiro-Caecias** [comment]
Drop mejorado, mientras intentamos calibrar los porcentajes según spells. Disponible en el próximo update.
