### ISSUE TITLE
Randomly spanish objective

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3303]
**Links:** https://www.wowhead.com/quest=38717/black-rook-prison

from WoWHead or our Armory

**What is happening:**
Mission objective is in spanish
![image](https://user-images.githubusercontent.com/84509345/143288551-bc11905d-ac4b-460b-920e-d72f210d0302.png)
Other places too
![image](https://user-images.githubusercontent.com/84509345/143289208-aaea224b-e512-4b99-ad5c-25aac602ff38.png)
This is near the dude i have to kill in the quest
![image](https://user-images.githubusercontent.com/84509345/143290343-069fec31-1b6b-4426-bb40-7e9e7db2d6e2.png)

**What should happen:**
Should be in english

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. Don't forget to clear Cache.
