### ISSUE TITLE
Lieutenant of the tower

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3304]
**Links:**
https://www.wowhead.com/quest=38721/lieutenant-of-the-tower
from WoWHead or our Armory

**What is happening:**
Maiev and Jarod do not help me kill the enemy, they just repeat the talk indefinitely and stand in one place, making the battle close to impossible
![image](https://user-images.githubusercontent.com/84509345/143291901-188018f5-7ede-482d-bfc0-bf0aece1f587.png)

**What should happen:**
They should help

**Comment by Arkanheal** [comment]
Doable but really hard if you can't kite

**Comment by Cefiro-Caecias** [comment]
Fixed, blizzlike. Available in the next update.
