### ISSUE TITLE
Orgrimmar teleport in Thunder Totem works as alliance

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3305]
**Links:**

from WoWHead or our Armory

**What is happening:**
Orgrimmar teleport in Thunder Totem (take the lift down to the Hall of Chieftains) works as alliance
![image](https://user-images.githubusercontent.com/84509345/143300469-26414bd6-5fbb-43aa-a79d-d744b67d9af1.png)
![image](https://user-images.githubusercontent.com/84509345/143300536-6b69bf53-00b9-47ad-98ca-463fb2d83e4d.png)

**What should happen:**
It should not work

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
