### ISSUE TITLE
[Tyce] - beeingt stuck as gohst after trying to enter timewalking.

### ISSUE THREAD

**Issue by burt245** [GuabinaCore/WoWKoi#3306]
**Links:**
n/a

**What is happening:**
we were doing timewalking instances for the weekly quest and every time we queued two  people got stuck in loading screen.
as usually we alt+f4ed and restarted the game, when we logged back in we were in the furthest northwest of sthe sea in stormheim, guaranteed to die from fatigue. after dying we were respawned to silverpine forest, unable to retrieve our corpses, unstucking would port us to dalaran but no spirit healer worked and we couldnt reach our corpses, leaving us struck untuil a gm came to help. 

**What should happen:**
after altf4 ing in loading screen we shouldnt have been ported in the sea and after dying in the sea we should have been respawned in stormheim/broken shores.

**Comment by Arkanheal** [comment]
@Sefrenia-Caecias This seems kinda serious. Especially for people with bad internet connections.

**Comment by Arkanheal** [comment]
It appears to be a real issue for every dungeon queue.
