### ISSUE TITLE
Salón de clase de mago "Teleportation Nexus"

### ISSUE THREAD

**Issue by Megafla** [GuabinaCore/WoWKoi#3307]
[**Links:**]
https://www.wowhead.com/order-advancement=386

**What is happening:**
Cunado termina la investigación de esa mejora de sede, los portales no aparecen.

**What should happen:**
Debería haber portales después de hacer la investigación.

**Comment by Arkanheal** [comment]
Duplicate #3365

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
