### ISSUE TITLE
Damage problem with mobs

### ISSUE THREAD

**Issue by Dario1243** [GuabinaCore/WoWKoi#3308]
**Links:**
https://www.wowhead.com/npc=91073/shadowfiend#drops
https://www.wowhead.com/npc=107029/blood-maggots
https://www.wowhead.com/npc=115379/felclaw-fiend
**What is happening:**
Mobs deal too much damage. For example Shadowfiend in Azsuna deal 280-300 k per one hit. 
![ScreenShot_20211124224512](https://user-images.githubusercontent.com/46204263/143317715-6f52da5a-6b1d-4165-9d0e-93471b6c3451.png)
The next problem is in a boss fight. When boss summons adds. that add deal tones of dmg. Name Blood Maggot
![ScreenShot_20211124220800](https://user-images.githubusercontent.com/46204263/143318155-34f3e791-dd11-47ed-a249-86b66761a94d.png)
Yes, add just 1 shot me. :D
The next mob is Felclaw Fiend in Val'sharah
![ScreenShot_20211124231027](https://user-images.githubusercontent.com/46204263/143319461-9016686c-5c0e-4c6b-ba57-e19cef25d749.png)

These mobs are just examples. There is a lot of mobs with low hp that deal tons of damage. Just I don't remember all of them. or some like murlocs are now reported so please repair that.
**What should happen:**
These mobs should do very very little amount of dmg.

**Comment by Arkanheal** [comment]
Linked #3255

**Comment by Arkanheal** [comment]
Closing here. Report to #3255
