### ISSUE TITLE
Quest: Trolling for Information in Dun Morogh

### ISSUE THREAD

**Issue by Kaleestraza** [GuabinaCore/WoWKoi#3309]
**Links:** https://www.wowhead.com/quest=24489/trolling-for-information

**What is happening:** Nothing happens when I approach the troll soothsayers. As a result, the quest cannot be completed. I have attempted abandoning the quest and retaking it, approaching from different angles or in different order, standing different lengths away from them, right clicking, etc. Nothing seems to trigger dialogue.

**What should happen:** The three Soothsayer NPSs are supposed to broadcast lines of dialogue when approached, giving you quest credit. Here is a video of the quest from retail: https://www.youtube.com/watch?v=HgZeQKIdwSE

**Comment by Cefiro-Caecias** [comment]
The starting zones will be repaired later, but this time I made an exception with your report. Fixed, blizzlike. Available in the next update ;)
