### ISSUE TITLE
Quest - Razor Beak and Antlers Pointy

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#331]
**Links:**
https://www.wowhead.com/quest=28829/razor-beak-and-antlers-pointy
https://www.wowhead.com/npc=10929/haleh

**What is happening:**
Quest can be started from both npc Haleh and Jadrag the Slicer

**What should happen:**
Quest can only be started from npc Jadrag the Slicer

**Comment by Cefiro-Caecias** [comment]
We have deliberately calibrated it that way, for clueless players.

**Comment by DeltaVortex** [comment]
Ummm there is no need? I mean you pass there while doing the quests from the other npc anyway. imo blizzlike in this case makes more sense and breaking the immersion I have while questing isn't good at all.

**Comment by Serithul** [comment]
You say you want to make the server blizzlike. This doesn't make it blizzlike imo. Please fix it, there really isn't a reason to do something like that.
