### ISSUE TITLE
Old content  Quest Resupplying the Excavation

### ISSUE THREAD

**Issue by HelooxD** [GuabinaCore/WoWKoi#3310]
Quest does not trigger if you find the npc

**Comment by Arkanheal** [comment]
Could you provide us with links as stated [here](https://github.com/GuabinaCore/wowkoi/wiki/How-to-Properly-Report-an-Issue) ?

**Comment by Cefiro-Caecias** [comment]
The starting zones will be repaired later, but this time I made an exception with your report. Fixed, blizzlike. Available in the next update ;)
