### ISSUE TITLE
[Tyce] - Trinket: Sylvanas' Barbed Arrow damage.

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#3311]
**Links:**
https://www.wowhead.com/item=121572/sylvanas-barbed-arrow (Horde)
https://www.wowhead.com/item=129258/sylvanas-broken-arrow (Alliance)
https://www.wowhead.com/spell=202761/banshees-blight
from WoWHead or our Armory

**What is happening:**
This trinket deals way too much damage (see screenshots)
![image](https://user-images.githubusercontent.com/27277903/143451043-2e1833d9-9d56-4e0a-a51c-4a17ae8c1a07.png)

**What should happen:**
Should deal less damage.

The damage shown in screenshot is from the Horde version of the trinket.

**IMPORTANT** It seems like the proc rate is a bit low

**Comment by Travven** [comment]
Fixed
