### ISSUE TITLE
[Dungeon] Fenryr in Halls of Valor

### ISSUE THREAD

**Issue by madbessoul** [GuabinaCore/WoWKoi#3313]
**Links:**

https://www.wowhead.com/npc=99868/fenryr
Same issue as https://github.com/GuabinaCore/WoWKoi/issues/3278

**What is happening:**

Still can't target the boss. He's hostile but can't cast spells on him.

**What should happen:**
Boss should start combat when getting close enough.

**Comment by Arkanheal** [comment]
Re-opening #3278. Closing here.
