### ISSUE TITLE
Vrykul story bro

### ISSUE THREAD

**Issue by Nicholas941205** [GuabinaCore/WoWKoi#3314]
Hello! i have a problem with that quest chain! after I completed Helheim and back quest, after the server has a restart and i lost progress on achivement, but my chain not lost only helheim and back missing

**Comment by Arkanheal** [comment]
You should try to contact ShenZin or Smaily on Discord. This bug tracker is for general bugs not "personal" ones. You could as well use the support related channels on Discord.
Closing.
