### ISSUE TITLE
Shaman Order Hall - Further Advancement

### ISSUE THREAD

**Issue by Grogser** [GuabinaCore/WoWKoi#3315]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=46781/further-advancement

**What is happening:**
The quest is marked as completed, yet I can't turn it in, since it's progress is 0/0.

**What should happen:**
Should be able to research a trait with the class hall upgrade guy, have the quest completed afterwards.

![Screenshot 2021-11-25 185140](https://user-images.githubusercontent.com/55659225/143485065-5de20496-18c7-46c1-afaf-507f59e58bee.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
