### ISSUE TITLE
Fury Artifact Quest

### ISSUE THREAD

**Issue by Koyosu** [GuabinaCore/WoWKoi#3316]
**Links:**

from WoWHead or our Armory

**What is happening:**So if you log off the quest while you are in stage 2 of getting the fury artifact weapon then you log in back this happens
![image](https://user-images.githubusercontent.com/82822996/143490642-cbcdf09e-71e2-4f5e-b38a-c40ba6585224.png)
just floating and going forward

**What should happen:**

**Comment by Koyosu** [comment]
https://www.wowhead.com/acquiring-warswords-fury-warrior-artifact

**Comment by Arkanheal** [comment]
You should contact Shen Zin or Smaily on Discord so they can untuck you. You could as well use the support channels.
This bugtracker is made for general bugs and this look like a personnal issue. Closing for now.
