### ISSUE TITLE
[Quest : 40864] Dalaran - Engineering main questline

### ISSUE THREAD

**Issue by TheUnmercey** [GuabinaCore/WoWKoi#3317]
**Links:**
https://www.wowhead.com/quest=40864/modular-modifications
https://de.wowhead.com/item=132523/reaves-batterie
https://www.wowhead.com/spell=198988/reaves-module-snack-distribution-mode
from WoWHead or our Armory

**What is happening:**
Reaves Battery does summon reaves to speak with - but he rejects any options.
Youre able to craft both Items - but you can't applie the Snack Mod to him.
You keep the Snack mod and can recast it over and over but its not consumed.

**What should happen:**
After using the Snack Mod onto Reaves the Item should be consumed and Reaves should be able to transform into a Dish/table to eat off everytime you resummon him you can choose the applied options.

In the comment section below "By varenne"
This should work with each of the Mod's in future mod content of Engineering.

**Comment by Cefiro-Caecias** [comment]
Fixed. You must abandon the quest, exit the game, clear Cache, and take the quest again. Available in the next update.
