### ISSUE TITLE
Huln's War-the nathrezim rép farming

### ISSUE THREAD

**Issue by Slaygin** [GuabinaCore/WoWKoi#3318]
In this quest u become a super powerfull tauren  while u have a quest that require u to kill a super strong boss u Can just ignore him and l'Ill the thrash around him to farm rep the "Plague imp" gives 75 to the dreamweavers and the "felguard légionnaires" 75 to highmountain and like u are in a strong tauren u just 1 shot them.
Free rep

**Comment by Arkanheal** [comment]
Could you provide us with quest and/or NPC links please? as stated [here](https://github.com/GuabinaCore/wowkoi/wiki/How-to-Properly-Report-an-Issue)

**Comment by MatiasSparda** [comment]
I guess he's talking about this quest https://www.wowhead.com/quest=39983/hulns-war-the-arrival#comments

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
