### ISSUE TITLE
Shaman Order Hall Campaign

### ISSUE THREAD

**Issue by Fritya** [GuabinaCore/WoWKoi#3319]
**Links:** https://www.wowhead.com/quest=42989/mahaat-the-indomitable

**What is happening:** I should be able to turn in the quest.

**What should happen:** The NPC is red and I can't turn it in.
![2021-11-25](https://user-images.githubusercontent.com/46970886/143501065-ce5588b7-3d75-4bb3-91c0-bc65b74eb080.png)

**Comment by Cefiro-Caecias** [comment]
That NPC was fixed days ago. Exit the game, clear the Cache of your WoW, and you will see the NPC in friendly mode ^^

**Comment by Fritya** [comment]
I cleared it but it's still red.
