### ISSUE TITLE
Solid Chests

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#332]
**Links:**
https://www.wowhead.com/object=2850/solid-chest#comments

**What is happening:**
Solid chests are scattered over Azeroth.

**What should happen:**
Solid chests are removed after Cataclysm changes and are replaced with Silverbound Treasure Chest, Sturdy Treasure Chest and Silken Treasure Chest.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
