### ISSUE TITLE
[Tyce] - Chance de parada y esquiva

### ISSUE THREAD

**Issue by MatiasSparda** [GuabinaCore/WoWKoi#3321]
**Links:**

from WoWHead or our Armory

**What is happening:** Las chances de parada y esquiva no estan funcionando correctamente, lo comprobe en un duelo y mi personaje no bloquea ningun golpe a pesar de tener la chance de parada por encima del 30% lo mismo le sucedio a la otra persona que utilizo emborronar (Aumenta la chance de esquiva) y no esquivaba ningun golpe. Adicionalmente las chances en los detalles figura su porcentaje pero dicen que es 0.

**What should happen:** Esquivar y parar golpes segun las chances correspondientes

![image](https://user-images.githubusercontent.com/47328328/143512686-7b3d841e-72f3-483b-954d-588eff2d20c4.png)

![image](https://user-images.githubusercontent.com/47328328/143512709-fb1169b7-fadd-4b11-ab95-385b9471156c.png)

**Comment by Noahkrr** [comment]
+1

**Comment by NewCrooS** [comment]
+2

**Comment by ashtrayxheart** [comment]
+3
