### ISSUE TITLE
[Quest : 41019] Hatchling of the talon

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#3322]
**Links:**

https://www.wowhead.com/quest=41094/hatchlings-of-the-talon#comments

**What is happening:**

the green orbs don't show up 

**What should happen:**
there are 10 green orbs for you to hit in order to get the achievement of : 
https://www.wowhead.com/achievement=10774/hatchling-of-the-talon
and a toy : 
https://www.wowhead.com/item=139773/emerald-winds#

**Comment by Cefiro-Caecias** [comment]
Temporal bug. Solved.
