### ISSUE TITLE
Mage living bomb will not spread

### ISSUE THREAD

**Issue by jlspwsn** [GuabinaCore/WoWKoi#3323]
**Links:*https://www.wowhead.com/spell=44457/living-bomb*

from WoWHead or our Armory

**What is happening:**
After using this skill, if the monster dies within the countdown, it will not spread.

**What should happen:**
The correct goal is within the countdown time. If the monster dies early, it should spread to other monsters immediately.Please check and test.

**Comment by Arkanheal** [comment]
Duplicate #3079. Closing
