### ISSUE TITLE
scouting map do not work warlock class hall

### ISSUE THREAD

**Issue by Redsand1** [GuabinaCore/WoWKoi#3324]
**Links:**
https://www.wowhead.com/dreadscar-rift
from WoWHead or our Armory

**What is happening:**
when i try to pick a quest from the scouting map for  any legion zone just doesnt work i click accept to the quest and only visually showed me i pick the quest but the game dosent track him when i re-open scouting map  the quest  still there ... this is for evry legion zone

**What should happen:**
the player should pick quest from the scouting map normally without any bugs

**Comment by NightwindOI** [comment]
Will be fixed with the upcoming server update (scouting map rework for all class''s ) 
Thx for your report!
