### ISSUE TITLE
Druid Artifact  Sowing the Seed - Seed of Ages

### ISSUE THREAD

**Issue by yggad** [GuabinaCore/WoWKoi#3325]
**Links:** https://www.wowhead.com/quest=40651/the-seed-of-ages

**What is happening:** Firstly, as a resto I didn't get my 100 AP to imbue my weapon, then with a second character as a balance I couldn't "plant" the seed. Tried relogging, dropping and picking up the quest again. That lead to the npcs disappearance.

**What should happen:** After the seed is planted, we should get the 100AP to imbue our weapon.

**Comment by Arkanheal** [comment]
I suggest you to contact Shen Zin and/or Smaily on Discord. 
Understand that this bugtracker is for general purposes and this looks like a personal bug that the GMs will be able to fix.
Closing for now. Feel free to comment.
