### ISSUE TITLE
[GM Ingame] - cant turn in quest - a growing crisis

### ISSUE THREAD

**Issue by burt245** [GuabinaCore/WoWKoi#3326]
[**Links:**
www.wowhead.com/quest=44152/a-growing-crisis
[screen of npc(and coordinates in the minimap)](https://imgur.com/a/6weshpf)

**What is happening:**
i cant turn in the quest "a growing crisis" because i cant talk to the npc at all. i allready tried to delete cache, restart quest and everything, its still the same.
(everyone else i asked had no issues with this quest)

**What should happen:**
i should be able to open the gossip frame when clicking the npc and then complete the quest, both doesnt happen.

**Comment by Arkanheal** [comment]
You should contact Shen Zin and/or Smaily on Discord, they'll be more than happy to help you.
Understand that this bugtracker is for general purposes and this looks like a personal bug.
Closing for now. Feel free to comment

**Comment by Arkanheal** [comment]
Some people having the same issue on supports channel. Reopening

**Comment by Cefiro-Caecias** [comment]
It's very strange. I just tried the quest, and it didn't give me a problem. The only way it gets bugged and you can't deliver it is if a GM gave you the quest with command, and if you haven't previously completed the quest "Friends With Benefits" (44053). Is this the case? o.O
