### ISSUE TITLE
The Queen's Grace Loom

### ISSUE THREAD

**Issue by doona12345** [GuabinaCore/WoWKoi#3327]
[**Links:**](https://www.wowhead.com/quest=38970/the-queens-grace-loom#comments)

from WoWHead 

This quest doesn't appear after the previous quest 'Master of Silkweave' is completed.

**What should happen:** Quest needs to appear and work as intended or something :)

thank you

**Comment by Arkanheal** [comment]
Duplicate #3276. Closing
