### ISSUE TITLE
[GM Ingame] - Val'sharah achievement: That's Val'sharah Folks!

### ISSUE THREAD

**Issue by Defqonn** [GuabinaCore/WoWKoi#3328]
**Links:** 
https://www.wowhead.com/achievement=10698/thats-valsharah-folks
SS link: https://imgur.com/Qkr7bme
SS 2 link: https://imgur.com/wfQvpgQ

from WoWHead or our Armory

**What is happening:**
So...  I completed all the quests in Val'sharah and I didn't get the achievement .... the All Nightmare Long part has not been completed even though all the quests have been completed. As you can see in the screenshots, only Val'sharah is not passed.

**What should happen:**

After completing a given section, the achievement should highlight that section as completed

**Comment by Arkanheal** [comment]
You should contact Shen Zin and/or Smaily on Discord. 
Understand that this bugtracker is for general purposes and it looks like a character/account specific encounter.
Closing for now. Feel free to comment.

**Comment by Defqonn** [comment]
Smaily told me to do a report here... :(

**Comment by Arkanheal** [comment]
Re-opening. Waiting for informations @NightwindOI

**Comment by NightwindOI** [comment]
i'll review the acc once reach the PC and will add more info (If its needed) or close the issue.

**Comment by Cefiro-Caecias** [comment]
Tell me the name of your character and let me know when you are in the game. Or you can contact me on Discord so I instantly solve your problem.

**Comment by Cefiro-Caecias** [comment]
Solved ^^
