### ISSUE TITLE
[Quest] Massacre At Light's Point

### ISSUE THREAD

**Issue by notrinium** [GuabinaCore/WoWKoi#333]
https://www.wowhead.com/quest=12701/massacre-at-lights-point

**What is happening:**

The range of the "Scarlet Cannon"s that we use are severely lacking, and allows only the killing of the closest half of the mobs, which requires players to wait a respawn cycle. 

**What should happen:**

Should have around double the range.

**Comment by Cefiro-Caecias** [comment]
Unavoidable system limitations, for now.
