### ISSUE TITLE
Black rook hold pvp quest

### ISSUE THREAD

**Issue by ghost** [GuabinaCore/WoWKoi#3330]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=42023/black-rook-rumble
**What is happening:**
No npc's are there to hit, and if there is they're untargetable

**What should happen:**
there should be plenty of npc's there to be able to complete the wquest & you should be able to kill them.

**Comment by Arkanheal** [comment]
Duplicate #3234. Closing.
