### ISSUE TITLE
[Little Adds excesive Damage]

### ISSUE THREAD

**Issue by MatiasSparda** [GuabinaCore/WoWKoi#3331]
**Links:** 

https://es.wowhead.com/npc=105756/ara%C3%B1ita-de-l%C3%ADnea-ley
https://es.wowhead.com/npc=107843/resonancia-arcana
https://es.wowhead.com/npc=89811/m%C3%BArloc-subyugado

from WoWHead or our Armory

**What is happening:** This mobs do excesive damage, really really high, ill be posting them in the comments of this post

**What should happen:** This mobs should do minor damage because they are minor adds

Id: 105756
107843
89811

**Comment by MatiasSparda** [comment]
Ill keep updating

**Comment by Arkanheal** [comment]
Closing here. Duplicate #3255. You can update there
