### ISSUE TITLE
SE BUSCA: Mata a Brogozog. / Azsuna

### ISSUE THREAD

**Issue by NewCrooS** [GuabinaCore/WoWKoi#3332]
![imagen_2021-11-26_225805](https://user-images.githubusercontent.com/94256935/143664585-8390df0d-e73c-4845-8ff6-c1d22cda7623.png)
Lo invocas lo matas pero no te cuenta para la misión de mundo de las Celadoras.

**Comment by Cefiro-Caecias** [comment]
Bug temporal. Resuelto.
