### ISSUE TITLE
World Quest Fishing 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3333]
**Links:**

from WoWHead or our Armory

**What is happening:**
sometimes when I fish he won't let me loot, I go up to a fishing spot but I don't get anything

these are some world quests that don't work, WQs are visible on the map, but when you get to the mission area they don't activate.
https://www.wowhead.com/quest=41615/huge-stormrays
https://www.wowhead.com/quest=41275/huge-stormrays
https://www.wowhead.com/quest=41609/huge-highmountain-salmon
https://www.wowhead.com/quest=41611/huge-cursed-queenfish
https://www.wowhead.com/quest=41252/wild-northern-barracuda

**What should happen:**

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=41243/huge-highmountain-salmon
https://www.wowhead.com/quest=41266/raft-fishing

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
