### ISSUE TITLE
[GM Ingame] - Stromheim quest bug

### ISSUE THREAD

**Issue by Nicholas941205** [GuabinaCore/WoWKoi#3334]
Hello! My Stromheim questchain bugged, i dont get Helheim and back progress. unable to complete loremaster..
Character name : Mynarys
A gm told me to write a bug report

**Comment by Cefiro-Caecias** [comment]
I need more precise information to be able to do something about it ^^

**Comment by Nicholas941205** [comment]
I alredy done with helheim quests, after start the new ones in greywatch, and the server has a restart, it drops me back to helheim without quest, only the greywatch available. I think the last quest missing

**Comment by Cefiro-Caecias** [comment]
What quest do you have? Which quest are you missing? I'll cook you over low heat if you don't give me more data :P

**Comment by Nicholas941205** [comment]
I done with the quest chain , only helheim and back missing. Gm Check my quests he said everything fine, i need to write a report. What more information needed?

**Comment by Nicholas941205** [comment]
I think the last quest missing what given outside, last quest of the progress of Helheim and back

**Comment by Cefiro-Caecias** [comment]
Here are all the Stormheim quests ordered by progression. I need to know which one you are specifically missing, or which one you are stuck on. I don't know them by heart, that's why I ask for specific information:

https://wowpedia.fandom.com/wiki/Stormheim_storyline

**Comment by Nicholas941205** [comment]
![asd](https://user-images.githubusercontent.com/95046383/143786221-39e78c1e-03b2-47ed-b1dd-65221bf913db.png)

only i see this, gm told me all my quest done, but no achivement

**Comment by Cefiro-Caecias** [comment]
Excellent. Now I know how to solve your problem. Let me know when you are in the game.

**Comment by Nicholas941205** [comment]
hello, i will online from now

**Comment by Cefiro-Caecias** [comment]
Solved.
