### ISSUE TITLE
leather working quest : "fel tanning"

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#3335]
**Links:**

https://www.wowhead.com/quest=40214/fel-tanning#comments

**What is happening:**
the quest needs 2 pre needs : 
1)doing all leather working stroyline 
2)doing story-line of "" in Suramar
i have done both but the npc doesn't give me the quest npc link : 

https://www.wowhead.com/npc=98969/stalriss-dawnrunner

**What should happen:**
the npc should give the quest

**Comment by armirmoazezi** [comment]
update : after asking a gm to manually add the quest the mechanic of the quest " it should give you a training recipe in order to complete the quest and get your reward " does not work

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
