### ISSUE TITLE
[Tyce] - Nomi not working

### ISSUE THREAD

**Issue by renifer15** [GuabinaCore/WoWKoi#3337]
Links:
https://www.wowhead.com/npc=101846/nomi

What is happening:
After clicking a gossip option for Work Orders, Nomi drops dialogue and all Work Order options disappear.

What should happen:
Gossip option for Work Order should open into another window to allow queuing of multiple work orders.

After handing in 'Opening the test kitchen' You are now able to start Work Orders for any type of Legion meat or fish you possess. Each Work Order lasts 4 hours. Creating a Work Order with a specific ingredients has a chance to teach you a recipe that uses that ingredient. In 7.1, Nomi will refund you one piece of meat when the order is complete. Since patch 7.2, Nomi gives Prepared Ingredients, which allows you to discover recipes, independently of materials.
There is a high chance you will get Badly Burnt Food back from your Work Order, so don't dump all of your cooking reagents into Work Orders. There is also a chance you can get duplicate recipes, so it seems better to queue up a variety of Work Orders with different ingredients, instead of queue up Work Orders for one type of reagent.

All Rank 2 and Rank 3 recipes come from Work Orders. Several Rank 1 recipes are from Work Orders, but most are from quests or rare spawns.

**Comment by Arkanheal** [comment]
You can get nothing from Work Orders and after you looted one, you cant send another one.

**Comment by Cefiro-Caecias** [comment]
The Nomi thing is an extraordinarily complicated system. It is pending reconstruction. Be patient ^^

**Comment by Arkanheal** [comment]
I mean it's not about beeing patient or smthing (like rushing ppl left the server quite some time ago) but it basically removes cooking from the game ^^ (specially for raids as Nomi is the only way to get feast.

**Comment by NightwindOI** [comment]
Remove or not....things take time. Thx god player's  can do dungeons and raids without feast's somehow ^_^

**Comment by ShikoSCS** [comment]
Fixed, available in the next update
