### ISSUE TITLE
Scout Map Warrior

### ISSUE THREAD

**Issue by Ceresit** [GuabinaCore/WoWKoi#3338]
![scout map](https://user-images.githubusercontent.com/95138010/143687507-890f8435-7af7-422a-8fc5-297c5bbbb482.JPG)

Hello, today I concluded that the warrior scout map cannot accept these quests which are very important for each area. But yesterday I could pick up an aszuna in the area.

**Comment by Cefiro-Caecias** [comment]
Temporal bug. Solved.
