### ISSUE TITLE
Holy Paladin Artifact Quest - The Brother's Trail

### ISSUE THREAD

**Issue by Grogser** [GuabinaCore/WoWKoi#3339]
**Links:** https://www.wowhead.com/quest=42377/the-brothers-trail

**What is happening:** Lanigosa isn't present in the ridge where Jotun should appear, therefore can't talk to her and finish the quest (the quest debug doesn't help)

**What should happen:**  https://www.youtube.com/watch?v=L1Mtf_kxAqw

**Comment by Arkanheal** [comment]
Could you confirm it's a duplicate of #3343 ?

**Comment by Cefiro-Caecias** [comment]
Temporal bug. Solved.
