### ISSUE TITLE
[Quest] Standing Up - Twilight Landshaper scaling issue?

### ISSUE THREAD

**Issue by Frosty015** [GuabinaCore/WoWKoi#334]
**Links:** [Standing Up](https://www.wowhead.com/quest=27035/standing-up) and the objective [Twilight Landshaper](https://www.wowhead.com/npc=44724/twilight-landshaper)

**What is happening:** When I attack the Twilight Landshaper, most of my attacks do only a small amount of damage or even miss entirely. For reference my character is a level 30 warrior and so the twilight landshaper is scaled up to my level, giving it about 4k health.

I cleared out the mobs surrounding the objective and went to work attacking it, I did so little damage and eventually the mobs respawned, and ganged up on me, ending up with my death

**What should happen:** I'm not sure if my warrior is just weak or what but looking at videos it didn't take as long for others to kill the landshaper, so I'm thinking it might be an issue with scaling? but not sure. It's my first time doing this quest as well.

**Comment by Frosty015** [comment]
[Image](https://i.imgur.com/D7wfafy.jpg) of my toon fighting the landshaper, by this point the mobs have started respawning and are about to attack me as well

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
