### ISSUE TITLE
Ceremonial Drums

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3340]
**Links:** https://www.wowhead.com/npc=108145/bluewax-drumtaker
https://www.wowhead.com/quest=42622/ceremonial-drums
from WoWHead or our Armory

**What is happening:**
Right after killing the little dudes, picking up the drums too quickly (before their fade in animation finishes) makes looting unsuccessful and they just fade out like their job here is done.
Waiting like a sec for them to completely appear gives a successful loot
![image](https://user-images.githubusercontent.com/84509345/143690336-7490b9d6-2f43-4f8c-949e-23b708da4499.png)

**What should happen:**
They should work even if i am speed🚗

**Comment by Noahkrr** [comment]
Possible solution: when you kill the npc, do not loot the loot from the npc because the mission credit is bugged, you have to loot the drum so that it can give you credit

**Comment by Cefiro-Caecias** [comment]
Temporal bug. Solved.
