### ISSUE TITLE
Lasan Skyhorn loves talking too much

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3341]
**Links:**https://www.wowhead.com/storyline/legion-assault-highmountain-307

from WoWHead or our Armory

**What is happening:**
The world quest conversation between him and some draenei restarts constantly for days since im in the area
![image](https://user-images.githubusercontent.com/84509345/143690715-66607778-80b2-4bed-93c5-73697c64708c.png)
![image](https://user-images.githubusercontent.com/84509345/143690728-c38f22a9-311f-49ee-93d3-abcee4120dcc.png)

**What should happen:**
Only say it when the quest is there

**Comment by Cefiro-Caecias** [comment]
It will be repaired when we rebuild the area, since at the moment I have not been able to specify who those conversations took place. Patience.
