### ISSUE TITLE
Huln's War

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3342]
**Links:**https://www.wowhead.com/quest=39983/hulns-war-the-arrival

from WoWHead or our Armory

**What is happening:**
1. Spiritwalker Ebonhorn is spamming the same message.
2. Gore Charge either works but does not deal damage, or i just run in one place
3. Plague Imp most of the time evades every attack
https://youtu.be/CUbHhG430wE

**What should happen:**
1. Just say it once
2. Work and should deal damage
3. Dont evade every attack

**Comment by Arkanheal** [comment]
Duplicate #3133 and #2852
