### ISSUE TITLE
Artifact Holy Pala

### ISSUE THREAD

**Issue by Spazz89668** [GuabinaCore/WoWKoi#3343]
Stage 8, Aide to the fallen 

Will not allow you to cleanse necessary targets to complete the quest.
Have attempted to restart client, delete cashe and tried to use the artifact quest debug.

**Comment by Arkanheal** [comment]
Have you tried to contact a GM on Discord (Shen Zin and/or Smaily)? This looks like a char/acc specific bug.
Keeping open for now. Feel free to comment on any update you could have.

For further issues could you please comply with [this page](https://github.com/GuabinaCore/wowkoi/wiki/How-to-Properly-Report-an-Issue).

**Comment by Spazz89668** [comment]
was act specific
