### ISSUE TITLE
Tribal Knowledge Quest

### ISSUE THREAD

**Issue by HelooxD** [GuabinaCore/WoWKoi#3344]
After completing almost the whole Blacksmith questline the last quest which needs to follow is "Tribal Knowledge". I can't take the quest and so I can't craft any demonsteel armor (needed for other questlines)

**Comment by HelooxD** [comment]
https://www.wowhead.com/legion-blacksmithing-guide

**Comment by Cefiro-Caecias** [comment]
Fixed.
