### ISSUE TITLE
[GM Ingame] - Azhuna versus Azshara not completed

### ISSUE THREAD

**Issue by Lavidabeaar** [GuabinaCore/WoWKoi#3345]
**Links:**
![image](https://user-images.githubusercontent.com/94609933/143723822-3215cd5f-1f9e-4a3d-8e4f-c6abc2516fe1.png)
(My picture)

from WoWHead or our Armory

**What is happening:**

Can't get the third chapter in Azsuna to get completed. Done all the necessary quest for it to be completed. Checked with a GM (Paerux) to check that everything was done right and he confirmed that it was. 

**What should happen:**
Should have completed the third chapter in Azhuna.

**Comment by Cefiro-Caecias** [comment]
Tell me the name of your character and let me know when you are in the game. Or you can contact me on Discord so I instantly solve your problem.

**Comment by Lavidabeaar** [comment]
IGN: Lavida.  I'am ingame right now

**Comment by Cefiro-Caecias** [comment]
I'am ingame, honey.

**Comment by Cefiro-Caecias** [comment]
Solved ^^
