### ISSUE TITLE
[Loch Modan] Tunnel Rat Geomancer Dialogue

### ISSUE THREAD

**Issue by Frosty015** [GuabinaCore/WoWKoi#335]
**Links:** [Geomancer](https://classic.wowhead.com/npc=1174/tunnel-rat-geomancer#screenshots)

[Sample of the bug](https://i.imgur.com/ObTyLdK.jpg)
**What is happening:** When attacking the mob, it says "Me no run from $C like you!"

**What should happen:** Should say "Me no run from [Class Name] like you!"

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
