### ISSUE TITLE
[Tyce] - Legendary Drop Rate - Bad Luck Protection

### ISSUE THREAD

**Issue by TheUnmercey** [GuabinaCore/WoWKoi#3350]
**Links:**
https://www.icy-veins.com/forums/topic/26152-legendary-bad-luck-protection-system/
from WoWHead or our Armory

**What is happening:**
I've been playing the Legion Koi content since the beginning, but the Legendary Drop didn't happen. However, my current number of boss kills has long since exceeded 300 (see screenshot). This means that in normal cases, the Bad Luck Protection would have intervened long ago. 

![2021-11-28 16_29_57-Window](https://user-images.githubusercontent.com/95048939/143775636-a0d8d5dd-fb1f-4d96-9fa2-ca88b994aa00.png)
**What should happen:**
Based on the Bad Luck Protection, an approximate number for the drop of the first Legendary Item has been calculated on Retail. Unfortunately, I don't know the exact number, but I think Bad Luck Protection should intervene if there are over 300 boss kills.
![2021-11-28 16_55_14-Window](https://user-images.githubusercontent.com/95048939/143775673-e72e2c69-aaf8-48bf-a01e-12fa57dfa14c.png)

**Comment by Arkanheal** [comment]
This needs further inspection but I do believe it to be true.

**Comment by ShikoSCS** [comment]
Fixed
