### ISSUE TITLE
[Freeing the Taken]

### ISSUE THREAD

**Issue by ggb1011** [GuabinaCore/WoWKoi#3351]
**Links:** https://www.wowhead.com/quest=42209/freeing-the-taken

from WoWHead or our Armory

**What is happening:**
I cant free the prisoners when i have the itmes

**What should happen:**
https://www.youtube.com/watch?v=4v0tm94sR_A&t=56s

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
