### ISSUE TITLE
[Sefrenia] - Fishing hooks

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3353]
**Links:**

from WoWHead or our Armory

**What is happening:**
Check the drop rate of these hooks and insert them into the game if they are not

Stormheim
https://www.wowhead.com/item=133713/moosehorn-hook#fished-in
https://www.wowhead.com/item=133716/soggy-drakescale
https://www.wowhead.com/item=133714/silverscale-minnow
https://www.wowhead.com/item=133715/ancient-vrykul-ring

Azsuna
https://www.wowhead.com/item=133701/skrog-toenail
https://www.wowhead.com/item=133702/aromatic-murloc-slime
https://www.wowhead.com/item=133704/rusty-queenfish-brooch
https://www.wowhead.com/item=133703/pearlescent-conch

Highmountain
https://www.wowhead.com/item=133709/funky-sea-snail
https://www.wowhead.com/item=133710/salmon-lure
https://www.wowhead.com/item=133711/swollen-murloc-egg
https://www.wowhead.com/item=133712/frost-worm

Valsharah
https://www.wowhead.com/item=133705/rotten-fishbone
https://www.wowhead.com/item=133707/nightmare-nightcrawler
https://www.wowhead.com/item=133708/drowned-thistleleaf

Suramar
https://www.wowhead.com/item=133717/enchanted-lure
https://www.wowhead.com/item=133719/sleeping-murloc
https://www.wowhead.com/item=133720/demonic-detritus

The Great Sea (these hooks have been successfully achieved)
https://www.wowhead.com/item=133721/message-in-a-beer-bottle
https://www.wowhead.com/item=133722/axefish-lure
https://www.wowhead.com/item=133724/decayed-whale-blubber
https://www.wowhead.com/item=133723/stunned-angry-shark
https://www.wowhead.com/item=133795/ravenous-fly

**Comment by Cefiro-Caecias** [comment]
The items are placed in their respective loot tables, and their drop percentage is placed according to what wowhead indicates, although they are very low: 0.6, 0.9, 1.1, etc. We can improve that percentage by reaching a consensus. I listen to suggestions.

**Comment by Cefiro-Caecias** [comment]
Added missing items, drop increased to 10% on fishing nodes. Available in the enxt update.
