### ISSUE TITLE
Hobart Grapplehammer/Fargo Flintlocke <Engineering Supplies> - Missing Items

### ISSUE THREAD

**Issue by TheUnmercey** [GuabinaCore/WoWKoi#3354]
**Links:**
https://www.wowhead.com/npc=93539/hobart-grapplehammer#sells
https://youtube.com/clip/Ugkx6949P5eBtH0Vkmm4A1TpXQuhrOvNOkjF
from WoWHead or our Armory

**What is happening:**
![2021-11-28 20_05_00-Window](https://user-images.githubusercontent.com/95048939/143782251-695dd4bb-fc18-4e38-a133-fbc08536d052.png)
These vendors do not sell the items required for the manufacture of various engineering items. 
- At this moment they can only be obtained by attaching the shoulder Enchantment - https://www.wowhead.com/item=144330/sprocket-container
**What should happen:**
These Items are required:
https://www.wowhead.com/item=136629/felgibber-shotgun
https://www.wowhead.com/item=136630/twirling-bottom-repeater
https://www.wowhead.com/item=136631/surface-to-infernal-rocket-launcher
https://www.wowhead.com/item=136632/chaos-blaster

**Comment by Cefiro-Caecias** [comment]
The NPC owns the items you mention, but due to the Class filter many times it does not show them. When you open the sale tab, in the upper right corner, activate the last option "All", and then it will show you all your items for sale.
