### ISSUE TITLE
Bonus objectives

### ISSUE THREAD

**Issue by Grogser** [GuabinaCore/WoWKoi#3357]
**What is happening:**
Bonus objectives are showing up as expired, none of them show progress when you try and do them, so players can't complete them.

**What should happen:**
Should work normally, couple bonus objectives should show up in every zone and award gold + exp. Players should be able to actually complete them.

**Comment by Noahkrr** [comment]
I have the same problem, the bonus objetives are not active, they must be active because I haven't completed them yet

**Comment by Cefiro-Caecias** [comment]
Temporal bug. Solved.
