### ISSUE TITLE
Balance druid, Seed of Ages

### ISSUE THREAD

**Issue by MolnarAlmos** [GuabinaCore/WoWKoi#3360]
**Links:** https://www.wowhead.com/quest=41255/sowing-the-seed

from WoWHead or our Armory

**What is happening:** Balance druids not getting Artifact Power to Imbue the weapon

**What should happen:** https://www.wowhead.com/quest=41255/sowing-the-seed

**Comment by Cefiro-Caecias** [comment]
You must have the Artifact Weapon equipped at the time of taking the quest, and then you will receive 100 AP. Please try again fulfilling that condition ^^
