### ISSUE TITLE
skinning 735-800 / quest 

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#3361]
**Links:**
https://www.wowhead.com/quest=40132/in-one-piece#comments 
this quest is not dropping at all ( i have 735 skinning skill point it should drop very early on ) 

https://www.wowhead.com/legion-skinning-guide
after reaching 735 there is no skill gain with skinning mobs ( i killed 400+ after reaching 735 ) 

**What should happen:**
the quest should drop fairly early 
you should get +1 point per mob just like 1-735

**Comment by Noahkrr** [comment]
World quets do not give points above 737p and some have a bug, and the amount of skins per rank (either rank 1,2 or 3), always give the same amount between 2-3-4

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
