### ISSUE TITLE
Xandris the dishonored

### ISSUE THREAD

**Issue by vechiiro** [GuabinaCore/WoWKoi#3364]
**Links:**

from WoWHead or our Armory

**What is happening:**
I just one shotted Xandris the dishonored NPC

**What should happen:**
I shouldn't one shot him im a 100lvl blood dk

**Comment by NightwindOI** [comment]
That's the reason
https://i.imgur.com/1ZLqJ2a.png
Quest work fine, but since that part is missing, everyone one-shot him (the tiger suppose to one-shot him tho)

**Comment by NightwindOI** [comment]
Closed mean it will be improved or gonna stay the way it is?

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.

**Comment by MrDeadNoob** [comment]
I have to reopen it because NPC doesnt die he restores instant help from 6% to ~40%

Video: https://disturbednoob.ml/media_files/bugreports/2022-06-01-03-37-59.mp4

**Comment by Cefiro-Caecias** [comment]
Hmmm... I just tried it 3 times, and had no problems. However, there is a persistent bug in your video. I dare to speculate that it was not a bug in the mob itself, but a temporary bug in the Server, which returned the variables wrong. Try it again when you can, and let me know if it worked for you.
