### ISSUE TITLE
[Tyce] - After learning the talent tree in the mage class hall, there are no portals everywhere.

### ISSUE THREAD

**Issue by jlspwsn** [GuabinaCore/WoWKoi#3365]
**Links:**
https://www.wowhead.com/order-advancement=386/teleportation-nexus

from WoWHead or our Armory

**What is happening:**

There is no portal to any place

**What should happen:**

After the research is successful, it can be quickly transmitted to various places

**Comment by jlspwsn** [comment]
![14](https://user-images.githubusercontent.com/49065263/144026137-089a28a4-9579-4527-8516-cd9d0f753c43.png)

**Comment by ericdethman** [comment]
confirmed, portals do not appear after learning the talent tree.

**Comment by jlspwsn** [comment]
> confirmed, portals do not appear after learning the talent tree.

How long can it be solved?

**Comment by jlspwsn** [comment]
+++++++++1

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
