### ISSUE TITLE
World Quest - Defense of Emerald Bay 

### ISSUE THREAD

**Issue by gigaslurp** [GuabinaCore/WoWKoi#3366]
**Links:**
[https://www.wowhead.com/quest=44884/defense-of-emerald-bay](https://www.wowhead.com/quest=44884/defense-of-emerald-bay)

**What is happening:**
Despite showing a world quest on the map and mini-map, there are no legion forces to kill.
![image](https://user-images.githubusercontent.com/73703079/143984040-a2403350-cc8a-4b96-bf0e-d6eabc51b7e4.png)

**What should happen:**
There should be legion mobs for the players to kill.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
