### ISSUE TITLE
Army of the light world quests

### ISSUE THREAD

**Issue by gankyplanky** [GuabinaCore/WoWKoi#3367]
![WoWScrnShot_113021_073909](https://user-images.githubusercontent.com/56677315/144004644-cbbf414e-5747-4fc2-bde4-f4718cfa05d1.jpg)
One of the daily missions for world quests appeared as army of the light, this shouldnt happen untill one unlocks argus world quests

**Comment by NightwindOI** [comment]
We gonna leave it like that for now, since removing it gonna take too much time. And since Argus is disabled now, it's ok.
