### ISSUE TITLE
world quest work order : warhide footpads 

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#3368]
**Links:**

https://www.wowhead.com/quest=41642/work-order-warhide-footpads 
the item link : 
https://www.wowhead.com/item=128877/warhide-footpads

**What is happening:**
the world quest appears on map and it exists on the zone bug when i create the pad even in the zone and objective is complete the quest will not get complete 

**What should happen:**
after creating the item it should give you rank 3 of that recipe

**Comment by Cefiro-Caecias** [comment]
Fixed.
