### ISSUE TITLE
mounting made easy quest

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#3369]
**Links:**
https://www.wowhead.com/quest=40215/mounting-made-easy 

**What is happening:**

the indicator for map is in wrong place 
when you find the npc the channeling spell breaks instanly therefore the quest is not doable 

**What should happen:**

indicator must be change 
the channeling spell should stays on as long as the npc is running away in order to capture it

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.-
