### ISSUE TITLE
Orgrimmar Guild Vendor - Goram

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#337]
**Links:**
https://www.wowhead.com/npc=46572/goram
from WoWHead or our Armory

**What is happening:**
He isn't spawned in orgrimmar.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Yes, it is in Orgrimmar, but its sale tab is disabled until the Guilds module is implemented.

**Comment by Serithul** [comment]
It is not in the place it should be then. Close to the tabard vendor.

**Comment by Serithul** [comment]
![WoWScrnShot_032920_231134](https://user-images.githubusercontent.com/62258982/77859531-ae736f80-7212-11ea-8b01-5491d57f43bd.jpg)
