### ISSUE TITLE
unable to retrieve emerald winds, AGAIN.

### ISSUE THREAD

**Issue by burt245** [GuabinaCore/WoWKoi#3370]
Links:
[from WoWHead or our Armory](https://www.wowhead.com/achievement=10774/hatchling-of-the-talon)

What is happening:
everything worked, i got the toy, used it, it worked. then server restarted and it was rolled back. 

a while later shen zin allready restored the item for me, but now its gone again! 

[proof](https://imgur.com/a/vivt162)

What should happen:
the toy should still be there.

player name is burtmacklin

**Comment by Cefiro-Caecias** [comment]
Item sent by mail ;)
