### ISSUE TITLE
Blood DK Runeforging missing

### ISSUE THREAD

**Issue by vechiiro** [GuabinaCore/WoWKoi#3372]
**Links:**

from WoWHead or our Armory

**What is happening:**
Well guys just like the title says. I am missing my runeforging ability since some time now. I have checked the shop just in case but no luck.

**What should happen:**
Please restore the ability and thank you ^^ 

PS : character name is "Vechiiro"

**Comment by Divix1** [comment]
It's an issue for all DK specs, not just blood. However it does seem as a reoccurring one based on the closed topics on the same subject without a permanent fix. 

The skill is granted by the level 100 boost but somewhere between boosting and obtaining the artefact weapons it goes missing. Some people said that it disappears when you first step into Dalaran (not sure tho).

If it's possible, a random NPC or something in the DK order hall that could teach them the skill or enchant their weapons might be an idea until there is a more permanent fix? Just a suggestion so GMs don't have to bother with every person who makes a DK on the server as runeforging is a fairly important mechanic for them.

**Comment by Cefiro-Caecias** [comment]
Contact me on Discord, so I enter the game and teach you those skills ;)
