### ISSUE TITLE
[Sefrenia] - NPC not synced with WQ - Profession

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3373]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=93237/brimstone-destroyer
https://www.wowhead.com/npc=103675/felhide-gargantuan
brimstone destroyer and felhide gargantuan, these npc are not in sync with their corresponding WQ, only a few, most of these npc are scattered on the map, making any user kill these npc and get materials, and if you want to wait a few 5 or more 6 minutes for the npc to reappear and kill it again and obtain materials (abusing the bug you can obtain large quantities in a short time, without waiting for the WQ to activate)
![image](https://user-images.githubusercontent.com/81131460/144171295-87fece61-c634-43b9-b1e3-c9fb70e2e7c7.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
