### ISSUE TITLE
[Tyce] - Monk - Hit Combo

### ISSUE THREAD

**Issue by itsmekasta** [GuabinaCore/WoWKoi#3375]
**Links:**

https://peakofserenity.com/2016/07/26/spotlight-hit-combo-and-mastery/
https://youtu.be/LxZu4QR6LlE?t=194

**What is happening:**

Flying Serpent Kick doesn't provide a stack of Hit Combo out of combat.
Only works once after I log back to the game.
Character is level 100.

**What should happen:**

Giving a stack of Hit Combo out of combat.
_It's really important to have it, since it's a part of its rotation before and during the pulls._

**Comment by Travven** [comment]
I didnt see this problem.
The spell is working OK.
