### ISSUE TITLE
This IS in My Contract

### ISSUE THREAD

**Issue by crunchytoastly** [GuabinaCore/WoWKoi#3377]
**Links:**
https://www.wowhead.com/quest=38237/this-is-in-my-contract

from WoWHead or our Armory

**What is happening:**
Imp despawns when you enter the cave

**What should happen:**
Should be able to talk to the imp to summon the mod

**Comment by crunchytoastly** [comment]
summon the mob* typo

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
