### ISSUE TITLE
Argussian Reach wq 

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#3378]
**Links:**
following world quest and its emissary must be removed from the game ( wording may change as devs please) : 

part 1 dungeon world quests : 

https://www.wowhead.com/quest=48985/seat-of-the-triumvirate-twilight-harbinger-tharuul
https://www.wowhead.com/quest=48957/seat-of-the-triumvirate-void-blade-zedaat
https://www.wowhead.com/quest=48951/seat-of-the-triumvirate-voidmaw
https://www.wowhead.com/quest=48953/seat-of-the-triumvirate-darkcaller
https://www.wowhead.com/quest=48959/seat-of-the-triumvirate-dark-fissures

part 2 rare elite world quests : 

https://www.wowhead.com/quest=48737/instructor-tarahna
https://www.wowhead.com/quest=48726/turek-the-lucid
https://www.wowhead.com/quest=48282/imp-mother-laglath
https://www.wowhead.com/quest=48466/venorn
https://www.wowhead.com/quest=48740/skreeg-the-devourer
https://www.wowhead.com/quest=48467/puscilla
https://www.wowhead.com/quest=48502/naroua-king-of-the-forest
https://www.wowhead.com/quest=48835/houndmaster-kerrax
https://www.wowhead.com/quest=48091/vagath-the-betrayed
https://www.wowhead.com/quest=48834/worldsplitter-skuul
https://www.wowhead.com/quest=48733/jedhin-champion-vorusk
https://www.wowhead.com/quest=47833/shadowcaster-voruun
https://www.wowhead.com/quest=48722/feasel-the-muffin-thief
https://www.wowhead.com/quest=48732/sabuul
https://www.wowhead.com/quest=48509/commander-sathrenael
https://www.wowhead.com/quest=48192/tar-spitter
https://www.wowhead.com/quest=48827/varga
https://www.wowhead.com/quest=47953/tereck-the-selector
https://www.wowhead.com/quest=48696/wrangler-kravos
https://www.wowhead.com/quest=48831/commander-texlaz
https://www.wowhead.com/quest=47728/talestra-the-vile
https://www.wowhead.com/quest=48725/venomtail-skyfin
https://www.wowhead.com/quest=48729/ataxon
https://www.wowhead.com/quest=48866/void-warden-valsuran
https://www.wowhead.com/quest=47542/siegemaster-voraan
https://www.wowhead.com/quest=48511/commander-endaxis
https://www.wowhead.com/quest=48730/sorolis-the-ill-fated
https://www.wowhead.com/quest=48836/watcher-aival
https://www.wowhead.com/quest=48867/chief-alchemist-munculus
https://www.wowhead.com/quest=47561/blistermaw
https://www.wowhead.com/quest=48510/commander-vecaya
https://www.wowhead.com/quest=48728/umbraliss
https://www.wowhead.com/quest=47507/khazaduum
https://www.wowhead.com/quest=48738/zultan-the-numerous
https://www.wowhead.com/quest=48837/all-seer-xanarian
https://www.wowhead.com/quest=48512/sister-subversia
https://www.wowhead.com/quest=47552/mistress-ilthendra
https://www.wowhead.com/quest=47566/garzoth
https://www.wowhead.com/quest=48694/soultwisted-monstrosity
https://www.wowhead.com/quest=48723/vigilant-thanos
https://www.wowhead.com/quest=48727/captain-faruq
https://www.wowhead.com/quest=48828/lieutenant-xakaar
https://www.wowhead.com/quest=48830/inquisitor-vethroz
https://www.wowhead.com/quest=48734/overseer-ybeda
https://www.wowhead.com/quest=48936/slithon-the-last
https://www.wowhead.com/quest=48731/herald-of-chaos
https://www.wowhead.com/quest=48735/overseer-ysorna
https://www.wowhead.com/quest=48739/commander-xethgar
https://www.wowhead.com/quest=48465/vraxthul
https://www.wowhead.com/quest=48701/baruut-the-bloodthirsty
https://www.wowhead.com/quest=48832/admiral-relvar
https://www.wowhead.com/quest=48724/vigilant-kuro
https://www.wowhead.com/quest=48736/overseer-ymorna
https://www.wowhead.com/quest=48829/wrath-lord-yarez
https://www.wowhead.com/quest=48698/kaara-the-pale

part 3 emissary quest : 
https://www.wowhead.com/quest=48642/argussian-reach

part 4 profession world quests : 

https://www.wowhead.com/quest=48363/work-order-florid-malachite
https://www.wowhead.com/quest=48364/work-order-hesselian
https://www.wowhead.com/quest=48359/work-order-fiendish-leather
https://www.wowhead.com/quest=48373/work-order-lightweave-cloth
https://www.wowhead.com/quest=48349/work-order-empyrium
https://www.wowhead.com/quest=48337/work-order-astral-glory
https://www.wowhead.com/quest=48323/work-order-tears-of-the-naaru
https://www.wowhead.com/quest=48318/work-order-lightblood-elixirs 

part 5 battle per world quests : 

https://www.wowhead.com/quest=49051/corrupted-blood-of-argus
https://www.wowhead.com/quest=49052/marcuus
https://www.wowhead.com/quest=49048/snozz
https://www.wowhead.com/quest=49047/bucky
https://www.wowhead.com/quest=49049/gloamwing
https://www.wowhead.com/quest=49050/shadeflicker

part 6 normal world quests : 

https://www.wowhead.com/quest=48338/supplies-needed-astral-glory
https://www.wowhead.com/quest=47456/calming-the-void
https://www.wowhead.com/quest=48358/supplies-needed-empyrium
https://www.wowhead.com/quest=48096/core-mechanics
https://www.wowhead.com/quest=48097/gatekeepers-review-cunning
https://www.wowhead.com/quest=48100/the-defense-of-eredath
https://www.wowhead.com/quest=48106/no-love-lost
https://www.wowhead.com/quest=48360/supplies-needed-fiendish-leather
https://www.wowhead.com/quest=47624/bury-it
https://www.wowhead.com/quest=47844/recurring-madness
https://www.wowhead.com/quest=47858/security-engaged
https://www.wowhead.com/quest=48175/hidden-in-the-hollows
https://www.wowhead.com/quest=47646/rope-around
https://www.wowhead.com/quest=47135/for-their-own-good
https://www.wowhead.com/quest=47625/the-ritual-we-share
https://www.wowhead.com/quest=48374/supplies-needed-lightweave-cloth
https://www.wowhead.com/quest=48098/garden-pests
https://www.wowhead.com/quest=47828/memories-of-the-fallen
https://www.wowhead.com/quest=48094/void-clot
https://www.wowhead.com/quest=48099/hostile-echology
https://www.wowhead.com/quest=48102/scale-samples
https://www.wowhead.com/quest=48103/gatekeepers-review-tenacity
https://www.wowhead.com/quest=47551/lessons-of-fire-and-pain
https://www.wowhead.com/quest=47563/spirits-of-the-fallen
https://www.wowhead.com/quest=48095/dark-experimentation

**Comment by armirmoazezi** [comment]
update : 
after further research i found out "army of the light" world quests have the same quest list as this one 

https://www.wowhead.com/faction=2170/argussian-reach#quests;0-2+1+13

https://www.wowhead.com/faction=2165/army-of-the-light#quests;0-2+1+13

**Comment by Cefiro-Caecias** [comment]
It is not possible, at the moment, to block these quests, since they are controlled by an automatic and autonomous system.
