### ISSUE TITLE
[Tyce] - Item Fighter Chow

### ISSUE THREAD

**Issue by jlspwsn** [GuabinaCore/WoWKoi#3379]
**Links:**
https://web.archive.org/web/20160910173131/http://www.wowhead.com:80/item=129179/fighter-chow

from WoWHead or our Armory

**What is happening:**
The description is to restore 1000% of health per second. The current game shows that it is 400%

**Comment by Travven** [comment]
The spell changed in 7.2
![Screenshot_2021-12-09-18-19-16-812_com android chrome](https://user-images.githubusercontent.com/75356961/145490978-414cb383-c251-40a5-8a99-ca4d92e3cab4.jpg)

**Comment by Travven** [comment]
Fixed.
