### ISSUE TITLE
Orgrimmar Left elevator problem.

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#338]
**Links:**
https://imgur.com/a/IImQEwa
from WoWHead or our Armory

**What is happening:**
As it can be seen in the picture, there are two platforms on the left side elevator, when seen from in front of the main building in valley of strength.

**What should happen:**
There should only be one platform.

**Comment by Cefiro-Caecias** [comment]
Lag visual bug.

**Comment by Serithul** [comment]
Indeed it was, sorry for this report
