### ISSUE TITLE
When i end side quest i got mark and cant use keys to walk

### ISSUE THREAD

**Issue by Skuniorek** [GuabinaCore/WoWKoi#3381]
Hey, after i done mission ,,burn the candle at the both ends,, i get mark like npc's have and i cant walk!
Unstuck didn't work.
Can someone reapair it?
https://cdn.discordapp.com/attachments/490641437537468439/915989595655647252/unknown.png

Name: Swaggmag

**Comment by OnlyWATCH** [comment]
![image](https://user-images.githubusercontent.com/82822767/144458240-1d2368eb-4466-44c6-9b14-238811d84733.png)

npc : https://www.wowhead.com/quest=40345/burn-the-candle-at-both-ends

quest 1 : https://www.wowhead.com/quest=40339/candle-of-command
quest 2 : https://www.wowhead.com/quest=40345/burn-the-candle-at-both-ends
quest 3 : https://www.wowhead.com/quest=39772/cant-hold-a-candle-to-you

**Comment by Cefiro-Caecias** [comment]
Temporal bug. Any problem, contact me on Discord.
