### ISSUE TITLE
The drop rate of Stalker claw is really low from the Legion Leatherworking StoryLine

### ISSUE THREAD

**Issue by Tonage** [GuabinaCore/WoWKoi#3384]
Quest Item: https://www.wowhead.com/item=130070/stalker-claw#dropped-by
Quest : https://www.wowhead.com/quest=40192/claw-of-the-land
from WoWHead or our Armory

**What is happening:**
This quest is from a story line of Legion Leatherworking.  It requests 100 claws of the pinerock stalkers. I killed about 50 stalkers only drop about 10 claws. 

**What should happen:**
THe drop rate of claws should be about 11% based on the wowhead. Additionally, if you are a skinner, you should be able to get additional claws from skinning.

Here is a video to show how the rate and numbers per drop should be.
https://www.youtube.com/watch?v=V2ciajYqvM4

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
