### ISSUE TITLE
[World quest] Tip the Scales [Azsuna]

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3385]
**Links:**

[from WoWHead or our Armory](https://www.wowhead.com/quest=37779/tip-the-scales)

**What is happening:**

 kill's and objectives don't count.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
I just tried both versions of the quest, and they worked perfectly for me. Make sure to delete the Cache folder from your WoW, or wait for the WQ reset that occurs on Tuesdays / Wednesdays.
