### ISSUE TITLE
[World quest] Faerie Fracas 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3386]
**Links:**

https://www.wowhead.com/quest=38842/faerie-fracas

**What is happening:**

Killing the mobs and clicking on the objects don't gain any quest progress.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
I tried that quest today, and it didn't give me a problem. I don't know what could be causing the bug for you.

**Comment by NightwindOI** [comment]
Well, it's not only me.  Can hand you my account to try it out with it.
