### ISSUE TITLE
 [Tyce] - Gear ilevel scaling

### ISSUE THREAD

**Issue by madbessoul** [GuabinaCore/WoWKoi#3387]
**Links:**
https://web.archive.org/web/20161114231025/https://www.wowhead.com/mythic-keystones-and-dungeons-guide
https://wow.4fansites.de/legion-item-level.php (in German, use Google Translate)
http://web.archive.org/web/20161024220650/http://www.worldofmoudi.com/ilvl-legion
https://www.reddit.com/r/wow/comments/584n02/updated_ilvl_chart_for_legion_including_71/ (Updated to 7.1)
https://www.millenium.org/news/245211.html (in French, use Google Translate)

![image](https://user-images.githubusercontent.com/2671740/144720238-197486a7-ec8c-463d-aa17-ec58850171f9.png)

***What is happening:***
Gear ilvl from almost every type of content is wrong ; everything is squished down to 850 without regard to player ilvl or M+ keys.
For example : 
 - Obliterum crafted gear can go as high as ilvl900, 
 - Mythic gear is scaled at 850 without regard to Titanforged/warforged or the key level.
 - World quests give up to 890 which is squished to 850.

***What should happen:***
Based on the links above and experience from players who have played retail at the beginning of Legion, here's an examples of the ilvl of gear from the main activities : 
 - Normal dungeons : 805+, rare Titanforged up to 825 (+20), epic titanforged up to 840 (+35)
 - Heroic dungeons : 825+, rare Titanforged up to 830, epic Titanforged up to 865.
 - Mythic dungeons : 
<html><body>

Level | Dungeon Chest | Class Hall Chest
-- | -- | --
Regular Mythic | 840 | N/A
2 | 845 | 850
3 | 845 | 855
4 | 850 | 860
5 | 850 | 865
6 | 855 | 865
7 | 855 | 870
8 | 860 | 870
9 | 860 | 875
10 | 865 | 880
11 | 870 | 880
12+ | 870 | 885

</body>
</html>
Possibility to get +10 above base ilvl (Warforged) or +15 (Titanforged)

 - World quests : starts at 805-840, scales with player ilevel.
 - Class Order Hall Sets : 810-850, scales with Order Hall progression
 - World boss : 860
 - Crafted items are capped at 815, and can be upgraded with obliterum with a cap of 850 (up to 855 with the release of Emerald Nightmare)
 - Legendary items : 895

This is not an exhaustive report, and ilevel is upgraded throughout the patches. Feel free to comment if I've got something wrong or have additional sources.

**Comment by ShikoSCS** [comment]
A general repair was made regarding this report. We cannot guarantee that it will be 100% blizzlike but it must be priced at the maximum itemlvl that can be obtained according to the type of difficulty or type of reward. We need you to notify us if you notice any defect.
