### ISSUE TITLE
[Dungeon] Neltharion Lair (NM)  [NPC] Wrong scale

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3388]
**Links:**

https://www.wowhead.com/npc=91000/vileshard-hulk
https://www.wowhead.com/npc=91004/ularogg-cragshaper
https://www.wowhead.com/npc=91005/naraxas
https://www.wowhead.com/npc=102287/emberhusk-dominator
https://www.wowhead.com/npc=91007/dargrul

**What is happening:**
All of them are scaled to level 110 as level, damage, and hp.

**What should happen:**
Suppose to scale down to your level from 100 to 110

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
