### ISSUE TITLE
[Tyce] - NPC damage in Mythic dungeons

### ISSUE THREAD

**Issue by madbessoul** [GuabinaCore/WoWKoi#3389]
## Links
[Vault of the Wardens, Mythic +2, 850ilevel (youtube)](https://www.youtube.com/watch?v=VjbKAe5Wz3k)
[Vault of the Wardens, Mythic +2 (youtube)](https://www.youtube.com/watch?v=MStEduYqocM)

https://web.archive.org/web/20161114231025/https://www.wowhead.com/mythic-keystones-and-dungeons-guide
(It's very hard to find reliables sources for the exact NPC damage for different bosses and trash mobs, the closest I've got is the aforementioned videos captured at the beginning of Legion and with an ilevel close to the current state of Wow-Koi)

## What is happening
NPC (Bosses and Trash mobs) do insanely high damage in Mythic+
We have tried killing the first boss of M2 Vault of the Wardens with an 850+ tank, he was taking insanely high damage compared to what is shown in the linked videos. 
More generally, damage scaling is off by an order of magnitude in Mythic+ dungeons, so the point where M2 feels like M10+.

## What should happen 
Damage in mythic+ should scale linearly the higher the keys, based on these modifiers : 
<html><body>

Level | +Health and Damage %
-- | --
Mythic | n/a
2 | +8%
3 | +17%
4 | +26%
5 | +36%
6 | +45%
7 | +59%
8 | +71%
9 | +85%
10 | +100%
11 | +116%

</body>
</html>

I am not sure if the problem arises from very high M0 base damage or overtuned modifiers for M+, but based on our Mythic runs, it feels like both are an issues, since although M0 is doable the damage is still too high.

This issue combined with the wrong scaling of gear ilevel (#3387) there is no incentive to do M+ and also encourages people to abuse Obliterum gear (900ilvl).

**Comment by jlspwsn** [comment]
+1
