### ISSUE TITLE
[Arthas] - Kall Worthaton - Goblin Mount seller

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#339]
**Links:**
https://www.wowhead.com/npc=48510/kall-worthaton
from WoWHead or our Armory

**What is happening:**
You can buy the mounts without being exalted with the Bilgewater Cartel.

**What should happen:**
You need exalted standing with the mentioned faction in order to buy the mounts.

**Comment by Cefiro-Caecias** [comment]
Arthas, qué hacemos con esto?:

1.- Si le pongo al item en Hotfixes que requiera exaltado para poder adquirirlo, el ítem no lo muestra, sólo dice que "no tienes la reputación adecuada" para poder comprarlo.

2.- Si le pongo un condition a la venta, el goblin no te muestra el ítem directamente, y parece bug o que no vend enada.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
