### ISSUE TITLE
NPC - misiones de mundo de profesiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3390]
**Links:**

from WoWHead or our Armory

**What is happening:**
**NPC Valdemar buscatormenta**
https://es.wowhead.com/npc=106904/valdemar-buscatormentas

Estas son las Misiones de mundo de Profesiones que termina:
necesario Inscripción 
https://es.wowhead.com/quest=41666/pedido-de-runa-vantus-nythendra
necesario Joyería
https://es.wowhead.com/quest=41654/pedido-aro-de-ópalo-de-reina
Sastrería
https://es.wowhead.com/quest=41648/pedido-brazales-de-filoseda
Alquimia
https://es.wowhead.com/quest=41660/pedido-brebajeskaggl
Herrería
https://es.wowhead.com/quest=41636/pedido-coraza-de-piedra-ley
necesario Desuello
https://es.wowhead.com/quest=41344/pedido-escamas-tormentosas
necesario peleteria Peletería
https://es.wowhead.com/quest=41642/pedido-escarpines-de-pellejo-de-guerra
necesario Herbolestería
https://es.wowhead.com/quest=41297/pedido-fjarnskaggl
necesario Ingeniería
https://es.wowhead.com/quest=41678/pedido-pack-de-armas
necesario Encantamiento
https://es.wowhead.com/quest=41672/pedido-palabra-de-celeridad
necesario Minería
https://es.wowhead.com/quest=41313/pedido-piedra-ley
necesario Pesca
https://es.wowhead.com/quest=41277/pedido-rayatormentas

Misiones de mundo
https://es.wowhead.com/quest=41345/suministros-necesarios-escamas-tormentosas
https://es.wowhead.com/quest=41298/suministros-necesarios-fjarnskaggl
https://es.wowhead.com/quest=41317/suministros-necesarios-piedra-ley

**NPC Sylvia Cornociervo**
https://es.wowhead.com/npc=106901/sylvia-cornociervo

Estas son las Misiones de mundo de Profesiones que termina:
necesario Inscripción
https://es.wowhead.com/quest=41664/pedido-de-runa-vantus-dragones-de-la-pesadilla
necesario Joyería
https://es.wowhead.com/quest=41652/pedido-anillo-de-ámbar-intenso
necesario Alquimia
https://es.wowhead.com/quest=41658/pedido-elixires-nemorosos
necesario Herbolesteria
https://es.wowhead.com/quest=41292/pedido-frondasueño
necesario Sastrería
https://es.wowhead.com/quest=41646/pedido-guantes-de-filoseda
necesario Herrería
https://es.wowhead.com/quest=41634/pedido-guardabrazos-de-piedra-ley
necesario Peletería
https://es.wowhead.com/quest=41640/pedido-máscara-de-pellejo-de-guerra
necesario Encantamiento
https://es.wowhead.com/quest=41670/pedido-palabra-de-agilidad
necesario Pesca
https://es.wowhead.com/quest=41272/pedido-perca-branquimusgo
necesario Minería
https://es.wowhead.com/quest=41312/pedido-piedra-ley
necesario Ingeniería
https://es.wowhead.com/quest=41676/pedido-pistola-de-vendas-de-pistón
Desuello
https://es.wowhead.com/quest=41338/pedido-cuero-de-petrapiel

Misiones de mundo
https://es.wowhead.com/quest=41293/suministros-necesarios-frondasueño
https://es.wowhead.com/quest=41316/suministros-necesarios-piedra-ley
https://es.wowhead.com/quest=41339/suministros-necesarios-cuero-de-petrapiel

**NPC Ransa Pluma Gris**
https://es.wowhead.com/npc=106902/ransa-pluma-gris

Estas son las Misiones de mundo de Profesiones que termina:
necesario Inscripción
https://es.wowhead.com/quest=41665/pedido-de-runa-vantus-ursoc
necesario Peletería
https://es.wowhead.com/quest=41641/pedido-bandas-de-vínculo-bélico
necesario Herrería
https://es.wowhead.com/quest=41635/pedido-botas-de-piedra-ley
necesario Joyería
https://es.wowhead.com/quest=41653/pedido-colgante-de-piedra-celestial
necesario Alquimia
https://es.wowhead.com/quest=41659/pedido-elixires-de-avalancha
necesario Herbolestería
https://es.wowhead.com/quest=41223/pedido-flor-de-raposa
necesario Ingeniería
https://es.wowhead.com/quest=41677/pedido-martillo-automático
necesario Encantamiento
https://es.wowhead.com/quest=41671/pedido-palabra-de-fuerza
necesario Mineria
https://es.wowhead.com/quest=41206/pedido-piedra-ley
 necesario Pesca
https://es.wowhead.com/quest=41240/pedido-salmón-de-monte-alto
necesario Sastrería
https://es.wowhead.com/quest=41647/pedido-toga-de-filoseda
necesario Desuello
https://es.wowhead.com/quest=41235/pedido-cuero-de-petrapiel

Misiones de mundo
https://es.wowhead.com/quest=41224/suministros-necesarios-flor-de-raposa
https://es.wowhead.com/quest=41207/suministros-necesarios-piedra-ley
https://es.wowhead.com/quest=41237/suministros-necesarios-cuero-de-petrapiel

**NPC Veridis Fallon**
https://es.wowhead.com/npc=107376/veridis-fallon

Estas son las Misiones de mundo de Profesiones que termina:
necesario Inscripcion
https://es.wowhead.com/quest=41663/pedido-de-runa-vantus-elerethe-renferal
necesario Herbolestería
https://es.wowhead.com/quest=41287/pedido-aethril
necesario Ingenieria
https://es.wowhead.com/quest=41675/pedido-armatesta-de-activación-por-parpadeo
necesario Peleteria
https://es.wowhead.com/quest=41639/pedido-bufas-de-vínculo-bélico
necesario Joyeria
https://es.wowhead.com/quest=41651/pedido-colgante-de-azsunita
necesario Sastreria
https://es.wowhead.com/quest=41645/pedido-cubrehombros-de-filoseda
necesario Desuello
https://es.wowhead.com/quest=41326/pedido-escamas-tormentosas
necesario Herreria
https://es.wowhead.com/quest=41633/pedido-grebas-de-piedra-ley
necesario Alquimia
https://es.wowhead.com/quest=41657/pedido-jarabes-de-magia-pura
necesario Encantamiento
https://es.wowhead.com/quest=41669/pedido-palabra-de-golpe-crítico
necesario Pesca
https://es.wowhead.com/quest=41267/pedido-pez-reina-maldito
necesario Mineria
https://es.wowhead.com/quest=41311/pedido-piedra-ley

Misiones de mundo
https://es.wowhead.com/quest=41288/suministros-necesarios-aethril
https://es.wowhead.com/quest=41327/suministros-necesarios-escamas-tormentosas
https://es.wowhead.com/quest=41315/suministros-necesarios-piedra-ley

**Comment by Noahkrr** [comment]
de esta lista algunas WQ no estan activas, un ejemplo: en Valsharah, el npc "NPC Sylvia Cornociervo"  (las WQ de peleteria y desuello no nunca aparecen en el mapa). verifiquen estas misiones e implementen las WQ que faltan.

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
