### ISSUE TITLE
[Tyce] - Druid Quest: A Hero's Weapon 

### ISSUE THREAD

**Issue by renifer15** [GuabinaCore/WoWKoi#3391]
**Links:**

from WoWHead or our Armory

**What is happening:**
After completing Druid order hall questline, you are not getting your 2nd line of appearances. You're getting a title, achiv but not appearances.

**What should happen:**
After completing your last quest in order hall which is Champion: Remulos, you should get a quest A Hero's Weapon which finish your class hall campaign and gives you second line of appearances and Forget for Battle achiv.

**Comment by NightwindOI** [comment]
Please edit your report or add more info in the comment section (as wowhead link of the questline, last quest of it, the appearance link and youtube video if possible)

**Comment by renifer15** [comment]
Last normal quest on server: https://www.wowhead.com/quest=42056/champion-remulos
Supposed to be last quest : https://www.wowhead.com/quest=43409/a-heros-weapon
Actual last quest on server for some reason: https://www.wowhead.com/quest=42432/the-emerald-nightmare-the-emerald-nightmare
Achiv link: https://www.wowhead.com/achievement=10994/a-glorious-campaign
Achiv 2 link: https://www.wowhead.com/achievement=10746/forged-for-battle
Appearance: https://imgur.com/a/Ri6FdqY
Video: https://www.youtube.com/watch?v=9uXBNTo4XUw

Quick fix: just add "A heros weapon" quest to the game (even tho i can see him on map but he is not there).
