### ISSUE TITLE
[Zone] Val'sharah [NPC] Gorebeak 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3392]
**Links:**

https://www.wowhead.com/npc=92117/gorebeak
https://www.wowhead.com/npc=92111/lorel-sagefeather

**What is happening:**
It's spawned by default

**What should happen:**
 You suppose to talk with Lorel Sagefeather to summon him .
 https://www.youtube.com/watch?v=LjxbWSHWWjc

**Comment by Cefiro-Caecias** [comment]
Fixed, blizzlike. Available in the next update.
