### ISSUE TITLE
[Quest] The Emerald Queen 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3393]
**Links:**

https://www.wowhead.com/quest=38377/the-emerald-queen
https://www.wowhead.com/npc=92742/ysera-summoned

**What is happening:**

The quest work just fine, the only issue is, once Ysera get summoned, they are two stacked at each other.

**What should happen:**

Suppose to be only one Ysera

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
