### ISSUE TITLE
[Object] Objects in Spanish

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3394]
**Links:**

https://www.wowhead.com/object=243952/twisted-root
https://www.wowhead.com/object=248416/shadowfen-heirlooms

**What is happening:**

They show up in Spanish

**What should happen:**
English

**Comment by NightwindOI** [comment]
Some more
https://imgur.com/a/C6h7Irk

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
