### ISSUE TITLE
[NPC] Temple Guard [MISC] 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3395]
**Links:**

https://www.wowhead.com/npc=94137/temple-guard
https://www.wowhead.com/npc=92789/darkfiend-dreadbringer
https://www.wowhead.com/npc=110896/ancient-annihilator

**What is happening:**
All just stay there and do nothing
https://imgur.com/a/mjEztyB

**What should happen:**
https://youtu.be/DwdYByX_VLY?t=14
https://youtu.be/bhk1LHuXetE?t=76

They suppose to fight each other. In general, the area needs some rework, but its purely cosmetic (as this one).

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
