### ISSUE TITLE
[Quest] Botanical Backlash

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3396]
**Links:**

https://www.wowhead.com/quest=42075/botanical-backlash
https://www.wowhead.com/npc=105933/apostle-of-lyrathos
https://www.wowhead.com/spell=184372/unfettered-growth

**What is happening:**
The spell that Apostle use is bugged. It summons too many plants or the plants are too powerful (not survive to find out)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
