### ISSUE TITLE
[Quest] Dark Side of the Moon 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3397]
**Links:**

https://www.wowhead.com/quest=41890/dark-side-of-the-moon

**What is happening:**
 
 The first part of the quest work, but when Tyrande turns back to the water, nothing happens.
 The ''Protect event'' never start.

**What should happen:**
https://www.youtube.com/watch?v=yLeiY3jv_rY

**Comment by Cefiro-Caecias** [comment]
Fixed.

**Comment by Kprtn** [comment]
I have the same problem now. 
 My name in game is Nuru
