### ISSUE TITLE
[Quest] The Fate of Val'Sharah 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3399]
**Links:**

https://www.wowhead.com/quest=38743/the-fate-of-valsharah

**What is happening:**

After you speak with Tyrande she is doing nothing and if you go to the temple by yourself there is no dragon to kill.

**What should happen:**
https://www.youtube.com/watch?v=YDlAikSDp2s

**Comment by Cefiro-Caecias** [comment]
This quest will be rebuilt blizzlike later.
