### ISSUE TITLE
Suramar - Withered Army Training

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3400]
**Links:**

https://www.wowhead.com/quest=43943/withered-army-training#comments

**What is happening:**

When you click on a withered army training dialogue option, it just completes a WQ and drains my Ancient mana but doesn't teleport me to the event area. I have completed army training once, after that (1 week later) it doesn't let me in again.

![WoWScrnShot_120521_140049](https://user-images.githubusercontent.com/63166930/144747721-679612cc-be2d-4bc8-a7d7-0a145e521833.jpg)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
This quest will be rebuilt blizzlike later.
