### ISSUE TITLE
Surama - Telemancy Beacon - Twilight Vineyards.

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3401]
**Links:**

https://www.wowhead.com/quest=44084/vengeance-for-margaux

**What is happening:**

After completing the quest above, Twilight Vineyards Telemancy Beacon should be present. Although on the mini map it says it's active, the teleport is not present.
![image](https://user-images.githubusercontent.com/63166930/144747993-b26f9588-eb39-4103-920e-02bd43678c8e.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
