### ISSUE TITLE
Lootbox

### ISSUE THREAD

**Issue by dilpertti** [GuabinaCore/WoWKoi#3402]
**Links:**

from WoWHead or our Armory

**What is happening:**
Opening a lootbox (for example the 80lvl mail reward which gives fireworks) but not looting the items but closing it, the lootbox disappears from inventory

**What should happen:**
The lootbox should stay in inventory as long as it has any items in it

**Comment by NightwindOI** [comment]
Please add the name of the loot box...or its works with any?

**Comment by dilpertti** [comment]
Item was "Magically Wrapped Gift", which player gets in mail when you ding 80.

**Comment by Cefiro-Caecias** [comment]
There is no bug in itself. It is part of the Core system. If you don't collect your reward, you lose it.
