### ISSUE TITLE
[Tyce] - Legendary items drop 

### ISSUE THREAD

**Issue by Skuniorek** [GuabinaCore/WoWKoi#3403]
https://www.wowhead.com/legion-legendary-items-guide

**I've been playing here for a long time and I have noticed that the drop of legendary items is not only very small, but only 3 items will fly. These are exactly Sepuz, Prydaz and Kill'jaden. Apart from these three legends, no one else fell out. So please fix the drop percentage for the rest of the legendary items to be the same as the other three.**

**Comment by NightwindOI** [comment]
Can u make a list with the ''other'' legendary's so dev's can check out the ID's please.

**Comment by burt245** [comment]
i can falisfie that. seen other legendarys. op probably percieves it this way because the legendaries hes naming are for all classes and speccs, unlike other legendaries.

**Comment by ShikoSCS** [comment]
Fixed
