### ISSUE TITLE
[Tyce] - Opening the test kitchen

### ISSUE THREAD

**Issue by quchii** [GuabinaCore/WoWKoi#3404]
![WoWScrnShot_120421_175058](https://user-images.githubusercontent.com/94390935/144752435-2cf81360-8994-4cf2-9d83-e7edebeb7652.jpg)

no food on table to collect

https://www.wowhead.com/quest=40991/opening-the-test-kitchen#

**Comment by Matti297** [comment]
there is one more table by the wall you can use that one

**Comment by Cefiro-Caecias** [comment]
Pending rebuilding the complete system.
