### ISSUE TITLE
Maw of Souls: Hammered By The Storm

### ISSUE THREAD

**Issue by gankyplanky** [GuabinaCore/WoWKoi#3405]
**Links:**
https://www.wowhead.com/quest=38532/maw-of-souls-hammered-by-the-storm#comments

**What is happening:**
Completed Maw of souls on heroic and the hammer for quest didnt drop 

**What should happen:**
The hammer for quest should be 100% drop from the last boss

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
