### ISSUE TITLE
Suramar NPC Shardmaiden

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3406]
**Links:**

**What is happening:**

[Shardmaiden](https://www.wowhead.com/npc=105554/shardmaiden) grants The nightfallen reputation upon killing.
![image](https://user-images.githubusercontent.com/63166930/144756840-dac39639-a464-4ccf-9760-4352958705e5.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
