### ISSUE TITLE
Missing quest, from Val'sharah storyline

### ISSUE THREAD

**Issue by unexpect3d** [GuabinaCore/WoWKoi#3407]
**Links:**

https://wowpedia.fandom.com/wiki/Regroup_at_the_Refuge

**What is happening:**

After completing Dark Side of the Moon (quest) Tyrande dint' give me follow-up (Regroup at the Refuge)

**What should happen:**
Get quest Regroup at the Refuge after Dark Side of the Moon (quest)

**Comment by vechiiro** [comment]
Yeah that one is bugged but you can bypass it...just do the one after it and i think and it should work itself out

**Comment by Cefiro-Caecias** [comment]
Fixed.
