### ISSUE TITLE
(WQ) Black Rook Rumble

### ISSUE THREAD

**Issue by gigaslurp** [GuabinaCore/WoWKoi#3408]
**Links:**
[https://www.wowhead.com/quest=42023/black-rook-rumble](https://www.wowhead.com/quest=42023/black-rook-rumble)

**What is happening:**
NPC Enemy (Mathias Zunn) for world quest isn't attackable (Invalid Target), making the world quest not completable.

![image](https://user-images.githubusercontent.com/73703079/144764260-d47f0e5f-a38d-4895-afb6-5a695421d110.png)

**What should happen:**
Should be able to attack Mathias Zunn, and any subsequent enemies that might spawn after killing Mathias for the world quest.

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=111138/alune-windmane 
This npc is buggy too, is immobile, and cannot be attacked.

**Comment by fanatikking** [comment]
https://www.wowhead.com/npc=111140/brock-the-crazed
Same goes for this one

**Comment by Cefiro-Caecias** [comment]
Fixed.
