### ISSUE TITLE
[Tyce] - Elevator in Thunder Totem

### ISSUE THREAD

**Issue by dilpertti** [GuabinaCore/WoWKoi#3414]
**Links:**

from WoWHead or our Armory

**What is happening:**
Southern elevator (maybe northern too) in Thunder Totem, Highmountain. Every now and then the elevator disappears, and I fall through it.

**What should happen:**
Shouldn't fall through.

**Comment by Cefiro-Caecias** [comment]
@ShikoSCS, defecto de la carga de mapas? Para Altair y el sistema multihilos?

**Comment by dilpertti** [comment]
English?

**Comment by ventarius5** [comment]
I can cofirm, it's not very often, but the platform does disappear sometimes.
