### ISSUE TITLE
[Tyce] - Polymorphed mobs attacking

### ISSUE THREAD

**Issue by dilpertti** [GuabinaCore/WoWKoi#3415]
**Links:**

from WoWHead or our Armory

**What is happening:**
Polymorphed Subjugated Murloc attacked me for 140-155k damage (without polymorph attacked for 80-100k)

**What should happen:**
Shouldn't attack me at all while polymorphed, nor should it increase their damage.

**Comment by Travven** [comment]
Spell id please

**Comment by dilpertti** [comment]
https://www.wowhead.com/spell=118/polymorph

**Comment by Travven** [comment]
Sorry i forgot ask the ID of that NPC too

**Comment by Cefiro-Caecias** [comment]
Fixed by Travven.
