### ISSUE TITLE
Quest - Quest Item - Sovereign Soul loot table

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3416]
**Links:**

https://www.wowhead.com/item=138482/sovereign-soul
https://www.wowhead.com/quest=42733/a-very-special-kind-of-fuel
**What is happening:**

Sovereign souls dropped from the trash mobs in Eye of Azshara, they drop only from bosses in dungeons. I can't confirm if it drops from other dungeons trash mobs cuz i haven't got time to check. I dropped 7 in a 5 boss dungeon.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
