### ISSUE TITLE
World Quest - Danger Ealdis - Val'sharah

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3417]
**Links:**
https://www.wowhead.com/quest=43346/danger-ealdis
from WoWHead or our Armory

**What is happening:**
WQ is active on the map, but when you get to the area where the WQ takes place, no targets appear ... and it's not active

**What should happen:**
El wq debería aparecer activo en el mapa, cuando lleguemos a la zona y nos dé el objetivo de matar al npc (https://www.wowhead.com/npc=110367/ealdis)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
