### ISSUE TITLE
a lot of people getting stuck in highmountain

### ISSUE THREAD

**Issue by burt245** [GuabinaCore/WoWKoi#3418]
**Links:**
n/a

**What is happening:**
people entering highmountain dont recieve any updates from the server anymore(no npcs or mobs visible, no usable actions) and become stuck, unstucking does work for some people, but not for everyone. even if the unstuck is sucessfully, people return to the flightmaster route after unstucking.

allways happens to me when the legion invasion quest pops up, i assume its tied to that.

**What should happen:**
we shouldnt get stuck (also unstucking should stop flightmaster flights)

**Comment by Cefiro-Caecias** [comment]
Fixed.
