### ISSUE TITLE
[Fishing] Drowned Mana 

### ISSUE THREAD

**Issue by doona12345** [GuabinaCore/WoWKoi#3419]
**Links:**

from WoWHead or our Armory](https://www.wowhead.com/quest=42911/drowned-mana)

**What is happening:** can't fish out drowned mana... ive fished for hours without hooking a single drowned mana.

**What should happen:**
the item/currency 'drowned mana' should be possible to be fished in  Margoss Retreat zone pool. And also the various other things related to it like reputation gain, Aquaos the Unleashed  etc.

**Comment by Cefiro-Caecias** [comment]
Fixed.
