### ISSUE TITLE
Felwood - Xavathras

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#342]
**Links:**
https://www.wowhead.com/npc=9454/xavathras#drops
from WoWHead or our Armory

**What is happening:**
He is saying "Face me, $r, and know the legion's wrath
![WoWScrnShot_032920_213421](https://user-images.githubusercontent.com/62258982/77857314-613cd100-7205-11ea-86b3-344d9881008e.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
