### ISSUE TITLE
[Arcane Thirst] suramar quest line

### ISSUE THREAD

**Issue by Redsand1** [GuabinaCore/WoWKoi#3421]
**Links:**

[from WoWHead or our Armory
](https://www.wowhead.com/quest=40009/arcane-thirst)
**What is happening:**
the qiest wants from me to kill keeper Selentia but she is immune from evry atack and spell unkillable

**What should happen**
the player need to kill her and continue with the quest line of suramar

**Comment by NightwindOI** [comment]
https://www.wowhead.com/npc=115028/kill-credit-ancient-switch

**Comment by NightwindOI** [comment]
Solved
