### ISSUE TITLE
Quest - Unsolid Ground (Deepholm) - Low Prio

### ISSUE THREAD

**Issue by spukay** [GuabinaCore/WoWKoi#3422]
**Links:**
https://www.wowhead.com/quest=26377/unsolid-ground
from WoWHead or our Armory

**What is happening:**

Cannot obtain the 6 Jade Crystal Clusters found around the area after attempting to interact with the item that has the quest item.
Loot window appears and then disappears after 1 second with no quest item in bag.

**What should happen:**
Should be able to obtain quest item, collect 6, use them to progress quest objective
![WoWScrnShot_120821_102942](https://user-images.githubusercontent.com/30602576/145255234-fa53c497-5589-47ce-afb1-bda309908e1c.jpg)
.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
