### ISSUE TITLE
Quest - Something that Burns (Deepholm) - Low Prio

### ISSUE THREAD

**Issue by spukay** [GuabinaCore/WoWKoi#3423]
**Links:**
https://www.wowhead.com/quest=27135/something-that-burns
from WoWHead or our Armory

**What is happening:**

Quest item "The Burning Heart" does not drop from summoned npc.

**What should happen:**
Should be able to loot quest item "The Burning  Heart" after killing npc.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
