### ISSUE TITLE
PROFESIÓN PESCA - Peces Raros

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3424]
**Links:**

from WoWHead or our Armory

**What is happening:**
**Azsuna**
necesario anzuelo: (https://es.wowhead.com/item=133738/pez-globo-miraspina)
https://es.wowhead.com/item=133726/ermitaño-de-narthalas
necesario anzuelo: (https://es.wowhead.com/item=133704/broche-de-pez-reina-oxidado)
https://es.wowhead.com/item=133727/pez-reina-fantasmal
necesario anzuelo: 
Academia de Nar'thalas. Primero pescaremos la uña del pie de skrog (https://es.wowhead.com/item=133701/uña-del-pie-de-skrog) que nos pondrá un buff. Cuando desaparezca aparecerá un múrloc(https://es.wowhead.com/npc=102338/cazaskrogs-ojosal) que nos soltará babosa múrloc aromática(https://es.wowhead.com/item=133702/babosa-múrloc-aromática). Al usarla podremos pescar el rare.
https://es.wowhead.com/item=133725/blénido-de-brillo-ley

**Val'sharah**
necesario anzuelo: (https://es.wowhead.com/item=133705/raspa-podrida)
https://es.wowhead.com/item=133730/branquimusgo-antiguo
necesario anzuelo: (https://es.wowhead.com/item=133708/hojacardo-ahogado)
https://es.wowhead.com/item=133729/solla-espinada
necesario anzuelo: (https://es.wowhead.com/item=133707/reptanoches-de-pesadilla)
https://es.wowhead.com/item=133728/aleterror

**Monte Alto**
necesario anzuelo: (https://es.wowhead.com/item=133712/gusano-de-escarcha)
https://es.wowhead.com/item=133732/carpa-riofrío
necesario anzuelo: (https://es.wowhead.com/item=133709/caracol-marino-hediondo) Al lootearlo nos pondrá un bufo que cuando desaparezca hará aparecer un Pescabrul Roepiedra(https://es.wowhead.com/npc=102347/pescabrul-roepiedra) que looteará el cebo de salmón(https://es.wowhead.com/item=133710/cebo-de-salmón) y al usarlo nos permitirá pescar el rare.
https://es.wowhead.com/item=133733/salmón-de-monte-alto-antiguo
necesario anzuelo: (https://es.wowhead.com/item=133711/huevo-de-múrloc-hinchado)
https://es.wowhead.com/item=133731/pez-globo-de-montaña

**Tormenheim**
necesario anzuelo: (https://es.wowhead.com/item=133716/escama-de-draco-empapada)
https://es.wowhead.com/item=133735/langosta-panzagrís
necesario anzuelo: (https://es.wowhead.com/item=133715/anillo-vrykul-antiguo)
https://es.wowhead.com/item=133734/oodelfjisk
necesario anzuelo: Pescaremos anzuelo de cuerno de alce(https://es.wowhead.com/item=133713/anzuelo-de-cuerno-de-alce) en bancos de rayatormenta, al usarlo nos permitirá pescar pezqueñín escamaplata(https://es.wowhead.com/item=133714/pezquenin-escamaplata), que usaremos para pescar el rare.
https://es.wowhead.com/item=133736/rayatormenta-tronadora

**Suramar( rios)**
necesario anzuelo: (https://es.wowhead.com/item=133717/cebo-encantado)
https://es.wowhead.com/item=133737/rana-comemagia
necesario anzuelo: (https://es.wowhead.com/item=133720/detritus-demoníacos)
https://es.wowhead.com/item=133739/koi-de-escamas-rúnicas-corrupto
necesario anzuelo: (https://es.wowhead.com/item=133719/múrloc-dormido)
https://es.wowhead.com/item=133738/pez-globo-miraspina

**Suramar (mar)**
necesario anzuelo: (https://es.wowhead.com/item=133723/tiburón-aturdido-y-enfadado)
https://es.wowhead.com/item=133741/calamar-del-fondo-del-mar
necesario anzuelo: (https://es.wowhead.com/item=133721/mensaje-en-una-botella-de-cerveza)
https://es.wowhead.com/item=133740/pez-hacha
necesario anzuelo: (https://es.wowhead.com/search?q=grasa+de+ballena+podrida)
https://es.wowhead.com/item=133742/barracuda-negra-antigua

MAS INFORMACION COMENTARIOS DE WOWHEAD EN INGLES (https://es.wowhead.com/achievement=10596/pezqueñines-no-gracias#english-comments)

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
