### ISSUE TITLE
Prospecting and gem chips

### ISSUE THREAD

**Issue by madbessoul** [GuabinaCore/WoWKoi#3425]
# Links:
 - [Jewelcrafting in Legion - Gem chip and Prospecting (youtube.com)](https://www.youtube.com/watch?v=35q3Xkw8b5A)
 - [Wowhead top comment on Gem Chip (dated from 7.0.3)](https://www.wowhead.com/item=129100/gem-chip#comments:id=2344309)
 - [6/23 Weekly Legion Developer Q&A: Professions with Senior Game Designer Paul Kubit](https://www.wowhead.com/news/6-23-weekly-legion-developer-q-a-professions-with-senior-game-designer-paul-253765#will-gem-chips-have-a-larger-use-currently-used-for-just-one-recipe-nightborne)

# What is happening:
When prospecting ore, one or more gem chips can be found and looted into the inventory and has no impact on the next gem that is prospected. Sometimes when prospecting nothing drops (marked by a non-lootable "Empty slot" item)
![image](https://user-images.githubusercontent.com/2671740/145291921-44003aa1-6553-4536-aba0-3f0e96b5d246.png)

# What should happen:

- Only one gem chip can be found when prospecting
- Gem chips turn into a [white chip](https://www.wowhead.com/item=129100/gem-chip) when looted into the inventory
- The color of the gem chip predicts the color of the next gem that will be prospected, regardless of the type of ore
- Prospecting always drops at least a gem chip.

## More in depth explanation : 

> ### Will Gem Chips have a larger use? Currently used for just one recipe ( Nightborne Delicacy Platter). Will they have a use within Jewelcrafting since they are obtained from prospecting ore?
>
 >   The color of your chips change, which gives you information that the next gem you prospect is that color gem. So if you want a 
>  specific gem, you could prospect cheap ore, and then when you see the right color pop up, switch to prospecting better ore to get > your gem.
>   Otherwise, they are vendor trash.

From [_6/23 Weekly Legion Developer Q&A: Professions with Senior Game Designer Paul Kubit_](https://www.wowhead.com/news/6-23-weekly-legion-developer-q-a-professions-with-senior-game-designer-paul-253765#will-gem-chips-have-a-larger-use-currently-used-for-just-one-recipe-nightborne)

> Gem chips are a new flavour item in Legion, yielded from prospecting, a skill usable by Jewelcrafters, and milling, used by Scribes. They are used as a reagent in cooking for one dish - Nightborne Delicacy Platter (only the non-coloured version - Gem Chip).
>
> When prospecting ore, a gem chip of a certain colour that appears in your Prospecting window will predict the next gem that you will obtain via prospecting, which can be quite helpful! As per the devs during the Legion Profession Q & A (Video | Text Summary), you can prospect lower quality ore until you get the gem chip you want (e.g. Gem Chip if you are gunning for Furystone) and then you can switch to higher quality ore to obtain the rarer gem of that colour.
>
> When milling, only the non-coloured version ( Gem Chip) will be produced.
>
> Note that the coloured version of each Gem Chip will only be seen in your prospecting window - the chips in your bags will be generic Gem Chip items.

From [_this Wowhead comment_](https://www.wowhead.com/item=129100/gem-chip#comments:id=2344309)

**Comment by Tonage** [comment]
Same bug. Hope to fix it soon.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
