### ISSUE TITLE
shaman class quests bugged

### ISSUE THREAD

**Issue by conyoshi** [GuabinaCore/WoWKoi#3427]
Hello, I have a problem with 2 shaman class quests, these must be delivered in the same area after taking a portal, In Deepholm, Therazane's Throne. These are called "The Great Stonemother (41775)" and "Ma'haat the Indomitable (42989)". The problem is the npcs are not there, both are bugged. Please help me with

**Comment by NightwindOI** [comment]
https://www.wowhead.com/quest=41775/the-great-stonemother
https://www.wowhead.com/quest=42989/mahaat-the-indomitable
For in-game help please send a message to any of the GMs or post your name in support chat.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.

**Comment by conyoshi** [comment]
Thanks 
 :)
