### ISSUE TITLE
A quest of the mining chain quests bugged : [Hellfire Citadel: Hellfire and Brimstone]

### ISSUE THREAD

**Issue by Gattel** [GuabinaCore/WoWKoi#3428]
**Links:**
Asmongold soloing Archimonde Mythic for the mount at level 110
https://www.youtube.com/watch?v=1FTeJtjhGVs

**What is happening:**
the corpse of Archimonde (Mythic) disappeared almost instantly before you can even loot the quest item, I couldn't even tell if it even drops

**What should happen:**
The corpse should stay there for a bit
![Screenshot_31](https://user-images.githubusercontent.com/76393149/145429776-eca70f56-4a69-4884-b717-fe20e0c2e061.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
