### ISSUE TITLE
Suramar - NPC Rares

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3429]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=110832/gorgroth
This rare should be lv110 and not lv100
![image](https://user-images.githubusercontent.com/81131460/145511609-e36b80a4-9e7b-4550-ac71-5e4e1f554db8.png)

https://www.wowhead.com/npc=113368/llorian
![image](https://user-images.githubusercontent.com/81131460/145512101-68a5aa5e-bd7b-4390-b41e-6d20149a99d6.png)

When you speak to Llorian, you can choose to give him 25  Ancient Mana which will trigger an assault of Withered in two waves. The first wave had two and the second wave had three Withered when I did it. After the assault he offers you his supplies (a clickable bag on the floor near him). Llorian's Supplies

https://www.wowhead.com/npc=105547/rauren
when entering combat with the npc, it does not attack, it is immobile, the npc is hostile, it must attack me

https://www.wowhead.com/npc=106351/artificer-lothaire
The npc is in the wrong place, it is happening in the river, and the npc(https://www.wowhead.com/npc=106349/damaged-spell-seeker-construct) that accompany it have no script, they are free and attack but cannot be attacked
how it should work:
the rare must be enclosed in a mana bubble, to free it we must kill the npcs that guard it, and once released we can kill the rare
https://www.youtube.com/watch?v=HJjjH8W53D0&t=65s

https://www.wowhead.com/npc=100864/corakar
the weird is functional. There is only one problem, there are 3 vrykul that kill the rare, and when I kill the rare, those vrykul attack me, I cannot kill them because they cannot be attacked.
these vrykul should be neutral and they should be locked in the cages, when the rare npc is low life, these vrykul should attack the rare
https://www.youtube.com/watch?v=Bc862KA586s

**Comment by Cefiro-Caecias** [comment]
Fixed all. Available in the next update.
