### ISSUE TITLE
WoTLK ICC Invincible's Reins farm

### ISSUE THREAD

**Issue by infidel99** [GuabinaCore/WoWKoi#3430]
**Links: https://youtu.be/Dudz7fa52Bc **

Youtube link is from youtube retail wow.... 
https://wowwiki-archive.fandom.com/wiki/Invincible

**What is happening:**

Zone: Northrend
Raid: ICC

Bug report:

As I walked through the Raid, I realized some things had been reworked, altered, skipped, and the like.  Bosses work solidly, but “valitrya” is totally in trouble.  The passage is not furnished, it is treated as if you need 25 people to do it, the portal for additional healing does not work!  The portal appears and disappears immediately, the two doors from which the monsters come do not rise, when the monsters pass they remain blocked and cannot be targeted, the Boss has 60 million HP, which is insane in a raid that should be under scaled.  Achivmenti are somewhat vague in description.  You should write 25 man normal - fashion, not fashion.  Plus it can happen that the loot falls from the heroic version.

I know Raid very well, I have solved 150 times with 15 characters, it on all private servers and I have 360586 people in Europe who have LK mounts.

**What should happen:**

**Comment by NightwindOI** [comment]
All that is ok, but please add more details to the issues.
Link with the wrong npc's, link with a video how they suppose to be (formation, spell, hp, and so on).
And again, it's ''old'' content so it's not a higher prior right now since we have a lot more ''Legion'' issue's to be solved before this one.
Thx for your report!

**Comment by Cefiro-Caecias** [comment]
This old raid will be rebuilt later. Patience ;)
