### ISSUE TITLE
Quest - "The Eldest" (WoD) garrison quest

### ISSUE THREAD

**Issue by j-9000** [GuabinaCore/WoWKoi#3433]
**Links:**
https://www.wowhead.com/quest=32795/the-eldest

**What is happening:**
Hatock is jumping on the mob "Grulloc" and both are un-targetable 

**What should happen:**
NPCs should appear and force Hatock to step down then you kill both mobs

**Comment by j-9000** [comment]
this quest is needed to get the lvl 2 hord garrison

**Comment by Cefiro-Caecias** [comment]
This old content will be rebuilt later. Patience ;)
