### ISSUE TITLE
[MISC] Spanish Objects

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3435]
**Links:**

from WoWHead or our Armory

**What is happening:**

https://imgur.com/a/Jlxudr5
https://imgur.com/a/zIVBQ6y

**What should happen:**

All of them must be in english

**Comment by Cefiro-Caecias** [comment]
Fixed all. Available in the next update. Do not forget to periodically delete the Cache folder of your WoW, or you will not see the new changes.
