### ISSUE TITLE
[Zone] Azsuna [NPC] [MISC] Scale issues and missing npc

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3436]
**Links:**

https://www.wowhead.com/npc=104258/queen-queenfish
The Inferno one is ok...my bad
https://www.wowhead.com/object=240354/genuinely-unguarded-treasure

**What is happening:**
https://imgur.com/a/iA4N2yk

**What should happen:**
Fish must be scaled
Inferno is fine...my bad
Treasure is missing (nothing to click on to summ the guards)
Syphonus is fine too 
Fjordun is fine too

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
