### ISSUE TITLE
[NPC] Flamescale 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3437]
**Links:**

https://www.wowhead.com/npc=97793/flamescale
https://www.wowhead.com/quest=39963/abandoned-fishing-pole

**What is happening:**

The Fishing pole that you need to summon the fish is missing.

**What should happen:**
https://www.youtube.com/watch?v=MG1DQ02dNMM

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.

**Comment by NightwindOI** [comment]
The pole is there, but once you click on it, there is no fish.
