### ISSUE TITLE
WQ - Return to the crag - Monte Alto

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3438]
**Links:**
https://www.wowhead.com/quest=41789/return-to-the-crag
from WoWHead or our Armory

**What is happening:**
the wq does not work correctly, when you kill harpies it counts them as fauna, and killing marauders or moose does not count them, in total killing harpies counts as two credits ..
Still the wq can be completed but there are errors in the credits.
![image](https://user-images.githubusercontent.com/81131460/145722926-8c459e59-094e-4515-b4f5-9c36d2f737bb.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the enxt update.
