### ISSUE TITLE
Ashenvale Bowman Level Scaling.

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#344]
**Links:**
https://github.com/GuabinaCore/WoWKoi/issues/328
from WoWHead or our Armory

Even after deleting my cache, going back to Splintertree Post in Ashenvale i see some Ashenvale Bowman not level scaling. The thing is that these mobs are different models from the others that scale AND from the pictures on the wowhead links. You can go there and check it by yourself.

**Comment by Cefiro-Caecias** [comment]
I am seeing them in front of me, and they are scaled. The ones that I see that are not scaled, are the "Ashenvale Assailant" :O

**Comment by Serithul** [comment]
This is what i see right now. My mouse is on another bowman who is scaling while i am targetting the one who isn't. There are a couple more like the one who isn't scaling. Keep in mind that i have deleted my cache folder when i saw your comment on the other report.

![WoWScrnShot_033020_000106](https://user-images.githubusercontent.com/62258982/77860775-acf97580-7219-11ea-82f9-7ab130594c4f.jpg)

**Comment by Serithul** [comment]
Also the Ashenvale Bowman corpses in front of the one in the picture are not level scaling also, might there be a connection of the two ?

**Comment by Cefiro-Caecias** [comment]
Doesn't make sense :O

It only remains for me to think that my fixes have not been applied well. In any case, in two days I already prepare the new release of DBs, where all my fixes will already be included.

**Comment by Serithul** [comment]
Alright, I will keep that in mind and check back again after that

**Comment by Cefiro-Caecias** [comment]
Kiss.
