### ISSUE TITLE
[WQ] World Quest - Darkheart Thicket: Preserving the Preservers

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3440]
**Links:**

https://www.wowhead.com/quest=42744/darkheart-thicket-preserving-the-preservers#comments

**What is happening:**

[Injured Preserver Druid](https://www.wowhead.com/npc=108460/injured-preserver-druid) may be clicked multiple times for additional credits.

**What should happen:**

No extra credits for you.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
