### ISSUE TITLE
Kirin Tor emissary grants 

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3442]
**Links:**

https://www.wowhead.com/quest=43179/the-kirin-tor-of-dalaran

**What is happening:**

Kirin tor emissary has Greater Army of the Light Insignia, Greater Legionfall Insignia and Greater Argussian Reach Insignia available as a reward.

![image](https://user-images.githubusercontent.com/63166930/145839109-c83393fc-1e84-449b-9825-b3bc7694e679.png)

**What should happen:**

no extra rep before progression for you

**Comment by Cefiro-Caecias** [comment]
Yes, at the moment it is.
