### ISSUE TITLE
regroup at the refuge

### ISSUE THREAD

**Issue by MohammadAbdelshafy** [GuabinaCore/WoWKoi#3445]
**Links:**

from WoWHead or our Armory

**What is happening:**
i cant take the quest "regroup at the refuge" from NPC Tyrande Whisperwind  at Valsharah

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
That quest is unlocked by completing secondary quests 38671 and 41707. But I'll still fix it so it's no longer a requirement ;)
