### ISSUE TITLE
Misión: Proles de la garfa

### ISSUE THREAD

**Issue by nazgrim94** [GuabinaCore/WoWKoi#3446]
**What is happening:**

El Add Aviana te da la posibilidad de volar y poder coger unos globos que están repartidos por el área respectiva para completar la mision en el cielo pero estos son imposibles de recolectar porque no aparecen

**What should happen:**
Los globos deberian poder rcogerse mientras se esta planeando en el aire

**Comment by Noahkrr** [comment]
tengo el mismo problema, imposible completar la mision, el logro y el juguete :c

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update. Será requisito tener o haber competado la quest para que se destrabe la opción de diálogo que habilita el vuelo para la quest.
