### ISSUE TITLE
Stormheim - NPC

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3449]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=92763/the-nameless-king
the npc does not appear, I already clicked the sign and I do not summon the rare

https://www.wowhead.com/npc=91893/erling-the-lightningborn
this npc is missing
https://www.wowhead.com/npc=91895/asger-jarlborn
this npc is missing
https://www.wowhead.com/npc=91894/strider-cuyler
this npc is missing
https://www.wowhead.com/npc=91892/thane-irglov-the-merciless
this rare npc is missing
a video where these npc are found, which guard the rare
https://www.youtube.com/watch?v=CNID8aR9knQ

You must find these rare and kill them to obtain the achievement "Adventurer of Stormheim".

BONUS: 
https://www.wowhead.com/spell=193684/mist-of-the-watchers
The spell does not work, the lookouts see me and attack me

**Comment by Cefiro-Caecias** [comment]
1) https://www.wowhead.com/npc=92763/the-nameless-king: I just tried it by playing the Offering Shrine, and it worked perfect.

2) https://www.wowhead.com/npc=91893/erling-the-lightningborn: Fixed. It will become visible when you have either quest 38374 or 41451.

3) https://www.wowhead.com/npc=91895/asger-jarlborn: Fixed. It will become visible when you have either quest 38374 or 41451.

4) https://www.wowhead.com/npc=91894/strider-cuyler: Fixed. It will become visible when you have either quest 38374 or 41451.

5) https://www.wowhead.com/npc=91892/thane-irglov-the-merciless: Fixed. It will become visible when you have either quest 38374 or 41451.

Available in the next update.
