### ISSUE TITLE
[Arthas] - The Final Voyage of the Brashtide

### ISSUE THREAD

**Issue by Infuried** [GuabinaCore/WoWKoi#345]
**Links:** Quest

from WoWHead or our Armory

**What is happening:**
Scripted perfectly except the Return button on the gryphon is not returning me to booty bay.

**What should happen:**
Return button on gryphon should return me to booty bay location

**Comment by Serithul** [comment]
https://www.wowhead.com/quest=26697/the-final-voyage-of-the-brashtide

**Comment by LKArthas** [comment]
Fixed
