### ISSUE TITLE
NPC - Val'sharah

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3451]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=92423/theryssia
this npc cannot be summoned, they must be invoked by clicking on the grave plate
https://www.wowhead.com/npc=93758/antydas-nightcaller
opening the chest should give me credit for achieving the npc antydas nightcaller
https://www.wowhead.com/npc=92965/darkshade
duplicate npc

**Comment by Cefiro-Caecias** [comment]
1) https://www.wowhead.com/npc=92423/theryssia: I just tried it, and it worked perfect for me, having the corresponding quests.

2) https://www.wowhead.com/npc=93758/antydas-nightcaller: Works fine.

3) https://www.wowhead.com/npc=92965/darkshade: Fixed. Available in the next update.

**Comment by CptKartoffel** [comment]
> 2. https://www.wowhead.com/npc=93758/antydas-nightcaller: Works fine.

Chest looted, Nothing happens. :V

**Comment by CptKartoffel** [comment]
>     2. https://www.wowhead.com/npc=93758/antydas-nightcaller: Works fine.

Chest looted. Nothing happens. :V

**Comment by Cefiro-Caecias** [comment]
2.- https://www.wowhead.com/npc=93758/antydas-nightcaller: re-fixed. Available in the next update.
