### ISSUE TITLE
[Tyce] - Stonehide/Stormscale Scale!

### ISSUE THREAD

**Issue by Gucciest** [GuabinaCore/WoWKoi#3453]
**Links:** https://www.wowhead.com/item=124113/stonehide-leather - Stonehide
https://www.wowhead.com/item=124115/stormscale - Stormscale

from WoWHead or our Armory

**What is happening:** Their drop chance is not scaled at all , can be checked easliy via-game logging and using a simple test of skinning with any rank (above ONE)

**What should happen:** According to Wowhead , Stonehide/Stormscale LARGER drop chance should be WAY higher (like between 3-8 from an stonehide/stormscale skinnable add) ONLY WHEN you have completed their simple quests and unlocked at least rank 1.

Please fix it , its just impossible to farm efficiently!

**Comment by Noahkrr** [comment]
Good point, it also clarifies that from rank 2 (be it skinning, herbalism, and mining) you can get blood from sargeras, currently at rank 1, you can get blood from sargeras, which is incorrect.

**Comment by Cefiro-Caecias** [comment]
I would need a guide or more info on this. For example, which items start to be dropped according to which skill rank, or which items increase their drop chance according to skill rank (they are two different things, as you will notice). Based on that, you could make some global adjustments. I confess that I do not know all the mechanics involved to start repairing right now (for example, I was unaware of what you said about the Bloods of Sargeras). Any help you provide will be welcome.
