### ISSUE TITLE
[Tyce] - I don't get reputation

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3454]
**Links:**

from WoWHead or our Armory

**What is happening:**
Reputation bar won't go up, when I do WQ, I should still get despite having Exalted reputation
![Captura](https://user-images.githubusercontent.com/81131460/146306119-33f2b052-6443-4f50-a4fb-c484855b9f07.PNG)

**Comment by Kprtn** [comment]
Sigue igual, una vez que se llega a exaltado la barra no sube

![WoWScrnShot_012522_185202](https://user-images.githubusercontent.com/96433337/151205568-4ddbd5bc-4db8-4776-8859-27285aa872ef.jpg)

**Comment by Noahkrr** [comment]
ya esta funcional.
