### ISSUE TITLE
Xandris the Dishonored

### ISSUE THREAD

**Issue by MolnarAlmos** [GuabinaCore/WoWKoi#3455]
**Links:**
**What is happening:** Xandris the Dishonored's Night Bolt is hit me 300k+ dmg, and 3 shots me
![WoWScrnShot_121621_083005](https://user-images.githubusercontent.com/95250425/146327720-882ff972-333a-48ef-bfcc-c40000b00e8f.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
