### ISSUE TITLE
Val'sharah Loremaster 

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3456]
**Links:**
https://www.wowhead.com/quest=43576/regroup-at-the-refuge
from WoWHead or our Armory

**What is happening:**
"Regroup at the Refuge" quest not can be appliabe because the NPC cannot been seened.

**What should happen:**
The NPC (Tyrande Whisperwind) despawning after completed the "Dark Side of the Moon" quest, and cannot be applied the next quest in the storyline.

**Comment by Cefiro-Caecias** [comment]
That quest is unlocked by completing secondary quests 38671 and 41707. But I'll still fix it so it's no longer a requirement ;)
