### ISSUE TITLE
[Quest] Amateur Hour

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3457]
**Links:**

https://www.wowhead.com/quest=40170/amateur-hour

**What is happening:**
Once u click on the dialog they become ''Invalid target''

**What should happen:**
Must be able to attack them
https://www.youtube.com/watch?v=yRU185sGB9c

**Comment by Cefiro-Caecias** [comment]
Fixed, blizzlike. Available in the next update.
