### ISSUE TITLE
[Arthas] - Quest The end of the Deserters

### ISSUE THREAD

**Issue by Infuried** [GuabinaCore/WoWKoi#346]
**Links:** QUEST NAME: The end of the Deserters

from WoWHead or our Armory

**What is happening:**
Incompleted even after defeating Gavis Greyshield. Suppose to escort him back to theramore but disappeared and didnt get Quest completion.

**What should happen:**

**Comment by Serithul** [comment]
https://www.wowhead.com/quest=11134/the-end-of-the-deserters

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
