### ISSUE TITLE
Missing NPCS in Legion Dalaran!

### ISSUE THREAD

**Issue by Gucciest** [GuabinaCore/WoWKoi#3460]
**Links:** Following links are for each missing NPC I've noticed:
Illnea Bloodthorn - https://www.wowhead.com/npc=115264/illnea-bloodthorn
Apothecary Lee - https://www.wowhead.com/npc=119486/apothecary-lee
Also would like to add that ALL the npcs that suppose to be located at the pvp quarter for the Horde / Alliance are missing!

from WoWHead or our Armory

**What is happening:** Npcs doesn't not exist in-game

![unknown](https://user-images.githubusercontent.com/95317162/146472254-13790064-823c-4017-b208-2de33083e55b.png)

**What should happen:** Suppose to be existed in-game! (ALSO MANY CLASSES CANNOT QUEUE FOR SKIRMMISH AT ALL TO BE ABLE TO COMPLETE THE WEEKLY WORLD QUEST SUCH AS ELEMENTAL SHAMANS)!

**Comment by Cefiro-Caecias** [comment]
1) Illnea Bloodthorn will not be available until we release the content of Patch 7.1.

2) Apothecary Lee and others: Fixed. Available in the next update.
