### ISSUE TITLE
WQ - Wanted: Lieutenant Strathmar

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3461]
**Links:**![image](https://user-images.githubusercontent.com/81131460/146480398-13ae5626-0f90-4609-bcad-80d709793179.png)
from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=44028/wanted-lieutenant-strathmar
As you can see in the image, when completing the WQ, I receive a reputation with the Court of Farondis and Wardens, I should receive a reputation with Nightfall and Wardens

![image](https://user-images.githubusercontent.com/81131460/146480398-13ae5626-0f90-4609-bcad-80d709793179.png)
**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
