### ISSUE TITLE
[Tyce] - Talentos de Cazador Punteria no funcionan 

### ISSUE THREAD

**Issue by galantehunter** [GuabinaCore/WoWKoi#3462]
**Links:** 
### **[Lobo solitario]**
https://es.wowhead.com/spell=155228/lobo-solitario#changelog
Lobo solitario Lobo solitario: Aumenta tu daño un 18% pero ya no puedes usar Llamar a mascota.
este talento te aplica un buff visible y permanente con el mismo icono que aparece en el talento el cual aumenta el daño en %18
lo que impide el uso de mascotas.

### **[Puntería certera]**
https://es.wowhead.com/spell=199527/punter%C3%ADa-fina
Puntería fina Puntería fina: Cada Disparo Arcano o Disparo de puntería consecutivo al mismo objetivo aumenta un 2% el daño que le infligen esos disparos. Se acumula hasta 10 veces y está limitado a 1 objetivo.

from WoWHead or our Armory

**What is happening:**
en el primer talento que reporto no aplica el buff solo no te permite utilizar mascotas. no te aumenta el 18% de daño
y en el segundo si bien se muestra el debuff en los pnj esto no aumenta el daño de disparo arcano o disparo de punteria.

**What should happen:**
ojala pudieron solucionar este tema desde ya muy agradecido.-

**Comment by Travven** [comment]
Ambos talentos estan funcionando bien. Para probar el lobo solitario use el talento de la flecha negra. El otro talento aunenta correctamente el daño. Recuerde q las armas tienen un rango de año, pero en el ultimo stack del francotirador paciente, aumenta un 20% el daño, lo q es muy notable

**Comment by Travven** [comment]
Fixes

**Comment by galantehunter** [comment]
la verdad como prueban los talentos, el lobo solitario no aumenta el daño se mantiene igual :( y con respecto al otro talento el daño no aumenta.
