### ISSUE TITLE
NPC - Kazrok - Azsuna

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3463]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=38352/kazrok
when clicking on the dialog nothing happens, the rare is still trapped and another problem is that the dogs(https://www.wowhead.com/npc=91585/fel-stalker) should be dead
video: https://www.youtube.com/watch?v=s9QMTSQPF14
![image](https://user-images.githubusercontent.com/81131460/146491746-09cae102-761f-412b-826b-ceb40e1d3f15.png)

bonus:
https://www.wowhead.com/npc=111383/lytheron-gloomscale
This npc when attacking it does not attack me, it ignores me

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
