### ISSUE TITLE
NPC - Highmountain

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3465]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=40423/unethical-adventurers
these are the rares that are invoked
https://www.wowhead.com/npc=100302/puck
https://www.wowhead.com/npc=109498/xaander
https://www.wowhead.com/npc=100303/zenobia
https://www.wowhead.com/npc=109500/jak
https://www.wowhead.com/npc=109501/darkful
Clicking on the treasure invokes the rares, these rares do not scale their lv, currently when they are summoned they are lv 98.
![fsfsffg](https://user-images.githubusercontent.com/81131460/146578220-a4a0a00d-6a02-4146-b5e5-089ee0b03925.PNG)

https://www.wowhead.com/quest=40414/devouring-darkness
Devouring Darkness is inside the cave, there is an area with 5 candles(https://www.wowhead.com/npc=97543/kobold-candle), turning them off will spawn rare. Currently the candles are out and the rare cannot be summoned.
video: https://www.youtube.com/watch?v=kQCKDspRt8Y

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
