### ISSUE TITLE
[Tyce] - Pet's Action Bar!

### ISSUE THREAD

**Issue by Gucciest** [GuabinaCore/WoWKoi#3466]
**Links:** Not needed because that report is about controlable pets in-game such Warlock/Hunter's ones!

from WoWHead or our Armory

**What is happening:** Their Action Bar/Control Bar (Management Bar) is completely gone , and sometimes the pet dissappear out of nowhere.
Prove from in-game photo : 
![image](https://user-images.githubusercontent.com/95317162/146599366-aa6441a3-0042-4d0c-b23d-2b1080247010.png)

**What should happen:** Should not happen at all.

**Comment by NightwindOI** [comment]
Please let me know if that's without any addons so we can eliminate that side of the report.
