### ISSUE TITLE
[NPC] Elindya Featherlight

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3467]
**Links:**

https://www.wowhead.com/npc=92334/elindya-featherlight
https://www.wowhead.com/npc=93654/skulvrax

**What is happening:**
Skulvrax is spawned by default. If u click to revive/heal Elindya, nothing happens.

**What should happen:**
A cute little event
https://www.youtube.com/watch?v=XvJccSqrZ7E

**Comment by Cefiro-Caecias** [comment]
Fixed, blizzlike. Available in the next update.

**Comment by CptKartoffel** [comment]
> Fixed, blizzlike. Available in the next update.

Still broken or broken again. :V

**Comment by Cefiro-Caecias** [comment]
Re-fixed. Available in the next update.
