### ISSUE TITLE
[Object] Unstable Barrel

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3469]
**Links:**
https://www.wowhead.com/npc=100029/unstable-barrel
https://www.wowhead.com/npc=100023/unstable-barrel

**What is happening:**
Nothing

**What should happen:**
It's used as ''fast travel'' between the two spots. Once you click the one of the tops...it starts to roll down the hill until reach the second point down there and brake.
https://i.imgur.com/4HO99oz.png

**Comment by Cefiro-Caecias** [comment]
I cannot reproduce the original sequence due to lack of data, so for the moment it will remain as an improvised teleport. Available in the next update.
