### ISSUE TITLE
Suramar: Search and Rescue!

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3470]
**Links:** https://www.wowhead.com/quest=41140/search-and-rescue

from WoWHead or our Armory

**What is happening:**
The Key is on the wall, but cannot be looted.
The Key name: Felsoul Cage Key

**What should happen:**
The Key can be lootable.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
