### ISSUE TITLE
[Quest] Cave of the blood trail

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3472]
**Links:**

https://www.wowhead.com/quest=39455/cave-of-the-blood-trial
https://www.wowhead.com/npc=95256/oakin-ironbull

**What is happening:**
Oakin Ironbull is wall true the cave/rock's around
 Bloodtotem Warmonger that spawns is level 98, so it does not scale with the player level 

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
