### ISSUE TITLE
[Quest] Wax On, Wax Off [MISC] 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3474]
**Links:**

https://www.wowhead.com/quest=39769/the-gates-of-wax
https://www.wowhead.com/item=128753/skull-of-bossing-around
https://www.wowhead.com/spell=201095/skull-of-bossing-around
https://www.wowhead.com/spell=191824/skull-of-bossing-around
https://www.wowhead.com/npc=101686/bluewax-ratcatcher
https://www.wowhead.com/npc=96986/bluewax-cavewhisker
https://wowpedia.fandom.com/wiki/Ollie_(rat)

**What is happening:**

The Gates of wax doesn't give you the buff at quest accepting.

**What should happen:**
Once u accept the quest, a ''buff/aura'' appears and make you  ''king'' to the kobolds , so they are friendly to you (rat pets too)
Can be seen here
https://www.youtube.com/watch?v=mu4sDPQCZSk
https://www.youtube.com/watch?v=kQCKDspRt8Y

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
