### ISSUE TITLE
[Tyce] - Mision Broken for my pleyer

### ISSUE THREAD

**Issue by danylvr37** [GuabinaCore/WoWKoi#3477]
**Links:**
https://es.wowhead.com/acquiring-the-kingslayers-assassination-rogue-artifact
https://es.wowhead.com/spell=192759/perdici%C3%B3n-de-reyes

from WoWHead or our Armory

**What is happening:**
During the mission to obtain the rogue's artifact weapons by assessination, the wow client unexpectedly stopped responding. This caused that I had to forcibly close the application. Having taken the kingslayer but without finishing the mission, I had to deliver the mission to the rogues' room as if it had been completed. By handing over this mission they were supposed to give me the rogues' mission board to continue the quest chain, but that didn't happen. I was left without any mission and waiting for you to fix this, or at least reestablish this quest chain for my character. My email is danylvr37@gmail.com and it has a single player named Nearest.

**What should happen:**
It should have gone on with the quest chain.

**Comment by danylvr37** [comment]
Start another player and complete the mission successfully. Same result. When the Mission is delivered to Garona on the table, a floating button is supposed to appear that tells me that he will drink beer with the rest of the assassins and this activates another event that continues with the mission chain. This button never appeared. When you go to fix this quest if you can give me back an upgrade to lvl 100 that I had to spend to test this, I will be grateful.

**Comment by Cefiro-Caecias** [comment]
Contact me on Discord when you can, see what I can do for you.
