### ISSUE TITLE
WQ - Life finds a way - Suramar

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3478]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=43583/life-finds-a-way
Active WQ, but you cannot find the Devilsaurus (https://www.wowhead.com/npc=111062/suesh), which you must mount and drop to escape the animal collection, and then start slaughter ..
video: https://www.youtube.com/watch?v=irS6hAfRHJ4

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
