### ISSUE TITLE
World Quest Emyssary on Broken Isles

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3479]
**Links:** 
World Quest's of Futher Campaign:
- Argussian Reach: https://www.wowhead.com/quest=48642/argussian-reach
- Armies of Legionfall: https://www.wowhead.com/quest=48641/armies-of-legionfall

**What is happening:**
The Server Patch is 7.3.5 but the Content of the Server now have 7.0.3. 
The Following Emissary WQ cannot be completed by Further Campaign.

**What should happen:**
Why we get World Quest Campain from futher Content that we cant completed?

**Comment by Cefiro-Caecias** [comment]
Due to the nature of the system (Core), I cannot block or disable those quests. We will have to live with them until we release the content of their respective Patches.
