### ISSUE TITLE
[Arthas] - Release spirit in Scarlet Monastery

### ISSUE THREAD

**Issue by Trevis77** [GuabinaCore/WoWKoi#348]
**What is happening:**
Release spirit in the Scarlet Monastery after dying teleports at the Sentinel Hill in Westfall.

**What should happen:**
You should respawn to the nearest graveyard of Scarlet Monastery.

**Comment by carlosyuniro** [comment]
x2

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
