### ISSUE TITLE
[Tyce] - Spell bug Mage: Ring of Frost

### ISSUE THREAD

**Issue by Nicholas941205** [GuabinaCore/WoWKoi#3481]
I think there is a little bug with this spell. When i use it in an instance, or outside, the spell stunns the enemy and interrupt them it's fine but after they get stunned it removes ALL of friendly dots from the target, or targets (sh priest, shaman, lock dots)

**Comment by Travven** [comment]
There is no problem with that.

**Comment by Travven** [comment]
Close this report

**Comment by Nicholas941205** [comment]
we tested it a lot of time, and it always happens...

**Comment by Travven** [comment]
I mean, that mechanic ia that way, removes the DoTs.

**Comment by Cefiro-Caecias** [comment]
Fixed by Travven.
