### ISSUE TITLE
Epic Elite World Quest - NPC  

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3484]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=44287/deadly-withered-jim
npc(https://www.wowhead.com/npc=102075/withered-jim) not found, active WQ impossible to complete.

https://www.wowhead.com/quest=43448/the-frozen-king
npc(https://www.wowhead.com/npc=110378/drugon-the-frostblood) not found, active WQ impossible to complete.

https://www.wowhead.com/quest=42779/the-sleeping-corruption
npc(https://www.wowhead.com/npc=108678/sharthos) not found, active WQ impossible to complete

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
