### ISSUE TITLE
Dungeon - Neltharion Lair - Naraxas

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3486]
**Links:**

[from WoWHead or our Armory](https://www.wowhead.com/npc=91005/naraxas)

**What is happening:**

If you jump into Naraxas pit, you die cuz of fall damage.

Loot container in the pit i very often empty.
![image](https://user-images.githubusercontent.com/63166930/147357371-affe54a6-acc3-4676-a9eb-e5f162340088.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
