### ISSUE TITLE
WQ - Life finds a way - Suramar

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3487]
**Links:**
www.wowhead.com/quest=43583/life-finds-a-way
from WoWHead or our Armory

**What is happening:**
the wq works fine almost everything, but there is a credit that is not completed, this is (Escape the Menagerie),that despite killing all the Nightfallen, the mission is impossible to complete.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
