### ISSUE TITLE
[Quest] Justice Rains from Above [MISC] Leftover objects

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3489]
**Links:**

https://www.wowhead.com/quest=40594/justice-rains-from-above

**What is happening:**

The quest work great, but once u complete it and the phase change, there are some objects leftover in the air
https://imgur.com/a/h4vrUAe

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
