### ISSUE TITLE
[Quest] Signal Boost 

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3491]
**Links:**

https://www.wowhead.com/quest=38060/signal-boost

**What is happening:**
Quest works fine, the issue is, if u are potato like me and spam on the object...it starts the event over and over...so I end up with two dragons. 
https://imgur.com/a/QQnQCSL

**What should happen:**
Some cooldown to trigger the event

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
