### ISSUE TITLE
[Object] Glimmering Treasure Chest [Zone] Stormheim

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3492]
**Links:**

https://www.wowhead.com/object=241717/glimmering-treasure-chest

**What is happening:**
1)Chest is empty
2) Nothing spawn when you open it

**What should happen:**
Guars must start spawning one by one once you open the chest
https://youtu.be/rmvQC4hP0wA?t=58

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
