### ISSUE TITLE
[Tyce] - Show new character models option does not work

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3493]
**Links:**

from WoWHead or our Armory

**What is happening:**
Removing the tick and restarting the game doesnt show me the old character models
![image](https://user-images.githubusercontent.com/84509345/147390517-e146a1ca-a8e3-40cb-8649-6e1e9cf76d38.png)

**What should happen:**
Change them to the old models

**Comment by NightwindOI** [comment]
Don't think if that can ever be ''fixed'', but gonna let it open for devs to check.
