### ISSUE TITLE
[Quest]  Put It All on Red

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3494]
**Links:**

https://www.wowhead.com/quest=42483/put-it-all-on-red
https://www.wowhead.com/item=138135/raxs-magnifying-glass

**What is happening:**
Quest works fine, but you don't get Raxs Magnifying glass as a quest reward.

**What should happen:**
You suppose to take the glass and use it on preview's items (that needs to be tested too if turn them into junk).
https://www.wowhead.com/item=138135/raxs-magnifying-glass#comments:id=2379635

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. Send me the name of your character, so I will send you the item by mail.
