### ISSUE TITLE
Daily quest bugged

### ISSUE THREAD

**Issue by conyoshi** [GuabinaCore/WoWKoi#3495]
Hi I have a problem with a dailys quest from Draenor, Tanaan Jungle in Vol'mar. There is a map, when you click it gives you 2 daily missions to choose, but it disappears and not giving you missions. I would like you can fix this to continue with these quest. Thank you :).

**Comment by Cefiro-Caecias** [comment]
That expansion will be repaired much later. Patience :p

**Comment by conyoshi** [comment]
okay thanks :)
