### ISSUE TITLE
[Tyce] - Class Hall Champion cannot be unassigned

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3497]
[**Links:**]
https://i.imgur.com/HjCBIbq.png

**What is happening:**
The Champion not followin me on the Broken Isle's and cannot be Unassigned.

**What should happen:**

**Comment by Kprtn** [comment]
tengo el mismo problema

![WoWScrnShot_122621_040441](https://user-images.githubusercontent.com/96433337/147497043-0e241b40-6120-4707-8f61-3919df7e8c82.jpg)
