### ISSUE TITLE
Felwort problem

### ISSUE THREAD

**Issue by Orika96** [GuabinaCore/WoWKoi#3498]
**Links:**

from WoWHead or our Armory

**What is happening:**

hi, on broken shore i can’t find Felwort with herbalism, I have the quest, and rank2, but I can’t find Felwort, please check it, cause I wanna get some of these herb.

thanks, char name: orika

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Try looking at another Legion map; Broken Shore is very particular, and almost everything in that area should be disabled until the next patch ;)
