### ISSUE TITLE
[Saitama] - Spell Trueshot 

### ISSUE THREAD

**Issue by Filqkus** [GuabinaCore/WoWKoi#35]
Hunter's spell Trueshot is supposed to make all of your arcane and multishots during the duration mark all targets. This does not occur, what happens is your buttons glow, but the effect is not there!

**Comment by login6710** [comment]
Fixed
https://github.com/GuabinaCore/TYCE-Group/commit/19f046a4a49f91ec367c6fcb7b03a4323efa6a19

https://github.com/GuabinaCore/TYCE-Group/commit/bcb90d29445a44ddc6ffcf548d20eeac92b2e360
