### ISSUE TITLE
Scarlet Purifier flamestrike damage

### ISSUE THREAD

**Issue by Trevis77** [GuabinaCore/WoWKoi#350]
**Links:**
https://www.wowhead.com/npc=58569/scarlet-purifier
https://www.wowhead.com/spell=110963/flamestrike

**What is happening:**
The damage of Scarlet Purifier's Flamestrike doesn't scale with player's level.

**Comment by Cefiro-Caecias** [comment]
A general fix for the scaling / overdamage of spells is still pending. Patience ;)

**Comment by Trevis77** [comment]
My bad, wasn't aware of that
