### ISSUE TITLE
[NPC] Felwing [Zone] Azsuna

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3501]
**Links:**

https://www.wowhead.com/npc=105938/felwing

**What is happening:**
There suppose to be a little event for summoning him. The event is there, but it's broken. Mobs spawn in the sky but just stay there. After the 3rd mob, there is no 4th and you are stuck.

**What should happen:**
https://youtu.be/d_nasuWf1xM?t=99

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
