### ISSUE TITLE
[Tyce] - Fishing bug

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#3502]
**Links:**
https://www.wowhead.com/fishing

**What is happening:**
The fishing blobber only visible for max 22 sec, after that the blobber just disappearing, even if the fish bite was in the last moment, we can't click on it, to catch the fish.

**What should happen:**
The blobber should be only disappear, if we get the the "No fish are hooked" message, that is the end of the fishing period, before that, we are still fishing. So if the fish only bite in the 22th sec, the blobber is visible for about 25 sec in total, not just for 22 sec, because players can't click on the invisible blobber.

**Comment by NightwindOI** [comment]
https://www.wowhead.com/npc=124736/fishing-bobber
