### ISSUE TITLE
[Quest] The Runes that Bind [NPC] Shieldmaiden Iounn

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3504]
**Links:**

https://www.wowhead.com/quest=38823/the-runes-that-bind
https://www.wowhead.com/npc=97270/shieldmaiden-iounn

**What is happening:**
It's npc issue but used the quest for a starting point. At the point when you need to take the quest, the NPC phases stack on each other.
https://imgur.com/a/fdYVElC

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
