### ISSUE TITLE
[NPC] Captain Brvet [MISC] Event

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3505]
**Links:**

https://es.wowhead.com/object=241528/cuerno-boca-infernal
https://www.wowhead.com/npc=92685/captain-brvet

**What is happening:**
The event work, but mobs don't step down from the boat and only the first one is rare.

**What should happen:**
They suppose to attack you one by one and all be rare's
https://youtu.be/gjbL5O-W9Rg?t=15

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
