### ISSUE TITLE
[NPC] Ashildir [Movement]

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3506]
**Links:**

https://www.wowhead.com/npc=93234/ashildir
https://www.wowhead.com/quest=38818/the-final-judgment

**What is happening:**
When you were about to take ''The Final Judgment'' she had double spawn stacking on each other.
https://imgur.com/a/e7hR7Wc

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
