### ISSUE TITLE
[Tyce] - Spell Arcane Barrier for quest Arcane Thirst

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3507]
**Links:**

https://www.wowhead.com/npc=98312/first-arcanist-thalyssra
https://www.wowhead.com/spell=194124/arcane-barrier
https://www.wowhead.com/quest=40009/arcane-thirst

**What is happening:**
The quest work, but the spell that Thalussra does nothing and make the quest itself very hard to be completed.

**What should happen:**
The Arcane barrier must do dmg.

**Comment by Travven** [comment]
Fixed
