### ISSUE TITLE
[Tyce] - Quest - A choice of Allies

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3512]
**Links:**

https://www.wowhead.com/quest=50242/a-choice-of-allies

**What is happening:**

After clicking Select -> Okay nothing happens. Thats strange, cuz i remember it working on beta.
![image](https://user-images.githubusercontent.com/63166930/147675354-fc02f3d4-4efe-408a-821d-a421ac95d1d3.png)

**What should happen:**

**Comment by NightwindOI** [comment]
https://www.wowhead.com/quest=50239/a-choice-of-allies same
