### ISSUE TITLE
[Tyce] - Quest: Druid Guardian Artifact Weapon

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3513]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=40647/when-dreams-become-nightmares
the search for the artifact weapon has several errors:
- Phase 1: upon reaching ursoc, it tells us how phase 2 (progresses), should continue defending Ursoc.
- Phase 2: When finished killing satyrs, ursoc says some dialogues, it should be the first wave.
- Phase 3: it tells me how the first wave should be, it should be the second wave, - Phase 4: it tells me how the second wave should be, when the third wave should be.
- Phase 5: Counts as the third wave, when it should be the fourth wave and the corruption of Ursoc
- Phase 6: tells how the fourth wave and the corruption of Ursoc, we should kill Malithar.
- Phase 7: the npc Malithar (https: //www.wowhead.com/npc=101390/arch-desecrator-malithar) remains immobile and does nothing, it should be the final phase where we take the weapon.
https://www.wowhead.com/npc=105243/lea-stonepaw
Lea doesn't attack, she should help me kill demons (phase 1-2)

https://www.wowhead.com/npc=101393/mylune
https://www.wowhead.com/npc=101754/verdant-warder
Mylune and Verdant warder when summoned by ursoc, these npc helpers must move and attack with spells and attacks, currently they don't move, they only cast spells

video: https://www.youtube.com/watch?v=liDd6CT45eo&t=1691s

**Comment by ShikoSCS** [comment]
Fixed
