### ISSUE TITLE
Quest: The Magister of Mixology (37727) Mobs not attacking

### ISSUE THREAD

**Issue by Hagigamer** [GuabinaCore/WoWKoi#3514]
Very low priority.
Quest: The Magister of Mixology (37727)
https://www.wowhead.com/quest=37727/the-magister-of-mixology
https://www.wowhead.com/object=239692/arcane-infused-egg
https://www.wowhead.com/npc=89652/shallows-heron

**What is happening:**

When taking eggs from the nests, the yellow mobs (Shallows Heron, 89652) do not react.

**What should happen:**

When taking an egg while a Shallows Heron is near, it should turn hostile and attack the player.
If I remember correctly, this has a chance of 50%-75% of happening. 
Quest completed 3 times on 3 characters, never got attacked by a mob.

**Comment by NightwindOI** [comment]
https://www.wowhead.com/object=239692/arcane-infused-egg#comments:id=2432339

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
