### ISSUE TITLE
Quest: Our very bones (37257) - Quest items not deleted

### ISSUE THREAD

**Issue by Hagigamer** [GuabinaCore/WoWKoi#3515]
Very low priority.

**Links:**

Quest: https://www.wowhead.com/quest=37257/our-very-bones
Item: https://www.wowhead.com/item=120080/pilfered-night-elf-bone

**What is happening:**

Quest objective is to collect 55 items (120080), but you can pick up more than 55 of the quest item.
Excess items are not deleted from bag after handing in the quest, but can be manually deleted.

**What should happen:**

Either player should not be able to store more than 55 in inventory (can not loot more) or excess items should be deleted after handing in quest.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
