### ISSUE TITLE
[NPC] Silverback Patriarch

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3518]
**Links:**

https://www.wowhead.com/npc=1558/silverback-patriarch

**What is happening:**
Not supposed to be there.
https://imgur.com/a/Kr7zseh

**What should happen:**
Delete it.

**Comment by Cefiro-Caecias** [comment]
I don't know how that miserable monkey got there. But when I went to check, it was gone. I close issue.
