### ISSUE TITLE
Emerald Nightmare TEST RUN! Il'gynoth, Heart of Corruption 

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3522]
**Links:**
https://www.twitch.tv/palda

**What is happening:**
Il'gynoth, Heart of Corruption :
We can go through the Eye. 
The Adds spawnin in timed period is too slow. 
Only Nightmare Horror are spawned, Deathglare and Corruptor Tentacle not spawned

NO P2 phase :O 

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
When the raid is released, it must be tested again. I close issue for the moment.
