### ISSUE TITLE
Arma artefacto - Pícaro Forajido

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3527]
**Links:**

from WoWHead or our Armory

**What is happening:**

1) https://www.wowhead.com/npc=102227/dread-harpooner
    al usar sigilo, sigo siendo visible para los add, ellos pueden atacarme
    
2) https://www.wowhead.com/npc=102191/dreadhound
    al estar en sigilo, me acerco a los canes y no sucede nada, debería revelar mi ubicación los canes
    
3) https://www.wowhead.com/quest=40849/the-dreadblades
   en la fase 2, donde pide enciontrar e Eliza, llego a la ubicacion de Eliza no sucede nada, tengo que salir de sigilo para que inicie la fase 3, Eliza dice sus dialogos y libera al gigante.
   
4) En la fase final al matar a Eliza y tomar el arma artefacto, me conto como credito y la gesta se completo, pero no recibi el arma en mi inventario.

video: https://www.youtube.com/watch?v=vaovHMOP9fE&t=322s

**Comment by Cefiro-Caecias** [comment]
1) Se verá más adelante, cuando reconstruya el escenario.

2) Se verá más adelante, cuando reconstruya el escenario.

3) Sí, debe verte para activar al gigante.

4) Reparado.
