### ISSUE TITLE
[Arthas] - Game crashing after defeating the last boss of the Scarlet Monastery

### ISSUE THREAD

**Issue by Trevis77** [GuabinaCore/WoWKoi#353]
**What is happening:**
We were a group of 4 players in the Scarlet Monastery, and the game crashed for everyone, and 2 of us have had to reboot their computer since it made crash everything.

**Comment by carlosyuniro** [comment]
3 jajaja a mi también me toco reiniciar

**Comment by Cefiro-Caecias** [comment]
Arthas, yo lo probé y no me crasheó nada. te lo paso a tí, por las dudas.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
