### ISSUE TITLE
Suramar quest chain bug 

### ISSUE THREAD

**Issue by dezmaflo** [GuabinaCore/WoWKoi#3531]
**Links:**

https://www.wowhead.com/quest=43502/a-change-of-seasons
https://www.wowhead.com/npc=103155/arcanist-valtrois

**What is happening:** A change of Seasons -- i can't complete quest because cannot find the npc
![image](https://user-images.githubusercontent.com/96207240/147835406-b4d05316-a8fa-4d65-af04-326b5dc13bf0.png)

**What should happen:**

**Comment by NightwindOI** [comment]
The npc is there, so it look like wrong phase.
