### ISSUE TITLE
Kirin Tor - missing world quests (WQ)

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3532]
**Links:**

https://www.wowhead.com/quest=43179/the-kirin-tor-of-dalaran
https://www.wowhead.com/world-quests-guide#kirin-tor-world-quests
**What is happening:**

---
1.
   Azsuna - Court of Farondis:
    -
 - [ ] [Barrels o' Fun](https://www.wowhead.com/quest=45069/barrels-o-fun)
 - [ ] [Like the Wind](https://www.wowhead.com/quest=45046/like-the-wind)
 - [ ] [Ley Race](https://www.wowhead.com/quest=43325/ley-race)
 - [ ] [The Magic of Flight](https://www.wowhead.com/quest=43327/the-magic-of-flight)
 - [ ] [Enigmatic](https://www.wowhead.com/quest=43328/enigmatic)
 
---
2.
   Highmountain - Highmountain Tribe:
    -
 - [ ] [Barrels o' Fun](https://www.wowhead.com/quest=45071/barrels-o-fun)
 - [ ] [Like the Wind](https://www.wowhead.com/quest=45048/like-the-wind)
 - [ ] [Ley Race](https://www.wowhead.com/quest=43764/ley-race)
 - [ ] [The Magic of Flight](https://www.wowhead.com/quest=43766/the-magic-of-flight)
 - [ ] [Enigmatic](https://www.wowhead.com/quest=43767/enigmatic)
---
3.
   Stormheim - Valajar :
    -
 - [ ] [Barrels o' Fun](https://www.wowhead.com/quest=45072/barrels-o-fun)
 - [ ] [Like the Wind](https://www.wowhead.com/quest=45049/like-the-wind)
 - [ ] [Ley Race](https://www.wowhead.com/quest=43769/ley-race)
 - [ ] [The Magic of Flight](https://www.wowhead.com/quest=43771/the-magic-of-flight)
 - [ ] [Enigmatic](https://www.wowhead.com/quest=43772/enigmatic)
 
---
4.
   Val'sharah - Dreamweavers:
    -
 - [ ] [Barrels o' Fun](https://www.wowhead.com/quest=45070/barrels-o-fun)
 - [ ] [Like the Wind](https://www.wowhead.com/quest=45047/like-the-wind)
 - [ ] [Ley Race](https://www.wowhead.com/quest=43753/ley-race)
 - [ ] [The Magic of Flight](https://www.wowhead.com/quest=43755/the-magic-of-flight)
 - [ ] [Enigmatic](https://www.wowhead.com/quest=43756/enigmatic)
 
---
5.
   Suramar - The Nightfallen:
    -
 - [ ] [Barrels o' Fun](https://www.wowhead.com/quest=45068/barrels-o-fun)
 - [ ] [Like the Wind](https://www.wowhead.com/quest=45032/like-the-wind)
 - [ ] [Ley Race](https://www.wowhead.com/quest=43774/ley-race)
 - [ ] [The Magic of Flight](https://www.wowhead.com/quest=43777/the-magic-of-flight)
 - [ ] [Enigmatic](https://www.wowhead.com/quest=43778/enigmatic)
 
---

 ---  --------------------------------------

**What should happen:**

**Comment by Likander** [comment]
This is still a problem with zero kirin tor world quests but the emissary quest still takes up a slot.

**Comment by Cefiro-Caecias** [comment]
Fixed all, but not blizzlike, due to lack of information on specialized pages. Available in the next update,
