### ISSUE TITLE
Quest -  Entangled Dreams

### ISSUE THREAD

**Issue by 111lazy** [GuabinaCore/WoWKoi#3537]
**Links:** 

https://www.wowhead.com/quest=38147/entangled-dreams

**What is happening:**

The bear dont want to open the door and i'm stuck.

**What should happen:**

He should open the door and let me walk to the boss

![WoWScrnShot_010222_141038](https://user-images.githubusercontent.com/96982846/147877102-e25f3f89-b768-46ba-b995-ff2336d26db2.jpg)
![WoWScrnShot_010222_141050](https://user-images.githubusercontent.com/96982846/147877106-0538c548-fe16-44ac-b4f4-fe05edb35efa.jpg)

**Comment by NightwindOI** [comment]
Will be fixed with the next server update (phase reverse)
