### ISSUE TITLE
ARTIFACT WEAPON FOR HOLY PALADIN

### ISSUE THREAD

**Issue by Jovan290** [GuabinaCore/WoWKoi#3540]
Hi, when i was around level 105 i got to choose new Artifact weapon and i have saw that NPC was offering for both of weapons so i have triend to take both of quests at same time, but i got only for Protection Paladin and for Holy not, i dont know what might be the reason maybe that i have tried to take both at same time or something else, now i am not able to see and to take starter quest for Holy weapon, please help me.

**Comment by Noahkrr** [comment]
there is an npc in Dalaran that fixes artifact weapon quests
