### ISSUE TITLE
(Entangled Dreams) Val'sharah quest!!!

### ISSUE THREAD

**Issue by Jovan290** [GuabinaCore/WoWKoi#3541]
![WoWScrnShot_010622_011856](https://user-images.githubusercontent.com/97184919/148308355-078b3f80-4a68-4ad3-93b7-a6d68f79ae66.jpg)

After u walk with bear towards Brambels he doesnt destroy the brambels and u cannot pass to destroy source of corruption, i have saw in previous Changelog that this issue was solved but i was trying several times and it doesnt work.I have removed the Cache folder before. Please help

**Comment by wowmagemaster** [comment]
It's still not working!!!

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
