### ISSUE TITLE
[Core] - Holy paladin - Blessing of Freedom

### ISSUE THREAD

**Issue by Jovan290** [GuabinaCore/WoWKoi#3542]
![WoWScrnShot_010622_024112](https://user-images.githubusercontent.com/97184919/148314702-0441b9ef-11f1-4700-a110-2894dd253868.jpg)

I was trying several times but when i get reduction debuff (BoF) doesnt remove it and doesnt remove debuff, Please FIX!

**Comment by Travven** [comment]
That mechanic is correct, that daze effect is not removed by HoF
