### ISSUE TITLE
[Core] Universal Profession Trainer - Spanish Dialogue

### ISSUE THREAD

**Issue by Frosty015** [GuabinaCore/WoWKoi#355]
**Links:** [Profession trainers like this one](https://www.wowhead.com/npc=47384/lien-farner)

**What is happening:** This is something I noticed so far in **all** profession trainers which offer apprentice level training in both gathering and crafting professions. Upon first interacting with them their dialogue comes up as spanish, but the options we can choose from when interacting with them are in english ("Tell me about gathering professions")

**What should happen:** Dialogue should be in english if I'm not mistaken as this is an international realm right? ^^

and just to clarify, I saw this in **All** universal basic profession trainers such as the one linked above. Profession trainers that offer training for one specific profession don't have this issue

**Comment by Cefiro-Caecias** [comment]
No English translation at the moment XD

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
