### ISSUE TITLE
Paladin Class Hall issue

### ISSUE THREAD

**Issue by IcicleUBW** [GuabinaCore/WoWKoi#3551]
**Links:**
![image](https://user-images.githubusercontent.com/97225139/148547233-0fb6b0bb-927e-461f-a4df-efc808b1d641.png)

location of NPC
![image](https://user-images.githubusercontent.com/97225139/148547400-067d30e6-3939-4843-b3d8-66c48555f3fe.png)

**2**
![image](https://user-images.githubusercontent.com/97225139/148547518-aa4ea44e-e96a-48aa-902d-c9da92150891.png)

location of NPC

![image](https://user-images.githubusercontent.com/97225139/148547612-8ae12fa4-0602-4384-8b04-1555c000be5c.png)

from WoWHead or our Armory
https://www.wowhead.com/order-advancement=400/plowshares-to-swords#comments
https://www.wowhead.com/order-advancement=399/grand-crusade#comments

**What is happening:**

The npc is not there thus the Paladin class hall upgrade doesn't work properly.

**What should happen:**

There should be NPC spawned on the following locations in the Paladin class hall, with a mini quest introducing the new work orders.

**Comment by ShikoSCS** [comment]
Fixed
