### ISSUE TITLE
Suramar quest bugged

### ISSUE THREAD

**Issue by conyoshi** [GuabinaCore/WoWKoi#3552]
Hi, I have a problem with the quest "Smuggled!" (44727). The mission asks me to release citizens from cages, when I finish releasing them, the mission restarts and is never completed, I attach photos if im not clear: https://imgur.com/DE5EhtU https://imgur.com/IJVd97a
Pls help and thanks.

**Comment by nazgrim94** [comment]
Si me sucede lo mismo que los npc liberados desde la jaula no actualizan la misión en el registro y no se puede completar.. Pero me pudieron ayudar...

**Comment by ventarius5** [comment]
Yes, I can confirm that opening cages doesn't grant credits toward the quest.

https://www.wowhead.com/quest=44727/smuggled
