### ISSUE TITLE
Npc with a lot of damage

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3554]
**Links:**

from WoWHead or our Armory

**What is happening:**
these npcs do a lot of damage, the damage they do should be reduced.

https://www.wowhead.com/npc=92415/storm-drake-whelp
https://www.wowhead.com/npc=92206/felscale-pilferer
https://www.wowhead.com/npc=92128/felskorn-pilferer
https://www.wowhead.com/npc=97906/runebound-wretch
https://www.wowhead.com/npc=91118/stinger-wasp
https://www.wowhead.com/npc=119522/burning-trickster
https://www.wowhead.com/npc=108327/undulating-boneslime
https://www.wowhead.com/npc=90140/eye-of-ernstenbok
https://www.wowhead.com/npc=101614/gnawer
https://www.wowhead.com/npc=95873/skywhisker-scrapper
https://www.wowhead.com/npc=115014/felsoul-imp
https://es.wowhead.com/npc=93442/credit-bunny

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=89811/subjugated-murloc

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=97859/karuas
https://www.wowhead.com/npc=97944/muorg
https://www.wowhead.com/npc=97822/garzareth
check this spell(https://www.wowhead.com/spell=210535/rain-of-fire), sometimes it fails, the spell doesn't go away and it kills me
https://www.wowhead.com/npc=97942/ravathes

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=105899/oglok-the-furious

**Comment by Cefiro-Caecias** [comment]
Reparados todos, disponibles en el próximo update.
La spell que reportaste pasa a manos de los Devs de Core.
