### ISSUE TITLE
Misión "Forzar una confesión"  Campaña de brujo (Sede de clase ) 

### ISSUE THREAD

**Issue by Kprtn** [GuabinaCore/WoWKoi#3556]
**Links:**
https://www.wowhead.com/quest=41788/coercing-a-confession
from WoWHead or our Armory

**What is happening:**

El npc "Galius Ciénago"  aparece enemigo y te ataca pero no se le puede atacar ( objetivo no válido) con lo cual no se puede completar la misión
![WoWScrnShot_010822_145644](https://user-images.githubusercontent.com/96433337/148653713-2c8b19ab-7473-4fd9-9c59-96a36cb9addb.jpg)

**What should happen:**
ir a la cueva, matar a Galius, entregar la misión
https://www.youtube.com/watch?v=93d-hEG2-m8

**Comment by Cefiro-Caecias** [comment]
Reparado, 100% blizzlike, para compensarte las molestias. Disponible mañana, luego del update matutino ^^
