### ISSUE TITLE
Suggested Content - Random Heroic Dungeon

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3557]
**Links:**

http://www.kepfeltoltes.eu/view.php?filename=722unknown.png

**What is happening:**

I dont get the reward for doin the Random Heroic Dungeon :C

**What should happen:**

**Comment by armirmoazezi** [comment]
what should happen : 
it should gives you the item that is shown to you but (suggested content) in adventure book
