### ISSUE TITLE
Suramar - Quest - The Felsoul Experiments

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3562]
**Links:**

https://www.wowhead.com/quest=45063/the-felsoul-experiments#comments

**What is happening:**

Using [Experimental Targeting Orb](https://www.wowhead.com/item=142399/experimental-targeting-orb) doesn't grant credits toward the quest.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
