### ISSUE TITLE
World Quest - stormheim - Now That's Just Clawful!

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3563]
**Links:**

https://www.wowhead.com/quest=44943/now-thats-just-clawful#

**What is happening:**

This WQ automatically transforms the player into the Murky form. After I "ejected" myself from the Murky form multiple times, I was got phased out of the normal world and teleported into the ocean. 

![image](https://user-images.githubusercontent.com/63166930/149160771-759b8591-71ed-418c-838f-438dbd6ee4d7.png)

**What should happen:**

**Comment by bastian-brito** [comment]
At this day, this bug persist. If flying over the quest zone, transform automatically into Murky. And every time an npc is killed NOT in Murky form, returns into that form immediately until the quest is over. 
Very annoying
