### ISSUE TITLE
[Arthas] - Brill Tavern Music

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#357]
**Links:**
https://www.youtube.com/watch?v=H5rZEpb3nwY
https://wow.tools/files/#search=undead_dance&page=1&sort=0&desc=asc

**What is happening:**
So I thought it would be nice to add in old Brill music (id 53747)  for nostlagia reasons and also it sounds cool :P. If it's not too difficult I would be happy to hear it ingame.

**Comment by Cefiro-Caecias** [comment]
Arthas, lo dejo a tu criterio.
