### ISSUE TITLE
Priest Class Hall Campaign - A Light in the Darkness

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3572]
**Links:**

[from WoWHead or our Armory](https://www.wowhead.com/quest=43401/a-light-in-the-darkness)

**What is happening:**

When I speak with Lord Maxwell Tyrosus and Prophet Velen the Scenario not Started and the Q cannot be completed.

**What should happen:**

**Comment by bastian-brito** [comment]
At this day, the scenario still doesn't start
