### ISSUE TITLE
The Arcway Mythic+ - Nal'tira

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3573]
**Links:**

[from WoWHead or our Armory](https://www.wowhead.com/npc=98207/naltira)

**What is happening:**

https://www.wowhead.com/spell=199811/blink-strikes
The team get 2 Blink Strike instead of 1 and the damage taken from the spell is doubled.
https://cdn.discordapp.com/attachments/809109817523437609/931689845632426075/unknown.png 

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed by Travven.
