### ISSUE TITLE
Prospecting ratios

### ISSUE THREAD

**Issue by Valcry1** [GuabinaCore/WoWKoi#3581]
https://ibb.co/Xsy6swq
https://ibb.co/Rp2Gh7f
https://ibb.co/QrGmV82
**What is happening:**
Prospecting ore is generating to many DawnLight and Furystone and too few of the others. Especially Shadowfury. Uncommon gems are a bit lopsided as well. This has been true outside this controlled group I did in the pictures. Pic 1 is before, pic 2 is after 190 leystone, and pic 3 is after 130 felslate with leystone.

**What should happen:**
Gem counts should be relatively close in count. Yellow and red of rare gems proc way too many times.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available now.
