### ISSUE TITLE
Emissary Legendary Drop 

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3582]
**Links:**

[from WoWHead or our Armory](https://www.wowhead.com/world-quests/legion/eu)

**What is happening:**

When I opened the Emissary box, and get a Legendary Item, i'll get a random spec Legendary (if i get with low %), not the spec that i have. 

**What should happen:**

When we get a Legendary from Emmisary Boxes, We should be collected the Active Specialization Legendary Gear

**Comment by NightwindOI** [comment]
https://i.imgur.com/Uo5KK0W.png
https://www.wowhead.com/item=137563/farondis-lockbox#comments:id=2364690
According to this, it's possible to get an item for another spec. I'll close the issue for now and make a little discussion with the staff to let it this way, or change it to drop only items for the spec.
