### ISSUE TITLE
WQ - Suramar - Hertha Grimdothir

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3583]
**Links:**

https://www.wowhead.com/quest=44029/wanted-hertha-grimdottir#comments
https://www.wowhead.com/quest=44021/wanted-hertha-grimdottir

**What is happening:**

Even though I have this WQ, the NPC doesn't show as objective of the WQ and killing her wont complete it. She became an objective of the quest after she respawned.

The ID i have is 44021.

![image](https://user-images.githubusercontent.com/63166930/149970662-2dbdc214-2ddb-4245-a4d4-4781d1cd9e48.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
I just tried all 3 quests involving this NPC, and they worked fine for me o.O

**Comment by ventarius5** [comment]
According to wowhead comment :

"Unlike most world quest rares, she did not seem to be cross faction taggable (either that or she bugged on that specific kill).

So if there are other faction around, check your completion before you leave the area ><"

maybe thats the reason?

**Comment by Cefiro-Caecias** [comment]
I will apply an experimental fix. When you can try to kill her, and tell me. Available in the next update.
