### ISSUE TITLE
The Loremaster of Karazhan, Part 6-7-8

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3595]
**Links:**
https://www.wowhead.com/quest=44557/finite-numbers
https://www.wowhead.com/quest=44683/holding-the-lines
https://www.wowhead.com/quest=44684/corruption-runs-deep

**What is happening:**
We can kill only the demons, but cannot d
-Disable Portals,
- Cannot secured Ley Lines, 
- Cannot collect sample's of Soil and Water. 

**What should happen:**
https://www.youtube.com/watch?v=h9TvR1MXDYg

https://wowpedia.fandom.com/wiki/Return_to_Karazhan
https://wowpedia.fandom.com/wiki/Return_to_Karazhan_(quest)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
