### ISSUE TITLE
Val'sharah - Moon Reaver 

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3597]
**Links:**

https://www.wowhead.com/quest=42751/moon-reaver
https://www.wowhead.com/npc=108887/keeper-remulos

**What is happening:**

After killing Boneflux and move to complete the quest Keeper Remulos not spawned in the Moonwell. 

**What should happen:**

**Comment by MohammadAbdelshafy** [comment]
this happens with me too

**Comment by bastian-brito** [comment]
still to this days is bugged, same here
