### ISSUE TITLE
[Core] - Shattering Strikes - Frost Death Knight talent.

### ISSUE THREAD

**Issue by Drathnor** [GuabinaCore/WoWKoi#36]
**Links:**

https://www.wowhead.com/spell=207057/shattering-strikes
https://www.wowhead.com/spell=51714/razorice
https://www.wowhead.com/spell=49143/frost-strike

**What is happening:**

If there are 5 stacks of Razorice on the target, Frost Strike doesn't consume them, and won't deal extra damage.

**What should happen:**

If there are 5 stacks of Razorice on the target, Frost Strike will consume them and deal 60% additional damage.

**Comment by ShikoSCS** [comment]
Fixed
