### ISSUE TITLE
World Quest (WQ) - WANTED: Skul'vrax

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3600]
**Links:**

https://www.wowhead.com/quest=43631/wanted-skulvrax#comments
https://www.wowhead.com/quest=43456/wanted-skulvrax#comments

**What is happening:**

The event work fine but Skul'vrax is not attackable after he appears.

**What should happen:**

**Comment by Thordekk** [comment]
Remove flag and fixed
