### ISSUE TITLE
Trial of the crusader hides of legend - Skinning

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3606]
**Links:**
https://www.wowhead.com/quest=40138/trial-of-the-crusader-hides-of-legend
from WoWHead or our Armory

**What is happening:**
The first credit of the quest can't be completed, because the raid npc(https://www.wowhead.com/npc=34796/gormok-the-impaler) doesn't die, it can't be selected. that does not let me advance the raid. i need to get to this npc (https://www.wowhead.com/npc=34797/icehowl) and by killing him I should get (https://www.wowhead.com/item=129912/hide-of-icehowl)

**Comment by IcicleUBW** [comment]
still broken tested 17-04-2022 boos still cant be target
