### ISSUE TITLE
Class hall mission "unassign"

### ISSUE THREAD

**Issue by Swagvok** [GuabinaCore/WoWKoi#3609]
**Links:**

from WoWHead or our Armory

**What is happening:*The Unassign button does nothing*

**What should happen:*It should Unassign my bodyguard, and show it in active followers*
![WoWScrnShot_012722_181523](https://user-images.githubusercontent.com/96172102/151409647-d529f7cb-8df6-42df-8e0d-ebc4029a4cfc.jpg)

**Comment by Doxxy0** [comment]
its still not working, recently tried it out. fresh install of the game
