### ISSUE TITLE
Cache of Fel Treasures was empty

### ISSUE THREAD

**Issue by larah92** [GuabinaCore/WoWKoi#3611]
**Links:**
https://www.wowhead.com/item=147520/cache-of-fel-treasures

from WoWHead or our Armory

**What is happening:**
I did Timewalking dungeons weekly quest in Dalaran. I got the chest from the quest, but Cache of Fel Treasures was fully empty.
My character's name is Zathana.

**What should happen:**
I'd like to to get any item or another chest to open.

**Comment by armirmoazezi** [comment]
there is a change to get non usable relics too as druid i got a fel relic / shadow relic

**Comment by larah92** [comment]
> there is a change to get non usable relics too as druid i got a fel relic / shadow relic

But i got nothing. It was empty. No cloth, no leather, no mail, no plate items and no relic or trinket, so fully nothing.
