### ISSUE TITLE
Legendary Drop Chance for Spec

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3615]
**Links:**

[from WoWHead or our Armory](https://www.wowhead.com/legion-legendary-items-guide)

**What is happening:**
Get Legendary in other specialization than we have :C 

"Only specific legendaries will drop for you - a  Shaman legendary will not drop for a  Death Knight, nor will a Restoration  Druid legendary drop for a Feral  Druid. This will be based on loot specialization - note that some legendaries will drop for multiple specs (see below re: Types of Legendaries; the loot specializations for each legendary are noted in the complete list in this guide)."
- Wowhead

**What should happen:**

**Comment by ShikoSCS** [comment]
Fixed
