### ISSUE TITLE
The Legendary bug

### ISSUE THREAD

**Issue by Swagvok** [GuabinaCore/WoWKoi#3616]
**Links:* https://www.youtube.com/watch?v=rnd2u_5e1JQ *

from WoWHead or our Armory

**What is happening:* 
Just check the video, my Fella is getting her main spec legendaries, while Us are mostly (99%) are getting the other spec's legos.
*

**What should happen:
We are supposed to get our main spec legos, till we got them all, and Then we can get the other specs too (i played a bit of retail legion, and we always got the main spec legos *proof: screenshot down below*)**
![received_1077972845638924](https://user-images.githubusercontent.com/96172102/151668810-ba664b0b-4326-494d-9c9b-558c0cd7d4c0.jpg)
![received_1077973825638826](https://user-images.githubusercontent.com/96172102/151668816-6b0e7644-0ba0-4c1a-a0de-163c7e0d834f.jpg)
![received_1077977022305173](https://user-images.githubusercontent.com/96172102/151668817-2de443e5-3a72-4255-80ca-0114416f5f06.jpg)

**Comment by ShikoSCS** [comment]
Fixed
