### ISSUE TITLE
Durotar - Mobs level scaling

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#362]
**Links:**
https://www.wowhead.com/npc=3100/elder-mottled-boar
https://www.wowhead.com/npc=3127/venomtail-scorpid
https://www.wowhead.com/npc=42859/wild-mature-swine
https://www.wowhead.com/npc=3123/bloodtalon-scythemaw
https://www.wowhead.com/npc=39595/furious-earthguard
https://www.wowhead.com/npc=39596/teeming-waterguard
from WoWHead or our Armory

**What is happening:**
They don't scale.

**What should happen:**
They should scale.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
