### ISSUE TITLE
Greater Power for Greater Threats

### ISSUE THREAD

**Issue by IcicleUBW** [GuabinaCore/WoWKoi#3625]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=46744/greater-power-for-greater-threats#comments
![image](https://user-images.githubusercontent.com/97225139/151701011-4cf16eaf-f581-4506-a1fd-f378bb04a028.png)

**What is happening:**

Quest does not work. Uppon reaching 35 ap traits you cant continue the quest. You cant get new traits

**What should happen:**

**Comment by PiR4T496** [comment]
i had the same problem 
https://ibb.co/4dffnqW
https://ibb.co/zGXJkm2

**Comment by ShikoSCS** [comment]
It is a small visual defect. Wait a few minutes, exit the game and re-enter several times and you will see that you can unlock more traits of your artifact
