### ISSUE TITLE
NPC - Crocolisco escamarea

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3633]
**Links:**
https://www.wowhead.com/npc=118255/seascale-crocolisk
from WoWHead or our Armory

**What is happening:**
este npc al matarlo da 82p de reputacion con ocaso de la legión, hay muchos de esos npc. no deberian dar reputacion..

**Comment by ShikoSCS** [comment]
Fixed, available in the next update
