### ISSUE TITLE
[Arthas] - Turtlemaster Odai

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#364]
**Links:**
https://www.wowhead.com/npc=66022/turtlemaster-odai
from WoWHead or our Armory

**What is happening:**
You can buy the mounts without Exalted reputation.
Also he has the mounts double to sell.

**What should happen:**
You should have Exalted reputation with Huojin Pandaren.
She should have each turtle once in her sales tab.

**Comment by Cefiro-Caecias** [comment]
Fixed.
