### ISSUE TITLE
Assault on Stormheim - Defending Broken Isles

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3640]
**Links:**

from WoWHead or our Armory[
](https://www.wowhead.com/quest=46247/defending-broken-isles)
**What is happening:**

Cannot Complete the Quest after completing the 4 quest on Legion Assault. Solve it

**What should happen:**

**Comment by OnlyWATCH** [comment]
scenario is totally %100 bugged , need to be fix it .

**Comment by PiR4T496** [comment]
The scenari is 100% bugged , only the first misions work , until reaching vethir , Vethir is bug, you can not give him the completed mission, then when you ride on his back and start shooting rays that part works, but from then on nothing works at all
