### ISSUE TITLE
Azsuna World Quest - Brogozog

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3641]
**Links:**

[from WoWHead or our Armory](https://www.wowhead.com/npc=91100/brogozog)

**What is happening:**

When you killed the NPC that not completed the WQ. 

**What should happen:**

**Comment by PiR4T496** [comment]
many times it happens because you have the mission log full or also sometimes it bugs and I was able to solve it by relogging or leaving and coming back

**Comment by ventarius5** [comment]
Unfortunately, I can confirm, that re-logging or clearing your quest log doesn't solve the issue. I've killed the NPC 3 times already and it still spawns as a non-WQ NPC:
![image](https://user-images.githubusercontent.com/63166930/168022017-bde8bba0-e9f2-4443-8f33-6d13792052cf.png)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
