### ISSUE TITLE
Alchemy , third healing potion upgrade .

### ISSUE THREAD

**Issue by PiR4T496** [GuabinaCore/WoWKoi#3647]
**Links:**
https://es.wowhead.com/spell=188300/poci%C3%B3n-de-sanaci%C3%B3n-antigua

from WoWHead or our Armory

**What is happening:**

Chance to create multiple potions,  never happen and it is not only with the healing potion, it also happens with the alchemist stone, which makes me believe that it is a widespread problem .

**What should happen:**

Chance to create multiple potions in rank 3 .

**Comment by ShikoSCS** [comment]
Fixed
