### ISSUE TITLE
Cocina - Pedidos

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3657]
**Links:**

from WoWHead or our Armory

**What is happening:**
actualmente tengo un pedido de cocina listo, pero no me deja recogerlo. ademas de eso me caen recetas que no puedo usar y ya no me deja hacer pedidos porque no puedo recoger.
otro problema es que solo puedes hacer un pedido, cuando deberías hacer múltiples pedidos hasta un maximo de 24  pedidos por día.
![image](https://user-images.githubusercontent.com/81131460/152923097-bc1fb4a1-3b10-40bd-8436-06c40ce7fdb7.png)
no debería recibir estos items. debería recibir las recetas de comida(porcentaje bajo), comida churrada, comida ligeramente quemada, comida de los ingredientes investigados .
![image](https://user-images.githubusercontent.com/81131460/152921576-82ae34c8-6619-46df-8392-2565607b3e58.png)

**What should happen:**
mediante la investigación de los productos por parte de [Nomi](https://es.wowhead.com/npc=101846/nomi), tardará 4 horas por cada pedido, pudiendose hacer hasta 24 pedidos a la vez, que se irán encadenando uno trás otro. Pero muchas de las investigaciones serán fallidas y  obtendras [Comida churrada](https://es.wowhead.com/item=133913/comida-churruscada) y [Comida ligeramente quemada](https://es.wowhead.com/item=143681/comida-ligeramente-quemada). también obtendrás [Aperitivos de Nomi](https://es.wowhead.com/item=151133/aperitivos-de-nomi) y [Ingredientes preparados](https://es.wowhead.com/item=146757/ingredientes-preparados).

Como debería funcionar los pedidos de investigación:
<html>
<body>

Investigación | Recompensa de receta de las siguientes comidas
-- | -- 
[Corvo magro](http://es.wowhead.com/item=124117/corvo-magro) | comida [Ensalada azsh'ari](http://es.wowhead.com/item=133571/ensalada-azsharita) (recetas [Rank 1](https://es.wowhead.com/spell=201506/ensalada-azshari), [Rank 2](https://es.wowhead.com/spell=201535/ensalada-azshari), [Rank 3](https://es.wowhead.com/spell=201555/ensalada-azshari)), comida [Cocido de Suramar](http://es.wowhead.com/item=133566/cocido-de-suramar) (recetas [Rank 2](https://es.wowhead.com/spell=201530/cocido-de-suramar), [Rank 3](https://es.wowhead.com/spell=201550/cocido-de-suramar)), comida [Corvo con sal y pimienta](http://es.wowhead.com/item=133557/corvo-con-sal-y-pimienta) (recetas [Rank 2](https://es.wowhead.com/spell=201524/corvo-con-sal-y-pimienta), [Rank 3](https://es.wowhead.com/spell=201544/corvo-con-sal-y-pimienta)), comida [Festín suculento](http://es.wowhead.com/item=133578/festin-suculento) (recetas [Rank 2](https://es.wowhead.com/spell=201542/festín-suculento) [Rank 3](https://es.wowhead.com/spell=201562/festín-suculento))
[Huevo de ave silvestre](http://es.wowhead.com/item=124121/huevo-de-ave-silvestre) | comida [Fuente de manjares de los Nocheterna](http://es.wowhead.com/item=133572/fuente-de-manjares-de-los-nocheterna) (recetas [Rank 1](https://es.wowhead.com/spell=201507/fuente-de-manjares-de-los-nocheterna), [Rank 2](https://es.wowhead.com/spell=201536/fuente-de-manjares-de-los-nocheterna), [Rank 3](https://es.wowhead.com/spell=201556/fuente-de-manjares-de-los-nocheterna)), comida [Bebida espumosa de Faronaar](http://es.wowhead.com/item=133563/bebida-espumosa-de-faronaar)  (recetas [Rank 2](https://es.wowhead.com/spell=201527/bebida-espumosa-de-faronaar), [Rank 3](https://es.wowhead.com/spell=201547/bebida-espumosa-de-faronaar)), comida [Festín suculento](http://es.wowhead.com/item=133578/festin-suculento) (recetas [Rank 2](https://es.wowhead.com/spell=201542/festín-suculento), [Rank 3](https://es.wowhead.com/spell=201562/festín-suculento))
[Filete de oso graso](http://es.wowhead.com/item=124118/filete-de-oso-graso) | comida [Magister hambriento](http://es.wowhead.com/item=133570/magister-hambriento) (recetas [Rank 1](https://es.wowhead.com/spell=201505/magister-hambriento), [Rank 2](https://es.wowhead.com/spell=201534/magister-hambriento), [Rank 3](https://es.wowhead.com/spell=201554/magister-hambriento)), comida [Tartar de oso](http://es.wowhead.com/item=133576/tartar-de-oso) (recetas [Rank 2](https://es.wowhead.com/spell=201540/tartar-de-oso), [Rank 3](https://es.wowhead.com/spell=201560/tartar-de-oso))
[Sangre Ley](http://es.wowhead.com/item=124120/sangre-ley) | comida [Magister hambriento](http://es.wowhead.com/item=133570/magister-hambriento) (recetas [Rank 1](https://es.wowhead.com/spell=201505/magister-hambriento), [Rank 2](https://es.wowhead.com/spell=201534/magister-hambriento), [Rank 3](https://es.wowhead.com/spell=201554/magister-hambriento)), comida [Fuente de manjares de los Nocheterna](http://es.wowhead.com/item=133572/fuente-de-manjares-de-los-nocheterna) (recetas [Rank 1](https://es.wowhead.com/spell=201507/fuente-de-manjares-de-los-nocheterna), [Rank 2](https://es.wowhead.com/spell=201536/fuente-de-manjares-de-los-nocheterna), [Rank 3](https://es.wowhead.com/spell=201556/fuente-de-manjares-de-los-nocheterna)), comida [Costillas a la barbacoa Ley](http://es.wowhead.com/item=133565/costillas-a-la-barbacoa-ley) (recetas [Rank 2](https://es.wowhead.com/spell=201529/costillas-a-la-barbacoa-ley), [Rank 3](https://es.wowhead.com/spell=201549/costillas-a-la-barbacoa-ley)), comida [Mrglgagh de barracuda](http://es.wowhead.com/item=133567/mrglgagh-de-barracuda) (recetas [Rank 2](https://es.wowhead.com/spell=201531/mrglgagh-de-barracuda), [Rank 3](https://es.wowhead.com/spell=201551/mrglgagh-de-barracuda)), comida [Festín copioso de Suramar](http://es.wowhead.com/item=133579/festin-copioso-de-suramar) (recetas [Rank 1](https://es.wowhead.com/spell=201516/festín-copioso-de-suramar), [Rank 2](https://es.wowhead.com/spell=201543/festín-copioso-de-suramar), [Rank 3](https://es.wowhead.com/spell=201563/festín-copioso-de-suramar))
[Pez reina maldito](http://es.wowhead.com/item=124107/pez-reina-maldito) | comida [Especial de pescabrul](http://es.wowhead.com/item=133574/especial-de-pescabrul) (recetas [Rank 1](https://es.wowhead.com/spell=201511/especial-de-pescabrul), [Rank 2](https://es.wowhead.com/spell=201538/especial-de-pescabrul), [Rank 3](https://es.wowhead.com/spell=201558/especial-de-pescabrul)), comida [Condumio de luchador](http://es.wowhead.com/item=133577/condumio-de-luchador) (recetas [Rank 2](https://es.wowhead.com/spell=201541/condumio-de-luchador), [Rank 3](https://es.wowhead.com/spell=201561/condumio-de-luchador)), comida [Festín copioso de Suramar](http://es.wowhead.com/item=133579/festin-copioso-de-suramar) (recetas [Rank 1](https://es.wowhead.com/spell=201516/festín-copioso-de-suramar), [Rank 2](https://es.wowhead.com/spell=201543/festín-copioso-de-suramar), [Rank 3](https://es.wowhead.com/spell=201563/festín-copioso-de-suramar))
[Perca branquimusgo](http://es.wowhead.com/item=124108/perca-branquimusgo) | comida [Especial de pescabrul](http://es.wowhead.com/item=133574/especial-de-pescabrul) (recetas [Rank 1](https://es.wowhead.com/spell=201511/especial-de-pescabrul), [Rank 2](https://es.wowhead.com/spell=201538/especial-de-pescabrul), [Rank 3](https://es.wowhead.com/spell=201558/especial-de-pescabrul)), comida [Branquimusgo bien frito](http://es.wowhead.com/item=133561/branquimusgo-bien-frito) (recetas [Rank 2](https://es.wowhead.com/spell=201525/branquimusgo-bien-frito), [Rank 3](https://es.wowhead.com/spell=201545/branquimusgo-bien-frito)), comida [Festín suculento](http://es.wowhead.com/item=133578/festin-suculento) (recetas [Rank 2](https://es.wowhead.com/spell=201542/festín-suculento), [Rank 3](https://es.wowhead.com/spell=201562/festín-suculento)), comida [Festín copioso de Suramar](http://es.wowhead.com/item=133579/festin-copioso-de-suramar) (recetas [Rank 1](https://es.wowhead.com/spell=201516/festín-copioso-de-suramar), [Rank 2](https://es.wowhead.com/spell=201543/festín-copioso-de-suramar), [Rank 3](https://es.wowhead.com/spell=201563/festín-copioso-de-suramar))
[Salmón de Monte Alto](http://es.wowhead.com/item=124109/salmon-de-monte-alto) | comida [Especial de pescabrul](http://es.wowhead.com/item=133574/especial-de-pescabrul) (recetas [Rank 1](https://es.wowhead.com/spell=201511/especial-de-pescabrul), [Rank 2](https://es.wowhead.com/spell=201538/especial-de-pescabrul), [Rank 3](https://es.wowhead.com/spell=201558/especial-de-pescabrul)), comida [Salmón al estilo drógbar](http://es.wowhead.com/item=133569/salmon-al-estilo-drogbar) (recetas [Rank 2](https://es.wowhead.com/spell=201533/salmón-al-estilo-drógbar), [Rank 3](https://es.wowhead.com/spell=201553/salmón-al-estilo-drógbar)), comida [Festín copioso de Suramar](http://es.wowhead.com/item=133579/festin-copioso-de-suramar) (recetas [Rank 1](https://es.wowhead.com/spell=201516/festín-copioso-de-suramar), [Rank 2](https://es.wowhead.com/spell=201543/festín-copioso-de-suramar), [Rank 3](https://es.wowhead.com/spell=201563/festín-copioso-de-suramar))
[Rayatormenta](http://es.wowhead.com/item=124110/rayatormenta) | comida [Plato de pescado rebozado con semillas](http://es.wowhead.com/item=133573/plato-de-pescado-rebozado-con-semillas) (recetas [Rank 1](https://es.wowhead.com/spell=201508/plato-de-pescado-rebozado-con-semillas), [Rank 2](https://es.wowhead.com/spell=201537/plato-de-pescado-rebozado-con-semillas), [Rank 3](https://es.wowhead.com/spell=201557/plato-de-pescado-rebozado-con-semillas)), comida [Rayatormenta con aroma a koi](http://es.wowhead.com/item=133568/rayatormenta-con-aroma-a-koi) (recetas [Rank 2](https://es.wowhead.com/spell=201532/rayatormenta-con-aroma-a-koi), [Rank 3](https://es.wowhead.com/spell=201552/rayatormenta-con-aroma-a-koi)), comida [Cocido de Suramar](http://es.wowhead.com/item=133566/cocido-de-suramar) (recetas [Rank 2](https://es.wowhead.com/spell=201530/cocido-de-suramar), [Rank 3](https://es.wowhead.com/spell=201550/cocido-de-suramar)), comida [Festín copioso de Suramar](http://es.wowhead.com/item=133579/festin-copioso-de-suramar) (recetas [Rank 1](https://es.wowhead.com/spell=201516/festín-copioso-de-suramar), [Rank 2](https://es.wowhead.com/spell=201543/festín-copioso-de-suramar), [Rank 3](https://es.wowhead.com/spell=201563/festín-copioso-de-suramar))
[Koi de escamas rúnicas](http://es.wowhead.com/item=124111/koi-de-escamas-runicas) | comida [Plato de pescado rebozado con semillas](http://es.wowhead.com/item=133573/plato-de-pescado-rebozado-con-semillas) (recetas [Rank 1](https://es.wowhead.com/spell=201508/plato-de-pescado-rebozado-con-semillas), [Rank 2](https://es.wowhead.com/spell=201537/plato-de-pescado-rebozado-con-semillas), [Rank 3](https://es.wowhead.com/spell=201557/plato-de-pescado-rebozado-con-semillas)), comida [Ensalada azsh'ari](http://es.wowhead.com/item=133571/ensalada-azsharita) (recetas [Rank 1](https://es.wowhead.com/spell=201506/ensalada-azshari), [Rank 2](https://es.wowhead.com/spell=201535/ensalada-azshari), [Rank 3](https://es.wowhead.com/spell=201555/ensalada-azshari)), comida [Rayatormenta con aroma a koi](http://es.wowhead.com/item=133568/rayatormenta-con-aroma-a-koi) (recetas [Rank 2](https://es.wowhead.com/spell=201532/rayatormenta-con-aroma-a-koi), [Rank 3](https://es.wowhead.com/spell=201552/rayatormenta-con-aroma-a-koi)), comida [Cocido de Suramar](http://es.wowhead.com/item=133566/cocido-de-suramar) (recetas [Rank 2](https://es.wowhead.com/spell=201530/cocido-de-suramar), [Rank 3](https://es.wowhead.com/spell=201550/cocido-de-suramar)), comida [Festín copioso de Suramar](http://es.wowhead.com/item=133579/festin-copioso-de-suramar) (recetas [Rank 1](https://es.wowhead.com/spell=201516/festín-copioso-de-suramar), [Rank 2](https://es.wowhead.com/spell=201543/festín-copioso-de-suramar), [Rank 3](https://es.wowhead.com/spell=201563/festín-copioso-de-suramar))
[Barracuda negra](http://es.wowhead.com/item=124112/barracuda-negra) | comida [Especial de pescabrul](http://es.wowhead.com/item=133574/especial-de-pescabrul) (recetas [Rank 1](https://es.wowhead.com/spell=201511/especial-de-pescabrul), [Rank 2](https://es.wowhead.com/spell=201538/especial-de-pescabrul), [Rank 3](https://es.wowhead.com/spell=201558/especial-de-pescabrul)), comida [Fuente de manjares de los Nocheterna](http://es.wowhead.com/item=133572/fuente-de-manjares-de-los-nocheterna) (recetas [Rank 1](https://es.wowhead.com/spell=201507/fuente-de-manjares-de-los-nocheterna), [Rank 2](https://es.wowhead.com/spell=201536/fuente-de-manjares-de-los-nocheterna), [Rank 3](https://es.wowhead.com/spell=201556/fuente-de-manjares-de-los-nocheterna)), comida [Mrglgagh de barracuda](http://es.wowhead.com/item=133567/mrglgagh-de-barracuda) (recetas [Rank 2](https://es.wowhead.com/spell=201531/mrglgagh-de-barracuda), [Rank 3](https://es.wowhead.com/spell=201551/mrglgagh-de-barracuda)), comida [Festín copioso de Suramar](http://es.wowhead.com/item=133579/festin-copioso-de-suramar) (recetas [Rank 1](https://es.wowhead.com/spell=201516/festín-copioso-de-suramar), [Rank 2](https://es.wowhead.com/spell=201543/festín-copioso-de-suramar), [Rank 3](https://es.wowhead.com/spell=201563/festín-copioso-de-suramar))
[Caballa plateada](http://es.wowhead.com/item=133607/caballa-plateada) | comida [Plato de pescado rebozado con semillas](http://es.wowhead.com/item=133573/plato-de-pescado-rebozado-con-semillas) (recetas [Rank 1](https://es.wowhead.com/spell=201508/plato-de-pescado-rebozado-con-semillas), [Rank 2](https://es.wowhead.com/spell=201537/plato-de-pescado-rebozado-con-semillas), [Rank 3](https://es.wowhead.com/spell=201557/plato-de-pescado-rebozado-con-semillas)), comida [Tiras de caballa seca](http://es.wowhead.com/item=133575/tiras-de-caballa-seca)  (recetas [Rank 2](https://es.wowhead.com/spell=201539/tiras-de-caballa-seca), [Rank 3](https://es.wowhead.com/spell=201559/tiras-de-caballa-seca))
[Costillas grandes de sabor fuerte](http://es.wowhead.com/item=124119/costillas-grandes-de-sabor-fuerte) | comida [Magister hambriento](http://es.wowhead.com/item=133570/magister-hambriento) (recetas [Rank 1](https://es.wowhead.com/spell=201505/magister-hambriento), [Rank 2](https://es.wowhead.com/spell=201534/magister-hambriento), [Rank 3](https://es.wowhead.com/spell=201554/magister-hambriento)), comida [Costillas a la barbacoa Ley](http://es.wowhead.com/item=133565/costillas-a-la-barbacoa-ley) (recetas [Rank 2](https://es.wowhead.com/spell=201529/costillas-a-la-barbacoa-ley), [Rank 3](https://es.wowhead.com/spell=201549/costillas-a-la-barbacoa-ley)), comida [Asado de costilla especiado](http://es.wowhead.com/item=133564/asado-de-costilla-especiado) (recetas [Rank 2](https://es.wowhead.com/spell=201528/asado-de-costilla-especiado), [Rank 3](https://es.wowhead.com/spell=201548/asado-de-costilla-especiado)), comida [Festín suculento](http://es.wowhead.com/item=133578/festin-suculento) (recetas [Rank 2](https://es.wowhead.com/spell=201542/festín-suculento), [Rank 3](https://es.wowhead.com/spell=201562/festín-suculento)), comida [Festín copioso de Suramar](http://es.wowhead.com/item=133579/festin-copioso-de-suramar) (recetas [Rank 1](https://es.wowhead.com/spell=201516/festín-copioso-de-suramar), [Rank 2](https://es.wowhead.com/spell=201543/festín-copioso-de-suramar), [Rank 3](https://es.wowhead.com/spell=201563/festín-copioso-de-suramar))
[Tajada de beicon](http://es.wowhead.com/item=133680/tajada-de-beicon) | comida [Beicon crujiente](http://es.wowhead.com/item=133681/beicon-crujiente) (recetas [Rank 1](https://es.wowhead.com/spell=201683/beicon-crujiente), [Rank 2](https://es.wowhead.com/spell=201684/beicon-crujiente), [Rank 3](https://es.wowhead.com/spell=201685/beicon-crujiente)), comida [Festín suculento](http://es.wowhead.com/item=133578/festin-suculento) (recetas [Rank 2](https://es.wowhead.com/spell=201542/festín-suculento), [Rank 3](https://es.wowhead.com/spell=201562/festín-suculento)), comida [Festín copioso de Suramar](http://es.wowhead.com/item=133579/festin-copioso-de-suramar) (recetas [Rank 1](https://es.wowhead.com/spell=201516/festín-copioso-de-suramar), [Rank 2](https://es.wowhead.com/spell=201543/festín-copioso-de-suramar), [Rank 3](https://es.wowhead.com/spell=201563/festín-copioso-de-suramar))

</body>
</html>

</body>
</html>

**Comment by Noahkrr** [comment]
aqui un ejemplo:
![image](https://user-images.githubusercontent.com/81131460/153463600-caebf0e3-916b-4a47-bfee-b1959069491a.png)

**Comment by ShikoSCS** [comment]
Calibrate NOMI Work Orders:

All Research recipes drop:
-- Badly Burnt Food (50%)
-- Slightly Burnt Food (35%)
-- Prepared Ingredients (5%)
-- Nomi Snacks (5%)
-- Broken Isles Recipe Scrap (5%)

Research recipes using Lean Shanks:
-- Salt & Pepper Shank (60%)
-- Salt and Pepper Shank 2 (2%)
-- Salt and Pepper Shank 3 (1%)
-- Suramar Surf and Turf: Rank 2 (1%)
-- Suramar Surf and Turf: Rank 3 (0.5%)
-- Hearty Feast: Rank 1 (1.5%)
-- Hearty Feast: Rank 2 (1%)
-- Hearty Feast: Rank 3 (0.5%)
-- Azshari Salad: Rank 1 (1.5%)
-- Azshari Salad: Rank 2 (1%)
-- Azshari Salad: Rank 3 (0.5%)

Research recipes using Wildfowl Eggs:
-- Faronaar Fizz (60%)
-- Faronaar Fizz Shank 2 (2%)
-- Faronaar Fizz Shank 3 (1%)
-- Hearty Feast: Rank 1 (1.5%)
-- Hearty Feast: Rank 2 (1%)
-- Hearty Feast: Rank 3 (0.5%)
-- Nightborne Delicacy Platter: Rank 1 (1.5%)
-- Nightborne Delicacy Platter: Rank 2 (1%)
-- Nightborne Delicacy Platter: Rank 3 (0.5%)

Research recipes using Big Gamy Ribs:
-- Spiced Rib Roast (60%)
-- Leybeque Ribs Rank 2 (2%)
-- Leybeque Ribs Rank 3 (1%)
-- Spiced Rib Roast Rank 2 (2%)
-- Spiced Rib Roast Rank 3 (1%)
-- Hearty Feast: Rank 1 (1.5%)
-- Hearty Feast: Rank 2 (1%)
-- Hearty Feast: Rank 3 (0.5%)
-- The Hungry Magister: Rank 1 (1.5%)
-- The Hungry Magister: Rank 2 (1%)
-- The Hungry Magister: Rank 3 (0.5%)
-- Lavish Suramar Feast: Rank 1 (1.5%)
-- Lavish Suramar Feast: Rank 2 (1%)
-- Lavish Suramar Feast: Rank 3 (0.5%)

Research recipes using Fatty Bearsteaks:
-- Bear Tartare (60%)
-- Bear Tartare Rank 2 (2%)
-- Bear Tartare Rank 3 (1%)
-- The Hungry Magister: Rank 1 (1.5%)
-- The Hungry Magister: Rank 2 (1%)
-- The Hungry Magister: Rank 3 (0.5%)

Research recipes using Leyblood:
-- Leybeque Ribs (60%)
-- Leybeque Ribs Rank 2 (2%)
-- Leybeque Ribs Rank 3 (1%)
-- Barracuda Mrglgagh 2 (2%)
-- Barracuda Mrglgagh 3 (1%)
-- Nightborne Delicacy Platter: Rank 1 (1.5%)
-- Nightborne Delicacy Platter: Rank 2 (1%)
-- Nightborne Delicacy Platter: Rank 3 (0.5%)
-- The Hungry Magister: Rank 1 (1.5%)
-- The Hungry Magister: Rank 2 (1%)
-- The Hungry Magister: Rank 3 (0.5%)
-- Lavish Suramar Feast: Rank 1 (1.5%)
-- Lavish Suramar Feast: Rank 2 (1%)
-- Lavish Suramar Feast: Rank 3 (0.5%)

Research recipes using Cursed Queenfish:
-- Fighter Chow (60%)
-- Fighter Chow Rank 2 (2%)
-- Fighter Chow Rank 3 (1%)
-- Fishbrul Special: Rank 1 (1.5%)
-- Fishbrul Special: Rank 2 (1%)
-- Fishbrul Special: Rank 3 (0.5%)
-- Nightborne Delicacy Platter: Rank 1 (1.5%)
-- Nightborne Delicacy Platter: Rank 2 (1%)
-- Nightborne Delicacy Platter: Rank 3 (0.5%)
-- Lavish Suramar Feast: Rank 1 (1.5%)
-- Lavish Suramar Feast: Rank 2 (1%)
-- Lavish Suramar Feast: Rank 3 (0.5%)

Research recipes using Mossgill Perch:
-- Deep-Fried Mossgill (60%)
-- Deep-Fried Mossgill 2 (2%)
-- Deep-Fried Mossgill 3 (1%)
-- Hearty Feast: Rank 1 (1.5%)
-- Hearty Feast: Rank 2 (1%)
-- Hearty Feast: Rank 3 (0.5%)
-- Fishbrul Special: Rank 1 (1.5%)
-- Fishbrul Special: Rank 2 (1%)
-- Fishbrul Special: Rank 3 (0.5%)
-- Lavish Suramar Feast: Rank 1 (1.5%)
-- Lavish Suramar Feast: Rank 2 (1%)
-- Lavish Suramar Feast: Rank 3 (0.5%)

Research recipes using Highmountain Salmon:
-- Drogbar-Style Salmon (60%)
-- Drogbar-Style Salmon Rank 2 (2%)
-- Drogbar-Style Salmon Rank 3 (1%)
-- Fishbrul Special: Rank 1 (1.5%)
-- Fishbrul Special: Rank 2 (1%)
-- Fishbrul Special: Rank 3 (0.5%)
-- Lavish Suramar Feast: Rank 1 (1.5%)
-- Lavish Suramar Feast: Rank 2 (1%)
-- Lavish Suramar Feast: Rank 3 (0.5%)

Research recipes using Stormrays:
-- Koi-Scented Stormray (60%)
-- Koi-Scented Stormray Rank 2 (2%)
-- Koi-Scented Stormray Rank 3 (1%)
-- Suramar Surf and Turf: Rank 2 (1%)
-- Suramar Surf and Turf: Rank 3 (0.5%)
-- Seed-Battered Fish Plate: Rank 1 (1.5%)
-- Seed-Battered Fish Plate: Rank 2 (1%)
-- Seed-Battered Fish Plate: Rank 3 (0.5%)
-- Lavish Suramar Feast: Rank 1 (1.5%)
-- Lavish Suramar Feast: Rank 2 (1%)
-- Lavish Suramar Feast: Rank 3 (0.5%)

Research recipes using Runescale Koi:
-- Koi-Scented Stormray (60%)
-- Koi-Scented Stormray Rank 2 (2%)
-- Koi-Scented Stormray Rank 3 (1%)
-- Suramar Surf and Turf: Rank 2 (1%)
-- Suramar Surf and Turf: Rank 3 (0.5%)
-- Azshari Salad: Rank 1 (1.5%)
-- Azshari Salad: Rank 2 (1%)
-- Azshari Salad: Rank 3 (0.5%)
-- Seed-Battered Fish Plate: Rank 1 (1.5%)
-- Seed-Battered Fish Plate: Rank 2 (1%)
-- Seed-Battered Fish Plate: Rank 3 (0.5%)
-- Lavish Suramar Feast: Rank 1 (1.5%)
-- Lavish Suramar Feast: Rank 2 (1%)
-- Lavish Suramar Feast: Rank 3 (0.5%)

Research recipes using Black Barracuda:
-- Barracuda Mrglgagh (60%)
-- Barracuda Mrglgagh Rank 2 (2%)
-- Barracuda Mrglgagh Rank 3 (1%)
-- Lavish Suramar Feast: Rank 1 (1.5%)
-- Lavish Suramar Feast: Rank 2 (1%)
-- Lavish Suramar Feast: Rank 3 (0.5%)
-- Fishbrul Special: Rank 1 (1.5%)
-- Fishbrul Special: Rank 2 (1%)
-- Fishbrul Special: Rank 3 (0.5%)
-- Nightborne Delicacy Platter: Rank 1 (1.5%)
-- Nightborne Delicacy Platter: Rank 2 (1%)
-- Nightborne Delicacy Platter: Rank 3 (0.5%)

Research recipes using Slabs of Bacon:
-- Crispy Bacon (60%)
-- Crispy Bacon Rank 1 (5%)
-- Crispy Bacon Rank 2 (2%)
-- Crispy Bacon Rank 3 (1%)
-- Lavish Suramar Feast: Rank 1 (1.5%)
-- Lavish Suramar Feast: Rank 2 (1%)
-- Lavish Suramar Feast: Rank 3 (0.5%)
-- Hearty Feast: Rank 1 (1.5%)
-- Hearty Feast: Rank 2 (1%)
-- Hearty Feast: Rank 3 (0.5%)

Research recipes using Silver Mackerel:
-- Dried Mackerel Strips (60%)
-- Dried Mackerel Strips 3 (1%)
-- Seed-Battered Fish Plate: Rank 1 (1.5%)
-- Seed-Battered Fish Plate: Rank 2 (1%)
-- Seed-Battered Fish Plate: Rank 3 (0.5%)

**Comment by ShikoSCS** [comment]
Queda pendiente la posibilidad de realizar varias investigaciones al mismo tiempo

**Comment by ShikoSCS** [comment]
Corregido lo pendiente
