### ISSUE TITLE
Cant pick up work order

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3658]
**Links:**
https://www.wowhead.com/npc=103760/ariana-fireheart
https://www.wowhead.com/npc=103025/battlelord-gaardoun
from WoWHead or our Armory

**What is happening:**
It says i have completed an illidari and an ashtongue work order but the flag is not clickable
![image](https://user-images.githubusercontent.com/84509345/152969336-a587f265-5d0a-4110-b492-5c4cfe4b06d8.png)
![image](https://user-images.githubusercontent.com/84509345/152970057-1d5dd794-83d5-4e8e-8d28-f1bb1402c067.png)

**What should happen:**
Let me have them

**Comment by ShikoSCS** [comment]
A repair was made, please report it if the problem persists.
