### ISSUE TITLE
Nomi - cooking work order

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3662]
**Links:**

https://www.wowhead.com/npc=101846/nomi

**What is happening:**

1. Currently, the work order table doesn't interact when you click on in.
2. Completing Work orders doesn't grant level 2 recipes, only lvl 3. IT should give both.
3.  I can't find any reference info about it, but originaly, the work order worked the way, that you had 10-15 work orders to place, and you could chose how many orders you put in each food option. NOW, it only lets you put 1 order in one food option. (hope that makes sense)

**What should happen:**

**Comment by ShikoSCS** [comment]
A repair was made, please report it if the problem persists.
