### ISSUE TITLE
long forgotten hippogryph

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#3663]
**Links:**
https://www.wowhead.com/item=138258/reins-of-the-long-forgotten-hippogryph
https://www.wowhead.com/object=251168/ephemeral-crystal
https://www.wowhead.com/spell=215316/crystal-dummy-aura-1
**What is happening:**

crystals are the but when you click on them they dont give the buff personally farmed them and collected 7 (5 should give you the mount) its not a visual bug the mount does not drop 

**What should happen:**
there are crystal called : ephemeral-crystal that should give a buff called : Crystal Dummy Aura 1 - 5
after you got the buff to 5 a mount called long forgotten hippogryph will drop into to you bag ( soulbound)

**Comment by jlspwsn** [comment]
I have completed this achievement. During the time it takes to find the click crystal, it will not give you a count. until you click on the requested quantity. Will automatically put the mount into the backpack. (don't die)
