### ISSUE TITLE
Mazmorra Torreon Grajo Negro - Spell - Pedrusco machacador

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3669]
**Links:**

from WoWHead or our Armory

**What is happening:**
las rocas (https://www.wowhead.com/spell=222397/boulder-crush) de la mazmorra torreon Grajo negro, no aturde ni te lni derriba. no esta funcionando el spell

**What should happen:**
 el spell de la roca Pedrusco machacador(https://www.wowhead.com/spell=222397/boulder-crush) también aturde y derriba al jugador afectado, asegurando prácticamente que un jugador golpeado por una roca será golpeado por otra.

**Comment by ShikoSCS** [comment]
Fixed

**Comment by Noahkrr** [comment]
Las rocas que caen en las escaleras siguen sin funcionar,  la roca no te aturde (al tocarte se supone que el spell debe activarse , empujándolo y aturdiendo al jugador) y traspasa al jugador..
