### ISSUE TITLE
NPC - Thaumaturge Vashreen - In patch 7.2

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3670]
**Links:**

from WoWHead or our Armory

**What is happening:**
In patch 7.2, the NPC returned to the game as a Forsaken Token vendor at the Deliverance Point on the Broken Shore (the npc moved to another area and his items were removed
). In 7.3 travel to Argus aboard the Vindicaar, trading for [Veiled Argunite] (the npc is currently on Argus selling new items
).

**What should happen:**
currently the client is 7.3, which moving the npc zone is impossible. the solution would be to create a custom npc that sells all the items that the npc Thaumaturge Vashreen sold in patch 7.2

[Relinquished tokens](https://www.wowhead.com/items/name:relinquished?filter=na=relinquished) are ONLY available from [Thaumaturge Vashreen](https://www.wowhead.com/npc=121589/thaumaturge-vashreen) at [[44.4, 62.2] (Deliverance Point)](https://www.wowhead.com/npc=121589#map) on the Broken Shore. Each token costs 5,000 [ Nethershard](https://www.wowhead.com/currency=1226/nethershard)s each.
Below is some further information regarding these items:
Tokens are available for all slots except weapons (Including [ Relinquished Relic](https://www.wowhead.com/item=147837/relinquished-relic)!)
Each token will yield a base item level 880 piece of gear that is spec-appropriate.
Relinquished tokens CAN yield Tier 19 gear.
Relinquished tokens have a rare chance to yield a legendary item for the appropriate slot
The items yielded can Warforge/Titanforge to anywhere from 885 to 925, and can proc a socket or additional tertiary stats.

<html>
<body>

Item | Cost | Type
-- | -- | --
[Relinquished Relic](https://www.wowdb.com/items/147837-relinquished-relic) | 5000 | Relic
[Relinquished Trinket](https://www.wowdb.com/items/147801-relinquished-trinket) | 5000 | Trinket
[Relinquished Hood](https://www.wowdb.com/items/147796-relinquished-hood) | 5000 | Head
[Relinquished Chestguard](https://www.wowdb.com/items/147793-relinquished-chestguard) | 5000 | Chest
[Relinquished Leggings](https://www.wowdb.com/items/147797-relinquished-leggings) | 5000 | Legs
[Relinquished Gauntlets](https://www.wowdb.com/items/147795-relinquished-gauntlets) | 5000 | Hands
[Relinquished Spaulders](https://www.wowdb.com/items/147800-relinquished-spaulders) | 5000 | Shoulder
[Relinquished Girdle](https://www.wowdb.com/items/147791-relinquished-girdle) | 5000 | Waist
[Relinquished Treads](https://www.wowdb.com/items/147792-relinquished-treads) | 5000 | Feet
[Relinquished Bracers](https://www.wowdb.com/items/147786-relinquished-bracers) | 5000 | Wrist
[Relinquished Cloak](https://www.wowdb.com/items/147794-relinquished-cloak) | 5000 | Back
[Relinquished Necklace](https://www.wowdb.com/items/147798-relinquished-necklace) | 5000 | Neck
[Relinquished Ring](https://www.wowdb.com/items/147799-relinquished-ring) | 5000 | Finger

</body>
</html>

more information click [here](https://wowpedia.fandom.com/wiki/Thaumaturge_Vashreen).

**Comment by Cefiro-Caecias** [comment]
Muy buen post. Y muy bien documentado, aunque no sé para qué me los escribes en inglés.
Pedido concedido. Disponible mañana en el próximo update.
