### ISSUE TITLE
Class hall troops cannot be picked up.

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3672]
**Links:**

https://www.wowhead.com/legion-class-hall-mission-guide#troops

**What is happening:**

This report refers to Demon Hunter class hall. I can't confirm if this bug is present in other class halls.

1. [Training Troops](https://www.wowhead.com/object=250913/training-troops) object cannot be picked up to collect your troops.

In the main window it says "work order ready for pickup", but in the right corner of the screen, the tooltip of the objct says: 
![image](https://user-images.githubusercontent.com/63166930/154247443-bce9bca0-2cc0-41e9-a52b-f51f030c2177.png)

![image](https://user-images.githubusercontent.com/63166930/154245592-f54ecd43-6462-4c2b-a37d-74a8fc822db9.png)

**What should happen:**

**Comment by ShikoSCS** [comment]
A repair was made, please report it if the problem persists.
