### ISSUE TITLE
Pillar of creation quest

### ISSUE THREAD

**Issue by IcicleUBW** [GuabinaCore/WoWKoi#3674]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=46253/pillars-of-creation#comments
**What is happening:**
Quest does not complete any objectives after killing bosses / interacting with the q item.

**What should happen:**
After killing boss everyone in the boss room should get the quest progress.

**Comment by Noahkrr** [comment]
[The Hammer](https://www.wowhead.com/npc=120408/hammer-of-khazgoroth) appears in the center of the room after Demonic Inquisition ([Atrigan](https://www.wowhead.com/npc=120996/atrigan)+[Belac](https://www.wowhead.com/npc=116691/belac)) is defeated. First boss of Tomb of Sargeras LFR Wing 2 (Wailing Halls).
[The Tidestone](https://www.wowhead.com/npc=120406/tidestone-of-golganneth) appears on the dias after [Mistress Sassz'ine](https://www.wowhead.com/npc=115767/mistress-sasszine) is defeated. Final boss of Tomb's LFR Wing 1 (The Gates of Hell).
[The Tears of Elune](https://www.wowhead.com/npc=120407/tears-of-elune) appear in the center of the room after [The Desolate Host](https://www.wowhead.com/npc=119072/the-desolate-host) is defeated. Final boss of Tomb's LFR Wing 2 (Wailing Halls).

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
