### ISSUE TITLE
bonus objective 

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#3679]
**Links:**

when you are lvl 100-110 you have some would quests in form of a bonus objective which gives a chunk of xp and gold usually (40-45k each ) the objectives  will appear on your map like a standard world quest but when you fly there (or just walk there) although you can see your objectives in your quest log by killing the mobs in the area you don't get any progress towards completion of the quest

**Comment by ventarius5** [comment]
I bet it's a core bug, so a list wont really be needed, but anyways...

![obraz](https://user-images.githubusercontent.com/63166930/154795028-56531471-a762-40e0-8b8c-7aad035a75c6.png)
