### ISSUE TITLE
The Nighthold - Krosus - Chest

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3681]
**Links:**
https://www.wowhead.com/object=248513/felbound-chest
from WoWHead or our Armory

**What is happening:**
Killing Krosus does not spawn his loot chest.

**What should happen:**
killing krosus should spawn his chest
![image](https://user-images.githubusercontent.com/81131460/154878412-2c7a2b15-7c3f-458a-9969-a9e0f45cecd4.png)

**Comment by ShikoSCS** [comment]
Fixed
