### ISSUE TITLE
KOI Coins 

### ISSUE THREAD

**Issue by Kprtn** [GuabinaCore/WoWKoi#3682]
**Links:**

from WoWHead or our Armory
Usé los KOI talents para crear las monedas, cliqué  las monedas para conseguir los puntos de tienda, cerré el juego, borré caché, al entrar de  nuevo y abrir la tienda me dice que solo tengo 2 puntos

**What is happening:**
![WoWScrnShot_021922_013417](https://user-images.githubusercontent.com/96433337/154956980-7fa0cceb-bd9b-4140-8f85-3421c89fcd70.jpg)

![WoWScrnShot_021922_013409](https://user-images.githubusercontent.com/96433337/154957019-afc92e75-31b0-4e85-8708-82f2c50bf019.jpg)

**What should happen:**

**Comment by Kprtn** [comment]
Ha de ser algún bug "visual", en  la página web si refleja la cantidad de puntos correcta. Estaré atento :)

**Comment by ShikoSCS** [comment]
Si, es un bug visual, en breve haremos una reparación que va a corregir este error
