### ISSUE TITLE
Nomi cooking research

### ISSUE THREAD

**Issue by IcicleUBW** [GuabinaCore/WoWKoi#3693]
**Links:**

from WoWHead or our Armory

[**What is happening:**](https://www.wowhead.com/legion-cooking-guide#new-food)
![image](https://user-images.githubusercontent.com/97225139/155786777-5a02f04b-054c-4f9a-a1e2-bb3466da5656.png)

Nomi cooking research gives higer recipes 2-3 stars instead of giving them in orer from 1 till 3.

**What should happen:**

**Comment by ShikoSCS** [comment]
Corrected, in case of detecting another problem, notify us.
