### ISSUE TITLE
Nomi Snacks

### ISSUE THREAD

**Issue by IcicleUBW** [GuabinaCore/WoWKoi#3694]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/item=151133/nomi-snacks#comments
**What is happening:**
![image](https://user-images.githubusercontent.com/97225139/155843210-50d13f56-d6f3-4d1e-9bf1-880f61d3da58.png)

Nomi snacks cant be used in any place or state next to nomi.
According to the comments we are supposed to click on the table -> table is not targetable , snacks are not useable 

1. You need to have at least 5 work orders in process with Nomi.
2. Click on the Nomi Snacks.
3. Click on work order table and you will get whatever 5 items he figures to give you (yes, the RNG gods odd sense of humor is very active in this so you could end up with recipes or fish, or junk).

**What should happen:**

**Comment by ShikoSCS** [comment]
Corrected, in case of detecting another problem, we would appreciate it if you could notify us.
