### ISSUE TITLE
World Quest - Withered Army Training

### ISSUE THREAD

**Issue by Nhavi** [GuabinaCore/WoWKoi#3699]
**Withered Army Training World Quest**

**Links**

https://www.wowhead.com/quest=43943/withered-army-training
https://www.wowhead.com/comprehensive-suramar-guide#withered-army-training

**What is happening:**

After finishing the world quest by talking to npc I am getting only reputation (in lower amount that normally) and **scenario is not starting.**

lower reputation reward proof:
https://imgur.com/a/6n0Jc04
Tested npc by giving 400 mana and later 900 mana. No scenario both times.

**What should happen:**

1. After talking with npc a scenario should start. Finishing scenario grants reward-chest (look comprehensive-suramar-guide in links).
2. World Quest grants 150 Nightfallen reputation.

**Comment by Likander** [comment]
This is happening to me too still
