### ISSUE TITLE
Three Is a Lucky Number quest

### ISSUE THREAD

**Issue by IcicleUBW** [GuabinaCore/WoWKoi#3700]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=42959/three-is-a-lucky-number
**What is happening:**
![image](https://user-images.githubusercontent.com/97225139/155899142-42727900-c975-4122-a295-5bb30d22af83.png)

The quest items are not dropping from any boss on any difficulty.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
