### ISSUE TITLE
Demon hunter class hall quest: Vault of the Wardens: Vault Break-In

### ISSUE THREAD

**Issue by Orika96** [GuabinaCore/WoWKoi#3701]
Hi!

https://www.wowhead.com/quest=42752/vault-of-the-wardens-vault-break-in

This is a dh quest in Vault of Wardens, the last boss Cordana should drop the quest item called: Sargerite Keystone. I killed and my guildmate killed the boss several times, but the item is not dropped. The chance should be 100%.

Need check for this q.

Thank you!

Ori

**Comment by Cefiro-Caecias** [comment]
Fixed.
