### ISSUE TITLE
[NPC] Leutenant Surtees untargetable - Fate of the Queen's Reprisal Quest

### ISSUE THREAD

**Issue by bastian-brito** [GuabinaCore/WoWKoi#3705]
**Links:**
https://www.wowhead.com/quest=40794/fate-of-the-queens-reprisal
https://www.wowhead.com/npc=106930/lieutenant-surtees
from WoWHead or our Armory

**What is happening:**

NPC is invisible and untargetable, but his weapons and [?] icon are visible, can't finish quest.

![imagen](https://user-images.githubusercontent.com/72405110/156792731-48337c46-5782-4cc8-b3f5-204e716a514e.png)
**What should happen:**

NPC should be visible and targetable, in order to finish the quest
![imagen](https://user-images.githubusercontent.com/72405110/156793107-75fe67f9-a61a-4796-8c91-7ba304014641.png)

**Comment by Cefiro-Caecias** [comment]
Fixed now, and available ^^

**Comment by bastian-brito** [comment]
Thanks!!
