### ISSUE TITLE
Problemas con los objetos de Campeones

### ISSUE THREAD

**Issue by PiR4T496** [GuabinaCore/WoWKoi#3706]
**Links:**
https://ibb.co/DfP236G
https://ibb.co/f0s2c0r
https://ibb.co/Fg5y1HH
https://ibb.co/tmjhd97
from WoWHead or our Armory

**What is happening:**
Tal como se ve en la imagen , Los objetos de campeon medan un 55% mas de ratio de probabilidad de exito en la mision , pero cuando vez la mision aparece 26% , como si los objetos estuviesen inutilizados , porque el 26% era la probabilidad base sin los objetos . 
 La mision duraba 2 Dias .

**What should happen:**
La probabilidad de exito de la Mision deberia ser de 81%

**Comment by Noahkrr** [comment]
en una misión de nivel alto, enviar campeones de nivel bajo siempre fracasara por mas que le otorgues buffos de porcentaje de éxito.

**Comment by Noahkrr** [comment]
creo que ya encontré el problema, no son los items, parece que algunos spell (spell pasivos que aumenta el exito en las misiones y de reducción de tiempo) del campeon no parecen funcionar correctamente..
