### ISSUE TITLE
Nighthold - Gul'dan Heroic 

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3710]
**Links:**

[**from WoWHead or our Armory**](https://www.wowhead.com/spell=211152/empowered-eye-of-guldan?dd=15&ddsize=30)

**What is happening:**

Empowered Eye of Gul'dan attacking out of 8yrd range and doin duble size of dmg

**What should happen:**

**Comment by Travven** [comment]
I check the range of the spell and can be casted in 100yrd and the range of the aoe is ok too.

**Comment by Cefiro-Caecias** [comment]
Fixed by Travven.
