### ISSUE TITLE
Wrong Ilvl on Boss Maleficus items 

### ISSUE THREAD

**Issue by PiR4T496** [GuabinaCore/WoWKoi#3712]
**Links:**
https://ibb.co/V2KN63w
https://ibb.co/qWvcR36
from WoWHead or our Armory

**What is happening:**
Wrong ilvl on items dropped by Maleficus

**What should happen:**
Ilvl of the objects should be 900+

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.

**Comment by PiR4T496** [comment]
El problema persiste a pesar del cambio, aqui una prueba de ello .
https://ibb.co/bvpkvQM
https://ibb.co/cLpW3KX
