### ISSUE TITLE
Items - Objetivos de misiones en Mazmorras

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3715]
**Links:**

from WoWHead or our Armory

**What is happening:**
1) https://www.wowhead.com/quest=43524/court-of-stars-literary-perfection
no se abrir el libro(https://www.wowhead.com/object=252410/scrolls-sigils-and-the-nightborne-way) no se obtiene nada y el libro desaparece. deberia obtenerse este item(https://www.wowhead.com/item=139782/wards-sigils-and-the-nightborne-way)

2) https://www.wowhead.com/quest=43525/vault-of-the-wardens-borrowing-without-asking
al matar a cordana nos cuenta credito, al subir a la asensor y abrir el cristal(https://www.wowhead.com/object=252443/containment-crystal) no genera nada. deberia generar el item(https://www.wowhead.com/item=139788/containment-crystal) de mision
video: https://www.youtube.com/watch?time_continue=170&v=6d0_jLI9rZQ&feature=emb_logo

3) https://www.wowhead.com/quest=40882/court-of-stars-revamping-the-recoil
este item(https://www.wowhead.com/item=133806/arcanic-compressor) cae al matar el jefe Capitan de patrullero Gerdo, funciona bien, pero este item cae sin tener la mision y la profesion. para obtener el item  necesitamos la profesion de ingenieria. y la mision.

4) https://www.wowhead.com/quest=42654/darkheart-thicket-nightmare-oak
Al matar corazon de roble otorga este item(https://www.wowhead.com/item=138270/nightmare-oak), puede ser obtenido en sus 3 dificultades de la mazmorra. sugiero que le suban el porcentaje de drop a 40 o 50%.

**Comment by Noahkrr** [comment]
5) https://www.wowhead.com/quest=43521/the-emerald-nightmare-essence-of-power
hice la banda, no obtuve ninguna esencia(https://www.wowhead.com/quest=43521/the-emerald-nightmare-essence-of-power) de los 7 jefes. deberia recibir 1 o 2 esencias por jefe o recibir Esencia furiosa(https://www.wowhead.com/item=139771/seething-essence) que contiene 5 esencias de cada jefe (porcentaje bajo)

6) https://www.wowhead.com/quest=43520/the-emerald-nightmare-in-nightmares
no se logra obtener el item (https://www.wowhead.com/item=139671/deathglare-iris) , solo obtuve el cuerno, deberia obtener los dos items

**Comment by Cefiro-Caecias** [comment]
1, 2 3 y 4 reparadas, y disponibles en el próximo update.

5 y 6, en revisión, estoy hablando con Shiko sobre ellas.
