### ISSUE TITLE
Maw of Souls: Retrieving the Svalnguard

### ISSUE THREAD

**Issue by armirmoazezi** [GuabinaCore/WoWKoi#3716]
**Links:**
https://www.wowhead.com/quest=40613/maw-of-souls-retrieving-the-svalnguard 
https://www.wowhead.com/item=132440/the-svalnguard
**What is happening:**
there is a object under the ship should drop the item called " The Svalnguard" but it does not

**Comment by Cefiro-Caecias** [comment]
Fixed.
