### ISSUE TITLE
Catedral de la Noche Eterna - Objetos de misión - NPC

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3719]
**Links:**

from WoWHead or our Armory

**What is happening:**
1) https://www.wowhead.com/item=137677/fel-blood
estos items de mision caen de los adds([Helblaze Felbringer](https://www.wowhead.com/npc=118724/helblaze-felbringer), [Wyrmtongue Scavenger](https://www.wowhead.com/npc=118719/wyrmtongue-scavenger), [Helblaze Imp](https://www.wowhead.com/npc=118717/helblaze-imp)) de la mazmorra Catedral de la Noche Eterna, no dberia recibir ningun item de mision, porque no tengo mision alguna. 
esta item de mision pertenecen a estas misiones:
https://www.wowhead.com/quest=43468/blood-for-the-wolfe (necesito ser Picaro)
https://www.wowhead.com/quest=45146/runic-reading (necesito ser Paladin)
https://www.wowhead.com/quest=37447/the-blood-of-demons (necesito ser Cazador de demonios)

2) https://www.wowhead.com/npc=118716/bilespray-lasher
al matar este npc, obtuve item(https://www.wowhead.com/item=129117/aethril-sample) y tambien obtuve este item (https://www.wowhead.com/item=129140/jeweled-spade-handle), no deberia recibir items de profesion porque no tengo la profesión de herbolesteria. 

3) www.wowhead.com/object=269939/legion-cache
al abrir el cofre no se obtiene nada. deberia haber items

**Comment by Cefiro-Caecias** [comment]
Reparados. Disponibles en el próximo update.
