### ISSUE TITLE
[Core] - Warrior Skills aren't doing as much damage as they should

### ISSUE THREAD

**Issue by Frosty015** [GuabinaCore/WoWKoi#372]
**Links:** [Combat logs](https://imgur.com/a/dxMokSn)

[Rampage](https://www.wowhead.com/spell=184367/rampage)
[Execute](https://www.wowhead.com/spell=5308/execute)
[Bloodthirst](https://www.wowhead.com/spell=23881/bloodthirst)
[Furious Slash](https://www.wowhead.com/spell=100130/furious-slash)
[Whirlwind](https://www.wowhead.com/spell=1680/whirlwind)
[Charge](https://www.wowhead.com/spell=100/charge)
[Heroic Throw](https://www.wowhead.com/spell=57755/heroic-throw)
[Heroic Leap](https://www.wowhead.com/spell=6544/heroic-leap)
[Raging Blow](https://www.wowhead.com/spell=85288/raging-blow)

**What is happening:** According to my skills, for example with raging blow I should be doing about 684 Physical damage, but according to my combat logs the damage I deal is much lower. 

_**Skills with issues:**_ _Rampage
Execute
Bloodthirst
Furious Slash
Whirlwind
Charge
Heroic Throw
Heroic Leap
Raging Blow_

**What should happen:** Skill damage should be adjusted to do the proper amount of damage

**Comment by Arkanheal** [comment]
You took armor into account? (but it's true your damage seem sort of low)

**Comment by Frosty015** [comment]
> 
> 
> You took armor into account? (but it's true your damage seem sort of low)

Unfortunately I wasn't able to test them on dummies, although I remember reading on the discord chat that damage numbers are normal on the dummies only, but unusually low against mobs, may be due to a scaling issue. 


Nonetheless, if you look at the screenshots, for example the first one I should be doing around 684 damage with raging blow, granted armor may reduce that but my damage is now reduced to a total of 124 which is less than even half of the damage I should be doing. From my understanding my damage should be somewhat close to the amount displayed on the tooltip

**Comment by yo931** [comment]
I noticed this on my level 1 too, tooltip says I deal 45 damage with shadowbolt but only shows as 4 when the spell hits. But when I hover over the hp of the level 1 mob (300 hp) it still goes down to 257 (43 damage). So seems to be a scaling/display thing for sure.
