### ISSUE TITLE
Items y Misiones - Botin de mazmorras

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3720]
**Links:**

from WoWHead or our Armory

**What is happening:**
recomendación: aumentar el porcentaje de caída de todos al 100% (solo items de misiones)

1) https://www.wowhead.com/quest=40613/maw-of-souls-retrieving-the-svalnguard
el escudo(https://www.wowhead.com/item=132440/the-svalnguard) si aparece pero al abrir no contiene nada y desaparece, deberia funcionar asi: al abrir el escudo debería otorgar (https://www.wowhead.com/object=245849/the-svalnguard) y todos los mienbros del grupo que tengan la mision deben dropear el item.

2) https://www.wowhead.com/quest=42752/vault-of-the-wardens-vault-break-in  (mision de DH)
Al matar a [Cordana Felsong](https://www.wowhead.com/npc=95888/cordana-felsong) deberia dropear este item [Sargerite Keystone](https://www.wowhead.com/item=138397/sargerite-keystone)

3) https://www.wowhead.com/quest=43558/bindings-of-the-windlord (mision de picaro)
al matar a [Ceniz'golm](https://es.wowhead.com/npc=95886/cenizgolm) deberia obtener este item [Bindings of the Windlord](https://www.wowhead.com/item=139468/bindings-of-the-windlord) y al matar a [Dargrul](https://www.wowhead.com/npc=91007/dargrul) debería obtener [Bindings of the Windlord](https://www.wowhead.com/item=139466/bindings-of-the-windlord)

4) https://www.wowhead.com/quest=43572/darkheart-thicket-the-nightmare-lash (mision de DK)
Al matar a [Shade of Xavius](https://www.wowhead.com/npc=99192/shade-of-xavius) obtenermos [Nightmare Lash](https://www.wowhead.com/item=139538/nightmare-lash)

5) https://www.wowhead.com/quest=44286/vault-of-the-wardens-a-masterpiece-of-flesh (mision de DK)
la mision pide obtener 3 items.
1er item [Beating Fel Heart](https://www.wowhead.com/item=141307/beating-fel-heart)) se dropea de [Inquisitor Tormentorum](https://www.wowhead.com/npc=96015/inquisitor-tormentorum)
2do item [Demonic Entrails](https://www.wowhead.com/item=141308/demonic-entrails) se dropea de [Glazer](https://www.wowhead.com/npc=95887/glazer)
3er item [Eye of the Warden](https://www.wowhead.com/item=141309/eye-of-the-warden) se dropea de  [Cordana Felsong](https://www.wowhead.com/npc=95888/cordana-felsong)

6) https://www.wowhead.com/quest=42959/three-is-a-lucky-number (mision de Mago)
la mision pide obtener 3 items.
1er item [Glittering Necklace](https://www.wowhead.com/item=138968/glittering-necklace) se obtiene de ([Cordana Felsong](https://www.wowhead.com/npc=95888/cordana-felsong), [Wrath of Azshara](https://www.wowhead.com/npc=96028/wrath-of-azshara), [Saelorn](https://www.wowhead.com/npc=102387/saelorn) y [Mephistroth](https://www.wowhead.com/npc=116944/mephistroth)
) 
2er item [Handful of Ancient Golden Discs](https://www.wowhead.com/item=138969/handful-of-ancient-golden-discs) se obtiene de ([Cordana Felsong](https://www.wowhead.com/npc=95888/cordana-felsong), [Wrath of Azshara](https://www.wowhead.com/npc=96028/wrath-of-azshara), [Saelorn](https://www.wowhead.com/npc=102387/saelorn), [Dargrul](https://www.wowhead.com/npc=91007/dargrul), [Fel Lord Betrug](https://www.wowhead.com/npc=102446/fel-lord-betrug), [Shade of Xavius](https://www.wowhead.com/npc=99192/shade-of-xavius) y [Mephistroth](https://www.wowhead.com/npc=116944/mephistroth)
3do item (https://www.wowhead.com/item=138971/cask-of-honey-brew)  se obtiene de ([Cordana Felsong](https://www.wowhead.com/npc=95888/cordana-felsong), [Wrath of Azshara](https://www.wowhead.com/npc=96028/wrath-of-azshara), [Saelorn](https://www.wowhead.com/npc=102387/saelorn), [Dargrul](https://www.wowhead.com/npc=91007/dargrul), [Fel Lord Betrug](https://www.wowhead.com/npc=102446/fel-lord-betrug), [Shade of Xavius](https://www.wowhead.com/npc=99192/shade-of-xavius), [L'ura](https://www.wowhead.com/npc=124729/lura) y [Mephistroth](https://www.wowhead.com/npc=116944/mephistroth)

7) https://www.wowhead.com/quest=42660/vault-of-the-wardens-matters-of-the-heart (mision de brujo)
al matar a [Cordana Felsong](https://www.wowhead.com/npc=95888/cordana-felsong), deberia obtener [Felsworn heart](https://www.wowhead.com/item=138989/felsworn-heart)

**Comment by Cefiro-Caecias** [comment]
1.- Reparado.

2.- Reparado.

3.- Reparado, pero no olvides que ambos items son dropeados por los cofres "Challenger's Cache", no por los Bosses.

4.- Reparado.

5.- Reparado.

6.- Reparado, pero no con cahnce del 100%, sino del 30%,  ya que prácticamente los mismos Bosses están dropeando los 3 items simultáneamente.

7.- Reparado.

Todos disponibles en el próximo update.
