### ISSUE TITLE
Hunter Disengage

### ISSUE THREAD

**Issue by Fangley** [GuabinaCore/WoWKoi#3723]
**Links:**

from WoWHead or our Armory

**What is happening:** Hunter disengage talent stops working (the ikon turns grey and can't be used) after a while, and only can be fixed with changing the talent (which is not optional for example during a mythic run)

**What should happen:** It should work all the time when the talent is changed to Disengage

**Comment by Travven** [comment]
Maybe was a bug in that moment. I tested the talent even between spec and didn't got bugged.

**Comment by Cefiro-Caecias** [comment]
Fixed by Travven.
