### ISSUE TITLE
Wrong legendary drop 

### ISSUE THREAD

**Issue by OnlyWATCH** [GuabinaCore/WoWKoi#3727]
**Links:**

from WoWHead or our Armory
1 : https://www.wowhead.com/item=146899/highmountain-supplies
2 : https://www.wowhead.com/item=146898/dreamweaver-cache
3 : https://www.wowhead.com/item=146897/farondis-chest
4 : https://www.wowhead.com/item=146900/nightfallen-cache
5 : https://www.wowhead.com/item=146901/valarjar-strongbox
6 : https://www.wowhead.com/item=146902/wardens-supply-kit
7 : https://www.wowhead.com/item=147361/legionfall-chest

**What is happening:**
1 : giving the wrong legendary items . 
2 : playing make ( new character no have lego ) taking paladin legos - hunter - shaman- demon hunter. 
3:Loot spec = frost , taking fire spec legendary . 

**What should happen:**
1 :
![image](https://user-images.githubusercontent.com/82822767/160244737-6669a26e-62ea-4976-9460-ac1a73a40fdc.png)

2:
![image](https://user-images.githubusercontent.com/82822767/160245193-136821b0-fa51-4c58-84b2-0f0832016c58.png)
![image](https://user-images.githubusercontent.com/82822767/160245249-ddb2eb25-ac53-41d0-b169-6ff3b94566f3.png)
![image](https://user-images.githubusercontent.com/82822767/160245257-5beca645-7090-4ac7-a063-d8674f99fdee.png)

3: 
![image](https://user-images.githubusercontent.com/82822767/160245376-3ca26d4f-c86b-4bcf-be7a-9820089d4515.png)

**Comment by ShikoSCS** [comment]
Fixed up
