### ISSUE TITLE
Rogue's ( Between the Eyes ) Skill is not working properly. 

### ISSUE THREAD

**Issue by pleasestopno** [GuabinaCore/WoWKoi#373]
**Links:**

from WoWHead or our Armory

**What is happening:**

It will only hit for roughly 101 damage max even with 5 skill points built up, i'm lvl 47 now and thats all it's ever done

**What should happen:**

It should be my most damaging skill. The stun works fine for the 5 point combo, it does a 5 second stun but the damage at my level should be roughly 2-3 k

**Comment by DeltaVortex** [comment]
#248 before you submit bugs, there is an option to view similar bugs to what you are about to submit ^^

**Comment by pleasestopno** [comment]
My bad man I’m new sorry Sent from Mail for Windows 10 From: LeonSent: Tuesday, March 31, 2020 1:18 AMTo: GuabinaCore/WoWKoiCc: pleasestopno; AuthorSubject: Re: [GuabinaCore/WoWKoi] Rogue's ( Between the Eyes ) Skill is not working properly. (#373) #248 before you submit bugs, there is an option to view similar bugs to what you are about to submit ^^—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DeltaVortex** [comment]
It's all good, just make sure you close the issue.
