### ISSUE TITLE
Fragmentos del Pasado - Mision - Karazhan

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3735]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=44734/fragments-of-the-past
Al usar el cristal, no otorga crédito de misión. deberia otorgar credito

**Comment by Cefiro-Caecias** [comment]
Aplicado fix temporal. Disponible en el próximo update.
