### ISSUE TITLE
NPC - Novice Warbull

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3736]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=118051/novice-warbull
Killing this npc grants 75p reputation with HighMountain, it shouldn't receive any reputation.

**What should happen:**

**Comment by Travven** [comment]
Once you get honored, don't give more reputation

**Comment by Cefiro-Caecias** [comment]
Fixed by Travven.
