### ISSUE TITLE
DEPRECATED: Bloody Request - Quest 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3738]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=42309/deprecated-bloody-request
When I complete the credit of this first aid mission, it does not let me complete the mission
![image](https://user-images.githubusercontent.com/81131460/162034098-c5f60c14-9e97-49db-9681-8fb2d90e45f7.png)

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
