### ISSUE TITLE
Quest - Champion Moroes

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3740]
**Links:**

from WoWHead or our Armory

**What is happening:**

Obtaining the[ Broken Pocket Watch](https://www.wowhead.com/item=142246/broken-pocket-watch)

This quest(https://www.wowhead.com/quest=44803/return-to-karazhan-master-of-the-house) is obtained by looting  Broken Pocket Watch. I received the Broken Pocket Watch off of Moroes from Mythic Karazhan today.

After starting the quest you need to complete four steps:
["An Odious Task"](https://www.wowhead.com/mission=1491/an-odious-task) mission complete (I can't complete the quest because it doesn't appear)
["A Rare Vintage"](https://www.wowhead.com/mission=1492/a-rare-vintage) mission complete (I can't complete the quest because it doesn't appear)
1 Spiced Rib Roast
1 [ Master's Bell](https://www.wowhead.com/item=142275/masters-bell) (Off the Shade of Medivh)

The npc [Phantom Valet](www.wowhead.com/npc=115551/phantom-valet) (the npc does not appear
) that ends the quest(https://www.wowhead.com/item=142246/broken-pocket-watch) and starts another quest(www.wowhead.com/quest=44865/butler-to-the-great)

After completing the last mission I was sent to a table to the northwest of Karazhan around (40, 74.5) to meet and setup the dinner party I had prepared for. The quest(www.wowhead.com/quest=44865/butler-to-the-great) will have you put out the guest's favorite dishes or drink and then [Moroes ](https://www.wowhead.com/champion=733)will appear after placing the last item. Upon telling him that you have slain his master and that he no longer has anyone to work for you offer him an opportunity to help you.

Rewards the Moroes follower as the last step.

video: https://www.youtube.com/watch?v=t7sjOgxKnEk

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
