### ISSUE TITLE
NPC - Broken Shore - Excavator Karla

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3741]
**Links:**

https://www.wowhead.com/npc=119886/excavator-karla#comments

**What is happening:**

After communicating with other players, I can confirm that she gives 1 quest per week.

**What should happen:**

According to wowhead comments, in 2018 7.3.5 patch, it was changed, that she gives all the quests at once, beside the last one.

![image](https://user-images.githubusercontent.com/63166930/164971688-39c09f0b-5de3-4ddf-899c-c1c07056ceba.png)

**Comment by Cefiro-Caecias** [comment]
1) Prerequisite to unlock the quests: Quest "Vengeance Point" (46845).

2) Quest chain progression:

-Spiders, huh?
-Grave Robbin'
-Tomb Raider
-Ship Graveyard
-We're Treasure Hunters
-The Motherlode
         Unlocks Treasure Master Iks'reeged

https://wowpedia.fandom.com/wiki/Spiders,_Huh%3F

Removed the requirement to wait 24 hours for the next quest. Available in the enxt update.
