### ISSUE TITLE
Engineering - Reaves Module: Piloted Combat Mode

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3749]
**Links:**

https://www.wowhead.com/spell=198990/reaves-module-piloted-combat-mode

**What is happening:**

Possibly incorrect drop rate values for these reagents:

1. [Hardened Circuitboard Plating](https://www.wowhead.com/item=140785/hardened-circuitboard-plating) (50) - I had spent about 2hrs in the farming spot, and barely got 3.
2. [X-87 Battle Circuit](https://www.wowhead.com/item=140781/x-87-battle-circuit) (50) - These drop in Gnomeregan. 2 full runs, got 1 items.
3. [Neural Net Detangler](https://www.wowhead.com/item=140782/neural-net-detangler) and [Predictive Combat Operations Databank](https://www.wowhead.com/item=140783/predictive-combat-operations-databank) - can't even confirm if they drop, cuz I havent dropped them yet

--

GM tested it, and it seems, that the module doesn't have any effect on Reaves.

**Comment by Cefiro-Caecias** [comment]
Fixed.
