### ISSUE TITLE
Druid Prowl not working as stealth

### ISSUE THREAD

**Issue by Likander** [GuabinaCore/WoWKoi#3755]
**What is happening:**
When stealthing as prowl enemies auto-detect character IMMEDIATLY. Stealth function of prowl not working at all.

**What should happen:**
Click prowl and go into cat stance, and are stealthed. While stealthed enemies can't detect you unless you attack them or walk through them.

**Comment by Travven** [comment]
this depends of how many level is the enemy above you. For example, a boss could detect you at some range.

**Comment by Cefiro-Caecias** [comment]
Fixed by Travven.
