### ISSUE TITLE
[Quest] [DK] How To Win Friends And Influence Enemies

### ISSUE THREAD

**Issue by zodiac-git** [GuabinaCore/WoWKoi#3757]
**Links:**

[How To Win Friends And Influence Enemies](https://www.wowhead.com/quest=12720/how-to-win-friends-and-influence-enemies)

**What is happening:**

The NPC just dies during the RP part while talking and not giving quest credit.

**What should happen:**

Players should receive credit when the NPC is done talking and dies.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
