### ISSUE TITLE
[Arthas] - Faction bags buyable without revered

### ISSUE THREAD

**Issue by Frosty015** [GuabinaCore/WoWKoi#376]
**Links:** [Link](https://www.wowhead.com/item=67526/darnassian-satchel)

**What is happening:** For fun I tried to buy the Darnassian satchel with only friendly rep, somehow was able to buy the bag.

**What should happen:** Shouldn't be able to buy the bag until I have revered rep with this faction. Issue might be present as well with the other faction bags so it might be good to check as well ^^

**Comment by Serithul** [comment]
This issue is also appearing on the horde side. Along with some factions mount vendors, like the pandaren.
