### ISSUE TITLE
Jewelcrafting Truly Outrageous credit reverting when trying to turn in quest

### ISSUE THREAD

**Issue by Likander** [GuabinaCore/WoWKoi#3762]
**Links:**
https://www.wowhead.com/quest=40529/truly-outrageous
from WoWHead or our Armory

**What is happening:**
I did the quest and got all 5 chips needed for the quest but when I went to turn it in my quest credit reverted back to 1 and won't let me turn it in.
![Untitled](https://user-images.githubusercontent.com/104089230/165678216-5b407910-acd4-448c-833a-180bd1fe0a96.png)

**What should happen:**
You prospect for gem chips, get 5 and turn in quest to get next step.

**Comment by Cefiro-Caecias** [comment]
Fixed.
