### ISSUE TITLE
WQ- kirin Tor - Barril de la Diversión

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3765]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=45072/barrels-o-fun (WQ Stormheim)
esta WQ de Kirin Tor consta juego de barriles (https://www.wowhead.com/npc=116459/barrels-o-fun) 3 rounds:
1er round: 3 barriles
2do round: 4 barriles
3er round: 5 barriles
como funciona: al acercanos  la wq activa, visualizaremos 3 barriles y  un npc (https://www.wowhead.com/npc=116010/archmage-kreimhold) y tendremos un boton (https://www.wowhead.com/spell=230891) que inicia (1er, 2do y 3er round), señalando el barril y despues todos los barriles se mueven, al terminar debemos acertar cual es barril correcto de lo contrario se reinicia el juego(esto funciona para todos los rounds) y una vez completado los 3 rounds, la WQ se completa.
video: https://www.youtube.com/watch?v=CSHxooKUYWE

aqui las demas WQ de las demas zonas funcionan igual..
https://www.wowhead.com/quest=45068/barrels-o-fun (WQ Suramar)
https://www.wowhead.com/quest=45069/barrels-o-fun (WQ Azsuna)
https://www.wowhead.com/quest=45070/barrels-o-fun (WQ Val'sharah)
https://www.wowhead.com/quest=45071/barrels-o-fun (WQ Highmountain)
https://www.wowhead.com/quest=45072/barrels-o-fun (WQ Stormheim)

mas información: https://wowpedia.fandom.com/wiki/Barrels_o%27_Fun

**Comment by ventarius5** [comment]
#3532

**Comment by Cefiro-Caecias** [comment]
Reparadas todas, pero no blizzlike, por falta de información en páginas especializadas. Disponibles en el próximo update.
