### ISSUE TITLE
NPC - Blingtron 4000/5000/6000 (Engineering)

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3766]
**Links:**

https://www.wowhead.com/npc=101527/blingtron-6000#starts
https://www.wowhead.com/npc=77789/blingtron-5000
https://www.wowhead.com/npc=43929/blingtron-4000#starts

**What is happening:**

Blingtron's grant a daily quest only to the person that summoned him. Other players don't see his daily quest.

**What should happen:**

Blingtron's quest should be visible to every player.

**Comment by Cefiro-Caecias** [comment]
There is no bug present. These quests will only be visible to those who have learned the Engineering profession.
