### ISSUE TITLE
Profesion - Mineria

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3767]
**Links:**

from WoWHead or our Armory

**What is happening:**
Aumentar el tiempo de invocación de los basilicos a 1 minuto o 2 minutos, cuando eres nivel bajo demoras en matar al basilisco y desaparece ..
al picar menas ([ Deposito de piedra Ley](https://www.wowhead.com/object=241726/leystone-deposit), [Veta de piedra Ley](https://www.wowhead.com/object=253280/leystone-seam) y [Deposito rico de piedra Ley](https://www.wowhead.com/object=245324/rich-leystone-deposit)), invocas [ Basilisco de Piedra Ley](https://www.wowhead.com/npc=104877/leystone-basilisk)
al picar menas ([Deposito de Pizarra vil](https://www.wowhead.com/object=241743/felslate-deposit), [Veta de Pizarra vil](https://www.wowhead.com/object=255344/felslate-seam) y [Deposito rico de Pizarra vil](https://www.wowhead.com/object=245325/rich-felslate-deposit)), invocas [ Basilisco de Pizarra vil](https://www.wowhead.com/npc=104895/felslate-basilisk)

**Comment by Cefiro-Caecias** [comment]
Reparados. Disponibles en el próximo update.

**Comment by Noahkrr** [comment]
Mejorar loot
[ Deposito de piedra Ley](https://www.wowhead.com/object=241726/leystone-deposit)  debemos recibir  1-4  [Mena de piedra Ley](https://www.wowhead.com/item=123918/leystone-ore)
[Deposito rico de piedra Ley](https://www.wowhead.com/object=245324/rich-leystone-deposit) debemos recibir  3-6 [Mena de piedra Ley](https://www.wowhead.com/item=123918/leystone-ore)
[Veta de piedra Ley](https://www.wowhead.com/object=253280/leystone-seam) debemos recibir 5-10 [Mena de piedra Ley](https://www.wowhead.com/item=123918/leystone-ore)
[Deposito de Pizarra vil](https://www.wowhead.com/object=241743/felslate-deposit) debemos recibir 1-4 [Mena de pizarra vil](https://www.wowhead.com/item=123919/felslate)
[Deposito rico de Pizarra vil](https://www.wowhead.com/object=245325/rich-felslate-deposit) debemos recibir 3-6 [Mena de pizarra vil](https://www.wowhead.com/item=123919/felslate)
[Veta de Pizarra vil](https://www.wowhead.com/object=255344/felslate-seam) debemos recibir 5-10 [Mena de pizarra vil](https://www.wowhead.com/item=123919/felslate)

**Comment by Cefiro-Caecias** [comment]
Reparados. Disponibles en el próximo update.
