### ISSUE TITLE
[Core] - World Quests System Bug

### ISSUE THREAD

**Issue by lemmiwinkss** [GuabinaCore/WoWKoi#3768]
**Links:**
https://www.wowhead.com/quest=41267/work-order-cursed-queenfish

**What is happening:**
My character "Lemi" in-game cannot accept work orders from emissary NPCs anymore.
How it used to work: fly to emissary NPC in Azsuna pick up quest, example "Work Order: Cursed Queenfish", gather 40 Cursed Queenfish, turn in the quest get rewards (wakening essence, blood of sargeras etc).
What happens now: fly to emissary NPC he has quest "Work Order: Cursed Queenfish", but the quest is grey as if I already have it, when I click on the quest, while having 40 Cursed Quennfish in my inventory it does not allow me to click "continue" on the quest to trade the fish for quest rewards.

**What should happen:**
Each emissary NPC should give a work order quest and the quest should be able to be turned in. After giving the requested 40 resources to the NPC it should reward the quest rewards, such as Wakening Essence.

**Comment by Patrikturc** [comment]
Same problem for me

**Comment by Cefiro-Caecias** [comment]
@Altairfree, el problema es simple: si estás haciendo estas WQs y no las terminas, o se cae el Server, o relogueas, dichas WQs no se "limpian" de tu log, y aunque no puedas verlas en tu pantalla, para el sistema las sigues "teniendo" pero con progreso freezado, y por endes nunca puedes entregarlas.

Mismo problema que en el reporte:
https://github.com/GuabinaCore/WoWKoi/issues/3779
