### ISSUE TITLE
Profesión- Joyería - Prospección de Minerales

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3769]
**Links:**

from WoWHead or our Armory

**What is happening:**

**Elaboración de reactivos y prospección**
El mineral de la Legión puede ser prospectado en busca de gemas: [Mena de Piedra Ley](https://www.wowhead.com/item=123918/leystone-ore) and [Mena de Pizarra vil](https://www.wowhead.com/item=123919/felslate). Pizarra vil es el mineral que produce más gemas. Este mineral puede producir lo siguiente:

(El botín de gemas es bajo, el botín debe mejorarse)
Gemas raras: [ Furystone](https://www.wowhead.com/item=130178/furystone), [ Dawnlight](https://www.wowhead.com/item=130180/dawnlight), [ Pandemonite](https://www.wowhead.com/item=130181/pandemonite), [ Maelstrom Sapphire](https://www.wowhead.com/item=130182/maelstrom-sapphire), [ Shadowruby](https://www.wowhead.com/item=130183/shadowruby), [ Eye of Prophecy](https://www.wowhead.com/item=130179/eye-of-prophecy)

(El botín de gemas es bajo, el botín debe mejorarse)
Gemas poco comunes: [ Sangrite](https://www.wowhead.com/item=130172/sangrite), [ Deep Amber](https://www.wowhead.com/item=130173/deep-amber), [ Azsunite](https://www.wowhead.com/item=130174/azsunite), [ Chaotic Spinel](https://www.wowhead.com/item=130175/chaotic-spinel), [ Skystone](https://www.wowhead.com/item=130176/skystone), [ Queen's Opal](https://www.wowhead.com/item=130177/queens-opal)

(Hasta ahora no he obtenido estos items, parece no funcionar)
A medida que prospeccione el mineral, descubrirá elementos que permiten la prospección masiva: [Boceto: Prospección en masa de pizarra vil](https://www.wowhead.com/item=141312/design-mass-prospect-felslate) y [Boceto: Prospección en masa de piedra Ley](https://www.wowhead.com/item=141312/design-mass-prospect-felslate)

(No se cumple, el sistema esta bug)
También puede prospectar Gem Chips, que en su mayoría son basura de proveedores. El color del chip de gema refleja cuál será la próxima gema, por lo que un uso menor para un chip de gema es prospectar mineral de piedra Ley, encontrar el color del chip de gema que buscas y cambiar a uno mejor [Pizarra Vil](https://www.wowhead.com/item=123919/felslate) con la esperanza de obtener la gema que necesita rápidamente.

[ Found Sack of Gems](https://www.wowhead.com/item=140221/found-sack-of-gems) (El botín de gemas es bajo, el botín debe mejorarse)

**Comment by Cefiro-Caecias** [comment]
Reparado todo, excepto el sistema de Chips, que debería hacerse por Core. Disponible en el próximo update.
