### ISSUE TITLE
Dungeon - Karazhan - npc

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3772]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=115484/fel-bat
the npc cannot be attacked

In this version of the Chess event, the chess board contains: (the chess event doesn't work properly, the npc can be attacked and won't react and can also ignore them and go to the next stage)
1 [King](https://www.wowhead.com/npc=115388/king)
1 [Queen](https://www.wowhead.com/npc=115395/queen)
2 [Knight](https://www.wowhead.com/npc=115406/knight)s
2 [Bishop](https://www.wowhead.com/npc=115401/bishop)s
1 [Rook](https://www.wowhead.com/npc=115407/rook)

https://www.wowhead.com/object=266592/medivhs-footlocker
this chest contains nothing, this chest should have loot items from the [Mana Devourer](https://www.wowhead.com/npc=116494/mana-devourer) boss

https://www.wowhead.com/object=269940/legion-cache
currently this chest is not in the dungeon, it should be

these quests are given by [Mage Darius](https://www.wowhead.com/npc=18255/mage-darius)  after completing quest [Return to Karazhan: In the Eye of the Beholder](https://www.wowhead.com/quest=44735/return-to-karazhan-in-the-eye-of-the-beholder) (these 5 missions do not appear)
https://www.wowhead.com/quest=45291/return-to-karazhan-book-wyrms
https://www.wowhead.com/quest=45292/return-to-karazhan-rebooting-the-cleaner
https://www.wowhead.com/quest=45293/return-to-karazhan-new-shoes
https://www.wowhead.com/quest=45294/return-to-karazhan-high-stress-hiatus
https://www.wowhead.com/quest=45295/return-to-karazhan-clearing-out-the-cobwebs

**Comment by Cefiro-Caecias** [comment]
1) https://www.wowhead.com/npc=115484/fel-bat: Fixed, available in the next update.

2) Chess event: It will be fixed later.

3) https://www.wowhead.com/object=266592/medivhs-footlocker: Fixed, available in the next update.

4) https://www.wowhead.com/object=269940/legion-cache: This chest is found. Any GM can take you to it using the command .go object 132684.

5) Quests by Mage Darius: Fixed, available in the next update.
