### ISSUE TITLE
[DB - Arthas] - Shaman Artifact Scenario: The Voice of Thunder

### ISSUE THREAD

**Issue by zodiac-git** [GuabinaCore/WoWKoi#3773]
[The Voice of Thunder](https://www.wowhead.com/quest=39771/the-voice-of-thunder#)

**What is happening:**

Can't finish the scenario, some objectives are not working. The weapon can be aquired, but the NPCs supposed to help the player with killing the spawning demons aren't doing anything. Some mobs are missing or placed at the wrong place as well.

**What should happen:**

[video](https://www.youtube.com/watch?v=EBJNm6YQC4Y)

**Comment by Cefiro-Caecias** [comment]
Fixed.
