### ISSUE TITLE
[Quest] Moon Reaver

### ISSUE THREAD

**Issue by zodiac-git** [GuabinaCore/WoWKoi#3774]
**Links:**

[Moon Reaver](https://www.wowhead.com/quest=42751/moon-reaver)

**What is happening:**

Can't turn in the quest, NPC is missing or wrongly phased.

**What should happen:**

[video](https://www.wowhead.com/quest=42751/moon-reaver#videos:id=101009)

**Comment by Cefiro-Caecias** [comment]
Reparado.
