### ISSUE TITLE
Timewalking - Completing Pandarian dungeons

### ISSUE THREAD

**Issue by Valcry1** [GuabinaCore/WoWKoi#3775]
**What is happening:**
Gate of the Setting Sun Dungeon has hidden mobs that will start attacking you after killing Striker Ga-dok and engaging Ri'mok. Healers eventually get aggro by healing, and can not be peeled. When the last boss is engaged, the boss stays in combat and you can not rez and reset. You end up having shut the client and it puts you dead somewhere. 

Stormstout Brewery has line of sight issues where ever there is a small dip in the floor. It is more apparent when trying to kill the last boss. Tanks can be a few yards in front of you, and you have no line of sight for healing. Gear that drops from this dungeon wasn't scaled to 880 either.

**Comment by Cefiro-Caecias** [comment]
Old content. It will be fixed later.
