### ISSUE TITLE
Portal to Twilight Vineyards

### ISSUE THREAD

**Issue by zodiac-git** [GuabinaCore/WoWKoi#3777]
**Links:**

[Twilight Vineyards](https://www.wowhead.com/achievement=11125/now-youre-thinking-with-portals#comments)

**What is happening:**

The portal present in Meredil is incorrrect after unlocking it. Currently it is a portal to Lunastre Estate.

**What should happen:**

The portal should take the player to Twilight Vineyards. See the top wowhead comment where it should be.

**Comment by Travven** [comment]
Fixed

**Comment by Cefiro-Caecias** [comment]
Fixed by Travven.
