### ISSUE TITLE
[Core] - Worlds Quests Problem

### ISSUE THREAD

**Issue by Staldan** [GuabinaCore/WoWKoi#3779]
(https://www.wowhead.com/quest=41670/work-order-word-of-agility)
(https://www.wowhead.com/quest=41317/supplies-needed-leystone)

If you go to each region's emissary you can turn in reagents for blood of sargeras and other stuff. If you go there, and you don't have the reagents at you the quests turn grey and you can't turn them in anymore. I am not sure if this is the 100% correct way how it gets bugged, but i had 4 quests in each region that i couldn't turn in until Paerux turned them in for me, then they started working correctly.

![WoWScrnShot_050622_113530](https://user-images.githubusercontent.com/103856597/167109085-4616e79c-b42c-4901-9dea-c087f92841c1.jpg)

**Comment by Cefiro-Caecias** [comment]
@Altairfree, el problema es simple: si estás haciendo estas WQs y no las terminas, o se cae el Server, o relogueas, dichas WQs no se "limpian" de tu log, y aunque no puedas verlas en tu pantalla, para el sistema las sigues "teniendo" pero con progreso freezado, y por endes nunca puedes entregarlas.

Mismo problema que en el reporte:
https://github.com/GuabinaCore/WoWKoi/issues/3768
