### ISSUE TITLE
Nightbane - Return to Karazhan

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3780]
**Links:**

from WoWHead or our Armory

**What is happening:**
Accessing the boss
Upon opening the door after zoning into Karazhan, the following emote happens: "The strange chill of a dark presence winds through the air." This starts the timer for the first crystal.
You have a STRICT timing to make it to Opera, kill Opera and click the first [Soul Fragment](https://www.wowhead.com/npc=115013/soul-fragment). You have 8 minutes from the moment you zone in to click the first crystal.
From there on each Soul Fragment you click add a bit of time to your timer. But its very very tight.
After the first crystal you will gain a buff,  Medivh's Echo, with a 6min duration. This is now your timer. As you click crystals, it will add a stacking buff and 5 minutes to the time you had left on your buff. (the accumulated time is shorter than normal, actually they give you 3 minutes, it should be 5 minutes for each crystal)
If you fail the speed run, you will get an emote notification: "The air grows slightly warmer".
The [Soul Fragment](https://www.wowhead.com/npc=115013/soul-fragment)s are located as follows: 1 in the audience from Opera, 1 before Maiden (you don’t need to kill her), 1 after you kill Moroes, 1 in the Spider Room (then you click the portal to the stairway), 1 after you kill Curator.
If you click all the Soul Fragment within the allotted time, run back to Nightbane's room after killing Curator.
Upon clicking the final crystal in time, your timer buff will change to [ Medivh's Presence](https://www.wowhead.com/spell=229077/medivhs-presence) and you will have 5 minutes to go speak with Medivh and summon Nightbane. When you speak to Medivh you get the [ One Night in Karazhan](https://www.wowhead.com/achievement=11430/one-night-in-karazhan) achievement. (when I talk to Medivh I don't get the achievement and I can't summon Dragon)
The original Roleplay upon summoning Nightbane will then play, and then you will be able to fight Nightbane.
Once you speak to Medivh and [Nightbane](https://www.wowhead.com/npc=114895/nightbane) is summoned, you are able to wipe without worry. He will still be there and shout at you as he continuously slays you.
[Smoldering Ember Wyrm](https://www.wowhead.com/item=142552) is personal loot.

video: https://www.youtube.com/watch?v=HjvT9Kh03SE

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
