### ISSUE TITLE
Misiones de clase - Cazador de Demonios

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3781]
**Links:**

from WoWHead or our Armory

**What is happening:**

Completé ambas misiones con una misión de campaña aleatoria, me contó todos los créditos, debería completar con misiones respectivas.

https://www.wowhead.com/quest=42802/securing-mardum
use el [Mapa de exploración](https://wowpedia.fandom.com/wiki/Scouting_Map) y completa la misión "Securing Mardum"
"Campaign [Securing Mardum](https://www.wowhead.com/mission=1245/securing-mardum)" completed

https://www.wowhead.com/quest=42731/working-with-the-wardens
usa el [Mapa de exploración](https://wowpedia.fandom.com/wiki/Scouting_Map) y completa la misiones "Working With the Wardens" 

"Campaign [Working With the Wardens: Isle of the Watchers](https://www.wowhead.com/mission=1157/working-with-the-wardens-isle-of-the-watchers)" completed
"Campaign [Working With the Wardens: Skul'vrax](https://www.wowhead.com/mission=1158/working-with-the-wardens-skulvrax)" completed
"Campaign [Working With the Wardens: Mellok, Son of Torok](https://www.wowhead.com/mission=1159/working-with-the-wardens-mellok-son-of-torok)" completed
"Campaign [Working With the Wardens: Fathnyr](https://www.wowhead.com/mission=1160/working-with-the-wardens-fathnyr)" completed
"Campaign [Working With the Wardens: Mal'Dreth the Corruptor](https://www.wowhead.com/mission=1161/working-with-the-wardens-maldreth-the-corruptor)" completed

https://www.wowhead.com/quest=42669/preparations-for-invasion
use el [Mapa de exploración](https://wowpedia.fandom.com/wiki/Scouting_Map) y complete las misiones "Preparations for Invasion" 

"Campaign [Preparations for Invasion: Scouting their Hold](https://www.wowhead.com/mission=1205/preparations-for-invasion-scouting-their-hold)" completed
"Campaign [Preparations for Invasion: Weapon Improvements](https://www.wowhead.com/mission=1206/preparations-for-invasion-weapon-improvements)" completed
"Campaign [Preparations for Invasion: Snatch and Grab](https://www.wowhead.com/mission=1207/preparations-for-invasion-snatch-and-grab)" completed
"Campaign [Preparations for Invasion: Ship-Shape](https://www.wowhead.com/mission=1208/preparations-for-invasion-ship-shape)" completed
"[Preparations for Invasion: Where Are the Felsouls?](https://www.wowhead.com/mission=1209/preparations-for-invasion-where-are-the-felsouls)" completed

https://www.wowhead.com/npc=113673/imprisoned-executioner
los muñecos de combates de los tankes no funcionan, deberia lanzar spells y atacarte

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=112992/seer-aleis (el npc no esta en la sala de clases)
Seer Aleis lleaga tu salon de clases despues de haber mejorado [ Focused War Effort](https://www.wowhead.com/order-advancement=420/focused-war-effort). Se encuentra en el nivel medio, junto a Loramus, y las órdenes de trabajo con él cuestan 25 recursos y están listas en segundos.
también inicia esta misión https://www.wowhead.com/quest=44226/fate-favors-us

**Comment by Noahkrr** [comment]
https://www.wowhead.com/item=141409/candraels-charm
este item solo debe ser obtenido por los Cazadores de Demonios, las demas clases no deberian obtenelo

**Comment by Cefiro-Caecias** [comment]
1) Misiones de campaña aleatoria: por el momento debe quedar así, ya que no puedo manipular el sistema para hacerlo más específico.

2) NPC "Imprisoned Executioner": por el momento debo dejarlo así, ya que programarlo para atacar resulta en defectos de aggro infinito.

3) NPC "Seer Aleis": agregado, y sólo visible si compras el update correspondiente. La quest "Fate Favors Us" tuve que ponerla autocompletable, ya que el sistema de las work orders de ese NPC al parecer no está creado.

4) Item "Candrael's Charm": reaparado, sólo le caerá a los DH.
