### ISSUE TITLE
[Core] - Pedido de  Armamentos - Sede de clase Cazador de Demonios y demás clases

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3783]
**Links:**

from WoWHead or our Armory

**What is happening:**
Ejemplo la clase cazador de demonios, el npc
https://www.wowhead.com/npc=110433/slitesh 
realiza los pedidos de armamentos que otorga son [ Champion Armaments](https://www.wowhead.com/item=139308/champion-armaments), no deberia obtener el item.

Deberia generarse este objetos:
https://www.wowhead.com/object=251993/requisitioned-armaments
https://www.wowhead.com/object=252013/requisitioned-armaments
https://www.wowhead.com/object=252015/requisitioned-armaments
https://www.wowhead.com/object=252016/requisitioned-armaments (para warrior)
https://www.wowhead.com/object=251996/requisitioned-armaments
https://www.wowhead.com/object=252014/requisitioned-armaments
https://www.wowhead.com/object=252005/requisitioned-armaments
https://www.wowhead.com/object=252058/requisitioned-armaments (para DK)

una vez terminado el pedido armamentos, al hacer click se obtendra estos items: (puedes hacer 3 pedidos, se obtendra un item aleatorio por cada pedido) cada pedido dura 1.5 dias
[ Piedra desgastada](https://www.wowhead.com/item=139816/well-worn-stone)
[ Adorno de la suerte](https://www.wowhead.com/item=139801/lucky-doodad)	
[ Fetiche auspicioso](https://www.wowhead.com/item=139802/auspicious-fetish)
[ Martillo de cocodrilo](https://www.wowhead.com/item=152438/krokul-sledgehammer)
[ Chuchería de Wakener](https://www.wowhead.com/item=152935/wakeners-bauble)
[ Recuerdo de los forjados por la Luz](https://www.wowhead.com/item=152445/memento-of-the-lightforged)
[ Reloj de bolsillo apresurado](https://www.wowhead.com/item=140572/hasty-pocketwatch)
[ Poción de energía](https://www.wowhead.com/item=140571/potion-of-energy)
[ Elixir de enfoque abrumador](https://www.wowhead.com/item=140573/elixir-of-overwhelming-focus)
[ Hacha de piedra serrada](https://www.wowhead.com/item=152927/serrated-stone-axe)
[ Flor de Arinor tocada por el Vacío](https://www.wowhead.com/item=152440/void-touched-arinor-blossom)
[ Armamentos Santificados de la Luz](https://www.wowhead.com/item=152443/sanctified-armaments-of-the-light)
[ Botas de montaña resistentes](https://www.wowhead.com/item=140581/sturdy-hiking-boots)
[ Sangre de demonio viscosa](https://www.wowhead.com/item=152437/viscid-demon-blood)
[ Matraz sin fondo](https://www.wowhead.com/item=140582/bottomless-flask)
[ Zafiro de luz azur](https://www.wowhead.com/item=152936/azurelight-sapphire)
[ Vial de aliento intemporal](https://www.wowhead.com/item=140583/vial-of-timeless-breath)
[ Martillo Xenedar exaltado](https://www.wowhead.com/item=152444/exalted-xenedar-hammer)
[ Colmillo Señor del Foso](https://www.wowhead.com/item=152439/pit-lord-tusk)
[ Efusión de vacío de la Guardia de las Sombras](https://www.wowhead.com/item=152933/shadowguard-void-effusion)
[ Tintura Xénica](https://www.wowhead.com/item=152931/xenic-tincture)
[ Látigo espinal de demonio vil](https://www.wowhead.com/item=152930/vilefiend-spine-whip)
[ Corazón de acechador empapado de sombras](https://www.wowhead.com/item=152934/shadow-soaked-stalker-heart)
[ Carga de ráfaga de luz](https://www.wowhead.com/item=152447/lightburst-charge)
[ Lanza de acechador de crestas puntiagudas](https://www.wowhead.com/item=152929/pronged-ridgestalker-spear)
[ Caperuza de tejido de sombra impermeable](https://www.wowhead.com/item=152442/impervious-shadoweave-hood)
[ Hoja de luz con recompensa de runas](https://www.wowhead.com/item=152932/runewarded-lightblade)

[ Zanahoria en un palo](https://www.wowhead.com/item=139814/carrot-on-a-stick)
[ Silla de montar del pionero](https://www.wowhead.com/item=139799/pathfinders-saddle)
[ Piedra vidente arcaica](https://www.wowhead.com/item=152928/archaic-seerstone)
[ Saco de lucidez](https://www.wowhead.com/item=152441/satchel-of-lucidity)
[ Escritura de las Órdenes Sagradas](https://www.wowhead.com/item=152446/writ-of-holy-orders)

[ Adorno fructífero](https://www.wowhead.com/item=139792/fruitful-bauble)
[ Curiosidad de la felicidad abundante](https://www.wowhead.com/item=139808/curio-of-abundant-happiness)
[ Elixir de la Abundancia](https://www.wowhead.com/item=139809/elixir-of-plenty)
[ Borrador de coraje](https://www.wowhead.com/item=139795/draught-of-courage)
[ Collar de recuerdos infinitos](https://www.wowhead.com/item=139811/necklace-of-endless-memories)
[ Poción de Tritón](https://www.wowhead.com/item=139812/potion-of-triton)

**items de campeones de clases especificas**
Solo Cazador de demonios
[ Vestigio del merodeador](https://www.wowhead.com/item=139835/marauders-vestige)
[ Reliquia de las sombras](https://www.wowhead.com/item=139836/shadow-relic)
[ Sigilo del demonio](https://www.wowhead.com/item=139837/demons-sigil)
[ Esencia de malicia](https://www.wowhead.com/item=139838/essence-of-malice)
[ Estándar demoníaco](https://www.wowhead.com/item=147571/demonic-standard)
[ La vista de Elune](https://www.wowhead.com/item=139863/elunes-sight)

Solo Caballero de la Muerte
[ Runa del juicio](https://www.wowhead.com/item=139876/rune-of-reckoning)
[ Toque de la muerte](https://www.wowhead.com/item=139877/deaths-touch)
[ Reliquia de la Espada de Ébano](https://www.wowhead.com/item=139878/relic-of-the-ebon-blade)
[ Sello de escarcha de ébano](https://www.wowhead.com/item=147572/sigil-of-ebon-frost)

Solo druida
[ Pergamino de crecimiento](https://www.wowhead.com/item=139864/scroll-of-growth)
[ Ficha resplandeciente](https://www.wowhead.com/item=139865/glowing-token)
[ ascua del bosque](https://www.wowhead.com/item=139866/forest-ember)
[ Hoja de Arboleda de los Sueños](https://www.wowhead.com/item=147570/dreamgrove-leaf)
[ Arco de los antiguos reyes](https://www.wowhead.com/item=139847/bow-of-ancient-kings)
Solo cazador
[ Vale del buscador](https://www.wowhead.com/item=139848/seekers-scrip)
[ Regalo de Brisaveloz](https://www.wowhead.com/item=139849/windrunners-gift)
[ Capa de engaño](https://www.wowhead.com/item=139850/cloak-of-deception)
[ Trampa Arcana](https://www.wowhead.com/item=147569/arcane-trap)
[ Sortija de fuerza primordial](https://www.wowhead.com/item=139845/band-of-primordial-strength)
Solo mago
[ Adorno Altonato](https://www.wowhead.com/item=139846/highborne-bauble)
[ Adorno de prestidigitador](https://www.wowhead.com/item=139843/conjurers-bauble)
[ Bagatela de arcanista](https://www.wowhead.com/item=139844/arcanists-trifle)
[ Esencia de Nether](https://www.wowhead.com/item=147568/essence-of-nether)
[ Joya potenciada por chi](https://www.wowhead.com/item=139859/chi-empowered-jewel)
solo monje
[ té de bendición](https://www.wowhead.com/item=139860/tea-of-blessing)
[ puedo madstone](https://www.wowhead.com/item=139861/mogu-madstone)
[ campana de furia](https://www.wowhead.com/item=139862/bell-of-fury)	
[ Enfoque calmante](https://www.wowhead.com/item=147567/soothing-focus)
[ Martillo de justicia](https://www.wowhead.com/item=139867/justice-hammer)
Solo paladín
[ Escudo de luz](https://www.wowhead.com/item=139868/lights-shield)
[ Tratado de la Ilustración](https://www.wowhead.com/item=139869/libram-of-enlightenment)
[ Adorno de mano de plata](https://www.wowhead.com/item=139870/silver-hand-ornament)
[ Cuerno de Valor](https://www.wowhead.com/item=147566/horn-of-valor)
[ Estatuilla sagrada](https://www.wowhead.com/item=139871/holy-figurine)
solo sacerdote
[ Comando de la luz](https://www.wowhead.com/item=139872/lights-command)
[ Cordura embotellada](https://www.wowhead.com/item=139873/bottled-sanity)
[ Filo de la cordura](https://www.wowhead.com/item=139874/sanity-edge)
[ Libro de los sermones perdidos](https://www.wowhead.com/item=147565/book-of-lost-sermons)
[ granadas de humo](https://www.wowhead.com/item=139831/smoke-grenades)
solo pícaro
[ Poción para dormir](https://www.wowhead.com/item=139832/sleep-potion)
[ Brebaje de sanguijuela](https://www.wowhead.com/item=139833/leech-brew)	
[ Polvo que se desvanece](https://www.wowhead.com/item=139834/vanishing-dust)
[ piedra de diamante](https://www.wowhead.com/item=147564/diamond-stone)
[ Publicación de vudú](https://www.wowhead.com/item=139839/voodoo-post)
Solo chamán
[ Pinza terrenal](https://www.wowhead.com/item=139840/earthly-pincer)
[ Tótem de la Tierra](https://www.wowhead.com/item=139841/totem-of-the-earth)
[ Carga furiosa](https://www.wowhead.com/item=139842/furious-charge)
[ Tótem de piedra](https://www.wowhead.com/item=147563/stone-totem)
[ Calavera de Abrazo](https://www.wowhead.com/item=139855/skull-of-embrace)
Solo brujo
[ Brebaje demoníaco](https://www.wowhead.com/item=139856/demonic-brew)
[ Yelmo de mando](https://www.wowhead.com/item=139857/helm-of-command)
[ Curiosidades de la Cosecha Negra](https://www.wowhead.com/item=139858/black-harvest-curio)
[ Reliquia de influencia demoníaca](https://www.wowhead.com/item=147561/relic-of-demonic-influence)
[ Poderío de Valarjar](https://www.wowhead.com/item=139851/valarjars-might)
solo guerrero
[ estandarte de guerra](https://www.wowhead.com/item=139852/war-banner)
[ Hacha de la Valkyra](https://www.wowhead.com/item=139853/axe-of-the-valkyra)
[ Cráneo de un enemigo caído](https://www.wowhead.com/item=139854/skull-of-a-fallen-foe)
[ Cuerno de ira](https://www.wowhead.com/item=147560/horn-of-rage)

items legendarios de campeones deben tener un % de loot mas bajo
[ Demonio en una caja](https://www.wowhead.com/item=139830/demon-in-a-box)
[ Diente de diablillo vil](https://www.wowhead.com/item=147557/fel-imp-tooth)
[ Cuartel General Tomo de Arcana](https://www.wowhead.com/item=152448/praetorium-tome-of-arcana)
[ plumas de la reina](https://www.wowhead.com/item=139828/queens-feathers)
[ Poción de sacrificio](https://www.wowhead.com/item=139829/potion-of-sacrifice)
[ Pluma de arpía](https://www.wowhead.com/item=147554/harpy-feather)
[ Garra perdida oscura](https://www.wowhead.com/item=152454/darklost-claw)
[ Vial de la vista](https://www.wowhead.com/item=147555/vial-of-sight)
[ Capa de ocultamiento](https://www.wowhead.com/item=147556/cloak-of-concealment)
[ Efigie de legión imbuida de vileza](https://www.wowhead.com/item=152453/fel-infused-legion-effigy)
[ Candelabro de luz azur](https://www.wowhead.com/item=152449/azurelight-candelabra)
[ Bastón de censor Augari](https://www.wowhead.com/item=152450/augari-censorite-staff)
[ Pergamino estigio volátil](https://www.wowhead.com/item=152451/volatile-stygian-scroll)
[ Calavera de guardia de la cólera pulsante](https://www.wowhead.com/item=152452/pulsing-wrathguard-skull)
[ Broche de sueños sin fin](https://www.wowhead.com/item=139827/brooch-of-endless-dreams)
[ Tomo de secretos](https://www.wowhead.com/item=139825/tome-of-secrets)
[ Gracia de Eltrig](https://www.wowhead.com/item=139826/eltrigs-grace)
[ Oferta de presagio](https://www.wowhead.com/item=139821/omens-bidding)
[ Colmillo Glacial](https://www.wowhead.com/item=139804/glacial-fang)
[ Ascuas de las Tierras de Fuego](https://www.wowhead.com/item=139819/embers-of-the-firelands)
[ Fragmento de Vacío Abisal](https://www.wowhead.com/item=147553/shard-of-twisting-nether)
[ Refugio de la luz](https://www.wowhead.com/item=139824/lights-haven)
[ Fin de la pesadilla](https://www.wowhead.com/item=139823/nightmares-end)
[ Polvo de Azeroth](https://www.wowhead.com/item=139822/dust-of-azeroth)
[ Resguardo de furia infinita](https://www.wowhead.com/item=147559/ward-of-infinite-fury)
[ Bolsa de maravilla](https://www.wowhead.com/item=147558/pouch-of-wonder)

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible mañana.
