### ISSUE TITLE
Suramar WQ's value's

### ISSUE THREAD

**Issue by Valcry1** [GuabinaCore/WoWKoi#3784]
**Links:**
https://www.wowhead.com/quest=44119/danger-volshax-breaker-of-will
https://www.wowhead.com/quest=41697/danger-colerian-alteria-and-selenyi
https://www.wowhead.com/quest=44024/wanted-shalan

**What is happening:**
WQ completion is not granting reputation with nightfallen rep. Did not check to see if wardens increased. Noticed Shal'an giving Court of farondis rep. 

**What should happen:**
Reputation should be granted for the numbers listed in links. I would go so far as to say a majority of WQ's in suramar are not granting enough rep or none at all from how slow the gains are compared to other reputations. 
https://www.wowhead.com/quests/legion/suramar?filter=1;1859;0#0-2+13

**Comment by Cefiro-Caecias** [comment]
Fixed all. Available in the next update.
