### ISSUE TITLE
Orígenes - Misiones para todas las clases(no paladin)

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3785]
**Links:**

from WoWHead or our Armory

**What is happening:**
Después de desbloquear los dos primeros campeones de Class Hall:

1- [Una estrella fugaz](https://www.wowhead.com/quest=44009/a-falling-star)
2- [Portador de la Luz](https://www.wowhead.com/quest=44004/bringer-of-the-light)
Misión secundaria: [La última batalla de Nobundo](https://www.wowhead.com/quest=43705/nobundos-last-stand)
3- [Carga de la luz](https://www.wowhead.com/quest=44153/lights-charge)
4- [La diosa te cuida](https://www.wowhead.com/quest=44337/goddess-watch-over-you)
5- [En la Casa de la Luz y la Sombra](https://www.wowhead.com/quest=44448/in-the-house-of-light-and-shadow)
6- [Despertares](https://www.wowhead.com/quest=44464/awakenings)
7- [Un camino poco claro](https://www.wowhead.com/quest=44466/an-unclear-path)
8- [El legado de Cresta de Cuervo](https://www.wowhead.com/quest=44479/ravencrests-legacy)
Misión secundaria: norte [45]  [Engendros viles de Lothros](https://www.wowhead.com/quest=44414/felspawns-of-lothros)
Misión secundaria: norte [45]  [El hacha roja](https://www.wowhead.com/quest=44415/the-red-axe)
Misión secundaria: norte [45]  [Cazador de la noche](https://www.wowhead.com/quest=44416/hunter-of-night)
9- [En la casa de mi padre](https://www.wowhead.com/quest=44480/in-my-fathers-house)
10- [Destino incumplido](https://www.wowhead.com/quest=44496/destiny-unfulfilled) o [Destino incumplido](https://www.wowhead.com/quest=44497/destiny-unfulfilled) (si eres Cazador de Demonios)
11- [La caza de Illidan Tempestira](https://www.wowhead.com/quest=45174/the-hunt-for-illidan-stormrage)
12- [Prisma de alma de los Illidari](https://www.wowhead.com/quest=45175/soul-prism-of-the-illidari)
13- [Prueba de valor: el antiguo y futuro Señor de las Sombras](https://www.wowhead.com/quest=45176/trial-of-valor-the-once-and-future-lord-of-shadows)
14- [El Bastión Nocturno](https://www.wowhead.com/quest=45177/the-nighthold)

mas información: https://wowpedia.fandom.com/wiki/Bringer_of_the_Light

**Comment by Cefiro-Caecias** [comment]
Reencadenadas las quests. Disponibles en el próximo update.
