### ISSUE TITLE
World Quest / WQ - Stonebound Soldiers - NPC Legionfall Soldier 

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3786]
**Links:**

https://www.wowhead.com/quest=46236/stonebound-soldiers

**What is happening:**

[Legionfall Soldier](https://www.wowhead.com/npc=119141/legionfall-soldier-cured) can be clicked multiple times for additional credits.

**What should happen:**

No spammerino on NPCrinno

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
