### ISSUE TITLE
Shal'Aran

### ISSUE THREAD

**Issue by Treisand** [GuabinaCore/WoWKoi#3788]
**Links: https://www.wowhead.com/quest=42229/shalaran**

from WoWHead or our Armory

**What is happening: Thalyssra not moving inside the cave like she is supposed to, thus not completing the quest**

**What should happen: She should walk inside the cave and have some dialogue, turn the lights on, and then the quest should be completed.**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
