### ISSUE TITLE
Mazmorra - La arqueria

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3789]
**Links:**

from WoWHead or our Armory

**What is happening:**
Durante el combate contra el jefe [Consejero Vandros](https://es.wowhead.com/npc=98208), al morir miembros de mi grupo, tienen la opción de liberar espíritu, cuando liberan aparecen afuera de la mazmorra en un cementerio de Suramar.
1- durante el combate contra cualquier jefe, al morir no deberías tener la opción de liberar espíritu, ya que los miembros  del grupo aun están en combate con el jefe. a menos que que el jefe muriese o todos los miembros mueran 
2- al liberar alma no debería sacarte de la mazmorra, deberías aparecer en el cementerio de la mazmorra

**Comment by Cefiro-Caecias** [comment]
Reparado.
