### ISSUE TITLE
Westfall Loremaster

### ISSUE THREAD

**Issue by JadedNate** [GuabinaCore/WoWKoi#379]
https://www.wowhead.com/achievement=4903/westfall-quests

**What is happening:**
Credit is not given when quests are completed; Achievement cannot be earned.

**What should happen:**
Upon completing the zone's storylines, credit should be given to the player until the storylines are all complete, resulting in the achievement.

**Comment by Cefiro-Caecias** [comment]
You must be missing some quest. The map was tested and Achievement is obtainable.
