### ISSUE TITLE
Warlords of draenor starting quest teleports me underground

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3790]
**Links:** https://www.wowhead.com/quest=34398/warlords-of-draenor-the-dark-portal

from WoWHead or our Armory

**What is happening:**
i was just curiously wanted to visit the location but i got the chance for a different underground adventure
![image](https://user-images.githubusercontent.com/84509345/168473287-96b31927-8521-4b96-ac76-963d2b13e125.png)

**What should happen:**
teleport to a higher place when i go through the portal

**Comment by Cefiro-Caecias** [comment]
Old content. It will be fixed later.
