### ISSUE TITLE
Moneda - Trozo de alma persistente

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3791]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/currency=1314/lingering-soul-fragment
estas monedas caen de todos los jefes de mazmorras, no deberia poder obtener estas monedas a menos que tenga activa esta misión [ Soul Prism of the Illidari](https://www.wowhead.com/quest=45175/soul-prism-of-the-illidari), una vez completada la mision, estas monedas deberían dejar de caer de los jefes mazmorras

**Comment by Cefiro-Caecias** [comment]
Por el momento, la petición es irresoluble, ya que carecemos de una herramienta para condicionar drop de Currencys, y por eso el sistema convertía esta currency en el molesto ítem Dedos de Necrófago : /
