### ISSUE TITLE
The Nighthold: Talisman of the Shal'dorei

### ISSUE THREAD

**Issue by IcicleUBW** [GuabinaCore/WoWKoi#3793]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=45383/the-nighthold-talisman-of-the-shaldorei
**What is happening:**
![image](https://user-images.githubusercontent.com/97225139/168858807-f9f38e69-5521-4dcc-9a67-90a8a4351671.png)
Echo of time is not dropping from Elisandre at any difficulty

**What should happen:**
You should get 1x echo of time each kill on Elisandre 100% drop rate for everyone in the raid group.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
