### ISSUE TITLE
Profesión -  Inscripción - Misiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3796]
**Links:**

from WoWHead or our Armory

**What is happening:**
Dato: todas las misiones se pueden completar.
principales problemas:
A) primer problema las misiones deben ser re-encadenadas y ordenadas, una tras otra..
B) las misiones pierden seguimiento al completar un crédito, no pueden ser rastreadas en el mapa.

**Cadena de Misiones de Inscripción**
Nivel 100
1. [Sign This](https://www.wowhead.com/quest=39847/sign-this)
2. [Smashing Herbs](https://www.wowhead.com/quest=39931/smashing-herbs)
3. [Fish Ink](https://www.wowhead.com/quest=39932/fish-ink)
4. [The Card Shark](https://www.wowhead.com/quest=39933/the-card-shark)

Nivel 102
5. [Our New Allies](https://www.wowhead.com/quest=39934/our-new-allies) / Demon hunter Inscription [Our New Allies](https://www.wowhead.com/quest=40056/our-new-allies)
6. [The Price of Power](https://www.wowhead.com/quest=39935/the-price-of-power) / Demon hunter Inscription [The Price of Power](https://www.wowhead.com/quest=40057/the-price-of-power)
7. [Inscription of the Body](https://www.wowhead.com/quest=39936/inscription-of-the-body) / Demon hunter Inscription [Defense Symbology](https://www.wowhead.com/quest=40058/defense-symbology)
8. [Opposites Repel](https://www.wowhead.com/quest=39937/opposites-repel) / Demon hunter Inscription [Opposites Repel](https://www.wowhead.com/quest=40059/opposites-repel)
9. [Containing the Demon Within](https://www.wowhead.com/quest=39938/containing-the-demon-within) / Demon hunter  Inscription [Containing the Demon Within](https://www.wowhead.com/quest=40060/containing-the-demon-within)
10. [Scribal Knowledge](https://www.wowhead.com/quest=39939/scribal-knowledge) / Demon hunter Inscription [To Know Your Enemy](https://www.wowhead.com/quest=40061/to-know-your-enemy)
11. [Control is Key](https://www.wowhead.com/quest=39941/control-is-key) / Demon hunter Inscription [Control is Key](https://www.wowhead.com/quest=40063/control-is-key)
12. [Runes of Power](https://www.wowhead.com/quest=39940/runes-of-power)
13. [The Burdens of Hunting](https://www.wowhead.com/quest=39943/the-burdens-of-hunting)

Nivel 104
14. [Mysterious Messages](https://www.wowhead.com/quest=39944/mysterious-messages)
15. [Runes Within the Ruins](https://www.wowhead.com/quest=39945/runes-within-the-ruins)
16. [Right Tool for the Job](https://www.wowhead.com/quest=39946/right-tool-for-the-job)
17. [Not So Complex?](https://www.wowhead.com/quest=39947/not-so-complex)
18. [Ancient Vrykul Mastered](https://www.wowhead.com/quest=40052/ancient-vrykul-mastered)

Nivel 106
19. [The Ink Flows](https://www.wowhead.com/quest=39948/the-ink-flows)
20. [Once a Scribe Like You](https://www.wowhead.com/quest=39949/once-a-scribe-like-you)
21. [An Odd Trinket](https://www.wowhead.com/quest=39950/an-odd-trinket)
22. [Halls of Valor: Vision of Valor](https://www.wowhead.com/quest=39953/halls-of-valor-vision-of-valor)

Nivel 108
23. [Mass Milling Techniques](https://www.wowhead.com/quest=39954/mass-milling-techniques)
24. [An Embarrassing Revelation](https://www.wowhead.com/quest=39961/an-embarrassing-revelation)
25. [The Plot Thickens](https://www.wowhead.com/quest=39955/the-plot-thickens) Lado Alianza / [The Plot Thickens](https://www.wowhead.com/quest=39959/the-plot-thickens) Lado Horda
26. [The Legacy Passed On](https://www.wowhead.com/quest=39956/the-legacy-passed-on) Lado Alianza / [The Legacy Passed On](https://www.wowhead.com/quest=39960/the-legacy-passed-on) Lado Horda

Nivel 110
27. [Demon Ink](https://www.wowhead.com/quest=39957/demon-ink)

estas misiones se obtienen al moler hierbas (mejorar el drop de los Objetos de misiones)

<html>
<body>

Hierba |  Objeto de misión | Misión
-- | -- | --
 [ Aethril](https://www.wowhead.com/item=124101/aethril)  | [ Cristal Aethrem](https://www.wowhead.com/item=136909/aethrem-crystal) | [Aethrem Crystal](https://www.wowhead.com/quest=39942/aethrem-crystal)
 [ hojasueño](https://www.wowhead.com/item=124102/dreamleaf)  | [ Vaina de pesadilla abultada](https://www.wowhead.com/item=136912/bulging-nightmare-pod) | [Bulging Nightmare Pod](https://www.wowhead.com/quest=40062/bulging-nightmare-pod)
  [ flor de raposa](https://www.wowhead.com/item=124103/foxflower) |  [ Racimo de semillas leñosas](https://www.wowhead.com/item=136915/woody-seed-cluster) |   [Woody Seed Cluster](https://www.wowhead.com/quest=40064/woody-seed-cluster)
 [ Fjarnskaggl](https://www.wowhead.com/item=124104/fjarnskaggl) |  [Fjarnsk](https://www.wowhead.com/item=136916/fjarnsk)  | [Fjarnsk](https://www.wowhead.com/quest=40065/fjarnsk)
 [ Rosa luz de las estrellas](https://www.wowhead.com/item=124105/starlight-rose) | [ Esencia de rosada](https://www.wowhead.com/item=136917/roseate-essence) | [Roseate Essence](https://www.wowhead.com/quest=39951/roseate-essence)
 [ Felwort](https://www.wowhead.com/item=124106/felwort) |  [ Esencia Cetrina](https://www.wowhead.com/item=136918/sallow-essence) | [Sallow Essence](https://www.wowhead.com/quest=39952/sallow-essence)

</body>
</html>

mas informacion: https://wowpedia.fandom.com/wiki/Inscription_quests

**Comment by Noahkrr** [comment]
Moler en masa
- [Moler flor de raposa a granel](https://www.wowhead.com/spell=209660/mass-mill-foxflower) se obtiene entre  10-8 [Pigmento rosado](https://www.wowhead.com/item=129032/roseate-pigment), 6-4 [Pigmento cetrino](https://www.wowhead.com/item=129034/sallow-pigment) y 15-12  [Semilla de Yseralina](https://www.wowhead.com/item=128304/yseralline-seed)
- [Moler semillas de yseralina a granel](https://www.wowhead.com/spell=210116/mass-mill-yseralline-seeds) se obtiene entre  6-4 [Pigmento rosado](https://www.wowhead.com/item=129032/roseate-pigment) y 6-4 [Pigmento cetrino](https://www.wowhead.com/item=129034/sallow-pigment)
- [Moler Fjarnskaggl a granel](https://www.wowhead.com/spell=209661/mass-mill-fjarnskaggl) se obtiene entre  12-10 [Pigmento rosado](https://www.wowhead.com/item=129032/roseate-pigment), 6-4  [Pigmento cetrino](https://www.wowhead.com/item=129034/sallow-pigment) y 15-12  [Semilla de Yseralina](https://www.wowhead.com/item=128304/yseralline-seed)
- [Moler rosa luz estelar a granel](https://www.wowhead.com/spell=209662/mass-mill-starlight-rose) se obtiene entre 15-10 [pigmento rosado](https://www.wowhead.com/item=129032/roseate-pigment), 6-4 [Pigmento cetrino](https://www.wowhead.com/item=129034/sallow-pigment) y 15-12  [Semilla de Yseralina](https://www.wowhead.com/item=128304/yseralline-seed)
- [Moler matojo vil a granel](https://www.wowhead.com/spell=209664/mass-mill-felwort) se obtiene entre  10-8 [pigmento rosado](https://www.wowhead.com/item=129032/roseate-pigment), 16-12 [Pigmento cetrino](https://www.wowhead.com/item=129034/sallow-pigment) y 15-12  [Semilla de Yseralina](https://www.wowhead.com/item=128304/yseralline-seed)
- [Moler aethril a granel](https://www.wowhead.com/spell=209658/mass-mill-aethril) se obtiene entre  10-8 [pigmento rosado](https://www.wowhead.com/item=129032/roseate-pigment), 16-12 [Pigmento cetrino](https://www.wowhead.com/item=129034/sallow-pigment), 15-12  [Semilla de Yseralina](https://www.wowhead.com/item=128304/yseralline-seed) y 12-8 [Trozo de gema](https://www.wowhead.com/item=129100/gem-chip)
- [Moler frondasueño a granel](https://www.wowhead.com/spell=209659/mass-mill-dreamleaf) se obtiene entre  10-8 [pigmento rosado](https://www.wowhead.com/item=129032/roseate-pigment), 6-4 [Pigmento cetrino](https://www.wowhead.com/item=129034/sallow-pigment), 15-12  [Semilla de Yseralina](https://www.wowhead.com/item=128304/yseralline-seed) y [Vaina de pesadilla](https://www.wowhead.com/item=136926/nightmare-pod)
- [Moler Gloria Astral a granel](https://www.wowhead.com/spell=247861/mass-mill-astral-glory) se obtiene entre  10-8 [pigmento rosado](https://www.wowhead.com/item=129032/roseate-pigment), 6-4 [Pigmento cetrino](https://www.wowhead.com/item=129034/sallow-pigment), 15-12  [Semilla de Yseralina](https://www.wowhead.com/item=128304/yseralline-seed) y 12-8 [Trozo de gema](https://www.wowhead.com/item=129100/gem-chip)

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
