### ISSUE TITLE
An npc disappears

### ISSUE THREAD

**Issue by Luismafury** [GuabinaCore/WoWKoi#3797]
**Links:** https://youtu.be/8Pbxr-bzgAY

- from WoWHead or our Armory https://es.wowhead.com/quest=37449/revelaciones-oscuras / https://www.wowhead.com/quest=37449/dark-revelations

**What is happening:** The npc disappears when almost reaching the destination of the quest

**What should happen:** And therefore the quest cannot be done

**Comment by Cefiro-Caecias** [comment]
Fixed.
