### ISSUE TITLE
[Saitama] - Murderous Efficiency - Frost Death Knight talent.

### ISSUE THREAD

**Issue by Drathnor** [GuabinaCore/WoWKoi#38]
**Links:**

https://www.wowhead.com/spell=207061/murderous-efficiency
https://www.wowhead.com/spell=51128/killing-machine
https://www.wowhead.com/spell=49020/obliterate

**What is happening:**
Consuming a Killing Machine never grants 1 Rune.

**What should happen:**

Consuming the Killing Machine effect has a 50% chance to grant you 1 Rune.

**Comment by login6710** [comment]
Fixed
