### ISSUE TITLE
Redridge Mountains Loremaster

### ISSUE THREAD

**Issue by JadedNate** [GuabinaCore/WoWKoi#380]
https://www.wowhead.com/achievement=4902/redridge-mountains-quests

**What is happening:**
Quests do not give the player credit once completing a storyline.

**What should happen:**
Player should finish quests in a storyline to gain credit towards the zone's achievement

**Comment by Cefiro-Caecias** [comment]
You must be missing some quest. The map was tested and Achievement is obtainable.

**Comment by JadedNate** [comment]
I have done every available quest in Redridge (0/3), Westfall (0/3), Duskwood (0/5), and Northern Stranglethorn Vale (0/3) and I have been given no credit for any questlines.
