### ISSUE TITLE
Arqueologia 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3800]
**Links:**

from WoWHead or our Armory

**What is happening:**

Kalimdor & Eastern Kingdoms

Draenor
https://www.wowhead.com/object=234105/arakkoa-archaeology-find
[Arakkoa Cipher](https://www.wowhead.com/item=109585/arakkoa-cipher) este item no funciona para obtener artefactos
![image](https://user-images.githubusercontent.com/81131460/172906862-9b0f4995-68bc-4478-b81a-fdc51802339a.png)
no genera nada, solo funciona con fragmentos

otro problema es cuando descubres restos arqueológicos, estos aparecen debajo del Pj, lo cual es un problema aveces obtengo vasijas y mi pj queda atrapado, como deberia funcionar: uno descubre restos arqueológico estos aparecen frente del Pj no debajo.
![image](https://user-images.githubusercontent.com/81131460/172907920-b670e3e5-632b-4ca7-a447-1ffb9fc69025.png)

Otro problema son las excavaciones en Legion, normalmente cuando aprendes arqueología, ya puedes ver las excavaciones. Eso no sucede, tuve que  aprender  excarvar desde el contenido antiguo y completar los 700/700 para visualizar las excavaciones en legion y aprender arqueologia legion en dalaran, mi profesion subio de 700/750, deberia haber subido  de 700/800 o de 1/800.

no deberia aprender arqueologia en legion con el instructor de dalaran, debo obtener [Cuaderno del excavador](https://www.wowhead.com/item=136419/excavators-notebook) al excarvar en las islas abruptas con un drop del 100% (las excavaciones de arqueologia en legion estan disponibles desde el nivel 1 de arqueologia osea 1/75 ..)

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update,
