### ISSUE TITLE
[DB - Arthas] - Warlock Campaign quest Bugged: Summoning the Sisters

### ISSUE THREAD

**Issue by Treisand** [GuabinaCore/WoWKoi#3801]
**Links: https://www.wowhead.com/quest=41795/summoning-the-sisters**

from WoWHead or our Armory

**What is happening: when i use the portal, i get transported to the place i'm supposed to be, but i get stunned and after a few seconds i get teleported back to Dalaran. Happens every time**

**What should happen: Should be able to talk to Ritssyn Flamescowl and complete the ritual to subdue the sisters**

**Comment by Cefiro-Caecias** [comment]
Fixed.
