### ISSUE TITLE
Suramar masquerade mask keeps disappearing

### ISSUE THREAD

**Issue by Likander** [GuabinaCore/WoWKoi#3802]
**Links:**

[from WoWHead or our Armory](https://www.wowhead.com/spell=211086/masquerade#reward-from-q)

**What is happening:**
Masquerade mask to travel in suramar without being attacked keeps disappearing and not coming back, or not working at all. Sometimes when running through the city near demons it turns off on it's own, which isn't supposed to happen since they aren't detectors.

**What should happen:**
Mask only despawns after being  dispelled from attacking or from remaining in orbists range too long. Should be able to travers entire city and past demons under disguise.

**Comment by Cefiro-Caecias** [comment]
Fixed.
