### ISSUE TITLE
[Quest] [Zone] Arcane Thirst

### ISSUE THREAD

**Issue by bastian-brito** [GuabinaCore/WoWKoi#3805]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=40009/arcane-thirst
**What is happening:**

NPC from later phases are present in Shal'Aran, in first encounter

Vanthir - ID 107598
First Arcanist Thalyssra - ID 112146
Valewalker Farodin - ID 107126

![imagen](https://user-images.githubusercontent.com/72405110/171227770-0af012d8-afcf-4d45-bd15-e459852a1247.png)

Also, 2 portals are open, to Falanar and The Waning Crescent

![imagen](https://user-images.githubusercontent.com/72405110/171228872-dca33a86-826c-4d99-b292-31daae0dc108.png)

**What should happen:**

Only enemies should be seen, and no portal yet

**Comment by MrDeadNoob** [comment]
not the small ones normaly they also makes a lot of damage

**Comment by Cefiro-Caecias** [comment]
For now, those NPCs will be phased out, until I fully rebuild Shal'Aran. For the rest, fixed the quest "Arcane Thirst", and fixed the damage of the NPCs "Ancient Keeper"; available in the next update.
