### ISSUE TITLE
Heirloom pants are missing from the guild vendor

### ISSUE THREAD

**Issue by Likander** [GuabinaCore/WoWKoi#3808]
**Links:**

https://www.wowhead.com/item=122254/stained-shadowcraft-pants?bonus=0

**What is happening:**
All heirloom pants are missing from the guild vendor and are thus unobtainable.
![heirloom pants](https://user-images.githubusercontent.com/104089230/172041593-5bd6c4a1-620c-4039-bc4d-c7373ba6a7b4.png)

**What should happen:**
Heirloom pants should be available for purchase from guild vendors.

**Comment by Cefiro-Caecias** [comment]
There is no bug present. The item is found in vendors. Check the options to show all items without Class or Specialization filters.
