### ISSUE TITLE
[DB] - The God-Queen's Fury

### ISSUE THREAD

**Issue by Paldauf** [GuabinaCore/WoWKoi#3811]
**Links:**

[from WoWHead or our Armory](https://www.wowhead.com/quest=45526/the-god-queens-fury)
https://www.wowhead.com/quest=45527/eyirs-forgiveness

**What is happening:**
When you want to "Complete the Quest" after Completing you cannot, cuz the NPC where need to be finished not spawned

**What should happen:**
https://www.youtube.com/watch?v=84x_TsHtcuY

**Comment by Cefiro-Caecias** [comment]
Fixed.
