### ISSUE TITLE
Druida - Misiones 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3812]
https://www.wowhead.com/spell=783/travel-form

al estar modo volador y cruzar un portal, y apareces al  otro lado en otro escenario, tu forma de viaje esta activa pero apareces en forma humana (he notado que el problema solo ocurre en escenarios donde puedes volar , tu forma voladora cambia a forma terrestre al ingresar a mazmorra, porque en mazmorra no esta permitido)

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=106288/sylvan-bear
estos osos al atacarles no responden te ignoran, deberian atacarte porque son npc hostiles

**Comment by Noahkrr** [comment]
https://www.wowhead.com/quest=42430/the-fangs-of-ashamane
la gesta artefacto del druida feral esta bug, en la fase 1 me pide seguir el rastro pero no se ve ningún rastro, en la fase 2 al activar el primer  pilar me completa credio, deberia activar ambos cristales para que cuente credito , en la fase 3 la plataforma no funciona, no me deja continuar la gesta

**Comment by Cefiro-Caecias** [comment]
1) Spell Travel Form: Derivado a los Devs de Core.

2) NPC Nightmare Lasher: reparado.

3) Portal de colina pardas: hasta donde sé, es sólo decorativo.

4) NPC Sylvan Bear: reparado.

5) Quest The Fangs of Ashamane: 

*Fase 1: lo de seguir el rastro no lo pude reproducir visualmente por falta de datos, aunque por fortuna no presenta mayores complicaciones, ya que sólo hay una ruta posible para seguir.

*Fase 2: si bien es cierto que completa el crédito, no pasa a la Fase 3 hasta no tocar ambos pilares, y sólo entonces se abre la puerta.

*Fase 3: reparado.

Todo disponible en el próximo update.
