### ISSUE TITLE
[Shaman] - Gathering the Storms Scenario

### ISSUE THREAD

**Issue by Dorlionn** [GuabinaCore/WoWKoi#3815]
**Links:**

[from WoWHead or our Armory](https://www.wowhead.com/quest=46792/gathering-of-the-storms#:~:text=Once%20you%20have%20achieved%20the,by%20completing%20the%20BrokenShore%20Questline.&text=Carried%20On%20the%20Wind%20has,of%20the%20Storms%20quest%2Fscenario.&text=Be%20sure%20to%20interrupt%20them%20as%20much%20as%20possible.)

**What is happening:**
Can't atack to mob

**What should happen:**
Can atack to mob

**Comment by Cefiro-Caecias** [comment]
It will be fixed later.
