### ISSUE TITLE
[Hunter] Eagle to hall class available only with artifact weapon equiped

### ISSUE THREAD

**Issue by bastian-brito** [GuabinaCore/WoWKoi#3816]
**Links:**
https://es.wowhead.com/npc=108868/talua
https://www.wowhead.com/item=128826/thasdorah-legacy-of-the-windrunners
https://www.wowhead.com/item=128808/talonclaw
https://www.wowhead.com/item=128861/titanstrike
from WoWHead or our Armory

**What is happening:**
The option to fly to the Hunter Class Hall is only available if a hunter artifact weapon is equiped. Unequiped or other weapon equiped (like the fishing artifact in my case when it happened) blocks the dialog option
![image](https://user-images.githubusercontent.com/72405110/174446736-43ead02d-af84-4ed6-bd89-28f973c7edcc.png)
![image](https://user-images.githubusercontent.com/72405110/174446749-8faf0113-12d4-4793-8b19-9b9a8c980de2.png)
![image](https://user-images.githubusercontent.com/72405110/174446764-76a77533-0b95-4f8b-a3ff-42f56e9b0be8.png)

**What should happen:**

The dialog option should be tied to the class of the character, not the equiped weapon

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update. His flight option will be available after you have turned in the quest "On Eagle's Wings" (40953).
