### ISSUE TITLE
[Core] - Priest Shadowfiend

### ISSUE THREAD

**Issue by Jeezuss69** [GuabinaCore/WoWKoi#382]
So it seems this mechanic isn't functioning really at all, faults in the below;

Spawning of the add for me has been inconsistent, could be a map thing and it spawning within textures that I couldn't see or just not spawning. On retail spawning this add, gives you a pet control bar so you can set it to attack specific targets within the 12sec window it's alive.

Second issue, when it did spawn, the add simply didn't move. Just stayed still in the spaw it was summoned and then faded away.

Reason why this mechanic is important for discipline priests is that in heavy damage windows or when assigned a time to ramp up attonement spread to then dps and raid heal this shadowfiends attacks count for dmg done = healing via attonement. Without it, it's a significant nerf to the viability of disc priest. 

I have cutting edge raiding experience as a disc in Legion + BFA (Mechanics have barely changed on it except for lights wrath removal and the odd talent change).

Thanks

**Comment by ShikoSCS** [comment]
Fixed
