### ISSUE TITLE
[Core] - Loot: ítem Dedos de Necrófago

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3822]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/item=1314/ghoul-fingers
este ítem caen en el loot del jefe final de todas las mazmorras en cualquier dificultad(normal, heroico, mítico 0), incluso caen en cofres de miticas + y  también caen  en el cofre semanal. No deberíamos recibir dicho Ítem

![wrwr](https://user-images.githubusercontent.com/81131460/175434849-485592a7-4c3f-4e25-86f5-74e4b27e0078.PNG)

otro problema es el error de combate, luego de matar muchos adds o jefes , el PJ se queda en combate, quizás sucede por los spell que lanzamos hacia el jefe, porque los jefes al estar como aliados tiene los spell activos que nosotros les lanzamos

otro problema son las llaves al actualizarse a si misma, ejemplo hacemos una llave Arboleda corazón oscuro m+4 y la completamos con exito y la llave sube +2 o+3, la llave se actualiza a la misma llave, osea ahora tenemos una llave Arboleda corazón oscuro  m+6, al salir de la mazmorra y entrar, ponemos la llave  y logramos entrar a la mitica+, pero no jefes y adds, debería reiniciarse automáticamente la mazmorra  e iniciar la llave m+6

**Comment by Cefiro-Caecias** [comment]
No tiene sentido: ese item sólo lo tiene asignado un mob en su loot. Da la impresión que el sistema no lee bien el item -1314, que es la currency Lingering Soul Fragment, como si estuviera obviando el valor negativo :O

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
