### ISSUE TITLE
totem del trueno 

### ISSUE THREAD

**Issue by Kprtn** [GuabinaCore/WoWKoi#3824]
**Links:**

from WoWHead or our Armory

**What is happening:**

Desde hace un par de semanas siempre que voy a totem del trueno está lleno de mobs que no deberían estar allí pues no la wq de "limpiar totem del trueno"  (o somo sea que se llame no está activa 

![WoWScrnShot_061522_201747](https://user-images.githubusercontent.com/96433337/175780336-bd8b7f91-4f37-4194-b815-4814f955a601.jpg)

**What should happen:**
totem del trueno debería estar libre de mobs excepto cuando la wq esté activa

**Comment by Cefiro-Caecias** [comment]
Aparentemente ya está resuelto.

**Comment by Kprtn** [comment]
sigue igual :p
