### ISSUE TITLE
Ingenieria de legión - a recargar pilas

### ISSUE THREAD

**Issue by Kprtn** [GuabinaCore/WoWKoi#3825]
**Links:**
https://es.wowhead.com/quest=46128/a-recargar-pilas

from WoWHead or our Armory

**What is happening:**
no me dan la misión
![WoWScrnShot_062022_035549](https://user-images.githubusercontent.com/96433337/175780772-dd0bdd5a-ac21-48f5-af2f-5a735e109f7d.jpg)

**What should happen:**
deberían darme la  misión :)

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
