### ISSUE TITLE
ingenieria de legión - asunto aceitoso 

### ISSUE THREAD

**Issue by Kprtn** [GuabinaCore/WoWKoi#3826]
**Links:**
https://es.wowhead.com/quest=40881/asunto-aceitoso
from WoWHead or our Armory

**What is happening:**
no me dan la misión, y en la anterior no me dieron ningún item que llevarle a Didi

![WoWScrnShot_062022_035558](https://user-images.githubusercontent.com/96433337/175780948-1b6673ff-527e-453f-885f-3c5a07a41a06.jpg)

**What should happen:**
debería haber recibido algo que emseñarle a Didi en la anterior misión y Didi debería darme esta misión

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
