### ISSUE TITLE
npc 消失

### ISSUE THREAD

**Issue by 3525161** [GuabinaCore/WoWKoi#3827]
任务地点沙尔艾兰，
任务名称 魔瘾
任务章节击杀守护者塞兰提亚
任务NPC消失不见
![IE1Y$Z G})V}QGBYK_ ~3KW](https://user-images.githubusercontent.com/108309592/176060281-f6958441-6d2c-47b5-97d1-3539e278b6aa.png)

from WoWHead or our Armory

**What is happening:**

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
I'm sorry, I don't understand the language or the exposed problem.
