### ISSUE TITLE
见证伊利丹的觉醒

### ISSUE THREAD

**Issue by 3525161** [GuabinaCore/WoWKoi#3828]
**Links:**
任务不能完成
from WoWHead or our Armory
点了NPC没有反应
**What is happening:**

**What should happen:**
![KX89D4@TKD W(X9XZYNGQ14](https://user-images.githubusercontent.com/108309592/176060543-79e7e31a-9c59-4698-9db3-39105b026fd4.png)

**Comment by Cefiro-Caecias** [comment]
I'm sorry, I don't understand the language or the exposed problem.
