### ISSUE TITLE
[Core] - Druid talent Restoration affinity not giving enough health

### ISSUE THREAD

**Issue by Likander** [GuabinaCore/WoWKoi#3829]
**Links:**

[from WoWHead or our Armory](https://www.wowhead.com/spell=197492/restoration-affinity)

**What is happening:**
Druid talent Restoration affinity for Guardian druid heals 0.8% of maximum health every 5 seconds.

**What should happen:**
Heals you for 3% of your maximum health every 5 sec.
![WoWScrnShot_062922_031842](https://user-images.githubusercontent.com/104089230/176388976-48415f32-7724-43d7-b5ca-250accdbec21.jpg)

**Comment by Travven** [comment]
That talent is that way to guardian druids, bevause of the mastery. Will be too broken the full 3%. Also if you pay attention when you are out of bear form in guadian druid you get 1.5%.

Thanks for the report.
