### ISSUE TITLE
misión - Black Rook Hold: El Señor del Black Rook Hold

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3831]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=44276/black-rook-hold-the-lord-of-black-rook-hold
no obtengo credito, al matar al demonio [Latosius](https://www.wowhead.com/npc=98970/latosius)

**Comment by Cefiro-Caecias** [comment]
Reparada. Disponible en el próximo update.
