### ISSUE TITLE
Druida - Misión - No me puedes robar el cielo

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3832]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=46319/you-cant-take-the-sky-from-me
no puedo continuar la fase 5 de la gesta, porque el npc [Thisalee Crow](https://www.wowhead.com/npc=120219/thisalee-crow)
no se mueve, al terminar la fase 4, esta npc deberia irse al acantilado y pedir ayuda de Aviana..
video: https://www.youtube.com/watch?v=9u9exjJ2v7g&t=208s

**Comment by Cefiro-Caecias** [comment]
Reparada. Disponible en el próximo update.

**Comment by Noahkrr** [comment]
el escenario sigue bugeandose en la fase 5, el npc aliado no se mueve y hay otro error, al morir no puedes recuperar tu cuerpo porque esta en el escenario, osea estas modo anima afuera del escenario sin poder revivir..
