### ISSUE TITLE
[Core] - Shaman Restoration: Set 2-piece from ToS does not work

### ISSUE THREAD

**Issue by Thandil** [GuabinaCore/WoWKoi#3833]
**Links:**

https://www.wowhead.com/item-set=1310/regalia-of-the-skybreaker

**What is happening:**
When the 2-piece of the shaman restoration Regalia of the Skybreaker from Tomb of Sargeras set is equipped, the buff does not work when it procs. The spell's initial heal is still dependent on user's critical strike and sometimes crits and sometimes does not. The HoT left on the player critically heals, but the initial heal does not.

**What should happen:**
Riptide should always critically heal when you have the 2-piece buff.

**Comment by Travven** [comment]
Hello.

Well, the 238115 Thronebreaker has a proc cooldown of 200 miliseconds, that is the reason why you see the proc activates for one attack.
So yes, it is intentional, to control the numbers lf ñroc of the spelm and not get OP.

Thanks for the report.

**Comment by Travven** [comment]
Fixed
