### ISSUE TITLE
Cementerio de barcos - Mision - Costa quebrada

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3834]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=46510/ship-graveyard
el objetivo  de la misión, no aparece en el mapa y tampoco esta la arqueta, que debería saquear para obtener el ítem de la misión

**Comment by Cefiro-Caecias** [comment]
Reparada, blizzlike. Disponible en el próximo update.
