### ISSUE TITLE
Profesión Herbolaria - Misiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3835]
**Links:**

from WoWHead or our Armory

**What is happening:**
Al aprender la profesion de Herbolesteria, podremos  saquear hierbas de 1-2 hierbas y 1-3 semillas de Yseralina
En el rango 3 de Felwort, desbloquearemos todas las semillas de todas las hierbas:
[ Fjarnskaggl](https://www.wowhead.com/item=124104/fjarnskaggl)
semilla [ Fjarnskaggl Seed](https://www.wowhead.com/item=129287/fjarnskaggl-seed)
[ Aethril](https://www.wowhead.com/item=124101/aethril)
semilla [ Aethril Seed](https://www.wowhead.com/item=129284/aethril-seed)
[ Foxflower](https://www.wowhead.com/item=124103/foxflower)
semilla [ Foxflower Seed](https://www.wowhead.com/item=129286/foxflower-seed)
[ Dreamleaf](https://www.wowhead.com/item=124102/dreamleaf)
semilla [ Dreamleaf Seed](https://www.wowhead.com/item=129285/dreamleaf-seed)
[ Felwort](https://www.wowhead.com/item=124106/felwort)
semilla [ Felwort Seed](https://www.wowhead.com/item=129289/felwort-seed)
[ Starlight Rose](https://www.wowhead.com/item=124105/starlight-rose)
semilla [ Starlight Rose Seed](https://www.wowhead.com/item=129288/starlight-rose-seed)

**Como obtener los rangos  de cada hierba**
[Aethril](https://www.wowhead.com/item=124101/aethril)
Rango 1: [ Aethril](https://www.wowhead.com/item=124101/aethril) : te enseña a recolectar aethril de manera más efectiva. (1-4 hierbas y 1-5 [Semilla de yseralina](https://www.wowhead.com/item=128304/yseralline-seed))
[ Muestra de Aethril](https://www.wowhead.com/spell=193292/aethril)  inicia una misión para llevar la muestra a Dalaran.
[ Spayed by the Spade](https://www.wowhead.com/quest=40014/spayed-by-the-spade) : Loot[ Pistilo prístino](https://www.wowhead.com/item=129128/pristine-pistil) y[ Estambre inoxidable](https://www.wowhead.com/item=129131/stainless-stamen) ; estos se encuentran naturalmente al recoger Aethril
Rango 2: [ Aethril](https://www.wowhead.com/spell=193293/aethril) : te enseña cómo encontrar materiales raros al recolectar aethril. (como la [ Sangre de Sargeras](https://www.wowhead.com/item=124124/blood-of-sargeras) x1)
[ Tiras de seda irregulares](https://www.wowhead.com/item=129135/ragged-strips-of-silk) inicia una misión para llevar la muestra a Dalaran.
[ La desesperación genera ingenio](https://www.wowhead.com/quest=40016/desperation-breeds-ingenuity) : Recoge 6[ tallos de Aethril masticados](https://www.wowhead.com/item=129153/chewed-aethril-stem) de Withered en Azsuna.
Rango 3: [ Aethril](https://www.wowhead.com/spell=193294/aethril) : Recolectar hierbas en las Islas Abruptas puede hacer que aparezcan hierbas adicionales. (también aumenta 1-6 hierbas y 1-6 [Semilla de yseralina](https://www.wowhead.com/item=128304/yseralline-seed) y tambien obtienes [ Sangre de Sargeras](https://www.wowhead.com/item=124124/blood-of-sargeras) x1)
Activado por la misión [ Un desliz de mano](https://www.wowhead.com/quest=40017/a-slip-of-the-hand)

[Frondasueño](https://www.wowhead.com/item=124102/dreamleaf)
Rango 1: [ Dreamleaf](https://www.wowhead.com/spell=193295/dreamleaf) : te enseña a recolectar dreamleaf de manera más efectiva. (1-4 hierbas y 1-5 [Semilla de yseralina](https://www.wowhead.com/item=128304/yseralline-seed))
[ Dreamleaf Sample](https://www.wowhead.com/item=129118/dreamleaf-sample) inicia una misión para llevar la muestra a Dalaran.
[ Una hierba](https://www.wowhead.com/quest=40019/an-empathetic-herb) empática: Obtén 15 hojas de ensueño sanas (plantas lilas) y 5 hojas de ensueño infestadas de plagas (de plantas corruptas)
Rango 2: [ Dreamleaf](https://www.wowhead.com/spell=193296/dreamleaf) : Te enseña cómo encontrar materiales raros cuando recolectas dreamleaf.
[ Blight-Twisted Herb](https://www.wowhead.com/item=129136/blight-twisted-herb) comienza una misión de entrega a Lorlathil
[ Una planta muerta es demasiada](https://www.wowhead.com/quest=40021/one-dead-plant-is-one-too-many) : Mata a 20 sátiros en Val'sharah.
Rango 3: [ Dreamleaf](https://www.wowhead.com/spell=193297/dreamleaf) : reúne aún más materiales de cada planta de dreamleaf. (también aumenta 1-6 hierbas y 1-6 [Semilla de yseralina](https://www.wowhead.com/item=128304/yseralline-seed) y tambien obtienes [ Sangre de Sargeras](https://www.wowhead.com/item=124124/blood-of-sargeras) x1)
[ Hierba asfixiada por la plaga](https://www.wowhead.com/item=129141/blight-choked-herb) comienza una misión de entrega
[ El](https://www.wowhead.com/quest=40023/the-last-straw) colmo :[ Mata a Tur'xoran](https://www.wowhead.com/npc=98142/turxoran) en Shala'nir.

[Matojo Vil](https://www.wowhead.com/item=124106/felwort)
Rango 1: [ Felwort](https://www.wowhead.com/spell=193307/felwort) : Reúne Felwort de manera más efectiva. ( 1-3 hierbas)
[ Muestra de hierba vil](https://www.wowhead.com/item=129122/felwort-sample) inicia una misión para llevar la muestra a Dalaran.
Rango 2: [ Felwort](https://www.wowhead.com/spell=193308/felwort) : encuentra materiales raros al recolectar Felwort. (obtienes [ Sangre de Sargeras](https://www.wowhead.com/item=124124/blood-of-sargeras) x1)
[ Análisis de Felwort](https://www.wowhead.com/quest=40041/felwort-analysis) : recupera notas de herboristería en Gorgrond, Un'goro y Sholazar Basin
Rango 3: [ Felwort](https://www.wowhead.com/spell=193309/felwort) : Reúne semillas de todas las hierbas de Broken Isles. (también aumenta 1-4 hierbas  y tambien obtienes [ Sangre de Sargeras](https://www.wowhead.com/item=124124/blood-of-sargeras) x1)
[ La Pesadilla Esmeralda: Dominio de Felwort](https://www.wowhead.com/quest=40042/the-emerald-nightmare-felwort-mastery) : Derrota[ a Cenarius](https://www.wowhead.com/npc=113534/cenarius) en la Pesadilla Esmeralda.

[ Fjarnskaggl](https://www.wowhead.com/item=124104/fjarnskaggl)
Rango 1: [ Fjarnskaggl](https://www.wowhead.com/spell=193301/fjarnskaggl) : Reúne fjarnskaggl de manera más efectiva. (1-4 hierbas y 1-5 [Semilla de yseralina](https://www.wowhead.com/item=128304/yseralline-seed))
[ Fjarnskaggl Sample](https://www.wowhead.com/item=129120/fjarnskaggl-sample) inicia una misión para llevar 20[ Fjarnskaggl](https://www.wowhead.com/item=124104/fjarnskaggl) a Dalaran.
Rango 2: [ Fjarnskaggl](https://www.wowhead.com/spell=193302/fjarnskaggl) : encuentra materiales raros al recolectar fjarnskaggl.
[ Paleta de cuerno de carnero](https://www.wowhead.com/item=129138/rams-horn-trowel) inicia una misión para llevar el objeto a Dalaran.
[ Vrykul Herblore](https://www.wowhead.com/quest=40031/vrykul-herblore) : recupera los tres tomos de herboristería en Stormheim.
Rango 3: [ Fjarnskaggl](https://www.wowhead.com/spell=193303/fjarnskaggl) : Monte rápidamente después de recolectar cualquier hierba en las Islas Abruptas. (también aumenta 1-6 hierbas y 1-6 [Semilla de yseralina](https://www.wowhead.com/item=128304/yseralline-seed) y tambien obtienes [ Sangre de Sargeras](https://www.wowhead.com/item=124124/blood-of-sargeras) x1)
[ Runed Journal Page](https://www.wowhead.com/item=129142/runed-journal-page) inicia una misión para devolver el objeto a Dalaran.
[ Fjarnskaggl](https://www.wowhead.com/quest=40033/fjarnskaggl) : lucha contra la élite después de invocarlo en Wind-Worn Cairn con 20[ Fjarnskaggl](https://www.wowhead.com/item=124104/fjarnskaggl)

[ flor de raposa](https://www.wowhead.com/item=124103/foxflower)
Rango 1: Flor de [ raposa](https://www.wowhead.com/spell=193298/foxflower) : Reúne flor de raposa con mayor eficacia. (1-4 hierbas y 1-5 [Semilla de yseralina](https://www.wowhead.com/item=128304/yseralline-seed))
[ Muestra de Flor raposa](https://www.wowhead.com/item=129119/foxflower-sample) de flor de raposa inicia una misión para llevar 20[ flores de raposa](https://www.wowhead.com/item=124103/foxflower) a Dalaran.
Rango 2: [ Foxflower](https://www.wowhead.com/spell=193299/foxflower) : encuentra materiales raros al recolectar foxflower.
[ Tallo de raposa mordisqueado](https://www.wowhead.com/item=129137/nibbled-foxflower-stem) inicia una misión para llevar el objeto a Dalaran.
[ Persigue al culpable](https://www.wowhead.com/quest=40026/chase-the-culprit) : Persigue al zorro y reúne 12[ pedacitos de flor de raposa masticada.](https://www.wowhead.com/item=129220/chewed-foxflower-bit)
Rango 3: flor de [ raposa](https://www.wowhead.com/spell=193300/foxflower) : reúne aún más materiales de cada planta de flor de raposa. (también aumenta 1-6 hierbas y 1-6 [Semilla de yseralina](https://www.wowhead.com/item=128304/yseralline-seed) y tambien obtienes [ Sangre de Sargeras](https://www.wowhead.com/item=124124/blood-of-sargeras) x1)
[ Foxflower Scent Gland](https://www.wowhead.com/item=129278/foxflower-scent-gland) inicia una misión para llevar a[ The Pied Picker](https://www.wowhead.com/quest=40028/the-pied-picker) a Dalaran.

[ Rosa luz de las estelar](https://www.wowhead.com/item=124105/starlight-rose)
Rango 1: [ Starlight Rose](https://www.wowhead.com/spell=193304/starlight-rose) : intentar recolectar una rosa starlight fallará con menos frecuencia. (1-2 hierbas y [Polvo de rosa luz estelar](http://es.wowhead.com/item=129121/polvo-de-rosa-luz-estelar) 75% de drop)
[ Starlight Rosedust](https://www.wowhead.com/item=129121/starlight-rosedust) inicia una misión para llevar el objeto a Dalaran.
[ The Gentlest Touch](https://www.wowhead.com/quest=40035/the-gentlest-touch) : Cosecha con éxito 15[ Starlight Rose](https://www.wowhead.com/item=124105/starlight-rose) .
Rango 2: [ Starlight Rose](https://www.wowhead.com/spell=193305/starlight-rose) : encuentra materiales raros al recolectar rosas starlight.
[ Empuñadura de pala enjoyada](https://www.wowhead.com/item=129140/jeweled-spade-handle) inicia una misión para llevar el objeto a Dalaran.
[ La espada de la pala](https://www.wowhead.com/quest=40037/the-spades-blade) : recupera[ la espada rota del herbolario](https://www.wowhead.com/item=129155/broken-herbalists-blade) en el Bastión de la Guardia Lunar.
Rango 3: [ Starlight Rose](https://www.wowhead.com/spell=193306/starlight-rose) : Intentar recolectar una rosa starlight siempre tendrá éxito. (1-3 hierbas  y [Polvo de rosa luz estelar](http://es.wowhead.com/item=129121/polvo-de-rosa-luz-estelar) 11% de drop)
[ Scribbled Ramblings](https://www.wowhead.com/item=129143/scribbled-ramblings) inicia una misión para llevar el objeto a Dalaran.
[ Caída de Tharillon](https://www.wowhead.com/quest=40039/tharillons-fall) : Usa 20[ Starlight Rosedust](https://www.wowhead.com/item=129158/starlight-rosedust) para convocar al[ herbolario Tharillon](https://www.wowhead.com/npc=98214/herbalist-tharillon)

**Comment by Cefiro-Caecias** [comment]
Voy poniendo comentarios de los avances, aunque no publicaré hasta terminar todo:

1) Beneficios de Rangos de Skill: no tengo herramientas en la DB para controlar que tengas mayor chance de drop, o que los items se dropeen en mayor cantidad. Eso es un sistema que debe ser creado por Core. Como solución temporal, el número de items de profesión que caerán serán de un mínimo de 1 y un máximo de 6, al azar.

2) Agregados los loots de Herboristería a los NPCs "Agronox" (117193), "Bilespray Lasher" (118716,121711), "Fulminating Lasher" (119978,121318), "Stranglevine Lasher" (119977) y "Vilebark Walker" (121569). 

3) Item [Muestra de Aethril](https://www.wowhead.com/spell=193292/aethril): sólo será dropeada si tienes aprendida Herboristería, y su chance de drop será del 15%.

4) Quest [Spayed by the Spade](https://www.wowhead.com/quest=40014/spayed-by-the-spade): reparado el drop de [Pistilo prístino](https://www.wowhead.com/item=129128/pristine-pistil) y [Estambre inoxidable](https://www.wowhead.com/item=129131/stainless-stamen), con chance del 15%.

5) Item [Tiras de seda irregulares](https://www.wowhead.com/item=129135/ragged-strips-of-silk): sólo será dropeada si tienes aprendido el Rango 1 de "Técnica de herboristería: aethril", y con chance del 15%.

6) Quest [La desesperación genera ingenio](https://www.wowhead.com/quest=40016/desperation-breeds-ingenuity): reparado el drop de los [Tallos de Aethril masticados](https://www.wowhead.com/item=129153/chewed-aethril-stem), y con chance del 15%.

**Comment by Cefiro-Caecias** [comment]
Reparado todo, disponible en el próximo update. Sólo quedan pendiente 2 puntos:

1) Beneficios de Rangos de Skill: no tengo herramientas en la DB para controlar que tengas mayor chance de drop, o que los items se dropeen en mayor cantidad. Eso es un sistema que debe ser creado por Core. Como solución temporal, el número de items de profesión que caerán serán de un mínimo de 1 y un máximo de 6, al azar.

2) Codificación de las Sangres de Sargeras,

**Comment by Cefiro-Caecias** [comment]
Terminado ^^
