### ISSUE TITLE
Herbolaria - Rango 3

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3836]
**Links:**

from WoWHead or our Armory

**What is happening:**
Frondasueño nivel 3
al picar nodos de frondasueño, tienes chances de invocar este npc [ Enredadera de pesadilla](www.wowhead.com/npc=98234/nightmare-creeper), que al matarlo obtienes [ Frondasueño](https://www.wowhead.com/item=124102/dreamleaf). (actualmente no aparecen los npcs)

Flor raposa nivel 3
al picar nodos de flor raposa, tenemos  chance de invocar un zorro(https://www.wowhead.com/npc=98235/frenzied-fox), este zorro al caminar invoca flores spell [Restos de flor raposa](https://www.wowhead.com/spell=193567/foxflower-scraps), estas flores al pasar encima de ellas, obtenemos [ Flor raposa](https://www.wowhead.com/item=124103/foxflower). (actualmente las flores desaparecen muy rapido y  tampoco funciona el botin de flores al pasar encima de las flores)
video: https://www.youtube.com/watch?v=IMKQXBt7ZEI&t=20s

Fjarnskaggl. nivel 3
al picar nodos de Fjarnskaggl, tenemos chance de obtener este buffo(https://www.wowhead.com/spell=227252/quick-mount) 

Aethril nivel 3 (https://www.wowhead.com/spell=193417/herbalism-technique-aethril-rank-3)
al picar nodos de Aethril tenemos chance de que aparezca otro nodo de aethril  (no he probado el spell, porque no puedo obtener la mision)
![image](https://user-images.githubusercontent.com/81131460/179907332-e9cab50a-3f10-473f-bcbf-9f0c11c95d6e.png)

https://www.wowhead.com/quest=40017/a-slip-of-the-hand
no  puedo obtener esta mision, se supone que al recolectar hierba de Aethril deberia poder obtener la mision que es autocompletable

**Comment by Cefiro-Caecias** [comment]
1) **Frondasueño Rango 3:** reparado; una vez hayas entregado la quest "La gota que colma el vaso" (40023) y obtenido el Rango 3, los nodos de Frondasueño tendrán un 15% de chance de invocar un "Trepador de la Pesadilla" (98234) cuando los despojas.

2) **Flor raposa Rango 3:** reparada; una vez hayas entregado la quest "El recolectista de Hamelín" (40028) y obtenido el Rango 3, los nodos de Flor raposa tendrán un 15% de chance de invocar un "Zorro demenciado" (98235) cuando los despojas, y recibirás materiales extra cada 2-3 segundos producto del camino de flores, incluso sin moverte, durante 6 segundos, hasta que el zorrito desaparezca.

3) **Fjarnskaggl Rango 3:** reparado; una vez hayas entregado la quest "Fjarnskaggl" (40033) y obtenido el Rango 3, los nodos de Fjarnskaggl tendrán un 15% de chance de castearte la spell "Montar rápido" (227252) cuando los despojas.

4) **Aethril Rango 3:** reparada; una vez hayas entregado la quest "Mano para las flores" (40017) y obtenido el Rango 3, los nodos de Aethril tendrán un 15% de chance de invocar un segundo nodo de Aethril cuando los despojas.

5) **Quest "Mano para las flores" (40017):** reparada; la recibirás la próxima vez que despojes un Aethril, y si ya has entregado la quest "La desesperación agudiza el ingenio" (40016).
