### ISSUE TITLE
Cant set hearthstone to skyfire triage camp in stormheim

### ISSUE THREAD

**Issue by Doxxy0** [GuabinaCore/WoWKoi#3838]
**Links:**
https://wowpedia.fandom.com/wiki/Skyfire_Triage_Camp
https://www.wowhead.com/npc=95889/commander-lorna-crowley
from WoWHead or our Armory

**What is happening:**
Nothing happens when i click on the npc
![image](https://user-images.githubusercontent.com/84509345/180284832-f309ef34-bac8-4324-85c2-15cfa7ddb0fc.png)

**What should happen:**
Ability to set hearthstone here

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
