### ISSUE TITLE
Shadow word : Void and Mind blast talent bug

### ISSUE THREAD

**Issue by GG-Tyga** [GuabinaCore/WoWKoi#3841]
**CLASS : PRIEST
SPEC : SHADOW**

**Links:**
https://wowpedia.fandom.com/wiki/Shadow_Word:_Void

Cannot post WoW head link as its banned in my country. Sorry

from WoWHead or our Armory

**What is happening:**
Currently When you select Talent "Shadow Word : Void" It does not replace Mind blast, Both spells are shown and are able to cast seperately

**What should happen:**
When you select " Shadow word : Void" talent, It should replace Mind blast.
![WoWScrnShot_072522_225740](https://user-images.githubusercontent.com/109982784/180838249-ab6dbf07-6d8e-4fa8-9a8e-85bb9e2884e6.jpg)

**Comment by bastian-brito** [comment]
The remplacement is added in BfA
![imagen](https://user-images.githubusercontent.com/72405110/180839081-e08752c6-71d0-4465-8849-c78573af0fb1.png)
working as intended
