### ISSUE TITLE
Misiones de profesión - creación de items legendarios

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3843]
**What is happening:**
Pre-requisitos:  tener en tu bolsa el item [Mención de artesano armero](https://www.wowhead.com/item=147451/armorcrafters-commendation), luego te diriges hacia el enano.

Esta cadena de Misiones se reinician cada semana (actualmente hay errores: en Peletería solo puede elegir un lego que puedas fabricar, el dialogo no aparece al reinicio de cada semana, lo cual no puedo crear otro lego, tambien las misiones de Herreria no aparecen).

**Sasteria**
Mision de entrada [Fashion History and a Philosophy of Style] (https://www.wowhead.com/quest=46804/fashion-history-and-a-philosophy-of-style) (esta misión es unica)

Desde aqui comienzas las misiones con un reinicio semanal (puedes hacer todas las misiones en un dia, pero si quieres volverla hacer las misiones tiene que pasar una semana para que esten disponibles)
1- [The Legend of the Threads](https://www.wowhead.com/quest=46678/the-legend-of-the-threads)(al completar esta misiones obtenermos las siguientes 4 misiones)
completar todo:
1.1 - [Drapings of the Ancients](https://www.wowhead.com/quest=46682/drapings-of-the-ancients) 
1.2 - [The Thread of Shadow](https://www.wowhead.com/quest=46679/the-thread-of-shadow) 
1.3 - [The Thread of Souls](https://www.wowhead.com/quest=46681/the-thread-of-souls) 
1.4 - [The Thread of Starlight](https://www.wowhead.com/quest=46680/the-thread-of-starlight)
una vez completado las 4 sub misiones obtendras esta ultima mision:
2- [Starweave and Shadowcloth](https://www.wowhead.com/quest=46683/starweave-and-shadowcloth)

**Peleteria**
En Peleteria tenemos opcion de crear 2 items legendarios

Mision de entrada [Fashion History and a Philosophy of Style] (esta mision es unica)
Desde aqui comienzas las misiones con un reinicio semanal (puedes hacer todas las misiones en un dia, pero si quieres volverla hacer las misiones tiene que pasar una semana para que esten disponibles)(https://www.wowhead.com/quest=46804/fashion-history-and-a-philosophy-of-style)  (no es semanal, es unica y una sola vez de puede hacer)
Dialogos originales:
Gossip I want to make leather boots.
 [[The Sentinel's Eternal Refuge]](https://wowpedia.fandom.com/wiki/The_Sentinel%27s_Eternal_Refuge)
Gossip I want to make chain mail gloves.
 [[Vigilance Perch]](https://wowpedia.fandom.com/wiki/Vigilance_Perch)
Are you certain this is what you want to make? You can only choose one legendary item to craft with this Armorcrafter's Commendation.
(Accept/Cancel)

Misiones de Botas de Cuero
Desde aqui comienzas las misiones con un reinicio semanal (puedes hacer todas las misiones en un dia, pero si quieres volverla hacer las misiones tiene que pasar una semana para que esten disponibles)
1- [The Legend of the Elderhide](https://www.wowhead.com/quest=46684/the-legend-of-the-elderhide) 
completar todo:
1.1 - [Leather of the Ancients](https://www.wowhead.com/quest=46688/leather-of-the-ancients) 
1.2 - [The Wisp and the Nightmare](https://www.wowhead.com/quest=46687/the-wisp-and-the-nightmare) 
1.3 - [The Wisp and the Sea](https://www.wowhead.com/quest=46686/the-wisp-and-the-sea) 
1.4 - [The Wisp and the Shadow](https://www.wowhead.com/quest=46685/the-wisp-and-the-shadow) 
una vez completado las 4 sub misiones obtendras esta ultima mision:
2- [Wisp Touched Elderhide](https://www.wowhead.com/quest=46689/wisp-touched-elderhide) 

Misiones de Manos de Malla
Desde aqui comienzas las misiones con un reinicio semanal (puedes hacer todas las misiones en un dia, pero si quieres volverla hacer las misiones tiene que pasar una semana para que esten disponibles)
1- [The Legend of the Wardenscale](https://www.wowhead.com/quest=46690/the-legend-of-the-wardenscale)
completar todo:
1.1 - [Mail of the Ancients](https://www.wowhead.com/quest=46694/mail-of-the-ancients) 
1.2 - [The Owl and the Dreadlord](https://www.wowhead.com/quest=46692/the-owl-and-the-dreadlord) 
1.3 - [The Owl and the Observer](https://www.wowhead.com/quest=46693/the-owl-and-the-observer) 
1.4 - [The Owl and the Traitor](https://www.wowhead.com/quest=46691/the-owl-and-the-traitor) 
una vez completado las 4 sub misiones obtendras esta ultima mision:
2- [Prime Wardenscale](https://www.wowhead.com/quest=46695/prime-wardenscale)

**Herreria**
Mision de entrada [Fashion History and a Philosophy of Style](https://www.wowhead.com/quest=46804/fashion-history-and-a-philosophy-of-style)  (esta mision es unica)
Desde aqui comienzas las misiones con un reinicio semanal (puedes hacer todas las misiones en un dia, pero si quieres volverla hacer las misiones tiene que pasar una semana para que esten disponibles)
1- [The Legend of the Four Hammers](https://www.wowhead.com/quest=46696/the-legend-of-the-four-hammers) 
completar todo:
1.1 - [Armor of the Ancients](https://www.wowhead.com/quest=46700/armor-of-the-ancients) 
1.2 - [The Dragonhunter](https://www.wowhead.com/quest=46698/the-dragonhunter) 
1.3 - [The Godfighter](https://www.wowhead.com/quest=46697/the-godfighter) 
1.4 - [The Hellslayer](https://www.wowhead.com/quest=46699/the-hellslayer) 
 una vez completado las 4 sub misiones obtendras esta ultima mision:
2- [Hammer of Forgotten Heroes](https://www.wowhead.com/quest=46701/hammer-of-forgotten-heroes) 

mas informacion en: https://wowpedia.fandom.com/wiki/Eliezer_Hammerbeard

**Comment by Cefiro-Caecias** [comment]
Rerparadas. Disponibles en el próximo update.
