### ISSUE TITLE
Mazmorra - El Bastión violeta-Mazmorra - NPCs

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3844]
**Links:**

from WoWHead or our Armory

**What is happening:**
probado en todas sus dificultades:
https://www.wowhead.com/npc=102266/violet-hold-guard
los cuatro guardias de la mazmorra Bastion Violeta aparecen muertos y se mueven hacia la puerta
![image](https://user-images.githubusercontent.com/81131460/181876946-8cb34b7e-2742-4b6a-846c-b58cda39c9a4.png)

https://www.wowhead.com/npc=102269/felstalker-ravener
los canes invocados del portal, aparecen muertos y se mueven hacia la puerta

https://www.wowhead.com/npc=102616/millificent-manastorm
este jefe de mazmorra, al llegar ala fase 2, el npc escapa de la mazmorra y la gallina que invoca no es targeteable, lo cual hace imposible continuar la mazmorra y si logras matar al jefe, este dropea un item para un jugador y  los demas no pueden lotear

Los npc que salen de los portales y se dirigen hacia la puerta de la mazmorra, lo volando o traspasando estructuras..

**Comment by Cefiro-Caecias** [comment]
Reparadas. Disponible en el próximo update.

Lo de que los NPCs que salen de los portales caminan por el aire o atraviesan estructuras, quedará para más adelante.
