### ISSUE TITLE
Costa abrupta cofres

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3845]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowdb.com/objects/271554-veiled-wyrmtongue-chest
actualmente obtenemos 56 fragmentos del vació, deberíamos obtener 56-187 fragmentos y recursos de sede de 50-70 y tambien tiene posibilidad de obtener legendarios según la clase y especialización que poseas

https://www.wowdb.com/objects/271227-hidden-wyrmtongue-cache
actualmente obtenemos 56 fragmentos del vació, deberíamos obtener 56-98 fragmentos y recursos de sede de 30-50 y tambien tiene posibilidad de obtener legendarios según la clase y especialización que poseas

Cofres especiales  (actualmente el loot es fijo, deberia variar entre 1-100000)
https://www.wowdb.com/objects/268572-curious-wyrmtongue-cache
deberíamos obtener 1-50300 fragmentos del vació
https://www.wowdb.com/objects/268571-curious-wyrmtongue-cache
deberíamos obtener 1-100301 fragmentos del vació
https://www.wowdb.com/objects/268570-curious-wyrmtongue-cache
deberíamos obtener 1-50000 fragmentos del vació
https://www.wowdb.com/objects/268569-curious-wyrmtongue-cache
deberíamos obtener 1-100783 fragmentos del vació
https://www.wowdb.com/objects/268568-curious-wyrmtongue-cache
deberíamos obtener 1-100000 fragmentos del vació
https://www.wowdb.com/objects/268567-curious-wyrmtongue-cache
deberíamos obtener 1-50535 fragmentos del vació
https://www.wowdb.com/objects/268566-curious-wyrmtongue-cache
deberíamos obtener 1-50000 fragmentos del vació
https://www.wowdb.com/objects/268565-curious-wyrmtongue-cache
deberíamos obtener 1-51983 fragmentos del vació
https://www.wowdb.com/objects/268564-curious-wyrmtongue-cache
deberíamos obtener 1-100772 fragmentos del vació
https://www.wowdb.com/objects/268563-curious-wyrmtongue-cache
deberíamos obtener 1-50000 fragmentos del vació
https://www.wowdb.com/objects/268561-curious-wyrmtongue-cache
deberíamos obtener 1-103851 fragmentos del vació
https://www.wowdb.com/objects/268560-curious-wyrmtongue-cache
deberíamos obtener 1-100000 fragmentos del vació
https://www.wowdb.com/objects/268559-curious-wyrmtongue-cache
deberíamos obtener 1-51200 fragmentos del vació
https://www.wowdb.com/objects/268558-curious-wyrmtongue-cache
deberíamos obtener 1-51000 fragmentos del vació
https://www.wowdb.com/objects/268557-curious-wyrmtongue-cache
deberíamos obtener 1-100000 fragmentos del vació
https://www.wowdb.com/objects/268556-curious-wyrmtongue-cache
deberíamos obtener 1-100000 fragmentos del vació
https://www.wowdb.com/objects/268555-curious-wyrmtongue-cache
deberíamos obtener 1-100000 fragmentos del vació
https://www.wowdb.com/objects/268554-curious-wyrmtongue-cache
deberíamos obtener 1-100000 fragmentos del vació
https://www.wowdb.com/objects/268553-curious-wyrmtongue-cache
deberíamos obtener 1-50000 fragmentos del vació
https://www.wowdb.com/objects/268552-curious-wyrmtongue-cache
deberíamos obtener 1-50155 fragmentos del vació
https://www.wowdb.com/objects/268551-curious-wyrmtongue-cache
deberíamos obtener 1-50001 fragmentos del vació
https://www.wowdb.com/objects/268550-curious-wyrmtongue-cache
deberíamos obtener 1-51866 fragmentos del vació
https://www.wowdb.com/objects/268549-curious-wyrmtongue-cache
deberíamos obtener 1-50000 fragmentos del vació
https://www.wowdb.com/objects/268548-curious-wyrmtongue-cache
deberíamos obtener 1-100000 fragmentos del vació
https://www.wowdb.com/objects/268547-curious-wyrmtongue-cache
deberíamos obtener 1-50000 fragmentos del vació
https://www.wowdb.com/objects/268546-curious-wyrmtongue-cache
deberíamos obtener 1-100000 fragmentos del vació
https://www.wowdb.com/objects/268545-curious-wyrmtongue-cache
deberíamos obtener 1-100175 fragmentos del vació
https://www.wowdb.com/objects/268543-curious-wyrmtongue-cache
deberíamos obtener 1-100000 fragmentos del vació
https://www.wowdb.com/objects/268542-curious-wyrmtongue-cache
deberíamos obtener 1-100001 fragmentos del vació
https://www.wowdb.com/objects/268541-curious-wyrmtongue-cache
deberíamos obtener 1-101883 fragmentos del vació
https://www.wowdb.com/objects/268540-curious-wyrmtongue-cache
deberíamos obtener 1-52151 fragmentos del vació
https://www.wowdb.com/objects/268539-curious-wyrmtongue-cache
deberíamos obtener 1-50000 fragmentos del vació
https://www.wowdb.com/objects/268538-curious-wyrmtongue-cache
deberíamos obtener 1-100000 fragmentos del vació
https://www.wowdb.com/objects/268537-curious-wyrmtongue-cache
deberíamos obtener 1-100000 fragmentos del vació
https://www.wowdb.com/objects/268536-curious-wyrmtongue-cache
deberíamos obtener 1-50155 fragmentos del vació
https://www.wowdb.com/objects/268535-curious-wyrmtongue-cache
deberíamos obtener 1-50000 fragmentos del vació
https://www.wowdb.com/objects/268534-curious-wyrmtongue-cache
deberíamos obtener 1-100000 fragmentos del vació
https://www.wowdb.com/objects/268533-curious-wyrmtongue-cache
deberíamos obtener 1-51894 fragmentos del vació
https://www.wowdb.com/objects/268532-curious-wyrmtongue-cache
deberíamos obtener 1-100000 fragmentos del vació

**Comment by Cefiro-Caecias** [comment]
Reparados (por cierto, el sistema no acepta valores de 5 cifras, así que a los cofres que daban 100.000 Fragmentos del Vacío debí quitarles un dígito. Disponibles en el próximo update.
