### ISSUE TITLE
[Core] - WQs: Errores (Punto 3)

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3847]
1) Las WQs al ser completadas, los npcs del objetivo ya completado desaparecen,esto no se cumplen porque no desaparecen los npcs de dicho objetivo (esto sucede en casi todas las WQs): reparado.

2) Las WQs  expiran en un tiempo determinado y los npcs del objetivo de la WQs desaparecen con ello, esto no se cumple, la WQ desaparece del mapa pero los npcs siguen en la zona del mapa. (esto que genera que  en la zona haya muchos adds o tambien hace que cuando otra WQ aparezca en la misma zona, los npcs de dicha WQ no aparezcan que hay npcs de la anterior WQ): reparado.

3) Las WQs al no ser completadas a tiempo, estas expiran, pero al volver aparecer la WQs, esta tiene los creditos guardados, deberian ser reiniciarse, cuando vuelven aparecer las WQs no deberian tener progreso alguno.

**Comment by Cefiro-Caecias** [comment]
Reparados punto 1 y 2. El punto 3 es para Core.
