### ISSUE TITLE
[Core] - Spell Hunter: Dire frenzy

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3849]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://wowpedia.fandom.com/wiki/Dire_Frenzy
This spell does not work correctly, according to the description of the spell the pet must give 5 hits in a row but it only gives 3 hits..

**Comment by Noahkrr** [comment]
estos spell que compre en mi salon de clase, desaparecen del panel de hechizos, deberian ser permanentes
https://es.wowhead.com/spell=125050/buscar
este spell no funciona, mi mascota debería poder saquear los cadáveres cercanos
https://es.wowhead.com/spell=209997/hacerse-el-muerto
este spell funciona en la mascota, pero no funciona en Hati, debería funcionar en ambas mascotas.
y para despertar a la mascota usar el spell(https://es.wowhead.com/spell=210000/despertar), este spell también debería afectar a Hati

**Comment by Travven** [comment]
Fixed all spells
