### ISSUE TITLE
Misiones - Costa abrupta

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3850]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=46511/were-treasure-hunters
la misión funciona bien, pero en el mapa no aparece donde se encuentra el objetivo de la misión
https://www.wowhead.com/quest=46499/spiders-huh
la misión funciona bien, pero en el mapa no aparece donde se encuentra el objetivo de la misión
https://www.wowhead.com/quest=46744/greater-power-for-greater-threats
esta misión debe ser autocompletable
https://www.wowhead.com/quest=46239/fel-to-the-core (misión de brujo)
esta misión deber ser autocompletable(no funcionan los escenarios de invasión)

**Comment by Cefiro-Caecias** [comment]
Reparadas. Disponibles en el próximo update.
