### ISSUE TITLE
WQs - herbolesteria

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3851]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=41290/aqueous-aethril
la WQ aparece en el mapa, pero no hay objetivo al llegar al area de misión. la mision pide saquear 12
[Aqueous Aethril](https://www.wowhead.com/item=135480/aqueous-aethril) (items) de [Aqueous Aethril](https://www.wowhead.com/object=247865/aqueous-aethril)

https://www.wowhead.com/quest=41225/felwort (actualmente no se puede completar porque no aparecen) 
No aparece el objeto [Felwort](https://www.wowhead.com/object=244786/felwort) que debemos saquear y  tampoco aparece el npc [Festering Inquisitor](https://www.wowhead.com/npc=103643/festering-inquisitor) que custodia la hierba
![imagen_2022-08-17_155401234](https://user-images.githubusercontent.com/81131460/185241090-660b6bfc-c21d-4588-b02e-f4e2bacdbd53.png)

**Comment by Cefiro-Caecias** [comment]
No hay bug presente. Ambas quest funcionan, y los elementos de sus objetivos están presentes. Quizás el problema se deba al defecto de Core que no limpia las quests del Log.
