### ISSUE TITLE
[DB - Arthas] - Mistweaver Artifact Quest Bugged

### ISSUE THREAD

**Issue by CaptainCatastrophe** [GuabinaCore/WoWKoi#3854]
https://www.wowhead.com/quest=41003/the-emperors-gift

from WoWHead or our Armory

Stages 3 and 4 of this scenario are bugged as all but 1 of the NPCs meant to help combat are just standing around doing nothing making dealing with Aspersius HIGHLY annoying. His drown ability and fel slime minions make completing this quest without 30+ deaths impossible. 

Other NPCs should be participating in combat so that this quest goes much smoother.

**Comment by LKArthas** [comment]
Fixed with Today's Commit
