### ISSUE TITLE
Argus - npcs - misiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3856]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/npc=121319/buscadora-sombra-vil
los npc hostiles estan tirados en el piso y no se mueven, se les puede atacar
https://es.wowhead.com/npc=121324/maestro-de-canes
los npc hostiles estan tirados en el piso y no se mueven, se les puede atacar
https://es.wowhead.com/npc=121297/devorador-babeante
los npc hostiles estan tirados en el piso y no se mueven, se les puede atacar
https://es.wowhead.com/npc=126197/basilisco-colmillovil
los npc hostiles no se mueven, se les puede atacar
https://es.wowhead.com/npc=124278/marsuul-marcado-por-la-vileza
npc con aura de aliado, deberia ser un npc hostil
https://www.wowhead.com/item=152575/birth-of-the-urzul
este item esta bug no activa mision, deberían retirarlo del juego

https://es.wowhead.com/quest=48442/fuerte-de-nathraxas-preparativos
esta misión debería ser atucompletable, tengo los 6 seguidores ilv900 y no se completa..

https://es.wowhead.com/quest=48739/comandante-xethgar
no esta el npc(https://es.wowhead.com/npc=126910/comandante-xethgar) que deberia matar..

(Al moler actualmente no se obtiene nada)
Moler [Gloria Astral](https://es.wowhead.com/item=151565/gloria-astral), se obtiene entre 2-3 [pigmento rosado](https://www.wowhead.com/item=129032/roseate-pigment), 1-2 [Pigmento cetrino](https://www.wowhead.com/item=129034/sallow-pigment), 1-3 [Semilla de Yseralina](https://www.wowhead.com/item=128304/yseralline-seed) y 2-3 [Trozo de gema](https://www.wowhead.com/item=129100/gem-chip)

**Comment by Cefiro-Caecias** [comment]
Reparado todo. Disponible en el próximo update. Eliminado de la lista Vaxthul, ya que lo publicaste en el otro Issue.
