### ISSUE TITLE
Elite Rares - Argus

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3857]
**Links:**

from WoWHead or our Armory

**What is happening:**

calibrar estos rares ya que algunos no aparecen en mision de mundo. todos los npcs deberian estar en sus lugares
<html>
<body>

Nro | Elite rare | zona | ubicacion & coordenadas | video
-- | -- | -- | -- | --
1 | [Inquisidor Vethroz](https://www.wowhead.com/npc=126946/inquisitor-vethroz)	 | Baldío Antoran | 61.1 45.7 Inicio de ruta | https://www.youtube.com/watch?v=5dEgNhsBShM
2 | [Alquimista jefe Munculus](https://www.wowhead.com/npc=127376/chief-alchemist-munculus) | Baldío Antoran | 60.9 22.9 | https://www.youtube.com/watch?v=uVGWjSdZJwc
3 | [Talestra el Vil](https://www.wowhead.com/npc=123689/talestra-the-vile) | Krokuun | 55.5 80.2 | https://www.youtube.com/watch?v=viinnPeIoFE
4 | [Blistermaw](https://www.wowhead.com/npc=122958/blistermaw) | Baldío Antoran | 61.7 37.2  | https://www.youtube.com/watch?v=rD7VvYm0X5c
5 | [Maestro de asedio Voraan](https://www.wowhead.com/npc=120393/siegemaster-voraan) | Krokuun  | 58.0 74.8 | https://www.youtube.com/watch?v=k-E0GpNbSuU
6 | [Comandante de escuadrón Vishax](https://www.wowhead.com/npc=127700/squadron-commander-vishax) | 	Baldío Antoran | 77,4 74,9 (Portal) | https://www.youtube.com/watch?v=fvMY4xpPBSE
7 | [Tereck el Selector](https://www.wowhead.com/npc=124804/tereck-the-selector) | Krokuun | 69.6 57.5 | https://www.youtube.com/watch?v=D2cM2az1c_A
8 | [Escupidor de alquitrán](https://www.wowhead.com/npc=125479/tar-spitter) | Krokuun | 69.7 80.5 | 	https://www.youtube.com/watch?v=q6ma8ohX0hE
9 | [Vrax'thul](https://www.wowhead.com/npc=126199/vraxthul) | Baldío Antoran | 53.1 35.8 | https://www.youtube.com/watch?v=tfbPLPeErmo
10 | [Puscila](https://www.wowhead.com/npc=126040/puscilla) | Baldío Antoran | 65,6 26,6 Entrada | https://www.youtube.com/watch?v=coj1yHQzMkw
11 | [Noruega](https://www.wowhead.com/npc=126419/naroua) | Krokuun | 70.5 33.7 | https://www.youtube.com/watch?v=OTux6q76xCA
12 | [Comandante Vecaya](https://www.wowhead.com/npc=122911/commander-vecaya) | Krokuun | 42,0 57,1 (Ruta ascendente) | https://www.youtube.com/watch?v=_si45-S8c7Y
13 | [hermana subversia](https://www.wowhead.com/npc=123464/sister-subversia) | Krokuun | 53.4 30.9 | https://www.youtube.com/watch?v=tdpfMmcRras
14 | [Vaquero Kravos](https://www.wowhead.com/npc=126852/wrangler-kravos) | Mac'Aree | 55.7 59.9 | https://www.youtube.com/watch?v=soeVAWti44w
15 | [Barut el sanguinario](https://www.wowhead.com/npc=126862/baruut-the-bloodthirsty) | Mac'Aree | 43.8 60.2 | https://www.youtube.com/watch?v=S7owXC70chQ
16 | [ver a thanos](https://www.wowhead.com/npc=126865/vigilant-thanos) | Mac'Aree | 36.3 23.6 | https://www.youtube.com/watch?v=1dD5zDI-PVs
17 | [Aletaceleste colavenenosa](https://www.wowhead.com/npc=126867/venomtail-skyfin) | Mac'Aree | 33.7 47.5 | https://www.youtube.com/watch?v=HIiE0GNzMgE
18 | [Capitán Faruq](https://www.wowhead.com/npc=126869/captain-faruq) | Mac'Aree | 27.2 29.8 | https://www.youtube.com/watch?v=NiypAfia2gY
19 | [Ataxón](https://www.wowhead.com/npc=126887/ataxon) | Mac'Aree | 30.3 40.4 | https://www.youtube.com/watch?v=R6Ed5P48lJA
20 | [Heraldo del Caos](https://www.wowhead.com/npc=126896/herald-of-chaos) | Mac'Aree | 35,5 58,7 (segundo piso) | https://www.youtube.com/watch?v=1z7L5aJjVm8
21 | [Vorusk campeón de Jed'hin](https://www.wowhead.com/npc=126899/jedhin-champion-vorusk) | Mac'Aree | 48.5 40.9 | https://www.youtube.com/watch?v=LnLaYbiK9Yw
22 | [Overseer Y'Sorna](https://www.wowhead.com/npc=125497/overseer-ysorna) | Mac'Aree | 58.0 30.9 | https://www.youtube.com/watch?v=vpeM9PhNPdY
23 | [Instructora Tarahna](https://www.wowhead.com/npc=126900/instructor-tarahna) | Mac'Aree | 61.4 50.2 | https://www.youtube.com/watch?v=E3jVu2OygUo
24 | [Comandante Xethgar](https://www.wowhead.com/npc=126910/commander-xethgar) | Mac'Aree | 56.8 14.5 | https://www.youtube.com/watch?v=vMbrBS-MEds
25 | [Slithon el último](https://www.wowhead.com/npc=126913/slithon-the-last) | Mac'Aree | 49.5 52.8 | https://www.youtube.com/watch?v=N0FDs7FMiuI
26 | [Maestro de canes Kerrax](https://www.wowhead.com/npc=127288/houndmaster-kerrax) | Baldío Antoran | 63.1 25.2 Entrada | https://www.youtube.com/watch?v=Ugm9F2iCMuw
27 | [Vigilante Aival](https://www.wowhead.com/npc=127291/watcher-aival) | Baldío Antoran | 52.7 29.5 | https://www.youtube.com/watch?v=rwuUZ1MWWAw
28 | [Almirante Rel'var](https://www.wowhead.com/npc=127090/admiral-relvar) | Baldío Antoran | 73.2 70.8 | https://www.youtube.com/watch?v=GkhSFfzBSew
29 | [Todovidente Xanarian](https://www.wowhead.com/npc=127096/all-seer-xanarian) | Baldío Antoran | 75.6 56.5 | https://www.youtube.com/watch?v=SNKOq7Al8GY
30 | [Zapatero](https://www.wowhead.com/npc=126208/varga) | Baldío Antoran | 64.3 48.2 | https://www.youtube.com/watch?v=UDyNEGhzPuA
31 | [Skuul divisor de mundos](https://www.wowhead.com/npc=127118/worldsplitter-skuul) | Baldío Antoran | 50.9 55.3 | https://www.youtube.com/watch?v=o7FhyPm0LbI
32 | [Lanzador de sombras Voruun](https://www.wowhead.com/npc=122838/shadowcaster-voruun) | Mac'Aree | 44.6 71.6 | https://www.youtube.com/watch?v=5-rkbP1jU8A
33 | [Gar'zoth](https://www.wowhead.com/npc=122999/garzoth) | Baldío Antoran | 56.2 45.5 | https://www.youtube.com/watch?v=82Njpf1sIvQ
34 | [Señora Il'thendra](https://www.wowhead.com/npc=122947/mistress-ilthendra) | Baldío Antoran | 57,4 32,9 (Interior edificio) | https://www.youtube.com/watch?v=AmcfAf009Gk
35 | [Comandante Texlaz](https://www.wowhead.com/npc=127084/commander-texlaz) | Baldío Antoran | 80,5 62,8 (portal) | https://www.youtube.com/watch?v=6OGtEp78ujI
36 | [Doomcaster Suprax](https://www.wowhead.com/npc=127703/doomcaster-suprax) | Baldío Antoran | 58.1 12.4 (Runas) | https://www.youtube.com/watch?v=yJtvVAIs5A4
37 | [Rezira el Vidente](https://www.wowhead.com/npc=127706/rezira-the-seer) | Baldío Antoran | 65.4 81.5 (Se puede llegar solo con portal) | https://www.youtube.com/watch?v=u42yrtDlKTY
38 | [Vagath el traicionado](https://www.wowhead.com/npc=125388/vagath-the-betrayed) | Krokuun | 60.8 20.8 | https://www.youtube.com/watch?v=fvWBXZVNgLI
39 | [Diablillo Madre Laglath](https://www.wowhead.com/npc=125820/imp-mother-laglath) | Krokuun | 41.7 70.2 | https://www.youtube.com/watch?v=nCaAg6zU5Rs
40 | [Ven'orn](https://www.wowhead.com/npc=126115/venorn) | Baldío Antoran | 66.0 54.1 | https://www.youtube.com/watch?v=vNsJ4eqH2d0
41 | [Khazaduum](https://www.wowhead.com/npc=125824/khazaduum) | Krokuun | 50.3 17.3 (Entrada) | https://www.youtube.com/watch?v=DfIWDgKJ7J8
42 | [Comandante Sathrenael](https://www.wowhead.com/npc=122912/commander-sathrenael) | Krokuun | 33.0 76.0 | https://www.youtube.com/watch?v=9Bk657OefTc
43 | [Comandante Endaxis](https://www.wowhead.com/npc=124775/commander-endaxis) | Krokuun | 44.5 58.7 | https://www.youtube.com/watch?v=Cy1EPSEHB2w
44 | [Monstruosidad retorcida por el alma](https://www.wowhead.com/npc=126815/soultwisted-monstrosity) | Mac'Aree | 65.3 67.5 | https://www.youtube.com/watch?v=3YYsmoBsjKc
45 | [Kaara la pálida](https://www.wowhead.com/npc=126860/kaara-the-pale) | Mac'Aree | 38.7 55.8 | https://www.youtube.com/watch?v=B47nalE-LHo
46 | [Feasel el ladrón de muffins](https://www.wowhead.com/npc=126864/feasel-the-muffin-thief) | Mac'Aree | 41.3 11.6 | https://www.youtube.com/watch?v=rjHZlReH1hU
47 | [Curso Vigilante](https://www.wowhead.com/npc=126866/vigilant-kuro) | Mac'Aree | 63.8 64.6 | https://www.youtube.com/watch?v=7AP0k5EAzg4
48 | [Turek el Lúcido](https://www.wowhead.com/npc=126868/turek-the-lucid) | Mac'Aree | 39.2 66.6 | https://www.youtube.com/watch?v=brgTMAXnCtY
49 | [Umbraliss](https://www.wowhead.com/npc=126885/umbraliss) | Mac'Aree | 35.2 37.2 | https://www.youtube.com/watch?v=pDdhHbfBgj8
50 | [Sorolis la Maldita](https://www.wowhead.com/npc=126889/sorolis-the-ill-fated) | Mac'Aree | 70.4 46.7 | https://www.youtube.com/watch?v=x48C9lvDGDk
51 | [Saúl](https://www.wowhead.com/npc=126898/sabuul) | Mac'Aree | 44.2 49.8 | https://www.youtube.com/watch?v=ZdVGe28jpe0
52 | [Supervisor Y'Beda](https://www.wowhead.com/npc=124440/overseer-ybeda) | Mac'Aree | 59.2 37.7 | https://www.youtube.com/watch?v=rpLof6sL3kw
53 | [Overseer Y'Morna](https://www.wowhead.com/npc=125498/overseer-ymorna) | Mac'Aree | 60.4 29.7 | https://www.youtube.com/watch?v=XpDJLAOxCyE
54 | [Zul'tan the Numerous](https://www.wowhead.com/npc=126908/zultan-the-numerous) | Mac'Aree | 64.0 29.5 | https://www.youtube.com/watch?v=mw-Dcsdknak
55 | [Skreeg el Devorador](https://www.wowhead.com/npc=126912/skreeg-the-devourer) | Mac'Aree | 49.7 9.9 | https://www.youtube.com/watch?v=X1ZqJSv-UVI
56 | [Señor de la Ira Yarez](https://www.wowhead.com/npc=126338/wrath-lord-yarez) | Baldío Antoran | 61.9 64.3 | https://www.youtube.com/watch?v=CfQi0KnN4tY
57 | [Guardián del Vacío Valsuran](https://www.wowhead.com/npc=127300/void-warden-valsuran) | Baldío Antoran | 55.7 21.9 | https://www.youtube.com/watch?v=zs42geu3DBA
58 | [Teniente Hakar](https://www.wowhead.com/npc=126254/lieutenant-xakaar) | Baldío Antoran | 62.4 53.8	| https://www.youtube.com/watch?v=NZctAXqqMAo

</body>
</html>

https://es.wowhead.com/npc=127705/madre-rosula (segui los pasos pero no aparece el npc)
para invocar este ncp: Necesitas matar diablillos en la cueva para saquear [ Imp Meat](https://www.wowhead.com/item=152999/imp-meat), necesitas 100 para poder crear un [ festín repugnante](https://www.wowhead.com/item=153013/disgusting-feast) . Usa ese festín frente a su piscina y ella engendrará.
video: https://www.youtube.com/watch?v=PzdOfJyKLD8
rares que no he encontrados:

https://www.wowhead.com/npc=127581/the-many-faced-devourer (este npc esta funcional, no lo toquen)

**Comment by Cefiro-Caecias** [comment]
Reparados. Disponibles en el próximo update.
