### ISSUE TITLE
[DB] - Misiones del salon de clases 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3859]
**Links:**

from WoWHead or our Armory

**What is happening:**
Misiones del salon de clases para seguidores
ilv 950 (para acceder a estas misiones primero deberemos completar: https://es.wowhead.com/quest=48447/dispersión-de-la-guardia-de-las-sombras).

https://es.wowhead.com/mission=1704/antorus-el-trono-ardiente
https://es.wowhead.com/mission=1708/antorus-el-trono-ardiente
https://es.wowhead.com/mission=1709/antorus-el-trono-ardiente
https://es.wowhead.com/mission=1710/antorus-el-trono-ardiente
https://es.wowhead.com/mission=1762/exterminadores-de-demonios
https://es.wowhead.com/mission=1756/vigilantes-de-portal
https://es.wowhead.com/mission=1752/devolver-el-fuego
https://es.wowhead.com/mission=1767/dejarlos-secos
https://es.wowhead.com/mission=1786/zzthe-demon-hoard
https://es.wowhead.com/mission=1763/riquezas-repugnantes
https://es.wowhead.com/mission=1761/resistir-la-marea
https://es.wowhead.com/mission=1788/zza-citadels-plunder
https://es.wowhead.com/mission=1758/evitar-el-apocalipsis
https://es.wowhead.com/mission=1787/zzraiding-the-ruins
https://es.wowhead.com/mission=1816/crisol-de-los-espíritus
https://es.wowhead.com/mission=1768/heraldos-de-guerra
https://es.wowhead.com/mission=1791/zzjourney-to-the-core
https://es.wowhead.com/mission=1754/se-acabó-la-espera
https://es.wowhead.com/mission=1764/aflicción-de-los-lenguavermis
https://es.wowhead.com/mission=1815/la-profanación-del-círculo
https://es.wowhead.com/mission=1766/afianzar-nuestra-posición
https://es.wowhead.com/mission=1790/zzmemory-of-a-lost-city
https://es.wowhead.com/mission=1770/aumentar-nuestro-asalto
https://es.wowhead.com/mission=1759/una-grieta-en-la-armadura
https://es.wowhead.com/mission=1797/los-bajos-fondos-de-la-legión
https://es.wowhead.com/mission=1760/encuentro-fortuito
https://es.wowhead.com/mission=1765/reforzar-nuestras-defensas
https://es.wowhead.com/mission=1751/hacia-la-vileza
https://es.wowhead.com/mission=1789/zza-relic-of-argus
https://es.wowhead.com/mission=1753/ventaja-tecnológica
https://es.wowhead.com/mission=1769/liberar-a-los-encarcelados
https://es.wowhead.com/mission=1755/la-vanguardia-de-la-legión
https://es.wowhead.com/mission=1757/adversidades-abrumadoras
https://es.wowhead.com/mission=1796/la-esencia-del-maligno

ilv925(para acceder a estas misiones primero deberemos completar: https://es.wowhead.com/quest=48445/las-ruinas-de-oronaar).

https://es.wowhead.com/mission=1738/especie-esquiva
https://es.wowhead.com/mission=1800/minería-meteorítica
https://es.wowhead.com/mission=1745/vacío-o-no
https://es.wowhead.com/mission=1747/premonición-oscura
https://es.wowhead.com/mission=1734/a-toda-prisa
https://es.wowhead.com/mission=1750/tejido-de-la-realidad
https://es.wowhead.com/mission=1740/penumbra-creciente
https://es.wowhead.com/mission=1743/desentrañar-la-locura
https://es.wowhead.com/mission=1746/ecos-condenados
https://es.wowhead.com/mission=1737/suplicar-a-los-caídos
https://es.wowhead.com/mission=1741/vacío-aglomerado
https://es.wowhead.com/mission=1801/susurros-que-guían
https://es.wowhead.com/mission=1748/alteración-del-orden-público
https://es.wowhead.com/mission=1749/calmar-el-vacío
https://es.wowhead.com/mission=1832/alimentar-los-hornos
https://es.wowhead.com/mission=1739/delirante
https://es.wowhead.com/mission=1794/billete-de-ida
https://es.wowhead.com/mission=1773/armamento-consagrado
https://es.wowhead.com/mission=1795/lidiar-con-lo-vil
https://es.wowhead.com/mission=1742/recuerdos-de-los-perdidos
https://es.wowhead.com/mission=1744/antigüedades-de-argus
https://es.wowhead.com/mission=1731/su-emancipación
https://es.wowhead.com/mission=1732/preservar-la-memoria
https://es.wowhead.com/mission=1733/dudas-invasivas
https://es.wowhead.com/mission=1735/lejos-de-casa
https://es.wowhead.com/mission=1736/vaticinio

Misiones de Argus parche 7.3
ilv 900 (las misiones de Argus se desbloquean al completar: https://es.wowhead.com/quest=48441/restos-de-vértice-caída-oscura)

https://es.wowhead.com/mission=1798/un-mundo-agonizante
https://es.wowhead.com/mission=1725/finalizar-el-asedio
https://es.wowhead.com/mission=1777/armas-ancestrales
https://es.wowhead.com/mission=1772/armadura-de-los-eredar
https://es.wowhead.com/mission=1730/el-teorema-del-caos
https://es.wowhead.com/mission=1718/fuego-a-discreción
https://es.wowhead.com/mission=1723/adentrarse-en-el-abismo
https://es.wowhead.com/mission=1728/defensas-destruidas
https://es.wowhead.com/mission=1799/el-túnel-secreto
https://es.wowhead.com/mission=1779/protección-bendita
https://es.wowhead.com/mission=1716/el-espíritu-de-los-vengativos
https://es.wowhead.com/mission=1793/la-sangre-del-destructor
https://es.wowhead.com/mission=1724/escalar-los-riscos
https://es.wowhead.com/mission=1711/fragmento-vil-cristalizado
https://es.wowhead.com/mission=1726/sin-retirada
https://es.wowhead.com/mission=1774/aprovisionamiento-de-resistencia
https://es.wowhead.com/mission=1727/armas-grandes
https://es.wowhead.com/mission=1775/instrumentos-de-guerra
https://es.wowhead.com/mission=1713/maquinaciones-oscuras
https://es.wowhead.com/mission=1778/munición-santificada
https://es.wowhead.com/mission=1717/el-destino-de-los-caídos
https://es.wowhead.com/mission=1833/arsenal-abandonado
https://es.wowhead.com/mission=1720/atadura-vil
https://es.wowhead.com/mission=1721/atravesar-el-corazón
https://es.wowhead.com/mission=1722/maquinaria-vil
https://es.wowhead.com/mission=1712/reducirlos-en-número
https://es.wowhead.com/mission=1729/enterrado
https://es.wowhead.com/mission=1714/ha-llegado-la-justicia
https://es.wowhead.com/mission=1715/consecuencias-calamitosas
https://es.wowhead.com/mission=1719/fuga-de-la-legión
https://es.wowhead.com/mission=1792/el-poder-de-un-titán

islas abruptas (parche 7.2) no recuerdo que mision se debe completar para desbloquear estas misiones en el tablon de misiones de sede ..
https://es.wowhead.com/mission=1698/equipo-de-élite-alijo-de-suministros-de-la-legión
https://es.wowhead.com/mission=1699/equipo-de-élite-templo-perdido
https://es.wowhead.com/mission=1697/equipo-de-élite-el-sentinax
https://es.wowhead.com/mission=1604/la-legión-caerá
https://es.wowhead.com/mission=1647/acaba-con-ellos
https://es.wowhead.com/mission=1652/una-tribu-digna
https://es.wowhead.com/mission=1653/un-jarabe-pesado
https://es.wowhead.com/mission=1671/liberación
https://es.wowhead.com/mission=1658/amigos-en-lugares-altos
https://es.wowhead.com/mission=1648/bendiciones-de-la-noche
https://es.wowhead.com/mission=1645/gracias-demoníacas
https://es.wowhead.com/mission=1632/sigue-soñando
https://es.wowhead.com/mission=1668/nunca-más
https://es.wowhead.com/mission=1687/amigos-en-lugares-altos
https://es.wowhead.com/mission=1651/una-situación-escamante
https://es.wowhead.com/mission=1646/un-viaje-vil
https://es.wowhead.com/mission=1650/las-tierras-salvajes-de-azsuna
https://es.wowhead.com/mission=1587/misión-de-desafío
https://es.wowhead.com/mission=1631/lluvia-de-monedas
https://es.wowhead.com/mission=1649/tierra-de-promesas-rotas
https://es.wowhead.com/mission=1654/una-buena-tarde
https://es.wowhead.com/mission=1673/visiones-nubladas
https://es.wowhead.com/mission=1660/adiós-hasta-la-vista

**Comment by Noahkrr** [comment]
https://es.wowhead.com/quest=48911/vacunas-de-vacío (mision de reinicio semanal)
el npc [Nabiru](https://es.wowhead.com/npc=127037/nabiru) para entregar la mison no esta ..

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
