### ISSUE TITLE
Frost DK artifact traits

### ISSUE THREAD

**Issue by Trailchills** [GuabinaCore/WoWKoi#3860]
**https://www.wowdb.com/spells/238079-runic-chills:** **https://www.wowdb.com/spells/238115-thronebreaker:**

What should be happening is every mob hit with Frostscythe in a pack of mobs should lower cd on Sindragosa's Fury at least when hit every 2nd time bc 50% chance. From my testing based on previous experience in playing frost dk,  in a large pack of mobs ( 20-40) 
while using burst ( Obliteration ) the CD should lower down to 0 in less than 1 minute depending on the healthpool of the mobs

What is happening now, it seems that the above mentioned traits are affecting only the main target and not the rest of the pack, meaning the CD goes down very slowly

Thank you

**Comment by Noahkrr** [comment]
https://www.wowhead.com/spell=207230/frostscythe
https://www.wowhead.com/spell=190778/sindragosas-fury
https://www.wowhead.com/spell=207256/obliteration

**Comment by Trailchills** [comment]
> https://www.wowhead.com/spell=207230/frostscythe https://www.wowhead.com/spell=190778/sindragosas-fury https://www.wowhead.com/spell=207256/obliteration

wowhead is not available for me, sorry

**Comment by Travven** [comment]
Hello.

Well, the spell 238115 Thronebreaker has a proc cooldown of 200 miliseconds, that is the reason why you see the proc activates for one time.
So yes, it is intentional, to control the numbers of procs the spell does at once and not get OP.

Thanks for the report.
