### ISSUE TITLE
[DB] - Cofres Augari 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3861]
**Links:**

from WoWHead or our Armory

**What is happening:**
para abrir estos cofres se necesita tener activo el spell [Embozo de ecos arcanos](https://es.wowhead.com/spell=248779/embozo-de-ecos-arcanos) (actualmente, cuando usar el spell, la barra de carga comienza y cuando esta termina no deja abrir el cofre, sale mensaje "aun no puedes hacer eso",  no me deja saquear el cofre)
https://es.wowhead.com/object=277343/tesoro-augari-olvidado
https://es.wowhead.com/object=277344/recuerdos-augari-preciados
https://es.wowhead.com/object=277346/cofre-augari-desaparecido
https://es.wowhead.com/object=277342/bienes-augari (en el juego tiene otro nombre, deberia ser "Augari goods"o "bienes Augari")
https://es.wowhead.com/object=277327/cofre-con-runas-augari
https://es.wowhead.com/object=276227/alijo-secreto-augari

**Comment by Cefiro-Caecias** [comment]
Reparado el defecto de la spell, los cofres que no contaban para el logro, y el logro "Achievement: Shoot First, Loot Later (12074)". Disponibles en el próximo update.
