### ISSUE TITLE
Herbolesteria - Profesion

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3866]
**Links:**

from WoWHead or our Armory

**What is happening:**
la mecánica es la misma con menas picadas invocan basilicos, en este caso es, al recolectar hierbas tienes un 20% de invocar estos npcs, segun la hierba que recolectes:

https://es.wowhead.com/npc=98232/hambriento-marchito
al saquear [Aetril](https://es.wowhead.com/object=244774/aethril), tienes chance de generar este npc hostil

https://es.wowhead.com/npc=98233/hambriento-marchito
al saquear [Rosa luz estelar](https://es.wowhead.com/object=244778/rosa-luz-estelar), tienes chance de generar este npc hostil

https://es.wowhead.com/npc=98234/trepador-de-la-pesadilla
al saquear [Frondasueño](https://es.wowhead.com/object=244776/frondasueño), tienes chance de generar este npc hostil

https://es.wowhead.com/npc=98235/zorro-demenciado
al saquear [Flor raposa](https://es.wowhead.com/object=241641/flor-de-raposa), tienes chance de generar este npc hostil, este zorro correra y brotaran rosasque al pisarlas obtienes items en tu bolsa..

mas informacion: https://es.wowhead.com/legion-herbalism-guide

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible en el próximo update.
