### ISSUE TITLE
[Core] - Dungeon Catedral de la Noche Eterna: Spells

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3867]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/npc=119952/destructor-guardia-vil
el spell [Celeridad ardiente](https://es.wowhead.com/spell=237577/celeridad-ardiente) esta bug, se activa el spell, pero no es visible el domo de vileza y los npcs al moverse, nadan no caminan, ademas dicho spell se genera al entrar al domo que crea el npc [Portador vil Llamarada Infernal](www.wowhead.com/npc=118724/helblaze-felbringer)

https://es.wowhead.com/spell=240951/desenfreno-destructivo (corregido)
este spell tiene mucho rango, no debería haberme matado ya que no he salido del area donde esta el jefe... únicamente deberías morir si estas en el camino de hechizo, osea fuera de los anillos de la biblioteca
![imagen_2022-09-09_175517250](https://user-images.githubusercontent.com/81131460/189456196-0f7b9280-5a2a-42a6-ae63-3464cb425edf.png)

(corregido)
tampoco una hay barrera en la sala donde esta el npc [Nalasha](https://es.wowhead.com/npc=118705/nalasha) y las arañas, se supone que debemos matar  a ese minijefe y a las arañas para que la barrera desaparezca y asi podremos subir las escaleras para combatir contra los 2 jefes finales..
otro error: las puertas de entrada del escenario de los 3 ultimos jefes deberian estar cerradas cuando entro en combate.

https://es.wowhead.com/npc=118418/égida-de-aggramar
este objeto esta bug, al tomar el escudo y al hacer click en eliminar hechizo, el escudo se suelta de tu pj generando otro escudo(esto genera multiples escudos), solo debería haber un solo item, en caso de eliminar el spell no deberia generarse otro item escudo..

https://es.wowhead.com/npc=120792/illidan-tempestira
luego de matar al jefe final de la mazmorra, este npc al terminar sus diálogos con los demás npcs, debería tener un texto (Necesito que me saquen de aquí), al hacer click en el texto, somos teletransportados afuera, en la entrada de la mazmorra.

**Comment by Noahkrr** [comment]
(nunca es usado el spell presencia abrasado)
Tan pronto como aparezcan los [Guardianes de portal vil](https://www.wowhead.com/es/npc=121714/guardi%C3%A1n-de-portal-vil) , comenzarán a lanzar [ Presencia abrasadora](https://www.wowhead.com/es/spell=241609/presencia-abrasadora). Si el lanzamiento de 20 segundos se apaga, se generará un agregado de Señor supre

https://www.wowhead.com/es/spell=239268/tormenta-de-veneno (esta spell esta bug, es canalizado pero no hay daño y no hay animacion)
que es un cono frontal que inflige una gran cantidad de daño.

https://www.wowhead.com/es/spell=238656/ola-de-las-sombras (no funciona correctamente, ya que el spell cae a jugadores que se encuentran detrás del jefe)(sigue sin funcionar)
Este spell es un gran cono frontal que inflige una gran cantidad de daño a cualquier persona atrapada en su camino, mientras que también deja una sustancia pegajosa púrpura en el suelo que te inflige daño.

**Comment by Noahkrr** [comment]
Mephistroth mítico: (actualmente no funciona)
Durante la Fase Dos, los jugadores serán bombardeados por otros [Alatemibles](https://es.wowhead.com/npc=115024/alatemible) que vuelan a través de una ventana, lanzan [ Llamarada vil](https://es.wowhead.com/spell=239525/llamarada-vil) y luego salen volando por la otra.
Puede evitarlos simplemente saliendo de los círculos arremolinados en el suelo.

**Comment by Noahkrr** [comment]
(sigue sin funcionar)
[Agronox](https://www.wowhead.com/es/npc=117193/agronox) también invocará una o dos flores inalcanzables en las esquinas de la habitación. (esto no funciona, durante el combate no los invoca)
Las flores agarrarán a uno o dos jugadores cada uno y colocarán [Vides asfixiantes](https://www.wowhead.com/es/npc=120014/vides-asfixiantes) sobre ellos, lo que les causará un daño cada vez mayor hasta que el jugador afectado se aleje 20 yardas y rompa la cadena.

(ese spell no funciona)
[Agronox](https://www.wowhead.com/es/npc=117193/agronox) emitirá periódicamente [ Esporas venenosas](https://www.wowhead.com/es/spell=236524/esporas-venenosas) . Esto coloca una desventaja permanente en todo el grupo que inflige daño de tictac.
Esto actúa como un pseudoenfado en la pelea, ya que cada aplicación de [ Esporas venenosas](https://www.wowhead.com/es/spell=236524/esporas-venenosas) agregará otra acumulación de daño al grupo.

(tampoco se cumple) (modo mitico)  (no lo he visto funcionar)
Todos los agregados en mítico deben eliminarse lo antes posible, ya que [Agronox](https://www.wowhead.com/es/npc=117193/agronox) puede lanzar [ Infusión de la Naturaleza](https://www.wowhead.com/es/spell=242199/infusi%C3%B3n-de-la-naturaleza) , que drena la salud de cualquier planta y se cura a sí mismo por 0.75% cada segundo.


https://www.wowhead.com/es/npc=120727/libro-del-silencio-eterno
este npc no se puede destruir, deberia destruirse
https://www.wowhead.com/es/npc=120646/libro-de-monstruosidades-arcanas
este npc no se puede destruir, deberia destruirse
https://www.wowhead.com/es/npc=118718/libro-del-invierno-eterno
este npc no se puede destruir y tampoco desaparece, se supone que dura 30 segundos

**Comment by Travven** [comment]
Solucionados

**Comment by Noahkrr** [comment]
Gran trabajo casi todo funciona, pero algunos problemas persisten como:
https://www.wowhead.com/es/npc=118704/dulzak (este spell no funciona correctamente, si estamos de espalda al elite, dicho spell no deberia caernos, se supone que el lanzamiento es en forma de cono si no estas en tu direccion no deberia caerte)
Los jugadores deben estar atentos a la dirección a la que se enfrenta para poder esquivar la [ Ola de las Sombras](https://www.wowhead.com/es/spell=238656/ola-de-las-sombras) durante su lanzamiento.

www.wowhead.com/es/spell=236524/esporas-venenosas
este spell necesita un revision, no siento que haga daño ni estan acumulado, se supone que hace daño por segundo, y el daño se va acumulando depende cuantas cargas tengamos

(este spell nunca es activado, se supone que deberia activarlo, si hay adds, deberia deberia castear dicho spell,)
Modo mitico - Concéntrate en el Succelent Lasher para detener [Agronox] (https://www.wowhead.com/es/npc=117193/agronox) de la curación a través de [ Infusión de la Naturaleza](https://www.wowhead.com/es/spell=242199/infusi%C3%B3n-de-la-naturaleza).

(esas flores muy rara vez son convocadas pero una sola vez  agarran al jugador, deberia ser otra vez invocadas despues que llame a las plantas explosivas y estas plantas agarran a aleatorios no tankes)
[Agronox](https://www.wowhead.com/es/npc=117193/agronox) también invocará  dos flores inalcanzables en las esquinas de la habitación.
Las flores agarrarán a uno o dos jugadores cada uno y colocarán [Vides asfixiantes](https://www.wowhead.com/es/npc=120014/vides-asfixiantes) sobre ellos, lo que les causará un daño cada vez mayor hasta que el jugador afectado se aleje 20 yardas y rompa la cadena.

https://es.wowhead.com/spell=240951/desenfreno-destructivo (sigue haciendo daño)
este spell tiene mucho rango, no debería haberme matado ya que no he salido del area donde esta el jefe... únicamente deberías morir si estas en el camino de hechizo, osea fuera de los anillos de la biblioteca

https://www.wowhead.com/npc=117590/shadow-of-mephistroth (funciona bien, pero no deberia moverse de sus lugar)
cuando aparecen estas sombras, estos no deberian moverse de su lugar..
