### ISSUE TITLE
[Core] - Porcentaje de las misiones de seguidores 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3869]
**Links:**

from WoWHead or our Armory

**What is happening:**
como ven en la imagen un solo seguidores cubre las dos facultades que pide la mision con una 102%
![image](https://user-images.githubusercontent.com/81131460/189791573-98ee37e9-83e3-4198-afe3-5b90e55bd16e.png)
al enviarlos y verificar la mision en curso, el porcentaje cambio
![image](https://user-images.githubusercontent.com/81131460/189791820-1f94773a-d407-435f-9fb7-9e8c9d18e37d.png)
ejemplo 2:
esta vez con 3 seguidores cubriendo cada spell con un 135%, tampoco funciona el botin extra, segun la imagen aparece unos numeros y tengo  35% (bonus de tirada)
![image](https://user-images.githubusercontent.com/81131460/189792607-0046131a-71cc-46de-a414-5328305c550f.png)
al enviarlos y verificar la misión en curso, el porcentaje cambio
![image](https://user-images.githubusercontent.com/81131460/189792901-045fa496-2936-4fa2-9569-77cd55bd3b41.png)
ejemplo 3:
tengo un 99% y cubro las 2 facultades que piden..
![image](https://user-images.githubusercontent.com/81131460/189794481-4ba351ea-977f-40d9-b1ab-320860c7db49.png)
al enviarlos y verificar la misión en curso, el porcentaje cambio
![image](https://user-images.githubusercontent.com/81131460/189794695-810cff68-d02e-420e-8a8d-52ce2cbac628.png)

**En conclusion:** el sistema de % exito no funciona, arroja valores random y casi siempre en misiones raras o de nivel, siempre fracaso a pesar de cumplir con el ilv de los seguidores, cubrir las facultades y tener un porcentaje alto, al enviarlos a misión, el porcentaje no es reconocido, aclaro no estoy usando items en mis seguidores, ya que obtengo el mismo resultado de exito..

**Comment by Noahkrr** [comment]
asi deberia funcionar el botin bonus que obtenemos en algunas misiones...
https://github.com/GuabinaCore/WoWKoi/issues/3792

**Comment by Cefiro-Caecias** [comment]
Reparado.
