### ISSUE TITLE
Mision - Equilibrio de poderes

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3870]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/quest=43533/equilibrio-de-poderes
el primer crédito "poder absorbido" se autocompleta, pero al llegar a la zona del crisol, obtenemos credito, pero los npcs no aparecen.. ni para entregar la misión..
video: https://www.youtube.com/watch?v=Nv2H3pbxbww

**Comment by Cefiro-Caecias** [comment]
Reparada 50% blizzlike, debido a falta de datos técnicos. Deberás abandonar la quest (si la tienes), borrar Cache y volverla a tomar. Disponible mañana.
