### ISSUE TITLE
Wqs - npc - Argus

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3872]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/quest=48691/cadena-de-almas
la mision es completable pero funciona mal, deberia usar el item [Dije del profeta](https://es.wowhead.com/item=152971/dije-del-profeta), que se usa en las almas de los tabidos, para asi poder liberarlos.

https://es.wowhead.com/quest=47563/espíritus-de-los-caídos
la mision es completable pero funciona mal, debería usar el item [Piedra titánica](https://es.wowhead.com/item=152995/piedra-titánica), que se usa para liberar los espíritus esclavos torturados.

https://es.wowhead.com/quest=47858/seguridad-en-combate
la mision es completable pero funciona mal, debería usar el item [Cristal de poder vigilante](https://es.wowhead.com/item=152357/cristal-de-poder-vigilante), que se usa para activar a los [Vigilantes domesticados](https://es.wowhead.com/npc=125842/vigilante-doméstico)

https://es.wowhead.com/quest=47180/locura-latente
la mision es completable pero funciona mal, deberia disipar 5 [manifestaciones del Vacío](https://es.wowhead.com/npc=121539/manifestación-del-vacío), usando el item [Efigie de oración sacralizada](https://es.wowhead.com/item=151563/efigie-de-oración-sacralizada)

https://es.wowhead.com/npc=123512/marsuul-cazamagos
npc no reaccionan al ataque y no se mueven.. 

es.wowhead.com/npc=127171/cristal-de-alma-cargado
estos cristales no deberian moverse, si atacan pero no se mueven..

**Comment by Cefiro-Caecias** [comment]
Reparados. Disponibles en el próximo update.
