### ISSUE TITLE
Misiones - razas aliadas

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3873]
**Links:**

from WoWHead or our Armory

**What is happening:**
Alianza:
https://es.wowhead.com/quest=50239/elección-de-aliados
el ultimo crédito "elije a que aliados quieres reclutar" no se completa, a pesar de haber elegido..
luego de completar dicha mision, depende de que aliados hayamos elegidos

Si  hemos escogido los elfos del vacio, [Alleria brisaveloz](https://es.wowhead.com/npc=126321/alleria-brisaveloz) debería darnos las siguientes misiones:
1- https://es.wowhead.com/quest=49787/las-tierras-fantasma
1.2- https://es.wowhead.com/quest=48962/falla-de-telogrus

Si  hemos escogido los elfos del vacio, [Alto exarca Turalyon](https://es.wowhead.com/npc=126319/alto-exarca-turalyon) debería darnos las siguientes misiones:
2- https://es.wowhead.com/quest=49698/los-forjados-por-la-luz
2.2- https://es.wowhead.com/quest=49266/forja-de-los-eones
2.3- https://es.wowhead.com/quest=50071/por-la-luz
video: https://www.youtube.com/watch?v=00uGAWE7MSg

Horda:
https://es.wowhead.com/quest=50242/elección-de-aliados
el ultimo crédito "elije a que aliados quieres reclutar" no se completa, a pesar de haber elegido..
luego de completar dicha mision, depende de que aliados hayamos elegidos, obtendremos una cadena de misiones con cierto npc..
video: https://www.youtube.com/watch?v=8tjHDr1DSO4

**Comment by Cefiro-Caecias** [comment]
Reparado. Disponible mañana.
