### ISSUE TITLE
WQs profesiones - Argus

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3874]
**Links:**

from WoWHead or our Armory

**What is happening:**
NPC "Alquimista Funen" (https://es.wowhead.com/npc=125346/alquimista-funen)

necesitas Alquimia
https://es.wowhead.com/quest=48323/pedido-lágrimas-de-los-naaru
necesitas Alquimia
https://es.wowhead.com/quest=48318/pedido-elixires-de-sangreluz
necesitas Herbolesteria
https://es.wowhead.com/quest=48337/pedido-gloria-astral

WQ para todas las profesiones
https://es.wowhead.com/quest=48338/suministros-necesarios-gloria-astral

NPC "Capitana Fareeya" (https://es.wowhead.com/npc=128370/capitana-fareeya)

necesitas Sastreria
https://es.wowhead.com/quest=48373/pedido-paño-de-tejido-de-luz
necesitas Desuello
https://es.wowhead.com/quest=48359/pedido-cuero-maligno
necesitas Mineria
https://es.wowhead.com/quest=48349/pedido-empirium
necesitas Joyeria
https://es.wowhead.com/quest=48364/pedido-heseliana
necesitas  joyería
https://es.wowhead.com/quest=48363/pedido-malaquita-florida

WQ para todas las profesiones
https://es.wowhead.com/quest=48360/suministros-necesarios-cuero-maligno
https://es.wowhead.com/quest=48358/suministros-necesarios-empirium
https://es.wowhead.com/quest=48374/suministros-necesarios-paño-de-tejido-de-luz

**Comment by Cefiro-Caecias** [comment]
Reparadas. Disponibles en el próximo update.
