### ISSUE TITLE
[Core] - Druida: Class Hall

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3875]
**What is happening:**

1- Rasgo Celadores de la arboleda esta bug, no funciona, el reclutador no da tropas
una vez aprendido el rasgo [Celadores de la Arboleda](https://es.wowhead.com/order-advancement=492/celadores-de-la-arboleda), opción reclutar tropas, debería obtener estas tropas [Celadores de la Arboleda](https://es.wowhead.com/champion=1016/celadores-de-la-arboleda) con el npc [Shalorn estrella](https://es.wowhead.com/npc=108391/shalorn-estrella)

2- Rasgo Simpreverde esta bug, no hay [Monticulo de tierra fertil]
https://www.wow-freakz.com/object_finder.php?object=253078&name=fertilized-dirt-mound
https://www.wow-freakz.com/object_finder.php?object=253077&name=fertilized-dirt-mound
(https://www.wowhead.com/object=181690/fertile-dirt-mound) segun wowhead
video: https://www.youtube.com/watch?v=0pqL4eiYbgU
como debería ser:
Una de las 7 plantas posibles cultivadas a partir de la elección de avance del orden del salón de clases de [ druida : ](https://www.wowhead.com/druid)[ Evergreen](https://www.wowhead.com/order-advancement=354/evergreen) .
Hay dos instancias de cada planta en la base de datos, así que asumo que esto se debe a que hay dos parcelas separadas.
Parece que las dos parcelas se alternan y se pueden saquear cada 1,5 días.
Cada planta tiene una pequeña posibilidad de contener [ Acorn of the Endless](https://www.wowhead.com/item=139554/acorn-of-the-endless) : la apariencia de arma púrpura oculta para Restoration [ Druid](https://www.wowhead.com/druid) .
Objeto / Item
[Tallo de espinas](https://www.wowhead.com/object=253153/thornstalk) / [Tallo de espinas](https://www.wowhead.com/object=253181/thornstalk)
[Vid de la arboleda](https://www.wowhead.com/object=253185/grove-vine) / [Vid de la arboleda](https://www.wowhead.com/object=253161/grove-vine)
[Arándano onírico](https://www.wowhead.com/object=253150/dreamberry) / [Arándano onírico](https://www.wowhead.com/object=253180/dreamberry)
[Flor de sol](https://www.wowhead.com/object=253148/sunblossom) / [Flor de sol](https://www.wowhead.com/object=253179/sunblossom)
[Bayas espirituales](https://www.wowhead.com/object=253183/spirit-berries) / [Bayas espirituales](https://www.wowhead.com/object=253157/spirit-berries)
[Flores de G'Hanir](https://www.wowhead.com/object=253116/ghanir-blossoms) / [Flores de G'Hanir](https://www.wowhead.com/object=253176/ghanir-blossoms)
[Flores de la Arboleda de los Sueños](https://www.wowhead.com/object=253118/dreamgrove-blossoms) / [Flores de la Arboleda de los Sueños](https://www.wowhead.com/object=253177/dreamgrove-blossoms)

**Comment by Cefiro-Caecias** [comment]
Devs de Core:

-Punto 1: Hace falta un sniff de ese NPC.

-Punto 2: puro Core, sistemas de spells, similar al sistema de Nomi.

**Comment by Cefiro-Caecias** [comment]
Derivado a Issue privado.
