### ISSUE TITLE
[Core] - Trono del Triunvirato: Spells

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3876]
**Links:**

from WoWHead or our Armory

**What is happening:**
1- corregido
(el spell campo de anulacion nunca es activado)
- Los [Subyugador de la guardia de las sombras](https://es.wowhead.com/npc=124171/subyugador-de-la-guardia-de-las-sombras) también aplican debuffs de [Campo de anulación](https://es.wowhead.com/spell=249081/campo-de-anulaci%C3%B3n) a los jugadores que no son tanques. Esta desventaja de 10 segundos reduce la velocidad de movimiento del jugador, al tiempo que hace que inflija daño a los jugadores cercanos cada vez que se mueve. Los jugadores afectados por la desventaja de Campo de anulacion deben quedarse quietos tanto como sea posible, solo moviéndose cuando necesitan esquivar otras fuentes de daño.

2- corregido
-[Dominadora del Vacío de la Guardia de las Sombras](https://es.wowhead.com/npc=127784/dominadora-del-vac%C3%ADo-de-la-guardia-de-las-sombras)s aplicar [Vacío corruptor](https://es.wowhead.com/spell=245510/vac%C3%ADo-corruptor) 
a los jugadores. Este punto de 7 segundos hace que el jugador arrastre a todos los jugadores cercanos.

3-  corregido
- [Acechador de Falla de la guardia de las sombras](es.wowhead.com/npc=122413/acechador-de-falla-de-la-guardia-de-las-sombras) (spells bug)
https://es.wowhead.com/spell=248411/trampa-inestable (nunca es activado)
https://es.wowhead.com/spell=248304/invocación-salvaje (el spell es canalizado pero no invoca pets)
este spell deberia invocar:
spell [Invocar a Acechasombras](https://es.wowhead.com/spell=248305/invocar-a-acechasombras) invoca al npc spell [Acechador sombrío](https://es.wowhead.com/npc=125080/acechador-sombrío)
spell [Invocar a Aletacielo](https://es.wowhead.com/spell=248306/invocar-a-aletacielo) invoca al npc [Aletacielo](https://es.wowhead.com/npc=125079/aletacielo)
spell [Invocar a Acechador de distorsión](https://es.wowhead.com/spell=248307/invocar-a-acechador-de-distorsión) invoca al npc [Acechador de distorsión](https://es.wowhead.com/npc=125081/acechador-de-distorsión)

4- corregido
- Habilidades y estrategia de[ Virrey Nezhar](https://es.wowhead.com/npc=124309/virrey-nezhar)
(este spell Vacio de colapso esta bug, nunca esta activo, deberia estra activo durante todo el combate contra el jefe)
Inmediatamente después de tirar del jefe, un anillo de [ Vacío en colapso](https://es.wowhead.com/spell=244906/vac%C3%ADo-en-colapso) aparecerá alrededor de la habitación y se cerrará lentamente durante la pelea.
Estar de pie en el [ Vacío en colapso](https://es.wowhead.com/spell=244906/vac%C3%ADo-en-colapso) te causará una gran cantidad de daño.
El [ Vacío en colapso](https://es.wowhead.com/spell=244906/vac%C3%ADo-en-colapso) solo se acercará. La habilidad solo restringe el espacio con el que el grupo tiene que trabajar, en lugar de actuar como un enfado duro.

https://www.wowhead.com/es/npc=125340/alasombría (SIGUE BUG LA ANIMACION NO PARA CUANDO ES CORTADO EL SPELL)
bug visual al interrumpir casteo de spell[ Chirrido aterrador](https://www.wowhead.com/es/spell=248831/chirrido-aterrador), no se corta visualmente, sigue hasta que termina el casteo(si tu cortas el spell debería parar, actualmente esto es un problema ya que muchos jugadores van a tratar de cortar spell al mismo tiempo, si ven que este no es cortado)

**Comment by Noahkrr** [comment]
https://www.wowhead.com/npc=125981/fragmented-voidling
sus dos spell no funcionan

https://www.wowhead.com/npc=122478/void-discharge
al morir este npc explota, cuando se canaliza la explosión debería haber un área avisando donde ocurre la explosión
![image](https://user-images.githubusercontent.com/81131460/198345803-3ed4923c-f85a-47f2-a2a9-9c12ed4439e6.png)
como ven en la imagen, al morir se genera un area avisando, luego de unos segundos explota..

https://www.wowhead.com/es/npc=122405/conjurador-de-la-guardia-de-las-sombras
sus spell no funcionan

Jefe[ L'ura](https://www.wowhead.com/es/npc=122314/lura) (CORREGIDO)
(todo lo descrito funciona, actualmente solo hace una llamada la vacio y despues contragolpe y fase 2, deberia hacer una segunda llamada al vacio, esta vez invocando 2 celadores  y al morir los  adds, otra ves contragolpe, luego fase 2)
Al iniciar el encuentro, [L'ura](https://www.wowhead.com/es/npc=122314/lura) se volverá inmune a todo daño y abrirá un único portal de vacío a través de su hechizo [ Llamada al Vacío .](https://www.wowhead.com/es/spell=247795/llamada-al-vac%C3%ADo)
Un [Celador de falla superior](https://www.wowhead.com/es/npc=124745/celador-de-falla-superior) emergerá del portal del vacío y lo estabilizará. El guardián necesita ser asesinado para quitar el portal, que está generando oleadas de [Vacío menguante,](https://www.wowhead.com/es/npc=123050/vac%C3%ADo-menguante) agrega.
Estos pequeños agregados vacíos generarán parches [ de Remanente de angustia](https://www.wowhead.com/es/spell=245242/remanente-de-angustia) en el suelo cuando mueran, lo que inflige daño a cualquiera que se encuentre dentro de él.

(SIGUE SIN FUNCIONAR  EL SPELL FRAGMENTO DE DESESPERACION, ES CASTEADO PERO NO HAY ANIMACION NI DAÑO)
(spell fragmento de desesperacion no funciona, deberia verse como la imagen  y deberia funcionar segun lo escrito)
![image](https://user-images.githubusercontent.com/81131460/197315189-d8264a9b-7b09-4c28-bd81-e072df73d19d.png)
El [Celador de falla superior](https://www.wowhead.com/es/npc=124745/celador-de-falla-superior) lanza [ Fragmento de desesperación](https://www.wowhead.com/es/spell=245164/fragmento-de-desesperaci%C3%B3n) , que marcará una zona de la habitación y lanzará un rayo hacia ella.
Debes asegurarte de que un solo jugador absorba el rayo para reducir el daño entrante.
Cuando el [Celador de falla superior](https://www.wowhead.com/es/npc=124745/celador-de-falla-superior) y todos los agregados de [Vacío menguante](https://www.wowhead.com/es/npc=123050/vac%C3%ADo-menguante) mueren, el jefe quedará aturdido durante 12 segundos con [ Contragolpe](https://www.wowhead.com/es/spell=247816/contragolpe) , lo que hace que reciba un 200% más de daño y también restablece todos los [ beneficios de Aumento de oscuridad](https://www.wowhead.com/es/spell=247915/aumento-de-oscuridad) que ha ganado hasta este punto. .

(CORREGIDO)
(actualmente esto no se cumple, se saltea a la fase 2 donde usa desplazamiento)
Después de que termine el primer [ Contragolpe](https://www.wowhead.com/es/spell=247816/contragolpe) , se generarán dos portales vacíos. El grupo tendrá que lidiar ahora con dos [Celador de falla superior](https://www.wowhead.com/es/npc=124745/celador-de-falla-superior) y el doble de sumas de [Vacío Menguante](https://www.wowhead.com/es/npc=123050/vac%C3%ADo-menguante) .

**Comment by Noahkrr** [comment]
https://www.wowhead.com/es/spell=247930/cadencia-umbría
este spell es canalizado por  [L'ura](https://www.wowhead.com/es/npc=122314/lura), pero no hace daño, deberia hacer daño.

**Comment by Noahkrr** [comment]
mas información en: https://www.wowhead.com/es/guide/seat-of-the-triumvirate-dungeon-ability-guide-5398

**Comment by Travven** [comment]
> https://www.wowhead.com/es/spell=247930/cadencia-umbría
> este spell es canalizado por  [L'ura](https://www.wowhead.com/es/npc=122314/lura), pero no hace daño, deberia hacer daño.
> 

Explica porque crees eso por favor...

**Comment by Travven** [comment]
Todo corregido

**Comment by Noahkrr** [comment]
https://www.wowhead.com/es/npc=127796/acechador-de-falla-de-la-guardia-de-las-sombras
este npc lanza muy seguido invocaciones haciendo spam en el chat, y desapareciendo sus antetiores invocaciones, deberia invocar cuando tengan las pets muertas y no estar casteandolo  cada rato, eso evita que sus pets ataquen..
