### ISSUE TITLE
[Arthas] - Artefacto Brujo Demonología

### ISSUE THREAD

**Issue by Deadrock89** [GuabinaCore/WoWKoi#3877]
Dentro de la gesta de brujo demonologia se encuentra un bug, despues de matar un boss no abre la puerta para contin uar por el puente y llegar al final de la gesta

https://es.wowhead.com/quest=42125/susurros-oscuros#videos-english

**Comment by Noahkrr** [comment]
confirmado, después de matar al demonio de la fase 2, sigue la fase 3 que pide "la barrera de Mephistroth cruzada", no se puede cruzar ya que hay una barrera que me bloquea el paso hacia el siguiente escenario donde se desarrolla la fase 3..
![image](https://user-images.githubusercontent.com/81131460/191584776-a88547a6-0917-4f24-a20f-c48b4fd8af76.png)

**Comment by Cefiro-Caecias** [comment]
Reparado.
