### ISSUE TITLE
Training Dummy Combat Bug

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#388]
**Links:**
https://www.wowhead.com/npc=31144/training-dummy
from WoWHead or our Armory

**What is happening:**
Hitting the dummy puts you in combat as it should but you never leave combat.

**What should happen:**
Some seconds after you stop attacking it, you should get out of combat.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in th next update.
