### ISSUE TITLE
Misión Aliados inesperados

### ISSUE THREAD

**Issue by Deadrock89** [GuabinaCore/WoWKoi#3880]
La misión Aliados inesperados no la esta dando Navarrog en alta montaña para poder completar la historia. Se entrega la misión "adenttrarse en la oscurdad" se completa y Navarrog no da la siguiente "aliados Inesperados"

https://discordapp.com/channels/@me/760619703542087740/1022727652852895794

**Comment by Cefiro-Caecias** [comment]
Lo acabo de probar y me dio la quest sin problemas o.O
