### ISSUE TITLE
Piedra de alquimista infernal - ítem

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3881]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/item=127842/infernal-alchemist-stone
al crear estos abalorios, aveces obtenemos ese ítem con los bonos "Titanforged" y "Warforged", ningun item de profesión debería obtener estos bonos...

**Comment by Cefiro-Caecias** [comment]
Ajustado. Disponible en el próximo update.
