### ISSUE TITLE
[Arthas] - Artefacto Brujo Destrucción

### ISSUE THREAD

**Issue by Deadrock89** [GuabinaCore/WoWKoi#3882]
Dentro de la gesta de la mision "ojo por cetro" la fase 6 donde Nagaz se vuelve en contra no ataca y cuando se mata no continua a la siguiente fase por lo cual no se puede sacar dicho artefacto

**Comment by LKArthas** [comment]
Fixed on https://github.com/GuabinaCore/TYCE-Group/commit/a380184ea792c6543a8252366d4be4648d1b013f now Enjoy
