### ISSUE TITLE
Azsuna - npcs

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3883]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/npc=111763/corruptor-vil-experimental
estos npcs no se mueven pero se pueden destruir y hacen daño con sus spell en area, actualmente hay adds invisibles y  algunos tienen otra skin y se mueven y golpean

https://es.wowhead.com/npc=111752/inquisidor-cautivado
sus hechizos estan bug,

[Descarga de Almasombría](https://es.wowhead.com/spell=216210/descarga-de-almasombr%C3%ADa)
Sombras (nunca es activado)
[Invocar ojo debilitador](https://es.wowhead.com/spell=222523/invocar-ojo-debilitador) 
(el ojo no hace daño con su rayo de luz)
[Mirada abrasadora](https://es.wowhead.com/spell=214415/mirada-abrasadora) (si es activado) 
pero luego activa otro spell [Interrogatorio corrupto](https://es.wowhead.com/spell=222535/interrogatorio-corrupto), este spell esta bug, porque al usarse el npc se esconde bajo tierra, recibe daño pero no se le puede interrumpir el spell, tambien te persigue escondido y no ataca..

**Comment by Cefiro-Caecias** [comment]
Reparado en su mayoría. Disponible mañana.
