### ISSUE TITLE
Argus Krokuun quest "Intercepting the Legions Plans" mob is missing

### ISSUE THREAD

**Issue by Likander** [GuabinaCore/WoWKoi#3885]
**Links:**

[from WoWHead or our Armory](https://www.wowhead.com/quest=47554/intercepting-the-legions-plans)

**What is happening:**
Multiple drops of Enigmatic legion orders are dropping after you've collected the 2 you need, and the dead codebreaker Brae who has the  Army of the light code book is missing.

**What should happen:**
Kill mobs get 2 enigmatic legion orders then drops stop. Go to where npc corpse is and get item from body. Turn in quest and continue.

**Comment by Cefiro-Caecias** [comment]
Fixed.
