### ISSUE TITLE
Misiones  - WQs 

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3886]
**What is happening:**

1) https://es.wowhead.com/quest=45845/fuego-interior: la mision esta bug, el ultimo credito "Tercio de disco de fuego" no se puede completar, ya que el contenedor no es targeteable. El contenedor [Tercio de disco de fuego](https://es.wowhead.com/object=267190/tercio-de-disco-de-fuego) y el item de misión, que debería contener es [Tercio de disco de Fuego](https://es.wowhead.com/item=143836/tercio-de-disco-de-fuego)

2) No hay portal de regreso hacia la ciudadela  violeta

3) Al tomar portal hacia el Crater de Dalaran, debería recibir el spell caida libre, actualmente no obtenermos dicho spell, caemos y morimos o sobrevivimos con poca vida.

4) https://es.wowhead.com/quest=45930/nosotros-no-encendimos-el-fuego
5) https://es.wowhead.com/quest=46236/soldados-petrificados
En ambas WQ: no aparecen npcs, apesar de estar activa las WQs, imposible completar si en la zona no hay nada..

**Comment by Cefiro-Caecias** [comment]
1) Reparado.

2) No debe haberlo, no he visto que haya uno en ningún video; además no hay que regresar a Dalaran, sino al Salón de Clase.

3) Reparado.

4) Reparado.

5) Reparado.

Todo disponible luego del próximo update.
