### ISSUE TITLE
[Arthas] - Artefacto Destrucción - Brujo

### ISSUE THREAD

**Issue by Deadrock89** [GuabinaCore/WoWKoi#3887]
[**Links:**](https://es.wowhead.com/quest=43254/arruinar-el-ritual)

**Dentro de la misión ritual del ritual posterior a matar a Allaris Nasarin cuando hay que coger el cetro no lo da y tampoco calydus abre el portal para poder finalizar la misión lo que genera no poder tener el artefacto de destrucción del brujo**

**Comment by LKArthas** [comment]
Fixed on Today's Commit, Arreglado en el commit de hoy
