### ISSUE TITLE
En tierras Extrañas - Mision

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3888]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://es.wowhead.com/quest=50305/en-tierras-extrañas
al llegar al tablero, debería contarme crédito y tampoco esta el npc [Keira Cuervónice](https://es.wowhead.com/npc=131347/keira-cuervónice) que para entregar la mision..

**Comment by Cefiro-Caecias** [comment]
Reparada. Disponible mañana.
