### ISSUE TITLE
Misiones - NPC - Mago

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3889]
1) https://www.wowhead.com/es/npc=106434/guardiana-alar
este npc deberia permitirme reclutar nuevos tropas [Kirin Tor Guardians](https://www.wowhead.com/champion=1006/kirin-tor-guardians), ya que aprendi el rasgo [Guardianes del Kirin Tor](https://www.wowhead.com/order-advancement=483/guardians-of-the-kirin-tor) 

2) https://www.wowhead.com/es/quest=42429/recuerdos-del-ébano-glacial
no puedo interactuar con los npcs, ya que no me presentan diálogos para obtener creditos..

**Comment by Cefiro-Caecias** [comment]
1) Pendiente de reconstrucción, hace falta un sniff para poder reconstruirla.

2) No hay bug presente: DEBES tener equipado a Ébano Glacial para que hablen contigo, y no tener el bufo que ellos otorgan.
