### ISSUE TITLE
Paladin - Misiones

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3890]
**Links:**

from WoWHead or our Armory

**What is happening:**
1) https://www.wowhead.com/es/npc=99997/arator-el-redentor: npc duplicado

2) https://www.wowhead.com/es/npc=90251/aponi-crin-brillante: npc duplicado

3) https://www.wowhead.com/es/npc=108776/lord-maxwell-neófitus: el npc se dirge a la tumba de Uther despues de completar la mision [Buscar consejo](https://www.wowhead.com/es/quest=42770/buscar-consejo), ahora tengo que iniciar la misión [Buscar consejo](https://www.wowhead.com/es/quest=42773/luz-reveladora) y el npc no aparece. y no puedo obtener la misión Luz reveladora..

**Comment by Sefrenia-Caecias** [comment]
1 y 2: El hall aun está en proceso de reconstrucción, así que lo iré limpiando y faseando a medida que siga avanzando, ten paciencia.

3) Luego d ela quest "Bucasr consejo", deberás realizar las quests "Mantener el orden" y "Suelo sagrado", que dan allí mismo Mehlar Hojalba y el Sumo sacerdote Thel'danis. Al terminarla,s podrás ver a Lord Maxwell Neófitus para que te de la quest "Luz reveladora".

**Comment by Cefiro-Caecias** [comment]
1 y 2): No te preocupes, iré faseando y quitando duplicaciones a medida que avance en la reconstrucción del Hall. Sólo ten paciencia.

3) Reparado, disponible mañana. El desajuste se debió al error de otro colaborador.
