### ISSUE TITLE
[DB] - Misiones de zona inicial - DK

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3891]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/quest=12678/if-chaos-drives-let-suffering-hold-the-reins
el mision funciona bien, pero cuando la completas en el mapa aparece en otra ubicación donde entregar la mision, es un bug visual del mapa, el npc esta en la Brecha de la Muerte

https://www.wowhead.com/quest=12679/tonight-we-dine-in-havenshire
el mision funciona bien, pero cuando la completas en el mapa aparece en otra ubicación donde entregar la mision, es un bug visual del mapa, el npc esta en la Brecha de la Muerte

https://www.wowhead.com/npc=29259/spirit-healer
npc esta muy arriba, no puedo obtener el dialogo para resucitar, deberia poder acceder al dialogo para resucitar

https://www.wowhead.com/npc=28534/valkyr-battle-maiden
al morir en combate, aparece este npc y me da la opcion de revivir, al aceptar, mi pj cae a la nada y me quedo atascado

https://www.wowhead.com/quest=12701/massacre-at-lights-point
el mision funciona bien, pero cuando la completas en el mapa aparece en otra ubicación donde entregar la mision, es un bug visual del mapa,  el npc esta en la Brecha de la Muerte

https://www.wowhead.com/quest=12719/nowhere-to-run-and-nowhere-to-hide
el mision funciona bien, pero cuando tomas la mision, el objetivo aparece en otra ubicacion, es un bug visual del mapa..

https://www.wowhead.com/quest=12722/lambs-to-the-slaughter
el mision funciona bien, pero cuando la completas la mision, en el mapa aparece en otra ubicación donde entregar la mision, es un bug visual del mapa,  el npc esta en la Cripta de los recuerdos

https://www.wowhead.com/quest=12724/the-path-of-the-righteous-crusader
el mision funciona bien, pero cuando tomas la mision, el objetivo aparece en otra ubicacion, es un bug visual del mapa..

https://www.wowhead.com/quest=12742/a-special-surprise
al terminar de decir sus dialogos   y unos segundos despues el npc desaparece o aveces lo matas y no cuenta credito

https://www.wowhead.com/quest=12754/ambush-at-the-overlook
el mision funciona bien, pero cuando la completas la mision, en el mapa aparece en otra ubicación donde entregar la mision, es un bug visual del mapa..

https://www.wowhead.com/quest=12755/a-meeting-with-fate
el mision funciona bien, pero cuando la completas la mision, pero el objetivo de la mision no aparece en el mapa..

https://www.wowhead.com/quest=12756/the-scarlet-onslaught-emerges
el mision funciona bien, pero el objetivo de la mision no aparece en el mapa..

https://www.wowhead.com/quest=12757/scarlet-armies-approach
el mision funciona bien, pero el objetivo de la mision no aparece en el mapa..

https://www.wowhead.com/quest=12779/an-end-to-all-things
el mision funciona bien, pero cuando la completas la mision, pero el objetivo de la mision no aparece en el mapa..

**Comment by Cefiro-Caecias** [comment]
Reparado en su mayoría.
