### ISSUE TITLE
[Arthas] - Misión: Invocando las Hermanas

### ISSUE THREAD

**Issue by Deadrock89** [GuabinaCore/WoWKoi#3892]
la Mision Invocando las Hermanas de la campaña del brujo se encuentra dañada, posterior a atravesar el portal quedo aturdido y 3 segundos despues me retorna a dalaran y no permite desarrollar la mision. LINK: https://www.wowhead.com/es/quest=41756/campeonas-gemelas-eredar

**Comment by Deadrock89** [comment]
aun continua el bug, no me permite continuar en la cadena y sacar los logros, esto limitado completamente para continuar mi progreso

**Comment by Cefiro-Caecias** [comment]
Reparada.
