### ISSUE TITLE
Paladin artifact bugs

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#3893]
Retribution
---

1. 
- [ ] [Seeking Guidance](https://www.wowhead.com/quest=42770/seeking-guidance)
   - [Lord Maxwell Tyrosus](https://www.wowhead.com/npc=108776/lord-maxwell-tyrosus) doesn't have a question mark above him. Can't turn in the quest.
---

Holy  
---

2.

 - [ ] works fine

---

Protection
---
3.

 - [ ]  [Shrine of Truthguard](https://www.wowhead.com/quest=42017/shrine-of-the-truthguard) quest
   - After you pick up Truthguard, it lands in your head slot instead of your weapon slot.
   - [Return to Dalaran](https://www.wowhead.com/npc=105892/return-to-dalaran) credit is not granted when approaching Lord Maxwell Tyrosus

**Comment by Cefiro-Caecias** [comment]
1.- Fixed.

2.- Thanks :D

3.- In this case, you must go outside the tomb to get the griffin; If you didn't, now I've added an extra security measure and you will find Maxwell in Dalaran who will help you with your problem by approaching him.

All available right now.
