### ISSUE TITLE
[Core] - Trono del Triunvirato NPCs

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3895]
**Links:**

from WoWHead or our Armory

**What is happening:**
estos npcs son inmunes al cualquier tipo de hechizo de frenado(silencio, aturdimiento, miedo o trampas) sea individual o en masa.. no deberian ser inmunes...
https://www.wowhead.com/es/npc=122322/tábido-famélico
https://www.wowhead.com/es/npc=122478/descarga-de-vacío
https://www.wowhead.com/es/npc=122398/señor-del-vacío-debilitado
https://www.wowhead.com/es/npc=122403/campeón-de-la-guardia-de-las-sombras
https://www.wowhead.com/es/npc=122413/acechador-de-falla-de-la-guardia-de-las-sombras
https://www.wowhead.com/es/npc=122421/adepto-de-guerra-umbrío
https://www.wowhead.com/es/npc=122423/gran-tejesombras
https://www.wowhead.com/es/npc=122404/dominador-del-vacío-de-la-guardia-de-las-sombras
https://www.wowhead.com/es/npc=122405/conjurador-de-la-guardia-de-las-sombras
https://www.wowhead.com/es/npc=122408/acechador-sombrío
https://www.wowhead.com/es/npc=122407/acechador-de-distorsión
https://www.wowhead.com/es/npc=122412/señor-del-vacío-esclavizado

**Comment by Noahkrr** [comment]
www.wowhead.com/es/npc=127882/vixx-el-recolector
npc especial, solo aparece en modo heroico, y esta rondando por todo el mapa

**Comment by Travven** [comment]
Corregidos
