### ISSUE TITLE
Guerrero - Mision - Prepararse para la guerra

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3898]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/es/quest=43585/prepararse-para-la-guerra
al obtener la mision, no se generan las sub-misiones que mis seguidores deben completar:
[Aiding the Valkyra](https://www.wowhead.com/mission=1378/aiding-the-valkyra)
[Lost at Sea](https://www.wowhead.com/mission=1379/lost-at-sea)
[Enslaved by Sea Giants](https://www.wowhead.com/mission=1380/enslaved-by-sea-giants)

**Comment by Cefiro-Caecias** [comment]
Reparado.
