### ISSUE TITLE
[Arthas/Sefrenia] - Quest: Argent Call: The Trial of the Crypt

### ISSUE THREAD

**Issue by zodIIac** [GuabinaCore/WoWKoi#39]
**Links:**

https://www.wowhead.com/quest=27464/argent-call-the-trial-of-the-crypt#comments

**What is happening:**

Grants wrong amount of reputation.

**What should happen:**

Upon completing the quest, player's reputation standing should be set to revered straight away.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
