### ISSUE TITLE
Mago - Misión - Quien lo encuentra se lo queda

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3900]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/es/quest=45615/quien-lo-encuentra-se-lo-queda
 ya hice todas las misiones de mi sede y esta misión no aparece en mi sede...
como deberia funcionar: (ya tengo el seguidor y el logro.. aun asi no tengo la mision "Quien lo encuentra se lo queda")
Esta es la primera misión de la cadena de misiones para reclutar a un nuevo seguidor [ mago : ](https://www.wowhead.com/mage)[el Gran Akazamzarak](https://www.wowhead.com/champion=995/the-great-akazamzarak) .
Antes de poder completar esta serie de misiones, debes ganar [ Champions of Legionfall](https://www.wowhead.com/achievement=11846/champions-of-legionfall) y reclutar [a Aethas Sunreaver](https://www.wowhead.com/champion=994/aethas-sunreaver) .
Después del reinicio semanal, encontrarás [The Great Akazamzarak](https://www.wowhead.com/npc=103092/the-great-akazamzarak) en el salón de clases junto al mapa de la misión.

**Comment by Cefiro-Caecias** [comment]
Tienes razón, había pasado por alto a este seguidor. Aventura reconstruida, disponible en la reapertura.
