### ISSUE TITLE
Maestro de vuelo - Draenor

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3901]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/es/npc=81888/rangari-nogo
no hay maestro de vuelo
https://www.wowhead.com/es/npc=84507/rangari-yaval
no hay maestro de vuelo
https://www.wowhead.com/es/npc=84508/gritavientos
no hay maestro de vuelo lado horda
https://www.wowhead.com/es/npc=86492/nisha
el punto de vuelo de hacia este maestro de vuelo, esta bug.. marca otra zona, debera marcame la zona "corona del rompedor", donde actualmente me encuentro y no  en "Paso alto"(actualmente estoy en Corona del rompedor, pero me marca otra zona)
![image](https://user-images.githubusercontent.com/81131460/199096660-eb63b072-df8f-4e2c-840d-8559d567d8b6.png)

https://www.wowhead.com/es/npc=90960/guardia-del-cielo-thann
No reconoce ruta del maestro de vuelo... como ven en la imagen, esytoy en la avanzada del Leon, y me marca otra zona "camara de la tierra"
![image](https://user-images.githubusercontent.com/81131460/199118564-918cfc02-e72e-4051-b448-dcb67ae9771a.png)

**Comment by Noahkrr** [comment]
https://www.wowhead.com/object=241716/stashed-iron-sea-booty
no hay objeto
https://www.wowhead.com/object=241712/ironbeards-treasure
no hay objeto
https://www.wowhead.com/object=241715/stashed-iron-sea-booty
no hay objeto
https://www.wowhead.com/object=241716/stashed-iron-sea-booty
no hay objeto
https://www.wowhead.com/object=241714/stashed-iron-sea-booty
no hay objeto
www.wowhead.com/es/npc=93076/capitán-barbaférrea
no hay rare en la cueva

**Comment by Cefiro-Caecias** [comment]
Reparado.
