### ISSUE TITLE
[Core] - Ojo de Azshara: Spells

### ISSUE THREAD

**Issue by Noahkrr** [GuabinaCore/WoWKoi#3902]
**Links:**

from WoWHead or our Armory

**What is happening:**
(estos maremotos se generan cuando el domo desaparece luego de matar a los 4 jefes anteriores)
La isla alrededor de la Ira de Azshara está protegida por [ maremotos](https://www.wowhead.com/spell=192801/tidal-wave) que barren el área en sentido contrario a las agujas del reloj. Los jugadores deben evitar ser golpeados por estos mientras luchan contra la basura en el área.

(corregido)
Poison Spit apunta al suelo cerca de dos jugadores aleatorios con cada lanzamiento.
Después de dos segundos, el proyectil [ Poison Spit](https://www.wowhead.com/spell=192050/poison-spit) aterrizará en estos lugares e infligirá un daño leve a moderado a los jugadores dentro del área de efecto.
Los jugadores deben salir de las zonas de [ Poison Spit](https://www.wowhead.com/spell=192050/poison-spit) antes de que caiga el proyectil.
![tet](https://user-images.githubusercontent.com/81131460/199830404-5652deb6-33bd-478a-aec6-958934dc2d61.PNG)
(corregido)
Además, si no hay objetivos dentro de su alcance cuerpo a cuerpo, Serpentrix lanzará [ Devastación](https://www.wowhead.com/spell=191848/rampage) , provocando [ Poison Spit](https://www.wowhead.com/spell=192050/poison-spit) a un ritmo rápido.
![gdgh](https://user-images.githubusercontent.com/81131460/199830660-ec5a9397-b4bf-4e13-815f-7d9a9ad5b82d.PNG)
(corregido)
Los relámpagos de[ Chaotic Tempest rebotarán en ubicaciones aleatorias cerca de los jugadores.](https://www.wowhead.com/spell=196290/chaotic-tempest)
Durante esta canalización, los jugadores deben asegurarse de evitar pararse en las áreas de efecto de [ Chaotic Tempest .](https://www.wowhead.com/spell=196290/chaotic-tempest)
![image](https://user-images.githubusercontent.com/81131460/199831030-7889d52a-4cd9-4329-b720-1d34c60134f3.png)

(cuando termina de canalizar Chorro de agua, deberia generar areas donde caera el spell y luego de unos segundos se genera los chorros, actualmente no genera las areas, pero si los chorros de agua)
el spell [ Chorro de agua](https://www.wowhead.com/spell=196027/aqua-spout) , que crea chorros de agua debajo de los pies de los jugadores que infligirán un gran daño y lanzarán a los jugadores afectados por el aire si no se esquivan.
![image](https://user-images.githubusercontent.com/81131460/199831904-25fa1491-da60-4020-9652-68c9c6edc8be.png)

mas información: https://www.wowhead.com/guide/eye-of-azshara-dungeon-strategy-guide
https://www.youtube.com/watch?v=-gvGR5DHCmA

**Comment by Travven** [comment]
Los chequee todos y solos los maremotos no se veian. Cierro.slds.

**Comment by Noahkrr** [comment]
www.wowhead.com/es/npc=97172/gotita-de-agua-salada
al atacar a una gotita , se volvera agrevisa y las demas cercanas tambien

(el spell Vientos violentos actualmente se activa cuando matas a 4 jefes, deberia activarse con 2 jefes aleatorios muertos y tambien deben cambiar de dirección, derecha a izquierda y viceversa)
Después de derrotar a dos jefes, [ Vientos violentos](https://www.wowhead.com/es/spell=191797/vientos-violentos)  ocasionalmente empujará a los jugadores en una dirección aleatoria.
una vez activo el spell deberia afectar todas las zonas en la mazmorras, menos las cuevas

(golpe de relampagos se activa tarde cuando ya mate a los 4 jefes y a los 4 nagas)
Después de matar a un tercer jefe, la tormenta se intensifica, provocando que [ Golpe de relámpagos](https://www.wowhead.com/es/spell=192794/golpe-de-rel%C3%A1mpagos) aparezca cerca de los jugadores cada pocos segundos.
[ Golpe de relámpagos](https://www.wowhead.com/es/spell=192794/golpe-de-rel%C3%A1mpagos) aparece primero como un pequeño remolino acuoso; después de 3 segundos, un relámpago cae al suelo e inflige daño de moderado a grave a los jugadores en un radio de 4 yardas

https://www.wowhead.com/es/npc=91787/gaviota-de-cala (spell al ras del suelo no funciona)
cuando se activa el clima vientos huracandos en la mazmorra, la gaviota debe descender con este spell[Al ras del suelo](https://www.wowhead.com/es/spell=194899/a-ras-de-suelo), actualmente estan volando



https://www.wowhead.com/es/spell=192801/maremoto
las olas no hacen daño al entrar en contacto con ellas, y deberian ser mas grandes y giran en direccion incorrecta, deberia girar en la direccion a la ubicacion de las nagas, actualmente giran pero se desvian muy lejos, las olas desaparecen al morir los 4 nagas
