### ISSUE TITLE
[Sefrenia] - Paladin [Quest] We Meet at Light's Hope

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#3904]
**Links:**
https://www.wowhead.com/quest=42811/we-meet-at-lights-hope
https://www.wowhead.com/npc=100337/kill-credit-secret-door-opened

**What is happening:**
The second part of the quest  (Enter Light's Hope Sanctum) wont trigger so you stuck and cant see the door.

**What should happen:**
https://www.youtube.com/watch?v=qzRfxyzKDOc&ab_channel=PhoenixGaming

**Comment by Cefiro-Caecias** [comment]
There is no bug present, the quest worked fine for me. Perhaps it is due to a host asynchrony defect : /
