### ISSUE TITLE
[Arthas] - Mob - Young Frostsaber

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#393]
**Links:**
https://www.wowhead.com/npc=7430/young-frostsaber

**What is happening:**
Mob has wrong scaling - 4k health more even though it's a child xD.

**What should happen:**
Mob should have less health than it's parents.

**Comment by Cefiro-Caecias** [comment]
Arthas, este bicho scala de HP en 1, así que no comprendo qué estará mal.

**Comment by LKArthas** [comment]
Fixed
