### ISSUE TITLE
Quest: Disarming Bears, Id: 28366

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#406]
**Links:**
https://www.wowhead.com/quest=28366/disarming-bears
from WoWHead or our Armory

**What is happening:**
Gives 4000 reputation with Timbermaw Hold.

**What should happen:**
Should only give 1000.

**Comment by Serithul** [comment]
It seems though quest reputation earned with Timbermaw Hold is x4.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
