### ISSUE TITLE
Quest: Deadwood Ritual, Id:8470

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#407]
**Links:**
https://www.wowhead.com/quest=8470/deadwood-ritual-totem
from WoWHead or our Armory

**What is happening:**
Gives 5600 reputation with Timbermaw Hold.

**What should happen:**
Should give 1400 reputation.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
