### ISSUE TITLE
Blazing Servitor too small

### ISSUE THREAD

**Issue by Trevis77** [GuabinaCore/WoWKoi#412]
**Links:**
https://www.wowhead.com/npc=74548/blazing-servitor
from WoWHead or our Armory

**What is happening:**
The mob should be way bigger as you can see on [that screenshot.](https://cdn.discordapp.com/attachments/692339309151518720/694656130135228481/WoWScrnShot_033120_225939.jpg)

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
