### ISSUE TITLE
Pillars in Razorfen Down

### ISSUE THREAD

**Issue by Trevis77** [GuabinaCore/WoWKoi#413]
**Links:**

from WoWHead or our Armory

**What is happening:**
Pillars that has nothing to do here are in the room of the boss Aarux as you can see on [this screenshot.](https://cdn.discordapp.com/attachments/692339309151518720/694656133968822282/WoWScrnShot_033120_225655.jpg)

**Comment by Cefiro-Caecias** [comment]
This Dungeon is still in the reconstruction stage. Patience ;)
