### ISSUE TITLE
Logro de las misiones "Me ve a la marchar"

### ISSUE THREAD

**Issue by carlosyuniro** [GuabinaCore/WoWKoi#415]
https://es.wowhead.com/achievement=5448/me-va-la-marcha-del-fuego
https://es.wowhead.com/achievement=5546/me-va-la-marcha-del-hielo
https://es.wowhead.com/achievement=5547/me-va-la-marcha-de-las-sombras

Todas tres están bug no se pueden activar y mucho menos hacerlas.

Gracias

**Comment by Cefiro-Caecias** [comment]
El mapa de Azshara aun no está terminado, se encuentra en reconstrucción al 50%, al igual que Desolace y Mil Agujas. Paciencia ;)
