### ISSUE TITLE
[Quest] The Wrath of a Dragonflight

### ISSUE THREAD

**Issue by Frosty015** [GuabinaCore/WoWKoi#416]
**Links:** [Quest](https://www.wowhead.com/quest=27894/the-wrath-of-a-dragonflight) and [mob](https://www.wowhead.com/npc=46859/kalaran-the-annihilator)

**What is happening:** Kalaran the Annihilator isn't spawning/not visible. I saw the mob at one point while I was focusing on the Darkflight soldiers, he was flying very low and clipping into the ground, he may have clipped underground and is now unreachable?

**What should happen:** Kalaran should fly higher

**Comment by Frosty015** [comment]
Update: Eventually found him

**Comment by Cefiro-Caecias** [comment]
:P
