### ISSUE TITLE
[Core] Badlands respawn location

### ISSUE THREAD

**Issue by Frosty015** [GuabinaCore/WoWKoi#417]
**Links:** [Spirit healer locations in badlands](https://www.wowhead.com/npc=6491/spirit-healer) - Just click on the  "badlands" map

[Example of issue](https://i.imgur.com/ACsOUbq.jpg)

**What is happening:** A lot of the time when I die in this area, especially when fighting in the New Kargath zone, I respawn at the spirit healer located at the entrance of the Uldaman Dungeon, it's a long walk and there are other spirit healers much closer to where I had died

**What should happen:** Respawn should be adjusted to bring me to the spirit healers closer to where I had died, there are many in the area.

**Comment by Frosty015** [comment]
Additional: I tried using the spirit healer located at the coords 51.8, 21.6 and it ended up rezzing my body in front of the Uldaman dungeon, resulting in my death due to the mobs inside

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
