### ISSUE TITLE
[Arthas] - Quest The Day that Deathwing Came: What Really Happened

### ISSUE THREAD

**Issue by Frosty015** [GuabinaCore/WoWKoi#419]
**Links:** [Quest](https://www.wowhead.com/quest=27715/the-day-that-deathwing-came-what-really-happened)

**What is happening:** In the last portion when facing deathwing, my character still took damage and I ended up dying

**What should happen:** Shouldn't die

**Comment by NightwindOI** [comment]
If u skip the cinematic u can fly.
After u complete the quest u can fly.
