### ISSUE TITLE
[Core] - Elemental shaman talents (t2) unusable

### ISSUE THREAD

**Issue by aurcin** [GuabinaCore/WoWKoi#421]
tier 2 talents (30 lvl row gust of wind, ancestrall guidance, wind rush totem) every tiem u log in, they are unusable. U need go to rest zone, then select/reselect one, then all ok u can use them untill u go off and next time u login they are unusable again

**Comment by Serithul** [comment]
I'm playing elemantal shaman and i don't have that type of problem. Maybe it is from your side ? Any addon that could do something like that ?

**Comment by aurcin** [comment]
i disabled all addons and tryed it didint solved problem. If for example i draged ancestral guidance on my skillbar, then i logout - login, no ancestrall guidance in skillbar, checking spellbooks - same, no talent, in talent tab it shows as selected, then changing talent to gust of wind and again to anestrall guidance, spell moves to skillbar as all new learned spells do it also appears in spellbook, i tryed to even put it on cd, then do logout, same shit, it disapears but when i try change it in talents window it says you cannot do it when spell is on coldown. Also i noticed this happends not only when i loging off but laso when i levelup. 

Can't make video, but can do some screens. As i said addons disabled im not a big fan of lot of addons have just couple. also my client is fresh, grabbed miniclient from website, wasn't playing on other servers. My in game character is Randerbigg, let me know if u need some extra information about thsi problem

**Comment by Serithul** [comment]
Have you removed the read-only property from your entire WoW folder ? Because reading this made me think of that.
Also i am using the full client right from the start so it may be because you are missing files (?).
Sorry to answer you here but i can't be in-game for some days.

**Comment by aurcin** [comment]
well, removed read-only didin't solve problem. No idea about mini client and all files downloaded but i have kinda fast internet, checked wow size its 43gb. Probably will try download torrent version and try log from there, but will do it a bit later

**Comment by aurcin** [comment]
ok, tryed from new client, downloaded torrent from sever website, (removed from torrent after downloaded fully, to avoid override, unchecked read-only) still same problem. Maybe my character is cursed, maybe u can login him and check or you face same problem.

**Comment by biosintesis** [comment]
It work okay on my server
