### ISSUE TITLE
[Core] - Shaman - Elemental - Totem Mastery

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#423]
**Links:**
https://www.wowhead.com/spell=210643/totem-mastery
https://www.wowhead.com/spell=202188/resonance-totem
from WoWHead or our Armory

**What is happening:**
One of the 4 totems, the resonance totem, which provides the likewise named aura, generates 2 maelstrom per second and not 1 per second.

**What should happen:**
Should generate 1 maelstrom per second.

**Comment by aurcin** [comment]
those also are imortal, somtimes if u agro 2 mobs one goes for u another can just hit those totems all day waiting till you finish his mate and switch on him

**Comment by biosintesis** [comment]
It work okay.
