### ISSUE TITLE
Quest: Words of the High Chief, Id:28472

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#427]
**Links:**
https://www.wowhead.com/quest=28472/words-of-the-high-chief
from WoWHead or our Armory

**What is happening:**
Gives 250 rep with everlook and 125 with Booty Bay, Gadgetzan and Ratchet.

**What should happen:**
Should give only 250 rep with everlook.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
