### ISSUE TITLE
Quest: Rubble Trouble, Id: 28610

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#428]
**Links:**
https://www.wowhead.com/quest=28610/rubble-trouble
from WoWHead or our Armory

**What is happening:**
Gives 250 rep with everlook and 125 rep with Gadgetzan, Ratchet and Booty Bay.

**What should happen:**
Should give 250 rep with everlook only.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
