### ISSUE TITLE
[Core] - Flying without a license

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#433]
**Links:**
https://www.wowhead.com/spell=90267/flight-masters-license
https://www.wowhead.com/spell=34090/expert-riding
from WoWHead or our Armory

**What is happening:**
When you learn Expert Riding, you can start flying without learning Flight Master's License on Kalimdor.

Also Flight Master's License doesn't show up as a learnable passive in the spellbook.

**What should happen:**
You should be able to fly in Kalimdor, Eastern Kingdoms and Deepholm only if you have learnt Flight Master's License. Also it has to show up in the spellbook before and after learning it.

**Comment by DeltaVortex** [comment]
This was removed in the last legion patch: https://wow.gamepedia.com/Flight_Master%27s_License

**Comment by Maczuga** [comment]
Flight Master's License should be removed from trainers as of 7.3.5 as it has no use in game and right now misleads players.

Following 3 spells should be removed from all trainers as those are obsolete:
https://www.wowhead.com/spell=90267/flight-masters-license
https://www.wowhead.com/spell=54197/cold-weather-flying
https://www.wowhead.com/spell=115913/wisdom-of-the-four-winds

Also following spells should be removed from trainers, as those are only obtainable via achievements:
https://www.wowhead.com/spell=191645/draenor-pathfinder
https://www.wowhead.com/spell=226342/broken-isles-pathfinder
https://www.wowhead.com/spell=233368/broken-isles-pathfinder
