### ISSUE TITLE
Durotar Mobs (part 2)

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#434]
**Links:**
https://www.wowhead.com/npc=3099/dire-mottled-boar
https://www.wowhead.com/npc=3125/clattering-scorpid
https://www.wowhead.com/npc=39245/northwatch-lug
https://www.wowhead.com/npc=39249/northwatch-lug
https://www.wowhead.com/npc=39251/northwatch-supply-crate
https://www.wowhead.com/npc=39261/northwatch-ranger
https://www.wowhead.com/npc=39260/northwatch-infantryman
https://www.wowhead.com/npc=3106/surf-crawler
https://www.wowhead.com/npc=39268/northwatch-sharpshooter
https://www.wowhead.com/npc=39267/northwatch-marine
https://www.wowhead.com/npc=39272/foaming-sea-elemental
from WoWHead or our Armory

**What is happening:**
All aren't level scaling.

Dire Mottled Boar is a neutral mob with hostile name and tooltip.

**What should happen:**
Should scale.

Dire Mottled Boar should have neutral name and tooltip.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
