### ISSUE TITLE
Winterspring - 3 Quests wrong start.

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#436]
**Links:**
https://www.wowhead.com/quest=28829/razor-beak-and-antlers-pointy
https://www.wowhead.com/quest=28830/chips-off-the-old-block
https://www.wowhead.com/quest=28831/damn-you-frostilicus
https://www.wowhead.com/npc=50263/jadrag-the-slicer
https://www.wowhead.com/npc=10929/haleh
from WoWHead or our Armory

**What is happening:**
These 3 quests can be started by Haleh and Jadrag the Slicer.

**What should happen:**
They should only start from Jadrag the Slicer.

Having seen github i know there is another [report](https://github.com/GuabinaCore/WoWKoi/issues/331) about one of the quests (Razor Beak and Antlers Pointy) on which it was stated that this was done on purpose. I am reporting it again because there is actually a quest that gets you to pass OVER Jadrag the Slicer and it's this quest [Magic Prehistoric](https://www.wowhead.com/quest=28839/magic-prehistoric). Meaning that there is no one will lose these quests.

**Comment by Serithul** [comment]
Also the chapter of winterspring is called Jadrag's Fate, so it's only natural for the quests to be started from him and completed to him.

**Comment by Cefiro-Caecias** [comment]
Put like this deliberately because of the dismissed players. Not everyone is as professional as you :3
