### ISSUE TITLE
Misión en desolace

### ISSUE THREAD

**Issue by carlosyuniro** [GuabinaCore/WoWKoi#438]
https://es.wowhead.com/quest=14264/m%C3%A1s-h%C3%BAmedo-que-mojado

Al transformarte en naga tienes que matar a los elementales de agua pero si atacas o te curas te quita la tranformacion y no te cuenta la misión, hay que estar transformados para que te cuente la misión.

https://www.youtube.com/watch?v=hBn23UnLiyI

**Comment by Cefiro-Caecias** [comment]
El mapa Desolace aun se encuentra en reconstrucción al 50%, al igual que Azshara y Mil Agujas. paciencia.
