### ISSUE TITLE
[Core] - Learning profesions

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#44]
Unable to learn second main profession. Currently have skinning and would like to learn leatherworking. 
Tried trainers in capital cities and no dice. you should learn leatherworking first and after skinning

**Comment by NightwindOI** [comment]
Confirmed
https://streamable.com/bixzpr

**Comment by TheFlash3113** [comment]
It seems to only affect leatherworking. If you learn skinning first, you're unable to learn leatherworking second. I was able to unlearn skinning and then learn leatherworking first and skinning second.

**Comment by alekso999** [comment]
You can't take any of the other professions as your 2nd if you already have skinning
