### ISSUE TITLE
[Core] - Warlock - Demonology - Hand of Gul'dan

### ISSUE THREAD

**Issue by PrecisionWisy** [GuabinaCore/WoWKoi#440]
**Links:**
https://www.wowhead.com/spell=105174/hand-of-guldan
from WoWHead or our Armory

**What is happening:**
Summons an insane amount of imps.

**What should happen:**
It should summon 1-4 imps depending on how many Soul Shards were used.

**Comment by biosintesis** [comment]
It summons the correctly amount of imps depending of soul shards spent.
