### ISSUE TITLE
[Arthas] - Rocket Rescue - Quest

### ISSUE THREAD

**Issue by Jeezuss69** [GuabinaCore/WoWKoi#444]
**What is happening:**
The  Pirate -destroying bomb - the bomb you through detonates sometimes short of the target mark

**What should happen:**
Detonate on impact not at a certain point of the arc

**Comment by NightwindOI** [comment]
Confirm, it reaches only the ships. Cant hit the pirates on the little islands

**Comment by MeatyBoii** [comment]
Even on ships, it doesn't always work.
