### ISSUE TITLE
[Arthas] - Quest - 24637 - The Butcher of Taurajo

### ISSUE THREAD

**Issue by RygardNin** [GuabinaCore/WoWKoi#446]
https://www.wowhead.com/quest=24637/the-butcher-of-taurajo#comments

**What is happening:**
       Arriving at location, Karthog has a dialog option. Talking to him he spawns General Hawthorne and 2 adds. Everything normal untill here. 
       I attacked one of the adds causing General Hawthorne and other add to run off and despawn. Karthog was then stuck with no option of dialog. I decided to revisit the location several times over next half hour. Karthog continues to be in same location with no option or spawning General Hawthorne. I attempted to drop and pick up quest again, but Karthog remains stuck.

**What should happen:**

I assume Karthog should reset in this instance, or General Hawthorne and other add should not of ran off.

**Comment by RygardNin** [comment]
Was able to complete after server reset.

**Comment by LKArthas** [comment]
Fixed
