### ISSUE TITLE
[Core] - Spell Warlock

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#45]
la habilidad inmolate de brujo no genera el soul shard que deberia, al parecer esta invertira con la habilidad Shadow bolt ya que esta si lo genera cuando no deberia de hacerlo (eso al menos en hasta nivel 12)
cuando la habilidad shadow bolt  es cambiada por la habilidad incinerate deja de general soul shards(la habilidad Incinerate si deberia generalos, no Shadow bolt)

**Comment by login6710** [comment]
Parcial fix

**Comment by biosintesis** [comment]
Tanto inmolar como incinerar no generan almas completas, sino fragmentos de almas.
