### ISSUE TITLE
Winterspring - 2 quests wrong starting point

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#452]
**Links:**
https://www.wowhead.com/quest=28856/the-sands-of-silithus
https://www.wowhead.com/quest=28858/blasted-lands-the-other-side-of-the-world
https://www.wowhead.com/npc=11118/innkeeper-vizzie
https://www.wowhead.com/npc=49396/jez-goodgrub
from WoWHead or our Armory

**What is happening:**
Quests can be started by Jes Goodgrub as well as Innkeeper Vizzie.

**What should happen:**
Should only start from Innkeepr Vizzie.

**Comment by Cefiro-Caecias** [comment]
We have deliberately put it that way.
