### ISSUE TITLE
Quest 14196 - Firestarter

### ISSUE THREAD

**Issue by RygardNin** [GuabinaCore/WoWKoi#454]
https://www.wowhead.com/quest=14196/firestarter

**What is happening:**
Quest item (Vortex Gem) does not summon "Whispy Vortex"

**What should happen:**
Should be able to summon "Whispy Vortex" after clicking Vortex Gem. Then you would kill 7 mobs to charge the vortex...

**Comment by RygardNin** [comment]
This holds up quest progression for Desolace I believe. Unable to find any follow up quest

**Comment by Cefiro-Caecias** [comment]
The Desolace map is still 50% in development, as are Azshara and Thousand Needles. Patience.
