### ISSUE TITLE
Excessive wolf howling - Dire Maul area

### ISSUE THREAD

**Issue by RygardNin** [GuabinaCore/WoWKoi#455]
**What is happening:**
Questing on the Ogres outside Dire Maul. Hearing Wolf (Longtooth Runner) sounds/emotes excessively. Even when there are no wolfs around. 

**What should happen:**

**Comment by RygardNin** [comment]
Not just Dire Maul area but all over Feralas.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
