### ISSUE TITLE
Speedbarge Diving Helm - don't gives  underwater breaching and speed

### ISSUE THREAD

**Issue by aurcin** [GuabinaCore/WoWKoi#458]
buff that u have when u in thousand needles, any time u go underwater u supose get helm that gives yous underwater breaching.

Even if i have that buff, when i go underwater i don't recieve any benefits.

[https://www.wowhead.com/spell=75651/speedbarge-diving-helm](url)

**Comment by Cefiro-Caecias** [comment]
The Thousand Needles, Azshara and Desolace maps are not finished yet, they are still at 50% development. Patience ;)
