### ISSUE TITLE
River Boad - don't dismount on land surface

### ISSUE THREAD

**Issue by aurcin** [GuabinaCore/WoWKoi#459]
So u can swimm till u reach land, go on land like u do whit regular mount, find some hillside to go up vertical, then turn 180 and u can fly now. Just can't change vertical postion, nees some land to do that but you can finish something like https://imgur.com/17NvSCu

**Comment by Cefiro-Caecias** [comment]
The Thousand Needles, Azshara and Desolace maps are not finished yet, they are still at 50% development. Patience ;)
