### ISSUE TITLE
Triple Ore nodes in Feralas

### ISSUE THREAD

**Issue by RygardNin** [GuabinaCore/WoWKoi#461]
Location:  75,60 - Feralas - Ore nodes inside The Writhing Deep (Silthid hive)

**What is happening:**

All node spawns have 3 ores at a time. Gold on top of Silver on top of Mithril/Truesilver. On ALL of the spawns inside there. Can mine 3 times, different ores without moving feet.

**What should happen:**
Should only have one ore node at all spawn locations.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the net update.
