### ISSUE TITLE
[Arthas] - Deadmines Encounter Bugs - Helix Gearbreaker / Lumbering Oaf

### ISSUE THREAD

**Issue by JadedNate** [GuabinaCore/WoWKoi#462]
https://www.wowhead.com/the-deadmines
https://www.wowhead.com/npc=47297/lumbering-oaf
https://www.wowhead.com/npc=47296/helix-gearbreaker#encounter

**What is happening (In order):**
1. When Lumbering Oaf uses [Oaf Smash], the target player is stuck while the NPC goes really slow or does not move.
2. Lumbering Oaf does not use his ability [Throw Helix] to have Helix Gearbreaker attach to another player in the encounter.
3. Lumbering Oaf does not properly use the ability [Sticky Bomb], Helix Gearbreaker yells "Bombs away!" as if he has thrown the bombs, but none appear on the battle floor.
4. Upon killing the Lumbering Oaf, Helix Gearbreaker lands on the ground and attacks the players, but only melee. He should throw his [Sticky Bomb]s and [Leap] at random target players.
5. Helix Gearbreaker's melee attacks are too powerful. As a tank with 18k health, he was hitting me for 3.5k every 2 seconds.

**What should happen (In order):**
1. Lumbering Oaf's [Oaf Smash] ability should pick up a player and ram him into the logs in the room at the end of the tracks within a few seconds of being held.
2. [Throw Helix] should cause Helix to be thrown to a random player in the encounter.
3. Helix should be throwing [Sticky Bomb]s for the players to avoid.
4. Helix should [Leap] to random players once the Lumbering Oaf has been defeated.
5. Helix Gearbreaker should deal level appropriate damage to the target player.

**Comment by Cefiro-Caecias** [comment]
This Dungeons is still under reconstruction. Patience.
