### ISSUE TITLE
[QUEST] Never Trust a Big Barb and a Smile

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#464]
**Links:**

Quest link  -  https://www.wowhead.com/quest=25165/never-trust-a-big-barb-and-a-smile
Quest NPC link  - https://classic.wowhead.com/npc=3125/clattering-scorpid

**What is happening:**
Quest NPC doesn't cast the spell required to complete the quest.
Cluttering scorpions cast Sundering cleave.

**What should happen:**
Cluttering scorpions should cast Poison ionstead of Sundering Cleave.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
