### ISSUE TITLE
[Core] - Frost DK Howling Blast

### ISSUE THREAD

**Issue by L1n0x** [GuabinaCore/WoWKoi#465]
https://www.wowhead.com/spell=49184/howling-blast

**What is happening:**

is only infecting the main target with Frost Fever

**What should happen:**

it should be infecting all the enemies around the main target (10 yards)

**Comment by AnastasioTheSexyTauren** [comment]
Now it's only afecting close range 10yrds enemies, (if you cast howling blast to a enemie that is far away, it won't get frost fever)

**Comment by ShikoSCS** [comment]
Fixed, please test it

**Comment by AnastasioTheSexyTauren** [comment]
ShikoSCS nope, it's more broken now, check the new report ^^
