### ISSUE TITLE
[Mob] Durotar mobs not scaling up

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#466]
**Links:**
https://classic.wowhead.com/npc=3122/bloodtalon-taillasher
https://classic.wowhead.com/npc=3126/armored-scorpid
https://classic.wowhead.com/npc=3115/dustwind-harpy
https://classic.wowhead.com/npc=3116/dustwind-pillager
https://classic.wowhead.com/npc=3114/razormane-battleguard
https://www.wowhead.com/npc=39452/dreadmaw-toothgnasher
https://classic.wowhead.com/npc=3113/razormane-dustrunner
https://www.wowhead.com/npc=42504/mature-swine
https://classic.wowhead.com/npc=3197/burning-blade-fanatic*
https://classic.wowhead.com/npc=3108/encrusted-surf-crawler

*Of note: The Burning Blade Fanatics' Voidwalker Minions are scaled up to lvl 60, when they should only be scaled up to lvl 20.

**What is happening:**
These mobs aren't scaling with player level (up to lvl 20).

**What should happen:**
These mobs should scale up with player level, however, only up to lvl 20 - whenever the player is above lvl 20, these mobs should stay at lvl 20.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
