### ISSUE TITLE
[Mob] Durotar mobs scaling up too high

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#467]
**Links:**
https://classic.wowhead.com/npc=3099/dire-mottled-boar
https://www.wowhead.com/npc=39272/foaming-sea-elemental
https://classic.wowhead.com/npc=3107/surf-crawler
https://www.wowhead.com/npc=39268/northwatch-sharpshooter
https://www.wowhead.com/npc=39267/northwatch-marine
https://classic.wowhead.com/npc=3125/clattering-scorpid
https://www.wowhead.com/npc=39260/northwatch-infantryman
https://www.wowhead.com/npc=39245/northwatch-lug
https://www.wowhead.com/npc=39251/northwatch-supply-crate
https://classic.wowhead.com/npc=3100/elder-mottled-boar
https://classic.wowhead.com/npc=3123/bloodtalon-scythemaw
https://classic.wowhead.com/npc=3127/venomtail-scorpid
https://www.wowhead.com/npc=39595/furious-earthguard
https://www.wowhead.com/npc=39596/teeming-waterguard

**What is happening:**
These mobs scale up above lvl 20.

**What should happen:**
These mobs should only scale up to lvl 20, even after the player character being above lvl 20.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
