### ISSUE TITLE
[Mob] Northern/Southern Barrens mobs not scaling up

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#468]
**Links:**
https://classic.wowhead.com/npc=3397/kolkar-bloodcharger 
https://www.wowhead.com/npc=34855/honors-stand-peasant
https://www.wowhead.com/npc=37103/uncontrolled-growth
https://www.wowhead.com/npc=39005/northwatch-rifleman*

*Of note: Northwatch Riflemans are Friendly to the Horde, when they should be enemies to the Horde (the Alliance should stay as-is.)

**What is happening:**
These mobs are not scaling up to lvl 60.

**What should happen:**
These mobs should be scaling up to lvl 60.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
