### ISSUE TITLE
[Mob] Un'Goro Crater/Silithus mobs not scaling up

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#469]
**Links:**
https://www.wowhead.com/npc=38213/juvenile-bloodpetal
https://classic.wowhead.com/npc=6556/muculent-ooze
https://www.wowhead.com/npc=50897/ffexk-the-dunestalker

**What is happening:**
These mobs are not scaling up to lvl 60.

**What should happen:**
These mobs should be scaling up to lvl 60.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
