### ISSUE TITLE
[Mob] Desolace/Stonetalon Mountains mobs not scaling up

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#471]
**Links:**
https://www.wowhead.com/npc=36206/blubbergut
https://www.wowhead.com/npc=14229/accursed-slitherblade
https://www.wowhead.com/npc=14225/prince-kellen
https://classic.wowhead.com/npc=5916/sentinel-amarassan

**What is happening:**
These mobs aren't scaling up to lvl 60.

**What should happen:**
These mobs should scale up to lvl 60.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
