### ISSUE TITLE
Jammal'an the Prophet

### ISSUE THREAD

**Issue by JadedNate** [GuabinaCore/WoWKoi#472]
https://classic.wowhead.com/npc=5710/jammalan-the-prophet
https://www.wowhead.com/npc=5710/jammalan-the-prophet#sounds

**What is happening:**
Jammal'an the Prophet yells: "The shield be down! Rise up Atal'ai! Rise up!" and does not stop until the encounter starts.

**What should happen:**
Jammal'an should not yell this at any point.

**Comment by Cefiro-Caecias** [comment]
This dungeon is still in development. Patience ;)
