### ISSUE TITLE
[Arthas] - Deadmines Boss Encounter - Glubtok

### ISSUE THREAD

**Issue by JadedNate** [GuabinaCore/WoWKoi#473]
https://www.wowhead.com/npc=47162/glubtok

**What is happening:**
Glubtok's melee attacks are dealing more damage than he should; On the opposite side, Glubtok's abilities following [Arcane Power] -- Fire Blossom and Frost Blossom -- Do not deal nearly enough damage as they should.

**What should happen:**
Glubtok's melee attacks should deal slightly less damage, his phase 2 abilities should deal more damage.

**Comment by Cefiro-Caecias** [comment]
This Dungeons is still under reconstruction. Patience.
