### ISSUE TITLE
[Arthas] - Deadmines - Overtuned NPCs

### ISSUE THREAD

**Issue by JadedNate** [GuabinaCore/WoWKoi#474]
https://www.wowhead.com/npc=48230/ogre-henchman#abilities
https://www.wowhead.com/npc=48279/goblin-overseer
https://www.wowhead.com/npc=48262/ogre-bodyguard

**What is happening:**
Ogre Henchmen, Goblin Overseers, and Ogre Bodyguards all do more damage than they should.

**What should happen:**
The NPCs should deal level appropriate damage.

(There may be more in the dungeon that are overtuned, but these were the only ones our group was able to get to)

**Comment by LKArthas** [comment]
Fixed avaible on next update
