### ISSUE TITLE
[Arthas] - Deadmines - Mine Bunny

### ISSUE THREAD

**Issue by JadedNate** [GuabinaCore/WoWKoi#475]
https://www.wowhead.com/npc=48338/mine-bunny
https://www.wowhead.com/npc=48343/goblin-cocktail

**What is happening:**
WoWhead says this NPC is not in the game, I don't know if these 2 NPCs should be removed from the dungeon, but regardless: The NPCs do not attack the player, and once they're killed they should drop a tray of Goblin Cocktails

**What should happen:**
Unsure if they should be removed or not, but the Mine Bunnies in Deadmines should attack the player and drop Goblin Cocktails upon death

**Comment by LKArthas** [comment]
It shouldn't be removed but they need drop the cocktail plates and attack the player

**Comment by LKArthas** [comment]
Fixed avaible on next update
