### ISSUE TITLE
[Mob] Darkshore mobs not scaling up

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#476]
**Links:**
https://www.wowhead.com/npc=62246/shimmershell-snail
https://www.wowhead.com/npc=33903/thistle-bear-cub

**What is happening:**
These mobs aren't scaling up to lvl 60.

**What should happen:**
These mobs should scale to lvl 60.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
