### ISSUE TITLE
We all scream for ice cream... and then die - dead employes non interactable

### ISSUE THREAD

**Issue by aurcin** [GuabinaCore/WoWKoi#477]
https://www.wowhead.com/quest=28051/we-all-scream-for-ice-cream-and-then-die

**What is happening:**
dead employes are just dead corpses in water

**What should happen:**
those should be clickable to hook them from water

**Comment by Cefiro-Caecias** [comment]
Thousand Needles, Azshara and Desolace maps are not finished yet, they are still 50%. Patience ;)
