### ISSUE TITLE
Not getting any progress on quest OR exploration achivements

### ISSUE THREAD

**Issue by aaberant** [GuabinaCore/WoWKoi#479]
**Links:**
![Capture](https://user-images.githubusercontent.com/62454214/78466444-03e9c980-76b6-11ea-9466-c79a122d9e93.PNG)

from WoWHead or our Armory

**What is happening:**
if I complete a questline in a zone I do not get any progress towards the achievement same with exploration

**What should happen:**
I should obtain progress on the achievement for exploration and questing for the zones I complete
![Capture1](https://user-images.githubusercontent.com/62454214/78466460-3f849380-76b6-11ea-8fa3-582416ff4016.PNG)

**Comment by Cefiro-Caecias** [comment]
Fixed.
