### ISSUE TITLE
Red Mob (oily sludge) not attacking even when right next to it

### ISSUE THREAD

**Issue by aaberant** [GuabinaCore/WoWKoi#480]
**Links:**
![Capture2](https://user-images.githubusercontent.com/62454214/78466602-daca3880-76b7-11ea-9496-efdce16c6b99.PNG)

from WoWHead or our Armory

**What is happening:**
The mob that is red is not attacking when near it

**What should happen:**
either its supposed to be yellow and its showing as red or its set to passive for some reason but I feel its just supposed to be a yellow mob not a red

**Comment by Serithul** [comment]
it actually is a hostile mob. https://www.wowhead.com/npc=48315/oily-sludge

**Comment by Cefiro-Caecias** [comment]
Not bug present.
