### ISSUE TITLE
[Arthas?] - Male Troll Death Knight floating right eyeball

### ISSUE THREAD

**Issue by MBW91** [GuabinaCore/WoWKoi#482]
This is an issue that I've already reported to Blizzard when it was current on their servers. It was fixed at some point.

The problem is, that the right glowing eyeball of the male Troll Death Knight is floating, depending on the camera rotation. To reproduce this, either create an male Troll Death Knight, unequip his helmet and rotate the camera around him, or go into the character creation, select a male Troll Death Knight, click customize (the character won't wear a helmet then) and rotate the character.

[Here](https://www.youtube.com/watch?v=FI_QtGDY-ns) you can find the original YouTube video I've made and also sent Blizzard in the past, showing the bug.

**Comment by JadedNate** [comment]
This is probably one of the funniest things I've ever seen lmao

**Comment by MBW91** [comment]
sadKEK

**Comment by dan2142** [comment]
LULW

**Comment by LKArthas** [comment]
No idea yet pheraps dbc modelo info
