### ISSUE TITLE
The Ballad of Maximillian - Ungoro

### ISSUE THREAD

**Issue by Jeezuss69** [GuabinaCore/WoWKoi#483]
**Links:**https://www.youtube.com/watch?v=hDIPlg5svtY

**What is happening:** 
You accept the quest and the NPC disappears and does not accompany you to the broodmother.

**What should happen:**
He should follow you.

**Comment by LKArthas** [comment]
Quest have issue that needs to dismount but works dismount and Take it and Will work for you until the dismount flag is added
