### ISSUE TITLE
Pet Tamer dueling

### ISSUE THREAD

**Issue by RygardNin** [GuabinaCore/WoWKoi#485]
https://www.wowhead.com/quest=31812/zunta-the-pet-tamer

**What is happening:**
Unable to duel pet tamer. I've only checked Zunta in Durotar and Dagra in Northern Barrens. In the chat dialog there is an option to "duelo" but it does not activate the duel.

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed.
