### ISSUE TITLE
[Arthas] - Orgrimmar Cooking Daily

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#489]
**Links:**
https://www.wowhead.com/quest=26220/everything-is-better-with-bacon
from WoWHead or our Armory

**What is happening:**
Doing this daily seems to not reset the daily quest given on the next day.

**What should happen:**
It should reset everyday with a random quest no matter which one was completed on the day before.

Note: i'm not sure if it's the fault of that daily or something else, but i don't have any other clue about why or how it happens. But it's the 2nd time it's happening to me

**Comment by Cefiro-Caecias** [comment]
Arthas, no descifro el problema.

**Comment by LKArthas** [comment]
Flags needs to be checked aganist the pool tables
