### ISSUE TITLE
[Arthas] - Quest: To Be Horde... , Id: 26115

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#495]
**Links:**
https://www.wowhead.com/quest=26115/to-be-horde
from WoWHead or our Armory

**What is happening:**
Event isn't working as it should be.

**Comment by Serithul** [comment]
More info on that is that the balloon with the bomb moves over the tree and then disappears. After that instead of seeing an explosion with a lot of smoke and stuff and then getting phased, you just get phased immediately.

**Comment by Serithul** [comment]
It should move over the tree, drop the bomb, a giant explosion happens with a lot of smoke and stuff and then become phased.

**Comment by LKArthas** [comment]
Serithul quest is working with the explosion there are a distances of sight bug that doesnt display it yet for players but those effects are added
