### ISSUE TITLE
Northwatch Marine Ticking Time Bomb Damage too High (Durotar - Tiragarde Keep)

### ISSUE THREAD

**Issue by Crzyfist** [GuabinaCore/WoWKoi#498]
**Links:**

from WoWHead or our Armory

**What is happening:** I was fighting a Northwatch Marine in Durotar (NPC being lvl 7, same as me) and suddenly i was dead...while checking Death Recap i noticed, that "Ticking Time Bomb" hit me for 587 Damage. That shouldn't be that high on that level i guess. 

**What should happen:** The Spell should deal less Damage by a Level 7 NPC. I'll put a screen of my Death Recap below.
![157f24c24ed8017eae9c8be71cbf148e-png](https://user-images.githubusercontent.com/47222399/78672429-eba9c280-78e0-11ea-9dd2-8a300211e1f2.jpg)

**Comment by Cefiro-Caecias** [comment]
Spells overdamage under review.
