### ISSUE TITLE
[Arthas] - Invincible Hogger

### ISSUE THREAD

**Issue by LostAgeMagic** [GuabinaCore/WoWKoi#499]
**Links:**

from WoWHead or our Armory

**What is happening:**
When Hogger rushes to the meat and starts to eat, he spawns several adds. It seems that once Hogger begins the eating mechanic, he sometimes becomes invincible and absorbs all received damage until the end of time, making the quest Wanted: "Hogger" impossible to complete. He's supposed to be stunned by damage to end the healing effect, but in this case he did not.
On the second attempt this invincibility bug did not reoccur, and he was stunned by damage as intended and was able to be defeated.

**What should happen:**
Hogger should be able to be stunned and take damage again.

**Comment by LKArthas** [comment]
Fixed
