### ISSUE TITLE
Zone: Eastern Plaguelands - The Scarlet Enclave

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#5]
Zone: Eastern Plaguelands - The Scarlet Enclave
Quest: Massacre at Light's Point (https://www.wowhead.com/quest=12701/massacre-at-lights-point)
Some of the mobs are unaffected by cannon shots, taking no damage and having no reaction to the shots.

**Comment by Cefiro-Caecias** [comment]
Fixed.
