### ISSUE TITLE
Orgrimmar Fishing Daily: A Golden Oportunity

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#508]
**Links:**
https://www.wowhead.com/quest=26572/a-golden-opportunity
https://www.wowhead.com/npc=43331/golden-stonefish
https://www.wowhead.com/item=58958/drowned-thunder-lizard-tail
from WoWHead or our Armory

**What is happening:**
Killing them with the 2nd quest item makes the mobs drop no loot.
They can be killed by the player without the 2nd quest item and they drop loot then.

**What should happen:**
They should not be able to get killed by the player. Only with the linked quest item and drop the item needed for the quest.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
