### ISSUE TITLE
Eversong Mobs

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#511]
**Links:**
https://www.wowhead.com/npc=15649/feral-dragonhawk-hatchling
https://www.wowhead.com/npc=15650/crazed-dragonhawk
https://www.wowhead.com/npc=15271/tender
https://www.wowhead.com/npc=15294/feral-tender

**What is happening:**
Mobs show as hostile to the player.

**What should happen:**
Mobs show as neutral to the player.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
