### ISSUE TITLE
[Arthas] - Quest= 28235 Burnside Must Fall - Hillsbrad Foothills

### ISSUE THREAD

**Issue by RygardNin** [GuabinaCore/WoWKoi#514]
https://www.wowhead.com/quest=28235/burnside-must-fall#comments

**What is happening:**
Event not triggering. Burnside remains invulnerable. I've tried dropping quest and re-accepting. Running under him as some comments on wowhead suggested, yet unable to trigger event to complete quest. Stopping zone progression.

**What should happen:**
As you approach Burnside, event should trigger, dropping shield and starting combat.

**Comment by RygardNin** [comment]
Update: After server restart I went back and Magister Burnside was in he air, in the correct position and I was able to trigger event by walking under him. Earlier when he was bugged, he was positioned on the ground.

**Comment by LKArthas** [comment]
Fixed
