### ISSUE TITLE
[Arthas] - Lord Walden Evade

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#515]
**Links:**
https://www.wowhead.com/npc=46963/lord-walden
https://www.wowhead.com/spell=57755/heroic-throw

**What is happening:**
Lord Walden constantly evades when you pull him using the spell Heroic Throw from afar. We tried tping out of dungeon to reset aggro and it didn't work - he still evades.

**What should happen:**
Lord Walden should aggro and take damage even when you use ranged spells on him.

**Comment by LKArthas** [comment]
Fixed
