### ISSUE TITLE
[Core] - Inspiring Presence (Talent) doesn't work at all (SpellID: 205484)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#516]
**Links:** //

from WoWHead or our Armory

**What is happening:**

Inspiring presence doesn't heal at all

**What should happen:**

All party members including the players should be healed by 3% of their damage dealt :D

**Comment by Serithul** [comment]
https://wow.gamepedia.com/Inspiring_Presence

**Comment by login6710** [comment]
Fixed
