### ISSUE TITLE
Quest: Enemies Below, Id: 

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#519]
**Links:**
https://www.wowhead.com/quest=31034/enemies-below
https://www.wowhead.com/quest=31036/enemies-below
https://www.wowhead.com/quest=31037/enemies-below
https://www.wowhead.com/npc=61724/commander-bagran
from WoWHead or our Armory

**What is happening:**
Missing completion text on Commander Bagran.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
