### ISSUE TITLE
[Core] - NPC Spell Earthgrab

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#52]
Lost One Seer Earthgrab Totem should be rooting the player not attacking https://imgur.com/h18qxyi.jpg

https://ptr.wowhead.com/spell=8377/earthgrab

**Comment by Thordekk** [comment]
That spell is from one npc or from player class?

**Comment by Velthur-bot-3000** [comment]
NPC link: https://www.wowhead.com/npc=761/lost-one-seer#abilities
