### ISSUE TITLE
Ragefire Chasm Quests Missing Text

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#520]
**Links:**
https://www.wowhead.com/quest=30984/no-orc-left-behind
https://www.wowhead.com/quest=30983/the-dark-shaman
https://www.wowhead.com/quest=30998/a-new-enemy
from WoWHead or our Armory

**What is happening:**
A New Enemy is missing progress text.

All are missing completion text.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
