### ISSUE TITLE
[Core] - Polymorph rarely breaks on damage taken

### ISSUE THREAD

**Issue by LostAgeMagic** [GuabinaCore/WoWKoi#522]
**Links:**

from WoWHead or our Armory

**What is happening:**
The spell Polymorph seems to not break when damage is taken, except seemingly randomly in rare occasions.

**What should happen:**
"Damage will cancel the effect." Does not occur in most cases.

**Comment by Thordekk** [comment]
If im correct damage interrupt spell its working correct
