### ISSUE TITLE
[Mob] Mobs not scaling up 

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#523]
**Links:**
Mobs that do not scale up:
https://www.wowhead.com/npc=39385/screamslash *
https://www.wowhead.com/npc=39337/wayward-plainstrider *
https://www.wowhead.com/npc=3112/razormane-scout *
https://www.wowhead.com/npc=3111/razormane-quilboar *
https://www.wowhead.com/npc=39352/gaur-icehorn *
https://www.wowhead.com/quest=25257/ghislania *
Mobs that scale up too high:
https://www.wowhead.com/npc=42859/wild-mature-swine *
https://www.wowhead.com/npc=3106/surf-crawler *

**What is happening:**
These mobs aren't scaling up to player level.
Note: Mobs marked with a * should only be scaled up to lvl 20, as they're in starting areas.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
