### ISSUE TITLE
[QUEST] My time has passed (Desolace - starting quest))

### ISSUE THREAD

**Issue by ventarius5** [GuabinaCore/WoWKoi#528]
**Links:**

https://www.wowhead.com/quest=14184/my-time-has-passed

**What is happening:**

After accepting/turning in the quest, a vehicle mount spawns and nothing happens further.

**What should happen:**

After accepting/turning in the quest, a vehicle mount should fly you to the quest destination.

**Comment by Cefiro-Caecias** [comment]
The Desolace, Azshara and Thousand Needles maps are still under reconstruction, at 50%.
