### ISSUE TITLE
[NPC]Death Knight starting zone frost weapon vendor

### ISSUE THREAD

**Issue by dan2142** [GuabinaCore/WoWKoi#529]
Accidentally sold my 1H swords and there is no way to get them back, i need help as the vendor Quartermaster Ozorg dose not sell any 1h swords for the frost spec.
https://www.wowhead.com/npc=28512/quartermaster-ozorg
https://www.wowhead.com/item=142320/runed-soulsaber&bonus=0
https://www.wowhead.com/item=142321/saber-of-the-ebon-blade&bonus=0

**Comment by Serithul** [comment]
He actually isn't supposed to sell the saber of the ebon blade.

**Comment by dan2142** [comment]
That dose not make any sense meaning that if u choose the saber at the end of the quest line u can still get the 2h axe or sword from the vendor but not the other way around umm what ?!

**Comment by Serithul** [comment]
Indeed. Blizzard has not added the saber to the Quartermaster Ozogs' wares for selling. I know it's frustrating but that's how it's supposed to be. Now if the devs decide to add them, it's another story. But it's definitely not a bug.

**Comment by dan2142** [comment]
Well more like them forgetting and adding them later in 8.3, tho i don't think we should only stick to blizzard as some basic QOL is always welcomed and they did a lot of mistakes themselves like forcing Frost in a 1h spec and forgetting to add the the items to the vendor or worst after that like for example the azerite system, rush BFA and release W3 reforged like that etc.

**Comment by Cefiro-Caecias** [comment]
Fixed, Available in the next update. It doesn't matter what Blizzard does with these weapons: what is exposed by @dan2142 makes a lot of sense ^^
