### ISSUE TITLE
[Core] - Warlock spells bugs.

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#535]
**Links:**
https://www.wowhead.com/spell=104316/call-dreadstalkers
https://www.wowhead.com/spell=205145/demonic-calling
https://www.wowhead.com/spell=686/shadow-bolt

https://www.wowhead.com/spell=234153/drain-life
https://www.wowhead.com/spell=198590/drain-soul

https://www.wowhead.com/spell=193396/demonic-empowerment

https://wow.gamepedia.com/Soul_Shards

https://www.wowhead.com/spell=6201/create-healthstone
from WoWHead or our Armory

**What is happening:**
Demonic calling buff is generated by a shadow bolt but consumed by the next shadow bolt not the dreadstalker pets.

Call of the dreadstalker deals more damage than intended.

Drain Life and Drain Soul heal for way more than they are supposed to.

Demonic empowerment only affects the permanent pet you have summoned, not the temporary ones.

The 5th soul shard generated either appears but is unusable or instantly disappears.
If u have 4 souls shards and you get out of combat, you instantly go to 3 soul shards.

The healthstone you create from the spell Create Healthstone appears to have 0 charges but can still be used.

**What should happen:**
Demonic Calling should be generated by shadow bolts and be consumed by Call of the dreadstalkers.
Call of the dreadstalkers shouldn't deal that much damage

Drain life and drain soul should heal for much less.

Demonic empowerment should affect all your pets, permanent or temporary summoned.

The 5th soul shard should appear and be usable if generated.
You should not get reset to 3 soul shards instantly, but they should degenerate over time down to 3.

The healthstone created should show 3 charges, with 1 being removed every time it is used.

**Comment by Evilwowshaman** [comment]
To add in, the same thing is happening on affliction as well as fury warrior. You're supposed to learn the rnak 2 of Unstable affliction at level 24, but you learn it as you get Unstable affliction. Rank 2 essentially gives soul shards back whenever the wearer of the debuff dies.
