### ISSUE TITLE
[Core] - Priest - Power Word: Shield

### ISSUE THREAD

**Issue by justfortest098** [GuabinaCore/WoWKoi#540]
**Links:**
from WoWHead or our Armory
https://www.wowhead.com/spell=17/power-word-shield

**What is happening:**
when you put it on low level, 1 hit remove it beside the fact that tooltip says XXXhp absorb left.
maybe due to the combat log bug dont know.

**What should happen:**
it should last until all the absorb amount become 0.

**Comment by Spydoc** [comment]
Just to add to this report, the shield was absorbing the proper amount of damage up to around level 20. After that point, the shield started getting destroyed from only one hit, as described in the report.

**Comment by Thordekk** [comment]
Duplicated report
