### ISSUE TITLE
Azshara - Arborcide Quest Chain

### ISSUE THREAD

**Issue by CodrinCiupec** [GuabinaCore/WoWKoi#542]
**Links:**
https://www.wowhead.com/quest=25275/report-to-the-labor-captain
from WoWHead or our Armory

**What is happening:**
Recharge ability on the shredder doesn't work. It's supposed to heal your shredder but it doesn't. Says immune when you use it.

**What should happen:**
Heal the shredder

**Comment by Serithul** [comment]
Azshara isn't fully scripted mate and won't be until some other progress is made first.

**Comment by Cefiro-Caecias** [comment]
The Desolace, Azshara and Thousand Needles maps are still under reconstruction, at 50%.
