### ISSUE TITLE
[Core] - Aggro and Evade

### ISSUE THREAD

**Issue by OxerMiester** [GuabinaCore/WoWKoi#543]
**Links:**

https://www.wowhead.com/npc=38301/spitescale-siren

**What is happening:**
Some of the mobs inside the cave aggro from far and follow me without attacking. All attacks (Normal and skills) will be evaded.

**What should happen:**
Hit should not be evaded and aggro should drop if u run far enough
![Evade](https://user-images.githubusercontent.com/63426109/78942855-1d8f7480-7aed-11ea-86d1-005fa82fb356.png)

**Comment by Serithul** [comment]
Link the mobs, not the associated quest. It's a mob behavior problem, not a quest one.

**Comment by Cefiro-Caecias** [comment]
New fix implemented. Available after the next update.
