### ISSUE TITLE
[Core] - Furious slash buff is not coming up

### ISSUE THREAD

**Issue by Evilwowshaman** [GuabinaCore/WoWKoi#550]
Fury warrior's ability called Furious Slash isn't working properly. It isn't giving its buff whenever it's casted.

 It is supposed to be giving the caster a buff stating "Increases your Bloodthirst critical strike chance by 15%, until it next deals a critical strike, stacking up to 6 times." (Huge impact when you're getting the "Enrage" buff every time you crit.)

**Comment by biosintesis** [comment]
Fix
