### ISSUE TITLE
[Core] - Honorable Medallion 

### ISSUE THREAD

**Issue by TheAxelSrb** [GuabinaCore/WoWKoi#551]
https://www.wowhead.com/quest=26074/beginning-of-the-end

When i was doing this quest i got the Honorable Medallion achievement when i left the hot air balloon in which you ride.
![Screenshot (58)](https://user-images.githubusercontent.com/63316343/79007432-73026a80-7b5b-11ea-984e-75af60dcd188.png)

You shouldn't get the achievement

**Comment by Maczuga** [comment]
Same here, the quest is called "Beginning of the End" - there is some Balloon Throwing Station that keeps damaging me and it won't fly off:

![image](https://user-images.githubusercontent.com/544349/79603752-34d1f180-80ed-11ea-846c-4826bb45c55c.png)
