### ISSUE TITLE
My time has come quest

### ISSUE THREAD

**Issue by TheAxelSrb** [GuabinaCore/WoWKoi#552]
https://www.wowhead.com/quest=14184/my-time-has-passed

The Dragonhawk isn't moving
![Screenshot (59)](https://user-images.githubusercontent.com/63316343/79010703-c88e4580-7b62-11ea-9b40-1dd0c96a622c.png)

The Dragonhawk should fly you to Furien's Post

**Comment by dan2142** [comment]
+1

**Comment by Cefiro-Caecias** [comment]
The Desolace, Azshara and Thousand Needles maps are still under reconstruction, at 50%.
