### ISSUE TITLE
[Arthas] - Northwatch Supply Crate aggressive

### ISSUE THREAD

**Issue by uh0** [GuabinaCore/WoWKoi#554]
**Links:**
https://www.wowhead.com/npc=39251/northwatch-supply-crate#objective-of

**What is happening:**
https://www.youtube.com/watch?v=Il5gtedE4w8
Boxes are aggressive and attack (if the box is attacked). Both the crate and Northwatch Lugs reward to much XP (recorded while 3x is live, but still far to high.).

**What should happen:**
https://youtu.be/677VIxbSzXY?t=42
Create should drop when attacked, then need to take damage before breaking for quest: https://www.wowhead.com/quest=25167

**Comment by uh0** [comment]
_They're also not despawning on time (if at all) once getting to "Attack Plans - Valley of the trials" 
https://classic.wowhead.com/object=3189/attack-plan-valley-of-trials

Tried to count how many but there seems to be endless._  

- This doesn't seem to be happening after the last server crash.

**Comment by LKArthas** [comment]
Fixed avaible on next update
