### ISSUE TITLE
Animations on NPCs are broken/looping

### ISSUE THREAD

**Issue by daddylongneck123** [GuabinaCore/WoWKoi#558]
**Links:**

from WoWHead or our Armory

**What is happening:**
Goblins in starting area football field cowering in fear
![WoWScrnShot_041020_202159](https://user-images.githubusercontent.com/63481493/79030940-96ccad00-7b69-11ea-98e4-91a52f0296e6.jpg)

**What should happen:**
Theyre supposed to be standing, cheering and cycling through emotes see:
https://youtu.be/jfG7BfktMZM?t=454  (@ 07:34 if link doesnt work)

**Comment by daddylongneck123** [comment]
see these orcs outside the orc starting area: 
![WoWScrnShot_041120_192905](https://user-images.githubusercontent.com/63481493/79057069-035bb080-7c2b-11ea-9d9e-6fe87830f957.jpg)

**Comment by daddylongneck123** [comment]
random NPCs with a map open constantly
![WoWScrnShot_041120_202919](https://user-images.githubusercontent.com/63481493/79057785-24280400-7c33-11ea-878c-819183267808.jpg)


 ![WoWScrnShot_041120_193437](https://user-images.githubusercontent.com/63481493/79057119-80872580-7c2b-11ea-9067-b1aad676fa4c.jpg)

![WoWScrnShot_041120_202824](https://user-images.githubusercontent.com/63481493/79057778-0c508000-7c33-11ea-877e-b70d5326811c.jpg)


![WoWScrnShot_041120_202311](https://user-images.githubusercontent.com/63481493/79057712-4e2cf680-7c32-11ea-9e72-2c5d5c3fb608.jpg)
:
![WoWScrnShot_041120_193529](https://user-images.githubusercontent.com/63481493/79057132-a57b9880-7c2b-11ea-94e0-ec5134a44719.jpg)

**Comment by daddylongneck123** [comment]
These trainers just stuck in this casting animation: 
![WoWScrnShot_041120_193615](https://user-images.githubusercontent.com/63481493/79057134-be844980-7c2b-11ea-93cd-bf030174ac77.jpg)

**Comment by daddylongneck123** [comment]
innkeeper dancing non stop: 
![WoWScrnShot_041120_202102](https://user-images.githubusercontent.com/63481493/79057685-f9897b80-7c31-11ea-864d-f9ea4b37b5a7.jpg)

**Comment by Arkanheal** [comment]
To be fair, I think it's even better this way. It gives a feel of something happening you know what I mean?
