### ISSUE TITLE
[QUEST BROKEN] Pirate Accuracy Increasing

### ISSUE THREAD

**Issue by LostAgeMagic** [GuabinaCore/WoWKoi#559]
**Links:**
https://www.wowhead.com/quest=25532/pirate-accuracy-increasing
from WoWHead or our Armory

**What is happening:**
Portion of the quest [0/1 Get a boat from Mazzer] does not complete despite getting a boat. Objective to extinguish fires does work.

**What should happen:**
Pretty obvious.

**Comment by Cefiro-Caecias** [comment]
The Desolace, Azshara and Thousand Needles maps are still under reconstruction, at 50%.
