### ISSUE TITLE
[Core] - Issue with mining

### ISSUE THREAD

**Issue by Evilwowshaman** [GuabinaCore/WoWKoi#560]
My mining skill is getting progression through copper veins at 125 skill rank, although they are gray for me. This is happening currently in Durotar, haven't payed much attention for it to be happening somewhere else.

Ores that are gray skilled for me, shouldn't reward me mining skill.

**Comment by Arkanheal** [comment]
See #4

**Comment by Velthur-bot-3000** [comment]
this is a duplicate bug tracker to issue #4 listed above.  I will close this ticket in order to keep only one open.  Thank you for reporting, and continue to enjoy the server!
