### ISSUE TITLE
Mobs levels (not a big thing)

### ISSUE THREAD

**Issue by Evilwowshaman** [GuabinaCore/WoWKoi#561]
Currently level of the mobs in starter zones are as well interesting. I'm in Durotar farming copper ore (earlier thread) with my lvl 30 warrior, and the mobs scale from lvl 9 to lvl 20. Even in a cave mobs with same name wary.

Mobs lvl can wary, but I don't think same place should have that big of a difference, when everywhere else the mobs are the same level as everyone else.

**Comment by Serithul** [comment]
The starting area mobs scale till level 20 in 7.3.5. You can check this link to see which areas scale from and to which level for 7.3.5.
Other than that there are times when there are multiple npc entries on wow's database with the same name though. If that's the case then you should report each and any mob you see according to how it is supposed to be.
Remember to link the mobs from wowhead.com as it is easier for them to search for specific mob ids in the database than search the whole database for a single mob and/or its' copies.

https://wow.gamepedia.com/Zone_scaling
