### ISSUE TITLE
[Core] - Heroic Leap Visual BUG

### ISSUE THREAD

**Issue by PilavKOI** [GuabinaCore/WoWKoi#562]
**Links:**
https://www.wowhead.com/spell=6544/heroic-leap#modified-by
couldn't really find 7.3.5 log

**What is happening:**

when u use Heroic Leap as any warrior spec There is visual bugs it is not really smooth as it is on retail You Do The crash animation before you even land behind you not under your feet

**What should happen:**
it should be smoother :D check a video about warrior in 7.3.5 its very smooth & enjoyable to use it You Feel like a OP warrior crashing the ground when arriving on there head xD <3

**Comment by GuabinaCore** [comment]
#593 same report
