### ISSUE TITLE
Spinal Dust

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#569]
**Links:**
https://www.wowhead.com/item=22642/spinal-dust#dropped-by
https://www.wowhead.com/npc=16305/dreadbone-sentinel
https://www.wowhead.com/npc=16308/deathcage-sorcerer
https://www.wowhead.com/npc=16303/dreadbone-skeleton
https://www.wowhead.com/npc=16307/deathcage-scryer

**What is happening:**
Spinal Dust's drop rate is 100% for all mobs.

**What should happen:**
Spinal Dust drop rate is 57% for dreadbone-sentinel, 30% for deathcage-sorcerer, 20% for deathcage-sorcerer and 9% for Deathcage Scryer.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
