### ISSUE TITLE
[Core] - Spell 190931/mongoose-fury

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#57]
Class - Hunter
Spec - Survival
Spell - Mongoose Fury (buff)
https://www.wowhead.com/spell=190931/mongoose-fury

6x stacking buff for 14 secs, does not increase every next Mongoose Bite by 50%, rather it increases every next Mongoose Bite by 50% from first attack.

How it works:
Stacking buff does not increase every next Mongoose Bite damage by 50% of previous buffed attack, rather it increases next Mongoose Bite only by 50% of first Mongoose Bite.
Example: 10.000, 15.000, 20.000, 25.000, 30.000, 35.000

How it should work:
It should increase every next Mongoose Bite damage by 50% out of previous one.
Example:
10.000, 15.000, 22.500, 33.750, 50.625, 75.938

**Comment by login6710** [comment]
Boys check this spell and in my opinion the calculation of the damage it is doing is correct. If we calculate based on the accumulation of the aura we will have a very large increase in damage. I tested it on lvl110 and it does a lot of damage if we modify the way it calculates damage. Anyway, for me this spell has no problems
