### ISSUE TITLE
[Core] - Deep Wounds (ID: 115768) and Protection warrior spells

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#570]
**Links:** https://www.wowhead.com/spell=115768/deep-wounds

from WoWHead or our Armory

**What is happening:**
Right now all protection warrior damaging spells (including Shield Slam and Thunderclap) are applying Deep Wounds to the damaged NPCs

**What should happen:**
Deep Wounds should only be applied to NPCs hit by Devastate - ID: 20243 (or Auto Hit if Devastator - ID: 236279 - is talented) and Revenge - ID: 6572.

**Comment by GuabinaCore** [comment]
Fixed
