### ISSUE TITLE
[Core] - Quest More Rotting Hearts

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#571]
**Links:**
https://www.wowhead.com/quest=9217/more-rotting-hearts

**What is happening:**
Quest marker is yellow.

**What should happen:**
Quest marker is blue (repeatable quest)

**Comment by Cefiro-Caecias** [comment]
Este es un error que afecta a todas las quests repetibles: las muestra con ícono amarillo y no azul.
