### ISSUE TITLE
[NPC] Dormus the Camel-Hoarder (NPCID: 50245)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#573]
**Links:** https://www.wowhead.com/npc=50245/dormus-the-camel-hoarder#comments

from WoWHead or our Armory

**What is happening:**
Dormus is always visible.

**What should happen:**
Dormus should only be visible if you find the right figurine in Uldum which gives you a debuff (after beeing tped from Uldum to Feralas) that allows you to see him.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
