### ISSUE TITLE
Durotar - Golden Stonefish

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#574]
**Links:**
https://www.wowhead.com/npc=43331/golden-stonefish
from WoWHead or our Armory

**What is happening:**
They aren't swimming as they should. They are stuck on the bottom of the lake they are in.

**What should happen:**
They should be swimming in the lake and not get stuck in the bottom.

**Comment by Cefiro-Caecias** [comment]
Pending aquatic mobs repair.
