### ISSUE TITLE
[Core] - Paladin - Judgement

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#576]
**Links:**
https://www.wowhead.com/spell=275779/judgment
from WoWHead or our Armory

**What is happening:**
Protection: Hits 2 targets at any time.

**What should happen:**
Protection: Should hit only 1 target at all times.

**Comment by Arkanheal** [comment]
Duplicate of #32

**Comment by Serithul** [comment]
Indeed, but i have reported a protection bug as well. Editing now to remove the Retribution part.

**Comment by ShikoSCS** [comment]
Fixed
