### ISSUE TITLE
Sunstrider Isle - Mob Level scaling.

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#578]
**Links:**
https://www.wowhead.com/npc=15274/mana-wyrm
https://www.wowhead.com/npc=15366/springpaw-cub
https://www.wowhead.com/npc=15372/springpaw-lynx
https://www.wowhead.com/npc=15271/tender
https://www.wowhead.com/npc=15294/feral-tender
https://www.wowhead.com/npc=15273/arcane-wraith
https://www.wowhead.com/npc=15298/tainted-arcane-wraith
https://www.wowhead.com/npc=15367/felendren-the-banished
from WoWHead or our Armory

**What is happening:**
They don't scale in the appropriate level zone.

**What should happen:**
Mana wyrm should scale from 1 till 4.
Springpaw Cub and Lynx should scale from 1 till 3.
Tender and Feral Tender should scale from 2 till 4.
Arcane Wraith, Tainted Arcane Wraith and Felendren the Banished should scale from 3 till 5.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
