### ISSUE TITLE
Eversong Woods - Mob Scaling

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#579]
**Links:**
https://www.wowhead.com/npc=15644/wretched-urchin
https://www.wowhead.com/npc=15638/arcane-patroller
https://www.wowhead.com/npc=15649/feral-dragonhawk-hatchling
https://www.wowhead.com/npc=15635/eversong-tender
https://www.wowhead.com/npc=15654/plaguebone-pillager
from WoWHead or our Armory

**What is happening:**
They don't scale.

**What should happen:**
Wretched Urchin, Feral Dragonhawk Hatchling should scale from 4 till 20.
Arcane Patroller from 5 till 20.
Eversong Tender, Plaguebone Pillager from 6 till 20.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
