### ISSUE TITLE
[Arthas] - Shadowfang Keep Dungeon wood door closed

### ISSUE THREAD

**Issue by ghost** [GuabinaCore/WoWKoi#580]
Links:
https://www.wowhead.com/npc=46962/baron-ashbury

**What is happening:**
I am multiboxing 5 characters and before first boss(Baron Ashbury) one of my character got stuck to stairs. It didn't never do any dmg to Baron Ashbury or reach it. After Baron Ashbury there is this door that opens after Baron Ashbury kill and that character who got stuck, the door did keep closed. Then i did wipe on second boss with my 4 man team and after res. The door was closed for all 5 characters. 

edit: I did saw lever in cellar but it doesn't work, also talking to undead npc doesn't work.

**What should happen:**
If one or more characters in party kills Baron Ashbury the door should stay open till end of dungeon to all character in party.

**Comment by LKArthas** [comment]
Fixed avaible on next update
