### ISSUE TITLE
[Arthas] - Quest In Defense of Krom'gar Fortress

### ISSUE THREAD

**Issue by dan2142** [GuabinaCore/WoWKoi#584]
https://www.wowhead.com/quest=26058/in-defense-of-kromgar-fortress
https://www.wowhead.com/npc=42015/gnomish-bomber
https://www.wowhead.com/npc=42016/gnomish-flying-machine

The hit box on the gnomish bombers  and  gnomish flying machine is bugged resulting in a lot of missing shots or unable to shoot them if they are too close.

**Comment by Maczuga** [comment]
Can confirm. I was able to kill 20 wing commanders and only 1 bomber. Bombers were mostly untouchable by guns, even tho I killed the commanders inside them.
