### ISSUE TITLE
[Arthas] - Stable master

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#59]
Class - Hunter -  all classes
<Stable Master> NPCs
https://wowwiki.fandom.com/wiki/Stable_master

How it works:
<Stable Master> NPCs are just vendor NPCs.

How it should work:
<Stable Master> NPCs should provide option to Hunters to buy stable slots to store Hunter Pets. Up to 50 pets.
In addition, <Stable Master> NPCs should offer a dialogue to heal all injured Battle Pets as well as find lost non-combat pets.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
