### ISSUE TITLE
[Core] - Shield Slam

### ISSUE THREAD

**Issue by PilavKOI** [GuabinaCore/WoWKoi#590]
**Links:**

Protection warrior spell

**What is happening:**

when you get a reset of [Shield Slam] it doesn't show an icon on your screen that it did so its hard to tell until you look at your bar

**What should happen:**
it should appear as an icon as [Revenge] does when it becomes free to use without wasting rage ^^

**Comment by Serithul** [comment]
https://www.wowhead.com/spell=23922/shield-slam

**Comment by GuabinaCore** [comment]
Fixed
