### ISSUE TITLE
[Core] - Warrior - Bounding Stride (TalentID: 202163)

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#593]
**Links:** https://www.wowhead.com/spell=202163/bounding-stride

from WoWHead or our Armory

**What is happening:**
So the duration of the movement speed buff starts to countdown at the beginning of the jump, so it's basically 2 sec instead of free for a max range Heroic Leap.

**What should happen:**
The duration of the movement speed bugg should start to countdown when you land the jump, which means you have a 3 sec duration no matter the Heroic Leap size.

**NB**: Might be linked to #562

**Comment by biosintesis** [comment]
0 counts in auras countdown.
