### ISSUE TITLE
Broken pathginding 

### ISSUE THREAD

**Issue by lillemand13** [GuabinaCore/WoWKoi#596]
**Links:**
-
from WoWHead or our Armory

**What is happening:**
When you get feared by mobs/players near a hill you get feared through the ground and fall to your death 

**What should happen:**
Stop/clim the hill

**Comment by PilavKOI** [comment]
that also happens when you use : https://www.wowhead.com/spell=126664/charge
or : https://www.wowhead.com/spell=198304/intercept on any wall or object you will fall under the map
on retail you would skip the objects until you reach your target

**Comment by Cefiro-Caecias** [comment]
V-maps issue is under review.
