### ISSUE TITLE
[Core] - Impending victory 

### ISSUE THREAD

**Issue by PilavKOI** [GuabinaCore/WoWKoi#597]
**Links:**

https://www.wowhead.com/spell=202168/impending-victory

**What is happening:**

Does not reset the cooldown when killing anything

**What should happen:**
killing an enemy that yields experience or honor resets the cooldown of impending victory

**Comment by Arkanheal** [comment]
Duplicate #518

**Comment by ShikoSCS** [comment]
Fixed, pliss tested
