### ISSUE TITLE
[Core] - Inspiring Presence

### ISSUE THREAD

**Issue by PilavKOI** [GuabinaCore/WoWKoi#598]
**Links:**

https://wow.gamepedia.com/Inspiring_Presence

**What is happening:**

0 healing to you and your allies tested in dungeon aura appearing on players and pets but not working at all

**What should happen:**
everyone who has the aura should be healed for 3% of all damage they deal.

**Comment by Arkanheal** [comment]
Supposed to be fixed in #516 can confirm it still doesn't work

**Comment by Arkanheal** [comment]
@Sefrenia-Caecias As it's not closed I'm commenting here.
Apparently up from [patch 7.1.0](https://wow.gamepedia.com/Patch_7.1.0#Warrior) and different sources across the internet ([this](https://www.reddit.com/r/wow/comments/4tohbn/warrior_inspiring_presence_and_soloing/) and [this](https://blizzardwatch.com/2016/09/14/patch-7-1-ptr-patch-notes/) amongst others). Inspiring Presence shouldn't heal the warrior but only his raid or party members. 
Which means that if there is 2 protections warriors with this talent in the group they have to benefit from one another and the buff does not stack for other party members.
