### ISSUE TITLE
[Core] - Bounding Stride

### ISSUE THREAD

**Issue by PilavKOI** [GuabinaCore/WoWKoi#599]
**Links:**

https://www.wowhead.com/spell=202163/bounding-stride

**What is happening:**

when you leap it should give you the bonus movement speed when you land on your location you choose

**What should happen:**

it gives you the bonus 70% for 3 sec before even landing also i have posted a bug about Heroic leap i think that it might be causing the problem to appear

**Comment by Arkanheal** [comment]
Duplicate #593
