### ISSUE TITLE
[Saitama] - Spell Flanking Strike

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#60]
Class - Hunter
Spec - Survival
Spell - Flanking Strike

Spell - Flanking Strike
https://wowwiki.fandom.com/wiki/Flanking_Strike

How it works:
Completely Missing Secondary component.

Secondary Component:
If the target is attacking Player, Player pets attack will deal 50% increased damage and 400% increased threat. Otherwise, Player attack will deal 50% increased damage

**Comment by login6710** [comment]
Fixed
https://github.com/GuabinaCore/TYCE-Group/commit/19f046a4a49f91ec367c6fcb7b03a4323efa6a19
