### ISSUE TITLE
Quest - Underlight Ore Samples

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#602]
**Links:**
https://www.wowhead.com/quest=9207/underlight-ore-samples
https://www.wowhead.com/npc=16251/deathstalker-maltendis
https://www.wowhead.com/npc=16293/apprentice-shatharia

**What is happening:**
Quest starts from npc Deathstalker Maltendis.

**What should happen:**
Quest starts from npc Apprentice Shatharia.

**Comment by Cefiro-Caecias** [comment]
Deliberately put like this, because of distracted players ;)
