### ISSUE TITLE
[Core] - Demonwrath

### ISSUE THREAD

**Issue by Spydoc** [GuabinaCore/WoWKoi#603]
**Links:**

https://www.wowhead.com/spell=176009/demonwrath

**What is happening:**

The skill doesn't do any damage at all.

**What should happen:**

The skill should be doing damage to targets that are near your minions.

**Comment by Crzyfist** [comment]
https://www.wowhead.com/spell=193440/demonwrath 

i think thats the correct one :D

**Comment by Spydoc** [comment]
Update:
After yesterday's fix the ability has started doing damage as intended but the range is abysmally huge. All targets that are roughly 70 yards around my minions get damaged and it should be only 10 yards.
