### ISSUE TITLE
[Core] - Paladin - Consecration dmg is insane

### ISSUE THREAD

**Issue by justfortest098** [GuabinaCore/WoWKoi#604]
**Links:**
https://www.wowhead.com/spell=26573/consecration
from WoWHead or our Armory
https://www.wowhead.com/spell=26573/consecration
**What is happening:**
The dmg is insane, we have paladin soloing dungeon bc of that.
maybe something wrong with the formula...

**What should happen:**

**Comment by Arkanheal** [comment]
From what I've seen as a 30-ish protection paladin, is that consecration deals between 2 and all the ticks in a single tick depending on the level of the NPC you're attacking. TBC though

**Comment by GhostySimon** [comment]
I've also noticed that Paladin's consecration instead of of doing X amount of damage during 9 seconds it does X amount of damage with every tick which is insane, to be honest :]
