### ISSUE TITLE
Mob - Phantasmal Seeker

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#608]
**Links:**
https://www.wowhead.com/npc=16323/phantasmal-seeker

**What is happening:**
Mob has elite hp/defence values and is invulnerable.

**What should happen:**
Mob isn't invulnerable and has normal hp/defence values.

note: scales from level 13-61

**Comment by Cefiro-Caecias** [comment]
Fixed, Available in the next update.
