### ISSUE TITLE
26297/the-dawning-of-a-new-day

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#61]
https://www.wowhead.com/quest=26297/the-dawning-of-a-new-day The event doesnt start.
falta el npc que esta sobre la carreta

**Comment by Cefiro-Caecias** [comment]
Fixed.

**Comment by LKArthas** [comment]
@johamanu esa misión inicia cuando vas a entrar a las minas de la muerte, sol acércate a donde te marca el Mapa y ahí lo activará
