### ISSUE TITLE
[Pet] Certain pets' abilities being unusable on lvl 1

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#610]
**Links:**
https://classic.wowhead.com/item=10360/black-kingsnake
https://www.wowhead.com/npc=14421/brown-prairie-dog
https://www.wowhead.com/item=29953/golden-dragonhawk-hatchling
https://www.wowhead.com/npc=65314/jade-crane-chick
https://www.wowhead.com/npc=63097/shore-crawler
https://www.wowhead.com/npc=7395/undercity-cockroach

**What is happening:**
These pets can't use their lvl 1 abilities, so they can't fight other battle pets. When I try to use the abilities, the error given says that the pets should be "level 1". I am not sure if all abilities are like this, or if only the abilities acquired at lvl 1 are like this, or if this dissapears after leveling over 1.

**What should happen:**
These pets shouuld be able to use their abilities that are unlocked on lvl 1 when you catch the pet.

**Comment by eighthourblink** [comment]
Adding - Something else I have seen is that pets that I have purchased from Pet Battle Trainers (Goldshire), these pets are also showing the same thing while in battle. Cant use any abilities although being level 1. 

Something else I noticed was that these pets did not go into my backpack after purchasing. They were automatically added to the journal. But the ones I have received from leveling / mailbox, look perfectly and able to do battles / capturing.

**Comment by Exlyss** [comment]
Adding - Some pets are unable to use the secondary skill they should learn at level 2, the only way to solve this for now seems to be relogging.

![WoWScrnShot_043020_183242](https://user-images.githubusercontent.com/64436148/80735878-9f355980-8b11-11ea-8ee7-92412f7703bf.jpg)
