### ISSUE TITLE
Quest Bug

### ISSUE THREAD

**Issue by lillemand13** [GuabinaCore/WoWKoi#614]
**Links:**
https://www.wowhead.com/quest=24939/run-out-the-guns
from WoWHead or our Armory

**What is happening:**
Its not all boats that counts in to the quest 

**What should happen:**
All row boats you shoot should count as 1 in the quest

**Comment by Cefiro-Caecias** [comment]
The Desolace, Azshara and Thousand Needles maps are still under reconstruction, at 50%.
