### ISSUE TITLE
Durotar mobs not scaling

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#617]
**Links:**
https://www.wowhead.com/npc=39385/screamslash
https://www.wowhead.com/npc=39337/wayward-plainstrider
https://www.wowhead.com/npc=3111/razormane-quilboar
https://www.wowhead.com/npc=3112/razormane-scout
https://www.wowhead.com/npc=3195/burning-blade-thug
https://www.wowhead.com/npc=3196/burning-blade-neophyte
from WoWHead or our Armory

**What is happening:**
Mobs not scaling up to 20.

**What should happen:**
Should scale up to 20.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
