### ISSUE TITLE
[Core] - Holy paladin - Judgment

### ISSUE THREAD

**Issue by fjef21** [GuabinaCore/WoWKoi#622]
**Links:** 
https://www.wowhead.com/spell=231644/judgment

from WoWHead or our Armory

**What is happening:**
As holy paladin, judgment does **not** increase dmg taken from crusader strike and holy shock.

**What should happen:**
As holy paladin, Judgment should increase the target dmg taken from your Crusader strike and Holy shock by 30% for 6 sec.

**Comment by Arkanheal** [comment]
Linked to #576 and #32

**Comment by biosintesis** [comment]
It work ok
