### ISSUE TITLE
[Core] - Holy Paladin - Crusader´s Might

### ISSUE THREAD

**Issue by fjef21** [GuabinaCore/WoWKoi#623]
**Links:**
https://www.wowhead.com/spell=196926/crusaders-might

from WoWHead or our Armory

**What is happening:**
Crusader Strike does not reduce Holy Shock and Light of Dawn cooldown.

**What should happen:**
Crusader Strike should reduce Holy Shock and Light of Dawn cooldown by 1.5 sec if the Crusader´s Might talent is taken.

**Comment by biosintesis** [comment]
The spell is working ok.
