### ISSUE TITLE
[Core] - Paladin - Consecration

### ISSUE THREAD

**Issue by fjef21** [GuabinaCore/WoWKoi#626]
**Links:**
https://www.wowhead.com/spell=81297/consecration

from WoWHead or our Armory

**What is happening:**
Consecration damage area is not staying in the place, where casted, but moving with the Paladin.

**What should happen:**
Consecration should only do damage in casted area and shouldn´t follow the Paladin.

**Comment by Serithul** [comment]
Linked to https://github.com/GuabinaCore/WoWKoi/issues/604

**Comment by ShikoSCS** [comment]
Fixed, please test it
