### ISSUE TITLE
[Core] - Holy Paladin - Beacon of Light

### ISSUE THREAD

**Issue by fjef21** [GuabinaCore/WoWKoi#627]
**Links:**
https://www.wowhead.com/spell=53563/beacon-of-light
from WoWHead or our Armory

**What is happening:**

The target with Beacon of Light doesn´t get healed when other party or raid member is healed by the Paladin.

**What should happen:**
When you heal other party of raid members , the target with Beacon of Light should get healed up to 40% of the amount healed.

**Comment by GuabinaCore** [comment]
Fixed
