### ISSUE TITLE
Las Minas de la Muerte y la masmorra.

### ISSUE THREAD

**Issue by carlosyuniro** [GuabinaCore/WoWKoi#633]
https://es.classic.wowhead.com/the-deadmines

Los Npc y los jefes tienen demasiado daños de 5 golpes bajan a los tanque esta es como la octava ves que voy y no se puede pasar del comienzo.

https://es.classic.wowhead.com/the-stockade 

cuando pasas un poco mas de la entrada te explota la pc literal, me toca reiniciarla

**Comment by LKArthas** [comment]
Fixed avaible on next update
