### ISSUE TITLE
[Core] - Arqueología Profesional 

### ISSUE THREAD

**Issue by carlosyuniro** [GuabinaCore/WoWKoi#646]
https://es.wowhead.com/scarlet-monastery

No te muestra las investigaciones ya hechas en el libro, esta bug esa sección.

**Comment by carlosyuniro** [comment]
https://es.wowhead.com/archaeology#spells

**Comment by Arkanheal** [comment]
Translation: "It doesn't show you the research already done in the book, this bug that section."
This bug actually breaks the profession completely as you can't "build" any artifact.

**Comment by Thordekk** [comment]
El sistema fue actualizado en breve se corregirá acorde a las nuevas funciones
