### ISSUE TITLE
[Core] - RDF Deserter Debuff

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#649]
**Links:**

If u kill the last boss and leave it's not suppose to have that debuff

**What is happening:**
Join RDF (was dead) and the party pop up. Once reach the corps I revive and enter the dung (RFD)
We kill the last boss...turn the quests etc and I leave 
The result is 30 min deserter
https://imgur.com/nbQzh7c

**What should happen:**

**Comment by Serithul** [comment]
https://www.wowhead.com/spell=71041/dungeon-deserter
