### ISSUE TITLE
[Arthas] - Skinning [MISC] SKill no High enough

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#650]
**Links:**
https://classic.wowhead.com/skinning
**What is happening:**
Same mob level one can be skinned, the other cant.
https://streamable.com/pf3w8m

**What should happen:**

**Comment by Maczuga** [comment]
To improve on that:
You can now skin any type of mob without a required skill level. The amount of scraps you get is determined by your skill level.

Right now - mobs seems to inherit their required skinning level from base level of NPC - so for example - I was at lvl 29, same as the mob AFTER scaling, but it base level prior to the Legion scaling was 16. My skinning was way lower than it should be for that 16 lvl mob, and was failing.

It should be always able to skin that beast - even the client shows the orange "Skinable" text, not the red one. 

Also from wowhead:

If the mob is considered insignificant enough (or if you're skinning mobs that are above your "appropriate" Skinning level), they **might** instead drops leather scraps that can be combined into full leather pieces.

I couldn't find any "scrap" items except the one for Light Leather. Also lvl 20-60 do not have any scrap items in their skinning loot.

https://www.wowhead.com/skinning
