### ISSUE TITLE
[Core] - Protection Paladin - Grand Crusader

### ISSUE THREAD

**Issue by Krulnir** [GuabinaCore/WoWKoi#652]
Grand Crusader: https://www.wowhead.com/spell=85043/grand-crusader
When you avoid a melee attack or use Hammer of the Righteous, you have a 15% chance to reset the remaining cooldown on Avenger's Shield.
This passive is not working at all.

**Comment by Serithul** [comment]
How are you sure it's not working ? it's a 15% chance to happen, so you might have just been unlucky

**Comment by Krulnir** [comment]
Because I'm level 60 now and it never once triggered, ever, I even took the
talent to boost it's proc chance and still, nothing.

**Comment by GuabinaCore** [comment]
Fixed please check after next update
