### ISSUE TITLE
[Arthas] - Quest Lost in the Floods

### ISSUE THREAD

**Issue by antonioyu0505** [GuabinaCore/WoWKoi#654]
**Links:**

https://www.wowhead.com/quest=25187/lost-in-the-floods
https://www.wowhead.com/item=52514/thonks-spyglass
**What is happening:**
After using Thonk's Spyglass and seeing the flooded hut, you automatically teleport over there if you end the cinematic earlier.

**What should happen:**
You should not teleport over there even after ending the cinematic earlier.

**Comment by LKArthas** [comment]
Fixed avaible on next update
