### ISSUE TITLE
[Core] - Classic Dungeonmaster Achievement

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#655]
**Links:**
https://www.wowhead.com/achievement=1283/classic-dungeonmaster
https://imgur.com/a/ShXWQoT
from WoWHead or our Armory

**What is happening:**
No progress shown even if you have the associated achievements.

**What should happen:**
Should show you the progress.

**Comment by Arkanheal** [comment]
It does that for most (if not all) achievements (mounts, pet, Tmog collections as well). And squirrels one as well.

**Comment by Thordekk** [comment]
Achievemt was updated to show progress try it now
