### ISSUE TITLE
[Core] - Tame Beast problem 

### ISSUE THREAD

**Issue by Watermaniac** [GuabinaCore/WoWKoi#656]
Links:
https://classic.wowhead.com/spell=1515/tame-beast
What is happening:
Cant tame any animal but the ones from starting zone, i think its because of mobs level scaling, even that im 1or 2 lvls higher then animal,it says "target is to high level".

What should happen:
Should be able to tame pets same level as me or below.

**Comment by asdregular** [comment]
The bug still persists.
