### ISSUE TITLE
[Core] - Bestial Wrath rank 2

### ISSUE THREAD

**Issue by L1n0x** [GuabinaCore/WoWKoi#658]
https://www.wowhead.com/spell=207033/bestial-wrath

**What is happening:**
Bestial Wrath rank 2 is only working when you use Dire Beasts

**What should happen:**
Bestial Wrath's remaining cooldown is reduced by 12 sec each time you use Dire Frenzy or Dire Beasts

**Comment by Anterrka** [comment]
Dire Beast also reduces the cooldown of Bestial Wrath even when you're below lv 54 for rank 2
