### ISSUE TITLE
[Arthas] - Quest Red Snapper - Very Tasty!

### ISSUE THREAD

**Issue by JadedNate** [GuabinaCore/WoWKoi#659]
https://www.wowhead.com/quest=9452/red-snapper-very-tasty

**What is happening:**
School of Red Snapper does not always give the player the quest item.

**What should happen:**
Red Snapper should have 100% drop rate.

**Comment by LKArthas** [comment]
As intendeed School of Red Snapper does not always give the player the quest item. some time spawns a murloc that have the quest item confirmed on retail
Closing
