### ISSUE TITLE
[Arthas] - Death Knight Starting Area Quest: The Gift That Keeps On Giving, Id: 12698

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#660]
**Links:**
https://www.wowhead.com/quest=12698/the-gift-that-keeps-on-giving
https://www.wowhead.com/item=39253/gift-of-the-harvester
from WoWHead or our Armory

**What is happening:**
Quest items has to be thrown on top of the miner in order for the transformation to occur.

**What should happen:**
Quest item has a set range around it which should trigger the transformation if a miner is inside it.

**Comment by black0ut23** [comment]
With the new core, the transformation doesn't even trigger regardless of where you place the item
