### ISSUE TITLE
[Quest] Rest and Relaxation

### ISSUE THREAD

**Issue by Randysandy929** [GuabinaCore/WoWKoi#662]
**Links:**
https://classic.wowhead.com/quest=2158/rest-and-relaxation
from WoWHead or our Armory

**What is happening:**
Falkhaan Isenstrider offers two iterations of Rest and Relaxation.

**What should happen:**
Falkhaan Isenstrider should off one iteration of Rest and Relaxation.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
