### ISSUE TITLE
[NPC] Fleeting Plainstrider [MISC] Faction

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#664]
**Links:**

https://classic.wowhead.com/npc=3246/fleeting-plainstrider
https://wow.gamepedia.com/Fleeting_Plainstrider
**What is happening:**
It's aggressive (visual)

**What should happen:**
Suppose to be neutral

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
