### ISSUE TITLE
Pandaren and Guild Invites.

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#667]
**Links:**

from WoWHead or our Armory

**What is happening:**
Pandaren players can be invited in a guild before choosing a Faction.

**What should happen:**
First a faction must be chosen then they should be able to get invited to a guild in that faction.

**Comment by zaneirth** [comment]
I too have just gotten a bug where before choosing a faction as a Pandaren i was able to accept a guild invite, also once i decided to choose my faction ( I chose Alliance ) none of the guild abilities unlocked, nor was I able to access the RDF feature.
