### ISSUE TITLE
Razormaw Matriarch not scaled up correctly

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#67]
**Links:**
https://classic.wowhead.com/npc=1140/razormaw-matriarch

**What is happening:**
The Razormaw Matriarch rare mob is not scaling up to the player's level, being only on level 25.

**What should happen:**
The Razormaw Matriarch should scale up with the player's level.

**Comment by Cefiro-Caecias** [comment]
Fixed.
