### ISSUE TITLE
TBC items in a Winterspring chest

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#670]
**What is happening:**

You can loot TBC gear from a Winterspring chest (coords: 50, 69. in a cave)

FYI, I got Raine's Choker of Combustion (ItemID: 37758)

**What should happen:**
You shouldn't be able to loot TBC items from the chest.

**Comment by Cefiro-Caecias** [comment]
Yes, there are TBC chests on Classic maps. It is not a bug.
