### ISSUE TITLE
Pandaren Starting Area Quests Auto-Accepted.

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#676]
**Links:**
https://www.wowhead.com/quest=30027/the-lesson-of-the-iron-bough
https://www.wowhead.com/quest=30038/the-lesson-of-the-iron-bough
https://www.wowhead.com/quest=30036/the-lesson-of-the-iron-bough
https://www.wowhead.com/quest=30034/the-lesson-of-the-iron-bough
https://www.wowhead.com/quest=30033/the-lesson-of-the-iron-bough
https://www.wowhead.com/quest=30035/the-lesson-of-the-iron-bough
https://www.wowhead.com/quest=30037/the-lesson-of-the-iron-bough
https://www.wowhead.com/quest=29406/the-lesson-of-the-sandy-fist
https://www.wowhead.com/quest=29524/the-lesson-of-stifled-pride
https://www.wowhead.com/quest=29408/the-lesson-of-the-burning-scroll
https://www.wowhead.com/quest=29409/the-disciples-challenge
https://www.wowhead.com/quest=29410/aysa-of-the-tushui
https://www.wowhead.com/quest=29419/the-missing-driver
https://www.wowhead.com/quest=29424/items-of-utmost-importance
from WoWHead or our Armory

**What is happening:**
They get accepted the moment you press the quest dialogue on the npc not giving you the time to read the lore or the objectives before accepting.

**What should happen:**
They should be accepted only when the player presses accept.

**Comment by Cefiro-Caecias** [comment]
In fact, it is not. In general, starting zone quests are self-accepting, as you can see from the same wowhead link:

https://www.wowhead.com/quest=30027/the-lesson-of-the-iron-bough#see-also
