### ISSUE TITLE
[Core] - Demonic Empowerment

### ISSUE THREAD

**Issue by Enigmaticresolve** [GuabinaCore/WoWKoi#684]
**Links:**
https://www.wowhead.com/spell=193396/demonic-empowerment#changelog
from WoWHead or our Armory

**What is happening:**
When a pet has missing health from damage when Demonic Empowerment is cast the current health of the pet decreases.

**What should happen:**
Current health should be unaffected.

**Comment by Serithul** [comment]
Included in https://github.com/GuabinaCore/WoWKoi/issues/535
