### ISSUE TITLE
[Core] - Shaman - Enhancement - Lava Lash

### ISSUE THREAD

**Issue by antonioyu0505** [GuabinaCore/WoWKoi#686]
**Links:**

https://www.wowhead.com/spell=60103/lava-lash

**What is happening:**
Using this spell with multiple enemies seems to trigger aggro on them, even if they're not your target.

**What should happen:**
This spell should not trigger aggro on other enemies because it is a single target ability.

**Comment by biosintesis** [comment]
Can you explain better??? Please...

**Comment by antonioyu0505** [comment]
If you cast lava lash you will draw aggro from every npc around your target, even if they are yellow instead of red. You can test it yourself by attacking a yellow mob surrounded by other yellow mobs with Lava Lash, you will see that every enemy attacks you.

**Comment by Maczuga** [comment]
I can confirm, hitting any target with Lava Lash causes all attackable NPCs withing meele radius to be in combat with you. 

Might be worth checking if there is some dead code from MoP or something that tries to apply Flame Shock onto near targets with Lava Lash.
