### ISSUE TITLE
[Arthas] - Quest A Vision of the Past

### ISSUE THREAD

**Issue by Randysandy929** [GuabinaCore/WoWKoi#687]
**Links:**
https://www.wowhead.com/quest=26320/a-vision-of-the-past
from WoWHead or our Armory

**What is happening:**
Essence gets teleported above the bridge at the entrance into the Ironclad Cove. I can see the Alliance NPCs fighting VanCleef and then eventually the Vanessa VanCleef small girl comes out. The quest doesn't complete and you cannot leave the spirit. I never pressed any buttons or did anything to move.

**What should happen:**
The quest should be completed and the vision should end, sending your character back to the beginning of the dungeon.

**Comment by LostAgeMagic** [comment]
Just tried to complete this as well, its almost as if Vancleef dies to slowly for you to be in range of the dialogue, but also you get teleported to the entrance of the room and are stuck as spirit, with no quest credit.
If you relog you end up spawning as your actual character in the shipyard area.

**Comment by lanccerus** [comment]
Just tested this.

First time, the bug happened as described by LostAgeMagic.
Then I logged out and back in and was killed by NPCs inside Deadmines.

When I did my ghost run back to the dungeon, I activated the quest item again and the quest worked correctly. I got credit at the end and was teleported back to the entrance of the dungeon.

**Comment by MeatyBoii** [comment]
I've had the exact same issue. VanCleef dies too slowly.

**Comment by thoomasdsf** [comment]
this quest randomly work, in the middle of the fight vancleef spawns more mobs. if any of these mobs hit you, get teleported to the entrance of the room

**Comment by Lamvince** [comment]
The quest works fine until the end of the vision.

What is happening: After the vision, you change from spirit to your actual character and fall where you are on the ground where you meet an unfortunate end at the hands of Admiral Ripsnarl.

What should happen: After the vision, character teleports to the start of the dungeon.

**Comment by dan2142** [comment]
+1 can confirm
