### ISSUE TITLE
[Saitama] - Spell Warrior - Protection 2 (6572)

### ISSUE THREAD

**Issue by johamanu** [GuabinaCore/WoWKoi#69]
Warrior - Protection - Spell and Buff
When the Revenge buff proc by either dodging or parrying an attack, the buff gets removed if you use ANY spell (not only Revenge) which render it useless.
How it should work : The buff should only get removed when using Revenge or when the 5 seconds timer is over. You should be able to use any other spells you want during the duration of the buff and then consume it by using revenge (if the timer isn't over yet)

**Comment by adrianrp1988** [comment]
Fixed
