### ISSUE TITLE
Disenchanting interacting in a weird way

### ISSUE THREAD

**Issue by Evilwowshaman** [GuabinaCore/WoWKoi#690]
I'm disenchanting Double-Stitched Woolen Shoulders (first shoulderpads you can craft through tailoring) and it's rewarding me with Overlord's Vambraces (lvl 43 bracers)

![Screenshot_1](https://user-images.githubusercontent.com/62144962/79315281-625f4500-7f0b-11ea-98b2-0794fe02bd84.png)

Definitely should only give you dust for disenchanting.

**Comment by Krulnir** [comment]
I've experienced the same problem, though rarely, when disenchanting some green drops, I receive two sets of lvl 43 bracers just like these.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
