### ISSUE TITLE
[Core] - Warlock Haunt ability

### ISSUE THREAD

**Issue by Evilwowshaman** [GuabinaCore/WoWKoi#691]
Every now and then the level 15 Affliction talent "Haunt" doesn't reset its cd after the mob dies with it.

It should reset if the debuff is on the mob and it dies with it.

**Comment by Evilwowshaman** [comment]
Also Soul Leech passive is supposed to be learned at level 34, yet I get the barrier from level 10 and forward.

**Comment by biosintesis** [comment]
Are you sure?? 
Please try again because in my server works.
