### ISSUE TITLE
Yet another chest

### ISSUE THREAD

**Issue by Evilwowshaman** [GuabinaCore/WoWKoi#692]
Found another one of these bad boys with like 15 rare items in them, including a few other interesting items:

https://www.wowhead.com/item=37810/blade-binding-bulwark
https://www.wowhead.com/item=66976/spaulders-of-the-savage-beast
https://www.wowhead.com/item=37760/cracklefire-wristguards
https://www.wowhead.com/item=37778/girdle-of-unerring-flight

The chest was located here, chest name as well in the same picture:

![kuva](https://user-images.githubusercontent.com/62144962/79320951-46f83800-7f13-11ea-8577-dbe5201a7bbb.png)

Don't think I even have to write anything in this section?

**Comment by Cefiro-Caecias** [comment]
Yes, it is correct, there are chests with item drops higher than the current level, since the zones are designed for characters of all levels to go through them. Even if you search wowhead, you will see those chests are in low level zones.
