### ISSUE TITLE
[Core] - Mob - Plagued Snapper

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#694]
**Links:**
https://www.wowhead.com/npc=33711/plagued-snapper#drops
https://www.wowhead.com/item=6541/willow-gloves

**What is happening:**
Mob doesn't scale + has incorrect loot table.

**What should happen:**
Mob Scales + has 13% chance to drop Willow Gloves

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
