### ISSUE TITLE
[Quest] Silithissues [NPC] SIlithid Swarmer

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#697]
**Links:**
https://www.wowhead.com/quest=24569/siegebreaker
https://classic.wowhead.com/npc=3252/silithid-swarmer

**What is happening:**
The swarmer's don't scale

**What should happen:**
They suppose to scale till 60

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
