### ISSUE TITLE
[Core] Mob - Dr. Whitherlimb

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#698]
**Links:**
https://www.wowhead.com/npc=22062/dr-whitherlimb#drops
https://www.wowhead.com/spell=38864/withering-poison
https://www.wowhead.com/spell=38871/monstrous-elixir
https://www.wowhead.com/item=31270/banshee-rod
https://www.wowhead.com/item=31269/ghoul-hammer
https://www.wowhead.com/item=31268/abomination-cleaver

**What is happening:**
1. Mob has wrong loot table.
2. Mob doesn't attack you when you silence it.
3. Mob doesn't cast Withering Poison or Monstrous Elixir.

**What should happen:**
1. Mob attacks you when you silence it
2. Mob casts Withering Poison and Monstrous Elixir.
3. 36% chance to drop Banshee Rod, 35% to drop Ghoul Hammer and 29% chance to drop Abomination Cleaver.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
