### ISSUE TITLE
[Core] Mob - Knucklerot

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#699]
**Links:**
https://www.wowhead.com/npc=16246/knucklerot#drops
https://www.wowhead.com/spell=8014/tetanus

**What is happening:**
1. Mob doesn't cast Tetanus.
2. Mob doesn't attack when you silence it.
3. Mob doesn't patrol to Goldenmist Village.

**What should happen:**
1. Mob casts Tetanus
2. Mob attacks you when you silence it.
3. Mob patrols to Goldenmist Village.

**Comment by Cefiro-Caecias** [comment]
Fixed (except patrol). Available in the next update.
