### ISSUE TITLE
[Core] Mob - Luzran

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#700]
**Links:**
https://www.wowhead.com/npc=16245/luzran#abilities

**What is happening:**

1. Mob doesn't cast Cleave/Knock Away/sunder armor.
3. Mob doesn't patrol through the dead scar.

**What should happen:**

1. Mob casts Cleave/Knock Away/sunder armor.
3. Mob patrols through the dead scar.

**Comment by Cefiro-Caecias** [comment]
Fixed (except patrol). Available in the next update.
