### ISSUE TITLE
Mob level scaling

### ISSUE THREAD

**Issue by Evilwowshaman** [GuabinaCore/WoWKoi#701]
The Stags at Azshara are a bit too low leveled.

![kuva](https://user-images.githubusercontent.com/62144962/79330722-b1fd3b00-7f22-11ea-91af-c59bc26451fc.png)

As you can see, I'm lvl 22 and they appear as lvl 9. They should be around the same level as I am.

**What should happen:**

**Comment by Evilwowshaman** [comment]
Not a single mobs scales up to level except for the shredders at the start of the questline

**Comment by NightwindOI** [comment]
Azshara is at 50% fixed, that explains the scale problem.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
