### ISSUE TITLE
[Quest] The Adept's Path

### ISSUE THREAD

**Issue by Krulnir** [GuabinaCore/WoWKoi#703]
Quest: The Adept's Path - https://www.wowhead.com/quest=27434/the-adepts-path
Quest Mob: Commander Springvale - https://www.wowhead.com/npc=4278/commander-springvale
Quest Item: Commander's Holy Symbol - https://www.wowhead.com/item=60879/commanders-holy-symbol

Commander Springvale is failing to drop the Commander's Holy Symbol.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
