### ISSUE TITLE
Azshara  "Hand-me-downs" quest

### ISSUE THREAD

**Issue by Evilwowshaman** [GuabinaCore/WoWKoi#705]
In the quest you're supposed to run in to the mine field to pick up corpses and loot stuff from them. You can keep on clicking the body in order to get like 8 of them at once.

One body should reward only 1 quest item.

**Comment by Serithul** [comment]
Azshara as well as thousand needles and desolace are not fully scripted yet.

**Comment by Cefiro-Caecias** [comment]
Azshara, Desolace, and Thousand Needles maps are 50% complete. Patience ^^
