### ISSUE TITLE
[NPC] Spiny Rock Crab [MISC] Visual

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#706]
**Links:**
https://www.wowhead.com/npc=44390/spiny-rock-crab

**What is happening:**

It looks aggressive but it's not
https://imgur.com/a/hA1AcjY

**What should happen:**
Suppose to be neutral

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
