### ISSUE TITLE
Quest - Captives at Deatholme

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#707]
**Links:**
https://www.wowhead.com/quest=9164/captives-at-deatholme
https://www.wowhead.com/npc=16209/ranger-vedoran#objective-of

**What is happening:**
Ranger Vedoran appears twice in the quest log. He has an additional spawn in eastern Deatholme that's not supposed to be there.

**What should happen:**
Ranger Vedoran appears only once in the quest log. He has a spawn only in southern Deatholme. coords: 32, 89

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
