### ISSUE TITLE
Disenchant Bug

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#708]
**Links:**
https://www.wowhead.com/spell=160201/disenchant
https://www.wowhead.com/item=14375/sanguine-cuffs
https://www.wowhead.com/item=10202/overlords-vambraces

**What is happening:**
Disenchanting Sanguine Cuffs gives you Overlord's Vambraces.

**What should happen:**
Disenchanting should give you normal items.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
