### ISSUE TITLE
Tabard vendor (?)

### ISSUE THREAD

**Issue by Evilwowshaman** [GuabinaCore/WoWKoi#709]
I shouldn't be able to buy these things off the Tabard Vendor with no reputation gain on the actual factions right? 
![kuva](https://user-images.githubusercontent.com/62144962/79362208-f8688f00-7f4e-11ea-94f6-e432f8e0c2ba.png)

![kuva](https://user-images.githubusercontent.com/62144962/79362225-fef70680-7f4e-11ea-88d8-6f3a2a839112.png)

Garyl is selling dope tmogs, but I don't think I should be able to get them.

**Comment by Evilwowshaman** [comment]
![kuva](https://user-images.githubusercontent.com/62144962/79362395-36fe4980-7f4f-11ea-9868-9da28510d915.png)
![kuva](https://user-images.githubusercontent.com/62144962/79362417-3e255780-7f4f-11ea-9455-6cd4016a32fb.png)

**Comment by Evilwowshaman** [comment]
![kuva](https://user-images.githubusercontent.com/62144962/79362438-44b3cf00-7f4f-11ea-864d-5dacd522029f.png)

**Comment by DeltaVortex** [comment]
here's what he sells: https://www.wowhead.com/npc=5188/garyl#sells
edit: the big gold items he isn't supposed to sell

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
