### ISSUE TITLE
[Arthas] - Rested Zone Silverpine

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#710]
**Links:**
https://www.wowhead.com/npc=45496/commander-hickley

**What is happening:**
Inn where npc commander hickley is located isn't considered a rested zone.

**What should happen:**
Should be considered a rested zone.

**Comment by Cefiro-Caecias** [comment]
Arthas, no tengo idea cómo hacer para que esa zona sea considerada zona de descanso. Te lo paso a ti.
