### ISSUE TITLE
[Core] - Guild ranks can't be moved up or down

### ISSUE THREAD

**Issue by Evilwowshaman** [GuabinaCore/WoWKoi#711]
You can make new ranks for the guild but eventually the arows turn gray and nothing happens:
![kuva](https://user-images.githubusercontent.com/62144962/79364296-d6244080-7f51-11ea-81de-bce3f84a5038.png)

The arrows should just move the ranks up or down, what ever you're up to.

**Comment by Serithul** [comment]
The guild module is not implemented yet in the server as we know for now
