### ISSUE TITLE
[NPC] Acidic Swamp Ooze/Bubbling Swamp Ooze [Faction]

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#712]
**Links:**

https://classic.wowhead.com/npc=4393/acidic-swamp-ooze
https://shadowlands.wowhead.com/npc=4394/bubbling-swamp-ooze

**What is happening:**
They look aggressive (red) but they are neutral.

**What should happen:**
Must be aggressive to everyone.

**Comment by Cefiro-Caecias** [comment]
There is no bug present. Those mobs are hostile to the player, but do not attack unless they attack first. Many mobs warn you in red that they are dangerous, but some are not hostile until they attack them first.
