### ISSUE TITLE
[Core] - Arqueología Bug 

### ISSUE THREAD

**Issue by carlosyuniro** [GuabinaCore/WoWKoi#717]
https://es.wowhead.com/archaeology
https://es.wowhead.com/item=69777/tambor-de-guerra-embrujado
from WoWHead or our Armory
Estaba aprendiendo Tambor de Guera Embrujado y lo cancele sin querer al moverme y me borro la "Tablilla del trol" las 3 que tenia y solo use 2 y se me borro el progreso que lo tenia lleno y no me dieron el item.

los artefactos completados no te muestra ninguno y ya tengo varios hechos 

**What should happen:**
![WoWScrnShot_041520_213053](https://user-images.githubusercontent.com/62365902/79402281-c280d600-7f61-11ea-8a1e-2be9b7b0781f.jpg)

![WoWScrnShot_041520_213053](https://user-images.githubusercontent.com/62365902/79402290-c90f4d80-7f61-11ea-8ae9-700ee688c4ae.jpg)

**Comment by Thordekk** [comment]
El sistema de Arqueología fue mejorado puede probar si el problema persiste
