### ISSUE TITLE
[Quest] Spirits of Stonemaul Hold [NPC] Stonemaul Spirit

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#718]
**Links:**

https://www.wowhead.com/quest=27410/spirits-of-stonemaul-hold
https://www.wowhead.com/npc=23786/stonemaul-spirit

**What is happening:**
Stonemaul Spirit's don't scale (stay at 40)

**What should happen:**
They suppose to scale till 60

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
