### ISSUE TITLE
[Quest] In Defense of Krom'gar Fortress [NPC] Gnomish Flying Machine

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#721]
**Links:**
https://www.wowhead.com/quest=26058/in-defense-of-kromgar-fortress
https://www.wowhead.com/npc=42016/gnomish-flying-machine

**What is happening:**
Flying Machine doesn't scale

**What should happen:**
Suppose to scale till 60

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
