### ISSUE TITLE
[NPC] Greater Duskbat [Visual]

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#724]
**Links:**

https://classic.wowhead.com/npc=1553/greater-duskbat

**What is happening:**
It looks aggressive but its neutral
Its too small model.

**What should happen:**
Must look neutral too and need scale the model.

**Comment by Serithul** [comment]
It is supposed to be small, check comments. https://www.wowhead.com/npc=1553/greater-duskbat#comments

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
