### ISSUE TITLE
[NPC] Duskbat [Visual]

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#725]
**Links:**

https://classic.wowhead.com/npc=1512/duskbat#comments

**What is happening:**
Too small model

**What should happen:**
Model need scale.

**Comment by Serithul** [comment]
It's actually supposed to be small, check the screenshots (middle one) https://www.wowhead.com/npc=1512/duskbat#screenshots

**Comment by NightwindOI** [comment]
Still think that u link is for battle pet pic.
https://youtu.be/ZkABHfBZhzM?t=287

**Comment by Serithul** [comment]
that's mangy duskbat (https://www.wowhead.com/npc=1513/mangy-duskbat) a different npc in the starting area of the undead, i actually pressed ur link and changed from classic to live and saw the screenshots.

**Comment by Serithul** [comment]
if u slow down the video you can see him killing a duskbat 1-2 seconds after the linked time and it is literally that small. 4:50 to be precise.

**Comment by NightwindOI** [comment]
maybe I have some problems with the eyes...All of them look smaller than suppose to be to me :D

**Comment by Cefiro-Caecias** [comment]
There is no bug present. You are viewing the comments and data of the new "Classic" version of the WoW. You must see the data related to BfA (even if we are in Legion):

https://www.wowhead.com/npc=1512/duskbat
