### ISSUE TITLE
[Core] - A Daughter's Embrace

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#727]
**Links:**

https://www.wowhead.com/quest=25046/a-daughters-embrace

**What is happening:**
If u pull the mobs outside the tower they become unmanageable and chase u to death. 

**What should happen:**
No matter if u pull them outside the tower or outside they must be killable.

**Comment by Cefiro-Caecias** [comment]
This general problem is being analyzed.
