### ISSUE TITLE
[Arthas] - Deathknight Starting Area

### ISSUE THREAD

**Issue by bonfim97** [GuabinaCore/WoWKoi#729]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=12687/into-the-realm-of-shadows

**What is happening:**
When reaching the quest AREA Death's Breach appears error "You're in the Wrong Zone".

**What should happen:**
After Reaching the designated Area and clicking the action, the quest should be completed.

**Comment by Serithul** [comment]
Duplicate of https://github.com/GuabinaCore/WoWKoi/issues/663
