### ISSUE TITLE
[Zone] Tirisfal Glades [NPC] Mob Scale

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#730]
**Links:**
[Vile Fin Puddlejumper](https://classic.wowhead.com/npc=1543/vile-fin-puddlejumper)
[Vile Fin Muckdweller](https://classic.wowhead.com/npc=1545/vile-fin-muckdweller)
[Vile Fin Murloc](https://classic.wowhead.com/npc=1541/vile-fin-murloc)
[Vile Fin Minor Oracle](https://classic.wowhead.com/npc=1544/vile-fin-minor-oracle)
[Decrepit Darkhound](https://classic.wowhead.com/npc=1547/decrepit-darkhound)
[Cursed  Darkhound](https://classic.wowhead.com/npc=1548/cursed-darkhound)
[Greater Duskbat](https://classic.wowhead.com/npc=1553/greater-duskbat)
[Ravaged Corpse](https://classic.wowhead.com/npc=1526/ravaged-corpse)
[Rotting Dead](https://classic.wowhead.com/npc=1525/rotting-dead)
[Worgen Infiltrator](https://www.wowhead.com/npc=38967/worgen-infiltrator)
[Vampiric Duskbat](https://classic.wowhead.com/npc=1554/vampiric-duskbat)
[Rot Hide Gnoll](https://classic.wowhead.com/npc=1674/rot-hide-gnoll)
[Rot Hide Mongrel](https://classic.wowhead.com/npc=1675/rot-hide-mongrel)
[Rot Hide Graverobber](https://classic.wowhead.com/npc=1941/rot-hide-graverobber)
[Maggot Eye](https://classic.wowhead.com/npc=1753/maggot-eye)
[Wailing Ancestor](https://classic.wowhead.com/npc=1534/wailing-ancestor)
[Rotting Ancestor](https://classic.wowhead.com/npc=1530/rotting-ancestor)
[Darkeye Bonecaster](https://classic.wowhead.com/npc=1522/darkeye-bonecaster)
[Cracked Skull Soldier](https://classic.wowhead.com/npc=1523/cracked-skull-soldier)
[Devlin Agamand](https://classic.wowhead.com/npc=1657/devlin-agamand)
[Nissa Agamand](https://classic.wowhead.com/npc=1655/nissa-agamand)
[Thurman Agamand](https://classic.wowhead.com/npc=1656/thurman-agamand)
[Shadow of Agamand](https://www.wowhead.com/npc=38981/shadow-of-agamand)
[Plagued Bruin](https://www.wowhead.com/npc=39049/plagued-bruin)
[Wandering Spirit](https://classic.wowhead.com/npc=1532/wandering-spirit)
[Bleeding Horror](https://classic.wowhead.com/npc=1529/bleeding-horror)
[Vicious Night Web Spider](https://classic.wowhead.com/npc=1555/vicious-night-web-spider)

**What is happening:**

All the mobs from an above missing scale.

**What should happen:**
Must scale till 20

**Comment by Cefiro-Caecias** [comment]
I hate you :P
Fixed. Available in the next update ;)
