### ISSUE TITLE
[Core] - Missing Talent Abilities/Spells

### ISSUE THREAD

**Issue by zeagur** [GuabinaCore/WoWKoi#732]
**Links:**

n/a

**What is happening:**
Warrior talent spells like `stormbolt`/`shockwave` after learned, if change `specialization` e.g. `protection` -> `fury` then `fury` -> `protection`. that spell will be automatically unlearn and gone from spellbook unless try to change talent to the other one then change back.
![Untitled](https://user-images.githubusercontent.com/43737901/79475974-9f722700-8032-11ea-9359-ab13a56d426f.png)

**What should happen:**
talent spell that are selected by player in that specialization should not be automatically unlearn after re-switch specailization.

**Comment by Clangeddin** [comment]
I can confirm this happens to me as well, the spells are unlearned also whenever I level up or relog the character.
