### ISSUE TITLE
[Core] - Monk - Chi Wave

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#734]
**Links:**
https://www.wowhead.com/spell=115098/chi-wave
from WoWHead or our Armory

**What is happening:**
Activated it without a target and it healed me twice.

![image](https://user-images.githubusercontent.com/62258982/79479681-cec66b00-8015-11ea-95b1-ca3f316e765a.png)

**What should happen:**
Should have only healed me once since there is no other target, hostile or friendly, to bounce around.

**Comment by Thordekk** [comment]
Duplicated
