### ISSUE TITLE
[Saitama] - Spell Marksmanship Hunter - Lone Wolf and other talents

### ISSUE THREAD

**Issue by Filqkus** [GuabinaCore/WoWKoi#74]
https://www.wowhead.com/spell=155228/lone-wolf#changelog - See 7.0.1 Version of the spell!
 
Upon specing into Lone Wolf your current pet is not dispawned in some situations. Which allows for effectively picking 2 talents from that row as you can go to a city. Pick a talent different than Lone Wolf , summon your pet and Pick Lone Wolf effectively making you have 18% dmg buff and a pet.

The talent should despawn current pet as soon as it is picked! Also it should give an 18% dmg buff but disable the usage of Call Pet!

**Comment by login6710** [comment]
Fixed
https://github.com/GuabinaCore/TYCE-Group/commit/526c2905460d2d9efdeeb5ac99fc6852c112648d
