### ISSUE TITLE
[Arthas] - Quest Seek and Destroy

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#744]
**Links:**

https://www.wowhead.com/quest=26009/seek-and-destroy

**What is happening:**
His just chilling there.

**What should happen:**
https://www.youtube.com/watch?v=O2fgPVpwVFU

**Comment by GhostySimon** [comment]
What Nightwind meant is that the the mob that you have to kill on this quest:

https://www.wowhead.com/npc=45219/caretaker-smithers

Doesn't go down thus you are unable to loot it for q item.

**Comment by LKArthas** [comment]
Fixed avaible on next update
