### ISSUE TITLE
[Arthas] - Cancelling a cinematic

### ISSUE THREAD

**Issue by Maczuga** [GuabinaCore/WoWKoi#749]
**Links:**

During quest: https://www.wowhead.com/quest=25187/lost-in-the-floods

**What is happening:**

When you cancel a 'cinematic' (the camera move sequence for some quests) - to got teleported to the place you cancelled the cinematic.

**What should happen:**

After cinematic cancel you should remain where it started - unless cinematic requires a teleport to the endpoint, but never should leave you in the middle of the desert :)

**Comment by LKArthas** [comment]
Fixed avaible on next update
