### ISSUE TITLE
Quest -Kum'isha's Endeavors

### ISSUE THREAD

**Issue by zodIIac** [GuabinaCore/WoWKoi#75]
**Links:**

https://www.wowhead.com/quest=25772/kumishas-endeavors

**What is happening:**
Upon accepting the quest, the provided item does not appear in the bag and the quest can't be turned in.
However, the chat log says the player recieved the item.

**What should happen:**
Player should receive the item correctly.

**Comment by LKArthas** [comment]
Fixed
