### ISSUE TITLE
[Core] - Arcane Missiles consumes the wrong charges and breaks Arcane Charge

### ISSUE THREAD

**Issue by stoneymahoney42** [GuabinaCore/WoWKoi#753]
**Links:**

https://www.wowhead.com/spell=150741/arcane-missiles

**What is happening:**

When Arcane Missiles stops channeling, all available charges on the spell are consumed (not Arcane Charges, they are seperate) and the Arcane Charges mechanic is broken - the number of Arcane Charges available does not visibly change but all spells consider that number to be zero, and the cap on the number of charges you can generate is cut down until you cast a spell that consumes all Arcane Charges (eg: Arcane Barrage) and the counter is correctly reset.

**What should happen:**

A Single charge of Arcane Missiles should be consumed when channeling starts. 1x Arcane Charge should be generated.

**Comment by Zinumwow** [comment]
I am with the same problem.
