### ISSUE TITLE
[CORE] Scaling between players

### ISSUE THREAD

**Issue by Maczuga** [GuabinaCore/WoWKoi#755]
**Links:**

---

**What is happening:**

Was in dungeon with higher level players (RDF), I was lvl 20, tank was lvl 37, I could barely heal him because I was healing him for ~150 with Healing Surge, he was 4,4k HP.

**What should happen:**

Scaling should be applied on % base. Target should be healed for the same % of HP I'd heal the player on the same level as mine.

**Comment by Serithul** [comment]
Already reported. Duplicate of https://github.com/GuabinaCore/WoWKoi/issues/463

**Comment by Maczuga** [comment]
Ok, closing then.
