### ISSUE TITLE
[Arthas] - The Stockades crashes client

### ISSUE THREAD

**Issue by Randysandy929** [GuabinaCore/WoWKoi#757]
**Links:**

from WoWHead or our Armory

**What is happening:**
Walking past the second sent of rooms in Stockades crashes the client.

**What should happen:**
No crash of client.

**Comment by Serithul** [comment]
Duplicate of https://github.com/GuabinaCore/WoWKoi/issues/620 which is a duplicate of https://github.com/GuabinaCore/WoWKoi/issues/442

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
