### ISSUE TITLE
[Arthas] - Quest Further Concerns

### ISSUE THREAD

**Issue by lanccerus** [GuabinaCore/WoWKoi#758]
**Links:**
https://www.wowhead.com/quest=35/further-concerns

**What is happening:**
The NPC Marshal Dughan (https://www.wowhead.com/npc=240/marshal-dughan) does not have the chat option to start riding the Stormcharger that will take the player to Eastvale Logging Camp.

**What should happen:**
The NPC mentioned above should have a chat option to start riding the Stormcharger that will take the player to Eastvale Logging Camp.

**Comment by LKArthas** [comment]
Fixed
