### ISSUE TITLE
[Dungeon] Blackrock Depths : Ring of Law

### ISSUE THREAD

**Issue by Randysandy929** [GuabinaCore/WoWKoi#759]
**Links:**

from WoWHead or our Armory

**What is happening:**
After killing the initial trash, the boss doesn't spawn and the players are bugged into the looting animation.

**What should happen:**
Boss should spawn, no bugs with looting animation.

**Comment by Cefiro-Caecias** [comment]
That Dungeon is still under repair. Patience ;)
