### ISSUE TITLE
mobs in azshara doesn't scale with level

### ISSUE THREAD

**Issue by onattuna** [GuabinaCore/WoWKoi#764]
**Links:**
https://imgur.com/kYicB0T

from WoWHead or our Armory

**What is happening:**
title

**What should happen:**

**Comment by Arkanheal** [comment]
Azshara isn't scripted yet, you shouldn't go to this zone :)

**Comment by Cefiro-Caecias** [comment]
Azshara, Desolace and Thousen Needles maps are under 50% repair. Patience ;)
