### ISSUE TITLE
[Core] - Grey Herbs give levels

### ISSUE THREAD

**Issue by onattuna** [GuabinaCore/WoWKoi#767]
**Links:**
https://imgur.com/a/rZHWqa3
from WoWHead or our Armory

**What is happening:**
title 

**What should happen:**

**Comment by carlosyuniro** [comment]
Solo dan nivel las 3 iniciales no me acuerdo el nombre ahora, igual que minería puedes subir a 300 con solo cobre.

**Comment by Arkanheal** [comment]
See #4

**Comment by Velthur-bot-3000** [comment]
Same issues apply from the mining report #4 , here is another WoD professions guide that gives the different level brackets for each herb.  

https://www.worldofmoudi.com/herbalism

Still need to configure the bonus loot depending on skill level.
