### ISSUE TITLE
[Core] - Sutileza Pícaro 

### ISSUE THREAD

**Issue by carlosyuniro** [GuabinaCore/WoWKoi#770]
https://es.wowhead.com/spell=108208/subterfugio

Al Salir de sigilo no se puede usar hechizos de sigilo en los 3 sec

"Tus facultades que requieren sigilo se pueden seguir usando hasta 3 sec después de haber salido del sigilo."

![WoWScrnShot_041620_221239](https://user-images.githubusercontent.com/62365902/79521392-7308db80-802f-11ea-922c-46aca1ed43f2.jpg)

**Comment by antonioyu0505** [comment]
Translation:
Subterfuge not properly working, after exiting stealth, cannot use stealth skills for the 3 seconds that it should allow.

**Comment by antonioyu0505** [comment]
Confirmed. Aside from that bug, if you use poisons, it kicks you out of stealth.
Additionally, if you happen to fail a skill while stealthed, it will kick you out of stealth.
