### ISSUE TITLE
[Arthas] - Quest Un'Goro Crater - The Fossil-Finder 3000

### ISSUE THREAD

**Issue by antonioyu0505** [GuabinaCore/WoWKoi#773]
**Links:**

https://www.wowhead.com/quest=24708/the-fossil-finder-3000

**What is happening:**
When using the device provided by the quest, it does not point out in the direction of the largest fossil, it merely points in the direction that the character is facing at the moment.

**What should happen:**
The character should turn to the direction of the largest fossil and also point at that direction. Moreover, the device tells the character how close they are to the fossil.

**Comment by Arkanheal** [comment]
Duplicate #566
