### ISSUE TITLE
[Arthas] - Quest Un'Goro Crater - The Ballad of Maximillian

### ISSUE THREAD

**Issue by antonioyu0505** [GuabinaCore/WoWKoi#774]
**Links:**

https://www.wowhead.com/quest=24707/the-ballad-of-maximillian

**What is happening:**
The third skill does not work, which deals 15.000 damage each time it is used.
After some time, the stallion stops moving.
After some time, you stop being able to use any skill at all.
While circling the lake, at some areas you cannot hurl rocks to the devilsaur.
Maximillian does not heal you.

**What should happen:**
After Maximillian hands you his shield, the third skill should be able to be used, which is tossing it to the devilsaur.
When you get low on health, Maximillian is supposed to heal you.
You should be able to use your first and second skills at any point given.

**Comment by antonioyu0505** [comment]
Resolved the first issue, it was because I had a full inventory. Yet the other issues remains.

**Comment by LKArthas** [comment]
remember that maximillian gives you a piece of its armor for you to throw if you don't have it you can't use the skill, regarding the stopping a global fix will be implemented for that
