### ISSUE TITLE
[Core] - Shaman - Enhancement - Stormstrike, Crash Lightning and Lava Lash

### ISSUE THREAD

**Issue by antonioyu0505** [GuabinaCore/WoWKoi#776]
**Links:**
https://www.wowhead.com/spell=187874/crash-lightning
https://www.wowhead.com/spell=213847/stormstrike
https://www.wowhead.com/spell=60103/lava-lash

**What is happening:**
All of these skills seems to have a reduced maelstrom cost, being 15 for Crash Lightning, 30 for Stormstrike and 25 for Lava Lash.
Casting Stormstrike with Stormbringer buff reduces this cost to 10.

**What should happen:**
The real maelstrom cost should be 20, 40 and 30, respectively.
Casting Stormstrike with Stormbringer buff should cost 20.

**Comment by Maczuga** [comment]
Can't confirm. I am level 25 atm and my costs are just fine. Perhaps you are over level 40 and Maelstrom Weapon passive is kicking in - giving you instantly some power after using them (which should work like that, only meele + WF procs should give it).

**Comment by Maczuga** [comment]
Yup, I just hit LVL 40 and I can confirm that it's the Maelstrom Weapon fault. Should only proc from white attack (meele non-special) and Windfury procs. 

Right now Stormstrike attacks generates +10 power, same goes for Lava Lash and Crash Lightning
