### ISSUE TITLE
Lynx Collar

### ISSUE THREAD

**Issue by Evilwowshaman** [GuabinaCore/WoWKoi#781]
**Links:**
https://www.wowhead.com/item=20797/lynx-collar
https://www.wowhead.com/npc=49874/blackrock-spy
**What is happening:**
Blackrock Spy orcs are dropping Lynx Collars, which are supposed to be dropping for another starter zone quest for Blood Elves.

**What should happen:**
They should only drop for the players on the quest on blood elves starting zone.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
