### ISSUE TITLE
[Core] - Hunter -- Everytime you Level disengage gets added to bar, but greyed out

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#782]
**Links:**
n/a Skills and Pets

**What is happening:**
Every time you level as a hunter, your pet dismisses itself.  As well as disengage gets added to your action bars, grayed out, because you shouldn't get it unless your marksman and level 65!  

**What should happen:**

Your pet should stay out after leveling, pet should always stay out unless you dismiss.  Disengage shouldn't be a talent for anyone other than marksman, and it shouldn't be a skill until 65.

**Comment by Velthur-bot-3000** [comment]
![2020 04 17-04 43](https://user-images.githubusercontent.com/43558040/79550303-28ef1c80-8066-11ea-85b0-9626f59207cd.png)


Showing disengage being given at level 26. grayed out on bar.

**Comment by Velthur-bot-3000** [comment]
Actually am misinformed, you are suppose to receive disengage at level 8, seems to be bugged and wont let us use it, just gets added every level greyed out.

https://wow.gamepedia.com/Disengage

https://wow.gamepedia.com/Disengage#Patches_and_hotfixes

**Comment by Thordekk** [comment]
Fixed pet not dissappear any more
