### ISSUE TITLE
NPC - Lost Gilnean Wardog

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#787]
**Links:**
https://www.wowhead.com/npc=51037/lost-gilnean-wardog#abilities

**What is happening:**
Rare doesn't spawn and patrol the camps above Deep Elem Mine.

**What should happen:**
Rare spawns

**Comment by Cefiro-Caecias** [comment]
Fixed (except patrol). Available in the next update.
