### ISSUE TITLE
[Core] - Pet achievement rewards

### ISSUE THREAD

**Issue by Macumbino** [GuabinaCore/WoWKoi#79]
**Links:**
https://www.wowhead.com/achievement=5875/littlest-pet-shop
https://www.wowhead.com/achievement=7500/going-to-need-more-leashes
https://www.wowhead.com/achievement=9643/so-many-pets
https://www.wowhead.com/achievement=1250/shop-smart-shop-pet-smart
https://www.wowhead.com/achievement=2516/lil-game-hunter
https://www.wowhead.com/achievement=1248/plethora-of-pets
https://www.wowhead.com/achievement=15/plenty-of-pets
https://www.wowhead.com/achievement=5876/petting-zoo
https://www.wowhead.com/achievement=5877/menagerie
https://www.wowhead.com/achievement=12958/master-of-minions
https://www.wowhead.com/achievement=7501/thats-a-lot-of-pet-food
https://www.wowhead.com/achievement=12992/pet-emporium

**What is happening:**
Every pet achievement up until 600 unique pets (maybe more? please check, as I'm not sure. The amount of achievements that activate seem to be random) seems to ding as soon as you get a pet. The rewards also arrive even if you have not gotten the achievements, as I have the "Shop Smart, Shop Pet.... Smart" achievement (thanks to a glitch), yet have gotten every pet reward up until Celestial Dragon (again, check every reward, as I may get more pet rewards for achievemtns in the future. The mail with a new pet seems to take 

**What should happen:**
You should only get the achievements when you get the correct amount of pets, and you should only get the pet rewards when you get the achievements.

**Comment by RygardNin** [comment]
Just received achievement "Plenty of Pets" -  I have no pets. Actually, I received one this morning from NPC Breanni, but pet is still in mail. Very random. I haven't even talked to pet trainer yet.
