### ISSUE TITLE
NPC - Nightlash

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#792]
**Links:**
https://www.wowhead.com/npc=46981/nightlash#abilities
https://www.wowhead.com/spell=3485/wail-of-nightlash

**What is happening:**
1. NPC doesn't patrol in the camp.
2. NPC doesn't cast Wail of Nightlash.

**What should happen:**
1. NPC patrols in the camp.
2. NPC casts Wail of Nightlash.

**Comment by Cefiro-Caecias** [comment]
Fixed (except patrol). Available in the next update.
