### ISSUE TITLE
[Zone] silverpine forest [NPC] Scale missing list.

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#798]
**Links:**
[Bloodfang Scavenger](https://www.wowhead.com/npc=44547/bloodfang-scavenger)
[Worgen Rusher](https://www.wowhead.com/npc=45535/worgen-rusher)
[Gilnean Hound](https://www.wowhead.com/npc=45367/gilnean-hound)
[Highland Fox](https://www.wowhead.com/npc=45335/highlands-fox)

**What is happening:**
All from Above don't scale.

**What should happen:**
All from Above suppose to scale to 60

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
