### ISSUE TITLE
[Quest] On The Mend

### ISSUE THREAD

**Issue by MBW91** [GuabinaCore/WoWKoi#804]
**Links:**
https://www.wowhead.com/quest=31589/on-the-mend

**What is happening:**
When trying to heal the battle pets at Murog, he always declines to do it:
![grafik](https://user-images.githubusercontent.com/10530989/79585780-95066a80-80d0-11ea-8c71-3bd186cb802f.png)

I tried it at different days and times, still no success.

**What should happen:**
He should heal the battle pets, so that the quest will be completed.

**Comment by Cefiro-Caecias** [comment]
To be shown the dialog option, you must first learn the spell https://www.wowhead.com/spell=119467/battle-pet-training
