### ISSUE TITLE
[Arthas] - Zul'Farrak Dungeon Gahz'rilla can't respawn/summon

### ISSUE THREAD

**Issue by ghost** [GuabinaCore/WoWKoi#805]
**Links:**
https://classic.wowhead.com/npc=7273/gahzrilla
https://classic.wowhead.com/object=141832/gong-of-zulfarrak

**What is happening:**
I did wipe on Gahz'rilla and after res did clear trash around it and suddenly Gahz'rilla disappeared. Can't click Gong to summon it again.

**What should happen:**
Gahz'rilla should be possible to resummon with Gong.

**Comment by Cefiro-Caecias** [comment]
This Dungeons is still under reconstruction. Patience.
