### ISSUE TITLE
Jumanza Grips Level requirement bugged

### ISSUE THREAD

**Issue by ghost** [GuabinaCore/WoWKoi#806]
**Links:**
https://classic.wowhead.com/item=18083/jumanza-grips

**What is happening:**
You much reach level 46 to use that item. I am level 47 druid. On the UI item doesn't have any lvl requirements.

**What should happen:**
Item should be possible to wear.

**Comment by Cefiro-Caecias** [comment]
You need to be Level 50 to equip it: https://www.wowhead.com/item=18083/jumanza-grips
