### ISSUE TITLE
[NPC/Scaling] Scarlet High Clerist

### ISSUE THREAD

**Issue by Maczuga** [GuabinaCore/WoWKoi#807]
**Links:**

https://www.wowhead.com/npc=1839/scarlet-high-clerist

**What is happening:**

Does not scale, always at lvl 50.

**What should happen:**

Should scale with level.

---

![image](https://user-images.githubusercontent.com/544349/79588384-1f9c9900-80d4-11ea-83af-c9bb9e7d31e2.png)

**Comment by Cefiro-Caecias** [comment]
Delete the Cache folder from your WoW to see the new changes; That NPC was escalated a long time ago.
