### ISSUE TITLE
[Arthas] - QUEST/NPC Zen'Kiki, the Druid

### ISSUE THREAD

**Issue by Maczuga** [GuabinaCore/WoWKoi#808]
**Links:**

https://www.wowhead.com/quest=26953/zenkiki-the-druid
https://www.wowhead.com/search?q=zen%27kiki#npcs

**What is happening:**

If you accept the quest mounted - he won't join you.

**What should happen:**

He should spawn even if you are mounted.

**Comment by NightwindOI** [comment]
Confirm
