### ISSUE TITLE
[SPELL - MONK] - Zen Pilgrimage

### ISSUE THREAD

**Issue by cauebarbosa** [GuabinaCore/WoWKoi#809]
**Links:**

from WoWHead or our Armory

https://pt.wowhead.com/spell=126892/peregrinação-zen

**What is happening:**

The skill is not working, the channeling is interrupted and a message saying that the spell is not available to me appears.

**What should happen:**

It should teleport us to the monk's "training" area at Peak of Serenity in Pandaria or Temple of the Five Dawns after completing the quest The Dawning Light.

**Comment by Serithul** [comment]
Since Pandaria and MoP expansion is not yet available it only natural for that peak not to work since it would enable you and any monk to enter the Pandaria continent.

**Comment by Cefiro-Caecias** [comment]
This spell was deliberately and temporarily disabled to prevent them from going to Pandaria before that expansion is repaired.
