### ISSUE TITLE
[Core] - Cannot "Solve" Archeology projects

### ISSUE THREAD

**Issue by Crimson-tear** [GuabinaCore/WoWKoi#81]
**Links:**
https://www.wowhead.com/item=69776/ancient-amber
from WoWHead or our Armory

**What is happening:**
Cannot "Solve" Archeology Projects any more. Clicking "Solve" have no respond/ no error message or anything. Namely "Ancient amber", I previously  already "Solve" one and currently having 200/200 fragments but now I cannot. Currenlty ALL Archeology projects cannot be solved.

**What should happen:**
Clicking "Solve" should consume the Fragments and create the item named in the project.

**Comment by Thordekk** [comment]
That function is rewrited now, all archeology system is being to be rewrited to new standards
