### ISSUE TITLE
[Zone] Northern Stranglethorn [NPC] List of problematic NPC's

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#810]
**Links:**

[Mosh'Ogg Witch Doctor](https://www.wowhead.com/npc=1144/moshogg-witch-doctor)
[Murkgill Oracle](https://www.wowhead.com/npc=4459/murkgill-oracle)
[Vale Howler](https://www.wowhead.com/npc=43050/vale-howler)
[Tsul'Kalu](https://www.wowhead.com/npc=51661/tsulkalu)

**What is happening:**

Mosh'Ogg Witch Doctor- [The totem](https://classic.wowhead.com/spell=3827/ward-of-laze) he summ act like a pet/NPC (move around). Suppose to stay at a place
Murkgill Oracle-Don't scale.Must scale to 60
Vale Howler-Its Neutral but look aggressive/visual
Tsul'Kalu-Scale is missing. Must scale to 60

**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
