### ISSUE TITLE
[Arthas] - Quest High Priest Venoxis

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#814]
**Links:**

https://www.wowhead.com/quest=26555/high-priest-venoxis#comments
https://www.wowhead.com/npc=43098/chabal

**What is happening:**
If u abound the quest cant retake it from him.
If u wipe Chabal don't give u the option to port u back.

**What should happen:**
Must be able to retake the quest from Chabal.
If u wipe Chabal give u the option to go back .

**Comment by NightwindOI** [comment]
Can some Dev add me this quest or complete it since it blocks the progress to the zone (if not it's ok).
Name Nightmage.

**Comment by LKArthas** [comment]
Fixed avaible on next update
