### ISSUE TITLE
[Core] - Spell Frost Death Knight Spell/Talent - Glacial Advance 

### ISSUE THREAD

**Issue by Filqkus** [GuabinaCore/WoWKoi#82]
https://www.wowhead.com/spell=194913/glacial-advance#changelog

Upon usage Glacial Advance spawns only 1 crystal cluster , and it does not advance forward. Instead it should spawn multiple that advance forward see wowhead screenshot!. Also check if attack power values correspond with the 7.3.0 version of the spell.

How to replicate. Get a frost dk, spec into glacial advance, use ability!

**Comment by GrandApothecary** [comment]
The dmg of this hability is huge! The spikes doesn't go forward, just spawn bellow the player who cast this. You can one-shot mobs, elite mobs, players. Because they do like 1-2-3k dmg per spike.

**Comment by GuabinaCore** [comment]
Fixed
