### ISSUE TITLE
Ironhide Devilsaur Falling through the Eart

### ISSUE THREAD

**Issue by gnarbrok** [GuabinaCore/WoWKoi#822]
**Links:**

https://www.wowhead.com/npc=6499/ironhide-devilsaur

**What is happening:**

Ironhide Devilsaur at the North part of the Roiling Gardens (there are clearly 2 spawn points for the Ironhide indicated on this map in the Roiling Gardens - I am talking about the more northern spawn point) just falls through the earth. 

**What should happen:**

He should not fall through the earth.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
