### ISSUE TITLE
[Arthas] - Quest Pierce Their Heart!

### ISSUE THREAD

**Issue by Spydoc** [GuabinaCore/WoWKoi#824]
**Links:**

https://www.wowhead.com/quest=13805/pierce-their-heart

**What is happening:**

When you use the quest item on the frozen heart, nothing happens. As of now, the quest is uncompletable.

**What should happen:**

When you use the quest item on the frozen heart, you should immediatelly get credit for completing the quest.

**Comment by GhostySimon** [comment]
![image](https://user-images.githubusercontent.com/63936782/80538895-7a57af80-8974-11ea-846d-4596f9eea0c4.png)

Was able to complete it only when using q item while standing on the bench :D

**Comment by LKArthas** [comment]
is completable yo need to stand near the hearth

**Comment by NightwindOI** [comment]
''Was able to complete it only when using q item while standing on the bench :D'' is right.
I try to be below the heart...around the heart or w/e...nothing work.Please re-open and fix.
