### ISSUE TITLE
[NPC] Missing Lashtail Raptor

### ISSUE THREAD

**Issue by Zinumwow** [GuabinaCore/WoWKoi#825]
**Links:**

https://www.wowhead.com/npc=686/lashtail-raptor

**What is happening:**
I was about to do the "Raptor Stalking" quest but it seems that there is no lashtail raptor on the place

**What should happen:**
It should have the npcs so i can kill it

**Comment by Zinumwow** [comment]
PS: There is very little young panthers in the map (https://www.wowhead.com/npc=683/young-panther)

**Comment by NightwindOI** [comment]
I did that quest before a day and was full of them. Maybe a respawn issue?

**Comment by Cefiro-Caecias** [comment]
Not bug present.
