### ISSUE TITLE
[Arthas] - Shadow Fang Keep (door after first boss won't open)

### ISSUE THREAD

**Issue by LostAgeMagic** [GuabinaCore/WoWKoi#834]
**Links:**

from WoWHead or our Armory

**What is happening:**
The door after the first boss is supposed to be opened by Packleader Ivar Bloodfang.
He walks up to the door, nothing happens, and then he walks away and stand nearby.

**What should happen:**
The door should open.

**Comment by LKArthas** [comment]
Fixed
