### ISSUE TITLE
[Core] - Druid not getting expert riding+flight form at level 58

### ISSUE THREAD

**Issue by lebrob** [GuabinaCore/WoWKoi#836]
**Links:**
https://www.wowhead.com/spell=34090/expert-riding
from WoWHead or our Armory

**What is happening:**
Druid isnt getting Expert Riding upon hitting level 58

**What should happen:**
Druid gets Expert Riding upon hitting level 58

**Comment by Maczuga** [comment]
From what I remember - Druid never got it for free. You had to learn 225 flying skill, then you could learn flight form (like during mop) now that travel form is unified - you still do not get flying for free
