### ISSUE TITLE
[QUEST/Chaining] Ice Delivery

### ISSUE THREAD

**Issue by Maczuga** [GuabinaCore/WoWKoi#841]
**Links:**

https://www.wowhead.com/quest=28628/ice-delivery

**What is happening:**

Not available after https://www.wowhead.com/quest=28632/fresh-from-the-hills

**What should happen:**

Should be

---

![image](https://user-images.githubusercontent.com/544349/79634910-c123f900-816d-11ea-9bb3-ba75e2ed3b3c.png)

**Comment by Maczuga** [comment]
Still not fixed. Quest not availalbe after doing https://www.wowhead.com/quest=28632/fresh-from-the-hills

![image](https://user-images.githubusercontent.com/544349/79985872-868ec900-84ab-11ea-8418-444f15dea75c.png)

**Comment by Nikismyname** [comment]
Still not fixed. Saying that because in the reddit post it said 100 percent for that zone, but that quest chokes of any further progress in the zone as far as I can tell.

**Comment by Maczuga** [comment]
They won't fix it. I already got response that the current chaining state is their decision and won't ever match the retail status. All my chaining issues were ignored and just closed.

**Comment by Nikismyname** [comment]
Is that because they intentionally skip some content for progress's sake, because I kinda agree with that. Even though it would be nice having 100% of the vanilla zones, it is probably better for the server if new content comes a bit faster in the future. I can't think of another reason.

**Comment by Maczuga** [comment]
Not at all. Check the reply here: https://github.com/GuabinaCore/WoWKoi/issues/714

It's called by them a 'server policy', but the reply I got stated, that their chaining makes player not going that much between some spots and let's you pick more quests - which is totally not true. 

Currently whole chaining is a mess, often you have to search for quests in known hubs, because some chains just get cut in the middle. Also most of the times you have only 1 quest and have to go back and forth many many times. 

Forget about leveling with Zygor or any guides made for retail. While Blizzard made their quest chain flow quite good so you do not have to visit same spot more than once or twice, here you have to learn some weird ass chaining that does not make any sense and stuff won't do anything about it. 

All their reddit posts stating, that zones are working 100% is obviously not true. Sure, quests are scripted very well, but without proper chaining it's worthless and that's a shame because you simply can't access some of them. 

Wish I could post that on reddit to prevent people from wasting time, but I do not have any karma there so my posts are deleted.

**Comment by Nikismyname** [comment]
Ok it is a bit weird the thing with the rearranging of the quests but Arthas said that the it is a bug that prevents finishing Winterspring, which is my big problem. Or did a quest pop up randomly somewhere in Winterspring that I need to find to continue?
