### ISSUE TITLE
[Zone]  The Barrens [NPC] Scale missing

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#842]
**Links:**

[Deviate Coiler](https://www.wowhead.com/npc=3630/deviate-coiler)
[Xelnaz](https://www.wowhead.com/npc=52312/xelnaz)
[Supervisor Lugwizzle](https://www.wowhead.com/npc=3445/supervisor-lugwizzle)
[Venture Co.Drudger](https://www.wowhead.com/npc=3284/venture-co-drudger) (Gnoll version of the npc scale well)
[Venture co.Mercenary](https://www.wowhead.com/npc=3282/venture-co-mercenary)
[Bristleback Hunter](https://classic.wowhead.com/npc=3258/bristleback-hunter)
[Warlord Krom'zar](https://www.wowhead.com/npc=9456/warlord-kromzar)
[Kolkar Invader ](https://www.wowhead.com/npc=9524/kolkar-invader)

**What is happening:**
Not scale.

**What should happen:**
Suppose to scale to 60

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
