### ISSUE TITLE
NPC: Swollen Voidwalker, Id: 39603

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#848]
**Links:**
https://www.wowhead.com/npc=39603/swollen-voidwalker
from WoWHead or our Armory

**What is happening:**
Isn't scaling.

**What should happen:**
Scale till 20.

**Comment by NightwindOI** [comment]
Duplicate https://github.com/GuabinaCore/WoWKoi/issues/637

**Comment by Serithul** [comment]
My bad
