### ISSUE TITLE
quest # 26472 Insane Druids Taneel Darkwood hits too hard

### ISSUE THREAD

**Issue by cyberfreak666** [GuabinaCore/WoWKoi#85]
https://www.wowhead.com/quest=26472/insane-druids#comments

I tried killing Taneel Darkwood  over ten times and keep getting killed within 2 hits and I do use the healing spells but they don't seem to be effective while fighting him while they work when I fight other mobs.  
according to the combat log the over tuned spell was shadow word pain hit for 3,814 which is way over kill can you fix this so he does not 2 shot me any more cause last fight I did not even get a chance to heal. 

If he was working normally shadow word pain and cast a minor heal
here is a link to the spell info for shadow word pain https://wow.gamepedia.com/Shadow_Word:_Pain

**Comment by LKArthas** [comment]
Fixed
