### ISSUE TITLE
[Arthas] - Items with missing scale val.1

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#851]
**Links:**

[[Myrmidon's Cape]](https://www.wowhead.com/item=8127/myrmidons-cape)
[[Widow Blade of the bear]](https://www.wowhead.com/item=15217/widow-blade)
[[Heavy Lamellar Gauntlets of the monkey]](https://www.wowhead.com/item=10242/heavy-lamellar-gauntlets)
[[Swashbuckler's Gloves of the whale]](https://www.wowhead.com/item=10186/swashbucklers-gloves)
[[Cabalist Spaulders of the whale]](https://www.wowhead.com/item=7532/cabalist-spaulders)
[[Mystical Belt of the owl]](https://www.wowhead.com/item=10180/mystical-belt)
[[Duskwoven Sandals of the owl]](https://www.wowhead.com/item=10058/duskwoven-sandals)
[[Chieftain's Gloves of the gorilla]](https://www.wowhead.com/item=9952/chieftains-gloves)
[[Righteous Boots of the owl]](https://www.wowhead.com/item=10068/righteous-boots)
[[Formidable Sabatons of the wolf]](https://www.wowhead.com/item=15630/formidable-sabatons)
[[Marble Circle of the gorilla]](https://www.wowhead.com/item=12002/marble-circle)
[[Revenant Boots of the bear]](https://www.wowhead.com/item=10131/revenant-boots)
[[Revenant Girdle of the boar]](https://www.wowhead.com/item=10130/revenant-girdle)
[[Overlord's Crown of the bear]](https://www.wowhead.com/item=10207/overlords-crown)
[[Royal Mallet of the boar]](https://www.wowhead.com/item=15263/royal-mallet)
[[Heavy Lamellar Girdle of strength]](https://www.wowhead.com/item=10243/heavy-lamellar-girdle)
[[Chieftain's Headdress of the wolf]](https://www.wowhead.com/item=9953/chieftains-headdress)
[[Cabalist Chestpiece of the whale]](https://www.wowhead.com/item=7527/cabalist-chestpiece)
[[Duskwoven Pants of spirit]](https://www.wowhead.com/item=10064/duskwoven-pants)
[[Warmonger]](https://www.wowhead.com/item=13052/warmonger)
[[Corpse Harvester of the wolf]](https://www.wowhead.com/item=15237/corpse-harvester)
[[Dwarven Magestaff of the boar]](https://www.wowhead.com/item=2072/dwarven-magestaff)

**What is happening:**

Dont scale with level

**What should happen:**
suppose to scale with level

**Comment by Arkanheal** [comment]
Seem to appear on all green item aside from quest ones

**Comment by Arkanheal** [comment]
Which means it's linked to #536
