### ISSUE TITLE
[Arthas] - Quest: Parts-is-Parts, Id: 24619

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#854]
**Links:**
https://www.wowhead.com/quest=24619/parts-is-parts
https://www.wowhead.com/item=49948/calders-bonesaw
https://www.wowhead.com/npc=37977/wildhammer-mercenary
from WoWHead or our Armory

**What is happening:**
Quest item Calder's Bonesaw can't be used on the corpse of Wildhammer Mercenary.

**What should happen:**
Calder's Bonesaw should be able to be use and produce the quest item needed for completion of the quest.

**Comment by LKArthas** [comment]
Fixed
