### ISSUE TITLE
Quest "The party never ends" bug

### ISSUE THREAD

**Issue by GhostySimon** [GuabinaCore/WoWKoi#861]
**Links:**

from WoWHead or our Armory

https://www.wowhead.com/quest=9067/the-party-never-ends
https://www.wowhead.com/npc=16442/vinemaster-suntouched

**What is happening:**

In the Silvermoon city you can't see the Innkeeper <Vinemaster Sountouched>. He's there but when you log in it dissapears.

**What should happen:**

NPC should be visible all the time.

**Comment by TheFlash3113** [comment]
Also [Innkeeper Velandra](https://www.wowhead.com/npc=16618/innkeeper-velandra) is missing in the same location. [Vinemaster Suntouched](https://www.wowhead.com/npc=16442/vinemaster-suntouched) is just a Wine & Spirits Merchant, but is the one related to this quest.

**Comment by Cefiro-Caecias** [comment]
Fixed.

**Comment by TheFlash3113** [comment]
Not fixed.
