### ISSUE TITLE
[Core] - Getting feared through walls

### ISSUE THREAD

**Issue by JadedNate** [GuabinaCore/WoWKoi#864]
**What is happening:**
Players can glitch through walls using enemy NPCs fears to get to random locations if done on a flying mount.
![WoWScrnShot_041820_233828](https://user-images.githubusercontent.com/57082188/79680217-c9fae600-81d2-11ea-821f-ac1571daec5c.jpg)

**What should happen:**
Not that lol

**Comment by Cefiro-Caecias** [comment]
This is a problem of textures and physics of the world, with which the majority of Server must learn to convince. The best solution is to remove fear from the NPCs that report.
