### ISSUE TITLE
[Arthas] - Jandice Barov deals way too much damage.

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#865]
**Links:**
https://www.wowhead.com/npc=59220/jandice-barov
https://www.wowhead.com/spell=113775/whirl-of-illusion
from WoWHead or our Armory

**What is happening:**
Whirl of Illusion happens at 66% and 33% of Jandice's HP and deals too much damage making the fight unable to be completed at all.

**What should happen:**
The damage should be set proper.

**Comment by LKArthas** [comment]
This is fixed on previous commit
