### ISSUE TITLE
[Core] Caster NPC AI/Logic

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#868]
**Links:**
Will Edit and add more Info later on
**What is happening:**
1)Let give for example [Sandfury Firecaller](https://www.wowhead.com/npc=5647/sandfury-firecaller).
You pull him with  [Pyroblast](https://www.wowhead.com/spell=11366/pyroblast), he comes half range and starts casting [Lava Gout](https://www.wowhead.com/spell=82641/lava-gout)-->You [Counterspell](https://classic.wowhead.com/spell=2139/counterspell) him and he just stays in one place. If u reset the fight he becomes ever more bugged.
If u just pull him and do nothing that happens:
He comes til 10y range, cast 1 spell, wait 2-3 sec, cast another spell-->repeat

**What should happen:**
1)You pull the Firecall Pyroblast, the core/NPC AI detect that's from 40y range. The NPC has Lava Gout(40y spell ) so at the moment u pull him, and u are in range for one of the spells, that NPC supposes to start casting that spell. Not move halfway true and then start with the cast.
If u Counterspell/silence casting NPC, it supposes to move in male range and attack u until silence duration is over.
When a caster mob starts attacking there is no gap between casts There is no reason for the mob just to stay and do nothing. If he has 1 spell=he must spam it. If he has 2 spells...spam both of them.

**Comment by Cefiro-Caecias** [comment]
Fixed.

**Comment by NightwindOI** [comment]
Only  Counterspell/Sillence part is fixed and work good (Sillence the mob--->he come to mele you).Anything else is still the same bugged thing.
