### ISSUE TITLE
[NPC/QUEST/ZONE] DK starting zone bugs

### ISSUE THREAD

**Issue by Maczuga** [GuabinaCore/WoWKoi#869]
Those are bugs I found during in DK starting zone:

First of all - there is missing XP selector NPC, I highly recommend moving it to command instead of NPC so people can change it everywhere.

- [ ] After creating a character only Death Coil and Death Grip were present on my bars. All default specialization spells were missing on bars, only present in spellbook.
- [ ] Instructor Razuvious walks slightly too fast (NPC ID: 28357)
- [ ] Eye of Acherus have it's spells in wrong order (source https://youtu.be/q0kzk854Wbg?t=358):
![image](https://user-images.githubusercontent.com/544349/79685307-1debe600-8238-11ea-8652-1155094fa7c6.png)
- [ ] Sometimes when you duel the same Death Knight for Death's Challenge quest (https://www.wowhead.com/quest=12733/deaths-challenge) - the duel flag does not disappear
![image](https://user-images.githubusercontent.com/544349/79685427-0f51fe80-8239-11ea-9d4a-9ff97df819c6.png)
- [ ] Also the same quest failed to give me a credit for duel won, most likely due to pet dealing the finishing blow to the target.
- [ ] Grand Theft Palomino (https://www.wowhead.com/quest=12680/grand-theft-palomino) - there is no "animation" for handling the horse - https://youtu.be/q0kzk854Wbg?t=1059. I should be ejected from the horse, and the Dark Rider of Acherus (ID: 28654) should cast a cyclone thingy on the horse.
- [ ] Into the Realm of Shadows (https://www.wowhead.com/quest=12687/into-the-realm-of-shadows) - can't return the Deathcharger. Pressing the Horseman's Call button (Spell ID 52362) in "Death's Breach" zone shows  "You are in the wrong zone"
![image](https://user-images.githubusercontent.com/544349/79685753-6062f200-823b-11ea-8848-383384dca3bf.png)
- [ ] Also if you abandon the quest Into the Realm of Shadows (https://www.wowhead.com/quest=12687/into-the-realm-of-shadows) - you are not put back into the regular phasing. Spell "Realm of Shadows" (ID 52693) remains active. You have to either change area or relog to get rid of the phasing spell now.
- [ ] The Gift That Keeps On Giving (https://www.wowhead.com/quest=12698/the-gift-that-keeps-on-giving) using the quest item (ID 39253) on either dead or alive Scarlet Miners (ID 28819) does nothing.
![image](https://user-images.githubusercontent.com/544349/79685956-dddb3200-823c-11ea-8caf-64b0004c3c29.png)
- [ ] There is also 1 Death Knight Initiate (ID 28406) which keeps killing miners - shouldn't be there.
![image](https://user-images.githubusercontent.com/544349/79685948-d451ca00-823c-11ea-8320-5a208bd12be9.png) - ref: https://youtu.be/q0kzk854Wbg?t=1410

For now that's it. I am blocked from further progress until "Into the Realm of Shadows" and "The Gift That Keeps On Giving" are fixed.

**Comment by Cefiro-Caecias** [comment]
Fixed.
