### ISSUE TITLE
[Core] - Character unequip items on respec + non working Equiment Manager spec assignment

### ISSUE THREAD

**Issue by Maczuga** [GuabinaCore/WoWKoi#870]
**Links:**

not related

**What is happening:**

Whenever I respec from Enhancement or Elemental to any other spec - for some reason Cloak, Waist, Ring 1 and Trinket 1 get unequipped.

Whenever I respec from Restoration to any other spec - for some reason Waist get unequipped.

I also tried doing auto-respec equipment by creating spec related profiles and setting the proper spec, but that does not work at all.

**What should happen:**

Respec should only unequip items that are unusable by spec (so offhand if it's a dual wield weapon when specing from Enhancement to other specs).

Also equip manager spec assignment should auto-equip that profile on spec change if profile exists.

**Comment by Zinumwow** [comment]
Im having the same problem as a druid.

**Comment by taktrix** [comment]
Bug confirmed, same issue.
