### ISSUE TITLE
[NPC] Dark Iron Spy 

### ISSUE THREAD

**Issue by drbubbs** [GuabinaCore/WoWKoi#872]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/npc=6123/dark-iron-spy#objective-of

**What is happening:**
The mob - Dark Iron Spy (Dun Morogh) has incorrect dialogue, it is using a variable for the characters name, **$C**.
![image](https://user-images.githubusercontent.com/63958157/79687474-63f87800-823f-11ea-90f7-0bf842e73fa1.png)

This message is also being said on death/running away, which doesn't seem correct.

**What should happen:**

The mob should say the characters name, with the dialogue at the start of combat.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
