### ISSUE TITLE
[Quest] Supervisor Fizsprocket

### ISSUE THREAD

**Issue by Spydoc** [GuabinaCore/WoWKoi#873]
**Links:**

https://www.wowhead.com/quest=26180/supervisor-fizsprocket

**What is happening:**

As soon as you take the quest, you're able to complete it because in the quest description it's written 0/0 Fizprocket's Clipboard (Complete).

**What should happen:**

The quest should require you to obtain the quest item by killing the appropriate NPC and when you take the quest, it should be written "0/1 Fizsprocket's Clipboard" in the description.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
