### ISSUE TITLE
[Core] - Eastern Kingdoms Explorer Achievement 

### ISSUE THREAD

**Issue by eighthourblink** [GuabinaCore/WoWKoi#875]
**Links:**
https://www.wowhead.com/achievement=42/eastern-kingdoms-explorer
from WoWHead or our Armory

**What is happening:**
Achievement "Eastern Kingdoms Explorer" is not being updated when zones are completed. In the screenshot, you can see that i have 3 zones completed, but the main achievement is not reflecting it. You can see that i completed Westfall and even says it on the main achievement, but its not showing up as completed. 

**What should happen:**
As zones are completed, "Eastern Kingdoms Explorer" should be filled in with green text / check mark once its completed. 

![big3](https://user-images.githubusercontent.com/2291863/79688504-b5434000-821c-11ea-8ed1-1913b561de22.png)

**Comment by Cefiro-Caecias** [comment]
Fixed.
