### ISSUE TITLE
[Arthas] - Worgen Starter Area Quest - Sacrifices

### ISSUE THREAD

**Issue by axryn** [GuabinaCore/WoWKoi#879]
Link: https://www.wowhead.com/quest=14212/sacrifices

Whats supposed to happen: Crowley should control the horse and path around the Greymane Court and Cathedral Quarter, while jumping over the barricades. You are allowed to use the torch to round up the mobs for quest credit.
https://youtu.be/YSHJmAOYNxc

What happens currently: You control Crowley's horse and are unable to jump over the barricades to the Cathedral Quarter. This makes the quest impossible to complete unless you relog and jump over the barricades yourself, while avoiding the huge amount of mobs.

**Comment by LKArthas** [comment]
Fixed
