### ISSUE TITLE
[Core] - Frost DK talent Icy Talons

### ISSUE THREAD

**Issue by L1n0x** [GuabinaCore/WoWKoi#882]
https://www.wowhead.com/spell=194878/icy-talons
https://www.wowhead.com/spell=213793/frost-strike

**What is happening:**
When you use Frost Strikes doesn't give you the buff of Icy talons
**What should happen:**
When you use Frost Strikes it should buff you with Icy talons

**Comment by GuabinaCore** [comment]
Fixed
