### ISSUE TITLE
[Core] - Death Knight (Frost) - Killing Machine & Obliterate

### ISSUE THREAD

**Issue by Krulnir** [GuabinaCore/WoWKoi#884]
Killing Machine: https://www.wowhead.com/spell=51128/killing-machine
Obliterate: https://www.wowhead.com/spell=49020/obliterate

Obliterate: Your auto attack critical strikes have a chance to make your next Obliterate critically strike.

Killing Machine is proc'ing as intended, and Obliterate is consuming the buff generated by it, however it is failing to critically strike.

**Comment by ShikoSCS** [comment]
Fixed
