### ISSUE TITLE
Wailing Caverns event - Muyoh

### ISSUE THREAD

**Issue by GhostySimon** [GuabinaCore/WoWKoi#887]
**Links:**

https://www.wowhead.com/npc=3678/muyoh

**What is happening:**

Muyoh doesn't initiate the event and stands still in the Wailing Caverns..

**What should happen:**

Muyoh should initiate the event and go for the final boss in the Wailing Caverns.

**Comment by Spydoc** [comment]
Duplicate: https://github.com/GuabinaCore/WoWKoi/issues/401
And it's stated that the dungeon is still being worked on.

**Comment by Cefiro-Caecias** [comment]
This Dungeon is still under construction.
