### ISSUE TITLE
[Core] - Riding skill achievement bug

### ISSUE THREAD

**Issue by GhostySimon** [GuabinaCore/WoWKoi#891]
**Links:**

from WoWHead or our Armory

**What is happening:**

When Paladin learns Apprentice riding skill automatically at level 20 he/she receives all the achievements related to learning riding skill, including artisan riding skill achievement "The right stuff", but skill itself is only in apprentice level.

**What should happen:**

Achievements should be given after you acquire related level of riding skill.

**Comment by Serithul** [comment]
Duplicate of https://github.com/GuabinaCore/WoWKoi/issues/262

**Comment by Thordekk** [comment]
We correct achievement data, try again when fix its applied
