### ISSUE TITLE
[Core] - Rogue - Outlaw - Roll the Bones

### ISSUE THREAD

**Issue by antonioyu0505** [GuabinaCore/WoWKoi#893]
**Links:**
https://www.wowhead.com/spell=193316/roll-the-bones
https://www.wowhead.com/spell=193358/grand-melee
**What is happening:**
Grand Melee is not giving Leech.
**What should happen:**
Grand Melee should give Leech

**Comment by antonioyu0505** [comment]
As per the Patch 7.2.5, Roll the Bones should give 1, 2 or 5 buffs with probabilities 79%, 20% and 1% respectively. However, it can give 3 and 6 buffs, which shouldn't happen.
**Proof:**
![WoWScrnShot_050120_175128](https://user-images.githubusercontent.com/50111341/80850895-0de2e780-8be4-11ea-8b35-695dc63dbeb6.jpg)

**Comment by sweetloo32** [comment]
From many accounts of other rogues and what I've witnessed on retail it can indeed give all 6 buffs. Its like rolling six 6-sided dice and it gives what ever side is the most facing up as a buff so if you get the possibilities of 1,2,3 or 6 for the buffs. Here is a post that explains it well. **https://www.reddit.com/r/wow/comments/4d6pex/roll_the_bones_explained/**
But yes indeed the leech is definitely not working.

**Comment by Serithul** [comment]
The reddit post you shared mate is from the alpha version of legion. While the wowhead link speaks of 7.2.5 . So I believe @antonioyu0505 is correct on what he says. It's quite possible it was changed during the alpha or on a later patch.
