### ISSUE TITLE
[Core] - DK TALENT + SPELLS !

### ISSUE THREAD

**Issue by RaphtaliaKoi** [GuabinaCore/WoWKoi#895]
**Links:**

https://www.wowhead.com/spell=48707/anti-magic-shell https://www.wowhead.com/spell=196770/remorseless-winter
https://www.wowhead.com/spell=51128/killing-machine
https://www.wowhead.com/spell=194878/icy-talons
https://www.wowhead.com/spell=207057/shattering-strikes
https://www.wowhead.com/spell=53343/rune-of-razorice

**What is happening:**
Frost Dk: 
[Shattering Strikes]:[Runeforging: Rune of Razorice]: Frost strike is not consuming Razorice stacks
[Anti-Magic Shell]: Does not work properly as i notice you do not get runic power from getting damaged by dots.. i recommend fully checking it !
[Remorseless Winter]: shows as a Debuff 
[Icy Talons]: Does not give 12% attack speed for 6 seconds & does not stack for 3 times 

**What should happen:**
Frost Dk:
[Shattering Strikes]:[Runeforging: Rune of Razorice]: Frost Strike should consume the 5 stacks of razorice & Deal 60% additional damage
[Anti-Magic Shell]: should gather runic power from any source of magic damage and prevent any source of dots or harmful magic effects.
[Remorseless Winter]: should be shown as a buff & can be cancel-able 
[Icy Talons]: should grand the passive & stack up to 3 times

**Comment by RaphtaliaKoi** [comment]
**Links:**
https://www.wowhead.com/spell=195679/bloodworms
https://www.wowhead.com/spell=49028/dancing-rune-weapon
https://www.wowhead.com/spell=195182/marrowrend

**What is happening:**
Blood Dk: 
[Blood Worms]: Does not work at all it procs a lot more than it should the worms don't attack they just stand still & follow until they heal you.. i was auto attack testing on my friend in a duel like 5 spawned.. heal is working fine but everything else not. 
[Dancing-Rune-Weapon]: Not working at all 
[Marrowrend]: whenever you gain a bone shield stack you gain more & more haste until its capped at 10% which gives 100% haste...

**What should happen:**
Blood Dk:
[Blood Worms]: should work as the link/ingame talent says.. only the healing works everything else none! they just target randomly go stare at the target and do nothing [UPDATE] The healing does work but it counts as Conversion when you check in that in combat log & in Details addon ! it should be healed as blood worms ^^ https://www.wowhead.com/spell=119975/conversion
[Dancing-Rune-Weapon]: should work as the link/in-game spell says giving the Dk 40% parry & so on.. the swords appear for 1 second then disappear no buff at all ! 
[Marrowrend]: should only give 10% haste. even if you have full stacks of bone shield or 1.. i don't know if the damage reduction is stacking as well.. ^^ didn't notice it as i am new to the class. also it should only remove a stack of bone shield if enemy hit you with auto attacks not spells. its getting removed by spells/dots also ! ^^

**Comment by RaphtaliaKoi** [comment]
Finish testing unholy seems Fine we are still 57 cuz of advancing into zone bug atm.. but as soon as we advance we will test all talents & update this issue ! <3 big love From <GET REKT SON> officer ^-^
as of the anti magic shell bug.. it seems to be affecting all specs ^^ [EDITED]

**Comment by RaphtaliaKoi** [comment]
[UPDATE] Dk Talent + spell: https://www.wowhead.com/spell=108194/asphyxiate
Problem: asphyxiate: Does the animation but the target can freely move/cast/attack 
How it should work: should be stunned for 5 seconds while in the air not being able to move!

**Comment by RaphtaliaKoi** [comment]
[UPDATE] Dk Passive: https://www.wowhead.com/spell=101568/dark-succor#changelog
Problem: not healing the right amount..
How it should work: should increase the healing by 100% when you kill an enemy that gives xp/honor well.. u will understand what i mean by reading it ^^ im bad at explaining trying my best !
it does proc and you get it for free use without runic power.. but it doesn't heal as much as it supposed to ! <3

**Comment by Serithul** [comment]
Unholy DK: Scourge Strike being AOE all the time
https://www.wowhead.com/spell=43265/death-and-decay
https://www.wowhead.com/spell=55090/scourge-strike

What happens:
Scourge Strike has always the passive bonus from death and decay.

What should happen:
Scourge Strike should only get the passive bonus when your death and decay is active and you are standing in it.

**Comment by antonioyu0505** [comment]
**Links:**
https://www.wowhead.com/spell=51462/runic-corruption
https://www.wowhead.com/spell=81229/runic-empowerment
**What happens:**
Runic corruption and Runic empowerment doesn't proc, tested multiple times.

**What should happen:**
It should proc based on the amount of runic power used.

**Comment by antonioyu0505** [comment]
**Links:**
https://www.wowhead.com/spell=79885/heart-strike
**What happens:**
It generates 20 of runic power.
**What should happen:**
It should generate 15 of runic power, because every rune used to cast a spell generates 10 and Heart Strike generates a bonus 5, so it should be 15 as opposed to 20.

**Comment by GuabinaCore** [comment]
Hi, Remorseless Winter, Icy Talon and Runic Empowerment should be fixed in the next update, please open 1 issue for spell. Thanks!
