### ISSUE TITLE
[NPC/Spawn] Khadgar's Upgraded Servant

### ISSUE THREAD

**Issue by Maczuga** [GuabinaCore/WoWKoi#896]
**Links:**

https://www.wowhead.com/npc=114550

**What is happening:**

He's here for some reason.

**What should happen:**

Shouldn't be.

---

![image](https://user-images.githubusercontent.com/544349/79741481-9e2a4e00-8301-11ea-8130-35a5a9973aa8.png)

**Comment by Cefiro-Caecias** [comment]
When we get to the Legion stage, we will put it in a special phase, so that only those who have quests in progress will see it ;)
