### ISSUE TITLE
Quest - Tomber's Supplies

### ISSUE THREAD

**Issue by Loquedog** [GuabinaCore/WoWKoi#90]
**Links:**

https://www.wowhead.com/quest=9152/tombers-supplies

**What is happening:**

The quest requires you to loot a certain box that is on an abandoned cart surrounded by ghouls. When you try to loot it, nothing happens(the is no loot) so you cannot complete the quest.

**What should happen:**

The item should be able to be looted so you can complete the quest.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the netx update.
