### ISSUE TITLE
[Core] - Achievement Ready, Set, Goat

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#900]
**Links:** https://www.wowhead.com/achievement=5444/ready-set-goat#comments
from WoWHead or our Armory

**What is happening:**
When you buy the item and try to complete the achievement without the quest, the achievement doesn't complete.

**What should happen:**
When you buy the item and try to complete the achievement without the quest, the achievement should complete.

**Comment by Thordekk** [comment]
We add all missing data try it again
