### ISSUE TITLE
Food Crate Floating in Solliden Farmstead 

### ISSUE THREAD

**Issue by eighthourblink** [GuabinaCore/WoWKoi#906]
**Links:**

https://classic.wowhead.com/object=3710/food-crate
Not the same food crate but you get the idea.

**What is happening:**
![1](https://user-images.githubusercontent.com/2291863/79866826-5b24b500-83ab-11ea-9e8a-3b1804702f84.png)

**What should happen:**
Food Crate should be on the ground, not floating in the air

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
