### ISSUE TITLE
[Arthas] - Farmers Broom Positioned Wrong on Character

### ISSUE THREAD

**Issue by eighthourblink** [GuabinaCore/WoWKoi#907]
**Links:**

https://classic.wowhead.com/item=3335/farmers-broom

**What is happening:**
![2](https://user-images.githubusercontent.com/2291863/79867066-be164c00-83ab-11ea-8950-c8063733872d.png)

**What should happen:**
Broom should be positioned like every other weapon

**Comment by Serithul** [comment]
https://www.wowhead.com/item=3335/farmers-broom#screenshots

It is correctly positioned. That link is from classic and is missing some screenshots. Remember to change the expansion on the upper right corner of wowhead anytime you are looking on classic links.

**Comment by eighthourblink** [comment]
Thanks for the suggestion. Does this link help? It just looks weird. I have another ticket open regarding another staff positioned wrong

New Link - https://www.wowhead.com/item=114980/farmers-broom&bonus=0
Another Ticket Link - https://github.com/GuabinaCore/WoWKoi/issues/636

**Comment by Serithul** [comment]
That is a link for another farmer's broom. These two are different. The 3335 one should be holstered as shown in your photo but the 114980 should be holstered as you suggest and as it shows in the screenshots. Which one do you have ?

You other issue is correct, no problem with that.

Edit: Upon inspecting the new link, i saw that that broom is bought from a vendor in shadowmoon valley, as we have no access to shadowmoon valley yet, i believe this is the link you are referring too, the one that dropped at Tirisfal Glades. This one is properly positioned mate. Have a look at the screenshots.

Link: https://www.wowhead.com/item=3335/farmers-broom

**Comment by eighthourblink** [comment]
Serithul, 

Thanks for the information. It was dropped in Trisfal Glades. If everything looks good to you guys, then we can close out the ticket. 

Im just here to help out. 

Also thanks for the server - even in the baby stages, the server has been enjoyable.

**Comment by Serithul** [comment]
Yeah man i know you are here to help. I hope i didn't seem angry or elitist or something. Sorry if i seemed like that, it wasn't in my intention.
