### ISSUE TITLE
[Core] - Victory Rush Passive

### ISSUE THREAD

**Issue by RaphtaliaKoi** [GuabinaCore/WoWKoi#908]
**Links:**

https://www.wowhead.com/spell=34428/victory-rush

**What is happening:**

https://cdn.discordapp.com/attachments/697056287501975562/702158939936260187/unknown.png
i am getting victory rush proc as fury warrior when i don't even have it 
**What should happen:**
i should not get victory rush as fury warrior at all its not a viable ability for this spec

**Comment by ShikoSCS** [comment]
This spell work fine in the spec Arms and Protection
