### ISSUE TITLE
[Arthas/Sefrenia] - Quest The Balance of Nature

### ISSUE THREAD

**Issue by Talir-Shogun** [GuabinaCore/WoWKoi#91]
How quest works now - After killing 6 Nightsabers, 2 NPC on mounts appear near Ilthalaine. When you give in quest there is a short dialogue between the 3 of them. At the end of 2 NPC on mounts just stay there even after you accept the next quest - Fel Moss Corruption. When you turn Fel Moss Corruption the 2 NPCs will appear and disappear quickly which is a bug. 

How it should work - after you give in the quest The Balance of Nature and there is a short dialogue the 2 NPCs on mount are supposed to turn away and walk on the road and fade away. The should not stay for the next quest.

**Comment by LKArthas** [comment]
Oks taking care

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
