### ISSUE TITLE
NPC - Thule Ravenclaw

### ISSUE THREAD

**Issue by DeltaVortex** [GuabinaCore/WoWKoi#910]
**Links:**
https://www.wowhead.com/npc=47023/thule-ravenclaw#drops
https://www.wowhead.com/npc=1870/hand-of-ravenclaw
https://www.wowhead.com/item=6577/defender-gauntlets
https://www.wowhead.com/spell=31976/shadow-shield
https://www.wowhead.com/spell=7655/hex-of-ravenclaw
https://www.wowhead.com/spell=7656/hex-of-ravenclaw
https://www.wowhead.com/spell=7657/hex-of-ravenclaw

**What is happening:**

1. His adds (id 1870) don't attack when you aggro him.
2. He doesn't use certain spells (silence maybe bugs him out)
3. Has incorrect drop table .

**What should happen:**

1. His adds attack you when you aggro him.
2. He casts Hex of Ravenclaw and Shadow Shield.
2. He drops Defender Gauntlets at 41% drop chance.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
