### ISSUE TITLE
[Arthas] - Quest: Investigate An'daroth, Id: 9160

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#913]
**Links:**
https://www.wowhead.com/quest=9160/investigate-andaroth
from WoWHead or our Armory

**What is happening:**
1) Investigate An'daroth shows twice on objectives (it's not because of addons).
![WoWScrnShot_042120_203741](https://user-images.githubusercontent.com/62258982/79896172-acb35b00-8410-11ea-88d1-66fb145af65f.jpg)

2)If you go to the camp and trigger the Investigate An'daroth objective the quest completes even if you haven't killed 12/12 mobs needed.

**What should happen:**
1) Should show only once.
2) Should only complete the appropriate objective, not the whole quest.

**Comment by LKArthas** [comment]
Fixed
