### ISSUE TITLE
Colmillor de cristal RARE

### ISSUE THREAD

**Issue by carlosyuniro** [GuabinaCore/WoWKoi#917]
https://es.classic.wowhead.com/npc=10376/colmillor-de-cristal
https://es.classic.wowhead.com/blackrock-spire

spamea muchas arañas y mata en segundo la raid

**Comment by Cefiro-Caecias** [comment]
Araña mala...! Mala...! ¬¬
Reparada. Invoca 8 arañas esbirras, pero tenía mal puesto que invocara 8 cada 5-10 segundos, sin parar. Ahora sólo lo hará 1 vez. Disponible en el próximo update.
