### ISSUE TITLE
Some critters drop loot

### ISSUE THREAD

**Issue by AnastasioTheSexyTauren** [GuabinaCore/WoWKoi#919]
links:
https://www.wowhead.com/npc=50478/ash-lizard 
https://www.wowhead.com/npc=61384/cockroach
https://www.wowhead.com/npc=61317/long-tailed-mole
I believe there's no need for more links, if there is ask me.

What is happening:
Ash Lizard drops a "Widow blade"
Cockroach dops "Preserved Threshadon meat"; "solid stone"; "ghost mushroom"
Long-tailed Mole drops "Preserved Threshadon meat"; "Bloodpetal sprout"

What should happen:
They shouldn't drop anything no drops

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
