### ISSUE TITLE
NPC - Young Nightsaber loot [2031]

### ISSUE THREAD

**Issue by Talir-Shogun** [GuabinaCore/WoWKoi#92]
**Links:**
https://www.wowhead.com/npc=2031/young-nightsaber#drops:0-19+16+1
from WoWHead or our Armory

**What is happening:**
Loot table seems to be bugged. They drop too much gray items. Most of the time they should drop only 1 Cat hair but now they drop 4-6 gray items.

**What should happen:**
Gray item drops should be a lot lower. They should drop only 1 gray hair 94% of the time.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
