### ISSUE TITLE
[Zone] Kalimdor [NPC] Rare's

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#921]
**Links:**

from WoWHead or our Armory

**What is happening:**

                                                              

-   **_Winterspring_** 

[Arcanus](https://www.wowhead.com/npc=51045/arcanus) is missing 
[Bornak the Gorer](https://www.wowhead.com/npc=50997/bornak-the-gorer) Is missing
[Mezzir the Howler](https://classic.wowhead.com/npc=10197/mezzir-the-howler) is missing
[Bruiser](https://www.wowhead.com/npc=50995/bruiser) is missing
[Gal'dorak](https://www.wowhead.com/npc=50993/galdorak) is missing
[Iceclaw](https://www.wowhead.com/npc=50819/iceclaw#comments) is missing
[Manas](https://www.wowhead.com/npc=50353/manas) is missing
[Norissis](https://www.wowhead.com/npc=50348/norissis) is missing
[Quetzl](https://www.wowhead.com/npc=50788/quetz) is missing
[Ronak](https://www.wowhead.com/npc=50346/ronak) is missing
[The Deep Tunneler](https://www.wowhead.com/npc=51028/the-deep-tunneler) is missing
[Grizzle Snowpaw](https://www.wowhead.com/npc=10199/grizzle-snowpaw) is missing

---------------------------------------------------------------------------------------------------------------                                                              

-   **_Felwood_**

[Spinecrawl](https://www.wowhead.com/npc=50724/spinecrawl) is missing
[Thicket](https://www.wowhead.com/npc=50864/thicket) is missing
[Gezan](https://www.wowhead.com/npc=51017/gezan) is missing
[Needle](https://www.wowhead.com/npc=50777/needle) is missing
[Cida](https://www.wowhead.com/npc=50905/cida) is missing
[Duskcoat](https://www.wowhead.com/npc=50833/duskcoat) is missing
[Fidonis](https://www.wowhead.com/npc=51046/fidonis) is missing
[Blackbog the Fang](https://www.wowhead.com/npc=50362/blackbog-the-fang) is missing
[Grovepaw](https://www.wowhead.com/npc=50925/grovepaw) is missing

---------------------------------------------------------------------------------------------------------------

- **_Darkshore_**

[Licillin](https://www.wowhead.com/npc=2191/licillin) It's there, but the items don't scale.
[Flagglemurk the Cruel](https://www.wowhead.com/npc=7015/flagglemurk-the-cruel) its there, but the items don't scale.
[Shadowclaw](https://www.wowhead.com/npc=149663/shadowclaw) it's there, but the items don't scale.
[Strider Clutchmother](https://www.wowhead.com/npc=2172/strider-clutchmother) is missing
[Firecaller Radison](https://www.wowhead.com/npc=2192/firecaller-radison) is there, but the items don't scale.
[Lord Sinslayer](https://www.wowhead.com/npc=7017/lord-sinslayer) is there, but the items don't scale.

---------------------------------------------------------------------------------------------------------------

- **_Ashenvale_**

[Apothecary Falthis](https://www.wowhead.com/npc=3735/apothecary-falthis) is missing

---------------------------------------------------------------------------------------------------------------

-  **_Stonetalon Mountains_**

[Volux](https://www.wowhead.com/npc=50895/volux) is missing
[Tenok](https://www.wowhead.com/npc=50874/tenok) is missing
[Dustflight the Cowardly](https://www.wowhead.com/npc=50884/dustflight-the-cowardly) is missing
[Arae](https://www.wowhead.com/npc=50812/arae) is missing
[Iriss the Widow](https://www.wowhead.com/npc=50759/iriss-the-widow) is missing

---------------------------------------------------------------------------------------------------------------

-  _**Northern Barrens**_ 
Done

---------------------------------------------------------------------------------------------------------------

- **_Southern Barrens_**

[Swinegart Spearhide](https://www.wowhead.com/npc=5864/swinegart-spearhide) is there, but the items don't scale.
[Georpriest Gukk'rok](https://www.wowhead.com/npc=5863/geopriest-gukkrok ) is there, but the items don't scale.
[Malgin Barleybrew](https://www.wowhead.com/npc=5848/malgin-barleybrew) is there, but the items don't scale.
[Heddin Stonewhisker](https://www.wowhead.com/npc=5847/heggin-stonewhisker) is there, but the items don't scale.
[Snort the Heckler](https://www.wowhead.com/npc=5829/snort-the-heckler) is there, but the items don't scale.

---------------------------------------------------------------------------------------------------------------

- **_Dustwallow Marsh_**

[Scruff](https://www.wowhead.com/npc=50945/scruff) is missing
[Anith](https://www.wowhead.com/npc=50784/anith) is missing
[Heronis](https://www.wowhead.com/npc=50342/heronis) is missing
[Teromak](https://www.wowhead.com/npc=50901/teromak) is missing
[Hayoc](https://www.wowhead.com/npc=14234/hayoc) is missing
[Scintillex](https://www.wowhead.com/npc=51069/scintillex) is missing
[Roth-Salam](https://www.wowhead.com/npc=51061/roth-salam) is missing
[Nychus](https://www.wowhead.com/npc=50875/nychus) is missing

---------------------------------------------------------------------------------------------------------------

- **_Tanaris_**

[Kregg Keelhaul](https://www.wowhead.com/npc=8203/kregg-keelhaul) is missing
[Omgorn the Lost](https://www.wowhead.com/npc=8201/omgorn-the-lost) is missing
[Soriid the Devourer](https://www.wowhead.com/npc=8204/soriid-the-devourer) is missing
[Quall](https://www.wowhead.com/npc=50343/quall) is missing
[Feras](https://www.wowhead.com/npc=50825/feras) is missing
[Goldenback](https://www.wowhead.com/npc=50986/goldenback) is missing
[Khep-Re](https://www.wowhead.com/npc=51062/khep-re) is missing

---------------------------------------------------------------------------------------------------------------

- **_Feralas_**

[Diamond Head](https://www.wowhead.com/npc=5345/diamond-head) is there, but the items don't scale.
[Arash-ethis](https://www.wowhead.com/npc=5349/arash-ethis) is missing.
[Mordei the Earthrender](https://www.wowhead.com/npc=43488/mordei-the-earthrender) is there, but the items don't scale.
[Old Grizzlegut](https://www.wowhead.com/npc=5352/old-grizzlegut) is there, but the items don't scale.
[Mushgog](https://www.wowhead.com/npc=11447/mushgog) is there, but male dmg need a Nerf. Hit like a truck.
[Qirot](https://www.wowhead.com/npc=5350/qirot) is there, but the items don't scale.
[The Razza](https://www.wowhead.com/npc=11497/the-razza) is missing.
 

---------------------------------------------------------------------------------------------------------------

- **_Desolace_**

[Kaskk](https://www.wowhead.com/npc=14226/kaskk) is missing
[Hissperak](https://www.wowhead.com/npc=14227/hissperak) is missing
[Accursed Slitherblade](https://www.wowhead.com/npc=14229/accursed-slitherblade) is there, but the items don't scale.
[Giggler](https://www.wowhead.com/npc=14228/giggler) is there but didn't scale.
[Prince Kellen](https://www.wowhead.com/npc=14225/prince-kellen) is there, but the items don't scale.

---------------------------------------------------------------------------------------------------------------

- _**Un'goro**_

[Ravasaur Matriarch](https://www.wowhead.com/npc=6581/ravasaur-matriarch) is missing
[Uhk'loc](https://www.wowhead.com/npc=6585/uhkloc) is there, but the items don't scale.

---------------------------------------------------------------------------------------------------------------

- **_Silithus_**

[Grubthor](https://www.wowhead.com/npc=14477/grubthor) is missing.
[Zora](https://www.wowhead.com/npc=14474/zora#comments) is missing.
[Gretheer](https://www.wowhead.com/npc=14472/gretheer) is there, but the items don't scale.
[Twilight Lord Everun](https://www.wowhead.com/npc=14479/twilight-lord-everun) is missing.

---------------------------------------------------------------------------------------------------------------

- **_Teldrassil_**

Done

---------------------------------------------------------------------------------------------------------------

- **_Bloodmyst Isle_**

[Fenissa the Assassin](https://www.wowhead.com/npc=22060/fenissa-the-assassin) is missing

---------------------------------------------------------------------------------------------------------------

- **_Thousand Needles_**

[Gibblesnik](https://www.wowhead.com/npc=14427/gibblesnik) is there, but the items don't scale.
[Barnacle Jim](https://www.wowhead.com/npc=50952/barnacle-jim) is missing.
[Nyaj](https://www.wowhead.com/npc=50748/nyaj) is missing.
[Cyn](https://www.wowhead.com/npc=50892/cyn) is missing.
[Achellios The Banished](https://www.wowhead.com/npc=5933/achellios-the-banished) is there, but the [guards](https://www.wowhead.com/npc=4250/galak-packhound) around him don't scale to 60.
The items drop don't scale too.
[Skyshadow](https://www.wowhead.com/npc=50785/skyshadow) is missing.
[Venomclaw](https://www.wowhead.com/npc=51001/venomclaw) is missing.
[The Barbed Horror](https://www.wowhead.com/npc=51008/the-barbed-horror) is missing.
[Kaxx ](https://www.wowhead.com/npc=50741/kaxx) is missing.

**What should happen:**
I know some zones are not 100% fixed etc, but just add the rare's now or w/e. Kalimdor is done.

**Comment by Cefiro-Caecias** [comment]
Winterspring finished. Mezzir the Howler and Grizzle Snowpaw do meet (Mezzir has 4 random spawn points; Grizzle is hard to tell apart from the other furbolgs, but it's where it should be).

Available in the next update.

I continue with your list.

Do you know how much I hate you? XD

**Comment by NightwindOI** [comment]
pain is temporary but the glory is eternal 
PS:There may be some error cuz the addon is retarded but still.

**Comment by Cefiro-Caecias** [comment]
Felwood, finished. Available in the next update. I continue tomorrow with the list.

I still hate you, gloriously XD

**Comment by Cefiro-Caecias** [comment]
Darkshore: All Rares meet, and everything is scaled. Do not forget to delete the cache folder of your WoW, or you will not see the changes.

**Comment by Cefiro-Caecias** [comment]
Ashenvale: the Apothecary Falthis is found.

**Comment by Cefiro-Caecias** [comment]
Stonetalon Mountains, done. Available in the next update.

**Comment by Cefiro-Caecias** [comment]
Southern Barrens: all Rares are scaled. Do not forget to delete the cache folder of your WoW, or you will not see the changes.

**Comment by Cefiro-Caecias** [comment]
Dustwallow Marsh, finished.

Hayoc is found, it has 2 random spawn points.

Available in the next update.

**Comment by Cefiro-Caecias** [comment]
Tanaris: the 3 Rares meet; some of them have multiple random spawn points.

Completed the 4 Rares of Stonetalon Mountains that you mistakenly put in Tanaris :P

Available in the next update.

**Comment by Cefiro-Caecias** [comment]
Feralas: all Rares meet, and are scaled; some of them have multiple random spawn points. **Don't forget to delete the Cache folder from your WoW, or you won't see the changes (such as scaling, for example).**

**Comment by Cefiro-Caecias** [comment]
Desolace: all Rares meet, and are scaled; some of them have multiple random spawn points.

Only Giggler was not scaled. Fixed. Available in the next update.

**Don't forget to delete the Cache folder from your WoW, or you won't see the changes (such as scaling, for example).**

**Comment by Cefiro-Caecias** [comment]
Un'goro Crater: all Rares meet, and are scaled; some of them have multiple random spawn points. **Don't forget to delete the Cache folder from your WoW, or you won't see the changes (such as scaling, for example).**

**Comment by Cefiro-Caecias** [comment]
Silithus: all Rares meet, and are scaled; some of them have multiple random spawn points. **Don't forget to delete the Cache folder from your WoW, or you won't see the changes (such as scaling, for example).**

**Comment by Cefiro-Caecias** [comment]
Bloodmyst Isle: all Rares meet, and are scaled; some of them have multiple random spawn points. **Don't forget to delete the Cache folder from your WoW, or you won't see the changes (such as scaling, for example).**

**Comment by Cefiro-Caecias** [comment]
Thousand Needles: Completed. Available in the next update.

Gibblesnik and Achellios are scaled. **Don't forget to delete the Cache folder from your WoW, or you won't see the changes (such as scaling, for example).**

I hate you. The next time I see a post from you, I will shake XDDDD

**Comment by NightwindOI** [comment]
Eastern kingdoms turn 🔪

**Comment by NightwindOI** [comment]
Ok don't kill me but...tested some rare's in Felwood and all good, but 4 of 5 was without any loot.Not sure if loot tables are fukt or I'm super unlucky.
