### ISSUE TITLE
[Arthas] - Quest Detonation

### ISSUE THREAD

**Issue by kazzxd20** [GuabinaCore/WoWKoi#923]
Links:
https://www.wowhead.com/quest=26668/detonation
from WoWHead or our Armory

What is happening:
Nothing happens, only keeps the quest taken and cannot finish it

What should happen:
Taking the quest should start an event that ends the quest chain then it can be completed.

**Comment by LKArthas** [comment]
Check if you take it while mounted, so far cinematics doesn't start while you'r on a mount, a global fix is preppared for that
