### ISSUE TITLE
NPC: Scarlet Commander

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#924]
**Links:**
https://www.wowhead.com/npc=28530/scarlet-commander
https://wow.gamepedia.com/Scarlet_Commander
from WoWHead or our Armory

**What is happening:**
Misspelling in it's talking emotes "Scarlet lilth!DIE!".
![WoWScrnShot_042220_174043](https://user-images.githubusercontent.com/62258982/79996053-a8df1180-84c0-11ea-9da2-ffa9780d72bc.jpg)

**What should happen:**
Should say "Scarlet filth! DIE!".

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
