### ISSUE TITLE
Quest - Endgame

### ISSUE THREAD

**Issue by MeatyBoii** [GuabinaCore/WoWKoi#927]
**Links:**https://www.wowhead.com/quest=26706/endgame

from WoWHead or our Armory

**What is happening:** 

Instead of fighting on the back of the hierogryphs, you can turn the quest in directly. There is no option to mount the animals, and Lorna Cowley has the question mark over her head directly after accepting the quest.

**What should happen:**
You should be able to fight the horde gunship.

**Comment by Cefiro-Caecias** [comment]
Indeed, that is the only quest in the Worgen saga that we have not been able to repair 100% blizzlike. It is pending in our agenda. Patience ^^
