### ISSUE TITLE
Frightened Citizen in Spanish on Enlish C

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#928]
**Links:**
https://www.wowhead.com/npc=34981/frightened-citizen
https://www.wowhead.com/npc=35836/frightened-citizen
from WoWHead or our Armory

**What is happening:**
Their name is in Spanish even when on a client with English locale.

**What should happen:**
The name should be in English when the client has English locale.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
