### ISSUE TITLE
[Core] - Rogue - Assassination - Hemorrhage

### ISSUE THREAD

**Issue by antonioyu0505** [GuabinaCore/WoWKoi#929]
**Links:**
https://classic.wowhead.com/spell=16511/hemorrhage

**What is happening:**
It seems that hemorrhage is not awarding the combo point that it is supposed to generate. If hemorrhage was used to generate 1 combo point, the finishers will use one less than it is supposed to be using.

**What should happen:**
Hemorrhage should generate 1 combo point and finishers should take this into account.

**Comment by ShikoSCS** [comment]
Fixed
