### ISSUE TITLE
[Arthas] - Quest: The Rebel Lord's Arsenal, Id:14159 

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#931]
**Links:**
https://www.wowhead.com/quest=14159/the-rebel-lords-arsenal
https://www.wowhead.com/npc=35378/lorna-crowley
from WoWHead or our Armory

**What is happening:**
Disclaimer: It may have been a desync issue when i was playing, but i'm reporting it in case it isn't.

Completing the quest triggers the event where you are bitten and knocked back. At that moment the quest giver, having turned to worgen form, jumps but instantly disappears.

**What should happen:**
It should leap in the air in order to get to you but he should be shot mid air and die from Lorna Crowley which is spawned because of the event, as shown in the video section of the quests link.

**Comment by LKArthas** [comment]
Fixed
