### ISSUE TITLE
[Arthas] - Quest : A Blight Upon the Land [Horde]

### ISSUE THREAD

**Issue by Hutsun1** [GuabinaCore/WoWKoi#933]
**Links:**
https://www.wowhead.com/quest=28237/a-blight-upon-the-land
https://youtu.be/WfY54ffU-B4 (how he transforms)

**What is happening:**
Warden Stillwater does not transform into a behemoth when his health drops below 50%.
He stays in his Undead form. When you kill him and complete the quest, his dead body spawned on the ground. 

**What should happen:**
He should transform and knock you in the air when his health drops at a certain level (attached the video from the WoW Head article)

**Comment by LKArthas** [comment]
Fixed avaible on next update
