### ISSUE TITLE
NPC / Zone : Dead Scar NPCs in Eversong not attacking

### ISSUE THREAD

**Issue by Hutsun1** [GuabinaCore/WoWKoi#934]
**Links:**
https://www.wowhead.com/npc=15654/plaguebone-pillager
https://www.wowhead.com/npc=15655/rotlimb-cannibal

**What is happening:**
The Plaguebone Pillager and Rotlimb Cannibal on the Dead Scar up from Sillvermoon (where Ranger Jaela gives a quest) up until the river do not attack at all. 

![WoWScrnShot_042220_232000](https://user-images.githubusercontent.com/64165736/80032054-45220c00-84f3-11ea-8475-414f99dd3a5d.jpg)

![WoWScrnShot_042220_233437](https://user-images.githubusercontent.com/64165736/80032017-36d3f000-84f3-11ea-92cf-1fc9e02b8d63.jpg)

**What should happen:**
Both NPC should be hostile to Alliance and Horde.

**Comment by Cefiro-Caecias** [comment]
They are hostile, but not aggressive, unless the attacks. It is thought so, since due to its quantity and proximity, no low level player could survive if it passes through that area.
