### ISSUE TITLE
[Achievement] [Skill] Worgen get all riding achievements at level 20

### ISSUE THREAD

**Issue by MrSolg** [GuabinaCore/WoWKoi#935]
**Links:**
https://www.wowhead.com/spell=33388/apprentice-riding --20

https://www.wowhead.com/spell=33391/journeyman-riding --40
https://www.wowhead.com/spell=34090/expert-riding --60
https://www.wowhead.com/spell=34091/artisan-riding --70
https://www.wowhead.com/spell=90265/master-riding --80

**What is happening:**
Upon reaching level 20 on a Worgen character, you receive the achievements all riding skills, not just Apprentice Riding at level 20. This is so you can use the ability Running Wild.

(Do note in my spellbook, I'm only credited for Apprentice Riding. I do not know if I'll get Journeyman at level 40 yet.)

**What should happen:**
Upon reaching level 20 on a Worgen character, you receive the achievement for just Apprentice Riding at level 20.

**Comment by Serithul** [comment]
This is a bug that happens on all races and classes. https://github.com/GuabinaCore/WoWKoi/issues/262
