### ISSUE TITLE
[Core] - Guardian elixir

### ISSUE THREAD

**Issue by GhostySimon** [GuabinaCore/WoWKoi#936]
**Links:**

from WoWHead or our Armory

**What is happening:**

If you drink a guardian elixir potion and use a scroll that acts as a guardian elixir, both effects stack

![image](https://user-images.githubusercontent.com/63936782/80039298-813e7800-84c5-11ea-93e2-5b82514f5c0e.png)

![image](https://user-images.githubusercontent.com/63936782/80039347-9adfbf80-84c5-11ea-9075-37b5a484c199.png)

**What should happen:**

One effect should replace another.

**Comment by ShikoSCS** [comment]
Fixed
