### ISSUE TITLE
[Core] - Clean Up Bags button not working

### ISSUE THREAD

**Issue by Talir-Shogun** [GuabinaCore/WoWKoi#94]
**Links:**

from WoWHead or our Armory

**What is happening:**
When I press B to open bags and I press Clean Up bags button while talking to a vendor it does not sell all gray items automatically

**What should happen:**
When I press Clean Up bag button while talking to a vendor it should sell all gray items (items indicated with a coin)

**Comment by Clangeddin** [comment]
Not only it should vendor all grey, when you're at the vendor, it should also sort all items in your inventory according to your bag preferences, even when you're not at the vendor.
At the moment, this is simply not working at all.
