### ISSUE TITLE
Mazmorra - Cueva de los lamentos 

### ISSUE THREAD

**Issue by carlosyuniro** [GuabinaCore/WoWKoi#941]
https://es.wowhead.com/npc=3678/muyoh
https://es.classic.wowhead.com/wailing-caverns

El Npc Muyoh no activa el evento para matar al jefe final, después de haber matado a los otros jefes.

**Comment by Cefiro-Caecias** [comment]
Este Dungeon aun se encuentra al 50% de desarrollo. Paciencia ;)
