### ISSUE TITLE
[Core] - Worgen starting area quest - Two By Sea - undead catapult not working properly

### ISSUE THREAD

**Issue by daddylongneck123** [GuabinaCore/WoWKoi#942]
Worgen starting area quest - Two By Sea - undead catapult not working properly: it launches your character straight through the boat rather than over it:

![WoWScrnShot_042320_002142](https://user-images.githubusercontent.com/63481493/80059015-d647b180-84f8-11ea-9cef-679d8bd09f0d.jpg)

**Comment by NightwindOI** [comment]
[Two By Sea](https://www.wowhead.com/quest=14382/two-by-sea) quest 
What [suppose to happen](https://youtu.be/zukvEkKQ-J8?t=67)

**Comment by Cefiro-Caecias** [comment]
Fixed.
