### ISSUE TITLE
[NPC] Saltwater Snapjaw

### ISSUE THREAD

**Issue by TheFlash3113** [GuabinaCore/WoWKoi#943]
**Links:**

https://classic.wowhead.com/npc=2505/saltwater-snapjaw

**What is happening:**

[Saltwater Snapjaw](https://classic.wowhead.com/npc=2505/saltwater-snapjaw) is a neutral mob with hostile tooltip, unitframe and nameplate.

**What should happen:**

It should have a neutral tooltip, unitframe and nameplate.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
