### ISSUE TITLE
[NPC] Whitetail Fox

### ISSUE THREAD

**Issue by TheFlash3113** [GuabinaCore/WoWKoi#944]
**Links:**

https://www.wowhead.com/npc=44474/whitetail-fox

**What is happening:**

[Whitetail Fox](https://www.wowhead.com/npc=44474/whitetail-fox) is a neutral mob with hostile tooltip, unitframe and nameplate.

**What should happen:**

It should have a neutral tooltip, unitframe and nameplate.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
