### ISSUE TITLE
[Ruins of Ahn'Qiraj][Ossirian the Unscarred]

### ISSUE THREAD

**Issue by RaphtaliaKoi** [GuabinaCore/WoWKoi#945]
**Links:**

https://www.wowhead.com/npc=15339/ossirian-the-unscarred#videos:id=3695
https://www.youtube.com/watch?v=YCB6Uw5m4cw

**What is happening:**

Mechanics aren't working properly 

**What should happen:**

should work as the video shows !

**Comment by RaphtaliaKoi** [comment]
The pillars cancel his ﻿ crazy damage buff and also leaves a random ( fire-shadow-nature ) etc + spell damage taken debuff on him .
it doesn't work here it takes much time for him to take the debuff and remove his buff

**Comment by Cefiro-Caecias** [comment]
Raid under review.
