### ISSUE TITLE
[Arthas] - Torek's Assault

### ISSUE THREAD

**Issue by Evilwowshaman** [GuabinaCore/WoWKoi#946]
**Links:**
https://classic.wowhead.com/quest=6544/toreks-assault

**What is happening:**
The quest is working as intented, but npc scriptings are a bit off. Torek is assaulting Silverwing Outpost, but his guards are just standing still next to him, doing nothing.

**What should happen:**
They should be helping him with the assault.

**Comment by NightwindOI** [comment]
More info about the QUest.Torek does like 100 male dmg-Must be more.
If anything outside the elf attacks u the orc's bug out.
https://streamable.com/fkjqe9
Duriel Moonfire Don't scale.
https://classic.wowhead.com/npc=12860/duriel-moonfire
Orc Formation stuck at each other (it may be a global issue)
https://streamable.com/ha8ow8
