### ISSUE TITLE
[Buru the Gorger]

### ISSUE THREAD

**Issue by RaphtaliaKoi** [GuabinaCore/WoWKoi#947]
**Links:**

https://www.wowhead.com/npc=15370/buru-the-gorger

**What is happening:**

Mechanics doesn't work properly with the eggs
Does way too much damage

**What should happen:**
he shouldn't do that much damage and eggs mechanic should work properly plz check the boss overall ^^ !

**Comment by Cefiro-Caecias** [comment]
Raid under review.
