### ISSUE TITLE
[NPC] Northridge Spider

### ISSUE THREAD

**Issue by TheFlash3113** [GuabinaCore/WoWKoi#948]
**Links:**

https://www.wowhead.com/npc=44284/northridge-spider

**What is happening:**

[Northridge Spider](https://www.wowhead.com/npc=44284/northridge-spider) is a neutral mob with hostile unitframe and nameplate.

**What should happen:**

It should have a neutral unitframe and nameplate.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
