### ISSUE TITLE
[Arthas/Sefrenia] - Tarindrella ID 49480

### ISSUE THREAD

**Issue by Talir-Shogun** [GuabinaCore/WoWKoi#95]
**Links:**
https://www.wowhead.com/npc=49480/tarindrella#abilities
from WoWHead or our Armory

**What is happening:**
She is supposed to cast 3 abilities and never auto attack. 
Cleanse Spirit
Entangling Roots
Summon Nature's Bite

Currently she is not casting Summon Nature's Bite and auto attack the mobs instead.

**What should happen:**
Cast 3 abilities and never auto attack

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
