### ISSUE TITLE
[Core] - Ogrish Motivation

### ISSUE THREAD

**Issue by MeatyBoii** [GuabinaCore/WoWKoi#953]
**Links:** https://www.wowhead.com/spell=89652/ogrish-motivation

**What is happening:** The spell lasts throughout the entire Deadmines dungeon, and even after leaving the group and moving back outside.

**What should happen:** The spell should lose its power once, as described in wowhead link, Ogre Henchman stops yelling.

**Comment by Thordekk** [comment]
Someone can tell me if exist issue?
