### ISSUE TITLE
[Arthas] - Closed doors in deadmine

### ISSUE THREAD

**Issue by GhostySimon** [GuabinaCore/WoWKoi#954]
**Links:**

from WoWHead or our Armory

**What is happening:**

After killing first boss we wiped twice - now the door is closed:
![image](https://user-images.githubusercontent.com/63936782/80142597-6e857b00-8579-11ea-9b2d-e2b967ecbcdb.png)

**What should happen:**

The doors should remain open no matter how many times we wipe.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
