### ISSUE TITLE
Frost DK Talent: Shattering Strikes

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#957]
**Links:**
https://www.wowhead.com/spell=207057/shattering-strikes
from WoWHead or our Armory

**What is happening:**
[Shattering Strikes]:[Runeforging: Rune of Razorice]: Frost strike is not consuming Razorice stacks

**What should happen:**
[Shattering Strikes]:[Runeforging: Rune of Razorice]: Frost Strike should consume the 5 stacks of razorice & Deal 60% additional damage

**Comment by ShikoSCS** [comment]
Fixed
