### ISSUE TITLE
Blood DK Talent: Bloodworms

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#958]
**Links:**
https://www.wowhead.com/spell=195679/bloodworms
from WoWHead or our Armory

**What is happening:**
Does not work at all it procs a lot more than it should the worms don't attack they just stand still & follow until they heal you.. i was auto attack testing on my friend in a duel like 5 spawned.. heal is working fine but everything else not.

**What should happen:**
should work as the link/ingame talent says.. only the healing works everything else none! they just target randomly go stare at the target and do nothing [UPDATE] The healing does work but it counts as Conversion when you check in that in combat log & in Details addon ! it should be healed as blood worms ^^ https://www.wowhead.com/spell=119975/conversion

**Comment by GuabinaCore** [comment]
Fixed
