### ISSUE TITLE
[Core] - MOUNT

### ISSUE THREAD

**Issue by dan2142** [GuabinaCore/WoWKoi#96]
Links: https://www.wowhead.com/spell=121820/obsidian-nightwing

What is happening: When mounting up in the water the fly mount cant fly only walk.

**Comment by Maczuga** [comment]
To elaborate on that - mounting - even in water should always use your max skill (excluding zone restrictions). 

Right now, if you mount on ground - all is ok, it you walk a bit into the water or you are swimming - mount will only use 100% ground speed without flying.

Example (currently):
- the place where I stand - if I mount I get ground + flying (if learned)
- the red circle - mounting causes you to only get ground speed without flying - you should get the flying too.

![image](https://user-images.githubusercontent.com/544349/79636369-727b5c80-8177-11ea-8286-1d58f4fc3c57.png)

**Comment by Thordekk** [comment]
Can u add one video from bug?
