### ISSUE TITLE
[Arthas] - Stratholme - Bloquea el juego.

### ISSUE THREAD

**Issue by carlosyuniro** [GuabinaCore/WoWKoi#966]
https://es.classic.wowhead.com/stratholme
https://es.classic.wowhead.com/npc=10438/maleki-el-p%C3%A1lido

Maleki el Pálido al atacar a este jefe nos tiro la computadora a todos, nos toco reiniciar la pc.

![WoWScrnShot_042320_202732](https://user-images.githubusercontent.com/62365902/80161160-d81b7e80-85a5-11ea-9c8b-bb1dfb8b99d5.jpg)

y al pasar por esa zona donde esta mi personaje paso lo mismo con un amigo y yo.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
