### ISSUE TITLE
Duplicate quest

### ISSUE THREAD

**Issue by GhostySimon** [GuabinaCore/WoWKoi#967]
**Links:**

from WoWHead or our Armory

**What is happening:**

Got two same quests by picking one from NPC and accepting the other one that has been picked up by a party member:
![image](https://user-images.githubusercontent.com/63936782/80163641-c84f6a80-85a4-11ea-9c67-a59bcc0fcf37.png)

**What should happen:**

Should not allow have two identical quests.

**Comment by Cefiro-Caecias** [comment]
One quest is Alliance and the other Horde. They were missing the Faction constraint. Fixed. Available in the next update.
