### ISSUE TITLE
[Core] - Hunter Kill Command doesn't deal damage.

### ISSUE THREAD

**Issue by Quelan** [GuabinaCore/WoWKoi#97]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/spell=205440/kill-command

**What is happening:**
When you cast "Kill Command" the animation occur but pet deals normal damage or sometimes doesn't even reset his autoattack timer.

**What should happen:**
 What should happen is that he should deal extra damage as stated in ability and even reset his autoattack timer.

**Comment by login6710** [comment]
Fixed 
https://github.com/GuabinaCore/TYCE-Group/commit/538949ea8d8ee688f40bb2958d3e46c40f0539b5
