### ISSUE TITLE
[Core] - Frost DK: Killing Machine

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#972]
**Links:**
https://www.wowhead.com/spell=51128/killing-machine
https://wowwiki.fandom.com/wiki/Glancing_blow
from WoWHead or our Armory

**What is happening:**
Killing Machine procs on Glancing Blows.

**What should happen:**
Killing Machine should proc only when an auto attack critical strikes.

Reproduction: Get a Frost DK to only auto attack a dummy and see the combat log when the passive procs. Blows will be marked as Glancing and none will be a Critical (also used a damage tracker addon to see how many attacks were of what kind etc)

**Comment by ShikoSCS** [comment]
Fixed
