### ISSUE TITLE
[Core] - DK mounting bug

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#973]
**Links:**

from WoWHead or our Armory

**What is happening:**
If you have your weapons unsheathed and you press a mount, the weapons are still unsheathed even when you are mounted.
![WoWScrnShot_042420_095820](https://user-images.githubusercontent.com/62258982/80183891-501f8e00-8612-11ea-96d1-13137c1b56ee.jpg)

**What should happen:**
Weapons should be sheathed when you use any travel mount.

**Comment by Serithul** [comment]
Relogging fixed the issue, but i'm not sure if it is or not a bug

**Comment by Thordekk** [comment]
Issue was caused by delay try now please
