### ISSUE TITLE
[Core] - Warrior spell Devastate

### ISSUE THREAD

**Issue by Velthur-bot-3000** [GuabinaCore/WoWKoi#974]
**Links:**
https://wow.gamepedia.com/Devastate

**What is happening:**
your spell " A direct strike, dealing 147 physical damage." Basically, weak AF

**What should happen:**
"A direct strike, dealing (277% of weapon damage) Physical damage. 30% chance to reset the remaining cooldown on Shield Slam."  Tooltip text from spell  

Thanks y'all

**Comment by Serithul** [comment]
It says 277% of weapon damage, have you checked the damage of your weapon and done the multiplication and the 2 numbers didn't match ?

**Comment by Velthur-bot-3000** [comment]
Sorry, got back to you a little late.  So seems the damage does scale according to weapon damage, seems to be accurate to the % listed.  Just still wondering about the chance to reset shield slam?

**Comment by Serithul** [comment]
You may or may not have been unlucky tbh. We shall see when the devs have a look at it.
