### ISSUE TITLE
[Core] - No achievement for riding skill

### ISSUE THREAD

**Issue by GhostySimon** [GuabinaCore/WoWKoi#978]
**Links:**

from WoWHead or our Armory

**What is happening:**

Didn't get the achievement after learning riding skill in Orgrimmar (see attached):
![image](https://user-images.githubusercontent.com/63936782/80219551-a12e8280-8610-11ea-93a8-c94191384d90.png)

**What should happen:**

Should have received the achievement.

**Comment by Thordekk** [comment]
We are implementing all missing achievements, sorry for inconvenniences
