### ISSUE TITLE
[Arthas] - Pulling certain mobs in certain dungeons slowly freezes PC

### ISSUE THREAD

**Issue by alekso999** [GuabinaCore/WoWKoi#979]
**Links:**

from WoWHead or our Armory

**What is happening:**

Certain pulls in Scarlet Monastery, Stratholme, Stockades freezes the game and then the whole PC.
Happens to all party members.
**What should happen:**

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
