### ISSUE TITLE
[Arthas/Sefrenia] - Quest: Vile Touch ID 28727

### ISSUE THREAD

**Issue by Talir-Shogun** [GuabinaCore/WoWKoi#98]
What is happening: After you kill the spider there is no event of Tarindrella killing the totem.

What should happen: after you kill the big spider there should be a small event where Tarindrella uses her Summon Nature's Bite ability to kill the Gnarlpine Corruption Totem near the eggs. There is also some dialogue during this event.

**Comment by LKArthas** [comment]
Fixed
