### ISSUE TITLE
[Zone] Eastern Kingdoms [NPC] Rare list

### ISSUE THREAD

**Issue by NightwindOI** [GuabinaCore/WoWKoi#981]
**Links:**

from WoWHead or our Armory

**What is happening:**

- **_The Cape of Stranglethron_**

[Rippa](https://www.wowhead.com/npc=14490/rippa) is missing.
[Kurmokk](https://www.wowhead.com/npc=14491/kurmokk) is missing.

---------------------------------------------------------------------------------------------------------------

- **_Northern Stranglethron_**

[Pogeyan](https://www.wowhead.com/npc=51663/pogeyan) is there, but the items don't scale.
[High Priestess Hai'watna](https://www.wowhead.com/npc=11383/high-priestess-haiwatna) is there, but the items don't scale.

---------------------------------------------------------------------------------------------------------------

- **_Blasted Lands_**

[Blackleaf](https://www.wowhead.com/npc=45260/blackleaf) is there, but the items don't scale.
[Cassia the Slitherqueen](https://www.wowhead.com/npc=45258/cassia-the-slitherqueen) is there, but the items don't scale.
[Akubar the Seer](https://www.wowhead.com/npc=8298/akubar-the-seer) is missing
[Spiteflayer](https://www.wowhead.com/npc=8299/spiteflayer)  is there, but the items don't scale.
[Mordak Nightbender](https://www.wowhead.com/npc=45257/mordak-nightbender) is missing.
[Grunter](https://www.wowhead.com/npc=8303/grunter) is there, but the items don't scale.
[Teremus the Devourer](https://www.wowhead.com/npc=7846/teremus-the-devourer) but at the wrong place and without any path.
[Narixxus the Doombringer](https://www.wowhead.com/npc=45262/narixxus-the-doombringer) is missing.
[Magronos the Unyielding](https://www.wowhead.com/npc=8297/magronos-the-unyielding) is there, but the items don't scale.
[Ravage](https://www.wowhead.com/npc=8300/ravage) is missing.
[Deatheye](https://www.wowhead.com/npc=8302/deatheye) is missing.
[Clack the Reaver](https://www.wowhead.com/npc=8301/clack-the-reaver) is there, but the items don't scale.
[Mojo the Twisted](https://www.wowhead.com/npc=8296/mojo-the-twisted) is there, but the items don't scale.
[Dreadscorn](https://www.wowhead.com/npc=8304/dreadscorn) is there, but the items don't scale.

---------------------------------------------------------------------------------------------------------------

- **_Swamp of Sorrows_**

[Chupacabros](https://www.wowhead.com/npc=50882/chupacabros) is missing.
[Jade](https://www.wowhead.com/npc=1063/jade) is there, but the items don't scale.
[Yukiko](https://www.wowhead.com/npc=50797/yukiko) is missing.
[Fingat](https://www.wowhead.com/npc=14446/fingat) is missing.
[Seawing](https://www.wowhead.com/npc=50886/seawing) is missing.
[Lost one Chieftain](https://www.wowhead.com/npc=763/lost-one-chieftain) is there, but the items don't scale.
[Molt Thorn](https://www.wowhead.com/npc=14448/molt-thorn) is there, but the items don't scale.
[Ionis](https://www.wowhead.com/npc=50790/ionis) is missing.
[Gib the Banana-Hoarder](https://www.wowhead.com/npc=51052/gib-the-banana-hoarder) is missing.
[Orlix the Swamplord](https://www.wowhead.com/npc=50903/orlix-the-swamplord) is missing.
[Shimmerscale](https://www.wowhead.com/npc=50738/shimmerscale) is missing.

---------------------------------------------------------------------------------------------------------------

- **_Deadwind Pass_**

Done.

---------------------------------------------------------------------------------------------------------------

- **_Duskwood_**

[Watcher Eva](https://www.wowhead.com/npc=45740/watcher-eva) is there, but the items don't scale.
[Nefaru](https://www.wowhead.com/npc=534/nefaru) is missing.
[Marus](https://www.wowhead.com/npc=45771/marus) is there, but the items don't scale.
[Carved One](https://www.wowhead.com/npc=45785/carved-one) is there, but the items don't scale.
[Eliza](https://www.wowhead.com/npc=45801/eliza) is there, but the[ ''Guard''](https://www.wowhead.com/spell=3107/summon-elizas-guard) she summ doesn't scale.
[The Unknown Soldier](https://www.wowhead.com/npc=45739/the-unknown-soldier) is there, but the items don't scale.
[Lightning Paw](https://www.wowhead.com/npc=118244/lightning-paw) is missing.
[Marina DeSirrus](https://www.wowhead.com/npc=45811/marina-desirrus) is there, but has a Male model for some reason (must be female) and the items don't scale.

---------------------------------------------------------------------------------------------------------------

- **_Westfall_**

[Vultros](https://www.wowhead.com/npc=462/vultros) is there, but there is no path(just random movement 20y range).
[ Slark](https://www.wowhead.com/npc=519/slark) is there, but the items don't scale.
[Master Digger](https://www.wowhead.com/npc=1424/master-digger) is there, but the items don't scale.
[Brack](https://www.wowhead.com/npc=520/brack) is missing.

---------------------------------------------------------------------------------------------------------------

- **_Elwynn Forest_**

[Grizzled Ben](https://www.wowhead.com/npc=50926/grizzled-ben) is missing.
[Terrapis](https://www.wowhead.com/npc=51014/terrapis) is missing.
[Snoot the Rooter](https://www.wowhead.com/npc=50942/snoot-the-rooter) is missing.
[Tarantis](https://www.wowhead.com/npc=50752/tarantis) is missing.
[Lamepaw the Whimperer](https://www.wowhead.com/npc=50916/lamepaw-the-whimperer) is missing.
[Bushtail](https://www.wowhead.com/npc=51077/bushtail) is missing.

---------------------------------------------------------------------------------------------------------------

- **_Redridge Mountains_**

[Ribchaser](https://www.wowhead.com/npc=14271/ribchaser) is there, but the items don't scale.
[Chitter](https://www.wowhead.com/npc=52146/chitter) is there, but the items don't scale.
[Seeker Aqualon](https://www.wowhead.com/npc=14269/seeker-aqualon) is there, but the items don't scale.
[Sqiddic](https://www.wowhead.com/npc=14270/squiddic) is there, but the items don't scale.
[Snarlflare](https://www.wowhead.com/npc=14272/snarlflare) is missing.
[Kazon](https://www.wowhead.com/npc=584/kazon) is there, but the items don't scale. (i  think)
[Boulderheart](https://www.wowhead.com/npc=14273/boulderheart) is there, but the items don't scale. (i think).

---------------------------------------------------------------------------------------------------------------

- **_Burning Steppes_**

[Catal](https://www.wowhead.com/npc=50807/catal) is missing.
[Volchan](https://www.wowhead.com/npc=10119/volchan) is there/kinda strange spot w/e .but he don't scale and the items too.
[Favored of Isiset](https://www.wowhead.com/npc=50810/favored-of-isiset) is missing.
[Deathmaw](https://www.wowhead.com/npc=10077/deathmaw) is there, but the items don't scale.
[Azelisk](https://www.wowhead.com/npc=50725/azelisk) is missing.
[Malfunctioning Reaver](https://www.wowhead.com/npc=8981/malfunctioning-reaver) is missing.
[Terrorspark](https://www.wowhead.com/npc=10078/terrorspark) is missing.
[Ornat](https://www.wowhead.com/npc=50361/ornat) is missing.
[Gruklash](https://www.wowhead.com/npc=8979/gruklash) is missing.
[Chiaa](https://www.wowhead.com/npc=50792/chiaa) is missing.
[Magmagan](https://www.wowhead.com/npc=50842/magmagan) is missing.
[Hematos](https://www.wowhead.com/npc=8976/hematos) is at the wrong place and the items don't scale.
[Sunwing](https://www.wowhead.com/npc=50357/sunwing) is missing.
[Venomspine](https://www.wowhead.com/npc=50730/venomspine) is missing.
[Jaxx the Rabid](https://www.wowhead.com/npc=50855/jaxx-the-rabid) is missing.
[Chromehound](https://www.wowhead.com/npc=50839/chromehound) is missing.

---------------------------------------------------------------------------------------------------------------

- **_Searing Gorge_**

[Hogzilla](https://www.wowhead.com/npc=50946/hogzilla) is missing.
[Rekk'tilac](https://www.wowhead.com/npc=8277/rekktilac) is there, but possible no loot(worth a check).
[Scald](https://www.wowhead.com/npc=8281/scald) is there, but possible no loot.
[Rexxus](https://www.wowhead.com/npc=51048/rexxus) is missing.
[Scorpoxx](https://www.wowhead.com/npc=51002/scorpoxx) is missing.
[Highlord Mastrogonde](https://www.wowhead.com/npc=8282/highlord-mastrogonde) is missing.
[Snips](https://www.wowhead.com/npc=51010/snips) is missing.
[Smoldar](https://www.wowhead.com/npc=8278/smoldar) is missing.
[Slavermaw](https://www.wowhead.com/npc=50846/slavermaw) is missing.
[Avis](https://www.wowhead.com/npc=50876/avis) is missing.
[Crystalback](https://www.wowhead.com/npc=50948/crystalback) is missing.

---------------------------------------------------------------------------------------------------------------

- **_Badlands_**

[Anathemus](https://www.wowhead.com/npc=2754/anathemus) is at the wrong spot.
[Broken Tooth](https://www.wowhead.com/npc=2850/broken-tooth) is missing.
[Barnabus](https://www.wowhead.com/npc=2753/barnabus) is there, but the items don't scale.
[Rumbler](https://classic.wowhead.com/npc=2752/rumbler) is there, but the items don't scale.
[Tabbs](https://www.wowhead.com/npc=50838/tabbs) is missing.
[Vorticus](https://www.wowhead.com/npc=51021/vorticus) is missing.
[Zormus](https://www.wowhead.com/npc=51018/zormus) is missing.
[Zaricotl](https://www.wowhead.com/npc=2931/zaricotl) is missing.
[Needlefang](https://www.wowhead.com/npc=50731/needlefang) is missing.
[Deathstrike ](https://www.wowhead.com/npc=50728/deathstrike) is missing.
[Blackshell the Impenetrable](https://www.wowhead.com/npc=51000/blackshell-the-impenetrable) is missing.
[7:XT](https://www.wowhead.com/npc=14224/7-xt) is missing
[Serkett](https://www.wowhead.com/npc=51007/serkett) is missing,

---------------------------------------------------------------------------------------------------------------

- **_Dun Morogh_**

[Weaponized Rabbot](https://www.wowhead.com/npc=107431/weaponized-rabbot) is missing.

---------------------------------------------------------------------------------------------------------------

- **_Loch Modan_**

[Shanda The Spinner](https://www.wowhead.com/npc=14266/shanda-the-spinner) is there, but the items don't scale.
[Lord Condar](https://www.wowhead.com/npc=14268/lord-condar) is there, but the items don't scale.
[Optimo](https://www.wowhead.com/npc=45399/optimo) is there, but the items don't scale.
[Ashtail](https://www.wowhead.com/npc=45380/ashtail) is there, but the items don't scale.
[Emogg the Crusher](https://www.wowhead.com/npc=14267/emogg-the-crusher) is there, but the items don't scale.
[Grizlak ](https://www.wowhead.com/npc=45398/grizlak) is there, but the items don't scale.
[Geoshape Maren](https://www.wowhead.com/npc=45404/geoshaper-maren) is there, but the items don't scale (i think).
[Sagepaw](https://www.wowhead.com/npc=45384/sagepaw) is there, but the items don't scale.
[Nix](https://www.wowhead.com/npc=45402/nix) is there, but the items don't scale.

---------------------------------------------------------------------------------------------------------------

- **_Wetlands_**

[Gazz the Loch-Hunter](https://www.wowhead.com/npc=44227/gazz-the-loch-hunter) is there, but the items don't scale.
[Mirelow](https://www.wowhead.com/npc=14424/mirelow) is there, but the items don't scale.
[Sludginn](https://www.wowhead.com/npc=14433/sludginn) is missing.
[Two-Toes](https://www.wowhead.com/npc=44224/two-toes) is there, but the items don't scale.
[Gnawbone](https://www.wowhead.com/npc=14425/gnawbone) is there, but the items don't scale.
[Chops](https://www.wowhead.com/npc=50964/chops#screenshots) is missing.

---------------------------------------------------------------------------------------------------------------

- **_Arathi Highlands_**

[Phalanax](https://www.wowhead.com/npc=51063/phalanax) is missing.
[Molok the Crusher](https://www.wowhead.com/npc=141942/molok-the-crusher) is there, but the items don't scale.
[Swee](https://www.wowhead.com/npc=50940/swee) is missing.
[Boros](https://www.wowhead.com/npc=50891/boros) is missing.
[Saurix](https://www.wowhead.com/npc=50865/saurix) is missing.
[Snuffles](https://www.wowhead.com/npc=51040/snuffles) is missing.
[Darbel Montrose](https://www.wowhead.com/npc=142688/darbel-montrose) is missing (Legi version)
[Cackle](https://www.wowhead.com/npc=50337/cackle) is missing.
[Glint](https://www.wowhead.com/npc=51067/glint#screenshots) is missing.
[Zorn](https://www.wowhead.com/npc=50770/zorn) is missing.
[Ripwing](https://www.wowhead.com/npc=50804/ripwing) is missing.

---------------------------------------------------------------------------------------------------------------

- **_The Hinterlands_**

[Zul'arek Hatefowler](https://www.wowhead.com/npc=8219/zularek-hatefowler) is there, but the items don't scale.
[Old Cliff Jumper](https://www.wowhead.com/npc=8211/old-cliff-jumper) is there, but the items don't scale.
[Witherheart the Stalker](https://www.wowhead.com/npc=8218/witherheart-the-stalker) is there, but the items don't scale.
[The Reak](https://www.wowhead.com/npc=8212/the-reak) is there, but the items don't scale.
[Grimungous](https://www.wowhead.com/npc=8215/grimungous) is there, but the items don't scale.
[Ironback](https://www.wowhead.com/npc=8213/ironback) is there, but the items don't scale.
[Ol' Muddle](https://www.wowhead.com/npc=107617/ol-muddle) is missing.

---------------------------------------------------------------------------------------------------------------

- **_Hillsbrad Foothills_**

[Lopex](https://www.wowhead.com/npc=51076/lopex) is missing.
[Narillasanz](https://www.wowhead.com/npc=2447/narillasanz) is there, but the items don't scale.
[Ro'Bark](https://www.wowhead.com/npc=14278/robark) is there, but the items don't scale.
[Lady Zephris](https://www.wowhead.com/npc=14277/lady-zephris) is there, but the items don't scale.
[Cranky Benj](https://www.wowhead.com/npc=14223/cranky-benj) is missing.
[Carcinak](https://www.wowhead.com/npc=50955/carcinak#screenshots) is missing.
[Creepthess](https://www.wowhead.com/npc=14279/creepthess) is there, but the items don't scale.
[Little Bjorn](https://www.wowhead.com/npc=50929/little-bjorn) is missing.
[Dustwing](https://www.wowhead.com/npc=50858/dustwing) is missing.
[Alitus](https://www.wowhead.com/npc=50335/alitus#screenshots) is missing.
[Miasmiss](https://www.wowhead.com/npc=50765/miasmiss) is missing. (i think)
[The Dark Prowler](https://www.wowhead.com/npc=50818/the-dark-prowler) is missing.
[Weevil](https://www.wowhead.com/npc=51057/weevil) is missing.
[Chordix](https://www.wowhead.com/npc=51022/chordix) is missing.
[Craw the Ravager](https://www.wowhead.com/npc=50967/craw-the-ravager) is missing.
[Jimmy the Bleeder](https://www.wowhead.com/npc=14281/jimmy-the-bleeder) is there, but the items don't scale.
[Indigos](https://www.wowhead.com/npc=47010/indigos) is there, but the items don't scale.
[Gravis Slipknot](https://www.wowhead.com/npc=14221/gravis-slipknot) is there, but the items don't scale.

---------------------------------------------------------------------------------------------------------------

- **_Silverpine Forest_**

[Corpsefeeder](https://www.wowhead.com/npc=50814/corpsefeeder) is missing.
[Thule Ravenclaw](https://www.wowhead.com/npc=47023/thule-ravenclaw) is missing.
[Berard the Moon-Crazed](https://www.wowhead.com/npc=46992/berard-the-moon-crazed) is there, but the items don't scale.
[Finn's Gambit](https://www.wowhead.com/npc=50949/finns-gambit) is there, but the items don't scale.
[Nightlash](https://www.wowhead.com/npc=46981/nightlash) is there, but the items don't scale.
[Bolgaff](https://www.wowhead.com/npc=47003/bolgaff) is there, but the items don't scale.
[Lost son of arugal](https://www.wowhead.com/npc=47015/lost-son-of-arugal) is missing.
[Gorefang](https://www.wowhead.com/npc=12431/gorefang) is there, but the items don't scale.
[Lost Gilnean Wardog](https://www.wowhead.com/npc=51037/lost-gilnean-wardog) is there, but the items don't scale.
[Kree](https://www.wowhead.com/npc=50330/kree) is missing.

---------------------------------------------------------------------------------------------------------------

- **_Tirisfal Glades_**

[Shadowstalker](https://www.wowhead.com/npc=50763/shadowstalker) is there, but don't scale (must scale to 22).
[Bonechewer](https://www.wowhead.com/npc=50803/bonechewer) is there, but don't scale. (must scale to 62 according to Wowhead)
[Nighthowl](https://www.wowhead.com/npc=50908/nighthowl) is there, but don't scale (must scale to 15 according to Wowhead).
[Plague](https://www.wowhead.com/npc=51044/plague) is there, but don't scale (14lv max according to Wowhead)

---------------------------------------------------------------------------------------------------------------

- **_Western Plagueland_**

[Heress](https://www.wowhead.com/npc=50809/heress) is missing.
[Alit](https://www.wowhead.com/npc=50345/alit) is missing.
[Foulmane](https://www.wowhead.com/npc=1847/foulmane) is there, but the items don't scale.
[The Husk](https://www.wowhead.com/npc=1851/the-husk) is at the wrong place.
[Parasitus](https://www.wowhead.com/npc=51029/parasitus) is missing.
[Ironweb](https://www.wowhead.com/npc=50778/ironweb) is there, but don't scale/maybe the items too.
[Warg](https://www.wowhead.com/npc=50922/warg) is missing.
[Dreadwhisper](https://www.wowhead.com/npc=1849/dreadwhisper) is there, but the items don't scale.
[Mange](https://www.wowhead.com/npc=50931/mange) is missing.
[Hamhide](https://www.wowhead.com/npc=50937/hamhide) is missing.
[Mutilax](https://www.wowhead.com/npc=50906/mutilax) is missing.
[Aphis](https://www.wowhead.com/npc=51058/aphis) is missing.

---------------------------------------------------------------------------------------------------------------

- **_Eastern Plaguelands_**

[Likk the Hunter](https://www.wowhead.com/npc=50775/likk-the-hunter) is missing.
[Deathspeaker Selendre](https://www.wowhead.com/npc=10827/deathspeaker-selendre) is missing.
[Quirix](https://www.wowhead.com/npc=51053/quirix) is missing.
[Gish the Unmoving](https://www.wowhead.com/npc=10825/gish-the-unmoving) is at the wrong place.
[Snark](https://www.wowhead.com/npc=50856/snark) is missing.
[Sporeggon](https://www.wowhead.com/npc=50779/sporeggon) is missing.
[Varah](https://www.wowhead.com/npc=50947/varah) is missing.
[Bleakheart](https://www.wowhead.com/npc=51042/bleakheart) is missing.
[Spirocula](https://www.wowhead.com/npc=51027/spirocula) is missing.
[Lynnia Abbendis](https://www.wowhead.com/npc=10828/lynnia-abbendis) is missing.
[Snort](https://www.wowhead.com/npc=50915/snort) is missing.
[Fene-mal](https://www.wowhead.com/npc=50813/fene-mal) is missing.
[Zyk'brin Warpbranch](https://www.wowhead.com/npc=10823/zulbrin-warpbranch) is missing.

---------------------------------------------------------------------------------------------------------------

- **_Ghostlands_**

 Done

---------------------------------------------------------------------------------------------------------------

If some rare is ''there'' when u port to him but I mark it as ''missing'' that's cuz wrong spawn point compare to Wowhead and NPC_Scanner.

_Eastern Kingdoms DONE_

---------------------------------------------------------------------------------------------------------------

 _****The king sends his regards****_

**Comment by Cefiro-Caecias** [comment]
The Cape of Stranglethorn: Those Rares if found in the area. Rippa has 3 random spawn points, and Kurmokk has two.

**Comment by Cefiro-Caecias** [comment]
Northern Stranglethron: scaling fixed days ago. Don't forget to delete the Cache folder from your WoW.

**Comment by Cefiro-Caecias** [comment]
Blasted Lands: All are found, scaled, and have multiple random spawn points.

**Comment by NightwindOI** [comment]
Hm, compare to  npc_scanner and Wowhead they are at wrong spots. So even if they are spawned, ppl still gonna report/think they are missing (as I do when trying to find them). Maybe re-position the spawn or something? Not sure.

**Comment by Cefiro-Caecias** [comment]
Swamp of Sorrows: Completed. Available in the next update.
Jade, Fingat, Lost One Chieftain and Molt Thorn are in the area.

**Comment by Cefiro-Caecias** [comment]
Duskwood:

-All the Rares were already scaled.
-Nefaru is found.
-Eliza's Guard, fixed.
-Lightning Paw is found, I put it a couple of weeks ago at the request of another player. It has 30 random spawn points.
-Marina DeSirrus, fixed.
-Available in the next update.

**Comment by Cefiro-Caecias** [comment]
No bug present: Cranky Benj is found.

**Comment by Cefiro-Caecias** [comment]
Elwynn Forest: fixed. Available in the next update.

**Comment by Cefiro-Caecias** [comment]
Redridge Mountains:

-All rares are present, and are scaled.
-Chitter did not possess combat SmartAI. Fixed. Available in the next update.

**Comment by Cefiro-Caecias** [comment]
Burning Steppes:

-Volchan: have 2 random spawn points. Rescaled.
-Malfunctioning Reaver: yes is present; It has 3 random spawn points.
-Terrorspark: yes it is present; It has 5 random spawn points.
-Gruklash: yes it is present; It has 2 random spawn points.
-Hematos: have 2 random spawn points.
-The rest, fixed. Available in the next update.

**Comment by Cefiro-Caecias** [comment]
Searing Gorge, fixed.

**Comment by Cefiro-Caecias** [comment]
Badlands:

-Anathemus: Have 2 random spawn points.
-Broken Tooth: Have 4 random spawn points.
-Barnabus: have 5 random spawn points.
-Rumbler: yes it is in the area.
-Zaricotl: have 4 random spawn points.
-7: XT: It has 7 random spawn points (only the escalation was missing).
-The rest, fixed. Available in the next update.

**Comment by Cefiro-Caecias** [comment]
Dun Morogh, fixed. Available in the next update.

**Comment by Cefiro-Caecias** [comment]
Loch Modan: Mobs escalated long ago.

**Comment by Cefiro-Caecias** [comment]
Wetlands: Only Chops was missing. The rest are in the area and scaled.

**Comment by Cefiro-Caecias** [comment]
Arathi Highlands:

-Darbel Montrose (https://www.wowhead.com/npc=2598) is found. Its second version (https://www.wowhead.com/npc=142688) is not from Legion, but from BfA.
-Molok the Crusher: escalated long ago.
-The rest, fixed. Available in the next update.

**Comment by Cefiro-Caecias** [comment]
The Hinterlands: All mobs were scaled. Only Ol 'Muddle was missing. Fixed. Available in the next update.

**Comment by Cefiro-Caecias** [comment]
Hillsbrad Foothills: fixed. Available in the next update.

**Comment by Cefiro-Caecias** [comment]
Silverpine Forest: All mobs are found and scaled, except for Corpsefeeder and Kree. Fixed. Available in the next update.

**Comment by Cefiro-Caecias** [comment]
Tirisfal Glades: fixed (mobs were also missing the loot). Available in the next update.

**Comment by Cefiro-Caecias** [comment]
Western Plaguelands: fixed. Available in the next update.

**Comment by Cefiro-Caecias** [comment]
Eastern Plaguelands:

-Deathspeaker Selendre: If found, it has 2 random spawn points.
-Gish the Unmoving: has 2 random spawn points.
-Lynnia Abbendis: yes it is.
-Zul'Brin Warpbranch: yes found.
-The rest, fixed. Available in the next update.

PD 1: the Burning Crusade and Northrend Rares are already in place and supervised.

PD 2: Until Cataclysm I hope not to see another post of rare, or I swear that I commit suicide.

PD 3: the alphabet and the decimal metric system do not reach me to express how much I hate you. My suffering bears your name XD

**Comment by NightwindOI** [comment]
To serve you in whatever you need
PS: The next big report is on the way.
PS2: You may think TBC rare's are in place, but ill prove u wrong 🗡️
