### ISSUE TITLE
[Quest] Wetter Than Wet

### ISSUE THREAD

**Issue by JadedNate** [GuabinaCore/WoWKoi#982]
https://www.wowhead.com/quest=14264/wetter-than-wet

**What is happening:**
The quest item Slitherblade Charm's ability is cancelled whenever the player uses an ability, and cannot kill the required NPCs to finish the quest.

**What should happen:**
The player should be able to use the Slitherblade Charm to kill 5 Servants of Neptulon.

**Comment by Cefiro-Caecias** [comment]
The Desolace map is still under repair, at 50%. Patience.
