### ISSUE TITLE
[Core] - Monk: Chi Wave overhealing Enemy NPC

### ISSUE THREAD

**Issue by ghost** [GuabinaCore/WoWKoi#99]
Links:
https://www.wowhead.com/spell=115098/chi-wave

What is happening:
Monk lvl 15 talent Chi Wave overheals enemy NPC.

What should happen:
It should not heal enemy target.

**Comment by Whizh** [comment]
Just testing this out and i need to add the chi wave does some weird stuff over heals you a lot (it says in the tooltip 59 healing and it does over 300 at lvl 16) and also heals the enemy plus can't get out of combat afterwards even when the enemy is dead

**Comment by Thordekk** [comment]
Rewrited spell https://www.wowhead.com/spell=115098/chi-wave you can test when server release
