### ISSUE TITLE
Thousand Needles quest chain bug

### ISSUE THREAD

**Issue by GhostySimon** [GuabinaCore/WoWKoi#991]
**Links:**

https://www.wowhead.com/quest=28504/warchiefs-command-thousand-needles

**What is happening:**

After completion of "Warchief's Command: Thousand Needles!", NPC Nysa doesn't give next quest in the chain "To the Summit"

**What should happen:**

Next chain quest should be available.

**Comment by LKArthas** [comment]
Fixed avaible on next update
