### ISSUE TITLE
[NPC] Plagued Swine

### ISSUE THREAD

**Issue by TheFlash3113** [GuabinaCore/WoWKoi#992]
**Links:**

https://classic.wowhead.com/npc=16117/plagued-swine

**What is happening:**

[Plagued Swine](https://classic.wowhead.com/npc=16117/plagued-swine) is a neutral mob with hostile tooltip, unitframe and nameplate.

**What should happen:**

It should have a neutral tooltip, unitframe and nameplate.

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.
